__d(
  "AdAccountProductCatalogSpecResolver.graphql",
  [],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = (function () {
      var e = [
          {
            defaultValue: !1,
            kind: "LocalArgument",
            name: "include_product_count_issues",
          },
          {
            defaultValue: !1,
            kind: "LocalArgument",
            name: "is_additional_cms_fields_enabled",
          },
          {
            defaultValue: !1,
            kind: "LocalArgument",
            name: "is_optimisation_enabled",
          },
          {
            defaultValue: null,
            kind: "LocalArgument",
            name: "legacy_account_id",
          },
          {
            defaultValue: !1,
            kind: "LocalArgument",
            name: "skip_unused_catalog_fields",
          },
          { defaultValue: !1, kind: "LocalArgument", name: "skip_user_tasks" },
        ],
        t = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "id",
          storageKey: null,
        },
        n = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "name",
          storageKey: null,
        },
        r = [t, n],
        o = {
          alias: null,
          args: null,
          concreteType: "AdBusiness",
          kind: "LinkedField",
          name: "business",
          plural: !1,
          selections: r,
          storageKey: null,
        },
        a = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "state",
          storageKey: null,
        },
        i = [
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "count",
            storageKey: null,
          },
        ],
        l = [t],
        s = [
          {
            kind: "Variable",
            name: "ad_account_id",
            variableName: "legacy_account_id",
          },
        ];
      return {
        argumentDefinitions: e,
        kind: "Fragment",
        metadata: null,
        name: "AdAccountProductCatalogSpecResolver",
        selections: [
          {
            kind: "InlineDataFragmentSpread",
            name: "AdAccountDpaEligibleProductCatalogListUtil_productCatalogSpec",
            selections: [
              o,
              {
                alias: null,
                args: null,
                concreteType: "CatalogCapabilityWithState",
                kind: "LinkedField",
                name: "capabilities_with_state",
                plural: !0,
                selections: [
                  {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "capability",
                    storageKey: null,
                  },
                  a,
                ],
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "capability_features",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "catalog_segment_type",
                storageKey: null,
              },
              {
                condition: "skip_unused_catalog_fields",
                kind: "Condition",
                passingValue: !1,
                selections: [
                  {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "catalog_segment_filter",
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: null,
                    concreteType: "ProductCatalogFeedsConnection",
                    kind: "LinkedField",
                    name: "feeds",
                    plural: !1,
                    selections: i,
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "has_connected_event_sources",
                    storageKey: null,
                  },
                ],
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "catalog_segment_use_cases",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                concreteType: "CommerceMerchantSettings",
                kind: "LinkedField",
                name: "commerce_merchant_settings",
                plural: !1,
                selections: [
                  t,
                  {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "merchant_status",
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: null,
                    concreteType: "Page",
                    kind: "LinkedField",
                    name: "merchant_page",
                    plural: !1,
                    selections: r,
                    storageKey: null,
                  },
                  {
                    condition: "skip_unused_catalog_fields",
                    kind: "Condition",
                    passingValue: !1,
                    selections: [
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "payment_provider",
                        storageKey: null,
                      },
                    ],
                  },
                  {
                    alias: null,
                    args: null,
                    concreteType: "Application",
                    kind: "LinkedField",
                    name: "application",
                    plural: !1,
                    selections: l,
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "shop_ads_capabilities",
                    storageKey: null,
                  },
                  {
                    condition: "is_additional_cms_fields_enabled",
                    kind: "Condition",
                    passingValue: !0,
                    selections: [
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "onsite_checkout_enabled_countries",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "onsite_checkout_enabled_for_shops_ads_supported_countries",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "offsite_iab_checkout_enabled_countries",
                        storageKey: null,
                      },
                    ],
                  },
                ],
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "da_pe_spend_28d",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "da_spend_28d",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "last_used_in_ad",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "original_creation_source",
                storageKey: null,
              },
              n,
              {
                alias: null,
                args: s,
                kind: "ScalarField",
                name: "has_issues_for_da",
                storageKey: null,
              },
              {
                condition: "include_product_count_issues",
                kind: "Condition",
                passingValue: !0,
                selections: [
                  {
                    alias: null,
                    args: s,
                    concreteType: "XFBCatalogSetupIssue",
                    kind: "LinkedField",
                    name: "catalog_issues_for_da",
                    plural: !0,
                    selections: [
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "type",
                        storageKey: null,
                      },
                    ],
                    storageKey: null,
                  },
                ],
              },
              {
                alias: null,
                args: s,
                kind: "ScalarField",
                name: "cpas_ad_account_relationship",
                storageKey: null,
              },
              {
                alias: null,
                args: s,
                kind: "ScalarField",
                name: "catalog_to_ad_account_relationship",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                concreteType: "Page",
                kind: "LinkedField",
                name: "page",
                plural: !1,
                selections: [
                  t,
                  n,
                  {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "link",
                    storageKey: null,
                  },
                ],
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "suggested_conversion_event",
                storageKey: null,
              },
              {
                condition: "is_optimisation_enabled",
                kind: "Condition",
                passingValue: !1,
                selections: [
                  {
                    alias: null,
                    args: null,
                    concreteType:
                      "ProductCatalogConnectedExternalEventSourcesConnection",
                    kind: "LinkedField",
                    name: "connected_external_event_sources",
                    plural: !1,
                    selections: i,
                    storageKey: null,
                  },
                ],
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "source_app_id",
                storageKey: null,
              },
              t,
              {
                alias: null,
                args: null,
                concreteType: "CatalogWebsiteOnboardingSettings",
                kind: "LinkedField",
                name: "website_onboarding_settings",
                plural: !1,
                selections: [
                  a,
                  {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "quality_band",
                    storageKey: null,
                  },
                ],
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                concreteType: "ProductCatalog",
                kind: "LinkedField",
                name: "parent_catalog",
                plural: !1,
                selections: l,
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                concreteType: "XFBStoreCatalogSettings",
                kind: "LinkedField",
                name: "store_catalog_settings",
                plural: !1,
                selections: [
                  t,
                  {
                    alias: null,
                    args: null,
                    concreteType: "Page",
                    kind: "LinkedField",
                    name: "page",
                    plural: !1,
                    selections: r,
                    storageKey: null,
                  },
                ],
                storageKey: null,
              },
              {
                condition: "skip_user_tasks",
                kind: "Condition",
                passingValue: !1,
                selections: [
                  {
                    alias: null,
                    args: null,
                    concreteType: "XFBUserTasks",
                    kind: "LinkedField",
                    name: "user_tasks",
                    plural: !1,
                    selections: [
                      {
                        alias: null,
                        args: null,
                        concreteType: "XFBUserTask",
                        kind: "LinkedField",
                        name: "data",
                        plural: !0,
                        selections: [
                          o,
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "tasks",
                            storageKey: null,
                          },
                        ],
                        storageKey: null,
                      },
                    ],
                    storageKey: null,
                  },
                ],
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "vertical",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "catalog_item_type",
                storageKey: null,
              },
            ],
            args: [
              {
                kind: "Variable",
                name: "include_product_count_issues",
                variableName: "include_product_count_issues",
              },
              {
                kind: "Variable",
                name: "is_additional_cms_fields_enabled",
                variableName: "is_additional_cms_fields_enabled",
              },
              {
                kind: "Variable",
                name: "is_optimisation_enabled",
                variableName: "is_optimisation_enabled",
              },
              {
                kind: "Variable",
                name: "legacy_account_id",
                variableName: "legacy_account_id",
              },
              {
                kind: "Variable",
                name: "skip_unused_catalog_fields",
                variableName: "skip_unused_catalog_fields",
              },
              {
                kind: "Variable",
                name: "skip_user_tasks",
                variableName: "skip_user_tasks",
              },
            ],
            argumentDefinitions: e,
          },
        ],
        type: "ProductCatalog",
        abstractKey: null,
      };
    })();
    a.exports = e;
  },
  null,
);
