__d(
  "AdCampaignDynamicAdObjectSpecTier3Resolver.graphql",
  ["AdDeliveryInfo-ad_delivery_info_spec-resolver"],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = (function () {
      var e = [
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "p25",
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "p50",
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "p75",
            storageKey: null,
          },
        ],
        t = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "value",
          storageKey: null,
        },
        r = [
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "end",
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "start",
            storageKey: null,
          },
          t,
        ];
      return {
        argumentDefinitions: [],
        kind: "Fragment",
        metadata: null,
        name: "AdCampaignDynamicAdObjectSpecTier3Resolver",
        selections: [
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "__typename",
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            concreteType: "XFBAnomalyInsightsType",
            kind: "LinkedField",
            name: "anomaly_insights",
            plural: !1,
            selections: [
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "cpc",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "cplc",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "cpm",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "cpr",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "ctr",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "cvr",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "website_purchase_roas",
                storageKey: null,
              },
            ],
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "cpr_benchmark",
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "creative_diversity_label",
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "creative_diversity_score",
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            concreteType: "XFBCreativeFatiguePredictionPLEType",
            kind: "LinkedField",
            name: "creative_fatigue_prediction_ple",
            plural: !1,
            selections: [
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "cpr_lift_estimation",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "should_display",
                storageKey: null,
              },
            ],
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            concreteType: "XFBPpsPeerBenchmarksType",
            kind: "LinkedField",
            name: "pps_peer_benchmarks",
            plural: !1,
            selections: [
              {
                alias: null,
                args: null,
                concreteType: "XFBPpsPeerBenchmarkQuartilesType",
                kind: "LinkedField",
                name: "ctr",
                plural: !1,
                selections: e,
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                concreteType: "XFBPpsPeerBenchmarkQuartilesType",
                kind: "LinkedField",
                name: "cpm",
                plural: !1,
                selections: e,
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                concreteType: "XFBPpsPeerBenchmarkQuartilesType",
                kind: "LinkedField",
                name: "cpc",
                plural: !1,
                selections: e,
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                concreteType: "XFBPpsPeerBenchmarkQuartilesType",
                kind: "LinkedField",
                name: "cvr",
                plural: !1,
                selections: e,
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                concreteType: "XFBPpsPeerBenchmarkQuartilesType",
                kind: "LinkedField",
                name: "cplc",
                plural: !1,
                selections: e,
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                concreteType: "XFBPpsPeerBenchmarkQuartilesType",
                kind: "LinkedField",
                name: "website_purchase_roas",
                plural: !1,
                selections: e,
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                concreteType: "XFBPpsPeerBenchmarkQuartilesType",
                kind: "LinkedField",
                name: "cpr",
                plural: !1,
                selections: e,
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                concreteType: "XFBPpsPeerBenchmarkFilterParamType",
                kind: "LinkedField",
                name: "filter_params",
                plural: !0,
                selections: [
                  {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "key",
                    storageKey: null,
                  },
                  t,
                ],
                storageKey: null,
              },
            ],
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            concreteType: "XFBRepeatReachStateType",
            kind: "LinkedField",
            name: "repeat_reach_state",
            plural: !1,
            selections: [
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "current_saturation_level",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "forecasted_saturation_level",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "high_saturation_threshold",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "should_display_cpr",
                storageKey: null,
              },
            ],
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            concreteType: "AppliedInsightsCreativeInsightsReachTrend",
            kind: "LinkedField",
            name: "low_creative_reach",
            plural: !1,
            selections: [
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "reach_trend",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                concreteType: "AppliedInsightsReachTrend",
                kind: "LinkedField",
                name: "current_reach",
                plural: !1,
                selections: r,
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                concreteType: "AppliedInsightsReachTrend",
                kind: "LinkedField",
                name: "earlier_reach",
                plural: !1,
                selections: r,
                storageKey: null,
              },
            ],
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            concreteType: "AdDeliveryInfo",
            kind: "LinkedField",
            name: "delivery_info",
            plural: !1,
            selections: [
              {
                alias: null,
                args: null,
                fragment: {
                  args: null,
                  kind: "FragmentSpread",
                  name: "AdDeliveryInfoAdDeliveryInfoSpecResolver",
                },
                kind: "RelayResolver",
                name: "ad_delivery_info_spec",
                resolverModule: n(
                  "AdDeliveryInfo-ad_delivery_info_spec-resolver",
                ).ad_delivery_info_spec,
                path: "delivery_info.ad_delivery_info_spec",
              },
            ],
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "effective_status",
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "id",
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "is_bid_constrained",
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "is_cost_constrained",
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            concreteType: "AdDeliveryInsightsLearningStageNode",
            kind: "LinkedField",
            name: "learning_stage_info",
            plural: !1,
            selections: [
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "conversions",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "exit_reason",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "last_significant_edit_timestamp",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "status",
                storageKey: null,
              },
            ],
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            concreteType: "AdsDeliveryPacedBidInfo",
            kind: "LinkedField",
            name: "paced_bid_info",
            plural: !1,
            selections: [
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "bidding_status",
                storageKey: null,
              },
            ],
            storageKey: null,
          },
        ],
        type: "AdCampaign",
        abstractKey: null,
      };
    })();
    a.exports = e;
  },
  null,
);
