__d(
  "AdCreativeDestinationGuidancesApplied",
  [],
  function (t, n, r, o, a, i) {
    var e = Object.freeze({
      SHOP_ADS_INLINE_PFR_RECOMMENDATION: "SHOP_ADS_INLINE_PFR_RECOMMENDATION",
      SHOP_ADS_PFR_HUB_RECOMMENDATION: "SHOP_ADS_PFR_HUB_RECOMMENDATION",
      SHOPS_ADS_DUPLICATION_UPGRADE_RECOMMENDATION:
        "SHOPS_ADS_DUPLICATION_UPGRADE_RECOMMENDATION",
      SHOPS_ADS_INLINE_PFR_RECOMMENDATION:
        "SHOPS_ADS_INLINE_PFR_RECOMMENDATION",
      SHOPS_ADS_MFR_RECOMMENDATION: "SHOPS_ADS_MFR_RECOMMENDATION",
      SHOPS_ADS_PFR_HUB_RECOMMENDATION: "SHOPS_ADS_PFR_HUB_RECOMMENDATION",
    });
    i.default = e;
  },
  66,
);
