__d(
  "AdCreativeMediaType",
  [],
  function (t, n, r, o, a, i) {
    var e = Object.freeze({
      AUTOMATIC: "AUTOMATIC",
      CAROUSEL: "CAROUSEL",
      CAROUSEL_IMAGE: "CAROUSEL_IMAGE",
      COLLECTIONS_IMAGE: "COLLECTIONS_IMAGE",
      COLLECTIONS_VIDEO: "COLLECTIONS_VIDEO",
      EXISTING_INSTAGRAM_POST: "EXISTING_INSTAGRAM_POST",
      EXISTING_POST: "EXISTING_POST",
      INSTAGRAM_LIVE_VIDEO: "INSTAGRAM_LIVE_VIDEO",
      POST: "POST",
      SCHEDULED_LIVE_VIDEO: "SCHEDULED_LIVE_VIDEO",
      SINGLE_IMAGE: "SINGLE_IMAGE",
      SINGLE_LINK: "SINGLE_LINK",
      SINGLE_PHOTO: "SINGLE_PHOTO",
      SINGLE_VIDEO: "SINGLE_VIDEO",
    });
    i.default = e;
  },
  66,
);
