__d(
  "AdCreativeObjectStorySpecificationResolver.graphql",
  [
    "AdCallToActionSpecification-call_to_action_spec-resolver",
    "AdObjectStoryChildLinkDataSpecification-child_attachment_spec-resolver",
    "AdImageCropsPerDimensionSpec-ad_object_spec-resolver",
    "XFBApiAdCreativeCustomOverlayImageSpec-custom_overlay_specification-resolver",
    "AdCustomizationRuleSpecification-customization_rules_specification-resolver",
    "AdImageCropsPerDimensionSpec-ad_object_spec-resolver",
    "AdCreativePostClickConfigurationSpecification-ad_object_spec-resolver",
    "AdCallToActionSpecification-call_to_action_spec-resolver",
    "AdCallToActionSpecification-call_to_action_spec-resolver",
    "AdObjectStoryChildLinkDataSpecification-child_attachment_spec-resolver",
    "AdImageCropsPerDimensionSpec-ad_object_spec-resolver",
    "XFBApiAdCreativeCustomOverlayImageSpec-custom_overlay_specification-resolver",
    "AdCustomizationRuleSpecification-customization_rules_specification-resolver",
    "AdImageCropsPerDimensionSpec-ad_object_spec-resolver",
    "AdCreativePostClickConfigurationSpecification-ad_object_spec-resolver",
    "AdCallToActionSpecification-call_to_action_spec-resolver",
    "AdCallToActionSpecification-call_to_action_spec-resolver",
    "AdImageCropsPerDimensionSpec-ad_object_spec-resolver",
    "AdCustomizationRuleSpecification-customization_rules_specification-resolver",
    "AdCreativePostClickConfigurationSpecification-ad_object_spec-resolver",
  ],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = (function () {
      var e = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "additional_image_index",
          storageKey: null,
        },
        t = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "attachment_style",
          storageKey: null,
        },
        r = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "branded_content_sponsor_page_id",
          storageKey: null,
        },
        o = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "branded_content_sponsor_relationship",
          storageKey: null,
        },
        a = {
          args: null,
          kind: "FragmentSpread",
          name: "AdCallToActionSpecificationCallToActionSpecResolver",
        },
        i = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "caption",
          storageKey: null,
        },
        l = {
          args: null,
          kind: "FragmentSpread",
          name: "AdObjectStoryChildLinkDataSpecificationChildAttachmentSpecResolver",
        },
        s = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "element_child_index",
          storageKey: null,
        },
        u = {
          args: null,
          kind: "FragmentSpread",
          name: "AdImageCropsPerDimensionSpecAdObjectSpecResolver",
        },
        c = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "element_id",
          storageKey: null,
        },
        d = {
          args: null,
          kind: "FragmentSpread",
          name: "XFBApiAdCreativeCustomOverlayImageSpecCustomOverlaySpecificationResolver",
        },
        m = {
          args: null,
          kind: "FragmentSpread",
          name: "AdCustomizationRuleSpecificationCustomizationRulesSpecificationResolver",
        },
        p = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "description",
          storageKey: null,
        },
        _ = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "event_id",
          storageKey: null,
        },
        f = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "image_hash",
          storageKey: null,
        },
        g = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "link",
          storageKey: null,
        },
        h = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "message",
          storageKey: null,
        },
        y = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "multi_share_end_card",
          storageKey: null,
        },
        C = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "multi_share_optimized",
          storageKey: null,
        },
        b = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "name",
          storageKey: null,
        },
        v = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "offer_id",
          storageKey: null,
        },
        S = {
          alias: "page_welcome_message",
          args: null,
          kind: "ScalarField",
          name: "page_welcome_message_string",
          storageKey: null,
        },
        R = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "phone_data_id",
          storageKey: null,
        },
        L = {
          args: null,
          kind: "FragmentSpread",
          name: "AdCreativePostClickConfigurationSpecificationAdObjectSpecResolver",
        },
        E = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "product_discount_id",
          storageKey: null,
        },
        k = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "branded_content_shared_to_sponsor_status",
          storageKey: null,
        },
        I = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "page_welcome_message",
          storageKey: null,
        },
        T = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "text_color",
          storageKey: null,
        },
        D = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "text_font",
          storageKey: null,
        },
        x = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "float_with_margin",
          storageKey: null,
        },
        $ = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "position",
          storageKey: null,
        },
        P = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "retailer_item_ids",
          storageKey: null,
        };
      return {
        argumentDefinitions: [],
        kind: "Fragment",
        metadata: { vultureHash: "jZOWvY9OxQirhu9NADlzP444S9g=" },
        name: "AdCreativeObjectStorySpecificationResolver",
        selections: [
          {
            alias: "object_story_spec",
            args: null,
            concreteType: "AdObjectStorySpecification",
            kind: "LinkedField",
            name: "ad_creative_object_story_spec",
            plural: !1,
            selections: [
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "instagram_actor_id",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                concreteType: "AdObjectStoryLinkDataSpecification",
                kind: "LinkedField",
                name: "link_data",
                plural: !1,
                selections: [
                  e,
                  t,
                  r,
                  o,
                  {
                    alias: null,
                    args: null,
                    concreteType: "AdCallToActionSpecification",
                    kind: "LinkedField",
                    name: "call_to_action",
                    plural: !1,
                    selections: [
                      {
                        alias: null,
                        args: null,
                        fragment: a,
                        kind: "RelayResolver",
                        name: "call_to_action_spec",
                        resolverModule: n(
                          "AdCallToActionSpecification-call_to_action_spec-resolver",
                        ).call_to_action_spec,
                        path: "object_story_spec.link_data.call_to_action.call_to_action_spec",
                      },
                    ],
                    storageKey: null,
                  },
                  i,
                  {
                    alias: "child_attachments",
                    args: null,
                    concreteType: "AdObjectStoryChildLinkDataSpecification",
                    kind: "LinkedField",
                    name: "child_attachments_spec",
                    plural: !0,
                    selections: [
                      {
                        alias: null,
                        args: null,
                        fragment: l,
                        kind: "RelayResolver",
                        name: "child_attachment_spec",
                        resolverModule: n(
                          "AdObjectStoryChildLinkDataSpecification-child_attachment_spec-resolver",
                        ).child_attachment_spec,
                        path: "object_story_spec.link_data.child_attachments.child_attachment_spec",
                      },
                    ],
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: null,
                    concreteType: "AdCreativeThumbnailInfo",
                    kind: "LinkedField",
                    name: "collection_thumbnails",
                    plural: !0,
                    selections: [
                      s,
                      {
                        alias: null,
                        args: null,
                        concreteType: "AdImageCropsPerDimensionSpec",
                        kind: "LinkedField",
                        name: "element_crops",
                        plural: !1,
                        selections: [
                          {
                            alias: null,
                            args: null,
                            fragment: u,
                            kind: "RelayResolver",
                            name: "ad_image_crops_per_dimension_spec",
                            resolverModule: n(
                              "AdImageCropsPerDimensionSpec-ad_object_spec-resolver",
                            ).ad_image_crops_per_dimension_spec,
                            path: "object_story_spec.link_data.collection_thumbnails.element_crops.ad_image_crops_per_dimension_spec",
                          },
                        ],
                        storageKey: null,
                      },
                      c,
                    ],
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: null,
                    concreteType: "XFBApiAdCreativeCustomOverlayImageSpec",
                    kind: "LinkedField",
                    name: "custom_overlay_spec",
                    plural: !1,
                    selections: [
                      {
                        alias: null,
                        args: null,
                        fragment: d,
                        kind: "RelayResolver",
                        name: "custom_overlay_specification",
                        resolverModule: n(
                          "XFBApiAdCreativeCustomOverlayImageSpec-custom_overlay_specification-resolver",
                        ).custom_overlay_specification,
                        path: "object_story_spec.link_data.custom_overlay_spec.custom_overlay_specification",
                      },
                    ],
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: null,
                    concreteType: "AdCustomizationRuleSpecification",
                    kind: "LinkedField",
                    name: "customization_rules_spec",
                    plural: !0,
                    selections: [
                      {
                        alias: null,
                        args: null,
                        fragment: m,
                        kind: "RelayResolver",
                        name: "customization_rules_specification",
                        resolverModule: n(
                          "AdCustomizationRuleSpecification-customization_rules_specification-resolver",
                        ).customization_rules_specification,
                        path: "object_story_spec.link_data.customization_rules_spec.customization_rules_specification",
                      },
                    ],
                    storageKey: null,
                  },
                  p,
                  _,
                  {
                    alias: null,
                    args: null,
                    concreteType: "AdImageCropsPerDimensionSpec",
                    kind: "LinkedField",
                    name: "image_crops_per_dimension",
                    plural: !1,
                    selections: [
                      {
                        alias: null,
                        args: null,
                        fragment: u,
                        kind: "RelayResolver",
                        name: "ad_image_crops_per_dimension_spec",
                        resolverModule: n(
                          "AdImageCropsPerDimensionSpec-ad_object_spec-resolver",
                        ).ad_image_crops_per_dimension_spec,
                        path: "object_story_spec.link_data.image_crops_per_dimension.ad_image_crops_per_dimension_spec",
                      },
                    ],
                    storageKey: null,
                  },
                  f,
                  g,
                  h,
                  y,
                  C,
                  b,
                  v,
                  S,
                  R,
                  {
                    alias: "picture",
                    args: null,
                    kind: "ScalarField",
                    name: "picture_string",
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: null,
                    concreteType:
                      "AdCreativePostClickConfigurationSpecification",
                    kind: "LinkedField",
                    name: "post_click_configuration",
                    plural: !1,
                    selections: [
                      {
                        alias: null,
                        args: null,
                        fragment: L,
                        kind: "RelayResolver",
                        name: "post_click_configuration_specification",
                        resolverModule: n(
                          "AdCreativePostClickConfigurationSpecification-ad_object_spec-resolver",
                        ).post_click_configuration_specification,
                        path: "object_story_spec.link_data.post_click_configuration.post_click_configuration_specification",
                      },
                    ],
                    storageKey: null,
                  },
                  E,
                  {
                    alias: "retailer_item_ids",
                    args: null,
                    kind: "ScalarField",
                    name: "retailer_item_string_ids",
                    storageKey: null,
                  },
                ],
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                concreteType: "NodeWrapper",
                kind: "LinkedField",
                name: "page",
                plural: !1,
                selections: [
                  {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "node_id",
                    storageKey: null,
                  },
                ],
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                concreteType: "AdObjectStoryPhotoDataSpecification",
                kind: "LinkedField",
                name: "photo_data",
                plural: !1,
                selections: [
                  k,
                  r,
                  o,
                  {
                    alias: null,
                    args: null,
                    concreteType: "AdCallToActionSpecification",
                    kind: "LinkedField",
                    name: "call_to_action",
                    plural: !1,
                    selections: [
                      {
                        alias: null,
                        args: null,
                        fragment: a,
                        kind: "RelayResolver",
                        name: "call_to_action_spec",
                        resolverModule: n(
                          "AdCallToActionSpecification-call_to_action_spec-resolver",
                        ).call_to_action_spec,
                        path: "object_story_spec.photo_data.call_to_action.call_to_action_spec",
                      },
                    ],
                    storageKey: null,
                  },
                  i,
                  f,
                  I,
                  {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "url",
                    storageKey: null,
                  },
                ],
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                concreteType: "AdObjectStoryTemplateDataSpecification",
                kind: "LinkedField",
                name: "template_data",
                plural: !1,
                selections: [
                  {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "ad_context",
                    storageKey: null,
                  },
                  e,
                  t,
                  {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "automated_product_tags",
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "is_local_expansion",
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "smart_pse_enabled",
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "boosted_product_set_id",
                    storageKey: null,
                  },
                  k,
                  r,
                  o,
                  {
                    alias: null,
                    args: null,
                    concreteType: "AdCallToActionSpecification",
                    kind: "LinkedField",
                    name: "call_to_action",
                    plural: !1,
                    selections: [
                      {
                        alias: null,
                        args: null,
                        fragment: a,
                        kind: "RelayResolver",
                        name: "call_to_action_spec",
                        resolverModule: n(
                          "AdCallToActionSpecification-call_to_action_spec-resolver",
                        ).call_to_action_spec,
                        path: "object_story_spec.template_data.call_to_action.call_to_action_spec",
                      },
                    ],
                    storageKey: null,
                  },
                  i,
                  {
                    alias: null,
                    args: null,
                    concreteType: "AdObjectStoryChildLinkDataSpecification",
                    kind: "LinkedField",
                    name: "child_attachments",
                    plural: !0,
                    selections: [
                      {
                        alias: null,
                        args: null,
                        fragment: l,
                        kind: "RelayResolver",
                        name: "child_attachment_spec",
                        resolverModule: n(
                          "AdObjectStoryChildLinkDataSpecification-child_attachment_spec-resolver",
                        ).child_attachment_spec,
                        path: "object_story_spec.template_data.child_attachments.child_attachment_spec",
                      },
                    ],
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: null,
                    concreteType: "AdCreativeThumbnailInfo",
                    kind: "LinkedField",
                    name: "collection_thumbnails",
                    plural: !0,
                    selections: [
                      s,
                      {
                        alias: null,
                        args: null,
                        concreteType: "AdImageCropsPerDimensionSpec",
                        kind: "LinkedField",
                        name: "element_crops",
                        plural: !1,
                        selections: [
                          {
                            alias: null,
                            args: null,
                            fragment: u,
                            kind: "RelayResolver",
                            name: "ad_image_crops_per_dimension_spec",
                            resolverModule: n(
                              "AdImageCropsPerDimensionSpec-ad_object_spec-resolver",
                            ).ad_image_crops_per_dimension_spec,
                            path: "object_story_spec.template_data.collection_thumbnails.element_crops.ad_image_crops_per_dimension_spec",
                          },
                        ],
                        storageKey: null,
                      },
                      c,
                    ],
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: null,
                    concreteType: "XFBApiAdCreativeCustomOverlayImageSpec",
                    kind: "LinkedField",
                    name: "custom_overlay_spec",
                    plural: !1,
                    selections: [
                      {
                        alias: null,
                        args: null,
                        fragment: d,
                        kind: "RelayResolver",
                        name: "custom_overlay_specification",
                        resolverModule: n(
                          "XFBApiAdCreativeCustomOverlayImageSpec-custom_overlay_specification-resolver",
                        ).custom_overlay_specification,
                        path: "object_story_spec.template_data.custom_overlay_spec.custom_overlay_specification",
                      },
                    ],
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: null,
                    concreteType: "AdCustomizationRuleSpecification",
                    kind: "LinkedField",
                    name: "customization_rules_spec",
                    plural: !0,
                    selections: [
                      {
                        alias: null,
                        args: null,
                        fragment: m,
                        kind: "RelayResolver",
                        name: "customization_rules_specification",
                        resolverModule: n(
                          "AdCustomizationRuleSpecification-customization_rules_specification-resolver",
                        ).customization_rules_specification,
                        path: "object_story_spec.template_data.customization_rules_spec.customization_rules_specification",
                      },
                    ],
                    storageKey: null,
                  },
                  p,
                  {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "disclaimer_text",
                    storageKey: null,
                  },
                  _,
                  {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "force_single_link",
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "format_option",
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: null,
                    concreteType: "AdImageCropsPerDimensionSpec",
                    kind: "LinkedField",
                    name: "image_crops_per_dimension",
                    plural: !1,
                    selections: [
                      {
                        alias: null,
                        args: null,
                        fragment: u,
                        kind: "RelayResolver",
                        name: "ad_image_crops_per_dimension_spec",
                        resolverModule: n(
                          "AdImageCropsPerDimensionSpec-ad_object_spec-resolver",
                        ).ad_image_crops_per_dimension_spec,
                        path: "object_story_spec.template_data.image_crops_per_dimension.ad_image_crops_per_dimension_spec",
                      },
                    ],
                    storageKey: null,
                  },
                  f,
                  {
                    alias: null,
                    args: null,
                    concreteType: "DynamicImageLayerSpec",
                    kind: "LinkedField",
                    name: "image_layer_specs",
                    plural: !0,
                    selections: [
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "image_source",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "layer_type",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "crop_image",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "pad_image",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "blending_mode",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "frame_auto_show_enroll_status",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "frame_image_hash",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "frame_source",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "opacity",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "overlay_position",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "scale",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "overlay_shape",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "shape_color",
                        storageKey: null,
                      },
                      T,
                      D,
                      {
                        alias: null,
                        args: null,
                        concreteType: "DynamicImageLayerTextOverlayContentSpec",
                        kind: "LinkedField",
                        name: "content",
                        plural: !1,
                        selections: [
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "high_price",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "low_price",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "price",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "type",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "types",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "auto_show_enroll_status",
                            storageKey: null,
                          },
                        ],
                        storageKey: null,
                      },
                    ],
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: null,
                    concreteType: "AdCreativeImageOverlaySpecification",
                    kind: "LinkedField",
                    name: "image_overlay_spec",
                    plural: !1,
                    selections: [
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "custom_text_type",
                        storageKey: null,
                      },
                      x,
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "overlay_template",
                        storageKey: null,
                      },
                      $,
                      D,
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "text_template_tags",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "text_type",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "theme_color",
                        storageKey: null,
                      },
                    ],
                    storageKey: null,
                  },
                  g,
                  h,
                  y,
                  C,
                  b,
                  v,
                  S,
                  {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "picture",
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: null,
                    concreteType:
                      "AdCreativePostClickConfigurationSpecification",
                    kind: "LinkedField",
                    name: "post_click_configuration",
                    plural: !1,
                    selections: [
                      {
                        alias: null,
                        args: null,
                        fragment: L,
                        kind: "RelayResolver",
                        name: "post_click_configuration_specification",
                        resolverModule: n(
                          "AdCreativePostClickConfigurationSpecification-ad_object_spec-resolver",
                        ).post_click_configuration_specification,
                        path: "object_story_spec.template_data.post_click_configuration.post_click_configuration_specification",
                      },
                    ],
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "preferred_image_tags",
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "preferred_video_tags",
                    storageKey: null,
                  },
                  E,
                  P,
                  {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "show_multiple_images",
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: null,
                    concreteType: "XFBDynamicAdStaticFallbackSpec",
                    kind: "LinkedField",
                    name: "static_fallback_spec",
                    plural: !1,
                    selections: [
                      {
                        alias: null,
                        args: null,
                        concreteType: "AdCallToActionSpecification",
                        kind: "LinkedField",
                        name: "call_to_action",
                        plural: !1,
                        selections: [
                          {
                            alias: null,
                            args: null,
                            fragment: a,
                            kind: "RelayResolver",
                            name: "call_to_action_spec",
                            resolverModule: n(
                              "AdCallToActionSpecification-call_to_action_spec-resolver",
                            ).call_to_action_spec,
                            path: "object_story_spec.template_data.static_fallback_spec.call_to_action.call_to_action_spec",
                          },
                        ],
                        storageKey: null,
                      },
                      p,
                      f,
                      g,
                      h,
                      b,
                    ],
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "use_flexible_image_aspect_ratio",
                    storageKey: null,
                  },
                ],
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                concreteType: "AdObjectStoryTextDataSpecification",
                kind: "LinkedField",
                name: "text_data",
                plural: !1,
                selections: [h],
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "threads_user_id",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                concreteType: "AdObjectStoryVideoDataSpecification",
                kind: "LinkedField",
                name: "video_data",
                plural: !1,
                selections: [
                  e,
                  k,
                  r,
                  o,
                  {
                    alias: null,
                    args: null,
                    concreteType: "AdCallToActionSpecification",
                    kind: "LinkedField",
                    name: "call_to_action",
                    plural: !1,
                    selections: [
                      {
                        alias: null,
                        args: null,
                        fragment: a,
                        kind: "RelayResolver",
                        name: "call_to_action_spec",
                        resolverModule: n(
                          "AdCallToActionSpecification-call_to_action_spec-resolver",
                        ).call_to_action_spec,
                        path: "object_story_spec.video_data.call_to_action.call_to_action_spec",
                      },
                    ],
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "caption_ids",
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: null,
                    concreteType: "AdCreativeThumbnailInfo",
                    kind: "LinkedField",
                    name: "collection_thumbnails",
                    plural: !0,
                    selections: [
                      s,
                      {
                        alias: null,
                        args: null,
                        concreteType: "AdImageCropsPerDimensionSpec",
                        kind: "LinkedField",
                        name: "element_crops",
                        plural: !1,
                        selections: [
                          {
                            alias: null,
                            args: null,
                            fragment: u,
                            kind: "RelayResolver",
                            name: "ad_image_crops_per_dimension_spec",
                            resolverModule: n(
                              "AdImageCropsPerDimensionSpec-ad_object_spec-resolver",
                            ).ad_image_crops_per_dimension_spec,
                            path: "object_story_spec.video_data.collection_thumbnails.element_crops.ad_image_crops_per_dimension_spec",
                          },
                        ],
                        storageKey: null,
                      },
                      c,
                    ],
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: null,
                    concreteType: "XFBApiAdCreativeCustomOverlayVideoSpec",
                    kind: "LinkedField",
                    name: "custom_overlay_spec",
                    plural: !0,
                    selections: [
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "background_color",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "background_opacity",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "duration",
                        storageKey: null,
                      },
                      x,
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "full_width",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "option",
                        storageKey: null,
                      },
                      $,
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "start",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "template",
                        storageKey: null,
                      },
                      T,
                    ],
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: null,
                    concreteType: "AdCustomizationRuleSpecification",
                    kind: "LinkedField",
                    name: "customization_rules_spec",
                    plural: !0,
                    selections: [
                      {
                        alias: null,
                        args: null,
                        fragment: m,
                        kind: "RelayResolver",
                        name: "customization_rules_specification",
                        resolverModule: n(
                          "AdCustomizationRuleSpecification-customization_rules_specification-resolver",
                        ).customization_rules_specification,
                        path: "object_story_spec.video_data.customization_rules_spec.customization_rules_specification",
                      },
                    ],
                    storageKey: null,
                  },
                  f,
                  {
                    alias: "image_url",
                    args: null,
                    kind: "ScalarField",
                    name: "image_url_string",
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "link_description",
                    storageKey: null,
                  },
                  h,
                  v,
                  I,
                  R,
                  {
                    alias: null,
                    args: null,
                    concreteType:
                      "AdCreativePostClickConfigurationSpecification",
                    kind: "LinkedField",
                    name: "post_click_configuration",
                    plural: !1,
                    selections: [
                      {
                        alias: null,
                        args: null,
                        fragment: L,
                        kind: "RelayResolver",
                        name: "post_click_configuration_specification",
                        resolverModule: n(
                          "AdCreativePostClickConfigurationSpecification-ad_object_spec-resolver",
                        ).post_click_configuration_specification,
                        path: "object_story_spec.video_data.post_click_configuration.post_click_configuration_specification",
                      },
                    ],
                    storageKey: null,
                  },
                  E,
                  P,
                  {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "title",
                    storageKey: null,
                  },
                  {
                    alias: "video_id",
                    args: null,
                    kind: "ScalarField",
                    name: "video_data_id",
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "video_thumbnail_source",
                    storageKey: null,
                  },
                  _,
                ],
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                concreteType: "XFBAdObjectStoryProductDataSpecification",
                kind: "LinkedField",
                name: "product_data",
                plural: !0,
                selections: [
                  {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "product_id",
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "product_source",
                    storageKey: null,
                  },
                ],
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "whats_app_business_phone_number_id",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "whats_app_business_asset_id",
                storageKey: null,
              },
            ],
            storageKey: null,
          },
        ],
        type: "AdCreative",
        abstractKey: null,
      };
    })();
    a.exports = e;
  },
  null,
);
