__d(
  "AdDraftFragmentSource",
  [],
  function (t, n, r, o, a, i) {
    var e = Object.freeze({
      NONE: "NONE",
      AD_COPY: "AD_COPY",
      BULK_IMPORT: "BULK_IMPORT",
      AD_BUILDER_IMPORT: "AD_BUILDER_IMPORT",
      AD_BUILDER_STANDALONE: "AD_BUILDER_STANDALONE",
      AD_PROPOSAL: "AD_PROPOSAL",
      CAMPAIGN_PLANNING: "CAMPAIGN_PLANNING",
      CLICK_AD_CREATE: "click_ad_create",
      CLICK_AD_VARIATIONS: "click_ad_variations",
      CLICK_AD_DUPLICATE: "click_ad_duplicate",
      CLICK_AD_DUPLICATE_BY_IMAGES: "click_ad_duplicate_by_images",
      CLICK_CREATE_AD_IN_PAGE_PANE: "click_create_ad_in_page_pane",
      CLICK_CREATE_AD_USING_AUDIENCE: "click_create_ad_using_audience",
      COPY_AD: "copy_ad",
      CREATE_FROM_TARGETING_SPEC: "create_from_targeting_spec",
      CLICK_CAMPAIGN_CREATE: "click_campaign_create",
      CLICK_CREATE_CAMPAIGN_USING_AUDIENCE:
        "click_create_campaign_using_audience",
      CLICK_CAMPAIGN_AUDIENCE_SPLITTING: "click_campaign_audience_splitting",
      CAMPAIGN_SECTION_NOTICE: "campaign_section_notice",
      CLICK_CAMPAIGN_GROUP_CREATE: "click_campaign_group_create",
      CLICK_CREATE_CAMPAIGN_GROUP_USING_OBJECTIVE:
        "click_create_campaign_group_using_objective",
      CAMPAIGN_GROUP_SECTION_NOTICE: "campaign_group_section_notice",
      CLICK_BULK_IMPORT: "click_bulk_import",
      CLICK_CAMPAIGN_DUPLICATE: "click_campaign_duplicate",
      CLICK_CAMPAIGN_GROUP_DUPLICATE: "click_campaign_group_duplicate",
      CLICK_DUPLICATE_FROM_TABLE: "click_duplicate_from_table",
      COPY_CAMPAIGN: "copy_campaign",
      CLICK_CONVERGENCE_GLOBAL_CREATE: "click_convergence_global_create",
      CLICK_CONVERGENCE_GLOBAL_EMPTY_STATE:
        "click_convergence_global_empty_state",
      CLICK_CONVERGENCE_GLOBAL_CREATE_EXTERNAL:
        "click_convergence_global_create_external",
      CREATE_ADD_AD_SET_AND_AD: "create_add_ad_set_and_ad",
      CREATE_ADD_AD_SET_AND_AD_CONTEXTUAL:
        "create_add_ad_set_and_ad_contextual",
      CREATE_ADD_AD_SET_AND_AD_EMPTY_STATE:
        "create_add_ad_set_and_ad_empty_state",
      CREATE_ADD_AD: "create_add_ad",
      CREATE_ADD_AD_CONTEXTUAL: "create_add_ad_contextual",
      CREATE_ADD_AD_EMPTY_STATE: "create_add_ad_empty_state",
      ROUTING_CREATION_MODAL: "routing_creation_modal",
      CLICK_CREATE_POST_IN_FILTERED_CREATIVE:
        "click_create_post_in_filtered_creative",
      CLICK_CREATE_POST_IN_PAGE_PANE: "click_create_post_in_page_pane",
      CLICK_CONTEXTUAL_MENU: "click_contextual_menu",
      CREATE_AD_CONTEXTUAL: "create_ad_contextual",
      CREATE_AD_SET_CONTEXTUAL: "create_ad_set_contextual",
      CLICK_CREATE_AD_BY_CREATE_FLOW: "click_create_ad_by_create_flow",
      CLICK_QUICK_CREATE: "click_quick_create",
      QUICK_DUPLICATE_FROM_TREE: "quick_duplicate_from_tree",
      QUICK_DUPLICATE_FROM_TOOLBAR: "quick_duplicate_from_toolbar",
      QUICK_DUPLICATE_FROM_SHORTCUT: "quick_duplicate_from_shortcut",
      DUPLICATE_CAMPAIGN_GROUP_FROM_CLIPBOARD:
        "duplicate_campaign_group_from_clipboard",
      DUPLICATE_CAMPAIGN_FROM_CLIPBOARD: "duplicate_campaign_from_clipboard",
      DUPLICATE_AD_FROM_CLIPBOARD: "duplicate_ad_from_clipboard",
      REACH_FREQUENCY_FROM_CREATE_FLOW: "reach_frequency_from_create_flow",
      STATIC_AD_TO_PAC: "static_ad_to_pac",
      EXISTING_POST_TO_PAC: "existing_post_to_pac",
      ITERATIVE_SPLIT_TEST_ADGROUP_EDIT_UPSELL:
        "iterative_split_test_adgroup_edit_upsell",
      ITERATIVE_SPLIT_TEST_CAMPAIGN_EDIT_UPSELL:
        "iterative_split_test_campaign_edit_upsell",
      SPLIT_TEST_FROM_CREATE_FLOW: "split_test_from_create_flow",
      SPLIT_TEST_FROM_EDIT_FLOW: "split_test_from_edit_flow",
      SPLIT_TEST_CAMPAIGN_GROUP_NOTICE_BAR:
        "split_test_campaign_group_notice_bar",
      SPLIT_TEST_CAMPAIGN_NOTICE_BAR: "split_test_campaign_notice_bar",
      SPLIT_TEST_ADGROUP_NOTICE_BAR: "split_test_adgroup_notice_bar",
      SPLIT_TEST_CHANGE_BLOCKED_DIALOG: "split_test_change_blocked_dialog",
      SPLIT_TEST_REPORTING_NO_WINNER: "split_test_reporting_no_winner",
      SPLIT_TEST_REPORTING_TIE: "split_test_reporting_tie",
      SPLIT_TEST_REPORTING_WINNER_FOUND: "split_test_reporting_winner_found",
      SPLIT_TEST_WINNER_BADGE: "split_test_winner_badge",
      TEST_AND_LEARN_SPLIT_TEST_REPORT: "test_and_learn_split_test_report",
      NES_CR_CREATE: "nes_cr_create",
      NES_DUPLICATE_CAMPAIGN_GROUP: "nes_duplicate_campaign_group",
      NES_DUPLICATE_CAMPAIGN: "nes_duplicate_campaign",
      NES_DUPLICATE_AD: "nes_duplicate_ad",
      CAMPAIGN_PLANNING_CREATE_DRAFT: "campaign_planning_create_draft",
      NOT_SPECIFIED: "not_specified",
      SPLIT_TEST_L2_FROM_AM_OR_ADEX: "split_test_l2_from_am_or_adex",
      PCM_MODAL: "pcm_modal",
      PCM_MODAL_DUPLICATE: "pcm_modal_duplicate",
      CREATION_PACKAGE: "CREATION_PACKAGE",
      CLICK_DUPLICATE_FROM_TOOLBAR: "click_duplicate_from_toolbar",
      CLICK_AD_DUPLICATE_FROM_TOOLBAR: "click_ad_duplicate_from_toolbar",
      CLICK_CAMPAIGN_DUPLICATE_FROM_TOOLBAR:
        "click_campaign_duplicate_from_toolbar",
      CLICK_CAMPAIGN_GROUP_DUPLICATE_FROM_TOOLBAR:
        "click_campaign_group_duplicate_from_toolbar",
      CLICK_DUPLICATE: "click_duplicate",
      CLICK_DUPLICATE_FROM_TREE: "click_duplicate_from_tree",
      CLICK_AD_DUPLICATE_FROM_TREE: "click_ad_duplicate_from_tree",
      CLICK_CAMPAIGN_DUPLICATE_FROM_TREE: "click_campaign_duplicate_from_tree",
      CLICK_CAMPAIGN_GROUP_DUPLICATE_FROM_TREE:
        "click_campaign_group_duplicate_from_tree",
      CLICK_DUPLICATE_FROM_EDIT_DROPDOWN: "click_duplicate_from_edit_dropdown",
      CLICK_AD_DUPLICATE_FROM_EDIT_DROPDOWN:
        "click_ad_duplicate_from_edit_dropdown",
      CLICK_CAMPAIGN_DUPLICATE_FROM_EDIT_DROPDOWN:
        "click_campaign_duplicate_from_edit_dropdown",
      CLICK_CAMPAIGN_GROUP_DUPLICATE_FROM_EDIT_DROPDOWN:
        "click_campaign_group_duplicate_from_edit_dropdown",
      CLICK_CAMPAIGN_GROUP_DUPLICATE_FROM_PERFORMANCE_SUMMARY:
        "click_campaign_group_duplicate_from_performance_summary",
      QUICK_DUPLICATE: "quick_duplicate",
      QUICK_DUPLICATE_FROM_EDIT_DROPDOWN: "quick_duplicate_from_edit_dropdown",
      QUICK_DUPLICATE_FROM_TABLE: "quick_duplicate_from_table",
      CBO_BUDGET_SEGMENTS: "CBO_BUDGET_SEGMENTS",
      AMA_CREATION_FLOW: "AMA_CREATION_FLOW",
      AMA_DUPLICATION_FLOW: "AMA_DUPLICATION_FLOW",
      AMA_EDIT_FLOW: "AMA_EDIT_FLOW",
      ODAX_DUPLICATE: "odax_duplicate",
      CLICK_AD_CREATE_MULTIPLE: "click_ad_create_multiple",
      SUGGESTED_ADS: "suggested_ads",
      QUICK_DUPLICATE_FROM_CHARTS_HEADER: "quick_duplicate_from_charts_header",
      CLICK_AD_DUPLICATE_CTA: "click_ad_duplicate_cta",
      SPLIT_TEST_REPORT_DUPLICATE_WINNER: "split_test_report_duplicate_winner",
      SPLIT_TEST_BEAKER_DUPLICATE_WINNER: "split_test_beaker_duplicate_winner",
      SHOPS_ADS_DUPLICATE_FROM_INSIGHTS_GUIDANCE_CARD:
        "shops_ads_duplicate_from_insights_guidance_card",
      SHOPS_ADS_QUICK_DUPLICATE_FROM_INSIGHTS_GUIDANCE_CARD:
        "shops_ads_quick_duplicate_from_insights_guidance_card",
      UPGRADE_DUPLICATE: "upgrade_duplicate",
      PREFLIGHT_CREATIVE_LIMITED_GUIDANCE_CARD:
        "preflight_creative_limited_guidance_card",
      ASPECT_RATIO_RECOMMENDATION_DUPLICATE_CTA:
        "aspect_ratio_recommendation_duplicate_cta",
      ODAX_EDITOR_DUPLICATE: "odax_editor_duplicate",
      UPGRADE_PACKAGE_DUPLICATE: "upgrade_package_duplicate",
      CLICK_DUPLICATE_FROM_TABLE_DELIVERY_STATUS_TOOLTIP:
        "click_duplicate_from_table_delivery_status_tooltip",
      CREATION_PACKAGE_DEFAULT_OPT_IN: "creation_package_default_opt_in",
      SMART_SUGGESTED_ADS_ON_ASC: "smart_suggested_ads_on_asc",
      ODAX_ENFORCEMENT_QUICK_DUPLICATE: "odax_enforcement_quick_duplicate",
      QUICK_DUPLICATE_REDIRECT: "quick_duplicate_redirect",
      SMART_SUGGESTED_ADS_ON_MANUAL: "smart_suggested_ads_on_manual",
      ASC_FRAGMENTATION_MFR: "asc_fragmentation_mfr",
      LIGHTWEIGHT_AB_TEST: "lightweight_ab_test",
      COPY_PASTE_REDIRECT: "copy_paste_redirect",
      GUIDED_ONBOARDING: "guided_onboarding",
      BLENDED_ADS_VIA_L3_DUPLICATION: "blended_ads_via_l3_duplication",
      BLENDED_ADS_VIA_MFR: "blended_ads_via_mfr",
      BLENDED_ADS_VIA_CREATION: "blended_ads_via_creation",
      FRAGMENTATION_AUTO_RULE: "fragmentation_auto_rule",
      CLICK_CAMPAIGN_GROUP_DUPLICATE_FROM_IG_CREATED_ADS:
        "click_campaign_group_duplicate_from_ig_created_ads",
      LWI_GRADUATION_CREATION_PACKAGE: "lwi_graduation_creation_package",
      LWI_GRADUATION_ITERATION_CREATION_PACKAGE:
        "lwi_graduation_iteration_creation_package",
      QUICK_DUPLICATE_UPGRADE_FROM_TREE: "quick_duplicate_upgrade_from_tree",
      QUICK_DUPLICATE_UPGRADE_FROM_TOOLBAR:
        "quick_duplicate_upgrade_from_toolbar",
      QUICK_DUPLICATE_UPGRADE_FROM_SHORTCUT:
        "quick_duplicate_upgrade_from_shortcut",
      QUICK_DUPLICATE_UPGRADE_FROM_EDIT_DROPDOWN:
        "quick_duplicate_upgrade_from_edit_dropdown",
      DUPLICATE_UPGRADE_CAMPAIGN_GROUP_FROM_CLIPBOARD:
        "duplicate_upgrade_campaign_group_from_clipboard",
      DUPLICATE_UPGRADE_CAMPAIGN_FROM_CLIPBOARD:
        "duplicate_upgrade_campaign_from_clipboard",
      DUPLICATE_UPGRADE_AD_FROM_CLIPBOARD:
        "duplicate_upgrade_ad_from_clipboard",
      IGFA_GRADUATION_CREATION_PACKAGE: "igfa_graduation_creation_package",
      BLENDED_ADS_VIA_CREATION_FOR_SHOPS_AND_SHOPIFY_ADVERTISERS_FLOW:
        "blended_ads_via_creation_for_shops_and_shopify_advertisers_flow",
      BLENDED_ADS_VIA_CREATION_FOR_DA_ADVERTISERS_FLOW:
        "blended_ads_via_creation_for_da_advertisers_flow",
      PURCHASE_OPTIMIZATION_MIDFLIGHT_RECOMMENDATION:
        "purchase_optimization_midflight_recommendation",
      DUPLICATE_UPGRADE_COPY_PASTE_REDIRECT:
        "duplicate_upgrade_copy_paste_redirect",
      LWI_GRADUATION: "lwi_graduation",
      PREFLIGHT_RECOMMENDATION_HUB: "preflight_recommendation_hub",
      QUICK_DUPLICATE_UPGRADE: "quick_duplicate_upgrade",
      COPY_PASTE_UPGRADE: "copy_paste_upgrade",
      IGFA_ONBOARDING: "igfa_onboarding",
      BLENDED_ADS_VIA_L3_DUPLICATION_FOR_DA_ADVERTISERS_FLOW:
        "blended_ads_via_l3_duplication_for_da_advertisers_flow",
      PREFLIGHT_MIXED_FORMATS_GUIDANCE_CARD:
        "preflight_mixed_formats_guidance_card",
      SHOPIFY_META_APP: "shopify_meta_app",
      APPLY_RECOMMENDATION: "apply_recommendation",
      ADS_SYD_AD_SLIDER: "ads_syd_ad_slider",
      IGFA_ADS_SLIDERS: "igfa_ads_sliders",
      ADS_SLIDER_MBS_HOME_DEEPLINK: "ads_slider_mbs_home_deeplink",
      ADS_SLIDER_MBS_AFTERPARTY_DEEPLINK: "ads_slider_mbs_afterparty_deeplink",
      SELLER_UPSELL_ON_APAC_MICE: "seller_upsell_on_apac_mice",
      MBS_CONTENT_TAB_DEEPLINK: "mbs_content_tab_deeplink",
      IGFA_SYD_WIDGET: "igfa_syd_widget",
      CTWA_AD4AD_AM_LANDING: "ctwa_ad4ad_am_landing",
      DUPLICATE_OPTIMAL_MODAL: "duplicate_optimal_modal",
      DUPLICATE_OPTIMAL_CREATION_MODAL: "duplicate_optimal_creation_modal",
      MBS_HOME_RECENT_POSTS_GRID_CARD_DEEPLINK:
        "mbs_home_recent_posts_grid_card_deeplink",
      MBS_OBJECT_INSIGHTS_DEEPLINK: "mbs_object_insights_deeplink",
      MBS_OBJECT_TEMPLATE_DEEPLINK: "mbs_object_template_deeplink",
      MBS_HOME_HEADER_DEEPLINK: "mbs_home_header_deeplink",
      MBS_AD_CENTER_HEADER_DEEPLINK: "mbs_ad_center_header_deeplink",
      IG_WEBFEED_AD4AD_AM_LANDING: "ig_webfeed_ad4ad_am_landing",
      SYD_RECENT_CAMPAIGNS_WIDGET: "syd_recent_campaigns_widget",
      FULL_FUNNEL_CREATION: "full_funnel_creation",
      MAIBA_LWI_BOOST_POST_TOOL: "maiba_lwi_boost_post_tool",
      PCR_BUNDLE: "pcr_bundle",
      LWI_BOOST_POST_AM_LANDING: "lwi_boost_post_am_landing",
      WTM_BOOST_POST_AM_LANDING: "wtm_boost_post_am_landing",
      CPAS_LVA_UPSELL: "cpas_lva_upsell",
      AM_SYD_NUO_GRADUATION: "am_syd_nuo_graduation",
      OPTIMAL_START_ENTRY_POINT: "optimal_start_entry_point",
      ADS_SIMPLIFIED_ONE_CLICK: "ads_simplified_one_click",
      WAM_ADS_SLIDER: "wam_ads_slider",
      AUTO_2_0: "auto_2_0",
      GBM_ADS_SLIDER_AM_CTA: "gbm_ads_slider_am_cta",
      WEBSITE_ADS_TOFU_AM_LANDING: "website_ads_tofu_am_landing",
      MAIBA_E2E_CAMPAIGN_CREATION: "maiba_e2e_campaign_creation",
      WEBSITE_ADS_AD4AD_AM_LANDING: "website_ads_ad4ad_am_landing",
      DFO_ADS_AD4AD_AM_LANDING: "dfo_ads_ad4ad_am_landing",
      OPTIMAL_START_CREATION: "optimal_start_creation",
      MCP_CAMPAIGN_CREATION: "mcp_campaign_creation",
      AMA_DRAFT_CREATION_FLOW: "AMA_DRAFT_CREATION_FLOW",
      AMA_DRAFT_DUPLICATION_FLOW: "AMA_DRAFT_DUPLICATION_FLOW",
      CAMPAIGN_TEMPLATE_CREATION: "campaign_template_creation",
      ADS_CAMPAIGN_EMPTY_STATE: "ads_campaign_empty_state",
      AMA_POST_TO_AD_FLOW: "AMA_POST_TO_AD_FLOW",
      PRODUCT_INSIGHTS_PE_DUPLICATION: "product_insights_pe_duplication",
      PARTNERSHIP_ADS_HUB_ONE_CLICK: "partnership_ads_hub_one_click",
      AM_BOOST_ON_FB_FOR_AA_DEEPLINK: "am_boost_on_fb_for_aa_deeplink",
      CTD_AD4AD_AM_LANDING: "ctd_ad4ad_am_landing",
    });
    i.default = e;
  },
  66,
);
