__d(
  "AdgroupAdObjectSpecTier1V2Resolver.graphql",
  [
    "AdCreative-ad_object_spec-resolver",
    "AdCallToActionSpecification-call_to_action_spec-resolver",
    "AdImageCropsPerDimensionSpec-ad_object_spec-resolver",
    "AdCallToActionSpecification-call_to_action_spec-resolver",
  ],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = (function () {
      var e = {
          args: null,
          kind: "FragmentSpread",
          name: "AdCallToActionSpecificationCallToActionSpecResolver",
        },
        t = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "source",
          storageKey: null,
        },
        r = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "text",
          storageKey: null,
        },
        o = [r],
        a = [
          r,
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "asset_source",
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "uuid",
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "text_gen_original_text",
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "text_gen_input_text",
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "action_type",
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "language",
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "target_audience",
            storageKey: null,
          },
        ];
      return {
        argumentDefinitions: [
          { defaultValue: null, kind: "LocalArgument", name: "thumbnail_size" },
        ],
        kind: "Fragment",
        metadata: null,
        name: "AdgroupAdObjectSpecTier1V2Resolver",
        selections: [
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "__typename",
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "ad_account_legacy_account_id",
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            concreteType: "AdCreative",
            kind: "LinkedField",
            name: "creative",
            plural: !1,
            selections: [
              {
                alias: null,
                args: [],
                fragment: {
                  args: [
                    {
                      kind: "Variable",
                      name: "thumbnail_size",
                      variableName: "thumbnail_size",
                    },
                  ],
                  kind: "FragmentSpread",
                  name: "AdCreativeAdObjectSpecResolver",
                },
                kind: "RelayResolver",
                name: "adgroup_creative_spec",
                resolverModule: n("AdCreative-ad_object_spec-resolver")
                  .adgroup_creative_spec,
                path: "creative.adgroup_creative_spec",
              },
            ],
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            concreteType: "CreativeAssetGroupsSpec",
            kind: "LinkedField",
            name: "creative_asset_groups_spec",
            plural: !1,
            selections: [
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "origins",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                concreteType: "CreativeAssetGroupSpec",
                kind: "LinkedField",
                name: "groups",
                plural: !0,
                selections: [
                  {
                    alias: null,
                    args: null,
                    concreteType: "AdCallToActionSpecification",
                    kind: "LinkedField",
                    name: "call_to_action",
                    plural: !1,
                    selections: [
                      {
                        alias: null,
                        args: null,
                        fragment: e,
                        kind: "RelayResolver",
                        name: "call_to_action_spec",
                        resolverModule: n(
                          "AdCallToActionSpecification-call_to_action_spec-resolver",
                        ).call_to_action_spec,
                        path: "creative_asset_groups_spec.groups.call_to_action.call_to_action_spec",
                      },
                    ],
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "group_uuid",
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "group_type",
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: null,
                    concreteType: "CreativeAssetGroupImageSpec",
                    kind: "LinkedField",
                    name: "images",
                    plural: !0,
                    selections: [
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "hash",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        concreteType: "AdImageCropsPerDimensionSpec",
                        kind: "LinkedField",
                        name: "image_crops",
                        plural: !1,
                        selections: [
                          {
                            alias: null,
                            args: null,
                            fragment: {
                              args: null,
                              kind: "FragmentSpread",
                              name: "AdImageCropsPerDimensionSpecAdObjectSpecResolver",
                            },
                            kind: "RelayResolver",
                            name: "ad_image_crops_per_dimension_spec",
                            resolverModule: n(
                              "AdImageCropsPerDimensionSpec-ad_object_spec-resolver",
                            ).ad_image_crops_per_dimension_spec,
                            path: "creative_asset_groups_spec.groups.images.image_crops.ad_image_crops_per_dimension_spec",
                          },
                        ],
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "url",
                        storageKey: null,
                      },
                      t,
                    ],
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: null,
                    concreteType: "CreativeAssetGroupVideoSpec",
                    kind: "LinkedField",
                    name: "videos",
                    plural: !0,
                    selections: [
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "video_id",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "image_hash",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "image_url",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "thumbnail_id",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "thumbnail_source",
                        storageKey: null,
                      },
                      t,
                    ],
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: null,
                    concreteType: "CreativeAssetGroupTextSpec",
                    kind: "LinkedField",
                    name: "short_texts",
                    plural: !0,
                    selections: o,
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: null,
                    concreteType: "CreativeAssetGroupTextSpec",
                    kind: "LinkedField",
                    name: "long_texts",
                    plural: !0,
                    selections: o,
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: null,
                    concreteType: "CreativeAssetGroupTextSpec",
                    kind: "LinkedField",
                    name: "texts",
                    plural: !0,
                    selections: [
                      r,
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "text_type",
                        storageKey: null,
                      },
                    ],
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: null,
                    concreteType: "CreativeAssetGroupPostSpec",
                    kind: "LinkedField",
                    name: "posts",
                    plural: !0,
                    selections: [
                      {
                        alias: null,
                        args: null,
                        concreteType: "CreativeMultiTextBodySpec",
                        kind: "LinkedField",
                        name: "bodies",
                        plural: !0,
                        selections: a,
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "body",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        concreteType: "AdCallToActionSpecification",
                        kind: "LinkedField",
                        name: "call_to_action",
                        plural: !1,
                        selections: [
                          {
                            alias: null,
                            args: null,
                            fragment: e,
                            kind: "RelayResolver",
                            name: "call_to_action_spec",
                            resolverModule: n(
                              "AdCallToActionSpecification-call_to_action_spec-resolver",
                            ).call_to_action_spec,
                            path: "creative_asset_groups_spec.groups.posts.call_to_action.call_to_action_spec",
                          },
                        ],
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "post_id",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "source_instagram_media_id",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "title",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        concreteType: "CreativeMultiTextTitleSpec",
                        kind: "LinkedField",
                        name: "titles",
                        plural: !0,
                        selections: a,
                        storageKey: null,
                      },
                    ],
                    storageKey: null,
                  },
                ],
                storageKey: null,
              },
            ],
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            concreteType: "AdgroupCreativeAutomationSpec",
            kind: "LinkedField",
            name: "creative_automation_spec",
            plural: !1,
            selections: [
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "enrollment_status",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "decision_type",
                storageKey: null,
              },
            ],
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "effective_instagram_media_id",
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "effective_instagram_story_id",
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "effective_status",
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "id",
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "instagram_permalink_url",
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "status",
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "uca_draft_version",
            storageKey: null,
          },
        ],
        type: "Adgroup",
        abstractKey: null,
      };
    })();
    a.exports = e;
  },
  null,
);
