__d(
  "AdsAutoGeneratedCaptionCaptionsFetchDataReducerPlugin",
  ["AdsAutoGeneratedCaptionDataManager", "AutoGeneratedCaptionData"],
  function (t, n, r, o, a, i, l) {
    "use strict";
    var e = {
        reduce: function (t, n) {
          return t.update("captionDataByVideoID", function (e) {
            var a = t.get("newVideos").indexOf(n.videoID) >= 0;
            return (
              o("AdsAutoGeneratedCaptionDataManager").fetchCaptions(
                n.videoID,
                a,
              ),
              e.get(n.videoID)
                ? e.set(
                    n.videoID,
                    e
                      .get(n.videoID)
                      .set("isFetched", !1)
                      .set(
                        "captionAutogenerationStatus",
                        n.captionAutogenerationStatus,
                      ),
                  )
                : e.set(n.videoID, new (r("AutoGeneratedCaptionData"))())
            );
          });
        },
      },
      s = e;
    l.default = s;
  },
  98,
);
