__d(
  "AdsAPIConnectionObjectFields",
  [],
  function (t, n, r, o, a, i) {
    var e = Object.freeze({
      ID: "id",
      NAME: "name",
      NAME_WITH_LOCATION_DESCRIPTOR: "name_with_location_descriptor",
      URL: "url",
      TYPE: "type",
      ENGAGEMENT_SCORE: "engagement_score",
      CHECKIN_CAPABLE: "checkin_capable",
      PICTURE: "picture",
      TABS: "tabs",
      IS_GAME: "is_game",
      SUPPORTED_PLATFORMS: "supported_platforms",
      NATIVE_APP_STORE_IDS: "native_app_store_ids",
      OBJECT_STORE_URLS: "object_store_urls",
      APP_INSTALLS_TRACKED: "app_installs_tracked",
      NATIVE_APP_TARGETING_IDS: "native_app_targeting_ids",
      OG_NAMESPACE: "og_namespace",
      OG_ACTIONS: "og_actions",
      OG_OBJECTS: "og_objects",
      WEBSITE: "website",
      LOGO_URL: "logo_url",
      ICON_URL: "icon_url",
      PRIVACY: "privacy",
      EVENT_PARENT_PAGE_ID: "event_parent_page_id",
      EVENT_PARENT_PAGE_NAME: "event_parent_page_name",
      EVENT_START_TIMESTAMP: "event_start_timestamp",
      EVENT_IS_VIEWER_ADMIN: "event_is_viewer_admin",
      DISPLAY_NAME: "display_name",
      PROPERTIES: "properties",
      CONNECTED_OBJECTS: "connected_objects",
      EXTRA_FBIDS: "extra_fbids",
      EXTRA_ONLY: "extra_only",
      LIMIT: "limit",
      OFFSET: "offset",
      BUSINESS_ID: "business_id",
      NON_BUSINESS_ONLY: "non_business_only",
      CPA_ACCESS: "cpa_access",
    });
    i.default = e;
  },
  66,
);
