__d(
  "AdsAPIAdAccountFields",
  [],
  function (t, n, r, o, a, i) {
    var e = Object.freeze({
      ACCOUNT_ADMARKET_ID: "account_admarket_id",
      ACCOUNT_CURRENCY_RATIO_TO_USD: "account_currency_ratio_to_usd",
      ACCOUNT_ID: "account_id",
      ACCOUNT_STATUS: "account_status",
      ACTIVE_ASL_SCHEDULE: "active_asl_schedule",
      ACTIVE_BILLING_DATE_PREFERENCE: "active_billing_date_preference",
      AD_COPIES_AND_EDITS: "ad_copies_and_edits",
      ADCAMPAIGNS: "adcampaigns",
      ADCAMPAIGN_GROUPS: "adcampaign_groups",
      ADCAMPAIGNSTATS: "adcampaignstats",
      ADCONTRACTS: "adcontracts",
      AD_PROPOSAL: "ad_proposal",
      ADSTEXTPREFILLSUGGESTIONS: "adstextprefillsuggestions",
      AGENCIES: "agencies",
      ASYNC_AD_COPIES: "asyncadcopies",
      ASYNC_AD_COPIES_FULL_FRAGMENTS: "asyncadcopiesfullfragments",
      AUDIENCE_STUDY_SIZE: "audience_study_size",
      AD_ACCOUNT_CREATION_REQUEST: "ad_account_creation_request",
      AD_ACCOUNT_PROMOTABLE_OBJECTS: "ad_account_promotable_objects",
      ADCREATIVES: "adcreatives",
      ADDRAFTS: "addrafts",
      ADGROUPS: "adgroups",
      ADGROUPSTATS: "adgroupstats",
      ADIMAGES: "adimages",
      ADLABELS: "adlabels",
      ADRULES: "adrules",
      ADRULES_OPERATION: "adrules_operation",
      ADREPORTSPECS: "adreportspecs",
      ADTAGS: "adtags",
      ADS_CREATION_SAVED_STATE: "ads_creation_saved_state",
      ADSPAYMENTCYCLE: "adspaymentcycle",
      ADVERTISER_VERIFICATION_STATUS: "advertiser_verification_status",
      AGE: "age",
      AGENCY_CLIENT_DECLARATION: "agency_client_declaration",
      AGENCY_FEE_CONFIG: "agency_fee_config",
      ALL_PAYMENT_METHODS: "all_payment_methods",
      ALL_CAPABILITIES: "all_capabilities",
      AMOUNT_SPENT: "amount_spent",
      ARCHIVED_CAMPAIGN_GROUP_COUNT: "archived_campaign_group_count",
      ARCHIVED_CAMPAIGN_COUNT: "archived_campaign_count",
      ARCHIVED_ADGROUP_COUNT: "archived_adgroup_count",
      ATTRIBUTION_SPEC: "attribution_spec",
      ATTR_WINDOW_DEPRECATION_GROUP: "attr_window_deprecation_group",
      ASSET_FEED_SPEC_FROM_EXISTING_POST: "asset_feed_spec_from_existing_post",
      ASSET_FEED_SPEC_FROM_INSTAGRAM_MEDIA:
        "asset_feed_spec_from_instagram_media",
      AUDI_EXTRACT_BANNED_TERMS: "audi_extract_banned_terms",
      AUDIENCES: "audiences",
      AUTOMATIC_CREATIVE_OPTIMIZATION_TEST_FRAMEWORK_ENROLLED:
        "automatic_creative_optimization_test_framework_enrolled",
      AI_GENERATED_FEATURES_TEST_FRAMEWORK_ENROLLED:
        "ai_generated_features_test_framework_enrolled",
      AVERAGE_DAILY_CAMPAIGN_BUDGET: "average_daily_campaign_budget",
      AVERAGE_LIFETIME_CAMPAIGN_BUDGET: "average_lifetime_campaign_budget",
      AVERAGE_DAILY_CAMPAIGN_GROUP_BUDGET:
        "average_daily_campaign_group_budget",
      AVERAGE_LIFETIME_CAMPAIGN_GROUP_BUDGET:
        "average_lifetime_campaign_group_budget",
      BALANCE: "balance",
      BANK_INFO_LIST: "bank_info_list",
      BILL_TO_ORG: "bill_to_org",
      BRANDS: "brands",
      BROADTARGETINGCATEGORIES: "broadtargetingcategories",
      BUSINESS: "business",
      BUSINESS_AD_ACCOUNT_REQUESTS: "business_ad_account_requests",
      BUSINESS_CITY: "business_city",
      BUSINESS_COUNTRY_CODE: "business_country_code",
      BUSINESS_ENTITY: "business_entity",
      BUSINESS_NAME: "business_name",
      BUSINESS_STATE: "business_state",
      BUSINESS_STREET: "business_street",
      BUSINESS_STREET2: "business_street2",
      BUSINESS_ZIP: "business_zip",
      BUSINESS_VERIFICATION_STATUS: "business_verification_status",
      BUSINESSLABELS: "businessprojects",
      CALL_ADS_AD_ACCOUNT_SIMILAR_ADVERTISER_BUDGET_RECOMMENDATION:
        "call_ads_ad_account_similar_advertiser_budget_recommendation",
      CALL_ADS_SIMILAR_ADVERTISER_BUDGET_RECOMMENDATION:
        "call_ads_similar_advertiser_budget_recommendation",
      CAMPAIGN_GROUP_WITH_CBO: "campaign_group_with_cbo",
      CAN_BE_BLOCKED_FROM_PIXEL_SHARING: "can_be_blocked_from_pixel_sharing",
      CAN_BYPASS_FS_CHECK: "can_bypass_fs_check",
      CAN_CREATE_BRAND_LIFT_STUDY: "can_create_brand_lift_study",
      CAN_PAY_NOW: "can_pay_now",
      CAN_REMOVE_PAYMENT_METHODS: "can_remove_payment_methods",
      CAN_REPAY_NOW: "can_repay_now",
      CAN_SEE_COLLABORATIVE_ADS_REPORTING:
        "can_see_collaborative_ads_reporting",
      CPAS_CAMPAIGN_DEFAULT_BUDGET: "cpas_campaign_default_budget",
      CPAS_CAMPAIGN_GROUP_DEFAULT_BUDGET: "cpas_campaign_group_default_budget",
      CAPABILITIES: "capabilities",
      CLIENT_TRANSPARENCY_STATUS: "client_transparency_status",
      CONNECTIONOBJECTS: "connectionobjects",
      CREATED_TIME: "created_time",
      CROSS_APP_DRAFT_FRAGMENT_COPIES: "cross_app_draft_fragment_copies",
      CURRENT_ADDRAFTS: "current_addrafts",
      CURRENCY: "currency",
      CURRENT_UNBILLED_SPEND: "current_unbilled_spend",
      CURRENT_UNPAID_UNREPAID_INVOICE: "current_unpaid_unrepaid_invoice",
      CUSTOM_AUDIENCES: "customaudiences",
      CUSTOMER_ELASTICITY_STUDY_METRICS: "customer_elasticity_study_metrics",
      RECOMMENDED_AUDIENCES: "recommendedaudiences",
      CUSTOMER_PO_NUMBER: "customer_po_number",
      CTM_PURCHASE_OPTIMIZATION_ELIGIBLE_PAGE_ID:
        "purchase_optimization_eligible_page_id",
      CTX_DFO_OBJECTIVE_DEFAULTS: "ctx_dfo_objective_defaults",
      CTX_ADVERTISER_SABR_LIFETIME_DURATION_RECOMMENDATION:
        "ctx_advertiser_sabr_lifetime_duration_recommendation",
      DAILY_SPEND_LIMIT: "daily_spend_limit",
      DIRECT_DEALS_TOS: "direct_deals_tos",
      DCAF: "dcaf",
      DEFAULT_DESTINATION: "default_destination",
      DEFAULT_DSA_BENEFICIARY: "default_dsa_beneficiary",
      DEFAULT_DSA_PAYOR: "default_dsa_payor",
      DEFAULT_OBJECTIVE: "default_objective",
      DEFAULT_VALUES: "default_values",
      DEFAULT_UNIFIED_ATTRIBUTION_SPEC: "default_unified_attribution_spec",
      DIRECT_DEALS_TOS_ACCEPTED: "direct_deals_tos_accepted",
      DISABLE_REASON: "disable_reason",
      DISPLAY_OMNI_CONVERSION_LOCATION_OPTED_IN:
        "display_omni_conversion_location_opted_in",
      DOMAIN_AND_SITE_LINKS: "domain_and_site_links",
      END_ADVERTISER: "end_advertiser",
      END_ADVERTISER_NAME: "end_advertiser_name",
      EXPIRED_FUNDING_SOURCE_DETAILS: "expired_funding_source_details",
      EXTENDED_CREDIT: "extended_credit",
      EXTENDED_CREDIT_INFO: "extended_credit_info",
      EXTENDED_CREDIT_INVOICE_GROUP: "extended_credit_invoice_group",
      FAILED_DELIVERY_CHECKS: "failed_delivery_checks",
      FB_ENTITY: "fb_entity",
      FLEX_SINGLE_OBJECTIVE: "flex_single_objective",
      FRIENDLY_NAME: "friendly_name",
      FUNDING_SOURCE: "funding_source",
      FUNDING_SOURCE_DETAILS: "funding_source_details",
      HAS_STARTED_PURCHASE_OPTIMIZED_CTM_AD_WITHIN_1D:
        "has_started_purchase_optimized_ctm_ad_within_1d",
      HAS_PURCHASE_OPTIMIZATION_ELIGIBLE_PAGE:
        "has_purchase_optimization_eligible_page",
      HAS_ADVERTISER_OPTED_IN_ODAX: "has_advertiser_opted_in_odax",
      HAS_COMBO_CARDS_ON_FILE: "has_combo_cards_on_file",
      HAS_PAGE_AUTHORIZED_ADACCOUNT: "has_page_authorized_adaccount",
      HAS_PERSONAL_ACCESS: "has_personal_access",
      HAS_EXTENDED_CREDIT: "has_extended_credit",
      HAS_MIGRATED_PERMISSIONS: "has_migrated_permissions",
      HAS_REPAY_PROCESSING_INVOICES: "has_repay_processing_invoices",
      HAS_VALUE_RULE_SET: "has_value_rule_set",
      ID: "id",
      IF_VIEWER_HAS_PERMISSION_TO_ADVERTISE:
        "if_viewer_has_permission_to_advertise",
      INCREMENTAL_CONVERSION_OPTIMIZATION_AD_STUDIES:
        "incremental_conversion_optimization_ad_studies",
      IO_NUMBER: "io_number",
      INVOICING_EMAILS: "invoicing_emails",
      INVOICE_GROUP_EMAILS: "invoice_group_emails",
      IS_ATTRIBUTION_SPEC_SYSTEM_DEFAULT: "is_attribution_spec_system_default",
      IS_BA_SKIP_DELAYED_ELIGIBLE: "is_ba_skip_delayed_eligible",
      IS_BIZ_MIGRATION_ELIGIBLE: "is_biz_migration_eligible",
      IS_BR_ENTITY_ACCOUNT: "is_br_entity_account",
      IS_CLOSED_BY_ADVERTISER_COMPROMISE_BOT:
        "is_closed_by_advertiser_compromise_bot",
      IS_COLLABORATIVE_ADS_AD_ACCOUNT: "is_collaborative_ads_ad_account",
      IS_CTX_ADVERTISER: "is_ctx_advertiser",
      IS_DIRECT_DEALS_ENABLED: "is_direct_deals_enabled",
      IS_DISABLED_UMBRELLA: "is_disabled_umbrella",
      IS_ELIGIBLE_FOR_SHARING_TO_BUSINESS:
        "is_eligible_for_sharing_to_business",
      IS_MI_BILLING_INFO_UPDATED: "is_mi_billing_info_updated",
      IS_NOTIFICATIONS_ENABLED: "is_notifications_enabled",
      IS_OBA_OPT_OUT: "is_oba_opt_out",
      IS_PAGELESS_CTWA_ELIGIBLE: "is_pageless_ctwa_eligible",
      IS_PENDING_NUMBERS_EXPOSURE_FLAG_ENABLED:
        "is_pending_numbers_exposure_flag_enabled",
      IS_PLACEMENT_SOFT_OPT_OUT_ENABLED: "is_placement_soft_opt_out_enabled",
      IS_PERSONAL: "is_personal",
      IS_PINLESS_DEBIT_ELIGIBLE: "is_pinless_debit_eligible",
      IS_PREPAY_ACCOUNT: "is_prepay_account",
      IS_SIMPLIFIED_CREATION_SEGMENT_ELIGIBLE:
        "is_simplified_creation_segment_eligible",
      IS_TAX_ID_REQUIRED: "is_tax_id_required",
      IS_SHOPLESS_AWPT_ELIGIBLE: "is_shopless_awpt_eligible",
      IS_EXPANDED_SHOPLESS_AWPT_ELIGIBLE: "is_expanded_shopless_awpt_eligible",
      IS_OMNICHANNEL_CAMPAIGN_ELIGIBLE: "is_omnichannel_campaign_eligible",
      IS_MM_LITE_API_ENABLED: "is_mm_lite_api_enabled",
      TAX_EXEMPT: "tax_exempt",
      IS_TIER_0: "is_tier_0",
      IS_TIER_0_FULL: "is_tier_0_full",
      IS_TIER_1: "is_tier_1",
      IS_TIER_RESTRICTED: "is_tier_restricted",
      IS_UPDATE_TIMEZONE_CURRENCY_TOO_RECENTLY:
        "is_update_timezone_currency_too_recently",
      IS_USING_HIGHER_DAILY_FLEX_RATE: "is_using_higher_daily_flex_rate",
      IS_WA_CLOUD_API_USER: "is_wa_cloud_api_user",
      IS_IN_MIDDLE_OF_LOCAL_ENTITY_MIGRATION:
        "is_in_middle_of_local_entity_migration",
      IS_IN_3DS_AUTHORIZATION_ENABLED_MARKET:
        "is_in_3ds_authorization_enabled_market",
      IS_ELIGIBLE_FOR_ADVANTAGE_PLUS_CREATIVE_REGULATED_CATEGORY:
        "is_eligible_for_advantage_plus_creative_regulated_category",
      IS_YOUTH_ADS_PAO_BASIC_ADVERTISER: "is_youth_ads_pao_basic_advertiser",
      IS_YOUTH_ADS_PAO_BASIC_ADVERTISER_ANNOUNCEMENT_ELIGIBLE:
        "is_youth_ads_pao_basic_advertiser_announcement_eligible",
      LIVE_VIDEO_ADVERTISER_DETAILS: "live_video_advertiser_details",
      LAST_SPEND_TIME: "last_spend_time",
      LAST_USED_TIME: "last_used_time",
      LIABLE_ADDRESS: "liable_address",
      LIABLE_ADDRESSES: "liable_addresses",
      LIABLE_TO_ORG: "liable_to_org",
      LINE_NUMBERS: "line_numbers",
      MAYBE_PAC_INTERNAL_POST_FROM_PRIMARY_POST:
        "maybe_pac_internal_post_from_primary_post",
      MAX_BILLING_THRESHOLD: "max_billing_threshold",
      MARKETING_MESSAGE_ENABLEMENT_STATUS:
        "marketing_message_enablement_status",
      MARKETING_MESSAGES_SETTINGS: "marketing_messages_settings",
      MEDIA_AGENCY: "media_agency",
      MIN_BILLING_THRESHOLD: "min_billing_threshold",
      MIN_CAMPAIGN_GROUP_SPEND_CAP: "min_campaign_group_spend_cap",
      MIN_DAILY_BUDGET: "min_daily_budget",
      MIN_LIVE_BOOSTING_BUDGET: "min_live_boosting_budget",
      MIN_PAYMENT: "min_payment",
      MOO_DEFAULT_CONVERSION_BID: "moo_default_conversion_bid",
      NAME: "name",
      NAMING_TEMPLATES: "naming_templates",
      NEXT_BILL_DATE: "next_bill_date",
      OFFSITE_CLO_SIGNAL_STATUS: "offsite_clo_signal_status",
      OFFSITE_PIXELS_TOS_ACCEPTED: "offsite_pixels_tos_accepted",
      ON_BEHALF_OF: "on_behalf_of",
      OPTIMAL_DELIVERY_GROWTH_OPPORTUNITIES:
        "optimal_delivery_growth_opportunities",
      OPPORTUNITY_SCORE: "opportunity_score",
      OPPORTUNITY_SCORE_WEIGHT: "opportunity_score_weight",
      OWNER: "owner",
      PAGES_IN_AUTHORIZATIONS: "pages_in_authorizations",
      PARTNER: "partner",
      PAYMENT_OPTIONS: "payment_options",
      PENDING_BILLING_DATE_PREFERENCE: "pending_billing_date_preference",
      PLACEMENT_USAGE: "placement_usage",
      PREPAY_ACCOUNT_BALANCE: "prepay_account_balance",
      PREPAY_DETAILS: "prepay_details",
      PROMOTION_PROGRESS_BAR_INFO: "promotion_progress_bar_info",
      REACHESTIMATE: "reachestimate",
      RF_SPEC: "rf_spec",
      RUN_STUDY_WINNERS: "run_study_winners",
      SEGMENT: "segment",
      SALES_SEGMENT_V2: "sales_segment_v2",
      SAVED_AUDIENCES: "saved_audiences",
      SELF_RESOLVE_URI: "self_resolve_uri",
      SEND_BILL_TO_ADDRESS: "send_bill_to_address",
      SEND_BILL_TO_ADDRESSES: "send_bill_to_addresses",
      SOLD_TO_ADDRESS: "sold_to_address",
      SOLD_TO_ADDRESSES: "sold_to_addresses",
      SOLD_TO_ORG: "sold_to_org",
      SHOW_CHECKOUT_EXPERIENCE: "show_checkout_experience",
      SHOW_IMPROVED_BOLETO: "show_improved_boleto",
      SHOW_SAC_CAMPAIGN_GROUP_INPUT: "show_sac_campaign_group_input",
      SOCIAL_SETTING_ENROLL_STATUS: "social_setting_enroll_status",
      SPEND_CAP: "spend_cap",
      SPEND_LIMITS: "spendlimits",
      STATS: "stats",
      STORED_BALANCE_STATUS: "stored_balance_status",
      SUBSIDY_AMOUNT_DETAILS: "subsidy_amount_details",
      SUGGESTED_CAMPAIGN_BUDGET: "suggested_campaign_budget",
      TAX_COUNTRY: "tax_country",
      TAX_ID: "tax_id",
      TAX_ID_STATUS: "tax_id_status",
      TAX_ID_TYPE: "tax_id_type",
      TIMEZONE_ID: "timezone_id",
      TIMEZONE_NAME: "timezone_name",
      TIMEZONE_OFFSET_HOURS_UTC: "timezone_offset_hours_utc",
      TOS_ACCEPTED: "tos_accepted",
      USER_TOS_ACCEPTED: "user_tos_accepted",
      TOTAL_PREPAY_BALANCE: "total_prepay_balance",
      TRANSACTIONS: "transactions",
      UNIQUE_ADCREATIVES: "unique_adcreatives",
      AUDIENCE_UPDATE_QUOTA_LEFT: "audience_update_quota_left",
      USER_ACCESS_EXPIRE_TIME: "user_access_expire_time",
      USER_ROLE: "user_role",
      USER_TASKS: "user_tasks",
      USER_SETTINGS: "user_settings",
      USERPERMISSIONS: "userpermissions",
      USERS: "users",
      VERTICAL_ID: "vertical_id",
      VERTICAL_NAME: "vertical_name",
      VIEWABLE_BUSINESS: "viewable_business",
      VIEWABLE_BUSINESSES: "viewable_businesses",
      WEBSITE_CREATIVE_ASSETS: "website_creative_assets",
      SITE_LINKS: "site_links",
      SITE_LINKS_LIVE_CRAWL: "site_links_live_crawl",
      BLOCKED_PLACEMENTS: "blocked_placements",
      POLICY_RISK_LEVEL: "policy_risk_level",
      ADTRUST_DSL: "adtrust_dsl",
      IS_NEW_ADVERTISER: "is_new_advertiser",
      DYNAMIC_PROBATION_DSL: "dynamic_probation_dsl",
      CONVERSION_HEALTH_KPI: "conversion_health_kpi",
      BLOCK_LIST_USAGE: "block_list_usage",
      AUTHORIZED_COUNTRY_FOR_POLITICAL_ADS:
        "authorized_country_for_political_ads",
      PAGE_AUTHORIZED_COUNTRY_FOR_POLITICAL_ADS:
        "page_authorized_country_for_political_ads",
      ADVANCED_MATCHING_KPI: "advanced_matching_kpi",
      IS_BUSINESS_VERIFICATION_ELIGIBLE: "is_business_verification_eligible",
      BRAND_SAFETY_CONTENT_FILTER_LEVELS: "brand_safety_content_filter_levels",
      BRAND_SAFETY_INHERITED_CONTENT_FILTER_LEVELS:
        "brand_safety_inherited_content_filter_levels",
      BRAND_SAFETY_EXCLUDED_TOPICS: "brand_safety_excluded_topics",
      BUSINESS_RESTRICTION_REASON: "business_restriction_reason",
      IS_BUSINESS_ALLOWED_TO_ADVERTISE: "is_business_allowed_to_advertise",
      IS_USER_ALLOWED_TO_ADVERTISE: "is_user_allowed_to_advertise",
      AM_ONESHOP_SETTINGS: "am_oneshop_settings",
      MODELED_REPORTING_TYPE: "modeled_reporting_type",
      OWNER_BUSINESS: "owner_business",
      ASSET_SCORE: "asset_score",
      AUTH_FLOW_FOR_TRUST_TIER_STATE: "auth_flow_for_trust_tier_state",
      EXISTING_CUSTOMERS: "existing_customers",
      ODAX_OPT_IN: "odax_opt_in",
      HAS_ACTIVE_SKAN_CAMPAIGN_GROUPS: "has_active_skan_campaign_groups",
      CUSTOM_AUDIENCE_INFO: "custom_audience_info",
      CTWA_SMB_ENFORCING_DAYS_LEFT: "ctwa_smb_enforcing_days_left",
      PROMOTION_METADATA: "promotion_metadata",
      PROMOTION_METADATA_LIVE_CRAWL: "promotion_metadata_live_crawl",
      IS_RETAIL_MEDIA_NETWORK: "is_retail_media_network",
      CTX_FLEXIBLE_FORMAT_TARGETING: "ctx_flexible_format_targeting",
      ADS_PAUSED: "ads_paused",
      AMOUNT_SPENT_HISTORY: "amount_spent_history",
      SPEND_CAP_HISTORY: "spend_cap_history",
      IS_VALUE_RULES_SMART_DEFAULT_ON: "is_value_rules_smart_default_on",
    });
    i.default = e;
  },
  66,
);
