__d(
  "AdsAdditionalOptionsConsts",
  ["immutable", "keyMirror"],
  function (t, n, r, o, a, i, l) {
    "use strict";
    var e,
      s = (e = r("keyMirror"))({
        adgroupAdFormat: null,
        adgroupCallToAction: null,
        adgroupConnectedSourcesCatalog: null,
        adgroupMarketingMessageCarouselCardsEditor: null,
        adgroupOmnichannelDestinationSelector: null,
        adgroupWTWAFirstMessageTemplateEditor: null,
        adgroupWebsiteExtensions: null,
      }),
      u = e({
        campaignGroupBidStrategy: null,
        campaignGroupBudgetScaling: null,
        campaignGroupBudgetStrategy: null,
        campaignGroupBuyingType: null,
        campaignGroupCatalog: null,
        campaignGroupDeliveryType: null,
        campaignGroupObjective: null,
        campaignGroupRegulatedCategory: null,
        campaignGroupScheduling: null,
        campaignGroupSpendLimits: null,
        campaignGroupTimeSuggestion: null,
      }),
      c = e({
        adBreaksExclusion: null,
        advantagePlusPlacements: null,
        age: null,
        appStore: null,
        attributionCountType: null,
        promotedApp: null,
        minAge: null,
        ageSuggestion: null,
        appAttributionWindow: null,
        audience: null,
        audienceExclusionF1: null,
        audienceInclusionF1: null,
        audienceSectionF2: null,
        audienceSuggestionsSection: null,
        messageMarketingAudience: null,
        messengerMarketingMessageAudience: null,
        bidStrategy: null,
        billingEvent: null,
        blcMsaBudgetControl: null,
        blockList: null,
        brandSafety: null,
        brandSafetyAudienceNetworkFilter: null,
        brandSafetyBlockLists: null,
        brandSafetyCommentsOnAds: null,
        brandSafetyContentFilter: null,
        brandSafetyContentTypeExclusion: null,
        brandSafetyFeedInventoryFilter: null,
        brandSafetyInContentFilter: null,
        brandSafetyMaturityRatingExclusions: null,
        brandSafetyNegativeKeywords: null,
        brandSafetyTopicExclusions: null,
        budgetBidding: null,
        caapAUFinserv: null,
        caapINFinserv: null,
        caapSGUniversal: null,
        caapUniversal: null,
        caapTWFinserv: null,
        caapTWUniversal: null,
        campaignAttribution: null,
        campaignAttributionType: null,
        campaignBudgetEndDate: null,
        campaignBudgetScaling: null,
        conversionLocation: null,
        conversionWindow: null,
        conversionWindowFunnel: null,
        dailyBudgetScheduling: null,
        deliveryType: null,
        detailedTargeting: null,
        deviceAndOS: null,
        deviceType: null,
        exclusions: null,
        experimentalLanguages: null,
        excludeAudiencesGoal: null,
        excludeEngagedAudiencesGoal: null,
        excludeCatalogueInteractionsF1: null,
        frequencyControlInterval: null,
        gender: null,
        infoNeededFromLeads: null,
        installState: null,
        installStateF1: null,
        installStateF2: null,
        languages: null,
        locations: null,
        lookalikeInclusionsGoal: null,
        existingCustomersInclusionsGoal: null,
        messageMarketingBillingEvent: null,
        messageMarketingConversionWindow: null,
        optimizationGoal: null,
        optimizationGoalPGD: null,
        placementAutoManual: null,
        placementControls: null,
        placementDeviceAndOS: null,
        placementPlatforms: null,
        reelsPlacementControls: null,
        reelsPlacementDeviceAndOS: null,
        reelsPlacementPlatforms: null,
        reservationAgeTargeting: null,
        reservationBidStrategySummaryF2: null,
        reservationCampaignDurationSummaryF2: null,
        reservationDeliveryTypeSummaryF2: null,
        reservationDetailedTargeting: null,
        reservationFrequencyControl: null,
        reservationGenderTargeting: null,
        reservationGetChargedSummaryF2: null,
        reservationLanguagesTargeting: null,
        reservationLocationsTargeting: null,
        reservationScheduling: null,
        scheduling: null,
        seamlessASPAudience: null,
        seamlessASPPlacements: null,
        seamlessASPPlacementsDetailed: null,
        searchThemes: null,
        sequencedConversionWindow: null,
        skippableAdsExclusion: null,
        spendControls: null,
        timeSuggestion: null,
        appInstallState: null,
        valueAdjustmentRule: null,
        dfcaDataSource: null,
        valueAdjustmentRuleFederatedPlacement3B: null,
        valueAdjustmentRuleFederatedChannel3B: null,
        valueAdjustmentRuleFederatedAudience: null,
        valueRulesGoal: null,
        engagedAudiencesInclusionsGoal: null,
        goalSectionF2: null,
      }),
      d = { ADGROUP: s, CAMPAIGN_GROUP: u, CAMPAIGN: c },
      m = e({ F0: null, F1: null, F2: null }),
      p = e({
        audienceSectionF2: null,
        goalSectionF2: null,
        audienceSuggestionsSection: null,
        alwaysVisibie: null,
        automaticPlacement: null,
        brandSafety: null,
        budget: null,
        budgetAndDelivery: null,
        campaignGroupBudget: null,
        conversion: null,
        delivery: null,
        invisible: null,
        asaReportingAudienceSettings: null,
        peCampaignGroupDetails: null,
        placement: null,
        targeting: null,
        progressiveDisclosurePlacement: null,
      }),
      _ = r("immutable")
        .Map(babelHelpers.extends({}, s, u, c))
        .map(function (e) {
          return { isEditable: !1, isSticky: !1, hasEdited: !1 };
        });
    ((l.AdditionalOptions = d),
      (l.AdditionalOptionsFrictionLevels = m),
      (l.AdditionalOptionsSections = p),
      (l.AdditionalOptionsDataProviderInitialState = _));
  },
  98,
);
