__d(
  "AdsAccountStoreNewSourceServerQuery.graphql",
  [
    "AdAccount-ad_object_spec-resolver",
    "AdAccountCheapFields.relayprovider",
    "perseusL4IsPlacementSoftOptOutEnabled.relayprovider",
    "AdAccountLazyBudgetAverages.relayprovider",
    "AdsManagerBetaGating.relayprovider",
    "relay-runtime",
  ],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = (function () {
      var e = {
          defaultValue: null,
          kind: "LocalArgument",
          name: "adAccountID",
        },
        t = [
          {
            kind: "Variable",
            name: "legacy_account_id",
            variableName: "adAccountID",
          },
        ],
        r = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "id",
          storageKey: null,
        },
        o = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "name",
          storageKey: null,
        },
        a = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "status",
          storageKey: null,
        },
        i = [
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "amount_with_offset",
            storageKey: null,
          },
        ],
        l = [
          o,
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "version",
            storageKey: null,
          },
        ],
        s = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "role",
          storageKey: null,
        },
        u = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "tasks",
          storageKey: null,
        },
        c = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "page_id",
          storageKey: null,
        },
        d = [
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "event_type",
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "window_days",
            storageKey: null,
          },
        ],
        m = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "country_code",
          storageKey: null,
        },
        p = [
          m,
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "value",
            storageKey: null,
          },
        ],
        _ = [r];
      return {
        fragment: {
          argumentDefinitions: [e],
          kind: "Fragment",
          metadata: null,
          name: "AdsAccountStoreNewSourceServerQuery",
          selections: [
            {
              alias: null,
              args: t,
              concreteType: "AdAccount",
              kind: "LinkedField",
              name: "ad_account",
              plural: !1,
              selections: [
                r,
                {
                  alias: null,
                  args: null,
                  fragment: {
                    args: null,
                    kind: "FragmentSpread",
                    name: "AdAccountAdObjectSpecResolver",
                  },
                  kind: "RelayResolver",
                  name: "adaccount_spec",
                  resolverModule: n("AdAccount-ad_object_spec-resolver")
                    .adaccount_spec,
                  path: "ad_account.adaccount_spec",
                },
              ],
              storageKey: null,
            },
          ],
          type: "Query",
          abstractKey: null,
        },
        kind: "Request",
        operation: {
          argumentDefinitions: [
            e,
            {
              defaultValue: null,
              kind: "LocalArgument",
              name: "__relay_internal__pv__AdAccountCheapFieldsrelayprovider",
            },
            {
              defaultValue: null,
              kind: "LocalArgument",
              name: "__relay_internal__pv__perseusL4IsPlacementSoftOptOutEnabledrelayprovider",
            },
            {
              defaultValue: null,
              kind: "LocalArgument",
              name: "__relay_internal__pv__AdAccountLazyBudgetAveragesrelayprovider",
            },
            {
              defaultValue: null,
              kind: "LocalArgument",
              name: "__relay_internal__pv__AdsManagerBetaGatingrelayprovider",
            },
          ],
          kind: "Operation",
          name: "AdsAccountStoreNewSourceServerQuery",
          selections: [
            {
              alias: null,
              args: t,
              concreteType: "AdAccount",
              kind: "LinkedField",
              name: "ad_account",
              plural: !1,
              selections: [
                r,
                {
                  name: "adaccount_spec",
                  args: null,
                  fragment: {
                    kind: "InlineFragment",
                    selections: [
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "__typename",
                        storageKey: null,
                      },
                      r,
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "account_currency_ratio_to_usd",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "account_status",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        concreteType: "AdBusiness",
                        kind: "LinkedField",
                        name: "ads_business",
                        plural: !1,
                        selections: [
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "id_for_display",
                            storageKey: null,
                          },
                          o,
                          r,
                        ],
                        storageKey: null,
                      },
                      {
                        condition:
                          "__relay_internal__pv__AdsManagerBetaGatingrelayprovider",
                        kind: "Condition",
                        passingValue: !0,
                        selections: [
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "ads_manager_beta_ai_recap_visible",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "ads_manager_beta_enrollment_status",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "ads_manager_beta_has_opted_out",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "ads_manager_beta_universal_composer_visible",
                            storageKey: null,
                          },
                        ],
                      },
                      {
                        alias: null,
                        args: null,
                        concreteType: "AdAccountAgencyFeeConfig",
                        kind: "LinkedField",
                        name: "agency_fee_config",
                        plural: !1,
                        selections: [
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "can_add_agency_fee_to_invoice",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "default_agency_fee_pct",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "is_agency_fee_disabled",
                            storageKey: null,
                          },
                          a,
                          r,
                        ],
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "business_country_code",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "business_verification_status",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "capabilities_legacy_slow",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "created_with_supported_timezone_offset",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "currency",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "is_new_advertiser",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "is_tier_restricted",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "legacy_account_id",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        concreteType: "CurrencyQuantity",
                        kind: "LinkedField",
                        name: "max_daily_budget",
                        plural: !1,
                        selections: i,
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "min_campaign_group_spend_cap",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        concreteType: "CurrencyQuantity",
                        kind: "LinkedField",
                        name: "min_daily_budget",
                        plural: !1,
                        selections: i,
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "min_live_boosting_budget",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "moo_default_conversion_bid",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "modeled_reporting_type",
                        storageKey: null,
                      },
                      o,
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "show_sac_campaign_group_input",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "tax_country",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        concreteType: "TimezoneInfo",
                        kind: "LinkedField",
                        name: "timezone_info",
                        plural: !1,
                        selections: [
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "timezone_id",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "timezone",
                            storageKey: null,
                          },
                        ],
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "timezone_offset_hours_utc",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        concreteType: "AdAccountTOSNameAndVersion",
                        kind: "LinkedField",
                        name: "tos_accepted",
                        plural: !0,
                        selections: l,
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "trust_tier",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "offsite_clo_signal_status",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "offsite_clo_crm_integration_status",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        concreteType: "XFBAdAccountUserPermissionsSpec",
                        kind: "LinkedField",
                        name: "user_permissions",
                        plural: !0,
                        selections: [
                          {
                            alias: null,
                            args: null,
                            concreteType: "User",
                            kind: "LinkedField",
                            name: "user",
                            plural: !1,
                            selections: [r, o],
                            storageKey: null,
                          },
                          s,
                          u,
                        ],
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        concreteType: "AdAccountTOSNameAndVersion",
                        kind: "LinkedField",
                        name: "user_tos_accepted",
                        plural: !0,
                        selections: l,
                        storageKey: null,
                      },
                      {
                        condition:
                          "__relay_internal__pv__AdAccountCheapFieldsrelayprovider",
                        kind: "Condition",
                        passingValue: !1,
                        selections: [
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "account_disabled_reason",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "adtrust_dsl",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "advertiser_size",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            concreteType:
                              "XFBAdvertiserVerificationStatusNodeData",
                            kind: "LinkedField",
                            name: "advertiser_verification_status",
                            plural: !1,
                            selections: [
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "banner_type",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "grace_period_ends_at",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "ufac_redirect_uri",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "verification_status",
                                storageKey: null,
                              },
                            ],
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "archived_adgroup_count",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "archived_campaign_count",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "archived_campaign_group_count",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            concreteType: "XFBMarketingMessagesAccountSettings",
                            kind: "LinkedField",
                            name: "marketing_messages_account_settings",
                            plural: !1,
                            selections: [
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "messenger_activation_status",
                                storageKey: null,
                              },
                              r,
                            ],
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "attr_window_deprecation_group",
                            storageKey: null,
                          },
                          {
                            condition:
                              "__relay_internal__pv__AdAccountLazyBudgetAveragesrelayprovider",
                            kind: "Condition",
                            passingValue: !1,
                            selections: [
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "average_campaign_daily_budget",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "average_campaign_group_daily_budget",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "average_campaign_group_lifetime_budget",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "average_campaign_lifetime_budget",
                                storageKey: null,
                              },
                            ],
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "brand_safety_excluded_topics",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "brand_safety_content_filter_levels",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "business_restriction_reason",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "can_bypass_funding_source",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "ctwa_smb_enforcing_days_left",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "call_ads_ad_account_similar_advertiser_budget_recommendation",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "ctx_advertiser_sabr_lifetime_duration_recommendation",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            concreteType: "XFBCTXDFOObjectiveDefaults",
                            kind: "LinkedField",
                            name: "ctx_dfo_objective_defaults",
                            plural: !1,
                            selections: [
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "objective",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "optimization_goal",
                                storageKey: null,
                              },
                              c,
                            ],
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "ctx_flexible_format_targeting",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "default_dsa_beneficiary",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "default_dsa_payor",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            concreteType: "ApiAttributionEventSpecClosedShape",
                            kind: "LinkedField",
                            name: "default_unified_attribution_spec",
                            plural: !0,
                            selections: d,
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            concreteType: "ApiAttributionEventSpecClosedShape",
                            kind: "LinkedField",
                            name: "passback_attribution_spec",
                            plural: !0,
                            selections: d,
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "dynamic_probation_dsl",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "end_advertiser_name",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "flex_single_objective",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "funding_source_id",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "has_purchase_optimization_eligible_page",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "has_value_rule_set",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "if_viewer_has_permission_to_advertise",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            concreteType: "AdAccountRelatedIcoStudySpec",
                            kind: "LinkedField",
                            name: "incremental_conversion_optimization_ad_studies",
                            plural: !0,
                            selections: [
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "ad_study_end_time",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "ad_study_id",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "ad_study_name",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "ad_study_start_time",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "ad_study_status",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                concreteType:
                                  "AdAccountRelatedIcoStudyCellSpec",
                                kind: "LinkedField",
                                name: "cells",
                                plural: !0,
                                selections: [
                                  {
                                    alias: null,
                                    args: null,
                                    kind: "ScalarField",
                                    name: "cell_id",
                                    storageKey: null,
                                  },
                                  {
                                    alias: null,
                                    args: null,
                                    kind: "ScalarField",
                                    name: "cell_name",
                                    storageKey: null,
                                  },
                                ],
                                storageKey: null,
                              },
                            ],
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "io_number",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "is_attribution_spec_system_default",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "is_ba_skip_delayed_eligible",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "is_biz_migration_eligible",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "is_business_allowed_to_advertise",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "is_business_verification_eligible",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "is_expanded_shopless_awpt_eligible",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "is_mi_billing_info_updated",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "is_omnichannel_campaign_eligible",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "is_mm_lite_api_enabled",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "is_wa_lightweight_business",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "is_pageless_ctwa_eligible",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "is_pending_numbers_exposure_flag_enabled",
                            storageKey: null,
                          },
                          {
                            condition:
                              "__relay_internal__pv__perseusL4IsPlacementSoftOptOutEnabledrelayprovider",
                            kind: "Condition",
                            passingValue: !1,
                            selections: [
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "is_placement_soft_opt_out_enabled",
                                storageKey: null,
                              },
                            ],
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "is_shopless_awpt_eligible",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "is_prepay_account",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "is_closed_by_advertiser_compromise_bot",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "is_self_report_eligible",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "is_simplified_creation_segment_eligible",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "is_tax_id_required",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "is_user_allowed_to_advertise",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "is_value_rules_smart_default_on",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: [
                              {
                                kind: "Literal",
                                name: "upsell_type",
                                value: "TURN_OFF_CONFIRMATION_UPSELL",
                              },
                            ],
                            kind: "ScalarField",
                            name: "is_eligible_for_ads_budgets_l2_flex_upsell",
                            storageKey:
                              'is_eligible_for_ads_budgets_l2_flex_upsell(upsell_type:"TURN_OFF_CONFIRMATION_UPSELL")',
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "is_du_flex_defaulting_opt_out_enabled",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "is_youth_ads_pao_basic_advertiser",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "is_youth_ads_pao_basic_advertiser_announcement_eligible",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "is_eligible_for_advantage_plus_creative_regulated_category",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "line_numbers",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            concreteType: "AccountLiveVideoAdvertiserDetails",
                            kind: "LinkedField",
                            name: "live_video_advertiser_details",
                            plural: !1,
                            selections: [
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "is_lva_toggle_on",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "should_show_lva_toggle",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "lva_default_budget",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "should_default_current_live",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "should_default_scheduled_live",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "lva_default_duration_s",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "ig_lva_default_duration_s",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "should_default_toggle_on_from_model",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "is_slva_pa_enabled",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                concreteType: "IGLVARecommendedBudget",
                                kind: "LinkedField",
                                name: "ig_lva_recommended_lifetime_budget",
                                plural: !1,
                                selections: [
                                  {
                                    alias: null,
                                    args: null,
                                    kind: "ScalarField",
                                    name: "amount",
                                    storageKey: null,
                                  },
                                  {
                                    alias: null,
                                    args: null,
                                    kind: "ScalarField",
                                    name: "source",
                                    storageKey: null,
                                  },
                                ],
                                storageKey: null,
                              },
                            ],
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "cpas_campaign_default_budget",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "cpas_campaign_group_default_budget",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            concreteType: "XFBPageAuthorizedCountry",
                            kind: "LinkedField",
                            name: "page_authorized_country_for_political_ads",
                            plural: !0,
                            selections: [m, c],
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            concreteType: "XFBPageInAuthorizations",
                            kind: "LinkedField",
                            name: "pages_in_authorizations",
                            plural: !0,
                            selections: [
                              c,
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "page_name",
                                storageKey: null,
                              },
                            ],
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "political_ad_account_authorized_country",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "purchase_optimization_eligible_page_fbid",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            concreteType: "ReachFrequencySpec",
                            kind: "LinkedField",
                            name: "rf_spec",
                            plural: !1,
                            selections: [
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "countries",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "global_io_max_campaign_duration",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                concreteType: "ReachFrequencyCountrySpec",
                                kind: "LinkedField",
                                name: "max_campaign_duration",
                                plural: !0,
                                selections: p,
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                concreteType: "ReachFrequencyCountrySpec",
                                kind: "LinkedField",
                                name: "max_days_to_finish",
                                plural: !0,
                                selections: p,
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                concreteType: "ReachFrequencyPauseThresholds",
                                kind: "LinkedField",
                                name: "max_pause_without_prediction_rerun",
                                plural: !0,
                                selections: [
                                  m,
                                  {
                                    alias: null,
                                    args: null,
                                    concreteType:
                                      "ReachFrequencyPauseThreshold",
                                    kind: "LinkedField",
                                    name: "pause_threshold",
                                    plural: !0,
                                    selections: [
                                      {
                                        alias: null,
                                        args: null,
                                        kind: "ScalarField",
                                        name: "min_campaign_length",
                                        storageKey: null,
                                      },
                                      {
                                        alias: null,
                                        args: null,
                                        kind: "ScalarField",
                                        name: "min_time_after_pause",
                                        storageKey: null,
                                      },
                                      {
                                        alias: null,
                                        args: null,
                                        kind: "ScalarField",
                                        name: "pause_minutes",
                                        storageKey: null,
                                      },
                                    ],
                                    storageKey: null,
                                  },
                                ],
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                concreteType: "ReachFrequencyCountrySpec",
                                kind: "LinkedField",
                                name: "min_campaign_duration",
                                plural: !0,
                                selections: p,
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                concreteType: "ReachFrequencyCountrySpec",
                                kind: "LinkedField",
                                name: "min_reach_limits",
                                plural: !0,
                                selections: p,
                                storageKey: null,
                              },
                            ],
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "self_resolve_uri",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "sales_segment_v2",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            concreteType: "XFBAdsValueAdjustmentRuleCollection",
                            kind: "LinkedField",
                            name: "preferred_value_rule_collection",
                            plural: !1,
                            selections: _,
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            concreteType: "XFBAdsValueRulesSpec",
                            kind: "LinkedField",
                            name: "value_rules_placement_suggested_spec",
                            plural: !1,
                            selections: [
                              {
                                alias: null,
                                args: null,
                                concreteType: "ValueAdjustmentRuleCollection",
                                kind: "LinkedField",
                                name: "value_rule_set",
                                plural: !1,
                                selections: [
                                  r,
                                  {
                                    alias: null,
                                    args: null,
                                    kind: "ScalarField",
                                    name: "value_rule_set_id",
                                    storageKey: null,
                                  },
                                  o,
                                  {
                                    alias: null,
                                    args: null,
                                    concreteType: "ValueAdjustmentRulePersona",
                                    kind: "LinkedField",
                                    name: "rules",
                                    plural: !0,
                                    selections: [
                                      r,
                                      o,
                                      {
                                        alias: null,
                                        args: null,
                                        kind: "ScalarField",
                                        name: "adjust_sign",
                                        storageKey: null,
                                      },
                                      {
                                        alias: null,
                                        args: null,
                                        kind: "ScalarField",
                                        name: "adjust_value",
                                        storageKey: null,
                                      },
                                      {
                                        alias: null,
                                        args: null,
                                        concreteType:
                                          "ValueAdjustmentRulePersonaCriteria",
                                        kind: "LinkedField",
                                        name: "criterias",
                                        plural: !0,
                                        selections: [
                                          r,
                                          {
                                            alias: null,
                                            args: null,
                                            kind: "ScalarField",
                                            name: "criteria_type",
                                            storageKey: null,
                                          },
                                          {
                                            alias: null,
                                            args: null,
                                            kind: "ScalarField",
                                            name: "operator",
                                            storageKey: null,
                                          },
                                          {
                                            alias: null,
                                            args: null,
                                            kind: "ScalarField",
                                            name: "criteria_values",
                                            storageKey: null,
                                          },
                                          {
                                            alias: null,
                                            args: null,
                                            kind: "ScalarField",
                                            name: "criteria_value_types",
                                            storageKey: null,
                                          },
                                        ],
                                        storageKey: null,
                                      },
                                    ],
                                    storageKey: null,
                                  },
                                  {
                                    alias: null,
                                    args: null,
                                    kind: "ScalarField",
                                    name: "is_default_setting",
                                    storageKey: null,
                                  },
                                  {
                                    alias: null,
                                    args: null,
                                    kind: "ScalarField",
                                    name: "product_type",
                                    storageKey: null,
                                  },
                                  a,
                                ],
                                storageKey: null,
                              },
                            ],
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            concreteType: "AdAccountUserSetting",
                            kind: "LinkedField",
                            name: "user_settings_without_update",
                            plural: !1,
                            selections: _,
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            concreteType: "PermittedAdAccountUser",
                            kind: "LinkedField",
                            name: "permitted_ad_account_users",
                            plural: !0,
                            selections: [
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "user_id",
                                storageKey: null,
                              },
                              o,
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "permissions",
                                storageKey: null,
                              },
                              s,
                              u,
                              r,
                            ],
                            storageKey: null,
                          },
                        ],
                      },
                    ],
                    type: "AdAccount",
                    abstractKey: null,
                  },
                  kind: "RelayResolver",
                  storageKey: null,
                  isOutputType: !0,
                },
              ],
              storageKey: null,
            },
          ],
        },
        params: {
          id: "28123458433974544",
          metadata: {},
          name: "AdsAccountStoreNewSourceServerQuery",
          operationKind: "query",
          text: null,
          providedVariables: {
            __relay_internal__pv__AdAccountCheapFieldsrelayprovider: n(
              "AdAccountCheapFields.relayprovider",
            ),
            __relay_internal__pv__perseusL4IsPlacementSoftOptOutEnabledrelayprovider:
              n("perseusL4IsPlacementSoftOptOutEnabled.relayprovider"),
            __relay_internal__pv__AdAccountLazyBudgetAveragesrelayprovider: n(
              "AdAccountLazyBudgetAverages.relayprovider",
            ),
            __relay_internal__pv__AdsManagerBetaGatingrelayprovider: n(
              "AdsManagerBetaGating.relayprovider",
            ),
          },
        },
      };
    })();
    (n("relay-runtime").PreloadableQueryRegistry.set(e.params.id, e),
      (a.exports = e));
  },
  null,
);
