__d(
  "AdsAPIObjectiveStringsStatic",
  ["fbt"],
  function (t, n, r, o, a, i, l) {
    a.exports = {
      result: {
        NONE: {
          name: null,
          nameAsAdjective: null,
          actionSingular: null,
          actionPlural: null,
        },
        OFFER_CLAIMS: {
          name: l._(/*BTDS*/ "Offer Claims"),
          nameAsAdjective: l._(/*BTDS*/ "Offer Claims"),
          actionSingular: null,
          actionPlural: null,
        },
        PAGE_LIKES: {
          name: l._(/*BTDS*/ "Page Likes"),
          nameAsAdjective: l._(/*BTDS*/ "Page Likes"),
          actionSingular: null,
          actionPlural: null,
        },
        CANVAS_APP_INSTALLS: {
          name: l._(/*BTDS*/ "App Installs (Desktop)"),
          nameAsAdjective: l._(/*BTDS*/ "App Installs (Desktop)"),
          actionSingular: null,
          actionPlural: null,
        },
        EVENT_RESPONSES: {
          name: l._(/*BTDS*/ "Event Responses"),
          nameAsAdjective: l._(/*BTDS*/ "Event Responses"),
          actionSingular: null,
          actionPlural: null,
        },
        CANVAS_APP_ENGAGEMENT: {
          name: l._(/*BTDS*/ "App Engagement (Desktop)"),
          nameAsAdjective: l._(/*BTDS*/ "App Engagement (Desktop)"),
          actionSingular: null,
          actionPlural: null,
        },
        POST_ENGAGEMENT: {
          name: l._(/*BTDS*/ "Engagement"),
          nameAsAdjective: l._(/*BTDS*/ "Page Post Engagement"),
          actionSingular: null,
          actionPlural: null,
        },
        WEBSITE_CONVERSIONS: {
          name: l._(/*BTDS*/ "Conversions"),
          nameAsAdjective: l._(/*BTDS*/ "Website Conversions"),
          actionSingular: null,
          actionPlural: null,
        },
        MOBILE_APP_INSTALLS: {
          name: l._(/*BTDS*/ "App Installs (Mobile)"),
          nameAsAdjective: l._(/*BTDS*/ "App Installs (Mobile)"),
          actionSingular: null,
          actionPlural: null,
        },
        LINK_CLICKS: {
          name: l._(/*BTDS*/ "Traffic"),
          nameAsAdjective: l._(/*BTDS*/ "Clicks to Website"),
          actionSingular: null,
          actionPlural: null,
        },
        MOBILE_APP_ENGAGEMENT: {
          name: l._(/*BTDS*/ "App Engagement (Mobile)"),
          nameAsAdjective: l._(/*BTDS*/ "App Engagement (Mobile)"),
          actionSingular: null,
          actionPlural: null,
        },
        VIDEO_VIEWS: {
          name: l._(/*BTDS*/ "Video Views"),
          nameAsAdjective: l._(/*BTDS*/ "Video Views"),
          actionSingular: null,
          actionPlural: null,
        },
        LOCAL_AWARENESS: {
          name: l._(/*BTDS*/ "Local Awareness"),
          nameAsAdjective: l._(/*BTDS*/ "Local Awareness"),
          actionSingular: l._(/*BTDS*/ "Local Awareness"),
          actionPlural: l._(/*BTDS*/ "Local Awareness"),
        },
        INSTAGRAM_BRAND_AWARENESS: {
          name: l._(/*BTDS*/ "Not Applicable"),
          nameAsAdjective: l._(/*BTDS*/ "Not Applicable"),
          actionSingular: l._(/*BTDS*/ "Not Applicable"),
          actionPlural: l._(/*BTDS*/ "Not Applicable"),
        },
        PRODUCT_CATALOG_SALES: {
          name: l._(/*BTDS*/ "Catalog Sales"),
          nameAsAdjective: l._(/*BTDS*/ "Product Catalog Sales"),
          actionSingular: null,
          actionPlural: null,
        },
        LEAD_GENERATION: {
          name: l._(/*BTDS*/ "Lead Generation"),
          nameAsAdjective: l._(/*BTDS*/ "Lead Generation"),
          actionSingular: null,
          actionPlural: null,
        },
        BRAND_AWARENESS: {
          name: l._(/*BTDS*/ "Brand Awareness"),
          nameAsAdjective: l._(/*BTDS*/ "Brand Awareness"),
          actionSingular: l._(/*BTDS*/ "Ad recall lift"),
          actionPlural: l._(/*BTDS*/ "Ad recall lift"),
        },
        RESEARCH_POLL: {
          name: l._(/*BTDS*/ "Research Poll"),
          nameAsAdjective: l._(/*BTDS*/ "Research Poll"),
          actionSingular: null,
          actionPlural: null,
        },
        EXTERNAL: {
          name: l._(/*BTDS*/ "Not Applicable"),
          nameAsAdjective: l._(/*BTDS*/ "Not Applicable"),
          actionSingular: null,
          actionPlural: null,
        },
        STORE_VISITS: {
          name: l._(/*BTDS*/ "Store Traffic"),
          nameAsAdjective: l._(/*BTDS*/ "Store Traffic"),
          actionSingular: null,
          actionPlural: null,
        },
        REACH: {
          name: l._(/*BTDS*/ "Reach"),
          nameAsAdjective: l._(/*BTDS*/ "Reach"),
          actionSingular: l._(/*BTDS*/ "Reach"),
          actionPlural: l._(/*BTDS*/ "Reach"),
        },
        APP_INSTALLS: {
          name: l._(/*BTDS*/ "App Installs"),
          nameAsAdjective: l._(/*BTDS*/ "App Installs"),
          actionSingular: null,
          actionPlural: null,
        },
        MESSAGES: {
          name: l._(/*BTDS*/ "Messages"),
          nameAsAdjective: l._(/*BTDS*/ "Messages"),
          actionSingular: null,
          actionPlural: null,
        },
        OUTCOME_ACQUISITION: {
          name: l._(/*BTDS*/ "Acquisition"),
          nameAsAdjective: l._(/*BTDS*/ "Acquisition"),
          actionSingular: null,
          actionPlural: null,
        },
        OUTCOME_AWARENESS: {
          name: l._(/*BTDS*/ "Awareness"),
          nameAsAdjective: l._(/*BTDS*/ "Awareness"),
          actionSingular: null,
          actionPlural: null,
        },
        OUTCOME_ENGAGEMENT: {
          name: l._(/*BTDS*/ "Engagement"),
          nameAsAdjective: l._(/*BTDS*/ "Engagement"),
          actionSingular: null,
          actionPlural: null,
        },
        OUTCOME_LEADS: {
          name: l._(/*BTDS*/ "Leads"),
          nameAsAdjective: l._(/*BTDS*/ "Leads"),
          actionSingular: null,
          actionPlural: null,
        },
        OUTCOME_SALES: {
          name: l._(/*BTDS*/ "Sales"),
          nameAsAdjective: l._(/*BTDS*/ "Sales"),
          actionSingular: null,
          actionPlural: null,
        },
        IMPRESSIONS: {
          name: l._(/*BTDS*/ "Impressions"),
          nameAsAdjective: l._(/*BTDS*/ "Impressions"),
          actionSingular: l._(/*BTDS*/ "Impression"),
          actionPlural: l._(/*BTDS*/ "Impressions"),
        },
        MILLE: {
          name: l._(/*BTDS*/ "1,000 Impressions"),
          nameAsAdjective: l._(/*BTDS*/ "1,000 Impressions"),
          actionSingular: l._(/*BTDS*/ "1,000 Impressions"),
          actionPlural: l._(/*BTDS*/ "1,000 Impressions"),
        },
        LOCAL_IMPRESSIONS: {
          name: l._(/*BTDS*/ "Local Impressions"),
          nameAsAdjective: l._(/*BTDS*/ "Local Impressions"),
          actionSingular: l._(/*BTDS*/ "Local Impressions"),
          actionPlural: l._(/*BTDS*/ "Local Impressions"),
        },
        MULTIPLE: {
          name: l._(/*BTDS*/ "Multiple"),
          nameAsAdjective: l._(/*BTDS*/ "Multiple"),
          actionSingular: l._(/*BTDS*/ "Multiple"),
          actionPlural: l._(/*BTDS*/ "Multiple"),
        },
        DEPRECATED_CLICKS: {
          name: l._(/*BTDS*/ "Not Applicable"),
          nameAsAdjective: l._(/*BTDS*/ "Not Applicable"),
          actionSingular: l._(/*BTDS*/ "Click"),
          actionPlural: l._(/*BTDS*/ "Clicks"),
        },
        INCOMPATIBLE_OFFER_CLAIMS: {
          name: l._(/*BTDS*/ "Not Applicable"),
          nameAsAdjective: l._(/*BTDS*/ "Not Applicable"),
          actionSingular: null,
          actionPlural: null,
        },
        INCOMPATIBLE_PAGE_LIKES: {
          name: l._(/*BTDS*/ "Not Applicable"),
          nameAsAdjective: l._(/*BTDS*/ "Not Applicable"),
          actionSingular: null,
          actionPlural: null,
        },
        INCOMPATIBLE_CANVAS_APP_INSTALLS: {
          name: l._(/*BTDS*/ "Not Applicable"),
          nameAsAdjective: l._(/*BTDS*/ "Not Applicable"),
          actionSingular: null,
          actionPlural: null,
        },
        INCOMPATIBLE_EVENT_RESPONSES: {
          name: l._(/*BTDS*/ "Not Applicable"),
          nameAsAdjective: l._(/*BTDS*/ "Not Applicable"),
          actionSingular: null,
          actionPlural: null,
        },
        INCOMPATIBLE_CANVAS_APP_ENGAGEMENT: {
          name: l._(/*BTDS*/ "Not Applicable"),
          nameAsAdjective: l._(/*BTDS*/ "Not Applicable"),
          actionSingular: null,
          actionPlural: null,
        },
        INCOMPATIBLE_POST_ENGAGEMENT: {
          name: l._(/*BTDS*/ "Not Applicable"),
          nameAsAdjective: l._(/*BTDS*/ "Not Applicable"),
          actionSingular: null,
          actionPlural: null,
        },
        INCOMPATIBLE_WEBSITE_CONVERSIONS: {
          name: l._(/*BTDS*/ "Not Applicable"),
          nameAsAdjective: l._(/*BTDS*/ "Not Applicable"),
          actionSingular: null,
          actionPlural: null,
        },
        INCOMPATIBLE_MOBILE_APP_INSTALLS: {
          name: l._(/*BTDS*/ "Not Applicable"),
          nameAsAdjective: l._(/*BTDS*/ "Not Applicable"),
          actionSingular: null,
          actionPlural: null,
        },
        INCOMPATIBLE_WEBSITE_CLICKS: {
          name: l._(/*BTDS*/ "Not Applicable"),
          nameAsAdjective: l._(/*BTDS*/ "Not Applicable"),
          actionSingular: l._(/*BTDS*/ "Click"),
          actionPlural: l._(/*BTDS*/ "Clicks"),
        },
        INCOMPATIBLE_PAGE_ENGAGEMENT: {
          name: l._(/*BTDS*/ "Not Applicable"),
          nameAsAdjective: l._(/*BTDS*/ "Not Applicable"),
          actionSingular: null,
          actionPlural: null,
        },
        WILDCARD_INTERNAL_ONLY: {
          name: null,
          nameAsAdjective: null,
          actionSingular: null,
          actionPlural: null,
        },
        PROFILE_FOLLOWERS: {
          name: null,
          nameAsAdjective: null,
          actionSingular: null,
          actionPlural: null,
        },
        GROUP_JOINS: {
          name: null,
          nameAsAdjective: null,
          actionSingular: null,
          actionPlural: null,
        },
        OUTCOME_TRAFFIC: {
          name: l._(/*BTDS*/ "Traffic"),
          nameAsAdjective: l._(/*BTDS*/ "Traffic"),
          actionSingular: null,
          actionPlural: null,
        },
        OUTCOME_APP_PROMOTION: {
          name: null,
          nameAsAdjective: null,
          actionSingular: null,
          actionPlural: null,
        },
        MEDIA_DOWNLOADS: {
          name: null,
          nameAsAdjective: null,
          actionSingular: null,
          actionPlural: null,
        },
        XPLATFORM_SALES: {
          name: null,
          nameAsAdjective: null,
          actionSingular: null,
          actionPlural: null,
        },
        CONVERSIONS: {
          name: l._(/*BTDS*/ "Conversions"),
          nameAsAdjective: l._(/*BTDS*/ "Website Conversions"),
          actionSingular: null,
          actionPlural: null,
        },
      },
    };
  },
  130,
);
