__d(
  "AdsAutoGeneratedCaptionCaptionsRegenerateCaptionDataReducerPlugin",
  [],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = {
        reduce: function (t, n) {
          return t.setIn(["captionDataByVideoID", n.videoID, "isFetched"], !1);
        },
      },
      l = e;
    i.default = l;
  },
  66,
);
