__d(
  "AdsAssetCustomizationCarouselEligibility",
  [],
  function (t, n, r, o, a, i) {
    var e = Object.freeze({
      OBJECTIVES: [
        "BRAND_AWARENESS",
        "REACH",
        "LINK_CLICKS",
        "APP_INSTALLS",
        "VIDEO_VIEWS",
        "LEAD_GENERATION",
        "WILDCARD_INTERNAL_ONLY",
        "CONVERSIONS",
        "POST_ENGAGEMENT",
        "MESSAGES",
        "OUTCOME_ENGAGEMENT",
        "OUTCOME_LEADS",
        "OUTCOME_SALES",
        "OUTCOME_AWARENESS",
      ],
      PROMOTED_OBJECTS: [
        "NONE",
        "OFFLINE_EVENT_SET",
        "PIXEL",
        "WEBSITE",
        "MOBILE_APP",
        "MESSENGER",
        "WHATSAPP",
        "ON_AD",
        "INSTAGRAM",
        "POST",
        "REMINDER",
        "VIDEO",
      ],
      PUBLISHER_PLATFORMS: [
        "facebook",
        "instagram",
        "audience_network",
        "messenger",
        "oculus",
        "whatsapp",
        "threads",
      ],
      DEVICE_PLATFORMS: ["desktop", "mobile"],
      FACEBOOK_POSITIONS: [
        "facebook_reels",
        "feed",
        "instant_article",
        "instream_video",
        "marketplace",
        "right_hand_column",
        "search",
        "story",
        "profile_feed",
      ],
      INSTAGRAM_POSITIONS: [
        "stream",
        "story",
        "explore",
        "explore_home",
        "ig_search",
        "reels",
        "profile_feed",
      ],
      MESSENGER_POSITIONS: ["messenger_home"],
      OCULUS_POSITIONS: [],
      AUDIENCE_NETWORK_POSITIONS: ["classic"],
      WHATSAPP_POSITIONS: ["status", "marketing_messages"],
    });
    i.default = e;
  },
  66,
);
