__d(
  "AdsAutoGeneratedCaptionSetNuxStatusDataReducerPlugin",
  [],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = {
        reduce: function (t, n) {
          return t.merge({
            showEditorNUX: n.payload && n.payload.showEditorNUX,
          });
        },
      },
      l = e;
    i.default = l;
  },
  66,
);
