__d(
  "AdsAutoGeneratedCaptionDataManager",
  [
    "AdsAutoCaptionConfig.experimental",
    "AdsAutoGeneratedCaptionCaptionsFetchDataAction",
    "AdsAutoGeneratedCaptionCaptionsFetchFinishedDataAction",
    "AdsAutoGeneratedCaptionCaptionsRegenerateCaptionDataAction",
    "AdsAutoGeneratedCaptionCaptionsSetDataAction",
    "AdsAutoGeneratedCaptionCaptionsShareEditDataAction",
    "AdsAutoGeneratedCaptionSetNewVideoDataAction",
    "AdsAutoGeneratedCaptionSetNuxStatusDataAction",
    "AdsAutoGeneratedCaptionUtils",
    "AdsAutogenerationCaptionStatus",
    "AdsGraphAPI",
    "AdsPerfInteractionsController",
    "AdsVideoCaptionCaptionHideAutoDataAction",
    "AdsVideoCaptionCaptionLoggingDataAction",
    "AdsVideoCaptionCaptionSetDataAction",
    "AsyncRequest",
    "AsyncResponse",
    "GraphAPIPolling",
    "ThisControllerNoLongerExists",
    "VideoSubtitleStatusType",
    "WebApiApplication",
    "XVideoCaptionDownloadAsyncControllerRouteBuilder",
    "XVideoCaptionEditorAdsNUXController",
    "XVideoCaptionGenerateAsyncControllerRouteBuilder",
    "XVideoCaptionPublishAsyncControllerRouteBuilder",
    "XVideoCaptionShareAsyncControllerRouteBuilder",
    "XVideoUnPublishCaptionAsyncControllerRouteBuilder",
    "adsManagerDefaultErrorHandler",
    "promiseDone",
  ],
  function (t, n, r, o, a, i, l) {
    "use strict";
    var e = !1;
    function s(e, t) {
      var n = r("XVideoCaptionDownloadAsyncControllerRouteBuilder").buildUri({
        caption_id: t,
      });
      new (r("AsyncRequest"))()
        .setMethod("POST")
        .setHandler(function (n) {
          var a = "",
            l = "";
          (n.payload && ((a = n.payload.file), (l = n.payload.locale)),
            o("AdsAutoGeneratedCaptionUtils").downloadCaptionFile(a, t, l)
              ? r("AdsVideoCaptionCaptionLoggingDataAction").dispatch(
                  {
                    event: "download_success",
                    videoID: e,
                    captionID: t,
                    message: null,
                  },
                  {
                    line: "75",
                    module: "AdsAutoGeneratedCaptionDataManager.js",
                    moduleID: i.id,
                  },
                )
              : r("AdsVideoCaptionCaptionLoggingDataAction").dispatch(
                  {
                    event: "download_error",
                    videoID: e,
                    captionID: t,
                    message: null,
                  },
                  {
                    line: "82",
                    module: "AdsAutoGeneratedCaptionDataManager.js",
                    moduleID: i.id,
                  },
                ));
        })
        .setErrorHandler(function (n) {
          (r("AsyncResponse").defaultErrorHandler(n),
            r("AdsVideoCaptionCaptionLoggingDataAction").dispatch(
              {
                event: "download_error",
                videoID: e,
                captionID: t,
                message: null,
              },
              {
                line: "93",
                module: "AdsAutoGeneratedCaptionDataManager.js",
                moduleID: i.id,
              },
            ));
        })
        .setURI(n)
        .send();
    }
    function u(t, n) {
      ((e = n),
        r("promiseDone")(
          c(t),
          function (e) {
            var o,
              a = e == null ? void 0 : e.data,
              l = a == null || (o = a[0]) == null ? void 0 : o.id;
            l &&
              r("AdsVideoCaptionCaptionLoggingDataAction").dispatch(
                {
                  event: "fetched_success",
                  videoID: t,
                  captionID: l,
                  message: n.toString(),
                },
                {
                  line: "114",
                  module: "AdsAutoGeneratedCaptionDataManager.js",
                  moduleID: i.id,
                },
              );
          },
          function (e) {
            (r("AdsAutoGeneratedCaptionCaptionsSetDataAction").dispatch(
              { captions: [], videoID: t },
              {
                line: "123",
                module: "AdsAutoGeneratedCaptionDataManager.js",
                moduleID: i.id,
              },
            ),
              r(
                "AdsAutoGeneratedCaptionCaptionsFetchFinishedDataAction",
              ).dispatch(
                { videoID: t },
                {
                  line: "127",
                  module: "AdsAutoGeneratedCaptionDataManager.js",
                  moduleID: i.id,
                },
              ),
              r("AdsPerfInteractionsController") != null &&
                r("AdsPerfInteractionsController").annotateFailure(
                  "am.dialog_editor.creative_caption",
                  i.id,
                  { error: e },
                ));
          },
        ));
    }
    function c(e) {
      var t = { data: [] },
        n = o("GraphAPIPolling").poll(
          function () {
            return o("AdsGraphAPI")
              .get(i.id)
              .object("video", e)
              .edge("auto_generated_captions")
              .get({
                fields: [
                  "id",
                  "locale",
                  "last_published_time",
                  "last_save_time",
                  "review_expire_time",
                  "status",
                ],
              });
          },
          function (n) {
            if (!n.data || n.data.length === 0)
              return (
                r("AdsAutoGeneratedCaptionCaptionsSetDataAction").dispatch(
                  { captions: [], videoID: e },
                  {
                    line: "167",
                    module: "AdsAutoGeneratedCaptionDataManager.js",
                    moduleID: i.id,
                  },
                ),
                !1
              );
            var o = !0,
              a = !0,
              l = !1;
            return (
              n.data.forEach(function (e) {
                var t = r("VideoSubtitleStatusType")[e.status];
                if (t === 0) {
                  o = !1;
                  return;
                } else if (t === 2) {
                  ((o = !0), (a = !1), (l = !0));
                  return;
                }
              }),
              a &&
                (r("AdsAutoGeneratedCaptionCaptionsSetDataAction").dispatch(
                  { captions: n.data, videoID: e },
                  {
                    line: "193",
                    module: "AdsAutoGeneratedCaptionDataManager.js",
                    moduleID: i.id,
                  },
                ),
                r("AdsVideoCaptionCaptionSetDataAction").dispatch(
                  { captions: n.data, videoID: e },
                  {
                    line: "198",
                    module: "AdsAutoGeneratedCaptionDataManager.js",
                    moduleID: i.id,
                  },
                ),
                (t = n)),
              l &&
                r("AdsAutoGeneratedCaptionCaptionsSetDataAction").dispatch(
                  { captions: n.data, videoID: e },
                  {
                    line: "205",
                    module: "AdsAutoGeneratedCaptionDataManager.js",
                    moduleID: i.id,
                  },
                ),
              o
            );
          },
          r("AdsAutoCaptionConfig.experimental").time_out_in_processing,
          r("AdsAutoCaptionConfig.experimental").poll_interval,
        );
      return n(t).then(function () {
        return t;
      });
    }
    function d() {
      var e = r("XVideoCaptionEditorAdsNUXController").getURIBuilder().getURI();
      new (r("AsyncRequest"))()
        .setMethod("POST")
        .setURI(e)
        .setHandler(function (e) {
          var t = e.payload || {};
          r("AdsAutoGeneratedCaptionSetNuxStatusDataAction").dispatch(
            { payload: t },
            {
              line: "230",
              module: "AdsAutoGeneratedCaptionDataManager.js",
              moduleID: i.id,
            },
          );
        })
        .send();
    }
    function m(e, t) {
      var n = r("XVideoCaptionShareAsyncControllerRouteBuilder").buildUri({
        caption_id: t,
      });
      new (r("AsyncRequest"))()
        .setMethod("POST")
        .setHandler(function (n) {
          var o = n.payload || {};
          (r("AdsAutoGeneratedCaptionCaptionsShareEditDataAction").dispatch(
            { captionID: t, expireTime: o.expire_time, videoID: e },
            {
              line: "255",
              module: "AdsAutoGeneratedCaptionDataManager.js",
              moduleID: i.id,
            },
          ),
            r("AdsVideoCaptionCaptionLoggingDataAction").dispatch(
              {
                event: "share_success",
                videoID: e,
                captionID: t,
                message: null,
              },
              {
                line: "260",
                module: "AdsAutoGeneratedCaptionDataManager.js",
                moduleID: i.id,
              },
            ));
        })
        .setErrorHandler(function (n) {
          (r("AsyncResponse").defaultErrorHandler(n),
            r("AdsVideoCaptionCaptionLoggingDataAction").dispatch(
              { event: "share_error", videoID: e, captionID: t, message: null },
              {
                line: "270",
                module: "AdsAutoGeneratedCaptionDataManager.js",
                moduleID: i.id,
              },
            ));
        })
        .setURI(n)
        .send();
    }
    function p(e, t) {
      var n = r("XVideoCaptionShareAsyncControllerRouteBuilder").buildUri({
        caption_id: t,
        revoke: 1,
      });
      new (r("AsyncRequest"))()
        .setMethod("POST")
        .setHandler(function (n) {
          var o = n.payload || {};
          (r("AdsAutoGeneratedCaptionCaptionsShareEditDataAction").dispatch(
            { captionID: t, expireTime: o.expire_time, videoID: e },
            {
              line: "299",
              module: "AdsAutoGeneratedCaptionDataManager.js",
              moduleID: i.id,
            },
          ),
            r("AdsVideoCaptionCaptionLoggingDataAction").dispatch(
              {
                event: "revoke_share_success",
                videoID: e,
                captionID: t,
                message: null,
              },
              {
                line: "304",
                module: "AdsAutoGeneratedCaptionDataManager.js",
                moduleID: i.id,
              },
            ));
        })
        .setErrorHandler(function (n) {
          (r("AsyncResponse").defaultErrorHandler(n),
            r("AdsVideoCaptionCaptionLoggingDataAction").dispatch(
              {
                event: "revoke_share_error",
                videoID: e,
                captionID: t,
                message: null,
              },
              {
                line: "314",
                module: "AdsAutoGeneratedCaptionDataManager.js",
                moduleID: i.id,
              },
            ));
        })
        .setURI(n)
        .send();
    }
    function _(e, t) {
      t.map(function (t) {
        var n = t.get("id"),
          a = o("ThisControllerNoLongerExists")
            .__DEADBUILDER__("znx0ijycp")
            .setInt("caption_id", n);
        new (r("AsyncRequest"))()
          .setMethod("POST")
          .setHandler(function (t) {
            var o = t.payload;
            o && o.created === "success"
              ? r("AdsVideoCaptionCaptionLoggingDataAction").dispatch(
                  {
                    event: "create_srt_success",
                    videoID: e,
                    captionID: n,
                    message: o && o.message,
                  },
                  {
                    line: "345",
                    module: "AdsAutoGeneratedCaptionDataManager.js",
                    moduleID: i.id,
                  },
                )
              : r("AdsVideoCaptionCaptionLoggingDataAction").dispatch(
                  {
                    event: "create_srt_error",
                    videoID: e,
                    captionID: n,
                    message: o && o.error,
                  },
                  {
                    line: "352",
                    module: "AdsAutoGeneratedCaptionDataManager.js",
                    moduleID: i.id,
                  },
                );
          })
          .setURI(a.getURI())
          .send();
      });
    }
    function f(e, t, n) {
      var a = o("ThisControllerNoLongerExists")
        .__DEADBUILDER__("c7pvbckjm")
        .setInt("caption_id", e)
        .setFBID("source_app_id", o("WebApiApplication").getClientID())
        .setEnum("placement", t)
        .setInt("ad_account_id", n);
      new (r("AsyncRequest"))().setMethod("POST").setURI(a.getURI()).send();
    }
    function g(e, t) {
      t.map(function (t) {
        var n = t.get("id"),
          a = o("ThisControllerNoLongerExists")
            .__DEADBUILDER__("sdykofts")
            .setInt("caption_id", n);
        new (r("AsyncRequest"))()
          .setMethod("POST")
          .setHandler(function (t) {
            var o = t.payload;
            o && o.created === "success"
              ? r("AdsVideoCaptionCaptionLoggingDataAction").dispatch(
                  {
                    event: "revoke_srt_success",
                    videoID: e,
                    captionID: n,
                    message: o && o.message,
                  },
                  {
                    line: "399",
                    module: "AdsAutoGeneratedCaptionDataManager.js",
                    moduleID: i.id,
                  },
                )
              : r("AdsVideoCaptionCaptionLoggingDataAction").dispatch(
                  {
                    event: "revoke_srt_error",
                    videoID: e,
                    captionID: n,
                    message: o && o.error,
                  },
                  {
                    line: "406",
                    module: "AdsAutoGeneratedCaptionDataManager.js",
                    moduleID: i.id,
                  },
                );
          })
          .setURI(a.getURI())
          .send();
      });
    }
    function h(e, t) {
      var n = o("WebApiApplication").getClientID(),
        a = r("XVideoCaptionPublishAsyncControllerRouteBuilder").buildUri(
          babelHelpers.extends(
            { caption_id: t },
            n != null ? { source_app_id: n } : {},
          ),
        );
      new (r("AsyncRequest"))()
        .setMethod("POST")
        .setHandler(function (n) {
          var o = n.payload;
          o && o.published === "success"
            ? r("AdsVideoCaptionCaptionLoggingDataAction").dispatch(
                {
                  event: "publish_success",
                  videoID: e,
                  captionID: t,
                  message: o && o.transcription,
                },
                {
                  line: "436",
                  module: "AdsAutoGeneratedCaptionDataManager.js",
                  moduleID: i.id,
                },
              )
            : r("AdsVideoCaptionCaptionLoggingDataAction").dispatch(
                {
                  event: "publish_error",
                  videoID: e,
                  captionID: t,
                  message: o && o.error,
                },
                {
                  line: "443",
                  module: "AdsAutoGeneratedCaptionDataManager.js",
                  moduleID: i.id,
                },
              );
        })
        .setURI(a)
        .send();
    }
    function y(e, t) {
      var n = o("WebApiApplication").getClientID(),
        a = r("XVideoUnPublishCaptionAsyncControllerRouteBuilder").buildUri(
          babelHelpers.extends(
            { caption_id: t },
            n != null ? { source_app_id: n } : {},
          ),
        );
      new (r("AsyncRequest"))()
        .setMethod("POST")
        .setHandler(function (n) {
          var o = n.payload;
          o && o.unpublish_status === "success"
            ? (r("AdsAutoGeneratedCaptionCaptionsFetchDataAction").dispatch(
                {
                  videoID: e,
                  captionAutogenerationStatus: r(
                    "AdsAutogenerationCaptionStatus",
                  ).NOT_STARTED,
                },
                {
                  line: "472",
                  module: "AdsAutoGeneratedCaptionDataManager.js",
                  moduleID: i.id,
                },
              ),
              r("AdsVideoCaptionCaptionLoggingDataAction").dispatch(
                {
                  event: "unpublish_success",
                  videoID: e,
                  captionID: t,
                  message: null,
                },
                {
                  line: "477",
                  module: "AdsAutoGeneratedCaptionDataManager.js",
                  moduleID: i.id,
                },
              ))
            : r("AdsVideoCaptionCaptionLoggingDataAction").dispatch(
                {
                  event: "unpublish_error",
                  videoID: e,
                  captionID: t,
                  message: o && o.error,
                },
                {
                  line: "484",
                  module: "AdsAutoGeneratedCaptionDataManager.js",
                  moduleID: i.id,
                },
              );
        })
        .setURI(a)
        .send();
    }
    function C() {
      return e;
    }
    function b(e) {
      (r("AdsAutoGeneratedCaptionCaptionsRegenerateCaptionDataAction").dispatch(
        { videoID: e },
        {
          line: "502",
          module: "AdsAutoGeneratedCaptionDataManager.js",
          moduleID: i.id,
        },
      ),
        v(e, !0));
    }
    function v(e, t) {
      var n = r("XVideoCaptionGenerateAsyncControllerRouteBuilder").buildUri(
        babelHelpers.extends(
          { video_id: e },
          t != null ? { regenerate: t } : {},
        ),
      );
      new (r("AsyncRequest"))()
        .setMethod("POST")
        .setHandler(function (t) {
          var n = t.payload;
          n && n.status === 1
            ? (r("AdsAutoGeneratedCaptionSetNewVideoDataAction").dispatch(
                { videoID: e },
                {
                  line: "528",
                  module: "AdsAutoGeneratedCaptionDataManager.js",
                  moduleID: i.id,
                },
              ),
              r("AdsAutoGeneratedCaptionCaptionsFetchDataAction").dispatch(
                {
                  videoID: e,
                  captionAutogenerationStatus: r(
                    "AdsAutogenerationCaptionStatus",
                  ).IN_PROGRESS,
                },
                {
                  line: "531",
                  module: "AdsAutoGeneratedCaptionDataManager.js",
                  moduleID: i.id,
                },
              ),
              r("AdsVideoCaptionCaptionLoggingDataAction").dispatch(
                {
                  event: "generate_success",
                  videoID: e,
                  captionID: n.caption_id,
                  message: null,
                },
                {
                  line: "536",
                  module: "AdsAutoGeneratedCaptionDataManager.js",
                  moduleID: i.id,
                },
              ))
            : (r("AdsAutoGeneratedCaptionCaptionsSetDataAction").dispatch(
                { captions: [], videoID: e },
                {
                  line: "543",
                  module: "AdsAutoGeneratedCaptionDataManager.js",
                  moduleID: i.id,
                },
              ),
              r("AdsVideoCaptionCaptionHideAutoDataAction").dispatch(
                { videoID: e },
                {
                  line: "547",
                  module: "AdsAutoGeneratedCaptionDataManager.js",
                  moduleID: i.id,
                },
              ),
              r("AdsVideoCaptionCaptionLoggingDataAction").dispatch(
                {
                  event: "generate_error",
                  videoID: e,
                  captionID: n && n.error,
                  message: null,
                },
                {
                  line: "550",
                  module: "AdsAutoGeneratedCaptionDataManager.js",
                  moduleID: i.id,
                },
              ));
        })
        .setURI(n)
        .setErrorHandler(r("adsManagerDefaultErrorHandler"))
        .send();
    }
    ((l.downloadCaption = s),
      (l.fetchCaptions = u),
      (l.pollCaptions = c),
      (l.fetchShouldShowNUX = d),
      (l.shareCaption = m),
      (l.revokeShareCaption = p),
      (l.createSRTJob = _),
      (l.sendNotif = f),
      (l.revokeSRTJob = g),
      (l.publishCaption = h),
      (l.unPublishCaption = y),
      (l.getIsNewVideo = C),
      (l.regenerateCaption = b),
      (l.generateCaption = v));
  },
  98,
);
