__d(
  "AdsAPIDeliveryInfoFields",
  [],
  function (t, n, r, o, a, i) {
    var e = Object.freeze({
      ACTIVE_ACCELERATED_CAMPAIGN_COUNT: "active_accelerated_campaign_count",
      ACTIVE_DAY_PARTED_CAMPAIGN_COUNT: "active_day_parted_campaign_count",
      ACTIVE_ROTATED_CAMPAIGN_COUNT: "active_rotated_campaign_count",
      ARE_ALL_DAILY_BUDGETS_SPENT: "are_all_daily_budgets_spent",
      COMPLETED_CAMPAIGN_COUNT: "completed_campaign_count",
      CREDIT_NEEDED_ADS_COUNT: "credit_needed_ads_count",
      DELIVERY_INSIGHT: "delivery_insight",
      DELIVERY_INSIGHTS: "delivery_insights",
      ELIGIBLE_FOR_DELIVERY_INSIGHTS: "eligible_for_delivery_insights",
      END_TIME: "end_time",
      HAS_ACCOUNT_HIT_SPEND_LIMIT: "has_account_hit_spend_limit",
      HAS_CAMPAIGN_GROUP_HIT_SPEND_LIMIT: "has_campaign_group_hit_spend_limit",
      HAS_NO_ACTIVE_ADS: "has_no_active_ads",
      HAS_NO_ADS: "has_no_ads",
      INACTIVE_ADS_COUNT: "inactive_ads_count",
      INACTIVE_CAMPAIGN_COUNT: "inactive_campaign_count",
      IS_ADGROUP_PARTIALLY_REJECTED: "is_adgroup_partially_rejected",
      IS_AD_UNECONOMICAL: "is_ad_uneconomical",
      IS_CAMPAIGN_ACCELERATED: "is_campaign_accelerated",
      IS_CAMPAIGN_COMPLETED: "is_campaign_completed",
      IS_CAMPAIGN_DAY_PARTED: "is_campaign_day_parted",
      IS_CAMPAIGN_DISABLED: "is_campaign_disabled",
      IS_CAMPAIGN_GROUP_DISABLED: "is_campaign_group_disabled",
      IS_CAMPAIGN_ROTATED: "is_campaign_rotated",
      IS_CAMPAIGN_SCHEDULED: "is_campaign_scheduled",
      IS_DAILY_BUDGET_SPENT: "is_daily_budget_spent",
      IS_ACCOUNT_CLOSED: "is_account_closed",
      IS_ACCOUNT_DISABLED: "is_account_disabled",
      IS_REACH_AND_FREQUENCY_MISCONFIGURED:
        "is_reach_and_frequency_misconfigured",
      PENDING_REVIEW_INFO: "pending_review_info",
      REACH_FREQUENCY_CAMPAIGN_UNDERDELIVERY_REASON:
        "reach_frequency_campaign_underdelivery_reason",
      IS_SPLIT_TEST_ACTIVE: "is_split_test_active",
      IS_SPLIT_TEST_VALID: "is_split_test_valid",
      LIFT_STUDY_TIME_PERIOD: "lift_study_time_period",
      LIMITED_CAMPAIGN_COUNT: "limited_campaign_count",
      LIMITED_CAMPAIGN_IDS: "limited_campaign_ids",
      NEEDS_CREDIT: "needs_credit",
      NEEDS_TAX_NUMBER: "needs_tax_number",
      NON_DELETED_ADS_COUNT: "non_deleted_ads_count",
      NOT_DELIVERING_CAMPAIGN_COUNT: "not_delivering_campaign_count",
      PENDING_ADS_COUNT: "pending_ads_count",
      REJECTED_ADS_COUNT: "rejected_ads_count",
      SCHEDULED_CAMPAIGN_COUNT: "scheduled_campaign_count",
      SIGNAL_DIAGNOSTIC_ISSUE: "signal_diagnostic_issue",
      START_TIME: "start_time",
      STATUS: "status",
      TEXT_PENALTY_LEVEL: "text_penalty_level",
      IS_ADFARM_PENALIZED: "is_adfarm_penalized",
      IS_CLICKBAIT_PENALIZED: "is_clickbait_penalized",
      IS_LQWE_PENALIZED: "is_lqwe_penalized",
      IS_ENGAGEMENT_BAIT_PENALIZED: "is_engagement_bait_penalized",
      IS_SENSATIONALISM_PENALIZED: "is_sensationalism_penalized",
      AD_PENALTY_MAP: "ad_penalty_map",
    });
    i.default = e;
  },
  66,
);
