__d(
  "AdsAutoGeneratedCaptionCaptionsShareEditDataAction",
  [
    "AdsAutoGeneratedCaptionCaptionsShareEditDataReducerPlugin",
    "AdsAutoGeneratedCaptionProvider",
    "Laminar",
  ],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = n("Laminar").__createAction(
      function () {
        return [
          n("Laminar").__createReducer(
            n("AdsAutoGeneratedCaptionCaptionsShareEditDataReducerPlugin"),
            n("AdsAutoGeneratedCaptionProvider"),
            {},
            "",
          ),
        ];
      },
      function () {
        return [];
      },
      "AdsAutoGeneratedCaption.CAPTIONS.SHARE_EDIT",
    );
    a.exports = e;
  },
  null,
);
