__d(
  "AdsAutoGeneratedCaptionCaptionsFetchDataAction",
  [
    "AdsAutoGeneratedCaptionCaptionsFetchDataReducerPlugin",
    "AdsAutoGeneratedCaptionProvider",
    "Laminar",
  ],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = n("Laminar").__createAction(
      function () {
        return [
          n("Laminar").__createReducer(
            n("AdsAutoGeneratedCaptionCaptionsFetchDataReducerPlugin"),
            n("AdsAutoGeneratedCaptionProvider"),
            {},
            "",
          ),
        ];
      },
      function () {
        return [];
      },
      "AdsAutoGeneratedCaption.CAPTIONS.FETCH",
    );
    a.exports = e;
  },
  null,
);
