__d(
  "AdsAutoGeneratedCaptionCaptionsShareEditDataReducerPlugin",
  [],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = {
        reduce: function (t, n) {
          var e = t
            .getIn(["captionDataByVideoID", n.videoID, "captions"])
            .map(function (e) {
              return e.id !== n.captionID
                ? e
                : babelHelpers.extends({}, e, {
                    review_expire_time: parseInt(n.expireTime, 10),
                  });
            });
          return t.setIn(["captionDataByVideoID", n.videoID, "captions"], e);
        },
      },
      l = e;
    i.default = l;
  },
  66,
);
