__d(
  "AdsAPIOfferFields",
  [],
  function (t, n, r, o, a, i) {
    var e = Object.freeze({
      AD_ACCOUNT: "ad_account",
      AD_IMAGE_HASH: "ad_image_hash",
      AD_IMAGE_HASHES: "ad_image_hashes",
      BARCODE_PHOTO: "barcode_photo",
      BARCODE_PHOTO_URI: "barcode_photo_uri",
      BARCODE_TYPE: "barcode_type",
      BARCODE_VALUE: "barcode_value",
      BLOCK_RESHARES: "block_reshares",
      CODE_TYPE: "code_type",
      CAPTION: "caption",
      CAROUSEL_DATA: "carousel_data",
      CAROUSEL_LINKS: "carousel_links",
      CAROUSEL_CAPTIONS: "carousel_captions",
      COMMERCE_PRODUCT_ITEM: "commerce_product_item",
      COMMERCE_STORE: "commerce_store",
      COMMERCE_STORE_COLLECTION: "commerce_store_collection",
      DEEPLINK: "deeplink",
      DEEPLINKS: "deeplinks",
      DETAILS: "details",
      DISABLE_LOCATION: "disable_location",
      DISCOUNTS: "discounts",
      DISCOUNT_CURRENCY: "currency",
      DISCOUNT_OVERRIDE_TEXT: "override",
      DISCOUNT_TEXT: "text",
      DISCOUNT_TYPE: "type",
      DISCOUNT_VALUE1: "value1",
      DISCOUNT_VALUE2: "value2",
      EXPIRATION_TIME: "expiration_time",
      FILE: "file",
      ID: "id",
      IMAGE_CROP: "image_crop",
      IMAGE_CROPS: "image_crops",
      IMAGE_URL: "image_url",
      INSTORE_CODE: "instore_code",
      LOCATION_TYPE: "location_type",
      MAX_SAVE_COUNT: "max_save_count",
      MESSAGE: "message",
      ONLINE_CODE: "online_code",
      OFFER: "offer",
      PAGE: "page",
      PAGE_SET_ID: "page_set_id",
      PLACE_DATA: "place_data",
      PUBLISHED: "published",
      PUBLISHED_ADS: "published_ads",
      PHOTO: "photo",
      PHOTOS: "photos",
      REDEMPTION_CODE: "redemption_code",
      REDEMPTION_LINK: "redemption_link",
      SAVE_COUNT: "save_count",
      START_TIME: "start_time",
      TERMS: "terms",
      TITLE: "title",
      TOTAL_UNIQUE_CODES: "total_unique_codes",
      UNIQUE_BARCODES: "unique_barcodes",
      UNIQUE_CODES: "unique_codes",
      UNIQUE_CODES_FILE_CODE_TYPE: "unique_codes_file_code_type",
      UNIQUE_CODES_FILE_NAME: "unique_codes_file_name",
      UNIQUE_CODES_FILE_UPLOAD_STATUS: "unique_codes_file_upload_status",
      UNPUBLISHED_CONTENT_TYPE: "unpublished_content_type",
      URL: "url",
      URLS: "urls",
      VIDEO_ID: "video_id",
      VIDEOS: "videos",
      VIEWS: "views",
    });
    i.default = e;
  },
  66,
);
