__d(
  "AdsAPIInstagramSupportedObjectives",
  [],
  function (t, n, r, o, a, i) {
    var e = Object.freeze({
      BRAND_AWARENESS: "BRAND_AWARENESS",
      LEAD_GENERATION: "LEAD_GENERATION",
      LOCAL_AWARENESS: "LOCAL_AWARENESS",
      MESSAGES: "MESSAGES",
      MOBILE_APP_ENGAGEMENT: "MOBILE_APP_ENGAGEMENT",
      MOBILE_APP_INSTALLS: "MOBILE_APP_INSTALLS",
      APP_INSTALLS: "APP_INSTALLS",
      POST_ENGAGEMENT: "POST_ENGAGEMENT",
      PRODUCT_CATALOG_SALES: "PRODUCT_CATALOG_SALES",
      REACH: "REACH",
      STORE_VISITS: "STORE_VISITS",
      VIDEO_VIEWS: "VIDEO_VIEWS",
      LINK_CLICKS: "LINK_CLICKS",
      WEBSITE_CONVERSIONS: "WEBSITE_CONVERSIONS",
      WILDCARD_INTERNAL_ONLY: "WILDCARD_INTERNAL_ONLY",
      OUTCOME_LEADS: "OUTCOME_LEADS",
      OUTCOME_SALES: "OUTCOME_SALES",
      OUTCOME_ENGAGEMENT: "OUTCOME_ENGAGEMENT",
      OUTCOME_AWARENESS: "OUTCOME_AWARENESS",
      CONVERSIONS: "CONVERSIONS",
    });
    i.default = e;
  },
  66,
);
