__d(
  "AdsAutoGeneratedCaptionProviderPlugin",
  ["immutable"],
  function (t, n, r, o, a, i, l) {
    "use strict";
    var e = (function (e) {
        function t() {
          return e.apply(this, arguments) || this;
        }
        return (babelHelpers.inheritsLoose(t, e), t);
      })(
        r("immutable").Record({
          captionDataByVideoID: r("immutable").Map(),
          newVideos: [],
          showEditorNUX: !1,
        }),
      ),
      s = { initialState: new e() },
      u = s;
    l.default = u;
  },
  98,
);
