__d(
  "AdsAutoGeneratedCaptionSetNewVideoDataReducerPlugin",
  ["AdsAutoGeneratedCaptionDataManager"],
  function (t, n, r, o, a, i, l) {
    "use strict";
    var e = {
        reduce: function (t, n) {
          var e = t.newVideos.slice();
          return (
            e.push(n.videoID),
            t.getIn(["captionDataByVideoID", n.videoID]) &&
              o("AdsAutoGeneratedCaptionDataManager").fetchCaptions(
                n.videoID,
                !0,
              ),
            t.set("newVideos", e)
          );
        },
      },
      s = e;
    l.default = s;
  },
  98,
);
