__d(
  "AdsAutoGeneratedCaptionCaptionsRegenerateCaptionDataAction",
  [
    "AdsAutoGeneratedCaptionCaptionsRegenerateCaptionDataReducerPlugin",
    "AdsAutoGeneratedCaptionProvider",
    "Laminar",
  ],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = n("Laminar").__createAction(
      function () {
        return [
          n("Laminar").__createReducer(
            n(
              "AdsAutoGeneratedCaptionCaptionsRegenerateCaptionDataReducerPlugin",
            ),
            n("AdsAutoGeneratedCaptionProvider"),
            {},
            "",
          ),
        ];
      },
      function () {
        return [];
      },
      "AdsAutoGeneratedCaption.CAPTIONS.REGENERATE_CAPTION",
    );
    a.exports = e;
  },
  null,
);
