__d(
  "AdsAutoGeneratedCaptionProvider",
  ["AdsAutoGeneratedCaptionProviderPlugin", "Laminar"],
  function (t, n, r, o, a, i) {
    "use strict";
    a.exports = n("Laminar").__createProvider(
      n("AdsAutoGeneratedCaptionProviderPlugin"),
      "AdsAutoGeneratedCaptionProviderPlugin",
    );
  },
  null,
);
