__d(
  "AdsAutoGeneratedCaptionCaptionsSetDataReducerPlugin",
  ["AdsAutogenerationCaptionStatus", "VideoSubtitleStatusType"],
  function (t, n, r, o, a, i, l) {
    "use strict";
    var e = {
        reduce: function (t, n) {
          if (
            !t.getIn(["captionDataByVideoID", n.videoID]) ||
            !n.captions ||
            !n.captions[0]
          )
            return t;
          var e = r("AdsAutogenerationCaptionStatus").SUCCESS;
          return (
            n.captions &&
              n.captions.findIndex(function (e) {
                return r("VideoSubtitleStatusType")[e.status] === 2;
              }) !== -1 &&
              (e = r("AdsAutogenerationCaptionStatus").FAILED),
            t.withMutations(function (t) {
              (t
                .setIn(["captionDataByVideoID", n.videoID, "isFetched"], !0)
                .setIn(
                  [
                    "captionDataByVideoID",
                    n.videoID,
                    "captionAutogenerationStatus",
                  ],
                  e,
                ),
                e !== r("AdsAutogenerationCaptionStatus").FAILED &&
                  t.setIn(
                    ["captionDataByVideoID", n.videoID, "captions"],
                    n.captions,
                  ));
            })
          );
        },
      },
      s = e;
    l.default = s;
  },
  98,
);
