__d(
  "AdsAutoGeneratedCaptionUtils",
  ["fbt", "imperativelyShowGeoModal", "isIE11"],
  function (t, n, r, o, a, i, l, s) {
    "use strict";
    function e(e, t, n) {
      try {
        var o = new Blob([e], { type: "text/plain" }),
          a = t + "." + n + ".srt";
        if (r("isIE11")()) window.navigator.msSaveOrOpenBlob(o, a);
        else {
          var i = window.URL.createObjectURL(o),
            l = document.createElement("a");
          ((l.href = i),
            l.setAttribute("download", a),
            document.body && document.body.appendChild(l),
            l.click(),
            document.body && document.body.removeChild(l));
        }
        return !0;
      } catch (e) {
        var u = s._(/*BTDS*/ "Download Error");
        r("imperativelyShowGeoModal")({
          body: s._(
            /*BTDS*/ "Something went wrong. We're working getting this fixed as soon as we can. You may be able to try again.",
          ),
          label: u,
          title: u,
        });
      }
      return !1;
    }
    l.downloadCaptionFile = e;
  },
  226,
);
