__d(
  "AdsAPTrackedInteractionsConfig",
  [],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = [
        "am.draft.create_draft",
        "am.message_marketing_draft.create_draft",
        "am.duplication.load_dialog",
        "am.duplication.load_manual_dialog",
        "am.duplication.load_upgrade_dialog",
        "am.edit_ads.load_media_picker_dialog",
        "am.edit_ads.upload_asset_in_media_dialog",
        "am.edit_targeting.audience_estimates",
        "am.edit_video.upload",
        "am.editor.change_level",
        "am.edit_ads.load_prioritized_products_section",
        "am.message_marketing_editor.change_level",
        "am.editor.change_same_level",
        "am.editor.save_changes",
        "am.insights_table.export_report",
        "am.insights_table.open_column_set_editor",
        "am.manage_ads.load_editor",
        "am.management.page_load",
        "am.publish_ads.in_editor",
        "am.publish_ads.in_review_and_publish",
        "am.quick_creation.load_crepe_dialog",
        "am.quick_creation.load_dialog",
        "am.route.navigate",
        "am.side_panel.load_charts",
        "am.syd.load_auto_apply_history_modal",
        "am.syd.route_navigate",
        "am.table_data_display.change_date_range",
        "am.table_data_display.change_level",
        "am.table_data_display.change_sort",
        "am.message_marketing_table_data_display.change_sort",
        "am.table_data_display.clear_ancestor_selection_filter",
        "am.table_data_display.filter",
        "am.table_data_display.open_ad_object",
        "am.table_data_display.refresh_button",
        "am.table.load_publish_dialog",
        "am.actions_cell_mfr.hover",
        "am.editor.open_wa_capture_generic_code_setup_modal",
      ],
      l = e;
    i.default = l;
  },
  66,
);
