__d(
  "adsAutoGeneratedCaptionActionsUnPublishCaption",
  ["AdsAutoGeneratedCaptionDataManager", "AdsAutoGeneratedCaptionProvider"],
  function (t, n, r, o, a, i, l) {
    "use strict";
    function e(e, t) {
      var n = r("AdsAutoGeneratedCaptionProvider")().getIn([
        "captionDataByVideoID",
        t,
        "captions",
      ]);
      n &&
        n.length > 0 &&
        n[0].locale === e &&
        o("AdsAutoGeneratedCaptionDataManager").unPublishCaption(t, n[0].id);
    }
    l.default = e;
  },
  98,
);
