__d(
  "AdsAutoGeneratedCaptionCaptionsFetchFinishedDataAction",
  [
    "AdsAutoGeneratedCaptionCaptionsFetchFinishedDataReducerPlugin",
    "AdsAutoGeneratedCaptionProvider",
    "Laminar",
  ],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = n("Laminar").__createAction(
      function () {
        return [
          n("Laminar").__createReducer(
            n("AdsAutoGeneratedCaptionCaptionsFetchFinishedDataReducerPlugin"),
            n("AdsAutoGeneratedCaptionProvider"),
            {},
            "",
          ),
        ];
      },
      function () {
        return [];
      },
      "AdsAutoGeneratedCaption.CAPTIONS.FETCH_FINISHED",
    );
    a.exports = e;
  },
  null,
);
