__d(
  "AdsFlexibleTargetingConstants",
  [
    "cssVar",
    "fbt",
    "$InternalEnum",
    "deepFreezeValue",
    "keyMirror",
    "mapObject",
  ],
  function (t, n, r, o, a, i, l, s, u) {
    "use strict";
    var e,
      c = r("keyMirror")({
        INCLUDE_ALL: null,
        INCLUDE_ANY: null,
        EXCLUDE_ANY: null,
      }),
      d = Object.freeze({ FLEXIBLE_TARGETING_API: !0 }),
      m = { INTERESTS: "interests", WORK_EMPLOYERS: "work_employers" },
      p = r("keyMirror")({
        relationship_statuses: null,
        interested_in: null,
        education_statuses: null,
        college_years: null,
      }),
      _ = "detailed_targeting",
      f = "account_level_brand_safety_detailed_targeting_exclusions",
      g = "account_level_employer_detailed_targeting_exclusions",
      h = {
        interests: ["Interests"],
        behaviors: ["Behaviors"],
        hashtag_interactions: ["Hashtag interactions"],
        purchase_intent: ["In-market categories"],
        user_adclusters: ["More Categories", "Partner Categories"],
        college_years: ["Demographics", "Education", "Undergrad Years"],
        education_majors: ["Demographics", "Education", "Fields of Study"],
        education_schools: ["Demographics", "Education", "Schools"],
        education_statuses: ["Demographics", "Education", "Education level"],
        ethnic_affinity: ["Demographics", "Multicultural Affinity"],
        family_statuses: ["Demographics", "Parents"],
        generation: ["Demographics", "Generation"],
        home_ownership: ["Demographics", "Home", "Home Ownership"],
        home_type: ["Demographics", "Home", "Home Type"],
        home_value: ["Demographics", "Home", "Home Value"],
        household_composition: [
          "Demographics",
          "Home",
          "Household Composition",
        ],
        income: ["Demographics", "Financial", "Income"],
        industries: ["Demographics", "Work", "Industries"],
        interested_in: ["Demographics", "Relationship", "Interested In"],
        life_events: ["Demographics", "Life Events"],
        moms: ["Demographics", "Parents", "Moms"],
        net_worth: ["Demographics", "Financial", "Net Worth"],
        office_type: ["Demographics", "Work", "Office Type"],
        politics: ["Demographics", "Politics (US)"],
        relationship_statuses: [
          "Demographics",
          "Relationship",
          "Relationship Status",
        ],
        work_employers: ["Demographics", "Work", "Employers"],
        work_positions: ["Demographics", "Work", "Job Titles"],
        location_categories: ["Places of Interest"],
        consumer_classification_brazil: [
          "Behaviors",
          "Consumer Classification",
          "Brazil",
        ],
      },
      y = {
        education_majors: !0,
        education_schools: !0,
        interests: !0,
        work_employers: !0,
        work_positions: !0,
      },
      C = {
        college_years: !0,
        education_statuses: !0,
        interested_in: !0,
        relationship_statuses: !0,
      },
      b = (e || (e = r("mapObject")))(h, function () {
        return !0;
      }),
      v = [
        {
          type: c.INCLUDE_ANY,
          income: [{ id: "6006371343132", name: "Over 125,000" }],
          behaviors: [{ id: "6017831572183", name: "iPhone 6" }],
        },
        {
          type: c.EXCLUDE_ANY,
          interests: [{ id: "6003167425934", name: "Shopping and fashion" }],
        },
      ],
      S = "FLEXIBLE_TARGETING_API",
      R = n("$InternalEnum").Mirrored(["INCLUDE_REPLACE"]),
      L = u._(/*BTDS*/ "Interests"),
      E = u._(/*BTDS*/ "Additional interests"),
      k = u._(/*BTDS*/ "Demographics"),
      I = u._(/*BTDS*/ "Education"),
      T = u._(/*BTDS*/ "Fields of study"),
      D = u._(/*BTDS*/ "Schools"),
      x = u._(/*BTDS*/ "Undergrad years"),
      $ = u._(/*BTDS*/ "Work"),
      P = u._(/*BTDS*/ "Employers"),
      N = u._(/*BTDS*/ "Job titles"),
      M = u._(/*BTDS*/ "Size:"),
      w = {
        interests: [L, E],
        education_majors: [k, I, T],
        education_schools: [k, I, D],
        college_years: [k, I, x],
        work_employers: [k, $, P],
        work_positions: [k, $, N],
      },
      A = [L, E],
      F = {
        ORIGIN_COLOR: "#FFFFFF",
        ANIMATION_COLOR: "rgba(88, 144, 255, 0.1)",
        DURATION: 1e3,
      },
      O = 10,
      B = new Date().getFullYear(),
      W = { CURRENT: B, MIN_YEAR: 1980, MAX_YEAR: B + 4 },
      q = {
        SAMSUNG_DEVICES: {
          id: "6004386010572",
          name: "Facebook access (mobile): Samsung Android mobile devices",
        },
        XIAOMI_DEVICES: { id: "6019164630583", name: "Owns: Xiaomi" },
        OCULUS_OWNERS: { id: "6213618838383", name: "Oculus Quest Owners" },
      },
      U = {
        ARRAY_TYPE_ENTRIES: p,
        COLLEGE_YEAR_RANGE: W,
        COMPONENT_ID_FOR_LOGGING: _,
        ACCOUNT_SETTINGS_BRAND_SAFETY_ID_FOR_LOGGING: f,
        ACCOUNT_SETTINGS_EMPLOYER_ID_FOR_LOGGING: g,
        DEFAULT_ITEM_EDITOR_WIDTH: 430,
        DEFAULT_PATH: A,
        EXPAND_WARNING_THRESHOLD: O,
        FLEXIBLE_API_BEHAVIORS: d,
        FLEXIBLE_TARGETING_API: S,
        FLEXIBLE_TARGETING_WARNING_MODE: R,
        ITEM_TYPE: c,
        MOCK_DATA: v,
        PRESENTER_ANIMATION: F,
        SPECIAL_PATHS: w,
        AUDIENCE_SIZE_LABEL_FBT: M,
        SUPPORT_TARGETING_TYPES: b,
        TARGETING_TYPE_TO_LABELS: h,
        TARGETING_TYPES_FROM_ENUM: C,
        VALID_ACCOUNT_LEVEL_EXCLUSIONS_TARGETING_TYPES: m,
        TARGETING_TYPES_FROM_SEARCH: y,
        USE_ENUM_TYPES: !1,
        USE_WORK_EDU_SEARCH_TYPES: !1,
        TARGETING_OEM_STORE: q,
        PRIMARY_LABEL: u._(/*BTDS*/ "Detailed targeting"),
        ADVANTAGE_DETAILED_TARGETING_PRIMARY_LABEL: u._(
          /*BTDS*/ "Advantage+ detailed targeting",
        ),
        INCLUDE_HEADER: u._(
          /*BTDS*/ "INCLUDE people who match at least ONE of the following",
        ),
        INCLUDE_HEADER_SIMPLIFIED: u._(/*BTDS*/ "Include people who match"),
        INCLUDE_AND_HEADER: u._(
          /*BTDS*/ "and MUST ALSO match at least ONE of the following",
        ),
        INCLUDE_AND_HEADER_SIMPLIFIED: u._(/*BTDS*/ "and must also match"),
        EXCLUDE_HEADER: u._(
          /*BTDS*/ "EXCLUDE people who match at least ONE of the following",
        ),
        EXCLUDE_HEADER_SIMPLIFIED: u._(/*BTDS*/ "Exclude people who match"),
        NUX_PAGE_HEADER: u._(/*BTDS*/ "Demographics, interests or behaviors"),
        NUX_PAGE_TEXT: u._(
          /*BTDS*/ "Now you can find all demographics, interests and behaviors in one place, then combine them in any way you want.",
        ),
        NUX_BUTTON_TEXT: u._(/*BTDS*/ "Get started"),
        DEFINE_SUBSET_HEADER: u._(/*BTDS*/ "Only include a subset"),
        DEFINE_SUBSET_DETAIL: u._(
          /*BTDS*/ "From the people in the audience above, only include people who also meet specific criteria. For example, you can choose parents above, and then narrow your audience to only include the ones who buy pet supplies.",
        ),
        TYPEAHEAD_PLACEHOLDER: u._(
          /*BTDS*/ "Add demographics, interests or behaviors",
        ),
        DETAILED_TARGETING_TOOLTIP: u._(
          /*BTDS*/ "Define your audience by including or excluding demographics, interests and behaviors.",
        ),
        DETAILED_TARGETING_TOOLTIP_DISABLE_EXCLUSION: u._(
          /*BTDS*/ "Define your audience by including demographics interests and behaviors.",
        ),
        OPT_OUT_DESCRIPTION: u._(
          /*BTDS*/ "This update lets you include and exclude demographics, interests and behaviors in any way you want. Switching back to the previous version will remove those options, so you can only combine targeting details within the same targeting types (ex: interests with interests or job titles with job titles).",
        ),
        OPT_OUT_HEADER: u._(/*BTDS*/ "Switch to the previous version?"),
        OPT_OUT_CONFIRM_QUESTION: u._(
          /*BTDS*/ "Are you sure you want to switch back? You will need to download your account and refresh the view to update your targeting controls.",
        ),
        OPT_OUT_CONFIRM_BUTTON: u._(/*BTDS*/ "Switch back"),
        NUX_PRESENTER_TEXT: u._(
          /*BTDS*/ "Adding more options here will make your audience bigger. To refine your audience, use the links below to exclude people or narrow based on other details.",
        ),
        NUX_PRESENTER_TITLE: u._(/*BTDS*/ "Tip"),
        LEARN_MORE_CMSID: "182371508761821",
        FLEXIBLE_TARGETING_NO_EDIT_INFO: u._(
          /*BTDS*/ "This ad set was created in a different interface using targeting options that are not available here. To edit your targeting, use the interface where you created this ad set.",
        ),
        FLEXIBLE_TARGETING_OPT_IN_STRING: u._(
          /*BTDS*/ "New detailed targeting controls let you include or exclude people based on any combination of demographics, interests and behaviors.",
        ),
        FLEXIBLE_TARGETING_OPT_IN_LINK: u._(/*BTDS*/ "Try it now."),
      };
    r("deepFreezeValue")(U);
    var V = U;
    l.default = V;
  },
  226,
);
