__d(
  "AdsGuidanceUnifiedEventsEvent",
  ["$InternalEnum"],
  function (t, n, r, o, a, i) {
    var e = n("$InternalEnum")({
        GUIDANCE_CARD_EXPLICIT_IMPRESSION: "guidance_card_explicit_impression",
        GUIDANCE_CARD_IMPLICIT_IMPRESSION: "guidance_card_implicit_impression",
        CTA_CLICK: "cta_click",
        GENERIC_INTERACTION: "generic_interaction",
        HOVER: "hover",
        LEARN_MORE: "learn_more",
        RADIO_BUTTON_SELECT: "radio_button_select",
        SAVE_TO_DESKTOP: "save_to_desktop",
        SEE_LESS: "see_less",
        SEE_MORE: "see_more",
        SHARE_VIA_EMAIL: "share_via_email",
        TOGGLE_OFF: "toggle_off",
        TOGGLE_ON: "toggle_on",
        TOGGLE_TAB_SELECTION: "toggle_tab_selection",
        TOOLTIP_SELECT_CTA: "tooltip_select_cta",
        AUTO_RESOLUTION_START: "auto_resolution_start",
        MANUAL_RESOLUTION_START: "manual_resolution_start",
        ONE_CLICK_APPLY_START: "one_click_apply_start",
        ONE_CLICK_RESOLUTION_START: "one_click_resolution_start",
        MANUAL_RESOLUTION_EDIT: "manual_resolution_edit",
        MANUAL_RESOLUTION_USER_INTERACT: "manual_resolution_user_interact",
        ONE_CLICK_RESOLUTION_EDIT: "one_click_resolution_edit",
        ONE_CLICK_RESOLUTION_USER_INTERACT:
          "one_click_resolution_user_interact",
        RESOLUTION_FLOW_IMPRESSION: "resolution_flow_impression",
        CANDIDATE_GENERATION_ERROR: "candidate_generation_error",
        DATA_LOAD_ERROR: "data_load_error",
        DATA_TRANSFORMATION_ERROR: "data_transformation_error",
        EXPERIMENTATION_ERROR: "experimentation_error",
        PUBLISH_ERROR: "publish_error",
        RENDERING_ERROR: "rendering_error",
        RESOLUTION_ERROR: "resolution_error",
        SHARE_VIA_EMAIL_ERROR: "share_via_email_error",
        STATE_TRANSITION_ERROR: "state_transition_error",
        AUTO_RESOLUTION: "auto_resolution",
        GUIDANCE_RESOLUTION_PUBLISH: "guidance_publish",
        INFERRED_RESOLUTION: "inferred_resolution",
        MANUAL_RESOLUTION: "manual_resolution",
        ONE_CLICK_APPLY: "one_click_apply",
        ONE_CLICK_RESOLUTION: "one_click_resolution",
        PCR_DRAFT_CREATION: "pcr_draft_creation",
        SAVE_TO_DRAFT: "save_to_draft",
        REC_DISMISS_DO_NOT_HAVE_TIME: "rec_dismiss_do_not_have_time",
        REC_DISMISS_DO_NOT_UNDERSTAND: "rec_dismiss_do_not_understand",
        REC_DISMISS_NOT_RELEVANT_FOR_BUSINESS:
          "rec_dismiss_not_relevant_for_business",
        DESELECT_RECOMMENDATION: "deselect_recommendation",
        MANUAL_RESOLUTION_FLOW_ABANDON: "manual_resolution_flow_abandon",
        ONE_CLICK_APPLY_ABANDON: "one_click_apply_abandon",
        ONE_CLICK_RESOLUTION_FLOW_ABANDON: "one_click_resolution_flow_abandon",
        REC_DISMISS: "rec_dismiss",
        INVALIDATION: "invalidation",
        QUALIFICATION: "qualification",
        RENDER_DECISION: "render_decision",
        GENERIC_NAVIGATION: "generic_navigation",
        SEE_ALL_RECOMMENDATIONS: "see_all_recommendations",
        SEE_LESS_RECOMMENDATIONS: "see_less_recommendations",
        SEE_MORE_RECOMMENDATIONS: "see_more_recommendations",
        SEE_RECOMMENDATIONS: "see_recommendations",
        ACTIVATE_RULE: "activate_rule",
        CREATE_RULE: "create_rule",
        PAUSE_RULE: "pause_rule",
        AUTO_RESOLUTION_ATTEMPT: "auto_resolution_attempt",
        AUTO_RESOLUTION_GEN_FILTER: "auto_resolution_gen_filter",
        AUTO_RESOLUTION_VALIDATION_ERROR: "auto_resolution_validation_error",
        FILTER_PREVIOUSLY_APPLIED: "filter_previously_applied",
        CRM_CLOSED_LOST_AD_STRATEGY_UNFIT: "crm_closed_lost_ad_strategy_unfit",
        CRM_CLOSED_LOST_AGENCY_RELATIONSHIP:
          "crm_closed_lost_agency_relationship",
        CRM_CLOSED_LOST_ALREADY_PITCHED: "crm_closed_lost_already_pitched",
        CRM_CLOSED_LOST_BRAND_SAFETY_CONCERNS:
          "crm_closed_lost_brand_safety_concerns",
        CRM_CLOSED_LOST_BUSY_WITH_OTHER_OPPORTUNITIES:
          "crm_closed_lost_busy_with_other_opportunities",
        CRM_CLOSED_LOST_CLIENT_BUDGET_UNAVAILABLE:
          "crm_closed_lost_client_budget_unavailable",
        CRM_CLOSED_LOST_CLIENT_RELATIONSHIP:
          "crm_closed_lost_client_relationship",
        CRM_CLOSED_LOST_CURRENT_PERFORMANCE_SATISFACTORY:
          "crm_closed_lost_current_performance_satisfactory",
        CRM_CLOSED_LOST_DUPLICATED_INITIATIVE:
          "crm_closed_lost_duplicated_initiative",
        CRM_CLOSED_LOST_INADEQUATE_COLLATERALS:
          "crm_closed_lost_inadequate_collaterals",
        CRM_CLOSED_LOST_LEADERSHIP_CHANGE: "crm_closed_lost_leadership_change",
        CRM_CLOSED_LOST_LEGAL_COMPLIANCE_ISSUES:
          "crm_closed_lost_legal_compliance_issues",
        CRM_CLOSED_LOST_MISSING_PRODUCT_FEATURE:
          "crm_closed_lost_missing_product_feature",
        CRM_CLOSED_LOST_NO_XFN_RESOURCES: "crm_closed_lost_no_xfn_resources",
        CRM_CLOSED_LOST_PLATFORM_STABILITY:
          "crm_closed_lost_platform_stability",
        CRM_CLOSED_LOST_RESOURCES: "crm_closed_lost_resources",
        CRM_CLOSED_LOST_SALES_BANDWIDTH: "crm_closed_lost_sales_bandwidth",
        CRM_CLOSED_LOST_TECHNICAL_ISSUES: "crm_closed_lost_technical_issues",
        CRM_CLOSED_LOST_UNFAVORABLE_MEASUREMENT_RESULTS:
          "crm_closed_lost_unfavorable_measurement_results",
        CRM_PUSH: "crm_push",
        PITCH_PLANNER_TREATMENT_PITCH: "pitch_planner_treatment_pitch",
        PITCH_WIZARD_TREATMENT_PITCH: "pitch_wizard_treatment_pitch",
        META_PRO_PITCH_PILL_IMPRESSION: "meta_pro_pitch_pill_impression",
        GK_EXPOSURE: "gk_exposure",
        QE_EXPOSURE: "qe_exposure",
        SERVER_CHECKED_QE_EXPOSURE: "server_checked_qe_exposure",
        COMPARISON: "comparison",
        REQUEST_RECEIVED: "request_received",
        REQUEST_TRIGGERED: "request_triggered",
        RESPONSE_READY: "response_ready",
        RESPONSE_RECEIVED: "response_received",
        QUALIFIED: "qualified",
        APPLIED: "applied",
        EMPTY_SCORE: "empty_score",
        GUIDANCE_CARD_HIDDEN: "guidance_card_hidden",
        MISSING_OPPORTUNITY_SCORE: "missing_opportunity_score",
        OPPORTUNITY_SCORE_LOADED: "opportunity_score_loaded",
        OUTCOME_PREDICTION_LOADED: "outcome_prediction_loaded",
        RANKING_SCORE_UNIQUENESS_CHECK_PASSED:
          "ranking_score_uniqueness_check_passed",
        TOTAL_OPPORTUNITY_SCORE_NOT_100: "total_opportunity_score_not_100",
        UGP_RECOMMENDATIONS_LOADED: "ugp_recommendations_loaded",
        SHADOW_LOGGING: "shadow_logging",
        REC_RETRIEVE: "rec_retrieve",
        GUIDANCE_PUBLISH_SUCCESS: "guidance_publish_success",
        GUIDANCE_PUBLISH_FAILED: "guidance_publish_failed",
        ADOPTING_ADVERTISER_COUNT_INSIGHT_AVAILABLE:
          "adopting_advertiser_count_insight_available",
        ADOPTING_ADVERTISER_COUNT_INSIGHT_ERROR:
          "adopting_advertiser_count_insight_error",
        ADOPTING_ADVERTISER_COUNT_INSIGHT_IMPRESSION:
          "adopting_advertiser_count_insight_impression",
        ADOPTING_ADVERTISER_COUNT_INSIGHT_UNAVAILABLE:
          "adopting_advertiser_count_insight_unavailable",
        BABT_INSIGHT_AVAILABLE: "babt_insight_available",
        BABT_INSIGHT_ERROR: "babt_insight_error",
        BABT_INSIGHT_UNAVAILABLE: "babt_insight_unavailable",
        CIB_DOTTED_UNDERLINE_IMPRESSION: "cib_dotted_underline_impression",
        CLOSE_THE_LOOP_INSIGHT_AVAILABLE: "close_the_loop_insight_available",
        CLOSE_THE_LOOP_INSIGHT_ERROR: "close_the_loop_insight_error",
        CLOSE_THE_LOOP_INSIGHT_UNAVAILABLE:
          "close_the_loop_insight_unavailable",
        COMPETITIVE_INDUSTRY_BENCHMARK_INSIGHT_AVAILABLE:
          "competitive_industry_benchmark_insight_available",
        COMPETITIVE_INDUSTRY_BENCHMARK_INSIGHT_ERROR:
          "competitive_industry_benchmark_insight_error",
        COMPETITIVE_INDUSTRY_BENCHMARK_INSIGHT_FETCH_CONTENT:
          "competitive_industry_benchmark_insight_fetch_content",
        COMPETITIVE_INDUSTRY_BENCHMARK_INSIGHT_HOVER:
          "competitive_industry_benchmark_insight_hover",
        COMPETITIVE_INDUSTRY_BENCHMARK_INSIGHT_IMPRESSION:
          "competitive_industry_benchmark_insight_impression",
        COMPETITIVE_INDUSTRY_BENCHMARK_INSIGHT_UNAVAILABLE:
          "competitive_industry_benchmark_insight_unavailable",
        MR_PLE_INSIGHT_AVAILABLE: "mr_ple_insight_available",
        MR_PLE_INSIGHT_ERROR: "mr_ple_insight_error",
        MR_PLE_INSIGHT_UNAVAILABLE: "mr_ple_insight_unavailable",
        PLE_BAU_INSIGHT_AVAILABLE: "ple_bau_insight_available",
        PLE_BAU_INSIGHT_ERROR: "ple_bau_insight_error",
        PLE_BAU_INSIGHT_FETCH_CONTENT: "ple_bau_insight_fetch_content",
        PLE_BAU_INSIGHT_UNAVAILABLE: "ple_bau_insight_unavailable",
        PLE_V2_INSIGHT_DATA_AVAILABILITY: "ple_v2_insight_data_availability",
        PLE_V2_INSIGHT_DATA_AVAILABILITY_COMPARE:
          "ple_v2_insight_data_availability_compare",
        PLE_V2_INSIGHT_FETCH_CONTENT: "ple_v2_insight_fetch_content",
        PLE_V2_INSIGHT_IMPRESSION: "ple_v2_insight_impression",
        GUIDANCE_CARD_CONTENT_IMPRESSION: "guidance_card_content_impression",
        APPLY_API_FAILURE: "apply_api_failure",
        APPLY_API_INVALID_REQUEST: "apply_api_invalid_request",
        APPLY_API_SUCCESS: "apply_api_success",
      }),
      l = e;
    i.default = l;
  },
  66,
);
