__d(
  "AdsGuidanceUnifiedEventsSurface",
  ["$InternalEnum"],
  function (t, n, r, o, a, i) {
    var e = n("$InternalEnum")({
        ADS_MANAGER: "ads_manager",
        ADS_MANAGER_APP: "ads_manager_app",
        AI_AGENT: "ai_agent",
        AUTO_APPLY_RULE: "auto_apply_rule",
        EMAIL: "email",
        EVENTS_MANAGER: "events_manager",
        FB_FEED_PROFILE: "fb_feed_profile",
        GITS_DEBUGGER: "gits_debugger",
        IN_PRODUCT_MESSAGE: "in_product_message",
        JEWEL_NOTIFICATION: "jewel_notification",
        LWI: "lightweight_interfaces",
        MAPI: "marketing_api",
        MARKETING_CAMPAIGNS: "marketing_campaigns",
        MARKETING_PROACTIVE_CHAT: "marketing_proactive_chat",
        MBS: "meta_business_suite",
        META_BUSINESS_PARTNERS: "meta_business_partners",
        PARTNER_CENTER_MBP: "partner_center_mbp",
        PARTNER_CENTER_RESELLER: "partner_center_reseller",
        PITCH_PLANNER: "pitch_planner",
        PITCH_WIZARD: "pitch_wizard",
        PROACTIVE_CHAT: "proactive_chat",
        SALES_GUIDANCE_PLATFORM: "sales_guidance_platform",
        SHOPIFY_META_APP: "shopify_meta_app",
        SOLUTIONS_JOURNEY: "solutions_journey",
        TEST: "test",
        ADS_AI: "ads_ai",
        ADS_REPORTING: "ads_reporting",
        AUTO_RULES: "auto_rules",
        PARTNER_DIRECTORY: "partner_directory",
        SALES_CRM: "sales_crm",
      }),
      l = e;
    i.default = l;
  },
  66,
);
