__d(
  "AdsInsightsMetricAvailableLevels",
  [],
  function (t, n, r, o, a, i) {
    var e = Object.freeze({
      budget: ["adset", "campaign"],
      impressions_goal: ["campaign", "adset"],
      schedule: ["adset"],
      adgroup_id: ["ad"],
      buying_type: ["campaign"],
      campaign_budget_value: ["adset"],
      campaign_id: ["adset", "ad"],
      action_destination: ["ad"],
      objective: ["campaign", "ad"],
      "actions:schedule": ["adset"],
      "relevance_score:negative_feedback": ["ad"],
      "relevance_score:positive_feedback": ["ad"],
      "relevance_score:score": ["ad"],
      quality_score_ectr: ["ad"],
      quality_score_ecvr: ["ad"],
      quality_score_organic: ["ad"],
      age_targeting: ["adset"],
      body: ["ad"],
      budget_remaining: ["adset", "campaign"],
      budget_pool_value_multiplier: ["adset"],
      budget_pool_shared_budget: ["adset"],
      budget_pool_value_weighted_conversions: ["adset"],
      budget_pool_value_weighted_cpa: ["adset"],
      destination: ["ad"],
      gender_targeting: ["adset"],
      labels: ["campaign"],
      location: ["adset"],
      preview_link: ["ad"],
      related_page: ["ad"],
      spent_percent: ["adset", "campaign"],
      elapsed: ["adset"],
      title: ["ad"],
      url_tags: ["ad"],
      conversion_tracking_pixel: ["ad"],
      app_tracking_event: ["ad"],
      offline_tracking_event: ["ad"],
      custom_audiences: ["adset"],
      excluded_custom_audiences: ["adset"],
      spend_limit: ["campaign"],
      conversion_location: ["adset", "ad"],
      performance_goal: ["adset"],
      agency_fee_markup: ["campaign"],
      agency_fee_amount: ["campaign"],
      billable_amount_spent: ["campaign"],
    });
    i.default = e;
  },
  66,
);
