__d(
  "AdsInsightsUnitValueLabelsStatic",
  ["fbt"],
  function (t, n, r, o, a, i, l) {
    a.exports = {
      ad_click: l._(/*BTDS*/ "Value, In-App Ad Click"),
      ad_click_mobile_app: null,
      ad_click_offline: null,
      ad_click_on_facebook: null,
      ad_click_total: null,
      ad_click_website: null,
      ad_impression: l._(/*BTDS*/ "Value, In-app ad impressions"),
      ad_impression_mobile_app: l._(/*BTDS*/ "Value, In-app ad impressions"),
      ad_impression_offline: null,
      ad_impression_on_facebook: null,
      ad_impression_total: null,
      ad_impression_website: null,
      add_payment_info: l._(/*BTDS*/ "Value, Add of Payment Info"),
      add_to_cart: l._(/*BTDS*/ "Value, Add to cart (website and in-app)"),
      add_to_cart_with_shared_items: l._(
        /*BTDS*/ "Value, Add to cart with shared items (website and in-app)",
      ),
      add_to_wishlist: l._(/*BTDS*/ "Value, Add To Wishlist"),
      app_custom_event: l._(/*BTDS*/ "Value, In-app action"),
      "app_custom_event.fb_mobile_achievement_unlocked": l._(
        /*BTDS*/ "Value, In-app feature unlock",
      ),
      "app_custom_event.fb_mobile_activate_app": l._(
        /*BTDS*/ "Value, In-app start",
      ),
      "app_custom_event.fb_mobile_add_payment_info": l._(
        /*BTDS*/ "Value, In-app payment detail",
      ),
      "app_custom_event.fb_mobile_add_to_cart": l._(
        /*BTDS*/ "Value, In-app add to cart",
      ),
      "app_custom_event.fb_mobile_add_to_cart_with_shared_items": l._(
        /*BTDS*/ "Value, In-app add to cart with shared items",
      ),
      "app_custom_event.fb_mobile_add_to_wishlist": l._(
        /*BTDS*/ "Value, In-app add to wishlist",
      ),
      "app_custom_event.fb_mobile_complete_registration": l._(
        /*BTDS*/ "Value, In-app registration",
      ),
      "app_custom_event.fb_mobile_content_view": l._(
        /*BTDS*/ "Value, In-app content view",
      ),
      "app_custom_event.fb_mobile_content_view_with_shared_items": l._(
        /*BTDS*/ "Value, In-app content view with shared items",
      ),
      "app_custom_event.fb_mobile_d2_retention": l._(
        /*BTDS*/ "Value, Mobile App Day 2 Retention",
      ),
      "app_custom_event.fb_mobile_d7_retention": l._(
        /*BTDS*/ "Value, Mobile App Day 7 Retention",
      ),
      "app_custom_event.fb_mobile_initiated_checkout": l._(
        /*BTDS*/ "Value, In-app checkout",
      ),
      "app_custom_event.fb_mobile_level_achieved": l._(
        /*BTDS*/ "Value, In-app achievement",
      ),
      "app_custom_event.fb_mobile_purchase": l._(
        /*BTDS*/ "Value, In-app purchase",
      ),
      "app_custom_event.fb_mobile_purchase_with_shared_items": l._(
        /*BTDS*/ "Value, In-app purchase with shared items",
      ),
      "app_custom_event.fb_mobile_rate": l._(/*BTDS*/ "Value, In-app rating"),
      "app_custom_event.fb_mobile_search": l._(/*BTDS*/ "Value, In-app search"),
      "app_custom_event.fb_mobile_spent_credits": l._(
        /*BTDS*/ "Value, In-app credit spend",
      ),
      "app_custom_event.fb_mobile_tutorial_completion": l._(
        /*BTDS*/ "Value, In-app tutorial completion",
      ),
      "app_custom_event.other": l._(/*BTDS*/ "Value, Other in-app action"),
      "app_custom_event.subscribe": null,
      app_engagement: l._(/*BTDS*/ "Value, App Engagement"),
      app_install: l._(/*BTDS*/ "Value, App Install"),
      app_site_visit: null,
      app_store_visit: null,
      app_story: l._(/*BTDS*/ "Value, App story"),
      app_use: l._(/*BTDS*/ "Value, App Use"),
      ar_effect_share: null,
      attention_event: l._(/*BTDS*/ "Value, Attention Impression"),
      cancel_subscription: null,
      cancel_subscription_mobile_app: null,
      cancel_subscription_offline: null,
      cancel_subscription_on_facebook: null,
      cancel_subscription_total: null,
      cancel_subscription_website: null,
      canvas_view: l._(/*BTDS*/ "Value, Canvas Component View"),
      card_view: l._(/*BTDS*/ "Value, Card View"),
      carousel_view: l._(/*BTDS*/ "Value, Carousel View"),
      checkin: l._(/*BTDS*/ "Value, Check-in"),
      click: l._(/*BTDS*/ "Click Value"),
      click_to_album: null,
      click_to_call_call_confirm: l._(
        /*BTDS*/ "Value, Estimated Call Confirmation Click",
      ),
      click_to_call_callback_request_submitted: null,
      click_to_call_native_20s_call_connect: l._(
        /*BTDS*/ "Value, 20-second Call",
      ),
      click_to_call_native_60s_call_connect: null,
      click_to_call_native_call_connect: null,
      click_to_call_native_call_placed: null,
      click_to_camera_effects: null,
      click_to_event: null,
      click_to_flyout: null,
      click_to_group: null,
      click_to_hashtag: null,
      click_to_hashtag_attempt: null,
      click_to_link_attempt: null,
      click_to_location_attempt: null,
      click_to_marketplace: null,
      click_to_others: null,
      click_to_page: null,
      click_to_permalink: null,
      click_to_profile: null,
      click_to_profile_attempt: null,
      click_to_story: null,
      comment: l._(/*BTDS*/ "Value, Post Comment"),
      commerce_event: l._(/*BTDS*/ "Value, Commerce Action"),
      "commerce_event.add_to_cart": l._(/*BTDS*/ "Value, Commerce Add to Cart"),
      "commerce_event.message_to_buy": l._(
        /*BTDS*/ "Value, Commerce Message To Buy",
      ),
      "commerce_event.other": l._(/*BTDS*/ "Value, Other Commerce Action"),
      "commerce_event.purchase": l._(/*BTDS*/ "Value, Commerce Purchase"),
      "commerce_event.view_content": l._(
        /*BTDS*/ "Value, Commerce Product View",
      ),
      complete_registration: l._(
        /*BTDS*/ "Value, Complete registration (website and in-app)",
      ),
      contact: l._(/*BTDS*/ "Value, Contact (website and in-app)"),
      contact_mobile_app: l._(/*BTDS*/ "Value, In-app contact"),
      contact_offline: l._(/*BTDS*/ "Value, Offline Contact"),
      contact_on_facebook: null,
      contact_total: null,
      contact_value: null,
      contact_website: l._(/*BTDS*/ "Value, Website Contact"),
      conversion_lead: l._(/*BTDS*/ "Value, Conversion lead"),
      credit_spent: l._(/*BTDS*/ "Value, Credit Spend"),
      custom_event_actions_add_meta_leads: null,
      custom_event_actions_add_meta_leads_multi_label: null,
      customize_product: l._(
        /*BTDS*/ "Value, Customize product (website and in-app)",
      ),
      customize_product_mobile_app: l._(
        /*BTDS*/ "Value, In-app customize product",
      ),
      customize_product_offline: l._(
        /*BTDS*/ "Value, Offline Customize Product",
      ),
      customize_product_on_facebook: null,
      customize_product_total: null,
      customize_product_value: null,
      customize_product_website: l._(
        /*BTDS*/ "Value, Website Customize Product",
      ),
      donate: l._(/*BTDS*/ "Value, Donate (website and in-app)"),
      donate_mobile_app: l._(/*BTDS*/ "Value, In-app donate"),
      donate_offline: l._(/*BTDS*/ "Value, Offline Donate"),
      donate_on_facebook: l._(/*BTDS*/ "Value, On-Facebook Donate"),
      donate_total: null,
      donate_value: null,
      donate_website: l._(/*BTDS*/ "Value, Website Donate"),
      dwell: l._(/*BTDS*/ "Value, Page Dwell"),
      engaged_page_view: null,
      "engaged_page_view.in_app_browser": null,
      "engaged_page_view.system_browser": null,
      estimatedAdRecall: l._(/*BTDS*/ "Ad recall lift value"),
      find_location: l._(/*BTDS*/ "Value, Find location (website and in-app)"),
      find_location_mobile_app: l._(/*BTDS*/ "Value, In-app find location"),
      find_location_offline: l._(/*BTDS*/ "Value, Offline Find Location"),
      find_location_on_facebook: null,
      find_location_total: null,
      find_location_value: null,
      find_location_website: l._(/*BTDS*/ "Value, Website Find Location"),
      follow: l._(/*BTDS*/ "Value, Question Follow"),
      "games.plays": l._(/*BTDS*/ "Value, Game Play"),
      gift_sale: l._(/*BTDS*/ "Value, Facebook Gift Sale"),
      group_join: null,
      grouped_pixel_custom_conversions_meta_leads: null,
      grouped_pixel_custom_conversions_meta_leads_multi_label: null,
      impression: l._(/*BTDS*/ "Impression Value"),
      initiate_checkout: l._(
        /*BTDS*/ "Value, Initiate checkout (website and in-app)",
      ),
      instagram_profile_engagement: l._(/*BTDS*/ "Value, Post HIA"),
      instagram_upcoming_event_reminder_toggle_on: l._(
        /*BTDS*/ "Value, Reminder",
      ),
      instant_experience_element_impression: null,
      interactive_component_tap: l._(
        /*BTDS*/ "Value, Interactive Component Tap",
      ),
      kiloDwell: l._(/*BTDS*/ "1,000 Dwells Value"),
      kiloImpression: l._(/*BTDS*/ "1,000 Impressions Value"),
      kiloReach: l._(/*BTDS*/ "1,000 People Reached Value"),
      landing_page_view: l._(/*BTDS*/ "Value, Landing Page View"),
      lead: l._(/*BTDS*/ "Value, Lead"),
      "leadgen.other": l._(/*BTDS*/ "Value, Lead (Form)"),
      leadgen_grouped: l._(/*BTDS*/ "Value, Lead (Form)"),
      leadgen_qualifying_question_answer: null,
      leadgen_quality_conversion: null,
      like: l._(/*BTDS*/ "Value, Follow or like"),
      link_click: l._(/*BTDS*/ "Value, Link Click"),
      mention: l._(/*BTDS*/ "Value, Page Mention"),
      "messenger.block": l._(/*BTDS*/ "Value, Message Block"),
      "messenger.reply": l._(/*BTDS*/ "Value, Message Reply"),
      mobile_app_install: l._(/*BTDS*/ "Value, Mobile App Install"),
      mobile_app_install_conversion: null,
      mobile_app_retention: null,
      mobile_app_roas: null,
      new_mobile: l._(/*BTDS*/ "Value, Newly Purchased Mobile Device"),
      offline_conversion: l._(/*BTDS*/ "Value, Conversion"),
      "offline_conversion.add_payment_info": l._(
        /*BTDS*/ "Value, Add Payment Info",
      ),
      "offline_conversion.add_to_cart": l._(/*BTDS*/ "Value, Add To Cart"),
      "offline_conversion.add_to_wishlist": l._(
        /*BTDS*/ "Value, Add To Wishlist",
      ),
      "offline_conversion.complete_registration": l._(
        /*BTDS*/ "Value, Complete Registration",
      ),
      "offline_conversion.contact": null,
      "offline_conversion.initiate_checkout": l._(
        /*BTDS*/ "Value, Initiate Checkout",
      ),
      "offline_conversion.lead": l._(/*BTDS*/ "Value, Lead"),
      "offline_conversion.other": l._(/*BTDS*/ "Value, Other"),
      "offline_conversion.purchase": l._(/*BTDS*/ "Value, Purchase (In-store)"),
      "offline_conversion.purchase_with_shared_items": l._(
        /*BTDS*/ "Value, Purchase with Shared Items",
      ),
      "offline_conversion.search": l._(/*BTDS*/ "Value, Search"),
      "offline_conversion.subscribe": null,
      "offline_conversion.view_content": l._(/*BTDS*/ "Value, View Content"),
      offsite_add_to_cart_add_20_s_calls: null,
      offsite_add_to_cart_add_20_s_calls_multi_label: null,
      offsite_complete_registration_add_20_s_calls: null,
      offsite_complete_registration_add_20_s_calls_multi_label: null,
      offsite_complete_registration_add_meta_leads: null,
      offsite_complete_registration_add_meta_leads_multi_label: null,
      offsite_contact_website_add_meta_leads: null,
      offsite_contact_website_add_meta_leads_multi_label: null,
      offsite_content_view_add_20_s_calls: null,
      offsite_content_view_add_20_s_calls_multi_label: null,
      offsite_content_view_add_meta_leads: null,
      offsite_content_view_add_meta_leads_multi_label: null,
      offsite_conversion: l._(/*BTDS*/ "Value, Conversion"),
      "offsite_conversion.add_to_cart": l._(/*BTDS*/ "Value, Add to Cart"),
      "offsite_conversion.checkout": l._(/*BTDS*/ "Value, Checkout"),
      "offsite_conversion.custom": null,
      "offsite_conversion.fb_pixel_add_payment_info": l._(
        /*BTDS*/ "Value, Add Payment Info",
      ),
      "offsite_conversion.fb_pixel_add_to_cart": l._(
        /*BTDS*/ "Value, Add To Cart",
      ),
      "offsite_conversion.fb_pixel_add_to_cart_with_shared_items": l._(
        /*BTDS*/ "Value, Website Add To Cart with Shared Items",
      ),
      "offsite_conversion.fb_pixel_add_to_wishlist": l._(
        /*BTDS*/ "Value, Add To Wishlist",
      ),
      "offsite_conversion.fb_pixel_complete_registration": l._(
        /*BTDS*/ "Value, Complete Registration",
      ),
      "offsite_conversion.fb_pixel_custom": null,
      "offsite_conversion.fb_pixel_custom_pltv": null,
      "offsite_conversion.fb_pixel_initiate_checkout": l._(
        /*BTDS*/ "Value, Initiate Checkout",
      ),
      "offsite_conversion.fb_pixel_lead": l._(/*BTDS*/ "Value, Lead"),
      "offsite_conversion.fb_pixel_other": l._(/*BTDS*/ "Value, Other"),
      "offsite_conversion.fb_pixel_other_product_set_purchases": null,
      "offsite_conversion.fb_pixel_prioritized_product_set_purchases": null,
      "offsite_conversion.fb_pixel_purchase": l._(/*BTDS*/ "Value, Purchase"),
      "offsite_conversion.fb_pixel_purchase_with_shared_items": l._(
        /*BTDS*/ "Value, Website Purchase with Shared Items",
      ),
      "offsite_conversion.fb_pixel_search": l._(
        /*BTDS*/ "Value, Website search",
      ),
      "offsite_conversion.fb_pixel_view_content": l._(
        /*BTDS*/ "Value, View Content",
      ),
      "offsite_conversion.fb_pixel_view_content_with_shared_items": l._(
        /*BTDS*/ "Value, Website View Content with Shared Items",
      ),
      "offsite_conversion.key_page_view": l._(/*BTDS*/ "Value, Key Page View"),
      "offsite_conversion.lead": l._(/*BTDS*/ "Value, Lead"),
      "offsite_conversion.margin": null,
      "offsite_conversion.other": l._(
        /*BTDS*/ "Value, Other Website Conversion",
      ),
      "offsite_conversion.predictive_life_time_value": null,
      "offsite_conversion.purchase": null,
      "offsite_conversion.registration": l._(/*BTDS*/ "Value, Registration"),
      "offsite_conversion.shops_to_website_purchase": null,
      "offsite_conversion.viewcontent": null,
      offsite_engagement: l._(/*BTDS*/ "Value, Engagement"),
      offsite_initiate_checkout_add_20_s_calls: null,
      offsite_initiate_checkout_add_20_s_calls_multi_label: null,
      offsite_lead_add_20_s_calls: null,
      offsite_lead_add_20_s_calls_multi_label: null,
      offsite_mobile_app_conversion: null,
      offsite_purchase_add_20_s_calls: null,
      offsite_purchase_add_20_s_calls_multi_label: null,
      offsite_search_add_meta_leads: null,
      offsite_search_add_meta_leads_multi_label: null,
      offsite_submit_application_add_meta_leads: null,
      offsite_submit_application_add_meta_leads_multi_label: null,
      omni_achievement_unlocked: l._(/*BTDS*/ "Value, Level Achieved"),
      omni_activate_app: l._(/*BTDS*/ "Value, App Activation"),
      omni_add_payment_info_pltv: null,
      omni_add_to_cart: l._(/*BTDS*/ "Value, Add To Cart"),
      omni_add_to_cart_with_shared_items: l._(
        /*BTDS*/ "Value, Add To Cart with Shared Items",
      ),
      omni_add_to_wishlist: null,
      omni_app_install: l._(/*BTDS*/ "Value, App Install"),
      omni_app_install_pltv: l._(/*BTDS*/ "pLTV, App installs"),
      omni_complete_registration: l._(/*BTDS*/ "Value, Registration Completed"),
      omni_complete_registration_pltv: l._(
        /*BTDS*/ "pLTV, Registrations completed",
      ),
      omni_custom: l._(/*BTDS*/ "Value, Custom event (in-app)"),
      omni_initiated_checkout: l._(/*BTDS*/ "Value, Checkout Initiated"),
      omni_landing_page_view: null,
      omni_level_achieved: l._(/*BTDS*/ "Value, Level Achieved"),
      omni_purchase: l._(/*BTDS*/ "Value, Purchase"),
      omni_purchase_margin: l._(/*BTDS*/ "Margin, Purchases"),
      omni_purchase_pltv: l._(/*BTDS*/ "pLTV, Purchases"),
      omni_purchase_with_shared_items: l._(
        /*BTDS*/ "Value, Purchase with Shared Items",
      ),
      omni_rate: l._(/*BTDS*/ "Value, Rating"),
      omni_search: l._(/*BTDS*/ "Value, Search"),
      omni_spend_credits: l._(/*BTDS*/ "Value, Credit Spend"),
      omni_tutorial_completion: l._(/*BTDS*/ "Value, Tutorial Completion"),
      omni_view_content: l._(/*BTDS*/ "Value, Content View"),
      omni_view_content_with_shared_items: l._(
        /*BTDS*/ "Value, Content View with Shared Items",
      ),
      one_pd_landing_page_view: null,
      "one_pd_landing_page_view.in_app_browser": null,
      "one_pd_landing_page_view.system_browser": null,
      onsite_app_add_to_cart: l._(
        /*BTDS*/ "Value, Add to cart (Meta and in-app)",
      ),
      onsite_app_purchase: l._(/*BTDS*/ "Value, Purchase (Meta and in-app)"),
      onsite_app_view_content: l._(
        /*BTDS*/ "Value, Content view (Meta and in-app)",
      ),
      onsite_conversion: l._(/*BTDS*/ "Value, Conversion"),
      "onsite_conversion.add_payment_info": null,
      "onsite_conversion.add_to_cart": null,
      "onsite_conversion.add_to_wishlist": null,
      "onsite_conversion.cart_impression": null,
      "onsite_conversion.click_to_call": null,
      "onsite_conversion.complete_registration": null,
      "onsite_conversion.creator_link_click": null,
      "onsite_conversion.creator_media_impression": null,
      "onsite_conversion.engaged_page_view": null,
      "onsite_conversion.find_location": null,
      "onsite_conversion.flow_complete": null,
      "onsite_conversion.initiate_checkout": l._(
        /*BTDS*/ "Value, Initiate Checkout",
      ),
      "onsite_conversion.initiate_offsite_checkout": null,
      "onsite_conversion.lead": null,
      "onsite_conversion.lead_custom_event": null,
      "onsite_conversion.lead_grouped": l._(
        /*BTDS*/ "Value, On-Facebook Leads",
      ),
      "onsite_conversion.leads_center_lead_disqualified": null,
      "onsite_conversion.level_achieved": null,
      "onsite_conversion.message_to_buy": null,
      "onsite_conversion.messaging_20s_call_connect": l._(
        /*BTDS*/ "Value, 20-second Messenger Call",
      ),
      "onsite_conversion.messaging_60s_call_connect": null,
      "onsite_conversion.messaging_accept": null,
      "onsite_conversion.messaging_appointment_booked": null,
      "onsite_conversion.messaging_automated_flow_complete": null,
      "onsite_conversion.messaging_block": l._(
        /*BTDS*/ "Value, New Blocked Messaging Connections",
      ),
      "onsite_conversion.messaging_business_calling_call_answered": null,
      "onsite_conversion.messaging_business_calling_call_denied": null,
      "onsite_conversion.messaging_business_calling_call_initiated": null,
      "onsite_conversion.messaging_business_calling_call_missed": null,
      "onsite_conversion.messaging_business_calling_opt_in_accepted": null,
      "onsite_conversion.messaging_business_calling_opt_in_denied": null,
      "onsite_conversion.messaging_business_calling_opt_in_sent": null,
      "onsite_conversion.messaging_business_llama_conversion_negative": null,
      "onsite_conversion.messaging_business_llama_conversion_positive": null,
      "onsite_conversion.messaging_conversation_depth": null,
      "onsite_conversion.messaging_conversation_engaged": null,
      "onsite_conversion.messaging_conversation_replied_7d": null,
      "onsite_conversion.messaging_conversation_seller_feedback_dissatisfied":
        null,
      "onsite_conversion.messaging_conversation_seller_feedback_satisfied":
        null,
      "onsite_conversion.messaging_conversation_started_7d": l._(
        /*BTDS*/ "Value, Messaging Conversation Started",
      ),
      "onsite_conversion.messaging_dedup_deep_conversation": null,
      "onsite_conversion.messaging_deep_conversation": null,
      "onsite_conversion.messaging_deep_conversation_shadow": null,
      "onsite_conversion.messaging_delete_message": null,
      "onsite_conversion.messaging_delete_thread": null,
      "onsite_conversion.messaging_delivery_receipt": null,
      "onsite_conversion.messaging_event_optimization_lead": null,
      "onsite_conversion.messaging_first_biz_reply": null,
      "onsite_conversion.messaging_first_biz_reply_continuation": null,
      "onsite_conversion.messaging_first_call": null,
      "onsite_conversion.messaging_first_long_call": null,
      "onsite_conversion.messaging_first_reply": null,
      "onsite_conversion.messaging_first_reply_continuation": null,
      "onsite_conversion.messaging_frx_feedback": null,
      "onsite_conversion.messaging_ig_buyer_dissatisfied_with_conversation":
        null,
      "onsite_conversion.messaging_ig_buyer_satisfied_with_conversation": null,
      "onsite_conversion.messaging_ignore_request": null,
      "onsite_conversion.messaging_in_thread_dxma_feedback_dissatisfied": null,
      "onsite_conversion.messaging_in_thread_dxma_feedback_satisfied": null,
      "onsite_conversion.messaging_in_thread_feedback_dissatisfied": null,
      "onsite_conversion.messaging_in_thread_feedback_dissatisfied_confusing_process":
        null,
      "onsite_conversion.messaging_in_thread_feedback_dissatisfied_not_helpful":
        null,
      "onsite_conversion.messaging_in_thread_feedback_dissatisfied_other": null,
      "onsite_conversion.messaging_in_thread_feedback_dissatisfied_slow_responses":
        null,
      "onsite_conversion.messaging_in_thread_feedback_dissatisfied_suspicious_behavior":
        null,
      "onsite_conversion.messaging_in_thread_feedback_dissatisfied_too_many_messages":
        null,
      "onsite_conversion.messaging_in_thread_feedback_satisfied": null,
      "onsite_conversion.messaging_mark_spam": null,
      "onsite_conversion.messaging_missed_call": null,
      "onsite_conversion.messaging_msgr_buyer_dissatisfied_with_purchase": null,
      "onsite_conversion.messaging_msgr_buyer_satisfied_with_purchase": null,
      "onsite_conversion.messaging_open_thread": null,
      "onsite_conversion.messaging_order_created_v2": null,
      "onsite_conversion.messaging_order_shipped_v2": null,
      "onsite_conversion.messaging_page_call_attempted": null,
      "onsite_conversion.messaging_page_depth_2_message_send": null,
      "onsite_conversion.messaging_page_depth_2_message_send_continuation":
        null,
      "onsite_conversion.messaging_page_send": null,
      "onsite_conversion.messaging_page_send_after_user_send": null,
      "onsite_conversion.messaging_page_send_num_same_conversation": null,
      "onsite_conversion.messaging_promotional_off": null,
      "onsite_conversion.messaging_qualified_lead": null,
      "onsite_conversion.messaging_read_receipt": null,
      "onsite_conversion.messaging_reply": l._(
        /*BTDS*/ "Value, Messaging Reply",
      ),
      "onsite_conversion.messaging_scam_proactive_warning_learn_more": null,
      "onsite_conversion.messaging_scam_proactive_warning_learn_more_experimental":
        null,
      "onsite_conversion.messaging_user_call_attempted": null,
      "onsite_conversion.messaging_user_call_placed": l._(
        /*BTDS*/ "Value, Call",
      ),
      "onsite_conversion.messaging_user_depth_2_message_send": null,
      "onsite_conversion.messaging_user_depth_2_message_send_continuation":
        null,
      "onsite_conversion.messaging_user_depth_3_message_send": null,
      "onsite_conversion.messaging_user_depth_3_message_send_continuation":
        null,
      "onsite_conversion.messaging_user_depth_5_message_send": null,
      "onsite_conversion.messaging_user_phone_call_dialog_confirm_clicked":
        null,
      "onsite_conversion.messaging_user_send_num_same_conversation": null,
      "onsite_conversion.messaging_user_subscribed": null,
      "onsite_conversion.messaging_welcome_message_view": null,
      "onsite_conversion.onsite_conversion_down_funnel_purchase": null,
      "onsite_conversion.onsite_conversion_messaging_down_funnel_purchase":
        null,
      "onsite_conversion.onsite_conversion_messaging_down_funnel_purchase_value":
        null,
      "onsite_conversion.order_creation": null,
      "onsite_conversion.other": null,
      "onsite_conversion.pdp_click_to_checkout": null,
      "onsite_conversion.pdp_click_to_offsite": null,
      "onsite_conversion.pdp_click_view_in_cart": null,
      "onsite_conversion.post_save": l._(/*BTDS*/ "Value, Post Save"),
      "onsite_conversion.purchase": l._(/*BTDS*/ "Value, Meta Purchase"),
      "onsite_conversion.rate": null,
      "onsite_conversion.referral_receiver_click": null,
      "onsite_conversion.referral_receiver_impression": null,
      "onsite_conversion.referral_sender_invites_sent": null,
      "onsite_conversion.referral_sender_message_sent": null,
      "onsite_conversion.search": l._(/*BTDS*/ "Value, On-Facebook Search"),
      "onsite_conversion.service_booking_request": null,
      "onsite_conversion.shops_collection_view": null,
      "onsite_conversion.shops_page_view": null,
      "onsite_conversion.submit_application": l._(
        /*BTDS*/ "Value, Application Submitted",
      ),
      "onsite_conversion.total_messaging_connection": null,
      "onsite_conversion.view_content": null,
      onsite_web_add_to_cart: l._(
        /*BTDS*/ "Value, Add to cart (Meta and website)",
      ),
      onsite_web_app_add_to_cart: l._(
        /*BTDS*/ "Value, Add to cart (Meta, website and in-app)",
      ),
      onsite_web_app_purchase: l._(
        /*BTDS*/ "Value, Purchase (Meta, website and in-app)",
      ),
      onsite_web_app_view_content: l._(
        /*BTDS*/ "Value, Content view (Meta, website, and in-app)",
      ),
      onsite_web_initiate_checkout: l._(
        /*BTDS*/ "Value, Initiate checkout (Meta and website)",
      ),
      onsite_web_lead: l._(/*BTDS*/ "Value, Lead (Meta and Website)"),
      onsite_web_purchase: l._(/*BTDS*/ "Value, Purchase (Meta and website)"),
      onsite_web_view_content: l._(
        /*BTDS*/ "Value, Content view (Meta and website)",
      ),
      other: l._(/*BTDS*/ "Value, Other Action"),
      outbound_click: l._(/*BTDS*/ "Value, Outbound Click"),
      page_engagement: l._(/*BTDS*/ "Value, Page Engagement"),
      page_story: l._(/*BTDS*/ "Value, Page Engagement"),
      page_visit_view: l._(/*BTDS*/ "Facebook Page Visit Value"),
      photo_view: l._(/*BTDS*/ "Value, Page Photo View"),
      post: l._(/*BTDS*/ "Value, Post Share"),
      post_engagement: l._(/*BTDS*/ "Value, Post Engagement"),
      post_interaction_gross: null,
      post_like: l._(/*BTDS*/ "Value, Post Like"),
      post_reaction: l._(/*BTDS*/ "Value, Post Reaction"),
      post_save: l._(/*BTDS*/ "Value, Post Save"),
      post_story: l._(/*BTDS*/ "Value, Post Engagement"),
      product_level_reporting: null,
      profile_and_page_engagement: l._(
        /*BTDS*/ "On-profile and Page engagement Value",
      ),
      profile_visit_view: l._(/*BTDS*/ "Instagram Profile Visit Value"),
      "promoted_product_set_result_app_custom_event.fb_mobile_purchase": l._(
        /*BTDS*/ "Value, Prioritized product set purchase (mobile app)",
      ),
      "promoted_product_set_result_offline_conversion.purchase": l._(
        /*BTDS*/ "Value, Prioritized product set purchase (in-store)",
      ),
      "promoted_product_set_result_offsite_conversion.fb_pixel_purchase": l._(
        /*BTDS*/ "Value, Prioritized product set purchase (website)",
      ),
      promoted_product_set_result_omni_purchase: l._(
        /*BTDS*/ "Value, Prioritized product set purchase (website, mobile app and in-store)",
      ),
      "promoted_product_set_result_onsite_conversion.purchase": l._(
        /*BTDS*/ "Value, Prioritized product set purchase (Meta)",
      ),
      promoted_product_set_result_purchase: l._(
        /*BTDS*/ "Value, Prioritized product set purchase (website and mobile app)",
      ),
      promoted_product_set_result_web_app_in_store_purchase: l._(
        /*BTDS*/ "Value, Prioritized product set purchase (website, mobile app, and in-store)",
      ),
      promoted_product_set_result_web_in_store_purchase: l._(
        /*BTDS*/ "Value, Prioritized product set purchase (website and in-store)",
      ),
      purchase: l._(/*BTDS*/ "Value, Purchase (website and in-app)"),
      purchase_with_shared_items: l._(
        /*BTDS*/ "Value, Purchase with shared items (website and in-app)",
      ),
      reach: l._(/*BTDS*/ "Reach Value"),
      receive_offer: l._(/*BTDS*/ "Value, Offer Save"),
      recurring_subscription_payment: null,
      recurring_subscription_payment_mobile_app: null,
      recurring_subscription_payment_offline: null,
      recurring_subscription_payment_on_facebook: null,
      recurring_subscription_payment_total: null,
      recurring_subscription_payment_website: null,
      result: l._(/*BTDS*/ "Result Value"),
      rsvp: l._(/*BTDS*/ "Value, Event Response"),
      schedule: l._(/*BTDS*/ "Value, Schedule (website and in-app)"),
      schedule_mobile_app: l._(/*BTDS*/ "Value, In-app schedule"),
      schedule_offline: l._(/*BTDS*/ "Value, Offline Schedule"),
      schedule_on_facebook: null,
      schedule_total: null,
      schedule_value: null,
      schedule_website: l._(/*BTDS*/ "Value, Website Schedule"),
      search: l._(/*BTDS*/ "Value, Search (website and in-app)"),
      start_trial: l._(/*BTDS*/ "Value, Start trial (website and in-app)"),
      start_trial_mobile_app: l._(/*BTDS*/ "Value, In-app start trial"),
      start_trial_offline: l._(/*BTDS*/ "Value, Offline Start Trial"),
      start_trial_on_facebook: null,
      start_trial_pltv: l._(/*BTDS*/ "pLTV, Trials started"),
      start_trial_pltv_total: null,
      start_trial_total: null,
      start_trial_value: null,
      start_trial_website: l._(/*BTDS*/ "Value, Website Start Trial"),
      store_visit: l._(/*BTDS*/ "Value, Store Visit"),
      submit_application: l._(
        /*BTDS*/ "Value, Submit application (website and in-app)",
      ),
      submit_application_mobile_app: l._(
        /*BTDS*/ "Value, In-app submit application",
      ),
      submit_application_offline: l._(
        /*BTDS*/ "Value, Offline Submit Application",
      ),
      submit_application_on_facebook: l._(
        /*BTDS*/ "Value, On-Facebook Submit Application",
      ),
      submit_application_total: null,
      submit_application_value: null,
      submit_application_website: l._(
        /*BTDS*/ "Value, Website Submit Application",
      ),
      subscribe: l._(/*BTDS*/ "Value, Subscribe (website and in-app)"),
      subscribe_mobile_app: l._(/*BTDS*/ "Value, In-app subscribe"),
      subscribe_offline: l._(/*BTDS*/ "Value, Offline Subscribe"),
      subscribe_on_facebook: null,
      subscribe_pltv: l._(/*BTDS*/ "pLTV, Subscriptions"),
      subscribe_pltv_total: null,
      subscribe_total: null,
      subscribe_value: null,
      subscribe_website: l._(/*BTDS*/ "Value, Website Subscribe"),
      tab_view: l._(/*BTDS*/ "Value, Page Tab View"),
      total_actions: l._(/*BTDS*/ "Value, Action"),
      total_profile_visits: l._(/*BTDS*/ "Visit Value"),
      video_10_sec_watched_actions: l._(/*BTDS*/ "10-Second Video View Value"),
      video_6_sec_watched_actions: l._(/*BTDS*/ "6-Second Video View Value"),
      video_click: null,
      video_continuous_2_sec_watched_actions: l._(
        /*BTDS*/ "2-Second Continuous Video View Value",
      ),
      video_play: l._(/*BTDS*/ "Value, Click to Play Video"),
      video_thruplay_watched_actions: l._(/*BTDS*/ "ThruPlay Value"),
      video_view: l._(/*BTDS*/ "Value, 3-Second Video View"),
      view_content: l._(/*BTDS*/ "Value, View content (website and in-app)"),
      view_content_with_shared_items: l._(
        /*BTDS*/ "Value, View content with shared items (website and in-app)",
      ),
      visit_instagram_profile: l._(/*BTDS*/ "Value, Instagram Profile Visit"),
      visit_location: l._(/*BTDS*/ "Value, Visit Location"),
      visit_location_value: null,
      vote: l._(/*BTDS*/ "Value, Question Answer"),
      wa_promo_channel_follow: null,
      web_app_in_store_purchase: l._(
        /*BTDS*/ "Value, Purchase (Website, mobile app and in-store)",
      ),
      web_in_store_purchase: l._(
        /*BTDS*/ "Value, Purchase (Website and in-store)",
      ),
    };
  },
  130,
);
