__d(
  "AdsInsightsBreakdownBaseConfig",
  [
    "fbt",
    "AdsBreakdownPluginShadowValidator",
    "AdsBreakdownPluginToBaseConfigAdapter",
    "AdsInsightsActionGroups",
    "AdsInsightsBreakdown",
    "AdsInsightsBreakdownContentUtils",
    "AdsInsightsBreakdownEntryGroups",
    "AdsInsightsBreakdownsSpec",
    "AdsInsightsDemographicsBreakdown",
    "AdsInsightsDmaDeprecationUtils",
    "AdsInsightsField",
    "AdsInsightsFields",
    "AdsInsightsGeographyBreakdown",
    "AdsInsightsMetaBreakdowns",
    "AdsInsightsMetricNames",
    "AdsLearnMore.react",
    "AdsMgmt2026H1BreakdownExperimentUtils",
    "PenguinConfig",
    "filterValues",
    "gkx",
    "memoize",
    "objectValues",
    "react",
  ],
  function (t, n, r, o, a, i, l, s) {
    "use strict";
    var e,
      u = e || (e = o("react")),
      c = {},
      d = [
        "image_asset",
        "video_asset",
        "media_asset",
        "link_url_asset",
        "body_asset",
        "title_asset",
        "description_asset",
        "call_to_action_asset",
      ];
    ((c.demographics = [
      {
        breakdown: "age",
        cutoffTime: r("PenguinConfig").CUTOFF_TIME_DEMOGRAPHICS,
        fields: [r("AdsInsightsField").AGE],
        name: r("AdsInsightsMetricNames").age,
        unsupported: [
          "action_canvas_component_name",
          "action_canvas_component_id",
          "action_device",
          "action_reaction",
          "action_video_sound",
          "media_asset",
          "place_page_id",
          "country",
          "region_id",
          "region",
          "dma",
          "comscore_market",
          "activity_recency",
          "impression_device",
          "creative_media_type",
          "publisher_platform",
          "platform_position",
          "device_platform",
          "product_id",
          "frequency_value",
          "hourly_stats_aggregated_by_advertiser_time_zone",
          "hourly_stats_aggregated_by_audience_time_zone",
          "reels_trending_topic",
          "is_auto_advance",
        ],
        tooltip: s._(
          /*BTDS*/ "View your data by age range. These values are estimated.",
        ),
      },
      {
        breakdown: "gender",
        cutoffTime: r("PenguinConfig").CUTOFF_TIME_DEMOGRAPHICS,
        fields: [r("AdsInsightsField").GENDER],
        name: r("AdsInsightsMetricNames").gender,
        unsupported: [
          "action_canvas_component_name",
          "action_canvas_component_id",
          "action_device",
          "action_reaction",
          "action_video_sound",
          "media_asset",
          "place_page_id",
          "country",
          "region_id",
          "region",
          "dma",
          "comscore_market",
          "activity_recency",
          "impression_device",
          "creative_media_type",
          "publisher_platform",
          "platform_position",
          "device_platform",
          "product_id",
          "frequency_value",
          "hourly_stats_aggregated_by_advertiser_time_zone",
          "hourly_stats_aggregated_by_audience_time_zone",
          "reels_trending_topic",
          "is_auto_advance",
        ],
        tooltip: s._(
          /*BTDS*/ "View your data by gender. These values are estimated.",
        ),
      },
      {
        breakdown: "user_segment_key",
        cutoffTime: r("PenguinConfig").CUTOFF_TIME_HOURLY,
        fields: [r("AdsInsightsField").USER_SEGMENT_KEY],
        name: r("AdsInsightsMetricNames")[
          r("AdsInsightsField").USER_SEGMENT_KEY
        ],
        unsupported: [
          "action_brand",
          "action_brand_name",
          "action_canvas_component_id",
          "action_canvas_component_name",
          "action_carousel_card_id",
          "action_carousel_card_name",
          "action_category",
          "action_category_name",
          "action_converted_brand_tag_id",
          "action_converted_category_tag_id",
          "action_converted_product_id",
          "action_destination",
          "action_device",
          "action_event_channel",
          "action_link_click_destination",
          "action_location_code",
          "action_reaction",
          "action_target_id",
          "action_type",
          "action_video_asset_id",
          "action_video_sound",
          "action_video_type",
          "app_optimized_custom_event_name",
          "attribution_model_type",
          "business_contact_option",
          "interactive_component_sticker_id",
          "interactive_component_sticker_response",
          "optimized_custom_event_name",
          "standard_event_content_type",
          "place_page_id",
          "country",
          "region_id",
          "region",
          "dma",
          "comscore_market",
          "user_segment_key",
          "activity_recency",
          "impression_device",
          "creative_media_type",
          "publisher_platform",
          "platform_position",
          "device_platform",
          "product_id",
          "frequency_value",
          "hourly_stats_aggregated_by_advertiser_time_zone",
          "hourly_stats_aggregated_by_audience_time_zone",
          "reels_trending_topic",
          "is_auto_advance",
        ],
        unsupportedWithComparison: !0,
        tooltip: s._(
          /*BTDS*/ "View your data by new audiences, engaged audiences and existing customers. You can manage audience segments in Advertising settings.",
        ),
        helpCenterLinkLabel: s._(/*BTDS*/ "About audience segments"),
        helpCenterLink:
          "https://www.intern.facebook.com/business/help/424052537147870",
      },
      {
        breakdown: "user_persona_id",
        fields: ["user_persona_id"],
        name: r("AdsInsightsMetricNames").user_persona_name,
        tooltip: s._(
          /*BTDS*/ "View your data by actions taken on brands from your catalog. These values are estimated.",
        ),
        unsupported: [
          "region",
          "region_id",
          "dma",
          "comscore_market",
          "place_page_id",
          "action_type",
          "impression_device",
          "action_target_id",
          "action_device",
          "impression_device",
          "publisher_platform",
          "platform_position",
          "action_reaction",
          "age",
          "gender",
          "product_id",
          "hourly_stats_aggregated_by_advertiser_time_zone",
          "hourly_stats_aggregated_by_audience_time_zone",
          "action_canvas_component_name",
          "action_video_sound",
          "activity_recency",
          "device_platform",
          "frequency_value",
          "region_id",
          "region",
          "creative_media_type",
          "reels_trending_topic",
          "is_auto_advance",
        ].concat(d),
      },
      {
        breakdown: "user_persona_name",
        fields: ["user_persona_name"],
        name: r("AdsInsightsMetricNames").user_persona_name,
        tooltip: s._(
          /*BTDS*/ "View your data by actions taken on categories from your catalog. These values are estimated.",
        ),
        unsupported: [
          "region",
          "region_id",
          "dma",
          "comscore_market",
          "place_page_id",
          "action_type",
          "impression_device",
          "action_target_id",
          "action_device",
          "impression_device",
          "publisher_platform",
          "platform_position",
          "action_reaction",
          "age",
          "gender",
          "product_id",
          "hourly_stats_aggregated_by_advertiser_time_zone",
          "hourly_stats_aggregated_by_audience_time_zone",
          "action_canvas_component_name",
          "action_video_sound",
          "activity_recency",
          "device_platform",
          "frequency_value",
          "region_id",
          "region",
          "creative_media_type",
          "reels_trending_topic",
          "is_auto_advance",
        ].concat(d),
      },
    ]),
      (c.geography = [
        {
          breakdown: "user_segment_key",
          cutoffTime: r("PenguinConfig").CUTOFF_TIME_HOURLY,
          fields: [r("AdsInsightsField").USER_SEGMENT_KEY],
          name: r("AdsInsightsMetricNames")[
            r("AdsInsightsField").USER_SEGMENT_KEY
          ],
          unsupported: [
            "action_brand",
            "action_brand_name",
            "action_canvas_component_id",
            "action_canvas_component_name",
            "action_carousel_card_id",
            "action_carousel_card_name",
            "action_category",
            "action_category_name",
            "action_converted_brand_tag_id",
            "action_converted_category_tag_id",
            "action_converted_product_id",
            "action_destination",
            "action_device",
            "action_event_channel",
            "action_link_click_destination",
            "action_location_code",
            "action_reaction",
            "action_target_id",
            "action_type",
            "action_video_asset_id",
            "action_video_sound",
            "action_video_type",
            "app_optimized_custom_event_name",
            "attribution_model_type",
            "business_contact_option",
            "interactive_component_sticker_id",
            "interactive_component_sticker_response",
            "optimized_custom_event_name",
            "standard_event_content_type",
            "activity_recency",
            "impression_device",
            "creative_media_type",
            "publisher_platform",
            "platform_position",
            "device_platform",
            "product_id",
            "frequency_value",
            "hourly_stats_aggregated_by_advertiser_time_zone",
            "hourly_stats_aggregated_by_audience_time_zone",
            "reels_trending_topic",
            "is_auto_advance",
          ],
          unsupportedWithComparison: !0,
          tooltip: s._(
            /*BTDS*/ "View your data by new audiences, engaged audiences and existing customers. You can manage audience segments in Advertising settings.",
          ),
          helpCenterLinkLabel: s._(/*BTDS*/ "About audience segments"),
          helpCenterLink:
            "https://www.intern.facebook.com/business/help/424052537147870",
        },
        {
          breakdown: "place_page_id",
          cutoffTime: r("PenguinConfig").CUTOFF_TIME_CALL_TO_ACTION_CLICKS,
          fields: [r("AdsInsightsField").PLACE_PAGE_ID],
          name: r("AdsInsightsMetricNames").place_page_id,
          unsupported: [
            "action_canvas_component_name",
            "action_canvas_component_id",
            "action_carousel_card_name",
            "action_carousel_card_id",
            "action_destination",
            "action_device",
            "action_reaction",
            "action_video_sound",
            "action_video_type",
            "age",
            "gender",
            "activity_recency",
            "impression_device",
            "creative_media_type",
            "publisher_platform",
            "platform_position",
            "device_platform",
            "product_id",
            "frequency_value",
            "hourly_stats_aggregated_by_advertiser_time_zone",
            "hourly_stats_aggregated_by_audience_time_zone",
            "reels_trending_topic",
            "user_segment_key",
            "is_auto_advance",
          ].concat(d),
          tooltip: s._(
            /*BTDS*/ "View your data by the impressions for each of your business locations. Business location breakdowns are only available for ads using dynamic Page location targeting. These values are estimated.",
          ),
          maxEntries: 30,
          maxEntriesWarning: s._(
            /*BTDS*/ "We can only show location name for the top 30 locations.",
          ),
        },
        {
          breakdown: "country",
          cutoffTime: r("PenguinConfig").CUTOFF_TIME_DEMOGRAPHICS,
          fields: [r("AdsInsightsField").COUNTRY],
          name: r("AdsInsightsMetricNames").country,
          unsupported: [
            "action_canvas_component_name",
            "action_canvas_component_id",
            "action_device",
            "action_reaction",
            "action_video_sound",
            "age",
            "gender",
            "activity_recency",
            "impression_device",
            "creative_media_type",
            "publisher_platform",
            "platform_position",
            "device_platform",
            "product_id",
            "frequency_value",
            "hourly_stats_aggregated_by_advertiser_time_zone",
            "hourly_stats_aggregated_by_audience_time_zone",
            "reels_trending_topic",
            "user_segment_key",
            "is_auto_advance",
          ].concat(d),
          tooltip: s._(
            /*BTDS*/ "View your data by the country where people live or were located when they saw your ads, depending on how you set your location targeting. These values are estimated.",
          ),
        },
        {
          breakdown: "region_id",
          cutoffTime: r("PenguinConfig").CUTOFF_TIME_REGION_PREDICTION,
          fields: [r("AdsInsightsField").REGION_ID],
          name: r("AdsInsightsMetricNames").region,
          unsupported: [
            "action_canvas_component_name",
            "action_canvas_component_id",
            "action_carousel_card_name",
            "action_carousel_card_id",
            "action_device",
            "action_reaction",
            "action_video_sound",
            "age",
            "gender",
            "activity_recency",
            "impression_device",
            "creative_media_type",
            "publisher_platform",
            "platform_position",
            "device_platform",
            "product_id",
            "frequency_value",
            "hourly_stats_aggregated_by_advertiser_time_zone",
            "hourly_stats_aggregated_by_audience_time_zone",
            "reels_trending_topic",
            "is_auto_advance",
          ].concat(d),
          tooltip: s._(
            /*BTDS*/ "View your data by the region (such as state or province) where people live or were located when they saw your ads, depending on how you set your location targeting. These values are estimated.",
          ),
        },
        {
          breakdown: "region",
          cutoffTime: r("PenguinConfig").CUTOFF_TIME_REGION_PREDICTION,
          fields: [r("AdsInsightsField").REGION],
          name: r("AdsInsightsMetricNames").region,
          unsupported: [
            "action_canvas_component_name",
            "action_canvas_component_id",
            "action_carousel_card_name",
            "action_carousel_card_id",
            "action_device",
            "action_reaction",
            "action_video_sound",
            "age",
            "gender",
            "activity_recency",
            "impression_device",
            "creative_media_type",
            "publisher_platform",
            "platform_position",
            "device_platform",
            "product_id",
            "frequency_value",
            "hourly_stats_aggregated_by_advertiser_time_zone",
            "hourly_stats_aggregated_by_audience_time_zone",
            "reels_trending_topic",
            "is_auto_advance",
          ].concat(d),
          tooltip: s._(
            /*BTDS*/ "View your data by the region (such as state or province) where people live or were located when they saw your ads, depending on how you set your location targeting. These values are estimated.",
          ),
        },
      ]
        .concat(
          o("AdsInsightsDmaDeprecationUtils").shouldHideDma()
            ? []
            : {
                breakdown: "dma",
                cutoffTime: r("PenguinConfig").CUTOFF_TIME_DMA,
                fields: [r("AdsInsightsField").DMA],
                name: r("AdsInsightsMetricNames").dma,
                unsupported: [
                  "action_canvas_component_name",
                  "action_canvas_component_id",
                  "action_carousel_card_name",
                  "action_carousel_card_id",
                  "action_device",
                  "action_reaction",
                  "action_video_sound",
                  "age",
                  "gender",
                  "activity_recency",
                  "impression_device",
                  "creative_media_type",
                  "publisher_platform",
                  "platform_position",
                  "device_platform",
                  "product_id",
                  "frequency_value",
                  "hourly_stats_aggregated_by_advertiser_time_zone",
                  "hourly_stats_aggregated_by_audience_time_zone",
                  "reels_trending_topic",
                  "user_segment_key",
                  "is_auto_advance",
                ].concat(d),
                tooltip: s._(
                  /*BTDS*/ "View your data by the designated marketing area (DMA) region where people live or were located when they saw your ads, depending on how you set your location targeting. The DMA region represents a U.S. media market, or an area reached by TV, radio, newspaper or other media. If ads were delivered outside the United States, data will appear in the Unknown category. These values are estimated.",
                ),
              },
        )
        .concat({
          breakdown: "comscore_market",
          cutoffTime: r("PenguinConfig").CUTOFF_TIME_COMSCORE,
          fields: [r("AdsInsightsField").COMSCORE_MARKET],
          name: r("AdsInsightsMetricNames").comscore_market,
          unsupported: [
            "action_canvas_component_name",
            "action_canvas_component_id",
            "action_carousel_card_name",
            "action_carousel_card_id",
            "action_device",
            "action_reaction",
            "action_video_sound",
            "age",
            "gender",
            "activity_recency",
            "impression_device",
            "creative_media_type",
            "publisher_platform",
            "platform_position",
            "device_platform",
            "product_id",
            "frequency_value",
            "hourly_stats_aggregated_by_advertiser_time_zone",
            "hourly_stats_aggregated_by_audience_time_zone",
            "reels_trending_topic",
            "user_segment_key",
            "is_auto_advance",
          ].concat(d),
          tooltip: s._(
            /*BTDS*/ "View your data by the Comscore Market region where people live or were located when they saw your ads, depending on how you set your location targeting. The Comscore Market represents a U.S. media market, or an area reached by TV, radio, newspaper or other media. If ads were delivered outside the United States, data will appear in the Unknown category. These values are estimated.",
          ),
        })),
      (c.impression = [
        {
          breakdown: "activity_recency",
          cutoffTime: r("PenguinConfig").CUTOFF_TIME_ACTIVITY_RECENCY,
          fields: [r("AdsInsightsField").ACTIVITY_RECENCY],
          name: r("AdsInsightsMetricNames").activity_recency,
          gkResult: r("gkx")("21457"),
          unsupported: [
            "action_canvas_component_name",
            "action_canvas_component_id",
            "action_carousel_card_name",
            "action_carousel_card_id",
            "action_destination",
            "action_device",
            "action_reaction",
            "action_video_sound",
            "action_video_type",
            "age",
            "gender",
            "user_segment_key",
            "place_page_id",
            "country",
            "region_id",
            "region",
            "dma",
            "comscore_market",
            "user_segment_key",
            "is_auto_advance",
          ].concat(d),
          tooltip: s._(
            /*BTDS*/ "View your data by viewer's recent offsite activity. These values are estimated.",
          ),
        },
        {
          breakdown: "impression_device",
          cutoffTime: r("PenguinConfig").CUTOFF_TIME_DEMOGRAPHICS,
          fields: [r("AdsInsightsField").IMPRESSION_DEVICE],
          name: r("AdsInsightsMetricNames").impression_device,
          unsupported: [
            "action_canvas_component_name",
            "action_canvas_component_id",
            "action_reaction",
            "action_video_sound",
            "age",
            "gender",
            "user_segment_key",
            "place_page_id",
            "country",
            "region_id",
            "region",
            "dma",
            "comscore_market",
            "user_segment_key",
            "is_auto_advance",
          ].concat(d),
          tooltip: s._(
            /*BTDS*/ "View your data by the devices people were using when they saw your ads. These values are estimated.",
          ),
        },
        {
          breakdown: "creative_media_type",
          fields: [r("AdsInsightsField").CREATIVE_MEDIA_TYPE],
          name: r("AdsInsightsMetricNames").creative_media_type,
          unsupported: [
            "age",
            "gender",
            "user_segment_key",
            "place_page_id",
            "country",
            "region_id",
            "region",
            "dma",
            "comscore_market",
            "user_segment_key",
            "is_auto_advance",
          ],
          tooltip: s._(
            /*BTDS*/ 'View your data by the type of media in your ad. Media can include image, video or both image and video. In some cases, such as when an asset type has changed during an ad\'s delivery or when an ad format uses a combination of image and video assets, impressions will be reported under the "Image and Video" grouping. These values are estimated.',
          ),
        },
        {
          breakdown: "publisher_platform",
          cutoffTime: r("PenguinConfig").CUTOFF_TIME_PLACEMENT,
          fields: [r("AdsInsightsField").PUBLISHER_PLATFORM],
          name: r("AdsInsightsMetricNames").publisher_platform,
          unsupported: [
            "action_canvas_component_name",
            "action_canvas_component_id",
            "action_reaction",
            "action_video_sound",
            "age",
            "gender",
            "user_segment_key",
            "place_page_id",
            "country",
            "region_id",
            "region",
            "dma",
            "comscore_market",
            "user_segment_key",
            "is_auto_advance",
          ].concat(
            d,
            o(
              "AdsMgmt2026H1BreakdownExperimentUtils",
            ).getIsAccountInMultiMediaPlacementBreakdownWithoutExposure()
              ? [
                  "flexible_format_asset_type",
                  "gen_ai_asset_type",
                  "creative_relaxation_asset_type",
                ]
              : [],
          ),
          tooltip: s._(
            /*BTDS*/ "View your data by platform where your ad was shown (ex: Facebook, Instagram). These values are estimated.",
          ),
        },
        {
          breakdown: "ad_extension_domain",
          cutoffTime: r("PenguinConfig").CUTOFF_TIME_PLACEMENT,
          gk_by_act: "ocmr",
          fields: [r("AdsInsightsField").AD_EXTENSION_DOMAIN],
          name: r("AdsInsightsMetricNames").ad_extension_domain,
          unsupported: [
            "action_canvas_component_name",
            "action_canvas_component_id",
            "action_reaction",
            "action_video_sound",
            "age",
            "gender",
            "user_segment_key",
            "place_page_id",
            "country",
            "region_id",
            "region",
            "dma",
            "comscore_market",
            "user_segment_key",
            "is_auto_advance",
          ].concat(d),
          tooltip: s._(
            /*BTDS*/ "View the performance of your different retailer links. Manage your retailer links in the Site Links extension under Ad creative settings.",
          ),
        },
        {
          breakdown: "ad_extension_url",
          cutoffTime: r("PenguinConfig").CUTOFF_TIME_PLACEMENT,
          gk_by_act: "ocmr",
          fields: [r("AdsInsightsField").AD_EXTENSION_URL],
          name: r("AdsInsightsMetricNames").ad_extension_url,
          unsupported: [
            "action_canvas_component_name",
            "action_canvas_component_id",
            "action_reaction",
            "action_video_sound",
            "age",
            "gender",
            "user_segment_key",
            "place_page_id",
            "country",
            "region_id",
            "region",
            "dma",
            "comscore_market",
            "user_segment_key",
            "is_auto_advance",
          ].concat(d),
          tooltip: s._(
            /*BTDS*/ "View the performance of each product added to your retailer links. Edit or remove products in the Site Links extension under Ad creative settings.",
          ),
        },
        {
          breakdown: "platform_position",
          cutoffTime: r("PenguinConfig").CUTOFF_TIME_PLACEMENT,
          fields: [r("AdsInsightsField").PLATFORM_POSITION],
          name: r("AdsInsightsMetricNames").platform_position,
          unsupported: [
            "action_canvas_component_name",
            "action_canvas_component_id",
            "action_reaction",
            "action_video_sound",
            "age",
            "gender",
            "user_segment_key",
            "place_page_id",
            "country",
            "region_id",
            "region",
            "dma",
            "comscore_market",
            "user_segment_key",
          ].concat(d),
          tooltip: s._(
            /*BTDS*/ "View your data by placement where your ad was shown (ex: Facebook desktop Feed, Instagram mobile feed). These values are estimated.",
          ),
        },
        {
          breakdown: "device_platform",
          cutoffTime: r("PenguinConfig").CUTOFF_TIME_PLACEMENT,
          fields: [r("AdsInsightsField").DEVICE_PLATFORM],
          name: r("AdsInsightsMetricNames").device_platform,
          unsupported: [
            "action_canvas_component_name",
            "action_canvas_component_id",
            "action_reaction",
            "action_video_sound",
            "age",
            "gender",
            "user_segment_key",
            "place_page_id",
            "country",
            "region_id",
            "region",
            "dma",
            "comscore_market",
            "user_segment_key",
            "is_auto_advance",
          ].concat(d),
          tooltip: s._(
            /*BTDS*/ "View your data by placement where your ad was shown and devices people were using when they saw your ads (ex: Facebook desktop Feed, Instagram mobile feed). These values are estimated.",
          ),
        },
        {
          breakdown: "product_id",
          cutoffTime: r("PenguinConfig").CUTOFF_TIME_DEMOGRAPHICS,
          disableSummaryBreakdown: !0,
          fields: [r("AdsInsightsField").PRODUCT_ID],
          name: r("AdsInsightsMetricNames").product_id,
          unsupported: [
            "action_canvas_component_name",
            "action_canvas_component_id",
            "action_carousel_card_id",
            "action_carousel_card_name",
            "action_device",
            "action_reaction",
            "action_video_sound",
            "age",
            "gender",
            "user_segment_key",
            "place_page_id",
            "country",
            "region_id",
            "region",
            "dma",
            "comscore_market",
            "user_segment_key",
            "is_auto_advance",
          ].concat(d),
          tooltip: s._(
            /*BTDS*/ "View your data by product ID. Product ID data is only available for ads connected to a catalog. These values are estimated.",
          ),
          maxEntries: 1e3,
          maxEntriesWarning: s._(
            /*BTDS*/ "We can only show product ID for the top 1,000 products.",
          ),
        },
        {
          breakdown: "frequency_value",
          cutoffTime: r("PenguinConfig").CUTOFF_TIME_DEMOGRAPHICS,
          fields: [r("AdsInsightsField").FREQUENCY_VALUE],
          name: r("AdsInsightsMetricNames").frequency_value,
          unsupported: [
            "action_canvas_component_name",
            "action_canvas_component_id",
            "action_device",
            "action_destination",
            "action_reaction",
            "action_video_sound",
            "action_video_type",
            "action_carousel_card_name",
            "action_carousel_card_id",
            "age",
            "gender",
            "user_segment_key",
            "place_page_id",
            "country",
            "region_id",
            "region",
            "dma",
            "comscore_market",
            "user_segment_key",
            "is_auto_advance",
          ].concat(d),
          tooltip: s._(
            /*BTDS*/ 'View your data by the average number of times people saw your ad. This breakdown is only available for ad sets created with the "reservation" buying option. These values are estimated.',
          ),
        },
        {
          breakdown: "hourly_stats_aggregated_by_advertiser_time_zone",
          cutoffTime: r("PenguinConfig").CUTOFF_TIME_HOURLY,
          fields: [
            r("AdsInsightsField")
              .HOURLY_STATS_AGGREGATED_BY_ADVERTISER_TIME_ZONE,
          ],
          name: r("AdsInsightsMetricNames")[
            r("AdsInsightsField")
              .HOURLY_STATS_AGGREGATED_BY_ADVERTISER_TIME_ZONE
          ],
          unsupported: [
            "action_canvas_component_name",
            "action_canvas_component_id",
            "action_device",
            "action_destination",
            "action_reaction",
            "action_video_sound",
            "action_video_type",
            "action_carousel_card_name",
            "action_carousel_card_id",
            "age",
            "gender",
            "user_segment_key",
            "place_page_id",
            "country",
            "region_id",
            "region",
            "dma",
            "comscore_market",
            "user_segment_key",
            "is_auto_advance",
          ].concat(d),
          unsupportedWithComparison: !0,
          tooltip: s._(
            /*BTDS*/ "View your data based on time of day in the ad account's time zone. These values are estimated.",
          ),
        },
        {
          breakdown: "hourly_stats_aggregated_by_audience_time_zone",
          cutoffTime: r("PenguinConfig").CUTOFF_TIME_HOURLY,
          fields: [
            r("AdsInsightsField").HOURLY_STATS_AGGREGATED_BY_AUDIENCE_TIME_ZONE,
          ],
          name: r("AdsInsightsMetricNames")[
            r("AdsInsightsField").HOURLY_STATS_AGGREGATED_BY_AUDIENCE_TIME_ZONE
          ],
          unsupported: [
            "action_canvas_component_name",
            "action_canvas_component_id",
            "action_device",
            "action_destination",
            "action_reaction",
            "action_video_sound",
            "action_video_type",
            "action_carousel_card_name",
            "action_carousel_card_id",
            "age",
            "gender",
            "user_segment_key",
            "place_page_id",
            "country",
            "region_id",
            "region",
            "dma",
            "comscore_market",
            "user_segment_key",
            "is_auto_advance",
          ].concat(d),
          unsupportedWithComparison: !0,
          tooltip: s._(
            /*BTDS*/ "View your data based on time of day in the time zone where the ad was viewed. These values are estimated.",
          ),
        },
        {
          breakdown: "reels_trending_topic",
          fields: [r("AdsInsightsField").REELS_TRENDING_TOPIC],
          gk_by_act: "reels_trending_ads_reporting",
          name: r("AdsInsightsMetricNames")[
            r("AdsInsightsField").REELS_TRENDING_TOPIC
          ],
          unsupported: [
            "action_canvas_component_name",
            "action_canvas_component_id",
            "action_device",
            "action_destination",
            "action_reaction",
            "action_video_sound",
            "action_video_type",
            "action_carousel_card_name",
            "action_carousel_card_id",
            "age",
            "gender",
            "user_segment_key",
            "place_page_id",
            "country",
            "region_id",
            "region",
            "dma",
            "comscore_market",
            "user_segment_key",
            "is_auto_advance",
          ].concat(d),
          tooltip: s._(
            /*BTDS*/ "View your Reels trending ads data by selected trending topic. These values are estimated.",
          ),
          helpCenterLinkLabel: s._(/*BTDS*/ "About Reels trending ads"),
          helpCenterLink:
            "https://www.facebook.com/business/help/705518531802910",
        },
        {
          breakdown: "pa_creator_ig_handle",
          cutoffTime: r("PenguinConfig").CUTOFF_TIME_HOURLY,
          fields: [r("AdsInsightsField").PA_CREATOR_IG_HANDLE],
          gkResult: r("gkx")("17061"),
          name: r("AdsInsightsMetricNames")[
            r("AdsInsightsField").PA_CREATOR_IG_HANDLE
          ],
          unsupported: [
            "action_canvas_component_name",
            "action_canvas_component_id",
            "action_device",
            "action_destination",
            "action_reaction",
            "action_video_sound",
            "action_video_type",
            "action_carousel_card_name",
            "action_carousel_card_id",
            "age",
            "gender",
            "user_segment_key",
            "place_page_id",
            "country",
            "region_id",
            "region",
            "dma",
            "comscore_market",
            "user_segment_key",
            "is_auto_advance",
          ].concat(d),
          unsupportedWithComparison: !0,
          tooltip: s._(
            /*BTDS*/ "View your data by the Instagram handle of your Creator partners. These values are estimated.",
          ),
        },
        {
          breakdown: "msa_seller_name",
          disableSummaryBreakdown: !0,
          fields: [r("AdsInsightsField").MSA_SELLER_NAME],
          gkResult: r("gkx")("15494"),
          name: r("AdsInsightsMetricNames")[
            r("AdsInsightsField").MSA_SELLER_NAME
          ],
          unsupported: r("objectValues")(r("AdsInsightsBreakdown"))
            .concat(r("objectValues")(r("AdsInsightsActionGroups")))
            .concat(r("objectValues")(r("AdsInsightsDemographicsBreakdown")))
            .concat(r("objectValues")(r("AdsInsightsGeographyBreakdown")))
            .concat(r("objectValues")(r("AdsInsightsMetaBreakdowns")))
            .concat(d)
            .filter(function (e) {
              return (
                e !== "msa_seller_name" &&
                e !== "hourly_stats_aggregated_by_advertiser_time_zone"
              );
            }),
          unsupportedWithComparison: !0,
          tooltip: s._(
            /*BTDS*/ "View your data by the catalog attributes used for assigning budget splits in your campaigns.",
          ),
        },
      ]));
    var m = c.impression
      .filter(function (e) {
        return e.breakdown !== "creative_media_type";
      })
      .map(function (e) {
        return e.breakdown;
      });
    ((c.action = [
      {
        breakdown: "action_device",
        cutoffTime: r("PenguinConfig").CUTOFF_TIME_ACTION_DEVICE,
        fields: [r("AdsInsightsField").ACTION_DEVICE],
        name: r("AdsInsightsMetricNames").action_device,
        unsupported: [
          "activity_recency",
          "age",
          "country",
          "dma",
          "comscore_market",
          "frequency_value",
          "gender",
          "hourly_stats_aggregated_by_advertiser_time_zone",
          "hourly_stats_aggregated_by_audience_time_zone",
          "place_page_id",
          "product_id",
          "region_id",
          "region",
          "reels_trending_topic",
          "is_auto_advance",
        ].concat(d),
        tooltip: s._(
          /*BTDS*/ "View your data by the devices people were using when they took any actions as a result of your ads. These values are estimated.",
        ),
      },
      {
        breakdown: "action_reaction",
        cutoffTime: r("PenguinConfig").CUTOFF_TIME_ACTION_REACTION,
        fields: [r("AdsInsightsField").ACTION_REACTION],
        name: r("AdsInsightsMetricNames").action_reaction,
        unsupported: ["activity_recency", "is_auto_advance"].concat(m, d),
        tooltip: s._(
          /*BTDS*/ "View your data by the reactions on your ads or boosted posts. The reactions button on an ad allows people to share different reactions on its content: Like, Love, Haha, Wow, Sad or Angry. These values are estimated.",
        ),
      },
      {
        breakdown: "action_destination",
        disableSummaryBreakdown: !0,
        fields: [r("AdsInsightsField").DESTINATION],
        name: r("AdsInsightsMetricNames").action_destination,
        unsupported: [
          "activity_recency",
          "frequency_value",
          "hourly_stats_aggregated_by_advertiser_time_zone",
          "hourly_stats_aggregated_by_audience_time_zone",
          "place_page_id",
          "is_auto_advance",
        ].concat(d),
        tooltip: s._(
          /*BTDS*/ "View your data by the URL people went to after clicking on your ad. These values are estimated.",
        ),
      },
      {
        breakdown: "action_event_channel",
        fields: [r("AdsInsightsField").ACTION_EVENT_CHANNEL],
        name: r("AdsInsightsMetricNames").action_event_channel,
        tooltip: s._(
          /*BTDS*/ "View the channels where customers interacted with your business, either on or off Facebook.",
        ),
        gk_by_act: "unified_standard_events_metrics_ui",
        unsupported: ["place_page_id", "product_id", "is_auto_advance"].concat(
          d,
        ),
      },
      {
        breakdown: "action_video_type",
        cutoffTime: r("PenguinConfig").CUTOFF_TIME_VIDEO_INSIGHTS_V2,
        fields: [r("AdsInsightsField").VIDEO_VIEW_TYPE],
        name: r("AdsInsightsMetricNames").action_video_type,
        unsupported: [
          "activity_recency",
          "frequency_value",
          "hourly_stats_aggregated_by_advertiser_time_zone",
          "hourly_stats_aggregated_by_audience_time_zone",
          "place_page_id",
          "is_auto_advance",
        ].concat(d),
        tooltip: s._(
          /*BTDS*/ "View your data by whether a video view was auto-play or click-to-play. These values are estimated.",
        ),
      },
      {
        breakdown: "is_auto_advance",
        fields: [r("AdsInsightsField").IS_AUTO_ADVANCE],
        name: r("AdsInsightsMetricNames").is_auto_advance,
        unsupported: [
          "age",
          "gender",
          "user_segment_key",
          "user_persona_id",
          "user_persona_name",
          "user_segment_key",
          "place_page_id",
          "country",
          "region_id",
          "region",
          "dma",
          "comscore_market",
          "activity_recency",
          "impression_device",
          "creative_media_type",
          "publisher_platform",
          "ad_extension_domain",
          "ad_extension_url",
          "device_platform",
          "product_id",
          "frequency_value",
          "hourly_stats_aggregated_by_advertiser_time_zone",
          "hourly_stats_aggregated_by_audience_time_zone",
          "reels_trending_topic",
          "action_device",
          "action_reaction",
          "action_destination",
          "action_event_channel",
          "action_video_type",
          "action_video_sound",
          "action_carousel_card_id",
          "action_carousel_card_name",
          "action_canvas_component_id",
          "action_canvas_component_name",
          "action_category",
          "action_brand",
          "action_brand_name",
          "action_category_name",
          "conversion_destination",
          "is_business_ai_assisted",
          "signal_source_bucket",
        ].concat(d),
        tooltip: s._(
          /*BTDS*/ "View the video plays metric by whether it was manually advanced through a click, tap or swipe, or if it was automatically advanced and started to play without an interaction. These values are estimated.",
        ),
      },
      {
        breakdown: "action_video_sound",
        cutoffTime: r("PenguinConfig").CUTOFF_TIME_ACTION_VIDEO_SOUND,
        fields: [r("AdsInsightsField").VIDEO_SOUND],
        name: r("AdsInsightsMetricNames").action_video_sound,
        unsupported: ["activity_recency", "is_auto_advance"].concat(m, d),
        tooltip: s._(
          /*BTDS*/ "View your data by whether sound was on or off for a video view. These values are estimated.",
        ),
      },
      {
        breakdown: "action_carousel_card_id",
        cutoffTime: r("PenguinConfig").CUTOFF_TIME_MPA_CONVERSIONS,
        disableSummaryBreakdown: !0,
        fields: [r("AdsInsightsField").CAROUSEL_CARD_ID],
        name: r("AdsInsightsMetricNames").action_carousel_card_id,
        unsupported: [
          "activity_recency",
          "dma",
          "comscore_market",
          "frequency_value",
          "hourly_stats_aggregated_by_advertiser_time_zone",
          "hourly_stats_aggregated_by_audience_time_zone",
          "place_page_id",
          "product_id",
          "region_id",
          "region",
          "reels_trending_topic",
          "is_auto_advance",
        ].concat(d),
        tooltip: o("AdsInsightsBreakdownContentUtils")
          .carouselCardTooltipContentBody,
        helpCenterLinkLabel: o("AdsInsightsBreakdownContentUtils")
          .carouselCardTooltipLearnMoreLinkLabel,
        helpCenterLink: o("AdsInsightsBreakdownContentUtils")
          .carouselCardTooltipLearnMoreLink,
      },
      {
        breakdown: "action_carousel_card_name",
        cutoffTime: r("PenguinConfig").CUTOFF_TIME_MPA_CONVERSIONS,
        disableSummaryBreakdown: !0,
        fields: [r("AdsInsightsField").CAROUSEL_CARD_NAME],
        name: r("AdsInsightsMetricNames").action_carousel_card_name,
        unsupported: [
          "activity_recency",
          "dma",
          "comscore_market",
          "frequency_value",
          "hourly_stats_aggregated_by_advertiser_time_zone",
          "hourly_stats_aggregated_by_audience_time_zone",
          "place_page_id",
          "product_id",
          "region_id",
          "region",
          "reels_trending_topic",
          "is_auto_advance",
        ].concat(d),
        tooltip: o("AdsInsightsBreakdownContentUtils")
          .carouselCardTooltipContentBody,
        helpCenterLinkLabel: o("AdsInsightsBreakdownContentUtils")
          .carouselCardTooltipLearnMoreLinkLabel,
        helpCenterLink: o("AdsInsightsBreakdownContentUtils")
          .carouselCardTooltipLearnMoreLink,
      },
      {
        breakdown: "action_canvas_component_id",
        cutoffTime:
          r("PenguinConfig").CUTOFF_TIME_CANVAS_VIEW_BREAKDOWN_INSIGHTS,
        disableSummaryBreakdown: !0,
        fields: [r("AdsInsightsField").ACTION_CANVAS_COMPONENT_ID],
        name: r("AdsInsightsMetricNames").action_canvas_component_id,
        unsupported: ["activity_recency"].concat(m, ["is_auto_advance"], d),
        tooltip: s._(
          /*BTDS*/ "View your data by each component in a Canvas experience. These values are estimated.",
        ),
      },
      {
        breakdown: "action_canvas_component_name",
        cutoffTime:
          r("PenguinConfig").CUTOFF_TIME_CANVAS_VIEW_BREAKDOWN_INSIGHTS,
        disableSummaryBreakdown: !0,
        fields: [r("AdsInsightsField").ACTION_CANVAS_COMPONENT_NAME],
        name: r("AdsInsightsMetricNames").action_canvas_component_name,
        unsupported: ["activity_recency"].concat(m, ["is_auto_advance"], d),
        tooltip: s._(
          /*BTDS*/ "View your data by each component in an Instant Experience. These values are estimated.",
        ),
      },
      {
        breakdown: "action_category",
        fields: [r("AdsInsightsField").ACTION_CATEGORY],
        name: r("AdsInsightsMetricNames").action_category,
        tooltip: s._(
          /*BTDS*/ "View your data by actions taken on categories from your catalog. These values are estimated.",
        ),
        gk_by_act: "ads_insights_da_category_brand_reporting",
        unsupported: ["product_id", "is_auto_advance"].concat(d),
      },
      {
        breakdown: "action_brand",
        fields: [r("AdsInsightsField").ACTION_BRAND],
        name: r("AdsInsightsMetricNames").action_brand,
        tooltip: s._(
          /*BTDS*/ "View your data by actions taken on brands from your catalog. These values are estimated.",
        ),
        gk_by_act: "ads_insights_da_category_brand_reporting",
        unsupported: ["product_id", "is_auto_advance"].concat(d),
      },
      {
        breakdown: "action_brand_name",
        fields: [r("AdsInsightsField").ACTION_BRAND_NAME],
        name: r("AdsInsightsMetricNames").action_brand_name,
        tooltip: s._(
          /*BTDS*/ "View your data by actions taken on brands from your catalog. These values are estimated.",
        ),
        unsupported: ["product_id", "is_auto_advance"].concat(d),
      },
      {
        breakdown: "action_category_name",
        fields: [r("AdsInsightsField").ACTION_CATEGORY_NAME],
        name: r("AdsInsightsMetricNames").action_category_name,
        tooltip: s._(
          /*BTDS*/ "View your data by actions taken on categories from your catalog. These values are estimated.",
        ),
        unsupported: ["product_id", "is_auto_advance"].concat(d),
      },
      {
        breakdown: "conversion_destination",
        disableSummaryBreakdown: !0,
        fields: [r("AdsInsightsField").CONVERSION_DESTINATION],
        name: r("AdsInsightsMetricNames").conversion_destination,
        unsupported: [
          "age",
          "gender",
          "signal_source_bucket",
          "action_brand",
          "action_brand_name",
          "action_canvas_component_id",
          "action_canvas_component_name",
          "action_carousel_card_id",
          "action_carousel_card_name",
          "action_category",
          "action_category_name",
          "action_converted_brand_tag_id",
          "action_converted_category_tag_id",
          "action_converted_product_id",
          "action_destination",
          "action_device",
          "action_event_channel",
          "action_link_click_destination",
          "action_location_code",
          "action_reaction",
          "action_target_id",
          "action_type",
          "action_video_asset_id",
          "action_video_sound",
          "action_video_type",
          "app_optimized_custom_event_name",
          "attribution_model_type",
          "business_contact_option",
          "interactive_component_sticker_id",
          "interactive_component_sticker_response",
          "optimized_custom_event_name",
          "standard_event_content_type",
          "place_page_id",
          "country",
          "region_id",
          "region",
          "dma",
          "comscore_market",
          "user_segment_key",
          "activity_recency",
          "impression_device",
          "creative_media_type",
          "publisher_platform",
          "platform_position",
          "device_platform",
          "product_id",
          "frequency_value",
          "hourly_stats_aggregated_by_advertiser_time_zone",
          "hourly_stats_aggregated_by_audience_time_zone",
          "reels_trending_topic",
          "is_auto_advance",
        ].concat(d),
        tooltip: s._(
          /*BTDS*/ "View your data by which messaging app the outcome (such as a purchase or lead) occurred on after people clicked on your messaging ad.",
        ),
      },
      {
        breakdown: "is_business_ai_assisted",
        fields: [r("AdsInsightsField").IS_BUSINESS_AI_ASSISTED],
        name: r("AdsInsightsMetricNames").is_business_ai_assisted,
        cutoffTime: r("PenguinConfig").CUTOFF_TIME_IS_BUSINESS_AI_ASSISTED,
        gkResult: r("gkx")("20189"),
        unsupported: r("objectValues")(r("AdsInsightsBreakdown"))
          .concat(r("objectValues")(r("AdsInsightsActionGroups")))
          .concat(r("objectValues")(r("AdsInsightsGeographyBreakdown")))
          .concat(r("objectValues")(r("AdsInsightsMetaBreakdowns")))
          .concat(d)
          .filter(function (e) {
            return e !== "is_business_ai_assisted";
          }),
        tooltip: s._(
          /*BTDS*/ "View your data by whether or not your Business AI assisted with conversions in an ad. This breakdown applies to purchase, purchase value, checkouts initiated, checkouts initiated value, adds to cart and adds to cart value.",
        ),
        helpCenterLinkLabel: s._(
          /*BTDS*/ "These values are estimated and in-development.",
        ),
        helpCenterLink:
          "https://www.facebook.com/business/help/181058782494426",
      },
      {
        breakdown: "signal_source_bucket",
        disableSummaryBreakdown: !0,
        fields: [r("AdsInsightsField").SIGNAL_SOURCE_BUCKET],
        name: r("AdsInsightsMetricNames").signal_source_bucket,
        unsupported: [
          "age",
          "gender",
          "conversion_destination",
          "action_brand",
          "action_brand_name",
          "action_canvas_component_id",
          "action_canvas_component_name",
          "action_carousel_card_id",
          "action_carousel_card_name",
          "action_category",
          "action_category_name",
          "action_converted_brand_tag_id",
          "action_converted_category_tag_id",
          "action_converted_product_id",
          "action_destination",
          "action_device",
          "action_event_channel",
          "action_link_click_destination",
          "action_location_code",
          "action_reaction",
          "action_target_id",
          "action_type",
          "action_video_asset_id",
          "action_video_sound",
          "action_video_type",
          "app_optimized_custom_event_name",
          "attribution_model_type",
          "business_contact_option",
          "interactive_component_sticker_id",
          "interactive_component_sticker_response",
          "optimized_custom_event_name",
          "standard_event_content_type",
          "place_page_id",
          "country",
          "region_id",
          "region",
          "dma",
          "comscore_market",
          "user_segment_key",
          "activity_recency",
          "impression_device",
          "creative_media_type",
          "publisher_platform",
          "platform_position",
          "device_platform",
          "product_id",
          "frequency_value",
          "hourly_stats_aggregated_by_advertiser_time_zone",
          "hourly_stats_aggregated_by_audience_time_zone",
          "reels_trending_topic",
          "is_auto_advance",
        ].concat(d),
        tooltip: s._(
          /*BTDS*/ "View your data by the source of the purchase activity in messaging conversations (such as manually-created purchases on Meta or third-party apps, or auto-detected purchases).",
        ),
      },
      {
        breakdown: "promoted_product_set_result",
        cutoffTime: r("PenguinConfig").CUTOFF_TIME_PROMOTED_PRODUCT_SET_RESULT,
        disableSummaryBreakdown: !0,
        fields: [r("AdsInsightsField").PROMOTED_PRODUCT_SET_RESULT],
        name: r("AdsInsightsMetricNames").promoted_product_set_result,
        gkResult: r("gkx")("22080"),
        unsupported: r("objectValues")(r("AdsInsightsBreakdown"))
          .concat(r("objectValues")(r("AdsInsightsActionGroups")))
          .concat(r("objectValues")(r("AdsInsightsGeographyBreakdown")))
          .concat(r("objectValues")(r("AdsInsightsMetaBreakdowns")))
          .concat(d)
          .filter(function (e) {
            return e !== "promoted_product_set_result";
          }),
        tooltip: h(),
        helpCenterLinkLabel: s._(
          /*BTDS*/ "These values are estimated and in-development.",
        ),
        helpCenterLink:
          "https://www.facebook.com/business/help/metrics-labeling#estimated",
      },
    ]),
      (c.time = [
        {
          breakdown: "days_1",
          fields: [
            r("AdsInsightsField").DATE_START,
            r("AdsInsightsField").DATE_STOP,
          ],
          name: r("AdsInsightsMetricNames").days_1,
          unsupportedWithComparison: !1,
          tooltip: s._(
            /*BTDS*/ "View your data by each day that your ads were active. These values are estimated.",
          ),
        },
        {
          breakdown: "days_7",
          fields: [
            r("AdsInsightsField").DATE_START,
            r("AdsInsightsField").DATE_STOP,
          ],
          name: r("AdsInsightsMetricNames").days_7,
          unsupportedWithComparison: !1,
          tooltip: s._(
            /*BTDS*/ "View your data by each week that your ads were active. These values are estimated.",
          ),
        },
        {
          breakdown: "days_14",
          fields: [
            r("AdsInsightsField").DATE_START,
            r("AdsInsightsField").DATE_STOP,
          ],
          name: r("AdsInsightsMetricNames").days_14,
          unsupportedWithComparison: !1,
          tooltip: s._(
            /*BTDS*/ "View your data by each 2-week period that your ads were active. This breakdown is estimated.",
          ),
        },
        {
          breakdown: "monthly",
          fields: [
            r("AdsInsightsField").DATE_START,
            r("AdsInsightsField").DATE_STOP,
          ],
          name: r("AdsInsightsMetricNames").monthly,
          unsupportedWithComparison: !1,
          tooltip: s._(
            /*BTDS*/ "View your data by each month that your ads were active. These values are estimated.",
          ),
        },
      ]),
      (c.object = [
        {
          breakdown: o("AdsInsightsBreakdownsSpec").ObjectBreakdowns.AD,
          fields: [],
          disableSummaryBreakdown: !0,
          name: s._(/*BTDS*/ "Ad"),
          unsupportedTypes: r("filterValues")(
            r("objectValues")(r("AdsInsightsBreakdownEntryGroups")),
            [r("AdsInsightsBreakdownEntryGroups").OBJECT],
          ),
          tooltip: s._(/*BTDS*/ "This shows the breakdown of results by ad."),
        },
        {
          breakdown: o("AdsInsightsBreakdownsSpec").ObjectBreakdowns.ADSET_ID,
          fields: [],
          disableSummaryBreakdown: !0,
          name: s._(/*BTDS*/ "Ad Set"),
          unsupportedTypes: r("filterValues")(
            r("objectValues")(r("AdsInsightsBreakdownEntryGroups")),
            [r("AdsInsightsBreakdownEntryGroups").OBJECT],
          ),
          tooltip: s._(
            /*BTDS*/ "This shows the breakdown of results by ad set.",
          ),
        },
        {
          breakdown: o("AdsInsightsBreakdownsSpec").ObjectBreakdowns.AD_NAME,
          fields: [],
          disableSummaryBreakdown: !0,
          name: s._(/*BTDS*/ "Ad Name"),
          unsupportedTypes: r("filterValues")(
            r("objectValues")(r("AdsInsightsBreakdownEntryGroups")),
            [r("AdsInsightsBreakdownEntryGroups").OBJECT],
          ),
          tooltip: s._(
            /*BTDS*/ "This shows the breakdown of results by ad name.",
          ),
        },
        {
          breakdown: o("AdsInsightsBreakdownsSpec").ObjectBreakdowns.ADSET_NAME,
          fields: [],
          disableSummaryBreakdown: !0,
          name: s._(/*BTDS*/ "Ad Set Name"),
          unsupportedTypes: r("filterValues")(
            r("objectValues")(r("AdsInsightsBreakdownEntryGroups")),
            [r("AdsInsightsBreakdownEntryGroups").OBJECT],
          ),
          tooltip: s._(
            /*BTDS*/ "This shows the breakdown of results by ad set name.",
          ),
        },
      ]));
    var p = c.impression
      .concat(c.action)
      .filter(function (e) {
        return (
          e.breakdown !== "age" &&
          e.breakdown !== "gender" &&
          e.breakdown !== "creative_media_type"
        );
      })
      .map(function (e) {
        return e.breakdown;
      });
    ((c.asset = [
      {
        breakdown: "image_asset",
        cutoffTime: r("PenguinConfig").CUTOFF_TIME_DEMOGRAPHICS,
        fields: [r("AdsInsightsField").IMAGE_ASSET],
        name: r("AdsInsightsMetricNames").image_asset,
        unsupported: p,
        tooltip: s._(
          /*BTDS*/ "View your data by image. These values are estimated. For offsite conversion metrics, this breakdown is in development.",
        ),
      },
      {
        breakdown: "video_asset",
        cutoffTime: r("PenguinConfig").CUTOFF_TIME_DEMOGRAPHICS,
        fields: [r("AdsInsightsField").VIDEO_ASSET],
        name: r("AdsInsightsMetricNames").video_asset,
        unsupported: p,
        tooltip: s._(
          /*BTDS*/ "View your data by video. These values are estimated. For offsite conversion metrics, this breakdown is in development.",
        ),
      },
      {
        breakdown: "media_asset",
        cutoffTime: r("PenguinConfig").CUTOFF_TIME_DEMOGRAPHICS,
        fields: [r("AdsInsightsField").MEDIA_ASSET],
        name: r("AdsInsightsMetricNames").media_asset,
        unsupported: ["age", "gender"].concat(p),
        tooltip: s._(
          /*BTDS*/ "View your data by image, media and slideshow. These values are estimated. For offsite conversion metrics, this breakdown is in development.",
        ),
      },
      {
        breakdown: "link_url_asset",
        cutoffTime: r("PenguinConfig").CUTOFF_TIME_DEMOGRAPHICS,
        fields: [r("AdsInsightsField").LINK_URL_ASSET],
        name: r("AdsInsightsMetricNames").link_url_asset,
        unsupported: p,
        tooltip: s._(
          /*BTDS*/ "View your data by website URL. These values are estimated. For offsite conversion metrics, this breakdown is in development.",
        ),
      },
      {
        breakdown: "body_asset",
        cutoffTime: r("PenguinConfig").CUTOFF_TIME_DEMOGRAPHICS,
        fields: [r("AdsInsightsField").BODY_ASSET],
        name: r("AdsInsightsMetricNames").body_asset,
        unsupported: p,
        tooltip: s._(
          /*BTDS*/ "View your data by text. These values are estimated. For offsite conversion metrics, this breakdown is in development.",
        ),
      },
      {
        breakdown: "title_asset",
        cutoffTime: r("PenguinConfig").CUTOFF_TIME_DEMOGRAPHICS,
        fields: [r("AdsInsightsField").TITLE_ASSET],
        name: r("AdsInsightsMetricNames").title_asset,
        unsupported: p,
        tooltip: s._(
          /*BTDS*/ "View your data by headline. These values are estimated. For offsite conversion metrics, this breakdown is in development.",
        ),
      },
      {
        breakdown: "description_asset",
        cutoffTime: r("PenguinConfig").CUTOFF_TIME_DEMOGRAPHICS,
        fields: [r("AdsInsightsField").DESCRIPTION_ASSET],
        name: r("AdsInsightsMetricNames").description_asset,
        unsupported: p,
        tooltip: s._(
          /*BTDS*/ "View your data by link description. These values are estimated. For offsite conversion metrics, this breakdown is in development.",
        ),
      },
      {
        breakdown: "call_to_action_asset",
        cutoffTime: r("PenguinConfig").CUTOFF_TIME_DEMOGRAPHICS,
        fields: [r("AdsInsightsField").CALL_TO_ACTION_ASSET],
        name: r("AdsInsightsMetricNames").call_to_action_asset,
        unsupported: p,
        tooltip: s._(
          /*BTDS*/ "View your data by call to action. These values are estimated. For offsite conversion metrics, this breakdown is in development.",
        ),
      },
    ]),
      (c.settings = [
        {
          breakdown: "objective",
          fields: [r("AdsInsightsField").OBJECTIVE],
          name: r("AdsInsightsMetricNames").objective,
          unsupported: [],
          tooltip: s._(
            /*BTDS*/ "The objective you selected for your campaign. Your objective reflects the goal you want to achieve with your advertising.",
          ),
        },
      ]),
      (c.attribution_setting_breakdowns = [
        {
          breakdown: o("AdsInsightsBreakdownsSpec").AttributionSettingBreakdowns
            .ATTRIBUTION_SETTING,
          fields: [r("AdsInsightsField").ATTRIBUTION_SETTING],
          name: s._(/*BTDS*/ "Attribution settings"),
          unsupportedTypes: r("filterValues")(
            r("objectValues")(r("AdsInsightsBreakdownEntryGroups")),
            [
              r("AdsInsightsBreakdownEntryGroups")
                .ATTRIBUTION_SETTING_BREAKDOWNS,
            ],
          ),
          tooltip: y(),
        },
        {
          breakdown: o("AdsInsightsBreakdownsSpec").AttributionSettingBreakdowns
            .CONVERSION_COUNT,
          fields: [r("AdsInsightsField").ATTRIBUTION_SETTING],
          name: s._(/*BTDS*/ "Conversion count"),
          unsupportedTypes: r("filterValues")(
            r("objectValues")(r("AdsInsightsBreakdownEntryGroups")),
            [
              r("AdsInsightsBreakdownEntryGroups")
                .ATTRIBUTION_SETTING_BREAKDOWNS,
            ],
          ),
          label: s._(/*BTDS*/ "Conversion count"),
          tooltip: C(),
        },
      ]),
      (c.creative = [
        {
          breakdown: "flexible_format_asset_type",
          fields: [r("AdsInsightsField").FLEXIBLE_FORMAT_ASSET_TYPE],
          name: r("AdsInsightsMetricNames").flexible_format_asset_type,
          unsupportedTypes: r("filterValues")(
            r("objectValues")(r("AdsInsightsBreakdownEntryGroups")),
            [r("AdsInsightsBreakdownEntryGroups").CREATIVE],
          ),
          tooltip: s._(
            /*BTDS*/ "View your data by flexible format. These values are estimated.",
          ),
        },
        {
          breakdown: "gen_ai_asset_type",
          fields: [r("AdsInsightsField").GEN_AI_ASSET_TYPE],
          name: r("AdsInsightsMetricNames").gen_ai_asset_type,
          unsupportedTypes: r("filterValues")(
            r("objectValues")(r("AdsInsightsBreakdownEntryGroups")),
            [r("AdsInsightsBreakdownEntryGroups").CREATIVE],
          ),
          tooltip: s._(
            /*BTDS*/ "View your data by generated images. These values are estimated.",
          ),
        },
        {
          breakdown: "creative_relaxation_asset_type",
          fields: [r("AdsInsightsField").CREATIVE_RELAXATION_ASSET_TYPE],
          name: r("AdsInsightsMetricNames").creative_relaxation_asset_type,
          unsupportedTypes: r("filterValues")(
            r("objectValues")(r("AdsInsightsBreakdownEntryGroups")),
            [r("AdsInsightsBreakdownEntryGroups").CREATIVE],
          ),
          tooltip: s._(
            /*BTDS*/ "View reporting for related media added to your ad. These values are estimated.",
          ),
        },
        {
          breakdown: "creative_automation_asset_id",
          fields: [r("AdsInsightsField").CREATIVE_AUTOMATION_ASSET_ID],
          name: r("AdsInsightsMetricNames").creative_automation_asset_id,
          unsupportedTypes: r("filterValues")(
            r("objectValues")(r("AdsInsightsBreakdownEntryGroups")),
            [
              r("AdsInsightsBreakdownEntryGroups").TIME,
              r("AdsInsightsBreakdownEntryGroups").CREATIVE,
            ].concat(
              o(
                "AdsMgmt2026H1BreakdownExperimentUtils",
              ).getIsAccountInMultiMediaPlacementBreakdownWithoutExposure()
                ? [r("AdsInsightsBreakdownEntryGroups").IMPRESSION]
                : [],
            ),
          ),
          tooltip: s._(
            /*BTDS*/ "View your data by media used in the ad. These values are estimated.",
          ),
        },
      ]));
    var _ = r("memoize")(function () {
      var e = {},
        t = {};
      return (
        Object.keys(c).forEach(function (n) {
          (c[n].forEach(function (t) {
            t.fields.length === 1 &&
              (t.label = o("AdsInsightsFields").getConfig(t.fields[0]).label);
            var n = o("AdsBreakdownPluginToBaseConfigAdapter").getBaseConfig(
                t.breakdown,
              ),
              r = o("AdsBreakdownPluginShadowValidator").validateBaseConfig(
                t.breakdown,
                t,
                n,
              );
            (o("AdsBreakdownPluginShadowValidator").logMismatches(r),
              (e[t.breakdown] = t));
          }),
            (t[n] = c[n].map(function (e) {
              return e.breakdown;
            })));
        }),
        { configsByID: e, idsByType: t }
      );
    });
    function f() {
      return _().configsByID;
    }
    function g() {
      return _().idsByType;
    }
    function h() {
      return s._(
        /*BTDS*/ "The number of purchase events (also known as orders) that were driven by your ads that included at least one product that prioritized conversions within a product set. {newline}{newline2} This metric counts the number of purchases that occurred after someone clicked or viewed a product in your ad that is set to prioritize conversions within its promoted product set. It only includes purchase events from eligible campaigns depending on your ads attribution settings.",
        [
          s._param("newline", u.jsx("br", {})),
          s._param("newline2", u.jsx("br", {})),
        ],
      );
    }
    h.displayName = h.name + " [from " + i.id + "]";
    function y() {
      return s._(
        /*BTDS*/ "View your data by attribution setting to see your conversions for various time windows and engagement types. {newline}{newline2}{learn more}",
        [
          s._param("newline", u.jsx("br", {})),
          s._param("newline2", u.jsx("br", {})),
          s._param(
            "learn more",
            u.jsx(r("AdsLearnMore.react"), {
              cmsID: "460276478298895",
              label: s._(/*BTDS*/ "About attribution settings"),
            }),
          ),
        ],
      );
    }
    y.displayName = y.name + " [from " + i.id + "]";
    function C() {
      return s._(
        /*BTDS*/ "View your data by conversion count to see the first conversion or all other conversions that happened after someone clicked or viewed your ad. {newline}{newline2}{learn more}",
        [
          s._param("newline", u.jsx("br", {})),
          s._param("newline2", u.jsx("br", {})),
          s._param(
            "learn more",
            u.jsx(r("AdsLearnMore.react"), {
              cmsID: "1237668294871467",
              label: s._(/*BTDS*/ "About conversion count"),
            }),
          ),
        ],
      );
    }
    ((C.displayName = C.name + " [from " + i.id + "]"),
      (l.getConfigsByID = f),
      (l.getIdsByType = g));
  },
  226,
);
