__d(
  "AdsInsightsField",
  [],
  function (t, n, r, o, a, i) {
    var e = Object.freeze({
      ACCOUNT_CREATIVE_THEMES: "account_creative_themes",
      ACCOUNT_ID: "account_id",
      ACCOUNT_NAME: "account_name",
      ACTION_BRAND: "action_brand",
      ACTION_BRAND_NAME: "action_brand_name",
      ACTION_CATEGORY: "action_category",
      ACTION_CATEGORY_NAME: "action_category_name",
      ACTION_CONVERTED_PRODUCT_ID: "action_converted_product_id",
      ACTION_DEVICE: "action_device",
      ACTIVITY_RECENCY: "activity_recency",
      AD_FORMAT_ASSET: "ad_format_asset",
      AD_IMPRESSION_VALUE: "ad_impression_value",
      ADGROUP_BID_TYPE: "adgroup_bid_type",
      ADGROUP_BID_VALUE: "adgroup_bid_value",
      ADGROUP_DELIVERY: "adgroup_delivery",
      ADGROUP_ID: "adgroup_id",
      ADGROUP_NAME: "adgroup_name",
      ADJUSTED_OFFLINE_PURCHASE: "adjusted_offline_purchase",
      ADS_FORMAT_ANALYSIS: "ads_format_analysis",
      ADVANCED_ACTIONS_28D_VIEW: "advanced_actions_28d_view",
      ADVANCED_REACH_1D_LOOKBACK: "advanced_reach_1d_lookback",
      ADVANCED_REACH_28D_LOOKBACK: "advanced_reach_28d_lookback",
      ADVANCED_REACH_7D_LOOKBACK: "advanced_reach_7d_lookback",
      AGE: "age",
      AGENCY_FEE_AMOUNT: "agency_fee_amount",
      AGENCY_FEE_MARKUP: "agency_fee_markup",
      ANCHOR_EVENT_ATTRIBUTION_SETTING: "anchor_event_attribution_setting",
      ANCHOR_EVENTS: "anchor_events",
      ANCHOR_EVENTS_PERFORMANCE_INDICATOR:
        "anchor_events_performance_indicator",
      APP_ID: "app_id",
      AR_EFFECT_SHARE: "ar_effect_share",
      ATTENTION_EVENTS_PER_IMPRESSION: "attention_events_per_impression",
      ATTRIBUTION_SETTING: "attribution_setting",
      AVERAGE_PURCHASES_CONVERSION_VALUE: "average_purchases_conversion_value",
      BILLABLE_AMOUNT_SPENT: "billable_amount_spent",
      BODY_ASSET: "body_asset",
      BODY_ASSET_VALUE: "body_asset_value",
      BUDGET_TOTAL_DAILY: "budget_total_daily",
      BUSINESS_CONTACT_OPTION_CLICKS: "business_contact_option_clicks",
      BUSINESS_IMAGE_CLICKS: "business_image_clicks",
      BUYING_TYPE: "buying_type",
      CALL_TO_ACTION_ASSET: "call_to_action_asset",
      CALL_TO_ACTION_ASSET_VALUE: "call_to_action_asset_value",
      CAMPAIGN_BID_TYPE: "campaign_bid_type",
      CAMPAIGN_BID_VALUE: "campaign_bid_value",
      CAMPAIGN_BUDGET_TYPE: "campaign_budget_type",
      CAMPAIGN_BUDGET_VALUE: "campaign_budget_value",
      CAMPAIGN_DELIVERY: "campaign_delivery",
      CAMPAIGN_END: "campaign_end",
      CAMPAIGN_GROUP_BUDGET_TYPE: "campaign_group_budget_type",
      CAMPAIGN_GROUP_BUDGET_VALUE: "campaign_group_budget_value",
      CAMPAIGN_GROUP_DELIVERY: "campaign_group_delivery",
      CAMPAIGN_GROUP_END: "campaign_group_end",
      CAMPAIGN_GROUP_ID: "campaign_group_id",
      CAMPAIGN_GROUP_NAME: "campaign_group_name",
      CAMPAIGN_GROUP_START: "campaign_group_start",
      CAMPAIGN_ID: "campaign_id",
      CAMPAIGN_NAME: "campaign_name",
      CAMPAIGN_START: "campaign_start",
      CANCEL_SUBSCRIPTION_ACTIONS: "cancel_subscription_actions",
      CANCEL_SUBSCRIPTION_VALUE: "cancel_subscription_value",
      CANVAS_AVG_VIEW_PERCENT: "canvas_avg_view_percent",
      CANVAS_AVG_VIEW_TIME: "canvas_avg_view_time",
      CATALOG_SEGMENT_ACTIONS: "catalog_segment_actions",
      CATALOG_SEGMENT_VALUE_IN_CATALOG_CURRENCY:
        "catalog_segment_value_in_catalog_currency",
      CATALOG_SEGMENT_VALUE_MOBILE_PURCHASE_ROAS:
        "catalog_segment_value_mobile_purchase_roas",
      CATALOG_SEGMENT_VALUE_WEBSITE_PURCHASE_ROAS:
        "catalog_segment_value_website_purchase_roas",
      CLICKS_TO_BUSINESS_AI: "clicks_to_business_ai",
      COARSE_CONVERSION_VALUE: "coarse_conversion_value",
      COMSCORE_MARKET: "comscore_market",
      COMSCORE_MARKET_CODE: "comscore_market_code",
      CONFIGURABLE_ATTRIBUTION_ACTION: "configurable_attribution_action",
      CONFIGURABLE_ATTRIBUTION_ACTIONVALUE:
        "configurable_attribution_actionvalue",
      CONFIGURABLE_AUDIENCE_OVERLAP_REACH:
        "configurable_audience_overlap_reach",
      CONFIGURABLE_REACHBYFREQUENCY_ACTION:
        "configurable_reachbyfrequency_action",
      CONFIGURABLE_REACHBYFREQUENCY_CONVERTERS_COUNT:
        "configurable_reachbyfrequency_converters_count",
      CONFIGURABLE_REACHBYFREQUENCY_IMPRESSIONS_COST:
        "configurable_reachbyfrequency_impressions_cost",
      CONFIGURABLE_REACHBYFREQUENCY_IMPRESSIONS_COUNT:
        "configurable_reachbyfrequency_impressions_count",
      CONFIGURABLE_REACHBYFREQUENCY_REACH:
        "configurable_reachbyfrequency_reach",
      CONTACT_ACTIONS: "contact_actions",
      CONTACT_VALUE: "contact_value",
      CONVERSION_DESTINATION: "conversion_destination",
      CONVERSION_LEAD_RATE: "conversion_lead_rate",
      CONVERSION_VALUES: "conversion_values",
      CONVERSIONS: "conversions",
      CONVERTED_PRODUCT_APP_CUSTOM_EVENT_FB_MOBILE_PURCHASE:
        "converted_product_app_custom_event_fb_mobile_purchase",
      CONVERTED_PRODUCT_APP_CUSTOM_EVENT_FB_MOBILE_PURCHASE_VALUE:
        "converted_product_app_custom_event_fb_mobile_purchase_value",
      CONVERTED_PRODUCT_COUNT: "converted_product_count",
      CONVERTED_PRODUCT_OFFLINE_PURCHASE: "converted_product_offline_purchase",
      CONVERTED_PRODUCT_OFFLINE_PURCHASE_VALUE:
        "converted_product_offline_purchase_value",
      CONVERTED_PRODUCT_OMNI_PURCHASE: "converted_product_omni_purchase",
      CONVERTED_PRODUCT_OMNI_PURCHASE_VALUES:
        "converted_product_omni_purchase_values",
      CONVERTED_PRODUCT_QUANTITY: "converted_product_quantity",
      CONVERTED_PRODUCT_VALUE: "converted_product_value",
      CONVERTED_PRODUCT_WEBSITE_PIXEL_PURCHASE:
        "converted_product_website_pixel_purchase",
      CONVERTED_PRODUCT_WEBSITE_PIXEL_PURCHASE_VALUE:
        "converted_product_website_pixel_purchase_value",
      CONVERTED_PROMOTED_PRODUCT_APP_CUSTOM_EVENT_FB_MOBILE_PURCHASE:
        "converted_promoted_product_app_custom_event_fb_mobile_purchase",
      CONVERTED_PROMOTED_PRODUCT_APP_CUSTOM_EVENT_FB_MOBILE_PURCHASE_VALUE:
        "converted_promoted_product_app_custom_event_fb_mobile_purchase_value",
      CONVERTED_PROMOTED_PRODUCT_OFFLINE_PURCHASE:
        "converted_promoted_product_offline_purchase",
      CONVERTED_PROMOTED_PRODUCT_OFFLINE_PURCHASE_VALUE:
        "converted_promoted_product_offline_purchase_value",
      CONVERTED_PROMOTED_PRODUCT_OMNI_PURCHASE:
        "converted_promoted_product_omni_purchase",
      CONVERTED_PROMOTED_PRODUCT_OMNI_PURCHASE_VALUES:
        "converted_promoted_product_omni_purchase_values",
      CONVERTED_PROMOTED_PRODUCT_QUANTITY:
        "converted_promoted_product_quantity",
      CONVERTED_PROMOTED_PRODUCT_VALUE: "converted_promoted_product_value",
      CONVERTED_PROMOTED_PRODUCT_WEBSITE_PIXEL_PURCHASE:
        "converted_promoted_product_website_pixel_purchase",
      CONVERTED_PROMOTED_PRODUCT_WEBSITE_PIXEL_PURCHASE_VALUE:
        "converted_promoted_product_website_pixel_purchase_value",
      COST_PER_10_SEC_VIDEO_VIEW: "cost_per_10_sec_video_view",
      COST_PER_15_SEC_VIDEO_VIEW: "cost_per_15_sec_video_view",
      COST_PER_2_SEC_CONTINUOUS_VIDEO_VIEW:
        "cost_per_2_sec_continuous_video_view",
      COST_PER_6_SEC_VIDEO_VIEW: "cost_per_6_sec_video_view",
      COST_PER_AD_CLICK: "cost_per_ad_click",
      COST_PER_COMPLETED_VIDEO_VIEW: "cost_per_completed_video_view",
      COST_PER_CONTACT: "cost_per_contact",
      COST_PER_CONVERSION_LEAD: "cost_per_conversion_lead",
      COST_PER_CUSTOMIZE_PRODUCT: "cost_per_customize_product",
      COST_PER_DDA_COUNTBY_CONVS: "cost_per_dda_countby_convs",
      COST_PER_DONATE: "cost_per_donate",
      COST_PER_FIND_LOCATION: "cost_per_find_location",
      COST_PER_MESSAGE_DELIVERED: "cost_per_message_delivered",
      COST_PER_ONE_THOUSAND_AD_IMPRESSION:
        "cost_per_one_thousand_ad_impression",
      COST_PER_OUTBOUND_CLICK: "cost_per_outbound_click",
      COST_PER_POST_CONVERSION_SIGNAL: "cost_per_post_conversion_signal",
      COST_PER_SCHEDULE: "cost_per_schedule",
      COST_PER_START_TRIAL: "cost_per_start_trial",
      COST_PER_STORE_VISIT: "cost_per_store_visit",
      COST_PER_STORE_VISIT_ACTION: "cost_per_store_visit_action",
      COST_PER_SUBMIT_APPLICATION: "cost_per_submit_application",
      COST_PER_SUBSCRIBE: "cost_per_subscribe",
      COST_PER_THRUPLAY: "cost_per_thruplay",
      COST_PER_UNIQUE_CLICK: "cost_per_unique_click",
      COST_PER_UNIQUE_OUTBOUND_CLICK: "cost_per_unique_outbound_click",
      COUNTRY: "country",
      CPC: "cpc",
      CPM: "cpm",
      CPP: "cpp",
      CPR_BENCHMARK: "cpr_benchmark",
      CREATIVE_AD_IDS: "creative_ad_ids",
      CREATIVE_AUTOMATION_ASSET_ID: "creative_automation_asset_id",
      CREATIVE_DELIVERY_INFO: "creative_delivery_info",
      CREATIVE_DIVERSITY_DATA: "creative_diversity_data",
      CREATIVE_DIVERSITY_LABEL: "creative_diversity_label",
      CREATIVE_DIVERSITY_SCORE: "creative_diversity_score",
      CREATIVE_FATIGUE_SUMMARY: "creative_fatigue_summary",
      CREATIVE_FATIGUED_ADS: "creative_fatigued_ads",
      CREATIVE_FINGERPRINT: "creative_fingerprint",
      CREATIVE_NAME: "creative_name",
      CREATIVE_OPPORTUNITY: "creative_opportunity",
      CREATIVE_SIMILARITY_SCORE: "creative_similarity_score",
      CTR: "ctr",
      CUSTOMIZE_PRODUCT_ACTIONS: "customize_product_actions",
      CUSTOMIZE_PRODUCT_VALUE: "customize_product_value",
      DATE_CREATED: "created_time",
      DATE_START: "date_start",
      DATE_STOP: "date_stop",
      DATE_UPDATED: "updated_time",
      DDA_COUNTBY_CONVS: "dda_countby_convs",
      DDA_RESULTS: "dda_results",
      DESCRIPTION_ASSET: "description_asset",
      DESCRIPTION_ASSET_VALUE: "description_asset_value",
      DIRECT_WEBSITE_PURCHASES: "direct_website_purchases",
      DIRECT_WEBSITE_PURCHASES_CONVERSION_VALUE:
        "direct_website_purchases_conversion_value",
      DONATE_ACTIONS: "donate_actions",
      DONATE_VALUE: "donate_value",
      EARNED_IMPRESSION: "earned_impression",
      FIDELITY_TYPE: "fidelity_type",
      FIND_LOCATION_ACTIONS: "find_location_actions",
      FIND_LOCATION_VALUE: "find_location_value",
      GENDER: "gender",
      HISTORICAL_BENCHMARK: "historical_benchmark",
      HSID: "hsid",
      IMAGE_ASSET: "image_asset",
      IMAGE_ASSET_VALUE: "image_asset_value",
      IMPRESSION_DEVICE: "impression_device",
      IMPRESSION_VIEW_TIME_ADVERTISER_HOUR:
        "impression_view_time_advertiser_hour",
      IMPRESSION_VIEW_TIME_USER_HOUR: "impression_view_time_user_hour",
      IMPRESSIONS: "impressions",
      INDUSTRY_CREATIVE_THEMES: "industry_creative_themes",
      INSTAGRAM_UPCOMING_EVENT_REMINDER_TOGGLE_OFF:
        "instagram_upcoming_event_reminder_toggle_off",
      INSTAGRAM_UPCOMING_EVENT_REMINDER_TOGGLE_ON:
        "instagram_upcoming_event_reminder_toggle_on",
      INSTAGRAM_UPCOMING_EVENT_REMINDERS_SET:
        "instagram_upcoming_event_reminders_set",
      INSTANT_EXPERIENCE_CLICKS_TO_OPEN: "instant_experience_clicks_to_open",
      INSTANT_EXPERIENCE_CLICKS_TO_START: "instant_experience_clicks_to_start",
      INSTANT_EXPERIENCE_ELEMENT_IMPRESSIONS:
        "instant_experience_element_impressions",
      INSTANT_EXPERIENCE_ELEMENT_REACH: "instant_experience_element_reach",
      INSTANT_EXPERIENCE_OUTBOUND_CLICKS: "instant_experience_outbound_clicks",
      INTERACTIVE_COMPONENT_STICKER_ID: "interactive_component_sticker_id",
      INTERACTIVE_COMPONENT_STICKER_RESPONSE:
        "interactive_component_sticker_response",
      INTERACTIVE_COMPONENT_TAP: "interactive_component_tap",
      IS_AUTO_ADVANCE: "is_auto_advance",
      IS_BUSINESS_AI_ASSISTED: "is_business_ai_assisted",
      IS_CONVERSION_ID_MODELED: "is_conversion_id_modeled",
      IS_VIDEO: "is_video",
      LANDING_DESTINATION: "landing_destination",
      LANDING_PAGE_VIEW_ACTIONS_PER_LINK_CLICK:
        "landing_page_view_actions_per_link_click",
      LANDING_PAGE_VIEW_PER_LINK_CLICK: "landing_page_view_per_link_click",
      LANDING_PAGE_VIEW_PER_PURCHASE_RATE:
        "landing_page_view_per_purchase_rate",
      LAST_SIGNIFICANT_EDIT: "last_significant_edit",
      LINK_CLICKS_PER_RESULTS: "link_clicks_per_results",
      LINK_URL_ASSET: "link_url_asset",
      LINK_URL_ASSET_VALUE: "link_url_asset_value",
      LIVE_VIDEO_ADS_VIDEO15SEC_WATCHED_ACTION:
        "live_video_ads_video15sec_watched_action",
      MARKETING_MESSAGES_ACTIVATE_APP_ACTIONS:
        "marketing_messages_activate_app_actions",
      MARKETING_MESSAGES_APP_ADD_TO_CART: "marketing_messages_app_add_to_cart",
      MARKETING_MESSAGES_APP_INITIATE_CHECKOUT:
        "marketing_messages_app_initiate_checkout",
      MARKETING_MESSAGES_APP_PURCHASE: "marketing_messages_app_purchase",
      MARKETING_MESSAGES_APP_PURCHASE_VALUES:
        "marketing_messages_app_purchase_values",
      MARKETING_MESSAGES_CLICK_RATE_BENCHMARK:
        "marketing_messages_click_rate_benchmark",
      MARKETING_MESSAGES_COST_PER_DELIVERED:
        "marketing_messages_cost_per_delivered",
      MARKETING_MESSAGES_COST_PER_LINK_BTN_CLICK:
        "marketing_messages_cost_per_link_btn_click",
      MARKETING_MESSAGES_DELIVERED: "marketing_messages_delivered",
      MARKETING_MESSAGES_DELIVERY_RATE: "marketing_messages_delivery_rate",
      MARKETING_MESSAGES_LANGUAGE: "marketing_messages_language",
      MARKETING_MESSAGES_LINK_BTN_CLICK: "marketing_messages_link_btn_click",
      MARKETING_MESSAGES_LINK_BTN_CLICK_RATE:
        "marketing_messages_link_btn_click_rate",
      MARKETING_MESSAGES_MEDIA_VIEW_RATE: "marketing_messages_media_view_rate",
      MARKETING_MESSAGES_MEDIA_VIEWED: "marketing_messages_media_viewed",
      MARKETING_MESSAGES_PHONE_CALL_BTN_CLICK:
        "marketing_messages_phone_call_btn_click",
      MARKETING_MESSAGES_PHONE_CALL_BTN_CLICK_RATE:
        "marketing_messages_phone_call_btn_click_rate",
      MARKETING_MESSAGES_QUICK_REPLY_BTN_CLICK:
        "marketing_messages_quick_reply_btn_click",
      MARKETING_MESSAGES_QUICK_REPLY_BTN_CLICK_RATE:
        "marketing_messages_quick_reply_btn_click_rate",
      MARKETING_MESSAGES_READ: "marketing_messages_read",
      MARKETING_MESSAGES_READ_RATE: "marketing_messages_read_rate",
      MARKETING_MESSAGES_READ_RATE_BENCHMARK:
        "marketing_messages_read_rate_benchmark",
      MARKETING_MESSAGES_SENT: "marketing_messages_sent",
      MARKETING_MESSAGES_SPEND: "marketing_messages_spend",
      MARKETING_MESSAGES_SPEND_CURRENCY: "marketing_messages_spend_currency",
      MARKETING_MESSAGES_TOP_BLOCK_REASON:
        "marketing_messages_top_block_reason",
      MARKETING_MESSAGES_WEBSITE_ADD_TO_CART:
        "marketing_messages_website_add_to_cart",
      MARKETING_MESSAGES_WEBSITE_INITIATE_CHECKOUT:
        "marketing_messages_website_initiate_checkout",
      MARKETING_MESSAGES_WEBSITE_PURCHASE:
        "marketing_messages_website_purchase",
      MARKETING_MESSAGES_WEBSITE_PURCHASE_VALUES:
        "marketing_messages_website_purchase_values",
      MEDIA_ASSET: "media_asset",
      MEDIA_ASSET_URL: "media_asset_url",
      MEDIA_CREATOR: "media_creator",
      MEDIA_DESTINATION_URL: "media_destination_url",
      MEDIA_FORMAT: "media_format",
      MEDIA_ORIGIN_URL: "media_origin_url",
      MEDIA_TEXT_CONTENT: "media_text_content",
      MEDIA_TYPE: "media_type",
      MEDIA_VIEWS: "media_views",
      MESSAGES_DELIVERED: "messages_delivered",
      MESSAGES_DELIVERED_CTR: "messages_delivered_ctr",
      MESSAGES_SENT: "messages_sent",
      MOBILE_APP_PURCHASE_ROAS: "mobile_app_purchase_roas",
      MSA_SELLER_BUDGET: "msa_seller_budget",
      MSA_SELLER_ID: "msa_seller_id",
      MSA_SELLER_NAME: "msa_seller_name",
      MULTI_EVENT_CONVERSION_ATTRIBUTION_SETTING:
        "multi_event_conversion_attribution_setting",
      NUM_ACTIVE_CAMPAIGN_GROUPS: "num_active_campaign_groups",
      NUM_CAMPAIGN_GROUPS: "num_campaign_groups",
      NUM_CAMPAIGNS: "num_campaigns",
      NUM_CREATIVE_AD_IDS: "num_creative_ad_ids",
      OBJECTIVE: "objective",
      ONSITE_CONVERSION_MESSAGING_DETECTED_PURCHASE_DEDUPED:
        "onsite_conversion_messaging_detected_purchase_deduped",
      ONSITE_CONVERSION_MESSAGING_ORDER_CREATED_V2:
        "onsite_conversion_messaging_order_created_v2",
      ONSITE_CONVERSION_MESSAGING_ORDER_SHIPPED_V2:
        "onsite_conversion_messaging_order_shipped_v2",
      OPPORTUNITY_SCORE_L4: "opportunity_score_l4",
      OPTIMIZATION_GOAL: "optimization_goal",
      OUTBOUND_CLICKS: "outbound_clicks",
      OUTBOUND_CLICKS_CTR: "outbound_clicks_ctr",
      PA_CREATOR_IG_HANDLE: "pa_creator_ig_handle",
      PERFORMANCE_INDICATOR: "performance_indicator",
      PLAYABLE_AVERAGE_GAME_LENGTH: "playable_average_game_length",
      PLAYABLE_CTA_CLICK: "playable_cta_click",
      PLAYABLE_DISMISSED: "playable_dismissed",
      PLAYABLE_GAME_START_RATE: "playable_game_start_rate",
      PLAYABLE_GAME_STARTED: "playable_game_started",
      PLAYABLE_PRESENTED: "playable_presented",
      POST_CONVERSION_SIGNAL_RESULT: "post_conversion_signal_result",
      POSTBACK_SEQUENCE_INDEX: "postback_sequence_index",
      PRIVATE_ATTRIBUTION_CONVERSIONS: "private_attribution_conversions",
      PRIVATE_ATTRIBUTION_SALES: "private_attribution_sales",
      PRODUCT_BRAND: "product_brand",
      PRODUCT_BRAND_BREAKDOWN: "product_brand_breakdown",
      PRODUCT_CATEGORY: "product_category",
      PRODUCT_CATEGORY_BREAKDOWN: "product_category_breakdown",
      PRODUCT_CONTENT_ID: "product_content_id",
      PRODUCT_CUSTOM_LABEL_0: "product_custom_label_0",
      PRODUCT_CUSTOM_LABEL_0_BREAKDOWN: "product_custom_label_0_breakdown",
      PRODUCT_CUSTOM_LABEL_1: "product_custom_label_1",
      PRODUCT_CUSTOM_LABEL_1_BREAKDOWN: "product_custom_label_1_breakdown",
      PRODUCT_CUSTOM_LABEL_2: "product_custom_label_2",
      PRODUCT_CUSTOM_LABEL_2_BREAKDOWN: "product_custom_label_2_breakdown",
      PRODUCT_CUSTOM_LABEL_3: "product_custom_label_3",
      PRODUCT_CUSTOM_LABEL_3_BREAKDOWN: "product_custom_label_3_breakdown",
      PRODUCT_CUSTOM_LABEL_4: "product_custom_label_4",
      PRODUCT_CUSTOM_LABEL_4_BREAKDOWN: "product_custom_label_4_breakdown",
      PRODUCT_CUSTOM_NUMBER_0: "product_custom_number_0",
      PRODUCT_CUSTOM_NUMBER_1: "product_custom_number_1",
      PRODUCT_CUSTOM_NUMBER_2: "product_custom_number_2",
      PRODUCT_CUSTOM_NUMBER_3: "product_custom_number_3",
      PRODUCT_CUSTOM_NUMBER_4: "product_custom_number_4",
      PRODUCT_GROUP_CONTENT_ID: "product_group_content_id",
      PRODUCT_GROUP_CONTENT_ID_BREAKDOWN: "product_group_content_id_breakdown",
      PRODUCT_GROUP_RETAILER_ID: "product_group_retailer_id",
      PRODUCT_ID: "product_id",
      PRODUCT_NAME: "product_name",
      PRODUCT_RETAILER_ID: "product_retailer_id",
      PRODUCT_SET_ID_BREAKDOWN: "product_set_id_breakdown",
      PRODUCT_VENDOR_ID: "product_vendor_id",
      PRODUCT_VENDOR_ID_BREAKDOWN: "product_vendor_id_breakdown",
      PRODUCT_VIEWS: "product_views",
      PROMOTED_PRODUCT_SET_RESULT: "promoted_product_set_result",
      PROMOTED_PRODUCT_SET_VALUE: "promoted_product_set_value",
      PURCHASE_PER_LANDING_PAGE_VIEW: "purchase_per_landing_page_view",
      PURCHASES_PER_LINK_CLICK: "purchases_per_link_click",
      QUALIFYING_QUESTION_ANSWER: "qualifying_question_answer",
      QUALIFYING_QUESTION_ANSWER_WITH_QUALIFIED_OPTION:
        "qualifying_question_answer_with_qualified_option",
      QUALIFYING_QUESTION_QUALIFY_ANSWER_RATE:
        "qualifying_question_qualify_answer_rate",
      READ_RATE: "read_rate",
      REALTIME_CLICKS: "realtime_clicks",
      REALTIME_IMPRESSION_SPEND: "realtime_impression_spend",
      REALTIME_IMPRESSIONS: "realtime_impressions",
      RECURRING_SUBSCRIPTION_PAYMENT_ACTIONS:
        "recurring_subscription_payment_actions",
      RECURRING_SUBSCRIPTION_PAYMENT_VALUE:
        "recurring_subscription_payment_value",
      REDOWNLOAD: "redownload",
      REGION: "region",
      REGION_ID: "region_id",
      REPEAT_REACH: "repeat_reach",
      RESULT_ADJUSTED_ROAS: "result_adjusted_roas",
      RESULT_ADJUSTED_VALUES: "result_adjusted_values",
      RESULT_ROAS: "result_roas",
      RESULT_VALUES: "result_values",
      RESULT_VALUES_PERFORMANCE_INDICATOR:
        "result_values_performance_indicator",
      RTA_UGC_TOPIC: "rta_ugc_topic",
      RULE_ASSET_VALUE: "rule_asset_value",
      SCHEDULE_ACTIONS: "schedule_actions",
      SCHEDULE_VALUE: "schedule_value",
      SHOP_CLICKS: "shop_clicks",
      SHOPS_ASSISTED_PURCHASES: "shops_assisted_purchases",
      SHOPS_ASSISTED_PURCHASES_CONVERSION_VALUE:
        "shops_assisted_purchases_conversion_value",
      SIGNAL_SOURCE_BUCKET: "signal_source_bucket",
      SKAN_CAMPAIGN_ID: "skan_campaign_id",
      SKAN_CONVERSION_ID: "skan_conversion_id",
      SKAN_VERSION: "skan_version",
      STANDARD_EVENT_CONTENT_TYPE: "standard_event_content_type",
      START_TRIAL_ACTIONS: "start_trial_actions",
      START_TRIAL_VALUE: "start_trial_value",
      STORE_VISIT_ACTIONS: "store_visit_actions",
      SUBMIT_APPLICATION_ACTIONS: "submit_application_actions",
      SUBMIT_APPLICATION_VALUE: "submit_application_value",
      SUBSCRIBE_ACTIONS: "subscribe_actions",
      SUBSCRIBE_VALUE: "subscribe_value",
      TITLE_ASSET: "title_asset",
      TITLE_ASSET_VALUE: "title_asset_value",
      TODAY_SPEND: "today_spend",
      TOTAL_CARD_VIEW: "total_card_view",
      TOTAL_POSTBACKS: "total_postbacks",
      TOTAL_POSTBACKS_DETAILED: "total_postbacks_detailed",
      TOTAL_POSTBACKS_DETAILED_V4: "total_postbacks_detailed_v4",
      UNIQUE_CONVERTED_PRODUCT_COUNT: "unique_converted_product_count",
      UNIQUE_CTR: "unique_ctr",
      UNIQUE_LINK_CLICKS_CTR: "unique_link_clicks_ctr",
      UNIQUE_OUTBOUND_CLICKS: "unique_outbound_clicks",
      UNIQUE_OUTBOUND_CLICKS_CTR: "unique_outbound_clicks_ctr",
      UNIQUE_VIDEO_CONTINUOUS_2_SEC_WATCHED_ACTIONS:
        "unique_video_continuous_2_sec_watched_actions",
      UNIQUE_VIDEO_VIEW_10_SEC: "unique_video_view_10_sec",
      UNIQUE_VIDEO_VIEW_15_SEC: "unique_video_view_15_sec",
      USER_SEGMENT_KEY: "user_segment_key",
      VIDEO_10_SEC_WATCHED_ACTIONS: "video_10_sec_watched_actions",
      VIDEO_15_SEC_WATCHED_ACTIONS: "video_15_sec_watched_actions",
      VIDEO_30_SEC_WATCHED_ACTIONS: "video_30_sec_watched_actions",
      VIDEO_6_SEC_WATCHED_ACTIONS: "video_6_sec_watched_actions",
      VIDEO_ASSET: "video_asset",
      VIDEO_ASSET_VALUE: "video_asset_value",
      VIDEO_AVG_TIME_WATCHED_ACTIONS: "video_avg_time_watched_actions",
      VIDEO_CONTINUOUS_2_SEC_WATCHED_ACTIONS:
        "video_continuous_2_sec_watched_actions",
      VIDEO_CTR_BY_SECOND: "video_ctr_by_second",
      VIDEO_HOLD_RATE: "video_hold_rate",
      VIDEO_HOOK_RATE: "video_hook_rate",
      VIDEO_P100_WATCHED_ACTIONS: "video_p100_watched_actions",
      VIDEO_P25_WATCHED_ACTIONS: "video_p25_watched_actions",
      VIDEO_P50_WATCHED_ACTIONS: "video_p50_watched_actions",
      VIDEO_P75_WATCHED_ACTIONS: "video_p75_watched_actions",
      VIDEO_P95_WATCHED_ACTIONS: "video_p95_watched_actions",
      VIDEO_PLAY_ACTIONS: "video_play_actions",
      VIDEO_PLAY_RETENTION_CURVE_ACTIONS: "video_play_retention_curve_actions",
      VIDEO_THRUPLAY_WATCHED_ACTIONS: "video_thruplay_watched_actions",
      VIDEO_VIEW_PER_IMPRESSION: "video_view_per_impression",
      WEBSITE_CTR: "website_ctr",
      WEBSITE_PURCHASE_ROAS: "website_purchase_roas",
      ZIP: "zip",
      PLR_CLICKS: "plr_clicks",
      PLR_SPEND: "plr_spend",
      PLR_CTR_DIFFERENCE: "plr_ctr_difference",
      PLR_IMPRESSIONS: "plr_impressions",
      PLR_CPC: "plr_cpc",
      PLR_COST_PER_INLINE_LINK_CLICK: "plr_cost_per_inline_link_click",
      PLR_INLINE_LINK_CLICKS: "plr_inline_link_clicks",
      PLR_INLINE_LINK_CLICK_CTR: "plr_inline_link_click_ctr",
      PLR_COST_PER_RESULT: "plr_cost_per_result",
      PLR_RESULTS: "plr_results",
      PLR_AVERAGE_PURCHASES_CONVERSION_VALUE:
        "plr_average_purchases_conversion_value",
      PLR_AD_PURCHASES_VALUE_PERCENTAGE: "plr_ad_purchases_value_percentage",
      RULE_SET_ID: "rule_set_id",
      RULE_SET_NAME: "rule_set_name",
      ACCOUNT_CURRENCY: "account_currency",
      ACCOUNT_DEFAULT_ATTRIBUTION_WINDOWS:
        "account_default_attribution_windows",
      ACCOUNT_TIMEZONE: "account_timezone",
      ACTION_CANVAS_COMPONENT_ID: "action_canvas_component_id",
      ACTION_CANVAS_COMPONENT_NAME: "action_canvas_component_name",
      ACTION_EVENT_CHANNEL: "action_event_channel",
      ACTION_LINK_CLICK_DESTINATION: "action_link_click_destination",
      ACTION_LOCATION_CODE: "action_location_code",
      ACTION_REACTION: "action_reaction",
      ACTION_RESULTS: "actions_results",
      ACTION_VIDEO_ASSET_ID: "action_video_asset_id",
      ACTIONS_PER_IMPRESSION: "actions_per_impression",
      AD_BID_TYPE: "ad_bid_type",
      AD_BID_VALUE: "ad_bid_value",
      AD_DELIVERY: "ad_delivery",
      AD_ID: "ad_id",
      AD_NAME: "ad_name",
      ADSET_BID_TYPE: "adset_bid_type",
      ADSET_BID_VALUE: "adset_bid_value",
      ADSET_BUDGET_TYPE: "adset_budget_type",
      ADSET_BUDGET_VALUE: "adset_budget_value",
      ADSET_DELIVERY: "adset_delivery",
      ADSET_END: "adset_end",
      ADSET_ID: "adset_id",
      ADSET_NAME: "adset_name",
      ADSET_START: "adset_start",
      APP_STORE_CLICKS: "app_store_clicks",
      ATTENTION_EVENTS_UNQ_PER_REACH: "attention_events_unq_per_reach",
      AUCTION_BID: "auction_bid",
      AUCTION_MAX_COMPETITOR_BID: "auction_max_competitor_bid",
      WISH_BID: "wish_bid",
      AUCTION_COMPETITIVENESS: "auction_competitiveness",
      USER_PERSONA_ID: "user_persona_id",
      USER_PERSONA_NAME: "user_persona_name",
      AD_EXTENSION_URL: "ad_extension_url",
      AD_EXTENSION_DOMAIN: "ad_extension_domain",
      BUDGET_GOAL: "budget_goal",
      CALL_TO_ACTION_CLICKS: "call_to_action_clicks",
      CANVAS_AVG_VIEW_PERCENT_PER_COMPONENT:
        "canvas_avg_view_percentage_per_component",
      CANVAS_COMPONENT_AVG_PCT_VIEW: "canvas_component_avg_pct_view",
      CARD_VIEWS: "card_views",
      CAROUSEL_CARD_ID: "action_carousel_card_id",
      CAROUSEL_CARD_NAME: "action_carousel_card_name",
      CLICKS: "clicks",
      CONVERSION_WINDOW: "conversion_window",
      COST_PER_DWELL_3_SEC: "cost_per_dwell_3_sec",
      COST_PER_DWELL_5_SEC: "cost_per_dwell_5_sec",
      COST_PER_DWELL_7_SEC: "cost_per_dwell_7_sec",
      COST_PER_DWELL_P50: "cost_per_dwell",
      COST_PER_ESTIMATED_AD_RECALLERS: "cost_per_estimated_ad_recallers",
      COST_PER_INLINE_POST_ENGAGEMENT: "cost_per_inline_post_engagement",
      COST_PER_INLINE_LINK_CLICK: "cost_per_inline_link_click",
      COST_PER_OBJECTIVE_RESULT: "cost_per_objective_result",
      COST_PER_OPTIMIZATION_RESULT: "cost_per_optimization_result",
      COST_PER_UNIQUE_INLINE_LINK_CLICK: "cost_per_unique_inline_link_click",
      COST_PER_RESULT: "cost_per_result",
      COST_PER_ACTION_RESULT: "cost_per_action_result",
      COST_PER_TOTAL_ACTIONS: "cost_per_total_action",
      AD_CREATIVE_LINK_URL: "ad_creative_link_url",
      CUMULATIVE_REACH: "cumulative_reach",
      LIFETIME_FREQUENCY: "lifetime_frequency",
      WEIGHTED_AD_LIFETIME_FREQUENCY: "weighted_ad_lifetime_frequency",
      NEW_REACH: "new_reach",
      DEAL_END: "deal_end",
      DEAL_START: "deal_start",
      DEDUPING_RATIO: "deduping_ratio",
      DEDUPING_1ST_SOURCE_AD: "deduping_1st_source_ad",
      DEDUPING_1ST_SOURCE_RATIO: "deduping_1st_source_ratio",
      DEDUPING_2ND_SOURCE_AD: "deduping_2nd_source_ad",
      DEDUPING_2ND_SOURCE_RATIO: "deduping_2nd_source_ratio",
      DEDUPING_3RD_SOURCE_AD: "deduping_3rd_source_ad",
      DEDUPING_3RD_SOURCE_RATIO: "deduping_3rd_source_ratio",
      DMA: "dma",
      DMA_CODE: "dma_code",
      DWELL_3_SEC: "dwell_3_sec",
      DWELL_5_SEC: "dwell_5_sec",
      DWELL_7_SEC: "dwell_7_sec",
      DWELL_P50_RATE: "dwell_rate",
      DEEPLINK_CLICKS: "deeplink_clicks",
      DESTINATION: "action_destination",
      ESTIMATED_AD_RECALLERS: "estimated_ad_recallers",
      ESTIMATED_AD_RECALLERS_LOWER_BOUND: "estimated_ad_recallers_lower_bound",
      ESTIMATED_AD_RECALLERS_UPPER_BOUND: "estimated_ad_recallers_upper_bound",
      ESTIMATED_AD_RECALL_RATE: "estimated_ad_recall_rate",
      ESTIMATED_AD_RECALL_RATE_LOWER_BOUND:
        "estimated_ad_recall_rate_lower_bound",
      ESTIMATED_AD_RECALL_RATE_UPPER_BOUND:
        "estimated_ad_recall_rate_upper_bound",
      FREQUENCY: "frequency",
      FREQUENCY_VALUE: "frequency_value",
      FULL_VIEW_REACH: "full_view_reach",
      FULL_VIEW_IMPRESSIONS: "full_view_impressions",
      HOURLY_STATS_AGGREGATED_BY_ADVERTISER_TIME_ZONE:
        "hourly_stats_aggregated_by_advertiser_time_zone",
      HOURLY_STATS_AGGREGATED_BY_AUDIENCE_TIME_ZONE:
        "hourly_stats_aggregated_by_audience_time_zone",
      IMPRESSIONS_AUTO_REFRESH: "impressions_auto_refresh",
      IMPRESSIONS_GOAL: "impressions_goal",
      CATALOG_SEGMENT_VALUE: "catalog_segment_value",
      IMPRESSIONS_GROSS: "impressions_gross",
      INLINE_LINK_CLICKS: "inline_link_clicks",
      UNIQUE_INLINE_LINK_CLICKS: "unique_inline_link_clicks",
      INLINE_POST_ENGAGEMENT: "inline_post_engagement",
      MEDIA_VIEWERS: "total_media_view_unique",
      OBJECTIVE_RESULTS: "objective_results",
      OBJECTIVE_RESULT_RATE: "objective_result_rate",
      OPTIMIZATION_RESULTS: "optimization_results",
      PAGE_ID: "page_id",
      PAGE_NAME: "page_name",
      PERCENTAGE_AUDIENCE_REACHED: "percentage_audience_reached",
      PERCENTAGE_FIRST_TIME_IMPRESSIONS: "percentage_first_time_impressions",
      PLACE_PAGE_ID: "place_page_id",
      PLACE_PAGE_NAME: "place_page_name",
      PLACEMENT: "placement",
      PUBLISHER_PLATFORM: "publisher_platform",
      PLATFORM_POSITION: "platform_position",
      DEVICE_PLATFORM: "device_platform",
      PRODUCT_ITEM_ID: "product_item_id",
      PRODUCT_SET_ID: "product_set_id",
      QUALITY_SCORE_ECTR: "quality_score_ectr",
      QUALITY_SCORE_ECVR: "quality_score_ecvr",
      QUALITY_SCORE_ORGANIC: "quality_score_organic",
      QUALITY_RANKING: "quality_ranking",
      ENGAGEMENT_RATE_RANKING: "engagement_rate_ranking",
      CONVERSION_RATE_RANKING: "conversion_rate_ranking",
      REACH: "reach",
      RELEVANCE_SCORE: "relevance_score",
      RELEVANCE_SCORE_VALUE: "relevance_score:score",
      RELEVANCE_SCORE_POSITIVE_FEEDBACK: "relevance_score:positive_feedback",
      RELEVANCE_SCORE_NEGATIVE_FEEDBACK: "relevance_score:negative_feedback",
      RELEVANCE_SCORE_ORGANIC_RANK: "relevance_score:organic_rank",
      RESULT_RATE: "result_rate",
      RESULTS: "results",
      RESULTS_SHARE: "results_share",
      SOCIAL_CLICKS: "social_clicks",
      SOCIAL_IMPRESSIONS: "social_impressions",
      SOCIAL_REACH: "social_reach",
      SPEND: "spend",
      STORE_VISITS: "store_visits",
      THUMB_STOPS: "thumb_stops",
      TOTAL_ACTION_VALUE: "total_action_value",
      TOTAL_ACTIONS: "total_actions",
      TOTAL_UNIQUE_ACTIONS: "total_unique_actions",
      UNIQUE_CLICKS: "unique_clicks",
      INLINE_LINK_CLICK_CTR: "inline_link_click_ctr",
      UNIQUE_INLINE_LINK_CLICK_CTR: "unique_inline_link_click_ctr",
      UNIQUE_IMPRESSIONS: "unique_impressions",
      UNIQUE_SOCIAL_CLICKS: "unique_social_clicks",
      UNIQUE_SOCIAL_IMPRESSIONS: "unique_social_impressions",
      VIDEO_AVG_PCT_WATCHED_ACTIONS: "video_avg_pct_watched_actions",
      VIDEO_AVG_PERCENT_WATCHED_ACTIONS: "video_avg_percent_watched_actions",
      VIDEO_AVG_SEC_WATCHED_ACTIONS: "video_avg_sec_watched_actions",
      VIDEO_TIME_WATCHED_ACTIONS: "video_time_watched_actions",
      VIDEO_COMPLETE_WATCHED_ACTIONS: "video_complete_watched_actions",
      VIDEO_SOUND: "action_video_sound",
      VIDEO_VIEW_TYPE: "action_video_type",
      VIDEO_COMPLETED_VIEW_OR_15S_PASSED_ACTIONS:
        "video_completed_view_or_15s_passed_actions",
      CONDITIONAL_TIME_SPENT_MS_OVER_2S_ACTIONS:
        "conditional_time_spent_ms_over_2s_actions",
      CONDITIONAL_TIME_SPENT_MS_OVER_3S_ACTIONS:
        "conditional_time_spent_ms_over_3s_actions",
      CONDITIONAL_TIME_SPENT_MS_OVER_6S_ACTIONS:
        "conditional_time_spent_ms_over_6s_actions",
      CONDITIONAL_TIME_SPENT_MS_OVER_10S_ACTIONS:
        "conditional_time_spent_ms_over_10s_actions",
      CONDITIONAL_TIME_SPENT_MS_OVER_15S_ACTIONS:
        "conditional_time_spent_ms_over_15s_actions",
      VIDEO_PLAY_RETENTION_0_TO_15S_ACTIONS:
        "video_play_retention_0_to_15s_actions",
      VIDEO_PLAY_RETENTION_20_TO_60S_ACTIONS:
        "video_play_retention_20_to_60s_actions",
      VIDEO_PLAY_RETENTION_GRAPH_ACTIONS: "video_play_retention_graph_actions",
      WEBSITE_CLICKS: "website_clicks",
      PURCHASE_ROAS: "purchase_roas",
      CATALOG_SEGMENT_VALUE_OMNI_PURCHASE_ROAS:
        "catalog_segment_value_omni_purchase_roas",
      RULE_ASSET: "rule_asset",
      DEBUG_STAGE_TRACE: "stage_trace",
      GENDER_TARGETING: "gender_targeting",
      AGE_TARGETING: "age_targeting",
      LOCATION: "location",
      LABELS: "labels",
      HEADLINE: "headline",
      DESCRIPTION: "description",
      WEBSITE_URL: "website_url",
      IMAGE_NAME: "image_name",
      VIDEO_NAME: "video_name",
      IMAGE_HASH: "image_hash",
      VIDEO_ID: "video_id",
      URL_TAGS: "url_tags",
      CALL_TO_ACTION_TYPE: "call_to_action_type",
      CUSTOM_AUDIENCES: "custom_audiences",
      EXCLUDED_CUSTOM_AUDIENCES: "excluded_custom_audiences",
      HIGH_CPA_SPEND_ALERT: "high_cpa_spend_alert",
      AD_CLICK_ACTION: "ad_click_actions",
      AD_IMPRESSION_ACTION: "ad_impression_actions",
      CUSTOM_DERIVED_METRICS: "custom_derived_metrics",
      CUSTOM_DERIVED_METRIC_ID: "custom_derived_metric_id",
      CUSTOM_BREAKDOWN: "custom_breakdown",
      REELS_TRENDING_TOPIC: "reels_trending_topic",
      TOTAL_LEARNING_PHASE_SPEND_RATIO: "total_learning_phase_spend_ratio",
      IN_LEARNING_SPEND: "in_learning_spend",
      LEARNING_LIMITED_SPEND: "learning_limited_spend",
      TOTAL_RUNNING_ADS: "total_running_ads",
      RUNNING_ADS_COUNT_IN_LEARNING: "running_ads_count_in_learning",
      RUNNING_ADS_COUNT_IN_LEARNING_LIMITED:
        "running_ads_count_in_learning_limited",
      TOTAL_RUNNING_ADSETS: "total_running_adsets",
      RUNNING_ADSETS_COUNT_IN_LEARNING: "running_adsets_count_in_learning",
      RUNNING_ADSETS_COUNT_IN_LEARNING_LIMITED:
        "running_adsets_count_in_learning_limited",
      TOTAL_LEARNING_PHASE_SPEND_RATIO_LEGACY:
        "total_learning_phase_spend_ratio_legacy",
      IN_LEARNING_SPEND_LEGACY: "in_learning_spend_legacy",
      LEARNING_LIMITED_SPEND_LEGACY: "learning_limited_spend_legacy",
      RUNNING_ADS_COUNT_IN_LEARNING_LEGACY:
        "running_ads_count_in_learning_legacy",
      RUNNING_ADS_COUNT_IN_LEARNING_LIMITED_LEGACY:
        "running_ads_count_in_learning_limited_legacy",
      RUNNING_ADSETS_COUNT_IN_LEARNING_LEGACY:
        "running_adsets_count_in_learning_legacy",
      RUNNING_ADSETS_COUNT_IN_LEARNING_LIMITED_LEGACY:
        "running_adsets_count_in_learning_limited_legacy",
      ONSITE_APP_ADD_TO_CART: "onsite_app_add_to_cart",
      ONSITE_APP_PURCHASE: "onsite_app_purchase",
      ONSITE_APP_VIEW_CONTENT: "onsite_app_view_content",
      ONSITE_WEB_ADD_TO_CART: "onsite_web_add_to_cart",
      ONSITE_WEB_APP_ADD_TO_CART: "onsite_web_app_add_to_cart",
      ONSITE_WEB_APP_PURCHASE: "onsite_web_app_purchase",
      ONSITE_WEB_APP_VIEW_CONTENT: "onsite_web_app_view_content",
      ONSITE_WEB_LEAD: "onsite_web_lead",
      ONSITE_WEB_PURCHASE: "onsite_web_purchase",
      ONSITE_WEB_VIEW_CONTENT: "onsite_web_view_content",
      VIEW_CONTENT: "view_content",
      CATALOG_MATCH: "catalog_match",
      VISIT_INSTAGRAM_PROFILE: "visit_instagram_profile",
      INSTAGRAM_PROFILE_FOLLOW_V2: "instagram_profile_follow_v2",
      PROFILE_VISIT_VIEW: "profile_visit_view",
      PAGE_VISIT_VIEW: "page_visit_view",
      TOTAL_PROFILE_VISITS: "total_profile_visits",
      PROFILE_AND_PAGE_ENGAGEMENT: "profile_and_page_engagement",
      FB_PROFILE_FOLLOW: "fb_profile_follow",
      TOTAL_FOLLOWS: "total_follows",
      CREATIVE_MEDIA_TYPE: "creative_media_type",
      MARKETING_MESSAGES_BTN_NAME: "marketing_messages_btn_name",
      ONSITE_CONVERSION_RETURNING_MESSAGING_CONNECTION:
        "onsite_conversion_returning_messaging_connection",
      COST_PER_ONSITE_CONVERSION_RETURNING_MESSAGING_CONNECTION:
        "cost_per_onsite_conversion_returning_messaging_connection",
      CONVERSION_LEADS: "conversion_leads",
      ONSITE_CONVERSION_LEADGEN_PREFERRED_LEAD:
        "onsite_conversion_leadgen_preferred_lead",
      ONSITE_CONVERSION_LEADGEN_NON_PREFERRED_LEAD:
        "onsite_conversion_leadgen_non_preferred_lead",
      PREDICTED_BAU_CPR: "predicted_bau_cpr",
      SOT_COST_PER_RESULT: "sot_cost_per_result",
      SOT_PURCHASE_ROAS: "sot_purchase_roas",
      SOT_RESULTS: "sot_results",
      LINK_CLICK_RESULTS: "link_click_results",
      COST_PER_LINK_CLICK_RESULT: "cost_per_link_click_result",
      FLEXIBLE_FORMAT_ASSET_TYPE: "flexible_format_asset_type",
      GEN_AI_ASSET_TYPE: "gen_ai_asset_type",
      CREATIVE_RELAXATION_ASSET_TYPE: "creative_relaxation_asset_type",
      INSTAGRAM_PROFILE_VISITS: "instagram_profile_visits",
      EXISTING_POST_ID: "existing_post_id",
      INSTAGRAM_PROFILE_FOLLOW: "instagram_profile_follow",
    });
    i.default = e;
  },
  66,
);
