__d(
  "AdsInsightsBreakdown",
  [],
  function (t, n, r, o, a, i) {
    var e = Object.freeze({
      ACTIVITY_RECENCY: "activity_recency",
      AD_EXTENSION_DOMAIN: "ad_extension_domain",
      AD_EXTENSION_URL: "ad_extension_url",
      AD_FORMAT_ASSET: "ad_format_asset",
      AFFILIATE_CLICK_REGION: "affiliate_click_region",
      AFFILIATE_LINK_URL: "affiliate_link_url",
      AGE: "age",
      APP_ID: "app_id",
      BID_TYPE: "bid_type",
      BODY_ASSET: "body_asset",
      BODY_ASSET_VALUE: "body_asset_value",
      BREAKDOWN_AD_OBJECTIVE: "breakdown_ad_objective",
      BREAKDOWN_REPORTING_AD_ID: "breakdown_reporting_ad_id",
      CALL_TO_ACTION_ASSET: "call_to_action_asset",
      CALL_TO_ACTION_ASSET_VALUE: "call_to_action_asset_value",
      COARSE_CONVERSION_VALUE: "coarse_conversion_value",
      COMSCORE_MARKET: "comscore_market",
      COMSCORE_MARKET_CODE: "comscore_market_code",
      COUNTRY: "country",
      CREATIVE_AUTOMATION_ASSET_ID: "creative_automation_asset_id",
      CREATIVE_FINGERPRINT: "creative_fingerprint",
      CREATIVE_RELAXATION_ASSET_TYPE: "creative_relaxation_asset_type",
      CRM_ADVERTISER_L12_TERRITORY_IDS: "crm_advertiser_l12_territory_ids",
      CRM_ADVERTISER_SUBVERTICAL_ID: "crm_advertiser_subvertical_id",
      CRM_ADVERTISER_VERTICAL_ID: "crm_advertiser_vertical_id",
      CRM_ULT_ADVERTISER_ID: "crm_ult_advertiser_id",
      DESCRIPTION_ASSET: "description_asset",
      DESCRIPTION_ASSET_VALUE: "description_asset_value",
      EXISTING_POST_ID: "existing_post_id",
      FIDELITY_TYPE: "fidelity_type",
      FLEXIBLE_FORMAT_ASSET_TYPE: "flexible_format_asset_type",
      GEN_AI_ASSET_TYPE: "gen_ai_asset_type",
      GENDER: "gender",
      HSID: "hsid",
      IMAGE_ASSET: "image_asset",
      IMAGE_ASSET_VALUE: "image_asset_value",
      IMPRESSION_DEVICE: "impression_device",
      IMPRESSION_VIEW_TIME_ADVERTISER_HOUR:
        "impression_view_time_advertiser_hour",
      IMPRESSION_VIEW_TIME_USER_HOUR: "impression_view_time_user_hour",
      INSTAGRAM_ADS_FOLLOW_TYPE: "instagram_ads_follow_type",
      INSTAGRAM_ADS_INSTAGRAM_MEDIA_PRODUCT_TYPE:
        "instagram_ads_instagram_media_product_type",
      INSTAGRAM_ADS_TIME_SINCE_CREATION_BUCKET:
        "instagram_ads_time_since_creation_bucket",
      INTERNAL_CAMPAIGN_ID: "internal_campaign_id",
      IS_AUTO_ADVANCE: "is_auto_advance",
      IS_BUSINESS_AI_ASSISTED: "is_business_ai_assisted",
      IS_CONVERSION_ID_MODELED: "is_conversion_id_modeled",
      IS_RENDERED_AS_DELAYED_SKIP_AD: "is_rendered_as_delayed_skip_ad",
      IS_VIDEO: "is_video",
      LANDING_DESTINATION: "landing_destination",
      LINK_URL_ASSET: "link_url_asset",
      LINK_URL_ASSET_VALUE: "link_url_asset_value",
      MDSA_LANDING_DESTINATION: "mdsa_landing_destination",
      MEDIA_ASSET: "media_asset",
      MEDIA_ASSET_URL: "media_asset_url",
      MEDIA_CREATOR: "media_creator",
      MEDIA_DESTINATION_URL: "media_destination_url",
      MEDIA_FORMAT: "media_format",
      MEDIA_ORIGIN_URL: "media_origin_url",
      MEDIA_TEXT_CONTENT: "media_text_content",
      MEDIA_TYPE: "media_type",
      MSA_SELLER_ID: "msa_seller_id",
      MSA_SELLER_NAME: "msa_seller_name",
      PA_CREATOR_IG_HANDLE: "pa_creator_ig_handle",
      PAGE_TYPE: "page_type",
      POSTBACK_SEQUENCE_INDEX: "postback_sequence_index",
      PRODUCT_BRAND_BREAKDOWN: "product_brand_breakdown",
      PRODUCT_CATEGORY_BREAKDOWN: "product_category_breakdown",
      PRODUCT_CUSTOM_LABEL_0_BREAKDOWN: "product_custom_label_0_breakdown",
      PRODUCT_CUSTOM_LABEL_1_BREAKDOWN: "product_custom_label_1_breakdown",
      PRODUCT_CUSTOM_LABEL_2_BREAKDOWN: "product_custom_label_2_breakdown",
      PRODUCT_CUSTOM_LABEL_3_BREAKDOWN: "product_custom_label_3_breakdown",
      PRODUCT_CUSTOM_LABEL_4_BREAKDOWN: "product_custom_label_4_breakdown",
      PRODUCT_FORMAT: "product_format",
      PRODUCT_GROUP_CONTENT_ID_BREAKDOWN: "product_group_content_id_breakdown",
      PRODUCT_GROUP_ID: "product_group_id",
      PRODUCT_ID: "product_id",
      PRODUCT_SET_ID_BREAKDOWN: "product_set_id_breakdown",
      PRODUCT_VENDOR_ID_BREAKDOWN: "product_vendor_id_breakdown",
      PROMOTED_PRODUCT_SET_RESULT: "promoted_product_set_result",
      PURCHASING_INTERFACE: "purchasing_interface",
      REDOWNLOAD: "redownload",
      REGION: "region",
      REGION_ID: "region_id",
      RTA_UGC_TOPIC: "rta_ugc_topic",
      RULE_ASSET_VALUE: "rule_asset_value",
      SKAN_CAMPAIGN_ID: "skan_campaign_id",
      SKAN_CONVERSION_ID: "skan_conversion_id",
      SKAN_VERSION: "skan_version",
      SOT_ATTRIBUTION_MODEL_TYPE: "sot_attribution_model_type",
      SOT_ATTRIBUTION_WINDOW: "sot_attribution_window",
      SOT_CHANNEL: "sot_channel",
      SOT_EVENT_TYPE: "sot_event_type",
      SOT_SOURCE: "sot_source",
      TITLE_ASSET: "title_asset",
      TITLE_ASSET_VALUE: "title_asset_value",
      USER_PERSONA_ID: "user_persona_id",
      USER_PERSONA_NAME: "user_persona_name",
      USER_SEGMENT_KEY: "user_segment_key",
      VIDEO_ASSET: "video_asset",
      VIDEO_ASSET_VALUE: "video_asset_value",
      ZIP: "zip",
      RULE_SET_ID: "rule_set_id",
      RULE_SET_NAME: "rule_set_name",
      BUSINESS_CONTACT_OPTION: "business_contact_option",
      DMA: "dma",
      DMA_CODE: "dma_code",
      FREQUENCY_VALUE: "frequency_value",
      OVERLAP_SEGMENT: "overlap_segment",
      PLACEMENT_PATH: "placement_path",
      HOURLY_STATS_AGGREGATED_BY_ADVERTISER_TIME_ZONE:
        "hourly_stats_aggregated_by_advertiser_time_zone",
      HOURLY_STATS_AGGREGATED_BY_AUDIENCE_TIME_ZONE:
        "hourly_stats_aggregated_by_audience_time_zone",
      INTERACTIVE_COMPONENT_STICKER_ID: "interactive_component_sticker_id",
      INTERACTIVE_COMPONENT_STICKER_RESPONSE:
        "interactive_component_sticker_response",
      MMM: "mmm",
      PLACE_PAGE_ID: "place_page_id",
      PLACEMENT: "placement",
      PUBLISHER_PLATFORM: "publisher_platform",
      PLATFORM_POSITION: "platform_position",
      DEVICE_PLATFORM: "device_platform",
      PRODUCT_ITEM_ID: "product_item_id",
      PRODUCT_SET_ID: "product_set_id",
      OPTIMIZED_CUSTOM_EVENT_NAME: "optimized_custom_event_name",
      ATTRIBUTION_MODEL_TYPE: "attribution_model_type",
      BRAND_NAME: "action_brand_name",
      CATEGORY_NAME: "action_category_name",
      APP_OPTIMIZED_CUSTOM_EVENT_NAME: "app_optimized_custom_event_name",
      STANDARD_EVENT_CONTENT_TYPE: "standard_event_content_type",
      CONVERSION_DESTINATION: "conversion_destination",
      SIGNAL_SOURCE_BUCKET: "signal_source_bucket",
      REELS_TRENDING_TOPIC: "reels_trending_topic",
      RULE_ASSET: "rule_asset",
      MARKETING_MESSAGES_BTN_NAME: "marketing_messages_btn_name",
      CREATIVE_FINGERPRINT_DETAILS: "creative_fingerprint_details",
      IMPRESSION_VIEW_TIME_ADVERTISER_HOUR_V2:
        "impression_view_time_advertiser_hour_v2",
    });
    i.default = e;
  },
  66,
);
