__d(
  "AdsInsightsAttributionWindow",
  [],
  function (t, n, r, o, a, i) {
    var e = Object.freeze({
      X1D_VIEW: "1d_view",
      X7D_VIEW: "7d_view",
      X28D_VIEW: "28d_view",
      X1D_CLICK: "1d_click",
      X7D_CLICK: "7d_click",
      X28D_CLICK: "28d_click",
      X1D_ATTENTION: "1d_attention",
      X7D_ATTENTION: "7d_attention",
      X28D_ATTENTION: "28d_attention",
      X1D_EVC: "1d_ev",
      X7D_EVC: "7d_ev",
      DDA: "dda",
      DEFAULT: "default",
      INLINE: "inline",
      X1D_CLICK_FIRST_CONVERSION: "1d_click_first_conversion",
      X7D_CLICK_FIRST_CONVERSION: "7d_click_first_conversion",
      X28D_CLICK_FIRST_CONVERSION: "28d_click_first_conversion",
      X1D_VIEW_FIRST_CONVERSION: "1d_view_first_conversion",
      X7D_VIEW_FIRST_CONVERSION: "7d_view_first_conversion",
      X28D_VIEW_FIRST_CONVERSION: "28d_view_first_conversion",
      X1D_EVC_FIRST_CONVERSION: "1d_ev_first_conversion",
      X7D_EVC_FIRST_CONVERSION: "7d_ev_first_conversion",
      X1D_CLICK_ALL_CONVERSIONS: "1d_click_all_conversions",
      X7D_CLICK_ALL_CONVERSIONS: "7d_click_all_conversions",
      X28D_CLICK_ALL_CONVERSIONS: "28d_click_all_conversions",
      X1D_VIEW_ALL_CONVERSIONS: "1d_view_all_conversions",
      X7D_VIEW_ALL_CONVERSIONS: "7d_view_all_conversions",
      X28D_VIEW_ALL_CONVERSIONS: "28d_view_all_conversions",
      X1D_EVC_ALL_CONVERSIONS: "1d_ev_all_conversions",
      X7D_EVC_ALL_CONVERSIONS: "7d_ev_all_conversions",
      SKAN_VIEW: "skan_view",
      SKAN_CLICK: "skan_click",
      SKAN_CLICK_SECOND_POSTBACK: "skan_click_second_postback",
      SKAN_VIEW_SECOND_POSTBACK: "skan_view_second_postback",
      SKAN_CLICK_THIRD_POSTBACK: "skan_click_third_postback",
      SKAN_VIEW_THIRD_POSTBACK: "skan_view_third_postback",
      INCREMENTALITY: "incrementality",
      INCREMENTALITY_FIRST_CONVERSION: "incrementality_first_conversion",
      INCREMENTALITY_ALL_CONVERSIONS: "incrementality_all_conversions",
      X1D_PASSBACK: "1d_passback",
      X7D_PASSBACK: "7d_passback",
      X28D_PASSBACK: "28d_passback",
      CUSTOM: "custom",
      X1D_A2A: "1d_sequenced",
      X7D_A2A: "7d_sequenced",
      X28D_A2A: "28d_sequenced",
    });
    i.default = e;
  },
  66,
);
