__d(
  "AdsMgmtCampaignDynamicStoreSourceTier3ServerQuery.graphql",
  ["AdCampaign-dynamic_ad_object_spec_tier3-resolver", "relay-runtime"],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = (function () {
      var e = [{ defaultValue: null, kind: "LocalArgument", name: "ids" }],
        t = [{ kind: "Variable", name: "ids", variableName: "ids" }],
        r = {
          alias: "node_id",
          args: null,
          kind: "ScalarField",
          name: "id",
          storageKey: null,
        },
        o = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "__typename",
          storageKey: null,
        },
        a = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "id",
          storageKey: null,
        },
        i = [
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "p25",
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "p50",
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "p75",
            storageKey: null,
          },
        ],
        l = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "value",
          storageKey: null,
        },
        s = [
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "key",
            storageKey: null,
          },
          l,
        ],
        u = [
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "end",
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "start",
            storageKey: null,
          },
          l,
        ],
        c = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "status",
          storageKey: null,
        };
      return {
        fragment: {
          argumentDefinitions: e,
          kind: "Fragment",
          metadata: null,
          name: "AdsMgmtCampaignDynamicStoreSourceTier3ServerQuery",
          selections: [
            {
              alias: null,
              args: t,
              concreteType: null,
              kind: "LinkedField",
              name: "nodes",
              plural: !0,
              selections: [
                {
                  kind: "InlineDataFragmentSpread",
                  name: "AdsMgmtCampaignDynamicStoreSourceTypeCheckFragment",
                  selections: [r, o],
                  args: null,
                  argumentDefinitions: [],
                },
                {
                  kind: "InlineFragment",
                  selections: [
                    a,
                    {
                      alias: null,
                      args: null,
                      fragment: {
                        args: null,
                        kind: "FragmentSpread",
                        name: "AdCampaignDynamicAdObjectSpecTier3Resolver",
                      },
                      kind: "RelayResolver",
                      name: "dynamic_campaign_spec_tier3",
                      resolverModule: n(
                        "AdCampaign-dynamic_ad_object_spec_tier3-resolver",
                      ).dynamic_campaign_spec_tier3,
                      path: "nodes.dynamic_campaign_spec_tier3",
                    },
                  ],
                  type: "AdCampaign",
                  abstractKey: null,
                },
              ],
              storageKey: null,
            },
          ],
          type: "Query",
          abstractKey: null,
        },
        kind: "Request",
        operation: {
          argumentDefinitions: e,
          kind: "Operation",
          name: "AdsMgmtCampaignDynamicStoreSourceTier3ServerQuery",
          selections: [
            {
              alias: null,
              args: t,
              concreteType: null,
              kind: "LinkedField",
              name: "nodes",
              plural: !0,
              selections: [
                o,
                { kind: "TypeDiscriminator", abstractKey: "__isNode" },
                r,
                a,
                {
                  kind: "InlineFragment",
                  selections: [
                    {
                      name: "dynamic_campaign_spec_tier3",
                      args: null,
                      fragment: {
                        kind: "InlineFragment",
                        selections: [
                          o,
                          {
                            alias: null,
                            args: null,
                            concreteType: "XFBAnomalyInsightsType",
                            kind: "LinkedField",
                            name: "anomaly_insights",
                            plural: !1,
                            selections: [
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "cpc",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "cplc",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "cpm",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "cpr",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "ctr",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "cvr",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "website_purchase_roas",
                                storageKey: null,
                              },
                            ],
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "cpr_benchmark",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "creative_diversity_label",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "creative_diversity_score",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            concreteType: "XFBCreativeFatiguePredictionPLEType",
                            kind: "LinkedField",
                            name: "creative_fatigue_prediction_ple",
                            plural: !1,
                            selections: [
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "cpr_lift_estimation",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "should_display",
                                storageKey: null,
                              },
                            ],
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            concreteType: "XFBPpsPeerBenchmarksType",
                            kind: "LinkedField",
                            name: "pps_peer_benchmarks",
                            plural: !1,
                            selections: [
                              {
                                alias: null,
                                args: null,
                                concreteType:
                                  "XFBPpsPeerBenchmarkQuartilesType",
                                kind: "LinkedField",
                                name: "ctr",
                                plural: !1,
                                selections: i,
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                concreteType:
                                  "XFBPpsPeerBenchmarkQuartilesType",
                                kind: "LinkedField",
                                name: "cpm",
                                plural: !1,
                                selections: i,
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                concreteType:
                                  "XFBPpsPeerBenchmarkQuartilesType",
                                kind: "LinkedField",
                                name: "cpc",
                                plural: !1,
                                selections: i,
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                concreteType:
                                  "XFBPpsPeerBenchmarkQuartilesType",
                                kind: "LinkedField",
                                name: "cvr",
                                plural: !1,
                                selections: i,
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                concreteType:
                                  "XFBPpsPeerBenchmarkQuartilesType",
                                kind: "LinkedField",
                                name: "cplc",
                                plural: !1,
                                selections: i,
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                concreteType:
                                  "XFBPpsPeerBenchmarkQuartilesType",
                                kind: "LinkedField",
                                name: "website_purchase_roas",
                                plural: !1,
                                selections: i,
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                concreteType:
                                  "XFBPpsPeerBenchmarkQuartilesType",
                                kind: "LinkedField",
                                name: "cpr",
                                plural: !1,
                                selections: i,
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                concreteType:
                                  "XFBPpsPeerBenchmarkFilterParamType",
                                kind: "LinkedField",
                                name: "filter_params",
                                plural: !0,
                                selections: s,
                                storageKey: null,
                              },
                            ],
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            concreteType: "XFBRepeatReachStateType",
                            kind: "LinkedField",
                            name: "repeat_reach_state",
                            plural: !1,
                            selections: [
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "current_saturation_level",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "forecasted_saturation_level",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "high_saturation_threshold",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "should_display_cpr",
                                storageKey: null,
                              },
                            ],
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            concreteType:
                              "AppliedInsightsCreativeInsightsReachTrend",
                            kind: "LinkedField",
                            name: "low_creative_reach",
                            plural: !1,
                            selections: [
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "reach_trend",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                concreteType: "AppliedInsightsReachTrend",
                                kind: "LinkedField",
                                name: "current_reach",
                                plural: !1,
                                selections: u,
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                concreteType: "AppliedInsightsReachTrend",
                                kind: "LinkedField",
                                name: "earlier_reach",
                                plural: !1,
                                selections: u,
                                storageKey: null,
                              },
                            ],
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            concreteType: "AdDeliveryInfo",
                            kind: "LinkedField",
                            name: "delivery_info",
                            plural: !1,
                            selections: [
                              {
                                name: "ad_delivery_info_spec",
                                args: null,
                                fragment: {
                                  kind: "InlineFragment",
                                  selections: [
                                    {
                                      alias: null,
                                      args: null,
                                      kind: "ScalarField",
                                      name: "active_accelerated_campaign_count",
                                      storageKey: null,
                                    },
                                    {
                                      alias: null,
                                      args: null,
                                      kind: "ScalarField",
                                      name: "active_day_parted_campaign_count",
                                      storageKey: null,
                                    },
                                    {
                                      alias: null,
                                      args: null,
                                      concreteType: "AdPenaltyMap",
                                      kind: "LinkedField",
                                      name: "ad_penalty_map",
                                      plural: !0,
                                      selections: s,
                                      storageKey: null,
                                    },
                                    {
                                      alias: null,
                                      args: null,
                                      kind: "ScalarField",
                                      name: "are_all_daily_budgets_spent",
                                      storageKey: null,
                                    },
                                    {
                                      alias: null,
                                      args: null,
                                      kind: "ScalarField",
                                      name: "credit_needed_ads_count",
                                      storageKey: null,
                                    },
                                    {
                                      alias: null,
                                      args: null,
                                      kind: "ScalarField",
                                      name: "eligible_for_delivery_insights",
                                      storageKey: null,
                                    },
                                    {
                                      alias: null,
                                      args: null,
                                      kind: "ScalarField",
                                      name: "end_time",
                                      storageKey: null,
                                    },
                                    {
                                      alias: null,
                                      args: null,
                                      kind: "ScalarField",
                                      name: "has_account_hit_spend_limit",
                                      storageKey: null,
                                    },
                                    {
                                      alias: null,
                                      args: null,
                                      kind: "ScalarField",
                                      name: "has_campaign_group_hit_spend_limit",
                                      storageKey: null,
                                    },
                                    {
                                      alias: null,
                                      args: null,
                                      kind: "ScalarField",
                                      name: "has_no_active_ads",
                                      storageKey: null,
                                    },
                                    {
                                      alias: null,
                                      args: null,
                                      kind: "ScalarField",
                                      name: "has_no_ads",
                                      storageKey: null,
                                    },
                                    {
                                      alias: null,
                                      args: null,
                                      kind: "ScalarField",
                                      name: "inactive_ads_count",
                                      storageKey: null,
                                    },
                                    {
                                      alias: null,
                                      args: null,
                                      kind: "ScalarField",
                                      name: "inactive_campaign_count",
                                      storageKey: null,
                                    },
                                    {
                                      alias: null,
                                      args: null,
                                      kind: "ScalarField",
                                      name: "is_account_closed",
                                      storageKey: null,
                                    },
                                    {
                                      alias: null,
                                      args: null,
                                      kind: "ScalarField",
                                      name: "is_account_disabled",
                                      storageKey: null,
                                    },
                                    {
                                      alias: null,
                                      args: null,
                                      kind: "ScalarField",
                                      name: "is_ad_uneconomical",
                                      storageKey: null,
                                    },
                                    {
                                      alias: null,
                                      args: null,
                                      kind: "ScalarField",
                                      name: "is_adfarm_penalized",
                                      storageKey: null,
                                    },
                                    {
                                      alias: null,
                                      args: null,
                                      kind: "ScalarField",
                                      name: "is_adgroup_partially_rejected",
                                      storageKey: null,
                                    },
                                    {
                                      alias: null,
                                      args: null,
                                      kind: "ScalarField",
                                      name: "is_campaign_accelerated",
                                      storageKey: null,
                                    },
                                    {
                                      alias: null,
                                      args: null,
                                      kind: "ScalarField",
                                      name: "is_campaign_completed",
                                      storageKey: null,
                                    },
                                    {
                                      alias: null,
                                      args: null,
                                      kind: "ScalarField",
                                      name: "is_campaign_day_parted",
                                      storageKey: null,
                                    },
                                    {
                                      alias: null,
                                      args: null,
                                      kind: "ScalarField",
                                      name: "is_campaign_disabled",
                                      storageKey: null,
                                    },
                                    {
                                      alias: null,
                                      args: null,
                                      kind: "ScalarField",
                                      name: "is_campaign_group_disabled",
                                      storageKey: null,
                                    },
                                    {
                                      alias: null,
                                      args: null,
                                      kind: "ScalarField",
                                      name: "is_clickbait_penalized",
                                      storageKey: null,
                                    },
                                    {
                                      alias: null,
                                      args: null,
                                      kind: "ScalarField",
                                      name: "is_daily_budget_spent",
                                      storageKey: null,
                                    },
                                    {
                                      alias: null,
                                      args: null,
                                      kind: "ScalarField",
                                      name: "is_engagement_bait_penalized",
                                      storageKey: null,
                                    },
                                    {
                                      alias: null,
                                      args: null,
                                      kind: "ScalarField",
                                      name: "is_lqwe_penalized",
                                      storageKey: null,
                                    },
                                    {
                                      alias: null,
                                      args: null,
                                      kind: "ScalarField",
                                      name: "is_reach_and_frequency_misconfigured",
                                      storageKey: null,
                                    },
                                    {
                                      alias: null,
                                      args: null,
                                      kind: "ScalarField",
                                      name: "is_sensationalism_penalized",
                                      storageKey: null,
                                    },
                                    {
                                      alias: "lift_study_time_period",
                                      args: null,
                                      kind: "ScalarField",
                                      name: "lift_study_time_period_enum",
                                      storageKey: null,
                                    },
                                    {
                                      alias: null,
                                      args: null,
                                      kind: "ScalarField",
                                      name: "needs_credit",
                                      storageKey: null,
                                    },
                                    {
                                      alias: null,
                                      args: null,
                                      kind: "ScalarField",
                                      name: "needs_tax_number",
                                      storageKey: null,
                                    },
                                    {
                                      alias: null,
                                      args: null,
                                      kind: "ScalarField",
                                      name: "non_deleted_ads_count",
                                      storageKey: null,
                                    },
                                    {
                                      alias: null,
                                      args: null,
                                      kind: "ScalarField",
                                      name: "not_delivering_campaign_count",
                                      storageKey: null,
                                    },
                                    {
                                      alias: null,
                                      args: null,
                                      kind: "ScalarField",
                                      name: "pending_ads_count",
                                      storageKey: null,
                                    },
                                    {
                                      alias: null,
                                      args: null,
                                      concreteType:
                                        "XFBAdDeliveryPendingReviewInfo",
                                      kind: "LinkedField",
                                      name: "pending_review_info",
                                      plural: !1,
                                      selections: [
                                        {
                                          alias: null,
                                          args: null,
                                          kind: "ScalarField",
                                          name: "latest_update_time",
                                          storageKey: null,
                                        },
                                        {
                                          alias: null,
                                          args: null,
                                          kind: "ScalarField",
                                          name: "review_status",
                                          storageKey: null,
                                        },
                                      ],
                                      storageKey: null,
                                    },
                                    {
                                      alias: null,
                                      args: null,
                                      kind: "ScalarField",
                                      name: "reach_frequency_campaign_underdelivery_reason",
                                      storageKey: null,
                                    },
                                    {
                                      alias: null,
                                      args: null,
                                      kind: "ScalarField",
                                      name: "rejected_ads_count",
                                      storageKey: null,
                                    },
                                    {
                                      alias: null,
                                      args: null,
                                      concreteType:
                                        "XFBAdSignalDiagnosticIssue",
                                      kind: "LinkedField",
                                      name: "signal_diagnostic_issue",
                                      plural: !1,
                                      selections: [
                                        {
                                          alias: null,
                                          args: null,
                                          kind: "ScalarField",
                                          name: "data_source_id",
                                          storageKey: null,
                                        },
                                        {
                                          alias: null,
                                          args: null,
                                          kind: "ScalarField",
                                          name: "data_source_type",
                                          storageKey: null,
                                        },
                                        {
                                          alias: null,
                                          args: null,
                                          kind: "ScalarField",
                                          name: "diagnostic_type",
                                          storageKey: null,
                                        },
                                        {
                                          alias: null,
                                          args: null,
                                          kind: "ScalarField",
                                          name: "event_name",
                                          storageKey: null,
                                        },
                                        {
                                          alias: null,
                                          args: null,
                                          kind: "ScalarField",
                                          name: "traffic_anomaly_drop_percentage",
                                          storageKey: null,
                                        },
                                        {
                                          alias: null,
                                          args: null,
                                          kind: "ScalarField",
                                          name: "traffic_anomaly_drop_timestamp",
                                          storageKey: null,
                                        },
                                      ],
                                      storageKey: null,
                                    },
                                    {
                                      alias: null,
                                      args: null,
                                      kind: "ScalarField",
                                      name: "start_time",
                                      storageKey: null,
                                    },
                                    c,
                                    {
                                      alias: null,
                                      args: null,
                                      kind: "ScalarField",
                                      name: "text_penalty_level",
                                      storageKey: null,
                                    },
                                  ],
                                  type: "AdDeliveryInfo",
                                  abstractKey: null,
                                },
                                kind: "RelayResolver",
                                storageKey: null,
                                isOutputType: !0,
                              },
                            ],
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "effective_status",
                            storageKey: null,
                          },
                          a,
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "is_bid_constrained",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "is_cost_constrained",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            concreteType: "AdDeliveryInsightsLearningStageNode",
                            kind: "LinkedField",
                            name: "learning_stage_info",
                            plural: !1,
                            selections: [
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "conversions",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "exit_reason",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "last_significant_edit_timestamp",
                                storageKey: null,
                              },
                              c,
                            ],
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            concreteType: "AdsDeliveryPacedBidInfo",
                            kind: "LinkedField",
                            name: "paced_bid_info",
                            plural: !1,
                            selections: [
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "bidding_status",
                                storageKey: null,
                              },
                            ],
                            storageKey: null,
                          },
                        ],
                        type: "AdCampaign",
                        abstractKey: null,
                      },
                      kind: "RelayResolver",
                      storageKey: null,
                      isOutputType: !0,
                    },
                  ],
                  type: "AdCampaign",
                  abstractKey: null,
                },
              ],
              storageKey: null,
            },
          ],
        },
        params: {
          id: "27833440953025506",
          metadata: {},
          name: "AdsMgmtCampaignDynamicStoreSourceTier3ServerQuery",
          operationKind: "query",
          text: null,
        },
      };
    })();
    (n("relay-runtime").PreloadableQueryRegistry.set(e.params.id, e),
      (a.exports = e));
  },
  null,
);
