__d(
  "AdsManagerLiveDataCampaignGroupThrowOnFieldErrorQuery.graphql",
  [
    "AdCampaignGroup-ad_object_field_error_spec-resolver",
    "GraphQLIncludeAdgroupActiveStudies.relayprovider",
    "relay-runtime",
  ],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = (function () {
      var e = { defaultValue: null, kind: "LocalArgument", name: "ids" },
        t = [{ kind: "Variable", name: "ids", variableName: "ids" }],
        r = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "__typename",
          storageKey: null,
        },
        o = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "id",
          storageKey: null,
        },
        a = [o],
        i = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "name",
          storageKey: null,
        },
        l = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "page_id",
          storageKey: null,
        };
      return {
        fragment: {
          argumentDefinitions: [e],
          kind: "Fragment",
          metadata: { throwOnFieldError: !0 },
          name: "AdsManagerLiveDataCampaignGroupThrowOnFieldErrorQuery",
          selections: [
            {
              alias: null,
              args: t,
              concreteType: null,
              kind: "LinkedField",
              name: "nodes",
              plural: !0,
              selections: [
                {
                  kind: "InlineFragment",
                  selections: [
                    {
                      alias: "ad_object_spec",
                      args: null,
                      fragment: {
                        args: null,
                        kind: "FragmentSpread",
                        name: "AdCampaignGroupAdObjectFieldErrorSpecResolver",
                      },
                      kind: "RelayResolver",
                      name: "ad_object_field_error_spec",
                      resolverModule: n(
                        "AdCampaignGroup-ad_object_field_error_spec-resolver",
                      ).ad_object_field_error_spec,
                      path: "nodes.ad_object_spec",
                    },
                  ],
                  type: "AdCampaignGroup",
                  abstractKey: null,
                },
              ],
              storageKey: null,
            },
          ],
          type: "Query",
          abstractKey: null,
        },
        kind: "Request",
        operation: {
          argumentDefinitions: [
            e,
            {
              defaultValue: null,
              kind: "LocalArgument",
              name: "__relay_internal__pv__GraphQLIncludeAdgroupActiveStudiesrelayprovider",
            },
          ],
          kind: "Operation",
          name: "AdsManagerLiveDataCampaignGroupThrowOnFieldErrorQuery",
          selections: [
            {
              alias: null,
              args: t,
              concreteType: null,
              kind: "LinkedField",
              name: "nodes",
              plural: !0,
              selections: [
                r,
                {
                  kind: "InlineFragment",
                  selections: [
                    {
                      name: "ad_object_field_error_spec",
                      args: null,
                      fragment: {
                        kind: "InlineFragment",
                        selections: [
                          r,
                          {
                            condition:
                              "__relay_internal__pv__GraphQLIncludeAdgroupActiveStudiesrelayprovider",
                            kind: "Condition",
                            passingValue: !0,
                            selections: [
                              {
                                alias: null,
                                args: null,
                                concreteType: "AdStudy",
                                kind: "LinkedField",
                                name: "adgroup_active_studies",
                                plural: !0,
                                selections: a,
                                storageKey: null,
                              },
                            ],
                          },
                          {
                            alias: null,
                            args: null,
                            concreteType: "AdAccount",
                            kind: "LinkedField",
                            name: "ad_account",
                            plural: !1,
                            selections: [
                              o,
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "legacy_account_id",
                                storageKey: null,
                              },
                            ],
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            concreteType: "XFBAdCreationPackageConfig",
                            kind: "LinkedField",
                            name: "ad_creation_package_config",
                            plural: !1,
                            selections: [
                              o,
                              {
                                alias: null,
                                args: null,
                                concreteType: "XFBAdCreationPackage",
                                kind: "LinkedField",
                                name: "package",
                                plural: !1,
                                selections: a,
                                storageKey: null,
                              },
                            ],
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            concreteType: "AdLabel",
                            kind: "LinkedField",
                            name: "ad_labels",
                            plural: !0,
                            selections: [o, i],
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "automation_unified_campaign_type",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            concreteType:
                              "AdproCampaignGroupBidConstraintShape",
                            kind: "LinkedField",
                            name: "bid_constraints",
                            plural: !1,
                            selections: [
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "roas_average_floor",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "cpa_average_target",
                                storageKey: null,
                              },
                            ],
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "bid_strategy",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            concreteType: "BoostedComponentWrapper",
                            kind: "LinkedField",
                            name: "boosted_component",
                            plural: !1,
                            selections: [
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "client_app_id",
                                storageKey: null,
                              },
                              l,
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "product",
                                storageKey: null,
                              },
                              o,
                            ],
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            concreteType: "XFBBrandLiftStudy",
                            kind: "LinkedField",
                            name: "brand_lift_studies",
                            plural: !0,
                            selections: [
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "description",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "end_time",
                                storageKey: null,
                              },
                              o,
                              i,
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "start_time",
                                storageKey: null,
                              },
                            ],
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "budget_remaining_safe_value_str",
                            storageKey: null,
                          },
                          {
                            alias: "budget_scaling_cost_target",
                            args: null,
                            kind: "ScalarField",
                            name: "budget_scaling_cost_target_safe_value_str",
                            storageKey: null,
                          },
                          {
                            alias: "budget_scaling_extra_budget",
                            args: null,
                            kind: "ScalarField",
                            name: "budget_scaling_extra_budget_safe_value_str",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "budget_scaling_cost_target_default",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "budget_scaling_budget_multiplier_default",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "budget_strategy",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "buying_type",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "buy_with_integration_partner",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "buy_with_prime_type",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "can_use_spend_cap",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            concreteType:
                              "AdCampaignGroupCollaborativeAdsPartnerInfoType",
                            kind: "LinkedField",
                            name: "collaborative_ads_partner_info",
                            plural: !1,
                            selections: [
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "merchant_partner_business_id",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "producer_dedicated_ad_account_id",
                                storageKey: null,
                              },
                            ],
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "campaign_group_active_time",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "created_time_with_timezone",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "daily_budget_safe_value_str",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "default_lifetime_flex_budget",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "effective_status",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            concreteType: "FrequencyControlSpec",
                            kind: "LinkedField",
                            name: "frequency_control_specs",
                            plural: !0,
                            selections: [
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "event",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "interval_days",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "max_frequency",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "type",
                                storageKey: null,
                              },
                            ],
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "has_secondary_skadnetwork_reporting",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "automation2_performance_status",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "has_automation2_brief_group",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "linked_testimonial_brief_id",
                            storageKey: null,
                          },
                          o,
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "is_autobid",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "is_average_price_pacing",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "is_direct_send_campaign",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "is_message_campaign",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "is_odax_campaign_group",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "is_pca_unified",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "is_full_funnel",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "is_meta_moment_maker_enabled",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "is_reels_trending_ads_enabled",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "is_skadnetwork_attribution",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "is_using_l3_schedule",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "last_budget_toggling_time_and_timezone",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "lifetime_budget_safe_value_str",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "lifetime_spent",
                            storageKey: null,
                          },
                          i,
                          {
                            alias: null,
                            args: null,
                            concreteType: "XFBAdsNamingTemplateConditions",
                            kind: "LinkedField",
                            name: "naming_template_custom_fields",
                            plural: !0,
                            selections: [
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "key",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "value",
                                storageKey: null,
                              },
                            ],
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "objective",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "pacing_type",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "primary_attribution",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            concreteType: "AdPromotedObject",
                            kind: "LinkedField",
                            name: "promoted_object",
                            plural: !1,
                            selections: [
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "application_id",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "custom_conversion_id",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "custom_event_type",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "event_id",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "object_store_url",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "offer_id",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "offline_conversion_data_set_id",
                                storageKey: null,
                              },
                              l,
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "pixel_aggregation_rule",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "pixel_rule",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "pixel_id",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "place_page_set_id",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "product_catalog_id",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "product_set_id",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "retention_days",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "lead_ads_custom_event_str",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "lead_ads_custom_event_type",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "lead_ads_follow_up_event",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "lead_ads_form_event_source_type",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "lead_ads_offsite_conversion_type",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "lead_ads_quality_volume_setting",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "lead_ads_selected_pixel_id",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "live_video_destination",
                                storageKey: null,
                              },
                              o,
                            ],
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "smart_promotion_type",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            concreteType: null,
                            kind: "LinkedField",
                            name: "source_campaign_group",
                            plural: !1,
                            selections: [r, o],
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "rf_prediction_id",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "should_prorate_budget",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "source_recommendation_type",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "special_ad_categories",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "special_ad_category",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "special_ad_category_country",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "spend_cap",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "start_time_with_timezone",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "status",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "stop_time_with_timezone",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "study_ids",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "topline_id",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            concreteType: "TimeSuggestion",
                            kind: "LinkedField",
                            name: "time_suggestion",
                            plural: !1,
                            selections: [
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "is_enabled",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                concreteType: "HighDemandPeriod",
                                kind: "LinkedField",
                                name: "high_demand_periods",
                                plural: !0,
                                selections: [
                                  o,
                                  {
                                    alias: null,
                                    args: null,
                                    kind: "ScalarField",
                                    name: "time_start",
                                    storageKey: null,
                                  },
                                  {
                                    alias: null,
                                    args: null,
                                    kind: "ScalarField",
                                    name: "time_end",
                                    storageKey: null,
                                  },
                                  {
                                    alias: null,
                                    args: null,
                                    kind: "ScalarField",
                                    name: "budget_value_type",
                                    storageKey: null,
                                  },
                                  {
                                    alias: null,
                                    args: null,
                                    kind: "ScalarField",
                                    name: "budget_value",
                                    storageKey: null,
                                  },
                                  {
                                    alias: null,
                                    args: null,
                                    kind: "ScalarField",
                                    name: "recurrence_type",
                                    storageKey: null,
                                  },
                                  {
                                    alias: null,
                                    args: null,
                                    concreteType: "TimeSuggestionWeeklySegment",
                                    kind: "LinkedField",
                                    name: "weekly_schedule",
                                    plural: !0,
                                    selections: [
                                      {
                                        alias: null,
                                        args: null,
                                        kind: "ScalarField",
                                        name: "days",
                                        storageKey: null,
                                      },
                                      {
                                        alias: null,
                                        args: null,
                                        kind: "ScalarField",
                                        name: "end_minute",
                                        storageKey: null,
                                      },
                                      {
                                        alias: null,
                                        args: null,
                                        kind: "ScalarField",
                                        name: "start_minute",
                                        storageKey: null,
                                      },
                                      {
                                        alias: null,
                                        args: null,
                                        kind: "ScalarField",
                                        name: "timezone_type",
                                        storageKey: null,
                                      },
                                    ],
                                    storageKey: null,
                                  },
                                  {
                                    alias: null,
                                    args: null,
                                    kind: "ScalarField",
                                    name: "study_id",
                                    storageKey: null,
                                  },
                                ],
                                storageKey: null,
                              },
                            ],
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "updated_time_with_timezone",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "yesterday_spent",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "disable_dyno_sampling_dangerous",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            concreteType:
                              "AdCampaignGroupMetaCheckoutExperienceConfig",
                            kind: "LinkedField",
                            name: "mc_experience_config",
                            plural: !1,
                            selections: [
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "is_campaign_enabled",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "is_terms_signed",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "merchant_type",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "is_user_manually_toggle_mc_off",
                                storageKey: null,
                              },
                            ],
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "is_existing__graphql_on_flux_only",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            concreteType: "AdCampaignGroupAgencyFeeConfig",
                            kind: "LinkedField",
                            name: "agency_fee_config",
                            plural: !1,
                            selections: [
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "agency_fee_pct",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "is_agency_fee_disabled",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "is_default_agency_fee",
                                storageKey: null,
                              },
                            ],
                            storageKey: null,
                          },
                        ],
                        type: "AdCampaignGroup",
                        abstractKey: null,
                      },
                      kind: "RelayResolver",
                      storageKey: null,
                      isOutputType: !0,
                    },
                  ],
                  type: "AdCampaignGroup",
                  abstractKey: null,
                },
                o,
              ],
              storageKey: null,
            },
          ],
        },
        params: {
          id: "37820330070915630",
          metadata: {},
          name: "AdsManagerLiveDataCampaignGroupThrowOnFieldErrorQuery",
          operationKind: "query",
          text: null,
          providedVariables: {
            __relay_internal__pv__GraphQLIncludeAdgroupActiveStudiesrelayprovider:
              n("GraphQLIncludeAdgroupActiveStudies.relayprovider"),
          },
        },
      };
    })();
    (n("relay-runtime").PreloadableQueryRegistry.set(e.params.id, e),
      (a.exports = e));
  },
  null,
);
