__d(
  "AdsPerformanceSummaryTypes",
  ["$InternalEnum"],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = n("$InternalEnum").Mirrored(["Default", "ShopsAds", "BudgetTab"]),
      l = n("$InternalEnum").Mirrored([
        "ACO",
        "AsaReportGuidanceCard",
        "AudienceSaturationCard",
        "BudgetCapCard",
        "BenchmarkReportGuidanceCard",
        "BreakdownCharts",
        "PersonaBreakdownChart",
        "CTMMessagingReportGuidanceCard",
        "CAPIOptimizationCard",
        "CampaignOptimization",
        "CommerceDynamicAdsCatalogIssues",
        "CreativeInsightsCard",
        "ChildrenBreakdown",
        "CampaignDuplicationCard",
        "CTXFunnelChart",
        "ShopsAdsCreativeDelivery",
        "Delivery",
        "DeliveryInsightsAuctionInsightsCard",
        "DeliveryErrors",
        "DeliveryWarnings",
        "DeliveryColumnMFR",
        "Engagement",
        "Insights",
        "Interactivity",
        "Recommendations",
        "MAIBAGoldenPathEntrypointCard",
        "MarketingMessagesGuidanceCard",
        "MobileUpsell",
        "AdCreativePerformanceGuidanceCard",
        "ODAXAdoptionGuidanceCard",
        "SplitTest",
        "VideoPerformance",
        "ShopsAdsROAS",
        "ShopsAdsCatalogIssues",
        "ShopsAdsGuidanceCard",
        "ShopsAdsMetrics",
        "ShopsAdsWebsiteOnlyTrafficGuidanceCard",
        "ShopsAdsConversionFunnel",
        "AgeGenderMisdeliveryPerceptionGuidanceCard",
        "BidForecasterCard",
        "BudgetForecasterCard",
        "LimitedByBidGuidanceCard",
        "LimitedByBudgetGuidanceCard",
        "BudgetCPAGuidanceCard",
        "IndustryCreativePatternsCard",
        "CreativeInspirationInsightsUnifiedCard",
        "TopProducts",
        "TopProductsL2",
        "TopProductsL3",
        "CreativeWorkspace",
        "PlayableHeatmap",
      ]),
      s = n("$InternalEnum").Mirrored([
        "Loading",
        "Error",
        "Hidden",
        "Visible",
      ]);
    ((i.PerformanceSummaryFlexGroupsEnum = e),
      (i.PerformanceSummaryWidgetNamesEnum = l),
      (i.PerformanceSummaryWidgetStatusEnum = s));
  },
  66,
);
