__d(
  "AdsPageInstagramAccountStoreSourceServerLoadedQuery.graphql",
  ["Page-instagram_business_account_spec-resolver"],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = (function () {
      var e = [
          { defaultValue: !1, kind: "LocalArgument", name: "skip_ibta" },
          { defaultValue: !1, kind: "LocalArgument", name: "skip_pbta" },
        ],
        t = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "id",
          storageKey: null,
        },
        r = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "has_profile_pic",
          storageKey: null,
        },
        o = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "legacy_instagram_user_id",
          storageKey: null,
        },
        a = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "is_authorized_for_political",
          storageKey: null,
        },
        i = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "is_professional_account",
          storageKey: null,
        },
        l = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "is_private",
          storageKey: null,
        },
        s = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "is_messaging_light_switch_enabled",
          storageKey: null,
        },
        u = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "is_ctd_leads_targeting_eligible",
          storageKey: null,
        },
        c = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "is_ctd_purchase_targeting_eligible",
          storageKey: null,
        },
        d = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "instagram_account_type",
          storageKey: null,
        },
        m = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "instagram_user_id",
          storageKey: null,
        },
        p = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "is_published",
          storageKey: null,
        },
        _ = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "profile_picture_url",
          storageKey: null,
        },
        f = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "username",
          storageKey: null,
        },
        g = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "is_shopping_onsite_checkout_enabled",
          storageKey: null,
        },
        h = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "shopping_review_status",
          storageKey: null,
        },
        y = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "date_joined",
          storageKey: null,
        },
        C = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "eimu_id",
          storageKey: null,
        },
        b = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "is_shopless_ig_account",
          storageKey: null,
        },
        v = [
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "threads_user_id",
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "threads_user_profile_pic",
            storageKey: null,
          },
        ],
        S = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "name",
          storageKey: null,
        },
        R = [t],
        L = {
          alias: "instagram_accounts",
          args: null,
          concreteType: "PageToInstagramUsersV2Connection",
          kind: "LinkedField",
          name: "page_instagram_users_v2",
          plural: !1,
          selections: [
            {
              alias: null,
              args: null,
              concreteType: "InstagramUserV2",
              kind: "LinkedField",
              name: "nodes",
              plural: !0,
              selections: [
                t,
                r,
                o,
                a,
                i,
                l,
                s,
                u,
                c,
                d,
                m,
                p,
                _,
                f,
                g,
                h,
                y,
                C,
                b,
                {
                  alias: null,
                  args: null,
                  concreteType: "XFBInstagramConnectedThreadsUserResponse",
                  kind: "LinkedField",
                  name: "instagram_connected_threads_user",
                  plural: !1,
                  selections: v,
                  storageKey: null,
                },
                {
                  condition: "skip_ibta",
                  kind: "Condition",
                  passingValue: !1,
                  selections: [
                    {
                      alias: null,
                      args: null,
                      concreteType: "XFBInstagramBackedThreadsUserResponse",
                      kind: "LinkedField",
                      name: "instagram_backed_threads_user",
                      plural: !1,
                      selections: v,
                      storageKey: null,
                    },
                  ],
                },
                {
                  alias: null,
                  args: null,
                  concreteType: "MiniShopStorefront",
                  kind: "LinkedField",
                  name: "mini_shop_storefront",
                  plural: !1,
                  selections: [
                    t,
                    {
                      alias: null,
                      args: null,
                      kind: "ScalarField",
                      name: "title",
                      storageKey: null,
                    },
                    {
                      alias: null,
                      args: null,
                      kind: "ScalarField",
                      name: "shop_status",
                      storageKey: null,
                    },
                    {
                      alias: null,
                      args: null,
                      concreteType: "CommerceMerchantSettings",
                      kind: "LinkedField",
                      name: "commerce_merchant_settings",
                      plural: !1,
                      selections: [
                        t,
                        S,
                        {
                          alias: null,
                          args: null,
                          kind: "ScalarField",
                          name: "shop_ads_capabilities",
                          storageKey: null,
                        },
                        {
                          alias: null,
                          args: null,
                          concreteType: "ProductCatalog",
                          kind: "LinkedField",
                          name: "shop_catalog",
                          plural: !1,
                          selections: [t, S],
                          storageKey: null,
                        },
                        {
                          alias: null,
                          args: null,
                          kind: "ScalarField",
                          name: "display_name",
                          storageKey: null,
                        },
                        {
                          alias: null,
                          args: null,
                          kind: "ScalarField",
                          name: "onsite_checkout_enabled_countries",
                          storageKey: null,
                        },
                        {
                          alias: null,
                          args: null,
                          kind: "ScalarField",
                          name: "onsite_checkout_enabled_for_shops_ads_supported_countries",
                          storageKey: null,
                        },
                        {
                          alias: null,
                          args: null,
                          kind: "ScalarField",
                          name: "offsite_iab_checkout_enabled_countries",
                          storageKey: null,
                        },
                      ],
                      storageKey: null,
                    },
                    {
                      alias: null,
                      args: null,
                      concreteType: "Page",
                      kind: "LinkedField",
                      name: "page",
                      plural: !1,
                      selections: [
                        t,
                        S,
                        {
                          alias: null,
                          args: null,
                          concreteType: "Image",
                          kind: "LinkedField",
                          name: "profile_picture",
                          plural: !1,
                          selections: [
                            {
                              alias: null,
                              args: null,
                              kind: "ScalarField",
                              name: "height",
                              storageKey: null,
                            },
                            {
                              alias: null,
                              args: null,
                              kind: "ScalarField",
                              name: "uri",
                              storageKey: null,
                            },
                            {
                              alias: null,
                              args: null,
                              kind: "ScalarField",
                              name: "is_silhouette",
                              storageKey: null,
                            },
                            {
                              alias: null,
                              args: null,
                              kind: "ScalarField",
                              name: "width",
                              storageKey: null,
                            },
                          ],
                          storageKey: null,
                        },
                      ],
                      storageKey: null,
                    },
                    {
                      alias: null,
                      args: null,
                      concreteType: "InstagramUserV2",
                      kind: "LinkedField",
                      name: "ig_user",
                      plural: !1,
                      selections: [
                        t,
                        f,
                        o,
                        _,
                        {
                          alias: null,
                          args: null,
                          kind: "ScalarField",
                          name: "profile_pic",
                          storageKey: null,
                        },
                      ],
                      storageKey: null,
                    },
                    {
                      alias: null,
                      args: null,
                      concreteType: "PAYShopWorkspace",
                      kind: "LinkedField",
                      name: "storefront_workspace",
                      plural: !1,
                      selections: R,
                      storageKey: null,
                    },
                  ],
                  storageKey: null,
                },
              ],
              storageKey: null,
            },
          ],
          storageKey: null,
        },
        E = {
          alias: "page_backed_instagram_accounts",
          args: null,
          concreteType: "PageToPageBackedInstagramUsersV2Connection",
          kind: "LinkedField",
          name: "page_backed_instagram_users_v2",
          plural: !1,
          selections: [
            {
              alias: null,
              args: null,
              concreteType: "InstagramUserV2",
              kind: "LinkedField",
              name: "nodes",
              plural: !0,
              selections: [
                t,
                r,
                o,
                m,
                d,
                a,
                s,
                u,
                c,
                i,
                l,
                p,
                _,
                f,
                g,
                h,
                y,
                C,
                b,
              ],
              storageKey: null,
            },
          ],
          storageKey: null,
        },
        k = {
          condition: "skip_pbta",
          kind: "Condition",
          passingValue: !1,
          selections: [
            {
              alias: "page_backed_threads_accounts",
              args: null,
              concreteType: "XFBPageBackedThreadsUserResponse",
              kind: "LinkedField",
              name: "page_backed_threads_user",
              plural: !1,
              selections: v,
              storageKey: null,
            },
          ],
        };
      return {
        fragment: {
          argumentDefinitions: e,
          kind: "Fragment",
          metadata: null,
          name: "AdsPageInstagramAccountStoreSourceServerLoadedQuery",
          selections: [
            {
              kind: "ClientExtension",
              selections: [
                {
                  alias: null,
                  args: null,
                  concreteType: "Page",
                  kind: "LinkedField",
                  name: "loaded_pages",
                  plural: !0,
                  selections: [
                    t,
                    L,
                    {
                      alias: "instagram_business_account",
                      args: null,
                      fragment: {
                        args: null,
                        kind: "FragmentSpread",
                        name: "PageInstagramBusinessAccountSpecResolverFragment",
                      },
                      kind: "RelayResolver",
                      name: "instagram_business_account_spec",
                      resolverModule: n(
                        "Page-instagram_business_account_spec-resolver",
                      ).instagram_business_account_spec,
                      path: "loaded_pages.instagram_business_account",
                    },
                    E,
                    k,
                  ],
                  storageKey: null,
                },
              ],
            },
          ],
          type: "Query",
          abstractKey: null,
        },
        kind: "Request",
        operation: {
          argumentDefinitions: e,
          kind: "Operation",
          name: "AdsPageInstagramAccountStoreSourceServerLoadedQuery",
          selections: [
            {
              kind: "ClientExtension",
              selections: [
                {
                  alias: null,
                  args: null,
                  concreteType: "Page",
                  kind: "LinkedField",
                  name: "loaded_pages",
                  plural: !0,
                  selections: [
                    t,
                    L,
                    {
                      name: "instagram_business_account_spec",
                      args: null,
                      fragment: {
                        kind: "InlineFragment",
                        selections: [
                          {
                            alias: null,
                            args: null,
                            concreteType: "InstagramUserV2",
                            kind: "LinkedField",
                            name: "instagram_business_account",
                            plural: !1,
                            selections: [C, t, o, l, d, i, g, p, _, h, f, u, c],
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            concreteType: null,
                            kind: "LinkedField",
                            name: "bizlink_instagram_business_account",
                            plural: !1,
                            selections: [
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "__typename",
                                storageKey: null,
                              },
                              C,
                              {
                                kind: "InlineFragment",
                                selections: R,
                                type: "Node",
                                abstractKey: "__isNode",
                              },
                            ],
                            storageKey: null,
                          },
                        ],
                        type: "Page",
                        abstractKey: null,
                      },
                      kind: "RelayResolver",
                      storageKey: null,
                      isOutputType: !0,
                    },
                    E,
                    k,
                  ],
                  storageKey: null,
                },
              ],
            },
          ],
        },
        params: {
          cacheID: "1643781ab4e3d54b727e0a8d6b711c9b",
          id: null,
          metadata: {},
          name: "AdsPageInstagramAccountStoreSourceServerLoadedQuery",
          operationKind: "query",
          text: null,
        },
      };
    })();
    a.exports = e;
  },
  null,
);
