__d(
  "AdsPerfInteractionConstants",
  [
    "$InternalEnum",
    "AdsDraftConstants",
    "InteractionTracingConfigDefault",
    "gkx",
    "qpl",
  ],
  function (t, n, r, o, a, i, l) {
    "use strict";
    var e,
      s,
      u = new Set([
        "am.editor.change_level",
        "am.message_marketing_editor.change_level",
        "am.editor.change_same_level",
        "am.manage_ads.load_editor",
        "am.route.initial_load",
        "am.side_panel.load_charts",
        "am.duplication.processing_duplication",
        "am.message_marketing_duplication.processing_duplication",
        "am.edit_targeting.audience_estimates",
        "am.draft.create_draft",
        "am.edit_ads.load_preview",
        "am.editor.load_campaign_tree",
      ]),
      c = new Set([
        "am.media_picker_dialog.load_optimize",
        "am.edit.apply_advantage_audience",
        "am.insights_chart.change_metrics",
        "am.full_page.load",
        "ar.view.metric_change",
        "ar.view.new_report",
        "ar.view.dimension_change",
        "ar.view.time_range_change",
        "ar.table.export_report",
        "ar.account_selector.load",
        "ar.view.filter_change",
        "ar.management.select_report",
        "ar.view.sort_change",
        "ar.page.load_next_page",
        "ar.manage_report.load_page",
        "ar.view.refresh_report",
        "ar.view.save_report",
        "ar.view.locked_dimension_change",
        "ar.view.locked_dimension_change",
        "ar.management.delete_report",
        "ar.table.duplicate_report",
        "ar.view.report_initial_load",
        "ar.management.page_load",
        "ar.management.filter_change",
        "ar.manage_report.sort",
        "ar.create.custom_breakdown",
        "ar.update.custom_breakdown",
        "ar.delete.custom_breakdown",
        "ar.manage_report.load_more",
        "ar.table.share_report",
        "ar.export_history.delete",
      ]),
      d =
        ((e = {}),
        (e["am.edit_video.upload"] = 50),
        (e["am.insights_table.export_report"] = 25),
        (e["am.route.initial_load"] = 33),
        (e["am.edit_ads.upload_asset_in_media_dialog"] = 25),
        (e["am.table.load_publish_dialog"] = 20),
        (e["am.management.page_load"] = 20),
        (e["am.duplication.processing_duplication"] = 10),
        (e["am.editor.change_level"] = 25),
        (e["am.editor.change_same_level"] = 10),
        (e["am.manage_ads.load_editor"] = 30),
        (e["am.table_data_display.refresh_button"] = 15),
        (e["am.table_data_display.change_level"] = 15),
        (e["am.table_data_display.change_date_range"] = 15),
        (e["am.publish_ads.in_editor"] = 25),
        e),
      m = new Set([
        (s = r("qpl"))._(270230590, "3812"),
        s._(270219248, "6605"),
        s._(270212896, "1656"),
        s._(270209003, "7190"),
        s._(270207160, "1644"),
        s._(270218712, "9178"),
      ]),
      p = new Set([s._(41484311, "2605"), s._(41484309, "430")]),
      _ = {
        DRAFT: "DRAFT",
        EXISTING: "EXISTING",
        MIXED: "MIXED_OBJECT_SOURCE",
        BULK: "BULK",
        SINGLE: "SINGLE",
      },
      f = {
        START: 1,
        SUCCESS: 2,
        FAIL: 3,
        CANCEL: 4,
        TIMEOUT: 113,
        OFFLINE: 160,
        ERROR: 87,
      },
      g = 12e4,
      h = babelHelpers.extends(
        {},
        o("InteractionTracingConfigDefault").DEFAULT_TRACING_CONFIG,
        {
          useDocumentBodyForVCRoot: !1,
          timeout: g,
          heroLatePlaceholderDetection: r("gkx")("21517"),
          qplPointFilterRegex:
            /(^(server_)?adp_|Relay_|late_mutation.+([2-9]|\d\d))|FLUSH_|Mount_|Queue_|Render_/,
        },
      ),
      y = babelHelpers.extends({}, h, {
        timeout: 60 * 6e4,
        disableLoomTrace: !0,
      }),
      C = new Map([
        [
          o("AdsDraftConstants").BACKGROUND_PUBLISH_USE_CASE,
          "am.toast_card.publish",
        ],
        ["tableExport", "am.toast_card.export_table"],
        ["importCriticalError", "am.toast_card.import"],
        ["importSuccess", "am.toast_card.import"],
        ["exportSuccess", "am.toast_card.export_ads"],
        ["creationError", "am.editor"],
        ["videoUpload", "am.toast_card.video_upload"],
      ]),
      b = [
        "AdPreviewPageletController",
        "/ads/ad_preview/render_props/",
        "/ads/ad_preview/errorsv2/",
        "/ajax/bootloader-endpoint/",
      ],
      v = {
        FOOTER_CELL_MOUNTED_OR_EMPTY_TABLE:
          "FOOTER_CELL_MOUNTED_OR_EMPTY_TABLE",
        AM_MANAGEMENT_PAGE_LOAD_END: "AM_MANAGEMENT_PAGE_LOAD_END",
        AM_EDITOR_CHANGE_CATALOG: "AM_EDITOR_CHANGE_CATALOG",
        EVENTS_MANAGER_DIAGNOSTIC: "EVENTS_MANAGER_DIAGNOSTIC",
        AM_TABLE_SCROLL: "AM_TABLE_SCROLL",
      },
      S = {
        ADS_MEDIA_PICKER_DIALOG_ADD_IMAGE:
          "AdsWizardMediaPickerContainer.react",
      },
      R = n("$InternalEnum").Mirrored([
        "ADS_CANVAS_SLIDESHOW_UPLOADER",
        "ADS_CHUNKED_UPLOADER_ENCODE",
        "ADS_CHUNKED_UPLOADER_UPLOAD",
        "ADS_DLO_SLIDESHOW_UPLOADER",
        "ADS_EDITOR_SLIDESHOW_UPLOADER",
        "ADS_INSTAGRAM_VIDEO_UPLOADER_PROVIDER",
        "ADS_UNCHUNKED_UPLOADER_UPLOAD",
        "UPLOAD_EDITED_VIDEO",
        "UPLOAD_BULK_VIDEOS",
      ]),
      L = n("$InternalEnum").Mirrored([
        "ADS_CHUNKED_UPLOADER",
        "ADS_INSTAGRAM_VIDEO_UPLOADER_PROVIDER",
        "ADS_UNCHUNKED_UPLOADER",
        "UNKNOWN",
        "UPLOAD_EDITED_VIDEO",
      ]),
      E = new Set([
        "edit_primary_text",
        "edit_primary_text_asset",
        "edit_headline",
        "edit_headline_asset",
        "edit_url",
        "edit_url_asset",
        "edit_description",
        "edit_description_asset",
        "AdsUEditorAdGroupCreativeTokenizedMessageFieldWithTextGenContainer.react",
        "AdsUEditorAdgroupCreativeTokenizedMessageFieldContainer.react",
        "AdsUEditorAdgroupTestimonialField.react",
      ]);
    ((l.EDITOR_INTERACTIONS = u),
      (l.ENABLE_BACKEND_DATA_FOR_INTERACTIONS = c),
      (l.QPL_LOSS_TRACK_INTERACTIONS = d),
      (l.EDITOR_INTERACTIONS_QPL_EVENT = m),
      (l.EDITOR_SCENARIOS_WWW_QPL_EVENT = p),
      (l.EDITOR_METADATA = _),
      (l.WWW_QPL_END_ACTION = f),
      (l.ADS_DEFAULT_TRACING_CONFIG = h),
      (l.ADS_VERY_LONG_INTERACTION_TRACING_CONFIG = y),
      (l.TOAST_CARD_USE_CASES_ON_HERO_TRACING = C),
      (l.LOG_INTERACTIONS_METADATA_CONTROLLERS_ALLOWLIST = b),
      (l.INTENTIONAL_VC_HOLDER_INSTANCE_IDS = v),
      (l.START_CALLSITES_NAME = S),
      (l.VideoUploadErrorCallsiteEnums = R),
      (l.VideoUploadSuccessCallsiteEnums = L),
      (l.EDIT_TEXT_ENTRY_POINT = E));
  },
  98,
);
