__d(
  "AdsPageInstagramAccountStoreSourceServerQuery.graphql",
  ["Page-instagram_business_account_spec-resolver", "relay-runtime"],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = (function () {
      var e = [
          { defaultValue: null, kind: "LocalArgument", name: "ids" },
          { defaultValue: !1, kind: "LocalArgument", name: "skip_ibta" },
          { defaultValue: !1, kind: "LocalArgument", name: "skip_pbta" },
        ],
        t = [{ kind: "Variable", name: "ids", variableName: "ids" }],
        r = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "id",
          storageKey: null,
        },
        o = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "has_profile_pic",
          storageKey: null,
        },
        a = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "legacy_instagram_user_id",
          storageKey: null,
        },
        i = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "is_authorized_for_political",
          storageKey: null,
        },
        l = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "is_messaging_light_switch_enabled",
          storageKey: null,
        },
        s = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "is_ctd_leads_targeting_eligible",
          storageKey: null,
        },
        u = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "is_ctd_purchase_targeting_eligible",
          storageKey: null,
        },
        c = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "is_professional_account",
          storageKey: null,
        },
        d = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "is_private",
          storageKey: null,
        },
        m = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "is_published",
          storageKey: null,
        },
        p = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "instagram_user_id",
          storageKey: null,
        },
        _ = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "instagram_account_type",
          storageKey: null,
        },
        f = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "profile_picture_url",
          storageKey: null,
        },
        g = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "username",
          storageKey: null,
        },
        h = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "is_shopping_onsite_checkout_enabled",
          storageKey: null,
        },
        y = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "shopping_review_status",
          storageKey: null,
        },
        C = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "date_joined",
          storageKey: null,
        },
        b = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "eimu_id",
          storageKey: null,
        },
        v = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "is_shopless_ig_account",
          storageKey: null,
        },
        S = [
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "threads_user_id",
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "threads_user_profile_pic",
            storageKey: null,
          },
        ],
        R = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "name",
          storageKey: null,
        },
        L = [r],
        E = {
          alias: "instagram_accounts",
          args: null,
          concreteType: "PageToInstagramUsersV2Connection",
          kind: "LinkedField",
          name: "page_instagram_users_v2",
          plural: !1,
          selections: [
            {
              alias: null,
              args: null,
              concreteType: "InstagramUserV2",
              kind: "LinkedField",
              name: "nodes",
              plural: !0,
              selections: [
                r,
                o,
                a,
                i,
                l,
                s,
                u,
                c,
                d,
                m,
                p,
                _,
                f,
                g,
                h,
                y,
                C,
                b,
                v,
                {
                  alias: null,
                  args: null,
                  concreteType: "XFBInstagramConnectedThreadsUserResponse",
                  kind: "LinkedField",
                  name: "instagram_connected_threads_user",
                  plural: !1,
                  selections: S,
                  storageKey: null,
                },
                {
                  condition: "skip_ibta",
                  kind: "Condition",
                  passingValue: !1,
                  selections: [
                    {
                      alias: null,
                      args: null,
                      concreteType: "XFBInstagramBackedThreadsUserResponse",
                      kind: "LinkedField",
                      name: "instagram_backed_threads_user",
                      plural: !1,
                      selections: S,
                      storageKey: null,
                    },
                  ],
                },
                {
                  alias: null,
                  args: null,
                  concreteType: "MiniShopStorefront",
                  kind: "LinkedField",
                  name: "mini_shop_storefront",
                  plural: !1,
                  selections: [
                    r,
                    {
                      alias: null,
                      args: null,
                      kind: "ScalarField",
                      name: "title",
                      storageKey: null,
                    },
                    {
                      alias: null,
                      args: null,
                      kind: "ScalarField",
                      name: "shop_status",
                      storageKey: null,
                    },
                    {
                      alias: null,
                      args: null,
                      concreteType: "CommerceMerchantSettings",
                      kind: "LinkedField",
                      name: "commerce_merchant_settings",
                      plural: !1,
                      selections: [
                        r,
                        R,
                        {
                          alias: null,
                          args: null,
                          kind: "ScalarField",
                          name: "shop_ads_capabilities",
                          storageKey: null,
                        },
                        {
                          alias: null,
                          args: null,
                          concreteType: "ProductCatalog",
                          kind: "LinkedField",
                          name: "shop_catalog",
                          plural: !1,
                          selections: [r, R],
                          storageKey: null,
                        },
                        {
                          alias: null,
                          args: null,
                          kind: "ScalarField",
                          name: "display_name",
                          storageKey: null,
                        },
                        {
                          alias: null,
                          args: null,
                          kind: "ScalarField",
                          name: "onsite_checkout_enabled_countries",
                          storageKey: null,
                        },
                        {
                          alias: null,
                          args: null,
                          kind: "ScalarField",
                          name: "onsite_checkout_enabled_for_shops_ads_supported_countries",
                          storageKey: null,
                        },
                        {
                          alias: null,
                          args: null,
                          kind: "ScalarField",
                          name: "offsite_iab_checkout_enabled_countries",
                          storageKey: null,
                        },
                      ],
                      storageKey: null,
                    },
                    {
                      alias: null,
                      args: null,
                      concreteType: "Page",
                      kind: "LinkedField",
                      name: "page",
                      plural: !1,
                      selections: [
                        r,
                        R,
                        {
                          alias: null,
                          args: null,
                          concreteType: "Image",
                          kind: "LinkedField",
                          name: "profile_picture",
                          plural: !1,
                          selections: [
                            {
                              alias: null,
                              args: null,
                              kind: "ScalarField",
                              name: "height",
                              storageKey: null,
                            },
                            {
                              alias: null,
                              args: null,
                              kind: "ScalarField",
                              name: "uri",
                              storageKey: null,
                            },
                            {
                              alias: null,
                              args: null,
                              kind: "ScalarField",
                              name: "is_silhouette",
                              storageKey: null,
                            },
                            {
                              alias: null,
                              args: null,
                              kind: "ScalarField",
                              name: "width",
                              storageKey: null,
                            },
                          ],
                          storageKey: null,
                        },
                      ],
                      storageKey: null,
                    },
                    {
                      alias: null,
                      args: null,
                      concreteType: "InstagramUserV2",
                      kind: "LinkedField",
                      name: "ig_user",
                      plural: !1,
                      selections: [
                        r,
                        g,
                        a,
                        f,
                        {
                          alias: null,
                          args: null,
                          kind: "ScalarField",
                          name: "profile_pic",
                          storageKey: null,
                        },
                      ],
                      storageKey: null,
                    },
                    {
                      alias: null,
                      args: null,
                      concreteType: "PAYShopWorkspace",
                      kind: "LinkedField",
                      name: "storefront_workspace",
                      plural: !1,
                      selections: L,
                      storageKey: null,
                    },
                  ],
                  storageKey: null,
                },
              ],
              storageKey: null,
            },
          ],
          storageKey: null,
        },
        k = {
          alias: "page_backed_instagram_accounts",
          args: null,
          concreteType: "PageToPageBackedInstagramUsersV2Connection",
          kind: "LinkedField",
          name: "page_backed_instagram_users_v2",
          plural: !1,
          selections: [
            {
              alias: null,
              args: null,
              concreteType: "InstagramUserV2",
              kind: "LinkedField",
              name: "nodes",
              plural: !0,
              selections: [
                r,
                o,
                a,
                i,
                l,
                s,
                u,
                p,
                _,
                c,
                d,
                m,
                f,
                g,
                h,
                y,
                C,
                b,
                v,
              ],
              storageKey: null,
            },
          ],
          storageKey: null,
        },
        I = {
          condition: "skip_pbta",
          kind: "Condition",
          passingValue: !1,
          selections: [
            {
              alias: "page_backed_threads_accounts",
              args: null,
              concreteType: "XFBPageBackedThreadsUserResponse",
              kind: "LinkedField",
              name: "page_backed_threads_user",
              plural: !1,
              selections: S,
              storageKey: null,
            },
          ],
        };
      return {
        fragment: {
          argumentDefinitions: e,
          kind: "Fragment",
          metadata: null,
          name: "AdsPageInstagramAccountStoreSourceServerQuery",
          selections: [
            {
              alias: null,
              args: t,
              concreteType: "Page",
              kind: "LinkedField",
              name: "pages",
              plural: !0,
              selections: [
                r,
                E,
                {
                  alias: "instagram_business_account",
                  args: null,
                  fragment: {
                    args: null,
                    kind: "FragmentSpread",
                    name: "PageInstagramBusinessAccountSpecResolverFragment",
                  },
                  kind: "RelayResolver",
                  name: "instagram_business_account_spec",
                  resolverModule: n(
                    "Page-instagram_business_account_spec-resolver",
                  ).instagram_business_account_spec,
                  path: "pages.instagram_business_account",
                },
                k,
                I,
              ],
              storageKey: null,
            },
          ],
          type: "Query",
          abstractKey: null,
        },
        kind: "Request",
        operation: {
          argumentDefinitions: e,
          kind: "Operation",
          name: "AdsPageInstagramAccountStoreSourceServerQuery",
          selections: [
            {
              alias: null,
              args: t,
              concreteType: "Page",
              kind: "LinkedField",
              name: "pages",
              plural: !0,
              selections: [
                r,
                E,
                {
                  name: "instagram_business_account_spec",
                  args: null,
                  fragment: {
                    kind: "InlineFragment",
                    selections: [
                      {
                        alias: null,
                        args: null,
                        concreteType: "InstagramUserV2",
                        kind: "LinkedField",
                        name: "instagram_business_account",
                        plural: !1,
                        selections: [b, r, a, d, _, c, h, m, f, y, g, s, u],
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        concreteType: null,
                        kind: "LinkedField",
                        name: "bizlink_instagram_business_account",
                        plural: !1,
                        selections: [
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "__typename",
                            storageKey: null,
                          },
                          b,
                          {
                            kind: "InlineFragment",
                            selections: L,
                            type: "Node",
                            abstractKey: "__isNode",
                          },
                        ],
                        storageKey: null,
                      },
                    ],
                    type: "Page",
                    abstractKey: null,
                  },
                  kind: "RelayResolver",
                  storageKey: null,
                  isOutputType: !0,
                },
                k,
                I,
              ],
              storageKey: null,
            },
          ],
        },
        params: {
          id: "26393503750284892",
          metadata: {},
          name: "AdsPageInstagramAccountStoreSourceServerQuery",
          operationKind: "query",
          text: null,
        },
      };
    })();
    (n("relay-runtime").PreloadableQueryRegistry.set(e.params.id, e),
      (a.exports = e));
  },
  null,
);
