__d(
  "AdsReportDatePresetType",
  [],
  function (t, n, r, o, a, i) {
    var e = Object.freeze({
      NONE: "",
      TODAY: "today",
      YESTERDAY: "yesterday",
      LAST_3_DAYS: "last_3_days",
      THIS_WEEK: "this_week",
      LAST_WEEK: "last_week",
      LAST_7_DAYS: "last_7_days",
      LAST_14_DAYS: "last_14_days",
      LAST_28_DAYS: "last_28_days",
      LAST_30_DAYS: "last_30_days",
      LAST_90_DAYS: "last_90_days",
      LAST_180_DAYS: "last_180_days",
      THIS_MONTH: "this_month",
      LAST_MONTH: "last_month",
      THIS_QUARTER: "this_quarter",
      LAST_3_MONTHS: "last_3_months",
      LIFETIME: "lifetime",
      MAXIMUM: "maximum",
      DATA_MAXIMUM: "data_maximum",
      LAST_3D: "last_3d",
      LAST_7D: "last_7d",
      LAST_14D: "last_14d",
      LAST_28D: "last_28d",
      LAST_30D: "last_30d",
      LAST_90D: "last_90d",
      LAST_24M: "last_24m",
      LAST_WEEK_MON_SUN: "last_week_mon_sun",
      LAST_WEEK_SUN_SAT: "last_week_sun_sat",
      LAST_QUARTER: "last_quarter",
      LAST_YEAR: "last_year",
      THIS_WEEK_MON_TODAY: "this_week_mon_today",
      THIS_WEEK_SUN_TODAY: "this_week_sun_today",
      THIS_YEAR: "this_year",
      LAST_2D: "last_2d",
      LAST_40D: "last_40d",
      LAST_2_DAYS: "last_2_days",
      LAST_8_DAYS: "last_8_days",
      THIS_MONTH_NO_TODAY: "this_month_no_today",
      THIS_WEEK_MON_NO_TODAY: "this_week_mon_no_today",
      THIS_WEEK_SUN_NO_TODAY: "this_week_sun_no_today",
      LAST_ND_3_2: "last_nd_3_2",
      LAST_ND_4_3: "last_nd_4_3",
      LAST_ND_5_4: "last_nd_5_4",
      LAST_ND_6_5: "last_nd_6_5",
      LAST_ND_7_6: "last_nd_7_6",
      LAST_ND_8_7: "last_nd_8_7",
      LAST_NQ_2_0: "last_nq_2_0",
      LAST_NQ_2_1: "last_nq_2_1",
      LAST_NQ_3_0: "last_nq_3_0",
      LAST_NQ_3_1: "last_nq_3_1",
      LAST_NM_1_0: "last_nm_1_0",
      LAST_NM_2_0: "last_nm_2_0",
      LAST_NM_3_0: "last_nm_3_0",
      LAST_NM_3_2: "last_nm_3_2",
      LAST_NM_4_3: "last_nm_4_3",
      LAST_NM_5_4: "last_nm_5_4",
    });
    i.default = e;
  },
  66,
);
