__d(
  "AdsVideoStore",
  [
    "fbt",
    "AdsBaseDataStore_LEGACY",
    "AdsLoadState_LEGACY",
    "AdsVideoAdsVideoCaptionChangeDefaultLocaleErrorDataAction",
    "AdsVideoAdsVideoCaptionChangeDefaultLocaleErrorDataActionFlux",
    "AdsVideoAdsVideoCaptionEditSuccessDataAction",
    "AdsVideoAdsVideoCaptionEditSuccessDataActionFlux",
    "AdsVideoAdsVideoCaptionPublishedDataActionFlux",
    "AdsVideoAdsVideoCaptionRemoveErrorDataAction",
    "AdsVideoAdsVideoCaptionRemoveErrorDataActionFlux",
    "AdsVideoAdsVideoCaptionUploadErrorDataAction",
    "AdsVideoAdsVideoCaptionUploadErrorDataActionFlux",
    "AdsVideoBatchLoadErrorDataActionFlux",
    "AdsVideoBatchLoadedDataActionFlux",
    "AdsVideoCaptionUtils",
    "AdsVideoDataManager",
    "AdsVideoEncodingSuccessDataActionFlux",
    "AdsVideoItemClickedDataActionFlux",
    "AdsVideoRemoveVideoCaptionDataActionFlux",
    "AdsVideoSetDefaultCaptionDataActionFlux",
    "AdsVideoUploadCaptionDataActionFlux",
    "AdsVideoUploadCaptionsDataActionFlux",
    "VideoCaptionSyntaxErrorTypedLogger",
    "adsAutoGeneratedCaptionActionsUnPublishCaption",
    "adsCreateStoreSelector",
    "promiseDone",
  ],
  function (t, n, r, o, a, i, l, s) {
    "use strict";
    var e = (function (e) {
        function t() {
          var t;
          return (
            (t = e.call(this) || this),
            (t.__moduleID = i.id),
            (t.isEditingVideoCaption = r("adsCreateStoreSelector")(
              [t],
              function () {
                return t.$AdsVideoStore$p_1;
              },
              { name: i.id },
            )),
            (t.getLastCaptionUploadErrorMessage = r("adsCreateStoreSelector")(
              [t],
              function () {
                return t.$AdsVideoStore$p_3();
              },
              { name: i.id },
            )),
            (t.$AdsVideoStore$p_1 = !1),
            (t.$AdsVideoStore$p_2 = null),
            t
          );
        }
        babelHelpers.inheritsLoose(t, e);
        var n = t.prototype;
        return (
          (n.getDataManager = function () {
            return r("AdsVideoDataManager");
          }),
          (n.$AdsVideoStore$p_3 = function () {
            if (!this.$AdsVideoStore$p_2) return "";
            if (this.$AdsVideoStore$p_2.error_user_msg)
              return this.$AdsVideoStore$p_2.error_user_msg;
            if (
              this.$AdsVideoStore$p_2.code &&
              !this.$AdsVideoStore$p_2.error_code
            )
              return this.$AdsVideoStore$p_2.message;
            switch (this.$AdsVideoStore$p_2.error_code) {
              case 200:
                return s._(
                  /*BTDS*/ "You may not have permission to edit this video, please upload a new one and try again.",
                );
              default:
                return s._(/*BTDS*/ "Caption Upload Failed.");
            }
          }),
          (n.__getActionTypes = function () {
            return [
              o("AdsVideoAdsVideoCaptionChangeDefaultLocaleErrorDataActionFlux")
                .actionType,
              o("AdsVideoAdsVideoCaptionEditSuccessDataActionFlux").actionType,
              o("AdsVideoAdsVideoCaptionPublishedDataActionFlux").actionType,
              o("AdsVideoAdsVideoCaptionRemoveErrorDataActionFlux").actionType,
              o("AdsVideoAdsVideoCaptionUploadErrorDataActionFlux").actionType,
              o("AdsVideoBatchLoadErrorDataActionFlux").actionType,
              o("AdsVideoBatchLoadedDataActionFlux").actionType,
              o("AdsVideoEncodingSuccessDataActionFlux").actionType,
              o("AdsVideoItemClickedDataActionFlux").actionType,
              o("AdsVideoRemoveVideoCaptionDataActionFlux").actionType,
              o("AdsVideoSetDefaultCaptionDataActionFlux").actionType,
              o("AdsVideoUploadCaptionDataActionFlux").actionType,
              o("AdsVideoUploadCaptionsDataActionFlux").actionType,
            ];
          }),
          (n.__onDispatch = function (t) {
            var e = this,
              n = t.action;
            switch (n.actionType) {
              case o("AdsVideoAdsVideoCaptionPublishedDataActionFlux")
                .actionType:
                ((this.$AdsVideoStore$p_1 = !0),
                  r("promiseDone")(
                    o("AdsVideoCaptionUtils").fetchCaption(n.videoID),
                    function (t) {
                      return e.$AdsVideoStore$p_4(t);
                    },
                    function (t) {
                      return e.$AdsVideoStore$p_5(t);
                    },
                  ),
                  this.__emitChange());
                break;
              case o("AdsVideoRemoveVideoCaptionDataActionFlux").actionType:
                ((this.$AdsVideoStore$p_2 = null),
                  (this.$AdsVideoStore$p_1 = !0),
                  r("promiseDone")(
                    o("AdsVideoCaptionUtils").remove(n.videoID, n.locale),
                    function (t) {
                      (r("adsAutoGeneratedCaptionActionsUnPublishCaption")(
                        n.locale,
                        n.videoID,
                      ),
                        e.$AdsVideoStore$p_4(t));
                    },
                    function (t) {
                      return e.$AdsVideoStore$p_6(t);
                    },
                  ),
                  this.__emitChange());
                break;
              case o("AdsVideoSetDefaultCaptionDataActionFlux").actionType:
                ((this.$AdsVideoStore$p_1 = !0),
                  r("promiseDone")(
                    o("AdsVideoCaptionUtils").changeDefaultLocale(
                      n.videoID,
                      n.locale,
                    ),
                    function (t) {
                      return e.$AdsVideoStore$p_4(t);
                    },
                    function (t) {
                      return e.$AdsVideoStore$p_5(t);
                    },
                  ),
                  this.__emitChange());
                break;
              case o("AdsVideoUploadCaptionDataActionFlux").actionType:
                ((this.$AdsVideoStore$p_1 = !0),
                  (this.$AdsVideoStore$p_2 = null),
                  r("promiseDone")(
                    o("AdsVideoCaptionUtils").upload(n.videoID, n.fileInput),
                    function (t) {
                      return e.$AdsVideoStore$p_4(t);
                    },
                    function (t) {
                      return e.$AdsVideoStore$p_7(t);
                    },
                  ),
                  this.__emitChange());
                break;
              case o("AdsVideoUploadCaptionsDataActionFlux").actionType:
                ((this.$AdsVideoStore$p_1 = !0),
                  (this.$AdsVideoStore$p_2 = null));
                var a = new (r("VideoCaptionSyntaxErrorTypedLogger"))();
                (a
                  .setVideoID(n.videoID)
                  .setSource("ads_manager")
                  .setShouldShowToUser(1),
                  r("promiseDone")(
                    o("AdsVideoCaptionUtils").validateCaptions(n.captionFiles),
                    function (t) {
                      (a.setUploadedCaptionFile(t.captionText).log(),
                        r("promiseDone")(
                          o("AdsVideoCaptionUtils").uploadCaptions(
                            n.videoID,
                            n.captionFiles,
                            n.localesToRemove,
                            n.defaultLocale,
                          ),
                          function (t) {
                            (e.$AdsVideoStore$p_4(t),
                              n.callback && n.callback());
                          },
                          function (t) {
                            e.$AdsVideoStore$p_7(t);
                          },
                        ));
                    },
                    function (t) {
                      (a
                        .setNewErrorCode(t.code)
                        .setNewErrorMessage(t.message)
                        .setUploadedCaptionFile(t.captionText)
                        .log(),
                        e.$AdsVideoStore$p_7(t));
                    },
                  ),
                  this.__emitChange());
                break;
              case o("AdsVideoAdsVideoCaptionEditSuccessDataActionFlux")
                .actionType:
                ((this.$AdsVideoStore$p_1 = !1),
                  (this.$AdsVideoStore$p_2 = null),
                  this.$AdsVideoStore$p_8(n.video),
                  this.__emitChange());
                break;
              case o("AdsVideoAdsVideoCaptionRemoveErrorDataActionFlux")
                .actionType:
              case o(
                "AdsVideoAdsVideoCaptionChangeDefaultLocaleErrorDataActionFlux",
              ).actionType:
                ((this.$AdsVideoStore$p_1 = !1), this.__emitChange());
                break;
              case o("AdsVideoAdsVideoCaptionUploadErrorDataActionFlux")
                .actionType:
                ((this.$AdsVideoStore$p_2 = n.error),
                  (this.$AdsVideoStore$p_1 = !1),
                  this.__emitChange());
                break;
              case o("AdsVideoEncodingSuccessDataActionFlux").actionType:
                this.__handleData(
                  new Map([[n.video.id, n.video]]),
                  r("AdsLoadState_LEGACY").LOADED,
                );
                break;
              case o("AdsVideoItemClickedDataActionFlux").actionType:
                ((this.$AdsVideoStore$p_2 = null), this.__emitChange());
                break;
              case o("AdsVideoBatchLoadedDataActionFlux").actionType:
                this.__handleData(n.videos, r("AdsLoadState_LEGACY").LOADED);
                break;
              case o("AdsVideoBatchLoadErrorDataActionFlux").actionType:
                this.__handleData(n.errors, r("AdsLoadState_LEGACY").ERROR);
                break;
            }
          }),
          (n.$AdsVideoStore$p_8 = function (t) {
            this.__handleData(
              new Map([[t.id, t]]),
              r("AdsLoadState_LEGACY").LOADED,
            );
          }),
          (n.$AdsVideoStore$p_5 = function (t) {
            r(
              "AdsVideoAdsVideoCaptionChangeDefaultLocaleErrorDataAction",
            ).dispatch(
              { error: t },
              { line: "299", module: "AdsVideoStore.js", moduleID: i.id },
            );
          }),
          (n.$AdsVideoStore$p_7 = function (t) {
            r("AdsVideoAdsVideoCaptionUploadErrorDataAction").dispatch(
              { error: t },
              { line: "307", module: "AdsVideoStore.js", moduleID: i.id },
            );
          }),
          (n.$AdsVideoStore$p_4 = function (t) {
            r("AdsVideoAdsVideoCaptionEditSuccessDataAction").dispatch(
              { video: t, timestamp: Date.now() },
              { line: "311", module: "AdsVideoStore.js", moduleID: i.id },
            );
          }),
          (n.$AdsVideoStore$p_6 = function (t) {
            r("AdsVideoAdsVideoCaptionRemoveErrorDataAction").dispatch(
              { error: t },
              { line: "318", module: "AdsVideoStore.js", moduleID: i.id },
            );
          }),
          t
        );
      })(r("AdsBaseDataStore_LEGACY")),
      u = new e();
    l.default = u;
  },
  226,
);
