__d(
  "ApiAdCreativeFields",
  [],
  function (t, n, r, o, a, i) {
    var e = Object.freeze({
      ACCOUNT_ID: "account_id",
      ACTOR_ID: "actor_id",
      ACTOR_TYPE: "actor_type",
      AD_DISCLAIMER_SPEC: "ad_disclaimer_spec",
      AD_LABELS: "adlabels",
      AD_LABELS_OPERATION: "adlabels_operation",
      AD_PREVIEW_MULTI_PHOTO_OVERLAY_COUNT:
        "ad_preview_multi_photo_overlay_count",
      AD_SENSITIVE_CONTEXT_ID: "ad_sensitive_context_id",
      ADDITIONAL_DATA: "additional_data",
      APP_EXPERIENCE_SPEC: "app_experience_spec",
      APPLINK_TREATMENT: "applink_treatment",
      ASSET_FEED_ID: "asset_feed_id",
      ASSET_FEED_SPEC: "asset_feed_spec",
      AUTHORIZATION_CATEGORY: "authorization_category",
      AUTO_UPDATE: "auto_update",
      BIZ_AI: "biz_ai",
      BODY: "body",
      BOOST_ASSET_SPEC: "boost_asset_spec",
      BRANDED_CONTENT: "branded_content",
      BRANDED_CONTENT_BOOSTING_TYPE: "branded_content_boosting_type",
      BRANDED_CONTENT_SPONSOR_PAGE_ID: "branded_content_sponsor_page_id",
      BUNDLE_FOLDER_ID: "bundle_folder_id",
      BUSINESS_AD_DATA_ID: "business_ad_data_id",
      CALL_TO_ACTION: "call_to_action",
      CALL_TO_ACTION_TYPE: "call_to_action_type",
      CAPTION_IDS: "caption_ids",
      CATALOG_STORY_SPEC: "catalog_story_spec",
      CATEGORIZATION_CRITERIA: "categorization_criteria",
      CATEGORY_MEDIA_SOURCE: "category_media_source",
      CLUSTER_ID: "cluster_id",
      COLLABORATIVE_ADS_LSB_IMAGE_BANK_ID:
        "collaborative_ads_lsb_image_bank_id",
      CONTEXTUAL_MULTI_ADS: "contextual_multi_ads",
      CREATIVE_ID: "creative_id",
      CREATIVE_INSIGHTS: "creative_insights",
      CREATIVE_OPTIMIZATION_SPEC: "creative_optimization_spec",
      CREATIVE_OPTIONAL: "creative_optional",
      CREATIVE_SOURCING_SPEC: "creative_sourcing_spec",
      DEGREES_OF_FREEDOM_SPEC: "degrees_of_freedom_spec",
      DEGREES_OF_FREEDOM_SPEC_DEPRECATED: "degree_of_freedom_spec",
      DERIVED_OBJECT_STORY_ID: "derived_object_story_id",
      DESTINATION_SET_ID: "destination_set_id",
      DESTINATION_SPEC: "destination_spec",
      DYNAMIC_AD_VOICE: "dynamic_ad_voice",
      EFFECTIVE_AUTHORIZATION_CATEGORY: "effective_authorization_category",
      EFFECTIVE_INSTAGRAM_MEDIA_ID: "effective_instagram_media_id",
      EFFECTIVE_INSTAGRAM_STORY_ID: "effective_instagram_story_id",
      EFFECTIVE_OBJECT_STORY_ID: "effective_object_story_id",
      ENABLE_DIRECT_INSTALL: "enable_direct_install",
      ENABLE_LAUNCH_INSTANT_APP: "enable_launch_instant_app",
      EXECUTION_OPTIONS: "execution_options",
      EXISTING_POST_TITLE: "existing_post_title",
      FACEBOOK_BRANDED_CONTENT: "facebook_branded_content",
      FORCE_CREATE_NEW_CREATIVE: "force_create_new_creative",
      FORCE_DOWNLOAD_IMAGE: "force_download_image",
      FORMAT_TRANSFORMATION_SPEC: "format_transformation_spec",
      GENERATIVE_ASSET_SPEC: "generative_asset_spec",
      HOUSE_SHOPS_ADS_SELLER_CONTENT: "house_shops_ads_seller_content",
      ID: "id",
      IMAGE_CROPS: "image_crops",
      IMAGE_FILE: "image_file",
      IMAGE_HASH: "image_hash",
      IMAGE_URL: "image_url",
      INSTAGRAM_ACTOR_ID: "instagram_actor_id",
      INSTAGRAM_ASSET_ID: "instagram_asset_id",
      INSTAGRAM_BRANDED_CONTENT: "instagram_branded_content",
      INSTAGRAM_DYNAMIC_MEDIAS: "instagram_dynamic_medias",
      INSTAGRAM_MEDIA_ID: "instagram_media_id",
      INSTAGRAM_PERMALINK_URL: "instagram_permalink_url",
      INSTAGRAM_STORY_ID: "instagram_story_id",
      INSTAGRAM_USER_ID: "instagram_user_id",
      INSTANT_CHECKOUT_SETTING: "instant_checkout_setting",
      INTERACTIVE_COMPONENTS_SPEC: "interactive_components_spec",
      IS_DCO_INTERNAL: "is_dco_internal",
      LINK_DEEP_LINK_URL: "link_deep_link_url",
      LINK_DESTINATION_DISPLAY_URL: "link_destination_display_url",
      LINK_OG_ID: "link_og_id",
      LINK_TARGET: "link_target",
      LINK_URL: "link_url",
      LIVE_VIDEO_REMINDER: "live_video_reminder",
      MARKETING_MESSAGE_SPEC: "marketing_message_spec",
      MARKETING_MESSAGE_STRUCTURED_SPEC: "marketing_message_structured_spec",
      MARKETING_MESSAGES_PRODUCT_IDENTITY:
        "marketing_messages_product_identity",
      MEDIA_SOURCING_SPEC: "media_sourcing_spec",
      MEDIA_TYPE: "media_type",
      MESSENGER_SPONSORED_MESSAGE: "messenger_sponsored_message",
      MOCKUP_ID: "mockup_id",
      NAME: "name",
      NORMALIZED_BC_TRIGGER: "normalized_bc_trigger",
      NUI_RELATED_PAGE_ID: "related_page_id",
      NUI_RELATED_PAGE_NAME: "related_page_name",
      OBJECT_ID: "object_id",
      OBJECT_STORE_URL: "object_store_url",
      OBJECT_STORY_ID: "object_story_id",
      OBJECT_STORY_SPEC: "object_story_spec",
      OBJECT_TYPE: "object_type",
      OBJECT_URL: "object_url",
      OMNICHANNEL_LINK_SPEC: "omnichannel_link_spec",
      OPTIMIZATION_TYPE: "optimization_type",
      PAGE_ID: "page_id",
      PAGE_PRIVACY_POLICY_URL: "page_privacy_policy_url",
      PAGE_WELCOME_MESSAGE: "page_welcome_message",
      PAGE_WHATSAPP_NUMBER_ID: "page_whatsapp_number_id",
      PHOTO_ALBUM_CONVERTED_CREATIVE_ID: "photo_album_converted_creative_id",
      PHOTO_ALBUM_CONVERTED_CREATIVE_VERSION_ID:
        "photo_album_converted_creative_version_id",
      PHOTO_ALBUM_SOURCE_OBJECT_STORY_ID: "photo_album_source_object_story_id",
      PLACE_PAGE_SET_ID: "place_page_set_id",
      PLATFORM_CUSTOMIZATIONS: "platform_customizations",
      PLAYABLE_ASSET_ID: "playable_asset_id",
      PORTRAIT_CUSTOMIZATIONS: "portrait_customizations",
      PREVIEWS: "previews",
      PRODUCT_DATA: "product_data",
      PRODUCT_SET_ID: "product_set_id",
      PRODUCT_SUGGESTION_SETTINGS: "product_suggestion_settings",
      RECOMMENDER_SETTINGS: "recommender_settings",
      REFERRAL_ID: "referral_id",
      REGIONAL_REGULATION_DISCLAIMER_SPEC:
        "regional_regulation_disclaimer_spec",
      SCRAPED_LINK_DATA_MAP: "scraped_link_data_map",
      SHOP_SPEC: "shop_spec",
      SOURCE_FACEBOOK_POST_ID: "source_facebook_post_id",
      SOURCE_INSTAGRAM_MEDIA_ID: "source_instagram_media_id",
      STATUS: "status",
      STORED_OBJECT_STORY_SPEC: "stored_object_story_spec",
      STORY_GRAPHQL_TOKEN: "story_graphql_token",
      STORY_ID: "story_id",
      TEMPLATE_URL: "template_url",
      TEMPLATE_URL_SPEC: "template_url_spec",
      TEXT_TYPE: "text_type",
      THREADS_MEDIA_ID: "threads_media_id",
      THREADS_USER_ID: "threads_user_id",
      THUMBNAIL_HEIGHT: "thumbnail_height",
      THUMBNAIL_ID: "thumbnail_id",
      THUMBNAIL_SOURCE: "thumbnail_source",
      THUMBNAIL_URL: "thumbnail_url",
      THUMBNAIL_WIDTH: "thumbnail_width",
      TITLE: "title",
      TYPE: "type",
      UCA_DRAFT_VERSION: "uca_draft_version",
      URL_TAGS: "url_tags",
      USE_PAGE_ACTOR_OVERRIDE: "use_page_actor_override",
      VIDEO_DATA: "video_data",
      VIDEO_HD: "video_hd",
      VIDEO_ID: "video_id",
      VISUAL_HASH: "visual_hash",
      WAMO_WHATSAPP_IDENTITY_SPEC: "wamo_whatsapp_identity_spec",
      WHATS_APP_BUSINESS_ASSET_ID: "whats_app_business_asset_id",
      WHATS_APP_BUSINESS_PHONE_NUMBER: "whats_app_business_phone_number",
      WHATSAPP_BUSINESS_PHONE_NUMBER_ID: "whatsapp_business_phone_number_id",
      WHATSAPP_BUSINESS_PROFILE_ID: "whatsapp_business_profile_id",
      WHATSAPP_CHANNEL_SPEC: "whatsapp_channel_spec",
      WHATSAPP_MM_BUSINESS_PHONE_NUMBER_ID:
        "whatsapp_mm_business_phone_number_id",
    });
    i.default = e;
  },
  66,
);
