__d(
  "ApiDynamicCreativeOptimizationTypes",
  [],
  function (t, n, r, o, a, i) {
    var e = Object.freeze({
      REGULAR: "REGULAR",
      LANGUAGE: "LANGUAGE",
      PLACEMENT: "PLACEMENT",
      VIDEO_BANDWIDTH: "VIDEO_BANDWIDTH",
      BRAND: "BRAND",
      ASSET_CUSTOMIZATION: "ASSET_CUSTOMIZATION",
      DCO_PARITY: "DCO_PARITY",
      PREVIEW_DYNAMIC_RENDERING: "PREVIEW_DYNAMIC_RENDERING",
      LOCALIZED_PLACEMENTS: "LOCALIZED_PLACEMENTS",
      DEGREES_OF_FREEDOM: "DEGREES_OF_FREEDOM",
      FORMAT_AUTOMATION: "FORMAT_AUTOMATION",
      DOF_WITH_IMAGE_CROP: "DOF_WITH_IMAGE_CROP",
      DOF_MESSAGING_DESTINATION: "DOF_MESSAGING_DESTINATION",
      ACO_AUTOFLOW: "ACO_AUTOFLOW",
      AUTOMATED_SHOPPING_ADS: "AUTOMATED_SHOPPING_ADS",
      MULTI_CREATOR: "MULTI_CREATOR",
      UNIFIED_PROFILE_VISIT_DESTINATION: "UNIFIED_PROFILE_VISIT_DESTINATION",
    });
    i.default = e;
  },
  66,
);
