__d(
  "AutoGeneratedCaptionData",
  ["AdsAutogenerationCaptionStatus", "immutable"],
  function (t, n, r, o, a, i, l) {
    "use strict";
    var e = (function (e) {
      function t() {
        return e.apply(this, arguments) || this;
      }
      return (babelHelpers.inheritsLoose(t, e), t);
    })(
      r("immutable").Record({
        captions: [],
        isFetched: !1,
        selectedLocale: null,
        captionAutogenerationStatus: r("AdsAutogenerationCaptionStatus")
          .NOT_STARTED,
      }),
    );
    l.default = e;
  },
  98,
);
