__d(
  "BillingAddCreditCardScreenQuery.graphql",
  ["BillingAddCreditCardScreenQuery_facebookRelayOperation"],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = (function () {
      var e = { defaultValue: null, kind: "LocalArgument", name: "country" },
        t = { defaultValue: null, kind: "LocalArgument", name: "currency" },
        r = { defaultValue: null, kind: "LocalArgument", name: "intent" },
        o = {
          defaultValue: null,
          kind: "LocalArgument",
          name: "paymentAccountID",
        },
        a = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "primary_email",
          storageKey: null,
        },
        i = {
          kind: "InlineFragment",
          selections: [
            {
              alias: null,
              args: null,
              concreteType: "Phone",
              kind: "LinkedField",
              name: "most_recently_verified_cell_phone",
              plural: !1,
              selections: [
                {
                  alias: null,
                  args: null,
                  concreteType: "PhoneNumber",
                  kind: "LinkedField",
                  name: "phone_number",
                  plural: !1,
                  selections: [
                    {
                      alias: null,
                      args: null,
                      kind: "ScalarField",
                      name: "universal_number",
                      storageKey: null,
                    },
                  ],
                  storageKey: null,
                },
              ],
              storageKey: null,
            },
          ],
          type: "User",
          abstractKey: null,
        },
        l = [
          {
            kind: "Variable",
            name: "legacy_account_id",
            variableName: "paymentAccountID",
          },
        ],
        s = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "__typename",
          storageKey: null,
        },
        u = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "is_using_ec",
          storageKey: null,
        },
        c = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "payment_modes",
          storageKey: null,
        },
        d = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "is_eligible_for_postpay_upgrade",
          storageKey: null,
        },
        m = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "name",
          storageKey: null,
        },
        p = {
          alias: null,
          args: null,
          concreteType: "BillingSafeModeState",
          kind: "LinkedField",
          name: "billing_safe_mode_state",
          plural: !1,
          selections: [
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "status",
              storageKey: null,
            },
          ],
          storageKey: null,
        },
        _ = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "has_cvco_restriction",
          storageKey: null,
        },
        f = [
          { kind: "Variable", name: "country", variableName: "country" },
          { kind: "Variable", name: "currency", variableName: "currency" },
          { kind: "Variable", name: "intent", variableName: "intent" },
        ],
        g = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "can_save_to_business",
          storageKey: null,
        },
        h = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "check_make_default",
          storageKey: null,
        },
        y = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "id",
          storageKey: null,
        },
        C = [
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "amount_with_offset",
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "currency",
            storageKey: null,
          },
        ];
      return {
        fragment: {
          argumentDefinitions: [e, t, r, o],
          kind: "Fragment",
          metadata: null,
          name: "BillingAddCreditCardScreenQuery",
          selections: [
            {
              alias: null,
              args: null,
              concreteType: "Viewer",
              kind: "LinkedField",
              name: "viewer",
              plural: !1,
              selections: [
                a,
                {
                  alias: null,
                  args: null,
                  concreteType: null,
                  kind: "LinkedField",
                  name: "actor",
                  plural: !1,
                  selections: [i],
                  storageKey: null,
                },
              ],
              storageKey: null,
            },
            {
              alias: null,
              args: l,
              concreteType: null,
              kind: "LinkedField",
              name: "payment_account",
              plural: !1,
              selections: [
                {
                  alias: null,
                  args: null,
                  concreteType: null,
                  kind: "LinkedField",
                  name: "billable_account",
                  plural: !1,
                  selections: [
                    s,
                    u,
                    {
                      args: null,
                      kind: "FragmentSpread",
                      name: "useBillingAddCreditCard_info",
                    },
                    {
                      args: null,
                      kind: "FragmentSpread",
                      name: "useBillingLandingFooter_data",
                    },
                    c,
                    d,
                    {
                      alias: null,
                      args: null,
                      concreteType: "BusinessPaymentAccount",
                      kind: "LinkedField",
                      name: "owner_business_payment_account",
                      plural: !1,
                      selections: [
                        {
                          alias: null,
                          args: null,
                          concreteType: "AdBusiness",
                          kind: "LinkedField",
                          name: "business",
                          plural: !1,
                          selections: [m],
                          storageKey: null,
                        },
                      ],
                      storageKey: null,
                    },
                    {
                      kind: "InlineFragment",
                      selections: [p, _],
                      type: "AdAccount",
                      abstractKey: null,
                    },
                  ],
                  storageKey: null,
                },
                s,
                {
                  alias: null,
                  args: f,
                  concreteType: null,
                  kind: "LinkedField",
                  name: "billing_payment_method_options",
                  plural: !0,
                  selections: [
                    s,
                    {
                      kind: "InlineFragment",
                      selections: [
                        {
                          args: null,
                          kind: "FragmentSpread",
                          name: "BillingAddCreditCardView_cards",
                        },
                        g,
                        h,
                      ],
                      type: "AdAccountNewCreditCardOption",
                      abstractKey: null,
                    },
                  ],
                  storageKey: null,
                },
              ],
              storageKey: null,
            },
          ],
          type: "Query",
          abstractKey: null,
        },
        kind: "Request",
        operation: {
          argumentDefinitions: [o, e, t, r],
          kind: "Operation",
          name: "BillingAddCreditCardScreenQuery",
          selections: [
            {
              alias: null,
              args: null,
              concreteType: "Viewer",
              kind: "LinkedField",
              name: "viewer",
              plural: !1,
              selections: [
                a,
                {
                  alias: null,
                  args: null,
                  concreteType: null,
                  kind: "LinkedField",
                  name: "actor",
                  plural: !1,
                  selections: [s, i, y],
                  storageKey: null,
                },
              ],
              storageKey: null,
            },
            {
              alias: null,
              args: l,
              concreteType: null,
              kind: "LinkedField",
              name: "payment_account",
              plural: !1,
              selections: [
                {
                  alias: null,
                  args: null,
                  concreteType: null,
                  kind: "LinkedField",
                  name: "billable_account",
                  plural: !1,
                  selections: [
                    s,
                    u,
                    {
                      kind: "TypeDiscriminator",
                      abstractKey: "__isBillableAccount",
                    },
                    {
                      alias: null,
                      args: null,
                      concreteType: "BusinessPaymentAccount",
                      kind: "LinkedField",
                      name: "owner_business_payment_account",
                      plural: !1,
                      selections: [
                        y,
                        {
                          alias: null,
                          args: null,
                          concreteType: "AdBusiness",
                          kind: "LinkedField",
                          name: "business",
                          plural: !1,
                          selections: [m, y],
                          storageKey: null,
                        },
                      ],
                      storageKey: null,
                    },
                    {
                      alias: null,
                      args: null,
                      concreteType: null,
                      kind: "LinkedField",
                      name: "billable_account_tax_info",
                      plural: !1,
                      selections: [
                        s,
                        {
                          alias: null,
                          args: null,
                          kind: "ScalarField",
                          name: "business_country_code",
                          storageKey: null,
                        },
                        {
                          alias: null,
                          args: null,
                          kind: "ScalarField",
                          name: "predicated_business_country_code",
                          storageKey: null,
                        },
                        {
                          alias: null,
                          args: null,
                          kind: "ScalarField",
                          name: "entity",
                          storageKey: null,
                        },
                        {
                          alias: null,
                          args: null,
                          kind: "ScalarField",
                          name: "can_update_tax_country",
                          storageKey: null,
                        },
                      ],
                      storageKey: null,
                    },
                    {
                      alias: null,
                      args: [
                        {
                          kind: "Literal",
                          name: "requested_flags",
                          value: ["TAX_COUNTRY_MISMATCH"],
                        },
                      ],
                      kind: "ScalarField",
                      name: "billing_flags",
                      storageKey:
                        'billing_flags(requested_flags:["TAX_COUNTRY_MISMATCH"])',
                    },
                    {
                      alias: null,
                      args: null,
                      kind: "ScalarField",
                      name: "application_type",
                      storageKey: null,
                    },
                    d,
                    {
                      alias: null,
                      args: null,
                      kind: "ScalarField",
                      name: "payment_item_type",
                      storageKey: null,
                    },
                    c,
                    {
                      alias: null,
                      args: null,
                      concreteType: "CurrencyAmount",
                      kind: "LinkedField",
                      name: "available_funds",
                      plural: !1,
                      selections: C,
                      storageKey: null,
                    },
                    {
                      kind: "InlineFragment",
                      selections: [_, p],
                      type: "AdAccount",
                      abstractKey: null,
                    },
                    {
                      alias: null,
                      args: null,
                      kind: "ScalarField",
                      name: "india_emandate_increase_status",
                      storageKey: null,
                    },
                    {
                      alias: null,
                      args: null,
                      concreteType: "CurrencyAmount",
                      kind: "LinkedField",
                      name: "india_emandate_higher_config_amount",
                      plural: !1,
                      selections: C,
                      storageKey: null,
                    },
                    {
                      kind: "InlineFragment",
                      selections: [
                        {
                          alias: null,
                          args: null,
                          kind: "ScalarField",
                          name: "product_variant",
                          storageKey: null,
                        },
                      ],
                      type: "Company",
                      abstractKey: "__isCompany",
                    },
                    y,
                  ],
                  storageKey: null,
                },
                s,
                {
                  alias: null,
                  args: f,
                  concreteType: null,
                  kind: "LinkedField",
                  name: "billing_payment_method_options",
                  plural: !0,
                  selections: [
                    s,
                    {
                      kind: "InlineFragment",
                      selections: [
                        h,
                        g,
                        {
                          alias: null,
                          args: null,
                          kind: "ScalarField",
                          name: "verify_tokenization_required",
                          storageKey: null,
                        },
                        {
                          alias: null,
                          args: [
                            { kind: "Literal", name: "limit", value: 5 },
                            {
                              kind: "Variable",
                              name: "payment_legacy_account_id",
                              variableName: "paymentAccountID",
                            },
                          ],
                          concreteType: "Image",
                          kind: "LinkedField",
                          name: "billing_icons",
                          plural: !0,
                          selections: [
                            {
                              alias: null,
                              args: null,
                              kind: "ScalarField",
                              name: "uri",
                              storageKey: null,
                            },
                            {
                              alias: null,
                              args: null,
                              kind: "ScalarField",
                              name: "scale",
                              storageKey: null,
                            },
                            {
                              alias: null,
                              args: null,
                              kind: "ScalarField",
                              name: "height",
                              storageKey: null,
                            },
                            {
                              alias: null,
                              args: null,
                              kind: "ScalarField",
                              name: "width",
                              storageKey: null,
                            },
                          ],
                          storageKey: null,
                        },
                      ],
                      type: "AdAccountNewCreditCardOption",
                      abstractKey: null,
                    },
                    y,
                  ],
                  storageKey: null,
                },
                y,
              ],
              storageKey: null,
            },
          ],
        },
        params: {
          id: n("BillingAddCreditCardScreenQuery_facebookRelayOperation"),
          metadata: {},
          name: "BillingAddCreditCardScreenQuery",
          operationKind: "query",
          text: null,
        },
      };
    })();
    a.exports = e;
  },
  null,
);
