__d(
  "BillingCreditCardTypes",
  [
    "FrontierPMAmericanExpressCard",
    "FrontierPMDefaultCard",
    "FrontierPMDinersClubCard",
    "FrontierPMDiscoverCard",
    "FrontierPMJCBCard",
    "FrontierPMMastercardCard",
    "FrontierPMVisaCard",
  ],
  function (t, n, r, o, a, i, l) {
    "use strict";
    var e = {
        cardLength: 16,
        code: 0,
        image: r("FrontierPMDefaultCard").src,
        isSupported: !0,
        matchingPattern: null,
        name: "",
        securityCodeLength: 3,
        type: "",
      },
      s = babelHelpers.extends({}, e, {
        cardLength: 15,
        code: 65,
        image: r("FrontierPMAmericanExpressCard").src,
        matchingPattern: /^3[47]/,
        name: "amex",
        securityCodeLength: 4,
        type: "american_express",
      }),
      u = babelHelpers.extends({}, e, {
        cardLength: 16,
        code: 80,
        matchingPattern: /^62/,
        name: "cup",
        securityCodeLength: 3,
        type: "cup",
      }),
      c = babelHelpers.extends({}, e, {
        cardLength: 14,
        code: 64,
        image: r("FrontierPMDinersClubCard").src,
        isSupported: !1,
        matchingPattern: /^30[0-5]/,
        name: "diners",
        securityCodeLength: 3,
        type: "diners_club",
      }),
      d = babelHelpers.extends({}, e, {
        cardLength: 16,
        code: 68,
        image: r("FrontierPMDiscoverCard").src,
        matchingPattern: /^(6011|65|64[4-9])/,
        name: "disc",
        securityCodeLength: 3,
        type: "discover",
      }),
      m = babelHelpers.extends({}, e, {
        cardLength: 16,
        code: 69,
        matchingPattern: /^40117[8-9]/,
        name: "elo",
        securityCodeLength: 3,
        type: "elo",
      }),
      p = babelHelpers.extends({}, e, {
        cardLength: 16,
        code: 74,
        image: r("FrontierPMJCBCard").src,
        matchingPattern: /^35(2[8-9]|[3-8])/,
        name: "jcb",
        securityCodeLength: 3,
        type: "jcb",
      }),
      _ = babelHelpers.extends({}, e, {
        cardLength: 16,
        code: 77,
        image: r("FrontierPMMastercardCard").src,
        matchingPattern: /^5[1-5]|^2(2(2[1-9]|[3-9])|[3-6]|7([01]|20))/,
        name: "mc",
        securityCodeLength: 3,
        type: "mastercard",
      }),
      f = babelHelpers.extends({}, e, {
        cardLength: 16,
        code: 82,
        matchingPattern: /^(508[5-9]|60[6-8]|8[12])/,
        name: "rupay",
        securityCodeLength: 3,
        type: "rupay",
      }),
      g = babelHelpers.extends({}, e, {
        cardLength: 16,
        code: 85,
        isSupported: !1,
        name: "unknown",
        securityCodeLength: 3,
        type: "rupay",
      }),
      h = babelHelpers.extends({}, e, {
        cardLength: 16,
        code: 86,
        image: r("FrontierPMVisaCard").src,
        matchingPattern: /^4/,
        name: "visa",
        securityCodeLength: 3,
        type: "visa",
      }),
      y = {
        americanExpress: s,
        chinaUnionPay: u,
        dinersClub: c,
        discover: d,
        elo: m,
        jcb: p,
        masterCard: _,
        rupay: f,
        unknown: g,
        visa: h,
      };
    ((l.americanExpress = s),
      (l.chinaUnionPay = u),
      (l.dinersClub = c),
      (l.discover = d),
      (l.elo = m),
      (l.jcb = p),
      (l.masterCard = _),
      (l.rupay = f),
      (l.unknown = g),
      (l.visa = h),
      (l.BillingCreditCardTypes = y));
  },
  98,
);
