__d(
  "BillingWizardLandingScreenQuery.graphql",
  ["BillingWizardLandingScreenQuery_facebookRelayOperation", "relay-runtime"],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = (function () {
      var e = [
          {
            defaultValue: null,
            kind: "LocalArgument",
            name: "paymentAccountID",
          },
        ],
        t = [
          {
            kind: "Variable",
            name: "legacy_account_id",
            variableName: "paymentAccountID",
          },
        ],
        r = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "is_mi_mandate_nux_enforced",
          storageKey: null,
        },
        o = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "currency",
          storageKey: null,
        },
        a = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "business_country_code",
          storageKey: null,
        },
        i = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "__typename",
          storageKey: null,
        },
        l = {
          alias: null,
          args: [
            {
              kind: "Literal",
              name: "requested_flags",
              value: ["CURRENCY_COUNTRY_MISMATCH"],
            },
          ],
          kind: "ScalarField",
          name: "billing_flags",
          storageKey:
            'billing_flags(requested_flags:["CURRENCY_COUNTRY_MISMATCH"])',
        },
        s = {
          alias: null,
          args: null,
          concreteType: "BillingSafeModeState",
          kind: "LinkedField",
          name: "billing_safe_mode_state",
          plural: !1,
          selections: [
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "status",
              storageKey: null,
            },
          ],
          storageKey: null,
        },
        u = {
          alias: null,
          args: [{ kind: "Literal", name: "days", value: 28 }],
          concreteType: "CurrencyAmount",
          kind: "LinkedField",
          name: "spending_over_past_n_days_currency_amount",
          plural: !1,
          selections: [
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "amount_in_currency",
              storageKey: null,
            },
          ],
          storageKey: "spending_over_past_n_days_currency_amount(days:28)",
        },
        c = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "id",
          storageKey: null,
        },
        d = {
          alias: null,
          args: null,
          concreteType: "AdBusiness",
          kind: "LinkedField",
          name: "owning_business",
          plural: !1,
          selections: [
            c,
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "viewer_is_admin",
              storageKey: null,
            },
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "viewer_is_finance_editor",
              storageKey: null,
            },
          ],
          storageKey: null,
        },
        m = [{ kind: "Literal", name: "filter", value: "PRIMARY_ONLY" }],
        p = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "credential_id",
          storageKey: null,
        },
        _ = {
          kind: "Variable",
          name: "payment_legacy_account_id",
          variableName: "paymentAccountID",
        },
        f = [
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "amount",
            storageKey: null,
          },
          o,
        ],
        g = [
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "uri",
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "scale",
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "height",
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "width",
            storageKey: null,
          },
        ],
        h = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "last_four_digits",
          storageKey: null,
        },
        y = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "card_association_name",
          storageKey: null,
        },
        C = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "is_expired",
          storageKey: null,
        },
        b = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "expiry_month",
          storageKey: null,
        },
        v = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "expiry_year",
          storageKey: null,
        },
        S = { kind: "Literal", name: "limit", value: 1 },
        R = [S, { kind: "Literal", name: "scale", value: 2 }],
        L = [
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "label",
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "value",
            storageKey: null,
          },
        ];
      return {
        fragment: {
          argumentDefinitions: e,
          kind: "Fragment",
          metadata: null,
          name: "BillingWizardLandingScreenQuery",
          selections: [
            {
              alias: null,
              args: t,
              concreteType: null,
              kind: "LinkedField",
              name: "payment_account",
              plural: !1,
              selections: [
                r,
                {
                  alias: null,
                  args: null,
                  concreteType: null,
                  kind: "LinkedField",
                  name: "billable_account",
                  plural: !1,
                  selections: [
                    o,
                    {
                      alias: null,
                      args: null,
                      concreteType: null,
                      kind: "LinkedField",
                      name: "billable_account_tax_info",
                      plural: !1,
                      selections: [a],
                      storageKey: null,
                    },
                    i,
                    l,
                    {
                      kind: "InlineFragment",
                      selections: [s, u, d],
                      type: "AdAccount",
                      abstractKey: null,
                    },
                    {
                      args: null,
                      kind: "FragmentSpread",
                      name: "useBillingLandingFooter_data",
                    },
                  ],
                  storageKey: null,
                },
                i,
                {
                  alias: null,
                  args: null,
                  concreteType: null,
                  kind: "LinkedField",
                  name: "billing_payment_method_options",
                  plural: !0,
                  selections: [i],
                  storageKey: null,
                },
                {
                  alias: "primary_payment_methods",
                  args: m,
                  concreteType: "PaymentCredentialDetails",
                  kind: "LinkedField",
                  name: "billing_payment_methods",
                  plural: !0,
                  selections: [
                    {
                      alias: null,
                      args: null,
                      concreteType: null,
                      kind: "LinkedField",
                      name: "credential",
                      plural: !1,
                      selections: [c],
                      storageKey: null,
                    },
                  ],
                  storageKey: 'billing_payment_methods(filter:"PRIMARY_ONLY")',
                },
                {
                  args: null,
                  kind: "FragmentSpread",
                  name: "useShouldShowImportablePaymentMethods",
                },
                {
                  args: null,
                  kind: "FragmentSpread",
                  name: "BillingNuxLandingView_data",
                },
                {
                  args: null,
                  kind: "FragmentSpread",
                  name: "useBillingNuxLanding_data",
                },
              ],
              storageKey: null,
            },
          ],
          type: "Query",
          abstractKey: null,
        },
        kind: "Request",
        operation: {
          argumentDefinitions: e,
          kind: "Operation",
          name: "BillingWizardLandingScreenQuery",
          selections: [
            {
              alias: null,
              args: t,
              concreteType: null,
              kind: "LinkedField",
              name: "payment_account",
              plural: !1,
              selections: [
                r,
                {
                  kind: "TypeDiscriminator",
                  abstractKey: "__isPaymentAccount",
                },
                {
                  alias: null,
                  args: null,
                  concreteType: null,
                  kind: "LinkedField",
                  name: "billing_payment_method_options",
                  plural: !0,
                  selections: [
                    i,
                    c,
                    {
                      kind: "TypeDiscriminator",
                      abstractKey: "__isPaymentCredentialOption",
                    },
                    {
                      alias: null,
                      args: null,
                      kind: "ScalarField",
                      name: "credential_type",
                      storageKey: null,
                    },
                    {
                      kind: "InlineFragment",
                      selections: [
                        p,
                        {
                          alias: "lpmSupportsRecurring",
                          args: [
                            _,
                            {
                              kind: "Literal",
                              name: "skip_qe_check",
                              value: !0,
                            },
                          ],
                          kind: "ScalarField",
                          name: "supports_recurring",
                          storageKey: null,
                        },
                        {
                          alias: "paymentMethodType",
                          args: null,
                          kind: "ScalarField",
                          name: "payment_method_type",
                          storageKey: null,
                        },
                        {
                          alias: null,
                          args: null,
                          kind: "ScalarField",
                          name: "title",
                          storageKey: null,
                        },
                        {
                          alias: "recurringDefaultAuthChargeRaw",
                          args: null,
                          concreteType: "CurrencyAmount",
                          kind: "LinkedField",
                          name: "recurring_default_auth_charge",
                          plural: !1,
                          selections: f,
                          storageKey: null,
                        },
                        {
                          alias: "recurringLPMUserExperienceType",
                          args: null,
                          kind: "ScalarField",
                          name: "recurring_user_experience_type",
                          storageKey: null,
                        },
                        {
                          alias: "maxMandateAmountRaw",
                          args: null,
                          concreteType: "CurrencyAmount",
                          kind: "LinkedField",
                          name: "recurring_max_mandate_amount",
                          plural: !1,
                          selections: [
                            {
                              alias: null,
                              args: null,
                              kind: "ScalarField",
                              name: "amount_with_offset",
                              storageKey: null,
                            },
                            o,
                          ],
                          storageKey: null,
                        },
                        {
                          alias: "saveRecurringCheckboxLabel",
                          args: null,
                          kind: "ScalarField",
                          name: "save_recurring_check_box_label",
                          storageKey: null,
                        },
                        {
                          alias: null,
                          args: null,
                          kind: "ScalarField",
                          name: "payment_method_type",
                          storageKey: null,
                        },
                        {
                          alias: null,
                          args: null,
                          concreteType: "CurrencyAmount",
                          kind: "LinkedField",
                          name: "recurring_default_auth_charge",
                          plural: !1,
                          selections: f,
                          storageKey: null,
                        },
                        {
                          alias: null,
                          args: null,
                          kind: "ScalarField",
                          name: "recurring_user_experience_type",
                          storageKey: null,
                        },
                      ],
                      type: "AdAccountAltpayOption",
                      abstractKey: null,
                    },
                    {
                      kind: "InlineFragment",
                      selections: [
                        {
                          alias: null,
                          args: [
                            { kind: "Literal", name: "limit", value: 5 },
                            _,
                          ],
                          concreteType: "Image",
                          kind: "LinkedField",
                          name: "billing_icons",
                          plural: !0,
                          selections: g,
                          storageKey: null,
                        },
                      ],
                      type: "BillingPaymentMethodOption",
                      abstractKey: "__isBillingPaymentMethodOption",
                    },
                    {
                      kind: "InlineFragment",
                      selections: [
                        {
                          alias: null,
                          args: null,
                          kind: "ScalarField",
                          name: "use_latest_trustly_sdk",
                          storageKey: null,
                        },
                        {
                          alias: null,
                          args: null,
                          kind: "ScalarField",
                          name: "is_high_cas_user",
                          storageKey: null,
                        },
                        {
                          alias: null,
                          args: null,
                          kind: "ScalarField",
                          name: "in_scope_of_direct_debit_experiment_eu",
                          storageKey: null,
                        },
                        {
                          alias: null,
                          args: null,
                          kind: "ScalarField",
                          name: "country",
                          storageKey: null,
                        },
                      ],
                      type: "AdAccountNewDirectDebitV2Option",
                      abstractKey: null,
                    },
                    {
                      kind: "InlineFragment",
                      selections: [
                        {
                          alias: null,
                          args: null,
                          kind: "ScalarField",
                          name: "should_show_prepay_mio_flow",
                          storageKey: null,
                        },
                      ],
                      type: "PaymentAccountRequestNewCreditLineOption",
                      abstractKey: null,
                    },
                    {
                      kind: "InlineFragment",
                      selections: [
                        {
                          alias: null,
                          args: null,
                          concreteType: "ExternalCreditCard",
                          kind: "LinkedField",
                          name: "metapay_cc_credential",
                          plural: !1,
                          selections: [p, h, y, C, b, v, c],
                          storageKey: null,
                        },
                      ],
                      type: "PaymentAccountNewMetaPayCreditCardOption",
                      abstractKey: null,
                    },
                    {
                      kind: "InlineFragment",
                      selections: [
                        {
                          alias: null,
                          args: null,
                          concreteType: "ExternalCreditCard",
                          kind: "LinkedField",
                          name: "business_cc_credential",
                          plural: !1,
                          selections: [
                            {
                              alias: "icons",
                              args: R,
                              concreteType: "Image",
                              kind: "LinkedField",
                              name: "billing_icons",
                              plural: !0,
                              selections: g,
                              storageKey: "billing_icons(limit:1,scale:2)",
                            },
                            y,
                            p,
                            C,
                            h,
                            c,
                          ],
                          storageKey: null,
                        },
                      ],
                      type: "AdAccountNewCreditCardBusinessOption",
                      abstractKey: null,
                    },
                    {
                      kind: "InlineFragment",
                      selections: [
                        {
                          alias: null,
                          args: null,
                          concreteType: null,
                          kind: "LinkedField",
                          name: "business_ec_credential",
                          plural: !1,
                          selections: [
                            i,
                            c,
                            {
                              alias: null,
                              args: null,
                              kind: "ScalarField",
                              name: "legal_entity_name",
                              storageKey: null,
                            },
                            {
                              alias: null,
                              args: null,
                              kind: "ScalarField",
                              name: "partition_from",
                              storageKey: null,
                            },
                          ],
                          storageKey: null,
                        },
                        {
                          alias: "ec_icons",
                          args: R,
                          concreteType: "Image",
                          kind: "LinkedField",
                          name: "billing_icons",
                          plural: !0,
                          selections: g,
                          storageKey: "billing_icons(limit:1,scale:2)",
                        },
                      ],
                      type: "AdAccountNewExtendedCreditBusinessOption",
                      abstractKey: null,
                    },
                    {
                      kind: "InlineFragment",
                      selections: [
                        {
                          alias: null,
                          args: null,
                          concreteType: "ExternalCreditCard",
                          kind: "LinkedField",
                          name: "sibling_cc_credential",
                          plural: !1,
                          selections: [
                            {
                              kind: "InlineFragment",
                              selections: [
                                {
                                  kind: "InlineFragment",
                                  selections: [
                                    {
                                      alias: null,
                                      args: [S],
                                      concreteType: "Image",
                                      kind: "LinkedField",
                                      name: "billing_icons",
                                      plural: !0,
                                      selections: g,
                                      storageKey: "billing_icons(limit:1)",
                                    },
                                  ],
                                  type: "BillingPaymentMethod",
                                  abstractKey: "__isBillingPaymentMethod",
                                },
                              ],
                              type: "PaymentCredential",
                              abstractKey: "__isPaymentCredential",
                            },
                            p,
                            y,
                            b,
                            v,
                            C,
                            h,
                            {
                              alias: null,
                              args: null,
                              concreteType: null,
                              kind: "LinkedField",
                              name: "payment_account",
                              plural: !1,
                              selections: [
                                i,
                                {
                                  alias: null,
                                  args: null,
                                  concreteType: null,
                                  kind: "LinkedField",
                                  name: "billable_account",
                                  plural: !1,
                                  selections: [
                                    i,
                                    {
                                      alias: null,
                                      args: null,
                                      kind: "ScalarField",
                                      name: "name",
                                      storageKey: null,
                                    },
                                    c,
                                    {
                                      alias: null,
                                      args: null,
                                      kind: "ScalarField",
                                      name: "product_name",
                                      storageKey: null,
                                    },
                                  ],
                                  storageKey: null,
                                },
                                c,
                              ],
                              storageKey: null,
                            },
                            c,
                          ],
                          storageKey: null,
                        },
                      ],
                      type: "NewSharableCreditCardBusinessOption",
                      abstractKey: null,
                    },
                  ],
                  storageKey: null,
                },
                {
                  alias: null,
                  args: null,
                  concreteType: null,
                  kind: "LinkedField",
                  name: "billable_account",
                  plural: !1,
                  selections: [
                    o,
                    {
                      alias: null,
                      args: null,
                      concreteType: null,
                      kind: "LinkedField",
                      name: "billable_account_tax_info",
                      plural: !1,
                      selections: [
                        i,
                        a,
                        {
                          alias: null,
                          args: null,
                          kind: "ScalarField",
                          name: "can_update_tax_country",
                          storageKey: null,
                        },
                        {
                          alias: null,
                          args: null,
                          kind: "ScalarField",
                          name: "predicated_business_country_code",
                          storageKey: null,
                        },
                        {
                          alias: null,
                          args: null,
                          concreteType: "StreetAddress",
                          kind: "LinkedField",
                          name: "intl_address",
                          plural: !1,
                          selections: [
                            {
                              alias: null,
                              args: null,
                              kind: "ScalarField",
                              name: "full_address",
                              storageKey: null,
                            },
                          ],
                          storageKey: null,
                        },
                      ],
                      storageKey: null,
                    },
                    i,
                    l,
                    {
                      kind: "InlineFragment",
                      selections: [
                        s,
                        u,
                        d,
                        {
                          alias: null,
                          args: [
                            {
                              kind: "Literal",
                              name: "ads_coupon_entrypoint",
                              value: "billing_nux_landing",
                            },
                            {
                              kind: "Literal",
                              name: "ads_coupon_objectives",
                              value: "GENERIC",
                            },
                          ],
                          concreteType: "AdsCouponProgressDataBase",
                          kind: "LinkedField",
                          name: "active_ad_coupon_progress",
                          plural: !1,
                          selections: [
                            {
                              alias: null,
                              args: null,
                              concreteType: "CurrencyAmount",
                              kind: "LinkedField",
                              name: "coupon_currency_amount",
                              plural: !1,
                              selections: [
                                {
                                  alias: null,
                                  args: null,
                                  kind: "ScalarField",
                                  name: "formatted_amount",
                                  storageKey: null,
                                },
                              ],
                              storageKey: null,
                            },
                          ],
                          storageKey:
                            'active_ad_coupon_progress(ads_coupon_entrypoint:"billing_nux_landing",ads_coupon_objectives:"GENERIC")',
                        },
                      ],
                      type: "AdAccount",
                      abstractKey: null,
                    },
                    {
                      kind: "TypeDiscriminator",
                      abstractKey: "__isBillableAccount",
                    },
                    {
                      kind: "InlineFragment",
                      selections: [
                        {
                          alias: null,
                          args: null,
                          kind: "ScalarField",
                          name: "product_variant",
                          storageKey: null,
                        },
                      ],
                      type: "Company",
                      abstractKey: "__isCompany",
                    },
                    c,
                    {
                      alias: null,
                      args: null,
                      kind: "ScalarField",
                      name: "can_update_currency_timezone",
                      storageKey: null,
                    },
                    {
                      alias: null,
                      args: null,
                      kind: "ScalarField",
                      name: "payment_modes",
                      storageKey: null,
                    },
                    {
                      alias: "isMissingPM",
                      args: [
                        {
                          kind: "Literal",
                          name: "requested_flags",
                          value: ["MISSING_PAYMENT_METHOD"],
                        },
                      ],
                      kind: "ScalarField",
                      name: "billing_flags",
                      storageKey:
                        'billing_flags(requested_flags:["MISSING_PAYMENT_METHOD"])',
                    },
                    {
                      alias: null,
                      args: null,
                      concreteType: "XFBBillingOptionListItem",
                      kind: "LinkedField",
                      name: "supported_country_options",
                      plural: !0,
                      selections: L,
                      storageKey: null,
                    },
                    {
                      alias: null,
                      args: null,
                      concreteType: "XFBBillingOptionListItem",
                      kind: "LinkedField",
                      name: "supported_currency_options",
                      plural: !0,
                      selections: L,
                      storageKey: null,
                    },
                    {
                      alias: null,
                      args: null,
                      kind: "ScalarField",
                      name: "is_eligible_for_postpay_upgrade",
                      storageKey: null,
                    },
                  ],
                  storageKey: null,
                },
                i,
                {
                  alias: null,
                  args: null,
                  concreteType: "PaymentCredentialDetails",
                  kind: "LinkedField",
                  name: "billing_payment_methods",
                  plural: !0,
                  selections: [
                    {
                      alias: null,
                      args: null,
                      concreteType: null,
                      kind: "LinkedField",
                      name: "credential",
                      plural: !1,
                      selections: [
                        i,
                        {
                          kind: "InlineFragment",
                          selections: [
                            {
                              alias: null,
                              args: null,
                              kind: "ScalarField",
                              name: "supports_recurring",
                              storageKey: null,
                            },
                          ],
                          type: "ExternalCreditCard",
                          abstractKey: null,
                        },
                        c,
                      ],
                      storageKey: null,
                    },
                  ],
                  storageKey: null,
                },
                {
                  alias: "primary_payment_methods",
                  args: m,
                  concreteType: "PaymentCredentialDetails",
                  kind: "LinkedField",
                  name: "billing_payment_methods",
                  plural: !0,
                  selections: [
                    {
                      alias: null,
                      args: null,
                      concreteType: null,
                      kind: "LinkedField",
                      name: "credential",
                      plural: !1,
                      selections: [i, c],
                      storageKey: null,
                    },
                  ],
                  storageKey: 'billing_payment_methods(filter:"PRIMARY_ONLY")',
                },
                c,
              ],
              storageKey: null,
            },
          ],
        },
        params: {
          id: n("BillingWizardLandingScreenQuery_facebookRelayOperation"),
          metadata: {},
          name: "BillingWizardLandingScreenQuery",
          operationKind: "query",
          text: null,
        },
      };
    })();
    (n("relay-runtime").PreloadableQueryRegistry.set(e.params.id, e),
      (a.exports = e));
  },
  null,
);
