__d(
  "BillingAccountInformationScreenQuery.graphql",
  ["BillingAccountInformationScreenQuery_facebookRelayOperation"],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = (function () {
      var e = [
          {
            defaultValue: null,
            kind: "LocalArgument",
            name: "paymentAccountID",
          },
        ],
        t = [
          {
            kind: "Variable",
            name: "legacy_account_id",
            variableName: "paymentAccountID",
          },
        ],
        r = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "__typename",
          storageKey: null,
        },
        o = {
          alias: null,
          args: [
            {
              kind: "Literal",
              name: "requested_flags",
              value: [
                "TAX_INFO_PROBLEM_HARD",
                "TAX_INFO_PROBLEM_SOFT_CRTICAL",
                "CURRENCY_COUNTRY_MISMATCH",
              ],
            },
          ],
          kind: "ScalarField",
          name: "billing_flags",
          storageKey:
            'billing_flags(requested_flags:["TAX_INFO_PROBLEM_HARD","TAX_INFO_PROBLEM_SOFT_CRTICAL","CURRENCY_COUNTRY_MISMATCH"])',
        },
        a = {
          kind: "InlineFragment",
          selections: [
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "has_pending_onboarding_review",
              storageKey: null,
            },
          ],
          type: "DeveloperBillableAccount",
          abstractKey: null,
        },
        i = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "id",
          storageKey: null,
        },
        l = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "value",
          storageKey: null,
        },
        s = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "label",
          storageKey: null,
        },
        u = [l, s],
        c = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "currency",
          storageKey: null,
        },
        d = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "country",
          storageKey: null,
        },
        m = [c, d],
        p = {
          alias: null,
          args: null,
          concreteType: "BillableAccountTaxIDFieldState",
          kind: "LinkedField",
          name: "can_update_tax_id_fields",
          plural: !0,
          selections: [
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "can_update",
              storageKey: null,
            },
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "reason",
              storageKey: null,
            },
          ],
          storageKey: null,
        },
        _ = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "can_update_tax_country",
          storageKey: null,
        },
        f = {
          kind: "TypeDiscriminator",
          abstractKey: "__isBillableAccountTaxInfo",
        },
        g = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "business_name",
          storageKey: null,
        },
        h = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "is_personal",
          storageKey: null,
        },
        y = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "second_tax_id",
          storageKey: null,
        },
        C = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "second_tax_id_type_enum",
          storageKey: null,
        },
        b = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "tax_exempt",
          storageKey: null,
        },
        v = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "tax_id",
          storageKey: null,
        },
        S = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "tax_id_type_enum",
          storageKey: null,
        },
        R = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "tax_id_verification_code",
          storageKey: null,
        },
        L = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "building",
          storageKey: null,
        },
        E = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "city",
          storageKey: null,
        },
        k = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "postal_code",
          storageKey: null,
        },
        I = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "region",
          storageKey: null,
        },
        T = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "street",
          storageKey: null,
        },
        D = {
          alias: null,
          args: null,
          concreteType: "StreetAddress",
          kind: "LinkedField",
          name: "intl_address",
          plural: !1,
          selections: [L, E, k, I, T],
          storageKey: null,
        },
        x = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "email",
          storageKey: null,
        },
        $ = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "phone_number",
          storageKey: null,
        },
        P = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "website",
          storageKey: null,
        },
        N = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "business_verification_type",
          storageKey: null,
        },
        M = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "business_country_code",
          storageKey: null,
        },
        w = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "has_acked_soft_tax_info_problem",
          storageKey: null,
        };
      return {
        fragment: {
          argumentDefinitions: e,
          kind: "Fragment",
          metadata: null,
          name: "BillingAccountInformationScreenQuery",
          selections: [
            {
              alias: null,
              args: t,
              concreteType: null,
              kind: "LinkedField",
              name: "payment_account",
              plural: !1,
              selections: [
                r,
                o,
                {
                  alias: null,
                  args: null,
                  concreteType: null,
                  kind: "LinkedField",
                  name: "billable_account",
                  plural: !1,
                  selections: [r, a],
                  storageKey: null,
                },
                {
                  args: null,
                  kind: "FragmentSpread",
                  name: "useBillingAccountInformation_values",
                },
                {
                  args: null,
                  kind: "FragmentSpread",
                  name: "useBillingAcknowledgeSoftTaxInfo_account",
                },
              ],
              storageKey: null,
            },
            {
              args: null,
              kind: "FragmentSpread",
              name: "useBillingAccountInformation_usStateZipPrefixes",
            },
          ],
          type: "Query",
          abstractKey: null,
        },
        kind: "Request",
        operation: {
          argumentDefinitions: e,
          kind: "Operation",
          name: "BillingAccountInformationScreenQuery",
          selections: [
            {
              alias: null,
              args: t,
              concreteType: null,
              kind: "LinkedField",
              name: "payment_account",
              plural: !1,
              selections: [
                r,
                o,
                {
                  alias: null,
                  args: null,
                  concreteType: null,
                  kind: "LinkedField",
                  name: "billable_account",
                  plural: !1,
                  selections: [
                    r,
                    a,
                    i,
                    {
                      kind: "TypeDiscriminator",
                      abstractKey: "__isBillableAccount",
                    },
                    {
                      alias: null,
                      args: null,
                      concreteType: "XFBBillingOptionListItem",
                      kind: "LinkedField",
                      name: "supported_currency_options",
                      plural: !0,
                      selections: u,
                      storageKey: null,
                    },
                    {
                      alias: null,
                      args: null,
                      concreteType: "XFBBillingOptionListItem",
                      kind: "LinkedField",
                      name: "supported_country_options",
                      plural: !0,
                      selections: u,
                      storageKey: null,
                    },
                    {
                      alias: null,
                      args: null,
                      concreteType: "XFBBillingCountryCurrencyRestrictions",
                      kind: "LinkedField",
                      name: "billing_country_currency_restrictions",
                      plural: !1,
                      selections: [
                        {
                          alias: null,
                          args: null,
                          concreteType: "XFBBillingCountryCurrencyRestriction",
                          kind: "LinkedField",
                          name: "country_currency",
                          plural: !0,
                          selections: m,
                          storageKey: null,
                        },
                        {
                          alias: null,
                          args: null,
                          concreteType: "XFBBillingCountryCurrencyRestriction",
                          kind: "LinkedField",
                          name: "currency_country",
                          plural: !0,
                          selections: m,
                          storageKey: null,
                        },
                      ],
                      storageKey: null,
                    },
                    {
                      alias: null,
                      args: null,
                      concreteType: null,
                      kind: "LinkedField",
                      name: "billable_account_tax_info",
                      plural: !1,
                      selections: [
                        r,
                        p,
                        _,
                        f,
                        g,
                        h,
                        y,
                        C,
                        b,
                        v,
                        S,
                        R,
                        D,
                        x,
                        $,
                        P,
                        N,
                        M,
                        {
                          alias: null,
                          args: null,
                          kind: "ScalarField",
                          name: "predicated_business_country_code",
                          storageKey: null,
                        },
                      ],
                      storageKey: null,
                    },
                    {
                      alias: null,
                      args: null,
                      kind: "ScalarField",
                      name: "can_update_currency_timezone",
                      storageKey: null,
                    },
                    {
                      alias: null,
                      args: null,
                      concreteType: "XFBBillingTimezoneOptionListItem",
                      kind: "LinkedField",
                      name: "supported_timezone_options",
                      plural: !0,
                      selections: [s, l],
                      storageKey: null,
                    },
                    {
                      kind: "InlineFragment",
                      selections: [
                        {
                          alias: null,
                          args: null,
                          kind: "ScalarField",
                          name: "ad_campaign_group_type",
                          storageKey: null,
                        },
                        {
                          alias: null,
                          args: null,
                          concreteType: "AdAccountAgencyClientDeclaration",
                          kind: "LinkedField",
                          name: "agency_client_declaration",
                          plural: !1,
                          selections: [
                            {
                              alias: null,
                              args: null,
                              kind: "ScalarField",
                              name: "agency_representing_client",
                              storageKey: null,
                            },
                            {
                              alias: null,
                              args: null,
                              concreteType: "StreetAddress",
                              kind: "LinkedField",
                              name: "client_address",
                              plural: !1,
                              selections: [L, E, d, k, I, T],
                              storageKey: null,
                            },
                            {
                              alias: null,
                              args: null,
                              kind: "ScalarField",
                              name: "client_based_in_france",
                              storageKey: null,
                            },
                            {
                              alias: null,
                              args: null,
                              kind: "ScalarField",
                              name: "client_email_address",
                              storageKey: null,
                            },
                            {
                              alias: null,
                              args: null,
                              kind: "ScalarField",
                              name: "client_name",
                              storageKey: null,
                            },
                            {
                              alias: null,
                              args: null,
                              kind: "ScalarField",
                              name: "has_written_mandate_from_advertiser",
                              storageKey: null,
                            },
                            {
                              alias: null,
                              args: null,
                              kind: "ScalarField",
                              name: "is_client_paying_invoices",
                              storageKey: null,
                            },
                            {
                              alias: null,
                              args: null,
                              kind: "ScalarField",
                              name: "is_advertising_for_multiple_clients",
                              storageKey: null,
                            },
                          ],
                          storageKey: null,
                        },
                      ],
                      type: "AdAccount",
                      abstractKey: null,
                    },
                    {
                      alias: null,
                      args: null,
                      kind: "ScalarField",
                      name: "require_additional_info_for_enhanced_authentication",
                      storageKey: null,
                    },
                    {
                      kind: "InlineFragment",
                      selections: [
                        {
                          alias: null,
                          args: null,
                          kind: "ScalarField",
                          name: "purchase_order_number",
                          storageKey: null,
                        },
                      ],
                      type: "WhatsAppBusinessAccount",
                      abstractKey: null,
                    },
                    c,
                    {
                      alias: null,
                      args: null,
                      concreteType: "TimezoneInfo",
                      kind: "LinkedField",
                      name: "timezone_info",
                      plural: !1,
                      selections: [
                        {
                          alias: null,
                          args: null,
                          kind: "ScalarField",
                          name: "timezone",
                          storageKey: null,
                        },
                      ],
                      storageKey: null,
                    },
                    w,
                  ],
                  storageKey: null,
                },
                {
                  kind: "TypeDiscriminator",
                  abstractKey: "__isPaymentAccount",
                },
                {
                  kind: "InlineFragment",
                  selections: [
                    {
                      alias: null,
                      args: null,
                      concreteType: null,
                      kind: "LinkedField",
                      name: "tax_info",
                      plural: !1,
                      selections: [
                        r,
                        _,
                        p,
                        f,
                        g,
                        h,
                        y,
                        C,
                        b,
                        v,
                        S,
                        R,
                        D,
                        x,
                        $,
                        P,
                        N,
                        M,
                      ],
                      storageKey: null,
                    },
                  ],
                  type: "BusinessPaymentAccount",
                  abstractKey: null,
                },
                {
                  alias: "brazilGK",
                  args: [
                    {
                      kind: "Literal",
                      name: "gk",
                      value: "BRAZIL_VAT_REFORM_CPF_ADDRESS_VALIDATION",
                    },
                  ],
                  kind: "ScalarField",
                  name: "gk_on_payment_account",
                  storageKey:
                    'gk_on_payment_account(gk:"BRAZIL_VAT_REFORM_CPF_ADDRESS_VALIDATION")',
                },
                w,
                i,
              ],
              storageKey: null,
            },
            {
              alias: null,
              args: null,
              concreteType: "XFBBillingUSStateZipPrefixesEntry",
              kind: "LinkedField",
              name: "xfb_billing_us_state_zip_prefixes",
              plural: !0,
              selections: [
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "state",
                  storageKey: null,
                },
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "zip_prefixes",
                  storageKey: null,
                },
              ],
              storageKey: null,
            },
          ],
        },
        params: {
          id: n("BillingAccountInformationScreenQuery_facebookRelayOperation"),
          metadata: {},
          name: "BillingAccountInformationScreenQuery",
          operationKind: "query",
          text: null,
        },
      };
    })();
    a.exports = e;
  },
  null,
);
