__d(
  "BillingPaymentAccountAddFundsStateMutation.graphql",
  ["BillingPaymentAccountAddFundsStateMutation_facebookRelayOperation"],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = (function () {
      var e = [{ defaultValue: null, kind: "LocalArgument", name: "input" }],
        t = [{ kind: "Variable", name: "data", variableName: "input" }],
        r = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "payment_item_type",
          storageKey: null,
        },
        o = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "currency",
          storageKey: null,
        },
        a = [
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "amount_with_offset",
            storageKey: null,
          },
          o,
        ],
        i = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "payment_modes",
          storageKey: null,
        },
        l = {
          alias: null,
          args: null,
          concreteType: "BillingAutoReloadInfo",
          kind: "LinkedField",
          name: "auto_reload_info",
          plural: !1,
          selections: [
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "auto_reload_status",
              storageKey: null,
            },
          ],
          storageKey: null,
        },
        s = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "offset_amount",
          storageKey: null,
        },
        u = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "charged_payment_method_id",
          storageKey: null,
        },
        c = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "client_mutation_id",
          storageKey: null,
        },
        d = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "payment_id",
          storageKey: null,
        },
        m = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "result",
          storageKey: null,
        },
        p = {
          alias: null,
          args: null,
          concreteType: "CVCOCredentialRequiredVerificationInfo",
          kind: "LinkedField",
          name: "risk_verification_info",
          plural: !1,
          selections: [
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "use_case",
              storageKey: null,
            },
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "resolvable_type",
              storageKey: null,
            },
          ],
          storageKey: null,
        },
        _ = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "is_cvco_unverifiable",
          storageKey: null,
        },
        f = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "__typename",
          storageKey: null,
        },
        g = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "async_payment_status_ent_id",
          storageKey: null,
        },
        h = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "external_uri",
          storageKey: null,
        },
        y = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "needs_await_completion",
          storageKey: null,
        },
        C = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "nonce",
          storageKey: null,
        },
        b = {
          alias: null,
          args: null,
          concreteType: "IframeBrokeredPaymentURLParams",
          kind: "LinkedField",
          name: "params",
          plural: !0,
          selections: [
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "key",
              storageKey: null,
            },
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "value",
              storageKey: null,
            },
          ],
          storageKey: null,
        },
        v = [f, g, h, y, C, b],
        S = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "external_ref_id",
          storageKey: null,
        },
        R = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "india_card_issuer",
          storageKey: null,
        },
        L = [
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "uri",
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "scale",
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "height",
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "width",
            storageKey: null,
          },
        ],
        E = [
          {
            kind: "InlineDataFragmentSpread",
            name: "BillingPaymentIconUtils_data",
            selections: L,
            args: null,
            argumentDefinitions: [],
          },
        ],
        k = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "card_association",
          storageKey: null,
        },
        I = {
          kind: "InlineFragment",
          selections: [g],
          type: "AwaitAsyncPaymentStep",
          abstractKey: null,
        },
        T = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "id",
          storageKey: null,
        };
      return {
        fragment: {
          argumentDefinitions: e,
          kind: "Fragment",
          metadata: null,
          name: "BillingPaymentAccountAddFundsStateMutation",
          selections: [
            {
              alias: null,
              args: t,
              concreteType: "AddFundsResponsePayload",
              kind: "LinkedField",
              name: "payment_account_add_funds",
              plural: !1,
              selections: [
                {
                  alias: null,
                  args: null,
                  concreteType: null,
                  kind: "LinkedField",
                  name: "billable_account",
                  plural: !1,
                  selections: [
                    r,
                    {
                      alias: null,
                      args: null,
                      concreteType: "CurrencyAmount",
                      kind: "LinkedField",
                      name: "prepay_balance",
                      plural: !1,
                      selections: [
                        {
                          kind: "InlineDataFragmentSpread",
                          name: "BillingCurrencyAmount_amount",
                          selections: a,
                          args: null,
                          argumentDefinitions: [],
                        },
                      ],
                      storageKey: null,
                    },
                    i,
                    l,
                  ],
                  storageKey: null,
                },
                {
                  alias: null,
                  args: null,
                  concreteType: "StoredBalance",
                  kind: "LinkedField",
                  name: "stored_balance",
                  plural: !1,
                  selections: [
                    {
                      alias: null,
                      args: null,
                      concreteType: "CurrencyQuantity",
                      kind: "LinkedField",
                      name: "balance",
                      plural: !1,
                      selections: [
                        o,
                        {
                          kind: "InlineDataFragmentSpread",
                          name: "BillingCurrencyAmount_PBCurrencyQuantity",
                          selections: [s, o],
                          args: null,
                          argumentDefinitions: [],
                        },
                      ],
                      storageKey: null,
                    },
                  ],
                  storageKey: null,
                },
                u,
                c,
                d,
                m,
                p,
                _,
                {
                  alias: null,
                  args: null,
                  concreteType: null,
                  kind: "LinkedField",
                  name: "next_action",
                  plural: !1,
                  selections: [
                    f,
                    {
                      kind: "InlineDataFragmentSpread",
                      name: "BillingExternalSitePaymentStepUtils_ExternalSitePaymentStep",
                      selections: [
                        {
                          kind: "InlineFragment",
                          selections: v,
                          type: "ExternalSitePaymentStep",
                          abstractKey: null,
                        },
                      ],
                      args: null,
                      argumentDefinitions: [],
                    },
                    {
                      kind: "InlineDataFragmentSpread",
                      name: "BillingNativeOTPPaymentStepUtils_NativeOTPPaymentStep",
                      selections: [
                        {
                          kind: "InlineFragment",
                          selections: [
                            f,
                            g,
                            S,
                            R,
                            {
                              alias: null,
                              args: null,
                              concreteType: "Image",
                              kind: "LinkedField",
                              name: "india_issuer_icon",
                              plural: !1,
                              selections: E,
                              storageKey: null,
                            },
                            {
                              alias: null,
                              args: null,
                              concreteType: "Image",
                              kind: "LinkedField",
                              name: "card_association_icon",
                              plural: !1,
                              selections: E,
                              storageKey: null,
                            },
                            k,
                            {
                              alias: null,
                              args: null,
                              concreteType: "ExternalSitePaymentStep",
                              kind: "LinkedField",
                              name: "external_otp_webview_fallback",
                              plural: !1,
                              selections: [
                                {
                                  kind: "InlineDataFragmentSpread",
                                  name: "BillingExternalSitePaymentStepUtils_ExternalSitePaymentStep",
                                  selections: v,
                                  args: null,
                                  argumentDefinitions: [],
                                },
                              ],
                              storageKey: null,
                            },
                          ],
                          type: "NativeOTPPaymentStep",
                          abstractKey: null,
                        },
                      ],
                      args: null,
                      argumentDefinitions: [],
                    },
                    I,
                  ],
                  storageKey: null,
                },
              ],
              storageKey: null,
            },
          ],
          type: "Mutation",
          abstractKey: null,
        },
        kind: "Request",
        operation: {
          argumentDefinitions: e,
          kind: "Operation",
          name: "BillingPaymentAccountAddFundsStateMutation",
          selections: [
            {
              alias: null,
              args: t,
              concreteType: "AddFundsResponsePayload",
              kind: "LinkedField",
              name: "payment_account_add_funds",
              plural: !1,
              selections: [
                {
                  alias: null,
                  args: null,
                  concreteType: null,
                  kind: "LinkedField",
                  name: "billable_account",
                  plural: !1,
                  selections: [
                    f,
                    r,
                    {
                      alias: null,
                      args: null,
                      concreteType: "CurrencyAmount",
                      kind: "LinkedField",
                      name: "prepay_balance",
                      plural: !1,
                      selections: a,
                      storageKey: null,
                    },
                    i,
                    l,
                    T,
                  ],
                  storageKey: null,
                },
                {
                  alias: null,
                  args: null,
                  concreteType: "StoredBalance",
                  kind: "LinkedField",
                  name: "stored_balance",
                  plural: !1,
                  selections: [
                    {
                      alias: null,
                      args: null,
                      concreteType: "CurrencyQuantity",
                      kind: "LinkedField",
                      name: "balance",
                      plural: !1,
                      selections: [o, s],
                      storageKey: null,
                    },
                    T,
                  ],
                  storageKey: null,
                },
                u,
                c,
                d,
                m,
                p,
                _,
                {
                  alias: null,
                  args: null,
                  concreteType: null,
                  kind: "LinkedField",
                  name: "next_action",
                  plural: !1,
                  selections: [
                    f,
                    {
                      kind: "InlineFragment",
                      selections: [g, h, y, C, b],
                      type: "ExternalSitePaymentStep",
                      abstractKey: null,
                    },
                    {
                      kind: "InlineFragment",
                      selections: [
                        g,
                        S,
                        R,
                        {
                          alias: null,
                          args: null,
                          concreteType: "Image",
                          kind: "LinkedField",
                          name: "india_issuer_icon",
                          plural: !1,
                          selections: L,
                          storageKey: null,
                        },
                        {
                          alias: null,
                          args: null,
                          concreteType: "Image",
                          kind: "LinkedField",
                          name: "card_association_icon",
                          plural: !1,
                          selections: L,
                          storageKey: null,
                        },
                        k,
                        {
                          alias: null,
                          args: null,
                          concreteType: "ExternalSitePaymentStep",
                          kind: "LinkedField",
                          name: "external_otp_webview_fallback",
                          plural: !1,
                          selections: v,
                          storageKey: null,
                        },
                      ],
                      type: "NativeOTPPaymentStep",
                      abstractKey: null,
                    },
                    I,
                  ],
                  storageKey: null,
                },
              ],
              storageKey: null,
            },
          ],
        },
        params: {
          id: n(
            "BillingPaymentAccountAddFundsStateMutation_facebookRelayOperation",
          ),
          metadata: {},
          name: "BillingPaymentAccountAddFundsStateMutation",
          operationKind: "mutation",
          text: null,
        },
      };
    })();
    a.exports = e;
  },
  null,
);
