__d(
  "BillingAwaitCardActivationScreenQuery.graphql",
  ["BillingAwaitCardActivationScreenQuery_facebookRelayOperation"],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = (function () {
      var e = {
          defaultValue: null,
          kind: "LocalArgument",
          name: "eventContext",
        },
        t = {
          defaultValue: null,
          kind: "LocalArgument",
          name: "paymentAccountID",
        },
        r = {
          defaultValue: null,
          kind: "LocalArgument",
          name: "paymentMethodID",
        },
        o = { defaultValue: null, kind: "LocalArgument", name: "statusEntID" },
        a = [
          {
            kind: "Variable",
            name: "event_context",
            variableName: "eventContext",
          },
          { kind: "Variable", name: "id", variableName: "statusEntID" },
        ],
        i = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "card_status",
          storageKey: null,
        },
        l = [
          {
            kind: "Variable",
            name: "legacy_account_id",
            variableName: "paymentAccountID",
          },
        ],
        s = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "payment_modes",
          storageKey: null,
        },
        u = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "next_bill_date",
          storageKey: null,
        },
        c = [
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "amount_with_offset",
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "currency",
            storageKey: null,
          },
        ],
        d = {
          alias: null,
          args: null,
          concreteType: "TimezoneInfo",
          kind: "LinkedField",
          name: "timezone_info",
          plural: !1,
          selections: [
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "timezone_id",
              storageKey: null,
            },
          ],
          storageKey: null,
        },
        m = [{ kind: "Variable", name: "id", variableName: "paymentMethodID" }],
        p = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "__typename",
          storageKey: null,
        },
        _ = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "last_four_digits",
          storageKey: null,
        },
        f = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "display_name",
          storageKey: null,
        },
        g = {
          kind: "InlineFragment",
          selections: [
            p,
            {
              kind: "InlineFragment",
              selections: [
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "card_association_name",
                  storageKey: null,
                },
                _,
              ],
              type: "ExternalCreditCard",
              abstractKey: null,
            },
            {
              kind: "InlineFragment",
              selections: [
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "bank_name",
                  storageKey: null,
                },
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "bank_account_type",
                  storageKey: null,
                },
                _,
              ],
              type: "DirectDebit",
              abstractKey: null,
            },
            {
              kind: "InlineFragment",
              selections: [
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "email",
                  storageKey: null,
                },
              ],
              type: "PaymentPaypalBillingAgreement",
              abstractKey: null,
            },
            {
              kind: "InlineFragment",
              selections: [
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "legal_entity_name",
                  storageKey: null,
                },
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "partition_from",
                  storageKey: null,
                },
              ],
              type: "IEntEC",
              abstractKey: "__isIEntEC",
            },
            {
              kind: "InlineFragment",
              selections: [
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "stored_balance_type",
                  storageKey: null,
                },
                {
                  alias: null,
                  args: null,
                  concreteType: "CurrencyAmount",
                  kind: "LinkedField",
                  name: "balance_amount",
                  plural: !1,
                  selections: [
                    {
                      alias: null,
                      args: null,
                      kind: "ScalarField",
                      name: "currency_name",
                      storageKey: null,
                    },
                  ],
                  storageKey: null,
                },
              ],
              type: "StoredBalance",
              abstractKey: null,
            },
            {
              kind: "InlineFragment",
              selections: [
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "credential_type",
                  storageKey: null,
                },
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "user_display_name",
                  storageKey: null,
                },
                f,
              ],
              type: "LPMCredential",
              abstractKey: null,
            },
            {
              kind: "InlineFragment",
              selections: [f],
              type: "AltPayCredential",
              abstractKey: null,
            },
          ],
          type: "PaymentCredential",
          abstractKey: "__isPaymentCredential",
        },
        h = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "id",
          storageKey: null,
        };
      return {
        fragment: {
          argumentDefinitions: [e, t, r, o],
          kind: "Fragment",
          metadata: null,
          name: "BillingAwaitCardActivationScreenQuery",
          selections: [
            {
              alias: null,
              args: a,
              concreteType: "XFBBillingAsyncCardStatus",
              kind: "LinkedField",
              name: "billing_async_card_status",
              plural: !1,
              selections: [i],
              storageKey: null,
            },
            {
              alias: null,
              args: l,
              concreteType: null,
              kind: "LinkedField",
              name: "payment_account",
              plural: !1,
              selections: [
                {
                  alias: null,
                  args: null,
                  concreteType: null,
                  kind: "LinkedField",
                  name: "billable_account",
                  plural: !1,
                  selections: [
                    {
                      kind: "InlineFragment",
                      selections: [
                        s,
                        {
                          kind: "InlineDataFragmentSpread",
                          name: "BillingAutomaticBillingStatusUtils_billableAccount",
                          selections: [
                            {
                              kind: "InlineFragment",
                              selections: [
                                u,
                                {
                                  alias: null,
                                  args: null,
                                  concreteType: "CurrencyAmount",
                                  kind: "LinkedField",
                                  name: "billing_threshold_currency_amount",
                                  plural: !1,
                                  selections: [
                                    {
                                      kind: "InlineDataFragmentSpread",
                                      name: "BillingCurrencyAmount_amount",
                                      selections: c,
                                      args: null,
                                      argumentDefinitions: [],
                                    },
                                  ],
                                  storageKey: null,
                                },
                                d,
                              ],
                              type: "BillableAccount",
                              abstractKey: "__isBillableAccount",
                            },
                          ],
                          args: null,
                          argumentDefinitions: [],
                        },
                      ],
                      type: "AdAccount",
                      abstractKey: null,
                    },
                  ],
                  storageKey: null,
                },
              ],
              storageKey: null,
            },
            {
              alias: null,
              args: m,
              concreteType: "ExternalCreditCard",
              kind: "LinkedField",
              name: "credit_card",
              plural: !1,
              selections: [
                {
                  kind: "InlineDataFragmentSpread",
                  name: "BillingPaymentMethodDisplayUtils_paymentCredential",
                  selections: [g],
                  args: null,
                  argumentDefinitions: [],
                },
              ],
              storageKey: null,
            },
          ],
          type: "Query",
          abstractKey: null,
        },
        kind: "Request",
        operation: {
          argumentDefinitions: [o, t, r, e],
          kind: "Operation",
          name: "BillingAwaitCardActivationScreenQuery",
          selections: [
            {
              alias: null,
              args: a,
              concreteType: "XFBBillingAsyncCardStatus",
              kind: "LinkedField",
              name: "billing_async_card_status",
              plural: !1,
              selections: [i, h],
              storageKey: null,
            },
            {
              alias: null,
              args: l,
              concreteType: null,
              kind: "LinkedField",
              name: "payment_account",
              plural: !1,
              selections: [
                p,
                {
                  alias: null,
                  args: null,
                  concreteType: null,
                  kind: "LinkedField",
                  name: "billable_account",
                  plural: !1,
                  selections: [
                    p,
                    {
                      kind: "InlineFragment",
                      selections: [
                        s,
                        {
                          kind: "InlineFragment",
                          selections: [
                            u,
                            {
                              alias: null,
                              args: null,
                              concreteType: "CurrencyAmount",
                              kind: "LinkedField",
                              name: "billing_threshold_currency_amount",
                              plural: !1,
                              selections: c,
                              storageKey: null,
                            },
                            d,
                          ],
                          type: "BillableAccount",
                          abstractKey: "__isBillableAccount",
                        },
                      ],
                      type: "AdAccount",
                      abstractKey: null,
                    },
                    h,
                  ],
                  storageKey: null,
                },
                h,
              ],
              storageKey: null,
            },
            {
              alias: null,
              args: m,
              concreteType: "ExternalCreditCard",
              kind: "LinkedField",
              name: "credit_card",
              plural: !1,
              selections: [g, h],
              storageKey: null,
            },
          ],
        },
        params: {
          id: n("BillingAwaitCardActivationScreenQuery_facebookRelayOperation"),
          metadata: { live: { polling_interval: 1e3 } },
          name: "BillingAwaitCardActivationScreenQuery",
          operationKind: "query",
          text: null,
        },
      };
    })();
    a.exports = e;
  },
  null,
);
