__d(
  "BillingAddFundsStateMutation.graphql",
  ["BillingAddFundsStateMutation_facebookRelayOperation"],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = (function () {
      var e = {
          defaultValue: null,
          kind: "LocalArgument",
          name: "includeCreateNewFromOldFragment",
        },
        t = { defaultValue: null, kind: "LocalArgument", name: "input" },
        r = [{ kind: "Variable", name: "data", variableName: "input" }],
        o = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "__typename",
          storageKey: null,
        },
        a = {
          kind: "InlineFragment",
          selections: [
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "credential_id",
              storageKey: null,
            },
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "supports_recurring",
              storageKey: null,
            },
          ],
          type: "ExternalCreditCard",
          abstractKey: null,
        },
        i = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "payment_modes",
          storageKey: null,
        },
        l = {
          alias: null,
          args: null,
          concreteType: "BillingAutoReloadInfo",
          kind: "LinkedField",
          name: "auto_reload_info",
          plural: !1,
          selections: [
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "auto_reload_status",
              storageKey: null,
            },
          ],
          storageKey: null,
        },
        s = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "currency",
          storageKey: null,
        },
        u = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "charged_payment_method_id",
          storageKey: null,
        },
        c = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "client_mutation_id",
          storageKey: null,
        },
        d = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "payment_id",
          storageKey: null,
        },
        m = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "result",
          storageKey: null,
        },
        p = {
          alias: null,
          args: null,
          concreteType: "CVCOCredentialRequiredVerificationInfo",
          kind: "LinkedField",
          name: "risk_verification_info",
          plural: !1,
          selections: [
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "use_case",
              storageKey: null,
            },
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "resolvable_type",
              storageKey: null,
            },
          ],
          storageKey: null,
        },
        _ = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "is_cvco_unverifiable",
          storageKey: null,
        },
        f = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "async_payment_status_ent_id",
          storageKey: null,
        },
        g = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "external_uri",
          storageKey: null,
        },
        h = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "needs_await_completion",
          storageKey: null,
        },
        y = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "nonce",
          storageKey: null,
        },
        C = {
          alias: null,
          args: null,
          concreteType: "IframeBrokeredPaymentURLParams",
          kind: "LinkedField",
          name: "params",
          plural: !0,
          selections: [
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "key",
              storageKey: null,
            },
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "value",
              storageKey: null,
            },
          ],
          storageKey: null,
        },
        b = [o, f, g, h, y, C],
        v = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "external_ref_id",
          storageKey: null,
        },
        S = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "india_card_issuer",
          storageKey: null,
        },
        R = [
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "uri",
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "scale",
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "height",
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "width",
            storageKey: null,
          },
        ],
        L = [
          {
            kind: "InlineDataFragmentSpread",
            name: "BillingPaymentIconUtils_data",
            selections: R,
            args: null,
            argumentDefinitions: [],
          },
        ],
        E = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "card_association",
          storageKey: null,
        },
        k = {
          kind: "InlineFragment",
          selections: [f],
          type: "AwaitAsyncPaymentStep",
          abstractKey: null,
        },
        I = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "id",
          storageKey: null,
        };
      return {
        fragment: {
          argumentDefinitions: [e, t],
          kind: "Fragment",
          metadata: null,
          name: "BillingAddFundsStateMutation",
          selections: [
            {
              alias: null,
              args: r,
              concreteType: "BillableAccountPrepayAddFundsResponsePayload",
              kind: "LinkedField",
              name: "billable_account_prepay_add_funds",
              plural: !1,
              selections: [
                o,
                {
                  condition: "includeCreateNewFromOldFragment",
                  kind: "Condition",
                  passingValue: !0,
                  selections: [
                    {
                      alias: null,
                      args: null,
                      concreteType: null,
                      kind: "LinkedField",
                      name: "payment_account",
                      plural: !1,
                      selections: [
                        {
                          alias: null,
                          args: null,
                          concreteType: "PaymentCredentialDetails",
                          kind: "LinkedField",
                          name: "billing_payment_methods",
                          plural: !0,
                          selections: [
                            {
                              alias: null,
                              args: null,
                              concreteType: null,
                              kind: "LinkedField",
                              name: "credential",
                              plural: !1,
                              selections: [a],
                              storageKey: null,
                            },
                          ],
                          storageKey: null,
                        },
                      ],
                      storageKey: null,
                    },
                  ],
                },
                {
                  alias: null,
                  args: null,
                  concreteType: null,
                  kind: "LinkedField",
                  name: "billable_account",
                  plural: !1,
                  selections: [i, l, s],
                  storageKey: null,
                },
                u,
                c,
                d,
                m,
                p,
                _,
                {
                  alias: null,
                  args: null,
                  concreteType: null,
                  kind: "LinkedField",
                  name: "next_action",
                  plural: !1,
                  selections: [
                    o,
                    {
                      kind: "InlineDataFragmentSpread",
                      name: "BillingExternalSitePaymentStepUtils_ExternalSitePaymentStep",
                      selections: [
                        {
                          kind: "InlineFragment",
                          selections: b,
                          type: "ExternalSitePaymentStep",
                          abstractKey: null,
                        },
                      ],
                      args: null,
                      argumentDefinitions: [],
                    },
                    {
                      kind: "InlineDataFragmentSpread",
                      name: "BillingNativeOTPPaymentStepUtils_NativeOTPPaymentStep",
                      selections: [
                        {
                          kind: "InlineFragment",
                          selections: [
                            o,
                            f,
                            v,
                            S,
                            {
                              alias: null,
                              args: null,
                              concreteType: "Image",
                              kind: "LinkedField",
                              name: "india_issuer_icon",
                              plural: !1,
                              selections: L,
                              storageKey: null,
                            },
                            {
                              alias: null,
                              args: null,
                              concreteType: "Image",
                              kind: "LinkedField",
                              name: "card_association_icon",
                              plural: !1,
                              selections: L,
                              storageKey: null,
                            },
                            E,
                            {
                              alias: null,
                              args: null,
                              concreteType: "ExternalSitePaymentStep",
                              kind: "LinkedField",
                              name: "external_otp_webview_fallback",
                              plural: !1,
                              selections: [
                                {
                                  kind: "InlineDataFragmentSpread",
                                  name: "BillingExternalSitePaymentStepUtils_ExternalSitePaymentStep",
                                  selections: b,
                                  args: null,
                                  argumentDefinitions: [],
                                },
                              ],
                              storageKey: null,
                            },
                          ],
                          type: "NativeOTPPaymentStep",
                          abstractKey: null,
                        },
                      ],
                      args: null,
                      argumentDefinitions: [],
                    },
                    k,
                  ],
                  storageKey: null,
                },
              ],
              storageKey: null,
            },
          ],
          type: "Mutation",
          abstractKey: null,
        },
        kind: "Request",
        operation: {
          argumentDefinitions: [t, e],
          kind: "Operation",
          name: "BillingAddFundsStateMutation",
          selections: [
            {
              alias: null,
              args: r,
              concreteType: "BillableAccountPrepayAddFundsResponsePayload",
              kind: "LinkedField",
              name: "billable_account_prepay_add_funds",
              plural: !1,
              selections: [
                o,
                {
                  alias: null,
                  args: null,
                  concreteType: null,
                  kind: "LinkedField",
                  name: "billable_account",
                  plural: !1,
                  selections: [o, i, l, s, I],
                  storageKey: null,
                },
                u,
                c,
                d,
                m,
                p,
                _,
                {
                  alias: null,
                  args: null,
                  concreteType: null,
                  kind: "LinkedField",
                  name: "next_action",
                  plural: !1,
                  selections: [
                    o,
                    {
                      kind: "InlineFragment",
                      selections: [f, g, h, y, C],
                      type: "ExternalSitePaymentStep",
                      abstractKey: null,
                    },
                    {
                      kind: "InlineFragment",
                      selections: [
                        f,
                        v,
                        S,
                        {
                          alias: null,
                          args: null,
                          concreteType: "Image",
                          kind: "LinkedField",
                          name: "india_issuer_icon",
                          plural: !1,
                          selections: R,
                          storageKey: null,
                        },
                        {
                          alias: null,
                          args: null,
                          concreteType: "Image",
                          kind: "LinkedField",
                          name: "card_association_icon",
                          plural: !1,
                          selections: R,
                          storageKey: null,
                        },
                        E,
                        {
                          alias: null,
                          args: null,
                          concreteType: "ExternalSitePaymentStep",
                          kind: "LinkedField",
                          name: "external_otp_webview_fallback",
                          plural: !1,
                          selections: b,
                          storageKey: null,
                        },
                      ],
                      type: "NativeOTPPaymentStep",
                      abstractKey: null,
                    },
                    k,
                  ],
                  storageKey: null,
                },
                {
                  condition: "includeCreateNewFromOldFragment",
                  kind: "Condition",
                  passingValue: !0,
                  selections: [
                    {
                      alias: null,
                      args: null,
                      concreteType: null,
                      kind: "LinkedField",
                      name: "payment_account",
                      plural: !1,
                      selections: [
                        o,
                        {
                          alias: null,
                          args: null,
                          concreteType: "PaymentCredentialDetails",
                          kind: "LinkedField",
                          name: "billing_payment_methods",
                          plural: !0,
                          selections: [
                            {
                              alias: null,
                              args: null,
                              concreteType: null,
                              kind: "LinkedField",
                              name: "credential",
                              plural: !1,
                              selections: [o, a, I],
                              storageKey: null,
                            },
                          ],
                          storageKey: null,
                        },
                        I,
                      ],
                      storageKey: null,
                    },
                  ],
                },
              ],
              storageKey: null,
            },
          ],
        },
        params: {
          id: n("BillingAddFundsStateMutation_facebookRelayOperation"),
          metadata: {},
          name: "BillingAddFundsStateMutation",
          operationKind: "mutation",
          text: null,
        },
      };
    })();
    a.exports = e;
  },
  null,
);
