__d(
  "CatalogCapability",
  [],
  function (t, n, r, o, a, i) {
    var e = Object.freeze({
      B2C_MARKETPLACE: "b2c_marketplace",
      BUSINESS_INBOX_IN_MESSENGER: "business_inbox_in_messenger",
      BIZ_MSG_AI_AGENT: "biz_msg_ai_agent",
      C2C_MARKETPLACE: "c2c_marketplace",
      CPAS_PARENT_CATALOG: "cpas_parent_catalog",
      DAILY_DEALS: "daily_deals",
      DAILY_DEALS_LEGACY: "daily_deals_legacy",
      IG_ONSITE_SHOPPING: "ig_onsite_shopping",
      IG_PRODUCT_TAGGING: "ig_product_tagging",
      MARKETPLACE: "marketplace",
      MARKETPLACE_ADS_DEPRECATED: "marketplace_ads_deprecated",
      MARKETPLACE_MOTORS: "marketplace_motors",
      MARKETPLACE_SHOPS: "marketplace_shops",
      MINI_SHOPS: "mini_shops",
      OFFLINE_CONVERSIONS: "offline_conversions",
      SHOPS: "shops",
      UNIVERSAL_CHECKOUT: "universal_checkout",
      WHATSAPP: "whatsapp",
      NEIGHBORHOODS: "neighborhoods",
      DA: "da",
      TEST_CAPABILITY: "test_capability",
      GROUPS: "groups",
      PROFILE: "profile",
      SERVICE: "service",
      US_MARKETPLACE: "us_marketplace",
      EVENT: "event",
      BUY_ON_FACEBOOK: "buy_on_facebook",
      EVENT_DEPRECATED: "EVENT",
      MARKETPLACE_HOME_SALES: "marketplace_home_sales",
      MARKETPLACE_HOME_RENTALS: "marketplace_home_rentals",
      LDP: "ldp",
      WHATSAPP_MARKETING_MESSAGE: "whatsapp_marketing_message",
    });
    i.default = e;
  },
  66,
);
