__d(
  "CDSStyleXDefaultTheme",
  [],
  function (t, n, r, o, a, i) {
    a.exports = {
      accent: "rgb(28,43,51)",
      "alert-banner-corner-radius": "8px",
      "always-black": "black",
      "always-dark-gradient": "linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0.6))",
      "always-dark-overlay": "rgba(0, 0, 0, 0.4)",
      "always-gray-40": "#65676B",
      "always-gray-75": "#BCC0C4",
      "always-gray-95": "#F0F2F5",
      "always-light-overlay": "rgba(255, 255, 255, 0.4)",
      "always-white": "rgb(255,255,255)",
      "attachment-footer-background": "rgba(28,43,51,0.10)",
      "background-deemphasized": "rgb(241,244,247)",
      "badge-background-color-blue": "var(--accent)",
      "badge-background-color-dark-gray": "var(--secondary-icon)",
      "badge-background-color-gray": "var(--disabled-icon)",
      "badge-background-color-green": "var(--positive)",
      "badge-background-color-light-blue": "var(--highlight-bg)",
      "badge-background-color-red": "var(--notification-badge)",
      "badge-background-color-yellow": "var(--base-lemon)",
      "base-blue": "#1877F2",
      "base-cherry": "#F3425F",
      "base-grape": "#9360F7",
      "base-lemon": "#F7B928",
      "base-lime": "#45BD62",
      "base-pink": "#FF66BF",
      "base-seafoam": "#54C7EC",
      "base-teal": "#2ABBA7",
      "base-tomato": "#FB724B",
      "blue-link": "rgb(0,100,224)",
      "blue-primary": "rgb(0,136,244)",
      "blue-secondary": "rgb(4,59,114)",
      "blue-tertiary": "rgb(235,245,255)",
      "blueprint-button-height-large": "48px",
      "blueprint-button-height-medium": "40px",
      "border-focused": "#63788A",
      "button-corner-radius": "4px",
      "button-corner-radius-large": "12px",
      "button-corner-radius-medium": "10px",
      "button-height-large": "52px",
      "button-height-medium": "36px",
      "button-icon-padding-large": "16px",
      "button-icon-padding-medium": "16px",
      "button-inner-icon-spacing-large": "3px",
      "button-inner-icon-spacing-medium": "3px",
      "button-padding-horizontal-large": "16px",
      "button-padding-horizontal-medium": "16px",
      "button-padding-icon-only": "16px",
      "card-background": "rgb(255,255,255)",
      "card-background-flat": "rgb(255,255,255)",
      "card-box-shadow":
        "0 8px 20px 0  var(--shadow-2), 0 2px 4px 0 var(--shadow-1)",
      "card-corner-radius": "4px",
      "card-padding-horizontal": "10px",
      "card-padding-vertical": "20px",
      "chartreuse-primary": "rgb(106,147,22)",
      "chartreuse-secondary": "rgb(50,65,19)",
      "chartreuse-tertiary": "rgb(226,255,152)",
      "chat-bubble-border-radius": "18px",
      "chat-bubble-emphasis-ring-after": "black",
      "chat-bubble-emphasis-ring-before": "white",
      "chat-bubble-padding-horizontal": "12px",
      "chat-bubble-padding-vertical": "8px",
      "chat-incoming-message-bubble-background-color": "#F0F0F0",
      "chat-outgoing-message-bubble-background-color": "var(--accent)",
      "chat-replied-message-background-color": "rgba(0, 0, 0, 0.03)",
      "chat-text-blockquote-color-background-line": "rgba(0, 0, 0, 0.12)",
      "chat-text-blockquote-color-text-primary-media":
        "rgba(255, 255, 255, 0.7)",
      "chip-corner-radius": "4px",
      "comment-background": "rgba(28,43,51,0.10)",
      "comment-bubble": "18px",
      "comment-footer-background": "#F6F9FA",
      "cyan-primary": "rgb(0,142,213)",
      "cyan-secondary": "rgb(15,63,93)",
      "cyan-tertiary": "rgb(231,245,255)",
      "dataviz-blue-primary": "#1D85FC",
      "dataviz-blue-secondary": "#043B72",
      "dataviz-orange": "#D06C14",
      "dataviz-primary-1": "rgb(0,174,143)",
      "dataviz-primary-2": "rgb(156,219,255)",
      "dataviz-primary-3": "rgb(73,156,255)",
      "dataviz-secondary-1": "rgb(83,78,191)",
      "dataviz-secondary-2": "rgb(103,96,228)",
      "dataviz-secondary-3": "rgb(119,45,88)",
      "dataviz-supplementary-1": "rgb(253,91,67)",
      "dataviz-supplementary-2": "rgb(161,132,0)",
      "dataviz-supplementary-3": "rgb(36,131,44)",
      "dataviz-supplementary-4": "rgb(51,51,52)",
      "dialog-anchor-vertical-padding": "32px",
      "dialog-corner-radius": "4px",
      "dialog-size-medium-width": "100%",
      "dialog-size-small-width": "100%",
      "disabled-button-background": "#E4E6EB",
      "disabled-button-text": "#BCC0C4",
      "disabled-icon": "rgba(28,43,51,0.25)",
      "disabled-text": "rgba(28,43,51,0.25)",
      divider: "rgb(222,227,233)",
      "divider-on-color": "#CED0D4",
      "emphasized-card-background-blue-comet":
        "linear-gradient(rgb(192,223,255),rgb(210,232,255))",
      "emphasized-card-background-green-comet":
        "linear-gradient(rgb(185,245,170),rgb(205,250,195))",
      "emphasized-card-background-purple-comet":
        "linear-gradient(rgb(210, 210, 255),rgb(225,225,253))",
      "emphasized-card-background-teal-comet":
        "linear-gradient(rgb(165,240,230),rgb(195,245,240))",
      "event-date": "rgb(220,55,60)",
      "fb-logo": "#0866FF",
      "fb-wordmark": "#0866FF",
      "fds-animation-enter-exit-in": "cubic-bezier(0.14, 1, 0.34, 1)",
      "fds-animation-enter-exit-out": "cubic-bezier(0.45, 0.1, 0.2, 1)",
      "fds-animation-expand-collapse-in": "cubic-bezier(0.17, 0.17, 0, 1)",
      "fds-animation-expand-collapse-out": "cubic-bezier(0.17, 0.17, 0, 1)",
      "fds-animation-fade-in": "cubic-bezier(0, 0, 1, 1)",
      "fds-animation-fade-out": "cubic-bezier(0, 0, 1, 1)",
      "fds-animation-move-in": "cubic-bezier(0.17, 0.17, 0, 1)",
      "fds-animation-move-out": "cubic-bezier(0.17, 0.17, 0, 1)",
      "fds-animation-passive-move-in": "cubic-bezier(0.5, 0, 0.1, 1)",
      "fds-animation-passive-move-out": "cubic-bezier(0.5, 0, 0.1, 1)",
      "fds-animation-quick-move-in": "cubic-bezier(0.1, 0.9, 0.2, 1)",
      "fds-animation-quick-move-out": "cubic-bezier(0.1, 0.9, 0.2, 1)",
      "fds-animation-swap-shuffle-in": "cubic-bezier(0.14, 1, 0.34, 1)",
      "fds-animation-swap-shuffle-out": "cubic-bezier(0.45, 0.1, 0.2, 1)",
      "fds-black": "#000000",
      "fds-black-alpha-05": "rgba(0, 0, 0, 0.05)",
      "fds-black-alpha-10": "rgba(0, 0, 0, 0.1)",
      "fds-black-alpha-15": "rgba(0, 0, 0, 0.15)",
      "fds-black-alpha-20": "rgba(0, 0, 0, 0.2)",
      "fds-black-alpha-30": "rgba(0, 0, 0, 0.3)",
      "fds-black-alpha-40": "rgba(0, 0, 0, 0.4)",
      "fds-black-alpha-50": "rgba(0, 0, 0, 0.5)",
      "fds-black-alpha-60": "rgba(0, 0, 0, 0.6)",
      "fds-black-alpha-80": "rgba(0, 0, 0, 0.8)",
      "fds-blue-05": "#ECF3FF",
      "fds-blue-30": "#AAC9FF",
      "fds-blue-40": "#77A7FF",
      "fds-blue-60": "#1877F2",
      "fds-blue-70": "#2851A3",
      "fds-blue-80": "#1D3C78",
      "fds-button-text": "#444950",
      "fds-comment-background": "#F2F3F5",
      "fds-dark-mode-gray-100": "#1C1C1C",
      "fds-dark-mode-gray-35": "#CCCCCC",
      "fds-dark-mode-gray-50": "#828282",
      "fds-dark-mode-gray-70": "#4A4A4A",
      "fds-dark-mode-gray-80": "#373737",
      "fds-dark-mode-gray-90": "#282828",
      "fds-duration-extra-extra-short-in": "100ms",
      "fds-duration-extra-extra-short-out": "100ms",
      "fds-duration-extra-long-in": "1000ms",
      "fds-duration-extra-long-out": "1000ms",
      "fds-duration-extra-short-in": "200ms",
      "fds-duration-extra-short-out": "150ms",
      "fds-duration-long-in": "500ms",
      "fds-duration-long-out": "350ms",
      "fds-duration-medium-in": "400ms",
      "fds-duration-medium-out": "350ms",
      "fds-duration-none": "0ms",
      "fds-duration-short-in": "280ms",
      "fds-duration-short-out": "200ms",
      "fds-fast": "200ms",
      "fds-gray-00": "#F5F6F7",
      "fds-gray-05": "#F2F3F5",
      "fds-gray-10": "#EBEDF0",
      "fds-gray-100": "#1C1E21",
      "fds-gray-20": "#DADDE1",
      "fds-gray-25": "#CCD0D5",
      "fds-gray-30": "#BEC3C9",
      "fds-gray-45": "#8D949E",
      "fds-gray-70": "#606770",
      "fds-gray-80": "#444950",
      "fds-gray-90": "#303338",
      "fds-green-55": "#00A400",
      "fds-green-60": "#31A73B",
      "fds-green-65": "#51CE70",
      "fds-highlight": "#3578E5",
      "fds-highlight-cell-background": "#ECF3FF",
      "fds-primary-icon": "#1C1E21",
      "fds-primary-text": "#1C1E21",
      "fds-red-55": "#FA383E",
      "fds-slow": "400ms",
      "fds-soft": "cubic-bezier(.08,.52,.52,1)",
      "fds-spectrum-aluminum-tint-70": "#E4F0F6",
      "fds-spectrum-blue-gray-tint-70": "#CFD1D5",
      "fds-spectrum-cherry": "#F35369",
      "fds-spectrum-cherry-tint-70": "#FBCCD2",
      "fds-spectrum-grape-tint-70": "#DDD5F0",
      "fds-spectrum-grape-tint-90": "#F4F1FA",
      "fds-spectrum-lemon-dark-1": "#F5C33B",
      "fds-spectrum-lemon-tint-70": "#FEF2D1",
      "fds-spectrum-lime": "#A3CE71",
      "fds-spectrum-lime-tint-70": "#E4F0D5",
      "fds-spectrum-orange-tint-70": "#FCDEC5",
      "fds-spectrum-orange-tint-90": "#FEF4EC",
      "fds-spectrum-seafoam-tint-70": "#CAEEF9",
      "fds-spectrum-slate-dark-2": "#89A1AC",
      "fds-spectrum-slate-tint-70": "#EAEFF2",
      "fds-spectrum-teal": "#6BCEBB",
      "fds-spectrum-teal-dark-1": "#4DBBA6",
      "fds-spectrum-teal-dark-2": "#31A38D",
      "fds-spectrum-teal-tint-70": "#D2F0EA",
      "fds-spectrum-teal-tint-90": "#F0FAF8",
      "fds-spectrum-tomato": "#FB724B",
      "fds-spectrum-tomato-tint-30": "#F38E7B",
      "fds-spectrum-tomato-tint-90": "#FDEFED",
      "fds-strong": "cubic-bezier(.12,.8,.32,1)",
      "fds-unified-blue-35": "#1455B0",
      "fds-unified-gray-20": "#323436",
      "fds-white": "#FFFFFF",
      "fds-white-alpha-05": "rgba(255, 255, 255, 0.05)",
      "fds-white-alpha-10": "rgba(255, 255, 255, 0.1)",
      "fds-white-alpha-20": "rgba(255, 255, 255, 0.2)",
      "fds-white-alpha-30": "rgba(255, 255, 255, 0.3)",
      "fds-white-alpha-40": "rgba(255, 255, 255, 0.4)",
      "fds-white-alpha-50": "rgba(255, 255, 255, 0.5)",
      "fds-white-alpha-60": "rgba(255, 255, 255, 0.6)",
      "fds-white-alpha-80": "rgba(255, 255, 255, 0.8)",
      "fds-yellow-20": "#FFBA00",
      "filter-accent":
        "invert(39%) sepia(57%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(147.75%) hue-rotate(202deg) brightness(97%) contrast(96%)",
      "filter-always-white": "invert(100%)",
      "filter-blue-link-icon":
        "invert(30%) sepia(98%) saturate(200%) saturate(200%) saturate(200%) saturate(166.5%) hue-rotate(192deg) brightness(91%) contrast(101%)",
      "filter-disabled-icon":
        "invert(80%) sepia(6%) saturate(200%) saturate(120%) hue-rotate(173deg) brightness(98%) contrast(89%)",
      "filter-negative":
        "invert(25%) sepia(33%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(110%) hue-rotate(345deg) brightness(132%) contrast(96%)",
      "filter-placeholder-icon":
        "invert(59%) sepia(11%) saturate(200%) saturate(135%) hue-rotate(176deg) brightness(96%) contrast(94%)",
      "filter-positive":
        "invert(37%) sepia(61%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(115%) hue-rotate(91deg) brightness(97%) contrast(105%)",
      "filter-primary-accent":
        "invert(39%) sepia(57%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(147.75%) hue-rotate(202deg) brightness(97%) contrast(96%)",
      "filter-primary-deemphasized-button-icon":
        "invert(28%) sepia(100%) saturate(6042%) hue-rotate(202deg) brightness(96%) contrast(101%)",
      "filter-primary-icon":
        "invert(8%) sepia(10%) saturate(200%) saturate(200%) saturate(166%) hue-rotate(177deg) brightness(104%) contrast(91%)",
      "filter-secondary-button-icon-on-media": "invert(100%)",
      "filter-secondary-icon":
        "invert(39%) sepia(21%) saturate(200%) saturate(109.5%) hue-rotate(174deg) brightness(94%) contrast(86%)",
      "filter-warning-icon":
        "invert(77%) sepia(29%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(200%) saturate(128%) hue-rotate(359deg) brightness(102%) contrast(107%)",
      "focus-ring-blue": "#1877F2",
      "focus-ring-outline-forced-colors": "2px auto transparent !important",
      "focus-ring-outline-link": "2px auto var(--focus-ring-blue)",
      "focus-ring-shadow-default":
        "0 0 0 2px var(--always-white), 0 0 0 4px var(--focus-ring-blue)",
      "focus-ring-shadow-inset":
        "0 0 0 2px var(--focus-ring-blue) inset, 0 0 0 4px var(--always-white) inset",
      "font-family-apple":
        "system-ui, -apple-system, BlinkMacSystemFont, '.SFNSText-Regular', sans-serif",
      "font-family-code": "ui-monospace, Menlo, Consolas, Monaco, monospace",
      "font-family-default": "Helvetica, Arial, sans-serif",
      "font-family-segoe":
        "Segoe UI Historic, Segoe UI, Helvetica, Arial, sans-serif",
      "font-family-system-fds":
        "system-ui, -apple-system, BlinkMacSystemFont, Segoe UI Historic, Segoe UI, Helvetica, Arial, sans-serif",
      "fuschia-primary": "rgb(250,45,138)",
      "fuschia-secondary": "rgb(118,14,62)",
      "fuschia-tertiary": "rgb(255,241,246)",
      "glimmer-animation-direction": "alternate",
      "glimmer-animation-duration": "1000ms",
      "glimmer-animation-timing-function": "steps(10, end)",
      "glimmer-base-opaque": "#979A9F",
      "glimmer-corner-radius": "4px",
      "glimmer-high-contrast-base-opaque": "#65686C",
      "glimmer-opacity-high-contrast-max": "1",
      "glimmer-opacity-high-contrast-min": "0.08",
      "glimmer-opacity-max": "1",
      "glimmer-opacity-min": "0.25",
      "glimmer-spinner-icon": "#65676B",
      "global-panel-width": "0px",
      "global-panel-width-expanded": "0px",
      "green-primary": "rgb(43,154,53)",
      "green-secondary": "rgb(26,68,27)",
      "green-tertiary": "rgb(227,250,224)",
      "header-height": "0px",
      "hero-banner-background": "#FFFFFF",
      "highlight-bg": "#E7F3FF",
      "hosted-view-selected-state": "rgb(52,72,84)",
      "hover-overlay": "rgba(0, 0, 0, 0.05)",
      "image-corner-radius": "4px",
      "infochip-medium-radius": "12px",
      "input-background": "rgb(255,255,255)",
      "input-background-active":
        "hsla(var(--accent-h), var(--accent-s), var(--accent-l), 0.05)",
      "input-background-disabled": "#F0F2F5",
      "input-background-error-active":
        "hsla(var(--negative-h), var(--negative-s), var(--negative-l), 0.05)",
      "input-background-error-hover":
        "hsla(var(--negative-h), var(--negative-s), var(--negative-l), 0.05)",
      "input-background-hover": "var(--input-background)",
      "input-background-warn-active":
        "hsla(var(--warning-h), var(--warning-s), var(--warning-l), 0.05)",
      "input-background-warn-hover":
        "hsla(var(--warning-h), var(--warning-s), var(--warning-l), 0.05)",
      "input-border-color": "#CED0D4",
      "input-border-color-hover": "var(--placeholder-text)",
      "input-border-width": "1px",
      "input-corner-radius": "4px",
      "input-label-color-disabled": "var(--disabled-text)",
      "input-label-color-error": "var(--negative)",
      "input-label-color-highlighted": "hsl(214, 89%, 52%)",
      "input-label-color-inside": "var(--secondary-text)",
      "inverse-text": "var(--always-white)",
      "list-cell-chevron": "rgb(99,120,138)",
      "list-cell-corner-radius": "4px",
      "list-cell-min-height": "52px",
      "list-cell-padding-vertical": "20px",
      "list-cell-padding-vertical-with-addon": "14px",
      "magenta-primary": "rgb(215,77,204)",
      "magenta-secondary": "rgb(96,36,91)",
      "magenta-tertiary": "rgb(255,239,254)",
      "media-hover": "rgba(68, 73, 80, 0.15)",
      "media-inner-border": "rgba(28,43,51,0.10)",
      "media-outer-border": "#FFFFFF",
      "media-pressed": "rgba(28,43,51,0.30)",
      "menu-base-list-item-padding-horizontal": "8px",
      "menu-base-list-item-padding-vertical": "12px",
      "menu-base-size-full-margin-end": "48px",
      "menu-item-base-margin-horizontal": "8px",
      "menu-item-base-margin-vertical": "0px",
      "menu-item-base-overlay-radius": "4px",
      "menu-item-base-padding-horizontal": "8px",
      "menu-item-base-padding-vertical": "12px",
      "menu-item-base-with-icon-padding-horizontal":
        "var(--menu-item-base-padding-horizontal)",
      "messenger-application-max-width": "2560px",
      "messenger-card-background": "#FFFFFF",
      "messenger-card-box-shadow": "0px 1px 2px 0px #0000001A",
      "messenger-card-corner-radius": "8px",
      "messenger-card-max-width": "480px",
      "messenger-card-min-width": "300px",
      "messenger-card-spacing": "16px",
      "messenger-reply-background": "#F0F2F5",
      "messenger-sidebar-collapsed-width": "44px",
      "messenger-sidebar-expanded-width": "240px",
      "mwp-header-background-color": "var(--messenger-card-background)",
      "mwp-header-button-color": "var(--accent)",
      "mwp-message-row-background": "var(--messenger-card-background)",
      "nav-bar-background": "rgba(0,0,0,0.00)",
      "nav-bar-background-gradient":
        "linear-gradient(to top, #FFFFFF, rgba(255,255,255.9), rgba(255,255,255,.7), rgba(255,255,255,.4), rgba(255,255,255,0))",
      "nav-bar-background-gradient-wash":
        "linear-gradient(to top, #F0F2F5, rgba(240,242,245.9), rgba(240,242,245,.7), rgba(240,242,245,.4), rgba(240,242,245,0))",
      "nav-list-cell-corner-radius": "4px",
      "nav-list-cell-min-height": "0px",
      "nav-list-cell-padding-vertical": "16px",
      "nav-list-cell-padding-vertical-with-addon": "16px",
      negative: "rgb(220,55,60)",
      "negative-background": "hsl(350, 87%, 55%, 20%)",
      "new-notification-background": "rgba(28,43,51,0.10)",
      "non-media-pressed": "rgba(28,43,51,0.15)",
      "non-media-pressed-on-dark": "rgba(255,255,255,0.30)",
      "notification-badge": "rgb(220,55,60)",
      "nux-card-body-padding-end": "24px",
      "orange-primary": "rgb(208,108,20)",
      "orange-secondary": "rgb(94,49,14)",
      "orange-tertiary": "rgb(255,241,239)",
      "overlay-alpha-80": "rgba(28,43,51,0.80)",
      "overlay-on-media": "rgba(28,43,51,0.70)",
      "page-footer-padding-vertical": "28px",
      "placeholder-icon": "rgba(133,149,164)",
      "placeholder-image": "rgb(222, 227, 233)",
      "placeholder-text": "rgba(28,43,51,0.50)",
      "placeholder-text-on-media": "rgba(255,255,255,0.45)",
      "popover-background": "rgb(255,255,255)",
      "popover-border-color": "transparent",
      "popover-border-style": "none",
      "popover-border-width": "0px",
      "popover-card-background": "var(--card-background)",
      positive: "rgb(0,126,89)",
      "positive-background": "#DEEFE1",
      "press-overlay": "rgba(0, 0, 0, 0.10)",
      "primary-button-background": "rgb(0,100,224)",
      "primary-button-icon": "rgb(255,255,255)",
      "primary-button-pressed": "#77A7FF",
      "primary-button-text": "rgb(255,255,255)",
      "primary-deemphasized-button-background": "rgba(0,0,0,0.00)",
      "primary-deemphasized-button-pressed": "rgb(0,0,0,.05)",
      "primary-deemphasized-button-pressed-overlay": "rgb(0,0,0,.1)",
      "primary-deemphasized-button-text": "rgb(255,255,255)",
      "primary-icon": "rgb(28,43,51)",
      "primary-text": "rgb(28,43,51)",
      "primary-text-on-media": "rgb(255,255,255)",
      "primary-web-focus-indicator": "#D24294",
      "progress-ring-blue-background": "rgba(24, 119, 242, 0.2)",
      "progress-ring-blue-foreground": "hsl(214, 89%, 52%)",
      "progress-ring-disabled-background": "rgba(190,195,201, 0.2)",
      "progress-ring-disabled-foreground": "#BEC3C9",
      "progress-ring-neutral-background": "rgba(0, 0, 0, 0.2)",
      "progress-ring-neutral-foreground": "#000000",
      "progress-ring-on-media-background": "rgba(255,255,255,0.20)",
      "progress-ring-on-media-foreground": "rgb(255,255,255)",
      "purple-primary": "rgb(125,116,255)",
      "purple-secondary": "rgb(55,50,121)",
      "purple-tertiary": "rgb(245,241,255)",
      "radio-border-color": "var(--primary-icon)",
      "radio-border-color-disabled": "var(--disabled-button-background)",
      "radio-border-color-selected": "var(--accent)",
      "radio-border-width": "2px",
      "radio-checked-icon-color": "var(--accent)",
      "radio-checked-icon-color-disabled": "var(--disabled-button-background)",
      "radio-checked-icon-size-large": "12px",
      "radio-checked-icon-size-medium": "12px",
      "radio-size-large": "24px",
      "radio-size-medium": "20px",
      "rating-star-active": "#EB660D",
      "red-primary": "rgb(251,60,68)",
      "red-secondary": "rgb(118,22,27)",
      "red-tertiary": "rgb(255,241,239)",
      "scroll-shadow": "0 0 16px 0 rgba(52,72,84,0.05)",
      "scroll-thumb": "#BCC0C4",
      "search-input-background": "rgba(0, 0, 0, 0.04)",
      "secondary-button-background": "rgba(0,0,0,0.00)",
      "secondary-button-background-floating": "#ffffff",
      "secondary-button-background-on-dark": "rgba(0, 0, 0, 0.4)",
      "secondary-button-pressed": "rgba(0,0,0,0.00)",
      "secondary-button-stroke": "rgb(203,210,217)",
      "secondary-button-text": "rgb(28,43,51)",
      "secondary-emphasized-button-stroke": "rgb(0,100,224)",
      "secondary-icon": "rgb(99,120,138)",
      "secondary-text": "rgb(99,120,138)",
      "secondary-text-on-media": "rgba(255,255,255,0.70)",
      "section-header-addOnEnd-button-padding-horizontal": "0px",
      "section-header-addOnEnd-button-padding-vertical": "0px",
      "section-header-addOnEnd-margin-horizontal": "8px",
      "section-header-addOnStart-margin-horizontal": "12px",
      "section-header-padding-vertical": "16px",
      "section-header-subtitle-margin-vertical": "14px",
      "section-header-subtitle-with-addOnEnd-margin-vertical": "6px",
      "section-header-text": "#4B4C4F",
      "separator-menu-item-margin-horizontal": "16px",
      "separator-menu-item-margin-vertical": "4px",
      "shadow-1": "rgba(0, 0, 0, 0.1)",
      "shadow-2": "rgba(0, 0, 0, 0.2)",
      "shadow-5": "rgba(0, 0, 0, 0.5)",
      "shadow-8": "rgba(0, 0, 0, 0.8)",
      "shadow-base": "0 1px 2px var(--shadow-2)",
      "shadow-elevated":
        "0 8px 20px 0 rgba(0, 0, 0, 0.2), 0 2px 4px 0 rgba(0, 0, 0, 0.1)",
      "shadow-emphasis": "0 2px 12px var(--shadow-2)",
      "shadow-inset": "rgba(255, 255, 255, 0.5)",
      "shadow-on-media": "0px 0px 1px rgba(0, 0, 0, 0.62)",
      "shadow-persistent": "0px 0px 12px rgba(52, 72, 84, 0.05)",
      "shadow-primary": "0px 5px 12px rgba(52, 72, 84, 0.2)",
      "shadow-responsive": "0px 8px 16px 0px rgba(0, 0, 0, 0.1)",
      "stepper-active": "#344854",
      "stepper-inactive": "rgba(52, 72, 84, 0.4)",
      "surface-background": "rgb(255,255,255)",
      "switch-active": "hsl(214, 89%, 52%)",
      "switch-inactive": "#CED0D4",
      "switch-unchecked-background-color": "#8F9297",
      "tab-height": "60px",
      "tab-icon-padding-end": "0px",
      "tab-text-icon-gap": "4px",
      "tab-underline-color": "transparent",
      "tab-underline-height": "3px",
      "teal-primary": "rgb(0,152,124)",
      "teal-secondary": "rgb(10,68,56)",
      "teal-tertiary": "rgb(227,247,241)",
      "text-badge-attention-background": "hsl(40, 89%, 52%)",
      "text-badge-corner-radius": "4px",
      "text-badge-critical-background": "#e41e3f",
      "text-badge-info-background": "hsl(214, 89%, 52%)",
      "text-badge-padding-horizontal": "6px",
      "text-badge-padding-vertical": "6px",
      "text-badge-success-background": "#31A24C",
      "text-highlight": "rgb(0,97,160)",
      "text-input-bar-background": "#F0F2F5",
      "text-input-caption-margin-top": "10px",
      "text-input-field-font-family": "Placeholder Font",
      "text-input-field-font-size": "1rem",
      "text-input-field-font-stretch": "initial",
      "text-input-field-font-weight": "500",
      "text-input-field-line-height": "1.2941",
      "text-input-label-font-family": "Placeholder Font",
      "text-input-label-font-size": "17px",
      "text-input-label-font-size-scale-multiplier": "0.75",
      "text-input-label-font-stretch": "initial",
      "text-input-label-font-weight": "400",
      "text-input-label-line-height": "1.2941",
      "text-input-multi-padding-between-text-scrollbar": "20px",
      "text-input-multi-padding-scrollbar": "16px",
      "text-input-outside-label": "#000000",
      "text-input-padding-vertical": "12px",
      "toast-addon-padding-horizontal": "6px",
      "toast-addon-padding-vertical": "0px",
      "toast-background": "rgb(255,255,255)",
      "toast-border-color": "transparent",
      "toast-border-style": "none",
      "toast-border-width": "0px",
      "toast-container-max-width": "100%",
      "toast-container-min-width": "320px",
      "toast-container-padding-horizontal": "14px",
      "toast-container-padding-vertical": "16px",
      "toast-corner-radius": "8px",
      "toast-text": "#1C2B33",
      "toast-text-link": "#4599FF",
      "toaster-view-max-width": "328px",
      "toggle-active-background": "rgb(28,43,51)",
      "toggle-active-icon": "rgb(255,255,255)",
      "toggle-active-text": "rgb(255,255,255)",
      "toggle-button-active-background": "#E7F3FF",
      "tooltip-background": "rgb(52,72,84)",
      "tooltip-box-shadow": "none",
      "tooltip-corner-radius": "8px",
      "typeahead-list-outer-padding-vertical": "8px",
      warning: "rgb(210,120,5)",
      wash: "#E4E6EB",
      "web-wash": "#F0F2F5",
      "yellow-primary": "rgb(161,132,0)",
      "yellow-secondary": "rgb(72,59,12)",
      "yellow-tertiary": "rgb(255,246,161)",
    };
  },
  null,
);
