__d(
  "CDSSpinnerVariants",
  [],
  function (t, n, r, o, a, i, l) {
    "use strict";
    var e = "x1k35ma4-B",
      s = "xz9a51c-B",
      u = "x1bt8ye9-B",
      c = "xaeq8qu-B",
      d = "xbtpni2-B",
      m = {
        blueLink: { stroke: "xw496ev", $$css: !0 },
        circle16: { animationName: "x1koaglw", $$css: !0 },
        circle24: { animationName: "xiepp7r", $$css: !0 },
        circle32: { animationName: "x1pb3rhs", $$css: !0 },
        circle48: { animationName: "x1w90wak", $$css: !0 },
        circle96: { animationName: "x1ubxy3j", $$css: !0 },
        onBlurAdaptiveButton: { stroke: "x1tkxns5", $$css: !0 },
        onBlurDarkButton: { stroke: "x1or3qak", $$css: !0 },
        onBlurLightButton: { stroke: "x1ul8mv4", $$css: !0 },
        onFilledDestructiveButton: { stroke: "x1rro14h", $$css: !0 },
        onGhostPrimaryButton: { stroke: "x1i9sqzd", $$css: !0 },
        onGhostSecondaryButton: { stroke: "x13jkr8g", $$css: !0 },
        onOnColorButton: { stroke: "x1dl6asj", $$css: !0 },
        onOutlineDestructiveButton: { stroke: "xti8gf0", $$css: !0 },
        onOutlinePrimaryButton: { stroke: "x13gce53", $$css: !0 },
        onOutlineSecondaryButton: { stroke: "xcvxvt1", $$css: !0 },
        onTonalDestructiveButton: { stroke: "xxlv1oi", $$css: !0 },
        onTonalPrimaryButton: { stroke: "xsnpeeu", $$css: !0 },
        primary: { stroke: "xn5zopi", $$css: !0 },
        primaryButtonNew: { stroke: "x16v7qao", $$css: !0 },
        primaryFallback: { stroke: "xufi9hs", $$css: !0 },
        primaryOnMediaButton: { stroke: "x2dpgu9", $$css: !0 },
        secondaryButtonNew: { stroke: "x1d3if0e", $$css: !0 },
        secondaryNew: { stroke: "x1d3if0e", $$css: !0 },
        secondaryOnMediaButton: { stroke: "xbwdf2z", $$css: !0 },
        trackCircleOnBlurAdaptiveButton: { stroke: "x1yoowy8", $$css: !0 },
        trackCircleOnBlurDarkButton: { stroke: "x95ynrb", $$css: !0 },
        trackCircleOnBlurLightButton: { stroke: "x9dgqg2", $$css: !0 },
        trackCircleOnFilledDestructiveButton: { stroke: "x1u4sa0r", $$css: !0 },
        trackCircleOnGhostPrimaryButton: { stroke: "x22bik3", $$css: !0 },
        trackCircleOnGhostSecondaryButton: { stroke: "x1uks3ol", $$css: !0 },
        trackCircleOnOnColorButton: { stroke: "x13xl5yv", $$css: !0 },
        trackCircleOnOutlineDestructiveButton: {
          stroke: "x1kcgy8i",
          $$css: !0,
        },
        trackCircleOnOutlinePrimaryButton: { stroke: "xgjeb9d", $$css: !0 },
        trackCircleOnOutlineSecondaryButton: { stroke: "x1yvk0yq", $$css: !0 },
        trackCircleOnTonalDestructiveButton: { stroke: "x14lrwu0", $$css: !0 },
        trackCircleOnTonalPrimaryButton: { stroke: "xvt5mbg", $$css: !0 },
        trackCirclePrimary: { stroke: "xt6f9kv", $$css: !0 },
        trackCirclePrimaryButton: { stroke: "xgtibcu", $$css: !0 },
        trackCirclePrimaryOnMediaButtonLottie: { stroke: "x8ufeyt", $$css: !0 },
        trackCircleSecondary: { stroke: "xi0xo6d", $$css: !0 },
        trackCircleSecondaryButton: { stroke: "x11j5cmb", $$css: !0 },
        trackCircleSecondaryOnMediaButtonLottie: {
          stroke: "xzu3x2x",
          $$css: !0,
        },
      },
      p = { xstyleConfig: { svg: m.blueLink } },
      _ = { xstyleConfig: { svg: m.primary } },
      f = { xstyleConfig: { svg: m.primaryFallback } },
      g = { xstyleConfig: { svg: m.primaryButtonNew } },
      h = { xstyleConfig: { svg: m.primaryOnMediaButton } },
      y = { xstyleConfig: { svg: m.secondaryNew } },
      C = { xstyleConfig: { svg: m.secondaryButtonNew } },
      b = { xstyleConfig: { svg: m.secondaryOnMediaButton } },
      v = { xstyleConfig: { svg: m.onOutlineSecondaryButton } },
      S = { xstyleConfig: { svg: m.onBlurAdaptiveButton } },
      R = { xstyleConfig: { svg: m.onBlurDarkButton } },
      L = { xstyleConfig: { svg: m.onBlurLightButton } },
      E = { xstyleConfig: { svg: m.onOnColorButton } },
      k = { xstyleConfig: { svg: m.onOutlinePrimaryButton } },
      I = { xstyleConfig: { svg: m.onOutlineDestructiveButton } },
      T = { xstyleConfig: { svg: m.onFilledDestructiveButton } },
      D = { xstyleConfig: { svg: m.onTonalDestructiveButton } },
      x = { xstyleConfig: { svg: m.onTonalPrimaryButton } },
      $ = { xstyleConfig: { svg: m.onGhostPrimaryButton } },
      P = { xstyleConfig: { svg: m.onGhostSecondaryButton } },
      N = m.trackCirclePrimary,
      M = m.trackCirclePrimaryButton,
      w = m.trackCircleSecondary,
      A = m.trackCircleSecondaryButton,
      F = m.trackCircleOnBlurAdaptiveButton,
      O = m.trackCircleOnBlurDarkButton,
      B = m.trackCircleOnBlurLightButton,
      W = m.trackCircleOnOnColorButton,
      q = m.trackCircleOnOutlinePrimaryButton,
      U = m.trackCircleOnOutlineDestructiveButton,
      V = m.trackCircleOnFilledDestructiveButton,
      H = m.trackCircleOnTonalDestructiveButton,
      G = m.trackCircleOnTonalPrimaryButton,
      z = m.trackCircleOnOutlineSecondaryButton,
      j = m.trackCircleOnGhostPrimaryButton,
      K = m.trackCircleOnGhostSecondaryButton,
      Q = m.trackCirclePrimaryOnMediaButtonLottie,
      X = m.trackCircleSecondaryOnMediaButtonLottie,
      Y = {
        size: 16,
        strokeWidth: 1.333,
        xstyleConfig: { circle: m.circle16 },
      },
      J = { size: 24, strokeWidth: 2, xstyleConfig: { circle: m.circle24 } },
      Z = { size: 32, strokeWidth: 2.66, xstyleConfig: { circle: m.circle32 } },
      ee = { size: 48, strokeWidth: 4, xstyleConfig: { circle: m.circle48 } },
      te = { size: 96, strokeWidth: 8, xstyleConfig: { circle: m.circle96 } },
      ne = {
        blueLink: p,
        "on-blur-adaptive-button": S,
        "on-blur-dark-button": R,
        "on-blur-light-button": L,
        "on-filled-destructive-button": T,
        "on-ghost-primary-button": $,
        "on-ghost-secondary-button": P,
        "on-on-color-button": E,
        "on-outline-destructive-button": I,
        "on-outline-primary-button": k,
        "on-outline-secondary-button": v,
        "on-tonal-destructive-button": D,
        "on-tonal-primary-button": x,
        primary: _,
        "primary-button": g,
        "primary-fallback": f,
        "primary-on-media-button": h,
        secondary: y,
        "secondary-button": C,
        "secondary-on-media-button": b,
      },
      re = { 16: Y, 24: J, 32: Z, 48: ee, 96: te };
    ((l.blueLinkVariant = p),
      (l.primaryVariant = _),
      (l.primaryFallbackVariant = f),
      (l.primaryButtonVariant = g),
      (l.primaryOnMediaButtonVariant = h),
      (l.secondaryVariant = y),
      (l.secondaryButtonVariant = C),
      (l.secondaryOnMediaButtonVariant = b),
      (l.onOutlineSecondaryButtonVariant = v),
      (l.onBlurAdaptiveButtonVariant = S),
      (l.onBlurDarkButtonVariant = R),
      (l.onBlurLightButtonVariant = L),
      (l.onOnColorButtonVariant = E),
      (l.onOutlinePrimaryButtonVariant = k),
      (l.onOutlineDestructiveButtonVariant = I),
      (l.onFilledDestructiveButtonVariant = T),
      (l.onTonalDestructiveButtonVariant = D),
      (l.onTonalPrimaryButtonVariant = x),
      (l.onGhostPrimaryButtonVariant = $),
      (l.onGhostSecondaryButtonVariant = P),
      (l.trackCirclePrimaryStyle = N),
      (l.trackCirclePrimaryButtonStyle = M),
      (l.trackCircleSecondaryStyle = w),
      (l.trackCircleSecondaryButtonStyle = A),
      (l.trackCircleOnBlurAdaptiveButtonStyle = F),
      (l.trackCircleOnBlurDarkButtonStyle = O),
      (l.trackCircleOnBlurLightButtonStyle = B),
      (l.trackCircleOnOnColorButtonStyle = W),
      (l.trackCircleOnOutlinePrimaryButtonStyle = q),
      (l.trackCircleOnOutlineDestructiveButtonStyle = U),
      (l.trackCircleOnFilledDestructiveButtonStyle = V),
      (l.trackCircleOnTonalDestructiveButtonStyle = H),
      (l.trackCircleOnTonalPrimaryButtonStyle = G),
      (l.trackCircleOnOutlineSecondaryButtonStyle = z),
      (l.trackCircleOnGhostPrimaryButtonStyle = j),
      (l.trackCircleOnGhostSecondaryButtonStyle = K),
      (l.trackCirclePrimaryOnMediaButtonStyle = Q),
      (l.trackCircleSecondaryOnMediaButtonStyle = X),
      (l.size16Variant = Y),
      (l.size24Variant = J),
      (l.size32Variant = Z),
      (l.size48Variant = ee),
      (l.size96Variant = te),
      (l.typeVariants = ne),
      (l.sizeVariants = re));
  },
  98,
);
