__d(
  "CDSSpinnerVariants",
  ["MetaConfig"],
  function (t, n, r, o, a, i, l) {
    "use strict";
    var e = r("MetaConfig")._("195"),
      s = "x1k35ma4-B",
      u = "xz9a51c-B",
      c = "x1bt8ye9-B",
      d = "xaeq8qu-B",
      m = "xbtpni2-B",
      p = {
        blueLink: { stroke: "xw496ev", $$css: !0 },
        circle16: { animationName: "x1koaglw", $$css: !0 },
        circle24: { animationName: "xiepp7r", $$css: !0 },
        circle32: { animationName: "x1pb3rhs", $$css: !0 },
        circle48: { animationName: "x1w90wak", $$css: !0 },
        circle96: { animationName: "x1ubxy3j", $$css: !0 },
        onFilledDestructiveButton: { stroke: "x1rro14h", $$css: !0 },
        onGhostPrimaryButton: { stroke: "x1i9sqzd", $$css: !0 },
        onGhostSecondaryButton: { stroke: "x13jkr8g", $$css: !0 },
        onOnColorButton: { stroke: "x1dl6asj", $$css: !0 },
        onOutlineDestructiveButton: { stroke: "xti8gf0", $$css: !0 },
        onOutlinePrimaryButton: { stroke: "x13gce53", $$css: !0 },
        onOutlineSecondaryButton: { stroke: "xcvxvt1", $$css: !0 },
        onTonalDestructiveButton: { stroke: "xxlv1oi", $$css: !0 },
        onTonalPrimaryButton: { stroke: "xsnpeeu", $$css: !0 },
        primary: { stroke: "xn5zopi", $$css: !0 },
        primaryButton: { stroke: "x5r0ow9", $$css: !0 },
        primaryButtonNew: { stroke: "x16v7qao", $$css: !0 },
        primaryFallback: { stroke: "xufi9hs", $$css: !0 },
        primaryOnMediaButton: { stroke: "x2dpgu9", $$css: !0 },
        secondary: { stroke: "xm3jyu", $$css: !0 },
        secondaryButton: { stroke: "xn5zopi", $$css: !0 },
        secondaryButtonNew: { stroke: "x1d3if0e", $$css: !0 },
        secondaryNew: { stroke: "x1d3if0e", $$css: !0 },
        secondaryOnMediaButton: { stroke: "xbwdf2z", $$css: !0 },
        trackCircleOnFilledDestructiveButton: { stroke: "x1u4sa0r", $$css: !0 },
        trackCircleOnGhostPrimaryButton: { stroke: "x22bik3", $$css: !0 },
        trackCircleOnGhostSecondaryButton: { stroke: "x1uks3ol", $$css: !0 },
        trackCircleOnOnColorButton: { stroke: "x13xl5yv", $$css: !0 },
        trackCircleOnOutlineDestructiveButton: {
          stroke: "x1kcgy8i",
          $$css: !0,
        },
        trackCircleOnOutlinePrimaryButton: { stroke: "xgjeb9d", $$css: !0 },
        trackCircleOnOutlineSecondaryButton: { stroke: "x1yvk0yq", $$css: !0 },
        trackCircleOnTonalDestructiveButton: { stroke: "x14lrwu0", $$css: !0 },
        trackCircleOnTonalPrimaryButton: { stroke: "xvt5mbg", $$css: !0 },
        trackCirclePrimary: { stroke: "xt6f9kv", $$css: !0 },
        trackCirclePrimaryButton: { stroke: "xgtibcu", $$css: !0 },
        trackCirclePrimaryOnMediaButton: { stroke: "xi0xo6d", $$css: !0 },
        trackCirclePrimaryOnMediaButtonLottie: { stroke: "x8ufeyt", $$css: !0 },
        trackCircleSecondary: { stroke: "xi0xo6d", $$css: !0 },
        trackCircleSecondaryButton: { stroke: "x11j5cmb", $$css: !0 },
        trackCircleSecondaryOnMediaButton: { stroke: "xi0xo6d", $$css: !0 },
        trackCircleSecondaryOnMediaButtonLottie: {
          stroke: "xzu3x2x",
          $$css: !0,
        },
      },
      _ = { xstyleConfig: { svg: p.blueLink } },
      f = { xstyleConfig: { svg: p.primary } },
      g = { xstyleConfig: { svg: p.primaryFallback } },
      h = { xstyleConfig: { svg: e ? p.primaryButtonNew : p.primaryButton } },
      y = { xstyleConfig: { svg: p.primaryOnMediaButton } },
      C = { xstyleConfig: { svg: e ? p.secondaryNew : p.secondary } },
      b = {
        xstyleConfig: { svg: e ? p.secondaryButtonNew : p.secondaryButton },
      },
      v = { xstyleConfig: { svg: p.secondaryOnMediaButton } },
      S = { xstyleConfig: { svg: p.onOutlineSecondaryButton } },
      R = { xstyleConfig: { svg: p.onOnColorButton } },
      L = { xstyleConfig: { svg: p.onOutlinePrimaryButton } },
      E = { xstyleConfig: { svg: p.onOutlineDestructiveButton } },
      k = { xstyleConfig: { svg: p.onFilledDestructiveButton } },
      I = { xstyleConfig: { svg: p.onTonalDestructiveButton } },
      T = { xstyleConfig: { svg: p.onTonalPrimaryButton } },
      D = { xstyleConfig: { svg: p.onGhostPrimaryButton } },
      x = { xstyleConfig: { svg: p.onGhostSecondaryButton } },
      $ = p.trackCirclePrimary,
      P = p.trackCirclePrimaryButton,
      N = p.trackCircleSecondary,
      M = p.trackCircleSecondaryButton,
      w = p.trackCircleOnOnColorButton,
      A = p.trackCircleOnOutlinePrimaryButton,
      F = p.trackCircleOnOutlineDestructiveButton,
      O = p.trackCircleOnFilledDestructiveButton,
      B = p.trackCircleOnTonalDestructiveButton,
      W = p.trackCircleOnTonalPrimaryButton,
      q = p.trackCircleOnOutlineSecondaryButton,
      U = p.trackCircleOnGhostPrimaryButton,
      V = p.trackCircleOnGhostSecondaryButton,
      H = e
        ? p.trackCirclePrimaryOnMediaButtonLottie
        : p.trackCirclePrimaryOnMediaButton,
      G = e
        ? p.trackCircleSecondaryOnMediaButtonLottie
        : p.trackCircleSecondaryOnMediaButton,
      z = {
        size: 16,
        strokeWidth: e ? 1.333 : 2,
        xstyleConfig: { circle: p.circle16 },
      },
      j = { size: 24, strokeWidth: 2, xstyleConfig: { circle: p.circle24 } },
      K = {
        size: 32,
        strokeWidth: e ? 2.66 : 2,
        xstyleConfig: { circle: p.circle32 },
      },
      Q = {
        size: 48,
        strokeWidth: e ? 4 : 2,
        xstyleConfig: { circle: p.circle48 },
      },
      X = {
        size: 96,
        strokeWidth: e ? 8 : 2,
        xstyleConfig: { circle: p.circle96 },
      },
      Y = {
        blueLink: _,
        "on-filled-destructive-button": k,
        "on-ghost-primary-button": D,
        "on-ghost-secondary-button": x,
        "on-on-color-button": R,
        "on-outline-destructive-button": E,
        "on-outline-primary-button": L,
        "on-outline-secondary-button": S,
        "on-tonal-destructive-button": I,
        "on-tonal-primary-button": T,
        primary: f,
        "primary-button": h,
        "primary-fallback": g,
        "primary-on-media-button": y,
        secondary: C,
        "secondary-button": b,
        "secondary-on-media-button": v,
      },
      J = { 16: z, 24: j, 32: K, 48: Q, 96: X };
    ((l.blueLinkVariant = _),
      (l.primaryVariant = f),
      (l.primaryFallbackVariant = g),
      (l.primaryButtonVariant = h),
      (l.primaryOnMediaButtonVariant = y),
      (l.secondaryVariant = C),
      (l.secondaryButtonVariant = b),
      (l.secondaryOnMediaButtonVariant = v),
      (l.onOutlineSecondaryButtonVariant = S),
      (l.onOnColorButtonVariant = R),
      (l.onOutlinePrimaryButtonVariant = L),
      (l.onOutlineDestructiveButtonVariant = E),
      (l.onFilledDestructiveButtonVariant = k),
      (l.onTonalDestructiveButtonVariant = I),
      (l.onTonalPrimaryButtonVariant = T),
      (l.onGhostPrimaryButtonVariant = D),
      (l.onGhostSecondaryButtonVariant = x),
      (l.trackCirclePrimaryStyle = $),
      (l.trackCirclePrimaryButtonStyle = P),
      (l.trackCircleSecondaryStyle = N),
      (l.trackCircleSecondaryButtonStyle = M),
      (l.trackCircleOnOnColorButtonStyle = w),
      (l.trackCircleOnOutlinePrimaryButtonStyle = A),
      (l.trackCircleOnOutlineDestructiveButtonStyle = F),
      (l.trackCircleOnFilledDestructiveButtonStyle = O),
      (l.trackCircleOnTonalDestructiveButtonStyle = B),
      (l.trackCircleOnTonalPrimaryButtonStyle = W),
      (l.trackCircleOnOutlineSecondaryButtonStyle = q),
      (l.trackCircleOnGhostPrimaryButtonStyle = U),
      (l.trackCircleOnGhostSecondaryButtonStyle = V),
      (l.trackCirclePrimaryOnMediaButtonStyle = H),
      (l.trackCircleSecondaryOnMediaButtonStyle = G),
      (l.size16Variant = z),
      (l.size24Variant = j),
      (l.size32Variant = K),
      (l.size48Variant = Q),
      (l.size96Variant = X),
      (l.typeVariants = Y),
      (l.sizeVariants = J));
  },
  98,
);
