__d(
  "CDSSpinnerVariants",
  [],
  function (t, n, r, o, a, i, l) {
    "use strict";
    var e = "x1k35ma4-B",
      s = "xz9a51c-B",
      u = "x1bt8ye9-B",
      c = "xaeq8qu-B",
      d = "xbtpni2-B",
      m = {
        blueLink: { stroke: "xw496ev", $$css: !0 },
        circle16: { animationName: "x1koaglw", $$css: !0 },
        circle24: { animationName: "xiepp7r", $$css: !0 },
        circle32: { animationName: "x1pb3rhs", $$css: !0 },
        circle48: { animationName: "x1w90wak", $$css: !0 },
        circle96: { animationName: "x1ubxy3j", $$css: !0 },
        onFilledDestructiveButton: { stroke: "x1rro14h", $$css: !0 },
        onGhostPrimaryButton: { stroke: "x1i9sqzd", $$css: !0 },
        onGhostSecondaryButton: { stroke: "x13jkr8g", $$css: !0 },
        onOnColorButton: { stroke: "x1dl6asj", $$css: !0 },
        onOutlineDestructiveButton: { stroke: "xti8gf0", $$css: !0 },
        onOutlinePrimaryButton: { stroke: "x13gce53", $$css: !0 },
        onOutlineSecondaryButton: { stroke: "xcvxvt1", $$css: !0 },
        onTonalDestructiveButton: { stroke: "xxlv1oi", $$css: !0 },
        onTonalPrimaryButton: { stroke: "xsnpeeu", $$css: !0 },
        primary: { stroke: "xn5zopi", $$css: !0 },
        primaryButtonNew: { stroke: "x16v7qao", $$css: !0 },
        primaryFallback: { stroke: "xufi9hs", $$css: !0 },
        primaryOnMediaButton: { stroke: "x2dpgu9", $$css: !0 },
        secondaryButtonNew: { stroke: "x1d3if0e", $$css: !0 },
        secondaryNew: { stroke: "x1d3if0e", $$css: !0 },
        secondaryOnMediaButton: { stroke: "xbwdf2z", $$css: !0 },
        trackCircleOnFilledDestructiveButton: { stroke: "x1u4sa0r", $$css: !0 },
        trackCircleOnGhostPrimaryButton: { stroke: "x22bik3", $$css: !0 },
        trackCircleOnGhostSecondaryButton: { stroke: "x1uks3ol", $$css: !0 },
        trackCircleOnOnColorButton: { stroke: "x13xl5yv", $$css: !0 },
        trackCircleOnOutlineDestructiveButton: {
          stroke: "x1kcgy8i",
          $$css: !0,
        },
        trackCircleOnOutlinePrimaryButton: { stroke: "xgjeb9d", $$css: !0 },
        trackCircleOnOutlineSecondaryButton: { stroke: "x1yvk0yq", $$css: !0 },
        trackCircleOnTonalDestructiveButton: { stroke: "x14lrwu0", $$css: !0 },
        trackCircleOnTonalPrimaryButton: { stroke: "xvt5mbg", $$css: !0 },
        trackCirclePrimary: { stroke: "xt6f9kv", $$css: !0 },
        trackCirclePrimaryButton: { stroke: "xgtibcu", $$css: !0 },
        trackCirclePrimaryOnMediaButtonLottie: { stroke: "x8ufeyt", $$css: !0 },
        trackCircleSecondary: { stroke: "xi0xo6d", $$css: !0 },
        trackCircleSecondaryButton: { stroke: "x11j5cmb", $$css: !0 },
        trackCircleSecondaryOnMediaButtonLottie: {
          stroke: "xzu3x2x",
          $$css: !0,
        },
      },
      p = { xstyleConfig: { svg: m.blueLink } },
      _ = { xstyleConfig: { svg: m.primary } },
      f = { xstyleConfig: { svg: m.primaryFallback } },
      g = { xstyleConfig: { svg: m.primaryButtonNew } },
      h = { xstyleConfig: { svg: m.primaryOnMediaButton } },
      y = { xstyleConfig: { svg: m.secondaryNew } },
      C = { xstyleConfig: { svg: m.secondaryButtonNew } },
      b = { xstyleConfig: { svg: m.secondaryOnMediaButton } },
      v = { xstyleConfig: { svg: m.onOutlineSecondaryButton } },
      S = { xstyleConfig: { svg: m.onOnColorButton } },
      R = { xstyleConfig: { svg: m.onOutlinePrimaryButton } },
      L = { xstyleConfig: { svg: m.onOutlineDestructiveButton } },
      E = { xstyleConfig: { svg: m.onFilledDestructiveButton } },
      k = { xstyleConfig: { svg: m.onTonalDestructiveButton } },
      I = { xstyleConfig: { svg: m.onTonalPrimaryButton } },
      T = { xstyleConfig: { svg: m.onGhostPrimaryButton } },
      D = { xstyleConfig: { svg: m.onGhostSecondaryButton } },
      x = m.trackCirclePrimary,
      $ = m.trackCirclePrimaryButton,
      P = m.trackCircleSecondary,
      N = m.trackCircleSecondaryButton,
      M = m.trackCircleOnOnColorButton,
      w = m.trackCircleOnOutlinePrimaryButton,
      A = m.trackCircleOnOutlineDestructiveButton,
      F = m.trackCircleOnFilledDestructiveButton,
      O = m.trackCircleOnTonalDestructiveButton,
      B = m.trackCircleOnTonalPrimaryButton,
      W = m.trackCircleOnOutlineSecondaryButton,
      q = m.trackCircleOnGhostPrimaryButton,
      U = m.trackCircleOnGhostSecondaryButton,
      V = m.trackCirclePrimaryOnMediaButtonLottie,
      H = m.trackCircleSecondaryOnMediaButtonLottie,
      G = {
        size: 16,
        strokeWidth: 1.333,
        xstyleConfig: { circle: m.circle16 },
      },
      z = { size: 24, strokeWidth: 2, xstyleConfig: { circle: m.circle24 } },
      j = { size: 32, strokeWidth: 2.66, xstyleConfig: { circle: m.circle32 } },
      K = { size: 48, strokeWidth: 4, xstyleConfig: { circle: m.circle48 } },
      Q = { size: 96, strokeWidth: 8, xstyleConfig: { circle: m.circle96 } },
      X = {
        blueLink: p,
        "on-filled-destructive-button": E,
        "on-ghost-primary-button": T,
        "on-ghost-secondary-button": D,
        "on-on-color-button": S,
        "on-outline-destructive-button": L,
        "on-outline-primary-button": R,
        "on-outline-secondary-button": v,
        "on-tonal-destructive-button": k,
        "on-tonal-primary-button": I,
        primary: _,
        "primary-button": g,
        "primary-fallback": f,
        "primary-on-media-button": h,
        secondary: y,
        "secondary-button": C,
        "secondary-on-media-button": b,
      },
      Y = { 16: G, 24: z, 32: j, 48: K, 96: Q };
    ((l.blueLinkVariant = p),
      (l.primaryVariant = _),
      (l.primaryFallbackVariant = f),
      (l.primaryButtonVariant = g),
      (l.primaryOnMediaButtonVariant = h),
      (l.secondaryVariant = y),
      (l.secondaryButtonVariant = C),
      (l.secondaryOnMediaButtonVariant = b),
      (l.onOutlineSecondaryButtonVariant = v),
      (l.onOnColorButtonVariant = S),
      (l.onOutlinePrimaryButtonVariant = R),
      (l.onOutlineDestructiveButtonVariant = L),
      (l.onFilledDestructiveButtonVariant = E),
      (l.onTonalDestructiveButtonVariant = k),
      (l.onTonalPrimaryButtonVariant = I),
      (l.onGhostPrimaryButtonVariant = T),
      (l.onGhostSecondaryButtonVariant = D),
      (l.trackCirclePrimaryStyle = x),
      (l.trackCirclePrimaryButtonStyle = $),
      (l.trackCircleSecondaryStyle = P),
      (l.trackCircleSecondaryButtonStyle = N),
      (l.trackCircleOnOnColorButtonStyle = M),
      (l.trackCircleOnOutlinePrimaryButtonStyle = w),
      (l.trackCircleOnOutlineDestructiveButtonStyle = A),
      (l.trackCircleOnFilledDestructiveButtonStyle = F),
      (l.trackCircleOnTonalDestructiveButtonStyle = O),
      (l.trackCircleOnTonalPrimaryButtonStyle = B),
      (l.trackCircleOnOutlineSecondaryButtonStyle = W),
      (l.trackCircleOnGhostPrimaryButtonStyle = q),
      (l.trackCircleOnGhostSecondaryButtonStyle = U),
      (l.trackCirclePrimaryOnMediaButtonStyle = V),
      (l.trackCircleSecondaryOnMediaButtonStyle = H),
      (l.size16Variant = G),
      (l.size24Variant = z),
      (l.size32Variant = j),
      (l.size48Variant = K),
      (l.size96Variant = Q),
      (l.typeVariants = X),
      (l.sizeVariants = Y));
  },
  98,
);
