__d(
  "ChatThemePersianPlum.stylex",
  ["WDSVars.stylex"],
  function (t, n, r, o, a, i, l) {
    "use strict";
    var e,
      s = "@media (prefers-color-scheme: dark)",
      u = { xoeyzqq: "x1p6r4fs xoeyzqq", $$css: !0 },
      c = { xoeyzqq: "xit04x9 xoeyzqq", $$css: !0 },
      d = { xoeyzqq: "x1vw3w91 xoeyzqq", $$css: !0 },
      m = { xoeyzqq: "x15ww44d xoeyzqq", $$css: !0 },
      p = {
        "--WDS-accent": (e = o("WDSVars.stylex")).WDSBaseColor.whiteOpaque,
        "--WDS-accent-deemphasized": "rgb(253, 206, 217)",
        "--WDS-accent-emphasized": "rgb(115, 26, 47)",
        "--WDS-content-action-emphasized": e.WDSBaseColor.whiteOpaque,
        "--WDS-content-external-link": e.WDSBaseColor.whiteOpaque,
        "--WDS-content-read": "#2A91FD",
        "--WDS-systems-bubble-surface-incoming": e.WDSBaseColor.whiteOpaque,
        "--WDS-systems-bubble-surface-incoming-RGB": "255, 255, 255",
        "--WDS-systems-bubble-surface-outgoing": "rgb(115, 26, 47)",
        "--WDS-systems-bubble-surface-outgoing-RGB": "115, 26, 47",
        "--WDS-systems-bubble-surface-overlay": e.WDSBaseColor.blackAlpha20,
        "--WDS-systems-bubble-surface-overlay-RGB": "0, 0, 0",
        "--WDS-systems-bubble-content-deemphasized":
          e.WDSBaseColor.whiteAlpha60,
      },
      _ = babelHelpers.extends({}, p, {
        "--WDS-systems-chat-foreground-wallpaper": "rgb(231, 223, 212)",
        "--WDS-systems-chat-background-wallpaper": "rgb(241, 237, 231)",
        "--WDS-systems-chat-background-wallpaper-RGB": "241, 237, 231",
      }),
      f = { xoeyzqq: "xfa0ct2 xoeyzqq", $$css: !0 },
      g = {
        "--WDS-accent": e.WDSBaseColor.whiteOpaque,
        "--WDS-accent-deemphasized": "rgb(83, 19, 34)",
        "--WDS-accent-emphasized": "rgb(253, 206, 217)",
        "--WDS-content-action-emphasized": e.WDSBaseColor.whiteOpaque,
        "--WDS-content-external-link": e.WDSBaseColor.whiteOpaque,
        "--WDS-content-read": e.WDSBaseColor.cobalt300,
        "--WDS-systems-bubble-surface-incoming": e.WDSBaseColor.neutralGray800,
        "--WDS-systems-bubble-surface-incoming-RGB": "36, 38, 38",
        "--WDS-systems-bubble-surface-outgoing": "rgb(125, 17, 46)",
        "--WDS-systems-bubble-surface-outgoing-RGB": "125, 17, 46",
        "--WDS-systems-bubble-surface-overlay": e.WDSBaseColor.blackAlpha20,
        "--WDS-systems-bubble-surface-overlay-RGB": "0, 0, 0",
        "--WDS-systems-bubble-content-deemphasized":
          e.WDSBaseColor.whiteAlpha50,
      },
      h = babelHelpers.extends({}, g, {
        "--WDS-systems-chat-foreground-wallpaper": "rgb(42, 19, 28)",
        "--WDS-systems-chat-background-wallpaper":
          e.WDSBaseColor.neutralGray1000,
        "--WDS-systems-chat-background-wallpaper-RGB": "10, 10, 10",
      }),
      y = { xoeyzqq: "xjvx379 xoeyzqq", $$css: !0 },
      C = {
        "--WDS-accent": "rgb(115, 26, 47)",
        "--WDS-accent-deemphasized": "rgb(253, 206, 217)",
        "--WDS-accent-emphasized": "rgb(115, 26, 47)",
        "--WDS-content-action-emphasized": "rgb(115, 26, 47)",
        "--WDS-content-external-link": "rgb(115, 26, 47)",
        "--WDS-content-read": e.WDSBaseColor.cobalt400,
        "--WDS-systems-bubble-surface-incoming": e.WDSBaseColor.whiteOpaque,
        "--WDS-systems-bubble-surface-incoming-RGB": "255, 255, 255",
        "--WDS-systems-bubble-surface-outgoing": "rgb(253, 206, 217)",
        "--WDS-systems-bubble-surface-outgoing-RGB": "253, 206, 217",
        "--WDS-systems-bubble-surface-overlay":
          e.WDSBaseColor.warmGray300Alpha15,
        "--WDS-systems-bubble-surface-overlay-RGB": "194, 189, 184",
      },
      b = {
        "--WDS-accent": "rgb(207, 74, 105)",
        "--WDS-accent-deemphasized": "rgb(83, 19, 34)",
        "--WDS-accent-emphasized": "rgb(253, 206, 217)",
        "--WDS-content-action-emphasized": "rgb(207, 74, 105)",
        "--WDS-content-external-link": "rgb(207, 74, 105)",
        "--WDS-content-read": e.WDSBaseColor.cobalt300,
        "--WDS-systems-bubble-surface-incoming": e.WDSBaseColor.neutralGray800,
        "--WDS-systems-bubble-surface-incoming-RGB": "36, 38, 38",
        "--WDS-systems-bubble-surface-outgoing": "rgb(83, 19, 35)",
        "--WDS-systems-bubble-surface-outgoing-RGB": "83, 19, 35",
        "--WDS-systems-bubble-surface-overlay": e.WDSBaseColor.blackAlpha20,
        "--WDS-systems-bubble-surface-overlay-RGB": "0, 0, 0",
      },
      v = { xoeyzqq: "xbfeo6q xoeyzqq", $$css: !0 },
      S = { xoeyzqq: "x6kwrwp xoeyzqq", $$css: !0 },
      R = { xoeyzqq: "x14b18eq xoeyzqq", $$css: !0 },
      L = { xoeyzqq: "xtat17h xoeyzqq", $$css: !0 };
    ((l.tonalSystem = u),
      (l.tonalLight = c),
      (l.tonalDark = d),
      (l.vibrantSystem = m),
      (l.vibrantLight = f),
      (l.vibrantDark = y),
      (l.bubbleLight = v),
      (l.bubbleDark = S),
      (l.bubbleTonalLight = R),
      (l.bubbleTonalDark = L));
  },
  98,
);
