__d(
  "ChatThemeTyrianPurple.stylex",
  ["WDSVars.stylex"],
  function (t, n, r, o, a, i, l) {
    "use strict";
    var e,
      s = "@media (prefers-color-scheme: dark)",
      u = { xoeyzqq: "x1jyegl xoeyzqq", $$css: !0 },
      c = { xoeyzqq: "x1qgnphw xoeyzqq", $$css: !0 },
      d = { xoeyzqq: "x1f1maog xoeyzqq", $$css: !0 },
      m = { xoeyzqq: "x1yflcxw xoeyzqq", $$css: !0 },
      p = {
        "--WDS-accent": (e = o("WDSVars.stylex")).WDSBaseColor.whiteOpaque,
        "--WDS-accent-deemphasized": "rgb(241, 217, 247)",
        "--WDS-accent-emphasized": "rgb(113, 48, 130)",
        "--WDS-content-action-emphasized": e.WDSBaseColor.whiteOpaque,
        "--WDS-content-external-link": e.WDSBaseColor.whiteOpaque,
        "--WDS-content-read": "#76B8FE",
        "--WDS-systems-bubble-surface-incoming": e.WDSBaseColor.whiteOpaque,
        "--WDS-systems-bubble-surface-incoming-RGB": "255, 255, 255",
        "--WDS-systems-bubble-surface-outgoing": "rgb(193, 90, 221)",
        "--WDS-systems-bubble-surface-outgoing-RGB": "193, 90, 221",
        "--WDS-systems-bubble-surface-overlay": e.WDSBaseColor.blackAlpha20,
        "--WDS-systems-bubble-surface-overlay-RGB": "0, 0, 0",
        "--WDS-systems-bubble-content-deemphasized":
          e.WDSBaseColor.whiteAlpha60,
      },
      _ = babelHelpers.extends({}, p, {
        "--WDS-systems-chat-foreground-wallpaper": "rgb(241, 217, 247)",
        "--WDS-systems-chat-background-wallpaper": e.WDSBaseColor.orange75,
        "--WDS-systems-chat-background-wallpaper-RGB": "255, 235, 230",
      }),
      f = { xoeyzqq: "xy7lrok xoeyzqq", $$css: !0 },
      g = {
        "--WDS-accent": e.WDSBaseColor.whiteOpaque,
        "--WDS-accent-deemphasized": "rgb(43, 24, 48)",
        "--WDS-accent-emphasized": "rgb(241, 217, 247)",
        "--WDS-content-action-emphasized": e.WDSBaseColor.whiteOpaque,
        "--WDS-content-external-link": e.WDSBaseColor.whiteOpaque,
        "--WDS-content-read": e.WDSBaseColor.cobalt300,
        "--WDS-systems-bubble-surface-incoming": e.WDSBaseColor.neutralGray800,
        "--WDS-systems-bubble-surface-incoming-RGB": "36, 38, 38",
        "--WDS-systems-bubble-surface-outgoing": "rgb(113, 48, 130)",
        "--WDS-systems-bubble-surface-outgoing-RGB": "113, 48, 130",
        "--WDS-systems-bubble-surface-overlay": e.WDSBaseColor.blackAlpha20,
        "--WDS-systems-bubble-surface-overlay-RGB": "0, 0, 0",
        "--WDS-systems-bubble-content-deemphasized":
          e.WDSBaseColor.whiteAlpha50,
      },
      h = babelHelpers.extends({}, g, {
        "--WDS-systems-chat-foreground-wallpaper": "rgb(39, 22, 44)",
        "--WDS-systems-chat-background-wallpaper":
          e.WDSBaseColor.neutralGray1000,
        "--WDS-systems-chat-background-wallpaper-RGB": "10, 10, 10",
      }),
      y = { xoeyzqq: "x1egei5y xoeyzqq", $$css: !0 },
      C = {
        "--WDS-accent": "rgb(193, 90, 221)",
        "--WDS-accent-deemphasized": "rgb(241, 217, 247)",
        "--WDS-accent-emphasized": "rgb(113, 48, 130)",
        "--WDS-content-action-emphasized": "rgb(193, 90, 221)",
        "--WDS-content-external-link": "rgb(193, 90, 221)",
        "--WDS-content-read": e.WDSBaseColor.cobalt400,
        "--WDS-systems-bubble-surface-incoming": e.WDSBaseColor.whiteOpaque,
        "--WDS-systems-bubble-surface-incoming-RGB": "255, 255, 255",
        "--WDS-systems-bubble-surface-outgoing": "rgb(241, 217, 247)",
        "--WDS-systems-bubble-surface-outgoing-RGB": "241, 217, 247",
        "--WDS-systems-bubble-surface-overlay":
          e.WDSBaseColor.warmGray300Alpha15,
        "--WDS-systems-bubble-surface-overlay-RGB": "194, 189, 184",
      },
      b = {
        "--WDS-accent": "rgb(209, 132, 230)",
        "--WDS-accent-deemphasized": "rgb(43, 24, 48)",
        "--WDS-accent-emphasized": "rgb(241, 217, 247)",
        "--WDS-content-action-emphasized": "rgb(209, 132, 230)",
        "--WDS-content-external-link": "rgb(209, 132, 230)",
        "--WDS-content-read": e.WDSBaseColor.cobalt300,
        "--WDS-systems-bubble-surface-incoming": e.WDSBaseColor.neutralGray800,
        "--WDS-systems-bubble-surface-incoming-RGB": "36, 38, 38",
        "--WDS-systems-bubble-surface-outgoing": "rgb(75, 33, 90)",
        "--WDS-systems-bubble-surface-outgoing-RGB": "75, 33, 90",
        "--WDS-systems-bubble-surface-overlay": e.WDSBaseColor.blackAlpha20,
        "--WDS-systems-bubble-surface-overlay-RGB": "0, 0, 0",
      },
      v = { xoeyzqq: "x1awvbkp xoeyzqq", $$css: !0 },
      S = { xoeyzqq: "x1rych3f xoeyzqq", $$css: !0 },
      R = { xoeyzqq: "x1ojquvv xoeyzqq", $$css: !0 },
      L = { xoeyzqq: "xds7qem xoeyzqq", $$css: !0 };
    ((l.tonalSystem = u),
      (l.tonalLight = c),
      (l.tonalDark = d),
      (l.vibrantSystem = m),
      (l.vibrantLight = f),
      (l.vibrantDark = y),
      (l.bubbleLight = v),
      (l.bubbleDark = S),
      (l.bubbleTonalLight = R),
      (l.bubbleTonalDark = L));
  },
  98,
);
