__d(
  "ChatThemeDefaultBlue.stylex",
  ["WDSVars.stylex"],
  function (t, n, r, o, a, i, l) {
    "use strict";
    var e,
      s = "@media (prefers-color-scheme: dark)",
      u = { xoeyzqq: "x191pzh xoeyzqq", $$css: !0 },
      c = { xoeyzqq: "xm098vz xoeyzqq", $$css: !0 },
      d = { xoeyzqq: "x1xb6obg xoeyzqq", $$css: !0 },
      m = { xoeyzqq: "x7bkt8b xoeyzqq", $$css: !0 },
      p = {
        "--WDS-accent": (e = o("WDSVars.stylex")).WDSBaseColor.whiteOpaque,
        "--WDS-accent-deemphasized": "rgb(211, 217, 238)",
        "--WDS-accent-emphasized": e.WDSBaseColor.cobalt700,
        "--WDS-content-action-emphasized": e.WDSBaseColor.whiteOpaque,
        "--WDS-content-external-link": e.WDSBaseColor.whiteOpaque,
        "--WDS-content-read": e.WDSBaseColor.whiteOpaque,
        "--WDS-systems-bubble-surface-incoming": e.WDSBaseColor.whiteOpaque,
        "--WDS-systems-bubble-surface-incoming-RGB": "255, 255, 255",
        "--WDS-systems-bubble-surface-outgoing": "#2A91FD",
        "--WDS-systems-bubble-surface-outgoing-RGB": "42, 145, 253",
        "--WDS-systems-bubble-surface-overlay": e.WDSBaseColor.blackAlpha20,
        "--WDS-systems-bubble-surface-overlay-RGB": "0, 0, 0",
        "--WDS-systems-bubble-content-deemphasized":
          e.WDSBaseColor.whiteAlpha50,
      },
      _ = {
        "--WDS-accent": e.WDSBaseColor.whiteOpaque,
        "--WDS-accent-deemphasized": "rgb(211, 217, 238)",
        "--WDS-accent-emphasized": e.WDSBaseColor.cobalt700,
        "--WDS-content-action-emphasized": e.WDSBaseColor.whiteOpaque,
        "--WDS-content-external-link": e.WDSBaseColor.whiteOpaque,
        "--WDS-content-read": e.WDSBaseColor.whiteOpaque,
        "--WDS-systems-bubble-surface-incoming": e.WDSBaseColor.whiteOpaque,
        "--WDS-systems-bubble-surface-incoming-RGB": "255, 255, 255",
        "--WDS-systems-bubble-surface-outgoing": "#2A91FD",
        "--WDS-systems-bubble-surface-outgoing-RGB": "42, 145, 253",
        "--WDS-systems-bubble-surface-overlay": e.WDSBaseColor.blackAlpha20,
        "--WDS-systems-bubble-surface-overlay-RGB": "0, 0, 0",
        "--WDS-systems-bubble-content-deemphasized":
          e.WDSBaseColor.whiteAlpha50,
        "--WDS-systems-chat-foreground-wallpaper": e.WDSBaseColor.cobalt100,
        "--WDS-systems-chat-background-wallpaper": e.WDSBaseColor.cobalt50,
        "--WDS-systems-chat-background-wallpaper-RGB": "242, 248, 255",
      },
      f = { xoeyzqq: "x1ezwr4w xoeyzqq", $$css: !0 },
      g = {
        "--WDS-accent": e.WDSBaseColor.whiteOpaque,
        "--WDS-accent-deemphasized": e.WDSBaseColor.cobalt800,
        "--WDS-accent-emphasized": e.WDSBaseColor.cobalt100,
        "--WDS-content-action-emphasized": e.WDSBaseColor.whiteOpaque,
        "--WDS-content-external-link": e.WDSBaseColor.whiteOpaque,
        "--WDS-content-read": e.WDSBaseColor.whiteOpaque,
        "--WDS-systems-bubble-surface-incoming": e.WDSBaseColor.neutralGray800,
        "--WDS-systems-bubble-surface-incoming-RGB": "36, 38, 38",
        "--WDS-systems-bubble-surface-outgoing": "#0A5FA0",
        "--WDS-systems-bubble-surface-outgoing-RGB": "10, 95, 160",
        "--WDS-systems-bubble-surface-overlay": e.WDSBaseColor.blackAlpha20,
        "--WDS-systems-bubble-surface-overlay-RGB": "0, 0, 0",
        "--WDS-systems-bubble-content-deemphasized":
          e.WDSBaseColor.whiteAlpha50,
      },
      h = {
        "--WDS-accent": e.WDSBaseColor.whiteOpaque,
        "--WDS-accent-deemphasized": e.WDSBaseColor.cobalt800,
        "--WDS-accent-emphasized": e.WDSBaseColor.cobalt100,
        "--WDS-content-action-emphasized": e.WDSBaseColor.whiteOpaque,
        "--WDS-content-external-link": e.WDSBaseColor.whiteOpaque,
        "--WDS-content-read": e.WDSBaseColor.whiteOpaque,
        "--WDS-systems-bubble-surface-incoming": e.WDSBaseColor.neutralGray800,
        "--WDS-systems-bubble-surface-incoming-RGB": "36, 38, 38",
        "--WDS-systems-bubble-surface-outgoing": "#0A5FA0",
        "--WDS-systems-bubble-surface-outgoing-RGB": "10, 95, 160",
        "--WDS-systems-bubble-surface-overlay": e.WDSBaseColor.blackAlpha20,
        "--WDS-systems-bubble-surface-overlay-RGB": "0, 0, 0",
        "--WDS-systems-bubble-content-deemphasized":
          e.WDSBaseColor.whiteAlpha50,
        "--WDS-systems-chat-foreground-wallpaper": e.WDSBaseColor.cobalt800,
        "--WDS-systems-chat-background-wallpaper": "#051321",
        "--WDS-systems-chat-background-wallpaper-RGB": "5, 19, 33",
      },
      y = { xoeyzqq: "xo0j6e0 xoeyzqq", $$css: !0 },
      C = { xoeyzqq: "x3avjbp xoeyzqq", $$css: !0 },
      b = { xoeyzqq: "xemwex4 xoeyzqq", $$css: !0 },
      v = {
        "--WDS-accent": "#2A91FD",
        "--WDS-accent-deemphasized": "rgb(211, 217, 238)",
        "--WDS-accent-emphasized": e.WDSBaseColor.cobalt700,
        "--WDS-content-action-emphasized": "#2A91FD",
        "--WDS-content-external-link": "#2A91FD",
        "--WDS-content-read": "#2A91FD",
        "--WDS-systems-bubble-surface-incoming": e.WDSBaseColor.whiteOpaque,
        "--WDS-systems-bubble-surface-incoming-RGB": "255, 255, 255",
        "--WDS-systems-bubble-surface-outgoing": e.WDSBaseColor.cobalt100,
        "--WDS-systems-bubble-surface-outgoing-RGB": "210, 232, 254",
        "--WDS-systems-bubble-surface-overlay": e.WDSBaseColor.blackAlpha10,
        "--WDS-systems-bubble-surface-overlay-RGB": "0, 0, 0",
        "--WDS-systems-bubble-content-deemphasized": "rgba(17, 27, 33, 0.7)",
      },
      S = {
        "--WDS-accent": e.WDSBaseColor.cobalt400,
        "--WDS-accent-deemphasized": e.WDSBaseColor.cobalt800,
        "--WDS-accent-emphasized": e.WDSBaseColor.cobalt100,
        "--WDS-content-action-emphasized": "#2A91FD",
        "--WDS-content-external-link": "#2A91FD",
        "--WDS-content-read": e.WDSBaseColor.cobalt300,
        "--WDS-systems-bubble-surface-incoming": e.WDSBaseColor.neutralGray800,
        "--WDS-systems-bubble-surface-incoming-RGB": "36, 38, 38",
        "--WDS-systems-bubble-surface-outgoing": "rgb(7, 47, 90)",
        "--WDS-systems-bubble-surface-outgoing-RGB": "7, 47, 90",
        "--WDS-systems-bubble-surface-overlay": e.WDSBaseColor.blackAlpha20,
        "--WDS-systems-bubble-surface-overlay-RGB": "0, 0, 0",
        "--WDS-systems-bubble-content-deemphasized":
          e.WDSBaseColor.whiteAlpha50,
      },
      R = babelHelpers.extends({}, p, {
        "--WDS-systems-bubble-surface-incoming": e.WDSBaseColor.neutralGray100,
        "--WDS-systems-bubble-surface-incoming-RGB": "238, 238, 238",
      }),
      L = babelHelpers.extends({}, g, {
        "--WDS-systems-bubble-surface-incoming": e.WDSBaseColor.neutralGray800,
        "--WDS-systems-bubble-surface-incoming-RGB": "36, 38, 38",
      }),
      E = { xoeyzqq: "xj0o8xd xoeyzqq", $$css: !0 },
      k = { xoeyzqq: "x1mxpwnn xoeyzqq", $$css: !0 },
      I = { xoeyzqq: "xsl5q99 xoeyzqq", $$css: !0 },
      T = { xoeyzqq: "x1mnpss8 xoeyzqq", $$css: !0 },
      D = { xoeyzqq: "xlb9b29 xoeyzqq", $$css: !0 },
      x = { xoeyzqq: "x1mxpwnn xoeyzqq", $$css: !0 };
    ((l.tonalSystem = u),
      (l.tonalLight = c),
      (l.tonalDark = d),
      (l.vibrantSystem = m),
      (l.vibrantLight = f),
      (l.vibrantDark = y),
      (l.minimalLight = C),
      (l.minimalDark = b),
      (l.bubbleLight = E),
      (l.bubbleDark = k),
      (l.bubbleTonalLight = I),
      (l.bubbleTonalDark = T),
      (l.bubbleMinimalLight = D),
      (l.bubbleMinimalDark = x));
  },
  98,
);
