__d(
  "ChatThemeRoyalBlue.stylex",
  ["WDSVars.stylex"],
  function (t, n, r, o, a, i, l) {
    "use strict";
    var e,
      s = "@media (prefers-color-scheme: dark)",
      u = { xoeyzqq: "x1ho8uq4 xoeyzqq", $$css: !0 },
      c = { xoeyzqq: "x1bq1lw5 xoeyzqq", $$css: !0 },
      d = { xoeyzqq: "xcx27cb xoeyzqq", $$css: !0 },
      m = { xoeyzqq: "x1brb1f xoeyzqq", $$css: !0 },
      p = {
        "--WDS-accent": (e = o("WDSVars.stylex")).WDSBaseColor.whiteOpaque,
        "--WDS-accent-deemphasized": "rgb(211, 217, 238)",
        "--WDS-accent-emphasized": e.WDSBaseColor.cobalt700,
        "--WDS-content-action-emphasized": e.WDSBaseColor.whiteOpaque,
        "--WDS-content-external-link": e.WDSBaseColor.whiteOpaque,
        "--WDS-content-read": e.WDSBaseColor.whiteOpaque,
        "--WDS-systems-bubble-surface-incoming": e.WDSBaseColor.whiteOpaque,
        "--WDS-systems-bubble-surface-incoming-RGB": "255, 255, 255",
        "--WDS-systems-bubble-surface-outgoing": "rgb(45, 104, 235)",
        "--WDS-systems-bubble-surface-outgoing-RGB": "45, 104, 235",
        "--WDS-systems-bubble-surface-overlay": e.WDSBaseColor.blackAlpha20,
        "--WDS-systems-bubble-surface-overlay-RGB": "0, 0, 0",
        "--WDS-systems-bubble-content-deemphasized":
          e.WDSBaseColor.whiteAlpha60,
      },
      _ = babelHelpers.extends({}, p, {
        "--WDS-systems-chat-foreground-wallpaper": "rgb(196, 217, 253)",
        "--WDS-systems-chat-background-wallpaper": "rgb(230, 239, 250)",
        "--WDS-systems-chat-background-wallpaper-RGB": "230, 239, 250",
      }),
      f = { xoeyzqq: "x15rn06d xoeyzqq", $$css: !0 },
      g = {
        "--WDS-accent": e.WDSBaseColor.whiteOpaque,
        "--WDS-accent-deemphasized": e.WDSBaseColor.cobalt800,
        "--WDS-accent-emphasized": e.WDSBaseColor.cobalt100,
        "--WDS-content-action-emphasized": e.WDSBaseColor.whiteOpaque,
        "--WDS-content-external-link": e.WDSBaseColor.whiteOpaque,
        "--WDS-content-read": e.WDSBaseColor.whiteOpaque,
        "--WDS-systems-bubble-surface-incoming": e.WDSBaseColor.neutralGray800,
        "--WDS-systems-bubble-surface-incoming-RGB": "36, 38, 38",
        "--WDS-systems-bubble-surface-outgoing": "rgb(4, 72, 144)",
        "--WDS-systems-bubble-surface-outgoing-RGB": "4, 72, 144",
        "--WDS-systems-bubble-surface-overlay": e.WDSBaseColor.blackAlpha20,
        "--WDS-systems-bubble-surface-overlay-RGB": "0, 0, 0",
        "--WDS-systems-bubble-content-deemphasized":
          e.WDSBaseColor.whiteAlpha50,
      },
      h = babelHelpers.extends({}, g, {
        "--WDS-systems-chat-foreground-wallpaper": "rgb(7, 28, 49)",
        "--WDS-systems-chat-background-wallpaper":
          e.WDSBaseColor.neutralGray1000,
        "--WDS-systems-chat-background-wallpaper-RGB": "10, 10, 10",
      }),
      y = { xoeyzqq: "xd74hew xoeyzqq", $$css: !0 },
      C = {
        "--WDS-accent": "rgb(45, 104, 235)",
        "--WDS-accent-deemphasized": "rgb(211, 217, 238)",
        "--WDS-accent-emphasized": e.WDSBaseColor.cobalt700,
        "--WDS-content-action-emphasized": "rgb(45, 104, 235)",
        "--WDS-content-external-link": "rgb(45, 104, 235)",
        "--WDS-content-read": "rgb(45, 104, 235)",
        "--WDS-systems-bubble-surface-incoming": e.WDSBaseColor.whiteOpaque,
        "--WDS-systems-bubble-surface-incoming-RGB": "255, 255, 255",
        "--WDS-systems-bubble-surface-outgoing": e.WDSBaseColor.cobalt100,
        "--WDS-systems-bubble-surface-outgoing-RGB": "210, 232, 254",
        "--WDS-systems-bubble-surface-overlay":
          e.WDSBaseColor.warmGray300Alpha15,
        "--WDS-systems-bubble-surface-overlay-RGB": "194, 189, 184",
      },
      b = {
        "--WDS-accent": e.WDSBaseColor.cobalt400,
        "--WDS-accent-deemphasized": e.WDSBaseColor.cobalt800,
        "--WDS-accent-emphasized": e.WDSBaseColor.cobalt100,
        "--WDS-content-action-emphasized": e.WDSBaseColor.cobalt400,
        "--WDS-content-external-link": e.WDSBaseColor.cobalt400,
        "--WDS-content-read": e.WDSBaseColor.cobalt300,
        "--WDS-systems-bubble-surface-incoming": e.WDSBaseColor.neutralGray800,
        "--WDS-systems-bubble-surface-incoming-RGB": "36, 38, 38",
        "--WDS-systems-bubble-surface-outgoing": "rgb(7, 47, 90)",
        "--WDS-systems-bubble-surface-outgoing-RGB": "7, 47, 90",
        "--WDS-systems-bubble-surface-overlay": e.WDSBaseColor.blackAlpha20,
        "--WDS-systems-bubble-surface-overlay-RGB": "0, 0, 0",
      },
      v = { xoeyzqq: "x16ydorl xoeyzqq", $$css: !0 },
      S = { xoeyzqq: "xn1qfrn xoeyzqq", $$css: !0 },
      R = { xoeyzqq: "x1sk1f76 xoeyzqq", $$css: !0 },
      L = { xoeyzqq: "x3hpqm9 xoeyzqq", $$css: !0 };
    ((l.tonalSystem = u),
      (l.tonalLight = c),
      (l.tonalDark = d),
      (l.vibrantSystem = m),
      (l.vibrantLight = f),
      (l.vibrantDark = y),
      (l.bubbleLight = v),
      (l.bubbleDark = S),
      (l.bubbleTonalLight = R),
      (l.bubbleTonalDark = L));
  },
  98,
);
