__d(
  "ChatThemeWhatsAppGreen.stylex",
  ["WDSVars.stylex"],
  function (t, n, r, o, a, i, l) {
    "use strict";
    var e,
      s = "@media (prefers-color-scheme: dark)",
      u = { xoeyzqq: "xnv0u6q xoeyzqq", $$css: !0 },
      c = { xoeyzqq: "xz9pgq1 xoeyzqq", $$css: !0 },
      d = { xoeyzqq: "x1rel9iu xoeyzqq", $$css: !0 },
      m = { xoeyzqq: "xbwrn9g xoeyzqq", $$css: !0 },
      p = {
        "--WDS-accent": (e = o("WDSVars.stylex")).WDSBaseColor.whiteOpaque,
        "--WDS-accent-deemphasized": e.WDSBaseColor.green100,
        "--WDS-accent-emphasized": e.WDSBaseColor.green700,
        "--WDS-content-action-emphasized": e.WDSBaseColor.whiteOpaque,
        "--WDS-content-external-link": e.WDSBaseColor.whiteOpaque,
        "--WDS-content-read": e.WDSBaseColor.whiteOpaque,
        "--WDS-systems-bubble-surface-incoming": e.WDSBaseColor.whiteOpaque,
        "--WDS-systems-bubble-surface-incoming-RGB": "255, 255, 255",
        "--WDS-systems-bubble-surface-outgoing": e.WDSBaseColor.green500,
        "--WDS-systems-bubble-surface-outgoing-RGB": "29, 170, 97",
        "--WDS-systems-bubble-surface-overlay": e.WDSBaseColor.blackAlpha20,
        "--WDS-systems-bubble-surface-overlay-RGB": "0, 0, 0",
        "--WDS-systems-bubble-content-deemphasized":
          e.WDSBaseColor.whiteAlpha60,
      },
      _ = babelHelpers.extends({}, p, {
        "--WDS-systems-chat-foreground-wallpaper": e.WDSBaseColor.cream150,
        "--WDS-systems-chat-background-wallpaper": e.WDSBaseColor.cream75,
        "--WDS-systems-chat-background-wallpaper-RGB": "245, 241, 235",
      }),
      f = { xoeyzqq: "xfb5h0 xoeyzqq", $$css: !0 },
      g = {
        "--WDS-accent": e.WDSBaseColor.whiteOpaque,
        "--WDS-accent-deemphasized": e.WDSBaseColor.green800,
        "--WDS-accent-emphasized": e.WDSBaseColor.green100,
        "--WDS-content-action-emphasized": e.WDSBaseColor.whiteOpaque,
        "--WDS-content-external-link": e.WDSBaseColor.whiteOpaque,
        "--WDS-content-read": e.WDSBaseColor.whiteOpaque,
        "--WDS-systems-bubble-surface-incoming": e.WDSBaseColor.neutralGray800,
        "--WDS-systems-bubble-surface-incoming-RGB": "36, 38, 38",
        "--WDS-systems-bubble-surface-outgoing": "rgb(22, 111, 70)",
        "--WDS-systems-bubble-surface-outgoing-RGB": "22, 111, 70",
        "--WDS-systems-bubble-surface-overlay": e.WDSBaseColor.blackAlpha20,
        "--WDS-systems-bubble-surface-overlay-RGB": "0, 0, 0",
        "--WDS-systems-bubble-content-deemphasized":
          e.WDSBaseColor.whiteAlpha50,
      },
      h = babelHelpers.extends({}, g, {
        "--WDS-systems-chat-foreground-wallpaper": e.WDSBaseColor.whiteAlpha10,
        "--WDS-systems-chat-background-wallpaper":
          e.WDSBaseColor.neutralGray1000,
        "--WDS-systems-chat-background-wallpaper-RGB": "10, 10, 10",
      }),
      y = { xoeyzqq: "x1p1y5yr xoeyzqq", $$css: !0 },
      C = {
        "--WDS-accent": e.WDSBaseColor.green500,
        "--WDS-accent-deemphasized": e.WDSBaseColor.green100,
        "--WDS-accent-emphasized": e.WDSBaseColor.green700,
        "--WDS-content-action-emphasized": e.WDSBaseColor.green600,
        "--WDS-content-external-link": e.WDSBaseColor.green600,
        "--WDS-content-read": e.WDSBaseColor.cobalt400,
        "--WDS-systems-bubble-surface-incoming": e.WDSBaseColor.whiteOpaque,
        "--WDS-systems-bubble-surface-incoming-RGB": "255, 255, 255",
        "--WDS-systems-bubble-surface-outgoing": e.WDSBaseColor.green100,
        "--WDS-systems-bubble-surface-outgoing-RGB": "217, 253, 211",
        "--WDS-systems-bubble-surface-overlay":
          e.WDSBaseColor.warmGray300Alpha15,
        "--WDS-systems-bubble-surface-overlay-RGB": "194, 189, 184",
      },
      b = {
        "--WDS-accent": e.WDSBaseColor.green450,
        "--WDS-accent-deemphasized": e.WDSBaseColor.green800,
        "--WDS-accent-emphasized": e.WDSBaseColor.green100,
        "--WDS-content-action-emphasized": e.WDSBaseColor.green450,
        "--WDS-content-external-link": e.WDSBaseColor.green450,
        "--WDS-content-read": e.WDSBaseColor.skyBlue300,
        "--WDS-systems-bubble-surface-incoming": e.WDSBaseColor.neutralGray800,
        "--WDS-systems-bubble-surface-incoming-RGB": "36, 38, 38",
        "--WDS-systems-bubble-surface-outgoing": e.WDSBaseColor.green750,
        "--WDS-systems-bubble-surface-outgoing-RGB": "20, 77, 55",
        "--WDS-systems-bubble-surface-overlay": e.WDSBaseColor.blackAlpha20,
        "--WDS-systems-bubble-surface-overlay-RGB": "0, 0, 0",
      },
      v = { xoeyzqq: "x1q4td31 xoeyzqq", $$css: !0 },
      S = { xoeyzqq: "x1npyc1o xoeyzqq", $$css: !0 },
      R = { xoeyzqq: "x10ie11x xoeyzqq", $$css: !0 },
      L = { xoeyzqq: "xbbt9kl xoeyzqq", $$css: !0 };
    ((l.tonalSystem = u),
      (l.tonalLight = c),
      (l.tonalDark = d),
      (l.vibrantSystem = m),
      (l.vibrantLight = f),
      (l.vibrantDark = y),
      (l.bubbleLight = v),
      (l.bubbleDark = S),
      (l.bubbleTonalLight = R),
      (l.bubbleTonalDark = L));
  },
  98,
);
