__d(
  "ChatThemeBrown.stylex",
  ["WDSVars.stylex"],
  function (t, n, r, o, a, i, l) {
    "use strict";
    var e,
      s = "@media (prefers-color-scheme: dark)",
      u = { xoeyzqq: "xe562fs xoeyzqq", $$css: !0 },
      c = { xoeyzqq: "x1trtijr xoeyzqq", $$css: !0 },
      d = { xoeyzqq: "x1e8a8ka xoeyzqq", $$css: !0 },
      m = { xoeyzqq: "xlvcl93 xoeyzqq", $$css: !0 },
      p = {
        "--WDS-accent": (e = o("WDSVars.stylex")).WDSBaseColor.whiteOpaque,
        "--WDS-accent-deemphasized": e.WDSBaseColor.brown100,
        "--WDS-accent-emphasized": e.WDSBaseColor.brown700,
        "--WDS-content-action-emphasized": e.WDSBaseColor.whiteOpaque,
        "--WDS-content-external-link": e.WDSBaseColor.whiteOpaque,
        "--WDS-content-read": e.WDSBaseColor.cobalt300,
        "--WDS-systems-bubble-surface-incoming": e.WDSBaseColor.whiteOpaque,
        "--WDS-systems-bubble-surface-incoming-RGB": "255, 255, 255",
        "--WDS-systems-bubble-surface-outgoing": e.WDSBaseColor.brown500,
        "--WDS-systems-bubble-surface-outgoing-RGB": "158, 105, 71",
        "--WDS-systems-bubble-surface-overlay": e.WDSBaseColor.blackAlpha20,
        "--WDS-systems-bubble-surface-overlay-RGB": "0, 0, 0",
        "--WDS-systems-bubble-content-deemphasized":
          e.WDSBaseColor.whiteAlpha60,
      },
      _ = babelHelpers.extends({}, p, {
        "--WDS-systems-chat-foreground-wallpaper": "rgb(237, 212, 197)",
        "--WDS-systems-chat-background-wallpaper": e.WDSBaseColor.brown75,
        "--WDS-systems-chat-background-wallpaper-RGB": "252, 237, 227",
      }),
      f = { xoeyzqq: "x1iulfxs xoeyzqq", $$css: !0 },
      g = {
        "--WDS-accent": e.WDSBaseColor.whiteOpaque,
        "--WDS-accent-deemphasized": e.WDSBaseColor.brown700,
        "--WDS-accent-emphasized": e.WDSBaseColor.brown100,
        "--WDS-content-action-emphasized": e.WDSBaseColor.whiteOpaque,
        "--WDS-content-external-link": e.WDSBaseColor.whiteOpaque,
        "--WDS-content-read": "#2A91FD",
        "--WDS-systems-bubble-surface-incoming": e.WDSBaseColor.neutralGray800,
        "--WDS-systems-bubble-surface-incoming-RGB": "36, 38, 38",
        "--WDS-systems-bubble-surface-outgoing": "rgb(91, 60, 41)",
        "--WDS-systems-bubble-surface-outgoing-RGB": "91, 60, 41",
        "--WDS-systems-bubble-surface-overlay": e.WDSBaseColor.blackAlpha20,
        "--WDS-systems-bubble-surface-overlay-RGB": "0, 0, 0",
        "--WDS-systems-bubble-content-deemphasized":
          e.WDSBaseColor.whiteAlpha50,
      },
      h = babelHelpers.extends({}, g, {
        "--WDS-systems-chat-foreground-wallpaper": "rgb(25, 19, 16)",
        "--WDS-systems-chat-background-wallpaper":
          e.WDSBaseColor.neutralGray1000,
        "--WDS-systems-chat-background-wallpaper-RGB": "10, 10, 10",
      }),
      y = { xoeyzqq: "xddqhzp xoeyzqq", $$css: !0 },
      C = {
        "--WDS-accent": e.WDSBaseColor.brown500,
        "--WDS-accent-deemphasized": e.WDSBaseColor.brown100,
        "--WDS-accent-emphasized": e.WDSBaseColor.brown700,
        "--WDS-content-action-emphasized": e.WDSBaseColor.brown600,
        "--WDS-content-external-link": e.WDSBaseColor.brown600,
        "--WDS-content-read": e.WDSBaseColor.cobalt400,
        "--WDS-systems-bubble-surface-incoming": e.WDSBaseColor.whiteOpaque,
        "--WDS-systems-bubble-surface-incoming-RGB": "255, 255, 255",
        "--WDS-systems-bubble-surface-outgoing": e.WDSBaseColor.brown100,
        "--WDS-systems-bubble-surface-outgoing-RGB": "244, 222, 209",
        "--WDS-systems-bubble-surface-overlay":
          e.WDSBaseColor.warmGray300Alpha15,
        "--WDS-systems-bubble-surface-overlay-RGB": "194, 189, 184",
      },
      b = {
        "--WDS-accent": e.WDSBaseColor.brown400,
        "--WDS-accent-deemphasized": e.WDSBaseColor.brown700,
        "--WDS-accent-emphasized": e.WDSBaseColor.brown100,
        "--WDS-content-action-emphasized": e.WDSBaseColor.brown400,
        "--WDS-content-external-link": e.WDSBaseColor.brown400,
        "--WDS-content-read": e.WDSBaseColor.cobalt300,
        "--WDS-systems-bubble-surface-incoming": e.WDSBaseColor.neutralGray800,
        "--WDS-systems-bubble-surface-incoming-RGB": "36, 38, 38",
        "--WDS-systems-bubble-surface-outgoing": "rgb(53, 39, 30)",
        "--WDS-systems-bubble-surface-outgoing-RGB": "53, 39, 30",
        "--WDS-systems-bubble-surface-overlay": e.WDSBaseColor.blackAlpha20,
        "--WDS-systems-bubble-surface-overlay-RGB": "0, 0, 0",
      },
      v = { xoeyzqq: "x108wbd8 xoeyzqq", $$css: !0 },
      S = { xoeyzqq: "x1haog3q xoeyzqq", $$css: !0 },
      R = { xoeyzqq: "xrrhhhl xoeyzqq", $$css: !0 },
      L = { xoeyzqq: "x1txocx4 xoeyzqq", $$css: !0 };
    ((l.tonalSystem = u),
      (l.tonalLight = c),
      (l.tonalDark = d),
      (l.vibrantSystem = m),
      (l.vibrantLight = f),
      (l.vibrantDark = y),
      (l.bubbleLight = v),
      (l.bubbleDark = S),
      (l.bubbleTonalLight = R),
      (l.bubbleTonalDark = L));
  },
  98,
);
