__d(
  "ChatThemePink.stylex",
  ["WDSVars.stylex"],
  function (t, n, r, o, a, i, l) {
    "use strict";
    var e,
      s = "@media (prefers-color-scheme: dark)",
      u = { xoeyzqq: "xx6zxi6 xoeyzqq", $$css: !0 },
      c = { xoeyzqq: "xljdxys xoeyzqq", $$css: !0 },
      d = { xoeyzqq: "x1ua7wxf xoeyzqq", $$css: !0 },
      m = { xoeyzqq: "x47m3z7 xoeyzqq", $$css: !0 },
      p = {
        "--WDS-accent": (e = o("WDSVars.stylex")).WDSBaseColor.whiteOpaque,
        "--WDS-accent-deemphasized": "rgb(255, 235, 241)",
        "--WDS-accent-emphasized": "rgb(109, 30, 62)",
        "--WDS-content-action-emphasized": e.WDSBaseColor.whiteOpaque,
        "--WDS-content-external-link": e.WDSBaseColor.whiteOpaque,
        "--WDS-content-read": "#76B8FE",
        "--WDS-systems-bubble-surface-incoming": e.WDSBaseColor.whiteOpaque,
        "--WDS-systems-bubble-surface-incoming-RGB": "255, 255, 255",
        "--WDS-systems-bubble-surface-outgoing": "rgb(230, 51, 113)",
        "--WDS-systems-bubble-surface-outgoing-RGB": "230, 51, 113",
        "--WDS-systems-bubble-surface-overlay": e.WDSBaseColor.blackAlpha20,
        "--WDS-systems-bubble-surface-overlay-RGB": "0, 0, 0",
        "--WDS-systems-bubble-content-deemphasized":
          e.WDSBaseColor.whiteAlpha60,
      },
      _ = babelHelpers.extends({}, p, {
        "--WDS-systems-chat-foreground-wallpaper": "rgb(255, 218, 231)",
        "--WDS-systems-chat-background-wallpaper": "rgb(255, 235, 241)",
        "--WDS-systems-chat-background-wallpaper-RGB": "255, 235, 241",
      }),
      f = { xoeyzqq: "x1ftzjz5 xoeyzqq", $$css: !0 },
      g = {
        "--WDS-accent": e.WDSBaseColor.whiteOpaque,
        "--WDS-accent-deemphasized": "rgb(109, 30, 62)",
        "--WDS-accent-emphasized": "rgb(255, 235, 241)",
        "--WDS-content-action-emphasized": e.WDSBaseColor.whiteOpaque,
        "--WDS-content-external-link": e.WDSBaseColor.whiteOpaque,
        "--WDS-content-read": "#76B8FE",
        "--WDS-systems-bubble-surface-incoming": e.WDSBaseColor.neutralGray800,
        "--WDS-systems-bubble-surface-incoming-RGB": "36, 38, 38",
        "--WDS-systems-bubble-surface-outgoing": "rgb(188, 40, 93)",
        "--WDS-systems-bubble-surface-outgoing-RGB": "188, 40, 93",
        "--WDS-systems-bubble-surface-overlay": e.WDSBaseColor.blackAlpha20,
        "--WDS-systems-bubble-surface-overlay-RGB": "0, 0, 0",
        "--WDS-systems-bubble-content-deemphasized":
          e.WDSBaseColor.whiteAlpha50,
      },
      h = babelHelpers.extends({}, g, {
        "--WDS-systems-chat-foreground-wallpaper": "rgb(43, 18, 33)",
        "--WDS-systems-chat-background-wallpaper":
          e.WDSBaseColor.neutralGray1000,
        "--WDS-systems-chat-background-wallpaper-RGB": "10, 10, 10",
      }),
      y = { xoeyzqq: "xqnptxy xoeyzqq", $$css: !0 },
      C = {
        "--WDS-accent": "rgb(230, 51, 113)",
        "--WDS-accent-deemphasized": "rgb(255, 235, 241)",
        "--WDS-accent-emphasized": "rgb(109, 30, 62)",
        "--WDS-content-action-emphasized": "rgb(230, 51, 113)",
        "--WDS-content-external-link": "rgb(230, 51, 113)",
        "--WDS-content-read": e.WDSBaseColor.cobalt400,
        "--WDS-systems-bubble-surface-incoming": e.WDSBaseColor.whiteOpaque,
        "--WDS-systems-bubble-surface-incoming-RGB": "255, 255, 255",
        "--WDS-systems-bubble-surface-outgoing": "rgb(255, 218, 231)",
        "--WDS-systems-bubble-surface-outgoing-RGB": "255, 218, 231",
        "--WDS-systems-bubble-surface-overlay":
          e.WDSBaseColor.warmGray300Alpha15,
        "--WDS-systems-bubble-surface-overlay-RGB": "194, 189, 184",
      },
      b = {
        "--WDS-accent": "rgb(255, 81, 139)",
        "--WDS-accent-deemphasized": "rgb(109, 30, 62)",
        "--WDS-accent-emphasized": "rgb(255, 235, 241)",
        "--WDS-content-action-emphasized": "rgb(255, 81, 139)",
        "--WDS-content-external-link": "rgb(255, 81, 139)",
        "--WDS-content-read": e.WDSBaseColor.cobalt300,
        "--WDS-systems-bubble-surface-incoming": e.WDSBaseColor.neutralGray800,
        "--WDS-systems-bubble-surface-incoming-RGB": "36, 38, 38",
        "--WDS-systems-bubble-surface-outgoing": "rgb(87, 30, 53)",
        "--WDS-systems-bubble-surface-outgoing-RGB": "87, 30, 53",
        "--WDS-systems-bubble-surface-overlay": e.WDSBaseColor.blackAlpha20,
        "--WDS-systems-bubble-surface-overlay-RGB": "0, 0, 0",
      },
      v = { xoeyzqq: "xor0teu xoeyzqq", $$css: !0 },
      S = { xoeyzqq: "x196sl27 xoeyzqq", $$css: !0 },
      R = { xoeyzqq: "x9jq6to xoeyzqq", $$css: !0 },
      L = { xoeyzqq: "x1si84pr xoeyzqq", $$css: !0 };
    ((l.tonalSystem = u),
      (l.tonalLight = c),
      (l.tonalDark = d),
      (l.vibrantSystem = m),
      (l.vibrantLight = f),
      (l.vibrantDark = y),
      (l.bubbleLight = v),
      (l.bubbleDark = S),
      (l.bubbleTonalLight = R),
      (l.bubbleTonalDark = L));
  },
  98,
);
