__d(
  "CometRelay",
  [
    "CometRelayQueryProfiler",
    "RelayFBCometMutations",
    "RelayFBEnvironmentActorID",
    "RelayFBMatchContainer",
    "RelayFBModuleResource",
    "RelayFBSubscription",
    "configureRelayForWWW",
    "enqueueMutation",
    "isRelayFBLocalEnvironment",
    "react",
    "react-relay/relay-hooks/EntryPointContainer.react",
    "react-relay/relay-hooks/ProfilerContext",
    "react-relay/relay-hooks/RelayEnvironmentProvider",
    "react-relay/relay-hooks/loadEntryPoint",
    "react-relay/relay-hooks/loadQuery",
    "react-relay/relay-hooks/useClientQuery",
    "react-relay/relay-hooks/useEntryPointLoader",
    "react-relay/relay-hooks/useFragment",
    "react-relay/relay-hooks/useIsParentQueryActive",
    "react-relay/relay-hooks/useLazyLoadQuery",
    "react-relay/relay-hooks/usePaginationFragment",
    "react-relay/relay-hooks/usePrefetchableForwardPaginationFragment",
    "react-relay/relay-hooks/usePreloadedQuery",
    "react-relay/relay-hooks/useQueryLoader",
    "react-relay/relay-hooks/useRefetchableFragment",
    "react-relay/relay-hooks/useRelayEnvironment",
    "react-relay/relay-hooks/useSubscribeToInvalidationState",
    "relay-runtime",
    "useFBMutation",
    "useFBMutationWithTracing",
    "useFBSubscription",
  ],
  function (t, n, r, o, a, i, l) {
    "use strict";
    var e,
      s = e || (e = o("react")),
      u = r("RelayFBSubscription").addFBisms(
        o("relay-runtime").requestSubscription,
      );
    (r("configureRelayForWWW")(),
      o("CometRelayQueryProfiler").install(),
      (i.exports = {
        ConnectionHandler: o("relay-runtime").ConnectionHandler,
        EntryPointContainer: r(
          "react-relay/relay-hooks/EntryPointContainer.react",
        ),
        MatchContainer: r("RelayFBMatchContainer"),
        ModuleResource: {
          getModuleId: o("RelayFBModuleResource").getModuleId,
          load: o("RelayFBModuleResource").load,
          read: o("RelayFBModuleResource").read,
          readAll: o("RelayFBModuleResource").readAll,
        },
        MutationTypes: o("relay-runtime").MutationTypes,
        ProfilerContext: r("react-relay/relay-hooks/ProfilerContext"),
        RangeOperations: o("relay-runtime").RangeOperations,
        RelayEnvironmentProvider: r(
          "react-relay/relay-hooks/RelayEnvironmentProvider",
        ),
        RelayFeatureFlags: o("relay-runtime").RelayFeatureFlags,
        VIEWER_ID: o("relay-runtime").VIEWER_ID,
        applyOptimisticMutation: o("relay-runtime").applyOptimisticMutation,
        commitLocalUpdate: o("relay-runtime").commitLocalUpdate,
        commitMutation: o("RelayFBCometMutations").addFBisms(
          o("relay-runtime").commitMutation,
        ),
        createPayloadFor3DField: o("relay-runtime").createPayloadFor3DField,
        enqueueMutation: o("RelayFBCometMutations").addFBisms(
          o("enqueueMutation").enqueueMutation,
        ),
        fetchQuery: o("relay-runtime").fetchQuery,
        generateUniqueClientID: o("relay-runtime").generateUniqueClientID,
        getActorID: o("RelayFBEnvironmentActorID").getActorID,
        graphql: o("relay-runtime").graphql,
        isLocalEnvironment: r("isRelayFBLocalEnvironment"),
        loadEntryPoint: r("react-relay/relay-hooks/loadEntryPoint"),
        loadQuery: o("react-relay/relay-hooks/loadQuery").loadQuery,
        readInlineData: o("relay-runtime").readInlineData,
        requestSubscription: u,
        useClientQuery: r("react-relay/relay-hooks/useClientQuery"),
        useEntryPointLoader: r("react-relay/relay-hooks/useEntryPointLoader"),
        useFBMutationWithTracing: o("useFBMutationWithTracing")
          .useFBMutationWithTracing,
        useFragment: r("react-relay/relay-hooks/useFragment"),
        useIsParentQueryActive: r(
          "react-relay/relay-hooks/useIsParentQueryActive",
        ),
        useLazyLoadQuery: r("react-relay/relay-hooks/useLazyLoadQuery"),
        useMutation: r("useFBMutation"),
        usePaginationFragment: r(
          "react-relay/relay-hooks/usePaginationFragment",
        ),
        usePrefetchableForwardPaginationFragment: r(
          "react-relay/relay-hooks/usePrefetchableForwardPaginationFragment",
        ),
        usePreloadedQuery: r("react-relay/relay-hooks/usePreloadedQuery"),
        useQueryLoader: r("react-relay/relay-hooks/useQueryLoader"),
        useRefetchableFragment: r(
          "react-relay/relay-hooks/useRefetchableFragment",
        ),
        useRelayEnvironment: r("react-relay/relay-hooks/useRelayEnvironment"),
        useSubscribeToInvalidationState: r(
          "react-relay/relay-hooks/useSubscribeToInvalidationState",
        ),
        useSubscription: r("useFBSubscription"),
      }));
  },
  34,
);
