__d(
  "CometPreludeCritical",
  [
    "Bootloader",
    "CometPreludeCriticalRequireConds",
    "CometResourceScheduler",
    "DeferredJSResourceScheduler",
    "Env",
    "HasteResponse",
    "HasteSupportData",
    "JSScheduler",
    "ReactDOMServerExternalRuntime",
    "Run",
    "ScheduledApplyEach",
    "ScheduledServerJS",
    "ScheduledServerJSDefine",
    "ScheduledServerJSWithCSS",
    "ServerJS",
    "bootstrapWebSession",
    "maybeDisableAnimations",
    "qplAnnotationsIntServerJS",
    "qplAnnotationsStringServerJS",
    "qplTagServerJS",
    "qplTimingsServerJS",
    "replaceNativeTimer",
  ],
  function (t, n, r, o, a, i) {
    "use strict";
    var e, l;
    (n("Bootloader"),
      n("CometPreludeCriticalRequireConds"),
      n("CometResourceScheduler"),
      n("DeferredJSResourceScheduler"),
      e || (e = n("Env")),
      n("HasteResponse"),
      n("HasteSupportData"),
      l || (l = n("JSScheduler")),
      n("Run"),
      n("ScheduledApplyEach"),
      n("ScheduledServerJS"),
      n("ScheduledServerJSWithCSS"),
      n("ScheduledServerJSDefine"),
      n("ServerJS"),
      n("bootstrapWebSession"),
      n("replaceNativeTimer"),
      n("qplTimingsServerJS"),
      n("qplTagServerJS"),
      n("qplAnnotationsIntServerJS"),
      n("qplAnnotationsStringServerJS"),
      n("maybeDisableAnimations"),
      n("ReactDOMServerExternalRuntime"));
  },
  null,
);
