__d(
  "CometUJLClickInteraction",
  ["CometUserJourneyLogger", "decodeTrackingNode"],
  function (t, n, r, o, a, i, l) {
    "use strict";
    var e = {
        1: "headline",
        3: "actor_photo",
        4: "action_links",
        5: "like",
        6: "unlike",
        10: "title",
        12: "photo",
        13: "video",
        14: "music",
        15: "attachment",
        17: "share",
        18: "story_text",
        19: "subtitle",
        20: "description",
        24: "view_all_comments",
        25: "comment",
        26: "comment_link",
        28: "substory",
        29: "xbutton",
        35: "app_cta",
        36: "ufi",
        41: "ad_extensions_card",
        42: "fan_page",
        43: "unfan_page",
        44: "see_more",
        50: "page_link",
        51: "social_context",
        55: "dropdown_button",
        69: "profile",
        82: "snowlift",
        85: "rhc_link_open",
        86: "cta_button",
        90: "hashtag",
        97: "sponsored_context",
        99: "story_footer",
        100: "story_location",
        107: "photo_gallery",
        109: "feedback_section",
        110: "album",
        111: "album_collage",
        114: "media_controls",
        119: "like_count",
        125: "attachment_title",
        132: "permalink",
        137: "show_likes",
        141: "close_button",
        144: "fullscreen_button",
        148: "view_all_shares",
        149: "thumbnail_link",
        163: "options_menu",
        185: "video_in_play_cta_button",
        186: "video_endscreen_cta",
        188: "video_endscreen_replay",
        191: "save_button",
        206: "video_pausescreen_resume",
        210: "video_cta_attachment",
        215: "lead_gen_popover",
        216: "lead_gen_submit",
        217: "lead_gen_privacy",
        218: "lead_gen_offsite",
        225: "translation",
        229: "story_timestamp",
        230: "story_header",
        231: "sponsored_story",
        237: "carousel_card_story",
        240: "instream_cta_button",
        241: "instream_cta_attachment",
        250: "hovercard",
        252: "political_ad_header",
        257: "video_settings",
        259: "attachment_footer",
        260: "lead_gen_thank_you",
        301: "story",
        304: "link",
        305: "attachment_follow",
        306: "snowflake_story",
        307: "snowflake_photo",
        312: "profile_link",
        316: "reaction_browser",
        337: "instant_experience_link",
        339: "comment_action",
        340: "attached_story",
        391: "aggregated_story",
        425: "product_tag",
        429: "view_products",
        430: "user_tag",
        442: "cta_margin_area",
        444: "shops_product",
        445: "shops_footer",
        456: "media_to_destination",
        461: "reels_like_floating_cta",
        462: "reels_comment_floating_cta",
        463: "reels_profile_floating_cta",
        464: "floating_cta_on_profile",
        467: "reels_post_loop_context_card",
        468: "reels_post_loop_deferred_card",
        469: "collection_product_tile",
        473: "inline_comment",
        479: "shop_tile",
        482: "reels",
        483: "reels_banner_ad",
        487: "reels_banner_ad_profile",
        495: "reels_ads_end_scene",
        525: "ads_product_page",
        526: "ads_text_overlay",
        527: "floating_cta_on_comments",
        528: "reels_hscroll",
        535: "floating_cta_on_permalink",
        536: "reels_multi_card_end",
        537: "reels_swipe_left",
        538: "collection_tile",
        539: "collection_hscroll_tile",
        540: "hide_ad",
        541: "report_ad",
        549: "collection_hero_media",
        550: "floating_cta_on_group",
        552: "ufi_copy_link",
        557: "ad_action_chip",
        558: "mute",
        559: "expand_to_fullscreen",
        560: "three_dots",
        561: "comment_timestamp",
        562: "sponsored_label",
        563: "undo",
        564: "reels_tooltip_cta",
        565: "reels_caption_browse",
        566: "reels_ads_long_press",
        567: "profile_tab_product_tile",
        568: "reels_ads_creative",
        569: "video_highlights",
        570: "video_endscene_card",
        572: "dynamic_landing_page",
        573: "dynamic_landing_page_cta",
        585: "reels_ads_post_scroll",
        587: "product_recommender_tile",
        589: "destination_automation_landing_page",
        592: "play_pause",
        595: "reels_single_image",
        596: "reels_mid_scene_cta",
        597: "reels_multiads_media",
        598: "reels_profile_browse",
        604: "reels_end_scene_cta",
        605: "see_less",
        613: "reels_scrubber_swipe_up",
        614: "reels_product_extensions",
        634: "reels_image_cta",
        642: "feed_ads_long_press",
        643: "instant_experience_product",
        646: "reels_product_extensions_end_scene",
        648: "reels_cta_long_press",
        649: "reels_midscene_long_press",
        658: "reels_ads_post_scroll_cta",
        669: "reels_ads_action_chip",
        672: "reels_single_image_expansion",
        681: "reels_ads_pill_cta",
      },
      s = 132;
    function u(e) {
      var t = r("decodeTrackingNode")(e);
      return t.length === 1 ? null : t[1][0];
    }
    function c(t, n, o, a) {
      var i;
      if (t.length !== 0) {
        var l = u(t[0]);
        if (l != null) {
          if (l === s && t.length > 1) {
            var c = u(t[1]);
            c != null && (l = c);
          }
          var d = (i = e[l]) != null ? i : "ad",
            m = d + "_clicked";
          (r("CometUserJourneyLogger").journeyPublishPoint(m, a),
            n != null &&
              o != null &&
              (r("CometUserJourneyLogger").journeyPublishPointAnnotationInt(
                m,
                "click_x",
                Math.round(n),
                a,
              ),
              r("CometUserJourneyLogger").journeyPublishPointAnnotationInt(
                m,
                "click_y",
                Math.round(o),
                a,
              )));
        }
      }
    }
    var d = { logClick: c };
    l.default = d;
  },
  98,
);
