__d(
  "CommerceManagerSidebarTabKey",
  [],
  function (t, n, r, o, a, i) {
    var e = Object.freeze({
      AD_INSIGHTS: "ad_insights",
      ADS_MANAGER: "ads_manager",
      AM_ACCOUNT_OVERVIEW: "am_account_overview",
      AM_ADS_REPORTING: "am_ads_reporting",
      AM_ADVERTISING_SETTINGS: "am_advertising_settings",
      AM_AUDIENCE: "am_audience",
      AM_BILLING_AND_PAYMENTS: "am_billing_and_payments",
      AM_CAMPAIGNS: "am_campaigns",
      AM_EVENTS_MANAGER: "am_events_manager",
      AUDIENCE: "audience",
      COMMUNITY_CONTENT: "community_content",
      DATA_SOURCES: "data_sources",
      DISCOUNTS: "discounts",
      DISPUTES: "disputes",
      ENTRY_POINTS: "entry_points",
      EVENTS: "events",
      HOME: "home",
      INSIGHTS: "insights",
      INSIGHTS_MARKETPLACE: "insights_marketplace",
      INSIGHTS_OVERVIEW: "insights_overview",
      INSIGHTS_PERFORMANCE: "insights_performance",
      INSIGHTS_PRODUCTS: "insights_products",
      MAILING_LIST: "mailing_list",
      ORDERS: "orders",
      PERFORMANCE: "performance",
      PERMISSIONS: "permissions",
      PRODUCT_TAGGED_CONTENT: "product_tagged_content",
      PRODUCTS: "products",
      PROMOTIONS: "promotions",
      QUESTIONS_AND_ANSWERS: "questions_and_answers",
      RATINGS_AND_REVIEWS: "ratings_and_reviews",
      RETURNS: "returns",
      SETS: "sets",
      SETTINGS: "settings",
      SHOP_BUILDER: "shop_builder",
      SHOPS_UPSELL: "shops_upsell",
      SUPPORT: "support",
      TEMPLATES_V2: "templates_v2",
      TO_DO_LIST: "to_do_list",
      VIDEO_GALLERY: "video_gallery",
      VIDEO_TEMPLATE_HUB: "video_template_hub",
    });
    i.default = e;
  },
  66,
);
