__d(
  "CoreWebBloksComponents",
  [
    "WebBloksCDSBottomSheetWrapper",
    "WebBloksCanvas",
    "WebBloksCollection",
    "WebBloksDatetimeTextProvider",
    "WebBloksDialog",
    "WebBloksDialogButton",
    "WebBloksDummyComponent",
    "WebBloksFieldset",
    "WebBloksFlexbox",
    "WebBloksGlimmer",
    "WebBloksImage",
    "WebBloksInternalAction",
    "WebBloksMergeWithBind",
    "WebBloksNavbar",
    "WebBloksOnMount",
    "WebBloksPullToRefreshContainer",
    "WebBloksRichText",
    "WebBloksScreenWrapperPrimitive",
    "WebBloksSlider",
    "WebBloksSwitch",
    "WebBloksText",
    "WebBloksTextInput",
    "WebBloksTextSpan",
    "WebBloksTransitionContainer",
    "WebBloksZoomable",
  ],
  function (t, n, r, o, a, i, l) {
    var e,
      s = {
        "bk.cds.bottomsheet.Wrapper": r("WebBloksCDSBottomSheetWrapper"),
        "bk.component.TransitionContainer": r("WebBloksTransitionContainer"),
        "bk.components.Canvas": r("WebBloksCanvas"),
        "bk.components.Collection": r("WebBloksCollection"),
        "bk.components.DatetimeTextProvider": r("WebBloksDatetimeTextProvider"),
        "bk.components.Flexbox": r("WebBloksFlexbox"),
        "bk.components.Glimmer": r("WebBloksGlimmer"),
        "bk.components.Image": r("WebBloksImage"),
        "bk.components.OnMount": r("WebBloksOnMount"),
        "bk.components.PullToRefreshContainer": r(
          "WebBloksPullToRefreshContainer",
        ),
        "bk.components.RichText": r("WebBloksRichText"),
        "bk.components.Slider": r("WebBloksSlider"),
        "bk.components.Switch": r("WebBloksSwitch"),
        "bk.components.Text": r("WebBloksText"),
        "bk.components.TextInput": r("WebBloksTextInput"),
        "bk.components.TextSpan": r("WebBloksTextSpan"),
        "bk.components.Video": (e = r("WebBloksDummyComponent")),
        "bk.components.VideoVersion": e,
        "bk.components.Zoomable": r("WebBloksZoomable"),
        "bk.components.dialog.Button": r("WebBloksDialogButton"),
        "bk.components.dialog.Dialog": r("WebBloksDialog"),
        "bk.components.internal.Action": r("WebBloksInternalAction"),
        "bk.components.internal.Merge": e,
        "bk.components.internal.MergeWithBind": r("WebBloksMergeWithBind"),
        "bk.components.internal.Shadow": e,
        "bk.components.screen.Wrapper": r("WebBloksScreenWrapperPrimitive"),
        "bk.components.webbloks.Fieldset": r("WebBloksFieldset"),
        "bk.data.screen.Navbar": r("WebBloksNavbar"),
      };
    l.COMPONENTS = s;
  },
  98,
);
