__d(
  "CoreWebBloksComponents",
  [
    "WebBloksCDSBottomSheetWrapper",
    "WebBloksCanvas",
    "WebBloksCollection",
    "WebBloksDatetimeTextProvider",
    "WebBloksDialog",
    "WebBloksDialogButton",
    "WebBloksDummyComponent",
    "WebBloksFieldset",
    "WebBloksFixedWrapper",
    "WebBloksFlexbox",
    "WebBloksGlimmer",
    "WebBloksImage",
    "WebBloksInternalAction",
    "WebBloksMergeWithBind",
    "WebBloksNavbar",
    "WebBloksOnMount",
    "WebBloksPullToRefreshContainer",
    "WebBloksRichText",
    "WebBloksScreenWrapperPrimitive",
    "WebBloksSlider",
    "WebBloksSwitch",
    "WebBloksText",
    "WebBloksTextInput",
    "WebBloksTextSpan",
    "WebBloksTransitionContainer",
    "WebBloksZoomable",
  ],
  function (t, n, r, o, a, i, l) {
    var e,
      s = {
        "bk.components.VideoVersion": (e = r("WebBloksDummyComponent")),
        㐅: r("WebBloksCollection"),
        㐇: r("WebBloksDatetimeTextProvider"),
        㐈: r("WebBloksFlexbox"),
        㐋: r("WebBloksImage"),
        㐏: r("WebBloksPullToRefreshContainer"),
        㐑: r("WebBloksRichText"),
        㐖: r("WebBloksSwitch"),
        㐗: r("WebBloksText"),
        㐘: r("WebBloksTextInput"),
        㐛: r("WebBloksTextSpan"),
        㐟: r("WebBloksInternalAction"),
        㐢: e,
        㐣: e,
        㗙: r("WebBloksNavbar"),
        㗠: r("WebBloksGlimmer"),
        㗥: r("WebBloksTransitionContainer"),
        㗧: r("WebBloksDialog"),
        㗨: r("WebBloksDialogButton"),
        㙚: r("WebBloksOnMount"),
        㚞: r("WebBloksScreenWrapperPrimitive"),
        㜍: r("WebBloksCDSBottomSheetWrapper"),
        㶘: e,
        㼠: r("WebBloksSlider"),
        㾄: r("WebBloksZoomable"),
        䃊: r("WebBloksCanvas"),
        䇓: r("WebBloksMergeWithBind"),
        䍩: r("WebBloksFieldset"),
        摌: r("WebBloksFixedWrapper"),
      };
    l.COMPONENTS = s;
  },
  98,
);
