__d(
  "CoreWebBloksComponents",
  [
    "WebBloksCDSBottomSheetWrapper",
    "WebBloksCanvas",
    "WebBloksCollection",
    "WebBloksDatetimeTextProvider",
    "WebBloksDialog",
    "WebBloksDialogButton",
    "WebBloksDummyComponent",
    "WebBloksFieldset",
    "WebBloksFixedWrapper",
    "WebBloksFlexbox",
    "WebBloksGlimmer",
    "WebBloksImage",
    "WebBloksInternalAction",
    "WebBloksMergeWithBind",
    "WebBloksNavbar",
    "WebBloksOnMount",
    "WebBloksPullToRefreshContainer",
    "WebBloksRichText",
    "WebBloksScreenWrapperPrimitive",
    "WebBloksSlider",
    "WebBloksSwitch",
    "WebBloksText",
    "WebBloksTextInput",
    "WebBloksTextSpan",
    "WebBloksTransitionContainer",
    "WebBloksZoomable",
  ],
  function (t, n, r, o, a, i, l) {
    var e = {
      㜍: r("WebBloksCDSBottomSheetWrapper"),
      㗥: r("WebBloksTransitionContainer"),
      䃊: r("WebBloksCanvas"),
      㐅: r("WebBloksCollection"),
      㐇: r("WebBloksDatetimeTextProvider"),
      㐈: r("WebBloksFlexbox"),
      㗠: r("WebBloksGlimmer"),
      㐋: r("WebBloksImage"),
      㙚: r("WebBloksOnMount"),
      㐏: r("WebBloksPullToRefreshContainer"),
      㐑: r("WebBloksRichText"),
      㼠: r("WebBloksSlider"),
      㐖: r("WebBloksSwitch"),
      㐗: r("WebBloksText"),
      㐘: r("WebBloksTextInput"),
      㐛: r("WebBloksTextSpan"),
      㶘: r("WebBloksDummyComponent"),
      㾄: r("WebBloksZoomable"),
      㗨: r("WebBloksDialogButton"),
      㗧: r("WebBloksDialog"),
      㐟: r("WebBloksInternalAction"),
      㐢: r("WebBloksDummyComponent"),
      䇓: r("WebBloksMergeWithBind"),
      㐣: r("WebBloksDummyComponent"),
      㚞: r("WebBloksScreenWrapperPrimitive"),
      䍩: r("WebBloksFieldset"),
      摌: r("WebBloksFixedWrapper"),
      㗙: r("WebBloksNavbar"),
    };
    l.COMPONENTS = e;
  },
  98,
);
