__d(
  "DynamicCreativeOptimizationDoFType",
  [],
  function (t, n, r, o, a, i) {
    var e = Object.freeze({
      DISABLED: "DISABLED",
      USER_ENROLLED_AUTOFLOW: "USER_ENROLLED_AUTOFLOW",
      USER_ENROLLED_LWI_ACO: "USER_ENROLLED_LWI_ACO",
      USER_ENROLLED_NON_DCO: "USER_ENROLLED_NON_DCO",
      USER_ENROLLED_IMAGE_CROPPING_NON_DCO:
        "USER_ENROLLED_IMAGE_CROPPING_NON_DCO",
      USER_ENROLLED: "USER_ENROLLED",
      VIDEO_TEMPLATES: "VIDEO_TEMPLATES",
      FAM_TOGGLE_ON: "FAM_TOGGLE_ON",
      FAM_TOGGLE_OFF: "FAM_TOGGLE_OFF",
      SMART_CROP_ELIGIBLE_ON: "SMART_CROP_ELIGIBLE_ON",
      SMART_CROP_ELIGIBLE_OFF: "SMART_CROP_ELIGIBLE_OFF",
      SMART_CROP_INELIGIBLE_ON: "SMART_CROP_INELIGIBLE_ON",
      SMART_CROP_INELIGIBLE_OFF: "SMART_CROP_INELIGIBLE_OFF",
      VCK_MIXED_FORMAT: "VCK_MIXED_FORMAT",
    });
    i.default = e;
  },
  66,
);
