__d(
  "EBMinosWasm.pb",
  ["WAProtoConst"],
  function (t, n, r, o, a, i, l) {
    var e,
      s = {},
      u = {},
      c = {},
      d = {},
      m = {},
      p = {},
      _ = {},
      f = {},
      g = {},
      h = {},
      y = {},
      C = {},
      b = {},
      v = {},
      S = {},
      R = {},
      L = {},
      E = {},
      k = {},
      I = {},
      T = {},
      D = {},
      x = {},
      $ = {},
      P = {},
      N = {},
      M = {},
      w = {},
      A = {},
      F = {},
      O = {},
      B = {},
      W = {},
      q = {},
      U = {},
      V = {},
      H = {},
      G = {},
      z = {},
      j = {},
      K = {},
      Q = {},
      X = {},
      Y = {},
      J = {},
      Z = {},
      ee = {},
      te = {},
      ne = {},
      re = {},
      oe = {},
      ae = {},
      ie = {},
      le = {},
      se = {},
      ue = {},
      ce = {},
      de = {},
      me = {},
      pe = {},
      _e = {},
      fe = {},
      ge = {},
      he = {},
      ye = {},
      Ce = {},
      be = {},
      ve = {},
      Se = {},
      Re = {},
      Le = {},
      Ee = {},
      ke = {},
      Ie = {},
      Te = {},
      De = {},
      xe = {},
      $e = {},
      Pe = {},
      Ne = {},
      Me = {},
      we = {},
      Ae = {},
      Fe = {},
      Oe = {},
      Be = {},
      We = {},
      qe = {},
      Ue = {},
      Ve = {},
      He = {},
      Ge = {};
    ((s.name = "MinosMessageMetadata"),
      (s.internalSpec = {
        mekId: [1, (e = o("WAProtoConst")).FLAGS.REQUIRED | e.TYPES.BYTES],
        timestamp: [2, e.FLAGS.REQUIRED | e.TYPES.UINT64],
        messageId: [3, e.FLAGS.REQUIRED | e.TYPES.STRING],
        threadId: [4, e.FLAGS.REQUIRED | e.TYPES.BYTES],
      }),
      (u.name = "MinosClientConfig"),
      (u.internalSpec = {
        preferredMessageEncryptionVersion: [
          1,
          e.FLAGS.REQUIRED | e.TYPES.INT32,
        ],
        preferredMekEncryptionVersion: [2, e.FLAGS.REQUIRED | e.TYPES.INT32],
      }),
      (c.name = "MinosEncryptAndSignMessageInput"),
      (c.internalSpec = {
        transportSigningSk: [1, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        mek: [2, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        plaintext: [3, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        metadata: [4, e.FLAGS.REQUIRED | e.TYPES.MESSAGE, s],
        transportSigningPk: [5, e.TYPES.BYTES],
        conf: [6, e.TYPES.MESSAGE, u],
      }),
      (d.name = "MinosEncryptAndSignMessageResult"),
      (d.internalSpec = {
        ciphertext: [1, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        signature: [2, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        version: [3, e.FLAGS.REQUIRED | e.TYPES.INT32],
      }),
      (m.name = "MinosDecryptAndVerifyMessageInput"),
      (m.internalSpec = {
        transportSigningPk: [1, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        mek: [2, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        encryptedMessageCiphertext: [3, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        encryptedMessageSignature: [4, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        metadata: [5, e.FLAGS.REQUIRED | e.TYPES.MESSAGE, s],
        messageEncryptionVersion: [6, e.TYPES.INT32],
        conf: [7, e.TYPES.MESSAGE, u],
      }),
      (p.name = "MinosDecryptAndVerifyMessageResult"),
      (p.internalSpec = {
        success: [1, e.TYPES.MESSAGE, _],
        errorMessage: [2, e.TYPES.STRING],
        __oneofs__: { result: ["success", "errorMessage"] },
      }),
      (_.name = "MinosDecryptAndVerifyMessageSuccess"),
      (_.internalSpec = { plaintext: [1, e.FLAGS.REQUIRED | e.TYPES.BYTES] }),
      (f.name = "MekBundle"),
      (f.internalSpec = {
        key: [1, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        mekId: [2, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        rosterHash: [3, e.FLAGS.REQUIRED | e.TYPES.BYTES],
      }),
      (g.name = "GenerateMekInput"),
      (g.internalSpec = { epochHeads: [1, e.FLAGS.REPEATED | e.TYPES.BYTES] }),
      (h.name = "GenerateMekResult"),
      (h.internalSpec = { mek: [1, e.FLAGS.REQUIRED | e.TYPES.MESSAGE, f] }),
      (y.name = "GenerateMekRosterHashInput"),
      (y.internalSpec = { epochHeads: [1, e.FLAGS.REPEATED | e.TYPES.BYTES] }),
      (C.name = "GenerateMekRosterHashResult"),
      (C.internalSpec = { rosterHash: [1, e.FLAGS.REQUIRED | e.TYPES.BYTES] }),
      (b.name = "EncryptMekForDistributionInput"),
      (b.internalSpec = {
        senderEpochHead: [1, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        toMailboxPk: [2, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        fromKeypair: [3, e.FLAGS.REQUIRED | e.TYPES.MESSAGE, v],
        mek: [4, e.FLAGS.REQUIRED | e.TYPES.MESSAGE, f],
        toEpochHead: [5, e.TYPES.BYTES],
        conf: [6, e.TYPES.MESSAGE, u],
      }),
      (v.name = "EncryptMekForDistributionInput$MailboxAuthKP"),
      (v.internalSpec = {
        sk: [1, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        pk: [2, e.FLAGS.REQUIRED | e.TYPES.BYTES],
      }),
      (S.name = "EncryptMekForDistributionResult"),
      (S.internalSpec = {
        ciphertext: [1, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        version: [2, e.FLAGS.REQUIRED | e.TYPES.UINT64],
      }),
      (R.name = "DecryptMekForDistributionInput"),
      (R.internalSpec = {
        toMailboxSk: [1, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        fromPk: [2, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        mekId: [3, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        senderEpochHead: [4, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        rosterHash: [5, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        ciphertext: [6, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        toEpochHead: [7, e.TYPES.BYTES],
        mekEncryptionVersion: [8, e.TYPES.INT32],
        conf: [9, e.TYPES.MESSAGE, u],
      }),
      (L.name = "DecryptMekForDistributionResult"),
      (L.internalSpec = {
        success: [1, e.TYPES.MESSAGE, E],
        errorMessage: [2, e.TYPES.STRING],
        __oneofs__: { result: ["success", "errorMessage"] },
      }),
      (E.name = "DecryptMekForDistributionSuccess"),
      (E.internalSpec = { mek: [1, e.FLAGS.REQUIRED | e.TYPES.BYTES] }),
      (k.name = "EncryptMeksForDistributionFromTransportSenderInput"),
      (k.internalSpec = {
        mek: [1, e.FLAGS.REQUIRED | e.TYPES.MESSAGE, f],
        transportSigningKp: [2, e.FLAGS.REQUIRED | e.TYPES.MESSAGE, I],
        recipientMailboxEncryptionPks: [3, e.FLAGS.REPEATED | e.TYPES.BYTES],
        recipientEpochHeads: [4, e.FLAGS.REPEATED | e.TYPES.BYTES],
        conf: [5, e.TYPES.MESSAGE, u],
      }),
      (I.name =
        "EncryptMeksForDistributionFromTransportSenderInput$TransportSigningKP"),
      (I.internalSpec = {
        sk: [1, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        pk: [2, e.FLAGS.REQUIRED | e.TYPES.BYTES],
      }),
      (T.name = "EncryptMeksForDistributionFromTransportSenderResult"),
      (T.internalSpec = {
        encryptedMeks: [1, e.FLAGS.REPEATED | e.TYPES.BYTES],
        ephemeralEncryptionPk: [2, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        signingPk: [3, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        signature: [4, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        version: [5, e.FLAGS.REQUIRED | e.TYPES.UINT64],
      }),
      (D.name = "DecryptMekForDistributionFromTransportSenderInput"),
      (D.internalSpec = {
        mekDistribution: [1, e.FLAGS.REQUIRED | e.TYPES.MESSAGE, x],
        mekId: [2, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        rosterHash: [3, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        recipientEncSk: [4, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        version: [5, e.FLAGS.REQUIRED | e.TYPES.UINT64],
        conf: [6, e.TYPES.MESSAGE, u],
      }),
      (x.name =
        "DecryptMekForDistributionFromTransportSenderInput$TransportSenderMEKDistributionSingleRecipient"),
      (x.internalSpec = {
        encryptedMek: [1, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        ephemeralEncryptionPk: [2, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        signingPk: [3, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        signature: [4, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        recipientEpochHead: [5, e.TYPES.BYTES],
      }),
      ($.name = "DecryptMekForDistributionFromTransportSenderResult"),
      ($.internalSpec = {
        success: [1, e.TYPES.MESSAGE, P],
        errorMessage: [2, e.TYPES.STRING],
        __oneofs__: { result: ["success", "errorMessage"] },
      }),
      (P.name = "DecryptMekForDistributionFromTransportSenderSuccess"),
      (P.internalSpec = { mek: [1, e.FLAGS.REQUIRED | e.TYPES.BYTES] }),
      (N.name = "WrapTransportSigningPublicKeyInput"),
      (N.internalSpec = { keyBytes: [1, e.FLAGS.REQUIRED | e.TYPES.BYTES] }),
      (M.name = "WrapTransportSigningPublicKeyResult"),
      (M.internalSpec = { prefixedKey: [1, e.FLAGS.REQUIRED | e.TYPES.BYTES] }),
      (w.name = "WrapTransportSigningSecretKeyInput"),
      (w.internalSpec = { keyBytes: [1, e.FLAGS.REQUIRED | e.TYPES.BYTES] }),
      (A.name = "WrapTransportSigningSecretKeyResult"),
      (A.internalSpec = { prefixedKey: [1, e.FLAGS.REQUIRED | e.TYPES.BYTES] }),
      (F.name = "DeriveMailboxSigningKeypairInput"),
      (F.internalSpec = {
        exportRootKey: [1, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        epochNumber: [2, e.FLAGS.REQUIRED | e.TYPES.UINT64],
      }),
      (O.name = "DeriveMailboxSigningKeypairResult"),
      (O.internalSpec = {
        success: [1, e.TYPES.MESSAGE, B],
        errorMessage: [2, e.TYPES.STRING],
        __oneofs__: { result: ["success", "errorMessage"] },
      }),
      (B.name = "DeriveMailboxSigningKeypairSuccess"),
      (B.internalSpec = {
        mailboxSigningPublicKey: [1, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        mailboxSigningPrivateKey: [2, e.FLAGS.REQUIRED | e.TYPES.BYTES],
      }),
      (W.name = "DeriveMailboxEncryptionKeypairInput"),
      (W.internalSpec = {
        exportRootKey: [1, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        epochNumber: [2, e.FLAGS.REQUIRED | e.TYPES.UINT64],
      }),
      (q.name = "DeriveMailboxEncryptionKeypairResult"),
      (q.internalSpec = {
        mailboxEncryptionPublicKey: [1, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        mailboxEncryptionPrivateKey: [2, e.FLAGS.REQUIRED | e.TYPES.BYTES],
      }),
      (U.name = "DeriveMailboxAuthKeypairInput"),
      (U.internalSpec = {
        exportRootKey: [1, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        epochNumber: [2, e.FLAGS.REQUIRED | e.TYPES.UINT64],
      }),
      (V.name = "DeriveMailboxAuthKeypairResult"),
      (V.internalSpec = {
        mailboxAuthPublicKey: [1, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        mailboxAuthPrivateKey: [2, e.FLAGS.REQUIRED | e.TYPES.BYTES],
      }),
      (H.name = "DeriveAttachmentAccessTokenSecretInput"),
      (H.internalSpec = { mediaKey: [1, e.FLAGS.REQUIRED | e.TYPES.BYTES] }),
      (G.name = "DeriveAttachmentAccessTokenSecretResult"),
      (G.internalSpec = {
        attachmentAccessTokenSecret: [1, e.FLAGS.REQUIRED | e.TYPES.BYTES],
      }),
      (z.name = "DeriveAttachmentPrimaryKeySecretInput"),
      (z.internalSpec = { mediaKey: [1, e.FLAGS.REQUIRED | e.TYPES.BYTES] }),
      (j.name = "DeriveAttachmentPrimaryKeySecretResult"),
      (j.internalSpec = {
        attachmentPrimaryKeySecret: [1, e.FLAGS.REQUIRED | e.TYPES.BYTES],
      }),
      (K.name = "EpochPublicData"),
      (K.internalSpec = {
        epochNumber: [1, e.FLAGS.REQUIRED | e.TYPES.UINT64],
        userFbid: [2, e.FLAGS.REQUIRED | e.TYPES.STRING],
        mailboxSigningPk: [3, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        mailboxEncryptionPk: [4, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        mailboxAuthPk: [5, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        previousEpochHead: [6, e.TYPES.BYTES],
      }),
      (Q.name = "EpochSignatures"),
      (Q.internalSpec = {
        selfSignature: [1, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        prevSignature: [2, e.TYPES.BYTES],
      }),
      (X.name = "MinosSignedEpoch"),
      (X.internalSpec = {
        epochPublicData: [1, e.FLAGS.REQUIRED | e.TYPES.MESSAGE, K],
        signatures: [2, e.FLAGS.REQUIRED | e.TYPES.MESSAGE, Q],
        epochHead: [3, e.FLAGS.REQUIRED | e.TYPES.BYTES],
      }),
      (Y.name = "MinosOpenInitialEpochInput"),
      (Y.internalSpec = {
        userFbid: [1, e.FLAGS.REQUIRED | e.TYPES.STRING],
        epochNumber: [2, e.FLAGS.REQUIRED | e.TYPES.UINT64],
        exportRootKey: [3, e.FLAGS.REQUIRED | e.TYPES.BYTES],
      }),
      (J.name = "MinosOpenInitialEpochResult"),
      (J.internalSpec = {
        minosSignedEpoch: [1, e.FLAGS.REQUIRED | e.TYPES.MESSAGE, X],
      }),
      (Z.name = "MinosOpenEpochInput"),
      (Z.internalSpec = {
        userFbid: [1, e.FLAGS.REQUIRED | e.TYPES.STRING],
        epochNumber: [2, e.FLAGS.REQUIRED | e.TYPES.UINT64],
        exportRootKey: [3, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        previousExportRootKey: [4, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        previousEpochNumber: [5, e.FLAGS.REQUIRED | e.TYPES.UINT64],
        previousEpochHead: [6, e.FLAGS.REQUIRED | e.TYPES.BYTES],
      }),
      (ee.name = "MinosOpenEpochResult"),
      (ee.internalSpec = {
        minosSignedEpoch: [1, e.FLAGS.REQUIRED | e.TYPES.MESSAGE, X],
      }),
      (te.name = "MinosValidateEpochInput"),
      (te.internalSpec = {
        epochPublicData: [1, e.FLAGS.REQUIRED | e.TYPES.MESSAGE, K],
        previousEpochPublicData: [2, e.FLAGS.REQUIRED | e.TYPES.MESSAGE, K],
        signatures: [3, e.FLAGS.REQUIRED | e.TYPES.MESSAGE, Q],
      }),
      (ne.name = "MinosValidateEpochResult"),
      (ne.internalSpec = {
        valid: [1, e.TYPES.BOOL],
        errorMessage: [2, e.TYPES.STRING],
        __oneofs__: { result: ["valid", "errorMessage"] },
      }),
      (re.name = "MinosVerifySingleEpochInput"),
      (re.internalSpec = {
        epochPublicData: [1, e.FLAGS.REQUIRED | e.TYPES.MESSAGE, K],
        signature: [2, e.FLAGS.REQUIRED | e.TYPES.BYTES],
      }),
      (oe.name = "MinosVerifySingleEpochResult"),
      (oe.internalSpec = { valid: [1, e.FLAGS.REQUIRED | e.TYPES.BOOL] }),
      (ae.name = "MinosThreadIdFromOneToOneThreadInput"),
      (ae.internalSpec = {
        actThreadId: [1, e.FLAGS.REQUIRED | e.TYPES.STRING],
        selfFbid: [2, e.FLAGS.REQUIRED | e.TYPES.STRING],
      }),
      (ie.name = "MinosThreadIdFromOneToOneThreadResult"),
      (ie.internalSpec = { threadId: [1, e.FLAGS.REQUIRED | e.TYPES.BYTES] }),
      (le.name = "MinosThreadIdFromActThreadIdInput"),
      (le.internalSpec = {
        actThreadId: [1, e.FLAGS.REQUIRED | e.TYPES.STRING],
      }),
      (se.name = "MinosThreadIdFromActThreadIdResult"),
      (se.internalSpec = { threadId: [1, e.FLAGS.REQUIRED | e.TYPES.BYTES] }),
      (ue.name = "MessagingMailboxPublicData"),
      (ue.internalSpec = {
        epochHead: [1, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        deviceRosterHash: [2, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        sequenceNumber: [3, e.FLAGS.REQUIRED | e.TYPES.UINT64],
        sigPk: [4, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        encPk: [5, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        authPk: [6, e.FLAGS.REQUIRED | e.TYPES.BYTES],
      }),
      (ce.name = "DetachedDevicePublicData"),
      (ce.internalSpec = {
        deviceId: [1, e.FLAGS.REQUIRED | e.TYPES.UINT64],
        name: [2, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        sigPk: [3, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        authPk: [4, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        encPk: [5, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        signature: [6, e.FLAGS.REQUIRED | e.TYPES.BYTES],
      }),
      (de.name = "MmkDistributionToDetachedDevice"),
      (de.internalSpec = {
        encryptedMmk: [1, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        recipDeviceHash: [2, e.FLAGS.REQUIRED | e.TYPES.BYTES],
      }),
      (me.name = "MmkDistributionToMailbox"),
      (me.internalSpec = {
        encryptedMmk: [1, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        recipMailboxHeadHash: [2, e.FLAGS.REQUIRED | e.TYPES.BYTES],
      }),
      (pe.name = "MmkDistribution"),
      (pe.internalSpec = {
        toDetachedDevices: [1, e.FLAGS.REPEATED | e.TYPES.MESSAGE, de],
        toMailbox: [2, e.FLAGS.REQUIRED | e.TYPES.MESSAGE, me],
        version: [3, e.FLAGS.REQUIRED | e.TYPES.UINT64],
      }),
      (_e.name = "SignedMmkDistributionFromMailbox"),
      (_e.internalSpec = {
        mmkDistribution: [1, e.FLAGS.REQUIRED | e.TYPES.MESSAGE, pe],
        signature: [2, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        fromMailbox: [3, e.FLAGS.REQUIRED | e.TYPES.MESSAGE, ue],
      }),
      (fe.name = "MandrakeMekBundle"),
      (fe.internalSpec = {
        key: [1, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        mekId: [2, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        mailboxHeadHash: [3, e.FLAGS.REQUIRED | e.TYPES.BYTES],
      }),
      (ge.name = "MandrakeOpenEpochInput"),
      (ge.internalSpec = {
        userFbid: [1, e.FLAGS.REQUIRED | e.TYPES.STRING],
        epochNumber: [2, e.FLAGS.REQUIRED | e.TYPES.UINT64],
        exportRootKey: [3, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        previousExportRootKey: [4, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        previousEpochNumber: [5, e.FLAGS.REQUIRED | e.TYPES.UINT64],
        previousEpochHead: [6, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        previousMmk: [7, e.TYPES.MESSAGE, ue],
        detachedDevices: [8, e.FLAGS.REPEATED | e.TYPES.MESSAGE, ce],
      }),
      (he.name = "MandrakeOpenEpochResult"),
      (he.internalSpec = {
        success: [1, e.TYPES.MESSAGE, ye],
        errorMessage: [2, e.TYPES.STRING],
        __oneofs__: { result: ["success", "errorMessage"] },
      }),
      (ye.name = "MandrakeOpenEpochSuccess"),
      (ye.internalSpec = {
        minosSignedEpoch: [1, e.FLAGS.REQUIRED | e.TYPES.MESSAGE, X],
        signedMmkDistribution: [2, e.FLAGS.REQUIRED | e.TYPES.MESSAGE, _e],
      }),
      (Ce.name = "MandrakeOpenInitialEpochInput"),
      (Ce.internalSpec = {
        userFbid: [1, e.FLAGS.REQUIRED | e.TYPES.STRING],
        epochNumber: [2, e.FLAGS.REQUIRED | e.TYPES.UINT64],
        exportRootKey: [3, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        detachedDevices: [4, e.FLAGS.REPEATED | e.TYPES.MESSAGE, ce],
      }),
      (be.name = "MandrakeOpenInitialEpochResult"),
      (be.internalSpec = {
        success: [1, e.TYPES.MESSAGE, ye],
        errorMessage: [2, e.TYPES.STRING],
        __oneofs__: { result: ["success", "errorMessage"] },
      }),
      (ve.name = "MandrakeEncryptMekInput"),
      (ve.internalSpec = {
        mek: [1, e.FLAGS.REQUIRED | e.TYPES.MESSAGE, fe],
        recipients: [2, e.FLAGS.REPEATED | e.TYPES.MESSAGE, ue],
        conf: [5, e.TYPES.MESSAGE, u],
        mmkSender: [3, e.TYPES.MESSAGE, Le],
        epochSender: [4, e.TYPES.MESSAGE, Re],
        detachedDeviceSender: [6, e.TYPES.MESSAGE, Se],
        __oneofs__: {
          sender: ["mmkSender", "epochSender", "detachedDeviceSender"],
        },
      }),
      (Se.name = "MandrakeEncryptMekInput$DetachedDeviceSender"),
      (Se.internalSpec = {
        detachedDevicePublicData: [1, e.FLAGS.REQUIRED | e.TYPES.MESSAGE, ce],
        authSk: [2, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        authPk: [3, e.FLAGS.REQUIRED | e.TYPES.BYTES],
      }),
      (Re.name = "MandrakeEncryptMekInput$EpochSender"),
      (Re.internalSpec = {
        epochPublicData: [1, e.FLAGS.REQUIRED | e.TYPES.MESSAGE, K],
        authSk: [2, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        authPk: [3, e.FLAGS.REQUIRED | e.TYPES.BYTES],
      }),
      (Le.name = "MandrakeEncryptMekInput$MmkSender"),
      (Le.internalSpec = {
        mmkPublicData: [1, e.FLAGS.REQUIRED | e.TYPES.MESSAGE, ue],
        authSk: [2, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        authPk: [3, e.FLAGS.REQUIRED | e.TYPES.BYTES],
      }),
      (Ee.name = "MandrakeEncryptMekResult"),
      (Ee.internalSpec = {
        success: [1, e.TYPES.MESSAGE, ke],
        errorMessage: [2, e.TYPES.STRING],
        __oneofs__: { result: ["success", "errorMessage"] },
      }),
      (ke.name = "MandrakeEncryptMekSuccess"),
      (ke.internalSpec = {
        distributions: [1, e.FLAGS.REPEATED | e.TYPES.MESSAGE, Ie],
        recipientsHash: [2, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        version: [3, e.FLAGS.REQUIRED | e.TYPES.UINT64],
      }),
      (Ie.name = "MandrakeEncryptMekSuccess$MekDistributionSingleRecipient"),
      (Ie.internalSpec = {
        encryptedMek: [1, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        toMmk: [2, e.FLAGS.REQUIRED | e.TYPES.MESSAGE, ue],
        recipientMembershipProof: [3, e.TYPES.MESSAGE, Me],
      }),
      (Te.name = "MandrakeDecryptMekInput"),
      (Te.internalSpec = {
        encryptedMek: [1, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        recipientsHash: [4, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        recipientEncSk: [5, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        mekEncryptionVersion: [6, e.TYPES.UINT64],
        conf: [7, e.TYPES.MESSAGE, u],
        recipientMmk: [8, e.FLAGS.REQUIRED | e.TYPES.MESSAGE, ue],
        mekId: [9, e.TYPES.BYTES],
        recipientMembershipProof: [10, e.TYPES.MESSAGE, Me],
        mmkSender: [2, e.TYPES.MESSAGE, $e],
        epochSender: [3, e.TYPES.MESSAGE, xe],
        precomputedEpochSender: [11, e.TYPES.MESSAGE, De],
        __oneofs__: {
          senderPublicData: [
            "mmkSender",
            "epochSender",
            "precomputedEpochSender",
          ],
        },
      }),
      (De.name = "MandrakeDecryptMekInput$PrecomputedEpochSenderPublicData"),
      (De.internalSpec = {
        authPk: [1, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        epochHead: [2, e.FLAGS.REQUIRED | e.TYPES.BYTES],
      }),
      (xe.name = "MandrakeDecryptMekInput$EpochSenderPublicData"),
      (xe.internalSpec = {
        epochPublicData: [1, e.FLAGS.REQUIRED | e.TYPES.MESSAGE, K],
      }),
      ($e.name = "MandrakeDecryptMekInput$MmkSenderPublicData"),
      ($e.internalSpec = {
        mmkPublicData: [1, e.FLAGS.REQUIRED | e.TYPES.MESSAGE, ue],
      }),
      (Pe.name = "MandrakeDecryptMekResult"),
      (Pe.internalSpec = {
        success: [1, e.TYPES.MESSAGE, Ne],
        errorMessage: [2, e.TYPES.STRING],
        __oneofs__: { result: ["success", "errorMessage"] },
      }),
      (Ne.name = "MandrakeDecryptMekSuccess"),
      (Ne.internalSpec = { mek: [1, e.FLAGS.REQUIRED | e.TYPES.BYTES] }),
      (Me.name = "MerkleMembershipProof"),
      (Me.internalSpec = {
        proof: [1, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        root: [2, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        leafIndex: [3, e.FLAGS.REQUIRED | e.TYPES.UINT64],
        totalLeaves: [4, e.FLAGS.REQUIRED | e.TYPES.UINT64],
      }),
      (we.name = "MmkFromDetachedDevice"),
      (we.internalSpec = {
        mmk: [1, e.FLAGS.REQUIRED | e.TYPES.MESSAGE, ue],
        fromDetachedDevice: [2, e.FLAGS.REQUIRED | e.TYPES.MESSAGE, ce],
        membershipProof: [3, e.FLAGS.REQUIRED | e.TYPES.MESSAGE, Me],
      }),
      (Ae.name = "MandrakeValidateNewMmkResult"),
      (Ae.internalSpec = {
        valid: [1, e.TYPES.BOOL],
        errorMessage: [2, e.TYPES.STRING],
        __oneofs__: { result: ["valid", "errorMessage"] },
      }),
      (Fe.name = "MandrakeValidateNewMmkFromMailboxInput"),
      (Fe.internalSpec = {
        newMmk: [1, e.FLAGS.REQUIRED | e.TYPES.MESSAGE, ue],
        signature: [2, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        prevMmk: [3, e.TYPES.MESSAGE, ue],
        epochPublicData: [4, e.FLAGS.REQUIRED | e.TYPES.MESSAGE, K],
      }),
      (Oe.name = "MandrakeValidateNewMmkFromDetachedDeviceInput"),
      (Oe.internalSpec = {
        mmkFromDevice: [1, e.FLAGS.REQUIRED | e.TYPES.MESSAGE, we],
        signature: [2, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        prevMmk: [3, e.FLAGS.REQUIRED | e.TYPES.MESSAGE, ue],
      }),
      (Be.name = "MinosCommand"),
      (Be.internalSpec = {
        encryptAndSignMessage: [1, e.TYPES.MESSAGE, c],
        decryptAndVerifyMessage: [2, e.TYPES.MESSAGE, m],
        generateMek: [3, e.TYPES.MESSAGE, g],
        generateMekRosterHash: [4, e.TYPES.MESSAGE, y],
        encryptMekForDistribution: [5, e.TYPES.MESSAGE, b],
        decryptMekForDistribution: [6, e.TYPES.MESSAGE, R],
        encryptMeksForDistributionFromTransportSender: [7, e.TYPES.MESSAGE, k],
        decryptMekForDistributionFromTransportSender: [8, e.TYPES.MESSAGE, D],
        wrapTransportSigningPublicKey: [9, e.TYPES.MESSAGE, N],
        wrapTransportSigningSecretKey: [10, e.TYPES.MESSAGE, w],
        deriveMailboxSigningKeypair: [11, e.TYPES.MESSAGE, F],
        deriveMailboxEncryptionKeypair: [12, e.TYPES.MESSAGE, W],
        deriveMailboxAuthKeypair: [13, e.TYPES.MESSAGE, U],
        deriveAttachmentAccessTokenSecret: [14, e.TYPES.MESSAGE, H],
        deriveAttachmentPrimaryKeySecret: [15, e.TYPES.MESSAGE, z],
        minosOpenInitialEpoch: [16, e.TYPES.MESSAGE, Y],
        minosOpenEpoch: [17, e.TYPES.MESSAGE, Z],
        minosValidateEpoch: [18, e.TYPES.MESSAGE, te],
        minosVerifySingleEpoch: [19, e.TYPES.MESSAGE, re],
        minosThreadIdFromOneToOneThread: [20, e.TYPES.MESSAGE, ae],
        minosThreadIdFromActThreadId: [21, e.TYPES.MESSAGE, le],
        mandrakeOpenEpoch: [22, e.TYPES.MESSAGE, ge],
        mandrakeEncryptMek: [23, e.TYPES.MESSAGE, ve],
        mandrakeDecryptMek: [24, e.TYPES.MESSAGE, Te],
        mandrakeOpenInitialEpoch: [25, e.TYPES.MESSAGE, Ce],
        mandrakeValidateNewMmkFromMailbox: [27, e.TYPES.MESSAGE, Fe],
        mandrakeValidateNewMmkFromDetachedDevice: [28, e.TYPES.MESSAGE, Oe],
        deriveMessagingMailboxKeypairs: [29, e.TYPES.MESSAGE, We],
        decryptSelfMmkDistribution: [30, e.TYPES.MESSAGE, Ve],
        __oneofs__: {
          commandInput: [
            "encryptAndSignMessage",
            "decryptAndVerifyMessage",
            "generateMek",
            "generateMekRosterHash",
            "encryptMekForDistribution",
            "decryptMekForDistribution",
            "encryptMeksForDistributionFromTransportSender",
            "decryptMekForDistributionFromTransportSender",
            "wrapTransportSigningPublicKey",
            "wrapTransportSigningSecretKey",
            "deriveMailboxSigningKeypair",
            "deriveMailboxEncryptionKeypair",
            "deriveMailboxAuthKeypair",
            "deriveAttachmentAccessTokenSecret",
            "deriveAttachmentPrimaryKeySecret",
            "minosOpenInitialEpoch",
            "minosOpenEpoch",
            "minosValidateEpoch",
            "minosVerifySingleEpoch",
            "minosThreadIdFromOneToOneThread",
            "minosThreadIdFromActThreadId",
            "mandrakeOpenEpoch",
            "mandrakeEncryptMek",
            "mandrakeDecryptMek",
            "mandrakeOpenInitialEpoch",
            "mandrakeValidateNewMmkFromMailbox",
            "mandrakeValidateNewMmkFromDetachedDevice",
            "deriveMessagingMailboxKeypairs",
            "decryptSelfMmkDistribution",
          ],
        },
      }),
      (We.name = "DeriveMessagingMailboxKeypairsInput"),
      (We.internalSpec = { mmkSeed: [1, e.FLAGS.REQUIRED | e.TYPES.BYTES] }),
      (qe.name = "DeriveMessagingMailboxKeypairsResult"),
      (qe.internalSpec = {
        success: [1, e.TYPES.MESSAGE, Ue],
        errorMessage: [2, e.TYPES.STRING],
        __oneofs__: { result: ["success", "errorMessage"] },
      }),
      (Ue.name = "DeriveMessagingMailboxKeypairsSuccess"),
      (Ue.internalSpec = {
        encSk: [1, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        encPk: [2, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        authSk: [3, e.TYPES.BYTES],
        authPk: [4, e.TYPES.BYTES],
      }),
      (Ve.name = "DecryptSelfMmkDistributionInput"),
      (Ve.internalSpec = {
        encryptedMmk: [1, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        exportRootKey: [2, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        mailboxHeadHash: [3, e.FLAGS.REQUIRED | e.TYPES.BYTES],
      }),
      (He.name = "DecryptSelfMmkDistributionResult"),
      (He.internalSpec = {
        success: [1, e.TYPES.MESSAGE, Ge],
        errorMessage: [2, e.TYPES.STRING],
        __oneofs__: { result: ["success", "errorMessage"] },
      }),
      (Ge.name = "DecryptSelfMmkDistributionSuccess"),
      (Ge.internalSpec = { mmkSeed: [1, e.FLAGS.REQUIRED | e.TYPES.BYTES] }),
      (l.MinosMessageMetadataSpec = s),
      (l.MinosClientConfigSpec = u),
      (l.MinosEncryptAndSignMessageInputSpec = c),
      (l.MinosEncryptAndSignMessageResultSpec = d),
      (l.MinosDecryptAndVerifyMessageInputSpec = m),
      (l.MinosDecryptAndVerifyMessageResultSpec = p),
      (l.MinosDecryptAndVerifyMessageSuccessSpec = _),
      (l.MekBundleSpec = f),
      (l.GenerateMekInputSpec = g),
      (l.GenerateMekResultSpec = h),
      (l.GenerateMekRosterHashInputSpec = y),
      (l.GenerateMekRosterHashResultSpec = C),
      (l.EncryptMekForDistributionInputSpec = b),
      (l.EncryptMekForDistributionInput$MailboxAuthKPSpec = v),
      (l.EncryptMekForDistributionResultSpec = S),
      (l.DecryptMekForDistributionInputSpec = R),
      (l.DecryptMekForDistributionResultSpec = L),
      (l.DecryptMekForDistributionSuccessSpec = E),
      (l.EncryptMeksForDistributionFromTransportSenderInputSpec = k),
      (l.EncryptMeksForDistributionFromTransportSenderInput$TransportSigningKPSpec =
        I),
      (l.EncryptMeksForDistributionFromTransportSenderResultSpec = T),
      (l.DecryptMekForDistributionFromTransportSenderInputSpec = D),
      (l.DecryptMekForDistributionFromTransportSenderInput$TransportSenderMEKDistributionSingleRecipientSpec =
        x),
      (l.DecryptMekForDistributionFromTransportSenderResultSpec = $),
      (l.DecryptMekForDistributionFromTransportSenderSuccessSpec = P),
      (l.WrapTransportSigningPublicKeyInputSpec = N),
      (l.WrapTransportSigningPublicKeyResultSpec = M),
      (l.WrapTransportSigningSecretKeyInputSpec = w),
      (l.WrapTransportSigningSecretKeyResultSpec = A),
      (l.DeriveMailboxSigningKeypairInputSpec = F),
      (l.DeriveMailboxSigningKeypairResultSpec = O),
      (l.DeriveMailboxSigningKeypairSuccessSpec = B),
      (l.DeriveMailboxEncryptionKeypairInputSpec = W),
      (l.DeriveMailboxEncryptionKeypairResultSpec = q),
      (l.DeriveMailboxAuthKeypairInputSpec = U),
      (l.DeriveMailboxAuthKeypairResultSpec = V),
      (l.DeriveAttachmentAccessTokenSecretInputSpec = H),
      (l.DeriveAttachmentAccessTokenSecretResultSpec = G),
      (l.DeriveAttachmentPrimaryKeySecretInputSpec = z),
      (l.DeriveAttachmentPrimaryKeySecretResultSpec = j),
      (l.EpochPublicDataSpec = K),
      (l.EpochSignaturesSpec = Q),
      (l.MinosSignedEpochSpec = X),
      (l.MinosOpenInitialEpochInputSpec = Y),
      (l.MinosOpenInitialEpochResultSpec = J),
      (l.MinosOpenEpochInputSpec = Z),
      (l.MinosOpenEpochResultSpec = ee),
      (l.MinosValidateEpochInputSpec = te),
      (l.MinosValidateEpochResultSpec = ne),
      (l.MinosVerifySingleEpochInputSpec = re),
      (l.MinosVerifySingleEpochResultSpec = oe),
      (l.MinosThreadIdFromOneToOneThreadInputSpec = ae),
      (l.MinosThreadIdFromOneToOneThreadResultSpec = ie),
      (l.MinosThreadIdFromActThreadIdInputSpec = le),
      (l.MinosThreadIdFromActThreadIdResultSpec = se),
      (l.MessagingMailboxPublicDataSpec = ue),
      (l.DetachedDevicePublicDataSpec = ce),
      (l.MmkDistributionToDetachedDeviceSpec = de),
      (l.MmkDistributionToMailboxSpec = me),
      (l.MmkDistributionSpec = pe),
      (l.SignedMmkDistributionFromMailboxSpec = _e),
      (l.MandrakeMekBundleSpec = fe),
      (l.MandrakeOpenEpochInputSpec = ge),
      (l.MandrakeOpenEpochResultSpec = he),
      (l.MandrakeOpenEpochSuccessSpec = ye),
      (l.MandrakeOpenInitialEpochInputSpec = Ce),
      (l.MandrakeOpenInitialEpochResultSpec = be),
      (l.MandrakeEncryptMekInputSpec = ve),
      (l.MandrakeEncryptMekInput$DetachedDeviceSenderSpec = Se),
      (l.MandrakeEncryptMekInput$EpochSenderSpec = Re),
      (l.MandrakeEncryptMekInput$MmkSenderSpec = Le),
      (l.MandrakeEncryptMekResultSpec = Ee),
      (l.MandrakeEncryptMekSuccessSpec = ke),
      (l.MandrakeEncryptMekSuccess$MekDistributionSingleRecipientSpec = Ie),
      (l.MandrakeDecryptMekInputSpec = Te),
      (l.MandrakeDecryptMekInput$PrecomputedEpochSenderPublicDataSpec = De),
      (l.MandrakeDecryptMekInput$EpochSenderPublicDataSpec = xe),
      (l.MandrakeDecryptMekInput$MmkSenderPublicDataSpec = $e),
      (l.MandrakeDecryptMekResultSpec = Pe),
      (l.MandrakeDecryptMekSuccessSpec = Ne),
      (l.MerkleMembershipProofSpec = Me),
      (l.MmkFromDetachedDeviceSpec = we),
      (l.MandrakeValidateNewMmkResultSpec = Ae),
      (l.MandrakeValidateNewMmkFromMailboxInputSpec = Fe),
      (l.MandrakeValidateNewMmkFromDetachedDeviceInputSpec = Oe),
      (l.MinosCommandSpec = Be),
      (l.DeriveMessagingMailboxKeypairsInputSpec = We),
      (l.DeriveMessagingMailboxKeypairsResultSpec = qe),
      (l.DeriveMessagingMailboxKeypairsSuccessSpec = Ue),
      (l.DecryptSelfMmkDistributionInputSpec = Ve),
      (l.DecryptSelfMmkDistributionResultSpec = He),
      (l.DecryptSelfMmkDistributionSuccessSpec = Ge));
  },
  98,
);
