__d(
  "FbWebWebBloksComponents",
  [
    "FBWebBloksAlert",
    "FBWebBloksAlertButton",
    "FBWebBloksBottomSheetNavbar",
    "FBWebBloksBottomSheetNavbarTrailingButton",
    "FBWebBloksCatsArkoseWebView",
    "FBWebBloksCatsReCaptchaWebView",
    "FBWebBloksCatsReCaptchaWebViewV2",
    "FBWebBloksFullScreenNavbar",
    "FBWebBloksFullScreenNavbarTrailingButton",
    "FBWebBloksPullToRefreshContainerFallback",
    "FBWebBloksShowreelDynamicTextV2",
    "FBWebBloksSurveyRtfTextQuestion",
    "WebBloksBottomSheet",
    "WebBloksDummy",
    "WebBloksIGSearch",
    "WebBloksText",
  ],
  function (t, n, r, o, a, i, l) {
    var e = {
      㐾: r("WebBloksBottomSheet"),
      㑋: r("WebBloksIGSearch"),
      㑍: r("WebBloksText"),
      㒎: r("WebBloksText"),
      㓟: r("WebBloksBottomSheet"),
      㓪: r("WebBloksText"),
      㗛: r("FBWebBloksAlert"),
      㗜: r("FBWebBloksAlertButton"),
      㵴: r("WebBloksDummy"),
      㶚: r("FBWebBloksShowreelDynamicTextV2"),
      䄉: r("FBWebBloksFullScreenNavbar"),
      䄍: r("FBWebBloksFullScreenNavbarTrailingButton"),
      䅻: r("FBWebBloksBottomSheetNavbar"),
      䅼: r("FBWebBloksBottomSheetNavbarTrailingButton"),
      䋃: r("FBWebBloksPullToRefreshContainerFallback"),
      帍: r("FBWebBloksCatsReCaptchaWebView"),
      弲: r("FBWebBloksSurveyRtfTextQuestion"),
      愰: r("FBWebBloksCatsReCaptchaWebViewV2"),
      拼: r("FBWebBloksCatsArkoseWebView"),
    };
    l.COMPONENTS = e;
  },
  98,
);
