__d(
  "FoxCoreWebBloksPrimitives",
  [
    "WebBloksJsArrayAt",
    "WebBloksJsArrayFind",
    "WebBloksJsArrayFindIndex",
    "WebBloksJsArrayIndexOf",
    "WebBloksJsArrayJoin",
    "WebBloksJsArrayLastIndexOf",
    "WebBloksJsArraySlice",
    "WebBloksJsNumberIsInteger",
    "WebBloksJsStringCharAt",
    "WebBloksJsStringCharCodeAt",
    "WebBloksJsStringIndexOf",
    "WebBloksJsStringLastIndexOf",
    "WebBloksJsStringRepeat",
    "WebBloksJsStringReplace",
    "WebBloksJsStringReplaceAll",
    "WebBloksJsStringSlice",
    "WebBloksJsStringSubstring",
    "WebBloksJsStringTrim",
    "WebBloksReactNormalizeChildren",
    "WebBloksStrictEqual",
  ],
  function (t, n, r, o, a, i, l) {
    var e = {},
      s = {
        "bk.action.js.array.At": r("WebBloksJsArrayAt"),
        "bk.action.js.array.Find": r("WebBloksJsArrayFind"),
        "bk.action.js.array.FindIndex": r("WebBloksJsArrayFindIndex"),
        "bk.action.js.array.IndexOf": r("WebBloksJsArrayIndexOf"),
        "bk.action.js.array.Join": r("WebBloksJsArrayJoin"),
        "bk.action.js.array.LastIndexOf": r("WebBloksJsArrayLastIndexOf"),
        "bk.action.js.array.Slice": r("WebBloksJsArraySlice"),
        "bk.action.js.number.IsInteger": r("WebBloksJsNumberIsInteger"),
        "bk.action.js.string.CharAt": r("WebBloksJsStringCharAt"),
        "bk.action.js.string.CharCodeAt": r("WebBloksJsStringCharCodeAt"),
        "bk.action.js.string.IndexOf": r("WebBloksJsStringIndexOf"),
        "bk.action.js.string.LastIndexOf": r("WebBloksJsStringLastIndexOf"),
        "bk.action.js.string.Repeat": r("WebBloksJsStringRepeat"),
        "bk.action.js.string.Replace": r("WebBloksJsStringReplace"),
        "bk.action.js.string.ReplaceAll": r("WebBloksJsStringReplaceAll"),
        "bk.action.js.string.Slice": r("WebBloksJsStringSlice"),
        "bk.action.js.string.Substring": r("WebBloksJsStringSubstring"),
        "bk.action.js.string.Trim": r("WebBloksJsStringTrim"),
        "bk.action.js.syntax.StrictEqual": r("WebBloksStrictEqual"),
        "bk.action.react.NormalizeChildren": r(
          "WebBloksReactNormalizeChildren",
        ),
      },
      u = {};
    ((l.COMPONENTS = e), (l.ACTIONS = s), (l.EXTENSION_HANDLERS = u));
  },
  98,
);
