__d(
  "FrontierWDSThemeDefinition",
  [],
  function (t, n, r, o, a, i, l) {
    "use strict";
    var e,
      s,
      u,
      c,
      d,
      m,
      p,
      _,
      f,
      g,
      h,
      y,
      C,
      b,
      v,
      S,
      R,
      L,
      E,
      k,
      I,
      T,
      D,
      x,
      $,
      P,
      N,
      M,
      w,
      A,
      F,
      O,
      B,
      W,
      q,
      U,
      V,
      H,
      G,
      z,
      j,
      K,
      Q,
      X,
      Y,
      J,
      Z,
      ee,
      te,
      ne,
      re,
      oe,
      ae,
      ie,
      le,
      se,
      ue,
      ce,
      de,
      me,
      pe,
      _e,
      fe,
      ge,
      he,
      ye,
      Ce,
      be,
      ve,
      Se,
      Re,
      Le,
      Ee,
      ke,
      Ie,
      Te,
      De,
      xe,
      $e,
      Pe,
      Ne,
      Me,
      we,
      Ae,
      Fe,
      Oe,
      Be,
      We,
      qe,
      Ue,
      Ve,
      He,
      Ge,
      ze,
      je,
      Ke,
      Qe,
      Xe,
      Ye,
      Je,
      Ze,
      et,
      tt,
      nt,
      rt,
      ot,
      at,
      it,
      lt,
      st,
      ut,
      ct,
      dt,
      mt,
      pt,
      _t,
      ft,
      gt,
      ht,
      yt,
      Ct,
      bt,
      vt,
      St,
      Rt,
      Lt,
      Et,
      kt,
      It,
      Tt,
      Dt,
      xt,
      $t,
      Pt,
      Nt,
      Mt,
      wt,
      At,
      Ft,
      Ot,
      Bt,
      Wt,
      qt,
      Ut,
      Vt,
      Ht,
      Gt,
      zt,
      jt,
      Kt,
      Qt,
      Xt,
      Yt,
      Jt,
      Zt,
      en,
      tn,
      nn,
      rn,
      on,
      an,
      ln,
      sn,
      un,
      cn,
      dn,
      mn,
      pn,
      _n,
      fn,
      gn,
      hn,
      yn,
      Cn,
      bn,
      vn,
      Sn,
      Rn,
      Ln,
      En,
      kn,
      In,
      Tn,
      Dn,
      xn,
      $n,
      Pn,
      Nn,
      Mn,
      wn,
      An,
      Fn,
      On,
      Bn,
      Wn,
      qn,
      Un,
      Vn,
      Hn,
      Gn,
      zn,
      jn,
      Kn,
      Qn,
      Xn,
      Yn,
      Jn,
      Zn,
      er,
      tr,
      nr,
      rr,
      or,
      ar,
      ir,
      lr,
      sr,
      ur,
      cr,
      dr,
      mr,
      pr,
      _r,
      fr,
      gr,
      hr,
      yr,
      Cr,
      br,
      vr,
      Sr,
      Rr,
      Lr,
      Er,
      kr,
      Ir,
      Tr,
      Dr,
      xr,
      $r,
      Pr,
      Nr,
      Mr,
      wr,
      Ar,
      Fr,
      Or,
      Br,
      Wr,
      qr,
      Ur,
      Vr,
      Hr,
      Gr,
      zr,
      jr,
      Kr,
      Qr,
      Xr,
      Yr,
      Jr,
      Zr,
      eo,
      to,
      no,
      ro,
      oo,
      ao,
      io,
      lo,
      so,
      uo,
      co,
      mo,
      po,
      _o,
      fo,
      go,
      ho,
      yo,
      Co,
      bo,
      vo,
      So,
      Ro,
      Lo,
      Eo,
      ko,
      Io,
      To,
      Do,
      xo,
      $o,
      Po,
      No,
      Mo,
      wo,
      Ao,
      Fo,
      Oo,
      Bo,
      Wo,
      qo,
      Uo,
      Vo,
      Ho,
      Go,
      zo,
      jo,
      Ko,
      Qo,
      Xo,
      Yo,
      Jo,
      Zo,
      ea,
      ta,
      na,
      ra,
      oa,
      aa,
      ia,
      la,
      sa,
      ua,
      ca,
      da,
      ma,
      pa,
      _a,
      fa,
      ga,
      ha,
      ya,
      Ca,
      ba,
      va,
      Sa,
      Ra,
      La,
      Ea,
      ka,
      Ia,
      Ta,
      Da,
      xa,
      $a,
      Pa,
      Na,
      Ma,
      wa,
      Aa,
      Fa,
      Oa,
      Ba,
      Wa,
      qa,
      Ua,
      Va,
      Ha,
      Ga,
      za,
      ja,
      Ka,
      Qa,
      Xa = "@media (prefers-color-scheme: dark)",
      Ya = {
        frontierButtonFocusOutlineWidth: "2px",
        frontierButtonHeightLarge: "56px",
        frontierButtonHeightMedium: "40px",
        frontierButtonHeightSmall: "32px",
        frontierButtonIconGlyphSizeLarge: "24px",
        frontierButtonIconGlyphSizeMedium: "24px",
        frontierButtonIconGlyphSizeSmall: "24px",
        frontierButtonIconSizeLarge: "56px",
        frontierButtonIconSizeMedium: "40px",
        frontierButtonIconSizeSmall: "32px",
        frontierCheckboxBoxHeight: "18px",
        frontierCheckboxBoxWidth: "18px",
        frontierChipBorderSize: "1px",
        frontierChipHeight: "32px",
        frontierDialogWebMinHeight: "480px",
        frontierDialogWebWidth: "600px",
        frontierDividerHeightDefault: "0.5px",
        frontierDividerHeightThick: "4px",
        frontierIconSize12: "12px",
        frontierIconSize16: "16px",
        frontierIconSize20: "20px",
        frontierIconSize24: "24px",
        frontierIconSize32: "32px",
        frontierIconSize48: "48px",
        frontierIconSize64: "64px",
        frontierIconSize80: "80px",
        frontierListcellMinheightDefault: "52px",
        frontierPillHeight: "20px",
        frontierProgressBarLarge: "8px",
        frontierProgressBarMedium: "4px",
        frontierProgressBarSmall: "2px",
        frontierProgressRingLarge: "160px",
        frontierProgressRingMedium: "96px",
        frontierProgressRingSmall: "44px",
        frontierProgressRingStrokeWidth: "8px",
        frontierRadioCheckHeight: "12px",
        frontierRadioCheckWidth: "12px",
        frontierRadioRadioHeight: "20px",
        frontierRadioRadioWidth: "20px",
        frontierSearchfieldHeight: "48px",
        frontierStepperStepLarge: "8px",
        frontierStepperStepMedium: "4px",
        frontierStepperStepSmall: "2px",
        frontierSwitchHandleSelectedDisabledHeight: "24px",
        frontierSwitchHandleSelectedDisabledWidth: "24px",
        frontierSwitchHandleSelectedHeight: "24px",
        frontierSwitchHandleSelectedWidth: "24px",
        frontierSwitchHandleUnselectedDisabledHeight: "16px",
        frontierSwitchHandleUnselectedDisabledWidth: "16px",
        frontierSwitchHandleUnselectedHeight: "16px",
        frontierSwitchHandleUnselectedWidth: "16px",
        frontierSwitchTrackerSelectedDisabledHeight: "32px",
        frontierSwitchTrackerSelectedDisabledWidth: "50px",
        frontierSwitchTrackerSelectedHeight: "32px",
        frontierSwitchTrackerSelectedWidth: "50px",
        frontierSwitchTrackerUnselectedDisabledHeight: "32px",
        frontierSwitchTrackerUnselectedDisabledWidth: "50px",
        frontierSwitchTrackerUnselectedHeight: "32px",
        frontierSwitchTrackerUnselectedWidth: "50px",
        frontierTabsItemHeight: "28px",
        frontierTextbadgeHeight: "20px",
      },
      Ja = {
        frontierAlertBannerMobileBorderBottom: "1px",
        frontierAlertBannerMobileBorderLeft: "1px",
        frontierAlertBannerMobileBorderRight: "1px",
        frontierAlertBannerMobileBorderTop: "1px",
        frontierAlertBannerMobileCornerRadius: "16px",
        frontierAlertBannerWebBorder: "0px",
        frontierAlertBannerWebCornerRadius: "16px",
        frontierButtonBorderRadius: "1000px",
        frontierCardMobileCornerRadius: "16px",
        frontierCardWebCornerRadius: "16px",
        frontierCheckboxBoxBorder: "2px",
        frontierCheckboxBoxRadius: "2px",
        frontierChipBorderRadius: "1000px",
        frontierDialogCornerRadius: "32px",
        frontierGlimmerCornerRadiusCircle: "8888px",
        frontierGlimmerCornerRadiusRounded: "8px",
        frontierGlimmerCornerRadiusSquare: "0px",
        frontierListRoundedBorder: "1px",
        frontierListRoundedCornerRadius: "8px",
        frontierListSquaredBorder: "1px",
        frontierListSquaredCornerRadius: "0px",
        frontierMenuRoundedBorder: "1px",
        frontierMenuRoundedCornerRadius: "8px",
        frontierMenuSquaredBorder: "1px",
        frontierMenuSquaredCornerRadius: "0px",
        frontierPillBorderRadius: "8888px",
        frontierProgressBarCornerRadius: "0px",
        frontierProgressBarStepRadiusLeft: "0px",
        frontierProgressBarStepRadiusRight: "0px",
        frontierRadioRadioBorder: "2px",
        frontierSearchfieldBorder: "0px",
        frontierSearchfieldCornerRadius: "8888px",
        frontierSelectinputCornerRadius: "8px",
        frontierStepperCornerRadius: "0px",
        frontierStepperStepRadiusLeft: "0px",
        frontierStepperStepRadiusRight: "0px",
        frontierSwitchHandleSelectedBorder: "0px",
        frontierSwitchHandleSelectedCornerRadius: "8888px",
        frontierSwitchHandleSelectedDisabledBorder: "0px",
        frontierSwitchHandleSelectedDisabledCornerRadius: "8888px",
        frontierSwitchHandleUnselectedBorder: "0px",
        frontierSwitchHandleUnselectedCornerRadius: "8888px",
        frontierSwitchHandleUnselectedDisabledBorder: "0px",
        frontierSwitchHandleUnselectedDisabledCornerRadius: "8888px",
        frontierSwitchTrackerSelectedBorder: "2px",
        frontierSwitchTrackerSelectedCornerRadius: "8888px",
        frontierSwitchTrackerSelectedDisabledBorder: "2px",
        frontierSwitchTrackerSelectedDisabledCornerRadius: "8888px",
        frontierSwitchTrackerUnselectedBorder: "2px",
        frontierSwitchTrackerUnselectedCornerRadius: "8888px",
        frontierSwitchTrackerUnselectedDisabledBorder: "2px",
        frontierSwitchTrackerUnselectedDisabledCornerRadius: "8888px",
        frontierTableBorder: "1px",
        frontierTableCornerRadius: "8px",
        frontierTableHeaderShadow: "none",
        frontierTabsBorder: "0px",
        frontierTabsItemBorder: "1px",
        frontierTabsItemWrapperRadius: "0px",
        frontierTextbadgeBorderRadius: "8888px",
        frontierTextinputCornerRadius: "8px",
        frontierTextinputFocusRingShadow: "var(--focus-ring-shadow-default)",
        frontierTokenizerTokenCornerRadius: "1000px",
        frontierTooltipCornerRadius: "8px",
      },
      Za = {
        "--surface-background":
          ((e = {}), (e[Xa] = "#000000"), (e.default = "#ffffff"), e),
        "--wash": ((s = {}), (s[Xa] = "#000000"), (s.default = "#ffffff"), s),
        frontierAlertBannerColorBackground:
          ((u = {}),
          (u[Xa] = "rgba(36, 38, 38, 1)"),
          (u.default = "rgba(241, 238, 235, 1)"),
          u),
        frontierAlertBannerColorBorder:
          ((c = {}),
          (c[Xa] = "rgba(255, 255, 255, 0.1)"),
          (c.default = "rgba(17, 27, 33, 0.1)"),
          c),
        frontierAlertBannerColorDescription:
          ((d = {}),
          (d[Xa] = "rgba(247, 248, 250, 1)"),
          (d.default = "rgba(10, 16, 20, 1)"),
          d),
        frontierAlertBannerColorDismissible:
          ((m = {}),
          (m[Xa] = "rgba(141, 149, 153, 1)"),
          (m.default = "rgba(91, 99, 104, 1)"),
          m),
        frontierAlertBannerColorIcon:
          ((p = {}),
          (p[Xa] = "rgba(141, 149, 153, 1)"),
          (p.default = "rgba(91, 99, 104, 1)"),
          p),
        frontierAlertBannerColorTitle:
          ((_ = {}),
          (_[Xa] = "rgba(247, 248, 250, 1)"),
          (_.default = "rgba(10, 16, 20, 1)"),
          _),
        frontierButtonApplePayBackgroundColor:
          ((f = {}),
          (f[Xa] = "rgba(255, 255, 255, 1)"),
          (f.default = "rgba(0, 0, 0, 1)"),
          f),
        frontierButtonApplePayBorderColor:
          ((g = {}),
          (g[Xa] = "rgba(255, 255, 255, 1)"),
          (g.default = "rgba(0, 0, 0, 1)"),
          g),
        frontierButtonApplePayIconColor:
          ((h = {}),
          (h[Xa] = "rgba(0, 0, 0, 1)"),
          (h.default = "rgba(255, 255, 255, 1)"),
          h),
        frontierButtonApplePayTextColor:
          ((y = {}),
          (y[Xa] = "rgba(0, 0, 0, 1)"),
          (y.default = "rgba(255, 255, 255, 1)"),
          y),
        frontierButtonFocusOutlineColor:
          ((C = {}),
          (C[Xa] = "rgba(75, 169, 254, 1)"),
          (C.default = "rgba(4, 87, 203, 1)"),
          C),
        frontierButtonPrimaryBackgroundColor:
          ((b = {}),
          (b[Xa] = "rgba(250, 250, 250, 1)"),
          (b.default = "rgba(23, 22, 22, 1)"),
          b),
        frontierButtonPrimaryBorderColor:
          ((v = {}),
          (v[Xa] = "rgba(250, 250, 250, 1)"),
          (v.default = "rgba(23, 22, 22, 1)"),
          v),
        frontierButtonPrimaryDestructiveBackgroundColor:
          ((S = {}),
          (S[Xa] = "rgba(234, 0, 56, 1)"),
          (S.default = "rgba(234, 0, 56, 1)"),
          S),
        frontierButtonPrimaryDestructiveBorderColor:
          ((R = {}),
          (R[Xa] = "rgba(234, 0, 56, 1)"),
          (R.default = "rgba(234, 0, 56, 1)"),
          R),
        frontierButtonPrimaryDestructiveIconColor:
          ((L = {}),
          (L[Xa] = "rgba(247, 248, 250, 1)"),
          (L.default = "rgba(250, 250, 250, 1)"),
          L),
        frontierButtonPrimaryDestructiveTextColor:
          ((E = {}),
          (E[Xa] = "rgba(247, 248, 250, 1)"),
          (E.default = "rgba(250, 250, 250, 1)"),
          E),
        frontierButtonPrimaryDisabledBackgroundColor:
          ((k = {}),
          (k[Xa] = "rgba(255, 255, 255, 0.1)"),
          (k.default = "rgba(194, 189, 184, 0.15)"),
          k),
        frontierButtonPrimaryDisabledBorderColor:
          ((I = {}),
          (I[Xa] = "rgba(255, 255, 255, 0.1)"),
          (I.default = "rgba(194, 189, 184, 0.15)"),
          I),
        frontierButtonPrimaryDisabledIconColor:
          ((T = {}),
          (T[Xa] = "rgba(62, 71, 77, 1)"),
          (T.default = "rgba(179, 185, 189, 1)"),
          T),
        frontierButtonPrimaryDisabledTextColor:
          ((D = {}),
          (D[Xa] = "rgba(62, 71, 77, 1)"),
          (D.default = "rgba(179, 185, 189, 1)"),
          D),
        frontierButtonPrimaryHoverBackgroundColor:
          ((x = {}),
          (x[Xa] = "rgba(0, 100, 224, 1)"),
          (x.default = "rgba(1, 113, 227, 1)"),
          x),
        frontierButtonPrimaryHoverBorderColor:
          (($ = {}),
          ($[Xa] = "rgba(0, 0, 0, 0)"),
          ($.default = "rgba(0, 0, 0, 0)"),
          $),
        frontierButtonPrimaryHoverIconColor:
          ((P = {}),
          (P[Xa] = "rgba(255, 255, 255, 1)"),
          (P.default = "rgba(255, 255, 255, 1)"),
          P),
        frontierButtonPrimaryHoverTextColor:
          ((N = {}),
          (N[Xa] = "rgba(255, 255, 255, 1)"),
          (N.default = "rgba(255, 255, 255, 1)"),
          N),
        frontierButtonPrimaryIconColor:
          ((M = {}),
          (M[Xa] = "rgba(10, 16, 20, 1)"),
          (M.default = "rgba(250, 250, 250, 1)"),
          M),
        frontierButtonPrimaryPressedBackgroundColor:
          ((w = {}),
          (w[Xa] = "rgba(250, 250, 250, 1)"),
          (w.default = "rgba(81, 80, 80, 1)"),
          w),
        frontierButtonPrimaryPressedBorderColor:
          ((A = {}),
          (A[Xa] = "rgba(250, 250, 250, 1)"),
          (A.default = "rgba(81, 80, 80, 1)"),
          A),
        frontierButtonPrimaryPressedIconColor:
          ((F = {}),
          (F[Xa] = "rgba(10, 16, 20, 1)"),
          (F.default = "rgba(250, 250, 250, 1)"),
          F),
        frontierButtonPrimaryPressedTextColor:
          ((O = {}),
          (O[Xa] = "rgba(10, 16, 20, 1)"),
          (O.default = "rgba(250, 250, 250, 1)"),
          O),
        frontierButtonPrimaryTextColor:
          ((B = {}),
          (B[Xa] = "rgba(10, 16, 20, 1)"),
          (B.default = "rgba(250, 250, 250, 1)"),
          B),
        frontierButtonSecondaryBackgroundColor:
          ((W = {}),
          (W[Xa] = "rgba(10, 16, 20, 1)"),
          (W.default = "rgba(255, 255, 255, 1)"),
          W),
        frontierButtonSecondaryBorderColor:
          ((q = {}),
          (q[Xa] = "rgba(255, 255, 255, 0.1)"),
          (q.default = "rgba(17, 27, 33, 0.2)"),
          q),
        frontierButtonSecondaryDestructiveBackgroundColor:
          ((U = {}),
          (U[Xa] = "rgba(10, 16, 20, 1)"),
          (U.default = "rgba(255, 255, 255, 1)"),
          U),
        frontierButtonSecondaryDestructiveBorderColor:
          ((V = {}),
          (V[Xa] = "rgba(234, 0, 56, 1)"),
          (V.default = "rgba(234, 0, 56, 1)"),
          V),
        frontierButtonSecondaryDestructiveIconColor:
          ((H = {}),
          (H[Xa] = "rgba(234, 0, 56, 1)"),
          (H.default = "rgba(234, 0, 56, 1)"),
          H),
        frontierButtonSecondaryDestructiveTextColor:
          ((G = {}),
          (G[Xa] = "rgba(234, 0, 56, 1)"),
          (G.default = "rgba(234, 0, 56, 1)"),
          G),
        frontierButtonSecondaryDisabledBackgroundColor:
          ((z = {}),
          (z[Xa] = "rgba(10, 16, 20, 1)"),
          (z.default = "rgba(255, 255, 255, 1)"),
          z),
        frontierButtonSecondaryDisabledBorderColor:
          ((j = {}),
          (j[Xa] = "rgba(255, 255, 255, 0.1)"),
          (j.default = "rgba(17, 27, 33, 0.2)"),
          j),
        frontierButtonSecondaryDisabledIconColor:
          ((K = {}),
          (K[Xa] = "rgba(62, 71, 77, 1)"),
          (K.default = "rgba(179, 185, 189, 1)"),
          K),
        frontierButtonSecondaryDisabledTextColor:
          ((Q = {}),
          (Q[Xa] = "rgba(62, 71, 77, 1)"),
          (Q.default = "rgba(179, 185, 189, 1)"),
          Q),
        frontierButtonSecondaryHoverBackgroundColor:
          ((X = {}),
          (X[Xa] = "rgba(0, 0, 0, 0)"),
          (X.default = "rgba(0, 0, 0, 0)"),
          X),
        frontierButtonSecondaryHoverBorderColor:
          ((Y = {}),
          (Y[Xa] = "rgba(115, 190, 250, 1)"),
          (Y.default = "rgba(1, 113, 227, 1)"),
          Y),
        frontierButtonSecondaryHoverIconColor:
          ((J = {}),
          (J[Xa] = "rgba(115, 190, 250, 1)"),
          (J.default = "rgba(1, 113, 227, 1)"),
          J),
        frontierButtonSecondaryHoverTextColor:
          ((Z = {}),
          (Z[Xa] = "rgba(115, 190, 250, 1)"),
          (Z.default = "rgba(1, 113, 227, 1)"),
          Z),
        frontierButtonSecondaryIconColor:
          ((ee = {}),
          (ee[Xa] = "rgba(33, 192, 99, 1)"),
          (ee.default = "rgba(27, 135, 85, 1)"),
          ee),
        frontierButtonSecondaryPressedBackgroundColor:
          ((te = {}),
          (te[Xa] = "rgba(10, 16, 20, 1)"),
          (te.default = "rgba(255, 255, 255, 1)"),
          te),
        frontierButtonSecondaryPressedBorderColor:
          ((ne = {}),
          (ne[Xa] = "rgba(255, 255, 255, 0.1)"),
          (ne.default = "rgba(17, 27, 33, 0.2)"),
          ne),
        frontierButtonSecondaryPressedIconColor:
          ((re = {}),
          (re[Xa] = "rgba(33, 192, 99, 0.75)"),
          (re.default = "rgba(27, 135, 85, 0.75)"),
          re),
        frontierButtonSecondaryPressedTextColor:
          ((oe = {}),
          (oe[Xa] = "rgba(33, 192, 99, 0.75)"),
          (oe.default = "rgba(27, 135, 85, 0.75)"),
          oe),
        frontierButtonSecondaryTextColor:
          ((ae = {}),
          (ae[Xa] = "rgba(33, 192, 99, 1)"),
          (ae.default = "rgba(27, 135, 85, 1)"),
          ae),
        frontierButtonTertiaryBackgroundColor:
          ((ie = {}),
          (ie[Xa] = "rgba(10, 16, 20, 1)"),
          (ie.default = "rgba(255, 255, 255, 1)"),
          ie),
        frontierButtonTertiaryBorderColor:
          ((le = {}),
          (le[Xa] = "rgba(10, 16, 20, 1)"),
          (le.default = "rgba(255, 255, 255, 1)"),
          le),
        frontierButtonTertiaryDestructiveBackgroundColor:
          ((se = {}),
          (se[Xa] = "rgba(0, 0, 0, 0)"),
          (se.default = "rgba(255, 255, 255, 0)"),
          se),
        frontierButtonTertiaryDestructiveBorderColor:
          ((ue = {}),
          (ue[Xa] = "rgba(0, 0, 0, 0)"),
          (ue.default = "rgba(255, 255, 255, 0)"),
          ue),
        frontierButtonTertiaryDestructiveIconColor:
          ((ce = {}),
          (ce[Xa] = "rgba(234, 0, 56, 1)"),
          (ce.default = "rgba(234, 0, 56, 1)"),
          ce),
        frontierButtonTertiaryDestructiveTextColor:
          ((de = {}),
          (de[Xa] = "rgba(234, 0, 56, 1)"),
          (de.default = "rgba(234, 0, 56, 1)"),
          de),
        frontierButtonTertiaryDisabledBackgroundColor:
          ((me = {}),
          (me[Xa] = "rgba(10, 16, 20, 1)"),
          (me.default = "rgba(255, 255, 255, 1)"),
          me),
        frontierButtonTertiaryDisabledBorderColor:
          ((pe = {}),
          (pe[Xa] = "rgba(10, 16, 20, 1)"),
          (pe.default = "rgba(255, 255, 255, 1)"),
          pe),
        frontierButtonTertiaryDisabledIconColor:
          ((_e = {}),
          (_e[Xa] = "rgba(62, 71, 77, 1)"),
          (_e.default = "rgba(179, 185, 189, 1)"),
          _e),
        frontierButtonTertiaryDisabledTextColor:
          ((fe = {}),
          (fe[Xa] = "rgba(62, 71, 77, 1)"),
          (fe.default = "rgba(179, 185, 189, 1)"),
          fe),
        frontierButtonTertiaryHoverBackgroundColor:
          ((ge = {}),
          (ge[Xa] = "rgba(0, 0, 0, 0)"),
          (ge.default = "rgba(0, 0, 0, 0)"),
          ge),
        frontierButtonTertiaryHoverBorderColor:
          ((he = {}),
          (he[Xa] = "rgba(0, 0, 0, 0)"),
          (he.default = "rgba(0, 0, 0, 0)"),
          he),
        frontierButtonTertiaryHoverIconColor:
          ((ye = {}),
          (ye[Xa] = "rgba(115, 190, 250, 1)"),
          (ye.default = "rgba(1, 113, 227, 1)"),
          ye),
        frontierButtonTertiaryHoverTextColor:
          ((Ce = {}),
          (Ce[Xa] = "rgba(115, 190, 250, 1)"),
          (Ce.default = "rgba(1, 113, 227, 1)"),
          Ce),
        frontierButtonTertiaryIconColor:
          ((be = {}),
          (be[Xa] = "rgba(33, 192, 99, 1)"),
          (be.default = "rgba(27, 135, 85, 1)"),
          be),
        frontierButtonTertiaryPressedBackgroundColor:
          ((ve = {}),
          (ve[Xa] = "rgba(10, 16, 20, 1)"),
          (ve.default = "rgba(255, 255, 255, 1)"),
          ve),
        frontierButtonTertiaryPressedBorderColor:
          ((Se = {}),
          (Se[Xa] = "rgba(10, 16, 20, 1)"),
          (Se.default = "rgba(255, 255, 255, 1)"),
          Se),
        frontierButtonTertiaryPressedIconColor:
          ((Re = {}),
          (Re[Xa] = "rgba(33, 192, 99, 0.75)"),
          (Re.default = "rgba(27, 135, 85, 0.75)"),
          Re),
        frontierButtonTertiaryPressedTextColor:
          ((Le = {}),
          (Le[Xa] = "rgba(33, 192, 99, 0.75)"),
          (Le.default = "rgba(27, 135, 85, 0.75)"),
          Le),
        frontierButtonTertiaryTextColor:
          ((Ee = {}),
          (Ee[Xa] = "rgba(33, 192, 99, 1)"),
          (Ee.default = "rgba(27, 135, 85, 1)"),
          Ee),
        frontierCheckboxColorSelectedBackground:
          ((ke = {}),
          (ke[Xa] = "rgba(250, 250, 250, 1)"),
          (ke.default = "rgba(23, 22, 22, 1)"),
          ke),
        frontierCheckboxColorSelectedBorder:
          ((Ie = {}),
          (Ie[Xa] = "rgba(250, 250, 250, 0)"),
          (Ie.default = "rgba(23, 22, 22, 0)"),
          Ie),
        frontierCheckboxColorSelectedCheck:
          ((Te = {}),
          (Te[Xa] = "rgba(10, 16, 20, 1)"),
          (Te.default = "rgba(255, 255, 255, 1)"),
          Te),
        frontierCheckboxColorSelectedDisabledBackground:
          ((De = {}),
          (De[Xa] = "rgba(62, 71, 77, 1)"),
          (De.default = "rgba(179, 185, 189, 1)"),
          De),
        frontierCheckboxColorSelectedDisabledBorder:
          ((xe = {}),
          (xe[Xa] = "rgba(62, 71, 77, 1)"),
          (xe.default = "rgba(179, 185, 189, 1)"),
          xe),
        frontierCheckboxColorSelectedDisabledCheck:
          (($e = {}),
          ($e[Xa] = "rgba(10, 16, 20, 1)"),
          ($e.default = "rgba(255, 255, 255, 1)"),
          $e),
        frontierCheckboxColorUnselectedBackground:
          ((Pe = {}),
          (Pe[Xa] = "rgba(141, 149, 153, 1)"),
          (Pe.default = "rgba(91, 99, 104, 1)"),
          Pe),
        frontierCheckboxColorUnselectedBorder:
          ((Ne = {}),
          (Ne[Xa] = "rgba(141, 149, 153, 1)"),
          (Ne.default = "rgba(91, 99, 104, 1)"),
          Ne),
        frontierCheckboxColorUnselectedDisabledBackground:
          ((Me = {}),
          (Me[Xa] = "rgba(62, 71, 77, 1)"),
          (Me.default = "rgba(179, 185, 189, 1)"),
          Me),
        frontierCheckboxColorUnselectedDisabledBorder:
          ((we = {}),
          (we[Xa] = "rgba(62, 71, 77, 1)"),
          (we.default = "rgba(179, 185, 189, 1)"),
          we),
        frontierChipColorDefaultBackground:
          ((Ae = {}),
          (Ae[Xa] = "rgba(10, 16, 20, 1)"),
          (Ae.default = "rgba(255, 255, 255, 1)"),
          Ae),
        frontierChipColorDefaultBorder:
          ((Fe = {}),
          (Fe[Xa] = "rgba(255, 255, 255, 0.1)"),
          (Fe.default = "rgba(17, 27, 33, 0.2)"),
          Fe),
        frontierChipColorDefaultIcon:
          ((Oe = {}),
          (Oe[Xa] = "rgba(141, 149, 153, 1)"),
          (Oe.default = "rgba(91, 99, 104, 1)"),
          Oe),
        frontierChipColorDefaultText:
          ((Be = {}),
          (Be[Xa] = "rgba(141, 149, 153, 1)"),
          (Be.default = "rgba(91, 99, 104, 1)"),
          Be),
        frontierChipColorDisabledBackground:
          ((We = {}),
          (We[Xa] = "rgba(10, 16, 20, 1)"),
          (We.default = "rgba(255, 255, 255, 1)"),
          We),
        frontierChipColorDisabledBorder:
          ((qe = {}),
          (qe[Xa] = "rgba(255, 255, 255, 0.1)"),
          (qe.default = "rgba(17, 27, 33, 0.2)"),
          qe),
        frontierChipColorDisabledIcon:
          ((Ue = {}),
          (Ue[Xa] = "rgba(247, 248, 250, 1)"),
          (Ue.default = "rgba(91, 99, 104, 1)"),
          Ue),
        frontierChipColorDisabledText:
          ((Ve = {}),
          (Ve[Xa] = "rgba(247, 248, 250, 1)"),
          (Ve.default = "rgba(91, 99, 104, 1)"),
          Ve),
        frontierChipColorPressedBackground:
          ((He = {}),
          (He[Xa] = "rgba(10, 16, 20, 1)"),
          (He.default = "rgba(255, 255, 255, 1)"),
          He),
        frontierChipColorPressedBorder:
          ((Ge = {}),
          (Ge[Xa] = "rgba(255, 255, 255, 0.1)"),
          (Ge.default = "rgba(17, 27, 33, 0.2)"),
          Ge),
        frontierChipColorPressedIcon:
          ((ze = {}),
          (ze[Xa] = "rgba(247, 248, 250, 1)"),
          (ze.default = "rgba(91, 99, 104, 1)"),
          ze),
        frontierChipColorPressedText:
          ((je = {}),
          (je[Xa] = "rgba(247, 248, 250, 1)"),
          (je.default = "rgba(91, 99, 104, 1)"),
          je),
        frontierChipColorSelectedBackground:
          ((Ke = {}),
          (Ke[Xa] = "rgba(32, 39, 43, 1)"),
          (Ke.default = "rgba(241, 238, 235, 1)"),
          Ke),
        frontierChipColorSelectedBorder:
          ((Qe = {}),
          (Qe[Xa] = "rgba(255, 255, 255, 0.1)"),
          (Qe.default = "rgba(17, 27, 33, 0.2)"),
          Qe),
        frontierChipColorSelectedIcon:
          ((Xe = {}),
          (Xe[Xa] = "rgba(247, 248, 250, 1)"),
          (Xe.default = "rgba(10, 16, 20, 1)"),
          Xe),
        frontierChipColorSelectedText:
          ((Ye = {}),
          (Ye[Xa] = "rgba(247, 248, 250, 1)"),
          (Ye.default = "rgba(10, 16, 20, 1)"),
          Ye),
        frontierColorBackgroundAccent:
          ((Je = {}),
          (Je[Xa] = "rgba(255, 255, 255, 1)"),
          (Je.default = "rgba(10, 16, 20, 1)"),
          Je),
        frontierColorBackgroundAccentDeemphasized:
          ((Ze = {}),
          (Ze[Xa] = "rgba(255, 255, 255, 0.5)"),
          (Ze.default = "rgba(17, 27, 33, 0.5)"),
          Ze),
        frontierColorBackgroundBrand:
          ((et = {}),
          (et[Xa] = "rgba(29, 170, 97, 1)"),
          (et.default = "rgba(29, 170, 97, 1)"),
          et),
        frontierColorBackgroundDeemphasized:
          ((tt = {}),
          (tt[Xa] = "rgba(18, 24, 28, 1)"),
          (tt.default = "rgba(247, 245, 243, 1)"),
          tt),
        frontierColorBackgroundDisabled:
          ((nt = {}),
          (nt[Xa] = "rgba(10, 16, 20, 1)"),
          (nt.default = "rgba(255, 255, 255, 1)"),
          nt),
        frontierColorBackgroundEmphasized:
          ((rt = {}),
          (rt[Xa] = "rgba(10, 16, 20, 1)"),
          (rt.default = "rgba(255, 255, 255, 1)"),
          rt),
        frontierColorBackgroundSurface:
          ((ot = {}),
          (ot[Xa] = "rgba(10, 16, 20, 1)"),
          (ot.default = "rgba(255, 255, 255, 1)"),
          ot),
        frontierColorBackgroundSurface2:
          ((at = {}),
          (at[Xa] = "rgba(10, 16, 20, 1)"),
          (at.default = "rgba(255, 255, 255, 1)"),
          at),
        frontierColorBackgroundSurface3:
          ((it = {}),
          (it[Xa] = "rgba(10, 16, 20, 1)"),
          (it.default = "rgba(255, 255, 255, 1)"),
          it),
        frontierColorBackgroundSurfaceInverted:
          ((lt = {}),
          (lt[Xa] = "rgba(255, 255, 255, 1)"),
          (lt.default = "rgba(10, 16, 20, 1)"),
          lt),
        frontierColorBackgroundSurfaceInverted2:
          ((st = {}),
          (st[Xa] = "rgba(255, 255, 255, 1)"),
          (st.default = "rgba(10, 16, 20, 1)"),
          st),
        frontierColorBackgroundTransparent:
          ((ut = {}),
          (ut[Xa] = "rgba(10, 16, 20, 0)"),
          (ut.default = "rgba(255, 255, 255, 0)"),
          ut),
        frontierColorBackgroundTransparent2:
          ((ct = {}),
          (ct[Xa] = "rgba(10, 16, 20, 0)"),
          (ct.default = "rgba(255, 255, 255, 0)"),
          ct),
        frontierColorBackgroundTransparent3:
          ((dt = {}),
          (dt[Xa] = "rgba(10, 16, 20, 0)"),
          (dt.default = "rgba(255, 255, 255, 0)"),
          dt),
        frontierColorBackgroundTransparentInverted:
          ((mt = {}),
          (mt[Xa] = "rgba(255, 255, 255, 0)"),
          (mt.default = "rgba(10, 16, 20, 0)"),
          mt),
        frontierColorBackgroundTransparentInverted2:
          ((pt = {}),
          (pt[Xa] = "rgba(255, 255, 255, 0)"),
          (pt.default = "rgba(10, 16, 20, 0)"),
          pt),
        frontierColorBackgroundTransparentInverted3:
          ((_t = {}),
          (_t[Xa] = "rgba(255, 255, 255, 0)"),
          (_t.default = "rgba(10, 16, 20, 0)"),
          _t),
        frontierColorStatusCritical:
          ((ft = {}),
          (ft[Xa] = "rgba(145, 20, 53, 1)"),
          (ft.default = "rgba(145, 20, 53, 1)"),
          ft),
        frontierColorStatusCriticalDeemphasized:
          ((gt = {}),
          (gt[Xa] = "rgba(33, 16, 24, 1)"),
          (gt.default = "rgba(251, 216, 220, 1)"),
          gt),
        frontierColorStatusInformational:
          ((ht = {}),
          (ht[Xa] = "rgba(2, 126, 181, 1)"),
          (ht.default = "rgba(2, 126, 181, 1)"),
          ht),
        frontierColorStatusInformationalDeemphasized:
          ((yt = {}),
          (yt[Xa] = "rgba(6, 29, 40, 1)"),
          (yt.default = "rgba(202, 236, 250, 1)"),
          yt),
        frontierColorStatusNegative:
          ((Ct = {}),
          (Ct[Xa] = "rgba(234, 0, 56, 1)"),
          (Ct.default = "rgba(121, 22, 50, 1)"),
          Ct),
        frontierColorStatusNegativeDeemphasized:
          ((bt = {}),
          (bt[Xa] = "rgba(33, 16, 24, 1)"),
          (bt.default = "rgba(251, 216, 220, 1)"),
          bt),
        frontierColorStatusPositive:
          ((vt = {}),
          (vt[Xa] = "rgba(37, 211, 102, 1)"),
          (vt.default = "rgba(24, 116, 74, 1)"),
          vt),
        frontierColorStatusPositiveDeemphasized:
          ((St = {}),
          (St[Xa] = "rgba(33, 16, 24, 1)"),
          (St.default = "rgba(217, 253, 211, 1)"),
          St),
        frontierColorStatusWarning:
          ((Rt = {}),
          (Rt[Xa] = "rgba(255, 185, 56, 1)"),
          (Rt.default = "rgba(133, 93, 41, 1)"),
          Rt),
        frontierColorStatusWarningDeemphasized:
          ((Lt = {}),
          (Lt[Xa] = "rgba(37, 30, 22, 1)"),
          (Lt.default = "rgba(255, 240, 212, 1)"),
          Lt),
        frontierDialogColorBackground:
          ((Et = {}),
          (Et[Xa] = "rgba(10, 16, 20, 1)"),
          (Et.default = "rgba(255, 255, 255, 1)"),
          Et),
        frontierDividerColorBackgroundDefault:
          ((kt = {}),
          (kt[Xa] = "rgba(255, 255, 255, 0.1)"),
          (kt.default = "rgba(17, 27, 33, 0.1)"),
          kt),
        frontierIconColorBrand:
          ((It = {}),
          (It[Xa] = "rgba(29, 170, 97, 1)"),
          (It.default = "rgba(29, 170, 97, 1)"),
          It),
        frontierIconColorDisabled:
          ((Tt = {}),
          (Tt[Xa] = "rgba(77, 85, 91, 1)"),
          (Tt.default = "rgba(141, 149, 153, 1)"),
          Tt),
        frontierIconColorInverted:
          ((Dt = {}),
          (Dt[Xa] = "rgba(10, 16, 20, 1)"),
          (Dt.default = "rgba(247, 248, 250, 1)"),
          Dt),
        frontierIconColorLink:
          ((xt = {}),
          (xt[Xa] = "rgba(33, 192, 99, 1)"),
          (xt.default = "rgba(29, 170, 97, 1)"),
          xt),
        frontierIconColorNegative:
          (($t = {}),
          ($t[Xa] = "rgba(234, 0, 56, 1)"),
          ($t.default = "rgba(121, 22, 50, 1)"),
          $t),
        frontierIconColorPlaceholder:
          ((Pt = {}),
          (Pt[Xa] = "rgba(141, 149, 153, 1)"),
          (Pt.default = "rgba(91, 99, 104, 1)"),
          Pt),
        frontierIconColorPositive:
          ((Nt = {}),
          (Nt[Xa] = "rgba(37, 211, 102, 1)"),
          (Nt.default = "rgba(24, 116, 74, 1)"),
          Nt),
        frontierIconColorPrimary:
          ((Mt = {}),
          (Mt[Xa] = "rgba(247, 248, 250, 1)"),
          (Mt.default = "rgba(10, 16, 20, 1)"),
          Mt),
        frontierIconColorPrimaryOnMedia:
          ((wt = {}),
          (wt[Xa] = "rgba(255, 255, 255, 1)"),
          (wt.default = "rgba(255, 255, 255, 1)"),
          wt),
        frontierIconColorSecondary:
          ((At = {}),
          (At[Xa] = "rgba(141, 149, 153, 1)"),
          (At.default = "rgba(91, 99, 104, 1)"),
          At),
        frontierIconColorWarning:
          ((Ft = {}),
          (Ft[Xa] = "rgba(255, 185, 56, 1)"),
          (Ft.default = "rgba(133, 93, 41, 1)"),
          Ft),
        frontierListcellColorOverlayHover:
          ((Ot = {}),
          (Ot[Xa] = "var(--hover-overlay)"),
          (Ot.default = "var(--hover-overlay)"),
          Ot),
        frontierListcellColorOverlayPressed:
          ((Bt = {}),
          (Bt[Xa] = "var(--press-overlay)"),
          (Bt.default = "var(--press-overlay)"),
          Bt),
        frontierListColorBackground:
          ((Wt = {}),
          (Wt[Xa] = "rgba(10, 16, 20, 1)"),
          (Wt.default = "rgba(255, 255, 255, 1)"),
          Wt),
        frontierListColorBorder:
          ((qt = {}),
          (qt[Xa] = "rgba(255, 255, 255, 0.1)"),
          (qt.default = "rgba(17, 27, 33, 0.1)"),
          qt),
        frontierMenuColorBackground:
          ((Ut = {}),
          (Ut[Xa] = "rgba(10, 16, 20, 1)"),
          (Ut.default = "rgba(255, 255, 255, 1)"),
          Ut),
        frontierMenuColorBorder:
          ((Vt = {}),
          (Vt[Xa] = "rgba(255, 255, 255, 0.1)"),
          (Vt.default = "rgba(17, 27, 33, 0.1)"),
          Vt),
        frontierPillColorBackgroundCritical:
          ((Ht = {}),
          (Ht[Xa] = "rgba(145, 20, 53, 1)"),
          (Ht.default = "rgba(145, 20, 53, 1)"),
          Ht),
        frontierPillColorBackgroundCriticalDeemphasized:
          ((Gt = {}),
          (Gt[Xa] = "rgba(33, 16, 24, 1)"),
          (Gt.default = "rgba(251, 216, 220, 1)"),
          Gt),
        frontierPillColorBackgroundDeemphasized:
          ((zt = {}),
          (zt[Xa] = "rgba(18, 24, 28, 1)"),
          (zt.default = "rgba(234, 237, 238, 1)"),
          zt),
        frontierPillColorBackgroundInformational:
          ((jt = {}),
          (jt[Xa] = "rgba(2, 126, 181, 1)"),
          (jt.default = "rgba(2, 126, 181, 1)"),
          jt),
        frontierPillColorBackgroundInformationalDeemphasized:
          ((Kt = {}),
          (Kt[Xa] = "rgba(6, 29, 40, 1)"),
          (Kt.default = "rgba(202, 236, 250, 1)"),
          Kt),
        frontierPillColorBackgroundPositive:
          ((Qt = {}),
          (Qt[Xa] = "rgba(37, 211, 102, 1)"),
          (Qt.default = "rgba(24, 116, 74, 1)"),
          Qt),
        frontierPillColorBackgroundPositiveDeemphasized:
          ((Xt = {}),
          (Xt[Xa] = "rgba(33, 16, 24, 1)"),
          (Xt.default = "rgba(217, 253, 211, 1)"),
          Xt),
        frontierPillColorBackgroundWarning:
          ((Yt = {}),
          (Yt[Xa] = "rgba(255, 185, 56, 1)"),
          (Yt.default = "rgba(133, 93, 41, 1)"),
          Yt),
        frontierPillColorBackgroundWarningDeemphasized:
          ((Jt = {}),
          (Jt[Xa] = "rgba(37, 30, 22, 1)"),
          (Jt.default = "rgba(255, 240, 212, 1)"),
          Jt),
        frontierProgressBarColorBrand:
          ((Zt = {}),
          (Zt[Xa] = "rgba(29, 170, 97, 1)"),
          (Zt.default = "rgba(29, 170, 97, 1)"),
          Zt),
        frontierProgressBarColorDisabled:
          ((en = {}),
          (en[Xa] = "rgba(77, 85, 91, 1)"),
          (en.default = "rgba(141, 149, 153, 1)"),
          en),
        frontierProgressBarColorNegative:
          ((tn = {}),
          (tn[Xa] = "rgba(234, 0, 56, 1)"),
          (tn.default = "rgba(121, 22, 50, 1)"),
          tn),
        frontierProgressBarColorPositive:
          ((nn = {}),
          (nn[Xa] = "rgba(37, 211, 102, 1)"),
          (nn.default = "rgba(24, 116, 74, 1)"),
          nn),
        frontierProgressBarColorPrimary:
          ((rn = {}),
          (rn[Xa] = "rgba(247, 248, 250, 1)"),
          (rn.default = "rgba(10, 16, 20, 1)"),
          rn),
        frontierProgressBarColorPrimaryOnMedia:
          ((on = {}),
          (on[Xa] = "rgba(255, 255, 255, 1)"),
          (on.default = "rgba(255, 255, 255, 1)"),
          on),
        frontierProgressBarColorSecondary:
          ((an = {}),
          (an[Xa] = "rgba(141, 149, 153, 1)"),
          (an.default = "rgba(91, 99, 104, 1)"),
          an),
        frontierProgressBarColorTrack:
          ((ln = {}),
          (ln[Xa] = "rgba(18, 24, 28, 1)"),
          (ln.default = "rgba(247, 245, 243, 1)"),
          ln),
        frontierProgressBarColorWarning:
          ((sn = {}),
          (sn[Xa] = "rgba(255, 185, 56, 1)"),
          (sn.default = "rgba(133, 93, 41, 1)"),
          sn),
        frontierProgressRingColorBrand:
          ((un = {}),
          (un[Xa] = "rgba(29, 170, 97, 1)"),
          (un.default = "rgba(29, 170, 97, 1)"),
          un),
        frontierProgressRingColorDisabled:
          ((cn = {}),
          (cn[Xa] = "rgba(77, 85, 91, 1)"),
          (cn.default = "rgba(141, 149, 153, 1)"),
          cn),
        frontierProgressRingColorNegative:
          ((dn = {}),
          (dn[Xa] = "rgba(234, 0, 56, 1)"),
          (dn.default = "rgba(121, 22, 50, 1)"),
          dn),
        frontierProgressRingColorPositive:
          ((mn = {}),
          (mn[Xa] = "rgba(37, 211, 102, 1)"),
          (mn.default = "rgba(24, 116, 74, 1)"),
          mn),
        frontierProgressRingColorPrimary:
          ((pn = {}),
          (pn[Xa] = "rgba(247, 248, 250, 1)"),
          (pn.default = "rgba(10, 16, 20, 1)"),
          pn),
        frontierProgressRingColorPrimaryOnMedia:
          ((_n = {}),
          (_n[Xa] = "rgba(255, 255, 255, 1)"),
          (_n.default = "rgba(255, 255, 255, 1)"),
          _n),
        frontierProgressRingColorSecondary:
          ((fn = {}),
          (fn[Xa] = "rgba(141, 149, 153, 1)"),
          (fn.default = "rgba(91, 99, 104, 1)"),
          fn),
        frontierProgressRingColorTrack:
          ((gn = {}),
          (gn[Xa] = "rgba(18, 24, 28, 1)"),
          (gn.default = "rgba(247, 245, 243, 1)"),
          gn),
        frontierProgressRingColorWarning:
          ((hn = {}),
          (hn[Xa] = "rgba(255, 185, 56, 1)"),
          (hn.default = "rgba(133, 93, 41, 1)"),
          hn),
        frontierRadioColorSelectedBackground:
          ((yn = {}),
          (yn[Xa] = "rgba(0, 0, 0, 0)"),
          (yn.default = "rgba(255, 255, 255, 0)"),
          yn),
        frontierRadioColorSelectedBorder:
          ((Cn = {}),
          (Cn[Xa] = "rgba(250, 250, 250, 1)"),
          (Cn.default = "rgba(23, 22, 22, 1)"),
          Cn),
        frontierRadioColorSelectedCheck:
          ((bn = {}),
          (bn[Xa] = "rgba(250, 250, 250, 1)"),
          (bn.default = "rgba(23, 22, 22, 1)"),
          bn),
        frontierRadioColorSelectedDisabledBackground:
          ((vn = {}),
          (vn[Xa] = "rgba(0, 0, 0, 0)"),
          (vn.default = "rgba(255, 255, 255, 0)"),
          vn),
        frontierRadioColorSelectedDisabledBorder:
          ((Sn = {}),
          (Sn[Xa] = "rgba(62, 71, 77, 1)"),
          (Sn.default = "rgba(179, 185, 189, 1)"),
          Sn),
        frontierRadioColorSelectedDisabledCheck:
          ((Rn = {}),
          (Rn[Xa] = "rgba(62, 71, 77, 1)"),
          (Rn.default = "rgba(179, 185, 189, 1)"),
          Rn),
        frontierRadioColorUnselectedBackground:
          ((Ln = {}),
          (Ln[Xa] = "rgba(0, 0, 0, 0)"),
          (Ln.default = "rgba(255, 255, 255, 0)"),
          Ln),
        frontierRadioColorUnselectedBorder:
          ((En = {}),
          (En[Xa] = "rgba(141, 149, 153, 1)"),
          (En.default = "rgba(91, 99, 104, 1)"),
          En),
        frontierRadioColorUnselectedDisabledBackground:
          ((kn = {}),
          (kn[Xa] = "rgba(0, 0, 0, 0)"),
          (kn.default = "rgba(255, 255, 255, 0)"),
          kn),
        frontierRadioColorUnselectedDisabledBorder:
          ((In = {}),
          (In[Xa] = "rgba(62, 71, 77, 1)"),
          (In.default = "rgba(179, 185, 189, 1)"),
          In),
        frontierSearchfieldColorBackground:
          ((Tn = {}),
          (Tn[Xa] = "rgba(255, 255, 255, 0.1)"),
          (Tn.default = "rgba(194, 189, 184, 0.15)"),
          Tn),
        frontierSearchfieldColorBorder:
          ((Dn = {}),
          (Dn[Xa] = "rgba(255, 255, 255, 0.1)"),
          (Dn.default = "rgba(194, 189, 184, 0.15)"),
          Dn),
        frontierSearchfieldColorDefaultIconLeft:
          ((xn = {}),
          (xn[Xa] = "rgba(247, 248, 250, 1)"),
          (xn.default = "rgba(10, 16, 20, 1)"),
          xn),
        frontierSearchfieldColorDefaultIconRight:
          (($n = {}),
          ($n[Xa] = "rgba(247, 248, 250, 1)"),
          ($n.default = "rgba(10, 16, 20, 1)"),
          $n),
        frontierSearchfieldColorDefaultPlaceholder:
          ((Pn = {}),
          (Pn[Xa] = "rgba(141, 149, 153, 1)"),
          (Pn.default = "rgba(91, 99, 104, 1)"),
          Pn),
        frontierSearchfieldColorDisabledIconLeft:
          ((Nn = {}),
          (Nn[Xa] = "rgba(247, 248, 250, 1)"),
          (Nn.default = "rgba(10, 16, 20, 1)"),
          Nn),
        frontierSearchfieldColorDisabledIconRight:
          ((Mn = {}),
          (Mn[Xa] = "rgba(247, 248, 250, 1)"),
          (Mn.default = "rgba(10, 16, 20, 1)"),
          Mn),
        frontierSearchfieldColorDisabledText:
          ((wn = {}),
          (wn[Xa] = "rgba(141, 149, 153, 1)"),
          (wn.default = "rgba(91, 99, 104, 1)"),
          wn),
        frontierSearchfieldColorFocusIconLeft:
          ((An = {}),
          (An[Xa] = "rgba(247, 248, 250, 1)"),
          (An.default = "rgba(10, 16, 20, 1)"),
          An),
        frontierSearchfieldColorFocusIconRight:
          ((Fn = {}),
          (Fn[Xa] = "rgba(247, 248, 250, 1)"),
          (Fn.default = "rgba(10, 16, 20, 1)"),
          Fn),
        frontierSearchfieldColorFocusPlaceholder:
          ((On = {}),
          (On[Xa] = "rgba(141, 149, 153, 1)"),
          (On.default = "rgba(91, 99, 104, 1)"),
          On),
        frontierSearchfieldColorFocusText:
          ((Bn = {}),
          (Bn[Xa] = "rgba(247, 248, 250, 1)"),
          (Bn.default = "rgba(10, 16, 20, 1)"),
          Bn),
        frontierSearchfieldColorResultIconLeft:
          ((Wn = {}),
          (Wn[Xa] = "rgba(247, 248, 250, 1)"),
          (Wn.default = "rgba(10, 16, 20, 1)"),
          Wn),
        frontierSearchfieldColorResultIconRight:
          ((qn = {}),
          (qn[Xa] = "rgba(247, 248, 250, 1)"),
          (qn.default = "rgba(10, 16, 20, 1)"),
          qn),
        frontierSearchfieldColorResultText:
          ((Un = {}),
          (Un[Xa] = "rgba(247, 248, 250, 1)"),
          (Un.default = "rgba(10, 16, 20, 1)"),
          Un),
        frontierSearchfieldColorTypingIconLeft:
          ((Vn = {}),
          (Vn[Xa] = "rgba(247, 248, 250, 1)"),
          (Vn.default = "rgba(10, 16, 20, 1)"),
          Vn),
        frontierSearchfieldColorTypingIconRight:
          ((Hn = {}),
          (Hn[Xa] = "rgba(247, 248, 250, 1)"),
          (Hn.default = "rgba(10, 16, 20, 1)"),
          Hn),
        frontierSearchfieldColorTypingText:
          ((Gn = {}),
          (Gn[Xa] = "rgba(247, 248, 250, 1)"),
          (Gn.default = "rgba(10, 16, 20, 1)"),
          Gn),
        frontierSelectinputColorEmptyBackground:
          ((zn = {}),
          (zn[Xa] = "rgba(10, 16, 20, 1)"),
          (zn.default = "rgba(255, 255, 255, 1)"),
          zn),
        frontierSelectinputColorEmptyBorder:
          ((jn = {}),
          (jn[Xa] = "rgba(108, 117, 122, 1)"),
          (jn.default = "rgba(141, 149, 153, 1)"),
          jn),
        frontierSelectinputColorEmptyHelper:
          ((Kn = {}),
          (Kn[Xa] = "rgba(141, 149, 153, 1)"),
          (Kn.default = "rgba(91, 99, 104, 1)"),
          Kn),
        frontierSelectinputColorEmptyInput:
          ((Qn = {}),
          (Qn[Xa] = "rgba(247, 248, 250, 1)"),
          (Qn.default = "rgba(10, 16, 20, 1)"),
          Qn),
        frontierSelectinputColorEmptyLabel:
          ((Xn = {}),
          (Xn[Xa] = "rgba(141, 149, 153, 1)"),
          (Xn.default = "rgba(91, 99, 104, 1)"),
          Xn),
        frontierSelectinputColorEmptyValidationBackground:
          ((Yn = {}),
          (Yn[Xa] = "rgba(10, 16, 20, 1)"),
          (Yn.default = "rgba(255, 255, 255, 1)"),
          Yn),
        frontierSelectinputColorEmptyValidationBorder:
          ((Jn = {}),
          (Jn[Xa] = "rgba(251, 80, 97, 1)"),
          (Jn.default = "rgba(234, 0, 56, 1)"),
          Jn),
        frontierSelectinputColorEmptyValidationHelper:
          ((Zn = {}),
          (Zn[Xa] = "rgba(251, 80, 97, 1)"),
          (Zn.default = "rgba(234, 0, 56, 1)"),
          Zn),
        frontierSelectinputColorEmptyValidationIconRight:
          ((er = {}),
          (er[Xa] = "rgba(251, 80, 97, 1)"),
          (er.default = "rgba(234, 0, 56, 1)"),
          er),
        frontierSelectinputColorEmptyValidationInput:
          ((tr = {}),
          (tr[Xa] = "rgba(247, 248, 250, 1)"),
          (tr.default = "rgba(10, 16, 20, 1)"),
          tr),
        frontierSelectinputColorEmptyValidationLabel:
          ((nr = {}),
          (nr[Xa] = "rgba(251, 80, 97, 1)"),
          (nr.default = "rgba(234, 0, 56, 1)"),
          nr),
        frontierSelectinputColorFilledBackground:
          ((rr = {}),
          (rr[Xa] = "rgba(10, 16, 20, 1)"),
          (rr.default = "rgba(255, 255, 255, 1)"),
          rr),
        frontierSelectinputColorFilledBorder:
          ((or = {}),
          (or[Xa] = "rgba(108, 117, 122, 1)"),
          (or.default = "rgba(141, 149, 153, 1)"),
          or),
        frontierSelectinputColorFilledDisabledBackground:
          ((ar = {}),
          (ar[Xa] = "rgba(10, 16, 20, 1)"),
          (ar.default = "rgba(255, 255, 255, 1)"),
          ar),
        frontierSelectinputColorFilledDisabledBorder:
          ((ir = {}),
          (ir[Xa] = "rgba(108, 117, 122, 1)"),
          (ir.default = "rgba(141, 149, 153, 1)"),
          ir),
        frontierSelectinputColorFilledDisabledHelper:
          ((lr = {}),
          (lr[Xa] = "rgba(141, 149, 153, 1)"),
          (lr.default = "rgba(91, 99, 104, 1)"),
          lr),
        frontierSelectinputColorFilledDisabledInput:
          ((sr = {}),
          (sr[Xa] = "rgba(141, 149, 153, 1)"),
          (sr.default = "rgba(10, 16, 20, 1)"),
          sr),
        frontierSelectinputColorFilledDisabledLabel:
          ((ur = {}),
          (ur[Xa] = "rgba(141, 149, 153, 1)"),
          (ur.default = "rgba(91, 99, 104, 1)"),
          ur),
        frontierSelectinputColorFilledHelper:
          ((cr = {}),
          (cr[Xa] = "rgba(141, 149, 153, 1)"),
          (cr.default = "rgba(91, 99, 104, 1)"),
          cr),
        frontierSelectinputColorFilledInput:
          ((dr = {}),
          (dr[Xa] = "rgba(247, 248, 250, 1)"),
          (dr.default = "rgba(10, 16, 20, 1)"),
          dr),
        frontierSelectinputColorFilledLabel:
          ((mr = {}),
          (mr[Xa] = "rgba(141, 149, 153, 1)"),
          (mr.default = "rgba(91, 99, 104, 1)"),
          mr),
        frontierSelectinputColorFocusedBackground:
          ((pr = {}),
          (pr[Xa] = "rgba(10, 16, 20, 1)"),
          (pr.default = "rgba(255, 255, 255, 1)"),
          pr),
        frontierSelectinputColorFocusedBorder:
          ((_r = {}),
          (_r[Xa] = "rgba(247, 248, 250, 1)"),
          (_r.default = "rgba(10, 16, 20, 1)"),
          _r),
        frontierSelectinputColorFocusedHelper:
          ((fr = {}),
          (fr[Xa] = "rgba(141, 149, 153, 1)"),
          (fr.default = "rgba(91, 99, 104, 1)"),
          fr),
        frontierSelectinputColorFocusedIconRight:
          ((gr = {}),
          (gr[Xa] = "rgba(247, 248, 250, 1)"),
          (gr.default = "rgba(10, 16, 20, 1)"),
          gr),
        frontierSelectinputColorFocusedInput:
          ((hr = {}),
          (hr[Xa] = "rgba(247, 248, 250, 1)"),
          (hr.default = "rgba(10, 16, 20, 1)"),
          hr),
        frontierSelectinputColorFocusedLabel:
          ((yr = {}),
          (yr[Xa] = "rgba(247, 248, 250, 1)"),
          (yr.default = "rgba(10, 16, 20, 1)"),
          yr),
        frontierSelectinputColorSuccessBackground:
          ((Cr = {}),
          (Cr[Xa] = "rgba(10, 16, 20, 1)"),
          (Cr.default = "rgba(255, 255, 255, 1)"),
          Cr),
        frontierSelectinputColorSuccessBorder:
          ((br = {}),
          (br[Xa] = "rgba(108, 117, 122, 1)"),
          (br.default = "rgba(141, 149, 153, 1)"),
          br),
        frontierSelectinputColorSuccessFocusedBackground:
          ((vr = {}),
          (vr[Xa] = "rgba(10, 16, 20, 1)"),
          (vr.default = "rgba(255, 255, 255, 1)"),
          vr),
        frontierSelectinputColorSuccessFocusedBorder:
          ((Sr = {}),
          (Sr[Xa] = "rgba(247, 248, 250, 1)"),
          (Sr.default = "rgba(10, 16, 20, 1)"),
          Sr),
        frontierSelectinputColorSuccessFocusedHelper:
          ((Rr = {}),
          (Rr[Xa] = "rgba(141, 149, 153, 1)"),
          (Rr.default = "rgba(91, 99, 104, 1)"),
          Rr),
        frontierSelectinputColorSuccessFocusedIconRight:
          ((Lr = {}),
          (Lr[Xa] = "rgba(113, 235, 133, 1)"),
          (Lr.default = "rgba(29, 170, 97, 1)"),
          Lr),
        frontierSelectinputColorSuccessFocusedInput:
          ((Er = {}),
          (Er[Xa] = "rgba(247, 248, 250, 1)"),
          (Er.default = "rgba(10, 16, 20, 1)"),
          Er),
        frontierSelectinputColorSuccessFocusedLabel:
          ((kr = {}),
          (kr[Xa] = "rgba(247, 248, 250, 1)"),
          (kr.default = "rgba(10, 16, 20, 1)"),
          kr),
        frontierSelectinputColorSuccessHelper:
          ((Ir = {}),
          (Ir[Xa] = "rgba(141, 149, 153, 1)"),
          (Ir.default = "rgba(91, 99, 104, 1)"),
          Ir),
        frontierSelectinputColorSuccessIconRight:
          ((Tr = {}),
          (Tr[Xa] = "rgba(113, 235, 133, 1)"),
          (Tr.default = "rgba(29, 170, 97, 1)"),
          Tr),
        frontierSelectinputColorSuccessInput:
          ((Dr = {}),
          (Dr[Xa] = "rgba(247, 248, 250, 1)"),
          (Dr.default = "rgba(10, 16, 20, 1)"),
          Dr),
        frontierSelectinputColorSuccessLabel:
          ((xr = {}),
          (xr[Xa] = "rgba(141, 149, 153, 1)"),
          (xr.default = "rgba(91, 99, 104, 1)"),
          xr),
        frontierSelectinputColorValidationBackground:
          (($r = {}),
          ($r[Xa] = "rgba(10, 16, 20, 1)"),
          ($r.default = "rgba(255, 255, 255, 1)"),
          $r),
        frontierSelectinputColorValidationBorder:
          ((Pr = {}),
          (Pr[Xa] = "rgba(251, 80, 97, 1)"),
          (Pr.default = "rgba(234, 0, 56, 1)"),
          Pr),
        frontierSelectinputColorValidationHelper:
          ((Nr = {}),
          (Nr[Xa] = "rgba(251, 80, 97, 1)"),
          (Nr.default = "rgba(234, 0, 56, 1)"),
          Nr),
        frontierSelectinputColorValidationIconRight:
          ((Mr = {}),
          (Mr[Xa] = "rgba(251, 80, 97, 1)"),
          (Mr.default = "rgba(234, 0, 56, 1)"),
          Mr),
        frontierSelectinputColorValidationInput:
          ((wr = {}),
          (wr[Xa] = "rgba(247, 248, 250, 1)"),
          (wr.default = "rgba(10, 16, 20, 1)"),
          wr),
        frontierSelectinputColorValidationLabel:
          ((Ar = {}),
          (Ar[Xa] = "rgba(251, 80, 97, 1)"),
          (Ar.default = "rgba(234, 0, 56, 1)"),
          Ar),
        frontierShimmer:
          ((Fr = {}), (Fr[Xa] = "#dbdbdb"), (Fr.default = "#262626"), Fr),
        frontierSpinnerColorBrand:
          ((Or = {}),
          (Or[Xa] = "rgba(29, 170, 97, 1)"),
          (Or.default = "rgba(29, 170, 97, 1)"),
          Or),
        frontierSpinnerColorInverse:
          ((Br = {}),
          (Br[Xa] = "rgba(10, 16, 20, 1)"),
          (Br.default = "rgba(247, 248, 250, 1)"),
          Br),
        frontierSpinnerColorPrimary:
          ((Wr = {}),
          (Wr[Xa] = "rgba(247, 248, 250, 1)"),
          (Wr.default = "rgba(10, 16, 20, 1)"),
          Wr),
        frontierSpinnerColorPrimaryOnMedia:
          ((qr = {}),
          (qr[Xa] = "rgba(255, 255, 255, 1)"),
          (qr.default = "rgba(255, 255, 255, 1)"),
          qr),
        frontierSpinnerColorSecondary:
          ((Ur = {}),
          (Ur[Xa] = "rgba(141, 149, 153, 1)"),
          (Ur.default = "rgba(91, 99, 104, 1)"),
          Ur),
        frontierStepperColorBrand:
          ((Vr = {}),
          (Vr[Xa] = "rgba(29, 170, 97, 1)"),
          (Vr.default = "rgba(29, 170, 97, 1)"),
          Vr),
        frontierStepperColorDisabled:
          ((Hr = {}),
          (Hr[Xa] = "rgba(77, 85, 91, 1)"),
          (Hr.default = "rgba(141, 149, 153, 1)"),
          Hr),
        frontierStepperColorNegative:
          ((Gr = {}),
          (Gr[Xa] = "rgba(234, 0, 56, 1)"),
          (Gr.default = "rgba(121, 22, 50, 1)"),
          Gr),
        frontierStepperColorPositive:
          ((zr = {}),
          (zr[Xa] = "rgba(37, 211, 102, 1)"),
          (zr.default = "rgba(24, 116, 74, 1)"),
          zr),
        frontierStepperColorPrimary:
          ((jr = {}),
          (jr[Xa] = "rgba(247, 248, 250, 1)"),
          (jr.default = "rgba(10, 16, 20, 1)"),
          jr),
        frontierStepperColorPrimaryOnMedia:
          ((Kr = {}),
          (Kr[Xa] = "rgba(255, 255, 255, 1)"),
          (Kr.default = "rgba(255, 255, 255, 1)"),
          Kr),
        frontierStepperColorSecondary:
          ((Qr = {}),
          (Qr[Xa] = "rgba(141, 149, 153, 1)"),
          (Qr.default = "rgba(91, 99, 104, 1)"),
          Qr),
        frontierStepperColorWarning:
          ((Xr = {}),
          (Xr[Xa] = "rgba(255, 185, 56, 1)"),
          (Xr.default = "rgba(133, 93, 41, 1)"),
          Xr),
        frontierSwitchColorHandleSelectedBackground:
          ((Yr = {}),
          (Yr[Xa] = "rgba(10, 10, 10, 1)"),
          (Yr.default = "rgba(255, 255, 255, 1)"),
          Yr),
        frontierSwitchColorHandleSelectedBorder:
          ((Jr = {}),
          (Jr[Xa] = "rgba(10, 10, 10, 1)"),
          (Jr.default = "rgba(255, 255, 255, 1)"),
          Jr),
        frontierSwitchColorHandleSelectedDisabledBackground:
          ((Zr = {}),
          (Zr[Xa] = "rgba(10, 10, 10, 1)"),
          (Zr.default = "rgba(255, 255, 255, 1)"),
          Zr),
        frontierSwitchColorHandleSelectedDisabledBorder:
          ((eo = {}),
          (eo[Xa] = "rgba(10, 10, 10, 1)"),
          (eo.default = "rgba(255, 255, 255, 1)"),
          eo),
        frontierSwitchColorHandleUnselectedBackground:
          ((to = {}),
          (to[Xa] = "rgba(117, 119, 120, 1)"),
          (to.default = "rgba(141, 149, 153, 1)"),
          to),
        frontierSwitchColorHandleUnselectedBorder:
          ((no = {}),
          (no[Xa] = "rgba(117, 119, 120, 1)"),
          (no.default = "rgba(141, 149, 153, 1)"),
          no),
        frontierSwitchColorHandleUnselectedDisabledBackground:
          ((ro = {}),
          (ro[Xa] = "rgba(117, 119, 120, 1)"),
          (ro.default = "rgba(141, 149, 153, 1)"),
          ro),
        frontierSwitchColorHandleUnselectedDisabledBorder:
          ((oo = {}),
          (oo[Xa] = "rgba(117, 119, 120, 1)"),
          (oo.default = "rgba(141, 149, 153, 1)"),
          oo),
        frontierSwitchColorTrackerSelectedBackground:
          ((ao = {}),
          (ao[Xa] = "rgba(250, 250, 250, 1)"),
          (ao.default = "rgba(23, 22, 22, 1)"),
          ao),
        frontierSwitchColorTrackerSelectedBorder:
          ((io = {}),
          (io[Xa] = "rgba(250, 250, 250, 1)"),
          (io.default = "rgba(23, 22, 22, 1)"),
          io),
        frontierSwitchColorTrackerSelectedDisabledBackground:
          ((lo = {}),
          (lo[Xa] = "rgba(250, 250, 250, 1)"),
          (lo.default = "rgba(23, 22, 22, 1)"),
          lo),
        frontierSwitchColorTrackerSelectedDisabledBorder:
          ((so = {}),
          (so[Xa] = "rgba(250, 250, 250, 1)"),
          (so.default = "rgba(23, 22, 22, 1)"),
          so),
        frontierSwitchColorTrackerUnselectedBackground:
          ((uo = {}),
          (uo[Xa] = "rgba(36, 38, 38, 1)"),
          (uo.default = "rgba(247, 245, 243, 1)"),
          uo),
        frontierSwitchColorTrackerUnselectedBorder:
          ((co = {}),
          (co[Xa] = "rgba(117, 119, 120, 1)"),
          (co.default = "rgba(141, 149, 153, 1)"),
          co),
        frontierSwitchColorTrackerUnselectedDisabledBackground:
          ((mo = {}),
          (mo[Xa] = "rgba(36, 38, 38, 1)"),
          (mo.default = "rgba(247, 245, 243, 1)"),
          mo),
        frontierSwitchColorTrackerUnselectedDisabledBorder:
          ((po = {}),
          (po[Xa] = "rgba(117, 119, 120, 1)"),
          (po.default = "rgba(141, 149, 153, 1)"),
          po),
        frontierTableColorBackground:
          ((_o = {}),
          (_o[Xa] = "rgba(36, 37, 38, 1)"),
          (_o.default = "rgba(255, 255, 255, 1)"),
          _o),
        frontierTableColorBorder:
          ((fo = {}),
          (fo[Xa] = "rgba(62, 64, 66, 1)"),
          (fo.default = "rgba(206, 208, 212, 1)"),
          fo),
        frontierTableColorHeaderBackground:
          ((go = {}),
          (go[Xa] = "rgba(255, 255, 255, 0.1)"),
          (go.default = "rgba(240, 242, 245, 1)"),
          go),
        frontierTableColorHeaderBorder:
          ((ho = {}),
          (ho[Xa] = "rgba(62, 64, 66, 1)"),
          (ho.default = "rgba(206, 208, 212, 1)"),
          ho),
        frontierTableColorRowHover:
          ((yo = {}),
          (yo[Xa] = "rgba(255, 255, 255, 0.1)"),
          (yo.default = "rgba(0, 0, 0, 0.05)"),
          yo),
        frontierTableColorRowSelected:
          ((Co = {}),
          (Co[Xa] = "rgba(45, 136, 255, 0.1)"),
          (Co.default = "rgba(231, 252, 227, 1)"),
          Co),
        frontierTableColorSortIcon:
          ((bo = {}),
          (bo[Xa] = "rgba(176, 179, 184, 1)"),
          (bo.default = "rgba(101, 103, 107, 1)"),
          bo),
        frontierTableColorSortIconActive:
          ((vo = {}),
          (vo[Xa] = "rgba(27, 135, 85, 1)"),
          (vo.default = "rgba(27, 135, 85, 1)"),
          vo),
        frontierTableColorTextHeader:
          ((So = {}),
          (So[Xa] = "rgba(228, 230, 235, 1)"),
          (So.default = "rgba(5, 5, 5, 1)"),
          So),
        frontierTableColorTextPrimary:
          ((Ro = {}),
          (Ro[Xa] = "rgba(228, 230, 235, 1)"),
          (Ro.default = "rgba(5, 5, 5, 1)"),
          Ro),
        frontierTabsColorBorder:
          ((Lo = {}),
          (Lo[Xa] = "rgba(255, 255, 255, 0)"),
          (Lo.default = "rgba(255, 255, 255, 0)"),
          Lo),
        frontierTabsColorItemSelectedBackground:
          ((Eo = {}),
          (Eo[Xa] = "rgba(255, 255, 255, 0)"),
          (Eo.default = "rgba(255, 255, 255, 0)"),
          Eo),
        frontierTabsColorItemSelectedBorder:
          ((ko = {}),
          (ko[Xa] = "rgba(247, 248, 250, 1)"),
          (ko.default = "rgba(10, 16, 20, 1)"),
          ko),
        frontierTabsColorItemSelectedText:
          ((Io = {}),
          (Io[Xa] = "rgba(247, 248, 250, 1)"),
          (Io.default = "rgba(10, 16, 20, 1)"),
          Io),
        frontierTabsColorItemUnselectedText:
          ((To = {}),
          (To[Xa] = "rgba(141, 149, 153, 1)"),
          (To.default = "rgba(91, 99, 104, 1)"),
          To),
        frontierTextbadgeColorBackgroundCritical:
          ((Do = {}),
          (Do[Xa] = "rgba(145, 20, 53, 1)"),
          (Do.default = "rgba(145, 20, 53, 1)"),
          Do),
        frontierTextbadgeColorBackgroundCriticalDeemphasized:
          ((xo = {}),
          (xo[Xa] = "rgba(33, 16, 24, 1)"),
          (xo.default = "rgba(251, 216, 220, 1)"),
          xo),
        frontierTextbadgeColorBackgroundDeemphasized:
          (($o = {}),
          ($o[Xa] = "rgba(18, 24, 28, 1)"),
          ($o.default = "rgba(234, 237, 238, 1)"),
          $o),
        frontierTextbadgeColorBackgroundInformational:
          ((Po = {}),
          (Po[Xa] = "rgba(2, 126, 181, 1)"),
          (Po.default = "rgba(2, 126, 181, 1)"),
          Po),
        frontierTextbadgeColorBackgroundInformationalDeemphasized:
          ((No = {}),
          (No[Xa] = "rgba(6, 29, 40, 1)"),
          (No.default = "rgba(202, 236, 250, 1)"),
          No),
        frontierTextbadgeColorBackgroundPositive:
          ((Mo = {}),
          (Mo[Xa] = "rgba(37, 211, 102, 1)"),
          (Mo.default = "rgba(24, 116, 74, 1)"),
          Mo),
        frontierTextbadgeColorBackgroundPositiveDeemphasized:
          ((wo = {}),
          (wo[Xa] = "rgba(33, 16, 24, 1)"),
          (wo.default = "rgba(217, 253, 211, 1)"),
          wo),
        frontierTextbadgeColorBackgroundWarning:
          ((Ao = {}),
          (Ao[Xa] = "rgba(255, 185, 56, 1)"),
          (Ao.default = "rgba(133, 93, 41, 1)"),
          Ao),
        frontierTextbadgeColorBackgroundWarningDeemphasized:
          ((Fo = {}),
          (Fo[Xa] = "rgba(37, 30, 22, 1)"),
          (Fo.default = "rgba(255, 240, 212, 1)"),
          Fo),
        frontierTextColorBrand:
          ((Oo = {}),
          (Oo[Xa] = "rgba(29, 170, 97, 1)"),
          (Oo.default = "rgba(29, 170, 97, 1)"),
          Oo),
        frontierTextColorDisabled:
          ((Bo = {}),
          (Bo[Xa] = "rgba(77, 85, 91, 1)"),
          (Bo.default = "rgba(141, 149, 153, 1)"),
          Bo),
        frontierTextColorInverted:
          ((Wo = {}),
          (Wo[Xa] = "rgba(10, 16, 20, 1)"),
          (Wo.default = "rgba(247, 248, 250, 1)"),
          Wo),
        frontierTextColorLink:
          ((qo = {}),
          (qo[Xa] = "rgba(33, 192, 99, 1)"),
          (qo.default = "rgba(29, 170, 97, 1)"),
          qo),
        frontierTextColorNegative:
          ((Uo = {}),
          (Uo[Xa] = "rgba(234, 0, 56, 1)"),
          (Uo.default = "rgba(121, 22, 50, 1)"),
          Uo),
        frontierTextColorPlaceholder:
          ((Vo = {}),
          (Vo[Xa] = "rgba(141, 149, 153, 1)"),
          (Vo.default = "rgba(91, 99, 104, 1)"),
          Vo),
        frontierTextColorPositive:
          ((Ho = {}),
          (Ho[Xa] = "rgba(37, 211, 102, 1)"),
          (Ho.default = "rgba(24, 116, 74, 1)"),
          Ho),
        frontierTextColorPrimary:
          ((Go = {}),
          (Go[Xa] = "rgba(247, 248, 250, 1)"),
          (Go.default = "rgba(10, 16, 20, 1)"),
          Go),
        frontierTextColorPrimaryOnMedia:
          ((zo = {}),
          (zo[Xa] = "rgba(255, 255, 255, 1)"),
          (zo.default = "rgba(255, 255, 255, 1)"),
          zo),
        frontierTextColorSecondary:
          ((jo = {}),
          (jo[Xa] = "rgba(141, 149, 153, 1)"),
          (jo.default = "rgba(91, 99, 104, 1)"),
          jo),
        frontierTextColorWarning:
          ((Ko = {}),
          (Ko[Xa] = "rgba(255, 185, 56, 1)"),
          (Ko.default = "rgba(133, 93, 41, 1)"),
          Ko),
        frontierTextinputColorEmptyBackground:
          ((Qo = {}),
          (Qo[Xa] = "rgba(10, 16, 20, 1)"),
          (Qo.default = "rgba(255, 255, 255, 1)"),
          Qo),
        frontierTextinputColorEmptyBorder:
          ((Xo = {}),
          (Xo[Xa] = "rgba(108, 117, 122, 1)"),
          (Xo.default = "rgba(141, 149, 153, 1)"),
          Xo),
        frontierTextinputColorEmptyHelper:
          ((Yo = {}),
          (Yo[Xa] = "rgba(141, 149, 153, 1)"),
          (Yo.default = "rgba(91, 99, 104, 1)"),
          Yo),
        frontierTextinputColorEmptyInput:
          ((Jo = {}),
          (Jo[Xa] = "rgba(247, 248, 250, 1)"),
          (Jo.default = "rgba(10, 16, 20, 1)"),
          Jo),
        frontierTextinputColorEmptyLabel:
          ((Zo = {}),
          (Zo[Xa] = "rgba(141, 149, 153, 1)"),
          (Zo.default = "rgba(91, 99, 104, 1)"),
          Zo),
        frontierTextinputColorEmptyValidationBackground:
          ((ea = {}),
          (ea[Xa] = "rgba(10, 16, 20, 1)"),
          (ea.default = "rgba(255, 255, 255, 1)"),
          ea),
        frontierTextinputColorEmptyValidationBorder:
          ((ta = {}),
          (ta[Xa] = "rgba(251, 80, 97, 1)"),
          (ta.default = "rgba(234, 0, 56, 1)"),
          ta),
        frontierTextinputColorEmptyValidationHelper:
          ((na = {}),
          (na[Xa] = "rgba(251, 80, 97, 1)"),
          (na.default = "rgba(234, 0, 56, 1)"),
          na),
        frontierTextinputColorEmptyValidationIconRight:
          ((ra = {}),
          (ra[Xa] = "rgba(251, 80, 97, 1)"),
          (ra.default = "rgba(234, 0, 56, 1)"),
          ra),
        frontierTextinputColorEmptyValidationInput:
          ((oa = {}),
          (oa[Xa] = "rgba(247, 248, 250, 1)"),
          (oa.default = "rgba(10, 16, 20, 1)"),
          oa),
        frontierTextinputColorEmptyValidationLabel:
          ((aa = {}),
          (aa[Xa] = "rgba(251, 80, 97, 1)"),
          (aa.default = "rgba(234, 0, 56, 1)"),
          aa),
        frontierTextinputColorFilledBackground:
          ((ia = {}),
          (ia[Xa] = "rgba(10, 16, 20, 1)"),
          (ia.default = "rgba(255, 255, 255, 1)"),
          ia),
        frontierTextinputColorFilledBorder:
          ((la = {}),
          (la[Xa] = "rgba(108, 117, 122, 1)"),
          (la.default = "rgba(141, 149, 153, 1)"),
          la),
        frontierTextinputColorFilledDisabledBackground:
          ((sa = {}),
          (sa[Xa] = "rgba(10, 16, 20, 1)"),
          (sa.default = "rgba(255, 255, 255, 1)"),
          sa),
        frontierTextinputColorFilledDisabledBorder:
          ((ua = {}),
          (ua[Xa] = "rgba(108, 117, 122, 1)"),
          (ua.default = "rgba(141, 149, 153, 1)"),
          ua),
        frontierTextinputColorFilledDisabledHelper:
          ((ca = {}),
          (ca[Xa] = "rgba(141, 149, 153, 1)"),
          (ca.default = "rgba(91, 99, 104, 1)"),
          ca),
        frontierTextinputColorFilledDisabledInput:
          ((da = {}),
          (da[Xa] = "rgba(141, 149, 153, 1)"),
          (da.default = "rgba(10, 16, 20, 1)"),
          da),
        frontierTextinputColorFilledDisabledLabel:
          ((ma = {}),
          (ma[Xa] = "rgba(141, 149, 153, 1)"),
          (ma.default = "rgba(91, 99, 104, 1)"),
          ma),
        frontierTextinputColorFilledHelper:
          ((pa = {}),
          (pa[Xa] = "rgba(141, 149, 153, 1)"),
          (pa.default = "rgba(91, 99, 104, 1)"),
          pa),
        frontierTextinputColorFilledInput:
          ((_a = {}),
          (_a[Xa] = "rgba(247, 248, 250, 1)"),
          (_a.default = "rgba(10, 16, 20, 1)"),
          _a),
        frontierTextinputColorFilledLabel:
          ((fa = {}),
          (fa[Xa] = "rgba(141, 149, 153, 1)"),
          (fa.default = "rgba(91, 99, 104, 1)"),
          fa),
        frontierTextinputColorFocusedBackground:
          ((ga = {}),
          (ga[Xa] = "rgba(10, 16, 20, 1)"),
          (ga.default = "rgba(255, 255, 255, 1)"),
          ga),
        frontierTextinputColorFocusedBorder:
          ((ha = {}),
          (ha[Xa] = "rgba(247, 248, 250, 1)"),
          (ha.default = "rgba(10, 16, 20, 1)"),
          ha),
        frontierTextinputColorFocusedHelper:
          ((ya = {}),
          (ya[Xa] = "rgba(141, 149, 153, 1)"),
          (ya.default = "rgba(91, 99, 104, 1)"),
          ya),
        frontierTextinputColorFocusedIconRight:
          ((Ca = {}),
          (Ca[Xa] = "rgba(247, 248, 250, 1)"),
          (Ca.default = "rgba(10, 16, 20, 1)"),
          Ca),
        frontierTextinputColorFocusedInput:
          ((ba = {}),
          (ba[Xa] = "rgba(247, 248, 250, 1)"),
          (ba.default = "rgba(10, 16, 20, 1)"),
          ba),
        frontierTextinputColorFocusedLabel:
          ((va = {}),
          (va[Xa] = "rgba(247, 248, 250, 1)"),
          (va.default = "rgba(10, 16, 20, 1)"),
          va),
        frontierTextinputColorSuccessBackground:
          ((Sa = {}),
          (Sa[Xa] = "rgba(10, 16, 20, 1)"),
          (Sa.default = "rgba(255, 255, 255, 1)"),
          Sa),
        frontierTextinputColorSuccessBorder:
          ((Ra = {}),
          (Ra[Xa] = "rgba(108, 117, 122, 1)"),
          (Ra.default = "rgba(141, 149, 153, 1)"),
          Ra),
        frontierTextinputColorSuccessFocusedBackground:
          ((La = {}),
          (La[Xa] = "rgba(10, 16, 20, 1)"),
          (La.default = "rgba(255, 255, 255, 1)"),
          La),
        frontierTextinputColorSuccessFocusedBorder:
          ((Ea = {}),
          (Ea[Xa] = "rgba(247, 248, 250, 1)"),
          (Ea.default = "rgba(10, 16, 20, 1)"),
          Ea),
        frontierTextinputColorSuccessFocusedHelper:
          ((ka = {}),
          (ka[Xa] = "rgba(141, 149, 153, 1)"),
          (ka.default = "rgba(91, 99, 104, 1)"),
          ka),
        frontierTextinputColorSuccessFocusedIconRight:
          ((Ia = {}),
          (Ia[Xa] = "rgba(113, 235, 133, 1)"),
          (Ia.default = "rgba(29, 170, 97, 1)"),
          Ia),
        frontierTextinputColorSuccessFocusedInput:
          ((Ta = {}),
          (Ta[Xa] = "rgba(247, 248, 250, 1)"),
          (Ta.default = "rgba(10, 16, 20, 1)"),
          Ta),
        frontierTextinputColorSuccessFocusedLabel:
          ((Da = {}),
          (Da[Xa] = "rgba(247, 248, 250, 1)"),
          (Da.default = "rgba(10, 16, 20, 1)"),
          Da),
        frontierTextinputColorSuccessHelper:
          ((xa = {}),
          (xa[Xa] = "rgba(141, 149, 153, 1)"),
          (xa.default = "rgba(91, 99, 104, 1)"),
          xa),
        frontierTextinputColorSuccessIconRight:
          (($a = {}),
          ($a[Xa] = "rgba(113, 235, 133, 1)"),
          ($a.default = "rgba(29, 170, 97, 1)"),
          $a),
        frontierTextinputColorSuccessInput:
          ((Pa = {}),
          (Pa[Xa] = "rgba(247, 248, 250, 1)"),
          (Pa.default = "rgba(10, 16, 20, 1)"),
          Pa),
        frontierTextinputColorSuccessLabel:
          ((Na = {}),
          (Na[Xa] = "rgba(141, 149, 153, 1)"),
          (Na.default = "rgba(91, 99, 104, 1)"),
          Na),
        frontierTextinputColorValidationBackground:
          ((Ma = {}),
          (Ma[Xa] = "rgba(10, 16, 20, 1)"),
          (Ma.default = "rgba(255, 255, 255, 1)"),
          Ma),
        frontierTextinputColorValidationBorder:
          ((wa = {}),
          (wa[Xa] = "rgba(251, 80, 97, 1)"),
          (wa.default = "rgba(234, 0, 56, 1)"),
          wa),
        frontierTextinputColorValidationHelper:
          ((Aa = {}),
          (Aa[Xa] = "rgba(251, 80, 97, 1)"),
          (Aa.default = "rgba(234, 0, 56, 1)"),
          Aa),
        frontierTextinputColorValidationIconRight:
          ((Fa = {}),
          (Fa[Xa] = "rgba(251, 80, 97, 1)"),
          (Fa.default = "rgba(234, 0, 56, 1)"),
          Fa),
        frontierTextinputColorValidationInput:
          ((Oa = {}),
          (Oa[Xa] = "rgba(247, 248, 250, 1)"),
          (Oa.default = "rgba(10, 16, 20, 1)"),
          Oa),
        frontierTextinputColorValidationLabel:
          ((Ba = {}),
          (Ba[Xa] = "rgba(251, 80, 97, 1)"),
          (Ba.default = "rgba(234, 0, 56, 1)"),
          Ba),
        frontierTokenizerTokenColorDefaultBackground:
          ((Wa = {}),
          (Wa[Xa] = "rgba(32, 39, 43, 1)"),
          (Wa.default = "rgba(241, 238, 235, 1)"),
          Wa),
        frontierTokenizerTokenColorDefaultBorder:
          ((qa = {}),
          (qa[Xa] = "rgba(255, 255, 255, 0.1)"),
          (qa.default = "rgba(17, 27, 33, 0.2)"),
          qa),
        frontierTokenizerTokenColorDefaultIcon:
          ((Ua = {}),
          (Ua[Xa] = "rgba(247, 248, 250, 1)"),
          (Ua.default = "rgba(10, 16, 20, 1)"),
          Ua),
        frontierTokenizerTokenColorDefaultText:
          ((Va = {}),
          (Va[Xa] = "rgba(247, 248, 250, 1)"),
          (Va.default = "rgba(10, 16, 20, 1)"),
          Va),
        frontierTokenizerTokenColorDisabledBackground:
          ((Ha = {}),
          (Ha[Xa] = "rgba(10, 16, 20, 1)"),
          (Ha.default = "rgba(255, 255, 255, 1)"),
          Ha),
        frontierTokenizerTokenColorDisabledBorder:
          ((Ga = {}),
          (Ga[Xa] = "rgba(255, 255, 255, 0.1)"),
          (Ga.default = "rgba(17, 27, 33, 0.2)"),
          Ga),
        frontierTokenizerTokenColorDisabledIcon:
          ((za = {}),
          (za[Xa] = "rgba(62, 71, 77, 1)"),
          (za.default = "rgba(179, 185, 189, 1)"),
          za),
        frontierTokenizerTokenColorDisabledText:
          ((ja = {}),
          (ja[Xa] = "rgba(62, 71, 77, 1)"),
          (ja.default = "rgba(179, 185, 189, 1)"),
          ja),
        frontierTooltipColorBackground:
          ((Ka = {}),
          (Ka[Xa] = "rgba(255, 255, 255, 1)"),
          (Ka.default = "rgba(10, 16, 20, 1)"),
          Ka),
        frontierTooltipColorText:
          ((Qa = {}),
          (Qa[Xa] = "rgba(10, 16, 20, 1)"),
          (Qa.default = "rgba(247, 248, 250, 1)"),
          Qa),
      },
      ei = {
        frontierChipDefaultAppearanceOpacity: 1,
        frontierChipDisabledAppearanceOpacity: 0.5,
        frontierChipPressedAppearanceOpacity: 0.75,
        frontierChipSelectedAppearanceOpacity: 1,
        frontierSwitchHandleSelectedDisabledOpacity: 1,
        frontierSwitchHandleSelectedOpacity: 1,
        frontierSwitchHandleUnselectedDisabledOpacity: 1,
        frontierSwitchHandleUnselectedOpacity: 1,
        frontierSwitchTrackerSelectedDisabledOpacity: 0.4,
        frontierSwitchTrackerSelectedOpacity: 1,
        frontierSwitchTrackerUnselectedDisabledOpacity: 0.4,
        frontierSwitchTrackerUnselectedOpacity: 1,
      },
      ti = {
        frontierAlertBannerGapTextWrapperInner: "16px",
        frontierAlertBannerGapTextWrapperTop: "8px",
        frontierAlertBannerGapWrapper: "16px",
        frontierAlertBannerMobilePaddingHorizontal: "16px",
        frontierAlertBannerMobilePaddingVertical: "16px",
        frontierAlertBannerWebPaddingHorizontal: "16px",
        frontierAlertBannerWebPaddingVertical: "8px",
        frontierAlertBannerWebPaddingWrapperHorizontal: "16px",
        frontierAlertBannerWebPaddingWrapperVertical: "16px",
        frontierButtonGap: "6px",
        frontierButtonGroupGap: "8px",
        frontierButtonPaddingHorizontal: "16px",
        frontierButtonPaddingHorizontalLarge: "30px",
        frontierButtonPaddingHorizontalMedium: "22px",
        frontierButtonPaddingHorizontalSmall: "18px",
        frontierButtonPaddingVertical: "8px",
        frontierButtonPaddingVerticalLarge: "14px",
        frontierButtonPaddingVerticalMedium: "10px",
        frontierButtonPaddingVerticalSmall: "6px",
        frontierButtonTextLabelLargeLetterSpacing: "0.25px",
        frontierButtonTextLabelMediumLetterSpacing: "0.25px",
        frontierButtonTextLabelSmallLetterSpacing: "0.25px",
        frontierCheckboxFieldTextWrapperPaddingTop: "7px",
        frontierChipInnerWrapperGap: "6px",
        frontierChipPaddingHorizontal: "16px",
        frontierChipPaddingVertical: "8px",
        frontierLayoutColumns: "12px",
        frontierLayoutColumnsSmall: "6px",
        frontierLayoutGapSmall: "12px",
        frontierLayoutGutter: "8px",
        frontierLayoutSpaceBetweenSectionSmallDefault: "28px",
        frontierLayoutSpaceBetweenSectionXsmallHasDivider: "14px",
        frontierLayoutSpaceWithinSectionMediumDefault: "16px",
        frontierLayoutSpaceWithinSectionSmall: "12px",
        frontierLayoutSpaceWithinSectionXsmall: "6px",
        frontierListcellGapCardTextTop: "5px",
        frontierListcellGapIconTextTop: "7px",
        frontierListcellGapInnerWrapper: "16px",
        frontierListcellGapWrapper: "16px",
        frontierListcellPaddingFlush: "0px",
        frontierListcellPaddingHorizontal: "16px",
        frontierListcellPaddingVertical: "12px",
        frontierPillGapHorizontal: "4px",
        frontierPillGroupGap: "6px",
        frontierPillPaddingHorizontal: "8px",
        frontierPillPaddingVertical: "4px",
        frontierProgressBarGap: "0px",
        frontierProgressRingContentGap: "8px",
        frontierSearchfieldGap: "16px",
        frontierSearchfieldPaddingHorizontal: "16px",
        frontierSearchfieldPaddingVertical: "8px",
        frontierSelectinputGapComponent: "8px",
        frontierSelectinputPaddingHorizontal: "16px",
        frontierSelectinputPaddingVertical: "16px",
        frontierStepperGapLarge: "4px",
        frontierStepperGapMedium: "4px",
        frontierStepperGapSmall: "2px",
        frontierSwitchHandleSelectedDisabledPadding: "4px",
        frontierSwitchHandleSelectedPadding: "4px",
        frontierSwitchHandleUnselectedDisabledPadding: "8px",
        frontierSwitchHandleUnselectedPadding: "8px",
        frontierTablePaddingCellHorizontal: "16px",
        frontierTablePaddingCellVertical: "12px",
        frontierTablePaddingHeaderHorizontal: "16px",
        frontierTablePaddingHeaderVertical: "12px",
        frontierTabsItemWrapperPaddingHorizontal: "8px",
        frontierTabsItemWrapperPaddingVertical: "4px",
        frontierTabsLayoutPaddingGap: "0px",
        frontierTabsLayoutPaddingHorizontal: "0px",
        frontierTabsLayoutPaddingVertical: "0px",
        frontierTextbadgeGapHorizontal: "4px",
        frontierTextbadgePaddingHorizontal: "8px",
        frontierTextbadgePaddingVertical: "4px",
        frontierTextBodyLargeEmphasizedLetterSpacing: "0.20000000298023px",
        frontierTextBodyLargeLetterSpacing: "0.20000000298023px",
        frontierTextBodyMediumEmphasizedLetterSpacing: "0.20000000298023px",
        frontierTextBodyMediumLetterSpacing: "0.25px",
        frontierTextBodyMetaLetterSpacing: "0.25px",
        frontierTextBodySmallEmphasizedLetterSpacing: "0.25px",
        frontierTextBodySmallLetterSpacing: "0.25px",
        frontierTextDisplayLetterSpacing: "0px",
        frontierTextEyebrowLetterSpacing: "0.25px",
        frontierTextHeadlineLargeLetterSpacing: "0px",
        frontierTextHeadlineMediumLetterSpacing: "0px",
        frontierTextinputPaddingHorizontal: "16px",
        frontierTextLabelLargeLetterSpacing: "0.20000000298023px",
        frontierTextLabelMediumLetterSpacing: "0.25px",
        frontierTextLabelSmallLetterSpacing: "0.25px",
        frontierTextpairingVerticalGap: "16px",
        frontierTextpairingVerticalGapSmall: "8px",
        frontierTextTitleLargeLetterSpacing: "0px",
        frontierTextTitleMediumLetterSpacing: "0px",
        frontierTokenizerLabelRaisedTranslateY: "-11px",
        frontierTokenizerPaddingBlockStart: "24px",
        frontierTokenizerPaddingVertical: "8px",
        frontierTooltipPaddingHorizontal: "12px",
        frontierTooltipPaddingVertical: "12px",
      },
      ni = {
        frontierButtonTextLabelLargeFontFamily:
          "Roboto, Segoe UI, sans-serif, system-ui !important",
        frontierButtonTextLabelLargeFontSize: "14px",
        frontierButtonTextLabelLargeFontWeight: "500",
        frontierButtonTextLabelLargeLineHeight: "20px",
        frontierButtonTextLabelMediumFontFamily:
          "Roboto, Segoe UI, sans-serif, system-ui !important",
        frontierButtonTextLabelMediumFontSize: "14px",
        frontierButtonTextLabelMediumFontWeight: "500",
        frontierButtonTextLabelMediumLineHeight: "20px",
        frontierButtonTextLabelSmallFontFamily:
          "Roboto, Segoe UI, sans-serif, system-ui !important",
        frontierButtonTextLabelSmallFontSize: "14px",
        frontierButtonTextLabelSmallFontWeight: "500",
        frontierButtonTextLabelSmallLineHeight: "20px",
        frontierLinkLargeFontFamily:
          "Roboto, Segoe UI, sans-serif, system-ui !important",
        frontierLinkLargeFontSize: "16px",
        frontierLinkLargeFontStyle: "normal",
        frontierLinkLargeFontWeight: "700",
        frontierLinkLargeLetterSpacing: "0.20000000298023px",
        frontierLinkLargeStretch: "normal",
        frontierLinkMediumFontFamily:
          "Roboto, Segoe UI, sans-serif, system-ui !important",
        frontierLinkMediumFontSize: "14px",
        frontierLinkMediumFontStyle: "normal",
        frontierLinkMediumFontWeight: "700",
        frontierLinkMediumLetterSpacing: "0.25px",
        frontierLinkMediumStretch: "normal",
        frontierLinkSmallFontFamily:
          "Roboto, Segoe UI, sans-serif, system-ui !important",
        frontierLinkSmallFontSize: "12px",
        frontierLinkSmallFontStyle: "normal",
        frontierLinkSmallFontWeight: "700",
        frontierLinkSmallLetterSpacing: "0.25px",
        frontierLinkSmallStretch: "normal",
        frontierTabsItemTextSelectedWeight: "400",
        frontierTabsItemTextUnselectedWeight: "400",
        frontierTextBodyLargeEmphasizedFontFamily:
          "Roboto, Segoe UI, sans-serif, system-ui !important",
        frontierTextBodyLargeEmphasizedFontSize: "16px",
        frontierTextBodyLargeEmphasizedFontStyle: "normal",
        frontierTextBodyLargeEmphasizedFontWeight: "500",
        frontierTextBodyLargeEmphasizedLineHeight: "24px",
        frontierTextBodyLargeEmphasizedStretch: "normal",
        frontierTextBodyLargeFontFamily:
          "Roboto, Segoe UI, sans-serif, system-ui !important",
        frontierTextBodyLargeFontSize: "16px",
        frontierTextBodyLargeFontStyle: "normal",
        frontierTextBodyLargeFontWeight: "400",
        frontierTextBodyLargeLineHeight: "24px",
        frontierTextBodyLargeStretch: "normal",
        frontierTextBodyMediumEmphasizedFontFamily:
          "Roboto, Segoe UI, sans-serif, system-ui !important",
        frontierTextBodyMediumEmphasizedFontSize: "14px",
        frontierTextBodyMediumEmphasizedFontStyle: "normal",
        frontierTextBodyMediumEmphasizedFontWeight: "500",
        frontierTextBodyMediumEmphasizedLineHeight: "20px",
        frontierTextBodyMediumEmphasizedStretch: "normal",
        frontierTextBodyMediumFontFamily:
          "Roboto, Segoe UI, sans-serif, system-ui !important",
        frontierTextBodyMediumFontSize: "14px",
        frontierTextBodyMediumFontStyle: "normal",
        frontierTextBodyMediumFontWeight: "400",
        frontierTextBodyMediumLineHeight: "20px",
        frontierTextBodyMediumStretch: "normal",
        frontierTextBodyMetaFontFamily:
          "Roboto, Segoe UI, sans-serif, system-ui !important",
        frontierTextBodyMetaFontSize: "14px",
        frontierTextBodyMetaFontStyle: "normal",
        frontierTextBodyMetaFontWeight: "400",
        frontierTextBodyMetaLineHeight: "20px",
        frontierTextBodyMetaStretch: "normal",
        frontierTextBodySmallEmphasizedFontFamily:
          "Roboto, Segoe UI, sans-serif, system-ui !important",
        frontierTextBodySmallEmphasizedFontSize: "12px",
        frontierTextBodySmallEmphasizedFontStyle: "normal",
        frontierTextBodySmallEmphasizedFontWeight: "500",
        frontierTextBodySmallEmphasizedLineHeight: "16px",
        frontierTextBodySmallEmphasizedStretch: "normal",
        frontierTextBodySmallFontFamily:
          "Roboto, Segoe UI, sans-serif, system-ui !important",
        frontierTextBodySmallFontSize: "12px",
        frontierTextBodySmallFontStyle: "normal",
        frontierTextBodySmallFontWeight: "400",
        frontierTextBodySmallLineHeight: "16px",
        frontierTextBodySmallStretch: "normal",
        frontierTextDisplayFontFamily:
          "Roboto, Segoe UI, sans-serif, system-ui !important",
        frontierTextDisplayFontSize: "48px",
        frontierTextDisplayFontStyle: "normal",
        frontierTextDisplayFontWeight: "600",
        frontierTextDisplayLineHeight: "52px",
        frontierTextDisplayStretch: "normal",
        frontierTextEyebrowFontFamily:
          "Roboto, Segoe UI, sans-serif, system-ui !important",
        frontierTextEyebrowFontSize: "12px",
        frontierTextEyebrowFontStyle: "normal",
        frontierTextEyebrowFontWeight: "700",
        frontierTextEyebrowLineHeight: "16px",
        frontierTextEyebrowStretch: "normal",
        frontierTextHeadlineLargeFontFamily:
          "Roboto, Segoe UI, sans-serif, system-ui !important",
        frontierTextHeadlineLargeFontSize: "24px",
        frontierTextHeadlineLargeFontStyle: "normal",
        frontierTextHeadlineLargeFontWeight: "400",
        frontierTextHeadlineLargeLineHeight: "32px",
        frontierTextHeadlineLargeStretch: "normal",
        frontierTextHeadlineMediumFontFamily:
          "Roboto, Segoe UI, sans-serif, system-ui !important",
        frontierTextHeadlineMediumFontSize: "22px",
        frontierTextHeadlineMediumFontStyle: "normal",
        frontierTextHeadlineMediumFontWeight: "400",
        frontierTextHeadlineMediumLineHeight: "28px",
        frontierTextHeadlineMediumStretch: "normal",
        frontierTextinputMinHeight: "60px",
        frontierTextLabelLargeFontFamily:
          "Roboto, Segoe UI, sans-serif, system-ui !important",
        frontierTextLabelLargeFontSize: "16px",
        frontierTextLabelLargeFontStyle: "normal",
        frontierTextLabelLargeFontWeight: "500",
        frontierTextLabelLargeLineHeight: "24px",
        frontierTextLabelLargeStretch: "normal",
        frontierTextLabelMediumFontFamily:
          "Roboto, Segoe UI, sans-serif, system-ui !important",
        frontierTextLabelMediumFontSize: "14px",
        frontierTextLabelMediumFontStyle: "normal",
        frontierTextLabelMediumFontWeight: "500",
        frontierTextLabelMediumLineHeight: "20px",
        frontierTextLabelMediumStretch: "normal",
        frontierTextLabelSmallFontFamily:
          "Roboto, Segoe UI, sans-serif, system-ui !important",
        frontierTextLabelSmallFontSize: "12px",
        frontierTextLabelSmallFontStyle: "normal",
        frontierTextLabelSmallFontWeight: "500",
        frontierTextLabelSmallLineHeight: "16px",
        frontierTextLabelSmallStretch: "normal",
        frontierTextTitleLargeFontFamily:
          "Roboto, Segoe UI, sans-serif, system-ui !important",
        frontierTextTitleLargeFontSize: "32px",
        frontierTextTitleLargeFontStyle: "normal",
        frontierTextTitleLargeFontWeight: "400",
        frontierTextTitleLargeLineHeight: "40px",
        frontierTextTitleLargeStretch: "normal",
        frontierTextTitleMediumFontFamily:
          "Roboto, Segoe UI, sans-serif, system-ui !important",
        frontierTextTitleMediumFontSize: "28px",
        frontierTextTitleMediumFontStyle: "normal",
        frontierTextTitleMediumFontWeight: "400",
        frontierTextTitleMediumLineHeight: "36px",
        frontierTextTitleMediumStretch: "normal",
      },
      ri = babelHelpers.extends({}, Ya, Za, Ja, ti, ei, ni),
      oi = babelHelpers.extends(
        {},
        Ya,
        Object.fromEntries(
          Object.keys(Za).map(function (e) {
            var t;
            return [e, (t = Za[e].default) != null ? t : Za[e]];
          }),
        ),
        Ja,
        ti,
        ei,
        ni,
      ),
      ai = babelHelpers.extends(
        {},
        Ya,
        Object.fromEntries(
          Object.keys(Za).map(function (e) {
            var t;
            return [e, (t = Za[e][Xa]) != null ? t : Za[e]];
          }),
        ),
        Ja,
        ti,
        ei,
        ni,
      ),
      ii = { x1w2u7rz: "xstxtw6 x1w2u7rz", $$css: !0 },
      li = { x1w2u7rz: "x7pt7jw x1w2u7rz", $$css: !0 },
      si = { x1w2u7rz: "x15k82jh x1w2u7rz", $$css: !0 },
      ui = Object.fromEntries(
        Object.keys(Za).map(function (e) {
          var t;
          return [e, (t = Za[e][Xa]) != null ? t : Za[e]];
        }),
      ),
      ci = Object.fromEntries(
        Object.keys(Za).map(function (e) {
          var t;
          return [e, (t = Za[e].default) != null ? t : Za[e]];
        }),
      ),
      di = {
        auto: babelHelpers.extends({}, Za, ei, Ya, ti),
        dark: babelHelpers.extends({}, ui, ei, Ya, ti),
        light: babelHelpers.extends({}, ci, ei, Ya, ti),
      };
    ((l.FrontierWDSAutoTheme = ii),
      (l.FrontierWDSLightTheme = li),
      (l.FrontierWDSDarkTheme = si),
      (l.FrontierWDSThemeNativeVarContextValues = di));
  },
  98,
);
