__d(
  "GeoDataVizThemeTypes",
  ["$InternalEnum"],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = n("$InternalEnum")({
        Blue: "blue",
        Brown: "brown",
        DarkGray: "dark_gray",
        DarkOrange: "dark_orange",
        DarkPurple: "dark_purple",
        DarkTeal: "dark_teal",
        Gray: "gray",
        Green: "green",
        LightBlue: "light_blue",
        Magenta: "magenta",
        OffWhite: "off_white",
        Orange: "orange",
        Purple: "purple",
        Teal: "teal",
      }),
      l = n("$InternalEnum")({
        Neutral: "neutral",
        Leading1: "leading1",
        Leading2: "leading2",
        Leading3: "leading3",
        Leading4: "leading4",
        Complementary1: "complementary1",
        Complementary2: "complementary2",
        Semantic: "semantic",
      }),
      s = n("$InternalEnum")({
        TofuSplitLine: "tofuSplitLine",
        AdsInsights: "adsInsights",
        AdsInsightsAudienceGeo: "adsInsightsAudienceGeo",
        CTMMessagingReportTrendComparison: "ctmMessagingReportTrendComparison",
        MetaCRM: "metaCRM",
        AdsReportBuilderNegative: "adsReportBuilderNegative",
        AdsReportBuilderPositive: "adsReportBuilderPositive",
        AdsReportBuilderNeutral: "adsReportBuilderNeutral",
        DisabledRing: "disabledRing",
        AdsExperimentsLow: "adsExperimentsLow",
        AdsExperimentsMedium: "adsExperimentsMedium",
        AdsExperimentsHigh: "adsExperimentsHigh",
        CreatorMarketplaceIG: "creatorMarketplaceIG",
        CreatorMarketplaceFB: "creatorMarketplaceFB",
        CreatorMarketplaceCrossPlatform: "creatorMarketplaceCrossPlatform",
      });
    ((i.CategoricalColor = e),
      (i.GeoPaletteType = l),
      (i.CustomPaletteType = s));
  },
  66,
);
