__d(
  "geoMargin",
  [],
  function (t, n, r, o, a, i, l) {
    "use strict";
    var e = {
        top0: { marginTop: "xdj266r", $$css: !0 },
        top4: { marginTop: "x1gslohp", $$css: !0 },
        top8: { marginTop: "x1xmf6yo", $$css: !0 },
        top12: { marginTop: "x14vqqas", $$css: !0 },
        top16: { marginTop: "xw7yly9", $$css: !0 },
        top20: { marginTop: "x1sy10c2", $$css: !0 },
        top24: { marginTop: "xqui205", $$css: !0 },
        end0: { marginInlineEnd: "x14z9mp", $$css: !0 },
        end4: { marginInlineEnd: "x2fvf9", $$css: !0 },
        end8: { marginInlineEnd: "x1xegmmw", $$css: !0 },
        end12: { marginInlineEnd: "xbmvrgn", $$css: !0 },
        end16: { marginInlineEnd: "x1ys307a", $$css: !0 },
        end20: { marginInlineEnd: "x3aesyq", $$css: !0 },
        end24: { marginInlineEnd: "xpwdb9g", $$css: !0 },
        bottom0: { marginBottom: "xat24cr", $$css: !0 },
        bottom4: { marginBottom: "x12nagc", $$css: !0 },
        bottom8: { marginBottom: "x1e56ztr", $$css: !0 },
        bottom12: { marginBottom: "xod5an3", $$css: !0 },
        bottom16: { marginBottom: "x1yztbdb", $$css: !0 },
        bottom20: { marginBottom: "xieb3on", $$css: !0 },
        bottom24: { marginBottom: "x1hq5gj4", $$css: !0 },
        start0: { marginInlineStart: "x1lziwak", $$css: !0 },
        start4: { marginInlineStart: "xdwrcjd", $$css: !0 },
        start8: { marginInlineStart: "x13fj5qh", $$css: !0 },
        start12: { marginInlineStart: "x1diwwjn", $$css: !0 },
        start16: { marginInlineStart: "xyqm7xq", $$css: !0 },
        start20: { marginInlineStart: "xqsn43r", $$css: !0 },
        start24: { marginInlineStart: "xefazk8", $$css: !0 },
        vert0: { marginTop: "xdj266r", marginBottom: "xat24cr", $$css: !0 },
        vert4: { marginTop: "x1gslohp", marginBottom: "x12nagc", $$css: !0 },
        vert8: { marginTop: "x1xmf6yo", marginBottom: "x1e56ztr", $$css: !0 },
        vert12: { marginTop: "x14vqqas", marginBottom: "xod5an3", $$css: !0 },
        vert16: { marginTop: "xw7yly9", marginBottom: "x1yztbdb", $$css: !0 },
        vert20: { marginTop: "x1sy10c2", marginBottom: "xieb3on", $$css: !0 },
        vert24: { marginTop: "xqui205", marginBottom: "x1hq5gj4", $$css: !0 },
        horiz0: {
          marginInlineStart: "x1lziwak",
          marginInlineEnd: "x14z9mp",
          marginLeft: null,
          marginRight: null,
          $$css: !0,
        },
        horiz4: {
          marginInlineStart: "xdwrcjd",
          marginInlineEnd: "x2fvf9",
          marginLeft: null,
          marginRight: null,
          $$css: !0,
        },
        horiz8: {
          marginInlineStart: "x13fj5qh",
          marginInlineEnd: "x1xegmmw",
          marginLeft: null,
          marginRight: null,
          $$css: !0,
        },
        horiz12: {
          marginInlineStart: "x1diwwjn",
          marginInlineEnd: "xbmvrgn",
          marginLeft: null,
          marginRight: null,
          $$css: !0,
        },
        horiz16: {
          marginInlineStart: "xyqm7xq",
          marginInlineEnd: "x1ys307a",
          marginLeft: null,
          marginRight: null,
          $$css: !0,
        },
        horiz20: {
          marginInlineStart: "xqsn43r",
          marginInlineEnd: "x3aesyq",
          marginLeft: null,
          marginRight: null,
          $$css: !0,
        },
        horiz24: {
          marginInlineStart: "xefazk8",
          marginInlineEnd: "xpwdb9g",
          marginLeft: null,
          marginRight: null,
          $$css: !0,
        },
        all0: {
          marginTop: "xdj266r",
          marginInlineEnd: "x14z9mp",
          marginBottom: "xat24cr",
          marginInlineStart: "x1lziwak",
          $$css: !0,
        },
        all4: {
          marginTop: "x1gslohp",
          marginInlineEnd: "x2fvf9",
          marginBottom: "x12nagc",
          marginInlineStart: "xdwrcjd",
          $$css: !0,
        },
        all8: {
          marginTop: "x1xmf6yo",
          marginInlineEnd: "x1xegmmw",
          marginBottom: "x1e56ztr",
          marginInlineStart: "x13fj5qh",
          $$css: !0,
        },
        all12: {
          marginTop: "x14vqqas",
          marginInlineEnd: "xbmvrgn",
          marginBottom: "xod5an3",
          marginInlineStart: "x1diwwjn",
          $$css: !0,
        },
        all16: {
          marginTop: "xw7yly9",
          marginInlineEnd: "x1ys307a",
          marginBottom: "x1yztbdb",
          marginInlineStart: "xyqm7xq",
          $$css: !0,
        },
        all20: {
          marginTop: "x1sy10c2",
          marginInlineEnd: "x3aesyq",
          marginBottom: "xieb3on",
          marginInlineStart: "xqsn43r",
          $$css: !0,
        },
        all24: {
          marginTop: "xqui205",
          marginInlineEnd: "xpwdb9g",
          marginBottom: "x1hq5gj4",
          marginInlineStart: "xefazk8",
          $$css: !0,
        },
      },
      s = e;
    l.default = s;
  },
  98,
);
