__d(
  "GeoPrivateDefaultAppearanceGeneratedStyles",
  [],
  function (t, n, r, o, a, i, l) {
    var e = {
        button: {
          borderTopWidth: "x972fbf",
          borderInlineEndWidth: "x10w94by",
          borderBottomWidth: "x1qhh985",
          borderInlineStartWidth: "x14e42zd",
          $$css: !0,
        },
        buttonInverted: {
          borderTopWidth: "x178xt8z",
          borderInlineEndWidth: "x1lun4ml",
          borderBottomWidth: "xso031l",
          borderInlineStartWidth: "xpilrb4",
          $$css: !0,
        },
        control: {
          borderTopWidth: "x972fbf",
          borderInlineEndWidth: "x10w94by",
          borderBottomWidth: "x1qhh985",
          borderInlineStartWidth: "x14e42zd",
          $$css: !0,
        },
        divider: {
          borderTopWidth: "x178xt8z",
          borderInlineEndWidth: "x1lun4ml",
          borderBottomWidth: "xso031l",
          borderInlineStartWidth: "xpilrb4",
          $$css: !0,
        },
        frame: {
          borderTopWidth: "xamhcws",
          borderInlineEndWidth: "x1alpsbp",
          borderBottomWidth: "xlxy82",
          borderInlineStartWidth: "xyumdvf",
          $$css: !0,
        },
        input: {
          borderTopWidth: "x178xt8z",
          borderInlineEndWidth: "x1lun4ml",
          borderBottomWidth: "xso031l",
          borderInlineStartWidth: "xpilrb4",
          $$css: !0,
        },
        media: {
          borderTopWidth: "x178xt8z",
          borderInlineEndWidth: "x1lun4ml",
          borderBottomWidth: "xso031l",
          borderInlineStartWidth: "xpilrb4",
          $$css: !0,
        },
      },
      s = {
        button: { outlineWidth: "x1k57tk5", $$css: !0 },
        buttonInverted: { outlineWidth: "x1qgsegg", $$css: !0 },
        control: { outlineWidth: "x1k57tk5", $$css: !0 },
        divider: { outlineWidth: "x1qgsegg", $$css: !0 },
        frame: { outlineWidth: "x1de99jn", $$css: !0 },
        input: { outlineWidth: "x1qgsegg", $$css: !0 },
        media: { outlineWidth: "x1qgsegg", $$css: !0 },
      },
      u = {
        addon: {
          borderStartStartRadius: "xjwep3j",
          borderStartEndRadius: "x1t39747",
          borderEndEndRadius: "x1wcsgtt",
          borderEndStartRadius: "x1pczhz8",
          $$css: !0,
        },
        content: {
          borderStartStartRadius: "x1i5p2am",
          borderStartEndRadius: "x1whfx0g",
          borderEndEndRadius: "xr2y4jy",
          borderEndStartRadius: "x1ihp6rs",
          $$css: !0,
        },
        container: {
          borderStartStartRadius: "x1obq294",
          borderStartEndRadius: "x5a5i1n",
          borderEndEndRadius: "xde0f50",
          borderEndStartRadius: "x15x8krk",
          $$css: !0,
        },
        control: {
          borderStartStartRadius: "x1i5p2am",
          borderStartEndRadius: "x1whfx0g",
          borderEndEndRadius: "xr2y4jy",
          borderEndStartRadius: "x1ihp6rs",
          $$css: !0,
        },
        layer: {
          borderStartStartRadius: "x1obq294",
          borderStartEndRadius: "x5a5i1n",
          borderEndEndRadius: "xde0f50",
          borderEndStartRadius: "x15x8krk",
          $$css: !0,
        },
        rounded: {
          borderStartStartRadius: "x1iwo8zk",
          borderStartEndRadius: "x1033uif",
          borderEndEndRadius: "x179ill4",
          borderEndStartRadius: "x1b60jn0",
          $$css: !0,
        },
      },
      c = {
        landscape16: { height: "xlup9mm", width: "xvy4d1p", $$css: !0 },
        landscape21: { height: "x158ke7r", width: "xq14iec", $$css: !0 },
        landscape24: { height: "xxk0z11", width: "x14qfxbe", $$css: !0 },
        landscape30: { height: "x1gnnpzl", width: "xzuapc8", $$css: !0 },
        landscape32: { height: "x10w6t97", width: "x1useyqa", $$css: !0 },
        landscape40: { height: "x1vqgdyp", width: "x1247r65", $$css: !0 },
        landscape41: { height: "x1njhlm6", width: "x1swbwvd", $$css: !0 },
        landscape48: { height: "xsdox4t", width: "xni59qk", $$css: !0 },
        landscape62: { height: "x1x0gksc", width: "x1vtj31x", $$css: !0 },
        landscape64: { height: "x1peatla", width: "x13oubkp", $$css: !0 },
        landscape80: { height: "xwzfr38", width: "xygnafs", $$css: !0 },
        landscape94: { height: "xyk13k4", width: "xzzq9k6", $$css: !0 },
        landscape96: { height: "xjp8j0k", width: "x1fznrkb", $$css: !0 },
        landscape118: { height: "x1xeopk8", width: "xgdcoeo", $$css: !0 },
        landscape144: { height: "x16d3s56", width: "x2qqsnf", $$css: !0 },
        landscape180: { height: "x1b51vyi", width: "xthkip5", $$css: !0 },
        landscape196: { height: "xzp6m1v", width: "x1i0n78g", $$css: !0 },
        landscape300: { height: "x1vd4hg5", width: "xbstwhj", $$css: !0 },
        portrait16: { height: "x1qx5ct2", width: "x1kky2od", $$css: !0 },
        portrait21: { height: "xd7y6wv", width: "x1kl0l3y", $$css: !0 },
        portrait24: { height: "x1gnnpzl", width: "xvy4d1p", $$css: !0 },
        portrait30: { height: "xrtz9ly", width: "x1849jeq", $$css: !0 },
        portrait32: { height: "x1vqgdyp", width: "x1td3qas", $$css: !0 },
        portrait40: { height: "x10wjd1d", width: "x100vrsf", $$css: !0 },
        portrait41: { height: "xaymia4", width: "x1r9kitl", $$css: !0 },
        portrait48: { height: "xng8ra", width: "x1useyqa", $$css: !0 },
        portrait62: { height: "x1kysglf", width: "xeepkih", $$css: !0 },
        portrait64: { height: "xwzfr38", width: "x1fu8urw", $$css: !0 },
        portrait80: { height: "xpyat2d", width: "x1dmp6jm", $$css: !0 },
        portrait94: { height: "x1najy0q", width: "x24u15m", $$css: !0 },
        portrait96: { height: "x1wkxgih", width: "x13oubkp", $$css: !0 },
        portrait118: { height: "x1xxjqy4", width: "x1sla5pk", $$css: !0 },
        portrait144: { height: "x1b51vyi", width: "x1fznrkb", $$css: !0 },
        portrait180: { height: "xtbh88u", width: "xzjbwwf", $$css: !0 },
        portrait196: { height: "x1n6b576", width: "x2i0jwv", $$css: !0 },
        portrait300: { height: "xijmrfd", width: "xdzyupr", $$css: !0 },
        portraitTall16: { height: "x1fgtraw", width: "x1kky2od", $$css: !0 },
        portraitTall21: { height: "xrtz9ly", width: "x1kl0l3y", $$css: !0 },
        portraitTall24: { height: "x5kalc8", width: "xvy4d1p", $$css: !0 },
        portraitTall30: { height: "x9dczf4", width: "x1849jeq", $$css: !0 },
        portraitTall32: { height: "xnnlda6", width: "x1td3qas", $$css: !0 },
        portraitTall40: { height: "x2x2exm", width: "x100vrsf", $$css: !0 },
        portraitTall41: { height: "xy75621", width: "x1r9kitl", $$css: !0 },
        portraitTall48: { height: "xcbkimw", width: "x1useyqa", $$css: !0 },
        portraitTall62: { height: "x41k7rp", width: "xeepkih", $$css: !0 },
        portraitTall64: { height: "x1ffmiix", width: "x1fu8urw", $$css: !0 },
        portraitTall80: { height: "x89wwaf", width: "x1dmp6jm", $$css: !0 },
        portraitTall94: { height: "x1yzmhis", width: "x24u15m", $$css: !0 },
        portraitTall96: { height: "x1a842fp", width: "x13oubkp", $$css: !0 },
        portraitTall118: { height: "x1mlwj4c", width: "x1sla5pk", $$css: !0 },
        portraitTall144: { height: "xrlp1an", width: "x1fznrkb", $$css: !0 },
        portraitTall180: { height: "xu3xrit", width: "xzjbwwf", $$css: !0 },
        portraitTall196: { height: "x1ad3yod", width: "x2i0jwv", $$css: !0 },
        portraitTall300: { height: "x1xy2ir9", width: "xdzyupr", $$css: !0 },
        square16: { height: "xlup9mm", width: "x1kky2od", $$css: !0 },
        square21: { height: "x158ke7r", width: "x1kl0l3y", $$css: !0 },
        square24: { height: "xxk0z11", width: "xvy4d1p", $$css: !0 },
        square30: { height: "x1gnnpzl", width: "x1849jeq", $$css: !0 },
        square32: { height: "x10w6t97", width: "x1td3qas", $$css: !0 },
        square40: { height: "x1vqgdyp", width: "x100vrsf", $$css: !0 },
        square41: { height: "x1njhlm6", width: "x1r9kitl", $$css: !0 },
        square48: { height: "xsdox4t", width: "x1useyqa", $$css: !0 },
        square62: { height: "x1x0gksc", width: "xeepkih", $$css: !0 },
        square64: { height: "x1peatla", width: "x1fu8urw", $$css: !0 },
        square80: { height: "xwzfr38", width: "x1dmp6jm", $$css: !0 },
        square94: { height: "xyk13k4", width: "x24u15m", $$css: !0 },
        square96: { height: "xjp8j0k", width: "x13oubkp", $$css: !0 },
        square118: { height: "x1xeopk8", width: "x1sla5pk", $$css: !0 },
        square144: { height: "x16d3s56", width: "x1fznrkb", $$css: !0 },
        square180: { height: "x1b51vyi", width: "xzjbwwf", $$css: !0 },
        square196: { height: "xzp6m1v", width: "x2i0jwv", $$css: !0 },
        square300: { height: "x1vd4hg5", width: "xdzyupr", $$css: !0 },
      };
    ((l.borderWidthStyles = e),
      (l.interactiveBorderWidthStyles = s),
      (l.borderRadiusStyles = u),
      (l.sizeStyles = c));
  },
  98,
);
