__d(
  "GeoPrivateNextOptimisticVfTextGeneratedStyles",
  [],
  function (t, n, r, o, a, i, l) {
    var e = {
        accent: {
          fontFamily: "x1vvvo52",
          fontSize: "xw23nyj",
          fontWeight: "xo1l8bm",
          lineHeight: "x63nzvj",
          $$css: !0,
        },
        appName: {
          fontFamily: "x1vvvo52",
          fontSize: "xkbp9ht",
          fontWeight: "x1xlr1w8",
          lineHeight: "xm2d7dc",
          $$css: !0,
        },
        data: {
          fontFamily: "x1vvvo52",
          fontSize: "x10d9sdx",
          fontWeight: "x1iikomf",
          lineHeight: "xrohxju",
          $$css: !0,
        },
        header1: {
          fontFamily: "x1vvvo52",
          fontSize: "x1ldc4aq",
          fontWeight: "x1xlr1w8",
          lineHeight: "x1cgboj8",
          $$css: !0,
        },
        header2: {
          fontFamily: "x1vvvo52",
          fontSize: "xm46was",
          fontWeight: "x1xlr1w8",
          lineHeight: "x1jrz1v4",
          $$css: !0,
        },
        header3: {
          fontFamily: "x1vvvo52",
          fontSize: "x1uxerd5",
          fontWeight: "x1xlr1w8",
          lineHeight: "xrohxju",
          $$css: !0,
        },
        header4: {
          fontFamily: "x1vvvo52",
          fontSize: "xsuwoey",
          fontWeight: "x1xlr1w8",
          lineHeight: "x63nzvj",
          $$css: !0,
        },
        interactive: {
          fontFamily: "x1vvvo52",
          fontSize: "x1fvot60",
          fontWeight: "xk50ysn",
          lineHeight: "xxio538",
          $$css: !0,
        },
        value: {
          fontFamily: "x1vvvo52",
          fontSize: "x1fvot60",
          fontWeight: "xo1l8bm",
          lineHeight: "xxio538",
          $$css: !0,
        },
        valueDescription: {
          fontFamily: "x1vvvo52",
          fontSize: "xw23nyj",
          fontWeight: "xo1l8bm",
          lineHeight: "x63nzvj",
          $$css: !0,
        },
        valueDescriptionEmphasized: {
          fontFamily: "x1vvvo52",
          fontSize: "xw23nyj",
          fontWeight: "x1xlr1w8",
          lineHeight: "x63nzvj",
          $$css: !0,
        },
      },
      s = {
        accent: {
          height: "xavktm2",
          paddingTop: "xulzmv6",
          paddingBottom: "x1sh9yuh",
          $$css: !0,
        },
        appName: {
          height: "xqjnyr0",
          paddingTop: "x14ciawu",
          paddingBottom: "ximzlnw",
          $$css: !0,
        },
        data: {
          height: "x1r35sqa",
          paddingTop: "xee31le",
          paddingBottom: "xzljxcv",
          $$css: !0,
        },
        header1: {
          height: "xecje49",
          paddingTop: "x1d4kcbu",
          paddingBottom: "x577seg",
          $$css: !0,
        },
        header2: {
          height: "x1a16cs9",
          paddingTop: "xsbsc5n",
          paddingBottom: "x6u2o8i",
          $$css: !0,
        },
        header3: {
          height: "x1oxkl7l",
          paddingTop: "x1vbyjet",
          paddingBottom: "x17zeodk",
          $$css: !0,
        },
        header4: {
          height: "x1oxkl7l",
          paddingTop: "x1vbyjet",
          paddingBottom: "x17zeodk",
          $$css: !0,
        },
        interactive: {
          height: "x1oxkl7l",
          paddingTop: "x1vbyjet",
          paddingBottom: "x17zeodk",
          $$css: !0,
        },
        value: {
          height: "x1oxkl7l",
          paddingTop: "x1vbyjet",
          paddingBottom: "x17zeodk",
          $$css: !0,
        },
        valueDescription: {
          height: "xavktm2",
          paddingTop: "xulzmv6",
          paddingBottom: "x1sh9yuh",
          $$css: !0,
        },
        valueDescriptionEmphasized: {
          height: "xavktm2",
          paddingTop: "xulzmv6",
          paddingBottom: "x1sh9yuh",
          $$css: !0,
        },
      };
    ((l.fontStyles = e), (l.fontGlimmerStyles = s));
  },
  98,
);
