__d(
  "GeoPrivateDefaultSpacingGeneratedStyles",
  [],
  function (t, n, r, o, a, i, l) {
    var e = {
        bottom: { paddingBottom: "xwxc41k", $$css: !0 },
        top: { paddingTop: "x1p5oq8j", $$css: !0 },
        end: {
          paddingInlineEnd: "x64bnmy",
          paddingLeft: null,
          paddingRight: null,
          $$css: !0,
        },
        start: {
          paddingInlineStart: "x13jy36j",
          paddingLeft: null,
          paddingRight: null,
          $$css: !0,
        },
        horizontal: {
          paddingInlineStart: "x13jy36j",
          paddingInlineEnd: "x64bnmy",
          paddingLeft: null,
          paddingRight: null,
          $$css: !0,
        },
        vertical: {
          paddingTop: "x1p5oq8j",
          paddingBottom: "xwxc41k",
          $$css: !0,
        },
      },
      s = {
        bottom: { paddingBottom: "x1l90r2v", $$css: !0 },
        top: { paddingTop: "xyamay9", $$css: !0 },
        end: {
          paddingInlineEnd: "xv54qhq",
          paddingLeft: null,
          paddingRight: null,
          $$css: !0,
        },
        start: {
          paddingInlineStart: "xf7dkkf",
          paddingLeft: null,
          paddingRight: null,
          $$css: !0,
        },
        horizontal: {
          paddingInlineStart: "xf7dkkf",
          paddingInlineEnd: "xv54qhq",
          paddingLeft: null,
          paddingRight: null,
          $$css: !0,
        },
        vertical: {
          paddingTop: "xyamay9",
          paddingBottom: "x1l90r2v",
          $$css: !0,
        },
      },
      u = {
        bottom: { paddingBottom: "xjkvuk6", $$css: !0 },
        top: { paddingTop: "x1iorvi4", $$css: !0 },
        end: {
          paddingInlineEnd: "x11lfxj5",
          paddingLeft: null,
          paddingRight: null,
          $$css: !0,
        },
        start: {
          paddingInlineStart: "x135b78x",
          paddingLeft: null,
          paddingRight: null,
          $$css: !0,
        },
        horizontal: {
          paddingInlineStart: "x135b78x",
          paddingInlineEnd: "x11lfxj5",
          paddingLeft: null,
          paddingRight: null,
          $$css: !0,
        },
        vertical: {
          paddingTop: "x1iorvi4",
          paddingBottom: "xjkvuk6",
          $$css: !0,
        },
      },
      c = {
        bottom: { marginBottom: "x4vbgl9", $$css: !0 },
        top: { marginTop: "x1rdy4ex", $$css: !0 },
        end: {
          marginInlineEnd: "x1lxpwgx",
          marginLeft: null,
          marginRight: null,
          $$css: !0,
        },
        start: {
          marginInlineStart: "x165d6jo",
          marginLeft: null,
          marginRight: null,
          $$css: !0,
        },
        horizontal: {
          marginInlineStart: "x165d6jo",
          marginInlineEnd: "x1lxpwgx",
          marginLeft: null,
          marginRight: null,
          $$css: !0,
        },
        vertical: { marginTop: "x1rdy4ex", marginBottom: "x4vbgl9", $$css: !0 },
      },
      d = {
        bottom: { paddingBottom: "xwib8y2", $$css: !0 },
        top: { paddingTop: "x1y1aw1k", $$css: !0 },
        end: {
          paddingInlineEnd: "xf159sx",
          paddingLeft: null,
          paddingRight: null,
          $$css: !0,
        },
        start: {
          paddingInlineStart: "xmzvs34",
          paddingLeft: null,
          paddingRight: null,
          $$css: !0,
        },
        horizontal: {
          paddingInlineStart: "xmzvs34",
          paddingInlineEnd: "xf159sx",
          paddingLeft: null,
          paddingRight: null,
          $$css: !0,
        },
        vertical: {
          paddingTop: "x1y1aw1k",
          paddingBottom: "xwib8y2",
          $$css: !0,
        },
      },
      m = {
        bottom: { marginBottom: "x1wsgfga", $$css: !0 },
        top: { marginTop: "x9otpla", $$css: !0 },
        end: {
          marginInlineEnd: "x1w5wx5t",
          marginLeft: null,
          marginRight: null,
          $$css: !0,
        },
        start: {
          marginInlineStart: "x1qfufaz",
          marginLeft: null,
          marginRight: null,
          $$css: !0,
        },
        horizontal: {
          marginInlineStart: "x1qfufaz",
          marginInlineEnd: "x1w5wx5t",
          marginLeft: null,
          marginRight: null,
          $$css: !0,
        },
        vertical: { marginTop: "x9otpla", marginBottom: "x1wsgfga", $$css: !0 },
      },
      p = {
        bottom: { paddingBottom: "xsag5q8", $$css: !0 },
        top: { paddingTop: "xz9dl7a", $$css: !0 },
        end: {
          paddingInlineEnd: "xpdmqnj",
          paddingLeft: null,
          paddingRight: null,
          $$css: !0,
        },
        start: {
          paddingInlineStart: "x1g0dm76",
          paddingLeft: null,
          paddingRight: null,
          $$css: !0,
        },
        horizontal: {
          paddingInlineStart: "x1g0dm76",
          paddingInlineEnd: "xpdmqnj",
          paddingLeft: null,
          paddingRight: null,
          $$css: !0,
        },
        vertical: {
          paddingTop: "xz9dl7a",
          paddingBottom: "xsag5q8",
          $$css: !0,
        },
      },
      _ = {
        bottom: { marginBottom: "xh3wvx0", $$css: !0 },
        top: { marginTop: "x7wgvq7", $$css: !0 },
        end: {
          marginInlineEnd: "xbcz3fp",
          marginLeft: null,
          marginRight: null,
          $$css: !0,
        },
        start: {
          marginInlineStart: "x18xomjl",
          marginLeft: null,
          marginRight: null,
          $$css: !0,
        },
        horizontal: {
          marginInlineStart: "x18xomjl",
          marginInlineEnd: "xbcz3fp",
          marginLeft: null,
          marginRight: null,
          $$css: !0,
        },
        vertical: { marginTop: "x7wgvq7", marginBottom: "xh3wvx0", $$css: !0 },
      },
      f = {
        bottom: { paddingBottom: "xwib8y2", $$css: !0 },
        top: { paddingTop: "x1y1aw1k", $$css: !0 },
        end: {
          paddingInlineEnd: "xpdmqnj",
          paddingLeft: null,
          paddingRight: null,
          $$css: !0,
        },
        start: {
          paddingInlineStart: "x1g0dm76",
          paddingLeft: null,
          paddingRight: null,
          $$css: !0,
        },
        horizontal: {
          paddingInlineStart: "x1g0dm76",
          paddingInlineEnd: "xpdmqnj",
          paddingLeft: null,
          paddingRight: null,
          $$css: !0,
        },
        vertical: {
          paddingTop: "x1y1aw1k",
          paddingBottom: "xwib8y2",
          $$css: !0,
        },
      },
      g = {
        bottom: { paddingBottom: "xwib8y2", $$css: !0 },
        top: { paddingTop: "x1y1aw1k", $$css: !0 },
        end: {
          paddingInlineEnd: "xf159sx",
          paddingLeft: null,
          paddingRight: null,
          $$css: !0,
        },
        start: {
          paddingInlineStart: "xmzvs34",
          paddingLeft: null,
          paddingRight: null,
          $$css: !0,
        },
        horizontal: {
          paddingInlineStart: "xmzvs34",
          paddingInlineEnd: "xf159sx",
          paddingLeft: null,
          paddingRight: null,
          $$css: !0,
        },
        vertical: {
          paddingTop: "x1y1aw1k",
          paddingBottom: "xwib8y2",
          $$css: !0,
        },
      },
      h = {
        bottom: { paddingBottom: "xwib8y2", $$css: !0 },
        top: { paddingTop: "x1y1aw1k", $$css: !0 },
        end: {
          paddingInlineEnd: "xv54qhq",
          paddingLeft: null,
          paddingRight: null,
          $$css: !0,
        },
        start: {
          paddingInlineStart: "xf7dkkf",
          paddingLeft: null,
          paddingRight: null,
          $$css: !0,
        },
        horizontal: {
          paddingInlineStart: "xf7dkkf",
          paddingInlineEnd: "xv54qhq",
          paddingLeft: null,
          paddingRight: null,
          $$css: !0,
        },
        vertical: {
          paddingTop: "x1y1aw1k",
          paddingBottom: "xwib8y2",
          $$css: !0,
        },
      },
      y = {
        bottom: { paddingBottom: "x1ykpatu", $$css: !0 },
        top: { paddingTop: "xm7lytj", $$css: !0 },
        end: {
          paddingInlineEnd: "x1kukv79",
          paddingLeft: null,
          paddingRight: null,
          $$css: !0,
        },
        start: {
          paddingInlineStart: "x1iwz3mf",
          paddingLeft: null,
          paddingRight: null,
          $$css: !0,
        },
        horizontal: {
          paddingInlineStart: "x1iwz3mf",
          paddingInlineEnd: "x1kukv79",
          paddingLeft: null,
          paddingRight: null,
          $$css: !0,
        },
        vertical: {
          paddingTop: "xm7lytj",
          paddingBottom: "x1ykpatu",
          $$css: !0,
        },
      },
      C = {
        bottom: { marginBottom: "x1e56ztr", $$css: !0 },
        top: { marginTop: "x1xmf6yo", $$css: !0 },
        end: {
          marginInlineEnd: "x1xegmmw",
          marginLeft: null,
          marginRight: null,
          $$css: !0,
        },
        start: {
          marginInlineStart: "x13fj5qh",
          marginLeft: null,
          marginRight: null,
          $$css: !0,
        },
        horizontal: {
          marginInlineStart: "x13fj5qh",
          marginInlineEnd: "x1xegmmw",
          marginLeft: null,
          marginRight: null,
          $$css: !0,
        },
        vertical: {
          marginTop: "x1xmf6yo",
          marginBottom: "x1e56ztr",
          $$css: !0,
        },
      },
      b = {
        bottom: {
          ":not([stylex-hack]) > * + *_marginBottom": "x1n14ejq",
          $$css: !0,
        },
        top: { ":not([stylex-hack]) > * + *_marginTop": "xavht8x", $$css: !0 },
        end: {
          ":not([stylex-hack]) > :not(:last-child)_marginInlineEnd": "x8va1my",
          ":not([stylex-hack]) > :not(:last-child)_marginLeft": null,
          ":not([stylex-hack]) > :not(:last-child)_marginRight": null,
          $$css: !0,
        },
        start: {
          ":not([stylex-hack]) > :not(:first-child)_marginInlineEnd":
            "x107ta9c",
          ":not([stylex-hack]) > :not(:first-child)_marginLeft": null,
          ":not([stylex-hack]) > :not(:first-child)_marginRight": null,
          $$css: !0,
        },
        horizontal: {
          ":not([stylex-hack]) > * + *_marginInlineStart": "x5mzjn8",
          ":not([stylex-hack]) > * + *_marginInlineEnd": "x16o6u9d",
          ":not([stylex-hack]) > * + *_marginLeft": null,
          ":not([stylex-hack]) > * + *_marginRight": null,
          $$css: !0,
        },
        vertical: {
          ":not([stylex-hack]) > * + *_marginTop": "xavht8x",
          ":not([stylex-hack]) > * + *_marginBottom": "x1n14ejq",
          $$css: !0,
        },
      },
      v = {
        bottom: { marginBottom: "x1yztbdb", $$css: !0 },
        top: { marginTop: "xw7yly9", $$css: !0 },
        end: {
          marginInlineEnd: "x1ys307a",
          marginLeft: null,
          marginRight: null,
          $$css: !0,
        },
        start: {
          marginInlineStart: "xyqm7xq",
          marginLeft: null,
          marginRight: null,
          $$css: !0,
        },
        horizontal: {
          marginInlineStart: "xyqm7xq",
          marginInlineEnd: "x1ys307a",
          marginLeft: null,
          marginRight: null,
          $$css: !0,
        },
        vertical: { marginTop: "xw7yly9", marginBottom: "x1yztbdb", $$css: !0 },
      },
      S = {
        bottom: {
          ":not([stylex-hack]) > * + *_marginBottom": "x1jbr5dy",
          $$css: !0,
        },
        top: { ":not([stylex-hack]) > * + *_marginTop": "x1kxxb1g", $$css: !0 },
        end: {
          ":not([stylex-hack]) > :not(:last-child)_marginInlineEnd": "x14bzwq1",
          ":not([stylex-hack]) > :not(:last-child)_marginLeft": null,
          ":not([stylex-hack]) > :not(:last-child)_marginRight": null,
          $$css: !0,
        },
        start: {
          ":not([stylex-hack]) > :not(:first-child)_marginInlineEnd": "xo1gg6t",
          ":not([stylex-hack]) > :not(:first-child)_marginLeft": null,
          ":not([stylex-hack]) > :not(:first-child)_marginRight": null,
          $$css: !0,
        },
        horizontal: {
          ":not([stylex-hack]) > * + *_marginInlineStart": "x1fd582z",
          ":not([stylex-hack]) > * + *_marginInlineEnd": "xfiozdf",
          ":not([stylex-hack]) > * + *_marginLeft": null,
          ":not([stylex-hack]) > * + *_marginRight": null,
          $$css: !0,
        },
        vertical: {
          ":not([stylex-hack]) > * + *_marginTop": "x1kxxb1g",
          ":not([stylex-hack]) > * + *_marginBottom": "x1jbr5dy",
          $$css: !0,
        },
      },
      R = {
        bottom: { marginBottom: "x1iymm2a", $$css: !0 },
        top: { marginTop: "xg87l8a", $$css: !0 },
        end: {
          marginInlineEnd: "x1dqj196",
          marginLeft: null,
          marginRight: null,
          $$css: !0,
        },
        start: {
          marginInlineStart: "xvc51xn",
          marginLeft: null,
          marginRight: null,
          $$css: !0,
        },
        horizontal: {
          marginInlineStart: "xvc51xn",
          marginInlineEnd: "x1dqj196",
          marginLeft: null,
          marginRight: null,
          $$css: !0,
        },
        vertical: { marginTop: "xg87l8a", marginBottom: "x1iymm2a", $$css: !0 },
      },
      L = {
        bottom: {
          ":not([stylex-hack]) > * + *_marginBottom": "x33y71p",
          $$css: !0,
        },
        top: { ":not([stylex-hack]) > * + *_marginTop": "x1w65fby", $$css: !0 },
        end: {
          ":not([stylex-hack]) > :not(:last-child)_marginInlineEnd": "xdweeqy",
          ":not([stylex-hack]) > :not(:last-child)_marginLeft": null,
          ":not([stylex-hack]) > :not(:last-child)_marginRight": null,
          $$css: !0,
        },
        start: {
          ":not([stylex-hack]) > :not(:first-child)_marginInlineEnd":
            "x1fx793y",
          ":not([stylex-hack]) > :not(:first-child)_marginLeft": null,
          ":not([stylex-hack]) > :not(:first-child)_marginRight": null,
          $$css: !0,
        },
        horizontal: {
          ":not([stylex-hack]) > * + *_marginInlineStart": "x40m3xb",
          ":not([stylex-hack]) > * + *_marginInlineEnd": "xr4kmwn",
          ":not([stylex-hack]) > * + *_marginLeft": null,
          ":not([stylex-hack]) > * + *_marginRight": null,
          $$css: !0,
        },
        vertical: {
          ":not([stylex-hack]) > * + *_marginTop": "x1w65fby",
          ":not([stylex-hack]) > * + *_marginBottom": "x33y71p",
          $$css: !0,
        },
      },
      E = {
        bottom: { marginBottom: "x12nagc", $$css: !0 },
        top: { marginTop: "x1gslohp", $$css: !0 },
        end: {
          marginInlineEnd: "x2fvf9",
          marginLeft: null,
          marginRight: null,
          $$css: !0,
        },
        start: {
          marginInlineStart: "xdwrcjd",
          marginLeft: null,
          marginRight: null,
          $$css: !0,
        },
        horizontal: {
          marginInlineStart: "xdwrcjd",
          marginInlineEnd: "x2fvf9",
          marginLeft: null,
          marginRight: null,
          $$css: !0,
        },
        vertical: { marginTop: "x1gslohp", marginBottom: "x12nagc", $$css: !0 },
      },
      k = {
        bottom: {
          ":not([stylex-hack]) > * + *_marginBottom": "x1xcg3fx",
          $$css: !0,
        },
        top: { ":not([stylex-hack]) > * + *_marginTop": "xyqj3jm", $$css: !0 },
        end: {
          ":not([stylex-hack]) > :not(:last-child)_marginInlineEnd": "x1xsc7gk",
          ":not([stylex-hack]) > :not(:last-child)_marginLeft": null,
          ":not([stylex-hack]) > :not(:last-child)_marginRight": null,
          $$css: !0,
        },
        start: {
          ":not([stylex-hack]) > :not(:first-child)_marginInlineEnd":
            "x1fwqcib",
          ":not([stylex-hack]) > :not(:first-child)_marginLeft": null,
          ":not([stylex-hack]) > :not(:first-child)_marginRight": null,
          $$css: !0,
        },
        horizontal: {
          ":not([stylex-hack]) > * + *_marginInlineStart": "x1gmw65p",
          ":not([stylex-hack]) > * + *_marginInlineEnd": "x1yjt41m",
          ":not([stylex-hack]) > * + *_marginLeft": null,
          ":not([stylex-hack]) > * + *_marginRight": null,
          $$css: !0,
        },
        vertical: {
          ":not([stylex-hack]) > * + *_marginTop": "xyqj3jm",
          ":not([stylex-hack]) > * + *_marginBottom": "x1xcg3fx",
          $$css: !0,
        },
      },
      I = {
        bottom: { marginBottom: "x1e56ztr", $$css: !0 },
        top: { marginTop: "x1xmf6yo", $$css: !0 },
        end: {
          marginInlineEnd: "x1xegmmw",
          marginLeft: null,
          marginRight: null,
          $$css: !0,
        },
        start: {
          marginInlineStart: "x13fj5qh",
          marginLeft: null,
          marginRight: null,
          $$css: !0,
        },
        horizontal: {
          marginInlineStart: "x13fj5qh",
          marginInlineEnd: "x1xegmmw",
          marginLeft: null,
          marginRight: null,
          $$css: !0,
        },
        vertical: {
          marginTop: "x1xmf6yo",
          marginBottom: "x1e56ztr",
          $$css: !0,
        },
      },
      T = {
        bottom: {
          ":not([stylex-hack]) > * + *_marginBottom": "x1n14ejq",
          $$css: !0,
        },
        top: { ":not([stylex-hack]) > * + *_marginTop": "xavht8x", $$css: !0 },
        end: {
          ":not([stylex-hack]) > :not(:last-child)_marginInlineEnd": "x8va1my",
          ":not([stylex-hack]) > :not(:last-child)_marginLeft": null,
          ":not([stylex-hack]) > :not(:last-child)_marginRight": null,
          $$css: !0,
        },
        start: {
          ":not([stylex-hack]) > :not(:first-child)_marginInlineEnd":
            "x107ta9c",
          ":not([stylex-hack]) > :not(:first-child)_marginLeft": null,
          ":not([stylex-hack]) > :not(:first-child)_marginRight": null,
          $$css: !0,
        },
        horizontal: {
          ":not([stylex-hack]) > * + *_marginInlineStart": "x5mzjn8",
          ":not([stylex-hack]) > * + *_marginInlineEnd": "x16o6u9d",
          ":not([stylex-hack]) > * + *_marginLeft": null,
          ":not([stylex-hack]) > * + *_marginRight": null,
          $$css: !0,
        },
        vertical: {
          ":not([stylex-hack]) > * + *_marginTop": "xavht8x",
          ":not([stylex-hack]) > * + *_marginBottom": "x1n14ejq",
          $$css: !0,
        },
      },
      D = {
        bottom: { marginBottom: "x12nagc", $$css: !0 },
        top: { marginTop: "x1gslohp", $$css: !0 },
        end: {
          marginInlineEnd: "x2fvf9",
          marginLeft: null,
          marginRight: null,
          $$css: !0,
        },
        start: {
          marginInlineStart: "xdwrcjd",
          marginLeft: null,
          marginRight: null,
          $$css: !0,
        },
        horizontal: {
          marginInlineStart: "xdwrcjd",
          marginInlineEnd: "x2fvf9",
          marginLeft: null,
          marginRight: null,
          $$css: !0,
        },
        vertical: { marginTop: "x1gslohp", marginBottom: "x12nagc", $$css: !0 },
      },
      x = {
        bottom: {
          ":not([stylex-hack]) > * + *_marginBottom": "x1xcg3fx",
          $$css: !0,
        },
        top: { ":not([stylex-hack]) > * + *_marginTop": "xyqj3jm", $$css: !0 },
        end: {
          ":not([stylex-hack]) > :not(:last-child)_marginInlineEnd": "x1xsc7gk",
          ":not([stylex-hack]) > :not(:last-child)_marginLeft": null,
          ":not([stylex-hack]) > :not(:last-child)_marginRight": null,
          $$css: !0,
        },
        start: {
          ":not([stylex-hack]) > :not(:first-child)_marginInlineEnd":
            "x1fwqcib",
          ":not([stylex-hack]) > :not(:first-child)_marginLeft": null,
          ":not([stylex-hack]) > :not(:first-child)_marginRight": null,
          $$css: !0,
        },
        horizontal: {
          ":not([stylex-hack]) > * + *_marginInlineStart": "x1gmw65p",
          ":not([stylex-hack]) > * + *_marginInlineEnd": "x1yjt41m",
          ":not([stylex-hack]) > * + *_marginLeft": null,
          ":not([stylex-hack]) > * + *_marginRight": null,
          $$css: !0,
        },
        vertical: {
          ":not([stylex-hack]) > * + *_marginTop": "xyqj3jm",
          ":not([stylex-hack]) > * + *_marginBottom": "x1xcg3fx",
          $$css: !0,
        },
      },
      $ = {
        bottom: { marginBottom: "xod5an3", $$css: !0 },
        top: { marginTop: "x14vqqas", $$css: !0 },
        end: {
          marginInlineEnd: "xbmvrgn",
          marginLeft: null,
          marginRight: null,
          $$css: !0,
        },
        start: {
          marginInlineStart: "x1diwwjn",
          marginLeft: null,
          marginRight: null,
          $$css: !0,
        },
        horizontal: {
          marginInlineStart: "x1diwwjn",
          marginInlineEnd: "xbmvrgn",
          marginLeft: null,
          marginRight: null,
          $$css: !0,
        },
        vertical: { marginTop: "x14vqqas", marginBottom: "xod5an3", $$css: !0 },
      },
      P = {
        bottom: {
          ":not([stylex-hack]) > * + *_marginBottom": "x149ltce",
          $$css: !0,
        },
        top: { ":not([stylex-hack]) > * + *_marginTop": "x1ov1sdl", $$css: !0 },
        end: {
          ":not([stylex-hack]) > :not(:last-child)_marginInlineEnd": "xbiq8gi",
          ":not([stylex-hack]) > :not(:last-child)_marginLeft": null,
          ":not([stylex-hack]) > :not(:last-child)_marginRight": null,
          $$css: !0,
        },
        start: {
          ":not([stylex-hack]) > :not(:first-child)_marginInlineEnd":
            "x1fvp05l",
          ":not([stylex-hack]) > :not(:first-child)_marginLeft": null,
          ":not([stylex-hack]) > :not(:first-child)_marginRight": null,
          $$css: !0,
        },
        horizontal: {
          ":not([stylex-hack]) > * + *_marginInlineStart": "xiikhqm",
          ":not([stylex-hack]) > * + *_marginInlineEnd": "x10tvb59",
          ":not([stylex-hack]) > * + *_marginLeft": null,
          ":not([stylex-hack]) > * + *_marginRight": null,
          $$css: !0,
        },
        vertical: {
          ":not([stylex-hack]) > * + *_marginTop": "x1ov1sdl",
          ":not([stylex-hack]) > * + *_marginBottom": "x149ltce",
          $$css: !0,
        },
      },
      N = {
        bottom: { marginBottom: "x1yztbdb", $$css: !0 },
        top: { marginTop: "xw7yly9", $$css: !0 },
        end: {
          marginInlineEnd: "x1ys307a",
          marginLeft: null,
          marginRight: null,
          $$css: !0,
        },
        start: {
          marginInlineStart: "xyqm7xq",
          marginLeft: null,
          marginRight: null,
          $$css: !0,
        },
        horizontal: {
          marginInlineStart: "xyqm7xq",
          marginInlineEnd: "x1ys307a",
          marginLeft: null,
          marginRight: null,
          $$css: !0,
        },
        vertical: { marginTop: "xw7yly9", marginBottom: "x1yztbdb", $$css: !0 },
      },
      M = {
        bottom: {
          ":not([stylex-hack]) > * + *_marginBottom": "x1jbr5dy",
          $$css: !0,
        },
        top: { ":not([stylex-hack]) > * + *_marginTop": "x1kxxb1g", $$css: !0 },
        end: {
          ":not([stylex-hack]) > :not(:last-child)_marginInlineEnd": "x14bzwq1",
          ":not([stylex-hack]) > :not(:last-child)_marginLeft": null,
          ":not([stylex-hack]) > :not(:last-child)_marginRight": null,
          $$css: !0,
        },
        start: {
          ":not([stylex-hack]) > :not(:first-child)_marginInlineEnd": "xo1gg6t",
          ":not([stylex-hack]) > :not(:first-child)_marginLeft": null,
          ":not([stylex-hack]) > :not(:first-child)_marginRight": null,
          $$css: !0,
        },
        horizontal: {
          ":not([stylex-hack]) > * + *_marginInlineStart": "x1fd582z",
          ":not([stylex-hack]) > * + *_marginInlineEnd": "xfiozdf",
          ":not([stylex-hack]) > * + *_marginLeft": null,
          ":not([stylex-hack]) > * + *_marginRight": null,
          $$css: !0,
        },
        vertical: {
          ":not([stylex-hack]) > * + *_marginTop": "x1kxxb1g",
          ":not([stylex-hack]) > * + *_marginBottom": "x1jbr5dy",
          $$css: !0,
        },
      };
    ((l.containerInternalPageSpacingStyles = e),
      (l.containerInternalComponentSpacingStyles = s),
      (l.componentFineSpacingStyles = u),
      (l.componentFineSpacingOffsetStyles = c),
      (l.componentNormalSpacingStyles = d),
      (l.componentNormalSpacingOffsetStyles = m),
      (l.componentCoarseSpacingStyles = p),
      (l.componentCoarseSpacingOffsetStyles = _),
      (l.controlNormalSpacingStyles = f),
      (l.controlFineSpacingStyles = g),
      (l.controlCoarseSpacingStyles = h),
      (l.inputSpacingStyles = y),
      (l.containerExternalRelatedSpacingStyles = C),
      (l.layoutContainerExternalRelatedSpacingStyles = b),
      (l.containerExternalUnrelatedSpacingStyles = v),
      (l.layoutContainerExternalUnrelatedSpacingStyles = S),
      (l.containerExternalSectionSpacingStyles = R),
      (l.layoutContainerExternalSectionSpacingStyles = L),
      (l.componentExternalRelatedSpacingStyles = E),
      (l.layoutComponentExternalRelatedSpacingStyles = k),
      (l.componentExternalUnrelatedSpacingStyles = I),
      (l.layoutComponentExternalUnrelatedSpacingStyles = T),
      (l.contentExternalHeadingSpacingStyles = D),
      (l.layoutContentExternalHeadingSpacingStyles = x),
      (l.contentExternalParagraphSpacingStyles = $),
      (l.layoutContentExternalParagraphSpacingStyles = P),
      (l.contentExternalSectionSpacingStyles = N),
      (l.layoutContentExternalSectionSpacingStyles = M));
  },
  98,
);
