__d(
  "GroupsCometAAV5ContentCreationComposerButton_renderer$normalization.graphql",
  [],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = (function () {
      var e = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "__typename",
          storageKey: null,
        },
        t = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "id",
          storageKey: null,
        },
        n = [e, t],
        r = [
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "uri",
            storageKey: null,
          },
        ],
        o = [
          e,
          t,
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "name",
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            concreteType: "Image",
            kind: "LinkedField",
            name: "profile_picture",
            plural: !1,
            selections: r,
            storageKey: null,
          },
        ];
      return {
        kind: "SplitOperation",
        metadata: {},
        name: "GroupsCometAAV5ContentCreationComposerButton_renderer$normalization",
        selections: [
          {
            alias: null,
            args: null,
            concreteType: "TextWithEntities",
            kind: "LinkedField",
            name: "edit_post_label",
            plural: !1,
            selections: [
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "text",
                storageKey: null,
              },
            ],
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            concreteType: null,
            kind: "LinkedField",
            name: "composer_static_image",
            plural: !1,
            selections: n,
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            concreteType: "Group",
            kind: "LinkedField",
            name: "group",
            plural: !1,
            selections: [
              t,
              {
                condition:
                  "__relay_internal__pv__groups_comet_use_glvrelayprovider",
                kind: "Condition",
                passingValue: !0,
                selections: [
                  {
                    alias: null,
                    args: null,
                    concreteType: null,
                    kind: "LinkedField",
                    name: "current_actor",
                    plural: !1,
                    selections: n,
                    storageKey: null,
                  },
                ],
              },
              {
                alias: null,
                args: null,
                concreteType: "Group",
                kind: "LinkedField",
                name: "if_viewer_can_create_reels",
                plural: !1,
                selections: n,
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                concreteType: null,
                kind: "LinkedField",
                name: "anonymous_profile_if_viewer_should_use_display_actor_id",
                plural: !1,
                selections: o,
                storageKey: null,
              },
              {
                alias: null,
                args: [
                  { kind: "Literal", name: "type", value: "GROUPS_ANONYMOUS" },
                ],
                concreteType: "AvailableActorsConnection",
                kind: "LinkedField",
                name: "available_actors",
                plural: !1,
                selections: [
                  {
                    alias: null,
                    args: null,
                    concreteType: "AvailableActorsEdge",
                    kind: "LinkedField",
                    name: "edges",
                    plural: !0,
                    selections: [
                      {
                        alias: null,
                        args: null,
                        concreteType: null,
                        kind: "LinkedField",
                        name: "node",
                        plural: !1,
                        selections: o,
                        storageKey: null,
                      },
                    ],
                    storageKey: null,
                  },
                ],
                storageKey: 'available_actors(type:"GROUPS_ANONYMOUS")',
              },
              {
                alias: null,
                args: null,
                concreteType: "XFBFeatureIntervention",
                kind: "LinkedField",
                name: "feature_intervention",
                plural: !1,
                selections: [
                  {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "feature_limit_type",
                    storageKey: null,
                  },
                ],
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                concreteType: "Group",
                kind: "LinkedField",
                name: "if_viewer_can_see_anonymous_post_toggle_button",
                plural: !1,
                selections: [t],
                storageKey: null,
              },
            ],
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            concreteType: "XFBAutomationAssistContentCreationRenderer",
            kind: "LinkedField",
            name: "if_can_use_text_format",
            plural: !1,
            selections: [
              {
                alias: null,
                args: null,
                concreteType: "TextFormatMetadata",
                kind: "LinkedField",
                name: "text_format_metadata",
                plural: !1,
                selections: [
                  {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "avatar_story_text_format_id",
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "preset_id",
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: [
                      { kind: "Literal", name: "supported", value: "3y1xqP" },
                    ],
                    concreteType: null,
                    kind: "LinkedField",
                    name: "background",
                    plural: !1,
                    selections: [
                      e,
                      {
                        kind: "InlineFragment",
                        selections: [
                          {
                            args: null,
                            documentName:
                              "FeedComposerCometFormattedTextBackgroundRoot_data",
                            fragmentName:
                              "FeedComposerCometFormattedTextBackgroundImageRenderer_data",
                            fragmentPropName: "data",
                            kind: "ModuleImport",
                          },
                        ],
                        type: "TextFormatImageBackground",
                        abstractKey: null,
                      },
                      {
                        kind: "InlineFragment",
                        selections: [
                          {
                            args: null,
                            documentName:
                              "FeedComposerCometFormattedTextBackgroundRoot_data",
                            fragmentName:
                              "FeedComposerCometFormattedTextBackgroundVideoRenderer_data",
                            fragmentPropName: "data",
                            kind: "ModuleImport",
                          },
                        ],
                        type: "TextFormatVideoBackground",
                        abstractKey: null,
                      },
                    ],
                    storageKey: 'background(supported:"3y1xqP")',
                  },
                  {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "color",
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: null,
                    concreteType: "InspirationsCustomFont",
                    kind: "LinkedField",
                    name: "inspirations_custom_font_object",
                    plural: !1,
                    selections: [
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "font_name",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "preferred_font_size",
                        storageKey: null,
                      },
                      t,
                    ],
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: null,
                    concreteType: "Image",
                    kind: "LinkedField",
                    name: "custom_thumbnail",
                    plural: !1,
                    selections: r,
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "background_description",
                    storageKey: null,
                  },
                  {
                    alias: "custom_thumbnail_hires",
                    args: [
                      { kind: "Literal", name: "height", value: 160 },
                      { kind: "Literal", name: "width", value: 160 },
                    ],
                    concreteType: "Image",
                    kind: "LinkedField",
                    name: "custom_thumbnail",
                    plural: !1,
                    selections: r,
                    storageKey: "custom_thumbnail(height:160,width:160)",
                  },
                  {
                    alias: "default_thumbnail",
                    args: [
                      { kind: "Literal", name: "height", value: 80 },
                      { kind: "Literal", name: "scale", value: 2 },
                      { kind: "Literal", name: "width", value: 80 },
                    ],
                    concreteType: "Image",
                    kind: "LinkedField",
                    name: "background_image",
                    plural: !1,
                    selections: r,
                    storageKey: "background_image(height:80,scale:2,width:80)",
                  },
                  {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "background_color",
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "background_gradient_color",
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "background_gradient_direction",
                    storageKey: null,
                  },
                ],
                storageKey: null,
              },
              e,
            ],
            storageKey: null,
          },
        ],
      };
    })();
    a.exports = e;
  },
  null,
);
