__d(
  "groupColorCandidates",
  ["fbt"],
  function (t, n, r, o, a, i, l, s) {
    "use strict";
    function e() {
      return {
        "000000": s._(/*BTDS*/ "black"),
        "000080": s._(/*BTDS*/ "dark blue"),
        "00008B": s._(/*BTDS*/ "dark blue"),
        "0000CD": s._(/*BTDS*/ "blue"),
        "0000FF": s._(/*BTDS*/ "blue"),
        "006400": s._(/*BTDS*/ "dark green"),
        "008000": s._(/*BTDS*/ "green"),
        "008080": s._(/*BTDS*/ "teal"),
        "0081C1": s._(/*BTDS*/ "steel blue"),
        "008B8B": s._(/*BTDS*/ "teal"),
        "0099E6": s._(/*BTDS*/ "light blue"),
        "00BFFF": s._(/*BTDS*/ "blue"),
        "00CED1": s._(/*BTDS*/ "bright blue"),
        "00FA9A": s._(/*BTDS*/ "light green"),
        "00FF00": s._(/*BTDS*/ "green"),
        "00FF7F": s._(/*BTDS*/ "green"),
        "00FFFF": s._(/*BTDS*/ "bright blue"),
        "099E89": s._(/*BTDS*/ "teal"),
        "0B9CFD": s._(/*BTDS*/ "light blue"),
        "1877F2": s._(/*BTDS*/ "blue"),
        191970: s._(/*BTDS*/ "dark blue"),
        "1E90FF": s._(/*BTDS*/ "blue"),
        "20B2AA": s._(/*BTDS*/ "teal"),
        "228B22": s._(/*BTDS*/ "green"),
        "24853C": s._(/*BTDS*/ "green"),
        "2E8B57": s._(/*BTDS*/ "green"),
        "2F4F4F": s._(/*BTDS*/ "teal"),
        "31A24C": s._(/*BTDS*/ "light green"),
        "32CD32": s._(/*BTDS*/ "green"),
        "3CB371": s._(/*BTDS*/ "green"),
        "40E0D0": s._(/*BTDS*/ "light blue"),
        "4169E1": s._(/*BTDS*/ "blue"),
        "4682B4": s._(/*BTDS*/ "blue"),
        "483D8B": s._(/*BTDS*/ "dark purple"),
        "48D1CC": s._(/*BTDS*/ "bright blue"),
        "4B0082": s._(/*BTDS*/ "dark purple"),
        "556B2F": s._(/*BTDS*/ "olive"),
        "5F9EA0": s._(/*BTDS*/ "teal"),
        "63BF4C": s._(/*BTDS*/ "light green"),
        "6495ED": s._(/*BTDS*/ "light blue"),
        663399: s._(/*BTDS*/ "purple"),
        "66CDAA": s._(/*BTDS*/ "teal"),
        696969: s._(/*BTDS*/ "dark grey"),
        "6A5ACD": s._(/*BTDS*/ "purple"),
        "6B8E23": s._(/*BTDS*/ "olive"),
        708090: s._(/*BTDS*/ "grey"),
        778899: s._(/*BTDS*/ "grey"),
        "7B68EE": s._(/*BTDS*/ "purple"),
        "7CFC00": s._(/*BTDS*/ "light green"),
        "7FFF00": s._(/*BTDS*/ "light green"),
        "7FFFD4": s._(/*BTDS*/ "bright blue"),
        8e5: s._(/*BTDS*/ "dark red"),
        800080: s._(/*BTDS*/ "purple"),
        808e3: s._(/*BTDS*/ "olive"),
        808080: s._(/*BTDS*/ "dark grey"),
        "814DE7": s._(/*BTDS*/ "purple"),
        "87CEEB": s._(/*BTDS*/ "light blue"),
        "87CEFA": s._(/*BTDS*/ "light blue"),
        "8A2BE2": s._(/*BTDS*/ "purple"),
        "8B0000": s._(/*BTDS*/ "dark red"),
        "8B008B": s._(/*BTDS*/ "dark purple"),
        "8B4513": s._(/*BTDS*/ "brown"),
        "8FBC8F": s._(/*BTDS*/ "olive"),
        "90EE90": s._(/*BTDS*/ "light green"),
        "9370DB": s._(/*BTDS*/ "purple"),
        "9400D3": s._(/*BTDS*/ "purple"),
        "98FB98": s._(/*BTDS*/ "light green"),
        "9932CC": s._(/*BTDS*/ "purple"),
        "9ACD32": s._(/*BTDS*/ "light green"),
        A0522D: s._(/*BTDS*/ "brown"),
        A52A2A: s._(/*BTDS*/ "dark red"),
        A9A9A9: s._(/*BTDS*/ "grey"),
        ADD8E6: s._(/*BTDS*/ "light blue"),
        ADFF2F: s._(/*BTDS*/ "light green"),
        AFEEEE: s._(/*BTDS*/ "light blue"),
        B0C4DE: s._(/*BTDS*/ "light grey"),
        B0E0E6: s._(/*BTDS*/ "light blue"),
        B22222: s._(/*BTDS*/ "dark red"),
        B55400: s._(/*BTDS*/ "brown"),
        B8860B: s._(/*BTDS*/ "beige"),
        BA2D52: s._(/*BTDS*/ "crimson"),
        BA55D3: s._(/*BTDS*/ "purple"),
        BC8F8F: s._(/*BTDS*/ "light red"),
        BDB76B: s._(/*BTDS*/ "olive"),
        C0C0C0: s._(/*BTDS*/ "grey"),
        C71585: s._(/*BTDS*/ "magenta"),
        CD5C5C: s._(/*BTDS*/ "red"),
        CD853F: s._(/*BTDS*/ "brown"),
        D16F14: s._(/*BTDS*/ "tan"),
        D2691E: s._(/*BTDS*/ "dark orange"),
        D2B48C: s._(/*BTDS*/ "beige"),
        D3D3D3: s._(/*BTDS*/ "light grey"),
        D8BFD8: s._(/*BTDS*/ "pink"),
        DA70D6: s._(/*BTDS*/ "light purple"),
        DAA520: s._(/*BTDS*/ "dark yellow"),
        DB7093: s._(/*BTDS*/ "pink"),
        DC143C: s._(/*BTDS*/ "red"),
        DCDCDC: s._(/*BTDS*/ "light grey"),
        DDA0DD: s._(/*BTDS*/ "light purple"),
        DEB887: s._(/*BTDS*/ "beige"),
        E0FFFF: s._(/*BTDS*/ "light blue"),
        E6E6FA: s._(/*BTDS*/ "light purple"),
        E9967A: s._(/*BTDS*/ "light orange"),
        EB660D: s._(/*BTDS*/ "orange"),
        ED41A5: s._(/*BTDS*/ "pink"),
        ED4A34: s._(/*BTDS*/ "dark orange"),
        EE82EE: s._(/*BTDS*/ "pink"),
        EEE8AA: s._(/*BTDS*/ "beige"),
        F02849: s._(/*BTDS*/ "red"),
        F08080: s._(/*BTDS*/ "light red"),
        F0E68C: s._(/*BTDS*/ "light yellow"),
        F0F8FF: s._(/*BTDS*/ "light blue"),
        F0FFF0: s._(/*BTDS*/ "light green"),
        F0FFFF: s._(/*BTDS*/ "white"),
        F25529: s._(/*BTDS*/ "dark orange"),
        F4A460: s._(/*BTDS*/ "light orange"),
        F5DEB3: s._(/*BTDS*/ "beige"),
        F5F5DC: s._(/*BTDS*/ "beige"),
        F5F5F5: s._(/*BTDS*/ "light grey"),
        F5FFFA: s._(/*BTDS*/ "light green"),
        F6AF09: s._(/*BTDS*/ "yellow"),
        F8F8FF: s._(/*BTDS*/ "white"),
        FA8072: s._(/*BTDS*/ "red"),
        FAEBD7: s._(/*BTDS*/ "beige"),
        FAF0E6: s._(/*BTDS*/ "beige"),
        FAFAD2: s._(/*BTDS*/ "light yellow"),
        FC5776: s._(/*BTDS*/ "coral"),
        FDF5E6: s._(/*BTDS*/ "beige"),
        FF0000: s._(/*BTDS*/ "red"),
        FF00FF: s._(/*BTDS*/ "magenta"),
        FF1493: s._(/*BTDS*/ "pink"),
        FF4500: s._(/*BTDS*/ "red"),
        FF6347: s._(/*BTDS*/ "red"),
        FF69B4: s._(/*BTDS*/ "pink"),
        FF7F50: s._(/*BTDS*/ "orange"),
        FF8C00: s._(/*BTDS*/ "orange"),
        FFA07A: s._(/*BTDS*/ "light orange"),
        FFA500: s._(/*BTDS*/ "orange"),
        FFB6C1: s._(/*BTDS*/ "pink"),
        FFC0CB: s._(/*BTDS*/ "pink"),
        FFD700: s._(/*BTDS*/ "yellow"),
        FFDAB9: s._(/*BTDS*/ "beige"),
        FFDEAD: s._(/*BTDS*/ "beige"),
        FFE4B5: s._(/*BTDS*/ "beige"),
        FFE4C4: s._(/*BTDS*/ "beige"),
        FFE4E1: s._(/*BTDS*/ "pink"),
        FFEBCD: s._(/*BTDS*/ "beige"),
        FFEFD5: s._(/*BTDS*/ "beige"),
        FFF0F5: s._(/*BTDS*/ "light pink"),
        FFF5EE: s._(/*BTDS*/ "white"),
        FFF8DC: s._(/*BTDS*/ "light yellow"),
        FFFACD: s._(/*BTDS*/ "light yellow"),
        FFFAF0: s._(/*BTDS*/ "white"),
        FFFAFA: s._(/*BTDS*/ "white"),
        FFFF00: s._(/*BTDS*/ "yellow"),
        FFFFE0: s._(/*BTDS*/ "light yellow"),
        FFFFF0: s._(/*BTDS*/ "white"),
        FFFFFF: s._(/*BTDS*/ "white"),
      };
    }
    l.default = e;
  },
  226,
);
