__d(
  "IGDSTextTypeSharedVariants",
  [],
  function (t, n, r, o, a, i, l) {
    "use strict";
    var e = {
        base: { fontStretch: "x14g2gp5", lineHeight: "xwu0ehp", $$css: !0 },
        defaultBaseLineAdjustment: { paddingBottom: "xcht7qi", $$css: !0 },
        defaultBottomOffset: { "::after_marginBottom": "xrvld1y", $$css: !0 },
        defaultMultilineBottomOffset: {
          "::after_marginBottom": "x1dap93i",
          $$css: !0,
        },
        defaultTopOffset: { "::before_marginTop": "xa794po", $$css: !0 },
        denseMode: {
          fontSize: "xbpoouy",
          fontWeight: "xbg3aqn",
          lineHeight: "x1gmnv1w",
          $$css: !0,
        },
        letterSpacing: { letterSpacing: "x1rdzvro", $$css: !0 },
        macGeckoBaseLineAdjustment: { paddingBottom: "x7vv8ti", $$css: !0 },
        macGeckoBottomOffset: { "::after_marginBottom": "x13a7v9q", $$css: !0 },
        macGeckoMultilineBottomOffset: {
          "::after_marginBottom": "x4t788g",
          $$css: !0,
        },
        macGeckoTopOffset: { "::before_marginTop": "x1n9r9dw", $$css: !0 },
        macWebkitBaseLineAdjustment: { paddingBottom: "xhwbanj", $$css: !0 },
        macWebkitBottomOffset: {
          "::after_marginBottom": "x1k611fb",
          $$css: !0,
        },
        macWebkitMultilineBottomOffset: {
          "::after_marginBottom": "x9bov0k",
          $$css: !0,
        },
        macWebkitTopOffset: { "::before_marginTop": "xvyoqso", $$css: !0 },
        root: { fontSize: "xu2cu48", fontWeight: "x15c40vi", $$css: !0 },
        textStyleApple: { fontFamily: "x144wcp0", $$css: !0 },
        textStyleDefault: { fontFamily: "x1hdkvq9", $$css: !0 },
        textStyleWindows: { fontFamily: "x1rl3oym", $$css: !0 },
        textTransform: { textTransform: "x1lnvu90", $$css: !0 },
        windowsBaseLineAdjustment: { paddingBottom: "x1nxbyug", $$css: !0 },
        windowsBottomOffset: { "::after_marginBottom": "x1yh5ldm", $$css: !0 },
        windowsMultilineBottomOffset: {
          "::after_marginBottom": "x1evnwt7",
          $$css: !0,
        },
        windowsTopOffset: { "::before_marginTop": "x1bwcrc1", $$css: !0 },
      },
      s = {
        base: { fontStretch: "x14g2gp5", lineHeight: "x1ltwk58", $$css: !0 },
        defaultBaseLineAdjustment: { paddingBottom: "xdeihhi", $$css: !0 },
        defaultBottomOffset: { "::after_marginBottom": "xgok60g", $$css: !0 },
        defaultMultilineBottomOffset: {
          "::after_marginBottom": "xtesvta",
          $$css: !0,
        },
        defaultTopOffset: { "::before_marginTop": "x1naxdtk", $$css: !0 },
        denseMode: {
          fontSize: "x1sh12sr",
          fontWeight: "x1e95onf",
          lineHeight: "x3fievf",
          $$css: !0,
        },
        letterSpacing: { letterSpacing: "x2erfd5", $$css: !0 },
        macGeckoBaseLineAdjustment: { paddingBottom: "x13p1orr", $$css: !0 },
        macGeckoBottomOffset: { "::after_marginBottom": "xvu967e", $$css: !0 },
        macGeckoMultilineBottomOffset: {
          "::after_marginBottom": "x1w6m5jr",
          $$css: !0,
        },
        macGeckoTopOffset: { "::before_marginTop": "x13kdv7s", $$css: !0 },
        macWebkitBaseLineAdjustment: { paddingBottom: "x1r6jgrq", $$css: !0 },
        macWebkitBottomOffset: {
          "::after_marginBottom": "x14t76q6",
          $$css: !0,
        },
        macWebkitMultilineBottomOffset: {
          "::after_marginBottom": "x1ljypm",
          $$css: !0,
        },
        macWebkitTopOffset: { "::before_marginTop": "x13ovmrm", $$css: !0 },
        root: { fontSize: "xhw6na0", fontWeight: "xe46h72", $$css: !0 },
        textStyleApple: { fontFamily: "x1w9ouiy", $$css: !0 },
        textStyleDefault: { fontFamily: "x18m7z38", $$css: !0 },
        textStyleWindows: { fontFamily: "x1et8e4m", $$css: !0 },
        textTransform: { textTransform: "x1qu1n7x", $$css: !0 },
        windowsBaseLineAdjustment: { paddingBottom: "x1otiuu", $$css: !0 },
        windowsBottomOffset: { "::after_marginBottom": "x7ulcfd", $$css: !0 },
        windowsMultilineBottomOffset: {
          "::after_marginBottom": "x1d5gbm8",
          $$css: !0,
        },
        windowsTopOffset: { "::before_marginTop": "x10m0jap", $$css: !0 },
      },
      u = {
        base: { fontStretch: "x14g2gp5", lineHeight: "xuwz08h", $$css: !0 },
        defaultBaseLineAdjustment: { paddingBottom: "xupxd21", $$css: !0 },
        defaultBottomOffset: { "::after_marginBottom": "x17470dc", $$css: !0 },
        defaultMultilineBottomOffset: {
          "::after_marginBottom": "x1kghvq4",
          $$css: !0,
        },
        defaultTopOffset: { "::before_marginTop": "xnx1uph", $$css: !0 },
        denseMode: {
          fontSize: "xytf8cw",
          fontWeight: "xv1dw6u",
          lineHeight: "x159eqr4",
          $$css: !0,
        },
        letterSpacing: { letterSpacing: "x1fxoii6", $$css: !0 },
        macGeckoBaseLineAdjustment: { paddingBottom: "x1u8cpjd", $$css: !0 },
        macGeckoBottomOffset: { "::after_marginBottom": "xe7v1un", $$css: !0 },
        macGeckoMultilineBottomOffset: {
          "::after_marginBottom": "x1rtpw8n",
          $$css: !0,
        },
        macGeckoTopOffset: { "::before_marginTop": "x1jmxu37", $$css: !0 },
        macWebkitBaseLineAdjustment: { paddingBottom: "x1f7coh4", $$css: !0 },
        macWebkitBottomOffset: { "::after_marginBottom": "xvpol1d", $$css: !0 },
        macWebkitMultilineBottomOffset: {
          "::after_marginBottom": "xtbspmq",
          $$css: !0,
        },
        macWebkitTopOffset: { "::before_marginTop": "x1t1hd0b", $$css: !0 },
        root: { fontSize: "x18c0a79", fontWeight: "xu37r0v", $$css: !0 },
        textStyleApple: { fontFamily: "xjff08q", $$css: !0 },
        textStyleDefault: { fontFamily: "xo94od6", $$css: !0 },
        textStyleWindows: { fontFamily: "x14ognje", $$css: !0 },
        textTransform: { textTransform: "xrxb4jq", $$css: !0 },
        windowsBaseLineAdjustment: { paddingBottom: "x13jzntu", $$css: !0 },
        windowsBottomOffset: { "::after_marginBottom": "xya83n1", $$css: !0 },
        windowsMultilineBottomOffset: {
          "::after_marginBottom": "x1cw5lcb",
          $$css: !0,
        },
        windowsTopOffset: { "::before_marginTop": "x5jzov0", $$css: !0 },
      },
      c = {
        base: { fontStretch: "x14g2gp5", lineHeight: "xsukrob", $$css: !0 },
        defaultBaseLineAdjustment: { paddingBottom: "xezr7x3", $$css: !0 },
        defaultBottomOffset: { "::after_marginBottom": "x1t3f45o", $$css: !0 },
        defaultMultilineBottomOffset: {
          "::after_marginBottom": "xv22j6y",
          $$css: !0,
        },
        defaultTopOffset: { "::before_marginTop": "x7lwq7z", $$css: !0 },
        denseMode: {
          fontSize: "xiuqcnp",
          fontWeight: "x2g67i0",
          lineHeight: "xqw8lsz",
          $$css: !0,
        },
        letterSpacing: { letterSpacing: "x75xjw4", $$css: !0 },
        macGeckoBaseLineAdjustment: { paddingBottom: "xns4fxu", $$css: !0 },
        macGeckoBottomOffset: { "::after_marginBottom": "xnqtbpu", $$css: !0 },
        macGeckoMultilineBottomOffset: {
          "::after_marginBottom": "x88lnn3",
          $$css: !0,
        },
        macGeckoTopOffset: { "::before_marginTop": "x4twp39", $$css: !0 },
        macWebkitBaseLineAdjustment: { paddingBottom: "xfadu90", $$css: !0 },
        macWebkitBottomOffset: { "::after_marginBottom": "x6rhghg", $$css: !0 },
        macWebkitMultilineBottomOffset: {
          "::after_marginBottom": "xd40qt4",
          $$css: !0,
        },
        macWebkitTopOffset: { "::before_marginTop": "x1kx5a0e", $$css: !0 },
        root: { fontSize: "x4u77h1", fontWeight: "x1hhbrkm", $$css: !0 },
        textStyleApple: { fontFamily: "x156u0bh", $$css: !0 },
        textStyleDefault: { fontFamily: "xr74ml6", $$css: !0 },
        textStyleWindows: { fontFamily: "x9gcn1t", $$css: !0 },
        textTransform: { textTransform: "x1nhu837", $$css: !0 },
        windowsBaseLineAdjustment: { paddingBottom: "x1bq5epv", $$css: !0 },
        windowsBottomOffset: { "::after_marginBottom": "x180ubun", $$css: !0 },
        windowsMultilineBottomOffset: {
          "::after_marginBottom": "x1uw5y03",
          $$css: !0,
        },
        windowsTopOffset: { "::before_marginTop": "x186v28w", $$css: !0 },
      },
      d = {
        base: { fontStretch: "x14g2gp5", lineHeight: "x1h2aame", $$css: !0 },
        defaultBaseLineAdjustment: { paddingBottom: "x1ypracm", $$css: !0 },
        defaultBottomOffset: { "::after_marginBottom": "x1e0bufz", $$css: !0 },
        defaultMultilineBottomOffset: {
          "::after_marginBottom": "x1yctw55",
          $$css: !0,
        },
        defaultTopOffset: { "::before_marginTop": "x17pkmn5", $$css: !0 },
        denseMode: {
          fontSize: "xyzh69a",
          fontWeight: "x1p6iq01",
          lineHeight: "x1j78d4s",
          $$css: !0,
        },
        letterSpacing: { letterSpacing: "x1wo7o99", $$css: !0 },
        macGeckoBaseLineAdjustment: { paddingBottom: "xli8mwh", $$css: !0 },
        macGeckoBottomOffset: { "::after_marginBottom": "x2gm6zh", $$css: !0 },
        macGeckoMultilineBottomOffset: {
          "::after_marginBottom": "x5gb9ot",
          $$css: !0,
        },
        macGeckoTopOffset: { "::before_marginTop": "xau1df5", $$css: !0 },
        macWebkitBaseLineAdjustment: { paddingBottom: "x9oitem", $$css: !0 },
        macWebkitBottomOffset: {
          "::after_marginBottom": "x1w5s5tg",
          $$css: !0,
        },
        macWebkitMultilineBottomOffset: {
          "::after_marginBottom": "xlnlpxv",
          $$css: !0,
        },
        macWebkitTopOffset: { "::before_marginTop": "x70t9wa", $$css: !0 },
        root: { fontSize: "xknk2x1", fontWeight: "x1sfxr9m", $$css: !0 },
        textStyleApple: { fontFamily: "x1v1cqkj", $$css: !0 },
        textStyleDefault: { fontFamily: "x14gulao", $$css: !0 },
        textStyleWindows: { fontFamily: "x1x4g4qz", $$css: !0 },
        textTransform: { textTransform: "xdj2hd7", $$css: !0 },
        windowsBaseLineAdjustment: { paddingBottom: "xyqfyij", $$css: !0 },
        windowsBottomOffset: { "::after_marginBottom": "x1ddapk8", $$css: !0 },
        windowsMultilineBottomOffset: {
          "::after_marginBottom": "xhwuuqq",
          $$css: !0,
        },
        windowsTopOffset: { "::before_marginTop": "xhlnu94", $$css: !0 },
      },
      m = {
        base: { fontStretch: "x14g2gp5", lineHeight: "x1cuq5th", $$css: !0 },
        defaultBaseLineAdjustment: { paddingBottom: "x1b9tsu8", $$css: !0 },
        defaultBottomOffset: { "::after_marginBottom": "xjcgctj", $$css: !0 },
        defaultMultilineBottomOffset: {
          "::after_marginBottom": "xxii2bd",
          $$css: !0,
        },
        defaultTopOffset: { "::before_marginTop": "xym0pbf", $$css: !0 },
        denseMode: {
          fontSize: "x194hovy",
          fontWeight: "x1eatvs8",
          lineHeight: "x1tv947e",
          $$css: !0,
        },
        letterSpacing: { letterSpacing: "xfebxq8", $$css: !0 },
        macGeckoBaseLineAdjustment: { paddingBottom: "x1xxobug", $$css: !0 },
        macGeckoBottomOffset: { "::after_marginBottom": "x1jhphw9", $$css: !0 },
        macGeckoMultilineBottomOffset: {
          "::after_marginBottom": "x1z0oues",
          $$css: !0,
        },
        macGeckoTopOffset: { "::before_marginTop": "x7nveq1", $$css: !0 },
        macWebkitBaseLineAdjustment: { paddingBottom: "x1r9niq5", $$css: !0 },
        macWebkitBottomOffset: { "::after_marginBottom": "xmnh81w", $$css: !0 },
        macWebkitMultilineBottomOffset: {
          "::after_marginBottom": "x1fdd75u",
          $$css: !0,
        },
        macWebkitTopOffset: { "::before_marginTop": "x6ynyl", $$css: !0 },
        root: { fontSize: "x97ohjl", fontWeight: "xdhhy6a", $$css: !0 },
        textStyleApple: { fontFamily: "x1thulwy", $$css: !0 },
        textStyleDefault: { fontFamily: "x6rbsbe", $$css: !0 },
        textStyleWindows: { fontFamily: "xuvvo9q", $$css: !0 },
        textTransform: { textTransform: "x1u1986e", $$css: !0 },
        windowsBaseLineAdjustment: { paddingBottom: "x1oxy7we", $$css: !0 },
        windowsBottomOffset: { "::after_marginBottom": "xlqb0dr", $$css: !0 },
        windowsMultilineBottomOffset: {
          "::after_marginBottom": "x11bshef",
          $$css: !0,
        },
        windowsTopOffset: { "::before_marginTop": "xna3psl", $$css: !0 },
      },
      p = {
        base: { fontStretch: "x14g2gp5", lineHeight: "xq8h1q1", $$css: !0 },
        defaultBaseLineAdjustment: { paddingBottom: "x1v1qt71", $$css: !0 },
        defaultBottomOffset: { "::after_marginBottom": "xr513f0", $$css: !0 },
        defaultMultilineBottomOffset: {
          "::after_marginBottom": "x1piheqb",
          $$css: !0,
        },
        defaultTopOffset: { "::before_marginTop": "x1cex7d8", $$css: !0 },
        denseMode: {
          fontSize: "xzk4hmu",
          fontWeight: "xnvl02l",
          lineHeight: "xm7ctxu",
          $$css: !0,
        },
        letterSpacing: { letterSpacing: "x1dvrbfx", $$css: !0 },
        macGeckoBaseLineAdjustment: { paddingBottom: "x1aob8is", $$css: !0 },
        macGeckoBottomOffset: { "::after_marginBottom": "x9sdvse", $$css: !0 },
        macGeckoMultilineBottomOffset: {
          "::after_marginBottom": "xd4quyv",
          $$css: !0,
        },
        macGeckoTopOffset: { "::before_marginTop": "x1mg1qmr", $$css: !0 },
        macWebkitBaseLineAdjustment: { paddingBottom: "x1mnct07", $$css: !0 },
        macWebkitBottomOffset: { "::after_marginBottom": "x1ax235", $$css: !0 },
        macWebkitMultilineBottomOffset: {
          "::after_marginBottom": "xwn7vr6",
          $$css: !0,
        },
        macWebkitTopOffset: { "::before_marginTop": "xl7vhk2", $$css: !0 },
        root: { fontSize: "x1gu7sq2", fontWeight: "x1xft52h", $$css: !0 },
        textStyleApple: { fontFamily: "xcck4y0", $$css: !0 },
        textStyleDefault: { fontFamily: "x1butjf6", $$css: !0 },
        textStyleWindows: { fontFamily: "x8jgv7z", $$css: !0 },
        textTransform: { textTransform: "xnhg04c", $$css: !0 },
        windowsBaseLineAdjustment: { paddingBottom: "x1c8qvny", $$css: !0 },
        windowsBottomOffset: { "::after_marginBottom": "x13h70lv", $$css: !0 },
        windowsMultilineBottomOffset: {
          "::after_marginBottom": "xbb536z",
          $$css: !0,
        },
        windowsTopOffset: { "::before_marginTop": "xlv9zue", $$css: !0 },
      },
      _ = {
        base: { fontStretch: "x14g2gp5", lineHeight: "x1k23c7z", $$css: !0 },
        defaultBaseLineAdjustment: { paddingBottom: "x7ijhhw", $$css: !0 },
        defaultBottomOffset: { "::after_marginBottom": "xnq5765", $$css: !0 },
        defaultMultilineBottomOffset: {
          "::after_marginBottom": "x1zuzfi",
          $$css: !0,
        },
        defaultTopOffset: { "::before_marginTop": "xb713r3", $$css: !0 },
        denseMode: {
          fontSize: "xm5q0ao",
          fontWeight: "x1a6ril7",
          lineHeight: "xrm3z6f",
          $$css: !0,
        },
        letterSpacing: { letterSpacing: "xp4hbjs", $$css: !0 },
        macGeckoBaseLineAdjustment: { paddingBottom: "xjfspsa", $$css: !0 },
        macGeckoBottomOffset: { "::after_marginBottom": "x1hckloa", $$css: !0 },
        macGeckoMultilineBottomOffset: {
          "::after_marginBottom": "xp88fye",
          $$css: !0,
        },
        macGeckoTopOffset: { "::before_marginTop": "x101ty20", $$css: !0 },
        macWebkitBaseLineAdjustment: { paddingBottom: "x64un6n", $$css: !0 },
        macWebkitBottomOffset: { "::after_marginBottom": "xlxnd9a", $$css: !0 },
        macWebkitMultilineBottomOffset: {
          "::after_marginBottom": "x1vfyl3y",
          $$css: !0,
        },
        macWebkitTopOffset: { "::before_marginTop": "x1g13z4n", $$css: !0 },
        root: { fontSize: "x8coufk", fontWeight: "x2c4k50", $$css: !0 },
        textStyleApple: { fontFamily: "x1ugfk27", $$css: !0 },
        textStyleDefault: { fontFamily: "x19h0ha6", $$css: !0 },
        textStyleWindows: { fontFamily: "x9rvswk", $$css: !0 },
        textTransform: { textTransform: "x12csnhc", $$css: !0 },
        windowsBaseLineAdjustment: { paddingBottom: "x3z8hm4", $$css: !0 },
        windowsBottomOffset: { "::after_marginBottom": "x11lvdlc", $$css: !0 },
        windowsMultilineBottomOffset: {
          "::after_marginBottom": "xsx0xqv",
          $$css: !0,
        },
        windowsTopOffset: { "::before_marginTop": "x9uwh9h", $$css: !0 },
      },
      f = {
        base: { fontStretch: "x14g2gp5", lineHeight: "x11dydje", $$css: !0 },
        defaultBaseLineAdjustment: { paddingBottom: "x1943cyq", $$css: !0 },
        defaultBottomOffset: { "::after_marginBottom": "xtdi2hr", $$css: !0 },
        defaultMultilineBottomOffset: {
          "::after_marginBottom": "xiqxk5w",
          $$css: !0,
        },
        defaultTopOffset: { "::before_marginTop": "x1qrbxwh", $$css: !0 },
        denseMode: {
          fontSize: "x1ugnjhw",
          fontWeight: "x1lcu5yg",
          lineHeight: "x13zy5jk",
          $$css: !0,
        },
        letterSpacing: { letterSpacing: "x1u2npe2", $$css: !0 },
        macGeckoBaseLineAdjustment: { paddingBottom: "xtfq0xv", $$css: !0 },
        macGeckoBottomOffset: { "::after_marginBottom": "xs33r6x", $$css: !0 },
        macGeckoMultilineBottomOffset: {
          "::after_marginBottom": "x1xloyyj",
          $$css: !0,
        },
        macGeckoTopOffset: { "::before_marginTop": "x66zmet", $$css: !0 },
        macWebkitBaseLineAdjustment: { paddingBottom: "xftnhvs", $$css: !0 },
        macWebkitBottomOffset: { "::after_marginBottom": "xhnc6cf", $$css: !0 },
        macWebkitMultilineBottomOffset: {
          "::after_marginBottom": "x22gdt7",
          $$css: !0,
        },
        macWebkitTopOffset: { "::before_marginTop": "x1udonej", $$css: !0 },
        root: { fontSize: "x1v5fi0l", fontWeight: "x1i9fr61", $$css: !0 },
        textStyleApple: { fontFamily: "xjtjxyg", $$css: !0 },
        textStyleDefault: { fontFamily: "xr40ig", $$css: !0 },
        textStyleWindows: { fontFamily: "x6hu5m0", $$css: !0 },
        textTransform: { textTransform: "xwzqg5u", $$css: !0 },
        windowsBaseLineAdjustment: { paddingBottom: "xs1kjqf", $$css: !0 },
        windowsBottomOffset: { "::after_marginBottom": "x1q7w562", $$css: !0 },
        windowsMultilineBottomOffset: {
          "::after_marginBottom": "xhl09dv",
          $$css: !0,
        },
        windowsTopOffset: { "::before_marginTop": "xaeq4pp", $$css: !0 },
      },
      g = {
        base: { fontStretch: "x14g2gp5", lineHeight: "x1x45mye", $$css: !0 },
        defaultBaseLineAdjustment: { paddingBottom: "xkmi0ni", $$css: !0 },
        defaultBottomOffset: { "::after_marginBottom": "x1u61fwj", $$css: !0 },
        defaultMultilineBottomOffset: {
          "::after_marginBottom": "x10ob5cs",
          $$css: !0,
        },
        defaultTopOffset: { "::before_marginTop": "x93jbrz", $$css: !0 },
        denseMode: {
          fontSize: "x8qep65",
          fontWeight: "x1rwit8z",
          lineHeight: "x1qzotnd",
          $$css: !0,
        },
        letterSpacing: { letterSpacing: "x1ezv77d", $$css: !0 },
        macGeckoBaseLineAdjustment: { paddingBottom: "xv04w", $$css: !0 },
        macGeckoBottomOffset: { "::after_marginBottom": "x5e9beu", $$css: !0 },
        macGeckoMultilineBottomOffset: {
          "::after_marginBottom": "x1drervt",
          $$css: !0,
        },
        macGeckoTopOffset: { "::before_marginTop": "x1xyb8q1", $$css: !0 },
        macWebkitBaseLineAdjustment: { paddingBottom: "x1s9f6mj", $$css: !0 },
        macWebkitBottomOffset: {
          "::after_marginBottom": "x1b7uiis",
          $$css: !0,
        },
        macWebkitMultilineBottomOffset: {
          "::after_marginBottom": "x7j2okt",
          $$css: !0,
        },
        macWebkitTopOffset: { "::before_marginTop": "xdzumob", $$css: !0 },
        root: { fontSize: "x1kbvqvl", fontWeight: "x1ho68u7", $$css: !0 },
        textStyleApple: { fontFamily: "x8ks6pm", $$css: !0 },
        textStyleDefault: { fontFamily: "x15gbx8r", $$css: !0 },
        textStyleWindows: { fontFamily: "x89bt1u", $$css: !0 },
        textTransform: { textTransform: "xwclnew", $$css: !0 },
        windowsBaseLineAdjustment: { paddingBottom: "xxzewt0", $$css: !0 },
        windowsBottomOffset: { "::after_marginBottom": "x1xl9tnb", $$css: !0 },
        windowsMultilineBottomOffset: {
          "::after_marginBottom": "xxtaysn",
          $$css: !0,
        },
        windowsTopOffset: { "::before_marginTop": "x2babgm", $$css: !0 },
      },
      h = {
        base: { fontStretch: "x14g2gp5", lineHeight: "x1n0rk3u", $$css: !0 },
        defaultBaseLineAdjustment: { paddingBottom: "x5l7cqo", $$css: !0 },
        defaultBottomOffset: { "::after_marginBottom": "x1w9ghjf", $$css: !0 },
        defaultMultilineBottomOffset: {
          "::after_marginBottom": "x12fopo6",
          $$css: !0,
        },
        defaultTopOffset: { "::before_marginTop": "x1r7c7ac", $$css: !0 },
        denseMode: {
          fontSize: "x1ukn0lg",
          fontWeight: "xiucit1",
          lineHeight: "x7bcos5",
          $$css: !0,
        },
        letterSpacing: { letterSpacing: "x1657d2q", $$css: !0 },
        macGeckoBaseLineAdjustment: { paddingBottom: "xlpmhqh", $$css: !0 },
        macGeckoBottomOffset: { "::after_marginBottom": "x107bqxl", $$css: !0 },
        macGeckoMultilineBottomOffset: {
          "::after_marginBottom": "x1hzg8pu",
          $$css: !0,
        },
        macGeckoTopOffset: { "::before_marginTop": "x1dr5zlz", $$css: !0 },
        macWebkitBaseLineAdjustment: { paddingBottom: "x83ogz9", $$css: !0 },
        macWebkitBottomOffset: {
          "::after_marginBottom": "x1c7buh5",
          $$css: !0,
        },
        macWebkitMultilineBottomOffset: {
          "::after_marginBottom": "x7t9phh",
          $$css: !0,
        },
        macWebkitTopOffset: { "::before_marginTop": "x1gjevi3", $$css: !0 },
        root: { fontSize: "x102cun8", fontWeight: "x1wt48cj", $$css: !0 },
        textStyleApple: { fontFamily: "x1fdb5y2", $$css: !0 },
        textStyleDefault: { fontFamily: "x62uxcb", $$css: !0 },
        textStyleWindows: { fontFamily: "x11kp1v9", $$css: !0 },
        textTransform: { textTransform: "xqukct2", $$css: !0 },
        windowsBaseLineAdjustment: { paddingBottom: "xcreck4", $$css: !0 },
        windowsBottomOffset: { "::after_marginBottom": "xtaxtew", $$css: !0 },
        windowsMultilineBottomOffset: {
          "::after_marginBottom": "x11ymuzt",
          $$css: !0,
        },
        windowsTopOffset: { "::before_marginTop": "x1hsoyt2", $$css: !0 },
      },
      y = {
        base: { fontStretch: "x14g2gp5", lineHeight: "x1ak80vu", $$css: !0 },
        defaultBaseLineAdjustment: { paddingBottom: "x1qaa854", $$css: !0 },
        defaultBottomOffset: { "::after_marginBottom": "xz87wex", $$css: !0 },
        defaultMultilineBottomOffset: {
          "::after_marginBottom": "xqkags4",
          $$css: !0,
        },
        defaultTopOffset: { "::before_marginTop": "xhzkbaj", $$css: !0 },
        denseMode: {
          fontSize: "x1j07yxv",
          fontWeight: "x113he9f",
          lineHeight: "x19taduc",
          $$css: !0,
        },
        letterSpacing: { letterSpacing: "x1k33xd4", $$css: !0 },
        macGeckoBaseLineAdjustment: { paddingBottom: "x18o7xqd", $$css: !0 },
        macGeckoBottomOffset: { "::after_marginBottom": "x1fjpyva", $$css: !0 },
        macGeckoMultilineBottomOffset: {
          "::after_marginBottom": "x1omx8t",
          $$css: !0,
        },
        macGeckoTopOffset: { "::before_marginTop": "x1trxqkc", $$css: !0 },
        macWebkitBaseLineAdjustment: { paddingBottom: "xufqigc", $$css: !0 },
        macWebkitBottomOffset: { "::after_marginBottom": "x6n7qkn", $$css: !0 },
        macWebkitMultilineBottomOffset: {
          "::after_marginBottom": "x1icyx4k",
          $$css: !0,
        },
        macWebkitTopOffset: { "::before_marginTop": "xp0ts7j", $$css: !0 },
        root: { fontSize: "x149ao6l", fontWeight: "x18fr5qf", $$css: !0 },
        textStyleApple: { fontFamily: "x1o4k75u", $$css: !0 },
        textStyleDefault: { fontFamily: "x121dfkn", $$css: !0 },
        textStyleWindows: { fontFamily: "x1und9tj", $$css: !0 },
        textTransform: { textTransform: "x16x7bwb", $$css: !0 },
        windowsBaseLineAdjustment: { paddingBottom: "xgsotlz", $$css: !0 },
        windowsBottomOffset: { "::after_marginBottom": "x8qgn7j", $$css: !0 },
        windowsMultilineBottomOffset: {
          "::after_marginBottom": "x15xig40",
          $$css: !0,
        },
        windowsTopOffset: { "::before_marginTop": "x9onejg", $$css: !0 },
      },
      C = {
        base: { fontStretch: "x14g2gp5", lineHeight: "xscnkjw", $$css: !0 },
        defaultBaseLineAdjustment: { paddingBottom: "xwa5x35", $$css: !0 },
        defaultBottomOffset: { "::after_marginBottom": "x1f5rmgg", $$css: !0 },
        defaultMultilineBottomOffset: {
          "::after_marginBottom": "x1b43ubb",
          $$css: !0,
        },
        defaultTopOffset: { "::before_marginTop": "x1vo3c7i", $$css: !0 },
        denseMode: {
          fontSize: "xr9v8gl",
          fontWeight: "x1sxyd0s",
          lineHeight: "x11aokpp",
          $$css: !0,
        },
        letterSpacing: { letterSpacing: "x1os6hbj", $$css: !0 },
        macGeckoBaseLineAdjustment: { paddingBottom: "x1t5ih0t", $$css: !0 },
        macGeckoBottomOffset: { "::after_marginBottom": "x146cd56", $$css: !0 },
        macGeckoMultilineBottomOffset: {
          "::after_marginBottom": "x265rsq",
          $$css: !0,
        },
        macGeckoTopOffset: { "::before_marginTop": "xvmvgqh", $$css: !0 },
        macWebkitBaseLineAdjustment: { paddingBottom: "x1nii1ug", $$css: !0 },
        macWebkitBottomOffset: {
          "::after_marginBottom": "x1hi4uuc",
          $$css: !0,
        },
        macWebkitMultilineBottomOffset: {
          "::after_marginBottom": "x5tsj40",
          $$css: !0,
        },
        macWebkitTopOffset: { "::before_marginTop": "x150fs93", $$css: !0 },
        root: { fontSize: "xbqaz7a", fontWeight: "x5za02j", $$css: !0 },
        textStyleApple: { fontFamily: "x1efwq7i", $$css: !0 },
        textStyleDefault: { fontFamily: "xovugq0", $$css: !0 },
        textStyleWindows: { fontFamily: "x258oje", $$css: !0 },
        textTransform: { textTransform: "xd8yua7", $$css: !0 },
        windowsBaseLineAdjustment: { paddingBottom: "x18ov5rh", $$css: !0 },
        windowsBottomOffset: { "::after_marginBottom": "xv8kkem", $$css: !0 },
        windowsMultilineBottomOffset: {
          "::after_marginBottom": "xim7bpe",
          $$css: !0,
        },
        windowsTopOffset: { "::before_marginTop": "x1yy2kid", $$css: !0 },
      },
      b = {
        base: { fontStretch: "x14g2gp5", lineHeight: "x20zut3", $$css: !0 },
        defaultBaseLineAdjustment: { paddingBottom: "x1vioi2c", $$css: !0 },
        defaultBottomOffset: { "::after_marginBottom": "xf09yys", $$css: !0 },
        defaultMultilineBottomOffset: {
          "::after_marginBottom": "xre1yb8",
          $$css: !0,
        },
        defaultTopOffset: { "::before_marginTop": "x1m6htss", $$css: !0 },
        denseMode: {
          fontSize: "xlbctm4",
          fontWeight: "x23awc4",
          lineHeight: "x1w20zkg",
          $$css: !0,
        },
        letterSpacing: { letterSpacing: "x16qv1k2", $$css: !0 },
        macGeckoBaseLineAdjustment: { paddingBottom: "xwduxm1", $$css: !0 },
        macGeckoBottomOffset: { "::after_marginBottom": "x1kyvw4o", $$css: !0 },
        macGeckoMultilineBottomOffset: {
          "::after_marginBottom": "xdkp8s0",
          $$css: !0,
        },
        macGeckoTopOffset: { "::before_marginTop": "x1pnr7gr", $$css: !0 },
        macWebkitBaseLineAdjustment: { paddingBottom: "x6rh3i8", $$css: !0 },
        macWebkitBottomOffset: { "::after_marginBottom": "xshxqn8", $$css: !0 },
        macWebkitMultilineBottomOffset: {
          "::after_marginBottom": "xfuuneq",
          $$css: !0,
        },
        macWebkitTopOffset: { "::before_marginTop": "x9sy4qm", $$css: !0 },
        root: { fontSize: "x1udwfil", fontWeight: "xmdhfcl", $$css: !0 },
        textStyleApple: { fontFamily: "x1i6l24r", $$css: !0 },
        textStyleDefault: { fontFamily: "x6hlu28", $$css: !0 },
        textStyleWindows: { fontFamily: "xtbra7w", $$css: !0 },
        textTransform: { textTransform: "x5xpare", $$css: !0 },
        windowsBaseLineAdjustment: { paddingBottom: "xb1tr7e", $$css: !0 },
        windowsBottomOffset: { "::after_marginBottom": "xizpnnv", $$css: !0 },
        windowsMultilineBottomOffset: {
          "::after_marginBottom": "x1glgqxs",
          $$css: !0,
        },
        windowsTopOffset: { "::before_marginTop": "x1xta6yy", $$css: !0 },
      },
      v = {
        base: { fontStretch: "x14g2gp5", lineHeight: "xksdf9m", $$css: !0 },
        defaultBaseLineAdjustment: { paddingBottom: "x1m8jc8i", $$css: !0 },
        defaultBottomOffset: { "::after_marginBottom": "x1w3oc0d", $$css: !0 },
        defaultMultilineBottomOffset: {
          "::after_marginBottom": "xy1eczs",
          $$css: !0,
        },
        defaultTopOffset: { "::before_marginTop": "x6fbvka", $$css: !0 },
        denseMode: {
          fontSize: "x182gyae",
          fontWeight: "xnycxby",
          lineHeight: "xe3xohw",
          $$css: !0,
        },
        letterSpacing: { letterSpacing: "xnvmg3q", $$css: !0 },
        macGeckoBaseLineAdjustment: { paddingBottom: "x1ncu18p", $$css: !0 },
        macGeckoBottomOffset: { "::after_marginBottom": "x17v88g0", $$css: !0 },
        macGeckoMultilineBottomOffset: {
          "::after_marginBottom": "x1mvidse",
          $$css: !0,
        },
        macGeckoTopOffset: { "::before_marginTop": "x1upuw1c", $$css: !0 },
        macWebkitBaseLineAdjustment: { paddingBottom: "x1cg523h", $$css: !0 },
        macWebkitBottomOffset: { "::after_marginBottom": "xatphn2", $$css: !0 },
        macWebkitMultilineBottomOffset: {
          "::after_marginBottom": "xceddp7",
          $$css: !0,
        },
        macWebkitTopOffset: { "::before_marginTop": "x1elx8kg", $$css: !0 },
        root: { fontSize: "xbu1q3b", fontWeight: "xmy0b1o", $$css: !0 },
        textStyleApple: { fontFamily: "x11q36e7", $$css: !0 },
        textStyleDefault: { fontFamily: "x1dhutxs", $$css: !0 },
        textStyleWindows: { fontFamily: "xqm94nd", $$css: !0 },
        textTransform: { textTransform: "x1vx78lb", $$css: !0 },
        windowsBaseLineAdjustment: { paddingBottom: "x1sx6nk9", $$css: !0 },
        windowsBottomOffset: { "::after_marginBottom": "x7vfz5c", $$css: !0 },
        windowsMultilineBottomOffset: {
          "::after_marginBottom": "x1ndgm2h",
          $$css: !0,
        },
        windowsTopOffset: { "::before_marginTop": "xa1pa7l", $$css: !0 },
      },
      S = {
        base: { fontStretch: "x14g2gp5", lineHeight: "x15175v8", $$css: !0 },
        defaultBaseLineAdjustment: { paddingBottom: "x23krkg", $$css: !0 },
        defaultBottomOffset: { "::after_marginBottom": "x1cp3tyo", $$css: !0 },
        defaultMultilineBottomOffset: {
          "::after_marginBottom": "x1emguw4",
          $$css: !0,
        },
        defaultTopOffset: { "::before_marginTop": "x1dtaoi", $$css: !0 },
        denseMode: {
          fontSize: "x1tunt5e",
          fontWeight: "x2qt8td",
          lineHeight: "xyogsne",
          $$css: !0,
        },
        letterSpacing: { letterSpacing: "xzyychw", $$css: !0 },
        macGeckoBaseLineAdjustment: { paddingBottom: "x7ztl0r", $$css: !0 },
        macGeckoBottomOffset: { "::after_marginBottom": "x1k44g7w", $$css: !0 },
        macGeckoMultilineBottomOffset: {
          "::after_marginBottom": "x1tgaq5b",
          $$css: !0,
        },
        macGeckoTopOffset: { "::before_marginTop": "x1nnwfca", $$css: !0 },
        macWebkitBaseLineAdjustment: { paddingBottom: "x1i7g6fa", $$css: !0 },
        macWebkitBottomOffset: {
          "::after_marginBottom": "x1l1ga17",
          $$css: !0,
        },
        macWebkitMultilineBottomOffset: {
          "::after_marginBottom": "xupu4yb",
          $$css: !0,
        },
        macWebkitTopOffset: { "::before_marginTop": "x8ke4dx", $$css: !0 },
        root: { fontSize: "x1jztii7", fontWeight: "x18z7o2g", $$css: !0 },
        textStyleApple: { fontFamily: "x1k1shlj", $$css: !0 },
        textStyleDefault: { fontFamily: "xj24ffp", $$css: !0 },
        textStyleWindows: { fontFamily: "x19v2pxt", $$css: !0 },
        textTransform: { textTransform: "xa3h53w", $$css: !0 },
        windowsBaseLineAdjustment: { paddingBottom: "xo0rnk9", $$css: !0 },
        windowsBottomOffset: { "::after_marginBottom": "xhlr4cv", $$css: !0 },
        windowsMultilineBottomOffset: {
          "::after_marginBottom": "xe5lrmx",
          $$css: !0,
        },
        windowsTopOffset: { "::before_marginTop": "x1izm8z2", $$css: !0 },
      },
      R = {
        base: { fontStretch: "x14g2gp5", lineHeight: "xfn8v9n", $$css: !0 },
        defaultBaseLineAdjustment: { paddingBottom: "x1ilusbs", $$css: !0 },
        defaultBottomOffset: { "::after_marginBottom": "xlo36fx", $$css: !0 },
        defaultMultilineBottomOffset: {
          "::after_marginBottom": "x2tpttv",
          $$css: !0,
        },
        defaultTopOffset: { "::before_marginTop": "x4fl6tw", $$css: !0 },
        denseMode: {
          fontSize: "xxqwieb",
          fontWeight: "x1wuwyi2",
          lineHeight: "x1ae9sgd",
          $$css: !0,
        },
        letterSpacing: { letterSpacing: "x5uxuo8", $$css: !0 },
        macGeckoBaseLineAdjustment: { paddingBottom: "xlr658r", $$css: !0 },
        macGeckoBottomOffset: { "::after_marginBottom": "x1okaews", $$css: !0 },
        macGeckoMultilineBottomOffset: {
          "::after_marginBottom": "xu7e4wg",
          $$css: !0,
        },
        macGeckoTopOffset: { "::before_marginTop": "xot2ckb", $$css: !0 },
        macWebkitBaseLineAdjustment: { paddingBottom: "x150t5mx", $$css: !0 },
        macWebkitBottomOffset: {
          "::after_marginBottom": "x1kgyul8",
          $$css: !0,
        },
        macWebkitMultilineBottomOffset: {
          "::after_marginBottom": "x13umxe3",
          $$css: !0,
        },
        macWebkitTopOffset: { "::before_marginTop": "x7yt436", $$css: !0 },
        root: { fontSize: "x1j3b5cy", fontWeight: "x1nvkwcz", $$css: !0 },
        textStyleApple: { fontFamily: "x8hw5xx", $$css: !0 },
        textStyleDefault: { fontFamily: "x1mx30uk", $$css: !0 },
        textStyleWindows: { fontFamily: "x1wvumtg", $$css: !0 },
        textTransform: { textTransform: "x1jj9c7s", $$css: !0 },
        windowsBaseLineAdjustment: { paddingBottom: "x1qnweig", $$css: !0 },
        windowsBottomOffset: { "::after_marginBottom": "xr1qma3", $$css: !0 },
        windowsMultilineBottomOffset: {
          "::after_marginBottom": "x8ks2wi",
          $$css: !0,
        },
        windowsTopOffset: { "::before_marginTop": "xyj2l2l", $$css: !0 },
      },
      L = {
        base: { fontStretch: "x14g2gp5", lineHeight: "x11w0jav", $$css: !0 },
        defaultBaseLineAdjustment: { paddingBottom: "xz3q007", $$css: !0 },
        defaultBottomOffset: { "::after_marginBottom": "x1bvlrrw", $$css: !0 },
        defaultMultilineBottomOffset: {
          "::after_marginBottom": "x1cmedpj",
          $$css: !0,
        },
        defaultTopOffset: { "::before_marginTop": "x1brzl8l", $$css: !0 },
        denseMode: {
          fontSize: "x1i8v6fc",
          fontWeight: "x9gg6wk",
          lineHeight: "x1y8cec2",
          $$css: !0,
        },
        letterSpacing: { letterSpacing: "xiyptsk", $$css: !0 },
        macGeckoBaseLineAdjustment: { paddingBottom: "xdlgdo1", $$css: !0 },
        macGeckoBottomOffset: { "::after_marginBottom": "x1fvujcg", $$css: !0 },
        macGeckoMultilineBottomOffset: {
          "::after_marginBottom": "xht6kmb",
          $$css: !0,
        },
        macGeckoTopOffset: { "::before_marginTop": "xizhain", $$css: !0 },
        macWebkitBaseLineAdjustment: { paddingBottom: "x6a3aqq", $$css: !0 },
        macWebkitBottomOffset: { "::after_marginBottom": "xo8whdk", $$css: !0 },
        macWebkitMultilineBottomOffset: {
          "::after_marginBottom": "xqrhqvn",
          $$css: !0,
        },
        macWebkitTopOffset: { "::before_marginTop": "x1tk7ace", $$css: !0 },
        root: { fontSize: "xucsd93", fontWeight: "x1r1qebe", $$css: !0 },
        textStyleApple: { fontFamily: "x1qfwfj7", $$css: !0 },
        textStyleDefault: { fontFamily: "x10gqqzf", $$css: !0 },
        textStyleWindows: { fontFamily: "x11ry79i", $$css: !0 },
        textTransform: { textTransform: "x1f8ud33", $$css: !0 },
        windowsBaseLineAdjustment: { paddingBottom: "x1n5ongv", $$css: !0 },
        windowsBottomOffset: { "::after_marginBottom": "x1f8qqv9", $$css: !0 },
        windowsMultilineBottomOffset: {
          "::after_marginBottom": "x1xxqwyl",
          $$css: !0,
        },
        windowsTopOffset: { "::before_marginTop": "xit955w", $$css: !0 },
      },
      E = {
        base: { fontStretch: "x14g2gp5", lineHeight: "xq5k0si", $$css: !0 },
        defaultBaseLineAdjustment: { paddingBottom: "xtxvd8l", $$css: !0 },
        defaultBottomOffset: { "::after_marginBottom": "x1s7nne0", $$css: !0 },
        defaultMultilineBottomOffset: {
          "::after_marginBottom": "x1fbp4q0",
          $$css: !0,
        },
        defaultTopOffset: { "::before_marginTop": "xakdoee", $$css: !0 },
        denseMode: {
          fontSize: "x16rszoe",
          fontWeight: "x16imdrf",
          lineHeight: "x1p9a9az",
          $$css: !0,
        },
        letterSpacing: { letterSpacing: "x7ps5go", $$css: !0 },
        macGeckoBaseLineAdjustment: { paddingBottom: "x1n0idbz", $$css: !0 },
        macGeckoBottomOffset: { "::after_marginBottom": "xyq6jvs", $$css: !0 },
        macGeckoMultilineBottomOffset: {
          "::after_marginBottom": "xwcs2yj",
          $$css: !0,
        },
        macGeckoTopOffset: { "::before_marginTop": "xpk5dfv", $$css: !0 },
        macWebkitBaseLineAdjustment: { paddingBottom: "xeytlfw", $$css: !0 },
        macWebkitBottomOffset: { "::after_marginBottom": "xklanna", $$css: !0 },
        macWebkitMultilineBottomOffset: {
          "::after_marginBottom": "xwhqcca",
          $$css: !0,
        },
        macWebkitTopOffset: { "::before_marginTop": "xwdgqf3", $$css: !0 },
        root: { fontSize: "xra7jnj", fontWeight: "x1cibqq4", $$css: !0 },
        textStyleApple: { fontFamily: "x1abqg0x", $$css: !0 },
        textStyleDefault: { fontFamily: "x105jos", $$css: !0 },
        textStyleWindows: { fontFamily: "x16c9v55", $$css: !0 },
        textTransform: { textTransform: "x1b5c41v", $$css: !0 },
        windowsBaseLineAdjustment: { paddingBottom: "x1aym7qp", $$css: !0 },
        windowsBottomOffset: { "::after_marginBottom": "xzht4zr", $$css: !0 },
        windowsMultilineBottomOffset: {
          "::after_marginBottom": "x1inyqtp",
          $$css: !0,
        },
        windowsTopOffset: { "::before_marginTop": "xkafqg0", $$css: !0 },
      },
      k = {
        base: { fontStretch: "x14g2gp5", lineHeight: "x1l0c6tc", $$css: !0 },
        defaultBaseLineAdjustment: { paddingBottom: "x194h3ps", $$css: !0 },
        defaultBottomOffset: { "::after_marginBottom": "x17l6lx3", $$css: !0 },
        defaultMultilineBottomOffset: {
          "::after_marginBottom": "x1o674iv",
          $$css: !0,
        },
        defaultTopOffset: { "::before_marginTop": "xiptq1y", $$css: !0 },
        denseMode: {
          fontSize: "xjehxpx",
          fontWeight: "xh6se3w",
          lineHeight: "x10asx6b",
          $$css: !0,
        },
        letterSpacing: { letterSpacing: "x1p4v3wy", $$css: !0 },
        macGeckoBaseLineAdjustment: { paddingBottom: "x9tcmpf", $$css: !0 },
        macGeckoBottomOffset: { "::after_marginBottom": "x16f1pn9", $$css: !0 },
        macGeckoMultilineBottomOffset: {
          "::after_marginBottom": "x1r7wlw4",
          $$css: !0,
        },
        macGeckoTopOffset: { "::before_marginTop": "x2im0uw", $$css: !0 },
        macWebkitBaseLineAdjustment: { paddingBottom: "x1hdhw5h", $$css: !0 },
        macWebkitBottomOffset: { "::after_marginBottom": "xo1vd4t", $$css: !0 },
        macWebkitMultilineBottomOffset: {
          "::after_marginBottom": "x1eu0i5t",
          $$css: !0,
        },
        macWebkitTopOffset: { "::before_marginTop": "x1hu3zyk", $$css: !0 },
        root: { fontSize: "x1ccqxdq", fontWeight: "x1hpoamw", $$css: !0 },
        textStyleApple: { fontFamily: "x8pwreu", $$css: !0 },
        textStyleDefault: { fontFamily: "xh7sr2q", $$css: !0 },
        textStyleWindows: { fontFamily: "x17pce3l", $$css: !0 },
        textTransform: { textTransform: "x19dz0u5", $$css: !0 },
        windowsBaseLineAdjustment: { paddingBottom: "x2e0bug", $$css: !0 },
        windowsBottomOffset: { "::after_marginBottom": "xp3ownr", $$css: !0 },
        windowsMultilineBottomOffset: {
          "::after_marginBottom": "xlce8fd",
          $$css: !0,
        },
        windowsTopOffset: { "::before_marginTop": "x16z0563", $$css: !0 },
      },
      I = {
        base: { fontStretch: "x14g2gp5", lineHeight: "xojf9y8", $$css: !0 },
        defaultBaseLineAdjustment: { paddingBottom: "x8pt91w", $$css: !0 },
        defaultBottomOffset: { "::after_marginBottom": "xhpds1a", $$css: !0 },
        defaultMultilineBottomOffset: {
          "::after_marginBottom": "x1tws87v",
          $$css: !0,
        },
        defaultTopOffset: { "::before_marginTop": "x1u3ute2", $$css: !0 },
        denseMode: {
          fontSize: "xf10he4",
          fontWeight: "xsdjmd6",
          lineHeight: "x9xn6tj",
          $$css: !0,
        },
        letterSpacing: { letterSpacing: "x1kzvw2a", $$css: !0 },
        macGeckoBaseLineAdjustment: { paddingBottom: "xs34txz", $$css: !0 },
        macGeckoBottomOffset: { "::after_marginBottom": "x1tisuvw", $$css: !0 },
        macGeckoMultilineBottomOffset: {
          "::after_marginBottom": "x1gfpr39",
          $$css: !0,
        },
        macGeckoTopOffset: { "::before_marginTop": "x1fb0ynx", $$css: !0 },
        macWebkitBaseLineAdjustment: { paddingBottom: "xcla1mw", $$css: !0 },
        macWebkitBottomOffset: { "::after_marginBottom": "x2gioed", $$css: !0 },
        macWebkitMultilineBottomOffset: {
          "::after_marginBottom": "x1bb43vm",
          $$css: !0,
        },
        macWebkitTopOffset: { "::before_marginTop": "xpg7yeh", $$css: !0 },
        root: { fontSize: "xveuv9e", fontWeight: "x1d9fzel", $$css: !0 },
        textStyleApple: { fontFamily: "xh7q0tc", $$css: !0 },
        textStyleDefault: { fontFamily: "xmhgz5s", $$css: !0 },
        textStyleWindows: { fontFamily: "xfgxiah", $$css: !0 },
        textTransform: { textTransform: "x1ievfu5", $$css: !0 },
        windowsBaseLineAdjustment: { paddingBottom: "x1svvx3i", $$css: !0 },
        windowsBottomOffset: { "::after_marginBottom": "xpuys3n", $$css: !0 },
        windowsMultilineBottomOffset: {
          "::after_marginBottom": "xay2mna",
          $$css: !0,
        },
        windowsTopOffset: { "::before_marginTop": "xv97iwz", $$css: !0 },
      },
      T = {
        base: { fontStretch: "x14g2gp5", lineHeight: "xbcx0ih", $$css: !0 },
        defaultBaseLineAdjustment: { paddingBottom: "x1vep0dm", $$css: !0 },
        defaultBottomOffset: { "::after_marginBottom": "x1crmjsk", $$css: !0 },
        defaultMultilineBottomOffset: {
          "::after_marginBottom": "xduwdi",
          $$css: !0,
        },
        defaultTopOffset: { "::before_marginTop": "xje1to7", $$css: !0 },
        denseMode: {
          fontSize: "xb9cjhm",
          fontWeight: "xbewu5b",
          lineHeight: "x7c500w",
          $$css: !0,
        },
        letterSpacing: { letterSpacing: "xa9pkv6", $$css: !0 },
        macGeckoBaseLineAdjustment: { paddingBottom: "x141pher", $$css: !0 },
        macGeckoBottomOffset: { "::after_marginBottom": "x15kyput", $$css: !0 },
        macGeckoMultilineBottomOffset: {
          "::after_marginBottom": "x1w96x43",
          $$css: !0,
        },
        macGeckoTopOffset: { "::before_marginTop": "x1mpacms", $$css: !0 },
        macWebkitBaseLineAdjustment: { paddingBottom: "xnc1cq5", $$css: !0 },
        macWebkitBottomOffset: { "::after_marginBottom": "xkb3dz0", $$css: !0 },
        macWebkitMultilineBottomOffset: {
          "::after_marginBottom": "x1ks37lf",
          $$css: !0,
        },
        macWebkitTopOffset: { "::before_marginTop": "xs14nl5", $$css: !0 },
        root: { fontSize: "x1sodpjp", fontWeight: "x1fujjar", $$css: !0 },
        textStyleApple: { fontFamily: "xp5m0gm", $$css: !0 },
        textStyleDefault: { fontFamily: "x1ud03kz", $$css: !0 },
        textStyleWindows: { fontFamily: "x1mspte8", $$css: !0 },
        textTransform: { textTransform: "xbu8soq", $$css: !0 },
        windowsBaseLineAdjustment: { paddingBottom: "x64qyf", $$css: !0 },
        windowsBottomOffset: { "::after_marginBottom": "x1id2g1", $$css: !0 },
        windowsMultilineBottomOffset: {
          "::after_marginBottom": "xre9j9m",
          $$css: !0,
        },
        windowsTopOffset: { "::before_marginTop": "xmme07h", $$css: !0 },
      },
      D = {
        base: { fontStretch: "x14g2gp5", lineHeight: "xg5k8oi", $$css: !0 },
        defaultBaseLineAdjustment: { paddingBottom: "x1056by3", $$css: !0 },
        defaultBottomOffset: { "::after_marginBottom": "x14yreqm", $$css: !0 },
        defaultMultilineBottomOffset: {
          "::after_marginBottom": "x1soikeo",
          $$css: !0,
        },
        defaultTopOffset: { "::before_marginTop": "xpukfev", $$css: !0 },
        denseMode: {
          fontSize: "x1uvnupv",
          fontWeight: "xoj6ec8",
          lineHeight: "xttx25h",
          $$css: !0,
        },
        letterSpacing: { letterSpacing: "x1q2gic2", $$css: !0 },
        macGeckoBaseLineAdjustment: { paddingBottom: "x1evijom", $$css: !0 },
        macGeckoBottomOffset: { "::after_marginBottom": "x18ew2s9", $$css: !0 },
        macGeckoMultilineBottomOffset: {
          "::after_marginBottom": "xn64fr3",
          $$css: !0,
        },
        macGeckoTopOffset: { "::before_marginTop": "xc3mfl4", $$css: !0 },
        macWebkitBaseLineAdjustment: { paddingBottom: "x1dwa2zb", $$css: !0 },
        macWebkitBottomOffset: {
          "::after_marginBottom": "x10civ6c",
          $$css: !0,
        },
        macWebkitMultilineBottomOffset: {
          "::after_marginBottom": "x11sgott",
          $$css: !0,
        },
        macWebkitTopOffset: { "::before_marginTop": "x1rezggo", $$css: !0 },
        root: { fontSize: "xw8audo", fontWeight: "xegfroq", $$css: !0 },
        textStyleApple: { fontFamily: "xog0vnc", $$css: !0 },
        textStyleDefault: { fontFamily: "x8ar7m4", $$css: !0 },
        textStyleWindows: { fontFamily: "x13r0slp", $$css: !0 },
        textTransform: { textTransform: "xsiiwme", $$css: !0 },
        windowsBaseLineAdjustment: { paddingBottom: "x120eboi", $$css: !0 },
        windowsBottomOffset: { "::after_marginBottom": "x1nywle8", $$css: !0 },
        windowsMultilineBottomOffset: {
          "::after_marginBottom": "x18za50f",
          $$css: !0,
        },
        windowsTopOffset: { "::before_marginTop": "x884x28", $$css: !0 },
      },
      x = {
        base: { fontStretch: "x14g2gp5", lineHeight: "x1cfjsnv", $$css: !0 },
        defaultBaseLineAdjustment: { paddingBottom: "x1rkglvj", $$css: !0 },
        defaultBottomOffset: { "::after_marginBottom": "x18kbyci", $$css: !0 },
        defaultMultilineBottomOffset: {
          "::after_marginBottom": "x92v787",
          $$css: !0,
        },
        defaultTopOffset: { "::before_marginTop": "x7fk0ls", $$css: !0 },
        denseMode: {
          fontSize: "xtmr4r",
          fontWeight: "xhrkdi5",
          lineHeight: "x6p9lco",
          $$css: !0,
        },
        letterSpacing: { letterSpacing: "xxls8um", $$css: !0 },
        macGeckoBaseLineAdjustment: { paddingBottom: "xldx9it", $$css: !0 },
        macGeckoBottomOffset: { "::after_marginBottom": "xrdi12a", $$css: !0 },
        macGeckoMultilineBottomOffset: {
          "::after_marginBottom": "x9ks1qg",
          $$css: !0,
        },
        macGeckoTopOffset: { "::before_marginTop": "x1al22lp", $$css: !0 },
        macWebkitBaseLineAdjustment: { paddingBottom: "x1ullsbb", $$css: !0 },
        macWebkitBottomOffset: { "::after_marginBottom": "xt47ex1", $$css: !0 },
        macWebkitMultilineBottomOffset: {
          "::after_marginBottom": "x13kzq40",
          $$css: !0,
        },
        macWebkitTopOffset: { "::before_marginTop": "x7t6ow5", $$css: !0 },
        root: { fontSize: "x1ntzsbt", fontWeight: "xok3b82", $$css: !0 },
        textStyleApple: { fontFamily: "x12lr58p", $$css: !0 },
        textStyleDefault: { fontFamily: "xk9tapt", $$css: !0 },
        textStyleWindows: { fontFamily: "x132gq93", $$css: !0 },
        textTransform: { textTransform: "xz9nc9h", $$css: !0 },
        windowsBaseLineAdjustment: { paddingBottom: "xv5hg7k", $$css: !0 },
        windowsBottomOffset: { "::after_marginBottom": "x1oj2g4j", $$css: !0 },
        windowsMultilineBottomOffset: {
          "::after_marginBottom": "xz2l9cv",
          $$css: !0,
        },
        windowsTopOffset: { "::before_marginTop": "x1aq7fg9", $$css: !0 },
      },
      $ = {
        base: { fontStretch: "x14g2gp5", lineHeight: "xpk8gty", $$css: !0 },
        defaultBaseLineAdjustment: { paddingBottom: "xqum6pr", $$css: !0 },
        defaultBottomOffset: { "::after_marginBottom": "x1palhoc", $$css: !0 },
        defaultMultilineBottomOffset: {
          "::after_marginBottom": "xzscaun",
          $$css: !0,
        },
        defaultTopOffset: { "::before_marginTop": "xf67qmf", $$css: !0 },
        denseMode: {
          fontSize: "x13sgls2",
          fontWeight: "x1qzbmar",
          lineHeight: "x1afewz9",
          $$css: !0,
        },
        letterSpacing: { letterSpacing: "xhxhvje", $$css: !0 },
        macGeckoBaseLineAdjustment: { paddingBottom: "xaxqgx0", $$css: !0 },
        macGeckoBottomOffset: { "::after_marginBottom": "x5zed6t", $$css: !0 },
        macGeckoMultilineBottomOffset: {
          "::after_marginBottom": "xfcg1p5",
          $$css: !0,
        },
        macGeckoTopOffset: { "::before_marginTop": "x1q40msd", $$css: !0 },
        macWebkitBaseLineAdjustment: { paddingBottom: "x1hcjvws", $$css: !0 },
        macWebkitBottomOffset: { "::after_marginBottom": "xuznr5d", $$css: !0 },
        macWebkitMultilineBottomOffset: {
          "::after_marginBottom": "x2i20i9",
          $$css: !0,
        },
        macWebkitTopOffset: { "::before_marginTop": "x1mk0ado", $$css: !0 },
        root: { fontSize: "xvixa1k", fontWeight: "x17d5fs5", $$css: !0 },
        textStyleApple: { fontFamily: "xzi8ry5", $$css: !0 },
        textStyleDefault: { fontFamily: "xqoeak5", $$css: !0 },
        textStyleWindows: { fontFamily: "x1khacsk", $$css: !0 },
        textTransform: { textTransform: "x11reowv", $$css: !0 },
        windowsBaseLineAdjustment: { paddingBottom: "x4wj09n", $$css: !0 },
        windowsBottomOffset: { "::after_marginBottom": "xd4gl61", $$css: !0 },
        windowsMultilineBottomOffset: {
          "::after_marginBottom": "x1c5dfv1",
          $$css: !0,
        },
        windowsTopOffset: { "::before_marginTop": "xm8qljs", $$css: !0 },
      },
      P = {
        base: { fontStretch: "x14g2gp5", lineHeight: "x1mmz377", $$css: !0 },
        defaultBaseLineAdjustment: { paddingBottom: "xy28k5f", $$css: !0 },
        defaultBottomOffset: { "::after_marginBottom": "x1glpxfl", $$css: !0 },
        defaultMultilineBottomOffset: {
          "::after_marginBottom": "x117z09e",
          $$css: !0,
        },
        defaultTopOffset: { "::before_marginTop": "x1ct1ubm", $$css: !0 },
        denseMode: {
          fontSize: "x16uvtji",
          fontWeight: "x1e3qdqd",
          lineHeight: "xd9u3k2",
          $$css: !0,
        },
        letterSpacing: { letterSpacing: "x323f1x", $$css: !0 },
        macGeckoBaseLineAdjustment: { paddingBottom: "x7v1vlr", $$css: !0 },
        macGeckoBottomOffset: { "::after_marginBottom": "x17p3qun", $$css: !0 },
        macGeckoMultilineBottomOffset: {
          "::after_marginBottom": "xcjni6q",
          $$css: !0,
        },
        macGeckoTopOffset: { "::before_marginTop": "x1nm7po3", $$css: !0 },
        macWebkitBaseLineAdjustment: { paddingBottom: "x1xfr7j2", $$css: !0 },
        macWebkitBottomOffset: { "::after_marginBottom": "x20s5sb", $$css: !0 },
        macWebkitMultilineBottomOffset: {
          "::after_marginBottom": "x1nqirrv",
          $$css: !0,
        },
        macWebkitTopOffset: { "::before_marginTop": "xc3dxt1", $$css: !0 },
        root: { fontSize: "x3jb5of", fontWeight: "x1x49jmd", $$css: !0 },
        textStyleApple: { fontFamily: "x1mkw76z", $$css: !0 },
        textStyleDefault: { fontFamily: "x1sjlma", $$css: !0 },
        textStyleWindows: { fontFamily: "x1foc67u", $$css: !0 },
        textTransform: { textTransform: "xpsmx9o", $$css: !0 },
        windowsBaseLineAdjustment: { paddingBottom: "x1aymjmv", $$css: !0 },
        windowsBottomOffset: { "::after_marginBottom": "x1b4jfr3", $$css: !0 },
        windowsMultilineBottomOffset: {
          "::after_marginBottom": "x96u5mc",
          $$css: !0,
        },
        windowsTopOffset: { "::before_marginTop": "x1kboiy0", $$css: !0 },
      },
      N = {
        base: { fontStretch: "x14g2gp5", lineHeight: "x10ps884", $$css: !0 },
        defaultBaseLineAdjustment: { paddingBottom: "x14fvla8", $$css: !0 },
        defaultBottomOffset: { "::after_marginBottom": "x14d2c8j", $$css: !0 },
        defaultMultilineBottomOffset: {
          "::after_marginBottom": "x17lmviu",
          $$css: !0,
        },
        defaultTopOffset: { "::before_marginTop": "x1ea0d2s", $$css: !0 },
        denseMode: {
          fontSize: "xmyy8l9",
          fontWeight: "x13d9wvd",
          lineHeight: "x16e53c3",
          $$css: !0,
        },
        letterSpacing: { letterSpacing: "x1x63gub", $$css: !0 },
        macGeckoBaseLineAdjustment: { paddingBottom: "xrp7xkf", $$css: !0 },
        macGeckoBottomOffset: { "::after_marginBottom": "x10jqere", $$css: !0 },
        macGeckoMultilineBottomOffset: {
          "::after_marginBottom": "x2yxhcm",
          $$css: !0,
        },
        macGeckoTopOffset: { "::before_marginTop": "x176nwhi", $$css: !0 },
        macWebkitBaseLineAdjustment: { paddingBottom: "x8xeo7b", $$css: !0 },
        macWebkitBottomOffset: { "::after_marginBottom": "xlh2lg6", $$css: !0 },
        macWebkitMultilineBottomOffset: {
          "::after_marginBottom": "x5l0vmf",
          $$css: !0,
        },
        macWebkitTopOffset: { "::before_marginTop": "x1tbeequ", $$css: !0 },
        root: { fontSize: "xul1aqh", fontWeight: "x1jfkw1j", $$css: !0 },
        textStyleApple: { fontFamily: "xywkf5", $$css: !0 },
        textStyleDefault: { fontFamily: "x36kb77", $$css: !0 },
        textStyleWindows: { fontFamily: "x1z0arlu", $$css: !0 },
        textTransform: { textTransform: "x1cfgcnx", $$css: !0 },
        windowsBaseLineAdjustment: { paddingBottom: "xpp9ksn", $$css: !0 },
        windowsBottomOffset: { "::after_marginBottom": "x1fyzprv", $$css: !0 },
        windowsMultilineBottomOffset: {
          "::after_marginBottom": "xl3piw3",
          $$css: !0,
        },
        windowsTopOffset: { "::before_marginTop": "x10atjdy", $$css: !0 },
      },
      M = { xstyleConfig: e },
      w = { xstyleConfig: s },
      A = { xstyleConfig: u },
      F = { xstyleConfig: c },
      O = { xstyleConfig: d },
      B = { xstyleConfig: m },
      W = { xstyleConfig: p },
      q = { xstyleConfig: _ },
      U = { xstyleConfig: f },
      V = { xstyleConfig: g },
      H = { xstyleConfig: h },
      G = { xstyleConfig: y },
      z = { xstyleConfig: C },
      j = { xstyleConfig: b },
      K = { xstyleConfig: v },
      Q = { xstyleConfig: S },
      X = { xstyleConfig: R },
      Y = { xstyleConfig: L },
      J = { xstyleConfig: E },
      Z = { xstyleConfig: k },
      ee = { xstyleConfig: I },
      te = { xstyleConfig: T },
      ne = { xstyleConfig: D },
      re = { xstyleConfig: x },
      oe = { xstyleConfig: $ },
      ae = { xstyleConfig: P },
      ie = { xstyleConfig: N };
    ((l.body1 = M),
      (l.body2 = w),
      (l.body3 = A),
      (l.body4 = F),
      (l.bodyLink1 = O),
      (l.bodyLink2 = B),
      (l.bodyLink3 = W),
      (l.bodyLink4 = q),
      (l.button1 = U),
      (l.button2 = V),
      (l.entityHeaderHeadline1 = H),
      (l.entityHeaderHeadline2 = G),
      (l.entityHeaderMeta1 = z),
      (l.entityHeaderMeta2 = j),
      (l.entityHeaderMeta3 = K),
      (l.headline3 = Q),
      (l.headline4 = X),
      (l.headlineEmphasized1 = Y),
      (l.headlineEmphasized2 = J),
      (l.headlineEmphasized3 = Z),
      (l.headlineEmphasized4 = ee),
      (l.headlineEmphasized5 = te),
      (l.meta1 = ne),
      (l.meta2 = re),
      (l.meta3 = oe),
      (l.meta4 = ae),
      (l.title1 = ie));
  },
  98,
);
