__d(
  "IXTFlowStateContext",
  ["react"],
  function (t, n, r, o, a, i, l) {
    "use strict";
    var e,
      s = e || (e = o("react")),
      u = e.useState,
      c = {
        business_id: "",
        bv_legal_name_for_idv: "",
        bv_submission_id: null,
        bv_wizard_advertiser_verification_phone_input: {
          countryCode: null,
          phoneNumber: null,
        },
        bv_wizard_are_more_vendors_available: !1,
        bv_wizard_auth_agency_name: "",
        bv_wizard_auth_number: "",
        bv_wizard_business_details_address_form: null,
        bv_wizard_business_details_contact_form: null,
        bv_wizard_business_details_form: null,
        bv_wizard_business_details_name_and_taxid_form: null,
        bv_wizard_business_record_candidates: [],
        bv_wizard_business_selection: null,
        bv_wizard_business_selection_screen_selected_option: null,
        bv_wizard_challenge_method: null,
        bv_wizard_challenge_selection: null,
        bv_wizard_challenge_selection_idx: 0,
        bv_wizard_confirm_business_form: null,
        bv_wizard_country_code: null,
        bv_wizard_credit_line_details_form: null,
        bv_wizard_current_tdp_execution_seq_num: 0,
        bv_wizard_is_captcha_passed: !1,
        bv_wizard_manual_review_files: {},
        bv_wizard_simplified_business_details_form: null,
        bv_wizard_state_management: {},
        bv_wizard_tax_id: null,
        bv_wizard_verification_option_selection: null,
        config_type: "",
        country_code: "",
        cpo_wizard_us_organization_type: null,
        disclaimerLabelTextOption: "PAID_FOR_BY",
        email: "",
        fecID: "",
        fev_wizard_freeform_org_info: {
          addressLine1: "",
          addressLine2: "",
          agentName: "",
          city: "",
          cnpj: "",
          committeeId: "",
          corporatePurpose: "",
          directorName: "",
          email: "",
          gst: "",
          orgName: "",
          phoneNumber: "",
          pointOfContact: "",
          postalCode: "",
          promoterName: "",
          region: "",
          state: "",
          treasurerName: "",
          website: "",
        },
        fev_wizard_gov_form: {
          addressLine1: "",
          addressLine2: "",
          city: "",
          email: "",
          organizationName: "",
          phoneNumber: "",
          postalCode: "",
          state: "",
          website: "",
        },
        fev_wizard_page_name_org_info: {
          addressLine1: "",
          addressLine2: "",
          agentName: "",
          city: "",
          cnpj: "",
          committeeId: "",
          corporatePurpose: "",
          directorName: "",
          email: "",
          gst: "",
          phoneNumber: "",
          pointOfContact: "",
          postalCode: "",
          promoterName: "",
          region: "",
          state: "",
          treasurerName: "",
        },
        fev_wizard_row_method: null,
        fev_wizard_tax_org_form: null,
        fev_wizard_tax_org_manual_review_files: null,
        fev_wizard_tax_org_record_selection: null,
        fev_wizard_us_method: null,
        fevWizardHasMCMCUpload: !1,
        fox_wizard_business_name: "",
        fox_wizard_business_type: null,
        fox_wizard_is_drug_labeler: null,
        fox_wizard_selected_ad_accounts: null,
        fox_wizard_verification_method: null,
        mv4b_legal_name: "",
        mv4b_user_phone: "",
        payer: "myself",
        rmg_info: {
          actingOnBehalfOf: null,
          advertiserActivity: null,
          applicationType: null,
          businessName: null,
          country_code: null,
          platformType: null,
          protective_measures: null,
          region_specific_gambling_types: null,
          requires_aggregator_license: null,
          requires_gambling_license: null,
          selectedAdAccounts: null,
          websites: null,
        },
        specialized_ads_addendum_accepted: !1,
        specialized_ads_addendum_viewed: !1,
        standalone_email_input: "",
        standalone_otp_sms_input: { countryCode: null, phoneNumber: null },
        website: "",
      };
    function d() {
      for (var e = Object.keys(c), t = {}, n = 0; n < e.length; n++) {
        var r = u(c[e[n]]);
        t[e[n]] = r;
      }
      return t;
    }
    var m = Object.keys(c).reduce(function (e, t) {
        return ((e[t] = [c[t], function () {}]), e);
      }, {}),
      p = s.createContext(m);
    ((l.useIXTFlowState = d), (l.IXTFlowStateContext = p));
  },
  98,
);
