__d(
  "KTWasm.pb",
  ["WAProtoConst"],
  function (t, n, r, o, a, i, l) {
    var e,
      s = {},
      u = {},
      c = {},
      d = {},
      m = {},
      p = {},
      _ = {};
    ((s.name = "KeyTransparencyCommand"),
      (s.internalSpec = {
        verifyKtForUserSignal: [5, (e = o("WAProtoConst")).TYPES.MESSAGE, u],
        verifyKtForUserMinos: [6, e.TYPES.MESSAGE, d],
        verifyKtForUserMandrake: [7, e.TYPES.MESSAGE, p],
        __oneofs__: {
          commandInput: [
            "verifyKtForUserSignal",
            "verifyKtForUserMinos",
            "verifyKtForUserMandrake",
          ],
        },
      }),
      (u.name = "VerifyKeyTransparencyForUserSignalCommand"),
      (u.internalSpec = {
        rootHash: [1, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        currentEpoch: [2, e.FLAGS.REQUIRED | e.TYPES.UINT64],
        userFbid: [3, e.FLAGS.REQUIRED | e.TYPES.INT64],
        historyProof: [4, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        metaSignature: [5, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        cloudflareSignature: [6, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        cloudflareMessage: [7, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        cloudflarePubKey: [8, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        auditorSignatureTtlSecs: [9, e.FLAGS.REQUIRED | e.TYPES.UINT64],
        local_device_keys: [10, e.TYPES.MAP, [e.TYPES.UINT64, e.TYPES.BYTES]],
      }),
      (c.name = "VerifyKeyTransparencyForUserSignalResult"),
      (c.internalSpec = {
        success: [1, e.TYPES.BOOL],
        error: [2, e.TYPES.STRING],
      }),
      (d.name = "VerifyKeyTransparencyForUserMinosCommand"),
      (d.internalSpec = {
        lookupResponse: [1, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        userFbid: [2, e.FLAGS.REQUIRED | e.TYPES.INT64],
        auditorSignatureTtlSecs: [3, e.FLAGS.REQUIRED | e.TYPES.UINT64],
        requestedAuditorList: [4, e.FLAGS.REPEATED | e.TYPES.STRING],
        isProductionBuild: [5, e.FLAGS.REQUIRED | e.TYPES.BOOL],
        localEpochHead: [6, e.FLAGS.REQUIRED | e.TYPES.BYTES],
      }),
      (m.name = "VerifyKeyTransparencyForUserMinosResult"),
      (m.internalSpec = {
        success: [1, e.TYPES.BOOL],
        error: [2, e.TYPES.STRING],
      }),
      (p.name = "VerifyKeyTransparencyForUserMandrakeCommand"),
      (p.internalSpec = {
        lookupResponse: [1, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        userFbid: [2, e.FLAGS.REQUIRED | e.TYPES.INT64],
        auditorSignatureTtlSecs: [3, e.FLAGS.REQUIRED | e.TYPES.UINT64],
        requestedAuditorList: [4, e.FLAGS.REPEATED | e.TYPES.STRING],
        isProductionBuild: [5, e.FLAGS.REQUIRED | e.TYPES.BOOL],
        localMailboxHead: [6, e.FLAGS.REQUIRED | e.TYPES.BYTES],
      }),
      (_.name = "VerifyKeyTransparencyForUserMandrakeResult"),
      (_.internalSpec = {
        success: [1, e.TYPES.BOOL],
        error: [2, e.TYPES.STRING],
      }),
      (l.KeyTransparencyCommandSpec = s),
      (l.VerifyKeyTransparencyForUserSignalCommandSpec = u),
      (l.VerifyKeyTransparencyForUserSignalResultSpec = c),
      (l.VerifyKeyTransparencyForUserMinosCommandSpec = d),
      (l.VerifyKeyTransparencyForUserMinosResultSpec = m),
      (l.VerifyKeyTransparencyForUserMandrakeCommandSpec = p),
      (l.VerifyKeyTransparencyForUserMandrakeResultSpec = _));
  },
  98,
);
