__d(
  "L1LiveTrueTieredReverseInteropStoreSourceTier2ServerQuery.graphql",
  ["Adgroup-ad_object_spec-tier2-resolver"],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = (function () {
      var e = {
          defaultValue: !0,
          kind: "LocalArgument",
          name: "fetch_instagram_field",
        },
        t = { defaultValue: null, kind: "LocalArgument", name: "ids" },
        r = [{ kind: "Variable", name: "ids", variableName: "ids" }],
        o = {
          alias: "node_id",
          args: null,
          kind: "ScalarField",
          name: "id",
          storageKey: null,
        },
        a = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "__typename",
          storageKey: null,
        },
        i = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "id",
          storageKey: null,
        },
        l = [
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "disapproval_reason",
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "raw_reason",
            storageKey: null,
          },
        ],
        s = [
          {
            name: "conversion_action_query_spec",
            args: null,
            fragment: {
              kind: "InlineFragment",
              selections: [
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "action_type_names",
                  storageKey: null,
                },
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "application_ids",
                  storageKey: null,
                },
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "conversion_id",
                  storageKey: null,
                },
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "creative_ids",
                  storageKey: null,
                },
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "custom_conversion",
                  storageKey: null,
                },
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "consolidated_datasets",
                  storageKey: null,
                },
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "dataset_split",
                  storageKey: null,
                },
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "event",
                  storageKey: null,
                },
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "event_creator",
                  storageKey: null,
                },
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "event_type",
                  storageKey: null,
                },
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "fb_pixel_ids",
                  storageKey: null,
                },
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "fb_pixel_event",
                  storageKey: null,
                },
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "leadgen_ids",
                  storageKey: null,
                },
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "object",
                  storageKey: null,
                },
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "object_domain",
                  storageKey: null,
                },
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "offer",
                  storageKey: null,
                },
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "offer_creator",
                  storageKey: null,
                },
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "offsite_pixel",
                  storageKey: null,
                },
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "page",
                  storageKey: null,
                },
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "page_parent",
                  storageKey: null,
                },
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "partner_account_link",
                  storageKey: null,
                },
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "post",
                  storageKey: null,
                },
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "post_object",
                  storageKey: null,
                },
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "post_object_wall",
                  storageKey: null,
                },
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "post_wall",
                  storageKey: null,
                },
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "product_set",
                  storageKey: null,
                },
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "question",
                  storageKey: null,
                },
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "question_creator",
                  storageKey: null,
                },
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "responses",
                  storageKey: null,
                },
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "subtypes",
                  storageKey: null,
                },
              ],
              type: "ConversionActionQuery",
              abstractKey: null,
            },
            kind: "RelayResolver",
            storageKey: null,
            isOutputType: !0,
          },
        ];
      return {
        fragment: {
          argumentDefinitions: [e, t],
          kind: "Fragment",
          metadata: null,
          name: "L1LiveTrueTieredReverseInteropStoreSourceTier2ServerQuery",
          selections: [
            {
              alias: null,
              args: r,
              concreteType: null,
              kind: "LinkedField",
              name: "nodes",
              plural: !0,
              selections: [
                {
                  kind: "InlineDataFragmentSpread",
                  name: "L1LiveThreeTiersReverseInteropStoreSourceNodeFragment",
                  selections: [o, a],
                  args: null,
                  argumentDefinitions: [],
                },
                {
                  kind: "InlineFragment",
                  selections: [
                    i,
                    {
                      alias: null,
                      args: [],
                      fragment: {
                        args: [
                          {
                            kind: "Variable",
                            name: "fetch_instagram_field",
                            variableName: "fetch_instagram_field",
                          },
                        ],
                        kind: "FragmentSpread",
                        name: "AdgroupAdObjectSpecTier2Resolver",
                      },
                      kind: "RelayResolver",
                      name: "adgroup_spec_tier2",
                      resolverModule: n("Adgroup-ad_object_spec-tier2-resolver")
                        .adgroup_spec_tier2,
                      path: "nodes.adgroup_spec_tier2",
                    },
                  ],
                  type: "Adgroup",
                  abstractKey: null,
                },
              ],
              storageKey: null,
            },
          ],
          type: "Query",
          abstractKey: null,
        },
        kind: "Request",
        operation: {
          argumentDefinitions: [t, e],
          kind: "Operation",
          name: "L1LiveTrueTieredReverseInteropStoreSourceTier2ServerQuery",
          selections: [
            {
              alias: null,
              args: r,
              concreteType: null,
              kind: "LinkedField",
              name: "nodes",
              plural: !0,
              selections: [
                a,
                { kind: "TypeDiscriminator", abstractKey: "__isNode" },
                o,
                i,
                {
                  kind: "InlineFragment",
                  selections: [
                    {
                      name: "adgroup_spec_tier2",
                      args: null,
                      fragment: {
                        kind: "InlineFragment",
                        selections: [
                          a,
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "ad_active_time",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "ad_campaign_id",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "ad_campaign_name",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "ad_schedule_end_time",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "ad_schedule_start_time",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "bid_amount_value",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            concreteType: "AdBidInfo",
                            kind: "LinkedField",
                            name: "bid_info",
                            plural: !0,
                            selections: [
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "amount",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "objective",
                                storageKey: null,
                              },
                            ],
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "bid_type",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "biz_ai_enabled_state",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "conversion_domain",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "created_time_with_timezone",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            concreteType: "AdCreativeAudiencePairingPersona",
                            kind: "LinkedField",
                            name: "creative_audience_pairing_persona",
                            plural: !1,
                            selections: [
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "age_min",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "age_max",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "genders",
                                storageKey: null,
                              },
                            ],
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "creative_link_url",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "demo_link_hash",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "display_sequence",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "effective_instagram_media_id",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "effective_instagram_story_id",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "engagement_audience",
                            storageKey: null,
                          },
                          i,
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "include_in_ad_study_id",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "is_eligible_for_message_editing",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "is_eligible_for_post_editing",
                            storageKey: null,
                          },
                          {
                            condition: "fetch_instagram_field",
                            kind: "Condition",
                            passingValue: !0,
                            selections: [
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "instagram_permalink_url",
                                storageKey: null,
                              },
                            ],
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "meta_reward_adgroup_status",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            concreteType: "XFBAdgroupMetadata",
                            kind: "LinkedField",
                            name: "metadata",
                            plural: !1,
                            selections: [
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "ad_standard_enhancements_edit_source",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "adgroup_media_source",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "adgroup_creation_source",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "carousel_style",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "carousel_with_static_card_style",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "is_pca_unified_format_ad",
                                storageKey: null,
                              },
                              i,
                            ],
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            concreteType: "XFBAdsNamingTemplateConditions",
                            kind: "LinkedField",
                            name: "naming_template_custom_fields",
                            plural: !0,
                            selections: [
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "key",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "value",
                                storageKey: null,
                              },
                            ],
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            concreteType: "AdgroupReviewFeedback",
                            kind: "LinkedField",
                            name: "new_review_feedback",
                            plural: !1,
                            selections: [
                              {
                                alias: null,
                                args: null,
                                concreteType: "ReviewFeedback",
                                kind: "LinkedField",
                                name: "global_feedback",
                                plural: !0,
                                selections: l,
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                concreteType: "PlacementSpecificReviewFeedback",
                                kind: "LinkedField",
                                name: "placement_specific_feedback",
                                plural: !0,
                                selections: [
                                  {
                                    alias: null,
                                    args: null,
                                    kind: "ScalarField",
                                    name: "review_placement",
                                    storageKey: null,
                                  },
                                  {
                                    alias: null,
                                    args: null,
                                    concreteType: "ReviewFeedback",
                                    kind: "LinkedField",
                                    name: "review_feedback",
                                    plural: !0,
                                    selections: l,
                                    storageKey: null,
                                  },
                                ],
                                storageKey: null,
                              },
                            ],
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            concreteType: "ConversionActionQuery",
                            kind: "LinkedField",
                            name: "optimization_specs",
                            plural: !0,
                            selections: s,
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            concreteType: "XFBAdsPlacementConfigSpec",
                            kind: "LinkedField",
                            name: "placement",
                            plural: !1,
                            selections: [
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "facebook_positions",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "oculus_positions",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "instagram_positions",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "audience_network_positions",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "messenger_positions",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "whatsapp_positions",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "threads_positions",
                                storageKey: null,
                              },
                            ],
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "priority",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "related_media_user_opted_out",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "shops_ads_metadata_tags",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            concreteType: null,
                            kind: "LinkedField",
                            name: "source_adgroup",
                            plural: !1,
                            selections: [a, i],
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            concreteType: "Application",
                            kind: "LinkedField",
                            name: "source_app",
                            plural: !1,
                            selections: [i],
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            concreteType: "TrackingAndConversionWithDefaults",
                            kind: "LinkedField",
                            name: "tracking_and_conversion_with_defaults",
                            plural: !1,
                            selections: [
                              {
                                alias: null,
                                args: null,
                                concreteType: "ConversionActionQuery",
                                kind: "LinkedField",
                                name: "custom_conversion",
                                plural: !0,
                                selections: s,
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                concreteType: "ConversionActionQuery",
                                kind: "LinkedField",
                                name: "custom_tracking",
                                plural: !0,
                                selections: s,
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                concreteType: "ConversionActionQuery",
                                kind: "LinkedField",
                                name: "default_conversion",
                                plural: !0,
                                selections: s,
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                concreteType: "ConversionActionQuery",
                                kind: "LinkedField",
                                name: "default_tracking",
                                plural: !0,
                                selections: s,
                                storageKey: null,
                              },
                            ],
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            concreteType: "ConversionActionQuery",
                            kind: "LinkedField",
                            name: "tracking_specs",
                            plural: !0,
                            selections: s,
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "updated_time_with_timezone",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "uca_draft_version",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "view_tags",
                            storageKey: null,
                          },
                        ],
                        type: "Adgroup",
                        abstractKey: null,
                      },
                      kind: "RelayResolver",
                      storageKey: null,
                      isOutputType: !0,
                    },
                  ],
                  type: "Adgroup",
                  abstractKey: null,
                },
              ],
              storageKey: null,
            },
          ],
        },
        params: {
          id: "27680636624958910",
          metadata: {},
          name: "L1LiveTrueTieredReverseInteropStoreSourceTier2ServerQuery",
          operationKind: "query",
          text: null,
        },
      };
    })();
    a.exports = e;
  },
  null,
);
