__d(
  "LSDeleteThenInsertThread",
  [],
  function (t, n, r, o, a, i) {
    function e() {
      var e = arguments,
        t = e[e.length - 1],
        n = [],
        r = [];
      return t.sequence([
        function (r) {
          return t.db
            .table(9)
            .fetch([[[e[7]]]])
            .next()
            .then(function (r, o) {
              var a,
                i,
                l = r.done,
                s = r.value;
              return l
                ? t.db
                    .table(9)
                    .put({
                      threadKey: e[7],
                      lastReadWatermarkTimestampMs: e[1],
                      authorityLevel: e[6],
                      mailboxType: e[8],
                      threadType: e[9],
                      folderName: e[10],
                      ongoingCallState: e[29],
                      parentThreadKey: e[35],
                      lastActivityTimestampMs: e[0],
                      snippet: e[2],
                      threadName: e[3],
                      threadPictureUrl: e[4],
                      needsAdminApprovalForNewParticipant: e[5],
                      threadPictureUrlFallback: e[11],
                      threadPictureUrlExpirationTimestampMs: e[12],
                      removeWatermarkTimestampMs: e[13],
                      muteExpireTimeMs: e[14],
                      muteCallsExpireTimeMs: e[15],
                      groupNotificationSettings: e[16],
                      isAdminSnippet: e[17],
                      snippetSenderContactId: e[18],
                      snippetText: e[20],
                      snippetStringHash: e[21],
                      snippetStringArgument1: e[22],
                      snippetAttribution: e[23],
                      snippetAttributionStringHash: e[24],
                      disappearingSettingTtl: e[25],
                      disappearingSettingUpdatedTs: e[26],
                      disappearingSettingUpdatedBy: e[27],
                      cannotReplyReason: e[30],
                      customEmoji: e[31],
                      customEmojiImageUrl: e[32],
                      outgoingBubbleColor: e[33],
                      themeFbid: e[34],
                      nullstateDescriptionText1: e[36],
                      nullstateDescriptionType1: e[37],
                      nullstateDescriptionText2: e[38],
                      nullstateDescriptionType2: e[39],
                      nullstateDescriptionText3: e[40],
                      nullstateDescriptionType3: e[41],
                      snippetHasEmoji: e[42],
                      hasPersistentMenu: e[43],
                      disableComposerInput: e[44],
                      cannotUnsendReason: e[45],
                      viewedPluginKey: e[46],
                      viewedPluginContext: e[47],
                      clientThreadKey: e[48],
                      capabilities: e[49],
                      shouldRoundThreadPicture: e[50],
                      proactiveWarningDismissTime: e[51],
                      isCustomThreadPicture: e[52],
                      otidOfFirstMessage: e[53],
                      normalizedSearchTerms: e[54],
                      additionalThreadContext: e[55],
                      disappearingThreadKey: e[56],
                      isDisappearingMode: e[57],
                      disappearingModeInitiator: e[58],
                      unreadDisappearingMessageCount: e[59],
                      lastMessageCtaId: e[61],
                      lastMessageCtaType: e[62],
                      consistentThreadFbid: e[63],
                      threadDescription: e[64],
                      unsendLimitMs: e[65],
                      syncGroup: e[66],
                      threadInvitesEnabled: e[67],
                      threadInviteLink: e[68],
                      numUnreadSubthreads: e[69],
                      subthreadCount: e[70],
                      threadInvitesEnabledV2: e[71],
                      joinRequestApprovalSetting: e[72],
                      pendingJoinRequestsCount: e[73],
                      eventStartTimestampMs: e[74],
                      eventEndTimestampMs: e[75],
                      takedownState: e[76],
                      memberCount: e[77],
                      admodCount: e[78],
                      secondaryParentThreadKey: e[79],
                      igFolder: e[80],
                      inviterId: e[81],
                      threadTags: e[82],
                      readReceiptsDisabledV2: e[83],
                      threadStatus: e[84],
                      threadSubtype: e[85],
                      pauseThreadTimestamp: e[86],
                      metadata: e[87],
                      syncSource: e[88],
                      unreadMessageCount: e[89],
                    })
                : ((o = s.item),
                  (n[1] = o.lastActivityTimestampMs),
                  (n[3] = o.parentThreadKey),
                  (n[2] = o.disappearingThreadKey),
                  (n[4] = o.isDisappearingMode),
                  t.i64.le(o.authorityLevel, e[6])
                    ? t.i64.gt(n[1], e[0]) && t.i64.neq(n[2], void 0)
                      ? (t.i64.eq(e[35], t.i64.cast([-1, 4294967286])) &&
                        t.i64.eq(n[3], t.i64.cast([0, 0]))
                          ? ((a = [n[3], o.folderName]),
                            (n[5] = a[0]),
                            (n[6] = a[1]))
                          : ((i = [e[35], e[10]]),
                            (n[5] = i[0]),
                            (n[6] = i[1])),
                        t.db
                          .table(9)
                          .put({
                            threadKey: e[7],
                            lastReadWatermarkTimestampMs:
                              o.lastReadWatermarkTimestampMs,
                            authorityLevel: e[6],
                            mailboxType: e[8],
                            threadType: e[9],
                            folderName: n[6],
                            ongoingCallState: e[29],
                            parentThreadKey: n[5],
                            lastActivityTimestampMs: n[1],
                            snippet: e[2],
                            threadName: e[3],
                            threadPictureUrl: e[4],
                            needsAdminApprovalForNewParticipant: e[5],
                            threadPictureUrlFallback: e[11],
                            threadPictureUrlExpirationTimestampMs: e[12],
                            removeWatermarkTimestampMs: e[13],
                            muteExpireTimeMs: e[14],
                            muteCallsExpireTimeMs: e[15],
                            groupNotificationSettings: e[16],
                            isAdminSnippet: e[17],
                            snippetSenderContactId: e[18],
                            snippetText: e[20],
                            snippetStringHash: e[21],
                            snippetStringArgument1: e[22],
                            snippetAttribution: e[23],
                            snippetAttributionStringHash: e[24],
                            disappearingSettingTtl: e[25],
                            disappearingSettingUpdatedTs: e[26],
                            disappearingSettingUpdatedBy: e[27],
                            cannotReplyReason: e[30],
                            customEmoji: e[31],
                            customEmojiImageUrl: e[32],
                            outgoingBubbleColor: e[33],
                            themeFbid: e[34],
                            nullstateDescriptionText1: e[36],
                            nullstateDescriptionType1: e[37],
                            nullstateDescriptionText2: e[38],
                            nullstateDescriptionType2: e[39],
                            nullstateDescriptionText3: e[40],
                            nullstateDescriptionType3: e[41],
                            snippetHasEmoji: e[42],
                            hasPersistentMenu: e[43],
                            disableComposerInput: e[44],
                            cannotUnsendReason: e[45],
                            viewedPluginKey: e[46],
                            viewedPluginContext: e[47],
                            clientThreadKey: e[48],
                            capabilities: e[49],
                            shouldRoundThreadPicture: e[50],
                            proactiveWarningDismissTime: e[51],
                            isCustomThreadPicture: e[52],
                            otidOfFirstMessage: e[53],
                            normalizedSearchTerms: e[54],
                            additionalThreadContext: e[55],
                            disappearingThreadKey: n[2],
                            isDisappearingMode: n[4],
                            disappearingModeInitiator: e[58],
                            unreadDisappearingMessageCount: e[59],
                            lastMessageCtaId: e[61],
                            lastMessageCtaType: e[62],
                            consistentThreadFbid: e[63],
                            threadDescription: e[64],
                            unsendLimitMs: e[65],
                            syncGroup: e[66],
                            threadInvitesEnabled: e[67],
                            threadInviteLink: e[68],
                            numUnreadSubthreads: e[69],
                            subthreadCount: e[70],
                            threadInvitesEnabledV2: e[71],
                            joinRequestApprovalSetting: e[72],
                            pendingJoinRequestsCount: e[73],
                            eventStartTimestampMs: e[74],
                            eventEndTimestampMs: e[75],
                            takedownState: e[76],
                            memberCount: e[77],
                            admodCount: e[78],
                            secondaryParentThreadKey: e[79],
                            igFolder: e[80],
                            inviterId: e[81],
                            threadTags: e[82],
                            readReceiptsDisabledV2: e[83],
                            threadStatus: e[84],
                            threadSubtype: e[85],
                            pauseThreadTimestamp: e[86],
                            metadata: e[87],
                            syncSource: e[88],
                            unreadMessageCount: e[89],
                          }))
                      : t.db
                          .table(9)
                          .put({
                            threadKey: e[7],
                            lastReadWatermarkTimestampMs: e[1],
                            authorityLevel: e[6],
                            mailboxType: e[8],
                            threadType: e[9],
                            folderName: e[10],
                            ongoingCallState: e[29],
                            parentThreadKey: e[35],
                            lastActivityTimestampMs: e[0],
                            snippet: e[2],
                            threadName: e[3],
                            threadPictureUrl: e[4],
                            needsAdminApprovalForNewParticipant: e[5],
                            threadPictureUrlFallback: e[11],
                            threadPictureUrlExpirationTimestampMs: e[12],
                            removeWatermarkTimestampMs: e[13],
                            muteExpireTimeMs: e[14],
                            muteCallsExpireTimeMs: e[15],
                            groupNotificationSettings: e[16],
                            isAdminSnippet: e[17],
                            snippetSenderContactId: e[18],
                            snippetText: e[20],
                            snippetStringHash: e[21],
                            snippetStringArgument1: e[22],
                            snippetAttribution: e[23],
                            snippetAttributionStringHash: e[24],
                            disappearingSettingTtl: e[25],
                            disappearingSettingUpdatedTs: e[26],
                            disappearingSettingUpdatedBy: e[27],
                            cannotReplyReason: e[30],
                            customEmoji: e[31],
                            customEmojiImageUrl: e[32],
                            outgoingBubbleColor: e[33],
                            themeFbid: e[34],
                            nullstateDescriptionText1: e[36],
                            nullstateDescriptionType1: e[37],
                            nullstateDescriptionText2: e[38],
                            nullstateDescriptionType2: e[39],
                            nullstateDescriptionText3: e[40],
                            nullstateDescriptionType3: e[41],
                            snippetHasEmoji: e[42],
                            hasPersistentMenu: e[43],
                            disableComposerInput: e[44],
                            cannotUnsendReason: e[45],
                            viewedPluginKey: e[46],
                            viewedPluginContext: e[47],
                            clientThreadKey: e[48],
                            capabilities: e[49],
                            shouldRoundThreadPicture: e[50],
                            proactiveWarningDismissTime: e[51],
                            isCustomThreadPicture: e[52],
                            otidOfFirstMessage: e[53],
                            normalizedSearchTerms: e[54],
                            additionalThreadContext: e[55],
                            disappearingThreadKey: n[2],
                            isDisappearingMode: n[4],
                            disappearingModeInitiator: e[58],
                            unreadDisappearingMessageCount: e[59],
                            lastMessageCtaId: e[61],
                            lastMessageCtaType: e[62],
                            consistentThreadFbid: e[63],
                            threadDescription: e[64],
                            unsendLimitMs: e[65],
                            syncGroup: e[66],
                            threadInvitesEnabled: e[67],
                            threadInviteLink: e[68],
                            numUnreadSubthreads: e[69],
                            subthreadCount: e[70],
                            threadInvitesEnabledV2: e[71],
                            joinRequestApprovalSetting: e[72],
                            pendingJoinRequestsCount: e[73],
                            eventStartTimestampMs: e[74],
                            eventEndTimestampMs: e[75],
                            takedownState: e[76],
                            memberCount: e[77],
                            admodCount: e[78],
                            secondaryParentThreadKey: e[79],
                            igFolder: e[80],
                            inviterId: e[81],
                            threadTags: e[82],
                            readReceiptsDisabledV2: e[83],
                            threadStatus: e[84],
                            threadSubtype: e[85],
                            pauseThreadTimestamp: e[86],
                            metadata: e[87],
                            syncSource: e[88],
                            unreadMessageCount: e[89],
                          })
                    : t.resolve());
            });
        },
        function (e) {
          return t.resolve(r);
        },
      ]);
    }
    ((e.__sproc_name__ = "LSMailboxDeleteThenInsertThreadStoredProcedure"),
      (e.__tables__ = ["threads"]),
      (a.exports = e));
  },
  null,
);
