__d(
  "LSExpandedStaticDependencies",
  [
    "LSAddParticipantIdToGroupThread",
    "LSCheckAuthoritativeMessageExists",
    "LSClearPinnedMessages",
    "LSCompleteThreadCutover",
    "LSDeleteBanner",
    "LSDeleteBannersByIds",
    "LSDeleteExistingMessageRanges",
    "LSDeleteRowRichStatusCustomAudience",
    "LSDeleteThenInsertAvatarFeatureConfig",
    "LSDeleteThenInsertBotProfileInfoV2",
    "LSDeleteThenInsertCmChannelList",
    "LSDeleteThenInsertCommunityUnjoinedThread",
    "LSDeleteThenInsertRankingRequest",
    "LSDeleteThenInsertRankingScore",
    "LSFillDeanonCacheForE2EEThread",
    "LSGetFirstAvailableAttachmentCTAID",
    "LSHybridThreadDelete",
    "LSInsertAttachmentCta",
    "LSInsertAttachmentItem",
    "LSInsertBlobAttachment",
    "LSInsertNewMessageRange",
    "LSIssueFetchThreadCapabilitiesTask",
    "LSIssueInsertPersistentMenuItemsForThreadTask",
    "LSIssueNextSync",
    "LSMailboxTaskCompletionApiOnTaskCompletion",
    "LSMarkThreadReadV2",
    "LSReplaceOptimisticReaction",
    "LSSetForwardScore",
    "LSSetMessageDisplayedContentTypes",
    "LSStaticDependencies",
    "LSStoreProjectConfiguration",
    "LSSyncBumpThreadDataToClient",
    "LSTransportHybridParticipantUpdateReceipts",
    "LSTriggerReenrollementFromOptOutDelta",
    "LSTruncateMetadataThreads",
    "LSTruncateTablesForSyncGroup",
    "LSUpdateAttachmentItemCtaAtIndex",
    "LSUpdateCommunityThreadStaleState",
    "LSUpdateOrInsertCommunitySurfaceRange",
    "LSUpdateOrInsertOhaiGatewayKeyConfigs",
    "LSUpdateOrInsertThread",
    "LSUpdateReadReceipt",
    "LSUpdateThreadActivityStatus",
    "LSUpdateThreadAuthorityAndMappingWithOTIDFromJID",
    "LSUpdateThreadDisappearingSetting",
    "LSUpdateThreadNullState",
    "LSUpdateThreadsRangesV2",
    "LSUpsertContextualProfileV1",
    "LSUpsertFolderSeenTimestamp",
    "LSUpsertInboxThreadsRange",
    "LSUpsertMessage",
    "LSUpsertReaction",
    "LSUpsertSyncGroupThreadsRange",
    "LSVerifyAndSaveNewCredentials",
    "LSVerifyCommunityFolderExistsV2",
    "LSVerifyE2EEMetadataThreadExistsV2",
    "LSWriteThreadCapabilities",
  ],
  function (t, n, r, o, a, i, l) {
    "use strict";
    var e = babelHelpers.extends({}, r("LSStaticDependencies"), {
        LSVerifyCommunityFolderExistsV2: r("LSVerifyCommunityFolderExistsV2"),
        addParticipantIdToGroupThread: r("LSAddParticipantIdToGroupThread"),
        checkAuthoritativeMessageExists: r("LSCheckAuthoritativeMessageExists"),
        clearPinnedMessages: r("LSClearPinnedMessages"),
        completeThreadCutover: r("LSCompleteThreadCutover"),
        deleteBanner: r("LSDeleteBanner"),
        deleteBannersByIds: r("LSDeleteBannersByIds"),
        deleteExistingMessageRanges: r("LSDeleteExistingMessageRanges"),
        deleteRowRichStatusCustomAudience: r(
          "LSDeleteRowRichStatusCustomAudience",
        ),
        deleteThenInsertAvatarFeatureConfig: r(
          "LSDeleteThenInsertAvatarFeatureConfig",
        ),
        deleteThenInsertBotProfileInfoV2: r(
          "LSDeleteThenInsertBotProfileInfoV2",
        ),
        deleteThenInsertCmChannelList: r("LSDeleteThenInsertCmChannelList"),
        deleteThenInsertCommunityUnjoinedThread: r(
          "LSDeleteThenInsertCommunityUnjoinedThread",
        ),
        deleteThenInsertRankingRequest: r("LSDeleteThenInsertRankingRequest"),
        deleteThenInsertRankingScore: r("LSDeleteThenInsertRankingScore"),
        fillDeanonCacheForE2EEThread: r("LSFillDeanonCacheForE2EEThread"),
        getFirstAvailableAttachmentCTAID: r(
          "LSGetFirstAvailableAttachmentCTAID",
        ),
        hybridThreadDelete: r("LSHybridThreadDelete"),
        insertAttachmentCta: r("LSInsertAttachmentCta"),
        insertAttachmentItem: r("LSInsertAttachmentItem"),
        insertBlobAttachment: r("LSInsertBlobAttachment"),
        insertNewMessageRange: r("LSInsertNewMessageRange"),
        issueFetchThreadCapabilitiesTask: r(
          "LSIssueFetchThreadCapabilitiesTask",
        ),
        issueInsertPersistentMenuItemsForThreadTask: r(
          "LSIssueInsertPersistentMenuItemsForThreadTask",
        ),
        issueNextSync: r("LSIssueNextSync"),
        mailboxTaskCompletionApiOnTaskCompletion: r(
          "LSMailboxTaskCompletionApiOnTaskCompletion",
        ),
        markThreadReadV2: r("LSMarkThreadReadV2"),
        replaceOptimisticReaction: r("LSReplaceOptimisticReaction"),
        setForwardScore: r("LSSetForwardScore"),
        setMessageDisplayedContentTypes: r("LSSetMessageDisplayedContentTypes"),
        storeProjectConfiguration: r("LSStoreProjectConfiguration"),
        syncBumpThreadDataToClient: r("LSSyncBumpThreadDataToClient"),
        transportHybridParticipantUpdateReceipts: r(
          "LSTransportHybridParticipantUpdateReceipts",
        ),
        triggerReenrollementFromOptOutDelta: r(
          "LSTriggerReenrollementFromOptOutDelta",
        ),
        truncateMetadataThreads: r("LSTruncateMetadataThreads"),
        truncateTablesForSyncGroup: r("LSTruncateTablesForSyncGroup"),
        updateAttachmentItemCtaAtIndex: r("LSUpdateAttachmentItemCtaAtIndex"),
        updateCommunityThreadStaleState: r("LSUpdateCommunityThreadStaleState"),
        updateOrInsertCommunitySurfaceRange: r(
          "LSUpdateOrInsertCommunitySurfaceRange",
        ),
        updateOrInsertOhaiGatewayKeyConfigs: r(
          "LSUpdateOrInsertOhaiGatewayKeyConfigs",
        ),
        updateOrInsertThread: r("LSUpdateOrInsertThread"),
        updateReadReceipt: r("LSUpdateReadReceipt"),
        updateThreadActivityStatus: r("LSUpdateThreadActivityStatus"),
        updateThreadAuthorityAndMappingWithOTIDFromJID: r(
          "LSUpdateThreadAuthorityAndMappingWithOTIDFromJID",
        ),
        updateThreadDisappearingSetting: r("LSUpdateThreadDisappearingSetting"),
        updateThreadNullState: r("LSUpdateThreadNullState"),
        updateThreadsRangesV2: r("LSUpdateThreadsRangesV2"),
        upsertContextualProfileV1: r("LSUpsertContextualProfileV1"),
        upsertFolderSeenTimestamp: r("LSUpsertFolderSeenTimestamp"),
        upsertInboxThreadsRange: r("LSUpsertInboxThreadsRange"),
        upsertMessage: r("LSUpsertMessage"),
        upsertReaction: r("LSUpsertReaction"),
        upsertSyncGroupThreadsRange: r("LSUpsertSyncGroupThreadsRange"),
        verifyAndSaveNewCredentials: r("LSVerifyAndSaveNewCredentials"),
        verifyE2EEMetadataThreadExistsV2: r(
          "LSVerifyE2EEMetadataThreadExistsV2",
        ),
        writeThreadCapabilities: r("LSWriteThreadCapabilities"),
      }),
      s = e;
    l.default = s;
  },
  98,
);
