__d(
  "LSUpdateOrInsertThread",
  [],
  function (t, n, r, o, a, i) {
    function e() {
      var e = arguments,
        t = e[e.length - 1],
        n = [],
        r = [];
      return t.sequence([
        function (r) {
          return t.db
            .table(9)
            .fetch([[[e[7]]]])
            .next()
            .then(function (r, o) {
              var a,
                i,
                l = r.done,
                s = r.value;
              return l
                ? t.db
                    .table(9)
                    .add({
                      threadKey: e[7],
                      lastReadWatermarkTimestampMs: e[1],
                      authorityLevel: e[6],
                      mailboxType: e[8],
                      threadType: e[9],
                      folderName: e[10],
                      ongoingCallState: e[32],
                      parentThreadKey: e[38],
                      lastActivityTimestampMs: e[0],
                      snippet: e[2],
                      threadName: e[3],
                      threadPictureUrl: e[4],
                      needsAdminApprovalForNewParticipant: e[5],
                      threadPictureUrlFallback: e[11],
                      threadPictureUrlExpirationTimestampMs: e[12],
                      removeWatermarkTimestampMs: e[13],
                      muteExpireTimeMs: e[14],
                      muteMentionExpireTimeMs: e[15],
                      muteCallsExpireTimeMs: e[16],
                      groupNotificationSettings: e[19],
                      isAdminSnippet: e[20],
                      snippetSenderContactId: e[21],
                      snippetText: e[23],
                      snippetStringHash: e[24],
                      snippetStringArgument1: e[25],
                      snippetAttribution: e[26],
                      snippetAttributionStringHash: e[27],
                      disappearingSettingTtl: e[28],
                      disappearingSettingUpdatedTs: e[29],
                      disappearingSettingUpdatedBy: e[30],
                      cannotReplyReason: e[33],
                      customEmoji: e[34],
                      customEmojiImageUrl: e[35],
                      outgoingBubbleColor: e[36],
                      themeFbid: e[37],
                      nullstateDescriptionText1: e[39],
                      nullstateDescriptionType1: e[40],
                      nullstateDescriptionText2: e[41],
                      nullstateDescriptionType2: e[42],
                      nullstateDescriptionText3: e[43],
                      nullstateDescriptionType3: e[44],
                      snippetHasEmoji: e[45],
                      hasPersistentMenu: e[46],
                      disableComposerInput: e[47],
                      cannotUnsendReason: e[48],
                      viewedPluginKey: e[49],
                      viewedPluginContext: e[50],
                      clientThreadKey: e[51],
                      capabilities: e[52],
                      shouldRoundThreadPicture: e[53],
                      proactiveWarningDismissTime: e[54],
                      isCustomThreadPicture: e[55],
                      otidOfFirstMessage: e[56],
                      normalizedSearchTerms: e[57],
                      additionalThreadContext: e[58],
                      disappearingThreadKey: e[59],
                      isDisappearingMode: e[60],
                      disappearingModeInitiator: e[61],
                      unreadDisappearingMessageCount: e[62],
                      lastMessageCtaId: e[64],
                      lastMessageCtaType: e[65],
                      lastMessageCtaTimestampMs: e[66],
                      consistentThreadFbid: e[67],
                      threadDescription: e[69],
                      unsendLimitMs: e[70],
                      capabilities2: e[78],
                      capabilities3: e[79],
                      syncGroup: e[82],
                      threadInvitesEnabled: e[83],
                      threadInviteLink: e[84],
                      isAllUnreadMessageMissedCallXma: e[85],
                      numUnreadSubthreads: e[86],
                      subthreadCount: e[87],
                      lastNonMissedCallXmaMessageTimestampMs: e[88],
                      isHidden: e[89],
                      threadInvitesEnabledV2: e[90],
                      joinRequestApprovalSetting: e[93],
                      hasPendingInvitation: e[94],
                      eventStartTimestampMs: e[95],
                      eventEndTimestampMs: e[96],
                      takedownState: e[97],
                      secondaryParentThreadKey: e[98],
                      igFolder: e[99],
                      inviterId: e[100],
                      threadTags: e[101],
                      isReadReceiptsDisabled: e[102],
                      readReceiptsDisabledV2: e[103],
                      threadStatus: e[104],
                      threadSubtype: e[105],
                      pauseThreadTimestamp: e[106],
                      metadata: e[107],
                      capabilities4: e[108],
                      syncSource: e[109],
                      capabilities5: e[110],
                      capabilities6: e[111],
                      ongoingCallTimestampMs: e[112],
                    })
                : ((o = s.item),
                  (n[1] = o.lastActivityTimestampMs),
                  (n[3] = o.parentThreadKey),
                  (n[2] = o.disappearingThreadKey),
                  (n[4] = o.isDisappearingMode),
                  t.i64.le(o.authorityLevel, e[6])
                    ? t.i64.gt(n[1], e[0]) && t.i64.neq(n[2], void 0)
                      ? (t.i64.eq(e[38], t.i64.cast([-1, 4294967286])) &&
                        t.i64.eq(n[3], t.i64.cast([0, 0]))
                          ? ((a = [n[3], o.folderName]),
                            (n[5] = a[0]),
                            (n[6] = a[1]))
                          : ((i = [e[38], e[10]]),
                            (n[5] = i[0]),
                            (n[6] = i[1])),
                        t.forEach(
                          t.db.table(9).fetch([[[e[7]]]]),
                          function (t) {
                            var r = t.update,
                              a = t.item;
                            return r({
                              lastReadWatermarkTimestampMs:
                                o.lastReadWatermarkTimestampMs,
                              authorityLevel: e[6],
                              mailboxType: e[8],
                              threadType: e[9],
                              folderName: n[6],
                              ongoingCallState: e[32],
                              parentThreadKey: n[5],
                              lastActivityTimestampMs: n[1],
                              snippet: e[2],
                              threadName: e[3],
                              threadPictureUrl: e[4],
                              needsAdminApprovalForNewParticipant: e[5],
                              threadPictureUrlFallback: e[11],
                              threadPictureUrlExpirationTimestampMs: e[12],
                              removeWatermarkTimestampMs: e[13],
                              muteExpireTimeMs: e[14],
                              muteMentionExpireTimeMs: e[15],
                              muteCallsExpireTimeMs: e[16],
                              groupNotificationSettings: e[19],
                              isAdminSnippet: e[20],
                              snippetSenderContactId: e[21],
                              snippetText: e[23],
                              snippetStringHash: e[24],
                              snippetStringArgument1: e[25],
                              snippetAttribution: e[26],
                              snippetAttributionStringHash: e[27],
                              disappearingSettingTtl: e[28],
                              disappearingSettingUpdatedTs: e[29],
                              disappearingSettingUpdatedBy: e[30],
                              cannotReplyReason: e[33],
                              customEmoji: e[34],
                              customEmojiImageUrl: e[35],
                              outgoingBubbleColor: e[36],
                              themeFbid: e[37],
                              nullstateDescriptionText1: e[39],
                              nullstateDescriptionType1: e[40],
                              nullstateDescriptionText2: e[41],
                              nullstateDescriptionType2: e[42],
                              nullstateDescriptionText3: e[43],
                              nullstateDescriptionType3: e[44],
                              snippetHasEmoji: e[45],
                              hasPersistentMenu: e[46],
                              disableComposerInput: e[47],
                              cannotUnsendReason: e[48],
                              viewedPluginKey: e[49],
                              viewedPluginContext: e[50],
                              clientThreadKey: e[51],
                              capabilities: e[52],
                              shouldRoundThreadPicture: e[53],
                              proactiveWarningDismissTime: e[54],
                              isCustomThreadPicture: e[55],
                              otidOfFirstMessage: e[56],
                              normalizedSearchTerms: e[57],
                              additionalThreadContext: e[58],
                              disappearingThreadKey: n[2],
                              isDisappearingMode: n[4],
                              disappearingModeInitiator: e[61],
                              unreadDisappearingMessageCount: e[62],
                              lastMessageCtaId: e[64],
                              lastMessageCtaType: e[65],
                              lastMessageCtaTimestampMs: e[66],
                              consistentThreadFbid: e[67],
                              threadDescription: e[69],
                              unsendLimitMs: e[70],
                              capabilities2: e[78],
                              capabilities3: e[79],
                              syncGroup: e[82],
                              threadInvitesEnabled: e[83],
                              threadInviteLink: e[84],
                              isAllUnreadMessageMissedCallXma: e[85],
                              numUnreadSubthreads: e[86],
                              subthreadCount: e[87],
                              lastNonMissedCallXmaMessageTimestampMs: e[88],
                              isHidden: e[89],
                              threadInvitesEnabledV2: e[90],
                              joinRequestApprovalSetting: e[93],
                              hasPendingInvitation: e[94],
                              eventStartTimestampMs: e[95],
                              eventEndTimestampMs: e[96],
                              takedownState: e[97],
                              secondaryParentThreadKey: e[98],
                              igFolder: e[99],
                              inviterId: e[100],
                              threadTags: e[101],
                              isReadReceiptsDisabled: e[102],
                              readReceiptsDisabledV2: e[103],
                              threadStatus: e[104],
                              threadSubtype: e[105],
                              pauseThreadTimestamp: e[106],
                              metadata: e[107],
                              capabilities4: e[108],
                              syncSource: e[109],
                              capabilities5: e[110],
                              capabilities6: e[111],
                              ongoingCallTimestampMs: e[112],
                              avatarStickerInstructionKeyId: void 0,
                              avatarStickerId: void 0,
                              avatarStickerThumbnailImageUrl: void 0,
                              avatarStickerThumbnailImageMimeType: void 0,
                              avatarStickerOriginalImageUrl: void 0,
                              avatarStickerOriginalImageMimeType: void 0,
                              draftMessage: void 0,
                              hasPendingJoinRequest: void 0,
                              pendingJoinRequestsCount: void 0,
                              memberCount: void 0,
                              admodCount: void 0,
                              ctmAdId: void 0,
                              ctmAdgroupId: void 0,
                              ctmAdCampaignId: void 0,
                              ctmAdCampaignGroupId: void 0,
                              ctmAdAccountId: void 0,
                              typingIndicatorDisabled: void 0,
                              unreadMessageCount: void 0,
                            });
                          },
                        ))
                      : t.forEach(
                          t.db.table(9).fetch([[[e[7]]]]),
                          function (t) {
                            var r = t.update,
                              o = t.item;
                            return r({
                              lastReadWatermarkTimestampMs: e[1],
                              authorityLevel: e[6],
                              mailboxType: e[8],
                              threadType: e[9],
                              folderName: e[10],
                              ongoingCallState: e[32],
                              parentThreadKey: e[38],
                              lastActivityTimestampMs: e[0],
                              snippet: e[2],
                              threadName: e[3],
                              threadPictureUrl: e[4],
                              needsAdminApprovalForNewParticipant: e[5],
                              threadPictureUrlFallback: e[11],
                              threadPictureUrlExpirationTimestampMs: e[12],
                              removeWatermarkTimestampMs: e[13],
                              muteExpireTimeMs: e[14],
                              muteMentionExpireTimeMs: e[15],
                              muteCallsExpireTimeMs: e[16],
                              groupNotificationSettings: e[19],
                              isAdminSnippet: e[20],
                              snippetSenderContactId: e[21],
                              snippetText: e[23],
                              snippetStringHash: e[24],
                              snippetStringArgument1: e[25],
                              snippetAttribution: e[26],
                              snippetAttributionStringHash: e[27],
                              disappearingSettingTtl: e[28],
                              disappearingSettingUpdatedTs: e[29],
                              disappearingSettingUpdatedBy: e[30],
                              cannotReplyReason: e[33],
                              customEmoji: e[34],
                              customEmojiImageUrl: e[35],
                              outgoingBubbleColor: e[36],
                              themeFbid: e[37],
                              nullstateDescriptionText1: e[39],
                              nullstateDescriptionType1: e[40],
                              nullstateDescriptionText2: e[41],
                              nullstateDescriptionType2: e[42],
                              nullstateDescriptionText3: e[43],
                              nullstateDescriptionType3: e[44],
                              snippetHasEmoji: e[45],
                              hasPersistentMenu: e[46],
                              disableComposerInput: e[47],
                              cannotUnsendReason: e[48],
                              viewedPluginKey: e[49],
                              viewedPluginContext: e[50],
                              clientThreadKey: e[51],
                              capabilities: e[52],
                              shouldRoundThreadPicture: e[53],
                              proactiveWarningDismissTime: e[54],
                              isCustomThreadPicture: e[55],
                              otidOfFirstMessage: e[56],
                              normalizedSearchTerms: e[57],
                              additionalThreadContext: e[58],
                              disappearingThreadKey: n[2],
                              isDisappearingMode: n[4],
                              disappearingModeInitiator: e[61],
                              unreadDisappearingMessageCount: e[62],
                              lastMessageCtaId: e[64],
                              lastMessageCtaType: e[65],
                              lastMessageCtaTimestampMs: e[66],
                              consistentThreadFbid: e[67],
                              threadDescription: e[69],
                              unsendLimitMs: e[70],
                              capabilities2: e[78],
                              capabilities3: e[79],
                              syncGroup: e[82],
                              threadInvitesEnabled: e[83],
                              threadInviteLink: e[84],
                              isAllUnreadMessageMissedCallXma: e[85],
                              numUnreadSubthreads: e[86],
                              subthreadCount: e[87],
                              lastNonMissedCallXmaMessageTimestampMs: e[88],
                              isHidden: e[89],
                              threadInvitesEnabledV2: e[90],
                              joinRequestApprovalSetting: e[93],
                              hasPendingInvitation: e[94],
                              eventStartTimestampMs: e[95],
                              eventEndTimestampMs: e[96],
                              takedownState: e[97],
                              secondaryParentThreadKey: e[98],
                              igFolder: e[99],
                              inviterId: e[100],
                              threadTags: e[101],
                              isReadReceiptsDisabled: e[102],
                              readReceiptsDisabledV2: e[103],
                              threadStatus: e[104],
                              threadSubtype: e[105],
                              pauseThreadTimestamp: e[106],
                              metadata: e[107],
                              capabilities4: e[108],
                              syncSource: e[109],
                              capabilities5: e[110],
                              capabilities6: e[111],
                              ongoingCallTimestampMs: e[112],
                              avatarStickerInstructionKeyId: void 0,
                              avatarStickerId: void 0,
                              avatarStickerThumbnailImageUrl: void 0,
                              avatarStickerThumbnailImageMimeType: void 0,
                              avatarStickerOriginalImageUrl: void 0,
                              avatarStickerOriginalImageMimeType: void 0,
                              draftMessage: void 0,
                              hasPendingJoinRequest: void 0,
                              pendingJoinRequestsCount: void 0,
                              memberCount: void 0,
                              admodCount: void 0,
                              ctmAdId: void 0,
                              ctmAdgroupId: void 0,
                              ctmAdCampaignId: void 0,
                              ctmAdCampaignGroupId: void 0,
                              ctmAdAccountId: void 0,
                              typingIndicatorDisabled: void 0,
                              unreadMessageCount: void 0,
                            });
                          },
                        )
                    : t.resolve());
            });
        },
        function (e) {
          return t.resolve(r);
        },
      ]);
    }
    ((e.__sproc_name__ = "LSMailboxUpdateOrInsertThreadStoredProcedure"),
      (e.__tables__ = ["threads"]),
      (a.exports = e));
  },
  null,
);
