__d(
  "MAIBAAdObjectHoverCardPopover_AMDQuery.graphql",
  [],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = (function () {
      var e = { defaultValue: null, kind: "LocalArgument", name: "adObjectId" },
        t = { defaultValue: null, kind: "LocalArgument", name: "adgroupIDs" },
        n = {
          defaultValue: null,
          kind: "LocalArgument",
          name: "campaignGroupIDs",
        },
        r = { defaultValue: null, kind: "LocalArgument", name: "campaignIDs" },
        o = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "id",
          storageKey: null,
        },
        a = [o],
        i = [
          {
            alias: null,
            args: null,
            concreteType: "AdDeliveryStatusNode",
            kind: "LinkedField",
            name: "delivery_status_info",
            plural: !1,
            selections: [
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "status",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                concreteType: "AdDeliverySubstatusNode",
                kind: "LinkedField",
                name: "substatuses",
                plural: !0,
                selections: a,
                storageKey: null,
              },
            ],
            storageKey: null,
          },
        ],
        l = {
          kind: "InlineFragment",
          selections: [
            {
              name: "__relay_model_instance",
              args: null,
              fragment: {
                kind: "InlineFragment",
                selections: a,
                type: "ClientAdAccount",
                abstractKey: null,
              },
              kind: "RelayResolver",
              storageKey: null,
              isOutputType: !1,
            },
          ],
          type: "ClientAdAccount",
          abstractKey: null,
        },
        s = [
          { kind: "Variable", name: "ids", variableName: "campaignGroupIDs" },
        ],
        u = {
          kind: "InlineFragment",
          selections: [
            {
              name: "__relay_model_instance",
              args: null,
              fragment: {
                kind: "InlineFragment",
                selections: a,
                type: "CombinedCampaignGroup",
                abstractKey: null,
              },
              kind: "RelayResolver",
              storageKey: null,
              isOutputType: !1,
            },
          ],
          type: "CombinedCampaignGroup",
          abstractKey: null,
        },
        c = {
          name: "ad_object_id",
          args: null,
          fragment: u,
          kind: "RelayResolver",
          storageKey: null,
          isOutputType: !0,
        },
        d = [{ kind: "Literal", name: "limit", value: 1 }],
        m = [{ kind: "Literal", name: "limit", value: 3 }],
        p = {
          kind: "InlineFragment",
          selections: [
            {
              name: "__relay_model_instance",
              args: null,
              fragment: {
                kind: "InlineFragment",
                selections: a,
                type: "CombinedCampaign",
                abstractKey: null,
              },
              kind: "RelayResolver",
              storageKey: null,
              isOutputType: !1,
            },
          ],
          type: "CombinedCampaign",
          abstractKey: null,
        },
        _ = {
          kind: "InlineFragment",
          selections: [
            {
              name: "__relay_model_instance",
              args: null,
              fragment: {
                kind: "InlineFragment",
                selections: a,
                type: "CombinedAdgroup",
                abstractKey: null,
              },
              kind: "RelayResolver",
              storageKey: null,
              isOutputType: !1,
            },
          ],
          type: "CombinedAdgroup",
          abstractKey: null,
        },
        f = {
          name: "ad_object_id",
          args: null,
          fragment: _,
          kind: "RelayResolver",
          storageKey: null,
          isOutputType: !0,
        },
        g = {
          kind: "ClientEdgeToClientObject",
          backingField: {
            name: "combined_adgroups_slow",
            args: m,
            fragment: p,
            kind: "RelayResolver",
            storageKey: "combined_adgroups_slow(limit:3)",
            isOutputType: !1,
          },
          linkedField: {
            alias: "combined_adgroups",
            args: m,
            concreteType: "CombinedAdgroup",
            kind: "LinkedField",
            name: "combined_adgroups_slow",
            plural: !0,
            selections: [f, o],
            storageKey: "combined_adgroups_slow(limit:3)",
          },
        },
        h = [{ kind: "Variable", name: "ids", variableName: "campaignIDs" }],
        y = {
          alias: null,
          args: null,
          concreteType: "CombinedCampaignGroup",
          kind: "LinkedField",
          name: "combined_campaign_group",
          plural: !1,
          selections: [c, o],
          storageKey: null,
        },
        C = [{ kind: "Variable", name: "ids", variableName: "adgroupIDs" }];
      return {
        fragment: {
          argumentDefinitions: [e, t, n, r],
          kind: "Fragment",
          metadata: null,
          name: "MAIBAAdObjectHoverCardPopover_AMDQuery",
          selections: [
            {
              args: null,
              kind: "FragmentSpread",
              name: "useMAIBAAdObjectHoverCardDataSelector_Fragment",
            },
          ],
          type: "Query",
          abstractKey: null,
        },
        kind: "Request",
        operation: {
          argumentDefinitions: [n, r, t, e],
          kind: "Operation",
          name: "MAIBAAdObjectHoverCardPopover_AMDQuery",
          selections: [
            {
              alias: "server",
              args: [
                { kind: "Variable", name: "id", variableName: "adObjectId" },
              ],
              concreteType: null,
              kind: "LinkedField",
              name: "node",
              plural: !1,
              selections: [
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "__typename",
                  storageKey: null,
                },
                {
                  kind: "InlineFragment",
                  selections: i,
                  type: "AdCampaignGroup",
                  abstractKey: null,
                },
                {
                  kind: "InlineFragment",
                  selections: i,
                  type: "AdCampaign",
                  abstractKey: null,
                },
                {
                  kind: "InlineFragment",
                  selections: i,
                  type: "Adgroup",
                  abstractKey: null,
                },
                o,
              ],
              storageKey: null,
            },
            {
              kind: "ClientEdgeToClientObject",
              backingField: {
                name: "selected_ad_account",
                args: null,
                fragment: null,
                kind: "RelayResolver",
                storageKey: null,
                isOutputType: !1,
              },
              linkedField: {
                alias: "client",
                args: null,
                concreteType: "ClientAdAccount",
                kind: "LinkedField",
                name: "selected_ad_account",
                plural: !1,
                selections: [
                  {
                    name: "self",
                    args: null,
                    fragment: l,
                    kind: "RelayResolver",
                    storageKey: null,
                    isOutputType: !0,
                  },
                  {
                    kind: "ClientEdgeToClientObject",
                    backingField: {
                      name: "combined_campaign_groups",
                      args: s,
                      fragment: l,
                      kind: "RelayResolver",
                      storageKey: null,
                      isOutputType: !1,
                    },
                    linkedField: {
                      alias: "campaign_groups",
                      args: s,
                      concreteType: "CombinedCampaignGroup",
                      kind: "LinkedField",
                      name: "combined_campaign_groups",
                      plural: !0,
                      selections: [
                        c,
                        {
                          name: "name",
                          args: null,
                          fragment: u,
                          kind: "RelayResolver",
                          storageKey: null,
                          isOutputType: !0,
                        },
                        {
                          kind: "ClientEdgeToClientObject",
                          backingField: {
                            name: "combined_campaigns_slow",
                            args: d,
                            fragment: u,
                            kind: "RelayResolver",
                            storageKey: "combined_campaigns_slow(limit:1)",
                            isOutputType: !1,
                          },
                          linkedField: {
                            alias: "combined_campaigns",
                            args: d,
                            concreteType: "CombinedCampaign",
                            kind: "LinkedField",
                            name: "combined_campaigns_slow",
                            plural: !0,
                            selections: [g, o],
                            storageKey: "combined_campaigns_slow(limit:1)",
                          },
                        },
                        {
                          name: "publish_status",
                          args: null,
                          fragment: u,
                          kind: "RelayResolver",
                          storageKey: null,
                          isOutputType: !0,
                        },
                        o,
                      ],
                      storageKey: null,
                    },
                  },
                  {
                    kind: "ClientEdgeToClientObject",
                    backingField: {
                      name: "combined_campaigns",
                      args: h,
                      fragment: l,
                      kind: "RelayResolver",
                      storageKey: null,
                      isOutputType: !1,
                    },
                    linkedField: {
                      alias: "campaigns",
                      args: h,
                      concreteType: "CombinedCampaign",
                      kind: "LinkedField",
                      name: "combined_campaigns",
                      plural: !0,
                      selections: [
                        {
                          name: "ad_object_id",
                          args: null,
                          fragment: p,
                          kind: "RelayResolver",
                          storageKey: null,
                          isOutputType: !0,
                        },
                        {
                          name: "name",
                          args: null,
                          fragment: p,
                          kind: "RelayResolver",
                          storageKey: null,
                          isOutputType: !0,
                        },
                        g,
                        {
                          kind: "ClientEdgeToClientObject",
                          backingField: {
                            name: "combined_campaign_group",
                            args: null,
                            fragment: p,
                            kind: "RelayResolver",
                            storageKey: null,
                            isOutputType: !1,
                          },
                          linkedField: y,
                        },
                        {
                          name: "publish_status",
                          args: null,
                          fragment: p,
                          kind: "RelayResolver",
                          storageKey: null,
                          isOutputType: !0,
                        },
                        o,
                      ],
                      storageKey: null,
                    },
                  },
                  {
                    kind: "ClientEdgeToClientObject",
                    backingField: {
                      name: "combined_adgroups",
                      args: C,
                      fragment: l,
                      kind: "RelayResolver",
                      storageKey: null,
                      isOutputType: !1,
                    },
                    linkedField: {
                      alias: "adgroups",
                      args: C,
                      concreteType: "CombinedAdgroup",
                      kind: "LinkedField",
                      name: "combined_adgroups",
                      plural: !0,
                      selections: [
                        f,
                        {
                          name: "name",
                          args: null,
                          fragment: _,
                          kind: "RelayResolver",
                          storageKey: null,
                          isOutputType: !0,
                        },
                        {
                          kind: "ClientEdgeToClientObject",
                          backingField: {
                            name: "combined_campaign_group",
                            args: null,
                            fragment: _,
                            kind: "RelayResolver",
                            storageKey: null,
                            isOutputType: !1,
                          },
                          linkedField: y,
                        },
                        {
                          name: "publish_status",
                          args: null,
                          fragment: _,
                          kind: "RelayResolver",
                          storageKey: null,
                          isOutputType: !0,
                        },
                        o,
                      ],
                      storageKey: null,
                    },
                  },
                  o,
                ],
                storageKey: null,
              },
            },
          ],
        },
        params: {
          id: "27102344426108597",
          metadata: {},
          name: "MAIBAAdObjectHoverCardPopover_AMDQuery",
          operationKind: "query",
          text: null,
        },
      };
    })();
    a.exports = e;
  },
  null,
);
