__d(
  "MAIBASubsurfaces",
  [],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = {
        NUX_MODAL: "nux_modal",
        MP_MODAL: "mp_modal",
        MP_MODAL_REQUEST_CALL: "mp_modal_request_call",
        MP_ENTRYPOINT_BUTTON: "mp_entrypoint_button",
        AD_PREVIEW_ENTRYPOINT_BUTTON: "ad_preview_entrypoint_button",
        ACTION_BAR_ENTRYPOINT_BUTTON: "action_bar_entrypoint_button",
        AD_OBJECT_OVERFLOW_MENU_ENTRYPOINT:
          "ad_object_overflow_menu_entrypoint",
        BUDGET_EDIT_MODAL_IN_SITU: "budget_edit_modal_in_situ",
        BUDGET_EDIT_MODAL_IN_SITU_ANALYSIS_BUTTON:
          "budget_edit_modal_in_situ_analysis_button",
        BUDGET_EDIT_MODAL_IN_SITU_APPLY_BUDGET:
          "budget_edit_modal_in_situ_apply_budget",
        BUDGET_EDIT_MODAL_IN_SITU_BUDGET_CHANGE:
          "budget_edit_modal_in_situ_budget_change",
        BUDGET_EDIT_MODAL_IN_SITU_RECOMMENDATION:
          "budget_edit_modal_in_situ_recommendation",
        BUDGET_EDIT_MODAL_IN_SITU_ANALYSIS:
          "budget_edit_modal_in_situ_analysis",
        BUDGET_EDIT_MODAL_IN_SITU_INSIGHTS:
          "budget_edit_modal_in_situ_insights",
        PERFORMANCE_DIAGNOSIS_WIDGET: "performance_diagnosis_widget",
        PERFORMANCE_DIAGNOSIS_ACCORDION: "performance_diagnosis_accordion",
        PERFORMANCE_DIAGNOSIS_ITEM: "performance_diagnosis_item",
        PERFORMANCE_DIAGNOSIS_SUGGESTED_PROMPTS:
          "performance_diagnosis_suggested_prompts",
        ROOT: "root",
        CHAT_APP: "chat_app",
        CHAT_WELCOME_PAGE: "chat_welcome_page",
        CHAT_404_PAGE: "chat_404_page",
        CHAT_THREAD: "chat_thread",
        FOOTER: "message_footer",
        COMPOSER_BUTTON: "composer_button",
        COMPOSER: "composer",
        CLOSE_BUTTON: "close_button",
        FULL_SCREEN_BUTTON: "full_screen_button",
        DEFAULT_SCREEN_SIZE_BUTTON: "minimze_screen_size_button",
        TITLE: "title",
        DEBUG_MENU: "debug_menu",
        AD_OBJECT_HOVER_CARD: "ad_object_hover_card",
        POST_HOVER_CARD: "post_hover_card",
        IMPROVED_MAIBA_EXPERIENCE_BANNER: "improved_maiba_experience_banner",
        COMPOSER_UPLOAD_FILE_BUTTON: "composer_upload_file_button",
        COMPOSER_UPLOADED_FILE_PREVIEW: "composer_uploaded_file_preview",
        COMPOSER_IMAGE_LIBRARY_BUTTON: "composer_image_library_button",
        COMPOSER_IMAGE_LIBRARY_MODAL: "composer_image_library_modal",
        COMPOSER_VIDEO_LIBRARY_BUTTON: "composer_video_library_button",
        COMPOSER_VIDEO_LIBRARY_MODAL: "composer_video_library_modal",
        COMPOSER_ADD_ATTACHMENT_MENU: "composer_add_attachment_menu",
        PROACTIVE_SUMMARY_CARD: "proactive_summary_card",
        BOT_MESSAGE: "bot_message",
        COMPOSED_TEXT: "composed_text",
        ASSET_SELECTION_CARD: "asset_selection_card",
        ADMIN_TEXT: "admin_text",
        CAROUSEL_ATTACHMENT: "carousel_attachment",
        SUGGESTED_PROMPT: "suggested_prompt",
        BUTTON_ATTACHMENT: "button_attachment",
        ORDERED_LIST_ITEM: "ordered_list_item",
        LINK: "link",
        STOP_STREAMING_NOTICE: "stop_streaming_notice",
        ERROR_NOTICE: "error_notice",
        MATH_OBJECT: "math_object",
        UNORDERED_LIST_ITEM: "unordered_list_item",
        HEADING_ONE: "heading_one",
        HEADING_TWO: "heading_two",
        HEADING_THREE: "heading_three",
        HEADING_FOUR: "heading_four",
        HEADING_FIVE: "heading_five",
        HEADING_SIX: "heading_six",
        CHECKBOX_ITEM: "checkbox_item",
        QUOTE: "quote",
        PLE: "ple",
        OS_SCORE: "os_score",
        OS_CTA: "os_cta",
        NON_OS_CTA: "non_os_cta",
        PERFORMANCE_SUMMARY_CTA: "performance_summary_cta",
        ADS_CHECKER_CTA: "ads_checker_cta",
        SIGNALS_CTA: "signals_cta",
        AD_OBJECT: "ad_object",
        PAGE_REFERENCE: "page_reference",
        AD_CREATION_SUMMARY: "ad_creation_summary",
        SUGGESTION_CARDS: "suggestion_cards",
        SELECTABLE_CARDS: "selectable_cards",
        DISAMBIGUATION: "disambiguation",
        OPTIONALITY: "optionality",
        BANNER: "banner",
        CHARTING: "charting",
        DATA_VIZ: "data_viz",
        DAG_CARD: "dag_card",
        NODE_COMPLETE: "node_complete",
        ASK_META_AI: "ask_meta_ai",
        MID_CHAT_PROMPT: "mid_chat_prompt",
        TOOL_CALL: "tool_call",
        CONFIRM_FORM: "confirm_form",
        ARTIFACT: "artifact",
        RECOMMENDED_POST_PREVIEW: "recommended_post_preview",
        AD_LIBRARY_PREVIEW: "ad_library_preview",
        NDP_CERTIFICATION: "ndp_certification",
        XFAC_CHALLENGE: "xfac_challenge",
        ACTION: "action",
        ICON: "icon",
        LIVE_BROWSER: "live_browser",
        PUBLISH_BUTTON: "publish_button",
        USER_MESSAGE: "user_message",
        USER_MESSAGE_IMAGE_ATTACHMENT: "user_message_image_attachment",
        USER_MESSAGE_DOCUMENT_ATTACHMENT: "user_message_document_attachment",
        CLIENT_VALUE: "client_value",
        THREADS_LIST_BUTTON: "threads_list_button",
        THREAD_LIST_ITEM: "thread_list_item",
        THREADS_LIST_SECTION: "threads_list_section",
        PINNED_THREADS_HEADER: "pinned_threads_header",
        RENAME_THREAD_MODAL: "rename_thread_modal",
        ARCHIVE_THREAD_MODAL: "archive_thread_modal",
        DELETE_THREAD_MODAL: "delete_thread_modal",
        THREAD_MANAGEMENT_MENU: "thread_management_menu",
        THREAD_RENAME_BUTTON: "thread_rename_button",
        THREAD_PIN_BUTTON: "thread_pin_button",
        THREAD_UNPIN_BUTTON: "thread_unpin_button",
        THREAD_ARCHIVE_BUTTON: "thread_archive_button",
        THREAD_UNARCHIVE_BUTTON: "thread_unarchive_button",
        THREAD_DELETE_BUTTON: "thread_delete_button",
        COMPOSER_ASSET_SELECTOR_BUTTON: "composer_asset_selector_button",
        COMPOSER_ASSET_MANAGER: "composer_asset_manager",
        ASSET_SELECTOR: "asset_selector",
        WABA_SELECTOR: "waba_selector",
        ASSET_ATTACHMENT: "asset_attachment",
        SELECTABLE_ASSET_LIST: "selectable_asset_list",
        SELECTABLE_ASSET: "selectable_asset",
        L4_ASSET_SELECTOR: "l4_asset_selector",
        L4_ASSET_ITEM: "l4_asset_item",
        DATA_VIZ_CARD_CONTAINER: "data_viz_card_container",
        DATA_VIZ_CHART_CARD: "data_viz_chart_card",
        DATA_VIZ_TABLE_CARD: "data_viz_table_card",
        DATA_VIZ_ERROR_CARD: "data_viz_error_card",
        DATA_VIZ_EXPORT_BUTTON: "data_viz_export_button",
        DATA_VIZ_SWAP_BUTTON: "data_viz_swap_button",
        DATA_VIZ_METRIC_SELECTOR: "data_viz_metric_selector",
        DAILY_SPEND_LIMIT: "daily_spend_limit",
        DAILY_SPEND_TRACKER: "daily_spend_tracker",
        AD_ACCOUNT_REVIEW_CARD: "ad_account_review_card",
        SETTING_BUTTON: "setting_button",
        SETTING_MODAL: "setting_modal",
        MEMORY_DELETE_CONFIRMATION_MODAL: "memory_delete_confirmation_modal",
        MEMORY_IMPORT_MODAL: "memory_import_modal",
        FEEDBACK_GUIDANCE_CARD: "feedback_guidance_card",
        CONTEXTUAL_SUPPORT_FEEDBACK_THUMBS_UP:
          "contextual_support_feedback_thumbs_up",
        CONTEXTUAL_SUPPORT_FEEDBACK_THUMBS_DOWN:
          "contextual_support_feedback_thumbs_down",
        CONTEXTUAL_SUPPORT_FEEDBACK_REPORT:
          "contextual_support_feedback_report",
        EXPLICIT_CONSENT_GUIDANCE: "explicit_consent_guidance",
        SCORECARD_INSITU: "scorecard_insitu",
        SCORECARD_INSITU_INSIGHTS: "scorecard_insitu_insights",
        SCORECARD_INSITU_EMPTY: "scorecard_insitu_empty",
        SCORECARD_INSITU_DISMISS: "scorecard_insitu_dismiss",
        SCORECARD_RANGE_SHORT: "scorecard_range_short",
        SCORECARD_FULL_REPORT: "scorecard_full_report",
        SCORECARD_ISSUE_CARD: "scorecard_issue_card",
        SCORECARD_CTA: "scorecard_cta",
        SCORECARD_SHELL_TAB: "scorecard_shell_tab",
        WORKSPACE_CANVAS_CLOSE_BUTTON: "workspace_canvas_close_button",
        WORKSPACE_CANVAS_ESCAPE_HATCH_BUTTON:
          "workspace_canvas_escape_hatch_button",
        WORKSPACE_CANVAS_LOADING: "workspace_canvas_loading",
        WORKSPACE_CANVAS_PUBLISH_BUTTON: "workspace_canvas_publish_button",
        WORKSPACE_CANVAS_SECTION_APPLY_BUTTON:
          "workspace_canvas_section_apply_button",
        WORKSPACE_CANVAS_SECTION_EDIT_BUTTON:
          "workspace_canvas_section_edit_button",
        WORKSPACE_CANVAS_SECTION_IMPRESSION:
          "workspace_canvas_section_impression",
        WORKSPACE_CANVAS_SUSPENSE_LOADING: "workspace_canvas_suspense_loading",
        WORKSPACE_INLINE_PILL_PUBLISH_BUTTON:
          "workspace_inline_pill_publish_button",
      },
      l = e;
    i.default = l;
  },
  66,
);
