__d(
  "MAWLocalizationType",
  ["MAWAdminMsgType"],
  function (t, n, r, o, a, i, l) {
    "use strict";
    var e = "emptySnippet",
      s = "currentUserCreatedGroup",
      u = "participantCreatedGroup",
      c = "unknownUserCreatedGroup",
      d = "currentUserGotPromoted",
      m = "currentUserGotDemoted",
      p = "participantGotPromoted",
      _ = "participantGotDemoted",
      f = "participantPromotedYou",
      g = "participantDemotedYou",
      h = "currentUserPromotedParticipant",
      y = "currentUserDemotedParticipant",
      C = "participantDemotedParticipant",
      b = "participantPromotedParticipant",
      v = "participantSelfDemoted",
      S = "currentUserSelfDemoted",
      R = "currentUserSendText",
      L = "currentUserSendImage",
      E = "currentUserSendVideo",
      k = "currentUserSendAudio",
      I = "currentUserSendGif",
      T = "currentUserSendSticker",
      D = "participantSendText",
      x = "participantSendTextInGroup",
      $ = "participantSendImage",
      P = "participantSendVideo",
      N = "participantSendAudio",
      M = "participantSendGif",
      w = "participantSendSticker",
      A = "unavailableSnippet",
      F = "messageUnavailableSnippet",
      O = "messageNotRestored",
      B = "unknownUserEphemeralSettingTurnedOnSeconds",
      W = "unknownUserEphemeralSettingTurnedOnMinutes",
      q = "unknownUserEphemeralSettingTurnedOnHours",
      U = "unknownUserEphemeralSettingTurnedOnDays",
      V = "youEphemeralSettingTurnedOnSeconds",
      H = "youEphemeralSettingTurnedOnMinutes",
      G = "youEphemeralSettingTurnedOnHours",
      z = "youEphemeralSettingTurnedOnDays",
      j = "participantEphemeralSettingTurnedOnSeconds",
      K = "participantEphemeralSettingTurnedOnMinutes",
      Q = "participantEphemeralSettingTurnedOnHours",
      X = "participantEphemeralSettingTurnedOnDays",
      Y = "unknownUserEphemeralSettingChangeSeconds",
      J = "unknownUserEphemeralSettingChangeMinutes",
      Z = "unknownUserEphemeralSettingChangeHours",
      ee = "unknownUserEphemeralSettingChangeDays",
      te = "youEphemeralSettingChangeSeconds",
      ne = "youEphemeralSettingChangeMinutes",
      re = "youEphemeralSettingChangeHours",
      oe = "youEphemeralSettingChangeDays",
      ae = "participantEphemeralSettingChangeSeconds",
      ie = "participantEphemeralSettingChangeMinutes",
      le = "participantEphemeralSettingChangeHours",
      se = "participantEphemeralSettingChangeDays",
      ue = "unknownUserEphemeralSettingTurnedOff",
      ce = "youEphemeralSettingTurnedOff",
      de = "participantEphemeralSettingTurnedOff",
      me = "ephemeralSettingsAutoReset",
      pe = "currentUserUnsentMessage",
      _e = "participantUnsentMessage",
      fe = "participantReactMessage",
      ge = "participantReactMessageInGroup",
      he = "unknownUserEphemeralTakeScreenshot",
      ye = "unknownUserEphemeralRecordScreen",
      Ce = "youEphemeralTakeScreenshot",
      be = "youEphemeralRecordScreen",
      ve = "participantEphemeralTakeScreenshot",
      Se = "participantEphemeralRecordScreen",
      Re = "currentUserSendAttachment",
      Le = "participantSendAttachment",
      Ee = "currentUserSentPost",
      ke = "currentUserSentReel",
      Ie = "currentUserSentStory",
      Te = "currentUserSentEvent",
      De = "currentUserMentionedStoryIG",
      xe = "currentUserReceivedStoryMentionIG",
      $e = "participantSentPost",
      Pe = "participantSentReel",
      Ne = "participantSentStory",
      Me = "participantSentEvent",
      we = "currentUserSentStoryHighlight",
      Ae = "participantSentStoryHighlight",
      Fe = "currentUserMissedAudioCall",
      Oe = "participantMissedAudioCall",
      Be = "currentUserMissedVideoCall",
      We = "participantMissedVideoCall",
      qe = "currentUserAudioCalled",
      Ue = "participantAudioCalled",
      Ve = "currentUserVideoCalled",
      He = "participantVideoCalled",
      Ge = "currentUserStartedGroupAudioCall",
      ze = "participantStartedGroupAudioCall",
      je = "currentUserStartedGroupVideoCall",
      Ke = "participantStartedGroupVideoCall",
      Qe = "currentUserBumpedOwnMessage",
      Xe = "currentUserBumpedMessage",
      Ye = "participantBumpedOwnMessage",
      Je = "participantBumpedParticipantMessage",
      Ze = "participantBumpedCurrentUserMessage",
      et = "userSendUnavailableMessage",
      tt = "userSendEncryptedMessage",
      nt = "currentUserSendUnrenderableMessage",
      rt = "participantSendUnrenderableMessage",
      ot = "currentUserSendLocationFallback",
      at = "participantSendLocation",
      it = "currentUserSendLiveLocationFallback",
      lt = "participantSendLiveLocation",
      st = "currentUserSendLocation",
      ut = "participantSendLocation",
      ct = "currentUserSendPollCreationFallback",
      dt = "participantSendPollCreation",
      mt = "currentUserSendContactShareFallback",
      pt = "participantSendContactShareFallback",
      _t = "currentUserSendContactShare",
      ft = "participantSendContactShare",
      gt = "currentUserSendAIContactShare",
      ht = "participantSendAIContactShare",
      yt = "currentUserSendStoryMentionFallback",
      Ct = "currentUserSendStoryMention",
      bt = "participantSendStoryMention",
      vt = "participantSendStoryMentionFallback",
      St = "currentUserSendPostMentionFallback",
      Rt = "participantSendPostMentionFallback",
      Lt = "currentUserSendMemoriesShare",
      Et = "participantSendMemoriesShare",
      kt = "currentUserSendPostMention",
      It = "participantSendPostMention",
      Tt = "currentUserSendNoteMentionFallback",
      Dt = "participantSendNoteMentionFallback",
      xt = "messengerMemoryEncryptedMessageFallback",
      $t = "rtcXMAMessageFallback",
      Pt = "metaAISendMessageFallback",
      Nt = "currentUserSendBumpMessageFallback",
      Mt = "participantSendBumpMessageFallback",
      wt = "participantSendBumpMessageOriginalUnavailable",
      At = "currentUserSendStickerReceiverFetchMessageFallback",
      Ft = "participantSendStickerReceiverFetchMessageFallback",
      Ot = "viewOncePhotoMessageFallback",
      Bt = "viewOnceVideoMessageFallback",
      Wt = "unavailableStory",
      qt = "unavailableStatus",
      Ut = "currentUserLimitSharingDisabled",
      Vt = "currentUserLimitSharingEnabled",
      Ht = "participantLimitSharingDisabled",
      Gt = "participantLimitSharingEnabled",
      zt = "dualThreadCutoverAdminMessageOtherUserNameUnknown",
      jt = "dualThreadCutoverAdminMessageSelfThread",
      Kt = "dualThreadCutoverAdminMessageWithOtherUserName",
      Qt = babelHelpers.extends({}, o("MAWAdminMsgType").ADMIN_MSG_TYPE, {
        CURRENT_USER_AUDIO_CALLED: qe,
        CURRENT_USER_BUMPED_MESSAGE: Xe,
        CURRENT_USER_BUMPED_OWN_MESSAGE: Qe,
        CURRENT_USER_CREATED_GROUP: s,
        CURRENT_USER_DEMOTED_PARTICIPANT: y,
        CURRENT_USER_GOT_DEMOTED: m,
        CURRENT_USER_GOT_PROMOTED: d,
        CURRENT_USER_LIMIT_SHARING_DISABLED: Ut,
        CURRENT_USER_LIMIT_SHARING_ENABLED: Vt,
        CURRENT_USER_MENTIONED_STORY_IG: De,
        CURRENT_USER_MISSED_AUDIO_CALL: Fe,
        CURRENT_USER_MISSED_VIDEO_CALL: Be,
        CURRENT_USER_PROMOTED_PARTICIPANT: h,
        CURRENT_USER_RECEIVED_STORY_MENTION_IG: xe,
        CURRENT_USER_SELF_DEMOTED: S,
        CURRENT_USER_SEND_AI_CONTACT_SHARE: gt,
        CURRENT_USER_SEND_ATTACHMENT: Re,
        CURRENT_USER_SEND_AUDIO: k,
        CURRENT_USER_SEND_BUMP_MESSAGE_FALLBACK: Nt,
        CURRENT_USER_SEND_CONTACT_SHARE: _t,
        CURRENT_USER_SEND_CONTACT_SHARE_FALLBACK: mt,
        CURRENT_USER_SEND_GIF: I,
        CURRENT_USER_SEND_IMAGE: L,
        CURRENT_USER_SEND_LIVE_LOCATION_FALLBACK: it,
        CURRENT_USER_SEND_LOCATION: st,
        CURRENT_USER_SEND_LOCATION_FALLBACK: ot,
        CURRENT_USER_SEND_MEMORIES_SHARE: Lt,
        CURRENT_USER_SEND_NOTE_MENTION_FALLBACK: Tt,
        CURRENT_USER_SEND_POLL_CREATION_FALLBACK: ct,
        CURRENT_USER_SEND_POST_MENTION: kt,
        CURRENT_USER_SEND_POST_MENTION_FALLBACK: St,
        CURRENT_USER_SEND_STICKER: T,
        CURRENT_USER_SEND_STICKER_RECEIVER_FETCH_MESSAGE_FALLBACK: At,
        CURRENT_USER_SEND_STORY_MENTION: Ct,
        CURRENT_USER_SEND_STORY_MENTION_FALLBACK: yt,
        CURRENT_USER_SEND_TEXT: R,
        CURRENT_USER_SEND_UNRENDERABLE_MESSAGE_FALLBACK: nt,
        CURRENT_USER_SEND_VIDEO: E,
        CURRENT_USER_SENT_EVENT: Te,
        CURRENT_USER_SENT_POST: Ee,
        CURRENT_USER_SENT_REEL: ke,
        CURRENT_USER_SENT_STORY: Ie,
        CURRENT_USER_SENT_STORY_HIGHLIGHT: we,
        CURRENT_USER_STARTED_GROUP_AUDIO_CALL: Ge,
        CURRENT_USER_STARTED_GROUP_VIDEO_CALL: je,
        CURRENT_USER_UNSENT_MESSAGE: pe,
        CURRENT_USER_VIDEO_CALLED: Ve,
        DUAL_THREAD_CUTOVER_ADMIN_MESSAGE_OTHER_USER_NAME_UNKNOWN: zt,
        DUAL_THREAD_CUTOVER_ADMIN_MESSAGE_SELF_THREAD: jt,
        DUAL_THREAD_CUTOVER_ADMIN_MESSAGE_WITH_OTHER_USER_NAME: Kt,
        EMPTY_SNIPPET: e,
        EPHEMERAL_SETTINGS_AUTO_RESET: me,
        MESSAGE_NOT_RESTORED: O,
        MESSAGE_UNAVAILABLE_SNIPPET: F,
        MESSENGER_MEMORY_ENCRYPTED_MESSAGE_FALLBACK: xt,
        META_AI_SEND_MESSAGE_FALLBACK: Pt,
        PARTICIPANT_AUDIO_CALLED: Ue,
        PARTICIPANT_BUMPED_CURRENT_USER_MESSAGE: Ze,
        PARTICIPANT_BUMPED_OWN_MESSAGE: Ye,
        PARTICIPANT_BUMPED_PARTICIPANT_MESSAGE: Je,
        PARTICIPANT_CREATED_GROUP: u,
        PARTICIPANT_DEMOTED_PARTICIPANT: C,
        PARTICIPANT_DEMOTED_YOU: g,
        PARTICIPANT_EPHEMERAL_RECORD_SCREEN: Se,
        PARTICIPANT_EPHEMERAL_SETTING_CHANGE_DAYS: se,
        PARTICIPANT_EPHEMERAL_SETTING_CHANGE_HOURS: le,
        PARTICIPANT_EPHEMERAL_SETTING_CHANGE_MINUTES: ie,
        PARTICIPANT_EPHEMERAL_SETTING_CHANGE_SECONDS: ae,
        PARTICIPANT_EPHEMERAL_SETTING_TURNED_OFF: de,
        PARTICIPANT_EPHEMERAL_SETTING_TURNED_ON_DAYS: X,
        PARTICIPANT_EPHEMERAL_SETTING_TURNED_ON_HOURS: Q,
        PARTICIPANT_EPHEMERAL_SETTING_TURNED_ON_MINUTES: K,
        PARTICIPANT_EPHEMERAL_SETTING_TURNED_ON_SECONDS: j,
        PARTICIPANT_EPHEMERAL_TAKE_SCREENSHOT: ve,
        PARTICIPANT_GOT_DEMOTED: _,
        PARTICIPANT_GOT_PROMOTED: p,
        PARTICIPANT_LIMIT_SHARING_DISABLED: Ht,
        PARTICIPANT_LIMIT_SHARING_ENABLED: Gt,
        PARTICIPANT_MISSED_AUDIO_CALL: Oe,
        PARTICIPANT_MISSED_VIDEO_CALL: We,
        PARTICIPANT_PROMOTED_PARTICIPANT: b,
        PARTICIPANT_PROMOTED_YOU: f,
        PARTICIPANT_REACT_MESSAGE: fe,
        PARTICIPANT_REACT_MESSAGE_IN_GROUP: ge,
        PARTICIPANT_SELF_DEMOTED: v,
        PARTICIPANT_SEND_AI_CONTACT_SHARE: ht,
        PARTICIPANT_SEND_ATTACHMENT: Le,
        PARTICIPANT_SEND_AUDIO: N,
        PARTICIPANT_SEND_BUMP_MESSAGE: Mt,
        PARTICIPANT_SEND_BUMP_MESSAGE_ORIGINAL_UNAVAILABLE_FALLBACK: wt,
        PARTICIPANT_SEND_CONTACT_SHARE: ft,
        PARTICIPANT_SEND_CONTACT_SHARE_FALLBACK: pt,
        PARTICIPANT_SEND_GIF: M,
        PARTICIPANT_SEND_IMAGE: $,
        PARTICIPANT_SEND_LIVE_LOCATION_FALLBACK: lt,
        PARTICIPANT_SEND_LOCATION: ut,
        PARTICIPANT_SEND_LOCATION_FALLBACK: at,
        PARTICIPANT_SEND_MEMORIES_SHARE: Et,
        PARTICIPANT_SEND_NOTE_MENTION_FALLBACK: Dt,
        PARTICIPANT_SEND_POLL_CREATION_FALLBACK: dt,
        PARTICIPANT_SEND_POST_MENTION: It,
        PARTICIPANT_SEND_POST_MENTION_FALLBACK: Rt,
        PARTICIPANT_SEND_STICKER: w,
        PARTICIPANT_SEND_STICKER_RECEIVER_FETCH_MESSAGE_FALLBACK: Ft,
        PARTICIPANT_SEND_STORY_MENTION: bt,
        PARTICIPANT_SEND_STORY_MENTION_FALLBACK: vt,
        PARTICIPANT_SEND_TEXT: D,
        PARTICIPANT_SEND_TEXT_IN_GROUP: x,
        PARTICIPANT_SEND_UNRENDERABLE_MESSAGE_FALLBACK: rt,
        PARTICIPANT_SEND_VIDEO: P,
        PARTICIPANT_SENT_EVENT: Me,
        PARTICIPANT_SENT_POST: $e,
        PARTICIPANT_SENT_REEL: Pe,
        PARTICIPANT_SENT_STORY: Ne,
        PARTICIPANT_SENT_STORY_HIGHLIGHT: Ae,
        PARTICIPANT_STARTED_GROUP_AUDIO_CALL: ze,
        PARTICIPANT_STARTED_GROUP_VIDEO_CALL: Ke,
        PARTICIPANT_UNSENT_MESSAGE: _e,
        PARTICIPANT_VIDEO_CALLED: He,
        RTC_XMA_FALLBACK: $t,
        UNAVAILABLE_SNIPPET: A,
        UNAVAILABLE_STATUS: qt,
        UNAVAILABLE_STORY: Wt,
        UNKNOWN_USER_CREATED_GROUP: c,
        UNKNOWN_USER_EPHEMERAL_RECORD_SCREEN: ye,
        UNKNOWN_USER_EPHEMERAL_SETTING_CHANGE_DAYS: ee,
        UNKNOWN_USER_EPHEMERAL_SETTING_CHANGE_HOURS: Z,
        UNKNOWN_USER_EPHEMERAL_SETTING_CHANGE_MINUTES: J,
        UNKNOWN_USER_EPHEMERAL_SETTING_CHANGE_SECONDS: Y,
        UNKNOWN_USER_EPHEMERAL_SETTING_TURNED_OFF: ue,
        UNKNOWN_USER_EPHEMERAL_SETTING_TURNED_ON_DAYS: U,
        UNKNOWN_USER_EPHEMERAL_SETTING_TURNED_ON_HOURS: q,
        UNKNOWN_USER_EPHEMERAL_SETTING_TURNED_ON_MINUTES: W,
        UNKNOWN_USER_EPHEMERAL_SETTING_TURNED_ON_SECONDS: B,
        UNKNOWN_USER_EPHEMERAL_TAKE_SCREENSHOT: he,
        USER_SEND_ENCRYPTED_MESSAGE_FALLBACK: tt,
        USER_SEND_UNAVAILABLE_MESSAGE_FALLBACK: et,
        VIEW_ONCE_PHOTO_MESSAGE: Ot,
        VIEW_ONCE_VIDEO_MESSAGE: Bt,
        YOU_EPHEMERAL_RECORD_SCREEN: be,
        YOU_EPHEMERAL_SETTING_CHANGE_DAYS: oe,
        YOU_EPHEMERAL_SETTING_CHANGE_HOURS: re,
        YOU_EPHEMERAL_SETTING_CHANGE_MINUTES: ne,
        YOU_EPHEMERAL_SETTING_CHANGE_SECONDS: te,
        YOU_EPHEMERAL_SETTING_TURNED_OFF: ce,
        YOU_EPHEMERAL_SETTING_TURNED_ON_DAYS: z,
        YOU_EPHEMERAL_SETTING_TURNED_ON_HOURS: G,
        YOU_EPHEMERAL_SETTING_TURNED_ON_MINUTES: H,
        YOU_EPHEMERAL_SETTING_TURNED_ON_SECONDS: V,
        YOU_EPHEMERAL_TAKE_SCREENSHOT: Ce,
      });
    ((l.CURRENT_USER_CREATED_GROUP = s),
      (l.CURRENT_USER_SEND_TEXT = R),
      (l.CURRENT_USER_SEND_IMAGE = L),
      (l.CURRENT_USER_SEND_VIDEO = E),
      (l.CURRENT_USER_SEND_AUDIO = k),
      (l.CURRENT_USER_SEND_GIF = I),
      (l.CURRENT_USER_SEND_STICKER = T),
      (l.UNKNOWN_USER_EPHEMERAL_SETTING_TURNED_ON_SECONDS = B),
      (l.UNKNOWN_USER_EPHEMERAL_TAKE_SCREENSHOT = he),
      (l.CURRENT_USER_SEND_ATTACHMENT = Re),
      (l.DUAL_THREAD_CUTOVER_ADMIN_MESSAGE_OTHER_USER_NAME_UNKNOWN = zt),
      (l.DUAL_THREAD_CUTOVER_ADMIN_MESSAGE_SELF_THREAD = jt),
      (l.DUAL_THREAD_CUTOVER_ADMIN_MESSAGE_WITH_OTHER_USER_NAME = Kt),
      (l.LOCALIZATION_TYPE = Qt));
  },
  98,
);
