__d(
  "MCDSTextType",
  ["$InternalEnum"],
  function (t, n, r, o, a, i) {
    var e = n("$InternalEnum")({
        HEADING1: "heading1",
        HEADING2: "heading2",
        HEADING2_EMPHASIZED: "heading2-emphasized",
        HEADING3: "heading3",
        HEADING4: "heading4",
        HEADING5: "heading5",
        HEADING5_DEEMPHASIZED: "heading5-deemphasized",
        HEADING5_EMPHASIZED: "heading5-emphasized",
        HEADING6: "heading6",
        HEADING6_EMPHASIZED: "heading6-emphasized",
        TITLE_LARGE: "title-large",
        TITLE_LARGE_EMPHASIZED: "title-large-emphasized",
        TITLE_SMALL: "title-small",
        TITLE_SMALL_EMPHASIZED: "title-small-emphasized",
        MCDS_H1: "mcds_h1",
        MCDS_H2: "mcds_h2",
        MCDS_H3: "mcds_h3",
        MCDS_TITLE_LARGE: "mcds_title_large",
        MCDS_TITLE_LARGE_EMPHASIZED: "mcds_title_large_emphasized",
        MCDS_TITLE_SMALL: "mcds_title_small",
        MCDS_TITLE_SMALL_EMPHASIZED: "mcds_title_small_emphasized",
        INHERIT: "inherit",
        MCDS_LARGE_BODY: "mcds-large-body",
        MCDS_LARGE_BODY_EMPHASIZED: "mcds-large-body-emphasized",
        MCDS_SMALL_BODY: "mcds-small-body",
        MCDS_SMALL_BODY_EMPHASIZED: "mcds-small-body-emphasized",
        MCDS_LABEL: "mcds-label",
        MCDS_LABEL_EMPHASIZED: "mcds-label-emphasized",
        MCDS_CTA: "mcds-cta",
        MCDS_MICRO_TEXT: "mcds-micro-text",
        MCDS_MICRO_TEXT_EMPHASIZED: "mcds-micro-text-emphasized",
        MCDS_NAV_LINK: "mcds-nav-link",
      }),
      l = e;
    i.default = l;
  },
  66,
);
