__d(
  "MessagingFolderTag",
  [],
  function (t, n, r, o, a, i) {
    var e = Object.freeze({
      INBOX: "inbox",
      OTHER: "other",
      SPAM: "spam",
      PENDING: "pending",
      MONTAGE: "montage",
      HIDDEN: "hidden",
      LEGACY: "legacy",
      DISABLED: "disabled",
      PAGE_BACKGROUND: "page_background",
      PAGE_DONE: "page_done",
      BLOCKED: "blocked",
      COMMUNITY: "community",
      RESTRICTED: "restricted",
      BC_PARTNERSHIP: "bc_partnership",
      E2EE_CUTOVER: "e2ee_cutover",
      E2EE_CUTOVER_ARCHIVED: "e2ee_cutover_archived",
      E2EE_CUTOVER_PENDING: "e2ee_cutover_pending",
      E2EE_CUTOVER_OTHER: "e2ee_cutover_other",
      E2EE_CUTOVER_RESTRICTED: "e2ee_cutover_restricted",
      INTEROP: "interop",
      INTEROP_PENDING: "interop_pending",
      ARCHIVED: "archived",
      AI_ACTIVE: "ai_active",
      SALSA_RESTRICTED: "salsa_restricted",
      MESSENGER_MARKETING_MESSAGE: "messenger_marketing_message",
      SECRET_CONVERSATIONS: "secret_conversations",
      WEBCHAT_PLUGIN: "webchat_plugin",
      NFB_OVERFLOW: "nfb_overflow",
      META_AI_THREAD: "meta_ai_thread",
      META_AI_GROUP_SIDE_CHAT: "meta_ai_group_side_chat",
      META_AI_IG_GROUP_SIDE_CHAT: "meta_ai_ig_group_side_chat",
      META_AI_SUPPORT_THREAD: "meta_ai_support_thread",
      UNKNOWN: "",
    });
    i.default = e;
  },
  66,
);
