__d(
  "MSGDataclassTypes.flow",
  ["$InternalEnum"],
  function (t, n, r, o, a, i) {
    "use strict";
    var e,
      l = (e = n("$InternalEnum"))({
        LlmOutput: "llm_output",
        SendQuery: "send_query",
        StartTyping: "start_typing",
        StopTyping: "stop_typing",
        VideoAboutToFinish: "video_about_to_finish",
      }),
      s = e({ ChooseMultiple: "CHOOSE_MULTIPLE", ChooseOne: "CHOOSE_ONE" }),
      u = e({ VotingEnded: "VOTING_ENDED", VotingOpen: "VOTING_OPEN" }),
      c = e({
        PsiQueryPlan: "PSI_QUERY_PLAN",
        SummarizeInboxFnfMessages: "SUMMARIZE_INBOX_FNF_MESSAGES",
      }),
      d = e({ MetaAi: "META_AI" }),
      m = e({
        Cancelled: "CANCELLED",
        Confirmed: "CONFIRMED",
        Pending: "PENDING",
      }),
      p = e({ Create: "CREATE", Delete: "DELETE", Update: "UPDATE" }),
      _ = e({
        Cancelled: "CANCELLED",
        Confirmed: "CONFIRMED",
        Pending: "PENDING",
      }),
      f = e({ Action: "ACTION", Navigation: "NAVIGATION" }),
      g = e({ End: "END", Start: "START" }),
      h = e({
        CopyToClipboard: "COPY_TO_CLIPBOARD",
        FollowUpPrompt: "FOLLOW_UP_PROMPT",
        SendToChat: "SEND_TO_CHAT",
      }),
      y = e({
        Archive: "ARCHIVE",
        Audio: "AUDIO",
        Document: "DOCUMENT",
        Html: "HTML",
        Markdown: "MARKDOWN",
        Pdf: "PDF",
        Spreadsheet: "SPREADSHEET",
        Svg: "SVG",
      }),
      C = e({
        Comment: "COMMENT",
        Default: "DEFAULT",
        Keyword: "KEYWORD",
        Method: "METHOD",
        Number: "NUMBER",
        Str: "STR",
      }),
      b = e({
        Follow: "FOLLOW",
        Join: "JOIN",
        Leave: "LEAVE",
        Message: "MESSAGE",
        Unfollow: "UNFOLLOW",
      }),
      v = e({
        CalendarEvent: "CALENDAR_EVENT",
        Group: "GROUP",
        Page: "PAGE",
        Person: "PERSON",
      }),
      S = e({ Dot: "DOT", HorizontalLine: "HORIZONTAL_LINE" }),
      R = e({
        CancelReasoning: "CANCEL_REASONING",
        GenerateImage: "GENERATE_IMAGE",
        OpenFullView: "OPEN_FULL_VIEW",
        UpgradeToSubs: "UPGRADE_TO_SUBS",
      }),
      L = e({
        ProjectCreationBack: "PROJECT_CREATION_BACK",
        StartProject: "START_PROJECT",
      }),
      E = e({ Failed: "FAILED", Fetched: "FETCHED", Fetching: "FETCHING" }),
      k = e({ Failed: "FAILED", Generating: "GENERATING", Ready: "READY" }),
      I = e({ Animate: "ANIMATE", Imagine: "IMAGINE", Memu: "MEMU" }),
      T = e({
        Geoblock: "GEOBLOCK",
        MediaLabel: "MEDIA_LABEL",
        PostCover: "POST_COVER",
        PostLabel: "POST_LABEL",
        WarningScreens: "WARNING_SCREENS",
      }),
      D = e({ Pin: "PIN", Radius: "RADIUS" }),
      x = e({ Failed: "FAILED", Fetched: "FETCHED", Fetching: "FETCHING" }),
      $ = e({ End: "END", Start: "START" }),
      P = e({ Circle: "CIRCLE", Square: "SQUARE", Vertical: "VERTICAL" }),
      N = e({ Center: "CENTER", Top: "TOP" }),
      M = e({
        Complete: "COMPLETE",
        Running: "RUNNING",
        Synthesizing: "SYNTHESIZING",
      }),
      w = e({ BigBrain: "BIG_BRAIN", Thinking: "THINKING" }),
      A = e({ BottomSheet: "BOTTOM_SHEET", InThread: "IN_THREAD" }),
      F = e({
        Bing: "BING",
        Brave: "BRAVE",
        Google: "GOOGLE",
        HelpCenter: "HELP_CENTER",
        InHouse: "IN_HOUSE",
        Kss: "KSS",
        Mase: "MASE",
      }),
      O = e({ Closed: "CLOSED", Open: "OPEN" }),
      B = e({
        Cheap: "CHEAP",
        Expensive: "EXPENSIVE",
        Moderate: "MODERATE",
        Splurge: "SPLURGE",
      }),
      W = e({ MarketplaceListing: "MARKETPLACE_LISTING", Place: "PLACE" }),
      q = e({ Done: "DONE", InProgress: "IN_PROGRESS", Pending: "PENDING" }),
      U = e({ Landscape: "LANDSCAPE", Portrait: "PORTRAIT" }),
      V = e({ GroupPost: "GROUP_POST", PagePost: "PAGE_POST" }),
      H = e({ Catalog: "CATALOG", Marketplace: "MARKETPLACE" }),
      G = e({ FbSocialSearch: "FB_SOCIAL_SEARCH" }),
      z = e({
        Completed: "COMPLETED",
        InProgress: "IN_PROGRESS",
        Planned: "PLANNED",
        Stopped: "STOPPED",
      }),
      j = e({
        ContextualQuery: "CONTEXTUAL_QUERY",
        WriteWithAi: "WRITE_WITH_AI",
      }),
      K = e({
        Completed: "COMPLETED",
        Failed: "FAILED",
        Init: "INIT",
        InProgress: "IN_PROGRESS",
        Unknown: "UNKNOWN",
      }),
      Q = e({
        FbGroup: "FB_GROUP",
        FbPage: "FB_PAGE",
        FbProfile: "FB_PROFILE",
        IgProfile: "IG_PROFILE",
        ThreadsProfile: "THREADS_PROFILE",
      }),
      X = e({
        Facebook: "FACEBOOK",
        Instagram: "INSTAGRAM",
        Threads: "THREADS",
      }),
      Y = e({
        CatalogProduct: "CATALOG_PRODUCT",
        FacebookPost: "FACEBOOK_POST",
        InstagramPost: "INSTAGRAM_POST",
        ThirdParty: "THIRD_PARTY",
        ThreadsPost: "THREADS_POST",
        VmGenerated: "VM_GENERATED",
        WearablesAcsActivity: "WEARABLES_ACS_ACTIVITY",
        WearablesAcsJournal: "WEARABLES_ACS_JOURNAL",
      }),
      J = e({
        Answer: "ANSWER",
        Refining: "REFINING",
        Researching: "RESEARCHING",
      }),
      Z = e({
        MetaSearch: "META_SEARCH",
        Thinking: "THINKING",
        WebSearch: "WEB_SEARCH",
      }),
      ee = e({ Details: "DETAILS" }),
      te = e({ Sources: "SOURCES", Steps: "STEPS" }),
      ne = e({ Done: "DONE", Pending: "PENDING", Running: "RUNNING" }),
      re = e({
        AppleHealth: "APPLE_HEALTH",
        Gmail: "GMAIL",
        GoogleCalendar: "GOOGLE_CALENDAR",
        GoogleContacts: "GOOGLE_CONTACTS",
        GoogleHealthConnect: "GOOGLE_HEALTH_CONNECT",
        OutlookCalendar: "OUTLOOK_CALENDAR",
        OutlookContacts: "OUTLOOK_CONTACTS",
        OutlookMail: "OUTLOOK_MAIL",
      }),
      oe = e({
        Initiated: "INITIATED",
        Linked: "LINKED",
        Unlinked: "UNLINKED",
      }),
      ae = e({ AiLookup: "AI_LOOKUP", ContextualMenu: "CONTEXTUAL_MENU" }),
      ie = e({
        Celebrity: "CELEBRITY",
        InfoTerm: "INFO_TERM",
        Movie: "MOVIE",
        Restaurant: "RESTAURANT",
        SportsTeam: "SPORTS_TEAM",
        TvShows: "TV_SHOWS",
      }),
      le = e({ Reasoning: "REASONING", Responding: "RESPONDING" }),
      se = e({
        CriticalUserMessage: "CRITICAL_USER_MESSAGE",
        Default: "DEFAULT",
        NonCriticalAdminXma: "NON_CRITICAL_ADMIN_XMA",
      }),
      ue = e({
        AiLookup: "AI_LOOKUP",
        GenericPrompt: "GENERIC_PROMPT",
        Icebreakers: "ICEBREAKERS",
        MetaAiFabHint: "META_AI_FAB_HINT",
        MetaAiTextConversationStarter: "META_AI_TEXT_CONVERSATION_STARTER",
        MetaAiVoiceConversationStarter: "META_AI_VOICE_CONVERSATION_STARTER",
        NullStatePrompt: "NULL_STATE_PROMPT",
        SuggestedPrompt: "SUGGESTED_PROMPT",
        ThreadviewSuggestedPrompt: "THREADVIEW_SUGGESTED_PROMPT",
        ThreadviewUserInputPrompt: "THREADVIEW_USER_INPUT_PROMPT",
        ThreadSurfingPrompt: "THREAD_SURFING_PROMPT",
        TypeaheadSuggestedPrompt: "TYPEAHEAD_SUGGESTED_PROMPT",
        UserInputPrompt: "USER_INPUT_PROMPT",
      }),
      ce = e({
        AttachmentWithLink: "ATTACHMENT_WITH_LINK",
        CarouselMultiPhoto: "CAROUSEL_MULTI_PHOTO",
        ReshareWithPhoto: "RESHARE_WITH_PHOTO",
        Satp: "SATP",
        SinglePhoto: "SINGLE_PHOTO",
        SinglePhotoSensitiveContent: "SINGLE_PHOTO_SENSITIVE_CONTENT",
        Text: "TEXT",
      }),
      de = e({
        DeleteAndInsertPakeMessage: "DELETE_AND_INSERT_PAKE_MESSAGE",
        DeleteBackupStateOnClient: "DELETE_BACKUP_STATE_ON_CLIENT",
        InitializeRestore: "INITIALIZE_RESTORE",
        IssueCheckBackupStateTask: "ISSUE_CHECK_BACKUP_STATE_TASK",
        LegacyRetroactiveBackup: "LEGACY_RETROACTIVE_BACKUP",
        RotateDeviceKeysStart: "ROTATE_DEVICE_KEYS_START",
        SyncDeviceCreationTimestamp: "SYNC_DEVICE_CREATION_TIMESTAMP",
        UpdateInitializeRestoreResult: "UPDATE_INITIALIZE_RESTORE_RESULT",
        UpdatePbqWithNeedsBackupUploadStatus:
          "UPDATE_PBQ_WITH_NEEDS_BACKUP_UPLOAD_STATUS",
        UpsertReenrollmentTrigger: "UPSERT_REENROLLMENT_TRIGGER",
        UpsertStatusTrigger: "UPSERT_STATUS_TRIGGER",
      }),
      me = e({ Message: "MESSAGE", Thread: "THREAD" }),
      pe = e({
        RemoveBackupItem: "REMOVE_BACKUP_ITEM",
        UpsertBackupItem: "UPSERT_BACKUP_ITEM",
      }),
      _e = e({
        Echo: "ECHO",
        EncryptedPlaceholder: "ENCRYPTED_PLACEHOLDER",
        Open: "OPEN",
        Protobuf: "PROTOBUF",
      }),
      fe = e({
        BackupNotFound: "BACKUP_NOT_FOUND",
        ClientNotSupported: "CLIENT_NOT_SUPPORTED",
        DecryptionFailed: "DECRYPTION_FAILED",
        Unknown: "UNKNOWN",
      }),
      ge = e({
        InfiniteRetroactive: "INFINITE_RETROACTIVE",
        Realtime: "REALTIME",
        RealtimeDelayed: "REALTIME_DELAYED",
        Restore: "RESTORE",
        Retroactive: "RETROACTIVE",
        Retry: "RETRY",
      }),
      he = e({ After: "AFTER", Before: "BEFORE" }),
      ye = e({
        ActionLog: "ACTION_LOG",
        Audio: "AUDIO",
        DisappearingMessage: "DISAPPEARING_MESSAGE",
        Ephemeral: "EPHEMERAL",
        File: "FILE",
        Gif: "GIF",
        Permanent: "PERMANENT",
        Photo: "PHOTO",
        Raven: "RAVEN",
        RavenPermanent: "RAVEN_PERMANENT",
        RavenReadOnce: "RAVEN_READ_ONCE",
        RavenReplayable: "RAVEN_REPLAYABLE",
        RavenReplayed: "RAVEN_REPLAYED",
        RavenSeen: "RAVEN_SEEN",
        ShareIgClips: "SHARE_IG_CLIPS",
        ShareIgMedia: "SHARE_IG_MEDIA",
        ShareLink: "SHARE_LINK",
        Shh: "SHH",
        StoryReply: "STORY_REPLY",
        UnreadRaven: "UNREAD_RAVEN",
        Video: "VIDEO",
      }),
      Ce = e({
        Fts: "FTS",
        HistoryRestore: "HISTORY_RESTORE",
        MpsReadApis: "MPS_READ_APIS",
        NewMemberExport: "NEW_MEMBER_EXPORT",
        Reporting: "REPORTING",
      }),
      be = e({
        AlreadyUploaded: "ALREADY_UPLOADED",
        NeedsUpload: "NEEDS_UPLOAD",
        NotApplicable: "NOT_APPLICABLE",
      }),
      ve = e({
        PermanentFailure: "PERMANENT_FAILURE",
        RetryableException: "RETRYABLE_EXCEPTION",
        Success: "SUCCESS",
      }),
      Se = e({ Fbn: "FBN", Instamadillo: "INSTAMADILLO", Unknown: "UNKNOWN" }),
      Re = e({
        GetMealDetails: "GET_MEAL_DETAILS",
        SuggestSimilarMeals: "SUGGEST_SIMILAR_MEALS",
        UpdateIngredients: "UPDATE_INGREDIENTS",
      }),
      Le = e({
        Landscape: "LANDSCAPE",
        Square: "SQUARE",
        Vertical: "VERTICAL",
      }),
      Ee = e({
        EditPrompt: "EDIT_PROMPT",
        NewMessage: "NEW_MESSAGE",
        Regenerate: "REGENERATE",
      }),
      ke = e({ Assistant: "ASSISTANT", User: "USER" }),
      Ie = e({
        CanFeedbackOnBotResponse: "CAN_FEEDBACK_ON_BOT_RESPONSE",
        CanReadAloud: "CAN_READ_ALOUD",
        Copy: "COPY",
      }),
      Te = e({
        Memu: "MEMU",
        Synthetic: "SYNTHETIC",
        Unknown: "UNKNOWN",
        UserUploaded: "USER_UPLOADED",
      }),
      De = e({ AskMetaAi: "ASK_META_AI", Summarize: "SUMMARIZE" }),
      xe = e({
        Address: "ADDRESS",
        FindNextGame: "FIND_NEXT_GAME",
        GetInfo: "GET_INFO",
        GetRestaurantInfo: "GET_RESTAURANT_INFO",
        LatestNews: "LATEST_NEWS",
        MenuHighlights: "MENU_HIGHLIGHTS",
        ResponseCard: "RESPONSE_CARD",
        Reviews: "REVIEWS",
        WhereToWatch: "WHERE_TO_WATCH",
      }),
      $e = e({
        Celebrity: "CELEBRITY",
        Movie: "MOVIE",
        Restaurant: "RESTAURANT",
        SportsTeam: "SPORTS_TEAM",
        TvShows: "TV_SHOWS",
      }),
      Pe = e({
        AiAnimatedPhoto: "AI_ANIMATED_PHOTO",
        AiMeme: "AI_MEME",
        AiMusicSongGen: "AI_MUSIC_SONG_GEN",
        AiVoiceNotes: "AI_VOICE_NOTES",
        ForwardedAi: "FORWARDED_AI",
        HiddenMetadata: "HIDDEN_METADATA",
        Imagine: "IMAGINE",
        MagicModBackdrop: "MAGIC_MOD_BACKDROP",
        MagicModRestyle: "MAGIC_MOD_RESTYLE",
        Memu: "MEMU",
        ThirdPartyAi: "THIRD_PARTY_AI",
        ThirdPartyAiEdited: "THIRD_PARTY_AI_EDITED",
      }),
      Ne = e({
        Compacting: "COMPACTING",
        MakingSomething: "MAKING_SOMETHING",
        Online: "ONLINE",
        OutOfCredits: "OUT_OF_CREDITS",
        Responding: "RESPONDING",
        WaitingForSubagents: "WAITING_FOR_SUBAGENTS",
        Working: "WORKING",
      }),
      Me = e({
        MarketplaceXmatCallFunction: "MARKETPLACE_XMAT_CALL_FUNCTION",
        MarketplaceXmaCallFunction: "MARKETPLACE_XMA_CALL_FUNCTION",
        ViewAllAiTasks: "VIEW_ALL_AI_TASKS",
        ViewSingleAiTask: "VIEW_SINGLE_AI_TASK",
        WatchPartySetUpNextGame: "WATCH_PARTY_SET_UP_NEXT_GAME",
        XmaCrmOptIn: "XMA_CRM_OPT_IN",
        XmaDailyGameChallengeJoin: "XMA_DAILY_GAME_CHALLENGE_JOIN",
        XmaDailyGameChallengeJoinAndPlay:
          "XMA_DAILY_GAME_CHALLENGE_JOIN_AND_PLAY",
        XmaDailyGameChallengePlay: "XMA_DAILY_GAME_CHALLENGE_PLAY",
        XmaDailyGameChallengeSeeLeaderboard:
          "XMA_DAILY_GAME_CHALLENGE_SEE_LEADERBOARD",
        XmaDisabledCta: "XMA_DISABLED_CTA",
        XmaGamePlay: "XMA_GAME_PLAY",
        XmaGenAiSearchPluginResponseSources:
          "XMA_GEN_AI_SEARCH_PLUGIN_RESPONSE_SOURCES",
        XmaMetaAiDigestSeeSummary: "XMA_META_AI_DIGEST_SEE_SUMMARY",
        XmaMetaAiLocation: "XMA_META_AI_LOCATION",
        XmaMetaAiLookupEntity: "XMA_META_AI_LOOKUP_ENTITY",
        XmaMetaAiReminders: "XMA_META_AI_REMINDERS",
        XmaMetaAiSingleSubscription: "XMA_META_AI_SINGLE_SUBSCRIPTION",
        XmaMetaAiSubscriptions: "XMA_META_AI_SUBSCRIPTIONS",
        XmaMetaAiTask: "XMA_META_AI_TASK",
        XmaMomentAddedView: "XMA_MOMENT_ADDED_VIEW",
        XmaMsgExternalLinkShare: "XMA_MSG_EXTERNAL_LINK_SHARE",
        XmaMusicArtist: "XMA_MUSIC_ARTIST",
        XmaOpenNative: "XMA_OPEN_NATIVE",
        XmaP2POpgTransfer: "XMA_P2P_OPG_TRANSFER",
        XmaSharedAlbumViewer: "XMA_SHARED_ALBUM_VIEWER",
        XmaWebUrl: "XMA_WEB_URL",
      }),
      we = e({
        NoBranding: "NO_BRANDING",
        PaidPartnership: "PAID_PARTNERSHIP",
      }),
      Ae = e({
        Imagine: "IMAGINE",
        Imagineme: "IMAGINEME",
        Imaginev2: "IMAGINEV2",
      }),
      Fe = e({ Animate: "ANIMATE", AnimateImagineme: "ANIMATE_IMAGINEME" }),
      Oe = e({
        AiAnimatedPhoto: "AI_ANIMATED_PHOTO",
        AiGeneratedSticker: "AI_GENERATED_STICKER",
        AiMusicSongGen: "AI_MUSIC_SONG_GEN",
        AiSummaryBottomSheet: "AI_SUMMARY_BOTTOM_SHEET",
        AnimatedAiSticker: "ANIMATED_AI_STICKER",
        Avatar: "AVATAR",
        AvatarStyle_1: "AVATAR_STYLE_1",
        AvatarStyle_2: "AVATAR_STYLE_2",
        ContentBasedSparks: "CONTENT_BASED_SPARKS",
        ContentConversationStarter: "CONTENT_CONVERSATION_STARTER",
        ContentMention: "CONTENT_MENTION",
        ContentReply: "CONTENT_REPLY",
        ContentShare: "CONTENT_SHARE",
        ConversationStarter: "CONVERSATION_STARTER",
        DisappearingMessage: "DISAPPEARING_MESSAGE",
        EditMessage: "EDIT_MESSAGE",
        Hotlike: "HOTLIKE",
        IncludesLink: "INCLUDES_LINK",
        IncludesOffPlatformContent: "INCLUDES_OFF_PLATFORM_CONTENT",
        IncludesOnPlatformContent: "INCLUDES_ON_PLATFORM_CONTENT",
        InvokesGenAiResponse: "INVOKES_GEN_AI_RESPONSE",
        IsDialtone: "IS_DIALTONE",
        IsNotDialtone: "IS_NOT_DIALTONE",
        LightweightInteractionAsStoryReply:
          "LIGHTWEIGHT_INTERACTION_AS_STORY_REPLY",
        MagicModImage: "MAGIC_MOD_IMAGE",
        Mention: "MENTION",
        MessageForward: "MESSAGE_FORWARD",
        MessageReply: "MESSAGE_REPLY",
        MessageReshare: "MESSAGE_RESHARE",
        MetaAiEntitySuggestedPrompts: "META_AI_ENTITY_SUGGESTED_PROMPTS",
        MetaAiIntents: "META_AI_INTENTS",
        MetaAiReminder: "META_AI_REMINDER",
        MetaAiSubscription: "META_AI_SUBSCRIPTION",
        MsysSend: "MSYS_SEND",
        MultitabEnv: "MULTITAB_ENV",
        NoteReply: "NOTE_REPLY",
        OffPlatform: "OFF_PLATFORM",
        OnPlatform: "ON_PLATFORM",
        PostReply: "POST_REPLY",
        PowerUp: "POWER_UP",
        QuicksnapReply: "QUICKSNAP_REPLY",
        Raven: "RAVEN",
        SentFromGenAiBot: "SENT_FROM_GEN_AI_BOT",
        ShareOfOriginalUserContent: "SHARE_OF_ORIGINAL_USER_CONTENT",
        SocialSticker: "SOCIAL_STICKER",
        StoryReply: "STORY_REPLY",
        Superlative: "SUPERLATIVE",
        SuperReact: "SUPER_REACT",
        ThirdPartyReshare: "THIRD_PARTY_RESHARE",
        VanishMode: "VANISH_MODE",
        WriteWithMetaAi: "WRITE_WITH_META_AI",
        ZeroBalanceDetected: "ZERO_BALANCE_DETECTED",
      }),
      Be = e({
        Imagine: "IMAGINE",
        ImagineRestyle: "IMAGINE_RESTYLE",
        Memu: "MEMU",
      }),
      We = e({ Reminder: "REMINDER", Subscription: "SUBSCRIPTION" }),
      qe = e({
        Image: "image",
        Link_1p: "link_1p",
        Link_3p: "link_3p",
        Text: "text",
        Voice: "voice",
      }),
      Ue = e({ MessageBreaks: "MESSAGE_BREAKS", SideBySide: "SIDE_BY_SIDE" }),
      Ve = e({
        FathersDay: "FATHERS_DAY",
        FriendshipDay: "FRIENDSHIP_DAY",
        Graduation: "GRADUATION",
        JulyFourth: "JULY_FOURTH",
        MothersDay: "MOTHERS_DAY",
        NationalSelfie: "NATIONAL_SELFIE",
        PhIndependenceDay: "PH_INDEPENDENCE_DAY",
      }),
      He = e({ Attribution: "ATTRIBUTION", Birthday: "BIRTHDAY" }),
      Ge = e({
        Clip: "CLIP",
        Comment: "COMMENT",
        Feed: "FEED",
        Live: "LIVE",
        LocationShare: "LOCATION_SHARE",
        MediaNote: "MEDIA_NOTE",
        Note: "NOTE",
        Profile: "PROFILE",
        ReelsAudio: "REELS_AUDIO",
        SocialContext: "SOCIAL_CONTEXT",
        Story: "STORY",
        StoryHighlight: "STORY_HIGHLIGHT",
      }),
      ze = e({ Mention: "MENTION", Reply: "REPLY" }),
      je = e({
        Mention: "MENTION",
        React: "REACT",
        Reply: "REPLY",
        Share: "SHARE",
      }),
      Ke = e({
        AnimatedEmoji: "ANIMATED_EMOJI",
        Genmoji: "GENMOJI",
        Metamoji: "METAMOJI",
        Undefined: "UNDEFINED",
      }),
      Qe = e({
        GenAiGetInfo: "GEN_AI_GET_INFO",
        GenAiReminder: "GEN_AI_REMINDER",
        GenAiThreadSurfing: "GEN_AI_THREAD_SURFING",
      }),
      Xe = e({
        AnimatedThankImage: "ANIMATED_THANK_IMAGE",
        AnimatedThankImageWithTextMessage:
          "ANIMATED_THANK_IMAGE_WITH_TEXT_MESSAGE",
        Unknown: "UNKNOWN",
      }),
      Ye = e({
        AutoReply: "AUTO_REPLY",
        AutoReplyV2: "AUTO_REPLY_V2",
        BulkReply: "BULK_REPLY",
        Unknown: "UNKNOWN",
      }),
      Je = e({
        AttachmentPreviewHeaderMedia: "ATTACHMENT_PREVIEW_HEADER_MEDIA",
        AttachmentPreviewMedia: "ATTACHMENT_PREVIEW_MEDIA",
      }),
      Ze = e({ Photo: "PHOTO" }),
      et = e({ Messages: "MESSAGES", Retro: "RETRO", Simple: "SIMPLE" }),
      tt = e({ Messages: "MESSAGES", Retro: "RETRO", Simple: "SIMPLE" }),
      nt = e({
        Accepted: "ACCEPTED",
        Deleted: "DELETED",
        Unactioned: "UNACTIONED",
      }),
      rt = e({
        CommentMentions: "COMMENT_MENTIONS",
        Ctm: "CTM",
        Cts: "CTS",
        Dating: "DATING",
        FbmInbox: "FBM_INBOX",
        FbGroups: "FB_GROUPS",
        FbHelpCenterXsMetaAi: "FB_HELP_CENTER_XS_META_AI",
        FbNotes: "FB_NOTES",
        FbSearch: "FB_SEARCH",
        Feed: "FEED",
        GenAiAssistant: "GEN_AI_ASSISTANT",
        GenAiFlAshImagine: "GEN_AI_FlASH_IMAGINE",
        GenAiLocation: "GEN_AI_LOCATION",
        GenAiMultiModal: "GEN_AI_MULTI_MODAL",
        GenAiSuggestedPrompts: "GEN_AI_SUGGESTED_PROMPTS",
        IgComment: "IG_COMMENT",
        IgExternalLink: "IG_EXTERNAL_LINK",
        IgFeed: "IG_FEED",
        IgLive: "IG_LIVE",
        IgNotes: "IG_NOTES",
        IgProfile: "IG_PROFILE",
        IgReels: "IG_REELS",
        IgStory: "IG_STORY",
        MagicMessenger: "MAGIC_MESSENGER",
        Mp: "MP",
        ProductHighlights: "PRODUCT_HIGHLIGHTS",
        Profile: "PROFILE",
        Psrib: "PSRIB",
        Rta: "RTA",
        Sharesheet: "SHARESHEET",
        Shorts: "SHORTS",
        SpectraAction: "SPECTRA_ACTION",
        Srib: "SRIB",
        Ufi: "UFI",
        Watch: "WATCH",
        ZorroMessage: "ZORRO_MESSAGE",
      }),
      ot = e({ MsgrE2EeGenai: "MSGR_E2EE_GENAI" }),
      at = e({
        Grouppost: "GROUPPOST",
        Momentlink: "MOMENTLINK",
        Shareurl: "SHAREURL",
        Statusupdate: "STATUSUPDATE",
        Unifiedresponse: "UNIFIEDRESPONSE",
      }),
      it = e({
        DxmaPlaceholder: "DXMA_PLACEHOLDER",
        ExpiredPlaceholder: "EXPIRED_PLACEHOLDER",
        Grid: "GRID",
        Hscroll: "HSCROLL",
        Layered: "LAYERED",
        PilePrompt: "PILE_PROMPT",
        Placeholder: "PLACEHOLDER",
        Portrait: "PORTRAIT",
        SharedStack: "SHARED_STACK",
        Single: "SINGLE",
        Stack: "STACK",
        StackCard: "STACK_CARD",
        StandardDxma: "STANDARD_DXMA",
        Xcenter: "XCENTER",
      }),
      lt = e({
        Bump: "BUMP",
        Mention: "MENTION",
        Reply: "REPLY",
        Share: "SHARE",
      }),
      st = e({
        AiWidget: "AI_WIDGET",
        GamePrediction: "GAME_PREDICTION",
        HorizonWeelXma: "HORIZON_WEEL_XMA",
        MomentLink: "MOMENT_LINK",
        ThreadsPostShare: "THREADS_POST_SHARE",
      }),
      ut = e({ XmaWebUrl: "XMA_WEB_URL" }),
      ct = e({ Mention: "MENTION", Reply: "REPLY" }),
      dt = e({
        Note: "NOTE",
        Prompt: "PROMPT",
        PromptResponse: "PROMPT_RESPONSE",
        Status: "STATUS",
      }),
      mt = e({
        FbContentShare: "FB_CONTENT_SHARE",
        FeelingsNote: "FEELINGS_NOTE",
        GameNote: "GAME_NOTE",
        GifNote: "GIF_NOTE",
        Marketplace: "MARKETPLACE",
        MoodsNote: "MOODS_NOTE",
        MusicNoteMusicOnly: "MUSIC_NOTE_MUSIC_ONLY",
        MusicNoteWithText: "MUSIC_NOTE_WITH_TEXT",
        PollNote: "POLL_NOTE",
        Status: "STATUS",
        TextNote: "TEXT_NOTE",
      }),
      pt = e({ Image: "IMAGE", Other: "OTHER", Video: "VIDEO" }),
      _t = e({
        AntiValentines: "ANTI_VALENTINES",
        AvatarAngry: "AVATAR_ANGRY",
        AvatarCry: "AVATAR_CRY",
        AvatarLaugh: "AVATAR_LAUGH",
        AvatarLove: "AVATAR_LOVE",
        Celebration: "CELEBRATION",
        Fire: "FIRE",
        Giftwrap: "GIFTWRAP",
        Halloween: "HALLOWEEN",
        Love: "LOVE",
        NewYears: "NEW_YEARS",
        NomNomDash: "NOM_NOM_DASH",
        ValentinesDay: "VALENTINES_DAY",
      }),
      ft = e({
        BasicSuperReactAnimation: "BASIC_SUPER_REACT_ANIMATION",
        FbEmoji: "FB_EMOJI",
        None: "NONE",
        NonDefaultEmoji: "NON_DEFAULT_EMOJI",
      }),
      gt = e({ Media: "MEDIA", Text: "TEXT" }),
      ht = e({
        Classifier: "CLASSIFIER",
        ReactiveEnforcement: "REACTIVE_ENFORCEMENT",
        RecipientParent: "RECIPIENT_PARENT",
        SenderParent: "SENDER_PARENT",
      }),
      yt = e({ Restore: "RESTORE", Takedown: "TAKEDOWN" }),
      Ct = e({
        PermanentDelete: "PERMANENT_DELETE",
        SoftDeleteWithoutAppeal: "SOFT_DELETE_WITHOUT_APPEAL",
        SoftDeleteWithoutAppealParentUnviewable:
          "SOFT_DELETE_WITHOUT_APPEAL_PARENT_UNVIEWABLE",
        SoftDeleteWithAppeal: "SOFT_DELETE_WITH_APPEAL",
        SoftDeleteWithAppealParentUnviewable:
          "SOFT_DELETE_WITH_APPEAL_PARENT_UNVIEWABLE",
        Unknown: "UNKNOWN",
      }),
      bt = e({
        FiveOptionStarRating: "FIVE_OPTION_STAR_RATING",
        IgTwoOptionCombined: "IG_TWO_OPTION_COMBINED",
        TwoOptionCombined: "TWO_OPTION_COMBINED",
        Unknown: "UNKNOWN",
      }),
      vt = e({
        AntiBully: "ANTI_BULLY",
        Event: "EVENT",
        Fundraiser: "FUNDRAISER",
        Instagram: "INSTAGRAM",
        Location: "LOCATION",
        Page: "PAGE",
        People: "PEOPLE",
        Product: "PRODUCT",
        ResharedContent: "RESHARED_CONTENT",
        ResharedPost: "RESHARED_POST",
        Unknown: "UNKNOWN",
      }),
      St = e({
        AboveKeyboardEmojiLightWeight: "ABOVE_KEYBOARD_EMOJI_LIGHT_WEIGHT",
        AboveKeyboardSuggestedEmoji: "ABOVE_KEYBOARD_SUGGESTED_EMOJI",
        AboveKeyboardSuggestedEmojiText: "ABOVE_KEYBOARD_SUGGESTED_EMOJI_TEXT",
        AboveKeyboardSuggestedText: "ABOVE_KEYBOARD_SUGGESTED_TEXT",
        Avatar: "AVATAR",
        GifLightWeight: "GIF_LIGHT_WEIGHT",
        PostLwrSuggestedReply: "POST_LWR_SUGGESTED_REPLY",
        QuickEmoji: "QUICK_EMOJI",
        QuickEmojiPalette: "QUICK_EMOJI_PALETTE",
        StickerLightWeight: "STICKER_LIGHT_WEIGHT",
        SuggestedEmoji: "SUGGESTED_EMOJI",
        SuggestedEmojiText: "SUGGESTED_EMOJI_TEXT",
        SuggestedReply: "SUGGESTED_REPLY",
        SuggestedText: "SUGGESTED_TEXT",
        Unspecified: "UNSPECIFIED",
        WriteWithAi: "WRITE_WITH_AI",
      }),
      Rt = e({
        Generating: "GENERATING",
        Imagining: "IMAGINING",
        RequestStart: "REQUEST_START",
        Searching: "SEARCHING",
        StreamingImage: "STREAMING_IMAGE",
        UnderstandingImage: "UNDERSTANDING_IMAGE",
      }),
      Lt = e({
        BanUser: "BAN_USER",
        HideMessage: "HIDE_MESSAGE",
        RemoveMessage: "REMOVE_MESSAGE",
        RemoveUser: "REMOVE_USER",
        ReportMessage: "REPORT_MESSAGE",
        SuspendUser: "SUSPEND_USER",
      }),
      Et = e({ Bar: "BAR", Baz: "BAZ", Foo: "FOO" }),
      kt = e({ Bar: "BAR", Baz: "BAZ", Foo: "FOO" }),
      It = e({
        Error: "ERROR",
        Success: "SUCCESS",
        Transcribing: "TRANSCRIBING",
        UnsupportedLanguage: "UNSUPPORTED_LANGUAGE",
        Untranscribed: "UNTRANSCRIBED",
      }),
      Tt = e({
        Chat: "CHAT",
        Faq: "FAQ",
        Other: "OTHER",
        Post: "POST",
        Product: "PRODUCT",
        Unknown: "UNKNOWN",
      }),
      Dt = e({
        Chat: "CHAT",
        Faq: "FAQ",
        Other: "OTHER",
        Post: "POST",
        Pricelist: "PRICELIST",
        Product: "PRODUCT",
        Unknown: "UNKNOWN",
      }),
      xt = e({
        Comment: "COMMENT",
        Default: "DEFAULT",
        Keyword: "KEYWORD",
        Method: "METHOD",
        Number: "NUMBER",
        Str: "STR",
      }),
      $t = e({ Chevron: "CHEVRON" }),
      Pt = e({ Circle: "CIRCLE", Square: "SQUARE" }),
      Nt = e({ Album: "ALBUM", Clips: "CLIPS", Video: "VIDEO" }),
      Mt = e({
        FbCommentMentionShare: "FB_COMMENT_MENTION_SHARE",
        FbEvent: "FB_EVENT",
        FbFeedPostPrivateReply: "FB_FEED_POST_PRIVATE_REPLY",
        FbFeedPostReactionReply: "FB_FEED_POST_REACTION_REPLY",
        FbFeedProductShare: "FB_FEED_PRODUCT_SHARE",
        FbFeedShare: "FB_FEED_SHARE",
        FbFeedVideoShare: "FB_FEED_VIDEO_SHARE",
        FbGamingCustomUpdate: "FB_GAMING_CUSTOM_UPDATE",
        FbPostMention: "FB_POST_MENTION",
        FbProducerStoryReply: "FB_PRODUCER_STORY_REPLY",
        FbShort: "FB_SHORT",
        FbStoryMention: "FB_STORY_MENTION",
        FbStoryReply: "FB_STORY_REPLY",
        FbStoryShare: "FB_STORY_SHARE",
        IgClipsShare: "IG_CLIPS_SHARE",
        IgExternalLink: "IG_EXTERNAL_LINK",
        IgIgtvShare: "IG_IGTV_SHARE",
        IgMediaShare: "IG_MEDIA_SHARE",
        IgMultipostShare: "IG_MULTIPOST_SHARE",
        IgProfileShare: "IG_PROFILE_SHARE",
        IgReceiverFetch: "IG_RECEIVER_FETCH",
        IgShopShare: "IG_SHOP_SHARE",
        IgSingleVideoPostShare: "IG_SINGLE_VIDEO_POST_SHARE",
        IgStoryHighlightReaction: "IG_STORY_HIGHLIGHT_REACTION",
        IgStoryHighlightReply: "IG_STORY_HIGHLIGHT_REPLY",
        IgStoryPhotoHighlightShare: "IG_STORY_PHOTO_HIGHLIGHT_SHARE",
        IgStoryPhotoMention: "IG_STORY_PHOTO_MENTION",
        IgStoryPhotoShare: "IG_STORY_PHOTO_SHARE",
        IgStoryReaction: "IG_STORY_REACTION",
        IgStoryReply: "IG_STORY_REPLY",
        IgStoryVideoHighlightShare: "IG_STORY_VIDEO_HIGHLIGHT_SHARE",
        IgStoryVideoMention: "IG_STORY_VIDEO_MENTION",
        IgStoryVideoShare: "IG_STORY_VIDEO_SHARE",
        IgTextPostAppShare: "IG_TEXT_POST_APP_SHARE",
        LiveLocation: "LIVE_LOCATION",
        MsgAiBotSearchResult: "MSG_AI_BOT_SEARCH_RESULT",
        MsgAiContact: "MSG_AI_CONTACT",
        MsgContact: "MSG_CONTACT",
        MsgEarlyAccessFbShare: "MSG_EARLY_ACCESS_FB_SHARE",
        MsgExternalLinkShare: "MSG_EXTERNAL_LINK_SHARE",
        MsgFile: "MSG_FILE",
        MsgGamePrediction: "MSG_GAME_PREDICTION",
        MsgGenAi_1PSearchResult: "MSG_GEN_AI_1P_SEARCH_RESULT",
        MsgGenAiMemuOnboardingResponse: "MSG_GEN_AI_MEMU_ONBOARDING_RESPONSE",
        MsgGenAiReminder: "MSG_GEN_AI_REMINDER",
        MsgGenAiRichResponse: "MSG_GEN_AI_RICH_RESPONSE",
        MsgGenAiSearchPluginResponse: "MSG_GEN_AI_SEARCH_PLUGIN_RESPONSE",
        MsgGenAiSubscription: "MSG_GEN_AI_SUBSCRIPTION",
        MsgGenAiTask: "MSG_GEN_AI_TASK",
        MsgIgMediaShare: "MSG_IG_MEDIA_SHARE",
        MsgLocationSharingDeprecated: "MSG_LOCATION_SHARING_DEPRECATED",
        MsgLocationSharingV2: "MSG_LOCATION_SHARING_V2",
        MsgManusGrowthReferral: "MSG_MANUS_GROWTH_REFERRAL",
        MsgMemoriesShare: "MSG_MEMORIES_SHARE",
        MsgMusicSticker: "MSG_MUSIC_STICKER",
        MsgOpgP2PPayment: "MSG_OPG_P2P_PAYMENT",
        MsgP2PPayment: "MSG_P2P_PAYMENT",
        MsgPhoneNumber: "MSG_PHONE_NUMBER",
        MsgPrivateXma: "MSG_PRIVATE_XMA",
        MsgReceiverFetch: "MSG_RECEIVER_FETCH",
        MsgReceiverFetchFallback: "MSG_RECEIVER_FETCH_FALLBACK",
        MsgReelsList: "MSG_REELS_LIST",
        MsgSharedAlbum: "MSG_SHARED_ALBUM",
        MsgSocialCueMemories: "MSG_SOCIAL_CUE_MEMORIES",
        MsgSupervisionInvite: "MSG_SUPERVISION_INVITE",
        None: "NONE",
        OcAvatarStaticSticker: "OC_AVATAR_STATIC_STICKER",
        RtcAudioCall: "RTC_AUDIO_CALL",
        RtcGroupAudioCall: "RTC_GROUP_AUDIO_CALL",
        RtcGroupVideoCall: "RTC_GROUP_VIDEO_CALL",
        RtcMissedAudioCall: "RTC_MISSED_AUDIO_CALL",
        RtcMissedGroupAudioCall: "RTC_MISSED_GROUP_AUDIO_CALL",
        RtcMissedGroupVideoCall: "RTC_MISSED_GROUP_VIDEO_CALL",
        RtcMissedVideoCall: "RTC_MISSED_VIDEO_CALL",
        RtcOngoingAudioCall: "RTC_ONGOING_AUDIO_CALL",
        RtcOngoingVideoCall: "RTC_ONGOING_VIDEO_CALL",
        RtcVideoCall: "RTC_VIDEO_CALL",
        Test: "TEST",
      }),
      wt = e({
        ChevronDown: "CHEVRON_DOWN",
        DotsThreeHorizontal: "DOTS_THREE_HORIZONTAL",
        Fb: "FB",
        FbAlwaysWhite: "FB_ALWAYS_WHITE",
        FbInfoSmall: "FB_INFO_SMALL",
        None: "NONE",
      }),
      At = e({
        AutoPlayable: "AUTO_PLAYABLE",
        AutoPlayableWithAspectRatio: "AUTO_PLAYABLE_WITH_ASPECT_RATIO",
        BlurredImage: "BLURRED_IMAGE",
        BlurredPlayable: "BLURRED_PLAYABLE",
        Default: "DEFAULT",
        ImageWithPlayButton: "IMAGE_WITH_PLAY_BUTTON",
        InformTreatmentWithLabel: "INFORM_TREATMENT_WITH_LABEL",
        InformTreatmentWithWarningScreen:
          "INFORM_TREATMENT_WITH_WARNING_SCREEN",
        P2PPreviewImageWithTextOverlay: "P2P_PREVIEW_IMAGE_WITH_TEXT_OVERLAY",
        Placeholder: "PLACEHOLDER",
        Playable: "PLAYABLE",
        YoutubePlayer: "YOUTUBE_PLAYER",
      }),
      Ft = e({
        Accepted: "ACCEPTED",
        AlreadyPlayed: "ALREADY_PLAYED",
        Completed: "COMPLETED",
        Expired: "EXPIRED",
        Invited: "INVITED",
      }),
      Ot = e({
        Arrived: "ARRIVED",
        Cancelled: "CANCELLED",
        Delayed: "DELAYED",
        Departed: "DEPARTED",
        OnTime: "ON_TIME",
        Unknown: "UNKNOWN",
      }),
      Bt = e({ Draw: "DRAW", Option1: "OPTION1", Option2: "OPTION2" }),
      Wt = e({ Vote: "VOTE" }),
      qt = e({
        MediaLabel: "MEDIA_LABEL",
        Misinformation: "MISINFORMATION",
        PostCover: "POST_COVER",
        PostLabel: "POST_LABEL",
        Private: "PRIVATE",
        Sensitive: "SENSITIVE",
        WarningScreens: "WARNING_SCREENS",
      }),
      Ut = e({
        Blur: "BLUR",
        Collage: "COLLAGE",
        InstagramIcon: "INSTAGRAM_ICON",
        Live: "LIVE",
        MessengerIcon: "MESSENGER_ICON",
        MultiPhoto: "MULTI_PHOTO",
        None: "NONE",
        Photo: "PHOTO",
        Pill: "PILL",
        ReelsIcon: "REELS_ICON",
        Video: "VIDEO",
        YoutubeShorts: "YOUTUBE_SHORTS",
        YoutubeVideo: "YOUTUBE_VIDEO",
      }),
      Vt = e({
        Grid: "GRID",
        Hscroll: "HSCROLL",
        Portrait: "PORTRAIT",
        SharedStack: "SHARED_STACK",
        Single: "SINGLE",
        Vstack: "VSTACK",
      }),
      Ht = e({
        Active: "ACTIVE",
        Ended: "ENDED",
        Expired: "EXPIRED",
        Started: "STARTED",
      }),
      Gt = e({
        BlurredCircle: "BLURRED_CIRCLE",
        Default: "DEFAULT",
        DefaultWithGradient: "DEFAULT_WITH_GRADIENT",
        Rounded: "ROUNDED",
        TemplateAsset: "TEMPLATE_ASSET",
      }),
      zt = e({ Paypal: "PAYPAL", Venmo: "VENMO" }),
      jt = e({ Payment: "PAYMENT", Request: "REQUEST" }),
      Kt = e({
        LiveVideo: "LIVE_VIDEO",
        None: "NONE",
        ShortsVideo: "SHORTS_VIDEO",
        VodVideo: "VOD_VIDEO",
      }),
      Qt = e({ Ended: "ENDED", Missed: "MISSED", Started: "STARTED" }),
      Xt = e({ Audio: "AUDIO", Video: "VIDEO" }),
      Yt = e({ Default: "DEFAULT", Overlay: "OVERLAY" }),
      Jt = e({ Bold: "BOLD", Regular: "REGULAR" }),
      Zt = e({ Daily: "DAILY", Weekly: "WEEKLY" }),
      en = e({
        Default: "DEFAULT",
        ExternalLinkIcon: "EXTERNAL_LINK_ICON",
        FacebookIcon: "FACEBOOK_ICON",
        InstagramIcon: "INSTAGRAM_ICON",
        ManusIcon: "MANUS_ICON",
        MessengerIcon: "MESSENGER_ICON",
        MetaAiIcon: "META_AI_ICON",
        MetaHorizonIcon: "META_HORIZON_ICON",
        OculusIcon: "OCULUS_ICON",
        ThreadsIcon: "THREADS_ICON",
        VibesIcon: "VIBES_ICON",
      }),
      tn = e({ Center: "CENTER", Left: "LEFT" }),
      nn = e({ Default: "DEFAULT" }),
      rn = e({ FinalScore: "FINAL_SCORE", Goal: "GOAL", RedCard: "RED_CARD" }),
      on = e({
        None: "NONE",
        YoutubeShorts: "YOUTUBE_SHORTS",
        YoutubeVideo: "YOUTUBE_VIDEO",
      });
    ((i.AiBotEmbodimentTrigger = l),
      (i.BcnSlideMessagePollSelectionMode = s),
      (i.BcnSlideMessagePollStatus = u),
      (i.ClientInstructionType = c),
      (i.FoaUnifiedResponseSurfaceType = d),
      (i.GenAi3PExtCtaState = m),
      (i.GenAi3PExtCalendarEventOperation = p),
      (i.GenAi3PExtCalendarEventState = _),
      (i.GenAiActionListRowType = f),
      (i.GenAiAddonActionAlignment = g),
      (i.GenAiAddonActionType = h),
      (i.GenAiArtifactType = y),
      (i.GenAiCodeBlockType = C),
      (i.GenAiCompactEntityActionType = b),
      (i.GenAiCompactEntityType = v),
      (i.GenAiDividerType = S),
      (i.GenAiFooterActionType = R),
      (i.GenAiigBloomActionButtonType = L),
      (i.GenAiImageAssetQueryStatus = E),
      (i.GenAiImaginePrimitiveStatus = k),
      (i.GenAiImagineType = I),
      (i.GenAiInformTreatmentRenderingType = T),
      (i.GenAiMapItemMarkerType = D),
      (i.GenAiMapQueryStatus = x),
      (i.GenAiMediaHorizontalAlignment = $),
      (i.GenAiMediaShape = P),
      (i.GenAiMediaVerticalAlignment = N),
      (i.GenAiMultiAgentPhase = M),
      (i.GenAiMultiAgentRenderingStyle = w),
      (i.GenAiMultipleResponseLayoutType = A),
      (i.GenAiOrchestratorSearchEngine = F),
      (i.GenAiPlaceDetailsItemOpeningStatus = O),
      (i.GenAiPlaceDetailsItemPriceLevel = B),
      (i.GenAiPlaceDetailsItemType = W),
      (i.GenAiPlanPhaseStatus = q),
      (i.GenAiPostOrientation = U),
      (i.GenAiPostType = V),
      (i.GenAiProductSourceType = H),
      (i.GenAiProductSurface = G),
      (i.GenAiSearchPlannerStepStatus = z),
      (i.GenAiSideChatContextualQueryIntent = j),
      (i.GenAiSlideDeckSlideStatus = K),
      (i.GenAiSocialEntityItemType = Q),
      (i.GenAiSourceApp = X),
      (i.GenAiSourcedItemType = Y),
      (i.GenAiSubagentPhase = J),
      (i.GenAiThinkingStatusIcon = Z),
      (i.GenAiThinkingStatusSecondaryScreenId = ee),
      (i.GenAiThinkingStatusSecondaryScreenTabId = te),
      (i.GenAiThinkingToolStatus = ne),
      (i.GenAiThirdPartyAccountLinkingIntegration = re),
      (i.GenAiThirdPartyAccountLinkingIntegrationStatus = oe),
      (i.GenAiThreadSurfingActionType = ae),
      (i.GenAiThreadSurfingEntityType = ie),
      (i.GenAiUnifiedResponseSectionType = le),
      (i.GenAiContextInjectionType = se),
      (i.GenAiPromptType = ue),
      (i.ImmersivePostContentType = ce),
      (i.MebSplitDatabaseExecutionType = de),
      (i.MpsBackupContentType = me),
      (i.MpsBackupOperation = pe),
      (i.MpsEncryptedBackupMessageType = _e),
      (i.MpsEncryptedPlaceholderErrorCode = fe),
      (i.MpsMessageBackupSource = ge),
      (i.MpsMessageRangeQueryDirection = he),
      (i.MpsMessageTag = ye),
      (i.MpsQueryCaller = Ce),
      (i.MpsServerAttachmentUploadStatus = be),
      (i.MpsServerMessageUploadStatus = ve),
      (i.MpsUploadType = Se),
      (i.SlvBasilConversationStarterType = Re),
      (i.SlvImagineImageOrientation = Le),
      (i.SlvPromptEditType = Ee),
      (i.SlvResponseRole = ke),
      (i.SlvViewerAction = Ie),
      (i.XmsgaiBotResponseImagineSource = Te),
      (i.XmsgaiInvocationOptions = De),
      (i.XmsgaiLookupActionType = xe),
      (i.XmsgaiLookupEntityType = $e),
      (i.XmsgaiProduct = Pe),
      (i.XmsgAiAgentActivityStatus = Ne),
      (i.XmsgctaType = Me),
      (i.XmsgContentBrandingOption = we),
      (i.Xmsge2EeGenAiEncryptedImageProductType = Ae),
      (i.Xmsge2EeGenAiEncryptedVideoProductType = Fe),
      (i.XmsgFeatureTags = Oe),
      (i.XmsgGenAiBotResponseProductType = Be),
      (i.XmsgGenAiBotSubscriptionProductType = We),
      (i.XmsgGenAiMessageType = qe),
      (i.XmsgGenAiNestedUnifiedResponseType = Ue),
      (i.XmsgHighlightsTabMoment = Ve),
      (i.XmsgHighlightsTabReplySourceType = He),
      (i.XmsgIgReceiverFetchContentType = Ge),
      (i.XmsgIgReceiverFetchXmaMediaNoteFetchParamsMessageType = ze),
      (i.XmsgIgXmaActionType = je),
      (i.XmsgImageGlyphType = Ke),
      (i.XmsgInlineEntityType = Qe),
      (i.XmsgMarketplaceLightweightReplyType = Xe),
      (i.XmsgMarketplaceSmartRepliesTriggerType = Ye),
      (i.XmsgMediaDispatchKey = Je),
      (i.XmsgMediaReactionType = Ze),
      (i.XmsgMemoriesE2EeSendTemplateType = et),
      (i.XmsgMemoriesTemplateType = tt),
      (i.XmsgMessageRequestStatus = nt),
      (i.XmsgMessageSendProductType = rt),
      (i.XmsgMessageStreamingProductType = ot),
      (i.XmsgMsgrReceiverFetchContentType = at),
      (i.XmsgMsgrReceiverFetchXmaLayoutType = it),
      (i.XmsgMsgrXmaActionType = lt),
      (i.XmsgMsgrXmaUnifiedQueryType = st),
      (i.XmsgMustacheCtaType = ut),
      (i.XmsgNoteMessageType = ct),
      (i.XmsgNoteModelType = dt),
      (i.XmsgNoteType = mt),
      (i.XmsgOculusMediaType = pt),
      (i.XmsgPowerUpStyle = _t),
      (i.XmsgReactionStyle = ft),
      (i.XmsgReportedMessageType = gt),
      (i.XmsgSpectraActionSource = ht),
      (i.XmsgSpectraActionType = yt),
      (i.XmsgSpectraTakeDownActionType = Ct),
      (i.XmsgStoryOverlayPollStyle = bt),
      (i.XmsgStoryOverlayTagType = vt),
      (i.XmsgStoryReplyType = St),
      (i.XmsgStreamStatusType = Rt),
      (i.XmsgSuggestedModerationActionType = Lt),
      (i.XmsgTestEnum = Et),
      (i.XmsgTestMinimalEnum = kt),
      (i.XmsgTranscriptionStatus = It),
      (i.XmsgXmaBizAiUnifiedResponseAttributionType = Tt),
      (i.XmsgXmaBizAiUnifiedResponseSourceAttributionType = Dt),
      (i.XmsgXmaCodeBlockType = xt),
      (i.XmsgXmaCompactGenericTemplateAccessoryType = $t),
      (i.XmsgXmaCompactGenericTemplatePreviewStyle = Pt),
      (i.XmsgXmaContentAttributionIcon = Nt),
      (i.XmsgXmaContentType = Mt),
      (i.XmsgXmaCtaIconType = wt),
      (i.XmsgXmaCustomPreviewType = At),
      (i.XmsgXmaDailyGameChallengePlayerStatus = Ft),
      (i.XmsgXmaFlightStatusEnum = Ot),
      (i.XmsgXmaGamePredictionOption = Bt),
      (i.XmsgXmaGamePredictionType = Wt),
      (i.XmsgXmaGatingType = qt),
      (i.XmsgXmaImageDecorationType = Ut),
      (i.XmsgXmaLayoutType = Vt),
      (i.XmsgXmaLiveLocationSessionState = Ht),
      (i.XmsgXmaMessagingAttachmentFaviconStyle = Gt),
      (i.XmsgXmaOpgP2pPaymentMethodType = zt),
      (i.XmsgXmaOpgP2pTransactionType = jt),
      (i.XmsgXmaOverlayContentType = Kt),
      (i.XmsgXmaRtcCallState = Qt),
      (i.XmsgXmaRtcCallType = Xt),
      (i.XmsgXmaStandardGenericBodyLayoutType = Yt),
      (i.XmsgXmaStandardGenericBodyTitleStyle = Jt),
      (i.XmsgXmaSubscriptionRecurrenceType = Zt),
      (i.XmsgXmaSubtitleDecorationType = en),
      (i.XmsgXmaVStackLayoutHeaderAlignmentType = tn),
      (i.XmsgXmaVerifiedType = nn),
      (i.XmsgXmaWatchPartySoccerEventType = rn),
      (i.XmsgXmaYoutubePreviewMediaType = on));
  },
  66,
);
