__d(
  "MultiwaySharedTypes",
  ["$InternalEnum"],
  function (t, n, r, o, a, i) {
    "use strict";
    var e,
      l = (e = n("$InternalEnum"))({ UNKNOWN: 0, SFU: 1, P2P: 2 }),
      s = e({
        UNKNOWN: 0,
        IGVIDEOCALL: 9,
        ROOM: 15,
        CRUCIBLE: 20,
        MBS_WA: 21,
        BOT: 22,
        HORIZON: 23,
        ULLC: 24,
        COPRESENCE: 25,
      }),
      u = e({ OFFER: 0, PRANSWER: 1, ANSWER: 2, PROFFER: 3 }),
      c = e({ LOW: 0, MEDIUM: 1, HIGH: 2, HD: 3, NUM_QUALITIES: 4 }),
      d = e({
        E2EE_NOT_MANDATED: 0,
        DEPRECATED_NO_REQUIREMENT: 1,
        E2EE_MANDATED: 2,
        E2EE_BYPASSED_USER_CONSENTED: 3,
      }),
      m = e({ NOT_SET: 0, CONTROL: 1, TEST: 2 }),
      p = e({ NotPaused: 0, Paused: 1 }),
      _ = e({ AUDIO: 0, VIDEO: 1, DATA: 2 }),
      f = e({
        UNKNOWN: 0,
        COMPOSITING_SERVICE: 1,
        MEDIA_SERVER: 2,
        CATHODE_AMBISONIC: 3,
        CATHODE_CAPTIONS: 4,
        CATHODE_MEETING_SUMMARIZER: 5,
        CATHODE_REALTIME_SHARED_STATE: 6,
        RP_GENAI_SERVICE: 7,
        SMART_GLASSES_ASSISTANT: 8,
      }),
      g = e({ CNAME: 0, TRACK: 1, DOMINANT_SPEAKER: 2 }),
      h = e({ UNKNOWN: 0, DEFAULT: 1, SCREEN_SHARE: 2 }),
      y = e({ UNSPECIFIED: 0, FNA: 1, FNA_PREFERRED: 2 }),
      C = e({ NONE: 0, EXTENSION_SELF_PARTICIPANT: 1 }),
      b = e({ IntValue: "intValue", StringValue: "stringValue" });
    a.exports = {
      ConferenceType: s,
      CustomMediaRoutingType: C,
      E2eeInfraMandatedExpStatus: m,
      E2eeMode: d,
      EdgerayType: y,
      EndpointServiceType: f,
      MediaPath: l,
      MediaPauseStatus: p,
      MediaType: _,
      QuickExperimentValue$Types: b,
      RenderedStreamType: h,
      SdpType: u,
      SubscriptionType: g,
      VideoQuality: c,
    };
  },
  null,
);
