__d(
  "multiway_DismissReason",
  [],
  function (t, n, r, o, a, i) {
    var e = Object.freeze({
      CALL_ENDED: 0,
      ANSWERED_ON_ANOTHER_DEVICE: 1,
      IN_ANOTHER_CALL: 2,
      CONNECTION_DROPPED: 3,
      REJECTED_ON_ANOTHER_DEVICE: 4,
      REMOVED_BY_PARTICIPANT: 5,
      REJECTED_BY_CALLEE: 6,
      INTERNAL_ERROR: 7,
      CALL_ENDED_BY_PRODUCT: 9,
      JOIN_APPROVAL_DENIED: 10,
      JOIN_APPROVAL_TIMEDOUT: 11,
      UNSUPPORTED_VERSION: 12,
      LIVE_NOT_ACKED: 13,
      TX_ACK_TIMEDOUT: 14,
      ANSWERED_BY_OTHER_USER: 15,
      PARTICIPANT_SELF_TERMINATION: 16,
      PARTICIPANT_REJOIN: 17,
      LONG_LASTING_AUDIO_ISSUE: 18,
      PRIMARY_ENDPOINT_HANGUP: 19,
      RECONNECT_FAILED: 20,
      E2EE_HARDENING_ERROR: 21,
      CALL_ENDED_BY_EXTENSION: 22,
      CALL_ENDED_BY_OVER_CAPACITY: 23,
      CALL_ENDED_BY_SERVER_TIMEOUT: 24,
    });
    i.default = e;
  },
  66,
);
