__d(
  "OffsiteCustomEventType",
  [],
  function (t, n, r, o, a, i) {
    var e = Object.freeze({
      JOB_ALERT_SUBSCRIBE: "JOB_ALERT_SUBSCRIBE",
      JOB_APPLICATION_CREATE: "JOB_APPLICATION_CREATE",
      JOB_APPLICATION_FORM_IMPRESSION: "JOB_APPLICATION_FORM_IMPRESSION",
      JOB_BROWSER_IMPRESSION: "JOB_BROWSER_IMPRESSION",
      JOB_OPENING_DETAIL_VIEW_IMPRESSION: "JOB_OPENING_DETAIL_VIEW_IMPRESSION",
      ACTIVATE_APP: "ACTIVATE_APP",
      COMPLETE_REGISTRATION: "COMPLETE_REGISTRATION",
      CONTENT_VIEW: "CONTENT_VIEW",
      ONSITE_APP_CONTENT_VIEW: "ONSITE_APP_CONTENT_VIEW",
      ONSITE_WEB_CONTENT_VIEW: "ONSITE_WEB_CONTENT_VIEW",
      ONSITE_WEB_APP_CONTENT_VIEW: "ONSITE_WEB_APP_CONTENT_VIEW",
      SEARCH: "SEARCH",
      RATE: "RATE",
      TUTORIAL_COMPLETION: "TUTORIAL_COMPLETION",
      CONTACT: "CONTACT",
      CUSTOMIZE_PRODUCT: "CUSTOMIZE_PRODUCT",
      DONATE: "DONATE",
      FIND_LOCATION: "FIND_LOCATION",
      SCHEDULE: "SCHEDULE",
      START_TRIAL: "START_TRIAL",
      SUBMIT_APPLICATION: "SUBMIT_APPLICATION",
      SUBSCRIBE: "SUBSCRIBE",
      RECURRING_SUBSCRIPTION_PAYMENT: "RECURRING_SUBSCRIPTION_PAYMENT",
      CANCEL_SUBSCRIPTION: "CANCEL_SUBSCRIPTION",
      VISIT_LOCATION: "VISIT_LOCATION",
      AD_CLICK: "AD_CLICK",
      AD_IMPRESSION: "AD_IMPRESSION",
      UPDATE_PLTV: "UPDATE_PLTV",
      APPEND_VALUE: "APPEND_VALUE",
      ADD_TO_CART: "ADD_TO_CART",
      ONSITE_APP_ADD_TO_CART: "ONSITE_APP_ADD_TO_CART",
      ONSITE_WEB_ADD_TO_CART: "ONSITE_WEB_ADD_TO_CART",
      ONSITE_WEB_APP_ADD_TO_CART: "ONSITE_WEB_APP_ADD_TO_CART",
      ADD_TO_WISHLIST: "ADD_TO_WISHLIST",
      INITIATED_CHECKOUT: "INITIATED_CHECKOUT",
      ADD_PAYMENT_INFO: "ADD_PAYMENT_INFO",
      PURCHASE: "PURCHASE",
      APPEND_CLICK_ATTRIBUTION: "APPEND_CLICK_ATTRIBUTION",
      ONSITE_APP_PURCHASE: "ONSITE_APP_PURCHASE",
      ONSITE_WEB_PURCHASE: "ONSITE_WEB_PURCHASE",
      ONSITE_WEB_APP_PURCHASE: "ONSITE_WEB_APP_PURCHASE",
      MESSAGE_TO_BUY: "MESSAGE_TO_BUY",
      LEAD: "LEAD",
      LEAD_CUSTOM_EVENT: "LEAD_CUSTOM_EVENT",
      LEAD_SUBMITTED: "LEAD_SUBMITTED",
      ONSITE_WEB_LEAD: "ONSITE_WEB_LEAD",
      PDP_CLICK_TO_OFFSITE: "PDP_CLICK_TO_OFFSITE",
      PDP_CLICK_VIEW_IN_CART: "PDP_CLICK_VIEW_IN_CART",
      PDP_CLICK_TO_CHECKOUT: "PDP_CLICK_TO_CHECKOUT",
      ORDER_CREATION: "ORDER_CREATION",
      CART_IMPRESSION: "CART_IMPRESSION",
      SHOP_MID_FUNNEL: "SHOP_MID_FUNNEL",
      LEVEL_ACHIEVED: "LEVEL_ACHIEVED",
      ACHIEVEMENT_UNLOCKED: "ACHIEVEMENT_UNLOCKED",
      SPENT_CREDITS: "SPENT_CREDITS",
      FLOW_COMPLETE: "FLOW_COMPLETE",
      SERVICE_BOOKING_REQUEST: "SERVICE_BOOKING_REQUEST",
      INSTAGRAM_PROFILE_FOLLOW: "INSTAGRAM_PROFILE_FOLLOW",
      INSTAGRAM_PROFILE_VIEW: "INSTAGRAM_PROFILE_VIEW",
      PROFILE_FOLLOW: "PROFILE_FOLLOW",
      PROFILE_VIEW: "PROFILE_VIEW",
      PROFILE_VISIT_DWELL3S: "PROFILE_VISIT_DWELL3S",
      PROFILE_VISIT_DWELL10S: "PROFILE_VISIT_DWELL10S",
      INSTAGRAM_AD_FOLLOW: "INSTAGRAM_AD_FOLLOW",
      INSTAGRAM_AD_FOLLOW_QUALITY_SCORE: "INSTAGRAM_AD_FOLLOW_QUALITY_SCORE",
      INSTAGRAM_FOLLOW_QUALITY_SCORE: "INSTAGRAM_FOLLOW_QUALITY_SCORE",
      PROFILE_FOLLOW_QUALITY_SCORE: "PROFILE_FOLLOW_QUALITY_SCORE",
      INSTAGRAM_LEAD_GEN_LAW: "INSTAGRAM_LEAD_GEN_LAW",
      UPCOMING_EVENT_REMINDER_SET: "UPCOMING_EVENT_REMINDER_SET",
      UPCOMING_EVENT_REMINDER_UNSET: "UPCOMING_EVENT_REMINDER_UNSET",
      UPCOMING_EVENT_NOTIFICATION_CLICK: "UPCOMING_EVENT_NOTIFICATION_CLICK",
      UPCOMING_EVENT_POST_NOTIFICATION_LINK_CLICK:
        "UPCOMING_EVENT_POST_NOTIFICATION_LINK_CLICK",
      UPCOMING_EVENT_POST_NOTIFICATION_UAS_TAP:
        "UPCOMING_EVENT_POST_NOTIFICATION_UAS_TAP",
      IG_RECONSIDERATION_ENTRY_POINT_CLICK:
        "IG_RECONSIDERATION_ENTRY_POINT_CLICK",
      MESSAGING_ACCEPT: "MESSAGING_ACCEPT",
      MESSAGING_BLOCK: "MESSAGING_BLOCK",
      MESSAGING_DELETE_THREAD: "MESSAGING_DELETE_THREAD",
      MESSAGING_FRX_FEEDBACK: "MESSAGING_FRX_FEEDBACK",
      MESSAGING_SCAM_PROACTIVE_WARNING_LEARN_MORE:
        "MESSAGING_SCAM_PROACTIVE_WARNING_LEARN_MORE",
      MESSAGING_SCAM_PROACTIVE_WARNING_LEARN_MORE_EXPERIMENTAL:
        "MESSAGING_SCAM_PROACTIVE_WARNING_LEARN_MORE_EXPERIMENTAL",
      MESSAGING_IN_THREAD_FEEDBACK_SATISFIED:
        "MESSAGING_IN_THREAD_FEEDBACK_SATISFIED",
      MESSAGING_IN_THREAD_FEEDBACK_DISSATISFIED:
        "MESSAGING_IN_THREAD_FEEDBACK_DISSATISFIED",
      MESSAGING_IN_THREAD_FEEDBACK_DISSATISFIED_CONFUSING_PROCESS:
        "MESSAGING_IN_THREAD_FEEDBACK_DISSATISFIED_CONFUSING_PROCESS",
      MESSAGING_IN_THREAD_FEEDBACK_DISSATISFIED_NOT_HELPFUL:
        "MESSAGING_IN_THREAD_FEEDBACK_DISSATISFIED_NOT_HELPFUL",
      MESSAGING_IN_THREAD_FEEDBACK_DISSATISFIED_SLOW_RESPONSES:
        "MESSAGING_IN_THREAD_FEEDBACK_DISSATISFIED_SLOW_RESPONSES",
      MESSAGING_IN_THREAD_FEEDBACK_DISSATISFIED_SUSPICIOUS_BEHAVIOR:
        "MESSAGING_IN_THREAD_FEEDBACK_DISSATISFIED_SUSPICIOUS_BEHAVIOR",
      MESSAGING_IN_THREAD_FEEDBACK_DISSATISFIED_TOO_MANY_MESSAGES:
        "MESSAGING_IN_THREAD_FEEDBACK_DISSATISFIED_TOO_MANY_MESSAGES",
      MESSAGING_IN_THREAD_FEEDBACK_DISSATISFIED_OTHER:
        "MESSAGING_IN_THREAD_FEEDBACK_DISSATISFIED_OTHER",
      MESSAGING_IN_THREAD_DXMA_FEEDBACK_SATISFIED:
        "MESSAGING_IN_THREAD_DXMA_FEEDBACK_SATISFIED",
      MESSAGING_IN_THREAD_DXMA_FEEDBACK_DISSATISFIED:
        "MESSAGING_IN_THREAD_DXMA_FEEDBACK_DISSATISFIED",
      MESSAGING_MSGR_BUYER_SATISFIED_WITH_PURCHASE:
        "MESSAGING_MSGR_BUYER_SATISFIED_WITH_PURCHASE",
      MESSAGING_MSGR_BUYER_DISSATISFIED_WITH_PURCHASE:
        "MESSAGING_MSGR_BUYER_DISSATISFIED_WITH_PURCHASE",
      MESSAGING_IG_BUYER_SATISFIED_WITH_CONVERSATION:
        "MESSAGING_IG_BUYER_SATISFIED_WITH_CONVERSATION",
      MESSAGING_IG_BUYER_DISSATISFIED_WITH_CONVERSATION:
        "MESSAGING_IG_BUYER_DISSATISFIED_WITH_CONVERSATION",
      MESSAGING_CONVERSATION_SELLER_FEEDBACK_SATISFIED:
        "MESSAGING_CONVERSATION_SELLER_FEEDBACK_SATISFIED",
      MESSAGING_CONVERSATION_SELLER_FEEDBACK_DISSATISFIED:
        "MESSAGING_CONVERSATION_SELLER_FEEDBACK_DISSATISFIED",
      MESSAGING_CONVERSATION_SELLER_FEEDBACK_BAN:
        "MESSAGING_CONVERSATION_SELLER_FEEDBACK_BAN",
      MESSAGING_CONVERSATION_SELLER_FEEDBACK_REPORT_SPAM:
        "MESSAGING_CONVERSATION_SELLER_FEEDBACK_REPORT_SPAM",
      MESSAGING_MARK_SPAM: "MESSAGING_MARK_SPAM",
      MESSAGING_REPLY: "MESSAGING_REPLY",
      MESSAGING_FIRST_REPLY: "MESSAGING_FIRST_REPLY",
      MESSAGING_FIRST_REPLY_CONTINUATION: "MESSAGING_FIRST_REPLY_CONTINUATION",
      MESSAGING_OPEN_THREAD: "MESSAGING_OPEN_THREAD",
      MESSAGING_IGNORE_REQUEST: "MESSAGING_IGNORE_REQUEST",
      MESSAGING_PROMOTIONAL_OFF: "MESSAGING_PROMOTIONAL_OFF",
      MESSAGING_READ_RECEIPT: "MESSAGING_READ_RECEIPT",
      MESSAGING_DELIVERY_RECEIPT: "MESSAGING_DELIVERY_RECEIPT",
      MESSAGING_DELETE_MESSAGE: "MESSAGING_DELETE_MESSAGE",
      MESSAGING_CONVERSATION_STARTED_7D: "MESSAGING_CONVERSATION_STARTED_7D",
      MESSAGING_DEEP_CONVERSATION: "MESSAGING_DEEP_CONVERSATION",
      MESSAGING_DEEP_CONVERSATION_SHADOW: "MESSAGING_DEEP_CONVERSATION_SHADOW",
      MESSAGING_DEDUP_DEEP_CONVERSATION: "MESSAGING_DEDUP_DEEP_CONVERSATION",
      MESSAGING_SYNTHETIC_DEEP_CONVERSATION:
        "MESSAGING_SYNTHETIC_DEEP_CONVERSATION",
      MESSAGING_AUTOMATED_FLOW_COMPLETE: "MESSAGING_AUTOMATED_FLOW_COMPLETE",
      MESSAGING_AUTOMATED_FLOW_CANCELLED: "MESSAGING_AUTOMATED_FLOW_CANCELLED",
      MESSENGER_RECEIPT_TEMPLATE: "MESSENGER_RECEIPT_TEMPLATE",
      MESSAGING_PAGE_SEND: "MESSAGING_PAGE_SEND",
      MESSAGING_PAGE_SEND_AFTER_USER_SEND:
        "MESSAGING_PAGE_SEND_AFTER_USER_SEND",
      MESSAGING_USER_DEPTH_2_MESSAGE_SEND:
        "MESSAGING_USER_DEPTH_2_MESSAGE_SEND",
      MESSAGING_USER_DEPTH_2_MESSAGE_SEND_CONTINUATION:
        "MESSAGING_USER_DEPTH_2_MESSAGE_SEND_CONTINUATION",
      MESSAGING_USER_DEPTH_3_MESSAGE_SEND:
        "MESSAGING_USER_DEPTH_3_MESSAGE_SEND",
      MESSAGING_USER_DEPTH_3_MESSAGE_SEND_CONTINUATION:
        "MESSAGING_USER_DEPTH_3_MESSAGE_SEND_CONTINUATION",
      MESSAGING_USER_DEPTH_5_MESSAGE_SEND:
        "MESSAGING_USER_DEPTH_5_MESSAGE_SEND",
      MESSAGING_PAGE_DEPTH_2_MESSAGE_SEND:
        "MESSAGING_PAGE_DEPTH_2_MESSAGE_SEND",
      MESSAGING_PAGE_DEPTH_2_MESSAGE_SEND_CONTINUATION:
        "MESSAGING_PAGE_DEPTH_2_MESSAGE_SEND_CONTINUATION",
      MESSAGING_CONVERSATION_DEPTH: "MESSAGING_CONVERSATION_DEPTH",
      MESSAGING_CONVERSATION_DEPTH_NEW_WHATSAPP_SCHEMA:
        "MESSAGING_CONVERSATION_DEPTH_NEW_WHATSAPP_SCHEMA",
      MESSAGING_QUALIFIED_LEAD: "MESSAGING_QUALIFIED_LEAD",
      MESSAGING_APPOINTMENT_BOOKED: "MESSAGING_APPOINTMENT_BOOKED",
      MESSAGING_PAGE_SEND_NUM_SAME_CONVERSATION:
        "MESSAGING_PAGE_SEND_NUM_SAME_CONVERSATION",
      MESSAGING_USER_SEND_NUM_SAME_CONVERSATION:
        "MESSAGING_USER_SEND_NUM_SAME_CONVERSATION",
      MESSAGING_BUSINESS_CALLING_OPT_IN_SENT:
        "MESSAGING_BUSINESS_CALLING_OPT_IN_SENT",
      MESSAGING_BUSINESS_CALLING_OPT_IN_ACCEPTED:
        "MESSAGING_BUSINESS_CALLING_OPT_IN_ACCEPTED",
      MESSAGING_BUSINESS_CALLING_OPT_IN_DENIED:
        "MESSAGING_BUSINESS_CALLING_OPT_IN_DENIED",
      MESSAGING_BUSINESS_CALLING_CALL_INITIATED:
        "MESSAGING_BUSINESS_CALLING_CALL_INITIATED",
      MESSAGING_BUSINESS_CALLING_CALL_ANSWERED:
        "MESSAGING_BUSINESS_CALLING_CALL_ANSWERED",
      MESSAGING_BUSINESS_CALLING_CALL_MISSED:
        "MESSAGING_BUSINESS_CALLING_CALL_MISSED",
      MESSAGING_BUSINESS_CALLING_CALL_DENIED:
        "MESSAGING_BUSINESS_CALLING_CALL_DENIED",
      MESSAGING_BUSINESS_LLAMA_CONVERSION_POSITIVE:
        "MESSAGING_BUSINESS_LLAMA_CONVERSION_POSITIVE",
      MESSAGING_BUSINESS_LLAMA_CONVERSION_NEGATIVE:
        "MESSAGING_BUSINESS_LLAMA_CONVERSION_NEGATIVE",
      MESSAGING_FIRST_BIZ_REPLY: "MESSAGING_FIRST_BIZ_REPLY",
      MESSAGING_FIRST_BIZ_REPLY_CONTINUATION:
        "MESSAGING_FIRST_BIZ_REPLY_CONTINUATION",
      MESSAGING_FIRST_CALL: "MESSAGING_FIRST_CALL",
      MESSAGING_FIRST_LONG_CALL: "MESSAGING_FIRST_LONG_CALL",
      MESSAGING_USER_PHONE_CALL_DIALOG_CONFIRM_CLICKED:
        "MESSAGING_USER_PHONE_CALL_DIALOG_CONFIRM_CLICKED",
      MESSAGING_USER_CALL_ATTEMPTED: "MESSAGING_USER_CALL_ATTEMPTED",
      MESSAGING_PAGE_CALL_ATTEMPTED: "MESSAGING_PAGE_CALL_ATTEMPTED",
      MESSAGING_CONNECTED_CALL_OR_DC: "MESSAGING_CONNECTED_CALL_OR_DC",
      MESSAGING_CALL_ATTEMPT_AND_DC: "MESSAGING_CALL_ATTEMPT_AND_DC",
      MESSAGING_CALL_ATTEMPT_AND_PAGE_INTERACTION:
        "MESSAGING_CALL_ATTEMPT_AND_PAGE_INTERACTION",
      MESSAGING_MISSED_CALL: "MESSAGING_MISSED_CALL",
      MESSAGING_USER_SUBSCRIBED: "MESSAGING_USER_SUBSCRIBED",
      MESSAGING_CONVERSATION_ENGAGED: "MESSAGING_CONVERSATION_ENGAGED",
      MESSAGING_WELCOME_MESSAGE_VIEW: "MESSAGING_WELCOME_MESSAGE_VIEW",
      MESSAGING_CONVERSATION_REPLIED_7D: "MESSAGING_CONVERSATION_REPLIED_7D",
      MESSAGING_DEEP_CONVERSATION_SEMANTICALLY_RELEVANT:
        "MESSAGING_DEEP_CONVERSATION_SEMANTICALLY_RELEVANT",
      MESSAGING_DEEP_CONVERSATION_SEMANTIC_DETECTION:
        "MESSAGING_DEEP_CONVERSATION_SEMANTIC_DETECTION",
      MESSAGING_DOWN_FUNNEL_PURCHASE_SEMANTICALLY_RELEVANT:
        "MESSAGING_DOWN_FUNNEL_PURCHASE_SEMANTICALLY_RELEVANT",
      MESSAGING_EVENT_OPTIMIZATION_LEAD_SEMANTICALLY_RELEVANT:
        "MESSAGING_EVENT_OPTIMIZATION_LEAD_SEMANTICALLY_RELEVANT",
      TOTAL_MESSAGING_CONNECTION: "TOTAL_MESSAGING_CONNECTION",
      DOWN_FUNNEL_PURCHASE: "DOWN_FUNNEL_PURCHASE",
      MESSAGING_DOWN_FUNNEL_PURCHASE: "MESSAGING_DOWN_FUNNEL_PURCHASE",
      MESSAGING_DOWN_FUNNEL_PURCHASE_VALUE:
        "MESSAGING_DOWN_FUNNEL_PURCHASE_VALUE",
      MESSAGING_EVENT_OPTIMIZATION_LEAD: "MESSAGING_EVENT_OPTIMIZATION_LEAD",
      MESSAGING_SHALLOW_LEAD: "MESSAGING_SHALLOW_LEAD",
      MESSAGING_STRUCTURED_LEAD: "MESSAGING_STRUCTURED_LEAD",
      MESSAGING_QUALITY_LEAD: "MESSAGING_QUALITY_LEAD",
      MESSAGING_DOWN_FUNNEL_LOW_PRECISION_PURCHASE:
        "MESSAGING_DOWN_FUNNEL_LOW_PRECISION_PURCHASE",
      MESSAGING_IGD_TO_WA_CHANNEL_SWITCH: "MESSAGING_IGD_TO_WA_CHANNEL_SWITCH",
      REFERRAL_SENDER_INVITES_SENT: "REFERRAL_SENDER_INVITES_SENT",
      REFERRAL_SENDER_MESSAGE_SENT: "REFERRAL_SENDER_MESSAGE_SENT",
      REFERRAL_RECEIVER_IMPRESSION: "REFERRAL_RECEIVER_IMPRESSION",
      REFERRAL_RECEIVER_CLICK: "REFERRAL_RECEIVER_CLICK",
      VIDEO_HOME_SELECTED: "VIDEO_HOME_SELECTED",
      VIDEO_HOME_WATCHLIST: "VIDEO_HOME_WATCHLIST",
      VIDEO_HOME_EXPLORE: "VIDEO_HOME_EXPLORE",
      VIDEO_HOME_PLAYER_START: "VIDEO_HOME_PLAYER_START",
      VIDEO_HOME_90_SECOND_VIEW: "VIDEO_HOME_90_SECOND_VIEW",
      FUNDRAISER_CREATE: "FUNDRAISER_CREATE",
      MESSENGER_CONNECTED_CALL: "MESSENGER_CONNECTED_CALL",
      MESSENGER_MISSED_CALL: "MESSENGER_MISSED_CALL",
      D2_RETENTION: "D2_RETENTION",
      D7_RETENTION: "D7_RETENTION",
      MOVIE_SHOWTIME_CLICK: "MOVIE_SHOWTIME_CLICK",
      LISTING_INTERACTION: "LISTING_INTERACTION",
      PDP_VIEW: "PDP_VIEW",
      CLICK_TO_CALL: "CLICK_TO_CALL",
      CLICK_TO_WEBSITE: "CLICK_TO_WEBSITE",
      POST_SAVE: "POST_SAVE",
      POST_SHARE: "POST_SHARE",
      MEANINGFUL_LISTING_INTERACTION: "MEANINGFUL_LISTING_INTERACTION",
      MARKETPLACE_MLI6: "MARKETPLACE_MLI6",
      MARKETPLACE_MLI9: "MARKETPLACE_MLI9",
      MARKETPLACE_MARK_AS_SOLD: "MARKETPLACE_MARK_AS_SOLD",
      ONE_PD_LPV: "ONE_PD_LPV",
      CLICK_TO_JOIN_NEW_CHANNEL_MEMBER: "CLICK_TO_JOIN_NEW_CHANNEL_MEMBER",
      OTHER: "OTHER",
    });
    i.default = e;
  },
  66,
);
