__d(
  "P2PTransferStatus",
  [],
  function (t, n, r, o, a, i) {
    var e = Object.freeze({
      SYSTEM_FAILURE: 0,
      PENDING_SENDER_MANUAL_REVIEW: 1,
      PENDING_SENDER_VERIFICATION: 2,
      CANCELED_SENDER_RISK: 3,
      PENDING_RECIPIENT_NUX: 4,
      CANCELED_DECLINED: 5,
      PENDING_RECIPIENT_VERIFICATION: 6,
      PENDING_RECIPIENT_MANUAL_REVIEW: 7,
      PENDING_RECIPIENT_PROCESSING: 8,
      PENDING_PUSH_FAIL: 9,
      CANCELED_RECIPIENT_RISK: 10,
      CANCELED_SYSTEM_FAIL: 11,
      CANCELED_EXPIRED: 12,
      COMPLETED: 13,
      INTERMEDIATE_PROCESSING: 14,
      PENDING_SENDER_INITED: 15,
      CANCELED_SAME_CARD: 16,
      PENDING_SENDER_VERIFICATION_PROCESSING: 17,
      PENDING_RECIPIENT_VERIFICATION_PROCESSING: 18,
      CANCELED_SENDER_CANCEL: 19,
      PENDING_SENDER_IDV_REVIEW: 20,
      PENDING_RECEIVER_IDV_REVIEW: 21,
    });
    i.default = e;
  },
  66,
);
