__d(
  "ReactFeatureFlags",
  ["gkx", "justknobx", "qex"],
  function (t, n, r, o, a, i, l) {
    "use strict";
    var e,
      s,
      u,
      c,
      d,
      m = r("gkx")("11557"),
      p = !1,
      _ = r("gkx")("163"),
      f = r("gkx")("21072") || ((e = r("qex")._("104")) != null ? e : !1),
      g = (s = r("qex")._("128")) != null ? s : 250,
      h = (u = r("qex")._("344")) != null ? u : 5e3,
      y = (c = r("qex")._("388")) != null ? c : 5e3,
      C = !1,
      b = (d = r("gkx")("17201")) != null ? d : !1,
      v = r("gkx")("18142") || r("gkx")("6800"),
      S = r("gkx")("18162") || r("gkx")("18172"),
      R = !0,
      L = !0,
      E = !0,
      k = r("gkx")("17254"),
      I = r("gkx")("2815"),
      T = !1,
      D =
        r("justknobx")._("678") &&
        (r("gkx")("12572") || r("qex")._("2513") === !0),
      x = !1,
      $ = !1,
      P = r("gkx")("20483");
    ((l.alwaysThrottleRetries = m),
      (l.enableNoCloningMemoCache = p),
      (l.enableObjectFiber = _),
      (l.enableRetryLaneExpiration = f),
      (l.syncLaneExpirationMs = g),
      (l.transitionLaneExpirationMs = h),
      (l.retryLaneExpirationMs = y),
      (l.enableScrollEndPolyfill = C),
      (l.enableInfiniteRenderLoopDetection = b),
      (l.enableParallelTransitions = v),
      (l.enableEffectEventMutationPhase = S),
      (l.enableTrustedTypesIntegration = R),
      (l.enableFragmentRefs = L),
      (l.enableFragmentRefsScrollIntoView = E),
      (l.enableFragmentRefsTextNodes = k),
      (l.enableViewTransition = I),
      (l.enableTransitionTracing = T),
      (l.enableInternalInstanceMap = D),
      (l.disableLegacyContextForFunctionComponents = x),
      (l.disableSchedulerTimeoutInWorkLoop = $),
      (l.enableSchedulingProfiler = P));
  },
  98,
);
