__d(
  "SBGLeadSource",
  [],
  function (t, n, r, o, a, i) {
    var e = Object.freeze({
      BOOSTED_APP_INSTALL: "boosted_app_install",
      BOOSTED_AUTOMOTIVE_INVENTORY: "boosted_automotive_inventory",
      BOOSTED_CONSOLIDATED_PRODUCT: "boosted_consolidated_product",
      BOOSTED_CTA: "boosted_cta",
      BOOSTED_EVENT: "boosted_event",
      BOOSTED_FB_INSTAGRAM_MEDIA: "boosted_fb_instagram_media",
      BOOSTED_FB_STORY: "boosted_fb_story",
      BOOSTED_IG_STORY: "boosted_ig_story",
      BOOSTED_INSTAGRAM_MEDIA: "boosted_instagram_media",
      BOOSTED_JOB_POST: "boosted_job_post",
      BOOSTED_LEAD_GEN: "boosted_lead_gen",
      BOOSTED_LOCAL_AWARENESS: "boosted_local_awareness",
      BOOSTED_MARKETPLACE_LISTING: "boosted_marketplace_listing",
      BOOSTED_PAGELIKE: "boosted_pagelike",
      BOOSTED_POST: "boosted_post",
      BOOSTED_REAL_ESTATE_LISTING: "boosted_real_estate_listing",
      BOOSTED_TOUR: "boosted_tour",
      BOOSTED_USER_POST: "boosted_user_post",
      BOOSTED_WEBSITE: "boosted_website",
      BOOSTED_POST_AB_TEST: "boosted_post_ab_test",
      SMBAS_ADCENTER: "smbas_adcenter",
      SMBAS_FTAE: "smbas_ftae",
      SMBAS_AYMT: "smbas_aymt",
      SMBAS_AD_CREATION: "smbas_adcreation",
      ADS_CAMP: "ads_camp",
      AYMT: "aymt",
      AYMT_UPRANK: "aymt_uprank",
      AYMT_NATIVE: "aymt_native",
      AYMT_NATIVE_DL: "aymt_native_dl",
      AYMT_NATIVE_LG: "aymt_native_lg",
      AYMT_NATIVE_WEB: "aymt_native_web",
      BOOSTUP_EMAIL: "newbie_onboarding_coupon_email_tp1",
      LANDING_PAGE: "landing_page",
      NEWBIE_ONBOARDING: "newbie_onboarding",
      SDR_TO_BOOSTUP: "sdr_to_boostup",
      SDR_TO_CTWA: "sdr_to_ctwa",
      SMB_HOME: "smb_home",
      ADS_MANAGER_START_YOUR_DAY_MARKETING_EXPERT_WIDGET:
        "ads_manager_start_your_day_marketing_expert_widget",
      ADS_MANAGER_START_YOUR_DAY_GUIDANCE_HUB_WIDGET:
        "ads_manager_start_your_day_guidance_hub_widget",
      ADS_MANAGER_PUSH_NOTIFICATION_NO_SHOW: "amd_push_notification_no_show",
      ADS_MANAGER_PUSH_NOTIFICATION_REMINDER: "amd_push_notification_reminder",
      ADS_MANAGER_APP_HELP_AND_SUPPORT_MARKETING_EXPERT:
        "ads_manager_app_help_and_support_marketing_expert",
      ADS_MANAGER_BIZ_SETUP_CAPI_MARKETING_EXPERT_BANNER:
        "ads_manager_biz_setup_capi_marketing_expert_banner",
      ADS_MANAGER_ADS_CREATION_FLOW_PERSISTENT_BUTTON:
        "ads_manager_ads_creation_flow_persistent_button",
      FACEBOOK_BUSINESS_SUITE_HOME_CARD: "facebook_business_suite_home_card",
      MBS_INBOX: "mbs_inbox",
      MBS_HOME: "mbs_home",
      ADS_MANAGER_IOS_ADS_CREATION_RIGHT_RAIL:
        "IOS_AdsMngr_Creation_EntryPoint",
      ADS_MANAGER_IOS_CAMPAIGNS_OVERVIEW_MODAL:
        "IOS_AdsMngr_CampaignsOverView_EntryPoint",
      ADS_MANAGER_AEM_CAMPAIGNS_OVERVIEW_MODAL: "AEM_Modal_Entry_Point",
      ADS_MANAGER_TABLE_ME_ENTRYPOINT_NAV_BAR_BUTTON:
        "ads_manager_table_me_entrypoint_nav_bar_button",
      OSMIP_HT_ENTRY_POINT: "OSMIP_HT_Entry_Point",
      OSMIP_PA_PROMPT_ENTRY_POINT: "OSMIP_PA_Prompt_Entry_Point",
      OSMIP_PA_PROMPT_PSEUDO_ENTRY_POINT: "OSMIP_PA_Pseudo_Prompt_Entry_Point",
      PERSISTENT_ENTRY_POINT_ADS_MANAGER: "Persistent_Entry_Point_Ads_Manager",
      AM_CAMPAIGNSOVERVIEW_ENTRY_POINT: "AM_CampaignsOverview_Entry_Point",
      AM_SYD_ENTRY_POINT: "AM_SYD_Entry_Point",
      AM_CREATION_L3_NEWCAMPAIGN_ENTRY_POINT:
        "AM_Creation_L3_NewCampaign_Entry_Point",
      AM_CREATION_L2_ADSET_ENTRY_POINT: "AM_Creation_L2_AdSet_Entry_Point",
      AM_CREATION_L1_AD_ENTRY_POINT: "AM_Creation_L1_Ad_Entry_Point",
      SDR_CHATBOT: "sdr_chatbot",
      OTHER: "other",
      IG_AD_TOOLS: "ig_ad_tools",
      IG_WEB_AD_TOOLS: "ig_web_ad_tools",
      IG_BOOST: "ig_boost",
      IG_PROMOTE: "ig_promote",
      IG_LANDING_PAGE: "ig_landing_page",
      IG_PRO_DASH: "ig_pro_dash",
      AMA_PUSH_NOTIFICATION_REMINDER: "ama_push_notification_reminder",
      AMA_PUSH_NOTIFICATION_NO_SHOW: "ama_push_notification_no_show",
      AMA_PUSH_NOTIFICATION_POST_CALL: "ama_push_notification_post_call",
      CONTACTABILITY_FLOW: "contactability_flow",
      CAPI_SETUP_CONNECTION_METHOD_ENTRYPOINT:
        "CAPI_Setup_Connection_Method_EntryPoint",
      CAPI_SETUP_INTEGRATION_OPTIONS_ENTRYPOINT:
        "CAPI_Setup_Integration_Options_EntryPoint",
      CAPI_PARTNER_INTEGRATION_ENTRYPOINT:
        "CAPI_Partner_Integration_EntryPoint",
      CAPI_GTM_TASKCARD_ENTRYPOINT: "CAPI_GTM_TaskCard_EntryPoint",
      CAPI_TASKCARD_ENTRYPOINT: "CAPI_TaskCard_EntryPoint",
      ADS_EVENTS_MANAGER_OVERVIEW_PAGE: "ads_events_manager_overview_page",
      ADS_EVENTS_MANAGER_TOP_NAV: "ads_events_manager_top_nav",
      WHATSAPP_QP_FILTER: "whatsapp_qp_filter",
      FLOATING_APPOINTMENTS_UNENGAGED_ADVERTISER_EMAIL:
        "floating_appointments_unengaged_advertiser_email",
      FLOATING_APPOINTMENTS_ENGAGED_ADVERTISER_EMAIL:
        "floating_appointments_engaged_advertiser_email",
      ADS_MANAGER_AI_IN_CHAT: "ads_manager_ai_in_chat",
      PROACTIVE_CHAT: "proactive_chat",
      PROACTIVE_CHAT_GENAI: "proactive_chat_genai",
      OPPORTUNITY_SCORE_HOVERCARD: "opportunity_score_hovercard",
      OPPORTUNITY_SCORE_SIDE_PANEL: "opportunity_score_side_panel",
      OPPORTUNITY_SCORE_START_YOUR_DAY: "opportunity_score_start_your_day",
      MESSENGER: "messenger",
    });
    i.default = e;
  },
  66,
);
