__d(
  "SecuredActionPasswordChallengeDialog_query.graphql",
  [],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = (function () {
      var e = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "name",
          storageKey: null,
        },
        t = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "title",
          storageKey: null,
        },
        n = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "description",
          storageKey: null,
        };
      return {
        argumentDefinitions: [
          { defaultValue: null, kind: "LocalArgument", name: "account_id" },
          { defaultValue: null, kind: "LocalArgument", name: "account_type" },
          { defaultValue: null, kind: "LocalArgument", name: "category_name" },
          {
            defaultValue: null,
            kind: "LocalArgument",
            name: "reauth_content_type",
          },
        ],
        kind: "Fragment",
        metadata: null,
        name: "SecuredActionPasswordChallengeDialog_query",
        selections: [
          {
            kind: "RequiredField",
            field: {
              alias: null,
              args: null,
              concreteType: "FXManageAccountsQueries",
              kind: "LinkedField",
              name: "fx_accounts_management",
              plural: !1,
              selections: [
                {
                  kind: "RequiredField",
                  field: {
                    alias: null,
                    args: null,
                    concreteType: null,
                    kind: "LinkedField",
                    name: "accounts",
                    plural: !0,
                    selections: [
                      {
                        kind: "RequiredField",
                        field: {
                          alias: null,
                          args: null,
                          kind: "ScalarField",
                          name: "id",
                          storageKey: null,
                        },
                        action: "THROW",
                        path: "fx_accounts_management.accounts.id",
                      },
                      {
                        kind: "RequiredField",
                        field: {
                          alias: null,
                          args: null,
                          kind: "ScalarField",
                          name: "display_name",
                          storageKey: null,
                        },
                        action: "THROW",
                        path: "fx_accounts_management.accounts.display_name",
                      },
                      {
                        kind: "RequiredField",
                        field: {
                          alias: null,
                          args: null,
                          concreteType: "XFBFXPlatformInfo",
                          kind: "LinkedField",
                          name: "platform_info",
                          plural: !1,
                          selections: [
                            {
                              kind: "RequiredField",
                              field: e,
                              action: "THROW",
                              path: "fx_accounts_management.accounts.platform_info.name",
                            },
                            {
                              kind: "RequiredField",
                              field: {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "type",
                                storageKey: null,
                              },
                              action: "THROW",
                              path: "fx_accounts_management.accounts.platform_info.type",
                            },
                          ],
                          storageKey: null,
                        },
                        action: "THROW",
                        path: "fx_accounts_management.accounts.platform_info",
                      },
                      {
                        kind: "RequiredField",
                        field: {
                          alias: null,
                          args: null,
                          concreteType: "XFBFXProfilePictureInfo",
                          kind: "LinkedField",
                          name: "profile_picture_info",
                          plural: !1,
                          selections: [
                            {
                              kind: "RequiredField",
                              field: {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "url",
                                storageKey: null,
                              },
                              action: "THROW",
                              path: "fx_accounts_management.accounts.profile_picture_info.url",
                            },
                          ],
                          storageKey: null,
                        },
                        action: "THROW",
                        path: "fx_accounts_management.accounts.profile_picture_info",
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "identity_type",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "is_msplit",
                        storageKey: null,
                      },
                    ],
                    storageKey: null,
                  },
                  action: "THROW",
                  path: "fx_accounts_management.accounts",
                },
              ],
              storageKey: null,
            },
            action: "THROW",
            path: "fx_accounts_management",
          },
          {
            kind: "RequiredField",
            field: {
              alias: null,
              args: [
                {
                  kind: "Variable",
                  name: "account_id",
                  variableName: "account_id",
                },
                {
                  kind: "Variable",
                  name: "account_type",
                  variableName: "account_type",
                },
                {
                  kind: "Variable",
                  name: "category_name",
                  variableName: "category_name",
                },
              ],
              concreteType: "XFBPasswordType",
              kind: "LinkedField",
              name: "password",
              plural: !1,
              selections: [
                {
                  kind: "RequiredField",
                  field: {
                    alias: null,
                    args: null,
                    concreteType: "PublicKeyAndIDForEncryption",
                    kind: "LinkedField",
                    name: "public_key_and_id_for_encryption",
                    plural: !1,
                    selections: [
                      {
                        kind: "RequiredField",
                        field: {
                          alias: null,
                          args: null,
                          kind: "ScalarField",
                          name: "public_key",
                          storageKey: null,
                        },
                        action: "THROW",
                        path: "password.public_key_and_id_for_encryption.public_key",
                      },
                      {
                        kind: "RequiredField",
                        field: {
                          alias: null,
                          args: null,
                          kind: "ScalarField",
                          name: "key_id",
                          storageKey: null,
                        },
                        action: "THROW",
                        path: "password.public_key_and_id_for_encryption.key_id",
                      },
                    ],
                    storageKey: null,
                  },
                  action: "THROW",
                  path: "password.public_key_and_id_for_encryption",
                },
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "password_reset_uri",
                  storageKey: null,
                },
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "show_fxreauth_design",
                  storageKey: null,
                },
                {
                  alias: null,
                  args: null,
                  concreteType: "FXCALSettingsErrorDialog",
                  kind: "LinkedField",
                  name: "error_data",
                  plural: !1,
                  selections: [
                    {
                      kind: "RequiredField",
                      field: t,
                      action: "THROW",
                      path: "password.error_data.title",
                    },
                    {
                      kind: "RequiredField",
                      field: n,
                      action: "THROW",
                      path: "password.error_data.description",
                    },
                    {
                      kind: "RequiredField",
                      field: {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "dismiss_label",
                        storageKey: null,
                      },
                      action: "THROW",
                      path: "password.error_data.dismiss_label",
                    },
                  ],
                  storageKey: null,
                },
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "has_password",
                  storageKey: null,
                },
                {
                  args: null,
                  kind: "FragmentSpread",
                  name: "SecuredActionCreatePasswordText_node",
                },
              ],
              storageKey: null,
            },
            action: "THROW",
            path: "password",
          },
          {
            alias: null,
            args: null,
            concreteType: "Viewer",
            kind: "LinkedField",
            name: "viewer",
            plural: !1,
            selections: [
              {
                alias: null,
                args: null,
                concreteType: null,
                kind: "LinkedField",
                name: "actor",
                plural: !1,
                selections: [e],
                storageKey: null,
              },
            ],
            storageKey: null,
          },
          {
            kind: "RequiredField",
            field: {
              alias: null,
              args: [
                {
                  kind: "Variable",
                  name: "account_identifier",
                  variableName: "account_id",
                },
                {
                  kind: "Variable",
                  name: "reauth_content_type",
                  variableName: "reauth_content_type",
                },
              ],
              concreteType: "XFBFXSettingsNativePasswordReauthContent",
              kind: "LinkedField",
              name: "reauth_content",
              plural: !1,
              selections: [
                {
                  kind: "RequiredField",
                  field: t,
                  action: "THROW",
                  path: "reauth_content.title",
                },
                {
                  kind: "RequiredField",
                  field: n,
                  action: "THROW",
                  path: "reauth_content.description",
                },
                {
                  kind: "RequiredField",
                  field: {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "continue_button_text",
                    storageKey: null,
                  },
                  action: "THROW",
                  path: "reauth_content.continue_button_text",
                },
                {
                  kind: "RequiredField",
                  field: {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "password_text",
                    storageKey: null,
                  },
                  action: "THROW",
                  path: "reauth_content.password_text",
                },
                {
                  kind: "RequiredField",
                  field: {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "forgot_password_text",
                    storageKey: null,
                  },
                  action: "THROW",
                  path: "reauth_content.forgot_password_text",
                },
              ],
              storageKey: null,
            },
            action: "THROW",
            path: "reauth_content",
          },
        ],
        type: "Query",
        abstractKey: null,
      };
    })();
    a.exports = e;
  },
  null,
);
