__d(
  "SidneeAbrConfigDefaults",
  [],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = 5e3,
      l = "0,1,1; 80,1.5,1.3; 97,2.0,1",
      s = 1,
      u = 65,
      c = 1,
      d = 5e3,
      m = 3e4,
      p = 2,
      _ = "0,1,1.4; 100,2,1",
      f = 1,
      g = 3e4,
      h = 1.7,
      y = 80,
      C = 1.3,
      b = 1.5,
      v = 1.85,
      S = 50,
      R = 0.5,
      L = 4,
      E = "-1,2,1; 0,1.7,2; 1,1",
      k = 1,
      I = 4,
      T = 2;
    ((i.avgSegmentDurationMsDefault = e),
      (i.badUploadQualityRewardCurveDefault = l),
      (i.badUploadQualityRewardCurveFallbackDefault = s),
      (i.badUploadQualityThresholdDefault = u),
      (i.bitrateMultiplierDefault = c),
      (i.bufferReductionMsDefault = d),
      (i.defaultVideoDurationMsDefault = m),
      (i.encodingRiskDefault = p),
      (i.goodUploadQualityRewardCurveDefault = _),
      (i.goodUploadQualityRewardCurveFallbackDefault = f),
      (i.lookAheadMsDefault = g),
      (i.maxAggressiveRiskDefault = h),
      (i.maxBandwidthConfidencePctDefault = y),
      (i.maxConservativeRiskDefault = C),
      (i.maxNormalRiskDefault = b),
      (i.maxVeryAggressiveRiskDefault = v),
      (i.minBandwidthConfidencePctDefault = S),
      (i.minBitrateMultiplierDefault = R),
      (i.rewardRatioRoundDigitsDefault = L),
      (i.riskCurveDefault = E),
      (i.riskCurveFallbackDefault = k),
      (i.riskRatioRoundDigitsDefault = I),
      (i.riskRewardRatioRoundDigitsDefault = T));
  },
  66,
);
