__d(
  "SignalsConnectionMethod",
  ["$InternalEnum"],
  function (t, n, r, o, a, i) {
    var e = n("$InternalEnum")({
        UNKNOWN: 0,
        BROWSER: 1,
        SERVER: 2,
        APP: 3,
        ONSITE: 5,
        BROWSER_MEASUREMENT: 6,
        SKADNETWORK: 7,
        SAFARI_PCM: 8,
        CHROME_MEASUREMENT: 9,
        IAW_AEM: 10,
        SERVER_AEM: 11,
        LOCAL_COMPUTATION_LOGGING: 12,
        EVENTS_MANAGER_UI_UPLOADER: 13,
        SFTP: 14,
        APP_AEM: 15,
        APPLE_APP_TO_WEB_PCM: 16,
        MMP: 17,
        SDK: 18,
        AE_API: 19,
        BROWSER_HISTORY: 20,
        META_CHECKOUT: 22,
        META_PAY: 23,
        FOA_INSTALL_STATUS: 24,
        IAB_AUTOFILL: 25,
        WHATSAPP_3PD: 26,
        META_CHECKOUT_SHOPIFY_1PD: 27,
        IAB_GENERIC_SIGNALS_1PD: 28,
        SERVER_CTX: 29,
        CAPIG: 30,
        SHOP_ADS_1PD: 32,
        CTX_MESSENGER_1PD: 34,
        CTX_MESSENGER_3PD: 35,
        CTX_INSTAGRAM_DIRECT_1PD: 36,
        CTX_INSTAGRAM_DIRECT_3PD: 37,
        CTX_WHATSAPP_1PD: 38,
        CTX_WHATSAPP_3PD: 39,
        CTA_WHATSAPP_1PD: 40,
        IAB_PIXEL_LESS_LPV: 41,
        PRIVACY_SANDBOX_ARA: 42,
        OCULUS_VR: 43,
        IAB_GENERIC_SIGNALS_3PD: 44,
        APP_GENERIC_SIGNALS_1PD: 45,
        CTA_MESSENGER_1PD: 46,
        AMAZON_VO: 47,
        SIGNALS_GATEWAY_1P: 48,
        WHATSAPP_1PD: 49,
        AD_REQUEST: 50,
        AD_IMPRESSION: 51,
        LINK_HISTORY_V2: 52,
        OCULUS_AD_1PD: 53,
        MM_WHATSAPP_1PD: 54,
        SHADOW_TEST_1PD: 55,
        IAB_MESSENGER_1PD: 56,
        MM_WHATSAPP_ONSITE_3PD: 57,
        LINK_HISTORY_V3: 58,
        FB_APP_INSTALL: 59,
        DEV_RESOURCES_CONTROLLER: 60,
        APP_AUTH_LOGGER: 61,
        DERIVED_EVENTS_PROCESSOR: 62,
        FLOW_STATE_BASE: 63,
        APP_MANAGER_3RD_PARTY: 64,
        GAMING_SERVICES_UNIVERSAL: 65,
        GAMING_UNIVERSAL: 66,
        SEM_FB_INHOUSE_CONVERSION: 67,
        PLATFORM_CONVERSION_TRACKING: 68,
        COMMERCE_LOGGING_API: 69,
        INSTANT_GAME_APP_EVENTS: 70,
        INSIGHTS_META: 71,
        FIRST_PARTY_ONSITE: 72,
        MM_WHATSAPP_SP: 73,
        ADS_SDK: 74,
        SHORT_DRAMA: 75,
        SHOP_EVERYTHING_1PD: 76,
        CTWA_WHATSAPP_1PD: 77,
      }),
      l = e;
    i.default = l;
  },
  66,
);
