__d(
  "StateSyncTopicsConfigTypes",
  ["$InternalEnum"],
  function (t, n, r, o, a, i) {
    "use strict";
    var e,
      l = (e = n("$InternalEnum"))({ UNKNOWN: 0, INTERNAL: 1, EXTERNAL: 2 }),
      s = e({
        UNKNOWN: 0,
        PARTICIPANT_JOIN: 100,
        PARTICIPANT_UPDATE: 101,
        PARTICIPANT_LEAVE: 102,
        PARTICIPANT_NEGOTIATED: 103,
        PARTICIPANT_SDP_CHANGED: 104,
        EXTENSION_CREATION: 201,
        EXTENSION_JOIN: 202,
        EXTENSION_UPDATE: 203,
        EXTENSION_LEAVE: 204,
        EXTENSION_REQUEST: 205,
        CONFERENCE_UPDATE: 501,
        DOMINANT_SPEAKER_UPDATE: 1001,
        MEDIA_ASPECT_RATIO_UPDATE: 1002,
        TIMER_FIRED: 1003,
        MEDIA_PATH_CHANGED: 1004,
        PARTICIPANTS_ACKED_MEDIA: 1005,
      }),
      u = e({ UNKNOWN: 0, ANY_PARTICIPANT_SUBSCRIBED: 1, ALWAYS_RESOLVE: 2 }),
      c = e({ CACHIUS: 1, IRIS: 2 }),
      d = e({
        Config_engine: 1,
        E2eeState: 2,
        Media_information: 3,
        Breakout: 4,
        Countdown_timer: 5,
        Effect_match: 6,
        Emoji_reactions: 7,
        Entered_avatars_mode: 8,
        Moderator_controls: 9,
        Polls: 10,
        Raised_hands_queue: 11,
        Xac_calling: 12,
        Action_items: 13,
        Can_you_see_my_screen: 14,
        Collage: 15,
        Companion: 16,
        Coplay: 17,
        Coview: 18,
        Custom_video_capabilities: 19,
        Dropin: 20,
        Dtmf: 21,
        E2ee_v2_msg: 22,
        Effect_sync: 23,
        Et_pluto_activity: 24,
        Et_pluto_session: 25,
        Et_test_activity: 26,
        Et_test_session: 27,
        Et_tubi_activity: 28,
        Et_tubi_session: 29,
        External_resolution_enabled: 30,
        Hyperspace_copresence_state: 31,
        Hyperspace_mic_state: 32,
        Intenticons: 33,
        Live_stream: 34,
        Live_stream_app_message: 35,
        Max_video_subscriptions: 36,
        Media_sync: 37,
        Media_sync_autoplay: 38,
        Meeting_assistant: 39,
        Meeting_transcription: 40,
        Morpheo_grid: 41,
        Multipeer_ar: 42,
        Number_of_people: 43,
        Opaque_blob: 44,
        Photo_booth: 45,
        Qna: 46,
        Quizzes: 47,
        Reactions: 48,
        Role_assignments: 49,
        Room_features_availability: 50,
        Rooms_notes: 51,
        Screenshare_floor_control: 52,
        Screenshare_single_floor_control: 53,
        Sctp_negotiation: 54,
        Sideband: 55,
        Simple: 56,
        Simple_external: 57,
        Simple_pass_through: 58,
        Simple_passthrough: 59,
        Snippets: 60,
        Sound_effects: 61,
        Whiteboard: 62,
        Whiteboard_messenger: 63,
        Workroom: 64,
        Workrooms_ask_everyone_to_open: 65,
        Workrooms_vr: 66,
        Avatar_transport_state: 67,
        Ambisonic: 68,
        Cathode_extension: 69,
        Biz_calling: 70,
        Work_costreaming: 71,
        Conversation_bot: 72,
        Voip_zone: 73,
        Admin_initiated_casting: 74,
        Smart_glasses_assistant: 75,
        Codec_avatar_2d: 76,
        Custom_media_routing: 77,
        Generic_floor_control: 78,
      });
    a.exports = {
      CryptoAuthVerifierIdentity: c,
      DataSource: s,
      DataSourceCondition: u,
      ResolutionPath: l,
      TopicId: d,
    };
  },
  null,
);
