__d(
  "TimelineAppSectionType",
  [],
  function (t, n, r, o, a, i) {
    var e = Object.freeze({
      APP: 0,
      ABOUT: 1,
      FRIENDS: 2,
      PHOTOS: 3,
      LIKES: 4,
      MAP: 5,
      SUBSCRIPTIONS: 6,
      SUBSCRIBERS: 7,
      PAGE_LIKES: 8,
      NOTES: 9,
      EVENTS: 10,
      BOOKS: 11,
      MUSIC: 12,
      TV_SHOWS: 13,
      MOVIES: 14,
      FITNESS: 15,
      CONTACT: 16,
      GROUPS: 17,
      SPORTS: 18,
      GAMES: 19,
      SAVED_FOR_LATER: 20,
      REVIEWS: 21,
      AT_WORK: 22,
      VIDEOS: 23,
      SAVE_LISTS: 24,
      TASKS: 25,
      FUN_FACT_ANSWERS: 26,
      SPACES: 27,
      STORIES_ARCHIVE: 28,
      WORK_CHAT: 29,
      TIMELINE: 30,
      WORK_FILES: 31,
      SHOP: 32,
      FRONTLINE_AREAS: 33,
      MENTIONS: 34,
      SERVICES: 35,
      FUNDRAISERS: 36,
      RATINGS: 38,
      JOBS: 39,
      LIVE_VIDEOS: 40,
      SOCIAL_LEARNING: 41,
      COMMUNITY: 42,
      MENU: 43,
      EXCLUSIVE_CONTENT: 44,
      COMMUNITY_PERMALINK: 45,
      HASHTAGS: 46,
      VOLUNTEERING: 47,
      MEMBERS: 48,
      COMMUNITY_RULES: 49,
      MEMBERS_BADGES: 50,
      LIVE_SHOPPING: 51,
      COLLECTIBLES: 52,
      PLACES_LIVED: 53,
      WORK: 54,
      EDUCATION: 55,
      CONTACT_INFO: 56,
      BASIC_INFO: 57,
      BLOOD_DONOR_INFO: 58,
      NAME_PRONUNCIATION: 59,
      NICKNAMES: 60,
      RELATIONSHIP: 61,
      FAMILY: 62,
      CATEGORY: 63,
      TRANSPARENCY: 64,
      INTERESTED_IN: 65,
      POLITICAL_VIEWS: 66,
      RELIGIOUS_VIEWS: 67,
      LIFE_EVENTS: 68,
      REELS: 69,
      MUSIC_CHARTS: 70,
      ARTICLES: 71,
      PUBLIC_CHATS: 72,
      CHANNELS: 73,
      FANDOM_BADGES: 74,
      RELATED_ACCOUNTS: 75,
    });
    i.default = e;
  },
  66,
);
