__d(
  "useLWISAFRData_safrPolicy.graphql",
  [],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = {
      argumentDefinitions: [],
      kind: "Fragment",
      metadata: null,
      name: "useLWISAFRData_safrPolicy",
      selections: [
        {
          kind: "RequiredField",
          field: {
            alias: null,
            args: null,
            concreteType: "SAFRDynamicUIRestrictions",
            kind: "LinkedField",
            name: "restrictions",
            plural: !1,
            selections: [
              {
                alias: null,
                args: null,
                concreteType: "SAFRConversionConfig",
                kind: "LinkedField",
                name: "conversion",
                plural: !1,
                selections: [
                  {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "promoted_object_blacklist",
                    storageKey: null,
                  },
                ],
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                concreteType: "SAFRFormatConfig",
                kind: "LinkedField",
                name: "format",
                plural: !1,
                selections: [
                  {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "format_blacklist",
                    storageKey: null,
                  },
                ],
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                concreteType: "SAFRObjectiveConfig",
                kind: "LinkedField",
                name: "objective",
                plural: !1,
                selections: [
                  {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "objective_blacklist",
                    storageKey: null,
                  },
                ],
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                concreteType: "SAFRPlacementsConfig",
                kind: "LinkedField",
                name: "placements",
                plural: !1,
                selections: [
                  {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "platform_blacklist",
                    storageKey: null,
                  },
                ],
                storageKey: null,
              },
              {
                kind: "InlineDataFragmentSpread",
                name: "LWICometSAFRUtils_ageRestrictions",
                selections: [
                  {
                    alias: null,
                    args: null,
                    concreteType: "SAFRAgeConfig",
                    kind: "LinkedField",
                    name: "age",
                    plural: !1,
                    selections: [
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "default_max_age",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "default_min_age",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "max_age_range",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "min_age_range",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "is_max_age_fixed",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "is_min_age_fixed",
                        storageKey: null,
                      },
                    ],
                    storageKey: null,
                  },
                ],
                args: null,
                argumentDefinitions: [],
              },
              {
                kind: "InlineDataFragmentSpread",
                name: "LWICometSAFRUtils_genderRestrictions",
                selections: [
                  {
                    alias: null,
                    args: null,
                    concreteType: "SAFRGenderConfig",
                    kind: "LinkedField",
                    name: "gender",
                    plural: !1,
                    selections: [
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "is_enabled",
                        storageKey: null,
                      },
                    ],
                    storageKey: null,
                  },
                ],
                args: null,
                argumentDefinitions: [],
              },
              {
                kind: "InlineDataFragmentSpread",
                name: "LWICometSAFRUtils_radiusRestrictions",
                selections: [
                  {
                    alias: null,
                    args: null,
                    concreteType: "SAFRLocationRadiusConfig",
                    kind: "LinkedField",
                    name: "location_radius",
                    plural: !1,
                    selections: [
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "default_radius_unit",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "default_radius_value",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "max_radius",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "min_radius",
                        storageKey: null,
                      },
                    ],
                    storageKey: null,
                  },
                ],
                args: null,
                argumentDefinitions: [],
              },
            ],
            storageKey: null,
          },
          action: "THROW",
          path: "restrictions",
        },
      ],
      type: "SAFRDynamicUIPolicy",
      abstractKey: null,
    };
    a.exports = e;
  },
  null,
);
