__d(
  "useWAWebStatusVisibilityLogger",
  ["WAWebMerlinImpressionManager", "react", "useVPVDImpression"],
  function (t, n, r, o, a, i, l) {
    "use strict";
    var e,
      s = (e || (e = o("react"))).useCallback;
    function u(e) {
      var t = e.encryptedStatusIdPromise,
        n = e.entryMethod,
        a = e.isCloseSharingPost,
        i = e.isFirstView,
        l = e.isPosterBiz,
        u = e.isSelfView,
        c = e.isSubImpression,
        d = e.isSuccessfulView,
        m = e.itemId,
        p = e.mediaType,
        _ = e.musicBlocked,
        f = e.psaCampaignId,
        g = e.psaLinkAvailable,
        h = e.statusCategory,
        y = e.statusContainsMusic,
        C = e.statusContainsQuestion,
        b = e.statusContentType,
        v = e.statusGroupIdPromise,
        S = e.statusItemViewResult,
        R = e.statusLoadTime,
        L = e.statusPogIndex,
        E = e.statusPosterIdPromise,
        k = e.statusPostIndex,
        I = e.statusPostPlaybackDuration,
        T = e.statusViewEntrypoint,
        D = e.statusViewerSessionId,
        x = e.updatesTabSessionId,
        $ = e.urlStatusType,
        P = e.userRidPromise,
        N = e.viewSequenceIndex,
        M = s(
          function (e) {
            var r = e.hiddenTime,
              s = e.visibleDuration,
              M = e.visibleTime;
            o("WAWebMerlinImpressionManager").logStatusVisibility({
              enter_ts: M,
              exit_ts: r,
              statusViewTime: s,
              itemId: m,
              visibilityData: {
                encryptedStatusIdPromise: t,
                userRidPromise: P,
                statusPosterIdPromise: E,
                statusGroupIdPromise: v,
                statusContentType: b,
                mediaType: p,
                isSelfView: u,
                isSubImpression: c,
                isFirstView: i,
                isCloseSharingPost: a,
                statusContainsMusic: y,
                musicBlocked: _,
                statusViewEntrypoint: T,
                updatesTabSessionId: x,
                statusViewerSessionId: D,
                statusPogIndex: L,
                statusPostIndex: k,
                statusCategory: h,
                statusPostPlaybackDuration: I,
                psaCampaignId: f,
                psaLinkAvailable: g,
                statusLoadTime: R,
                urlStatusType: $,
                isPosterBiz: l,
                statusContainsQuestion: C,
                isSuccessfulView: d,
                statusItemViewResult: S,
                entryMethod: n,
                viewSequenceIndex: N,
              },
            });
          },
          [
            m,
            t,
            P,
            E,
            v,
            b,
            p,
            u,
            c,
            i,
            a,
            y,
            _,
            T,
            x,
            D,
            L,
            k,
            h,
            I,
            f,
            g,
            R,
            $,
            l,
            C,
            d,
            S,
            n,
            N,
          ],
        );
      return r("useVPVDImpression")({ onVPVDEnd: M });
    }
    l.default = u;
  },
  98,
);
