__d(
  "VideoPlayerAutoplayRulesProvider",
  [
    "FBLogger",
    "VideoPlayerViewabilityConstants",
    "createEvaluateVideoAutoplayIgnoreOnInvisibleRule",
    "createEvaluateVideoAutoplayIgnoreOnLowBandwidthRule",
    "createEvaluateVideoAutoplayPauseOnInvisibleRule",
    "createEvaluateVideoAutoplayPauseOnMutedInvisibleRule",
    "evaluateVideoAutoplayDefaultIgnoreRule",
    "evaluateVideoAutoplayIgnoreOnBackgroundedRule",
    "evaluateVideoAutoplayIgnoreOnBroadcastEndedRule",
    "evaluateVideoAutoplayIgnoreOnEndedRule",
    "evaluateVideoAutoplayIgnoreOnFrozenRule",
    "evaluateVideoAutoplayIgnoreOnProductPausedRule",
    "evaluateVideoAutoplayIgnoreOnUnmuteRule",
    "evaluateVideoAutoplayIgnoreOnUserPausedRule",
    "evaluateVideoAutoplayIgnoreOnUserPlayRule",
    "evaluateVideoAutoplayPauseOnAdBackgroundedRule",
    "evaluateVideoAutoplayPauseOnAdInvisibleRule",
    "evaluateVideoAutoplayPauseOnAdMutedBackgroundedRule",
    "evaluateVideoAutoplayPauseOnBackgroundedRule",
    "evaluateVideoAutoplayPauseOnBackgroundedSubtreeRule",
    "evaluateVideoAutoplayPauseOnHiddenSubtreeRule",
    "evaluateVideoAutoplayPauseOnMutedBackgroundedRule",
  ],
  function (t, n, r, o, a, i, l) {
    "use strict";
    var e,
      s,
      u,
      c,
      d,
      m,
      p,
      _,
      f,
      g,
      h,
      y,
      C,
      b = 25e4,
      v = [
        (e = r("evaluateVideoAutoplayIgnoreOnFrozenRule")),
        (s = r("evaluateVideoAutoplayPauseOnAdInvisibleRule")),
        (u = r("createEvaluateVideoAutoplayPauseOnInvisibleRule"))(
          (c = r("VideoPlayerViewabilityConstants"))
            .DEFAULT_VIEWABILITY_PERCENTAGE_FOR_PAUSE,
        ),
        (d = r("evaluateVideoAutoplayPauseOnAdMutedBackgroundedRule")),
        (m = r("evaluateVideoAutoplayPauseOnHiddenSubtreeRule")),
        (p = r("evaluateVideoAutoplayIgnoreOnUnmuteRule")),
        (_ = r("evaluateVideoAutoplayIgnoreOnUserPausedRule")),
        (f = r("evaluateVideoAutoplayIgnoreOnUserPlayRule")),
        (g = r("evaluateVideoAutoplayIgnoreOnEndedRule")),
      ],
      S = [
        e,
        s,
        u(c.DEFAULT_VIEWABILITY_PERCENTAGE_FOR_PAUSE),
        (h = r("evaluateVideoAutoplayPauseOnBackgroundedSubtreeRule")),
        d,
        m,
        p,
        _,
        f,
        g,
      ],
      R = [
        e,
        s,
        u(c.DEFAULT_VIEWABILITY_PERCENTAGE_FOR_PAUSE),
        (y = r("createEvaluateVideoAutoplayIgnoreOnLowBandwidthRule"))(b),
        r("evaluateVideoAutoplayPauseOnAdBackgroundedRule"),
        (C = r("evaluateVideoAutoplayPauseOnMutedBackgroundedRule")),
        m,
        p,
        _,
        f,
        g,
      ],
      L = [e, y(b), C, p, _, f, g],
      E = [e, u(c.DEFAULT_VIEWABILITY_PERCENTAGE_FOR_PAUSE), m, _, f, g],
      k = [e, s, d, m, y(b), _];
    (k.push(u(c.DEFAULT_VIEWABILITY_PERCENTAGE_FOR_PAUSE)),
      k.push(r("evaluateVideoAutoplayIgnoreOnBroadcastEndedRule")));
    var I = k.slice(),
      T = [
        e,
        s,
        r("createEvaluateVideoAutoplayPauseOnMutedInvisibleRule")(0.01),
        d,
        m,
        p,
        _,
        f,
        g,
      ].filter(Boolean),
      D = [e, u(c.DEFAULT_VIEWABILITY_PERCENTAGE_FOR_PAUSE), m, p, _, f, g],
      x = [e, u(c.DEFAULT_VIEWABILITY_PERCENTAGE_FOR_PAUSE), m, p, _, f, g],
      $ = [e, s, d, m, p, _, f, g],
      P = [e, s, m, _, f, g],
      N = [e, m, p, _, f, g],
      M = [e, m, p, _, f, g],
      w = [e, s, u(c.DEFAULT_VIEWABILITY_PERCENTAGE_FOR_PAUSE), d, p, _, f, g],
      A = [r("evaluateVideoAutoplayDefaultIgnoreRule")],
      F = [u(0)],
      O = [u(0)],
      B = [
        e,
        u(0.25),
        r("evaluateVideoAutoplayPauseOnBackgroundedRule"),
        m,
        _,
        h,
      ],
      W = [e, m, _],
      q = [u(0.25)],
      U = [e, C, m, p, _, f, g, u(0.001)],
      V = [C, m, p, _],
      H = [
        e,
        u(c.DEFAULT_VIEWABILITY_PERCENTAGE_FOR_PAUSE),
        C,
        h,
        m,
        p,
        _,
        f,
        g,
      ],
      G = [],
      z = [e, m, _, f, g],
      j = [e, s, y(b), C, m, p, _, f, g],
      K = [e, m, u(0), p, _, f, g],
      Q = [e, m, h, u(c.DEFAULT_VIEWABILITY_PERCENTAGE_FOR_PAUSE), p, _, f, g],
      X = [e, m, u(0.25), p, _, f, g],
      Y = [
        r("evaluateVideoAutoplayIgnoreOnBackgroundedRule"),
        r("createEvaluateVideoAutoplayIgnoreOnInvisibleRule")(0),
      ],
      J = [
        e,
        s,
        u(c.DEFAULT_VIEWABILITY_PERCENTAGE_FOR_PAUSE),
        d,
        m,
        p,
        _,
        r("evaluateVideoAutoplayIgnoreOnProductPausedRule"),
        f,
        g,
      ],
      Z = {
        always_disable: A,
        barcelona_carousel: V,
        barcelona_feed: H,
        basic: v,
        bulletin: F,
        creator_studio: w,
        creator_studio_sliding_tray_rules: O,
        default_feed: R,
        dolly: U,
        focused_story_view: L,
        gif: E,
        igd_music_sticker: Y,
        kadabra_lightbox_feed: Q,
        kadabra_tile_feed: X,
        kds_video: K,
        live_producer: D,
        live_studio: x,
        music_at_post_level_experience: j,
        polaris_feed: B,
        polaris_grid: q,
        polaris_live: W,
        polaris_notes: G,
        reels: S,
        reels_audio: z,
        stages: M,
        tournament_hero: $,
        wa_web: J,
        watch_feed: I,
        watch_live_tab: T,
        wns: P,
        work_knowledge: N,
      },
      ee = function (t) {
        var e = Z[t];
        if (!e)
          throw r("FBLogger")("comet_video_player").mustfixThrow(
            "Unknown VideoPlayerAutoplayRulesType passed to VideoPlayerAutoplayRulesProvider",
          );
        return e;
      };
    function te(e) {
      return e;
    }
    ((l.provideAutoplayRules = ee), (l.makeVideoPlayerAutoplayRules = te));
  },
  98,
);
