__d(
  "VideoData",
  ["invariant"],
  function (t, n, r, o, a, i, l, s) {
    var e = (function () {
      function e(e) {
        this.$1 = e || {
          aspect_ratio: 0,
          original_height: 0,
          original_width: 0,
          video_id: "",
        };
      }
      var t = e.prototype;
      return (
        (t.hasHD = function () {
          return !!this.$1.hd_src;
        }),
        (t.getP2PSettings = function () {
          return this.$1.p2p_settings;
        }),
        (t.getEncodingTag = function () {
          return this.$1.encoding_tag;
        }),
        (t.getContentCategory = function () {
          return this.$1.content_category;
        }),
        (t.getVideoID = function () {
          return this.$1.video_id;
        }),
        (t.getVideoURL = function () {
          return this.$1.video_url;
        }),
        (t.getAspectRatio = function () {
          return this.$1.aspect_ratio;
        }),
        (t.getRotation = function () {
          return this.$1.rotation || 0;
        }),
        (t.getCaptionsAutogeneratedIndicatorConfig = function () {
          return this.$1.captions_autogenerated_indicator_config;
        }),
        (t.hasSubtitles = function () {
          return !!this.$1.subtitles_src;
        }),
        (t.hasDashManifest = function () {
          return !!this.$1.dash_manifest;
        }),
        (t.getDashManifest = function () {
          return this.$1.dash_manifest;
        }),
        (t.getDashPrefetchedRepresentationIDs = function () {
          return this.$1.dash_prefetched_representation_ids;
        }),
        (t.getSubtitlesSrc = function () {
          var e = this.$1.subtitles_src;
          return ((e != null && e !== "") || s(0, 1109), e);
        }),
        (t.getPlayableSrcSD = function () {
          return this.$1.sd_src_no_ratelimit != null &&
            this.$1.sd_src_no_ratelimit !== ""
            ? this.$1.sd_src_no_ratelimit
            : this.getPlayableSrcRateLimitedSD();
        }),
        (t.getPlayableSrcHD = function () {
          return this.$1.hd_src_no_ratelimit != null &&
            this.$1.hd_src_no_ratelimit !== ""
            ? this.$1.hd_src_no_ratelimit
            : this.getPlayableSrcRateLimitedHD();
        }),
        (t.getPlayableSrcRateLimitedSD = function () {
          return this.$1.sd_src;
        }),
        (t.getPlayableSrcRateLimitedHD = function () {
          return this.$1.hd_src;
        }),
        (t.getLiveManifestUrl = function () {
          return (
            this.isLiveStream() || s(0, 1110),
            this.getPlayableSrcRateLimitedSD()
          );
        }),
        (t.hasRateLimit = function () {
          return !!this.$1.sd_src_no_ratelimit;
        }),
        (t.getStreamType = function () {
          var e = this.$1.stream_type;
          return ((e != null && e !== "") || s(0, 1111), e);
        }),
        (t.isBroadcast = function () {
          return !!this.$1.is_broadcast;
        }),
        (t.isServableViaFbms = function () {
          return !!this.$1.is_servable_via_fbms;
        }),
        (t.isLiveStream = function () {
          return !!this.$1.is_live_stream;
        }),
        (t.isHls = function () {
          return !!this.$1.is_hls;
        }),
        (t.isGaming = function () {
          return this.$1.content_category === "gaming";
        }),
        (t.isLowLatency = function () {
          return !!this.$1.is_low_latency;
        }),
        (t.getDesiredLatencyMs = function () {
          return this.$1.desired_latency_ms;
        }),
        (t.getLatencyToleranceMs = function () {
          return this.$1.latency_tolerance_ms;
        }),
        (t.isFacecastAudio = function () {
          return !!this.$1.is_facecast_audio;
        }),
        (t.liveRoutingToken = function () {
          return this.$1.live_routing_token;
        }),
        (t.getHDTag = function () {
          return this.$1.hd_tag;
        }),
        (t.getSDTag = function () {
          return this.$1.sd_tag;
        }),
        (t.getProjection = function () {
          return this.$1.projection;
        }),
        (t.getPlayerVersionOverwrite = function () {
          return this.$1.player_version_overwrite;
        }),
        (t.getFalloverData = function () {
          var t = this.$1.fallover_data;
          return t
            ? t.map(function (t) {
                return new e(t);
              })
            : [];
        }),
        (t.getSphericalConfig = function () {
          return this.$1.spherical_config;
        }),
        (t.isSpherical = function () {
          return !!this.$1.is_spherical;
        }),
        (t.getOriginalHeight = function () {
          return this.$1.original_height;
        }),
        (t.getOriginalWidth = function () {
          return this.$1.original_width;
        }),
        (t.getOverrideConfig = function () {
          return this.$1.override_config;
        }),
        (t.getRawData = function () {
          return this.$1;
        }),
        (t.getPrefetchCache = function () {
          return this.$1.prefetch_cache;
        }),
        (t.getWidevineCert = function () {
          return this.$1.widevine_cert;
        }),
        (t.getFairplayCert = function () {
          return this.$1.fairplay_cert;
        }),
        (t.getDRMHelper = function () {
          var e;
          return (e = this.$1) == null || (e = e.extra_drm_info) == null
            ? void 0
            : e.drm_helper;
        }),
        (t.getGraphApiVideoLicenseUri = function () {
          var e;
          return (e = this.$1) == null || (e = e.extra_drm_info) == null
            ? void 0
            : e.graph_api_video_license_uri;
        }),
        (t.getVideoLicenseUriMap = function () {
          var e;
          return (e = this.$1) == null || (e = e.extra_drm_info) == null
            ? void 0
            : e.video_license_uri_map;
        }),
        (t.isLiveTraceEnabledOnPlayer = function () {
          return !!this.$1.is_live_trace_enabled_on_player;
        }),
        (t.getManifestServiceParam = function () {
          var e;
          return (e = this.$1) == null ? void 0 : e.ms_param;
        }),
        e
      );
    })();
    l.default = e;
  },
  98,
);
