__d(
  "VideoPlayerImplementationEngineStateMachineWithEffects",
  [
    "CometVisualCompletion",
    "PlaybackSpeedExperiments",
    "VideoPlayerImplementationStateMachine",
    "VideoPlayerImplementationStateMachineHostCallQueue",
    "VideoPlayerImplementationStateMachineState",
    "VideoPlayerImplementationStateMachineStateUncontrolledState",
  ],
  function (t, n, r, o, a, i, l) {
    "use strict";
    function e(e) {
      var t = e.alwaysShowCaptions,
        n = e.areCaptionsAutogenerated,
        a = e.autoLoopSuspendedRef,
        i = e.captionDisplayStyle,
        l = e.captionsControllerRef,
        u = e.debugLogId,
        c = e.dimensions,
        d = e.engineExtrasAPI,
        m = e.engineMetadata,
        p = e.fullscreenControllerRef,
        _ = e.handleFatalError,
        f = e.handleStateMachine,
        g = e.videoElementAPIRef,
        h = e.videoLiveTraceRef,
        y = e.videoPlayerPassiveViewabilityInfo;
      function C(e) {
        o(
          "VideoPlayerImplementationStateMachineHostCallQueue",
        ).applyOrQueueHostCall({
          engineExtrasAPI: d,
          hostCall: e,
          machine: S,
          videoElementAPI: g.current,
        });
      }
      var b = null,
        v = [
          function (e, t, n) {
            return (
              n.type === "implementation_host_call_applied" &&
              n.payload.hostCall.type === "host_call_play" &&
              t.controlledState.lastPlayReason === "autoplay_initiated"
                ? r("CometVisualCompletion").addFirstMarkerPoint(
                    "firstVideoAutoplayStalling",
                  )
                : t.controlledState.playbackState !==
                    e.controlledState.playbackState &&
                  t.controlledState.playbackState === "playing" &&
                  t.controlledState.lastPlayReason === "autoplay_initiated" &&
                  r("CometVisualCompletion").addFirstMarkerPoint(
                    "firstVideoAutoplayPlaying",
                  ),
              !0
            );
          },
          function (e, t, n) {
            return (f(e, t, n), !0);
          },
          function (e, t, n) {
            return !0;
          },
          function (e, t, n) {
            if (
              (e.controlledState.bufferingDetected === !1 &&
                t.controlledState.bufferingDetected === !0) ||
              (e.controlledState.bufferingDetected === !0 &&
                t.controlledState.bufferingDetected === !1)
            )
              if (t.controlledState.bufferingDetected) {
                var r,
                  o =
                    (r = t.controlledState.lastBufferingType) != null
                      ? r
                      : "in_play",
                  a = d.getPerfLoggerProvider();
                b = a
                  ? a
                      .getOperationLogger("buffering")
                      .setState("buffering")
                      .setType(o)
                      .start()
                  : null;
              } else
                !t.controlledState.bufferingDetected &&
                  b != null &&
                  (b.log(), (b = null));
            return !0;
          },
          function (e, t, n) {
            return n.type !== "implementation_engine_destroy_requested";
          },
          function (e, t, n) {
            if (n.type !== "implementation_engine_initialized") return !0;
            var r = g.current;
            return (
              r != null &&
                o(
                  "VideoPlayerImplementationStateMachineHostCallQueue",
                ).flushHostCallQueue({
                  engineExtrasAPI: d,
                  machine: S,
                  reason: n.type,
                  state: t,
                  videoElementAPI: r,
                }),
              !1
            );
          },
          function (e, t, n) {
            if (n.type !== "implementation_video_node_mounted") return !0;
            var r = g.current;
            return (
              r != null &&
                t.controlledState.hostCallCanApply &&
                t.controlledState.hostCallQueue.length > 0 &&
                o(
                  "VideoPlayerImplementationStateMachineHostCallQueue",
                ).flushHostCallQueue({
                  engineExtrasAPI: d,
                  machine: S,
                  reason: "deferred_flush_on_video_element_mounted",
                  state: t,
                  videoElementAPI: r,
                }),
              !0
            );
          },
          function (e, t, n) {
            if (n.type !== "dom_event_ended") return !0;
            var r = t.controlledState;
            return (
              !a.current &&
                ((r.loopCount > 0 && r.loopCurrent < r.loopCount) ||
                  r.loopCount === -1) &&
                S.dispatch({
                  payload: { reason: "loop_initiated" },
                  type: "controller_play_requested",
                }),
              !1
            );
          },
          function (e, t, n) {
            if (n.type !== "controller_pause_requested") return !0;
            var r = t.controlledState.playbackState;
            return (
              r !== "paused" ||
                C({
                  payload: {
                    hostCallID: o(
                      "VideoPlayerImplementationStateMachineHostCallQueue",
                    ).makeHostCallID(),
                    reason: n.type,
                  },
                  type: "host_call_pause",
                }),
              !1
            );
          },
          function (e, t, n) {
            if (n.type !== "controller_play_requested") return !0;
            var r = t.controlledState.playbackState;
            return (
              r !== "stalling" ||
                C({
                  payload: {
                    hostCallID: o(
                      "VideoPlayerImplementationStateMachineHostCallQueue",
                    ).makeHostCallID(),
                    reason: n.type,
                  },
                  type: "host_call_play",
                }),
              !1
            );
          },
          function (e, t, n) {
            if (n.type !== "controller_seek_requested") return !0;
            var r = t.controlledState,
              a = r.seeking,
              i = r.seekTargetPosition;
            return (
              a &&
                i != null &&
                C({
                  payload: {
                    currentTime: i,
                    hostCallID: o(
                      "VideoPlayerImplementationStateMachineHostCallQueue",
                    ).makeHostCallID(),
                    reason: n.type,
                  },
                  type: "host_call_set_current_time",
                }),
              !1
            );
          },
          function (e, t, n) {
            if (n.type !== "controller_muted_requested") return !0;
            var r = t.controlledState.muted;
            return (
              r !== n.payload.muted ||
                C({
                  payload: {
                    hostCallID: o(
                      "VideoPlayerImplementationStateMachineHostCallQueue",
                    ).makeHostCallID(),
                    muted: r,
                    reason: n.type,
                  },
                  type: "host_call_set_muted",
                }),
              !1
            );
          },
          function (e, t, n) {
            return n.type !== "controller_scrub_begin_requested"
              ? !0
              : (C({
                  payload: {
                    hostCallID: o(
                      "VideoPlayerImplementationStateMachineHostCallQueue",
                    ).makeHostCallID(),
                    playbackRate: 0,
                    reason: n.type,
                  },
                  type: "host_call_set_playback_rate",
                }),
                !1);
          },
          function (e, t, n) {
            if (n.type !== "controller_scrub_end_requested") return !0;
            var r = t.controlledState,
              a = r.seeking,
              i = r.seekTargetPosition,
              l = r.targetPlaybackRate;
            return (
              a && i != null
                ? (C({
                    payload: {
                      hostCallID: o(
                        "VideoPlayerImplementationStateMachineHostCallQueue",
                      ).makeHostCallID(),
                      playbackRate: l,
                      reason: n.type + ":seek",
                    },
                    type: "host_call_set_playback_rate",
                  }),
                  C({
                    payload: {
                      currentTime: i,
                      hostCallID: o(
                        "VideoPlayerImplementationStateMachineHostCallQueue",
                      ).makeHostCallID(),
                      reason: n.type + ":seek",
                    },
                    type: "host_call_set_current_time",
                  }))
                : C({
                    payload: {
                      hostCallID: o(
                        "VideoPlayerImplementationStateMachineHostCallQueue",
                      ).makeHostCallID(),
                      playbackRate: l,
                      reason: n.type + ":cancel",
                    },
                    type: "host_call_set_playback_rate",
                  }),
              !1
            );
          },
          function (e, t, n) {
            return n.type !== "buffering_begin_requested"
              ? !0
              : (n.payload.disableZeroPlaybackRate === !0 ||
                  C({
                    payload: {
                      hostCallID: o(
                        "VideoPlayerImplementationStateMachineHostCallQueue",
                      ).makeHostCallID(),
                      playbackRate: 0,
                      reason: n.type,
                    },
                    type: "host_call_set_playback_rate",
                  }),
                !1);
          },
          function (e, t, n) {
            return n.type !== "controller_set_playback_rate"
              ? !0
              : (C({
                  payload: {
                    hostCallID: o(
                      "VideoPlayerImplementationStateMachineHostCallQueue",
                    ).makeHostCallID(),
                    playbackRate: n.payload.playbackRate,
                    reason: n.type,
                  },
                  type: "host_call_set_playback_rate",
                }),
                !1);
          },
          function (e, t, n) {
            return n.type !== "buffering_end_requested"
              ? !0
              : (C({
                  payload: {
                    hostCallID: o(
                      "VideoPlayerImplementationStateMachineHostCallQueue",
                    ).makeHostCallID(),
                    playbackRate: t.controlledState.targetPlaybackRate,
                    reason: n.type,
                  },
                  type: "host_call_set_playback_rate",
                }),
                !1);
          },
          function (e, t, n) {
            return n.type !== "controller_volume_requested"
              ? !0
              : (C({
                  payload: {
                    hostCallID: o(
                      "VideoPlayerImplementationStateMachineHostCallQueue",
                    ).makeHostCallID(),
                    reason: n.type,
                    volume: t.controlledState.volume,
                  },
                  type: "host_call_set_volume",
                }),
                !1);
          },
          function (e, t, n) {
            return n.type !== "controller_video_variant_requested"
              ? !0
              : (C({
                  payload: {
                    hostCallID: o(
                      "VideoPlayerImplementationStateMachineHostCallQueue",
                    ).makeHostCallID(),
                    reason: n.type,
                    selectedVideoVariant:
                      t.controlledState.selectedVideoVariant,
                  },
                  type: "host_call_set_video_variant",
                }),
                !1);
          },
          function (e, t, n) {
            return n.type !== "controller_quality_requested"
              ? !0
              : (C({
                  payload: {
                    hostCallID: o(
                      "VideoPlayerImplementationStateMachineHostCallQueue",
                    ).makeHostCallID(),
                    reason: n.type,
                    selectedVideoQuality:
                      t.controlledState.selectedVideoQuality,
                  },
                  type: "host_call_set_video_quality",
                }),
                !1);
          },
          function (e, t, n) {
            return n.type === "controller_set_latency_level_requested" ||
              n.type === "implementation_set_latency_level_requested"
              ? (C({
                  payload: {
                    hostCallID: o(
                      "VideoPlayerImplementationStateMachineHostCallQueue",
                    ).makeHostCallID(),
                    latencyLevel: n.payload.latencyLevel,
                    reason: n.type,
                  },
                  type: "host_call_set_latency_level",
                }),
                !1)
              : !0;
          },
          function (e, t, n) {
            if (
              !(
                n.type === "dom_event_timeupdate" ||
                n.type === "captions_loaded"
              )
            )
              return !0;
            var r = l.current,
              a = t.controlledState.captionsVisible,
              i = g.current,
              u = i ? i.getPlayheadPosition() : 0;
            if (
              o("PlaybackSpeedExperiments").enableCometPlaybackSpeedControl() &&
              t.controlledState.isLiveRewindActive
            ) {
              var c,
                m = t.controlledState.seekableRanges,
                p = m != null && (c = m.end(m.length() - 1)) != null ? c : 0;
              u >= p &&
                S.dispatch({
                  payload: { isLiveRewindActive: !1 },
                  type: "controller_set_is_live_rewind_active_requested",
                });
            }
            if (
              !d.getRepresentationCaptionsExpectedFromManifest() &&
              r &&
              a &&
              t.controlledState.captionsLoaded
            ) {
              var _ = r.handleTimeUpdate(u),
                f = r.getCaptionFormat(),
                y = e.controlledState.activeCaptions,
                C = e.controlledState.captionFormat;
              (f !== C &&
                S.dispatch({
                  payload: { captionFormat: f },
                  type: "controller_set_caption_format_requested",
                }),
                s(y, _) &&
                  S.dispatch({
                    payload: { activeCaptions: _, captionsLocale: null },
                    type: "controller_set_active_captions_requested",
                  }));
            }
            var b = h.current;
            return (b != null && b.onUpdateStatus({ position: u }), !1);
          },
          function (e, t, n) {
            if (n.type !== "cea608_bytes_received") return !0;
            var r = l.current;
            if (r) {
              var o = n.payload,
                a = o.timescale,
                i = o.videoBytes;
              r.handleCea608BytesReceived({ timescale: a, videoBytes: i });
            }
            return !1;
          },
          function (e, t, n) {
            if (n.type !== "controller_set_captions_url_requested") return !0;
            var r = l.current;
            if (r) {
              var o = n.payload.captionsUrl;
              r.updateCaptionsUrl(o);
            }
            return !1;
          },
          function (e, t, n) {
            return n.type !== "controller_set_is_live_rewind_active_requested"
              ? !0
              : (d.setEnableLiveheadCatchup(!n.payload.isLiveRewindActive),
                o(
                  "PlaybackSpeedExperiments",
                ).enableCometPlaybackSpeedControl() &&
                  !n.payload.isLiveRewindActive &&
                  S.dispatch({
                    payload: { playbackRate: 1 },
                    type: "controller_set_playback_rate",
                  }),
                !1);
          },
          function (e, t, n) {
            return n.type !== "controller_picture_in_picture_requested"
              ? !0
              : (C({
                  payload: {
                    hostCallID: o(
                      "VideoPlayerImplementationStateMachineHostCallQueue",
                    ).makeHostCallID(),
                    reason: n.type,
                  },
                  type: "host_call_picture_in_picture",
                }),
                !1);
          },
          function (e, t, n) {
            return n.type !== "controller_picture_in_picture_exit_requested"
              ? !0
              : (C({
                  payload: {
                    hostCallID: o(
                      "VideoPlayerImplementationStateMachineHostCallQueue",
                    ).makeHostCallID(),
                    reason: n.type,
                  },
                  type: "host_call_exit_picture_in_picture",
                }),
                !1);
          },
        ],
        S = o(
          "VideoPlayerImplementationStateMachine",
        ).createVideoPlayerImplementationStateMachineWithStateTransitionHandlers(
          {
            collectUncontrolledState: function () {
              var e = g.current;
              return o(
                "VideoPlayerImplementationStateMachineStateUncontrolledState",
              ).createVideoPlayerImplementationStateMachineStateUncontrolledState(
                {
                  engineExtrasAPI: d,
                  fullscreenControllerRef: p,
                  videoElementAPI: e,
                  videoLiveTraceRef: h,
                  videoPlayerPassiveViewabilityInfo: y,
                },
              );
            },
            debugLogId: u,
            initialState: o(
              "VideoPlayerImplementationStateMachineState",
            ).createVideoPlayerImplementationStateMachineInitialState({
              alwaysShowCaptions: t,
              areCaptionsAutogenerated: n,
              captionDisplayStyle: i,
              dimensions: c,
              isAbrEnabled: m.isAbrEnabled,
              playerVersion: m.playerVersion,
              streamingFormat: m.streamingFormat,
              videoPlayerPassiveViewabilityInfo: y,
            }),
            onFatalError: _,
            stateTransitionHandlers: v,
          },
        );
      return S;
    }
    function s(e, t) {
      var n, r;
      if (e === null && t === null) return !1;
      if (e === null || t === null) return !0;
      var o = (n = t.rows) != null ? n : [],
        a = (r = e.rows) != null ? r : [];
      return (
        a.length !== o.length ||
        a.some(function (e, t) {
          return e !== o[t];
        })
      );
    }
    l.createVideoPlayerImplementationEngineStateMachineWithEffects = e;
  },
  98,
);
