__d(
  "VideoCaption",
  ["immutable"],
  function (t, n, r, o, a, i, l) {
    var e = (function () {
      function e(e, t) {
        ((this.locale = e),
          (this.locale_name = t),
          (this.is_default = !1),
          (this.is_auto_generated = !1),
          (this.ads_placements_application_mode = null),
          (this.formatted_asset_customization_placements = null));
      }
      var t = e.prototype;
      return (
        (t.getLocale = function () {
          return this.locale;
        }),
        (t.getLocaleName = function () {
          return this.locale_name;
        }),
        (t.getIsDefault = function () {
          return this.is_default;
        }),
        (t.setIsDefault = function (t) {
          this.is_default = t;
        }),
        (t.getIsAutoGenerated = function () {
          return this.is_auto_generated;
        }),
        (t.setIsAutoGenerated = function (t) {
          this.is_auto_generated = t;
        }),
        (t.getCreateTime = function () {
          return this.create_time;
        }),
        (t.setCreateTime = function (t) {
          this.create_time = t;
        }),
        (t.getAdsPlacementApplicationMode = function () {
          return this.ads_placements_application_mode;
        }),
        (t.setAdsPlacementsApplicationMode = function (t) {
          this.ads_placements_application_mode = t;
        }),
        (t.getAssetCustomizationPlacements = function () {
          return this.formatted_asset_customization_placements;
        }),
        (t.setAssetCustomizationPlacements = function (t) {
          this.formatted_asset_customization_placements = r("immutable")
            .List(t)
            .map(function (e) {
              var t = e[0],
                n = e[1],
                r = null,
                o = null;
              if (t.key === "platform" && n.key === "position")
                ((r = t), (o = n));
              else if (t.key === "position" && n.key === "platform")
                ((r = n), (o = t));
              else return null;
              return { platform: r.value, position: o.value };
            })
            .filter(Boolean);
        }),
        e
      );
    })();
    l.default = e;
  },
  98,
);
