__d(
  "VideoPlayerWwwLogger",
  ["VideoPlayerWwwFalcoEvent"],
  function (t, n, r, o, a, i, l) {
    "use strict";
    function e(e) {
      var t,
        n =
          e.logData.live_trace_stream_id != null &&
          e.logData.live_trace_stream_type != null;
      return {
        access_token: e.logData.access_token,
        ad_client_token: e.logData.ad_client_token,
        attribution_id: e.logData.attribution_id,
        attribution_id_v2: e.logData.attribution_id_v2,
        attribution_id_v2_root: e.logData.attribution_id_v2_root,
        audio_only: e.logData.audio_only,
        audio_representation_id: e.logData.audio_representation_id,
        autoplay_eligible: e.logData.autoplay_eligible,
        autoplay_failure_reasons: e.logData.autoplay_failure_reasons,
        autoplay_setting: e.logData.autoplay_setting,
        available_qualities: e.logData.available_qualities,
        broadcaster_origin: e.logData.broadcaster_origin,
        browser_tab_id: e.logData.browser_tab_id,
        caption_state: e.logData.caption_state,
        cast_client_app_id: e.logData.cast_client_app_id,
        client_latency_setting: e.logData.client_latency_setting,
        current_playback_speed: e.logData.current_playback_speed,
        current_viewability_percentage: Number(
          e.logData.current_viewability_percentage,
        ),
        current_volume: e.logData.current_volume,
        dash_perf_logging_enabled: e.logData.dash_perf_logging_enabled,
        data_connection_quality: e.logData.data_connection_quality,
        debug_reason: e.logData.debug_reason,
        device_id: e.logData.device_id,
        device_type: e.logData.device_type,
        downstream_share_origin_uri: e.logData.downstream_share_origin_uri,
        downstream_share_start_time: e.logData.downstream_share_start_time,
        downstream_share_visit_uuid: e.logData.downstream_share_visit_uuid,
        dropped_frame_count: Number(e.logData.dropped_frame_count),
        error: e.logData.error,
        error_code: e.logData.error_code,
        error_description: e.logData.error_description,
        error_domain: e.logData.error_domain,
        error_type: e.logData.error_type,
        error_user_info: e.logData.error_user_info,
        event_name: e.eventType,
        event_seq_num: e.logData.event_seq_num,
        external_log_id: e.logData.external_log_id,
        external_log_type: e.logData.external_log_id,
        fb_manifest_identifier: e.logData.fb_manifest_identifier,
        feed_aggregation_type: e.logData.feed_aggregation_type,
        feed_position: e.logData.feed_position,
        frame_events: e.logData.frame_events,
        ft: e.logData.ft,
        imf_emsg_id: e.logData.imf_emsg_id,
        imf_event_type: e.logData.imf_event_type,
        imf_topic: e.logData.imf_topic,
        interrupt_count:
          e.logData.interrupt_count !== null
            ? Number(e.logData.interrupt_count)
            : null,
        interrupt_time: Number(e.logData.interrupt_time),
        is_abr_enabled: e.logData.is_abr_enabled,
        is_fbms: e.logData.is_fbms,
        is_live_preview: (t = e.logData.is_live_preview) != null ? t : !1,
        is_live_video_rewound: e.logData.is_live_video_rewound,
        is_mixed_codec_manifest: e.logData.is_mixed_codec_manifest,
        is_p2p_playback: e.logData.is_p2p_playback,
        is_pip: e.logData.is_pip,
        is_predictive_playback: e.logData.is_predictive_playback,
        is_sound_on: e.logData.is_sound_on,
        is_stalling: e.logData.is_stalling,
        is_templated_manifest: e.logData.is_templated_manifest,
        last_viewability_percentage: Number(
          e.logData.last_viewability_percentage,
        ),
        live_trace_source_id: e.logData.live_trace_source_id,
        live_trace_stream_id: n ? e.logData.live_trace_stream_id : null,
        live_trace_stream_type: n ? e.logData.live_trace_stream_type : null,
        mpd_validation_errors: e.logData.mpd_validation_errors,
        network_connected: e.logData.network_connected,
        next_quality_label: e.logData.next_quality_label,
        next_representation_id: e.logData.next_representation_id,
        next_video_codecs: e.logData.next_video_codecs,
        notification_id: e.logData.notification_id,
        notification_medium: e.logData.notification_medium,
        offset_ms:
          e.logData.offset_ms != null ? String(e.logData.offset_ms) : null,
        permalink_share_id: e.logData.permalink_share_id,
        playback_caption_format: e.logData.playback_caption_format,
        playback_caption_locale: e.logData.playback_caption_locale,
        playback_duration: e.logData.playback_duration,
        playback_is_broadcast: e.logData.playback_is_broadcast,
        playback_is_drm: e.logData.playback_is_drm,
        playback_is_live_streaming: e.logData.playback_is_live_streaming,
        player_format: e.logData.player_format,
        player_instance_key: e.logData.player_instance_key,
        player_mode: e.logData.player_mode,
        player_origin: e.logData.player_origin,
        player_state: e.logData.player_state,
        player_suborigin: e.logData.player_suborigin,
        player_version: e.logData.player_version,
        projection: e.logData.projection,
        quality_label: e.logData.quality_label,
        reaction_video_channel_type: e.logData.reaction_video_channel_type,
        representation_id: e.logData.representation_id,
        resource_url: e.logData.resource_url,
        routeTracePolicy: e.routeTracePolicy,
        seq_num: e.logData.seq_num,
        source: e.source_VPL_LOGGING_HACK,
        source_VPL_LOGGING_HACK: e.logData.source_VPL_LOGGING_HACK,
        srt_job_id: e.logData.srt_job_id,
        srt_job_tracking_id: e.logData.srt_job_tracking_id,
        stall_count: Number(e.logData.stall_count),
        stall_count_200_ms: Number(e.logData.stall_count_200_ms),
        stall_time: Number(e.logData.stall_time),
        state: e.logData.state,
        streaming_format: e.logData.streaming_format,
        time_ms: e.logData.time_ms,
        total_frame_count: Number(e.logData.total_frame_count),
        tracking_data_encrypted: e.logData.tracking_data_encrypted,
        tracking_nodes: e.logData.tracking_nodes,
        tv_session_id: e.logData.tv_session_id,
        v2_heart_beat: e.logData.v2_heart_beat,
        video_bandwidth: e.logData.video_bandwidth,
        video_buffer_end_position: e.logData.video_buffer_end_position,
        video_chaining_depth_level: e.logData.video_chaining_depth_level,
        video_chaining_parent_video_id:
          e.logData.video_chaining_parent_video_id,
        video_chaining_session_id: e.logData.video_chaining_session_id,
        video_channel_id: e.logData.video_channel_id,
        video_codecs: e.logData.video_codecs,
        video_id: e.logData.video_id,
        video_last_start_time_position:
          e.logData.video_last_start_time_position,
        video_play_reason: e.logData.video_play_reason,
        video_player_height: Number(e.logData.video_player_height),
        video_player_width: Number(e.logData.video_player_width),
        video_time_position: e.logData.video_time_position,
        vpts: e.logData.vpts,
        web_client_revision: e.logData.web_client_revision,
      };
    }
    var s = {
        logComet: function (n) {
          r("VideoPlayerWwwFalcoEvent").log(function () {
            return e(n);
          });
        },
        logCometImmediately: function (n) {
          r("VideoPlayerWwwFalcoEvent").logImmediately(function () {
            return e(n);
          });
        },
      },
      u = s;
    l.default = u;
  },
  98,
);
