__d(
  "VirtualizationExperimentConfig",
  ["cometVirtualizationMarginReconcile"],
  function (t, n, r, o, a, i, l) {
    "use strict";
    var e = 4e3,
      s = !0,
      u = !1,
      c = !1,
      d = !1,
      m = !1,
      p = !1,
      _ = "static",
      f = !1,
      g = !1,
      h = !1,
      y = new Set(["static", "dynamic"]),
      C = new Set(["thread_view", "weave_inbox_thread"]),
      b = {
        polaris_feed_story_tray_item: {
          hiding_disabled: !1,
          pin_children_on_interaction: !0,
          react_activity_mode: !1,
          surface_enabled: !0,
        },
        weave_inbox_board_card: {
          hiding_disabled: !1,
          pin_children_on_interaction: !0,
          pin_children_with_player: !1,
          root_margin_top_bottom: 1e3,
          surface_enabled: !0,
        },
        weave_inbox_thread: {
          hiding_disabled: !1,
          is_at_bottom_scroll_up: !0,
          pin_children_on_interaction: !0,
          pin_children_with_player: !1,
          root_margin_top_bottom: 500,
          surface_enabled: !0,
        },
      },
      v = {
        comet_feed_unit_card: {
          hiding_disabled: !1,
          pin_children_on_interaction: !0,
          pin_children_with_player: !1,
          root_margin_top_bottom: 4e3,
          surface_enabled: !0,
        },
        marketplace_item: { surface_enabled: !1 },
      },
      S = {
        comet_feed_unit_card: {
          hiding_disabled: !1,
          pin_children_on_interaction: !0,
          pin_children_with_player: !0,
          root_margin_top_bottom: 500,
          surface_enabled: !0,
          virtualization_strategy: "dynamic",
        },
        comet_profile_photos: {
          hiding_disabled: !1,
          pin_children_on_interaction: !0,
          pin_children_with_player: !1,
          root_margin_top_bottom: 1e3,
          surface_enabled: !0,
        },
        comet_tofu_stories_container: {
          hiding_disabled: !1,
          pin_children_on_interaction: !0,
          pin_children_with_player: !1,
          root_margin_top_bottom: 1e3,
          surface_enabled: !0,
        },
        comet_watch_tab: {
          hiding_disabled: !1,
          pin_children_on_interaction: !0,
          pin_children_with_player: !1,
          root_margin_top_bottom: 4e3,
          surface_enabled: !0,
          virtualization_strategy: "dynamic",
        },
        marketplace_item: {
          hiding_disabled: !1,
          pin_children_on_interaction: !0,
          pin_children_with_player: !1,
          root_margin_top_bottom: 1e3,
          surface_enabled: !0,
        },
        thread_list: {
          hiding_disabled: !1,
          pin_children_on_interaction: !0,
          pin_children_with_player: !1,
          root_margin_top_bottom: 500,
          surface_enabled: !0,
        },
        thread_view: {
          hiding_disabled: !1,
          is_at_bottom_scroll_up: !0,
          pin_children_on_interaction: !0,
          pin_children_with_player: !1,
          root_margin_top_bottom: 500,
          surface_enabled: !0,
        },
      },
      R = {
        comet_feed_unit_card: {
          hiding_disabled: !1,
          pin_children_on_interaction: !0,
          pin_children_with_player: !0,
          root_margin_top_bottom: 500,
          surface_enabled: !0,
          virtualization_strategy: "static",
        },
      };
    ((l.DEFAULT_TOP_BOTTOM_MARGIN = e),
      (l.DEFAULT_PIN_CHILDREN_ON_INTERACTION = s),
      (l.DEFAULT_PIN_CHILDREN_WITH_PLAYER = u),
      (l.DEFAULT_PIN_EXCLUSION_ENABLED = c),
      (l.DEFAULT_PERSISTED_MARGIN_ENABLED = d),
      (l.DEFAULT_EMA_WEIGHT_CAP = o(
        "cometVirtualizationMarginReconcile",
      ).EMA_WEIGHT_CAP),
      (l.DEFAULT_DISABLE_HIDING = m),
      (l.DEFAULT_ACTIVITY_MODE_ON = p),
      (l.DEFAULT_VIRTUALIZATION_STRATEGY = _),
      (l.DEFAULT_AT_BOTTOM_SCROLL_UP = f),
      (l.DEFAULT_TEXT_SEARCHABLE = g),
      (l.DEFAULT_SKIP_SCROLL_ANCHORING_CHECK = h),
      (l.VALID_STRATEGIES = y),
      (l.infiniteScrollUpSurfaces = C),
      (l.ROLLOUT_CONFIG = b),
      (l.GK_HOLDOUT_CONFIG = v),
      (l.GK_ROLLOUT_CONFIG = S),
      (l.FIREFOX_ROLLOUT_CONFIG = R));
  },
  98,
);
