__d(
  "WAMsgType",
  [],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = "Text",
      l = "Futureproof",
      s = "Ciphertext",
      u = "Unavailable",
      c = "Image",
      d = "Video",
      m = "Ptt",
      p = "Admin",
      _ = "Revoked",
      f = "Gif",
      g = "Sticker",
      h = "DocumentFile",
      y = "ExpiredEphemeral",
      C = "EphemeralSettingAdmin",
      b = "EphemeralSyncResponse",
      v = "DeleteForMe",
      S = "EphemeralSettingChangeFromCurrentDevice",
      R = "AlertICDC",
      L = "GroupInvite",
      E = "NoteReply",
      k = "Reaction",
      I = "SenderKeyDistribution",
      T = "EditAction",
      D = "ReceiverFetch",
      x = "Raven",
      $ = "GroupPollCreate",
      P = "GroupPollUpdate",
      N = {
        ADMIN: p,
        CIPHERTEXT: s,
        DELETE_FOR_ME: v,
        DOCUMENT_FILE: h,
        EDIT_ACTION: T,
        EPHEMERAL_SETTING_ADMIN: C,
        EPHEMERAL_SETTING_CHANGE_FROM_CURRENT_DEVICE: S,
        EPHEMERAL_SYNC_RESPONSE: b,
        EXPIRED_EPHEMERAL: y,
        FUTUREPROOF: l,
        GIF: f,
        GROUP_INVITE: L,
        ICDC_ALERT: R,
        IMAGE: c,
        PTT: m,
        REACTION: k,
        REVOKED: _,
        SK_DISTRIBUTION: I,
        STICKER: g,
        TEXT: e,
        UNAVAILABLE: u,
        VIDEO: d,
        RECEIVER_FETCH: D,
        RAVEN: x,
        GROUP_POLL_CREATE: $,
        GROUP_POLL_UPDATE: P,
        NOTE_REPLY: E,
      };
    ((i.TEXT = e),
      (i.FUTUREPROOF = l),
      (i.CIPHERTEXT = s),
      (i.UNAVAILABLE = u),
      (i.IMAGE = c),
      (i.VIDEO = d),
      (i.PTT = m),
      (i.ADMIN = p),
      (i.REVOKED = _),
      (i.GIF = f),
      (i.STICKER = g),
      (i.DOCUMENT_FILE = h),
      (i.EXPIRED_EPHEMERAL = y),
      (i.EPHEMERAL_SETTING_ADMIN = C),
      (i.EPHEMERAL_SYNC_RESPONSE = b),
      (i.DELETE_FOR_ME = v),
      (i.EPHEMERAL_SETTING_CHANGE_FROM_CURRENT_DEVICE = S),
      (i.ICDC_ALERT = R),
      (i.GROUP_INVITE = L),
      (i.NOTE_REPLY = E),
      (i.REACTION = k),
      (i.SK_DISTRIBUTION = I),
      (i.EDIT_ACTION = T),
      (i.RECEIVER_FETCH = D),
      (i.RAVEN = x),
      (i.GROUP_POLL_CREATE = $),
      (i.GROUP_POLL_UPDATE = P),
      (i.MSG_TYPE = N));
  },
  66,
);
