__d(
  "WAOdsEnums",
  ["$InternalEnum"],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = n("$InternalEnum")({
      WA_CONNECTIVITY: "wa_connectivity",
      SPAM_REPORT: "wmi_spam_report",
      DECRYPTION: "armadillo_msg_decryption",
      DEVICE_REREG_CHECK: "armadillo_device_rereg_check",
      DEVICE_REGISTRATION: "armadillo_device_registration",
      DEVICE_REGISTRATION_NON_EMPLOYEE:
        "armadillo_device_registration_non_employee",
      PHASH_MISMATCH: "phash_mismatch",
      WEB_PLACEHOLDER: "armadillo_web_placeholder",
      PREKEY_UPLOAD: "armadillo_prekey_upload",
      PREKEY_DIGEST: "armadillo_prekey_digest",
      C2C_META_SYNC: "armadillo_c2c_meta_sync",
      ADMIN_MESSAGE: "armadillo_admin_message",
      PREVIEW_SNIPPET: "armadillo_snippet",
      TOTAL_INCOMING_MESSAGE: "armadillo_total_incoming_message",
      COMPARE_IDENTITY: "armadillo_compare_identity",
      GET_PREKEY: "armadillo_get_prekey",
      SECURITY_ALERT_FOR_CONTACT: "armadillo_security_alert_for_contact",
      SECURITY_ALERT_FOR_SELF: "armadillo_security_alert_for_self",
      MSG_SEND: "armadillo_message_send",
      RETRY_MISSING_MSG: "armadillo_retry_missing_msg",
      REGISTRATION_TYPE: "aramdillo_registration_type",
      CLOCK_SKEW_UPDATE: "clock_skew_update",
      STREAM_ERROR: "wajs_stream_error",
      POISON_QUEUE_ENTTITY: "armadillo_poison_queue_entity",
      PQ_MIGRATION: "wajs_pq_migration",
      WORM: "wajs_worm",
      CAT_ROTATION: "cat_rotation",
      EB_RESTORE: "eb_restore",
      EB_UPLOAD: "eb_upload",
      WA_REREGISTRATION: "wa_reregistration",
      EB_SWITCH_STATE: "eb_switch_state",
      EB_MESSAGE_PROBE: "eb_message_probe",
      EB_CLIENT_STATE_CHECK: "eb_client_state_check",
      EB_RECOVERY_CODE_DB: "eb_recovery_code_db",
      AUTOMATIC_EB: "automatic_eb",
      MAW_BRIDGE: "maw_bridge",
      MAW_BRIDGE_UI_EVENT: "maw_bridge_ui_event",
      MAW_DB_DEPRECATION: "maw_db_deprecation",
      WA_DISCONNECT: "armadillo_disconnect",
      GROUP_CREATE: "armadillo_group_create",
      GROUP_DELETE: "armadillo_group_delete",
      GROUP_ADD_PARTICIPANT: "armadillo_group_add_participant",
      GROUP_PROMOTE_PARTICIPANT: "armadillo_group_promote_participant",
      GROUP_DEMOTE_PARTICIPANT: "armadillo_group_demote_participant",
      GROUP_REMOVE_PARTICIPANT: "armadillo_group_remove_participant",
      GROUP_LEAVE_PARTICIPANT: "armadillo_group_leave_participant",
      GROUP_REVOKE_PARTICIPANT_INVITE:
        "armadillo_group_revoke_participant_invite",
      GROUP_SKS_INVALID: "armadillo_group_sks_invalid",
      GROUP_SET_MEMBER_ADD_MODE: "armadillo_group_set_member_add_mode",
      GROUP_JOIN: "armadillo_group_join",
      GROUP_SET_SUBJECT: "armadillo_group_set_subject",
      OPEN_GROUP_ADD_PARTICIPANT: "open_group_add_participant",
      SEND_READ_RECEIPTS: "armadillo_send_read_receipts",
      MESSAGE_MISSING_THREAD_JID: "MESSAGE_MISSING_THREAD_JID",
      MESSAGE_MISSING: "MESSAGE_MISSING",
      MAW_NON_TIMEOUT: "maw_non_timeout",
      MAW_TIMEOUT: "maw_timeout",
      WA_FAIL_STANZA_QUEUE_ITEM: "wa_fail_stanza_queue_item",
      MAW_MISMATCH_PARTICIPANT: "maw_mismatch_participant",
      MAW_ONE_TO_ONE_THREAD_PARTICIPANT_CLEANUP:
        "maw_one_to_one_thread_participant_cleanup",
      MAW_THREADID_DEPRECATION: "maw_threadid_deprecation",
      MAW_THREADID_DEPRECATION_DETAILS: "maw_threadid_deprecation_details",
      MAW_DELETE_DANGLING_PARTICIPANTS: "maw_delete_dangling_participants",
      S2S_QPL_MISSING_INSTANCE_KEY: "s2s_qpl_missing_instance_key",
      MAW_DEPRECATED_REDIRECT: "maw_deprecated_redirect",
      MAW_DEPRECATED_BRIDGE_USAGE: "maw_deprecated_bridge_usage",
      MAW_MUTATION_VALIDATOR: "maw_mutation_validator",
      MAW_THREAD_UPDATE_MIDDLEWARE: "maw_thread_update_middleware",
      MAW_THREADLIST_ITEM_UPDATE: "maw_threadlist_item_update",
      MAW_THREAD_BUMPED_V2: "maw_thread_bumped_v2",
      MAW_MY_USER_JID_GETTER: "maw_my_user_jid_getter",
      WA_NO_SIGNED_PRE_KEY: "wa_no_signed_pre_key",
      WA_LONG_SESSION_DROP: "wa_long_session_drop",
      MAW_PROTOCOL_MSG_ID_INDEX: "maw_protocol_msg_id_index",
      MAW_DUPLICATE_MSGS: "maw_duplicate_msgs",
      MAW_LS_SYNC_IMPROVEMENTS: "maw_ls_sync_improvements",
      MAW_DELETE_DB_ON_LOGOUT: "maw_delete_db_on_logout",
      MAW_VAULTING: "maw_vaulting",
      MAW_SEND_REACTION: "maw_send_reaction",
      MAW_OLD_MESSAGE_SEND: "maw_old_message_send",
      MAW_MIGRATE_REACTION_TS_AS_INDEX: "maw_migrate_reaction_ts_as_index",
      MAW_TC_MS5_OPEN_SNIPPET: "maw_tc_ms5_open_snippet",
      MAW_S2S_INSTANCE_KEY_NULL: "maw_s2s_instance_key_null",
      MAW_XMA_PROTOCOL_PARSING: "maw_xma_protocol_parsing",
      IGDW_INSTAMADILLO_MESSAGE_ON_OLD_WORKER: "igdw_new_msg_old_worker",
      WORKER_SCHEDULER_STUCK: "worker_scheduler_stuck",
      MAW_DB_UNEXPECTED_VERSION: "maw_db_unexpected_version",
      MAW_DB_MIGRATION_CURRENT_VERSION: "maw_db_migration_current_version",
      MAW_MEDIA_DB_DUPLICATE_MEDIA: "maw_media_db_duplicate_media",
      MAW_MEDIA_DB_DUPLICATE_CHUNK: "maw_media_db_duplicate_chunk",
      MAW_MEDIA_MISMATCH_HASHED_PLAINTEXT_HASH:
        "maw_media_mismatch_hashed_plaintext_hash",
      MAW_EB_DECODE_MESSAGE_PROTOBUF_SUPPLEMENTAL:
        "maw_eb_decode_message_protobuf_supplemental",
      MAW_THREAD_GET_NEWEST_REACTION_BATCH_NUM:
        "maw_thread_get_newest_reaction_batch_num",
      MAW_THREAD_MAPPING: "maw_thread_mapping",
      WA_PROTOCOL_QUEUE_NOTIFICATION: "wa_protocol_queue_notification",
      MPS_THREAD_SNIPPET_CONSISTENCY: "mps_thread_snippet_consistency",
      MAW_JOB_MANAGER: "maw_job_manager",
    });
    i.Entity = e;
  },
  66,
);
