__d(
  "WASmaxInMessageDeliverEnums",
  ["WAJids"],
  function (t, n, r, o, a, i, l) {
    var e,
      s = { 0: "0", 1: "1" },
      u = {
        "1p_sticker": "1p_sticker",
        audio: "audio",
        avatar_sticker: "avatar_sticker",
        buttons_response: "buttons_response",
        cataloglink: "cataloglink",
        collection: "collection",
        contact: "contact",
        contact_array: "contact_array",
        document: "document",
        feed_reshare: "feed_reshare",
        genai_sticker: "genai_sticker",
        gif: "gif",
        group_history: "group_history",
        history: "history",
        image: "image",
        list_response: "list_response",
        location: "location",
        motion_photo: "motion_photo",
        motion_video: "motion_video",
        native_flow_response: "native_flow_response",
        order: "order",
        product: "product",
        productlink: "productlink",
        ptt: "ptt",
        ptv: "ptv",
        sticker: "sticker",
        sticker_pack: "sticker_pack",
        story_reply: "story_reply",
        url: "url",
        user_created_sticker: "user_created_sticker",
        vcard: "vcard",
        video: "video",
        xma: "xma",
      },
      c = {
        "1p_sticker": "1p_sticker",
        audio: "audio",
        avatar_sticker: "avatar_sticker",
        cataloglink: "cataloglink",
        collection: "collection",
        document: "document",
        genai_sticker: "genai_sticker",
        gif: "gif",
        image: "image",
        motion_photo: "motion_photo",
        motion_video: "motion_video",
        productlink: "productlink",
        ptt: "ptt",
        ptv: "ptv",
        sticker: "sticker",
        sticker_pack: "sticker_pack",
        url: "url",
        user_created_sticker: "user_created_sticker",
        vcard: "vcard",
        video: "video",
      },
      d = { 1: "1", 2: "2" },
      m = { 1: "1", 3: "3" },
      p = { ACCEPT: "ACCEPT", REJECT: "REJECT", UNKNOWN: "UNKNOWN" },
      _ = {
        account_authentication_request: "account_authentication_request",
        address_message: "address_message",
        call_permission_request: "call_permission_request",
        form_message: "form_message",
        galaxy_message: "galaxy_message",
        menu_options: "menu_options",
      },
      f = {
        address_message: "address_message",
        galaxy_message: "galaxy_message",
      },
      g = {
        ads_manager: "ads_manager",
        graph_api: "graph_api",
        maiba: "maiba",
        maiba_ai_hub: "maiba_ai_hub",
        marketing_messages_with_optimizations:
          "marketing_messages_with_optimizations",
        unified_inbox: "unified_inbox",
      },
      h = {
        ads_manager: "ads_manager",
        maiba: "maiba",
        maiba_ai_hub: "maiba_ai_hub",
        marketing_messages_with_optimizations:
          "marketing_messages_with_optimizations",
        third_party: "third_party",
        unified_inbox: "unified_inbox",
      },
      y = {
        allowlist: "allowlist",
        contacts: "contacts",
        denylist: "denylist",
      },
      C = { allow: "allow", bypass: "bypass", deny: "deny", error: "error" },
      b = {
        ASPRESENTED: "ASPRESENTED",
        BIMONTHLY: "BIMONTHLY",
        DAILY: "DAILY",
        FORTNIGHTLY: "FORTNIGHTLY",
        HALFYEARLY: "HALFYEARLY",
        MONTHLY: "MONTHLY",
        ONETIME: "ONETIME",
        QUARTERLY: "QUARTERLY",
        UNKNOWN: "UNKNOWN",
        WEEKLY: "WEEKLY",
        YEARLY: "YEARLY",
      },
      v = {
        audio: "audio",
        avatar_sticker: "avatar_sticker",
        buttons_response: "buttons_response",
        cataloglink: "cataloglink",
        contact: "contact",
        contact_array: "contact_array",
        document: "document",
        feed_reshare: "feed_reshare",
        gif: "gif",
        history: "history",
        image: "image",
        list_response: "list_response",
        location: "location",
        native_flow_response: "native_flow_response",
        order: "order",
        product: "product",
        productlink: "productlink",
        ptt: "ptt",
        ptv: "ptv",
        sticker: "sticker",
        story_reply: "story_reply",
        url: "url",
        vcard: "vcard",
        video: "video",
        xma: "xma",
      },
      S = {
        br: "br",
        incentive: "incentive",
        p2m: "p2m",
        p2p: "p2p",
        payout: "payout",
        upi: "upi",
        upi_lite: "upi_lite",
      },
      R = { buyer: "buyer", seller: "seller" },
      L = {
        card: "card",
        "net-banking": "net-banking",
        upi: "upi",
        wallet: "wallet",
      },
      E = { closed: "closed", open: "open" },
      k = {
        country: "country",
        es: "es",
        react: "react",
        sys_msg_version: "sys_msg_version",
        tos3: "tos3",
        true: "true",
      },
      I = { creation: "creation", edit: "edit", response: "response" },
      T = {
        default: "default",
        group_history: "group_history",
        history: "history",
        member_tag: "member_tag",
      },
      D = {
        delivery: "delivery",
        impressions: "impressions",
        link_clicks: "link_clicks",
        no_optimization: "no_optimization",
        offsite_conversions: "offsite_conversions",
        replies: "replies",
      },
      x = {
        DEREGISTER: "DEREGISTER",
        INIT_TOP_UP: "INIT_TOP_UP",
        PAY: "PAY",
        TOP_UP: "TOP_UP",
      },
      $ = { ds: "ds", fc: "fc", ge: "ge" },
      P = { EXACT: "EXACT", MAX: "MAX" },
      N = { FAILED: "FAILED", PENDING: "PENDING", SUCCESS: "SUCCESS" },
      M = { FAILURE: "FAILURE", INIT: "INIT", SUCCESS: "SUCCESS" },
      w = { false: "false", true: "true" },
      A = { FBPAY: "FBPAY", UPI: "UPI" },
      F = { first: "first", full: "full", inner: "inner", last: "last" },
      O = {
        FULL: "FULL",
        MISSING_FIELD_NOT_PARTIAL: "MISSING_FIELD_NOT_PARTIAL",
        PARTIAL: "PARTIAL",
      },
      B = { group: "group", sender: "sender" },
      W = { guest: "guest", wa: "wa" },
      q = {
        hd_image_dual_upload: "hd_image_dual_upload",
        hd_video_dual_upload: "hd_video_dual_upload",
        hevc_video_dual_upload: "hevc_video_dual_upload",
        media_poll: "media_poll",
        motion_photo: "motion_photo",
        sticker_annotation: "sticker_annotation",
      },
      U = { high: "high", high_force: "high_force", low: "low" },
      V = { high: "high", low: "low", unknown: "unknown" },
      H = { hosted: "hosted", view_once: "view_once" },
      G = { hpp_payment_link: "hpp_payment_link", upi: "upi" },
      z = { lid: "lid", pn: "pn" },
      j = { matched: "matched", unmatched: "unmatched" },
      K = {
        message_limit_reached: "message_limit_reached",
        under_limit: "under_limit",
      },
      Q = { msg: "msg", pkmsg: "pkmsg" },
      X = {
        new_member: "new_member",
        rereg_recovery_request: "rereg_recovery_request",
        rereg_recovery_response: "rereg_recovery_response",
        user_delete: "user_delete",
        user_update: "user_update",
      },
      Y = { on_demand: "on_demand", scheduled: "scheduled" },
      J = { p2m: "p2m", p2p: "p2p" },
      Z = { request: "request", send: "send" },
      ee = { smb_mm: "smb_mm", smb_promo: "smb_promo" },
      te = {
        tier3: "tier3",
        tier6_matched: "tier6_matched",
        tier6_unmatched: "tier6_unmatched",
      },
      ne = {
        "": "",
        call_permission_request: "call_permission_request",
        catalog_message: "catalog_message",
        menu_options: "menu_options",
        order_details: "order_details",
        order_status: "order_status",
        otp: "otp",
        payment_info: "payment_info",
        payment_key_info: "payment_key_info",
        payment_method: "payment_method",
        payment_status: "payment_status",
        video_call: "video_call",
        voice_call: "voice_call",
      },
      re = {
        validators: [
          (e = o("WAJids")).validateDeviceJid,
          e.validateBroadcastJid,
          e.validateDeviceJid,
          e.validateGroupJid,
          e.validateInteropDeviceJid,
          e.validateInteropDeviceJid,
          e.validateDeviceJid,
          e.validateStatusJid,
        ],
        typeName:
          "DeviceJid|BroadcastJid|DeviceJid|GroupJid|InteropDeviceJid|InteropDeviceJid|DeviceJid|StatusJid",
      },
      oe = {
        validators: [e.validateDeviceJid, e.validateDeviceJid],
        typeName: "DeviceJid|DeviceJid",
      },
      ae = {
        validators: [
          e.validateDeviceJid,
          e.validateDeviceJid,
          e.validateInteropDeviceJid,
          e.validateInteropDeviceJid,
          e.validateDeviceJid,
        ],
        typeName:
          "DeviceJid|DeviceJid|InteropDeviceJid|InteropDeviceJid|DeviceJid",
      },
      ie = {
        validators: [
          e.validateDeviceJid,
          e.validateDeviceJid,
          e.validateUserJid,
          e.validateUserJid,
          e.validateDeviceJid,
          e.validateLidUserJid,
          e.validateUserJid,
        ],
        typeName:
          "DeviceJid|DeviceJid|UserJid|UserJid|DeviceJid|LidUserJid|UserJid",
      },
      le = {
        validators: [
          e.validateDeviceJid,
          e.validateDeviceJid,
          e.validateUserJid,
          e.validateUserJid,
          e.validateLidUserJid,
          e.validateUserJid,
        ],
        typeName: "DeviceJid|DeviceJid|UserJid|UserJid|LidUserJid|UserJid",
      },
      se = {
        validators: [e.validateGroupJid, e.validateUserJid],
        typeName: "GroupJid|UserJid",
      },
      ue = {
        validators: [e.validateUserJid, e.validateUserJid],
        typeName: "UserJid|UserJid",
      };
    ((l.ENUM_0_1 = s),
      (l.ENUM_1PSTICKER_AUDIO_AVATARSTICKER_BUTTONSRESPONSE_CATALOGLINK_COLLECTION_CONTACT_CONTACTARRAY_DOCUMENT_FEEDRESHARE_GENAISTICKER_GIF_GROUPHISTORY_HISTORY_IMAGE_LISTRESPONSE_LOCATION_MOTIONPHOTO_MOTIONVIDEO_NATIVEFLOWRESPONSE_ORDER_PRODUCT_PRODUCTLINK_PTT_PTV_STICKER_STICKERPACK_STORYREPLY_URL_USERCREATEDSTICKER_VCARD_VIDEO_XMA =
        u),
      (l.ENUM_1PSTICKER_AUDIO_AVATARSTICKER_CATALOGLINK_COLLECTION_DOCUMENT_GENAISTICKER_GIF_IMAGE_MOTIONPHOTO_MOTIONVIDEO_PRODUCTLINK_PTT_PTV_STICKER_STICKERPACK_URL_USERCREATEDSTICKER_VCARD_VIDEO =
        c),
      (l.ENUM_1_2 = d),
      (l.ENUM_1_3 = m),
      (l.ENUM_ACCEPT_REJECT_UNKNOWN = p),
      (l.ENUM_ACCOUNTAUTHENTICATIONREQUEST_ADDRESSMESSAGE_CALLPERMISSIONREQUEST_FORMMESSAGE_GALAXYMESSAGE_MENUOPTIONS =
        _),
      (l.ENUM_ADDRESSMESSAGE_GALAXYMESSAGE = f),
      (l.ENUM_ADSMANAGER_GRAPHAPI_MAIBA_MAIBAAIHUB_MARKETINGMESSAGESWITHOPTIMIZATIONS_UNIFIEDINBOX =
        g),
      (l.ENUM_ADSMANAGER_MAIBA_MAIBAAIHUB_MARKETINGMESSAGESWITHOPTIMIZATIONS_THIRDPARTY_UNIFIEDINBOX =
        h),
      (l.ENUM_ALLOWLIST_CONTACTS_DENYLIST = y),
      (l.ENUM_ALLOW_BYPASS_DENY_ERROR = C),
      (l.ENUM_ASPRESENTED_BIMONTHLY_DAILY_FORTNIGHTLY_HALFYEARLY_MONTHLY_ONETIME_QUARTERLY_UNKNOWN_WEEKLY_YEARLY =
        b),
      (l.ENUM_AUDIO_AVATARSTICKER_BUTTONSRESPONSE_CATALOGLINK_CONTACT_CONTACTARRAY_DOCUMENT_FEEDRESHARE_GIF_HISTORY_IMAGE_LISTRESPONSE_LOCATION_NATIVEFLOWRESPONSE_ORDER_PRODUCT_PRODUCTLINK_PTT_PTV_STICKER_STORYREPLY_URL_VCARD_VIDEO_XMA =
        v),
      (l.ENUM_BR_INCENTIVE_P2M_P2P_PAYOUT_UPI_UPILITE = S),
      (l.ENUM_BUYER_SELLER = R),
      (l.ENUM_CARD_NETBANKING_UPI_WALLET = L),
      (l.ENUM_CLOSED_OPEN = E),
      (l.ENUM_COUNTRY_ES_REACT_SYSMSGVERSION_TOS3_TRUE = k),
      (l.ENUM_CREATION_EDIT_RESPONSE = I),
      (l.ENUM_DEFAULTP_GROUPHISTORY_HISTORY_MEMBERTAG = T),
      (l.ENUM_DELIVERY_IMPRESSIONS_LINKCLICKS_NOOPTIMIZATION_OFFSITECONVERSIONS_REPLIES =
        D),
      (l.ENUM_DEREGISTER_INITTOPUP_PAY_TOPUP = x),
      (l.ENUM_DS_FC_GE = $),
      (l.ENUM_EXACT_MAX = P),
      (l.ENUM_FAILED_PENDING_SUCCESS = N),
      (l.ENUM_FAILURE_INIT_SUCCESS = M),
      (l.ENUM_FALSE_TRUE = w),
      (l.ENUM_FBPAY_UPI = A),
      (l.ENUM_FIRST_FULL_INNER_LAST = F),
      (l.ENUM_FULL_MISSINGFIELDNOTPARTIAL_PARTIAL = O),
      (l.ENUM_GROUP_SENDER = B),
      (l.ENUM_GUEST_WA = W),
      (l.ENUM_HDIMAGEDUALUPLOAD_HDVIDEODUALUPLOAD_HEVCVIDEODUALUPLOAD_MEDIAPOLL_MOTIONPHOTO_STICKERANNOTATION =
        q),
      (l.ENUM_HIGH_HIGHFORCE_LOW = U),
      (l.ENUM_HIGH_LOW_UNKNOWN = V),
      (l.ENUM_HOSTED_VIEWONCE = H),
      (l.ENUM_HPPPAYMENTLINK_UPI = G),
      (l.ENUM_LID_PN = z),
      (l.ENUM_MATCHED_UNMATCHED = j),
      (l.ENUM_MESSAGELIMITREACHED_UNDERLIMIT = K),
      (l.ENUM_MSG_PKMSG = Q),
      (l.ENUM_NEWMEMBER_REREGRECOVERYREQUEST_REREGRECOVERYRESPONSE_USERDELETE_USERUPDATE =
        X),
      (l.ENUM_ONDEMAND_SCHEDULED = Y),
      (l.ENUM_P2M_P2P = J),
      (l.ENUM_REQUEST_SEND = Z),
      (l.ENUM_SMBMM_SMBPROMO = ee),
      (l.ENUM_TIER3_TIER6MATCHED_TIER6UNMATCHED = te),
      (l.ENUM__CALLPERMISSIONREQUEST_CATALOGMESSAGE_MENUOPTIONS_ORDERDETAILS_ORDERSTATUS_OTP_PAYMENTINFO_PAYMENTKEYINFO_PAYMENTMETHOD_PAYMENTSTATUS_VIDEOCALL_VOICECALL =
        ne),
      (l.DEVICEJID_BROADCASTJID_DEVICEJID_GROUPJID_INTEROPDEVICEJID_INTEROPDEVICEJID_DEVICEJID_STATUSJID =
        re),
      (l.DEVICEJID_DEVICEJID = oe),
      (l.DEVICEJID_DEVICEJID_INTEROPDEVICEJID_INTEROPDEVICEJID_DEVICEJID = ae),
      (l.DEVICEJID_DEVICEJID_USERJID_USERJID_DEVICEJID_LIDUSERJID_USERJID = ie),
      (l.DEVICEJID_DEVICEJID_USERJID_USERJID_LIDUSERJID_USERJID = le),
      (l.GROUPJID_USERJID = se),
      (l.USERJID_USERJID = ue));
  },
  98,
);
