__d(
  "WAWebSpamConstants",
  ["WAWebMsgType"],
  function (t, n, r, o, a, i, l) {
    var e,
      s = Object.freeze({
        Block: "block_dialog",
        OverflowMenuBlock: "overflow_menu_block",
        OverflowMenuReport: "overflow_menu_report",
        MediaViewer: "media_viewer",
        MessageMenu: "message_menu",
        CommunityHome: "community_home",
        AccountInfoReport: "account_info_report",
        AccountInfoReportAsGuestUser: "account_info_report_as_guest_user",
        GroupInfoReport: "group_info_report",
        GroupSpamBannerReport: "group_spam_banner_report",
        OneToOneChatSpamBannerReport: "1_1_spam_banner_report",
        OneToOneOldSpamBannerBlock: "1_1_old_spam_banner_block",
        BizSpamBannerBlock: "biz_spam_banner_block",
        ChatListBlock: "chat_list_block",
        ChatListNoInsubBlock: "chat_list_noinsub_block",
        NotificationBlock: "notification_block",
        StatusPostReport: "status_post_report",
        NewsletterInfoReport: "newsletter_info_report",
        ChatFmxCardReportAsGuestUser: "chat_fmx_card_report_as_guest_user",
        ChatFmxCardSafetyToolsReport: "chat_fmx_card_safety_tools_report",
        ChatFmxCardSafetyToolsReportSuspicious:
          "chat_fmx_card_safety_tools_report_suspicious",
        GroupFmxCardLeave: "group_fmx_card_leave",
        GroupFmxCardLeaveNonSuspicious: "group_fmx_card_leave_non_suspicious",
        GroupInfoLeaveReportUpsell: "group_info_leave_report_upsell",
        GroupChatlistLeaveReportUpsell: "group_chatlist_leave_report_upsell",
        GroupOverflowMenuLeaveReportUpsell:
          "group_overflow_menu_leave_report_upsell",
        GroupSafetyCheckModalUpsell: "group_safety_check_bottom_sheet",
        CommentActions: "comment_actions_bottom_sheet",
        NewsletterQuestionResponseReport: "newsletter_question_response_report",
        GalaxyFlowsContextMenuReport: "extension_menu_report",
      }),
      u = new Set([
        (e = o("WAWebMsgType")).MSG_TYPE.CHAT,
        e.MSG_TYPE.AUDIO,
        e.MSG_TYPE.IMAGE,
        e.MSG_TYPE.PTT,
        e.MSG_TYPE.PTV,
        e.MSG_TYPE.VIDEO,
        e.MSG_TYPE.VCARD,
        e.MSG_TYPE.LIST,
        e.MSG_TYPE.LIST_RESPONSE,
        e.MSG_TYPE.BUTTONS_RESPONSE,
        e.MSG_TYPE.NATIVE_FLOW,
        e.MSG_TYPE.DOCUMENT,
        e.MSG_TYPE.STICKER,
        e.MSG_TYPE.LOCATION,
        e.MSG_TYPE.POLL_CREATION,
        e.MSG_TYPE.POLL_RESULT_SNAPSHOT,
        e.MSG_TYPE.STATUS,
        e.MSG_TYPE.EVENT_CREATION,
        e.MSG_TYPE.STICKER_PACK,
        e.MSG_TYPE.NEWSLETTER_QUESTION_RESPONSE,
        e.MSG_TYPE.AUTOMATED_GREETING_MESSAGE,
      ]),
      c = new Set(
        [].concat(Array.from(u), [
          e.MSG_TYPE.UNKNOWN,
          e.MSG_TYPE.REVOKED,
          e.MSG_TYPE.CIPHERTEXT,
          e.MSG_TYPE.INTERACTIVE,
        ]),
      ),
      d = new Set([
        e.MSG_TYPE.CHAT,
        e.MSG_TYPE.AUDIO,
        e.MSG_TYPE.IMAGE,
        e.MSG_TYPE.PTT,
        e.MSG_TYPE.VIDEO,
        e.MSG_TYPE.POLL_CREATION,
        e.MSG_TYPE.STATUS,
      ]);
    ((l.SpamFlow = s),
      (l.SUPPORTED_MESSAGE_TYPES_FOR_MESSAGE_LEVEL_REPORTING = u),
      (l.SPAM_REPORT_SUPPORTED_MESSAGE_TYPES = c),
      (l.PAID_PARTNERSHIP_LABEL_SUPPORTED_MESSAGE_TYPES = d));
  },
  98,
);
