__d(
  "WAWebMediaDataGetters",
  ["WAWebGetters", "WAWebGettersCaches"],
  function (t, n, r, o, a, i, l) {
    var e = o("WAWebGetters").createGetterFactories({
        createCache: o("WAWebGettersCaches").createMediaDataCache,
      }),
      s = e.field,
      u = s("accessibilityLabel"),
      c = s("animatedAsNewMsg"),
      d = s("animationDuration"),
      m = s("aspectRatio"),
      p = s("directPath"),
      _ = s("duration"),
      f = s("emojis"),
      g = s("encFilehash"),
      h = s("extractedLottieSticker"),
      y = s("filehash"),
      C = s("filename"),
      b = s("fullHeight"),
      v = s("fullPreviewData"),
      S = s("fullWidth"),
      R = s("isAvatar"),
      L = s("isFirstParty"),
      E = s("isGif"),
      k = s("isViewOnce"),
      I = s("loadedSize"),
      T = s("mediaBlob"),
      D = s("mediaKey"),
      x = s("mediaKeyTimestamp"),
      $ = s("mediaStage"),
      P = s("mimetype"),
      N = s("pageCount"),
      M = s("parsedVcards"),
      w = s("preview"),
      A = s("progressiveStage"),
      F = s("renderableUrl"),
      O = s("rgbaBuffer"),
      B = s("rgbaHeight"),
      W = s("rgbaWidth"),
      q = s("sidecar"),
      U = s("singleLoopDuration"),
      V = s("size"),
      H = s("stickerPackId"),
      G = s("stickerPackName"),
      z = s("stickerPackPublisher"),
      j = s("stickerPremiumStatus"),
      K = s("type"),
      Q = s("waveform");
    ((l.getAccessibilityLabel = u),
      (l.getAnimatedAsNewMsg = c),
      (l.getAnimationDuration = d),
      (l.getAspectRatio = m),
      (l.getDirectPath = p),
      (l.getDuration = _),
      (l.getEmojis = f),
      (l.getEncFilehash = g),
      (l.getExtractedLottieSticker = h),
      (l.getFilehash = y),
      (l.getFilename = C),
      (l.getFullHeight = b),
      (l.getFullPreviewData = v),
      (l.getFullWidth = S),
      (l.getIsAvatar = R),
      (l.getIsFirstParty = L),
      (l.getIsGif = E),
      (l.getIsViewOnce = k),
      (l.getLoadedSize = I),
      (l.getMediaBlob = T),
      (l.getMediaKey = D),
      (l.getMediaKeyTimestamp = x),
      (l.getMediaStage = $),
      (l.getMimetype = P),
      (l.getPageCount = N),
      (l.getParsedVcards = M),
      (l.getPreview = w),
      (l.getProgressiveStage = A),
      (l.getRenderableUrl = F),
      (l.getRgbaBuffer = O),
      (l.getRgbaHeight = B),
      (l.getRgbaWidth = W),
      (l.getSidecar = q),
      (l.getSingleLoopDuration = U),
      (l.getSize = V),
      (l.getStickerPackId = H),
      (l.getStickerPackName = G),
      (l.getStickerPackPublisher = z),
      (l.getStickerPremiumStatus = j),
      (l.getType = K),
      (l.getWaveform = Q));
  },
  98,
);
