__d(
  "WAWebBizAdManagementRoot_query.graphql",
  ["WAWebBizAdManagementRootPaginationQuery.graphql"],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = (function () {
      var e = ["ctwa", "all_user_ads"],
        t = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "id",
          storageKey: null,
        },
        r = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "boosting_status_display_text",
          storageKey: null,
        },
        o = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "formatted_for_lwi",
          storageKey: null,
        },
        a = {
          alias: null,
          args: null,
          concreteType: null,
          kind: "LinkedField",
          name: "boosting_info",
          plural: !1,
          selections: [
            {
              alias: null,
              args: [
                { kind: "Literal", name: "height", value: 256 },
                { kind: "Literal", name: "width", value: 256 },
              ],
              kind: "ScalarField",
              name: "thumbnail_image_url",
              storageKey: "thumbnail_image_url(height:256,width:256)",
            },
            {
              alias: null,
              args: null,
              concreteType: "CurrencyQuantity",
              kind: "LinkedField",
              name: "spent",
              plural: !1,
              selections: [
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "currency",
                  storageKey: null,
                },
                o,
              ],
              storageKey: null,
            },
          ],
          storageKey: null,
        },
        i = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "image_url",
          storageKey: null,
        },
        l = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "message",
          storageKey: null,
        },
        s = {
          alias: null,
          args: null,
          concreteType: null,
          kind: "LinkedField",
          name: "spec",
          plural: !1,
          selections: [
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "start_time",
              storageKey: null,
            },
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "duration_in_days",
              storageKey: null,
            },
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "boosting_status",
              storageKey: null,
            },
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "budget_type",
              storageKey: null,
            },
            {
              alias: null,
              args: null,
              concreteType: "CurrencyQuantity",
              kind: "LinkedField",
              name: "budget",
              plural: !1,
              selections: [o],
              storageKey: null,
            },
            {
              alias: null,
              args: [{ kind: "Literal", name: "is_forced", value: !0 }],
              concreteType: "AdAccount",
              kind: "LinkedField",
              name: "ad_account",
              plural: !1,
              selections: [
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "legacy_account_id",
                  storageKey: null,
                },
              ],
              storageKey: "ad_account(is_forced:true)",
            },
            {
              alias: null,
              args: null,
              concreteType: "AdsLWIAdGroupSpec",
              kind: "LinkedField",
              name: "adgroup_spec",
              plural: !0,
              selections: [
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "adgroup_id",
                  storageKey: null,
                },
                {
                  alias: null,
                  args: null,
                  concreteType: "AdsCreativeSpecification",
                  kind: "LinkedField",
                  name: "creative",
                  plural: !1,
                  selections: [
                    {
                      alias: null,
                      args: null,
                      kind: "ScalarField",
                      name: "body",
                      storageKey: null,
                    },
                    i,
                    {
                      alias: null,
                      args: null,
                      kind: "ScalarField",
                      name: "thumbnail_url",
                      storageKey: null,
                    },
                    {
                      alias: null,
                      args: null,
                      concreteType: "AdObjectStorySpecification",
                      kind: "LinkedField",
                      name: "object_story_spec",
                      plural: !1,
                      selections: [
                        {
                          alias: null,
                          args: null,
                          concreteType: "AdObjectStoryLinkDataSpecification",
                          kind: "LinkedField",
                          name: "link_data",
                          plural: !1,
                          selections: [
                            l,
                            {
                              alias: null,
                              args: null,
                              kind: "ScalarField",
                              name: "link",
                              storageKey: null,
                            },
                            {
                              alias: null,
                              args: null,
                              concreteType:
                                "AdObjectStoryChildLinkDataSpecification",
                              kind: "LinkedField",
                              name: "child_attachments",
                              plural: !0,
                              selections: [
                                {
                                  alias: null,
                                  args: null,
                                  kind: "ScalarField",
                                  name: "picture",
                                  storageKey: null,
                                },
                              ],
                              storageKey: null,
                            },
                          ],
                          storageKey: null,
                        },
                        {
                          alias: null,
                          args: null,
                          concreteType: "AdObjectStoryVideoDataSpecification",
                          kind: "LinkedField",
                          name: "video_data",
                          plural: !1,
                          selections: [
                            l,
                            {
                              alias: null,
                              args: null,
                              kind: "ScalarField",
                              name: "video_id",
                              storageKey: null,
                            },
                            i,
                          ],
                          storageKey: null,
                        },
                      ],
                      storageKey: null,
                    },
                  ],
                  storageKey: null,
                },
              ],
              storageKey: null,
            },
            {
              alias: null,
              args: null,
              concreteType: "AdsLWIAudience",
              kind: "LinkedField",
              name: "audience",
              plural: !1,
              selections: [
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "target_spec_string_without_placements",
                  storageKey: null,
                },
              ],
              storageKey: null,
            },
          ],
          storageKey: null,
        },
        u = {
          alias: null,
          args: null,
          concreteType: "AdCampaignGroup",
          kind: "LinkedField",
          name: "campaign_group",
          plural: !1,
          selections: [
            {
              alias: null,
              args: [
                {
                  kind: "Literal",
                  name: "metrics",
                  value: ["REACH", "RESULTS", "CLICKS"],
                },
              ],
              concreteType: "AdInsightsConnection",
              kind: "LinkedField",
              name: "ad_insights",
              plural: !1,
              selections: [
                {
                  alias: null,
                  args: null,
                  concreteType: "AdInsightsEdge",
                  kind: "LinkedField",
                  name: "edges",
                  plural: !0,
                  selections: [
                    {
                      alias: null,
                      args: null,
                      concreteType: "AdInsightsNode",
                      kind: "LinkedField",
                      name: "node",
                      plural: !1,
                      selections: [
                        {
                          alias: null,
                          args: null,
                          kind: "ScalarField",
                          name: "reach",
                          storageKey: null,
                        },
                        {
                          alias: null,
                          args: null,
                          kind: "ScalarField",
                          name: "results",
                          storageKey: null,
                        },
                        {
                          alias: null,
                          args: null,
                          kind: "ScalarField",
                          name: "clicks",
                          storageKey: null,
                        },
                        {
                          alias: null,
                          args: null,
                          kind: "ScalarField",
                          name: "spend",
                          storageKey: null,
                        },
                      ],
                      storageKey: null,
                    },
                  ],
                  storageKey: null,
                },
              ],
              storageKey: 'ad_insights(metrics:["REACH","RESULTS","CLICKS"])',
            },
          ],
          storageKey: null,
        };
      return {
        argumentDefinitions: [
          { defaultValue: null, kind: "LocalArgument", name: "after" },
          { defaultValue: null, kind: "LocalArgument", name: "first" },
          { defaultValue: null, kind: "LocalArgument", name: "options" },
          { defaultValue: null, kind: "LocalArgument", name: "page_id_1" },
          { defaultValue: null, kind: "LocalArgument", name: "page_id_2" },
        ],
        kind: "Fragment",
        metadata: {
          connection: [
            { count: "first", cursor: "after", direction: "forward", path: e },
          ],
          refetch: {
            connection: {
              forward: { count: "first", cursor: "after" },
              backward: null,
              path: e,
            },
            fragmentPathInResult: [],
            operation: n("WAWebBizAdManagementRootPaginationQuery.graphql"),
          },
        },
        name: "WAWebBizAdManagementRoot_query",
        selections: [
          {
            kind: "RequiredField",
            field: {
              alias: null,
              args: null,
              concreteType: "CTWAAPI",
              kind: "LinkedField",
              name: "ctwa",
              plural: !1,
              selections: [
                {
                  alias: "all_user_ads",
                  args: [
                    {
                      kind: "Variable",
                      name: "options",
                      variableName: "options",
                    },
                    {
                      kind: "Variable",
                      name: "page_id_1",
                      variableName: "page_id_1",
                    },
                    {
                      kind: "Variable",
                      name: "page_id_2",
                      variableName: "page_id_2",
                    },
                  ],
                  concreteType: "CTWAAPIAllUserAdsConnection",
                  kind: "LinkedField",
                  name: "__WAWebBizAdManagementRoot_all_user_ads_connection",
                  plural: !1,
                  selections: [
                    {
                      alias: null,
                      args: null,
                      concreteType: "CTWAAPIAllUserAdsEdge",
                      kind: "LinkedField",
                      name: "edges",
                      plural: !0,
                      selections: [
                        {
                          alias: null,
                          args: null,
                          concreteType: null,
                          kind: "LinkedField",
                          name: "node",
                          plural: !1,
                          selections: [
                            {
                              kind: "InlineFragment",
                              selections: [t],
                              type: "Node",
                              abstractKey: "__isNode",
                            },
                            {
                              alias: null,
                              args: [
                                {
                                  kind: "Literal",
                                  name: "supported",
                                  value: "304s3R",
                                },
                              ],
                              concreteType: null,
                              kind: "LinkedField",
                              name: "wrapper_renderer",
                              plural: !1,
                              selections: [
                                {
                                  kind: "InlineFragment",
                                  selections: [
                                    {
                                      alias: null,
                                      args: null,
                                      concreteType:
                                        "CTWABoostedComponentWrapper",
                                      kind: "LinkedField",
                                      name: "boosted_component",
                                      plural: !1,
                                      selections: [
                                        {
                                          args: null,
                                          kind: "FragmentSpread",
                                          name: "WAWebBizAdDetailsDrawer_boostedComponent",
                                        },
                                        t,
                                        r,
                                        a,
                                        s,
                                        u,
                                      ],
                                      storageKey: null,
                                    },
                                  ],
                                  type: "CTWAAdsManagementBoostedComponent",
                                  abstractKey: null,
                                },
                                {
                                  kind: "InlineFragment",
                                  selections: [
                                    {
                                      alias: null,
                                      args: null,
                                      concreteType:
                                        "BoostedComponentAsyncWrapper",
                                      kind: "LinkedField",
                                      name: "async_request",
                                      plural: !1,
                                      selections: [
                                        {
                                          args: null,
                                          kind: "FragmentSpread",
                                          name: "WAWebBizAdDetailsDrawer_asyncRequest",
                                        },
                                        t,
                                        r,
                                        a,
                                        s,
                                        u,
                                      ],
                                      storageKey: null,
                                    },
                                  ],
                                  type: "LWIAdsManagementBoostedComponentAsyncRequest",
                                  abstractKey: null,
                                },
                              ],
                              storageKey:
                                'wrapper_renderer(supported:"304s3R")',
                            },
                            {
                              alias: null,
                              args: null,
                              kind: "ScalarField",
                              name: "__typename",
                              storageKey: null,
                            },
                          ],
                          storageKey: null,
                        },
                        {
                          alias: null,
                          args: null,
                          kind: "ScalarField",
                          name: "cursor",
                          storageKey: null,
                        },
                      ],
                      storageKey: null,
                    },
                    {
                      alias: null,
                      args: null,
                      concreteType: "PageInfo",
                      kind: "LinkedField",
                      name: "page_info",
                      plural: !1,
                      selections: [
                        {
                          alias: null,
                          args: null,
                          kind: "ScalarField",
                          name: "has_next_page",
                          storageKey: null,
                        },
                        {
                          alias: null,
                          args: null,
                          kind: "ScalarField",
                          name: "end_cursor",
                          storageKey: null,
                        },
                      ],
                      storageKey: null,
                    },
                  ],
                  storageKey: null,
                },
              ],
              storageKey: null,
            },
            action: "THROW",
            path: "ctwa",
          },
        ],
        type: "Query",
        abstractKey: null,
      };
    })();
    a.exports = e;
  },
  null,
);
