__d(
  "WAWebCrossposting.flow",
  ["$InternalEnum"],
  function (t, n, r, o, a, i) {
    var e,
      l = (e = n("$InternalEnum"))({
        PENDING: "CROSSPOSTING_REQUEST_PENDING",
        HARD_FAILURE: "CROSSPOSTING_REQUEST_HARD_FAILURE",
        OFFLINE_FAILURE: "CROSSPOSTING_REQUEST_OFFLINE_FAILURE",
        SUCCESS: "CROSSPOSTING_REQUEST_SUCCESS",
      }),
      s = e({ FACEBOOK: 0, INSTAGRAM: 1 }),
      u = e({ FACEBOOK: "F", INSTAGRAM: "I" }),
      c = e({ FACEBOOK: "FB", INSTAGRAM: "IG" }),
      d = "0",
      m = e({ ClientKey: "client_key", ServerKey: "server_key" }),
      p = 64,
      _ = "WAFFLE_CROSSPOSTING",
      f = e({ V1: 1 }),
      g = "STORY",
      h = 4,
      y = e({
        OK: 0,
        UNKNOWN_ERROR: 1,
        DUPLICATE_REQUEST: 2,
        ALREADY_SHARED: 3,
        ACCOUNT_LINK_ERROR: 4,
        DEACTIVATED_ACCOUNT: 5,
      });
    ((i.CrosspostingState = l),
      (i.CrosspostingDestination = s),
      (i.CrosspostingDestinationGQLValue = u),
      (i.CrosspostingDestinationIQValue = c),
      (i.NoPreviousCrosspostingRecord = d),
      (i.SharedKey = m),
      (i.SHARED_KEY_LENGTH = p),
      (i.HKDF_INFO = _),
      (i.PurposeEncryptionVersion = f),
      (i.CROSSPOSTING_SURFACE_STORY = g),
      (i.PurposeEncryptionVersionBytesLength = h),
      (i.CrosspostResponseCodes = y));
  },
  66,
);
