__d(
  "WAWebWamEnumLwiAdsContentType",
  [],
  function (t, n, r, o, a, i) {
    var e = Object.freeze({
      LWI_ADS_CONTENT_TYPE_PRODUCT: 1,
      LWI_ADS_CONTENT_TYPE_STATUS: 2,
      LWI_ADS_CONTENT_TYPE_DEVICE_MEDIA: 3,
      LWI_ADS_CONTENT_TYPE_BUSINESS_PROFILE_PIC: 4,
      LWI_ADS_CONTENT_TYPE_CAMERA: 9,
      LWI_ADS_CONTENT_TYPE_RECENTLY_USED_MEDIA: 10,
      LWI_ADS_CONTENT_TYPE_CATALOGS_ALL: 11,
      LWI_ADS_CONTENT_TYPE_STATUSES_ALL: 12,
      LWI_ADS_CONTENT_TYPE_RECREATION_MEDIA: 13,
      LWI_ADS_CONTENT_DRAFT_AD_NUX: 14,
      LWI_ADS_CONTENT_TYPE_PREVIOUS_ADS: 15,
      LWI_ADS_CONTENT_TYPE_FB_MEDIA: 16,
      LWI_ADS_CONTENT_TYPE_IG_MEDIA: 17,
    });
    i.LWI_ADS_CONTENT_TYPE = e;
  },
  66,
);
