__d(
  "WAWebFrontendGroupMetadataGetters",
  ["WAWebGetters", "WAWebGettersCaches", "WAWebGroupMetadataGetters"],
  function (t, n, r, o, a, i, l) {
    var e = "https://chat.whatsapp.com/",
      s = o("WAWebGetters").createGetterFactories({
        root: o("WAWebGroupMetadataGetters").getGroupMetadataUnsafe,
        createCache: o("WAWebGettersCaches").createFrontendGroupMetadataCache,
      }),
      u = s.clearCacheFor,
      c = s.computed,
      d = s.field;
    function m(e) {
      u(e);
    }
    function p(e) {
      return d(e);
    }
    var _ = p("afterReadDuration"),
      f = p("allowNonAdminSubGroupCreation"),
      g = p("announce"),
      h = p("cachedDeviceCount"),
      y = p("cachedDeviceSizeBucket"),
      C = p("creation"),
      b = p("defaultSubgroup"),
      v = p("displayedDesc"),
      S = p("ephemeralDuration"),
      R = p("groupAdder"),
      L = p("hasCapi"),
      E = p("hiddenSubgroup"),
      k = p("id"),
      I = p("isInternal"),
      T = p("isLidAddressingMode"),
      D = p("isOpenBotGroup"),
      x = p("isParentGroup"),
      $ = p("isTeeBotGroup"),
      P = p("joinedSubgroups"),
      N = p("lastReportToAdminTimestamp"),
      M = p("memberAddMode"),
      w = p("memberLinkMode"),
      A = p("membershipApprovalMode"),
      F = p("memberShareGroupHistoryMode"),
      O = p("noFrequentlyForwarded"),
      B = p("owner"),
      W = p("parentGroup"),
      q = p("reportToAdminMode"),
      U = p("restrict"),
      V = p("shouldDefaultGroupHistoryShareOn"),
      H = p("size"),
      G = p("support"),
      z = p("terminated"),
      j = p("uniqueShortNameMap"),
      K = p("unjoinedSubgroups"),
      Q = d("inviteCode"),
      X = c(
        function (t) {
          var n = t[0];
          return n ? "" + e + n : null;
        },
        [Q],
      );
    ((l.clearFrontendGroupMetadataGetterCacheFor = m),
      (l.getAfterReadDuration = _),
      (l.getAllowNonAdminSubGroupCreation = f),
      (l.getAnnounce = g),
      (l.getCachedDeviceCount = h),
      (l.getCachedDeviceSizeBucket = y),
      (l.getCreation = C),
      (l.getDefaultSubgroup = b),
      (l.getDisplayedDesc = v),
      (l.getEphemeralDuration = S),
      (l.getGroupAdder = R),
      (l.getHasCapi = L),
      (l.getHiddenSubgroup = E),
      (l.getId = k),
      (l.getIsInternal = I),
      (l.getIsLidAddressingMode = T),
      (l.getIsOpenBotGroup = D),
      (l.getIsParentGroup = x),
      (l.getIsTeeBotGroup = $),
      (l.getJoinedSubgroups = P),
      (l.getLastReportToAdminTimestamp = N),
      (l.getMemberAddMode = M),
      (l.getMemberLinkMode = w),
      (l.getMembershipApprovalMode = A),
      (l.getMemberShareGroupHistoryMode = F),
      (l.getNoFrequentlyForwarded = O),
      (l.getOwner = B),
      (l.getParentGroup = W),
      (l.getReportToAdminMode = q),
      (l.getRestrict = U),
      (l.getShouldDefaultGroupHistoryShareOn = V),
      (l.getSize = H),
      (l.getSupport = G),
      (l.getTerminated = z),
      (l.getUniqueShortNameMap = j),
      (l.getUnjoinedSubgroups = K),
      (l.getInviteCode = Q),
      (l.getGroupInviteLink = X));
  },
  98,
);
