__d(
  "WAWebUserPrefsKeys",
  ["$InternalEnum", "WAWebUserPrefsLoginKeys"],
  function (t, n, r, o, a, i, l) {
    var e = n("$InternalEnum").Mirrored([
        "TryItPixKeyPromoDismissed",
        "ChargesInfoBannerDismissed",
      ]),
      s = n("$InternalEnum").Mirrored([
        "AbpropsWebRefreshId",
        "ChatLockHide",
        "RecentSearches",
        "ChatLockSecretCode",
        "DisableLinkPreviews",
        "DeviceCapabilities",
        "PrimaryDeviceCapabilities",
        "PageLoadDebug",
        "SyncContactToAddressbookCounts",
        "MutexBlockStrategy",
        "CagEventsAwarenessBannerFirstSeenTimestamp",
        "WABrigadingState",
        "OHAIKeyConfig",
        "VerifiedBusinessNameLidTableMigrationComplete",
        "BusinessProfileLidTableMigrationComplete",
        "FavoritesLidTableMigrationComplete",
        "LabelAssociationsLidTableMigrationComplete",
        "PhoneNumberHidingThreadPromotionMigrationState",
        "SNAPLPersistentId",
        "SNAPLNewsLetterPersistentId",
        "MusicEligibleCountries",
        "CartDbLidMigrationComplete",
        "WindowsNotificationBannerSetting",
        "WindowsStatusReactionsSetting",
        "WindowsTaskbarNotificationSetting",
        "WindowsNotificationToneSetting",
        "WindowsGroupNotificationToneSetting",
        "WindowsStatusNotificationToneSetting",
        "WindowsIsSystemTrayEnabled",
        "WebUiRefreshNuxAcknowledged",
        "WebUiRefreshNuxViewsCount",
        "WindowsDontShowRateTheAppPromptAgain",
        "WindowsLastRateTheAppPromptTimestamp",
        "GuestActiveInviteCode",
        "GuestDeviceId",
        "GuestSessionId",
        "GuestNotifPrimerDialogDisabled",
        "GuestNotifPrimerDialogDisplayCount",
        "BlocklistMigrated",
        "InactiveGroupLidMigrationComplete",
        "GPCCompleted",
        "DetectedOutcomeOnboardingStatus",
        "MetaAISearchNullStateIndex",
        "WebQuestionsPrivacyBannerDismissed",
        "WebQuestionsResponsePrivacyBannerDismissed",
        "UserHasAvatar",
        "MemberLabelPrimaryCapability",
        "BizBroadcastPrimaryCapability",
        "GuestLastPageLoadTs",
        "IsSmb",
        "IsHostedMeAccount",
        "UsernameState",
        "WebTPSharerSkipConfirmation",
      ]),
      u = Object.freeze(
        babelHelpers.extends(
          {
            STORAGE_TEST: "storage_test",
            CLIENT_TOKEN: "WAToken1",
            SERVER_TOKEN: "WAToken2",
            SECRET: "WASecretKey",
            SECURITY_NOTIFICATIONS: "WASecurityNotifications",
            BROWSER_ID: "WABrowserId",
            GROUP_ASSIGNED_COLOR: "WAGroupAssignedColor-17",
            GLOBAL_MUTE_SOUNDS: "WAGlobalSounds",
            GLOBAL_MUTE_CALL_RINGTONE: "WAGlobalCallRingtone",
            OUTGOING_MESSAGE_SOUND: "WAOutgoingMessageSound",
            GLOBAL_MUTE_NOTIFICATIONS: "WAGlobalNotifications",
            GLOBAL_MUTE_CALL_NOTIFICATIONS: "WAGlobalCallNotifications",
            GLOBAL_MUTE_IN_APP_NOTIFICATIONS: "WAGlobalInAppNotifications",
            GLOBAL_MUTE_PREVIEWS: "WAGlobalPreviews",
            GLOBAL_OFFLINE_NOTIFICATIONS_ENABLED:
              "WAGlobalOfflineNotificationsEnabled",
            GLOBAL_NOTIFICATIONS_ENABLED: "WAGlobalNotificationsEnabled",
            GLOBAL_NOTIFICATION_REACTIONS_ENABLED:
              "WAGlobalNotificationReactionsEnabled",
            GLOBAL_SOUNDS_ENABLED: "WAGlobalSoundsEnabled",
            GLOBAL_GROUP_NOTIFICATIONS_ENABLED:
              "WAGlobalGroupNotificationsEnabled",
            GLOBAL_GROUP_NOTIFICATION_REACTIONS_ENABLED:
              "WAGlobalGroupNotificationReactionsEnabled",
            GLOBAL_GROUP_SOUNDS_ENABLED: "WAGlobalGroupSoundsEnabled",
            GLOBAL_STATUS_NOTIFICATIONS_ENABLED:
              "WAGlobalStatusNotificationsEnabled",
            GLOBAL_STATUS_NOTIFICATION_REACTIONS_ENABLED:
              "WAGlobalStatusNotificationReactionsEnabled",
            GLOBAL_STATUS_SOUNDS_ENABLED: "WAGlobalStatusSoundsEnabled",
            GLOBAL_OFFLINE_NOTIFICATIONS_ENABLED_ONCE:
              "WAGlobalOfflineNotificationsEnabledOnce",
            GLOBAL_COLLAPSE_MUTED: "WAGlobalCollapseMuted",
            NOTIFICATION_SOUND: "WANotificationSound",
            AUTO_DOWNLOAD_PHOTOS: "WAAutoDownloadPhotos",
            AUTO_DOWNLOAD_AUDIO: "WAAutoDownloadAudio",
            AUTO_DOWNLOAD_VIDEOS: "WAAutoDownloadVideos",
            AUTO_DOWNLOAD_DOCUMENTS: "WAAutoDownloadDocuments",
            LANG: "WALangPref",
            LANG_FROM_USER: "WALangUserPref",
            LANG_FROM_PHONE: "WALangPhonePref",
            LANG_DID_MISMATCH_WITH_COOKIE: "WALangPrefDidMismatchWithCookie",
            LAST_ACTIVE_EMOJI_TAB: "WALastActiveEmojiTab",
            LAST_SELECTED_COMPOSE_BOX_PANEL: "WALastActiveComposeBoxPanel",
            LAST_CHAT_MUTE_DURATION: "WALastChatMuteDuration",
            UNKNOWN_ID: "WAUnknownID",
            LOAD_RETRY_GENERATION: "WALoadRetryGeneration",
            WHATSAPP_MUTEX: "whatsapp-mutex",
            MUTEX_PING_TIMEOUT_SECONDS: "mutex-ping-timeout",
            LAST_WID: "last-wid",
            SAVE_TO_CAMERA_ROLL: "save_to_camera_roll",
            PINS_DEBUG_MODE: "pins_debug_mode",
            IS_OPT_IN_EXTERNAL_BETA: "is_opt_in_external_beta",
            DEXIE_VERSION: "dexie_version",
            POSTCODE_AUTO_OPEN_CHANGE_POSTCODE_DONE:
              "postcode_auto_open_change_postcode_done",
            POSTCODE_AUTO_OPEN_CHANGE_POSTCODE_COUNT:
              "postcode_auto_open_change_postcode_count",
            POSTCODE_TOOLTIP_VIEW_COUNT: "postcode_tooltip_view_count",
            POSTCODE_TOOLTIP_VIEWED_IN_SESSION:
              "postcode_tooltip_viewed_in_session",
            LAST_PUSHNAME: "last-pushname",
            PTT_PLAYBACK_RATE: "WAPttPlaybackRate",
            LOGOUT_DIRTY_BIT: "post-logout",
            DAILY_STATS_START_TIME: "WADailyStatsStartTime",
            PRIMARY_FEATURES: "WAPrimaryFeatures",
            TOS_STATE_FETCH_ITERATION: "ToSStateFetchIteration",
            NUX_LIST: "WANuxList",
            NUX_DATA: "WANuxData",
            ACTIVE_USAGE_DAYS_SINCE_DIALOG_OPENED:
              "WAActiveUsageDaysSinceDialogOpened",
            BANNER_STATES: "WABannerStates",
            LID: "WALid",
            ME_DISPLAY_NAME: "me-display-name",
            PRESERVED_USER_KEYS: "preserved_user_keys",
            LAST_STATUS_USAGE: "last-status-usage",
            REMEMBER_ME: "remember-me",
            NO_TAKEOVER: "no-takeover",
            WHATSAPP_LS_VERSION: "ver",
            USER_ACTIVITY_TIME_SPENT_EVENT: "WaTimeSpentEvent",
            TIME_SPENT_BITARRAY_EVENT: "WAWebTsBitarrayEvent",
            MEDIA_VOLUME: "video-volume",
            MEDIA_MUTE: "video-mute",
            MEDIA_HD: "hd-media",
            CONTACT_CHECKSUM: "contact-checksum",
            CONTACT_CHECKSUM_MODEL_STORAGE: "contact_checksum",
            FREQUENT_CONTACTS: "frequent_contacts",
            GK_PROTO: "gk_proto",
            INITIAL_HIST_BOUNDARY: "history_initial_sync_boundry",
            INITIAL_GROUP_PHASH: "initial_group_phash",
            IS_SMB: "is-smb",
            COMPOSE_CONTENTS_PREFIX: "compose-contents_",
            THEME: "theme",
            SYSTEM_THEME_MODE: "system-theme-mode",
            LAST_MEDIA_EDITOR_PAINT_COLOR: "WALastMediaEditorPaintColor",
            ABPROPS: "abprops",
            ABPROPS_REFRESH_ID: "abprops-refresh-id",
            GROUP_ABPROPS_REFRESH_ID: "group-abprops-refresh-id",
            GROUP_ABPROPS_EMERGENCY_PUSH_TIMESTAMP:
              "group-abprops-emergency-push-timestamp",
            QP_EMERGENCY_FORCE_FETCH_LAST_HANDLED_NONCE:
              "qp-emergency-force-fetch-last-handled-nonce",
            HISTORY_SYNC_EARLIEST_DATE: "history-sync-earliest-date",
            HISTORY_SYNC_COMPLETE_ON_DEMAND_ACCESS_GRANTED:
              "WAHistorySyncCompleteOnDemandAccessGranted",
            CHATS_USER_SENT_MESSAGE_TO: "chats-user-sent-message-to",
            CONTACT_SYNC_REFRESH: "contact-sync-refresh-seconds",
            TOS_3: "TOS_STATE_20210210",
            LOCAL_TAKEOVER_OK: "local-takeover-ok",
            PS_KILLSWITCH_TOKEN: "ps-killswitch-token",
            STORAGE_DISMISS_STATE: "storage-dismiss-state",
            STORAGE_ALERT_FLAG: "storage-alert-flag",
            HOUR_24_FROM_PHONE: "hour-24-from-phone",
            HOUR_24: "hour-24",
            HOUR_24_FROM_DEVICE: "hour-24-from-device",
            PERSISTENT_EXPIRING_ID: "WaPersistentExpiringId",
            FIRST_SEEN_DESKTOP_UPSELL_BBAR: "first-seen-desktop-upsell-bbar",
            DESKTOP_UPSELL_USER_HAS_CLICKED_CALL_MODAL:
              "desktop-upsell-user-has-clicked-call-modal",
            DESKTOP_UPSELL_USER_HAS_DISMISSED_CHATLIST_TOASTBAR:
              "desktop-upsell-user-has-dismissed_chatlist-toastbar",
            DESKTOP_UPSELL_USER_HAS_SEEN_LARGE_BANNER:
              "desktop-upsell-user-has-seen-large-banner",
            WEB_NOTIFICATIONS_BB_STATUS: "WAWebNotificationsButterbarStatus",
            OFFLINE_NOTIFICATIONS_BB_STATUS:
              "WAOfflineNotificationsButterbarStatus",
            FB_SHOPS_SUNSET_BB_STATUS: "WAWebFBShopsSunsetButterbarStatus",
            NOTIFICATIONS_GRANULARITY_AWARENESS_BANNER_STATUS:
              "WANotificationsGranularityAwarenessBannerStatus",
            EXISTING_LID_SIGNAL_SESSION_IS_CLEANED:
              "existing_lid_signal_session_is_cleaned",
            LID_DB_MIGRATION: "lid_db_migration",
            VERIFIED_BUSINESS_NAME_IS_CLEANED:
              "WAVerifiedBusinessNameIsCleaned",
            WHATSAPP_WEB_EXTERNAL_BETA: "whatsapp_web_beta",
            WHATSAPP_WEB_EXTERNAL_BETA_DIRTY_BIT: "whatsapp_web_beta_dirty_bit",
            WHATSAPP_WEB_EXTERNAL_BETA_IDB: "WAWebBetaOptInStatus",
            WHATSAPP_WEB_EXTERNAL_BETA_DIRTY_BIT_IDB: "WAWebBetaOptInDirtyBit",
            CHAT_UTM: "deeplink_utm",
            EXTERNAL_ENTRY_POINT: "external_entry_point",
            AD_CREATION_FLOW_ID_KEY: "ad_creation_flow_id_key",
            AD_CREATION_SEQUENCE_NUMBER_KEY: "ad_creation_sequence_number_key",
            AD_ENTRY_POINTS_CONFIGURATION: "ad_entry_points_configuration",
            AD_ACCOUNT_TOKEN: "ad_account_token",
            AD_ACCOUNT_BP_ID: "ad_account_bp_id",
            AD_ACCOUNT_TOKEN_STRENGTH: "ad_account_token_strength",
            FB_ACCOUNT_TOKEN: "fb_account_token",
            FB_ACCOUNT_BP_ID: "fb_account_bp_id",
            NATIVE_ADS_MVP_ELIGIBILITY: "native_ads_mvp_eligibility",
            CHATLIST_PANEL_STATE: "chatlist_panel_state",
            CTWA_DATA_SHARING_UPSELL_ACTIVE: "ctwa_data_sharing_upsell_active",
            CTWA_DATA_SHARING_COOL_OFF: "ctwa_data_sharing_cool_off",
            CTWA_CONSUMER_TRANSPARENCY_INFO_ICON:
              "ctwa_consumer_transparency_info_icon",
            CTWA_MESSAGE_RECEIVED: "ctwa_message_received",
            CTWA_DATA_SHARING_DISCLOSURE_SHOWN_COUNT:
              "ctwa_data_sharing_disclosure_shown_count",
            CTWA_DATA_SHARING_OPT_OUT_DISCLOSURE_SHOWN_COUNT:
              "ctwa_data_sharing_opt_out_disclosure_shown_count",
            CTWA_PREFERRED_AD_ACCOUNT_TYPE: "ctwa_preferred_ad_account_type",
            GUEST_MSG_NOTIFICATION_TEXT: "guest_msg_notification_text",
            GUEST_MSG_NOTIFICATION_TEXT_WITH_PUSHNAME:
              "guest_msg_notification_text_with_pushname",
            GUEST_MSG_NOTIFICATION_TITLE: "guest_msg_notification_title",
            GUEST_ACTIVE_INVITE_CODE: "guest_active_invite_code",
            GUEST_INVITER_PUSHNAME: "guest_inviter_pushname",
            GUEST_INVITER_PROFILE_PIC_URL: "guest_inviter_profile_pic_url",
            DISAPPEARING_MSG_DISCLAIMER_DIMISSED:
              "disappearing_msg_disclaimer_dimissed",
            TIME_SPENT_SESSION: "WAWebTimeSpentSession",
            TIME_SPENT_PENDING_BACKGROUND_NAVIGATION:
              "WAWebTimeSpentPendingBackgroundNavigation",
            WA_WEB_CACHED_RECOMMENDED_NEWSLETTERS:
              "WAWebCachedRecommendedNewsletters",
            WA_WEB_NEWSLETTERS_SUBSCRIBERS_FULL:
              "WAWebNewsletterSubscribersFull",
            WA_WEB_NEWSLETTERS_SUBSCRIBERS_LIMITED:
              "WAWebNewsletterSubscribersLimited",
            WA_WEB_CACHED_NEWSLETTERS_SUBSCRIBERS:
              "WAWebCachedNewsletterSubscribers",
            WA_WEB_CACHED_NEWSLETTER_DIRECTORY_PAGES:
              "WAWebCachedNewsletterDirectoryPages",
            WA_WEB_CACHED_NEWSLETTER_DIRECTORY_CATERGORY_PREVIEW:
              "WAWebCachedNewsletterDirectoryCategoryPreview",
            WA_WEB_CACHED_META_AI_SEARCH_NULL_STATE_SUGGESTIONS:
              "WAWebMetaAISearchNullStateSuggestions",
            WA_WEB_CACHED_META_AI_SEARCH_TYPE_AHEAD_SUGGESTIONS:
              "WAWebMetaAISearchTypeAheadSuggestions",
            WA_WEB_CACHED_DYNAMIC_AI_MODES: "WAWebCachedDynamicAIModes",
            WA_WEB_META_AI_GLASSES_BANNER_DISPLAY_INFO_TYPE:
              "WAWebMetaAIGlassesBannerDisplayInfoType",
            LAST_PROFILE_PIC_THUMB_UPDATE_TS:
              "last_profile_pic_thumb_update_ts_v2",
            AUTO_LOGOUT_ENABLED: "auto_logout_enabled",
            PAYMENT_INFO: "WAPaymentInfo",
            CUSTOM_PAYMENT_METHODS: "WACustomPaymentMethods",
            MERCHANT_PAYMENT_PARTNER: "WAMerchantPaymentPartner",
            PAYMENT_TOS: "WAPaymentTos",
            WA_WEB_ID_UPSELL_SNOOZE_UNTIL: "WAWebIDUpsellSnoozeUntil",
            WA_WEB_DB_TABLE_USAGE_ENABLED: "WAWebDBUsageLoggingEnabled",
            WA_WEB_WAM_BEACONING_SETTINGS: "WAWebWAMBeaconingSettings",
            WA_WEB_SIGNAL_STORAGE_LID_MIGRATION:
              "WAWebSignalStorageLidMigration",
            WA_WEB_GALAXY_DISABLE_CTA_COLLECTION:
              "WAWebGalaxyDisableCTACollection",
            WA_WEB_GALAXY_DISABLE_CTA_AGM_COLLECTION:
              "WAWebGalaxyDisableCTAAGMCollection",
            WA_WEB_REFRESH_STATE: "wa_web_refresh_state",
            WA_WEB_META_AI_THREAD_MIGRATION_STATE:
              "WAWebMetaAIThreadMigrationState",
            WINDOWS_PENDING_CLIENT_KEY_SETUP:
              "WAWebWindowsPendingClientKeySetup",
          },
          o("WAWebUserPrefsLoginKeys").WAWebUserPrefsLoginKeys,
        ),
      ),
      c = Object.freeze({
        EMOJI_VARIANT_COLLECTION: "emoji_variant_collection",
        RECENT_EMOJI_COLLECTION: "recent_emoji_collection",
        RECENT_REACTIONS_COLLECTION: "recent_reactions_collection",
        CHAT_PREFERENCE_COLLECTION: "chat_preference",
        CONVERSION_TUPLE_COLLECTION: "conversion_tuple",
        MUTE_COLLECTION: "mute",
        PROFILE_PIC_THUMB_COLLECTION: "profile_pic_thumb",
        UNATTRIBUTED_MESSAGE_COLLECTION: "unattributed_message_collection",
        CART_COLLECTION: "cart_collection",
        DAILY_AGGREGATED_STATS_COLLECTION: "daily_aggregated_stats",
      }),
      d = Object.freeze({
        NOISE_INFO: "WANoiseInfo",
        NOISE_INFO_IV: "WANoiseInfoIv",
        ME_INFO: "WAMeInfo",
        DEVICE_ID: "WADeviceId",
        INITIAL_HISTORY_SYNCED: "WaInitialHistorySynced",
        HISTORY_SYNC_REMAINING_PAUSED_SECONDS:
          "WAHistorySyncRemainingPausedSeconds",
        IS_SMB: "WAIsSMB",
        LAST_OFFLINE_MESSAGE: "WALastOfflineMessage",
        WEB_ENC_SALT: "WebEncKeySalt",
        SYNCD_PRIMARY_ALLOWS_ALL_MUTATIONS: "WASyncdPrimaryAllowsAllMutations",
        IS_COMMUNITY_DISCOVERED: "WAIsCommunityDiscovered",
        SCREEN_LOCK_DURATION_SECONDS: "WAScreenLockDuration",
        SCREEN_UNLOCK_TRY_COUNT: "WAScreenUnlockTryCount",
        SCREEN_LOCK_IV: "WAScreenLockIV",
        SCREEN_LOCK_DATA_IV: "WAScreenLockDataIV",
        SCREEN_LOCK_SALT: "WAScreenLockSalt",
        SCREEN_LOCK_ITERATIONS: "WAScreenLockIterations",
        CACHED_PROFILE_PIC_EURL: "WACachedProfilePicEURL",
        COMMUNITY_TAB_LAST_SEEN_TIMESTAMP: "WACommunityTabLastSeenTimestamp",
        KEY_SEVER_CLIENT_EXPIRATION_OVERRIDE:
          "key_sever_client_expiration_override",
        COLUMN_PACKING_ENABLED: "WAWebColumnPackingEnabled",
        NEWSLETTER_TAB_LAST_SEEN_TIMESTAMP: "WANewslettersTabLastSeenTimestamp",
        NEWSLETTER_WAS_BOOTSTRAPPED: "WANewslettersWasBootstrapped",
        BOT_LIST_LAST_REQUESTED_TIMESTAMP: "WABotListLastRequestedTimestamp",
        UGC_BOT_LIST_LAST_REQUESTED_TIMESTAMP:
          "WAUgcBotListLastRequestedTimestamp",
        UGC_BOT_LIST_LAST_BHASH: "WAUgcBotListLastBhash",
        IS_HOSTED_ME_ACCOUNT: "WAIsHostedMeAccount",
        MMS4_CONN: "WAMms4Conn",
      }),
      m = Object.freeze({
        NOISE_INFO: "WANoiseInfo",
        NOISE_INFO_IV: "WANoiseInfoIv",
        WEB_ENC_SALT: "WAWebEncKeySalt",
      }),
      p = Object.freeze({
        ROUTING_INFO: "WARoutingInfo",
        INITIAL_HISTORY_SYNCED: "WAInitialHistorySynced",
        HISTORY_SYNC_STATUS: "WAHistorySyncStatus",
        BLOCKLIST_HASH: "WABlocklistHash",
        OPTOUTLIST_HASH: "WAOptOutListHash",
        CRITICAL_DATA_SYNCED: "WACriticalDataSynced",
        SHOULD_CHECK_CONTACT_SYNC_STATUS: "WAShouldCheckContactSyncStatus",
        ADV_SECRET_KEY: "WAADVSecretKey",
        MD_HISTORY_LAST_CHUNK_PROCESSED: "WAMdHistoryLastChunkProcessed",
        UNARCHIVE_CHATS_SETTING: "WAUnarchiveChatsSetting",
        ARCHIVE_V2_ENABLED_SETTING: "WAArchiveV2EnabledSetting",
        MD_SYNC_ACTIONS_ACTION_SANITIZED: "WAMdSyncActionsActionSanitized",
        CHAT_THREAD_LOGGING_OFFSET: "WAChatThreadLoggingOffset",
        CHAT_THREAD_LOGGING_SECRET: "WAChatThreadLoggingSecret",
        CHAT_THREAD_LOGGING_LAST_UPLOADED_START_TS:
          "WAChatThreadLoggingLastUploadedStartTs",
        IS_COMMUNITY_DISCOVERED: "WAIsCommunityDiscovered",
        PAIRING_TIMESTAMP: "WAMdPairingTimestamp",
        RECENT_MAILBOX_AGE_DAYS: "WAMdRecentMailboxAgeDays",
        LAST_PERIODIC_APP_STATE_SYNC_TS: "WAMdLastPeriodicAppStateSyncTs",
        HISTORY_SYNC_CHUNK_COUNT_FOR_END_OF_RECENT_SYNC:
          "WAHistorySyncChunkCountForEndOfRecentSync",
        MOBILE_PLATFORM: "WAMobilePlatform",
        NON_CRITICAL_DATA_SYNC_STATUS: "WANonCriticalDataSyncStatus",
        PRIMARY_FEATURES: "WAPrimaryFeatures",
        APP_VERSION_BASE: "WAVersionBase",
        ESTIMATED_HISTORY_SYNC_CHUNK_COUNT_FOR_END_OF_RECENT_SYNC:
          "WAEstimatedHistorySyncChunkCountForEndOfRecentSync",
        LOGIN_COUNTER: "WALoginCounter",
        OFFLINE_PUSH_COUNT: "WAOfflinePushCount",
        HISTORY_SYNC_SINGLE_CHUNK_STATUS: "WAHistorySyncSingleChunkStatus",
        LAST_PUSH_COMPLETE_TIMESTAMP: "WALastPushCompleteTimestamp",
        OFFLINE_PUSH_DISABLED: "WAOfflinePushDisabled",
        MD_HISTORY_LAST_RECENT_SYNC_CHUNK_PROCESSED:
          "WAMdHistoryLastRecentSyncChunkProcessed",
        OFFLINE_NOTIFICATION_L10N_CONTENT: "WAOfflineNotificationContent",
        LOGOUT_REASON: "WALogoutReason",
        HISTORY_SYNC_STATUS_AFTER_PAIRING_LOGGING_COUNT:
          "WAHistorySyncStatusAfterPairingLoggingCount",
        STATUS_ALLOW_LIST: "WAStatusPostingAllowList",
        STATUS_DENY_LIST: "WAStatusPostingDenyList",
        STATUS_SENDER_KEY: "WAStatusPostingSenderkey",
        STATUS_PRIVACY_SETTING: "WAStatusPostingPrivacySetting",
        STATUS_SHARE_TO_FB: "WAStatusShareToFB",
        STATUS_SHARE_TO_IG: "WAStatusShareToIG",
        STATUS_RESHARE_ALLOWED: "WAStatusReshareAllowed",
        OFFLINE_NOTIFICATION_ENGAGEMENT: "WAOfflineNotificationEngagement",
        NOTIFICATION_ENGAGEMENT: "WANotificationEngagement",
        IS_HOSTED_ME_ACCOUNT: "WAIsHostedMeAccount",
        TEXT_STATUS_SUGGESTIONS: "WATextStatusSuggestions",
        MMS4_CONN: "WAMms4Conn",
        HISTORY_SYNC_TOTAL_PROCESSED_MESSAGE_COUNT:
          "WAHistorySyncTotalProcessedMessageCount",
        HAVE_PROCESSED_COEX_ADV: "WAHaveProcessedCoexAdv",
        NCT_SALT: "WAWebNctSalt",
        OPUS_MIGRATION_COMPLETE: "WAOpusMigrationComplete",
      }),
      _ = Object.freeze({
        USER_PRIVACY_SETTINGS: "user-privacy-settings",
        INITIAL_HIST_BOUNDARY: "history_initial_sync_boundry",
      });
    ((l.PaymentsBannerUserPrefs = e),
      (l.UserPrefs = s),
      (l.KEYS = u),
      (l.COLLECTIONS_KEYS = c),
      (l.MD_KEYS = d),
      (l.MD_NOISE_KEYS = m),
      (l.BACKEND_ONLY_KEYS = p),
      (l.HASHED_KEYS = _));
  },
  98,
);
