__d(
  "WAWebUnstyledButton.react",
  [
    "WAWebClassnames",
    "WAWebKeyboardIsKeyActivation",
    "WAWebUISpacing",
    "WAWebUnstyledButtonStyles",
    "WDSFocusStateStyles",
    "react",
    "stylex",
    "useMergeRefs",
  ],
  function (t, n, r, o, a, i, l) {
    var e = [
        "ref",
        "children",
        "className_DONOTUSE",
        "customDataAttr",
        "dataTab",
        "dir",
        "disabled",
        "onBlur",
        "onClick",
        "onContextMenu",
        "onDisabledClick",
        "onFocus",
        "onMouseDown",
        "onMouseEnter",
        "onMouseLeave",
        "onMouseOver",
        "onMouseUp",
        "onPaste",
        "role",
        "tabIndex",
        "testid",
        "title",
        "type",
        "xstyle",
      ],
      s,
      u,
      c = u || (u = o("react")),
      d = u,
      m = d.useCallback,
      p = d.useRef;
    function _(t) {
      var n,
        a = t.ref,
        i = t.children,
        l = t.className_DONOTUSE,
        u = t.customDataAttr,
        d = t.dataTab,
        _ = t.dir,
        f = t.disabled,
        g = t.onBlur,
        h = t.onClick,
        y = t.onContextMenu,
        C = t.onDisabledClick,
        b = t.onFocus,
        v = t.onMouseDown,
        S = t.onMouseEnter,
        R = t.onMouseLeave,
        L = t.onMouseOver,
        E = t.onMouseUp,
        k = t.onPaste,
        I = t.role,
        T = t.tabIndex,
        D = T === void 0 ? 0 : T,
        x = t.testid,
        $ = t.title,
        P = t.type,
        N = P === void 0 ? "button" : P,
        M = t.xstyle,
        w = babelHelpers.objectWithoutPropertiesLoose(t, e),
        A = p(null),
        F = r("useMergeRefs")(a, A),
        O = (n = w["aria-label"]) != null ? n : $,
        B = m(function (e) {
          if (r("WAWebKeyboardIsKeyActivation")(e)) {
            var t;
            (e.stopPropagation(),
              e.preventDefault(),
              (t = A.current) == null || t.click());
          }
        }, []),
        W = f === !0 ? C : h,
        q = m(
          function (e) {
            W != null &&
              (f === !0 && (e.stopPropagation(), e.preventDefault()), W(e));
          },
          [W, f],
        );
      return c.jsx(
        "button",
        babelHelpers.extends(
          {
            className: o("WAWebClassnames").classnamesConvertMeToStylexPlease(
              (s || (s = r("stylex")))(
                r("WAWebUnstyledButtonStyles").button,
                o("WDSFocusStateStyles").WDSFocusStateStyles.genericFocus,
                o("WAWebUISpacing").uiPadding.all0,
                f === !0 && r("WAWebUnstyledButtonStyles").disabled,
                M,
              ),
              l,
            ),
            tabIndex: D,
            "data-tab": d != null ? d : void 0,
            "data-testid": void 0,
            disabled: f === !0 && C == null,
            "aria-disabled": f === !0,
            onClick: W == null ? null : q,
            onContextMenu: y,
            onMouseEnter: S,
            onMouseOver: L,
            onMouseLeave: R,
            onMouseDown: v,
            onMouseUp: E,
            onKeyPress: B,
            onPaste: k,
            onFocus: b,
            onBlur: g,
            ref: F,
            title: $,
            type: N,
            role: I,
            dir: _,
            "aria-label": O,
            "data-custom-attr": u,
          },
          w,
          { children: i },
        ),
      );
    }
    ((_.displayName = _.name + " [from " + i.id + "]"), (l.default = _));
  },
  98,
);
