__d(
  "WAWebWamEnumDisclosureEntryPointType",
  [],
  function (t, n, r, o, a, i) {
    var e = Object.freeze({
      PRE_THREAD: 0,
      ON_THREAD_ENTRY: 1,
      SEND_FROM_THREAD: 2,
      SEND_FROM_THREAD_KEYBOARD: 3,
      ICEBREAKERS: 4,
      THREAD_ATTACHMENT_BAR: 5,
      THREAD_EMOJI_BAR: 6,
      AUDIO_VIDEO_CALL_FROM_THREAD: 7,
      AUDIO_CALL_FROM_THREAD: 8,
      VIDEO_CALL_FROM_THREAD: 9,
      AUDIO_NOTE_FROM_THREAD: 10,
      VIDEO_NOTE_FROM_THREAD: 11,
      CAMERA_MEDIA_SELECTION: 12,
      CALL_FROM_PROFILE: 13,
      OVERFLOW_SEND_ORDER: 14,
      MESSAGE_FROM_PROFILE: 15,
      VIDEO_CALL_FROM_PROFILE: 16,
      CALL_FROM_BUSINESS_DETAILS_CARD: 17,
      TEXT_ENTRY_FROM_THREAD: 18,
      VIEW_CATALOG_FROM_THREAD: 19,
      VIEW_CATALOG_FROM_PROFILE: 20,
      SEND_CALL_LINK_FROM_THREAD: 21,
    });
    i.DISCLOSURE_ENTRY_POINT_TYPE = e;
  },
  66,
);
