__d(
  "WAWebBotProfileGetters",
  ["WAWebGetters"],
  function (t, n, r, o, a, i, l) {
    var e = o("WAWebGetters").createGetterFactories(),
      s = e.field,
      u = s("prompts"),
      c = s("commands"),
      d = s("isDefault"),
      m = s("posingAsProfessional"),
      p = s("id"),
      _ = s("lastFetchedTimeMs"),
      f = s("name"),
      g = s("product"),
      h = s("isDeprecated"),
      y = s("creatorLid"),
      C = s("isDeleted");
    ((l.getPrompts = u),
      (l.getCommands = c),
      (l.getIsDefault = d),
      (l.getPosingAsProfessional = m),
      (l.getId = p),
      (l.getLastFetchedTimeMs = _),
      (l.getName = f),
      (l.getProduct = g),
      (l.getIsDeprecated = h),
      (l.getCreatorLid = y),
      (l.getIsDeleted = C));
  },
  98,
);
