__d(
  "WAWebWamEnumCanonicalEntRecoveryCompanionEvent",
  [],
  function (t, n, r, o, a, i) {
    var e = Object.freeze({
      COMPANION_REGISTERED: 0,
      REQUEST_NONCE_FROM_PRIMARY: 1,
      FETCH_COMPANION_NONCE: 2,
      FORWARD_NONCE_PRIMARY_TO_COMPANION: 3,
      RECEIVED_COMPANION_NONCE_FROM_PRIMARY: 4,
      EXCHANGE_NONCE: 5,
      CREDENTIALS_STORED: 6,
      VALIDATE_ACCESS_TOKEN: 7,
      CRED_REQUEST_STARTED: 8,
      CRED_REQUEST_SUCCEEDED_FROM_STORAGE: 9,
      CRED_REQUEST_SUCCEEDED_VIA_RECOVERY: 10,
      CRED_REQUEST_FAILED_TIMEOUT: 11,
      CRED_REQUEST_FAILED_ERROR: 12,
    });
    i.CANONICAL_ENT_RECOVERY_COMPANION_EVENT = e;
  },
  66,
);
