__d(
  "WAWebStatusPostWamEvent",
  [
    "WAWebWamCodegenUtils",
    "WAWebWamEnumMediaType",
    "WAWebWamEnumPairedMediaType",
    "WAWebWamEnumPrivacySettingsValueType",
    "WAWebWamEnumStatusCategory",
    "WAWebWamEnumStatusPairedMediaQuality",
    "WAWebWamEnumStatusPostOrigin",
    "WAWebWamEnumStatusPostResult",
    "WAWebWamEnumStatusType",
  ],
  function (t, n, r, o, a, i, l) {
    var e,
      s = (e = o("WAWebWamCodegenUtils")).defineEvents(
        {
          StatusPost: [
            1176,
            {
              channelStatusId: [57, e.TYPES.INTEGER],
              cid: [58, e.TYPES.STRING],
              containsPrompt: [19, e.TYPES.BOOLEAN],
              defaultStatusPrivacySetting: [
                6,
                o("WAWebWamEnumPrivacySettingsValueType")
                  .PRIVACY_SETTINGS_VALUE_TYPE,
              ],
              dualUploadPairedMediaId: [44, e.TYPES.STRING],
              editable: [15, e.TYPES.BOOLEAN],
              externalInteractables: [16, e.TYPES.INTEGER],
              externalPackageName: [17, e.TYPES.STRING],
              extraStickersData: [22, e.TYPES.STRING],
              groupMentionCount: [48, e.TYPES.STRING],
              hasArFilters: [23, e.TYPES.BOOLEAN],
              hasCaption: [24, e.TYPES.BOOLEAN],
              hasDrawings: [25, e.TYPES.BOOLEAN],
              hasFilters: [26, e.TYPES.BOOLEAN],
              individualMentionCount: [49, e.TYPES.INTEGER],
              isCropped: [36, e.TYPES.BOOLEAN],
              isDraft: [55, e.TYPES.BOOLEAN],
              isForwardable: [51, e.TYPES.BOOLEAN],
              isForwarded: [52, e.TYPES.BOOLEAN],
              isFromLayouts: [41, e.TYPES.BOOLEAN],
              isMediaAiImagineGenerated: [43, e.TYPES.BOOLEAN],
              isPromptResponse: [20, e.TYPES.BOOLEAN],
              isResharable: [47, e.TYPES.BOOLEAN],
              isReshare: [13, e.TYPES.BOOLEAN],
              isResultTerminal: [11, e.TYPES.BOOLEAN],
              isRotated: [37, e.TYPES.BOOLEAN],
              isSameSongFromAttribution: [40, e.TYPES.BOOLEAN],
              isVideoManuallyTrimmed: [38, e.TYPES.BOOLEAN],
              isVideoMuted: [27, e.TYPES.BOOLEAN],
              isVideoTrimmed: [28, e.TYPES.BOOLEAN],
              mediaType: [2, o("WAWebWamEnumMediaType").MEDIA_TYPE],
              messageKeyHash: [21, e.TYPES.STRING],
              messageSendT: [12, e.TYPES.TIMER],
              pairedMediaType: [
                45,
                o("WAWebWamEnumPairedMediaType").PAIRED_MEDIA_TYPE,
              ],
              perPostStatusPrivacySetting: [
                7,
                o("WAWebWamEnumPrivacySettingsValueType")
                  .PRIVACY_SETTINGS_VALUE_TYPE,
              ],
              retryCount: [5, e.TYPES.INTEGER],
              shareType: [18, e.TYPES.STRING],
              statusAudienceSelected: [56, e.TYPES.INTEGER],
              statusAudienceSelectorClicked: [8, e.TYPES.BOOLEAN],
              statusAudienceSelectorUpdated: [9, e.TYPES.BOOLEAN],
              statusAudienceSize: [39, e.TYPES.INTEGER],
              statusCategory: [
                53,
                o("WAWebWamEnumStatusCategory").STATUS_CATEGORY,
              ],
              statusContainsMusic: [14, e.TYPES.BOOLEAN],
              statusId: [29, e.TYPES.STRING],
              statusMentionCount: [10, e.TYPES.INTEGER],
              statusPairedMediaQuality: [
                46,
                o("WAWebWamEnumStatusPairedMediaQuality")
                  .STATUS_PAIRED_MEDIA_QUALITY,
              ],
              statusPostOrigin: [
                4,
                o("WAWebWamEnumStatusPostOrigin").STATUS_POST_ORIGIN,
              ],
              statusPostResult: [
                3,
                o("WAWebWamEnumStatusPostResult").STATUS_POST_RESULT,
              ],
              statusSessionId: [1, e.TYPES.INTEGER],
              statusType: [30, o("WAWebWamEnumStatusType").STATUS_TYPE],
              stickersCount: [31, e.TYPES.INTEGER],
              textStatusColorChanged: [32, e.TYPES.BOOLEAN],
              textStatusFontChanged: [33, e.TYPES.BOOLEAN],
              textToolCount: [34, e.TYPES.INTEGER],
              unifiedSessionId: [35, e.TYPES.STRING],
              updatesTabSessionId: [54, e.TYPES.INTEGER],
              urlHasAdditionalText: [42, e.TYPES.BOOLEAN],
            },
            [1, 1, 1],
            "regular",
          ],
        },
        { StatusPost: [] },
      );
    l.StatusPostWamEvent = s;
  },
  98,
);
