__d(
  "WAWebWamEnumShopsManagementAction",
  [],
  function (t, n, r, o, a, i) {
    var e = Object.freeze({
      ACTION_CLICK_SHOPS_SETTING: 1,
      ACTION_CLICK_CATALOG_SETTING: 2,
      ACTION_CLICK_COMMERCE_MANAGER_IN_CATALOG_SETTING: 3,
      ACTION_CLICK_CANCEL_IN_CATALOG_SETTING: 4,
      ACTION_CLICK_VIEW_SHOPS_IN_SHOPS_SETTING: 5,
      ACTION_CLICK_COMMERCE_MANAGER_IN_SHOPS_SETTING: 6,
      ACTION_CLICK_CANCEL_IN_SHOPS_SETTING: 7,
      ACTION_SHOPS_PRODUCT_PREVIEW_VISIBLE: 8,
      ACTION_CLICK_SHOPS_PRODUCT_PREVIEW_TILE: 9,
      ACTION_CLICK_MANAGE_SHOPS: 10,
      ACTION_SHARE_SHOPS: 11,
      ACTION_CLICK_VIEW_SHOPS_FROM_EDIT_BIZ_PROFILE: 12,
      ACTION_CLICK_COMMERCE_MANAGER_FROM_EDIT_BIZ_PROFILE: 13,
      ACTION_CLICK_CANCEL_FROM_EDIT_BIZ_PROFILE: 14,
    });
    i.SHOPS_MANAGEMENT_ACTION = e;
  },
  66,
);
