__d(
  "WAWebBackendJobs.flow",
  ["$InternalEnum"],
  function (t, n, r, o, a, i) {
    var e = n("$InternalEnum")({
        Skmsg: "skmsg",
        Pkmsg: "pkmsg",
        Msg: "msg",
        Msmsg: "msmsg",
      }),
      l = n("$InternalEnum")({
        Image: "image",
        Video: "video",
        Ptv: "ptv",
        Audio: "audio",
        Ptt: "ptt",
        Location: "location",
        VCard: "vcard",
        Document: "document",
        Url: "url",
        Call: "call",
        Gif: "gif",
        Future: "future",
        ContactArray: "contact_array",
        LiveLocation: "livelocation",
        ProfilePic: "profile_pic",
        Sticker: "sticker",
        StickerPack: "sticker_pack",
        Hsm: "hsm",
        ProductImage: "product_image",
        Template: "template",
        MdAppState: "md_app_state",
        MdHistorySync: "md_history_sync",
        List: "list",
        ListResponse: "list_response",
        Button: "button",
        ButtonResponse: "button_response",
        Order: "order",
        Product: "product",
        NativeFlowResponse: "native_flow_response",
        GroupHistory: "group_history",
      }),
      s = n("$InternalEnum")({ Hide: "hide", Show: "show" });
    ((i.CiphertextType = e), (i.EncMediaType = l), (i.DecryptFailType = s));
  },
  66,
);
