__d(
  "WAWebWamEnumUsernameCreationCurrentScreen",
  [],
  function (t, n, r, o, a, i) {
    var e = Object.freeze({
      USERNAME_MANAGE: 1,
      USERNAME_EDUCATION: 2,
      USERNAME_EDIT: 3,
      USERNAME_EDIT_OPTIONS: 4,
      USERNAME_DELETE_DIALOG: 5,
      USERNAME_COMPLETE: 6,
      USERNAME_PIN_EDUCATION: 7,
      USERNAME_PIN_UPSELL: 8,
      USERNAME_PIN_MANAGE: 9,
      USERNAME_PIN_EDIT: 10,
      USERNAME_PIN_DELETE_DIALOG: 11,
      BACKGROUND_NO_UI: 12,
      USE_EXISTING_FOA_USERNAME_VIA_LINK_UPSELL_BOTTOMSHEET: 13,
      USE_EXISTING_FOA_LINKED_USERNAMES_BOTTOMSHEET: 14,
      FOA_USERNAME_NOT_AVAILABLE_BOTTOMSHEET: 15,
      ACCOUNT_CENTER_HELP_ARTICLE: 16,
      FB_ACCOUNT_ALREADY_LINKED_DIALOG: 17,
    });
    i.USERNAME_CREATION_CURRENT_SCREEN = e;
  },
  66,
);
