__d(
  "WAWebStatusActionButtonStyles",
  [],
  function (t, n, r, o, a, i, l) {
    var e = {
      backgroundProtection: {
        alignItems: "x6s0dn4",
        backgroundColor: "x1honnu5",
        borderStartStartRadius: "xt8t1vi",
        borderStartEndRadius: "x1xc408v",
        borderEndEndRadius: "x129tdwq",
        borderEndStartRadius: "x15urzxu",
        display: "x78zum5",
        flexShrink: "x2lah0s",
        height: "x1vqgdyp",
        justifyContent: "xl56j7k",
        width: "x100vrsf",
        $$css: !0,
      },
      iconButton: {
        display: "x3nfvp2",
        alignItems: "x6s0dn4",
        justifyContent: "xl56j7k",
        alignSelf: "xpvyfi4",
        marginBottom: "xfitlp5",
        marginInlineStart: "x1j0eyxp",
        marginInlineEnd: "xcknrev",
        $$css: !0,
      },
      square26Svg: { height: "xd7y6wv", width: "x23j0i4", $$css: !0 },
      square26SvgCentered: {
        alignItems: "x6s0dn4",
        display: "x78zum5",
        justifyContent: "xl56j7k",
        $$css: !0,
      },
      bottomBarContainer: {
        position: "x10l6tqk",
        right: "x3m8u43",
        bottom: "xn0vg7t",
        left: "xu96u03",
        insetInlineStart: null,
        insetInlineEnd: null,
        zIndex: "x12xzxwr",
        width: "x19sv2k2",
        maxWidth: "x1kozois",
        marginInlineEnd: "x11t971q",
        marginInlineStart: "xvc5jky",
        paddingBottom: "x1a8lsjc",
        $$css: !0,
      },
      bottomBarRow: {
        display: "x78zum5",
        flexDirection: "x1q0g3np",
        justifyContent: "x13a6bvl",
        paddingTop: "x889kno",
        paddingInlineEnd: "x2vl965",
        paddingBottom: "x1a8lsjc",
        paddingInlineStart: "xe2zdcy",
        $$css: !0,
      },
    };
    l.statusActionButtonStyles = e;
  },
  98,
);
