__d(
  "WAWebWamEnumSettingsItemType",
  [],
  function (t, n, r, o, a, i) {
    var e = Object.freeze({
      PROFILE: 0,
      BUSINESS_TOOLS: 1,
      ACCOUNT: 2,
      CHATS: 3,
      NOTIFICATIONS: 4,
      DATA_STORAGE_USAGE: 5,
      HELP: 6,
      INVITE_FRIEND: 7,
      STARRED_MESSAGES: 8,
      WHATSAPP_WEB: 9,
      PREMIUM_SUBSCRIPTION: 10,
      PRIVACY: 11,
      SECURITY: 12,
      THEME: 13,
      CHAT_WALLPAPER: 14,
      MEDIA_AUTO_DOWNLOAD: 15,
      REQUEST_ACCOUNT_INFO: 16,
      KEYBOARD_SHORTCUTS: 17,
      DEVELOPER: 18,
      DATA_SHARING: 19,
      DESKTOP_SETTINGS: 20,
      LINKED_DEVICES: 21,
      UNKNOWN: 22,
      QR_CODE: 23,
      DEVICES: 24,
      PROFILE_CARD: 25,
      PRIVACY_CARD: 26,
      CONTACTS_CARD: 27,
      AVATAR: 28,
      PAYMENTS: 29,
      LOGOUT: 30,
      META_VERIFIED: 31,
      TEXT_STATUS: 32,
      THIRD_PARTY: 33,
      IG_BOOKMARK: 34,
      FB_BOOKMARK: 35,
      FAVORITES: 36,
      THREADS_BOOKMARK: 37,
      LISTS: 38,
      PROFILE_LINKS: 39,
      WAFFLE: 40,
      FEEDBACK: 41,
      META_AI_BOOKMARK: 42,
      META_HORIZON_BOOKMARK: 43,
      VIBES_BOOKMARK: 44,
      CONTACTS: 45,
      APPEARANCE: 46,
    });
    i.SETTINGS_ITEM_TYPE = e;
  },
  66,
);
