__d(
  "WAWebConsumerFetchQuickPromotionsQuery.graphql",
  ["WAWebConsumerFetchQuickPromotionsQuery_facebookRelayOperation"],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = (function () {
      var e = [
          { defaultValue: null, kind: "LocalArgument", name: "nux_ids" },
          {
            defaultValue: null,
            kind: "LocalArgument",
            name: "trigger_context",
          },
        ],
        t = [
          { kind: "Literal", name: "include_holdouts", value: !0 },
          { kind: "Literal", name: "supports_client_side_filters", value: !0 },
          {
            kind: "Variable",
            name: "surface_nux_ids",
            variableName: "nux_ids",
          },
          {
            kind: "Variable",
            name: "trigger_context",
            variableName: "trigger_context",
          },
        ],
        r = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "surface_nux_id",
          storageKey: null,
        },
        o = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "client_ttl_seconds",
          storageKey: null,
        },
        a = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "priority",
          storageKey: null,
        },
        i = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "is_holdout",
          storageKey: null,
        },
        l = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "log_eligibility_waterfall",
          storageKey: null,
        },
        s = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "start",
          storageKey: null,
        },
        u = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "end",
          storageKey: null,
        },
        c = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "promotion_id",
          storageKey: null,
        },
        d = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "is_server_force_pass",
          storageKey: null,
        },
        m = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "ab_prop_name",
          storageKey: null,
        },
        p = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "max_impressions",
          storageKey: null,
        },
        _ = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "surface_delay_in_seconds",
          storageKey: null,
        },
        f = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "encrypted_logging_data",
          storageKey: null,
        },
        g = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "client_side_dry_run",
          storageKey: null,
        },
        h = [
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "text",
            storageKey: null,
          },
        ],
        y = [
          {
            kind: "InlineDataFragmentSpread",
            name: "WAWebConsumerFetchQuickPromotionsQuery_QPText",
            selections: h,
            args: null,
            argumentDefinitions: [],
          },
        ],
        C = {
          alias: null,
          args: null,
          concreteType: "TextWithEntities",
          kind: "LinkedField",
          name: "title",
          plural: !1,
          selections: y,
          storageKey: null,
        },
        b = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "limit",
          storageKey: null,
        },
        v = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "url",
          storageKey: null,
        },
        S = [
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "jpeg_thumbnail",
            storageKey: null,
          },
        ],
        R = {
          alias: null,
          args: null,
          concreteType: "WAQPMediaDetails",
          kind: "LinkedField",
          name: "wa_light_mode_media_details",
          plural: !1,
          selections: S,
          storageKey: null,
        },
        L = {
          alias: null,
          args: null,
          concreteType: "WAQPMediaDetails",
          kind: "LinkedField",
          name: "wa_dark_mode_media_details",
          plural: !1,
          selections: S,
          storageKey: null,
        },
        E = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "accessibility_text_for_image",
          storageKey: null,
        },
        k = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "is_dismissible",
          storageKey: null,
        },
        I = {
          alias: null,
          args: null,
          concreteType: "QPContentAttributeDescriptor",
          kind: "LinkedField",
          name: "content_attributes",
          plural: !1,
          selections: [
            {
              alias: null,
              args: null,
              concreteType: "WhatsappQPColors",
              kind: "LinkedField",
              name: "wa_banner_background_color",
              plural: !1,
              selections: [
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "light_mode_highlight_color",
                  storageKey: null,
                },
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "dark_mode_highlight_color",
                  storageKey: null,
                },
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "light_mode_background_color",
                  storageKey: null,
                },
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "dark_mode_background_color",
                  storageKey: null,
                },
              ],
              storageKey: null,
            },
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "wa_primary_cta_alternative_url",
              storageKey: null,
            },
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "wa_eligible_duration_after_impression_in_seconds",
              storageKey: null,
            },
          ],
          storageKey: null,
        },
        T = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "value",
          storageKey: null,
        },
        D = {
          alias: null,
          args: null,
          concreteType: "WAQPContentAttribute",
          kind: "LinkedField",
          name: "wa_qp_content_attributes_do_not_use",
          plural: !0,
          selections: [
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "name",
              storageKey: null,
            },
            T,
          ],
          storageKey: null,
        },
        x = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "clause_type",
          storageKey: null,
        },
        $ = [
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "filter_name",
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            concreteType: "QPFilterParameter",
            kind: "LinkedField",
            name: "parameters",
            plural: !0,
            selections: [
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "key",
                storageKey: null,
              },
              T,
            ],
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "passes_if_client_not_supported",
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "filter_result",
            storageKey: null,
          },
        ],
        P = {
          kind: "InlineDataFragmentSpread",
          name: "WAWebConsumerFetchQuickPromotionsQuery_QPWAFilterClause",
          selections: [
            x,
            {
              alias: null,
              args: null,
              concreteType: "QuickPromotionFlattenedFilter",
              kind: "LinkedField",
              name: "filters",
              plural: !0,
              selections: [
                {
                  kind: "InlineDataFragmentSpread",
                  name: "WAWebConsumerFetchQuickPromotionsQuery_QPWAFilter",
                  selections: $,
                  args: null,
                  argumentDefinitions: [],
                },
              ],
              storageKey: null,
            },
          ],
          args: null,
          argumentDefinitions: [],
        },
        N = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "__typename",
          storageKey: null,
        },
        M = {
          alias: null,
          args: null,
          concreteType: "TextWithEntities",
          kind: "LinkedField",
          name: "title",
          plural: !1,
          selections: h,
          storageKey: null,
        },
        w = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "id",
          storageKey: null,
        },
        A = {
          alias: null,
          args: null,
          concreteType: "QuickPromotionFlattenedFilter",
          kind: "LinkedField",
          name: "filters",
          plural: !0,
          selections: $,
          storageKey: null,
        };
      return {
        fragment: {
          argumentDefinitions: e,
          kind: "Fragment",
          metadata: null,
          name: "WAWebConsumerFetchQuickPromotionsQuery",
          selections: [
            {
              alias: null,
              args: t,
              concreteType: "QuickPromotionMultiverseBatchFetchSurface",
              kind: "LinkedField",
              name: "quick_promotion_multiverse_batch_fetch_root",
              plural: !0,
              selections: [
                r,
                {
                  alias: null,
                  args: null,
                  concreteType:
                    "QuickPromotionMultiverseSurfaceEligiblePromotionsConnection",
                  kind: "LinkedField",
                  name: "eligible_promotions",
                  plural: !1,
                  selections: [
                    {
                      alias: null,
                      args: null,
                      concreteType:
                        "QuickPromotionMultiverseSurfaceEligiblePromotionsEdge",
                      kind: "LinkedField",
                      name: "edges",
                      plural: !0,
                      selections: [
                        {
                          kind: "RequiredField",
                          field: o,
                          action: "LOG",
                          path: "quick_promotion_multiverse_batch_fetch_root.eligible_promotions.edges.client_ttl_seconds",
                        },
                        {
                          kind: "RequiredField",
                          field: a,
                          action: "LOG",
                          path: "quick_promotion_multiverse_batch_fetch_root.eligible_promotions.edges.priority",
                        },
                        {
                          kind: "RequiredField",
                          field: i,
                          action: "LOG",
                          path: "quick_promotion_multiverse_batch_fetch_root.eligible_promotions.edges.is_holdout",
                        },
                        {
                          kind: "RequiredField",
                          field: l,
                          action: "LOG",
                          path: "quick_promotion_multiverse_batch_fetch_root.eligible_promotions.edges.log_eligibility_waterfall",
                        },
                        {
                          kind: "RequiredField",
                          field: {
                            alias: null,
                            args: null,
                            concreteType: "TimeRange",
                            kind: "LinkedField",
                            name: "time_range",
                            plural: !1,
                            selections: [
                              {
                                kind: "RequiredField",
                                field: s,
                                action: "LOG",
                                path: "quick_promotion_multiverse_batch_fetch_root.eligible_promotions.edges.time_range.start",
                              },
                              {
                                kind: "RequiredField",
                                field: u,
                                action: "LOG",
                                path: "quick_promotion_multiverse_batch_fetch_root.eligible_promotions.edges.time_range.end",
                              },
                            ],
                            storageKey: null,
                          },
                          action: "LOG",
                          path: "quick_promotion_multiverse_batch_fetch_root.eligible_promotions.edges.time_range",
                        },
                        {
                          alias: null,
                          args: null,
                          concreteType: null,
                          kind: "LinkedField",
                          name: "node",
                          plural: !1,
                          selections: [
                            {
                              kind: "InlineDataFragmentSpread",
                              name: "WAWebConsumerFetchQuickPromotionsQuery_QuickPromotion",
                              selections: [
                                c,
                                d,
                                m,
                                p,
                                _,
                                f,
                                g,
                                {
                                  alias: null,
                                  args: null,
                                  concreteType: null,
                                  kind: "LinkedField",
                                  name: "creatives",
                                  plural: !0,
                                  selections: [
                                    {
                                      kind: "InlineDataFragmentSpread",
                                      name: "WAWebConsumerFetchQuickPromotionsQuery_QPCreative",
                                      selections: [
                                        C,
                                        {
                                          alias: null,
                                          args: null,
                                          concreteType: "TextWithEntities",
                                          kind: "LinkedField",
                                          name: "content",
                                          plural: !1,
                                          selections: y,
                                          storageKey: null,
                                        },
                                        {
                                          alias: null,
                                          args: null,
                                          concreteType: null,
                                          kind: "LinkedField",
                                          name: "primary_action",
                                          plural: !1,
                                          selections: [
                                            {
                                              kind: "InlineDataFragmentSpread",
                                              name: "WAWebConsumerFetchQuickPromotionsQuery_QPAction",
                                              selections: [C, b, v],
                                              args: null,
                                              argumentDefinitions: [],
                                            },
                                          ],
                                          storageKey: null,
                                        },
                                        {
                                          alias: null,
                                          args: null,
                                          concreteType: null,
                                          kind: "LinkedField",
                                          name: "dismiss_action",
                                          plural: !1,
                                          selections: [b],
                                          storageKey: null,
                                        },
                                        R,
                                        L,
                                        E,
                                        k,
                                      ],
                                      args: null,
                                      argumentDefinitions: [],
                                    },
                                  ],
                                  storageKey: null,
                                },
                                I,
                                D,
                                {
                                  alias: null,
                                  args: null,
                                  concreteType:
                                    "QuickPromotionFlattenedFilterClause",
                                  kind: "LinkedField",
                                  name: "contextual_filters_for_wa_do_not_use",
                                  plural: !1,
                                  selections: [
                                    P,
                                    {
                                      alias: null,
                                      args: null,
                                      concreteType:
                                        "QuickPromotionFlattenedFilterClause",
                                      kind: "LinkedField",
                                      name: "clauses",
                                      plural: !0,
                                      selections: [
                                        P,
                                        {
                                          alias: null,
                                          args: null,
                                          concreteType:
                                            "QuickPromotionFlattenedFilterClause",
                                          kind: "LinkedField",
                                          name: "clauses",
                                          plural: !0,
                                          selections: [
                                            P,
                                            {
                                              alias: null,
                                              args: null,
                                              concreteType:
                                                "QuickPromotionFlattenedFilterClause",
                                              kind: "LinkedField",
                                              name: "clauses",
                                              plural: !0,
                                              selections: [P],
                                              storageKey: null,
                                            },
                                          ],
                                          storageKey: null,
                                        },
                                      ],
                                      storageKey: null,
                                    },
                                  ],
                                  storageKey: null,
                                },
                              ],
                              args: null,
                              argumentDefinitions: [],
                            },
                          ],
                          storageKey: null,
                        },
                      ],
                      storageKey: null,
                    },
                  ],
                  storageKey: null,
                },
              ],
              storageKey: null,
            },
          ],
          type: "Query",
          abstractKey: null,
        },
        kind: "Request",
        operation: {
          argumentDefinitions: e,
          kind: "Operation",
          name: "WAWebConsumerFetchQuickPromotionsQuery",
          selections: [
            {
              alias: null,
              args: t,
              concreteType: "QuickPromotionMultiverseBatchFetchSurface",
              kind: "LinkedField",
              name: "quick_promotion_multiverse_batch_fetch_root",
              plural: !0,
              selections: [
                r,
                {
                  alias: null,
                  args: null,
                  concreteType:
                    "QuickPromotionMultiverseSurfaceEligiblePromotionsConnection",
                  kind: "LinkedField",
                  name: "eligible_promotions",
                  plural: !1,
                  selections: [
                    {
                      alias: null,
                      args: null,
                      concreteType:
                        "QuickPromotionMultiverseSurfaceEligiblePromotionsEdge",
                      kind: "LinkedField",
                      name: "edges",
                      plural: !0,
                      selections: [
                        o,
                        a,
                        i,
                        l,
                        {
                          alias: null,
                          args: null,
                          concreteType: "TimeRange",
                          kind: "LinkedField",
                          name: "time_range",
                          plural: !1,
                          selections: [s, u],
                          storageKey: null,
                        },
                        {
                          alias: null,
                          args: null,
                          concreteType: null,
                          kind: "LinkedField",
                          name: "node",
                          plural: !1,
                          selections: [
                            N,
                            {
                              kind: "TypeDiscriminator",
                              abstractKey: "__isQuickPromotionInterface",
                            },
                            c,
                            d,
                            m,
                            p,
                            _,
                            f,
                            g,
                            {
                              alias: null,
                              args: null,
                              concreteType: null,
                              kind: "LinkedField",
                              name: "creatives",
                              plural: !0,
                              selections: [
                                N,
                                {
                                  kind: "TypeDiscriminator",
                                  abstractKey:
                                    "__isQuickPromotionCreativeInterface",
                                },
                                M,
                                {
                                  alias: null,
                                  args: null,
                                  concreteType: "TextWithEntities",
                                  kind: "LinkedField",
                                  name: "content",
                                  plural: !1,
                                  selections: h,
                                  storageKey: null,
                                },
                                {
                                  alias: null,
                                  args: null,
                                  concreteType: null,
                                  kind: "LinkedField",
                                  name: "primary_action",
                                  plural: !1,
                                  selections: [
                                    N,
                                    {
                                      kind: "TypeDiscriminator",
                                      abstractKey:
                                        "__isQuickPromotionActionInterface",
                                    },
                                    M,
                                    b,
                                    v,
                                  ],
                                  storageKey: null,
                                },
                                {
                                  alias: null,
                                  args: null,
                                  concreteType: null,
                                  kind: "LinkedField",
                                  name: "dismiss_action",
                                  plural: !1,
                                  selections: [N, b],
                                  storageKey: null,
                                },
                                R,
                                L,
                                E,
                                k,
                                {
                                  kind: "InlineFragment",
                                  selections: [w],
                                  type: "Node",
                                  abstractKey: "__isNode",
                                },
                              ],
                              storageKey: null,
                            },
                            I,
                            D,
                            {
                              alias: null,
                              args: null,
                              concreteType:
                                "QuickPromotionFlattenedFilterClause",
                              kind: "LinkedField",
                              name: "contextual_filters_for_wa_do_not_use",
                              plural: !1,
                              selections: [
                                x,
                                A,
                                {
                                  alias: null,
                                  args: null,
                                  concreteType:
                                    "QuickPromotionFlattenedFilterClause",
                                  kind: "LinkedField",
                                  name: "clauses",
                                  plural: !0,
                                  selections: [
                                    x,
                                    A,
                                    {
                                      alias: null,
                                      args: null,
                                      concreteType:
                                        "QuickPromotionFlattenedFilterClause",
                                      kind: "LinkedField",
                                      name: "clauses",
                                      plural: !0,
                                      selections: [
                                        x,
                                        A,
                                        {
                                          alias: null,
                                          args: null,
                                          concreteType:
                                            "QuickPromotionFlattenedFilterClause",
                                          kind: "LinkedField",
                                          name: "clauses",
                                          plural: !0,
                                          selections: [x, A],
                                          storageKey: null,
                                        },
                                      ],
                                      storageKey: null,
                                    },
                                  ],
                                  storageKey: null,
                                },
                              ],
                              storageKey: null,
                            },
                            w,
                          ],
                          storageKey: null,
                        },
                      ],
                      storageKey: null,
                    },
                  ],
                  storageKey: null,
                },
              ],
              storageKey: null,
            },
          ],
        },
        params: {
          id: n(
            "WAWebConsumerFetchQuickPromotionsQuery_facebookRelayOperation",
          ),
          metadata: {},
          name: "WAWebConsumerFetchQuickPromotionsQuery",
          operationKind: "query",
          text: null,
        },
      };
    })();
    a.exports = e;
  },
  null,
);
