__d(
  "WAWebStatusImgStyles",
  [],
  function (t, n, r, o, a, i, l) {
    var e = {
      actionLink: {
        position: "x10l6tqk",
        bottom: "x1kiq0my",
        display: "x78zum5",
        alignItems: "x6s0dn4",
        justifyContent: "xl56j7k",
        width: "xh8yej3",
        $$css: !0,
      },
      mediaViewer: {
        position: "x1n2onr6",
        width: "xh8yej3",
        height: "x5yr21d",
        overflowX: "x6ikm8r",
        overflowY: "x10wlt62",
        borderStartStartRadius: "xyi3aci",
        borderStartEndRadius: "xwf5gio",
        borderEndEndRadius: "x1p453bz",
        borderEndStartRadius: "x1suzm8a",
        $$css: !0,
      },
      playerContent: {
        position: "x10l6tqk",
        top: "x13vifvy",
        insetInlineStart: "x1o0tod",
        left: null,
        right: null,
        width: "xh8yej3",
        height: "x5yr21d",
        $$css: !0,
      },
      thumbnailImage: {
        display: "x1lliihq",
        width: "xh8yej3",
        height: "x5yr21d",
        objectFit: "xl1xv1r",
        borderStartStartRadius: "xyi3aci",
        borderStartEndRadius: "xwf5gio",
        borderEndEndRadius: "x1p453bz",
        borderEndStartRadius: "x1suzm8a",
        $$css: !0,
      },
      v3Image: {
        position: "x1n2onr6",
        display: "x1lliihq",
        height: "x5yr21d",
        marginInlineEnd: "x11t971q",
        marginInlineStart: "xvc5jky",
        borderStartStartRadius: "xyi3aci",
        borderStartEndRadius: "xwf5gio",
        borderEndEndRadius: "x1p453bz",
        borderEndStartRadius: "x1suzm8a",
        $$css: !0,
      },
    };
    l.statusImgStyles = e;
  },
  98,
);
