__d(
  "WAWebProtobufsAICommonDeprecated.pb",
  ["$InternalEnum", "WAProtoConst"],
  function (t, n, r, o, a, i, l) {
    var e,
      s,
      u = (s = n("$InternalEnum"))({
        AI_RICH_RESPONSE_TYPE_UNKNOWN: 0,
        AI_RICH_RESPONSE_TYPE_STANDARD: 1,
      }),
      c = s({
        AI_RICH_RESPONSE_UNKNOWN: 0,
        AI_RICH_RESPONSE_GRID_IMAGE: 1,
        AI_RICH_RESPONSE_TEXT: 2,
        AI_RICH_RESPONSE_INLINE_IMAGE: 3,
        AI_RICH_RESPONSE_TABLE: 4,
        AI_RICH_RESPONSE_CODE: 5,
        AI_RICH_RESPONSE_DYNAMIC: 6,
        AI_RICH_RESPONSE_MAP: 7,
        AI_RICH_RESPONSE_LATEX: 8,
        AI_RICH_RESPONSE_CONTENT_ITEMS: 9,
      }),
      d = s({
        AI_RICH_RESPONSE_IMAGE_LAYOUT_LEADING_ALIGNED: 0,
        AI_RICH_RESPONSE_IMAGE_LAYOUT_TRAILING_ALIGNED: 1,
        AI_RICH_RESPONSE_IMAGE_LAYOUT_CENTER_ALIGNED: 2,
      }),
      m = s({
        AI_RICH_RESPONSE_CODE_HIGHLIGHT_DEFAULT: 0,
        AI_RICH_RESPONSE_CODE_HIGHLIGHT_KEYWORD: 1,
        AI_RICH_RESPONSE_CODE_HIGHLIGHT_METHOD: 2,
        AI_RICH_RESPONSE_CODE_HIGHLIGHT_STRING: 3,
        AI_RICH_RESPONSE_CODE_HIGHLIGHT_NUMBER: 4,
        AI_RICH_RESPONSE_CODE_HIGHLIGHT_COMMENT: 5,
      }),
      p = s({
        AI_RICH_RESPONSE_DYNAMIC_METADATA_TYPE_UNKNOWN: 0,
        AI_RICH_RESPONSE_DYNAMIC_METADATA_TYPE_IMAGE: 1,
        AI_RICH_RESPONSE_DYNAMIC_METADATA_TYPE_GIF: 2,
      }),
      _ = s({ DEFAULT: 0, CAROUSEL: 1 }),
      f = {},
      g = {},
      h = {},
      y = {},
      C = {},
      b = {},
      v = {},
      S = {},
      R = {},
      L = {},
      E = {},
      k = {},
      I = {},
      T = {},
      D = {},
      x = {};
    ((f.name = "AIRichResponseImageURL"),
      (f.internalSpec = {
        imagePreviewUrl: [1, (e = o("WAProtoConst")).TYPES.STRING],
        imageHighResUrl: [2, e.TYPES.STRING],
        sourceUrl: [3, e.TYPES.STRING],
      }),
      (g.name = "AIRichResponseGridImageMetadata"),
      (g.internalSpec = {
        gridImageUrl: [1, e.TYPES.MESSAGE, f],
        imageUrls: [2, e.FLAGS.REPEATED | e.TYPES.MESSAGE, f],
      }),
      (h.name = "AIRichResponseInlineImageMetadata"),
      (h.internalSpec = {
        imageUrl: [1, e.TYPES.MESSAGE, f],
        imageText: [2, e.TYPES.STRING],
        alignment: [3, e.TYPES.ENUM, d],
        tapLinkUrl: [4, e.TYPES.STRING],
      }),
      (y.name = "AIRichResponseCodeMetadata"),
      (y.internalSpec = {
        codeLanguage: [1, e.TYPES.STRING],
        codeBlocks: [2, e.FLAGS.REPEATED | e.TYPES.MESSAGE, C],
      }),
      (C.name = "AIRichResponseCodeMetadata$AIRichResponseCodeBlock"),
      (C.internalSpec = {
        highlightType: [1, e.TYPES.ENUM, m],
        codeContent: [2, e.TYPES.STRING],
      }),
      (b.name = "AIRichResponseTableMetadata"),
      (b.internalSpec = {
        rows: [1, e.FLAGS.REPEATED | e.TYPES.MESSAGE, v],
        title: [2, e.TYPES.STRING],
      }),
      (v.name = "AIRichResponseTableMetadata$AIRichResponseTableRow"),
      (v.internalSpec = {
        items: [1, e.FLAGS.REPEATED | e.TYPES.STRING],
        isHeading: [2, e.TYPES.BOOL],
      }),
      (S.name = "AIRichResponseDynamicMetadata"),
      (S.internalSpec = {
        type: [1, e.TYPES.ENUM, p],
        version: [2, e.TYPES.UINT64],
        url: [3, e.TYPES.STRING],
        loopCount: [4, e.TYPES.UINT32],
      }),
      (R.name = "AIRichResponseLatexMetadata"),
      (R.internalSpec = {
        text: [1, e.TYPES.STRING],
        expressions: [2, e.FLAGS.REPEATED | e.TYPES.MESSAGE, L],
      }),
      (L.name = "AIRichResponseLatexMetadata$AIRichResponseLatexExpression"),
      (L.internalSpec = {
        latexExpression: [1, e.TYPES.STRING],
        url: [2, e.TYPES.STRING],
        width: [3, e.TYPES.DOUBLE],
        height: [4, e.TYPES.DOUBLE],
        fontHeight: [5, e.TYPES.DOUBLE],
        imageTopPadding: [6, e.TYPES.DOUBLE],
        imageLeadingPadding: [7, e.TYPES.DOUBLE],
        imageBottomPadding: [8, e.TYPES.DOUBLE],
        imageTrailingPadding: [9, e.TYPES.DOUBLE],
      }),
      (E.name = "AIRichResponseMapMetadata"),
      (E.internalSpec = {
        centerLatitude: [1, e.TYPES.DOUBLE],
        centerLongitude: [2, e.TYPES.DOUBLE],
        latitudeDelta: [3, e.TYPES.DOUBLE],
        longitudeDelta: [4, e.TYPES.DOUBLE],
        annotations: [5, e.FLAGS.REPEATED | e.TYPES.MESSAGE, k],
        showInfoList: [6, e.TYPES.BOOL],
      }),
      (k.name = "AIRichResponseMapMetadata$AIRichResponseMapAnnotation"),
      (k.internalSpec = {
        annotationNumber: [1, e.TYPES.UINT32],
        latitude: [2, e.TYPES.DOUBLE],
        longitude: [3, e.TYPES.DOUBLE],
        title: [4, e.TYPES.STRING],
        body: [5, e.TYPES.STRING],
      }),
      (I.name = "AIRichResponseContentItemsMetadata"),
      (I.internalSpec = {
        itemsMetadata: [1, e.FLAGS.REPEATED | e.TYPES.MESSAGE, T],
        contentType: [2, e.TYPES.ENUM, _],
      }),
      (T.name =
        "AIRichResponseContentItemsMetadata$AIRichResponseContentItemMetadata"),
      (T.internalSpec = {
        reelItem: [1, e.TYPES.MESSAGE, D],
        __oneofs__: { aIRichResponseContentItem: ["reelItem"] },
      }),
      (D.name = "AIRichResponseContentItemsMetadata$AIRichResponseReelItem"),
      (D.internalSpec = {
        title: [1, e.TYPES.STRING],
        profileIconUrl: [2, e.TYPES.STRING],
        thumbnailUrl: [3, e.TYPES.STRING],
        videoUrl: [4, e.TYPES.STRING],
      }),
      (x.name = "AIRichResponseSubMessage"),
      (x.internalSpec = {
        messageType: [1, e.TYPES.ENUM, c],
        gridImageMetadata: [2, e.TYPES.MESSAGE, g],
        messageText: [3, e.TYPES.STRING],
        imageMetadata: [4, e.TYPES.MESSAGE, h],
        codeMetadata: [5, e.TYPES.MESSAGE, y],
        tableMetadata: [6, e.TYPES.MESSAGE, b],
        dynamicMetadata: [7, e.TYPES.MESSAGE, S],
        latexMetadata: [8, e.TYPES.MESSAGE, R],
        mapMetadata: [9, e.TYPES.MESSAGE, E],
        contentItemsMetadata: [10, e.TYPES.MESSAGE, I],
      }),
      (l.AIRichResponseMessageType = u),
      (l.AIRichResponseSubMessageType = c),
      (l.AIRichResponseInlineImageMetadata$AIRichResponseImageAlignment = d),
      (l.AIRichResponseCodeMetadata$AIRichResponseCodeHighlightType = m),
      (l.AIRichResponseDynamicMetadata$AIRichResponseDynamicMetadataType = p),
      (l.AIRichResponseContentItemsMetadata$ContentType = _),
      (l.AIRichResponseImageURLSpec = f),
      (l.AIRichResponseGridImageMetadataSpec = g),
      (l.AIRichResponseInlineImageMetadataSpec = h),
      (l.AIRichResponseCodeMetadataSpec = y),
      (l.AIRichResponseCodeMetadata$AIRichResponseCodeBlockSpec = C),
      (l.AIRichResponseTableMetadataSpec = b),
      (l.AIRichResponseTableMetadata$AIRichResponseTableRowSpec = v),
      (l.AIRichResponseDynamicMetadataSpec = S),
      (l.AIRichResponseLatexMetadataSpec = R),
      (l.AIRichResponseLatexMetadata$AIRichResponseLatexExpressionSpec = L),
      (l.AIRichResponseMapMetadataSpec = E),
      (l.AIRichResponseMapMetadata$AIRichResponseMapAnnotationSpec = k),
      (l.AIRichResponseContentItemsMetadataSpec = I),
      (l.AIRichResponseContentItemsMetadata$AIRichResponseContentItemMetadataSpec =
        T),
      (l.AIRichResponseContentItemsMetadata$AIRichResponseReelItemSpec = D),
      (l.AIRichResponseSubMessageSpec = x));
  },
  98,
);
