__d(
  "WAWebBizAiAppointmentConnectorsQuery.graphql",
  ["WAWebBizAiAppointmentConnectorsQuery_facebookRelayOperation"],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = (function () {
      var e = [{ defaultValue: null, kind: "LocalArgument", name: "locale" }],
        t = [
          { kind: "Literal", name: "product_category", value: "APPOINTMENTS" },
          { kind: "Literal", name: "surface", value: "WHATSAPP" },
        ],
        r = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "is_connected",
          storageKey: null,
        },
        o = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "integration_config_id",
          storageKey: null,
        },
        a = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "connection_status",
          storageKey: null,
        },
        i = {
          alias: "pluginType",
          args: null,
          kind: "ScalarField",
          name: "__typename",
          storageKey: null,
        },
        l = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "id",
          storageKey: null,
        },
        s = [{ kind: "Variable", name: "locale", variableName: "locale" }],
        u = {
          alias: null,
          args: s,
          kind: "ScalarField",
          name: "display_name",
          storageKey: null,
        },
        c = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "description",
          storageKey: null,
        },
        d = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "name",
          storageKey: null,
        },
        m = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "apixfn_plugin",
          storageKey: null,
        },
        p = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "auth_type",
          storageKey: null,
        },
        _ = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "oauth_type",
          storageKey: null,
        },
        f = {
          alias: null,
          args: s,
          kind: "ScalarField",
          name: "title",
          storageKey: null,
        },
        g = {
          alias: null,
          args: s,
          kind: "ScalarField",
          name: "title_subtext",
          storageKey: null,
        },
        h = [
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "uri",
            storageKey: null,
          },
        ],
        y = {
          alias: null,
          args: null,
          concreteType: "Image",
          kind: "LinkedField",
          name: "logo",
          plural: !1,
          selections: h,
          storageKey: null,
        },
        C = {
          alias: null,
          args: null,
          concreteType: "Image",
          kind: "LinkedField",
          name: "logo_dark_mode",
          plural: !1,
          selections: h,
          storageKey: null,
        },
        b = {
          alias: null,
          args: null,
          concreteType: "PluginProductCategory",
          kind: "LinkedField",
          name: "product_categories",
          plural: !0,
          selections: [
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "product_category",
              storageKey: null,
            },
          ],
          storageKey: null,
        },
        v = {
          alias: null,
          args: s,
          concreteType: "PluginTemplateRendering",
          kind: "LinkedField",
          name: "template_rendering",
          plural: !1,
          selections: [
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "template_type",
              storageKey: null,
            },
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "footer_text_markdown",
              storageKey: null,
            },
            {
              alias: null,
              args: null,
              concreteType: "PluginValueProp",
              kind: "LinkedField",
              name: "value_props",
              plural: !0,
              selections: [
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "glyph_name",
                  storageKey: null,
                },
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "text_markdown",
                  storageKey: null,
                },
              ],
              storageKey: null,
            },
            {
              alias: null,
              args: null,
              concreteType: "FormInstructions",
              kind: "LinkedField",
              name: "form_instructions",
              plural: !1,
              selections: [
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "title",
                  storageKey: null,
                },
                {
                  alias: null,
                  args: null,
                  concreteType: "FormInstruction",
                  kind: "LinkedField",
                  name: "instructions",
                  plural: !0,
                  selections: [
                    {
                      alias: null,
                      args: null,
                      kind: "ScalarField",
                      name: "type",
                      storageKey: null,
                    },
                    {
                      alias: null,
                      args: null,
                      kind: "ScalarField",
                      name: "markdown",
                      storageKey: null,
                    },
                  ],
                  storageKey: null,
                },
              ],
              storageKey: null,
            },
          ],
          storageKey: null,
        },
        S = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "key",
          storageKey: null,
        },
        R = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "help_link",
          storageKey: null,
        },
        L = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "label",
          storageKey: null,
        },
        E = {
          alias: null,
          args: s,
          concreteType: "XFBKeyDescriptionType",
          kind: "LinkedField",
          name: "authorization_params",
          plural: !0,
          selections: [
            S,
            c,
            R,
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "param_type",
              storageKey: null,
            },
            L,
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "label_description",
              storageKey: null,
            },
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "placeholder_text",
              storageKey: null,
            },
            {
              alias: null,
              args: null,
              concreteType: "XFBBizAIAuthParamOption",
              kind: "LinkedField",
              name: "options",
              plural: !0,
              selections: [
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "value",
                  storageKey: null,
                },
                L,
              ],
              storageKey: null,
            },
          ],
          storageKey: null,
        },
        k = {
          alias: null,
          args: null,
          concreteType: "XFBKeyDescriptionType",
          kind: "LinkedField",
          name: "template_variables_url",
          plural: !0,
          selections: [S, c, R],
          storageKey: null,
        },
        I = {
          kind: "InlineFragment",
          selections: [
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "auth_option_key",
              storageKey: null,
            },
          ],
          type: "XFBBizAIIntegrationMembranePlugin",
          abstractKey: null,
        };
      return {
        fragment: {
          argumentDefinitions: e,
          kind: "Fragment",
          metadata: null,
          name: "WAWebBizAiAppointmentConnectorsQuery",
          selections: [
            {
              alias: null,
              args: t,
              concreteType: "MetaAIBizAgentWAPluginsForSurfaceResponse",
              kind: "LinkedField",
              name: "meta_ai_biz_agent_wa_plugins_for_surface",
              plural: !1,
              selections: [
                {
                  alias: null,
                  args: null,
                  concreteType: "MetaAIBizAgentWAPluginConnectionStatus",
                  kind: "LinkedField",
                  name: "plugins",
                  plural: !0,
                  selections: [
                    {
                      kind: "InlineDataFragmentSpread",
                      name: "WAWebBizAiAppointmentConnectorsQuery_connectorEntry",
                      selections: [
                        r,
                        o,
                        a,
                        {
                          alias: null,
                          args: null,
                          concreteType: null,
                          kind: "LinkedField",
                          name: "plugin",
                          plural: !1,
                          selections: [
                            i,
                            l,
                            u,
                            c,
                            d,
                            m,
                            p,
                            {
                              alias: null,
                              args: null,
                              concreteType: "BizAIPluginOAuthConfig",
                              kind: "LinkedField",
                              name: "oauth_config",
                              plural: !1,
                              selections: [_],
                              storageKey: null,
                            },
                            f,
                            g,
                            y,
                            C,
                            b,
                            v,
                            E,
                            k,
                            I,
                          ],
                          storageKey: null,
                        },
                      ],
                      args: s,
                      argumentDefinitions: e,
                    },
                  ],
                  storageKey: null,
                },
              ],
              storageKey:
                'meta_ai_biz_agent_wa_plugins_for_surface(product_category:"APPOINTMENTS",surface:"WHATSAPP")',
            },
          ],
          type: "Query",
          abstractKey: null,
        },
        kind: "Request",
        operation: {
          argumentDefinitions: e,
          kind: "Operation",
          name: "WAWebBizAiAppointmentConnectorsQuery",
          selections: [
            {
              alias: null,
              args: t,
              concreteType: "MetaAIBizAgentWAPluginsForSurfaceResponse",
              kind: "LinkedField",
              name: "meta_ai_biz_agent_wa_plugins_for_surface",
              plural: !1,
              selections: [
                {
                  alias: null,
                  args: null,
                  concreteType: "MetaAIBizAgentWAPluginConnectionStatus",
                  kind: "LinkedField",
                  name: "plugins",
                  plural: !0,
                  selections: [
                    r,
                    o,
                    a,
                    {
                      alias: null,
                      args: null,
                      concreteType: null,
                      kind: "LinkedField",
                      name: "plugin",
                      plural: !1,
                      selections: [
                        {
                          alias: null,
                          args: null,
                          kind: "ScalarField",
                          name: "__typename",
                          storageKey: null,
                        },
                        i,
                        l,
                        u,
                        c,
                        d,
                        m,
                        p,
                        {
                          alias: null,
                          args: null,
                          concreteType: "BizAIPluginOAuthConfig",
                          kind: "LinkedField",
                          name: "oauth_config",
                          plural: !1,
                          selections: [_, l],
                          storageKey: null,
                        },
                        f,
                        g,
                        y,
                        C,
                        b,
                        v,
                        E,
                        k,
                        I,
                      ],
                      storageKey: null,
                    },
                  ],
                  storageKey: null,
                },
              ],
              storageKey:
                'meta_ai_biz_agent_wa_plugins_for_surface(product_category:"APPOINTMENTS",surface:"WHATSAPP")',
            },
          ],
        },
        params: {
          id: n("WAWebBizAiAppointmentConnectorsQuery_facebookRelayOperation"),
          metadata: {},
          name: "WAWebBizAiAppointmentConnectorsQuery",
          operationKind: "query",
          text: null,
        },
      };
    })();
    a.exports = e;
  },
  null,
);
