__d(
  "WAWebQbmMessageReadWamEvent",
  [
    "WAWebWamCodegenUtils",
    "WAWebWamEnumChatsFolderType",
    "WAWebWamEnumContactType",
    "WAWebWamEnumQbmFlag",
    "WAWebWamEnumReadSource",
    "WAWebWamEnumSignupEntryPoint",
    "WAWebWamEnumThreadCreationTime",
    "WAWebWamEnumThumbnailType",
  ],
  function (t, n, r, o, a, i, l) {
    var e,
      s = (e = o("WAWebWamCodegenUtils")).defineEvents(
        {
          QbmMessageRead: [
            3792,
            {
              apiDailyThreadCount7d: [18, e.TYPES.INTEGER],
              apiMessageCount1d: [19, e.TYPES.INTEGER],
              apiMessageCount7d: [20, e.TYPES.INTEGER],
              apiTotalMessageCount: [23, e.TYPES.INTEGER],
              apiTotalNewThreadCount: [24, e.TYPES.INTEGER],
              apiUniqueThreadCount1d: [21, e.TYPES.INTEGER],
              apiUniqueThreadCount7d: [22, e.TYPES.INTEGER],
              bizTrustTier: [34, e.TYPES.STRING],
              bodyUrlCountInt: [51, e.TYPES.INTEGER],
              bodyUrlUniqueCountInt: [52, e.TYPES.INTEGER],
              buttonValueJsonArray: [44, e.TYPES.STRING],
              chatsFolderType: [
                1,
                o("WAWebWamEnumChatsFolderType").CHATS_FOLDER_TYPE,
              ],
              companionDevices: [41, e.TYPES.INTEGER],
              contactType: [2, o("WAWebWamEnumContactType").CONTACT_TYPE],
              ctaUrlUniqueCountInt: [53, e.TYPES.INTEGER],
              decisionId: [40, e.TYPES.STRING],
              deltaTime: [3, e.TYPES.INTEGER],
              deltaTimeReceived: [8, e.TYPES.INTEGER],
              entSourceSubplatform: [39, e.TYPES.STRING],
              hsmTagStr: [9, e.TYPES.STRING],
              iasEntryPoint: [
                57,
                o("WAWebWamEnumSignupEntryPoint").SIGNUP_ENTRY_POINT,
              ],
              iasOptinDs: [58, e.TYPES.STRING],
              isBizIntent: [37, e.TYPES.BOOLEAN],
              isBroadcastMessage: [38, e.TYPES.BOOLEAN],
              isBulkAction: [14, e.TYPES.BOOLEAN],
              isCoex: [55, e.TYPES.BOOLEAN],
              isFromAdsManagerMm: [10, e.TYPES.BOOLEAN],
              isFromCapi: [11, e.TYPES.BOOLEAN],
              isIasSubscriber: [59, e.TYPES.BOOLEAN],
              isInsubContact: [35, e.TYPES.BOOLEAN],
              isMuted: [15, e.TYPES.BOOLEAN],
              isOba: [43, e.TYPES.BOOLEAN],
              isThroughDecisionService: [56, e.TYPES.BOOLEAN],
              messageFieldJsonArray: [45, e.TYPES.STRING],
              messageHasButton: [16, e.TYPES.BOOLEAN],
              messageHasUrl: [17, e.TYPES.BOOLEAN],
              messageIdHmac: [13, e.TYPES.STRING],
              messageTypeStr: [6, e.TYPES.STRING],
              qbmFlag: [4, o("WAWebWamEnumQbmFlag").QBM_FLAG],
              readReceiptsEnabled: [12, e.TYPES.BOOLEAN],
              readSource: [5, o("WAWebWamEnumReadSource").READ_SOURCE],
              smbDailyThreadCount7d: [25, e.TYPES.INTEGER],
              smbMessageCount1d: [26, e.TYPES.INTEGER],
              smbMessageCount7d: [27, e.TYPES.INTEGER],
              smbTotalMessageCount: [28, e.TYPES.INTEGER],
              smbTotalNewThreadCount: [29, e.TYPES.INTEGER],
              smbUniqueThreadCount1d: [30, e.TYPES.INTEGER],
              smbUniqueThreadCount7d: [31, e.TYPES.INTEGER],
              submessageFieldJsonArray: [46, e.TYPES.STRING],
              threadCreationTime: [
                32,
                o("WAWebWamEnumThreadCreationTime").THREAD_CREATION_TIME,
              ],
              threadDwellTime: [33, e.TYPES.INTEGER],
              threadIdHmac: [7, e.TYPES.STRING],
              threadLidHmac: [42, e.TYPES.STRING],
              thumbnailType: [
                36,
                o("WAWebWamEnumThumbnailType").THUMBNAIL_TYPE,
              ],
              urlUniqueCountInt: [54, e.TYPES.INTEGER],
            },
            [1, 1, 1],
            "regular",
          ],
        },
        { QbmMessageRead: [] },
      );
    l.QbmMessageReadWamEvent = s;
  },
  98,
);
