__d(
  "WAWebWamEnumPrivacyControlItemType",
  [],
  function (t, n, r, o, a, i) {
    var e = Object.freeze({
      LAST_SEEN_AND_ONLINE: 0,
      PROFILE_PHOTO: 1,
      ABOUT: 2,
      GROUPS: 3,
      STATUS: 4,
      READ_RECEIPT: 5,
      BLOCKED: 6,
      LIVE_LOCATION: 7,
      SCREEN_LOCK: 8,
      DDM_TIMER: 9,
      CALLS: 10,
      FINGERPRINT_LOCK: 11,
      DISAPPEARING_MESSAGES: 12,
      UNKNOWN: 13,
      CHECKUP: 14,
      SHOW_PREVIEW: 15,
      E2EE_BACKUPS: 16,
      TWO_STEP_VERIFICATION: 17,
      FACE_AND_HAND_EFFECTS: 18,
      ADVANCED: 19,
      CHAT_LOCK: 20,
      AVATAR: 21,
      CONTACTS: 22,
      PRIVACY_CHECKUP: 23,
      PIX: 24,
      DEFENSE_MODE: 25,
      PROFILE_LINKS: 26,
      PASSKEY: 27,
      EMAIL: 28,
      CHANNELS: 29,
      COVER_PHOTO: 30,
      GROUP_CREATION: 31,
    });
    i.PRIVACY_CONTROL_ITEM_TYPE = e;
  },
  66,
);
