__d(
  "WAWebTeeEnums",
  ["$InternalEnum"],
  function (t, n, r, o, a, i) {
    var e,
      l = (e = n("$InternalEnum"))({
        DEFAULT: 0,
        TEXT: 1,
        IMAGE: 2,
        VIDEO: 3,
        AUDIO: 4,
        CONTACT: 5,
        LOCATION: 6,
        LINK: 7,
        DOCUMENT: 8,
        GIF: 9,
        STICKER: 10,
        PAYMENT_REQUEST: 11,
        POLL: 12,
        EVENT: 13,
        MEDIA_ALBUM: 14,
        PRODUCT: 15,
        PTT: 16,
        REQUEST_WELCOME_MESSAGE: 17,
        REACTION: 18,
      }),
      s = e({
        SUCCESS: 0,
        FAILED_LOW_CONFIDENCE: 1,
        FAILED_TOO_MANY_TOKENS: 2,
        IN_PROGRESS: 3,
        FAILED_VIOLATION: 4,
        FAILED_UNKNOWN: 5,
        SUCCESS_NO_RESPONSE: 6,
        SUCCESS_RATE_LIMITED: 7,
        FAILURE_NO_RESPONSE: 8,
        FAILED_CANNED_RESPONSE: 9,
        IN_PROGRESS_REASONING: 10,
      }),
      u = e({
        TEE_CLIENT_UNKNOWN: 0,
        TEE_CLIENT_WA: 1,
        TEE_CLIENT_MSGR: 2,
        TEE_CLIENT_IG: 3,
        TEE_CLIENT_FB: 4,
        TEE_CLIENT_SILVERSTONE: 5,
      }),
      c = e({ USER: 0, ASSISTANT: 1 }),
      d = e({
        CONVERSATION_TYPE_UNKNOWN: 0,
        CONVERSATION_TYPE_INDIVIDUAL: 1,
        CONVERSATION_TYPE_GROUP: 2,
        CONVERSATION_TYPE_OTHER: 3,
      }),
      m = e({ AGE_UNKNOWN: 0, AGE_OVER_18: 1, AGE_UNDER_18: 2 }),
      p = e({ VIOLATION_STATUS_UNKNOWN: 0, NO_VIOLATION: 1, VIOLATION: 2 }),
      _ = e({ MOCK: "mock", REAL: "real", INTERCEPT: "intercept" }),
      f = e({
        SUMMARY: "summary",
        WRITE_WITH_AI: "write_with_ai",
        SIDE_CHAT: "side_chat",
        TEST: "test",
      });
    ((i.TEEMessageType = l),
      (i.TEEResponseStatus = s),
      (i.TEEClientSurface = u),
      (i.ChatRole = c),
      (i.ConversationType = d),
      (i.AgeStatus = m),
      (i.ViolationStatus = p),
      (i.TeeClientMode = _),
      (i.TeeRequestType = f));
  },
  66,
);
