__d(
  "WAWebMdDebugSettingStyles",
  [],
  function (t, n, r, o, a, i, l) {
    var e = {
      settingItem: {
        paddingTop: "xyamay9",
        paddingInlineEnd: "xyri2b",
        paddingBottom: "x1l90r2v",
        paddingInlineStart: "x1c1uobl",
        borderBottomWidth: "xso031l",
        borderBottomStyle: "x1q0q8m5",
        borderBottomColor: "x120ee7l",
        $$css: !0,
      },
      checkboxLabel: {
        display: "xt0psk2",
        marginInlineStart: "xdzw4kq",
        verticalAlign: "xxymvpz",
        $$css: !0,
      },
      propsButton: {
        fontSize: "x1f6kntn",
        fontWeight: "xk50ysn",
        color: "xhslqc4",
        borderBottomWidth: "xso031l",
        borderBottomStyle: "xpvcztv",
        borderBottomColor: "x1yepkla",
        $$css: !0,
      },
      propsButtonIcon: {
        marginInlineEnd: "x2fvf9",
        fontSize: "x14bfe9o",
        $$css: !0,
      },
      syncDeviceInput: {
        paddingTop: "x1y1aw1k",
        paddingInlineEnd: "xf159sx",
        paddingBottom: "xwib8y2",
        paddingInlineStart: "xmzvs34",
        marginInlineEnd: "x1ys307a",
        verticalAlign: "xxymvpz",
        resize: "xtt52l0",
        borderTopStyle: "x1ejq31n",
        borderInlineEndStyle: "x18oe1m7",
        borderBottomStyle: "x1sy0etr",
        borderInlineStartStyle: "xstzfhl",
        $$css: !0,
      },
      createUsernameChatInput: {
        paddingTop: "x1y1aw1k",
        paddingInlineEnd: "xf159sx",
        paddingBottom: "xwib8y2",
        paddingInlineStart: "xmzvs34",
        marginInlineEnd: "x1ys307a",
        marginInlineStart: "xdzw4kq",
        color: "xzsf02u",
        borderTopStyle: "x1ejq31n",
        borderInlineEndStyle: "x18oe1m7",
        borderBottomStyle: "x1sy0etr",
        borderInlineStartStyle: "xstzfhl",
        $$css: !0,
      },
      decryptFailInput: {
        paddingTop: "x1y1aw1k",
        paddingInlineEnd: "xf159sx",
        paddingBottom: "xwib8y2",
        paddingInlineStart: "xmzvs34",
        marginInlineEnd: "xbelrpt",
        marginInlineStart: "xdzw4kq",
        color: "xzsf02u",
        borderTopStyle: "x1ejq31n",
        borderInlineEndStyle: "x18oe1m7",
        borderBottomStyle: "x1sy0etr",
        borderInlineStartStyle: "xstzfhl",
        $$css: !0,
      },
      addContactInput: {
        paddingTop: "x1y1aw1k",
        paddingInlineEnd: "xf159sx",
        paddingBottom: "xwib8y2",
        paddingInlineStart: "xmzvs34",
        marginInlineEnd: "x1ys307a",
        marginInlineStart: "xdzw4kq",
        color: "xzsf02u",
        borderTopStyle: "x1ejq31n",
        borderInlineEndStyle: "x18oe1m7",
        borderBottomStyle: "x1sy0etr",
        borderInlineStartStyle: "xstzfhl",
        $$css: !0,
      },
    };
    l.styles = e;
  },
  98,
);
