__d(
  "WAWebCommonMsgSubtypeTypes",
  [],
  function (t, n, r, o, a, i) {
    var e = Object.freeze({
      Subject: "subject",
      Add: "add",
      Remove: "remove",
      Leave: "leave",
      Picture: "picture",
      Modify: "modify",
      Suspend: "suspend",
      Delete: "delete",
      Create: "create",
      Promote: "promote",
      Demote: "demote",
      Invite: "invite",
      RevokeInvite: "revoke_invite",
      Description: "description",
      ParentGroupDescription: "parent_group_description",
      Restrict: "restrict",
      Announce: "announce",
      AnnounceMsgBounce: "announce_msg_bounce",
      V4AddInviteSent: "v4_add_invite_sent",
      V4AddInviteJoin: "v4_add_invite_join",
      NoFrequentlyForwarded: "no_frequently_forwarded",
      InitialPHashMismatch: "initial_pHash_mismatch",
      Ephemeral: "ephemeral",
      GrowthLocked: "growth_locked",
      GrowthUnlocked: "growth_unlocked",
      ParentGroupLink: "parent_group_link",
      SiblingGroupLink: "sibling_group_link",
      SubGroupLink: "sub_group_link",
      ParentGroupUnlink: "parent_group_unlink",
      SiblingGroupUnlink: "sibling_group_unlink",
      SubGroupUnlink: "sub_group_unlink",
      LinkedGroupJoin: "linked_group_join",
      DeleteParentGroup: "delete_parent_group",
      DeleteParentGroupUnlink: "delete_parent_group_unlink",
      DeleteParentSubGroupUnlink: "delete_parent_sub_group_unlink",
      IntegrityParentGroupUnlink: "integrity_parent_group_unlink",
      IntegritySubGroupUnlink: "integrity_sub_group_unlink",
      LinkedGroupPromote: "linked_group_promote",
      LinkedGroupDemote: "linked_group_demote",
      MembershipApprovalMode: "membership_approval_mode",
      MembershipApprovalRequest: "membership_approval_request",
      MemberAddMode: "member_add_mode",
      MemberLinkMode: "member_link_mode",
      JoinFloodNotification: "join_flood_notification",
      MemberShareGroupHistoryMode: "member_share_group_history_mode",
      CreatedMembershipRequests: "created_membership_requests",
      RevokedMembershipRequests: "revoked_membership_requests",
      AutoAdd: "auto_add",
      DefaultSubGroupAdminAdd: "default_sub_group_admin_add",
      DefaultSubGroupPromote: "default_sub_group_promote",
      DefaultSubGroupDemote: "default_sub_group_demote",
      InviteAutoAdd: "invite_auto_add",
      CommunityParticipantAddRich: "community_participant_add_rich",
      CommunityInviteRich: "community_invite_rich",
      SubGroupParticipantAddRich: "sub_group_participant_add_rich",
      SubGroupInviteRich: "sub_group_invite_rich",
      CommunityLinkParentGroupRich: "community_link_parent_group_rich",
      CommunityInviteAutoAddRich: "community_invite_auto_add_rich",
      AllowNonAdminSubGroupCreation: "allow_non_admin_sub_group_creation",
      AllowAdminReports: "allow_admin_reports",
      CreatedSubgroupSuggestion: "created_subgroup_suggestion",
      RevokedSubGroupSuggestions: "revoked_sub_group_suggestions",
      AdminReportReceived: "admin_report_received",
      SubgroupSuggestionsChangeNumber: "subgroup_suggestions_change_number",
      SubgroupAdminTriggeredAutoAdd: "subgroup_admin_triggered_auto_add",
      SubgroupAdminTriggeredInviteAutoAdd:
        "subgroup_admin_triggered_invite_auto_add",
      EmptySubgroupCreate: "empty_subgroup_create",
      GeneralChatAdd: "general_chat_add",
      GeneralChatAutoAddDisabled: "general_chat_auto_add_disabled",
      CommunityOwnerUpdate: "community_owner_update",
      HiddenGroup: "hidden_group",
      GroupSafetyCheck: "group_safety_check",
      GroupAdder: "group_adder",
      MemberLabel: "member_label",
      MessageHistoryBundle: "message_history_bundle",
      MessageHistoryNotice: "message_history_notice",
      Url: "url",
      Encrypt: "encrypt",
      EncryptNow: "encrypt_now",
      E2EIdentityUnavailable: "e2e_identity_unavailable",
      Identity: "identity",
      Device: "device",
      ChatPsa: "chat_psa",
      ErrorInDeviceList: "error_in_device_list",
      Miss: "miss",
      MissVideo: "miss_video",
      MissGroup: "miss_group",
      MissGroupVideo: "miss_group_video",
      Silence: "silence",
      AdminRevoke: "admin_revoke",
      SenderRevoke: "sender_revoke",
      EphemeralSetting: "ephemeral_setting",
      EphemeralSyncResponse: "ephemeral_sync_response",
      SharePhoneNumber: "share_phone_number",
      AppStateFatalExceptionNotification:
        "app_state_fatal_exception_notification",
      AppStateSyncKeyShare: "app_state_sync_key_share",
      AppStateSyncKeyRequest: "app_state_sync_key_request",
      HistorySyncNotification: "history_sync_notification",
      MessageEdit: "message_edit",
      MessageEditDecrypted: "message_edit_decrypted",
      BotFeedback: "bot_feedback",
      BotMemuOnboarding: "bot_memu_onboarding",
      BotRequestWelcome: "bot_request_welcome",
      StatusMentionMessage: "status_mention_message",
      StatusGroupMentionMessage: "status_group_mention_message",
      StatusNotificationMessage: "status_notification_message",
      Request: "request",
      Send: "send",
      Ciphertext: "ciphertext",
      Futureproof: "futureproof",
      PollVote: "poll_vote",
      PollEditDecrypted: "poll_edit_decrypted",
      PollAddOptionDecrypted: "poll_add_option_decrypted",
      Sender: "sender",
      Admin: "admin",
      Phone: "phone",
      PhoneOnlyFeature: "phone_only_feature",
      Reaction: "reaction",
      NonVerifiedTransition: "non_verified_transition",
      UnverifiedTransition: "unverified_transition",
      VerifiedTransition: "verified_transition",
      VerifiedLowUnknown: "verified_low_unknown",
      VerifiedHigh: "verified_high",
      VerifiedInitialUnknown: "verified_initial_unknown",
      VerifiedInitialLow: "verified_initial_low",
      VerifiedInitialHigh: "verified_initial_high",
      VerifiedTransitionAnyToNone: "verified_transition_any_to_none",
      VerifiedTransitionAnyToHigh: "verified_transition_any_to_high",
      VerifiedTransitionHighToLow: "verified_transition_high_to_low",
      VerifiedTransitionHighToUnknown: "verified_transition_high_to_unknown",
      VerifiedTransitionUnknownToLow: "verified_transition_unknown_to_low",
      VerifiedTransitionLowToUnknown: "verified_transition_low_to_unknown",
      VerifiedTransitionNoneToLow: "verified_transition_none_to_low",
      VerifiedTransitionNoneToUnknown: "verified_transition_none_to_unknown",
      PaymentTransactionStatusUpdateFailed:
        "payment_transaction_status_update_failed",
      PaymentTransactionStatusUpdateRefunded:
        "payment_transaction_status_update_refunded",
      PaymentTransactionStatusUpdateRefundFailed:
        "payment_transaction_status_update_refund_failed",
      PaymentTransactionStatusReceiverPendingSetup:
        "payment_transaction_status_receiver_pending_setup",
      PaymentTransactionStatusReceiverSuccessAfterHiccup:
        "payment_transaction_status_receiver_success_after_hiccup",
      PaymentTransactionRequestCancelled:
        "payment_transaction_request_cancelled",
      PaymentActionAccountSetupReminder:
        "payment_action_account_setup_reminder",
      PaymentActionSendPaymentReminder: "payment_action_send_payment_reminder",
      PaymentActionSendPaymentInvitation:
        "payment_action_send_payment_invitation",
      PaymentActionRequestDeclined: "payment_action_request_declined",
      PaymentActionRequestExpired: "payment_action_request_expired",
      PaymentInviteAccountSetUp: "payment_invite_account_set_up",
      BizVerifiedTransitionTopToBottom: "biz_verified_transition_top_to_bottom",
      BizVerifiedTransitionBottomToTop: "biz_verified_transition_bottom_to_top",
      BizIntroTop: "biz_intro_top",
      BizIntroBottom: "biz_intro_bottom",
      BizNameChange: "biz_name_change",
      BizMoveToConsumerApp: "biz_move_to_consumer_app",
      BizTwoTierMigrationTop: "biz_two_tier_migration_top",
      BizTwoTierMigrationBottom: "biz_two_tier_migration_bottom",
      SenderInvite: "sender_invite",
      ReceiverInvite: "receiver_invite",
      ChangeNumber: "change_number",
      ChangeUsername: "change_username",
      ChangeLid: "change_lid",
      MaskedThreadCreated: "masked_thread_created",
      PhoneNumberThreadPromotion: "pnh_thread_promotion",
      CagMaskedThreadCreated: "cag_masked_thread_created",
      InfoEncrypted: "info_encrypted",
      DescAdd: "desc_add",
      DescRemove: "desc_remove",
      Fanout: "fanout",
      BotUnavailableFanout: "bot_unavailable_fanout",
      HostedUnavailableFanout: "hosted_unavailable_fanout",
      ViewOnceUnavailableFanout: "view_once_unavailable_fanout",
      DisappearingMode: "disappearing_mode",
      DisappearingModeUpdate: "disappearing_mode_update",
      DisappearingModeUnsupported: "disappearing_mode_unsupported",
      BlockContact: "block_contact",
      CommunityCreate: "community_create",
      EphemeralKeepInChat: "ephemeral_keep_in_chat",
      KeepInChat: "keep_in_chat",
      ChatAssignment: "chat_assignment",
      PeerDataOperationRequestMessage: "peer_data_operation_request_message",
      ChatAssignmentUnassign: "chat_assignment_unassign",
      PeerDataOperationRequestResponseMessage:
        "peer_data_operation_request_response_message",
      MarketingMessagesFromBusinessStopped:
        "marketing_messages_from_business_stopped",
      MarketingMessagesFromBusinessResumed:
        "marketing_messages_from_business_resumed",
      MarketingMessagesPostSendOptOut: "marketing_messages_post_send_opt_out",
      NewsletterCreated: "newsletter_created",
      NewsletterPrivacy: "newsletter_privacy",
      NewsletterDeleted: "newsletter_deleted",
      NewsletterAdminContextCard: "newsletter_admin_context_card",
      PollCreation: "poll_creation",
      PollUpdate: "poll_update",
      ContactInfoCard: "contact_info_card",
      OrderEphemeralExemption: "order_ephemeral_exemption",
      BotInit: "bot_init",
      BotTypingPlaceholder: "bot_typing_placeholder",
      BotInvokeDisclaimer: "bot_invoke_disclaimer",
      BizBot1PDisclosure: "biz_bot_1p_disclosure",
      BizBot3PDisclosure: "biz_bot_3p_disclosure",
      BotSessionTransparencyNotice: "bot_session_transparency_notice",
      BlueMsgBspFbToBspPremise: "blue_msg_bsp_fb_to_bsp_premise",
      BlueMsgBspFbToSelfFb: "blue_msg_bsp_fb_to_self_fb",
      BlueMsgBspFbToSelfPremise: "blue_msg_bsp_fb_to_self_premise",
      BlueMsgBspFbUnverified: "blue_msg_bsp_fb_unverified",
      BlueMsgBspFbUnverifiedToBspPremiseVerified:
        "blue_msg_bsp_fb_unverified_to_bsp_premise_verified",
      BlueMsgBspFbUnverifiedToSelfFbVerified:
        "blue_msg_bsp_fb_unverified_to_self_fb_verified",
      BlueMsgBspFbUnverifiedToSelfPremiseVerified:
        "blue_msg_bsp_fb_unverified_to_self_premise_verified",
      BlueMsgBspFbVerified: "blue_msg_bsp_fb_verified",
      BlueMsgBspFbVerifiedToBspPremiseUnverified:
        "blue_msg_bsp_fb_verified_to_bsp_premise_unverified",
      BlueMsgBspFbVerifiedToSelfFbUnverified:
        "blue_msg_bsp_fb_verified_to_self_fb_unverified",
      BlueMsgBspFbVerifiedToSelfPremiseUnverified:
        "blue_msg_bsp_fb_verified_to_self_premise_unverified",
      BlueMsgBspPremiseToSelfPremise: "blue_msg_bsp_premise_to_self_premise",
      BlueMsgBspPremiseUnverified: "blue_msg_bsp_premise_unverified",
      BlueMsgBspPremiseUnverifiedToSelfPremiseVerified:
        "blue_msg_bsp_premise_unverified_to_self_premise_verified",
      BlueMsgBspPremiseVerified: "blue_msg_bsp_premise_verified",
      BlueMsgBspPremiseVerifiedToSelfPremiseUnverified:
        "blue_msg_bsp_premise_verified_to_self_premise_unverified",
      BlueMsgConsumerToBspFbUnverified:
        "blue_msg_consumer_to_bsp_fb_unverified",
      BlueMsgConsumerToBspPremiseUnverified:
        "blue_msg_consumer_to_bsp_premise_unverified",
      BlueMsgConsumerToSelfFbUnverified:
        "blue_msg_consumer_to_self_fb_unverified",
      BlueMsgConsumerToSelfPremiseUnverified:
        "blue_msg_consumer_to_self_premise_unverified",
      BlueMsgSelfFbToBspPremise: "blue_msg_self_fb_to_bsp_premise",
      BlueMsgSelfFbToSelfPremise: "blue_msg_self_fb_to_self_premise",
      BlueMsgSelfFbUnverified: "blue_msg_self_fb_unverified",
      BlueMsgSelfFbUnverifiedToBspPremiseVerified:
        "blue_msg_self_fb_unverified_to_bsp_premise_verified",
      BlueMsgSelfFbUnverifiedToSelfPremiseVerified:
        "blue_msg_self_fb_unverified_to_self_premise_verified",
      BlueMsgSelfFbVerified: "blue_msg_self_fb_verified",
      BlueMsgSelfFbVerifiedToBspPremiseUnverified:
        "blue_msg_self_fb_verified_to_bsp_premise_unverified",
      BlueMsgSelfFbVerifiedToSelfPremiseUnverified:
        "blue_msg_self_fb_verified_to_self_premise_unverified",
      BlueMsgSelfPremiseToBspPremise: "blue_msg_self_premise_to_bsp_premise",
      BlueMsgSelfPremiseUnverified: "blue_msg_self_premise_unverified",
      BlueMsgSelfPremiseVerified: "blue_msg_self_premise_verified",
      BlueMsgToBspFb: "blue_msg_to_bsp_fb",
      BlueMsgToConsumer: "blue_msg_to_consumer",
      BlueMsgToSelfFb: "blue_msg_to_self_fb",
      BlueMsgUnverifiedToBspFbVerified:
        "blue_msg_unverified_to_bsp_fb_verified",
      BlueMsgUnverifiedToBspPremiseVerified:
        "blue_msg_unverified_to_bsp_premise_verified",
      BlueMsgUnverifiedToSelfFbVerified:
        "blue_msg_unverified_to_self_fb_verified",
      BlueMsgUnverifiedToVerified: "blue_msg_unverified_to_verified",
      BlueMsgVerifiedToBspFbUnverified:
        "blue_msg_verified_to_bsp_fb_unverified",
      BlueMsgVerifiedToBspPremiseUnverified:
        "blue_msg_verified_to_bsp_premise_unverified",
      BlueMsgVerifiedToSelfFbUnverified:
        "blue_msg_verified_to_self_fb_unverified",
      BlueMsgVerifiedToUnverified: "blue_msg_verified_to_unverified",
      BizPrivacyModeInitFb: "biz_privacy_mode_init_fb",
      BizPrivacyModeInitBsp: "biz_privacy_mode_init_bsp",
      BizPrivacyModeToFb: "biz_privacy_mode_to_fb",
      BizPrivacyModeToBsp: "biz_privacy_mode_to_bsp",
      SagaInit: "saga_init",
      SupportSystemMessage: "support_system_message",
      BizAccountTypeChangedToHosted: "biz_account_type_changed_to_hosted",
      BizMeAccountTypeIsHostedSystemMsg: "biz_me_account_type_is_hosted",
      BizMeAccountTypeIsHostedSystemMsgTransition:
        "biz_me_account_type_is_hosted_transition",
      BizAccountTypeIsHostedSystemMsg: "biz_account_type_is_hosted",
      EventEditDecrypted: "event_edit_decrypted",
      HostedGroup: "is_capi_hosted_group",
      LimitSharingSystemMessage: "limit_sharing_system_message",
      BizAutomaticallyLabeledChatSystemMessage:
        "biz_automatically_labeled_chat_system_message",
      GuestUpsell: "guest_upsell",
      BizPerCustomer3pdDataShareOptIn: "biz_per_customer_3pd_data_share_opt_in",
      BizPerCustomer3pdDataShareOptOut:
        "biz_per_customer_3pd_data_share_opt_out",
      CtwaConsumerDataSharingDisclosureSystemMessage:
        "ctwa_consumer_data_sharing_disclosure_system_message",
      MmSignalSharingSystemMessage: "mm_signal_sharing_system_message",
      LoadingImage: "loading_image",
      LoadingVideo: "loading_video",
      HostedGroupDoNotUseS440891: "is_hosted_group",
      GroupTransitionToBotGroupSystemMsg: "group_transition_to_bot_group",
      BizBroadcastStatus: "biz_broadcast_status",
      GroupTransitionToTeeBotGroupSystemMsg:
        "group_transition_to_tee_bot_group",
      Signup: "signup",
    });
    i.MsgSubtype = e;
  },
  66,
);
