__d(
  "WAWebBizGraphQLRefreshCartJobQuery.graphql",
  [],
  function (t, n, r, o, a, i) {
    var e = (function () {
      var e = [{ defaultValue: null, kind: "LocalArgument", name: "request" }],
        t = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "status",
          storageKey: null,
        },
        n = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "price",
          storageKey: null,
        },
        r = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "currency",
          storageKey: null,
        },
        o = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "name",
          storageKey: null,
        },
        a = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "description",
          storageKey: null,
        },
        i = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "id",
          storageKey: null,
        },
        l = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "request_image_url",
          storageKey: null,
        },
        s = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "height",
          storageKey: null,
        },
        u = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "width",
          storageKey: null,
        },
        c = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "value",
          storageKey: null,
        },
        d = [
          {
            alias: null,
            args: [
              { kind: "Variable", name: "request", variableName: "request" },
            ],
            concreteType: "XWACheckoutRefreshCartResponseSuccess",
            kind: "LinkedField",
            name: "xwa_checkout_refresh_cart",
            plural: !1,
            selections: [
              {
                alias: null,
                args: null,
                concreteType:
                  "XWACheckoutRefreshCartResponseSuccessProductList",
                kind: "LinkedField",
                name: "cart",
                plural: !1,
                selections: [
                  {
                    alias: null,
                    args: null,
                    concreteType: "XWACatalogProduct",
                    kind: "LinkedField",
                    name: "products",
                    plural: !0,
                    selections: [
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "is_hidden",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "availability",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "product_availability",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        concreteType: "XWAProductCatalogProductStatusInfo",
                        kind: "LinkedField",
                        name: "status_info",
                        plural: !1,
                        selections: [
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "reject_reason",
                            storageKey: null,
                          },
                          t,
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "can_appeal",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "commerce_url",
                            storageKey: null,
                          },
                        ],
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "image_fetch_status",
                        storageKey: null,
                      },
                      n,
                      r,
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "retailer_id",
                        storageKey: null,
                      },
                      o,
                      a,
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "url",
                        storageKey: null,
                      },
                      i,
                      {
                        alias: null,
                        args: null,
                        concreteType: "XWAProductCatalogProductMedia",
                        kind: "LinkedField",
                        name: "media",
                        plural: !1,
                        selections: [
                          {
                            alias: null,
                            args: null,
                            concreteType: "XWAProductCatalogProductMediaImage",
                            kind: "LinkedField",
                            name: "images",
                            plural: !0,
                            selections: [
                              i,
                              l,
                              {
                                alias: null,
                                args: null,
                                concreteType:
                                  "XWAProductCatalogProductMediaImageOriginalDimensions",
                                kind: "LinkedField",
                                name: "original_dimensions",
                                plural: !1,
                                selections: [s, u],
                                storageKey: null,
                              },
                            ],
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            concreteType: "XWAProductCatalogProductMediaVideo",
                            kind: "LinkedField",
                            name: "videos",
                            plural: !0,
                            selections: [
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "thumbnail_url",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "original_video_url",
                                storageKey: null,
                              },
                              i,
                            ],
                            storageKey: null,
                          },
                        ],
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        concreteType: "XWAProductCatalogProductSalePrice",
                        kind: "LinkedField",
                        name: "sale_price",
                        plural: !1,
                        selections: [
                          n,
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "start_date",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "end_date",
                            storageKey: null,
                          },
                        ],
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "max_available",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "belongs_to",
                        storageKey: null,
                      },
                      t,
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "compliance_category",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        concreteType: "XWAProductCatalogProductComplianceInfo",
                        kind: "LinkedField",
                        name: "compliance_info",
                        plural: !1,
                        selections: [
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "country_code_origin",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "importer_name",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            concreteType:
                              "XWAProductCatalogProductComplianceInfoImporterAddress",
                            kind: "LinkedField",
                            name: "importer_address",
                            plural: !1,
                            selections: [
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "street1",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "street2",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "city",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "region",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "postal_code",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "country_code",
                                storageKey: null,
                              },
                            ],
                            storageKey: null,
                          },
                        ],
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        concreteType: "XWACatalogProductVariantInfo",
                        kind: "LinkedField",
                        name: "variant_info",
                        plural: !1,
                        selections: [
                          {
                            alias: null,
                            args: null,
                            concreteType: "XWACatalogVariantTypes",
                            kind: "LinkedField",
                            name: "types",
                            plural: !0,
                            selections: [
                              o,
                              {
                                alias: null,
                                args: null,
                                concreteType: "XWACatalogVariantTypeOption",
                                kind: "LinkedField",
                                name: "options",
                                plural: !0,
                                selections: [
                                  c,
                                  {
                                    alias: null,
                                    args: null,
                                    concreteType:
                                      "XWAProductCatalogProductMediaImage",
                                    kind: "LinkedField",
                                    name: "thumbnail_media",
                                    plural: !1,
                                    selections: [
                                      {
                                        alias: null,
                                        args: null,
                                        concreteType:
                                          "XWAProductCatalogProductMediaImageOriginalDimensions",
                                        kind: "LinkedField",
                                        name: "original_dimensions",
                                        plural: !1,
                                        selections: [u, s],
                                        storageKey: null,
                                      },
                                      l,
                                      {
                                        alias: null,
                                        args: null,
                                        kind: "ScalarField",
                                        name: "original_image_url",
                                        storageKey: null,
                                      },
                                      i,
                                    ],
                                    storageKey: null,
                                  },
                                ],
                                storageKey: null,
                              },
                            ],
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            concreteType: "XWACatalogVariantListingDetails",
                            kind: "LinkedField",
                            name: "listing_details",
                            plural: !1,
                            selections: [
                              a,
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "multi_price",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "lowest_price",
                                storageKey: null,
                              },
                            ],
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            concreteType: "XWACatalogVariantProperties",
                            kind: "LinkedField",
                            name: "variant_properties",
                            plural: !0,
                            selections: [c, o],
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            concreteType: "XWACatalogVariantAvailability",
                            kind: "LinkedField",
                            name: "availability",
                            plural: !1,
                            selections: [
                              {
                                alias: null,
                                args: null,
                                concreteType: "XWAVariantAvailabilityListing",
                                kind: "LinkedField",
                                name: "listing",
                                plural: !0,
                                selections: [
                                  {
                                    alias: null,
                                    args: null,
                                    kind: "ScalarField",
                                    name: "is_available",
                                    storageKey: null,
                                  },
                                  {
                                    alias: null,
                                    args: null,
                                    kind: "ScalarField",
                                    name: "product_id",
                                    storageKey: null,
                                  },
                                  {
                                    alias: null,
                                    args: null,
                                    concreteType:
                                      "XWAVariantAvailabilityListingOption",
                                    kind: "LinkedField",
                                    name: "options",
                                    plural: !0,
                                    selections: [o, c],
                                    storageKey: null,
                                  },
                                ],
                                storageKey: null,
                              },
                            ],
                            storageKey: null,
                          },
                        ],
                        storageKey: null,
                      },
                    ],
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: null,
                    concreteType: "XWACheckoutPriceDetails",
                    kind: "LinkedField",
                    name: "price_details",
                    plural: !1,
                    selections: [
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "total_amount",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "subtotal_amount",
                        storageKey: null,
                      },
                      r,
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "price_status",
                        storageKey: null,
                      },
                    ],
                    storageKey: null,
                  },
                ],
                storageKey: null,
              },
            ],
            storageKey: null,
          },
        ];
      return {
        fragment: {
          argumentDefinitions: e,
          kind: "Fragment",
          metadata: null,
          name: "WAWebBizGraphQLRefreshCartJobQuery",
          selections: d,
          type: "Query",
          abstractKey: null,
        },
        kind: "Request",
        operation: {
          argumentDefinitions: e,
          kind: "Operation",
          name: "WAWebBizGraphQLRefreshCartJobQuery",
          selections: d,
        },
        params: {
          id: "WAWebBizGraphQLRefreshCartJobQuery",
          metadata: {},
          name: "WAWebBizGraphQLRefreshCartJobQuery",
          operationKind: "query",
          text: null,
        },
      };
    })();
    e.hash = "a43f6584b79d805c7239ab4726af7cd7";
    var l = e;
    i.default = l;
  },
  66,
);
