__d(
  "WAWebProtobufsAICommon.pb",
  ["$InternalEnum", "WAProtoConst", "WAWebProtobufsProtocol.pb"],
  function (t, n, r, o, a, i, l) {
    var e,
      s,
      u,
      c = (u = n("$InternalEnum"))({ UNKNOWN_PLUGIN: 0, REELS: 1, SEARCH: 2 }),
      d = u({ UNKNOWN: 0, BING: 1, GOOGLE: 2, SUPPORT: 3 }),
      m = u({ BOT_LINKED_ACCOUNT_TYPE_1P: 0 }),
      p = u({ UNSPECIFIED: 0, WA_BOT_MSG: 1, WA_TEE_BOT_MSG: 2 }),
      _ = u({ UNKNOWN_TYPE: 0, C50: 1, SURVEY_PLATFORM: 2 }),
      f = u({
        UNDEFINED_ENTRY_POINT: 0,
        FAVICON: 1,
        CHATLIST: 2,
        AISEARCH_NULL_STATE_PAPER_PLANE: 3,
        AISEARCH_NULL_STATE_SUGGESTION: 4,
        AISEARCH_TYPE_AHEAD_SUGGESTION: 5,
        AISEARCH_TYPE_AHEAD_PAPER_PLANE: 6,
        AISEARCH_TYPE_AHEAD_RESULT_CHATLIST: 7,
        AISEARCH_TYPE_AHEAD_RESULT_MESSAGES: 8,
        AIVOICE_SEARCH_BAR: 9,
        AIVOICE_FAVICON: 10,
        AISTUDIO: 11,
        DEEPLINK: 12,
        NOTIFICATION: 13,
        PROFILE_MESSAGE_BUTTON: 14,
        FORWARD: 15,
        APP_SHORTCUT: 16,
        FF_FAMILY: 17,
        AI_TAB: 18,
        AI_HOME: 19,
        AI_DEEPLINK_IMMERSIVE: 20,
        AI_DEEPLINK: 21,
        META_AI_CHAT_SHORTCUT_AI_STUDIO: 22,
        UGC_CHAT_SHORTCUT_AI_STUDIO: 23,
        NEW_CHAT_AI_STUDIO: 24,
        AIVOICE_FAVICON_CALL_HISTORY: 25,
        ASK_META_AI_CONTEXT_MENU: 26,
        ASK_META_AI_CONTEXT_MENU_1ON1: 27,
        ASK_META_AI_CONTEXT_MENU_GROUP: 28,
        INVOKE_META_AI_1ON1: 29,
        INVOKE_META_AI_GROUP: 30,
        META_AI_FORWARD: 31,
        NEW_CHAT_AI_CONTACT: 32,
        MESSAGE_QUICK_ACTION_1_ON_1_CHAT: 33,
        MESSAGE_QUICK_ACTION_GROUP_CHAT: 34,
        ATTACHMENT_TRAY_1_ON_1_CHAT: 35,
        ATTACHMENT_TRAY_GROUP_CHAT: 36,
        ASK_META_AI_MEDIA_VIEWER_1ON1: 37,
        ASK_META_AI_MEDIA_VIEWER_GROUP: 38,
        MEDIA_PICKER_1_ON_1_CHAT: 39,
        MEDIA_PICKER_GROUP_CHAT: 40,
        ASK_META_AI_NO_SEARCH_RESULTS: 41,
        META_AI_SETTINGS: 45,
        WEB_INTRO_PANEL: 46,
        WEB_NAVIGATION_BAR: 47,
        GROUP_MEMBER: 54,
        CHATLIST_SEARCH: 55,
        NEW_CHAT_LIST: 56,
      }),
      g = u({
        AI_TAB_THREAD: 1,
        AI_HOME_THREAD: 2,
        AI_DEEPLINK_IMMERSIVE_THREAD: 3,
        AI_DEEPLINK_THREAD: 4,
        ASK_META_AI_CONTEXT_MENU_THREAD: 5,
      }),
      h = u({
        NONE: 0,
        NULL_STATE: 1,
        TYPEAHEAD: 2,
        USER_INPUT: 3,
        EMU_FLASH: 4,
        EMU_FLASH_FOLLOWUP: 5,
        VOICE: 6,
        AI_HOME_SESSION: 7,
      }),
      y = u({ CENTER: 1, LEFT: 2, RIGHT: 3 }),
      C = u({ ONCE: 1, DAILY: 2, WEEKLY: 3, BIWEEKLY: 4, MONTHLY: 5 }),
      b = u({ NOTIFY: 1, CREATE: 2, DELETE: 3, UPDATE: 4 }),
      v = u({ UNKNOWN_STATUS: 0, AVAILABLE: 1, QUOTA_EXCEED_LIMIT: 2 }),
      S = u({ UNKNOWN_TYPE: 0, LLAMA_PROD: 1, LLAMA_PROD_PREMIUM: 2 }),
      R = u({ UNKNOWN: 0, OTHER: 1, GOOGLE: 2, BING: 3 }),
      L = u({ UNKNOWN_PROVIDER: 0, OTHER: 1, GOOGLE: 2, BING: 3 }),
      E = u({ UNKNOWN: 0, PLANNED: 1, EXECUTING: 2, FINISHED: 3 }),
      k = u({
        UNKNOWN: 0,
        PROGRESS_INDICATOR: 1,
        RICH_RESPONSE_HEADING: 2,
        RICH_RESPONSE_NESTED_LIST: 3,
        AI_MEMORY: 4,
        RICH_RESPONSE_THREAD_SURFING: 5,
        RICH_RESPONSE_TABLE: 6,
        RICH_RESPONSE_CODE: 7,
        RICH_RESPONSE_STRUCTURED_RESPONSE: 8,
        RICH_RESPONSE_INLINE_IMAGE: 9,
        WA_IG_1P_PLUGIN_RANKING_CONTROL: 10,
        WA_IG_1P_PLUGIN_RANKING_UPDATE_1: 11,
        WA_IG_1P_PLUGIN_RANKING_UPDATE_2: 12,
        WA_IG_1P_PLUGIN_RANKING_UPDATE_3: 13,
        WA_IG_1P_PLUGIN_RANKING_UPDATE_4: 14,
        WA_IG_1P_PLUGIN_RANKING_UPDATE_5: 15,
        WA_IG_1P_PLUGIN_RANKING_UPDATE_6: 16,
        WA_IG_1P_PLUGIN_RANKING_UPDATE_7: 17,
        WA_IG_1P_PLUGIN_RANKING_UPDATE_8: 18,
        WA_IG_1P_PLUGIN_RANKING_UPDATE_9: 19,
        WA_IG_1P_PLUGIN_RANKING_UPDATE_10: 20,
        RICH_RESPONSE_SUB_HEADING: 21,
        RICH_RESPONSE_GRID_IMAGE: 22,
        AI_STUDIO_UGC_MEMORY: 23,
        RICH_RESPONSE_LATEX: 24,
        RICH_RESPONSE_MAPS: 25,
        RICH_RESPONSE_INLINE_REELS: 26,
        AGENTIC_PLANNING: 27,
        ACCOUNT_LINKING: 28,
        STREAMING_DISAGGREGATION: 29,
        RICH_RESPONSE_GRID_IMAGE_3P: 30,
        RICH_RESPONSE_LATEX_INLINE: 31,
        QUERY_PLAN: 32,
        PROACTIVE_MESSAGE: 33,
        RICH_RESPONSE_UNIFIED_RESPONSE: 34,
        PROMOTION_MESSAGE: 35,
        SIMPLIFIED_PROFILE_PAGE: 36,
        RICH_RESPONSE_SOURCES_IN_MESSAGE: 37,
        RICH_RESPONSE_SIDE_BY_SIDE_SURVEY: 38,
        RICH_RESPONSE_UNIFIED_TEXT_COMPONENT: 39,
        AI_SHARED_MEMORY: 40,
        RICH_RESPONSE_UNIFIED_SOURCES: 41,
        RICH_RESPONSE_UNIFIED_DOMAIN_CITATIONS: 42,
        RICH_RESPONSE_UR_INLINE_REELS_ENABLED: 43,
        RICH_RESPONSE_UR_MEDIA_GRID_ENABLED: 44,
        RICH_RESPONSE_UR_TIMESTAMP_PLACEHOLDER: 45,
        RICH_RESPONSE_IN_APP_SURVEY: 46,
        AI_RESPONSE_MODEL_BRANDING: 47,
        SESSION_TRANSPARENCY_SYSTEM_MESSAGE: 48,
        RICH_RESPONSE_UR_REASONING: 49,
        RICH_RESPONSE_UR_ZEITGEIST_CITATIONS: 50,
        RICH_RESPONSE_UR_ZEITGEIST_CAROUSEL: 51,
        AI_IMAGINE_LOADING_INDICATOR: 52,
        RICH_RESPONSE_UR_IMAGINE: 53,
        AI_IMAGINE_UR_TO_NATIVE_LOADING_INDICATOR: 54,
        RICH_RESPONSE_UR_BLOKS_ENABLED: 55,
        RICH_RESPONSE_INLINE_LINKS_ENABLED: 56,
        RICH_RESPONSE_UR_IMAGINE_VIDEO: 57,
        JSON_PATCH_STREAMING: 58,
        AI_TAB_FORCE_CLIPPY: 59,
        UNIFIED_RESPONSE_EMBEDDED_SCREENS: 60,
        AI_SUBSCRIPTION_ENABLED: 61,
      }),
      I = u({ DEFAULT_MODE: 0, THINK_HARD_MODE: 1 }),
      T = u({ UNKNOWN_FEATURE: 0, REASONING_FEATURE: 1 }),
      D = u({ UNKNOWN: 0, IMAGINE: 1, MEMU: 2, FLASH: 3, EDIT: 4 }),
      x = u({ O18_BINARY: 0, WAFFLE: 1 }),
      $ = u({ UNKNOWN: 0, BING: 1, GOOGLE: 2, SUPPORT: 3, OTHER: 4 }),
      P = u({ BOT_MESSAGE_ORIGIN_TYPE_AI_INITIATED: 0 }),
      N = u({ UNKNOWN: 0, DEFAULT: 1, INCOGNITO: 2, SIDE_CHAT: 3 }),
      M = u({ NONE: 0, GENERIC: 1 }),
      w = u({ BOT_FEEDBACK_MULTIPLE_POSITIVE_GENERIC: 1 }),
      A = u({
        BOT_FEEDBACK_MULTIPLE_NEGATIVE_GENERIC: 1,
        BOT_FEEDBACK_MULTIPLE_NEGATIVE_HELPFUL: 2,
        BOT_FEEDBACK_MULTIPLE_NEGATIVE_INTERESTING: 4,
        BOT_FEEDBACK_MULTIPLE_NEGATIVE_ACCURATE: 8,
        BOT_FEEDBACK_MULTIPLE_NEGATIVE_SAFE: 16,
        BOT_FEEDBACK_MULTIPLE_NEGATIVE_OTHER: 32,
        BOT_FEEDBACK_MULTIPLE_NEGATIVE_REFUSED: 64,
        BOT_FEEDBACK_MULTIPLE_NEGATIVE_NOT_VISUALLY_APPEALING: 128,
        BOT_FEEDBACK_MULTIPLE_NEGATIVE_NOT_RELEVANT_TO_TEXT: 256,
      }),
      F = u({
        BOT_FEEDBACK_POSITIVE: 0,
        BOT_FEEDBACK_NEGATIVE_GENERIC: 1,
        BOT_FEEDBACK_NEGATIVE_HELPFUL: 2,
        BOT_FEEDBACK_NEGATIVE_INTERESTING: 3,
        BOT_FEEDBACK_NEGATIVE_ACCURATE: 4,
        BOT_FEEDBACK_NEGATIVE_SAFE: 5,
        BOT_FEEDBACK_NEGATIVE_OTHER: 6,
        BOT_FEEDBACK_NEGATIVE_REFUSED: 7,
        BOT_FEEDBACK_NEGATIVE_NOT_VISUALLY_APPEALING: 8,
        BOT_FEEDBACK_NEGATIVE_NOT_RELEVANT_TO_TEXT: 9,
        BOT_FEEDBACK_NEGATIVE_PERSONALIZED: 10,
        BOT_FEEDBACK_NEGATIVE_CLARITY: 11,
        BOT_FEEDBACK_NEGATIVE_DOESNT_LOOK_LIKE_THE_PERSON: 12,
        BOT_FEEDBACK_NEGATIVE_HALLUCINATION_INTERNAL_ONLY: 13,
        BOT_FEEDBACK_NEGATIVE: 14,
      }),
      O = u({ TEXT_EXTRACTION: 0, OCR_AND_IMAGES: 1 }),
      B = u({
        PROMPT: 0,
        CREATE_IMAGE: 1,
        ANIMATE_PHOTO: 2,
        ANALYZE_FILE: 3,
        COLLABORATE: 4,
      }),
      W = u({ UNKNOWN_TYPE: 0, NY_AI_SAFETY_DISCLAIMER: 1 }),
      q = u({ AAPI: 0, CLIPPY: 1 }),
      U = {},
      V = {},
      H = {},
      G = {},
      z = {},
      j = {},
      K = {},
      Q = {},
      X = {},
      Y = {},
      J = {},
      Z = {},
      ee = {},
      te = {},
      ne = {},
      re = {},
      oe = {},
      ae = {},
      ie = {},
      le = {},
      se = {},
      ue = {},
      ce = {},
      de = {},
      me = {},
      pe = {},
      _e = {},
      fe = {},
      ge = {},
      he = {},
      ye = {},
      Ce = {},
      be = {},
      ve = {},
      Se = {},
      Re = {},
      Le = {},
      Ee = {},
      ke = {},
      Ie = {},
      Te = {},
      De = {},
      xe = {},
      $e = {},
      Pe = {},
      Ne = {},
      Me = {},
      we = {},
      Ae = {},
      Fe = {},
      Oe = {},
      Be = {},
      We = {},
      qe = {},
      Ue = {},
      Ve = {},
      He = {},
      Ge = {},
      ze = {},
      je = {},
      Ke = {},
      Qe = {},
      Xe = {},
      Ye = {},
      Je = {},
      Ze = {},
      et = {},
      tt = {},
      nt = {},
      rt = {},
      ot = {};
    ((U.name = "BotPluginMetadata"),
      (U.internalSpec = {
        provider: [1, (e = o("WAProtoConst")).TYPES.ENUM, d],
        pluginType: [2, e.TYPES.ENUM, c],
        thumbnailCdnUrl: [3, e.TYPES.STRING],
        profilePhotoCdnUrl: [4, e.TYPES.STRING],
        searchProviderUrl: [5, e.TYPES.STRING],
        referenceIndex: [6, e.TYPES.UINT32],
        expectedLinksCount: [7, e.TYPES.UINT32],
        searchQuery: [9, e.TYPES.STRING],
        parentPluginMessageKey: [
          10,
          e.TYPES.MESSAGE,
          (s = o("WAWebProtobufsProtocol.pb")).MessageKeySpec,
        ],
        deprecatedField: [11, e.TYPES.ENUM, c],
        parentPluginType: [12, e.TYPES.ENUM, c],
        faviconCdnUrl: [13, e.TYPES.STRING],
      }),
      (V.name = "BotSuggestedPromptMetadata"),
      (V.internalSpec = {
        suggestedPrompts: [1, e.FLAGS.REPEATED | e.TYPES.STRING],
        selectedPromptIndex: [2, e.TYPES.UINT32],
        promptSuggestions: [3, e.TYPES.MESSAGE, H],
        selectedPromptId: [4, e.TYPES.STRING],
      }),
      (H.name = "BotPromptSuggestions"),
      (H.internalSpec = {
        suggestions: [1, e.FLAGS.REPEATED | e.TYPES.MESSAGE, G],
      }),
      (G.name = "BotPromptSuggestion"),
      (G.internalSpec = {
        prompt: [1, e.TYPES.STRING],
        promptId: [2, e.TYPES.STRING],
      }),
      (z.name = "BotLinkedAccountsMetadata"),
      (z.internalSpec = {
        accounts: [1, e.FLAGS.REPEATED | e.TYPES.MESSAGE, j],
        acAuthTokens: [2, e.TYPES.BYTES],
        acErrorCode: [3, e.TYPES.INT32],
      }),
      (j.name = "BotLinkedAccount"),
      (j.internalSpec = { type: [1, e.TYPES.ENUM, m] }),
      (K.name = "BotMemoryMetadata"),
      (K.internalSpec = {
        addedFacts: [1, e.FLAGS.REPEATED | e.TYPES.MESSAGE, Q],
        removedFacts: [2, e.FLAGS.REPEATED | e.TYPES.MESSAGE, Q],
        disclaimer: [3, e.TYPES.STRING],
      }),
      (Q.name = "BotMemoryFact"),
      (Q.internalSpec = {
        fact: [1, e.TYPES.STRING],
        factId: [2, e.TYPES.STRING],
      }),
      (X.name = "BotSignatureVerificationMetadata"),
      (X.internalSpec = { proofs: [1, e.FLAGS.REPEATED | e.TYPES.MESSAGE, Y] }),
      (Y.name = "BotSignatureVerificationUseCaseProof"),
      (Y.internalSpec = {
        version: [1, e.TYPES.INT32],
        useCase: [2, e.TYPES.ENUM, p],
        signature: [3, e.TYPES.BYTES],
        certificateChain: [4, e.FLAGS.REPEATED | e.TYPES.BYTES],
      }),
      (J.name = "BotPromotionMessageMetadata"),
      (J.internalSpec = {
        promotionType: [1, e.TYPES.ENUM, _],
        buttonTitle: [2, e.TYPES.STRING],
      }),
      (Z.name = "BotRenderingMetadata"),
      (Z.internalSpec = {
        keywords: [1, e.FLAGS.REPEATED | e.TYPES.MESSAGE, ee],
      }),
      (ee.name = "BotRenderingMetadata$Keyword"),
      (ee.internalSpec = {
        value: [1, e.TYPES.STRING],
        associatedPrompts: [2, e.FLAGS.REPEATED | e.TYPES.STRING],
      }),
      (te.name = "BotMetricsMetadata"),
      (te.internalSpec = {
        destinationId: [1, e.TYPES.STRING],
        destinationEntryPoint: [2, e.TYPES.ENUM, f],
        threadOrigin: [3, e.TYPES.ENUM, g],
      }),
      (ne.name = "BotSessionMetadata"),
      (ne.internalSpec = {
        sessionId: [1, e.TYPES.STRING],
        sessionSource: [2, e.TYPES.ENUM, h],
      }),
      (re.name = "BotMediaMetadata"),
      (re.internalSpec = {
        fileSha256: [1, e.TYPES.STRING],
        mediaKey: [2, e.TYPES.STRING],
        fileEncSha256: [3, e.TYPES.STRING],
        directPath: [4, e.TYPES.STRING],
        mediaKeyTimestamp: [5, e.TYPES.INT64],
        mimetype: [6, e.TYPES.STRING],
        orientationType: [7, e.TYPES.ENUM, y],
      }),
      (oe.name = "BotMemuMetadata"),
      (oe.internalSpec = {
        faceImages: [1, e.FLAGS.REPEATED | e.TYPES.MESSAGE, re],
      }),
      (ae.name = "BotReminderMetadata"),
      (ae.internalSpec = {
        requestMessageKey: [1, e.TYPES.MESSAGE, s.MessageKeySpec],
        action: [2, e.TYPES.ENUM, b],
        name: [3, e.TYPES.STRING],
        nextTriggerTimestamp: [4, e.TYPES.UINT64],
        frequency: [5, e.TYPES.ENUM, C],
      }),
      (ie.name = "BotModelMetadata"),
      (ie.internalSpec = {
        modelType: [1, e.TYPES.ENUM, S],
        premiumModelStatus: [2, e.TYPES.ENUM, v],
        modelNameOverride: [3, e.TYPES.STRING],
      }),
      (le.name = "BotProgressIndicatorMetadata"),
      (le.internalSpec = {
        progressDescription: [1, e.TYPES.STRING],
        stepsMetadata: [2, e.FLAGS.REPEATED | e.TYPES.MESSAGE, se],
        estimatedCompletionTime: [3, e.TYPES.INT64],
      }),
      (se.name = "BotProgressIndicatorMetadata$BotPlanningStepMetadata"),
      (se.internalSpec = {
        statusTitle: [1, e.TYPES.STRING],
        statusBody: [2, e.TYPES.STRING],
        sourcesMetadata: [3, e.FLAGS.REPEATED | e.TYPES.MESSAGE, de],
        status: [4, e.TYPES.ENUM, E],
        isReasoning: [5, e.TYPES.BOOL],
        isEnhancedSearch: [6, e.TYPES.BOOL],
        sections: [7, e.FLAGS.REPEATED | e.TYPES.MESSAGE, ue],
      }),
      (ue.name =
        "BotProgressIndicatorMetadata$BotPlanningStepMetadata$BotPlanningStepSectionMetadata"),
      (ue.internalSpec = {
        sectionTitle: [1, e.TYPES.STRING],
        sectionBody: [2, e.TYPES.STRING],
        sourcesMetadata: [3, e.FLAGS.REPEATED | e.TYPES.MESSAGE, ce],
      }),
      (ce.name =
        "BotProgressIndicatorMetadata$BotPlanningStepMetadata$BotPlanningSearchSourceMetadata"),
      (ce.internalSpec = {
        title: [1, e.TYPES.STRING],
        provider: [2, e.TYPES.ENUM, L],
        sourceUrl: [3, e.TYPES.STRING],
        favIconUrl: [4, e.TYPES.STRING],
      }),
      (de.name =
        "BotProgressIndicatorMetadata$BotPlanningStepMetadata$BotPlanningSearchSourcesMetadata"),
      (de.internalSpec = {
        sourceTitle: [1, e.TYPES.STRING],
        provider: [2, e.TYPES.ENUM, R],
        sourceUrl: [3, e.TYPES.STRING],
      }),
      (me.name = "BotCapabilityMetadata"),
      (me.internalSpec = {
        capabilities: [1, e.FLAGS.REPEATED | e.TYPES.ENUM, k],
      }),
      (pe.name = "BotModeSelectionMetadata"),
      (pe.internalSpec = {
        mode: [1, e.FLAGS.REPEATED | e.TYPES.ENUM, I],
        overrideMode: [2, e.FLAGS.REPEATED | e.TYPES.UINT32],
      }),
      (_e.name = "BotQuotaMetadata"),
      (_e.internalSpec = {
        botFeatureQuotaMetadata: [1, e.FLAGS.REPEATED | e.TYPES.MESSAGE, fe],
      }),
      (fe.name = "BotQuotaMetadata$BotFeatureQuotaMetadata"),
      (fe.internalSpec = {
        featureType: [1, e.TYPES.ENUM, T],
        remainingQuota: [2, e.TYPES.UINT32],
        expirationTimestamp: [3, e.TYPES.UINT64],
      }),
      (ge.name = "BotImagineMetadata"),
      (ge.internalSpec = {
        imagineType: [1, e.TYPES.ENUM, D],
        shortPrompt: [2, e.TYPES.STRING],
      }),
      (he.name = "BotAgeCollectionMetadata"),
      (he.internalSpec = {
        ageCollectionEligible: [1, e.TYPES.BOOL],
        shouldTriggerAgeCollectionOnClient: [2, e.TYPES.BOOL],
        ageCollectionType: [3, e.TYPES.ENUM, x],
      }),
      (ye.name = "BotSourcesMetadata"),
      (ye.internalSpec = {
        sources: [1, e.FLAGS.REPEATED | e.TYPES.MESSAGE, Ce],
      }),
      (Ce.name = "BotSourcesMetadata$BotSourceItem"),
      (Ce.internalSpec = {
        provider: [1, e.TYPES.ENUM, $],
        thumbnailCdnUrl: [2, e.TYPES.STRING],
        sourceProviderUrl: [3, e.TYPES.STRING],
        sourceQuery: [4, e.TYPES.STRING],
        faviconCdnUrl: [5, e.TYPES.STRING],
        citationNumber: [6, e.TYPES.UINT32],
        sourceTitle: [7, e.TYPES.STRING],
      }),
      (be.name = "InThreadSurveyMetadata"),
      (be.internalSpec = {
        tessaSessionId: [1, e.TYPES.STRING],
        simonSessionId: [2, e.TYPES.STRING],
        simonSurveyId: [3, e.TYPES.STRING],
        tessaRootId: [4, e.TYPES.STRING],
        requestId: [5, e.TYPES.STRING],
        tessaEvent: [6, e.TYPES.STRING],
        invitationHeaderText: [7, e.TYPES.STRING],
        invitationBodyText: [8, e.TYPES.STRING],
        invitationCtaText: [9, e.TYPES.STRING],
        invitationCtaUrl: [10, e.TYPES.STRING],
        surveyTitle: [11, e.TYPES.STRING],
        questions: [12, e.FLAGS.REPEATED | e.TYPES.MESSAGE, Re],
        surveyContinueButtonText: [13, e.TYPES.STRING],
        surveySubmitButtonText: [14, e.TYPES.STRING],
        privacyStatementFull: [15, e.TYPES.STRING],
        privacyStatementParts: [16, e.FLAGS.REPEATED | e.TYPES.MESSAGE, ve],
        feedbackToastText: [17, e.TYPES.STRING],
        startQuestionIndex: [18, e.TYPES.INT32],
      }),
      (ve.name = "InThreadSurveyMetadata$InThreadSurveyPrivacyStatementPart"),
      (ve.internalSpec = {
        text: [1, e.TYPES.STRING],
        url: [2, e.TYPES.STRING],
      }),
      (Se.name = "InThreadSurveyMetadata$InThreadSurveyOption"),
      (Se.internalSpec = {
        stringValue: [1, e.TYPES.STRING],
        numericValue: [2, e.TYPES.UINT32],
        textTranslated: [3, e.TYPES.STRING],
      }),
      (Re.name = "InThreadSurveyMetadata$InThreadSurveyQuestion"),
      (Re.internalSpec = {
        questionText: [1, e.TYPES.STRING],
        questionId: [2, e.TYPES.STRING],
        questionOptions: [3, e.FLAGS.REPEATED | e.TYPES.MESSAGE, Se],
      }),
      (Le.name = "BotMessageOriginMetadata"),
      (Le.internalSpec = {
        origins: [1, e.FLAGS.REPEATED | e.TYPES.MESSAGE, Ee],
      }),
      (Ee.name = "BotMessageOrigin"),
      (Ee.internalSpec = { type: [1, e.TYPES.ENUM, P] }),
      (ke.name = "BotUnifiedResponseMutation"),
      (ke.internalSpec = {
        sbsMetadata: [1, e.TYPES.MESSAGE, Te],
        mediaDetailsMetadataList: [2, e.FLAGS.REPEATED | e.TYPES.MESSAGE, Ie],
      }),
      (Ie.name = "BotUnifiedResponseMutation$MediaDetailsMetadata"),
      (Ie.internalSpec = {
        id: [1, e.TYPES.STRING],
        highResMedia: [2, e.TYPES.MESSAGE, re],
        previewMedia: [3, e.TYPES.MESSAGE, re],
      }),
      (Te.name = "BotUnifiedResponseMutation$SideBySideMetadata"),
      (Te.internalSpec = {
        primaryResponseId: [1, e.TYPES.STRING],
        surveyCtaHasRendered: [2, e.TYPES.BOOL],
      }),
      (De.name = "AIThreadInfo"),
      (De.internalSpec = {
        serverInfo: [1, e.TYPES.MESSAGE, $e],
        clientInfo: [2, e.TYPES.MESSAGE, xe],
      }),
      (xe.name = "AIThreadInfo$AIThreadClientInfo"),
      (xe.internalSpec = {
        type: [1, e.TYPES.ENUM, N],
        sourceChatJid: [2, e.TYPES.STRING],
      }),
      ($e.name = "AIThreadInfo$AIThreadServerInfo"),
      ($e.internalSpec = { title: [1, e.TYPES.STRING] }),
      (Pe.name = "AIMediaCollectionMetadata"),
      (Pe.internalSpec = {
        collectionId: [1, e.TYPES.STRING],
        uploadOrderIndex: [2, e.TYPES.UINT32],
      }),
      (Ne.name = "AIMediaCollectionMessage"),
      (Ne.internalSpec = {
        collectionId: [1, e.TYPES.STRING],
        expectedMediaCount: [2, e.TYPES.UINT32],
        hasGlobalCaption: [3, e.TYPES.BOOL],
      }),
      (Me.name = "BotCommandMetadata"),
      (Me.internalSpec = {
        commandName: [1, e.TYPES.STRING],
        commandDescription: [2, e.TYPES.STRING],
        commandPrompt: [3, e.TYPES.STRING],
      }),
      (we.name = "BotMetadata"),
      (we.internalSpec = {
        personaId: [2, e.TYPES.STRING],
        pluginMetadata: [3, e.TYPES.MESSAGE, U],
        suggestedPromptMetadata: [4, e.TYPES.MESSAGE, V],
        invokerJid: [5, e.TYPES.STRING],
        sessionMetadata: [6, e.TYPES.MESSAGE, ne],
        memuMetadata: [7, e.TYPES.MESSAGE, oe],
        timezone: [8, e.TYPES.STRING],
        reminderMetadata: [9, e.TYPES.MESSAGE, ae],
        modelMetadata: [10, e.TYPES.MESSAGE, ie],
        messageDisclaimerText: [11, e.TYPES.STRING],
        progressIndicatorMetadata: [12, e.TYPES.MESSAGE, le],
        capabilityMetadata: [13, e.TYPES.MESSAGE, me],
        imagineMetadata: [14, e.TYPES.MESSAGE, ge],
        memoryMetadata: [15, e.TYPES.MESSAGE, K],
        renderingMetadata: [16, e.TYPES.MESSAGE, Z],
        botMetricsMetadata: [17, e.TYPES.MESSAGE, te],
        botLinkedAccountsMetadata: [18, e.TYPES.MESSAGE, z],
        richResponseSourcesMetadata: [19, e.TYPES.MESSAGE, ye],
        aiConversationContext: [20, e.TYPES.BYTES],
        botPromotionMessageMetadata: [21, e.TYPES.MESSAGE, J],
        botModeSelectionMetadata: [22, e.TYPES.MESSAGE, pe],
        botQuotaMetadata: [23, e.TYPES.MESSAGE, _e],
        botAgeCollectionMetadata: [24, e.TYPES.MESSAGE, he],
        conversationStarterPromptId: [25, e.TYPES.STRING],
        botResponseId: [26, e.TYPES.STRING],
        verificationMetadata: [27, e.TYPES.MESSAGE, X],
        unifiedResponseMutation: [28, e.TYPES.MESSAGE, ke],
        botMessageOriginMetadata: [29, e.TYPES.MESSAGE, Le],
        inThreadSurveyMetadata: [30, e.TYPES.MESSAGE, be],
        botThreadInfo: [31, e.TYPES.MESSAGE, De],
        regenerateMetadata: [32, e.TYPES.MESSAGE, Ye],
        sessionTransparencyMetadata: [33, e.TYPES.MESSAGE, Je],
        botDocumentMessageMetadata: [34, e.TYPES.MESSAGE, Ze],
        botGroupMetadata: [35, e.TYPES.MESSAGE, Ae],
        botRenderingConfigMetadata: [36, e.TYPES.MESSAGE, Fe],
        botInfrastructureDiagnostics: [37, e.TYPES.MESSAGE, nt],
        aiMediaCollectionMetadata: [38, e.TYPES.MESSAGE, Pe],
        commandMetadata: [39, e.TYPES.MESSAGE, Me],
        internalMetadata: [999, e.TYPES.BYTES],
      }),
      (Ae.name = "BotGroupMetadata"),
      (Ae.internalSpec = {
        participantsMetadata: [1, e.FLAGS.REPEATED | e.TYPES.MESSAGE, Oe],
      }),
      (Fe.name = "BotRenderingConfigMetadata"),
      (Fe.internalSpec = {
        bloksVersioningId: [1, e.TYPES.STRING],
        pixelDensity: [2, e.TYPES.DOUBLE],
      }),
      (Oe.name = "BotGroupParticipantMetadata"),
      (Oe.internalSpec = { botFbid: [1, e.TYPES.STRING] }),
      (Be.name = "BotFeedbackMessage"),
      (Be.internalSpec = {
        messageKey: [1, e.TYPES.MESSAGE, s.MessageKeySpec],
        kind: [2, e.TYPES.ENUM, F],
        text: [3, e.TYPES.STRING],
        kindNegative: [4, e.TYPES.UINT64],
        kindPositive: [5, e.TYPES.UINT64],
        kindReport: [6, e.TYPES.ENUM, M],
        sideBySideSurveyMetadata: [7, e.TYPES.MESSAGE, We],
      }),
      (We.name = "BotFeedbackMessage$SideBySideSurveyMetadata"),
      (We.internalSpec = {
        selectedRequestId: [1, e.TYPES.STRING],
        surveyId: [2, e.TYPES.UINT32],
        simonSessionFbid: [3, e.TYPES.STRING],
        responseOtid: [4, e.TYPES.STRING],
        responseTimestampMsString: [5, e.TYPES.STRING],
        isSelectedResponsePrimary: [6, e.TYPES.BOOL],
        messageIdToEdit: [7, e.TYPES.STRING],
        analyticsData: [8, e.TYPES.MESSAGE, je],
        metaAiAnalyticsData: [9, e.TYPES.MESSAGE, qe],
      }),
      (qe.name =
        "BotFeedbackMessage$SideBySideSurveyMetadata$SidebySideSurveyMetaAiAnalyticsData"),
      (qe.internalSpec = {
        surveyId: [1, e.TYPES.UINT32],
        primaryResponseId: [2, e.TYPES.STRING],
        testArmName: [3, e.TYPES.STRING],
        timestampMsString: [4, e.TYPES.STRING],
        ctaImpressionEvent: [5, e.TYPES.MESSAGE, ze],
        ctaClickEvent: [6, e.TYPES.MESSAGE, Ge],
        cardImpressionEvent: [7, e.TYPES.MESSAGE, He],
        responseEvent: [8, e.TYPES.MESSAGE, Ve],
        abandonEvent: [9, e.TYPES.MESSAGE, Ue],
      }),
      (Ue.name =
        "BotFeedbackMessage$SideBySideSurveyMetadata$SidebySideSurveyMetaAiAnalyticsData$SideBySideSurveyAbandonEventData"),
      (Ue.internalSpec = { abandonDwellTimeMsString: [1, e.TYPES.STRING] }),
      (Ve.name =
        "BotFeedbackMessage$SideBySideSurveyMetadata$SidebySideSurveyMetaAiAnalyticsData$SideBySideSurveyResponseEventData"),
      (Ve.internalSpec = {
        responseDwellTimeMsString: [1, e.TYPES.STRING],
        selectedResponseId: [2, e.TYPES.STRING],
      }),
      (He.name =
        "BotFeedbackMessage$SideBySideSurveyMetadata$SidebySideSurveyMetaAiAnalyticsData$SideBySideSurveyCardImpressionEventData"),
      (He.internalSpec = {}),
      (Ge.name =
        "BotFeedbackMessage$SideBySideSurveyMetadata$SidebySideSurveyMetaAiAnalyticsData$SideBySideSurveyCTAClickEventData"),
      (Ge.internalSpec = {
        isSurveyExpired: [1, e.TYPES.BOOL],
        clickDwellTimeMsString: [2, e.TYPES.STRING],
      }),
      (ze.name =
        "BotFeedbackMessage$SideBySideSurveyMetadata$SidebySideSurveyMetaAiAnalyticsData$SideBySideSurveyCTAImpressionEventData"),
      (ze.internalSpec = { isSurveyExpired: [1, e.TYPES.BOOL] }),
      (je.name =
        "BotFeedbackMessage$SideBySideSurveyMetadata$SideBySideSurveyAnalyticsData"),
      (je.internalSpec = {
        tessaEvent: [1, e.TYPES.STRING],
        tessaSessionFbid: [2, e.TYPES.STRING],
        simonSessionFbid: [3, e.TYPES.STRING],
      }),
      (Ke.name = "ForwardedAIBotMessageInfo"),
      (Ke.internalSpec = {
        botName: [1, e.TYPES.STRING],
        botJid: [2, e.TYPES.STRING],
        creatorName: [3, e.TYPES.STRING],
      }),
      (Qe.name = "BotMessageSharingInfo"),
      (Qe.internalSpec = {
        botEntryPointOrigin: [1, e.TYPES.ENUM, f],
        forwardScore: [2, e.TYPES.UINT32],
      }),
      (Xe.name = "AIRichResponseUnifiedResponse"),
      (Xe.internalSpec = { data: [1, e.TYPES.BYTES] }),
      (Ye.name = "AIRegenerateMetadata"),
      (Ye.internalSpec = {
        messageKey: [1, e.TYPES.MESSAGE, s.MessageKeySpec],
        responseTimestampMs: [2, e.TYPES.INT64],
      }),
      (Je.name = "SessionTransparencyMetadata"),
      (Je.internalSpec = {
        disclaimerText: [1, e.TYPES.STRING],
        hcaId: [2, e.TYPES.STRING],
        sessionTransparencyType: [3, e.TYPES.ENUM, W],
      }),
      (Ze.name = "BotDocumentMessageMetadata"),
      (Ze.internalSpec = { pluginType: [1, e.TYPES.ENUM, O] }),
      (et.name = "AIHomeState"),
      (et.internalSpec = {
        lastFetchTime: [1, e.TYPES.INT64],
        capabilityOptions: [2, e.FLAGS.REPEATED | e.TYPES.MESSAGE, tt],
        conversationOptions: [3, e.FLAGS.REPEATED | e.TYPES.MESSAGE, tt],
      }),
      (tt.name = "AIHomeState$AIHomeOption"),
      (tt.internalSpec = {
        type: [1, e.TYPES.ENUM, B],
        title: [2, e.TYPES.STRING],
        promptText: [3, e.TYPES.STRING],
        sessionId: [4, e.TYPES.STRING],
        imageWdsIdentifier: [5, e.TYPES.STRING],
        imageTintColor: [6, e.TYPES.STRING],
        imageBackgroundColor: [7, e.TYPES.STRING],
        cardTypeId: [8, e.TYPES.STRING],
      }),
      (nt.name = "BotInfrastructureDiagnostics"),
      (nt.internalSpec = {
        botBackend: [1, e.TYPES.ENUM, q],
        toolsUsed: [2, e.FLAGS.REPEATED | e.TYPES.STRING],
        isThinking: [3, e.TYPES.BOOL],
      }),
      (rt.name = "BotAgentMetadata"),
      (rt.internalSpec = { deepLinkMetadata: [1, e.TYPES.MESSAGE, ot] }),
      (ot.name = "BotAgentDeepLinkMetadata"),
      (ot.internalSpec = { token: [1, e.TYPES.STRING] }),
      (l.BotPluginMetadata$PluginType = c),
      (l.BotPluginMetadata$SearchProvider = d),
      (l.BotLinkedAccount$BotLinkedAccountType = m),
      (l.BotSignatureVerificationUseCaseProof$BotSignatureUseCase = p),
      (l.BotPromotionMessageMetadata$BotPromotionType = _),
      (l.BotMetricsEntryPoint = f),
      (l.BotMetricsThreadEntryPoint = g),
      (l.BotSessionSource = h),
      (l.BotMediaMetadata$OrientationType = y),
      (l.BotReminderMetadata$ReminderFrequency = C),
      (l.BotReminderMetadata$ReminderAction = b),
      (l.BotModelMetadata$PremiumModelStatus = v),
      (l.BotModelMetadata$ModelType = S),
      (l.BotProgressIndicatorMetadata$BotPlanningStepMetadata$BotPlanningSearchSourcesMetadata$BotPlanningSearchSourceProvider =
        R),
      (l.BotProgressIndicatorMetadata$BotPlanningStepMetadata$BotSearchSourceProvider =
        L),
      (l.BotProgressIndicatorMetadata$BotPlanningStepMetadata$PlanningStepStatus =
        E),
      (l.BotCapabilityMetadata$BotCapabilityType = k),
      (l.BotModeSelectionMetadata$BotUserSelectionMode = I),
      (l.BotQuotaMetadata$BotFeatureQuotaMetadata$BotFeatureType = T),
      (l.BotImagineMetadata$ImagineType = D),
      (l.BotAgeCollectionMetadata$AgeCollectionType = x),
      (l.BotSourcesMetadata$BotSourceItem$SourceProvider = $),
      (l.BotMessageOrigin$BotMessageOriginType = P),
      (l.AIThreadInfo$AIThreadClientInfo$AIThreadType = N),
      (l.BotFeedbackMessage$ReportKind = M),
      (l.BotFeedbackMessage$BotFeedbackKindMultiplePositive = w),
      (l.BotFeedbackMessage$BotFeedbackKindMultipleNegative = A),
      (l.BotFeedbackMessage$BotFeedbackKind = F),
      (l.BotDocumentMessageMetadata$DocumentPluginType = O),
      (l.AIHomeState$AIHomeOption$AIHomeActionType = B),
      (l.SessionTransparencyType = W),
      (l.BotInfrastructureDiagnostics$BotBackend = q),
      (l.BotPluginMetadataSpec = U),
      (l.BotSuggestedPromptMetadataSpec = V),
      (l.BotPromptSuggestionsSpec = H),
      (l.BotPromptSuggestionSpec = G),
      (l.BotLinkedAccountsMetadataSpec = z),
      (l.BotLinkedAccountSpec = j),
      (l.BotMemoryMetadataSpec = K),
      (l.BotMemoryFactSpec = Q),
      (l.BotSignatureVerificationMetadataSpec = X),
      (l.BotSignatureVerificationUseCaseProofSpec = Y),
      (l.BotPromotionMessageMetadataSpec = J),
      (l.BotRenderingMetadataSpec = Z),
      (l.BotRenderingMetadata$KeywordSpec = ee),
      (l.BotMetricsMetadataSpec = te),
      (l.BotSessionMetadataSpec = ne),
      (l.BotMediaMetadataSpec = re),
      (l.BotMemuMetadataSpec = oe),
      (l.BotReminderMetadataSpec = ae),
      (l.BotModelMetadataSpec = ie),
      (l.BotProgressIndicatorMetadataSpec = le),
      (l.BotProgressIndicatorMetadata$BotPlanningStepMetadataSpec = se),
      (l.BotProgressIndicatorMetadata$BotPlanningStepMetadata$BotPlanningStepSectionMetadataSpec =
        ue),
      (l.BotProgressIndicatorMetadata$BotPlanningStepMetadata$BotPlanningSearchSourceMetadataSpec =
        ce),
      (l.BotProgressIndicatorMetadata$BotPlanningStepMetadata$BotPlanningSearchSourcesMetadataSpec =
        de),
      (l.BotCapabilityMetadataSpec = me),
      (l.BotModeSelectionMetadataSpec = pe),
      (l.BotQuotaMetadataSpec = _e),
      (l.BotQuotaMetadata$BotFeatureQuotaMetadataSpec = fe),
      (l.BotImagineMetadataSpec = ge),
      (l.BotAgeCollectionMetadataSpec = he),
      (l.BotSourcesMetadataSpec = ye),
      (l.BotSourcesMetadata$BotSourceItemSpec = Ce),
      (l.InThreadSurveyMetadataSpec = be),
      (l.InThreadSurveyMetadata$InThreadSurveyPrivacyStatementPartSpec = ve),
      (l.InThreadSurveyMetadata$InThreadSurveyOptionSpec = Se),
      (l.InThreadSurveyMetadata$InThreadSurveyQuestionSpec = Re),
      (l.BotMessageOriginMetadataSpec = Le),
      (l.BotMessageOriginSpec = Ee),
      (l.BotUnifiedResponseMutationSpec = ke),
      (l.BotUnifiedResponseMutation$MediaDetailsMetadataSpec = Ie),
      (l.BotUnifiedResponseMutation$SideBySideMetadataSpec = Te),
      (l.AIThreadInfoSpec = De),
      (l.AIThreadInfo$AIThreadClientInfoSpec = xe),
      (l.AIThreadInfo$AIThreadServerInfoSpec = $e),
      (l.AIMediaCollectionMetadataSpec = Pe),
      (l.AIMediaCollectionMessageSpec = Ne),
      (l.BotCommandMetadataSpec = Me),
      (l.BotMetadataSpec = we),
      (l.BotGroupMetadataSpec = Ae),
      (l.BotRenderingConfigMetadataSpec = Fe),
      (l.BotGroupParticipantMetadataSpec = Oe),
      (l.BotFeedbackMessageSpec = Be),
      (l.BotFeedbackMessage$SideBySideSurveyMetadataSpec = We),
      (l.BotFeedbackMessage$SideBySideSurveyMetadata$SidebySideSurveyMetaAiAnalyticsDataSpec =
        qe),
      (l.BotFeedbackMessage$SideBySideSurveyMetadata$SidebySideSurveyMetaAiAnalyticsData$SideBySideSurveyAbandonEventDataSpec =
        Ue),
      (l.BotFeedbackMessage$SideBySideSurveyMetadata$SidebySideSurveyMetaAiAnalyticsData$SideBySideSurveyResponseEventDataSpec =
        Ve),
      (l.BotFeedbackMessage$SideBySideSurveyMetadata$SidebySideSurveyMetaAiAnalyticsData$SideBySideSurveyCardImpressionEventDataSpec =
        He),
      (l.BotFeedbackMessage$SideBySideSurveyMetadata$SidebySideSurveyMetaAiAnalyticsData$SideBySideSurveyCTAClickEventDataSpec =
        Ge),
      (l.BotFeedbackMessage$SideBySideSurveyMetadata$SidebySideSurveyMetaAiAnalyticsData$SideBySideSurveyCTAImpressionEventDataSpec =
        ze),
      (l.BotFeedbackMessage$SideBySideSurveyMetadata$SideBySideSurveyAnalyticsDataSpec =
        je),
      (l.ForwardedAIBotMessageInfoSpec = Ke),
      (l.BotMessageSharingInfoSpec = Qe),
      (l.AIRichResponseUnifiedResponseSpec = Xe),
      (l.AIRegenerateMetadataSpec = Ye),
      (l.SessionTransparencyMetadataSpec = Je),
      (l.BotDocumentMessageMetadataSpec = Ze),
      (l.AIHomeStateSpec = et),
      (l.AIHomeState$AIHomeOptionSpec = tt),
      (l.BotInfrastructureDiagnosticsSpec = nt),
      (l.BotAgentMetadataSpec = rt),
      (l.BotAgentDeepLinkMetadataSpec = ot));
  },
  98,
);
