__d(
  "WAWebMoment-ga",
  ["WAWeb-moment"],
  function (t, n, r, o, a, i, l) {
    var e = [
        "Ean\xE1ir",
        "Feabhra",
        "M\xE1rta",
        "Aibre\xE1n",
        "Bealtaine",
        "Meitheamh",
        "I\xFAil",
        "L\xFAnasa",
        "Me\xE1n F\xF3mhair",
        "Deireadh F\xF3mhair",
        "Samhain",
        "Nollaig",
      ],
      s = [
        "Ean",
        "Feabh",
        "M\xE1rt",
        "Aib",
        "Beal",
        "Meith",
        "I\xFAil",
        "L\xFAn",
        "M.F.",
        "D.F.",
        "Samh",
        "Noll",
      ],
      u = [
        "D\xE9 Domhnaigh",
        "D\xE9 Luain",
        "D\xE9 M\xE1irt",
        "D\xE9 C\xE9adaoin",
        "D\xE9ardaoin",
        "D\xE9 hAoine",
        "D\xE9 Sathairn",
      ],
      c = ["Domh", "Luan", "M\xE1irt", "C\xE9ad", "D\xE9ar", "Aoine", "Sath"],
      d = ["Do", "Lu", "M\xE1", "C\xE9", "D\xE9", "A", "Sa"],
      m = r("WAWeb-moment").defineLocale("ga", {
        months: e,
        monthsShort: s,
        monthsParseExact: !0,
        weekdays: u,
        weekdaysShort: c,
        weekdaysMin: d,
        longDateFormat: {
          LT: "HH:mm",
          LTS: "HH:mm:ss",
          L: "DD/MM/YYYY",
          LL: "D MMMM YYYY",
          LLL: "D MMMM YYYY HH:mm",
          LLLL: "dddd, D MMMM YYYY HH:mm",
        },
        calendar: {
          sameDay: "[Inniu ag] LT",
          nextDay: "[Am\xE1rach ag] LT",
          nextWeek: "dddd [ag] LT",
          lastDay: "[Inn\xE9 ag] LT",
          lastWeek: "dddd [seo caite] [ag] LT",
          sameElse: "L",
        },
        relativeTime: {
          future: "i %s",
          past: "%s \xF3 shin",
          s: "c\xFApla soicind",
          ss: "%d soicind",
          m: "n\xF3im\xE9ad",
          mm: "%d n\xF3im\xE9ad",
          h: "uair an chloig",
          hh: "%d uair an chloig",
          d: "l\xE1",
          dd: "%d l\xE1",
          M: "m\xED",
          MM: "%d m\xEDonna",
          y: "bliain",
          yy: "%d bliain",
        },
        dayOfMonthOrdinalParse: /\d{1,2}(d|na|mh)/,
        ordinal: function (t) {
          var e = t === 1 ? "d" : t % 10 === 2 ? "na" : "mh";
          return t + e;
        },
        week: { dow: 1, doy: 4 },
      });
  },
  34,
);
