__d(
  "WAWebWamEnumChannelDirectoryAction",
  [],
  function (t, n, r, o, a, i) {
    var e = Object.freeze({
      DIRECTORY_OPEN_TAP: 1,
      DIRECTORY_CLOSED_TAP: 2,
      DIRECTORY_SEARCH_TAP: 3,
      DIRECTORY_SERVER_ERROR: 4,
      DIRECTORY_NAVIGATE_TO_CHANNEL: 5,
      DIRECTORY_RETURN_FROM_CHANNEL: 6,
      DIRECTORY_FOLLOW_TAP: 7,
      DIRECTORY_UNFOLLOW_TAP: 8,
      DIRECTORY_SORT_BY_RECENTLY_ADDED: 9,
      DIRECTORY_SORT_BY_POPULARITY: 10,
      DIRECTORY_SORT_BY_ALPHABETICALLY: 11,
      DIRECTORY_IMP: 12,
      DIRECTORY_SEARCH_IMP: 13,
      DIRECTORY_PILL_SELECTION: 14,
      DIRECTORY_COUNTRY_SELECTION: 15,
      DIRECTORY_CATEGORY_SEE_ALL: 16,
      SEARCH: 17,
      SERP_LOADED: 18,
    });
    i.CHANNEL_DIRECTORY_ACTION = e;
  },
  66,
);
