__d(
  "WAWebDailyWamEvent",
  [
    "WAWebWamCodegenUtils",
    "WAWebWamEnumAndroidKeystoreStateType",
    "WAWebWamEnumBackupEncryptionMethod",
    "WAWebWamEnumBackupNetworkSetting",
    "WAWebWamEnumBackupSchedule",
    "WAWebWamEnumContactsPermissionAuthorizationStatusType",
    "WAWebWamEnumEmailState",
    "WAWebWamEnumGalleryPermissionState",
    "WAWebWamEnumMediaAutoDownloadQuality",
    "WAWebWamEnumMediaQuality",
    "WAWebWamEnumMetaAiModelTierType",
    "WAWebWamEnumNotificationSettingType",
    "WAWebWamEnumPrivacySettingsContactsBuckets",
    "WAWebWamEnumPrivacySettingsValueType",
    "WAWebWamEnumUsernameState",
  ],
  function (t, n, r, o, a, i, l) {
    var e,
      s,
      u,
      c = (e = o("WAWebWamCodegenUtils")).defineEvents(
        {
          Daily: [
            1158,
            {
              accessibilityVoiceover: [108, e.TYPES.BOOLEAN],
              addressbookSize: [11, e.TYPES.INTEGER],
              addressbookWhatsappSize: [12, e.TYPES.INTEGER],
              aiMemorySavedCnt: [223, e.TYPES.INTEGER],
              aiWidgetInstalled: [210, e.TYPES.BOOLEAN],
              androidAdvertisingId: [135, e.TYPES.STRING],
              androidKeystoreState: [
                139,
                o("WAWebWamEnumAndroidKeystoreStateType")
                  .ANDROID_KEYSTORE_STATE_TYPE,
              ],
              appCodeHash: [103, e.TYPES.STRING],
              appLastOpenTimestamp: [212, e.TYPES.INTEGER],
              appStandbyBucket: [121, e.TYPES.INTEGER],
              autoDlAudioCellular: [90, e.TYPES.BOOLEAN],
              autoDlAudioRoaming: [91, e.TYPES.BOOLEAN],
              autoDlAudioWifi: [89, e.TYPES.BOOLEAN],
              autoDlDocCellular: [96, e.TYPES.BOOLEAN],
              autoDlDocRoaming: [97, e.TYPES.BOOLEAN],
              autoDlDocWifi: [95, e.TYPES.BOOLEAN],
              autoDlImageCellular: [87, e.TYPES.BOOLEAN],
              autoDlImageRoaming: [88, e.TYPES.BOOLEAN],
              autoDlImageWifi: [86, e.TYPES.BOOLEAN],
              autoDlVideoCellular: [93, e.TYPES.BOOLEAN],
              autoDlVideoRoaming: [94, e.TYPES.BOOLEAN],
              autoDlVideoWifi: [92, e.TYPES.BOOLEAN],
              backupEncryptionMethod: [
                231,
                o("WAWebWamEnumBackupEncryptionMethod")
                  .BACKUP_ENCRYPTION_METHOD,
              ],
              backupNetworkSetting: [
                10,
                o("WAWebWamEnumBackupNetworkSetting").BACKUP_NETWORK_SETTING,
              ],
              backupRestoreEncryptionVersion: [138, e.TYPES.INTEGER],
              backupSchedule: [
                9,
                o("WAWebWamEnumBackupSchedule").BACKUP_SCHEDULE,
              ],
              canonicalEntLastValidationTsMs: [241, e.TYPES.INTEGER],
              channelsMediaFolderSize: [186, e.TYPES.INTEGER],
              chatDatabaseSize: [19, e.TYPES.INTEGER],
              chatLockFolderCount: [168, e.TYPES.INTEGER],
              contactsCreatedOnWhatsappSize: [200, e.TYPES.INTEGER],
              contactsPermissionAuthorizationStatus: [
                201,
                o("WAWebWamEnumContactsPermissionAuthorizationStatusType")
                  .CONTACTS_PERMISSION_AUTHORIZATION_STATUS_TYPE,
              ],
              contactsRequiringSyncBeforeDisplaySize: [238, e.TYPES.INTEGER],
              count1on1Threads: [216, e.TYPES.INTEGER],
              countEphemeralThreads: [181, e.TYPES.INTEGER],
              countEphemeralThreadsEnabledByMe: [182, e.TYPES.INTEGER],
              countGroupThreads: [217, e.TYPES.INTEGER],
              countLimitSharing1on1Threads: [218, e.TYPES.INTEGER],
              countLimitSharingGroupThreads: [219, e.TYPES.INTEGER],
              dailyPasskeyCount: [247, e.TYPES.INTEGER],
              dbAddressbookTableSize: [206, e.TYPES.INTEGER],
              defaultAfterReadDuration: [248, e.TYPES.INTEGER],
              defaultAfterReadEnabled: [249, e.TYPES.BOOLEAN],
              defaultDisappearingDuration: [140, e.TYPES.INTEGER],
              defenseMode: [214, e.TYPES.INTEGER],
              deprecatedContactsSize: [228, e.TYPES.INTEGER],
              deviceLanguage: [153, e.TYPES.STRING],
              emailState: [174, o("WAWebWamEnumEmailState").EMAIL_STATE],
              entSecurityNotificationsEnabled: [134, e.TYPES.BOOLEAN],
              experimentTmoPreloadGroupDaily: [166, e.TYPES.INTEGER],
              favoritedAnimatedStickerCount: [113, e.TYPES.INTEGER],
              favoritedFirstPartyStickerCount: [112, e.TYPES.INTEGER],
              favoritedTotalStickerCount: [111, e.TYPES.INTEGER],
              galleryPermission: [
                164,
                o("WAWebWamEnumGalleryPermissionState")
                  .GALLERY_PERMISSION_STATE,
              ],
              hasTextstatusEmojiModified24h: [175, e.TYPES.BOOLEAN],
              hasTextstatusModified24h: [176, e.TYPES.BOOLEAN],
              hasTextstatusTextModified24h: [177, e.TYPES.BOOLEAN],
              hasUsername: [187, e.TYPES.BOOLEAN],
              hasUsernamePin: [222, e.TYPES.BOOLEAN],
              inNetworkContactsSize: [190, e.TYPES.INTEGER],
              installedAnimatedStickerPackCount: [116, e.TYPES.INTEGER],
              installedAnimatedThirdPartyStickerPackCount: [
                137,
                e.TYPES.INTEGER,
              ],
              installedFirstPartyStickerPackCount: [115, e.TYPES.INTEGER],
              installedTotalStickerPackCount: [114, e.TYPES.INTEGER],
              isCanonicalEntPresent: [234, e.TYPES.BOOLEAN],
              isContactSyncToOsDefaultOn: [202, e.TYPES.BOOLEAN],
              isDefaultDisappearingMessagingUser: [183, e.TYPES.BOOLEAN],
              isEphemeralMessagingUser: [184, e.TYPES.BOOLEAN],
              isProfilePhotoSet: [195, e.TYPES.BOOLEAN],
              keyboardLanguage: [154, e.TYPES.STRING],
              languageCode: [5, e.TYPES.STRING],
              lastBackupTimestamp: [63, e.TYPES.INTEGER],
              lastCloudBackupSize: [185, e.TYPES.INTEGER],
              locationCode: [6, e.TYPES.STRING],
              lockFolderHidden: [171, e.TYPES.BOOLEAN],
              lowestAppStandbyBucket: [160, e.TYPES.INTEGER],
              mdPairTime: [124, e.TYPES.INTEGER],
              mediaAutoDownloadQualitySetting: [
                244,
                o("WAWebWamEnumMediaAutoDownloadQuality")
                  .MEDIA_AUTO_DOWNLOAD_QUALITY,
              ],
              mediaFolderFileCount: [21, e.TYPES.INTEGER],
              mediaFolderSize: [20, e.TYPES.INTEGER],
              mediaQualitySetting: [
                188,
                o("WAWebWamEnumMediaQuality").MEDIA_QUALITY,
              ],
              mediaSizeCacheAgeSeconds: [239, e.TYPES.INTEGER],
              metaAiModelActual: [
                198,
                o("WAWebWamEnumMetaAiModelTierType").META_AI_MODEL_TIER_TYPE,
              ],
              metaAiModelSelected: [
                199,
                o("WAWebWamEnumMetaAiModelTierType").META_AI_MODEL_TIER_TYPE,
              ],
              metaAiVoiceDefaultOn: [220, e.TYPES.BOOLEAN],
              metaAiVoiceSelection: [221, e.TYPES.STRING],
              modifiedInternalProps: [155, e.TYPES.BOOLEAN],
              nativeContactsGlobalSettingEnabled: [205, e.TYPES.BOOLEAN],
              networkIsRoaming: [7, e.TYPES.BOOLEAN],
              networkOperatorName: [159, e.TYPES.STRING],
              numAccounts: [163, e.TYPES.INTEGER],
              numContactsWithTextstatus24h: [178, e.TYPES.INTEGER],
              numContactsWithTextstatusEmoji24h: [179, e.TYPES.INTEGER],
              numContactsWithTextstatusText24h: [180, e.TYPES.INTEGER],
              numberOfSim: [250, e.TYPES.INTEGER],
              osBuildNumber: [4, e.TYPES.STRING],
              osNotificationSetting: [
                118,
                o("WAWebWamEnumNotificationSettingType")
                  .NOTIFICATION_SETTING_TYPE,
              ],
              outOfNetworkContactsSize: [191, e.TYPES.INTEGER],
              packageName: [102, e.TYPES.STRING],
              passkeyExists: [165, e.TYPES.BOOLEAN],
              paymentsIsEnabled: [100, e.TYPES.BOOLEAN],
              peripheralConnected: [209, e.TYPES.STRING],
              peripheralLinkedProductLine: [229, e.TYPES.STRING],
              permissionAccessCoarseLocation: [57, e.TYPES.INTEGER],
              permissionAccessFineLocation: [58, e.TYPES.INTEGER],
              permissionCamera: [56, e.TYPES.INTEGER],
              permissionContacts: [104, e.TYPES.BOOLEAN],
              permissionReadExternalStorage: [53, e.TYPES.INTEGER],
              permissionRecordAudio: [55, e.TYPES.INTEGER],
              phoneCores: [156, e.TYPES.INTEGER],
              phoneyid: [162, e.TYPES.STRING],
              preloadsAppManagerId: [224, e.TYPES.STRING],
              preloadsAttributionJson: [227, e.TYPES.STRING],
              privacySettingsAbout: [
                141,
                (s = o("WAWebWamEnumPrivacySettingsValueType"))
                  .PRIVACY_SETTINGS_VALUE_TYPE,
              ],
              privacySettingsAboutExceptNum: [
                142,
                (u = o("WAWebWamEnumPrivacySettingsContactsBuckets"))
                  .PRIVACY_SETTINGS_CONTACTS_BUCKETS,
              ],
              privacySettingsCoverPhoto: [235, s.PRIVACY_SETTINGS_VALUE_TYPE],
              privacySettingsGroups: [143, s.PRIVACY_SETTINGS_VALUE_TYPE],
              privacySettingsGroupsExceptNum: [
                144,
                u.PRIVACY_SETTINGS_CONTACTS_BUCKETS,
              ],
              privacySettingsLastSeen: [145, s.PRIVACY_SETTINGS_VALUE_TYPE],
              privacySettingsLastSeenExceptNum: [
                146,
                u.PRIVACY_SETTINGS_CONTACTS_BUCKETS,
              ],
              privacySettingsProfileLinks: [225, s.PRIVACY_SETTINGS_VALUE_TYPE],
              privacySettingsProfileLinksExceptNum: [
                226,
                u.PRIVACY_SETTINGS_CONTACTS_BUCKETS,
              ],
              privacySettingsProfilePhoto: [147, s.PRIVACY_SETTINGS_VALUE_TYPE],
              privacySettingsProfilePhotoExceptNum: [
                148,
                u.PRIVACY_SETTINGS_CONTACTS_BUCKETS,
              ],
              privacySettingsStatus: [150, s.PRIVACY_SETTINGS_VALUE_TYPE],
              privacySettingsStatusExceptNum: [
                151,
                u.PRIVACY_SETTINGS_CONTACTS_BUCKETS,
              ],
              privacySettingsStatusShareNum: [
                152,
                u.PRIVACY_SETTINGS_CONTACTS_BUCKETS,
              ],
              profileLinksCount: [211, e.TYPES.INTEGER],
              receiptsEnabled: [8, e.TYPES.BOOLEAN],
              secretCodeActive: [172, e.TYPES.BOOLEAN],
              showMetaAiButtonSetting: [173, e.TYPES.BOOLEAN],
              simMcc: [2, e.TYPES.INTEGER],
              simMnc: [3, e.TYPES.INTEGER],
              simPhoneNumberMatched: [243, e.TYPES.INTEGER],
              storageAvailSize: [31, e.TYPES.INTEGER],
              storageAvailSizeWithCache: [136, e.TYPES.INTEGER],
              storageTotalSize: [32, e.TYPES.INTEGER],
              supportedDecoders: [169, e.TYPES.STRING],
              supportedEncoders: [170, e.TYPES.STRING],
              syncedInNetworkContactsSize: [192, e.TYPES.INTEGER],
              totalCountInNetworkUniquePhoneNumber: [193, e.TYPES.INTEGER],
              totalCountSyncedInNetworkUniquePhoneNumber: [
                194,
                e.TYPES.INTEGER,
              ],
              totalMissedCalls: [232, e.TYPES.INTEGER],
              totalUnreadMessages: [233, e.TYPES.INTEGER],
              traceIdInt: [240, e.TYPES.INTEGER],
              trafficAnonymization: [215, e.TYPES.INTEGER],
              uniquePhoneNumberContactsSizeWithUsername: [236, e.TYPES.INTEGER],
              unreadBadgeFrequency: [213, e.TYPES.INTEGER],
              unverifiedProfileLinksCount: [245, e.TYPES.INTEGER],
              usernameOnlyContactsSize: [237, e.TYPES.INTEGER],
              usernameState: [
                242,
                o("WAWebWamEnumUsernameState").USERNAME_STATE,
              ],
              verifiedProfileLinksCount: [246, e.TYPES.INTEGER],
              videoFolderFileCount: [23, e.TYPES.INTEGER],
              videoFolderSize: [22, e.TYPES.INTEGER],
              webcContactsTableSize: [207, e.TYPES.INTEGER],
              webcFilteredContactsSize: [208, e.TYPES.INTEGER],
            },
            [1, 1, 1],
            "regular",
          ],
        },
        { Daily: [] },
      );
    l.DailyWamEvent = c;
  },
  98,
);
