__d(
  "WAWebMexFetchNewsletterDirectorySearchResultsJobQuery.graphql",
  [],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = (function () {
      var e = {
          defaultValue: null,
          kind: "LocalArgument",
          name: "fetch_status_metadata",
        },
        t = { defaultValue: null, kind: "LocalArgument", name: "input" },
        n = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "id",
          storageKey: null,
        },
        r = [
          n,
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "text",
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "update_time",
            storageKey: null,
          },
        ],
        o = [
          {
            alias: null,
            args: [{ kind: "Variable", name: "input", variableName: "input" }],
            concreteType: "XWA2NewsletterSearchResponse",
            kind: "LinkedField",
            name: "xwa2_newsletters_directory_search",
            plural: !1,
            selections: [
              {
                alias: null,
                args: null,
                concreteType: "XWA2PageInfo",
                kind: "LinkedField",
                name: "page_info",
                plural: !1,
                selections: [
                  {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "hasNextPage",
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "hasPreviousPage",
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "startCursor",
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "endCursor",
                    storageKey: null,
                  },
                ],
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                concreteType: "XWA2Newsletter",
                kind: "LinkedField",
                name: "result",
                plural: !0,
                selections: [
                  n,
                  {
                    alias: null,
                    args: null,
                    concreteType: "XWA2NewsletterThreadMetadata",
                    kind: "LinkedField",
                    name: "thread_metadata",
                    plural: !1,
                    selections: [
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "creation_time",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "invite",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "handle",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "subscribers_count",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        concreteType: "XWA2NewsletterName",
                        kind: "LinkedField",
                        name: "name",
                        plural: !1,
                        selections: r,
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        concreteType: "XWA2NewsletterDescription",
                        kind: "LinkedField",
                        name: "description",
                        plural: !1,
                        selections: r,
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: [
                          { kind: "Literal", name: "type", value: "PREVIEW" },
                        ],
                        concreteType: "XWA2Picture",
                        kind: "LinkedField",
                        name: "picture",
                        plural: !1,
                        selections: [
                          n,
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "direct_path",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "type",
                            storageKey: null,
                          },
                        ],
                        storageKey: 'picture(type:"PREVIEW")',
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "verification",
                        storageKey: null,
                      },
                    ],
                    storageKey: null,
                  },
                  {
                    condition: "fetch_status_metadata",
                    kind: "Condition",
                    passingValue: !0,
                    selections: [
                      {
                        alias: null,
                        args: null,
                        concreteType: "XWA2NewsletterStatusMetadata",
                        kind: "LinkedField",
                        name: "status_metadata",
                        plural: !1,
                        selections: [
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "last_status_server_id",
                            storageKey: null,
                          },
                          {
                            alias: null,
                            args: null,
                            kind: "ScalarField",
                            name: "last_status_sent_time",
                            storageKey: null,
                          },
                        ],
                        storageKey: null,
                      },
                    ],
                  },
                ],
                storageKey: null,
              },
            ],
            storageKey: null,
          },
        ];
      return {
        fragment: {
          argumentDefinitions: [e, t],
          kind: "Fragment",
          metadata: null,
          name: "WAWebMexFetchNewsletterDirectorySearchResultsJobQuery",
          selections: o,
          type: "Query",
          abstractKey: null,
        },
        kind: "Request",
        operation: {
          argumentDefinitions: [t, e],
          kind: "Operation",
          name: "WAWebMexFetchNewsletterDirectorySearchResultsJobQuery",
          selections: o,
        },
        params: {
          id: "26301059626252132",
          metadata: {},
          name: "WAWebMexFetchNewsletterDirectorySearchResultsJobQuery",
          operationKind: "query",
          text: null,
        },
      };
    })();
    a.exports = e;
  },
  null,
);
