__d(
  "WAWebWamEnumMessageContextMenuOptionType",
  [],
  function (t, n, r, o, a, i) {
    var e = Object.freeze({
      UNKNOWN: 1,
      OVERFLOW: 2,
      FORWARD: 3,
      DELETE: 4,
      REPLY: 5,
      REPLY_PRIVATELY: 6,
      STAR_OR_UNSTAR: 7,
      COPY: 8,
      REPORT: 9,
      MESSAGE_CONTACT: 10,
      MESSAGE_INFO: 11,
      EDIT: 12,
      FORWARD_SELECT_MESSAGES: 13,
      DELETE_SELECT_MESSAGES: 14,
      SELECT: 15,
      ADD_TO_CALENDAR: 16,
      COPY_LINK_URL: 17,
      REACT: 18,
      DOWNLOAD: 19,
      KEEP_OR_UNKEEP: 20,
      FAVORITE_OR_UNFAVORITE_STICKER: 21,
      COPY_STICKER: 22,
      VIEW_STICKER_PACK: 23,
      DOWNLOAD_ALL: 24,
      SAVE_AS: 25,
      SHARE: 26,
      PIN_OR_UNPIN: 27,
      ASK_META_AI: 28,
      BOT_FEEDBACK: 29,
      REPORT_TO_ADMIN: 30,
      COPY_NEWSLETTER_LINK: 31,
      PAID_PARTNERSHIP: 32,
      VERIFY_SECURITY_CODE: 33,
      ADD_TO_NOTE: 34,
    });
    i.MESSAGE_CONTEXT_MENU_OPTION_TYPE = e;
  },
  66,
);
