__d(
  "WAWebVoipSplitButton.react",
  [
    "WAWebFlex.react",
    "WAWebUnstyledButton.react",
    "WAWebVoipUiPopoutWindowContext",
    "WDSIconIcArrowDropDown.react",
    "WDSTooltip.react",
    "WDSVars.stylex",
    "react",
  ],
  function (t, n, r, o, a, i, l) {
    "use strict";
    var e,
      s = e || (e = o("react")),
      u = e.useContext,
      c = {
        splitButton: {
          backgroundColor: "x1od0jb8",
          borderTopColor: "x1v8p93f",
          borderInlineEndColor: "x1o3jo1z",
          borderBottomColor: "x16stqrj",
          borderInlineStartColor: "xv5lvn5",
          borderStartStartRadius: "xt8t1vi",
          borderStartEndRadius: "x1xc408v",
          borderEndEndRadius: "x129tdwq",
          borderEndStartRadius: "x15urzxu",
          borderTopStyle: "x1ejq31n",
          borderInlineEndStyle: "x18oe1m7",
          borderBottomStyle: "x1sy0etr",
          borderInlineStartStyle: "xstzfhl",
          borderTopWidth: "x972fbf",
          borderInlineEndWidth: "x10w94by",
          borderBottomWidth: "x1qhh985",
          borderInlineStartWidth: "x14e42zd",
          cursor: "x1ypdohk",
          height: "x1vqgdyp",
          overflowX: "x6ikm8r",
          overflowY: "x10wlt62",
          color: "x17t9dm2",
          $$css: !0,
        },
        splitButtonSmall: { height: "x10w6t97", $$css: !0 },
        mutedSplitButton: {
          backgroundColor: "x1p8t8ri",
          color: "x1lljey2",
          $$css: !0,
        },
        splitButtonLeft: {
          borderStartStartRadius: "xt8t1vi",
          borderEndStartRadius: "x15urzxu",
          borderStartEndRadius: "x17un8ov",
          borderEndEndRadius: "x1e7945m",
          height: "x1vqgdyp",
          paddingInlineStart: "x1iw51ew",
          paddingInlineEnd: "x1uc92m",
          $$css: !0,
        },
        splitButtonLeftSmall: {
          height: "x10w6t97",
          paddingInlineEnd: "x1j8ymqv",
          $$css: !0,
        },
        splitButtonRight: {
          borderStartStartRadius: "x1bczwif",
          borderEndStartRadius: "x11o6v7j",
          borderStartEndRadius: "x1xc408v",
          borderEndEndRadius: "x129tdwq",
          height: "x1vqgdyp",
          width: "xezivpi",
          paddingInlineStart: "x1c1uobl",
          paddingInlineEnd: "x1nzty39",
          $$css: !0,
        },
        splitButtonRightSmall: {
          height: "x10w6t97",
          paddingInlineEnd: "x1uc92m",
          $$css: !0,
        },
        disabled: { opacity: "xti2d7y", cursor: "x1h6gzvc", $$css: !0 },
        buttonBase: {
          alignItems: "x6s0dn4",
          backgroundColor: "xjbqb8w",
          display: "x78zum5",
          justifyContent: "xl56j7k",
          $$css: !0,
        },
        buttonHover: { ":hover_backgroundColor": "x1k5h0tu", $$css: !0 },
        focusInner: {
          ":focus-visible_outlineOffset": "xyu9ima",
          ":focus-visible_outlineWidth": "x100v1rl",
          $$css: !0,
        },
      },
      d = 1e3;
    function m(e) {
      var t = e.Icon,
        n = e.disabled,
        a = n === void 0 ? !1 : n,
        i = e.disableDropdownButton,
        l = i === void 0 ? !1 : i,
        m = e.disableMainButton,
        p = m === void 0 ? !1 : m,
        _ = e.dropdownButtonLabel,
        f = e.dropdownButtonTestId,
        g = e.dropdownRef,
        h = e.isMuted,
        y = h === void 0 ? !1 : h,
        C = e.mainButtonLabel,
        b = e.mainButtonTestId,
        v = e.onDropdownClick,
        S = e.onMainClick,
        R = e.testId,
        L = e.tooltipOwnerAnchorRef,
        E = e.tooltipOwnerDocument,
        k = u(r("WAWebVoipUiPopoutWindowContext")),
        I = k.isContextInPopoutWindow && !k.isDocPip,
        T = I ? 24 : 20;
      return s.jsx("div", {
        style: y
          ? {
              "--WDS-surface-highlight-RGB":
                o("WDSVars.stylex").WDSColors[
                  "--WDS-persistent-always-black-RGB"
                ],
            }
          : void 0,
        children: s.jsxs(o("WAWebFlex.react").FlexRow, {
          align: "center",
          role: "group",
          "aria-label": C,
          xstyle: [
            c.splitButton,
            !I && c.splitButtonSmall,
            y && c.mutedSplitButton,
            a && c.disabled,
          ],
          testid: void 0,
          children: [
            s.jsx(o("WAWebFlex.react").FlexItem, {
              grow: 1,
              shrink: 0,
              children: s.jsx(r("WDSTooltip.react"), {
                label: C,
                ownerAnchorRef: L,
                ownerDocument: E,
                delayTooltipMs: d,
                children: s.jsx(r("WAWebUnstyledButton.react"), {
                  testid: void 0,
                  disabled: a || p,
                  onClick: S,
                  xstyle: [
                    c.buttonBase,
                    c.splitButtonLeft,
                    !I && c.splitButtonLeftSmall,
                    !a && !p && c.buttonHover,
                    c.focusInner,
                  ],
                  "aria-label": C,
                  children: s.jsx(t, { height: T, width: T }),
                }),
              }),
            }),
            s.jsx(o("WAWebFlex.react").FlexItem, {
              grow: 0,
              shrink: 0,
              basis: "auto",
              children: s.jsx(r("WDSTooltip.react"), {
                label: _,
                ownerAnchorRef: L,
                ownerDocument: E,
                delayTooltipMs: d,
                children: s.jsx(r("WAWebUnstyledButton.react"), {
                  testid: void 0,
                  disabled: a || l,
                  onClick: v,
                  xstyle: [
                    c.buttonBase,
                    c.splitButtonRight,
                    !I && c.splitButtonRightSmall,
                    !a && !l && c.buttonHover,
                    c.focusInner,
                  ],
                  ref: g,
                  "aria-label": _,
                  children: s.jsx(r("WDSIconIcArrowDropDown.react"), {
                    height: T,
                    width: T,
                  }),
                }),
              }),
            }),
          ],
        }),
      });
    }
    ((m.displayName = m.name + " [from " + i.id + "]"), (l.default = m));
  },
  98,
);
