__d(
  "WAWebContactSyncEventWamEvent",
  ["WAWebWamCodegenUtils", "WAWebWamEnumContactSyncSource"],
  function (t, n, r, o, a, i, l) {
    var e,
      s = (e = o("WAWebWamCodegenUtils")).defineEvents(
        {
          ContactSyncEvent: [
            1006,
            {
              contactSyncBusinessResponseNew: [20, e.TYPES.INTEGER],
              contactSyncChangedVersionRowCount: [10, e.TYPES.INTEGER],
              contactSyncConsecutiveCount: [26, e.TYPES.INTEGER],
              contactSyncDeviceResponseNew: [19, e.TYPES.INTEGER],
              contactSyncDisappearingModeResponseNew: [22, e.TYPES.INTEGER],
              contactSyncEndTimestamp: [23, e.TYPES.TIMER],
              contactSyncErrorCode: [14, e.TYPES.INTEGER],
              contactSyncFailureProtocol: [16, e.TYPES.INTEGER],
              contactSyncIsMultiIq: [33, e.TYPES.BOOLEAN],
              contactSyncLatency: [17, e.TYPES.INTEGER],
              contactSyncMultiIqCompletedPages: [34, e.TYPES.INTEGER],
              contactSyncMultiIqFailedPageIndex: [35, e.TYPES.INTEGER],
              contactSyncMultiIqSessionDurationMs: [36, e.TYPES.INTEGER],
              contactSyncMultiIqTotalPages: [37, e.TYPES.INTEGER],
              contactSyncNoop: [12, e.TYPES.BOOLEAN],
              contactSyncPayResponseNew: [21, e.TYPES.INTEGER],
              contactSyncRequestClearWaSyncData: [6, e.TYPES.BOOLEAN],
              contactSyncRequestIsUrgent: [5, e.TYPES.BOOLEAN],
              contactSyncRequestOrigin: [28, e.TYPES.INTEGER],
              contactSyncRequestPreparationLatency: [27, e.TYPES.INTEGER],
              contactSyncRequestProtocol: [15, e.TYPES.INTEGER],
              contactSyncRequestRetryCount: [7, e.TYPES.INTEGER],
              contactSyncRequestShouldRetry: [8, e.TYPES.BOOLEAN],
              contactSyncRequestedCount: [11, e.TYPES.INTEGER],
              contactSyncResponseCount: [13, e.TYPES.INTEGER],
              contactSyncSidelistRequestedCount: [30, e.TYPES.INTEGER],
              contactSyncSidelistResponseCount: [31, e.TYPES.INTEGER],
              contactSyncSource: [
                24,
                o("WAWebWamEnumContactSyncSource").CONTACT_SYNC_SOURCE,
              ],
              contactSyncStartTimestamp: [25, e.TYPES.TIMER],
              contactSyncStatusResponseNew: [18, e.TYPES.INTEGER],
              contactSyncSuccess: [9, e.TYPES.BOOLEAN],
              contactSyncType: [1, e.TYPES.STRING],
              contactSyncTypeCode: [4, e.TYPES.INTEGER],
              contactSyncTypeIsBackground: [3, e.TYPES.BOOLEAN],
              contactSyncTypeIsFull: [2, e.TYPES.BOOLEAN],
              contactSyncTypeIsMetadata: [29, e.TYPES.BOOLEAN],
              contactSyncTypeIsSnapshot: [32, e.TYPES.BOOLEAN],
            },
            [1, 20, 100],
            "regular",
          ],
        },
        { ContactSyncEvent: [] },
      );
    l.ContactSyncEventWamEvent = s;
  },
  98,
);
