__d(
  "WAWebMenuBarStyles",
  [],
  function (t, n, r, o, a, i, l) {
    var e = {
      menu: {
        display: "x78zum5",
        alignItems: "x6s0dn4",
        boxSizing: "x1afcbsf",
        $$css: !0,
      },
      menuDefault: { color: "x14ug900", $$css: !0 },
      menuStrong: { color: "xhslqc4", $$css: !0 },
      menuInverse: { color: "x17t9dm2", $$css: !0 },
      menuNavBar: { height: "x5yr21d", alignItems: "x1cy8zhl", $$css: !0 },
      menuGapSingle: { columnGap: "x1s70e7g", $$css: !0 },
      btnThemeForceSize: {
        height: "xxk0z11",
        width: "xvy4d1p",
        display: "x78zum5",
        justifyContent: "xl56j7k",
        alignItems: "x6s0dn4",
        $$css: !0,
      },
      item: {
        position: "x1n2onr6",
        flex: "x1okw0bk",
        height: "x5yr21d",
        borderStartStartRadius: "x1c9tyrk",
        borderStartEndRadius: "xeusxvb",
        borderEndEndRadius: "x1pahc9y",
        borderEndStartRadius: "x1ertn4p",
        transition: "xlkovuz",
        ":active_transition": "x16j0l1c",
        $$css: !0,
      },
      itemButton: {
        display: "x78zum5",
        alignItems: "x6s0dn4",
        boxSizing: "x1afcbsf",
        color: "x1heor9g",
        borderStartStartRadius: "x1fmog5m",
        borderStartEndRadius: "xu25z0z",
        borderEndEndRadius: "x140muxe",
        borderEndStartRadius: "xo1y3bh",
        $$css: !0,
      },
      itemSelected: { backgroundColor: "x4wrhlh", $$css: !0 },
      itemActive: { backgroundColor: "x4wrhlh", $$css: !0 },
      itemActiveStateNotDisabled: {
        ":active_backgroundColor": "x11xlx4c",
        $$css: !0,
      },
      itemShowHoverBg: { ":hover_backgroundColor": "x17gydlx", $$css: !0 },
      itemDisabled: { opacity: "xyd83as", $$css: !0 },
      itemDisabledRoleBtn: { cursor: "xt0e3qv", $$css: !0 },
      itemThemeNavBar: {
        maxHeight: "x18wx58x",
        maxWidth: "xo92w5m",
        $$css: !0,
      },
      itemChild: { display: "x78zum5", alignItems: "x1cy8zhl", $$css: !0 },
      itemThemeMediaEditor: {
        "@media screen and (max-width: 850px)_paddingTop": "x1f9lq3s",
        "@media screen and (max-width: 850px)_paddingInlineEnd": "xazzkgq",
        "@media screen and (max-width: 850px)_paddingBottom": "xslj4r9",
        "@media screen and (max-width: 850px)_paddingInlineStart": "x1fia4fy",
        "@media screen and (max-width: 850px)_marginLeft": "x17qx6bn",
        "@media screen and (max-width: 850px)_marginInlineStart": null,
        "@media screen and (max-width: 850px)_marginInlineEnd": null,
        $$css: !0,
      },
    };
    l.default = e;
  },
  98,
);
