__d(
  "WAWebBBLoggerTypes",
  [
    "WAWebWamEnumEntryPoint",
    "WAWebWamEnumSmbUserActionTypeEnum",
    "WAWebWamEnumSurfaceType",
  ],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = importNamespace("WAWebWamEnumEntryPoint").ENTRY_POINT,
      l = importNamespace(
        "WAWebWamEnumSmbUserActionTypeEnum",
      ).SMB_USER_ACTION_TYPE_ENUM,
      s = importNamespace("WAWebWamEnumSurfaceType").SURFACE_TYPE,
      u = {
        ADD_ATTACHMENT_BUTTON: "add_attachment_button",
        ADD_AUDIENCE_BUTTON: "add_audience_button",
        ADD_CTA_BUTTON: "add_cta_button",
        ADD_FUNDS_WIZARD: "add_funds_wizard",
        ATTACHMENT_DOCUMENT_PREVIEW_BUTTON:
          "attachment_document_preview_button",
        ATTACHMENT_DOCUMENT_REMOVE_BUTTON: "attachment_document_remove_button",
        ATTACHMENT_IMAGE_PREVIEW_BUTTON: "attachment_image_preview_button",
        ATTACHMENT_IMAGE_REMOVE_BUTTON: "attachment_image_remove_button",
        ATTACHMENT_PREVIEW_SAVE_BUTTON: "attachment_preview_save_button",
        ATTACHMENT_SELECTION_PREVIEW: "attachment_selection_preview",
        ATTACHMENT_VIDEO_PREVIEW_BUTTON: "attachment_video_preview_button",
        ATTACHMENT_VIDEO_REMOVE_BUTTON: "attachment_video_remove_button",
        ATTACHMENTS_CAMERA_DROPDOWN: "attachments_camera_dropdown",
        ATTACHMENTS_DOCUMENT_DROPDOWN: "attachments_document_dropdown",
        ATTACHMENTS_IMAGE_VIDEOS_DROPDOWN: "attachments_image_videos_dropdown",
        AUDIENCE_INFO_BUTTON: "audience_info_button",
        AUDIENCES_TAB_BUTTON: "audiences_tab_button",
        BACK_BUTTON: "back_button",
        BB: "bb",
        BILLING_FAQ_LINK: "billing_faq_link",
        BILLING_INFO_FETCH: "billing_info_fetch",
        BILLING_PRIVACY_POLICY_LINK: "billing_privacy_policy_link",
        BILLING_TOS_LINK: "billing_tos_link",
        BILLING_WIZARD: "billing_wizard",
        BILLING_WIZARD_FAILED: "billing_wizard_failed",
        BROADCAST_CHAT_LIST_IMPRESSION: "broadcast_chat_list_impression",
        BROADCAST_CHAT_LIST_STATE: "broadcast_chat_list_state",
        BROADCAST_INFO_DRAWER: "broadcast_info_drawer",
        BROADCAST_ITEM_OVERFLOW_BUTTON: "broadcast_item_overflow_button",
        BROADCASTS_TAB_BUTTON: "broadcasts_tab_button",
        BUSINESS_BROADCASTS_BUTTON: "business_broadcasts_button",
        CANCEL: "cancel",
        CHAT_LIST_CONTEXT_MENU: "chat_list_context_menu",
        CHECKOUT_FETCH: "checkout_fetch",
        CHOOSE_AUDIENCE_BUTTON: "choose_audience_button",
        CLOSE_BUTTON: "close_button",
        CONTACT_CHECKBOX: "contact_checkbox",
        CONTACT_NAME: "contact_name",
        CONTINUE: "continue",
        CONVERSATION_HEADER_MENU: "conversation_header_menu",
        CREATE_AUDIENCE_BUTTON: "create_audience_button",
        CREATE_BROADCAST_BUTTON: "create_broadcast_button",
        DELETE_ALL_ERROR_CONTACTS: "delete_all_error_contacts",
        DELETE_AUDIENCE_BUTTON: "delete_audience_button",
        DELETE_BROADCAST_BUTTON: "delete_broadcast_button",
        DELETE_CONTACT: "delete_contact",
        DELETE_DIALOG: "delete_dialog",
        DELETE_ERROR_CONTACT: "delete_error_contact",
        DELIVERED_TO_DRAWER: "delivered_to_drawer",
        EDIT_ERROR_CONTACT: "edit_error_contact",
        EDIT_RECIPIENTS_BUTTON: "edit_recipients_button",
        ELIGIBILITY_GATE: "eligibility_gate",
        EMAIL_ONBOARDING: "email_onboarding",
        EXISTING_AUDIENCE_LIST_ITEM: "existing_audience_list_item",
        EXISTING_AUDIENCES_BUTTON: "existing_audiences_button",
        EXISTING_AUDIENCES_MODAL: "existing_audiences_modal",
        EXIT_CONFIRMATION_CONTINUE_BUTTON: "exit_confirmation_continue_button",
        EXIT_CONFIRMATION_DISMISS_BUTTON: "exit_confirmation_dismiss_button",
        GENAI_AI_TEXT_CLEARED: "genai_ai_text_cleared",
        GENAI_AI_TEXT_USED: "genai_ai_text_used",
        GENAI_CARD_TAPPED: "genai_card_tapped",
        GENAI_DAILY_LIMIT: "genai_daily_limit",
        GENAI_ERROR_RETRY: "genai_error_retry",
        GENAI_ERROR_SHOWN: "genai_error_shown",
        GENAI_MODAL_CLOSED: "genai_modal_closed",
        GENAI_NUX_ACCEPT: "genai_nux_accept",
        GENAI_NUX_DISMISS: "genai_nux_dismiss",
        GENAI_NUX_MODAL: "genai_nux_modal",
        GENAI_REFRESH: "genai_refresh",
        GENAI_SUGGESTION_USED: "genai_suggestion_used",
        GENAI_SUGGESTIONS_SHOWN: "genai_suggestions_shown",
        IMPORT_AUDIENCE_BUTTON: "import_audience_button",
        IMPORTED_CONTACT_LIST_NAME: "imported_contact_list_name",
        LABEL_CHAT_CLICKED: "label_chat_clicked",
        LABEL_CHAT_SAVED: "label_chat_saved",
        LEARN_MORE_LINK: "learn_more_link",
        MENU: "menu",
        MESSAGE_CONTEXT_MENU: "message_context_menu",
        NEW_AUDIENCE_DROPDOWN: "new_audience_dropdown",
        NEW_BROADCAST_BUTTON: "new_broadcast_button",
        NEW_BROADCAST_TILE: "new_broadcast_tile",
        OPEN_BROADCAST_THREAD: "open_broadcast_thread",
        OPEN_FILE: "open_file",
        OVERFLOW_MENU_BUTTON: "overflow_menu_button",
        PAGE: "page",
        PAYMENT_METHOD_CHANGE_BUTTON: "payment_method_change_button",
        PAYMENT_METHOD_SECTION: "payment_method_section",
        PAYMENT_REQUIRED_ACTION_BUTTON: "payment_required_action_button",
        PERFORMANCE_EXPLAINED_BUTTON: "performance_explained_button",
        PHONE_NUMBER: "phone_number",
        PREVIEW_BUTTON: "preview_button",
        QP_BANNER: "qp_banner",
        REFRESH_INSIGHTS_BUTTON: "refresh_insights_button",
        RENAME_AUDIENCE_BUTTON: "rename_audience_button",
        RENAME_BROADCAST_BUTTON: "rename_broadcast_button",
        SAVE: "save",
        SAVE_AUDIENCE_BUTTON: "save_audience_button",
        SAVE_TEMPLATE: "save_template",
        SEND_BROADCAST_BUTTON: "send_broadcast_button",
        SEND_BUTTON: "send_button",
        SEND_CAMPAIGN_ACK: "send_campaign_ack",
        STAR_MESSAGE_BUTTON: "star_message_button",
        SUGGESTED_AUDIENCE_CARD_CLICK: "suggested_audience_card_click",
        SUGGESTED_AUDIENCE_CARD_ERROR: "suggested_audience_card_error",
        SUGGESTED_AUDIENCE_CARDS_IMPRESSION:
          "suggested_audience_cards_impression",
        TOS_NUX_ACCEPT: "tos_nux_accept",
        TOS_NUX_ACCEPT_FAILED: "tos_nux_accept_failed",
        TOS_NUX_ACCEPT_SUCCESS: "tos_nux_accept_success",
        TOS_NUX_DISMISS: "tos_nux_dismiss",
        TOS_NUX_LINK: "tos_nux_link",
        TOS_NUX_MODAL: "tos_nux_modal",
        TOS_REVIEW_BANNER: "tos_review_banner",
        UNDO_RENAME_AUDIENCE: "undo_rename_audience",
        UNDO_RENAME_BROADCAST: "undo_rename_broadcast",
        UPLOAD_FILE: "upload_file",
      };
    ((i.ENTRY_POINT = e),
      (i.SMB_USER_ACTION_TYPE_ENUM = l),
      (i.SURFACE_TYPE = s),
      (i.UserActionTarget = u));
  },
  66,
);
