__d(
  "WAWebMexFetchSubgroupSuggestionsJobQuery.graphql",
  [],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = (function () {
      var e = { defaultValue: null, kind: "LocalArgument", name: "group_id" },
        t = {
          defaultValue: null,
          kind: "LocalArgument",
          name: "query_context",
        },
        n = {
          defaultValue: null,
          kind: "LocalArgument",
          name: "sub_group_hint_id",
        },
        r = [
          {
            fields: [
              { kind: "Variable", name: "group_id", variableName: "group_id" },
              {
                kind: "Variable",
                name: "query_context",
                variableName: "query_context",
              },
              {
                kind: "Variable",
                name: "sub_group_hint",
                variableName: "sub_group_hint_id",
              },
            ],
            kind: "ObjectValue",
            name: "group_input",
          },
        ],
        o = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "id",
          storageKey: null,
        },
        a = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "value",
          storageKey: null,
        },
        i = [a],
        l = {
          alias: null,
          args: null,
          concreteType: "XWA2GroupSubject",
          kind: "LinkedField",
          name: "subject",
          plural: !1,
          selections: i,
          storageKey: null,
        },
        s = {
          alias: null,
          args: null,
          concreteType: "XWA2User",
          kind: "LinkedField",
          name: "creator",
          plural: !1,
          selections: [o],
          storageKey: null,
        },
        u = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "creation_time",
          storageKey: null,
        },
        c = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "total_participants_count",
          storageKey: null,
        },
        d = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "is_existing_group",
          storageKey: null,
        },
        m = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "hidden_group",
          storageKey: null,
        };
      return {
        fragment: {
          argumentDefinitions: [e, t, n],
          kind: "Fragment",
          metadata: null,
          name: "WAWebMexFetchSubgroupSuggestionsJobQuery",
          selections: [
            {
              alias: null,
              args: r,
              concreteType: null,
              kind: "LinkedField",
              name: "xwa2_group_query_by_id",
              plural: !1,
              selections: [
                o,
                {
                  kind: "InlineFragment",
                  selections: [
                    {
                      alias: null,
                      args: null,
                      concreteType: "XWA2CommunitySubGroupSuggestionConnection",
                      kind: "LinkedField",
                      name: "sub_group_suggestions",
                      plural: !1,
                      selections: [
                        {
                          alias: null,
                          args: null,
                          concreteType: "XWA2CommunitySubGroupSuggestionEdge",
                          kind: "LinkedField",
                          name: "edges",
                          plural: !0,
                          selections: [
                            {
                              alias: null,
                              args: null,
                              concreteType: "XWA2CommunitySubGroupSuggestion",
                              kind: "LinkedField",
                              name: "node",
                              plural: !1,
                              selections: [
                                o,
                                l,
                                {
                                  alias: null,
                                  args: null,
                                  concreteType: "XWA2GroupDescription",
                                  kind: "LinkedField",
                                  name: "description",
                                  plural: !1,
                                  selections: i,
                                  storageKey: null,
                                },
                                s,
                                u,
                                c,
                                d,
                                m,
                              ],
                              storageKey: null,
                            },
                          ],
                          storageKey: null,
                        },
                      ],
                      storageKey: null,
                    },
                  ],
                  type: "XWA2CommunityGroup",
                  abstractKey: null,
                },
              ],
              storageKey: null,
            },
          ],
          type: "Query",
          abstractKey: null,
        },
        kind: "Request",
        operation: {
          argumentDefinitions: [e, n, t],
          kind: "Operation",
          name: "WAWebMexFetchSubgroupSuggestionsJobQuery",
          selections: [
            {
              alias: null,
              args: r,
              concreteType: null,
              kind: "LinkedField",
              name: "xwa2_group_query_by_id",
              plural: !1,
              selections: [
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "__typename",
                  storageKey: null,
                },
                o,
                {
                  kind: "InlineFragment",
                  selections: [
                    {
                      alias: null,
                      args: null,
                      concreteType: "XWA2CommunitySubGroupSuggestionConnection",
                      kind: "LinkedField",
                      name: "sub_group_suggestions",
                      plural: !1,
                      selections: [
                        {
                          alias: null,
                          args: null,
                          concreteType: "XWA2CommunitySubGroupSuggestionEdge",
                          kind: "LinkedField",
                          name: "edges",
                          plural: !0,
                          selections: [
                            {
                              alias: null,
                              args: null,
                              concreteType: "XWA2CommunitySubGroupSuggestion",
                              kind: "LinkedField",
                              name: "node",
                              plural: !1,
                              selections: [
                                o,
                                l,
                                {
                                  alias: null,
                                  args: null,
                                  concreteType: "XWA2GroupDescription",
                                  kind: "LinkedField",
                                  name: "description",
                                  plural: !1,
                                  selections: [a, o],
                                  storageKey: null,
                                },
                                s,
                                u,
                                c,
                                d,
                                m,
                              ],
                              storageKey: null,
                            },
                          ],
                          storageKey: null,
                        },
                      ],
                      storageKey: null,
                    },
                  ],
                  type: "XWA2CommunityGroup",
                  abstractKey: null,
                },
              ],
              storageKey: null,
            },
          ],
        },
        params: {
          id: "23972005349071865",
          metadata: {},
          name: "WAWebMexFetchSubgroupSuggestionsJobQuery",
          operationKind: "query",
          text: null,
        },
      };
    })();
    a.exports = e;
  },
  null,
);
