__d(
  "waWebMinificationMap",
  ["WebBloksModel"],
  function (t, n, r, o, a, i, l) {
    var e = o("WebBloksModel").defineWebBloksMinificationMap({
        "bk.AnyComponent": {
          styleId: "\u4285",
          toCanonicalAttrs: { style: '"' },
        },
        "bk.AnyData": { styleId: "\u4286", toCanonicalAttrs: {} },
        "bk.cds.bottomsheet.Wrapper": {
          styleId: "\u370D",
          toCanonicalAttrs: {
            content: "$",
            header: "(",
            top_banner: "-",
            web_background_overlay_color: "+",
            web_mode_override: ",",
          },
        },
        "bk.component.TransitionContainer": {
          styleId: "\u35E5",
          toCanonicalAttrs: { crossfade: "$", progress: "#" },
        },
        "bk.component.WebFocusBoundaryExtension": {
          styleId: "\u4283",
          toCanonicalAttrs: {
            on_gain_focus_inside: "#",
            on_lose_focus_inside: "$",
          },
        },
        "bk.components.AccessibilityExtension": {
          styleId: "\u3401",
          toCanonicalAttrs: {
            disabled: "+",
            enabled: "#",
            hint: "(",
            label: "$",
            ordered_children: "-",
            role: "&",
          },
        },
        "bk.components.AnchorIdExtension": {
          styleId: "\u356E",
          toCanonicalAttrs: { anchor_id: "#", key: "$" },
        },
        "bk.components.AnchorTagExtension": {
          styleId: "\u4244",
          toCanonicalAttrs: { href: "#", prefer_native_navigation: "$" },
        },
        "bk.components.AutomationTestExtension": {
          styleId: "\u34FE",
          toCanonicalAttrs: { testing_id: "#" },
        },
        "bk.components.BKSTextInputFormatter": {
          styleId: "\u35C8",
          toCanonicalAttrs: { format_text: "$" },
        },
        "bk.components.BoxDecoration": {
          styleId: "\u3402",
          toCanonicalAttrs: {
            background: "#",
            border_color: "$",
            border_themed_color: "&",
            border_width: "(",
            clipping: "+",
            contrib: "=",
            corner_radius: ".",
            corners_to_apply_radius: "8",
            elevation: "0",
            foreground: "1",
            shadow_offset_height: "9",
            shadow_offset_width: ":",
            shadow_opacity: "3",
            shadow_radius: ";",
            shadow_themed_color: "4",
          },
        },
        "bk.components.Canvas": {
          styleId: "\u40CA",
          toCanonicalAttrs: { height: "#", width: "$" },
        },
        "bk.components.Collection": {
          styleId: "\u3405",
          toCanonicalAttrs: {
            background_themed_color: ")",
            direction: "*",
            fading_edge_length: "K",
            is_scroll_enabled: "_",
            item_spacing: ",",
            layout_config: "^",
            layout_config_type: "`",
            measurement_version_internal_use_only: "c",
            on_page_scroll: "1",
            on_scroll_callback: "=",
            on_scroll_snap: "3",
            persist_scroll_position: "t",
            shows_scroll_indicator: "C",
            snap: "6",
            snap_style: "E",
            spacing_after: "7",
            spacing_before: "8",
            stack_from_end: "I",
            starting_index: "B",
            use_correct_measure: "?",
          },
        },
        "bk.components.ColorDrawable": {
          styleId: "\u3406",
          toCanonicalAttrs: { color: "#" },
        },
        "bk.components.DatetimeTextProvider": {
          styleId: "\u3407",
          toCanonicalAttrs: { format: "#", timestamp: "$", type: "&" },
        },
        "bk.components.Flexbox": {
          styleId: "\u3408",
          toCanonicalAttrs: {
            align_content: "#",
            align_items: "$",
            decoration: "&",
            enabled: "(",
            flex_direction: ")",
            flex_wrap: "*",
            justify_content: ",",
            on_click: "-",
            on_mount: ".",
            padding_bottom: "6",
            padding_end: "7",
            padding_left: "8",
            padding_right: "9",
            padding_start: ":",
            padding_top: ";",
            visibility: "1",
          },
        },
        "bk.components.FoaGestureExtension": {
          styleId: "\u3DD9",
          toCanonicalAttrs: {
            on_double_tap: "$",
            on_double_tap_with_touch_point: "-",
            on_double_tap_with_touch_point_v2: "A",
            on_long_press: "#",
            on_long_press_with_touch_point: "5",
            on_long_press_with_touch_point_v2: "=",
            on_pinch: ",",
            on_scroll: "0",
            on_swipe_down: "&",
            on_swipe_left: "(",
            on_swipe_right: ")",
            on_swipe_up: "*",
            on_tap: "+",
            on_tap_with_touch_point: "6",
            on_tap_with_touch_point_v2: ">",
            on_touch_down: "1",
            on_touch_up: "2",
          },
        },
        "bk.components.FoaTouchExtension": {
          styleId: "\u369D",
          toCanonicalAttrs: {
            on_touch_cancel: "#",
            on_touch_down: "$",
            on_touch_up: "&",
          },
        },
        "bk.components.Glimmer": {
          styleId: "\u35E0",
          toCanonicalAttrs: {
            component_style: "#",
            corner_radius: "$",
            index: "&",
            shape: "(",
            surface_background_color: ")",
          },
        },
        "bk.components.GradientDrawable": {
          styleId: "\u3409",
          toCanonicalAttrs: {
            begin_color: "#",
            end_color: "$",
            middle_color: "&",
            orientation: "(",
          },
        },
        "bk.components.GradientThemedColorDrawable": {
          styleId: "\u340A",
          toCanonicalAttrs: {
            begin_color: "#",
            end_color: "$",
            middle_color: "&",
            orientation: "(",
          },
        },
        "bk.components.HoverExtension": {
          styleId: "\u57F7",
          toCanonicalAttrs: {
            on_pointer_enter: "#",
            on_pointer_leave: "$",
            on_pointer_move: "&",
          },
        },
        "bk.components.Image": {
          styleId: "\u340B",
          toCanonicalAttrs: {
            color_filter: "#",
            contrib: ".",
            dark_url: "$",
            focus_point: "=",
            on_image_perf_update: ",",
            scale_type: "(",
            url: ")",
          },
        },
        "bk.components.OnMount": {
          styleId: "\u365A",
          toCanonicalAttrs: {
            on_first_mount: ")",
            on_mount: "*",
            on_unmount: "+",
          },
        },
        "bk.components.PullToRefreshContainer": {
          styleId: "\u340F",
          toCanonicalAttrs: { child: "#", is_refreshing: "&", on_refresh: "$" },
        },
        "bk.components.RenderLifecycleExtension": {
          styleId: "\u3558",
          toCanonicalAttrs: { on_component_rendered: "#" },
        },
        "bk.components.RichText": {
          styleId: "\u3411",
          toCanonicalAttrs: {
            baseline_spacing: ".",
            cap_spacing: "0",
            emoji_enabled: "2",
            line_height_multiplier: "&",
            max_number_of_lines: "(",
            on_click: ")",
            spans: "E",
            spans_for_truncation: "F",
            text_align: "*",
            text_direction: "6",
            text_size_unit: "7",
            truncation_spans: ",",
            use_composable_and_extensible_spans: "D",
          },
        },
        "bk.components.ScrollToIndexByIdArgs": {
          styleId: "\u35A7",
          toCanonicalAttrs: { animated: "&", snap_to: "#", target_id: "$" },
        },
        "bk.components.Slider": {
          styleId: "\u3F20",
          toCanonicalAttrs: {
            filled_track_color: "+",
            initial_value: "1",
            on_change: "&",
            on_end_touch: ")",
            on_start_touch: "*",
            progress: "(",
            thumb_color: ",",
            thumb_diameter: "-",
            track_height: ".",
            unfilled_track_color: "0",
          },
        },
        "bk.components.Spinner": {
          styleId: "\u3562",
          toCanonicalAttrs: { color: "#" },
        },
        "bk.components.StateDrawable": {
          styleId: "\u3414",
          toCanonicalAttrs: { state_items: "#" },
        },
        "bk.components.StateDrawableItem": {
          styleId: "\u3415",
          toCanonicalAttrs: { drawable: "#", state: "$" },
        },
        "bk.components.Switch": {
          styleId: "\u3416",
          toCanonicalAttrs: {
            checked: "#",
            enabled: "&",
            is_controlled: "3",
            off_color: ")",
            on_color: "(",
            on_toggle: "$",
            thumb_color_disabled_off: "4",
            thumb_color_disabled_on: "5",
            thumb_color_off: "6",
            thumb_color_on: "7",
            track_color_disabled_off: "1",
            track_color_disabled_on: "2",
            track_color_off: ",",
            track_color_on: "-",
          },
        },
        "bk.components.Text": {
          styleId: "\u3417",
          toCanonicalAttrs: {
            font_family: "#",
            line_height: ";",
            line_height_multiplier: "$",
            max_number_of_lines: "&",
            on_click: "(",
            strikethrough: "2",
            text: ")",
            text_align: "*",
            text_color: "+",
            text_provider: ",",
            text_size: "-",
            text_style: ".",
            text_themed_color: "0",
            truncation_string: "1",
          },
        },
        "bk.components.TextInput": {
          styleId: "\u3418",
          toCanonicalAttrs: {
            allow_text_change_callback: ">",
            background_color: "\x8C",
            cursor_color: "A",
            digits_key_listener: "S",
            enabled: "J",
            font_family: "#",
            hint: "$",
            hint_text_themed_color: "&",
            html_autocapitalize: "_",
            html_autocomplete: "`",
            html_autocorrect: "a",
            html_name: "b",
            max_length: "(",
            max_number_of_lines: "B",
            on_gain_focus: "*",
            on_lose_focus: "-",
            on_submit: ".",
            on_text_change: "0",
            resize_height_based_on_content: "?",
            single_line: "1",
            text: "2",
            text_align: "3",
            text_color: "4",
            text_size: "5",
            text_style: "6",
            text_themed_color: "7",
            type: "8",
          },
        },
        "bk.components.TextInputDatePickerExtension": {
          styleId: "\u3F27",
          toCanonicalAttrs: {
            initial_time_seconds: "#",
            maximum_time_seconds: "$",
            minimum_time_seconds: "&",
            mode: "(",
            on_date_change: "+",
          },
        },
        "bk.components.TextInputMaskExtension": {
          styleId: "\u3419",
          toCanonicalAttrs: { mask: "#" },
        },
        "bk.components.TextSpan": {
          styleId: "\u341B",
          toCanonicalAttrs: {
            accessibility_label: "B",
            accessibility_role: "C",
            font_family: "#",
            image_align: "D",
            image_component: ";",
            image_height: "=",
            image_margin: "E",
            image_width: ">",
            on_click: "$",
            shadow_color: "5",
            shadow_offset_dx: "6",
            shadow_offset_dy: "7",
            shadow_radius: "8",
            strikethrough: "-",
            text: "&",
            text_color: "(",
            text_provider: ")",
            text_size: "*",
            text_style: "+",
            text_themed_color: ",",
            tracking: "1",
            underline: "4",
          },
        },
        "bk.components.ThemedColorDrawable": {
          styleId: "\u341C",
          toCanonicalAttrs: { color: "#" },
        },
        "bk.components.Tooltip": {
          styleId: "\u358C",
          toCanonicalAttrs: {
            arrow_type: "(",
            child: ")",
            decoration: "*",
            height: "+",
            margin: ",",
            offset_horizontal: "-",
            offset_vertical: ".",
            position: "0",
            width: "1",
          },
        },
        "bk.components.TooltipContainer": {
          styleId: "\u403C",
          toCanonicalAttrs: {
            child: "*",
            on_compute_position: "(",
            on_touch_outside: "-",
            on_visibility_update: ")",
            tooltip: "+",
            tooltip_visibility: ",",
          },
        },
        "bk.components.Video": {
          styleId: "\u3D98",
          toCanonicalAttrs: { video_versions: "," },
        },
        "bk.components.ViewTransformsExtension": {
          styleId: "\u3578",
          toCanonicalAttrs: {
            css_transition_delay: "=",
            css_transition_duration: "5",
            css_transition_timing_function: "6",
            drop_shadow_blur_radius: "8",
            drop_shadow_color: "9",
            drop_shadow_offset_x: ":",
            drop_shadow_offset_y: ";",
            pivot_x: ")",
            pivot_y: "*",
            rotation: "\x8A",
            scale_x: "#",
            scale_y: "$",
            translate_x: "&",
            translate_y: "(",
            will_change: "7",
          },
        },
        "bk.components.VisibilityExtension": {
          styleId: "\u34E2",
          toCanonicalAttrs: {
            key: "&",
            on_appear: "#",
            on_disappear: "$",
            on_update: "(",
            trigger_on_first_appear_only: "*",
          },
        },
        "bk.components.WebCssAnimationExtension": {
          styleId: "\u639A",
          toCanonicalAttrs: {
            delay_ms: "#",
            direction: "$",
            duration_ms: "&",
            fill_mode: "(",
            iteration_count: ")",
            keyframes: "*",
            play_state: "+",
            respect_reduced_motion: ",",
            timing_function: "-",
            transform_origin_x: ".",
            transform_origin_y: "0",
          },
        },
        "bk.components.WebDataAttributesExtension": {
          styleId: "\u62F0",
          toCanonicalAttrs: { attributes: "#" },
        },
        "bk.components.WebNativeAccessibilityExtension": {
          styleId: "\u4033",
          toCanonicalAttrs: {
            "aria-controls": "3",
            "aria-describedby": "6",
            "aria-expanded": "2",
            "aria-hidden": "8",
            "aria-pressed": "4",
            "aria-selected": "5",
            checked: ",",
            enabled: "1",
            heading_level: "+",
            label: "0",
            lang: "7",
            role: "-",
          },
        },
        "bk.components.Zoomable": {
          styleId: "\u3F84",
          toCanonicalAttrs: {
            content: "#",
            double_tap_scale: "$",
            max_scale: "&",
          },
        },
        "bk.components.dialog.Button": {
          styleId: "\u35E8",
          toCanonicalAttrs: {
            appearance: "(",
            on_click: "#",
            testing_id: ".",
            text: "$",
          },
        },
        "bk.components.dialog.Dialog": {
          styleId: "\u35E7",
          toCanonicalAttrs: {
            message: "#",
            preferred_button_index: "*",
            primary_button: "$",
            secondary_button: "&",
            tertiary_button: ",",
            title: "(",
          },
        },
        "bk.components.internal.Action": {
          styleId: "\u341F",
          toCanonicalAttrs: { handler: "#" },
        },
        "bk.components.internal.Merge": {
          styleId: "\u3422",
          toCanonicalAttrs: {},
        },
        "bk.components.internal.MergeWithBind": {
          styleId: "\u41D3",
          toCanonicalAttrs: {},
        },
        "bk.components.internal.Shadow": {
          styleId: "\u3423",
          toCanonicalAttrs: { child: "#", init_state: "&", reduce: "+" },
        },
        "bk.components.screen.ScreenWrapper": {
          styleId: "\u4123",
          toCanonicalAttrs: {
            container_config: "#",
            content: "$",
            navigation_callbacks: "&",
          },
        },
        "bk.components.screen.Wrapper": {
          styleId: "\u369E",
          toCanonicalAttrs: { content: "#", contribs: "&", navbar: "$" },
        },
        "bk.components.webbloks.DragExtension": {
          styleId: "\u64E4",
          toCanonicalAttrs: {
            direction: "#",
            on_drag_begin: "$",
            on_drag_end: "&",
          },
        },
        "bk.components.webbloks.Fieldset": {
          styleId: "\u4369",
          toCanonicalAttrs: {},
        },
        "bk.components.webbloks.FixedWrapper": {
          styleId: "\u644C",
          toCanonicalAttrs: {
            bottom: "#",
            left: "$",
            right: "&",
            top: "(",
            z_index: ")",
          },
        },
        "bk.data.BaseTextSpan": { styleId: "\u41F6", toCanonicalAttrs: {} },
        "bk.data.CollectionStickyItemConfig": {
          styleId: "\u41D9",
          toCanonicalAttrs: { is_sticky: "#", position: "$" },
        },
        "bk.data.ComposableTextSpan": {
          styleId: "\u41F7",
          toCanonicalAttrs: {
            accessibility_label: "#",
            spans: "$",
            styles: "&",
          },
        },
        "bk.data.GradientLine": {
          styleId: "\u3E6A",
          toCanonicalAttrs: { end_point: ")", start_point: "*" },
        },
        "bk.data.ImageSpan": {
          styleId: "\u4202",
          toCanonicalAttrs: {
            accessibility_label: ",",
            image_align: "$",
            image_component: "&",
            image_height: "(",
            image_margin: ")",
            image_width: "*",
            styles: "+",
          },
        },
        "bk.data.Point": {
          styleId: "\u3EB4",
          toCanonicalAttrs: { x: "#", y: "$" },
        },
        "bk.data.TextSpan": {
          styleId: "\u41F0",
          toCanonicalAttrs: {
            accessibility_label: "#",
            styles: "$",
            text: "&",
            text_provider: "(",
          },
        },
        "bk.data.VideoVersion": {
          styleId: "\u3DCC",
          toCanonicalAttrs: {
            height: "#",
            quality_type: "$",
            url: "&",
            video_id: "(",
            width: ")",
          },
        },
        "bk.data.WebCssKeyframe": {
          styleId: "\u639B",
          toCanonicalAttrs: {
            at_opacity: "#",
            at_rotation: "$",
            at_scale: "&",
            at_translate_x: "(",
            at_translate_y: ")",
            offset: "*",
          },
        },
        "bk.data.action.bloks.FetchAsyncComponentsOptions": {
          styleId: "\u3FF8",
          toCanonicalAttrs: {},
        },
        "bk.data.async_action.OpenAsyncActionOptions": {
          styleId: "\u3F03",
          toCanonicalAttrs: {
            on_failure: "#",
            on_success_with_result: "$",
            props: "(",
            scope: "&",
          },
        },
        "bk.data.bloks.DataPropEntry": {
          styleId: "\u3FD6",
          toCanonicalAttrs: { name: "#", variable_id: "$" },
        },
        "bk.data.bloks.TreeResourceReferences": {
          styleId: "\u3F75",
          toCanonicalAttrs: {
            ft: "+",
            props: ")",
            referenced_embedded_elements: "#",
            referenced_embedded_payloads: "$",
            referenced_external_variables: "&",
            referenced_internal_variables: "(",
          },
        },
        "bk.data.boxdecoration.Contrib": {
          styleId: "\u36EE",
          toCanonicalAttrs: { borders_to_apply: "+" },
        },
        "bk.data.cds.OpenScreenOptions": {
          styleId: "\u3ED5",
          toCanonicalAttrs: { mode: "&", on_dismiss: "(", props: "," },
        },
        "bk.data.contrib.screen.wrapper.Web": {
          styleId: "\u3FD5",
          toCanonicalAttrs: {
            disable_text_selection: ",",
            enable_folding_address_bar: "+",
            enable_navbar_overlay: ".",
            screen_theme: "-",
            should_wrap: "#",
          },
        },
        "bk.data.debug.internal.DeviceLogOptions": {
          styleId: "\u3F34",
          toCanonicalAttrs: { priority: "#", tag: "$" },
        },
        "bk.data.dialog.OpenDialogOptions": {
          styleId: "\u35F0",
          toCanonicalAttrs: {},
        },
        "bk.data.image.Contrib": {
          styleId: "\u3D8D",
          toCanonicalAttrs: { base_sixty_four_encoded_image: "$" },
        },
        "bk.data.navigation.OpenUrlOptions": {
          styleId: "\u3F1E",
          toCanonicalAttrs: { open_in_new_tab: "#", url_params: "$" },
        },
        "bk.data.qpl.EventConfig": {
          styleId: "\u3F59",
          toCanonicalAttrs: { sample_rate: "#", sampling_type: "$" },
        },
        "bk.data.qpl.MarkerParams": {
          styleId: "\u3588",
          toCanonicalAttrs: { is_tti_marker: "#", marker_start_time: "$" },
        },
        "bk.data.qpl.MarkerPointParams": {
          styleId: "\u35B3",
          toCanonicalAttrs: { point_data_string: "#", timestamp: "$" },
        },
        "bk.data.qpl.userflow.StartOptions": {
          styleId: "\u3D88",
          toCanonicalAttrs: { background_behavior: "#", trigger_source: "$" },
        },
        "bk.data.screen.CloseParams": {
          styleId: "\u4172",
          toCanonicalAttrs: { is_inclusive: "$", screen_id: "&", type: "#" },
        },
        "bk.data.screen.Navbar": {
          styleId: "\u35D9",
          toCanonicalAttrs: { contribs: "(", hide_navbar: "#", title: "$" },
        },
        "bk.data.screen.NavigationCallbacks": {
          styleId: "\u4180",
          toCanonicalAttrs: { on_enter: "#", on_exit: "$" },
        },
        "bk.data.screen.Screen": {
          styleId: "\u35D8",
          toCanonicalAttrs: {
            app_id: "#",
            contribs: "*",
            loaded_screen: "$",
            loading_screen: "&",
            navbar_data: "3",
            screen_id: "-",
            tti_marker_id: "1",
            ttrc_marker_id: "4",
            url_relative_path: "A",
          },
        },
        "bk.data.screen.ScreenConfig": {
          styleId: "\u4128",
          toCanonicalAttrs: {
            analytics_extras: "(",
            analytics_module: ")",
            animate_on_navigation: "+",
            controller_name: ";",
            props: "&",
            url_relative_path: "2",
          },
        },
        "bk.data.screens.OpenFullScreenOptions": {
          styleId: "\u35B6",
          toCanonicalAttrs: {
            presentation_mode: "#",
            props: "&",
            should_disable_animation: "$",
            web_url: "(",
          },
        },
        "bk.data.toast.CubicBezierInterpolatorConfig": {
          styleId: "\u36B9",
          toCanonicalAttrs: { x_a: "#", x_b: "$", y_a: "&", y_b: "(" },
        },
        "bk.data.toast.ShowToastOptions": {
          styleId: "\u36B7",
          toCanonicalAttrs: {
            auto_dismiss_duration_ms: "#",
            dismiss_animation_duration_ms: "$",
            dismiss_animation_interpolator: "&",
            on_dismiss: "(",
            on_show: ")",
            show_animation_duration_ms: "*",
            show_animation_interpolator: "+",
          },
        },
        "bk.data.toast.ShowToastOptionsV2": {
          styleId: "\u3F8D",
          toCanonicalAttrs: {
            auto_dismiss_duration_ms: "#",
            dismiss_animation_duration_ms: "$",
            dismiss_animation_interpolator: "&",
            on_dismiss: "(",
            on_show: ")",
            show_animation_duration_ms: "*",
            show_animation_interpolator: "+",
          },
        },
        "bk.extensions.OnDataChange": {
          styleId: "\u3FB6",
          toCanonicalAttrs: {
            data: ")",
            fire_on_first_mount: "*",
            on_change: "#",
            on_cleanup: "(",
          },
        },
        "bk.style.Base": {
          styleId: "\u5E89",
          toCanonicalAttrs: {
            align_self: "=",
            aspect_ratio: "#",
            bottom: "$",
            collection_sticky_item_config: ">",
            end: "(",
            flex_basis: "F",
            flex_grow: "?",
            flex_shrink: "A",
            grid_is_full_span: "C",
            grid_span_count: "D",
            height: ")",
            left: "*",
            margin_bottom: "+",
            margin_end: ",",
            margin_left: "-",
            margin_right: ".",
            margin_start: "0",
            margin_top: "1",
            max_height: "2",
            max_width: "3",
            min_height: "4",
            min_width: "5",
            position_type: "6",
            right: "7",
            staggered_grid_cell_aspect_ratio: "E",
            start: "8",
            top: "9",
            width: ":",
            z_index: ";",
          },
        },
        "bk.style.GridCollectionStyle": {
          styleId: "\u3FF4",
          toCanonicalAttrs: { is_full_span: "$", span_count: "#" },
        },
        "bk.style.textspan.ClickableStyle": {
          styleId: "\u41E9",
          toCanonicalAttrs: { accessibility_role: "#", on_click: "$" },
        },
        "bk.style.textspan.ColorStyle": {
          styleId: "\u41EB",
          toCanonicalAttrs: { text_themed_color: "#" },
        },
        "bk.style.textspan.ResizeToFitStyle": {
          styleId: "\u41FB",
          toCanonicalAttrs: {
            max_text_size: "#",
            min_text_size: "$",
            resize_mode: "(",
          },
        },
        "bk.style.textspan.ShadowStyle": {
          styleId: "\u41E7",
          toCanonicalAttrs: {
            shadow_color: "#",
            shadow_offset_dx: "$",
            shadow_offset_dy: "&",
            shadow_radius: "(",
          },
        },
        "bk.style.textspan.StrikethroughStyle": {
          styleId: "\u41EA",
          toCanonicalAttrs: { strikethrough: "#" },
        },
        "bk.style.textspan.TextStyle": {
          styleId: "\u41E6",
          toCanonicalAttrs: {
            font_family: "#",
            text_size: ")",
            text_style: "*",
            tracking: ",",
          },
        },
        "bk.style.textspan.UnderlineStyle": {
          styleId: "\u41EC",
          toCanonicalAttrs: { underline: "#" },
        },
        "bk.types.CanvasBlendingMode": {
          styleId: "\u40E2",
          toCanonicalAttrs: { mode: "#" },
        },
        "bk.types.CanvasFill": {
          styleId: "\u40E5",
          toCanonicalAttrs: {
            blending_mode: "#",
            shading: "&",
            shadow: "(",
            shape: ")",
          },
        },
        "bk.types.CanvasGradient": {
          styleId: "\u40D2",
          toCanonicalAttrs: { positions: "#", themed_colors: "$" },
        },
        "bk.types.CanvasGroup": {
          styleId: "\u40ED",
          toCanonicalAttrs: {
            clip: "#",
            clip_to_bounds: ")",
            height: "$",
            transform: "&",
            width: "(",
          },
        },
        "bk.types.CanvasLayer": {
          styleId: "\u40EF",
          toCanonicalAttrs: {
            blending_mode: "#",
            clip: "$",
            height: "&",
            transform: "(",
            width: ")",
          },
        },
        "bk.types.CanvasPath": {
          styleId: "\u40D1",
          toCanonicalAttrs: { fill_rule: "#" },
        },
        "bk.types.CanvasPathAdd": {
          styleId: "\u40E6",
          toCanonicalAttrs: { path: "#", transform: "$" },
        },
        "bk.types.CanvasPathArc": {
          styleId: "\u40F4",
          toCanonicalAttrs: {
            center_x: "#",
            center_y: "$",
            clockwise: "&",
            end_angle: "(",
            radius: ")",
            start_angle: "*",
          },
        },
        "bk.types.CanvasPathCircle": {
          styleId: "\u40D4",
          toCanonicalAttrs: { center_x: "#", center_y: "$", radius: "&" },
        },
        "bk.types.CanvasPathClose": { styleId: "\u40D8", toCanonicalAttrs: {} },
        "bk.types.CanvasPathCubicTo": {
          styleId: "\u40F5",
          toCanonicalAttrs: {
            control_a_x: "#",
            control_a_y: "$",
            control_b_x: "&",
            control_b_y: "(",
            end_x: ")",
            end_y: "*",
          },
        },
        "bk.types.CanvasPathDifference": {
          styleId: "\u40EE",
          toCanonicalAttrs: {},
        },
        "bk.types.CanvasPathEllipse": {
          styleId: "\u40E0",
          toCanonicalAttrs: { height: "#", width: "$", x: "&", y: "(" },
        },
        "bk.types.CanvasPathIntersection": {
          styleId: "\u40EB",
          toCanonicalAttrs: {},
        },
        "bk.types.CanvasPathLineTo": {
          styleId: "\u40F6",
          toCanonicalAttrs: { x: "#", y: "$" },
        },
        "bk.types.CanvasPathMoveTo": {
          styleId: "\u40F7",
          toCanonicalAttrs: { x: "#", y: "$" },
        },
        "bk.types.CanvasPathQuadTo": {
          styleId: "\u40F8",
          toCanonicalAttrs: {
            control_x: "#",
            control_y: "$",
            end_x: "&",
            end_y: "(",
          },
        },
        "bk.types.CanvasPathRect": {
          styleId: "\u40DB",
          toCanonicalAttrs: {
            corner_radius: "#",
            height: "$",
            width: "&",
            x: "(",
            y: ")",
          },
        },
        "bk.types.CanvasPathUnion": { styleId: "\u40E9", toCanonicalAttrs: {} },
        "bk.types.CanvasPathXor": { styleId: "\u40EC", toCanonicalAttrs: {} },
        "bk.types.CanvasShadingColor": {
          styleId: "\u40CF",
          toCanonicalAttrs: { themed_color: "#" },
        },
        "bk.types.CanvasShadingGradientLinear": {
          styleId: "\u40E8",
          toCanonicalAttrs: {
            end_x: "#",
            end_y: "$",
            gradient: "&",
            start_x: "(",
            start_y: ")",
          },
        },
        "bk.types.CanvasShadingGradientRadial": {
          styleId: "\u40E7",
          toCanonicalAttrs: {
            center_x: "#",
            center_y: "$",
            gradient: "&",
            radius: "(",
          },
        },
        "bk.types.CanvasShadow": {
          styleId: "\u40D3",
          toCanonicalAttrs: {
            dx: "#",
            dy: "$",
            radius: "&",
            themed_color: "(",
          },
        },
        "bk.types.CanvasShapeArc": {
          styleId: "\u40CC",
          toCanonicalAttrs: {
            center_x: "#",
            center_y: "$",
            clockwise: "&",
            end_angle: "(",
            radius: ")",
            start_angle: "*",
          },
        },
        "bk.types.CanvasShapeCircle": {
          styleId: "\u40D6",
          toCanonicalAttrs: { center_x: "#", center_y: "$", radius: "&" },
        },
        "bk.types.CanvasShapeEllipse": {
          styleId: "\u40D5",
          toCanonicalAttrs: { height: "#", width: "$", x: "&", y: "(" },
        },
        "bk.types.CanvasShapeLine": {
          styleId: "\u40DC",
          toCanonicalAttrs: {
            end_x: "#",
            end_y: "$",
            start_x: "&",
            start_y: "(",
          },
        },
        "bk.types.CanvasShapeRect": {
          styleId: "\u40D9",
          toCanonicalAttrs: {
            corner_radius: "#",
            height: "$",
            width: "&",
            x: "(",
            y: ")",
          },
        },
        "bk.types.CanvasStroke": {
          styleId: "\u40EA",
          toCanonicalAttrs: {
            blending_mode: "#",
            dash_lengths: "$",
            dash_phase: ".",
            line_cap: "&",
            line_join: "(",
            line_width: ")",
            miter_limit: "*",
            shading: "+",
            shadow: ",",
            shape: "-",
          },
        },
        "bk.types.CanvasTransform": {
          styleId: "\u40DE",
          toCanonicalAttrs: {
            a: "#",
            b: "$",
            c: "&",
            d: "(",
            tx: ")",
            ty: "*",
          },
        },
        "bk.types.CanvasTransformInverseV2": {
          styleId: "\u41C2",
          toCanonicalAttrs: {},
        },
        "bk.types.CanvasTransformRotate": {
          styleId: "\u40DF",
          toCanonicalAttrs: { degrees: "#", pivot_x: "$", pivot_y: "&" },
        },
        "bk.types.CanvasTransformScale": {
          styleId: "\u40CE",
          toCanonicalAttrs: { pivot_x: "#", pivot_y: "$", x: "&", y: "(" },
        },
        "bk.types.CanvasTransformSkew": {
          styleId: "\u40CD",
          toCanonicalAttrs: { pivot_x: "#", pivot_y: "$", x: "&", y: "(" },
        },
        "bk.types.CanvasTransformSkewV2": {
          styleId: "\u41BE",
          toCanonicalAttrs: { pivot_x: "#", pivot_y: "$", x: "&", y: "(" },
        },
        "bk.types.CanvasTransformTranslate": {
          styleId: "\u40D7",
          toCanonicalAttrs: { x: "#", y: "$" },
        },
        "bk.types.Drawable": { styleId: "\u3430", toCanonicalAttrs: {} },
        "bk.types.GridCollectionLayoutConfig": {
          styleId: "\u3FF5",
          toCanonicalAttrs: {
            cell_aspect_ratio: "#",
            cross_axis_span_spacing: "$",
            main_axis_span_spacing: "&",
            padding: "(",
            span_count: ")",
          },
        },
        "bk.types.Inset": {
          styleId: "\u3FA9",
          toCanonicalAttrs: { bottom: "#", end: ")", start: "*", top: "(" },
        },
        "bk.types.Style": { styleId: "\u3433", toCanonicalAttrs: {} },
        "bk.types.TextProvider": { styleId: "\u3434", toCanonicalAttrs: {} },
        "bk.types.ThemedColor": {
          styleId: "\u3435",
          toCanonicalAttrs: { dark_color: "#", light_color: "$" },
        },
        "bk.types.TooltipComputePositionData": {
          styleId: "\u403F",
          toCanonicalAttrs: {
            arrow_height: ".",
            arrow_metadata: "$",
            arrow_width: "0",
            arrow_x: "&",
            arrow_y: "(",
            content_height: "5",
            content_width: "6",
            content_x: "7",
            content_y: "8",
            position: "-",
            tooltip_height: ")",
            tooltip_width: "*",
            tooltip_x: "+",
            tooltip_y: ",",
          },
        },
        "bk.types.contrib.screen.Navbar": {
          styleId: "\u362D",
          toCanonicalAttrs: {},
        },
        "bk.types.contrib.screen.NavbarButton": {
          styleId: "\u362E",
          toCanonicalAttrs: {},
        },
        "bk.types.contrib.screen.Screen": {
          styleId: "\u3630",
          toCanonicalAttrs: {},
        },
        "bk.types.contrib.screen.Wrapper": {
          styleId: "\u3E5C",
          toCanonicalAttrs: {},
        },
        collection: {
          styleId: "\u3436",
          toCanonicalAttrs: {
            height: "#",
            is_sticky: "$",
            on_appear: "&",
            on_disappear: "(",
            sticky_item_config: "6",
            width: ")",
          },
        },
        flex: {
          styleId: "\u3438",
          toCanonicalAttrs: {
            align_self: "#",
            aspect_ratio: "$",
            bottom: "&",
            end: "(",
            flex_basis: "R",
            grow: ")",
            height: "*",
            left: "+",
            margin_bottom: ",",
            margin_end: "-",
            margin_left: ".",
            margin_right: "0",
            margin_start: "1",
            margin_top: "2",
            max_height: "3",
            max_width: "4",
            min_height: "5",
            min_width: "6",
            padding_bottom: "7",
            padding_end: "8",
            padding_left: "9",
            padding_right: ":",
            padding_start: ";",
            padding_top: "=",
            position_type: ">",
            right: "?",
            shrink: "A",
            start: "B",
            top: "C",
            width: "D",
          },
        },
        "mini.data.Product": {
          styleId: "\u34E7",
          toCanonicalAttrs: {
            current_price: "#",
            current_price_stripped: "+",
            full_price: "$",
            full_price_stripped: ",",
            has_viewer_saved: ".",
            inventory_quantity: "1",
            is_checkout_enabled: "2",
            main_image: "&",
            merchant: "-",
            merchant_id: "(",
            name: ")",
            product_id: "*",
            thumbnail_image: "0",
            variant_values: "3",
          },
        },
        "mini.data.ProductImage": {
          styleId: "\u34E8",
          toCanonicalAttrs: {
            height: "#",
            image_id: "$",
            url: "&",
            width: "(",
          },
        },
        "mini.data.ProductVariant": {
          styleId: "\u354C",
          toCanonicalAttrs: {
            is_preselected: ")",
            variant_id: "#",
            variant_name: "$",
            variant_style: "&",
            variant_value: "(",
          },
        },
      }),
      s = e;
    l.default = s;
  },
  98,
);
