__d(
  "WAWebProtobufsWeb.pb",
  [
    "$InternalEnum",
    "WAProtoConst",
    "WAWebProtobufsE2E.pb",
    "WAWebProtobufsProtocol.pb",
  ],
  function (t, n, r, o, a, i, l) {
    var e,
      s,
      u,
      c,
      d = (c = n("$InternalEnum"))({ E2EE: 0, FB: 2, BSP: 1, BSP_AND_FB: 3 }),
      m = c({
        UNKNOWN: 0,
        REVOKE: 1,
        CIPHERTEXT: 2,
        FUTUREPROOF: 3,
        NON_VERIFIED_TRANSITION: 4,
        UNVERIFIED_TRANSITION: 5,
        VERIFIED_TRANSITION: 6,
        VERIFIED_LOW_UNKNOWN: 7,
        VERIFIED_HIGH: 8,
        VERIFIED_INITIAL_UNKNOWN: 9,
        VERIFIED_INITIAL_LOW: 10,
        VERIFIED_INITIAL_HIGH: 11,
        VERIFIED_TRANSITION_ANY_TO_NONE: 12,
        VERIFIED_TRANSITION_ANY_TO_HIGH: 13,
        VERIFIED_TRANSITION_HIGH_TO_LOW: 14,
        VERIFIED_TRANSITION_HIGH_TO_UNKNOWN: 15,
        VERIFIED_TRANSITION_UNKNOWN_TO_LOW: 16,
        VERIFIED_TRANSITION_LOW_TO_UNKNOWN: 17,
        VERIFIED_TRANSITION_NONE_TO_LOW: 18,
        VERIFIED_TRANSITION_NONE_TO_UNKNOWN: 19,
        GROUP_CREATE: 20,
        GROUP_CHANGE_SUBJECT: 21,
        GROUP_CHANGE_ICON: 22,
        GROUP_CHANGE_INVITE_LINK: 23,
        GROUP_CHANGE_DESCRIPTION: 24,
        GROUP_CHANGE_RESTRICT: 25,
        GROUP_CHANGE_ANNOUNCE: 26,
        GROUP_PARTICIPANT_ADD: 27,
        GROUP_PARTICIPANT_REMOVE: 28,
        GROUP_PARTICIPANT_PROMOTE: 29,
        GROUP_PARTICIPANT_DEMOTE: 30,
        GROUP_PARTICIPANT_INVITE: 31,
        GROUP_PARTICIPANT_LEAVE: 32,
        GROUP_PARTICIPANT_CHANGE_NUMBER: 33,
        BROADCAST_CREATE: 34,
        BROADCAST_ADD: 35,
        BROADCAST_REMOVE: 36,
        GENERIC_NOTIFICATION: 37,
        E2E_IDENTITY_CHANGED: 38,
        E2E_ENCRYPTED: 39,
        CALL_MISSED_VOICE: 40,
        CALL_MISSED_VIDEO: 41,
        INDIVIDUAL_CHANGE_NUMBER: 42,
        GROUP_DELETE: 43,
        GROUP_ANNOUNCE_MODE_MESSAGE_BOUNCE: 44,
        CALL_MISSED_GROUP_VOICE: 45,
        CALL_MISSED_GROUP_VIDEO: 46,
        PAYMENT_CIPHERTEXT: 47,
        PAYMENT_FUTUREPROOF: 48,
        PAYMENT_TRANSACTION_STATUS_UPDATE_FAILED: 49,
        PAYMENT_TRANSACTION_STATUS_UPDATE_REFUNDED: 50,
        PAYMENT_TRANSACTION_STATUS_UPDATE_REFUND_FAILED: 51,
        PAYMENT_TRANSACTION_STATUS_RECEIVER_PENDING_SETUP: 52,
        PAYMENT_TRANSACTION_STATUS_RECEIVER_SUCCESS_AFTER_HICCUP: 53,
        PAYMENT_ACTION_ACCOUNT_SETUP_REMINDER: 54,
        PAYMENT_ACTION_SEND_PAYMENT_REMINDER: 55,
        PAYMENT_ACTION_SEND_PAYMENT_INVITATION: 56,
        PAYMENT_ACTION_REQUEST_DECLINED: 57,
        PAYMENT_ACTION_REQUEST_EXPIRED: 58,
        PAYMENT_ACTION_REQUEST_CANCELLED: 59,
        BIZ_VERIFIED_TRANSITION_TOP_TO_BOTTOM: 60,
        BIZ_VERIFIED_TRANSITION_BOTTOM_TO_TOP: 61,
        BIZ_INTRO_TOP: 62,
        BIZ_INTRO_BOTTOM: 63,
        BIZ_NAME_CHANGE: 64,
        BIZ_MOVE_TO_CONSUMER_APP: 65,
        BIZ_TWO_TIER_MIGRATION_TOP: 66,
        BIZ_TWO_TIER_MIGRATION_BOTTOM: 67,
        OVERSIZED: 68,
        GROUP_CHANGE_NO_FREQUENTLY_FORWARDED: 69,
        GROUP_V4_ADD_INVITE_SENT: 70,
        GROUP_PARTICIPANT_ADD_REQUEST_JOIN: 71,
        CHANGE_EPHEMERAL_SETTING: 72,
        E2E_DEVICE_CHANGED: 73,
        VIEWED_ONCE: 74,
        E2E_ENCRYPTED_NOW: 75,
        BLUE_MSG_BSP_FB_TO_BSP_PREMISE: 76,
        BLUE_MSG_BSP_FB_TO_SELF_FB: 77,
        BLUE_MSG_BSP_FB_TO_SELF_PREMISE: 78,
        BLUE_MSG_BSP_FB_UNVERIFIED: 79,
        BLUE_MSG_BSP_FB_UNVERIFIED_TO_SELF_PREMISE_VERIFIED: 80,
        BLUE_MSG_BSP_FB_VERIFIED: 81,
        BLUE_MSG_BSP_FB_VERIFIED_TO_SELF_PREMISE_UNVERIFIED: 82,
        BLUE_MSG_BSP_PREMISE_TO_SELF_PREMISE: 83,
        BLUE_MSG_BSP_PREMISE_UNVERIFIED: 84,
        BLUE_MSG_BSP_PREMISE_UNVERIFIED_TO_SELF_PREMISE_VERIFIED: 85,
        BLUE_MSG_BSP_PREMISE_VERIFIED: 86,
        BLUE_MSG_BSP_PREMISE_VERIFIED_TO_SELF_PREMISE_UNVERIFIED: 87,
        BLUE_MSG_CONSUMER_TO_BSP_FB_UNVERIFIED: 88,
        BLUE_MSG_CONSUMER_TO_BSP_PREMISE_UNVERIFIED: 89,
        BLUE_MSG_CONSUMER_TO_SELF_FB_UNVERIFIED: 90,
        BLUE_MSG_CONSUMER_TO_SELF_PREMISE_UNVERIFIED: 91,
        BLUE_MSG_SELF_FB_TO_BSP_PREMISE: 92,
        BLUE_MSG_SELF_FB_TO_SELF_PREMISE: 93,
        BLUE_MSG_SELF_FB_UNVERIFIED: 94,
        BLUE_MSG_SELF_FB_UNVERIFIED_TO_SELF_PREMISE_VERIFIED: 95,
        BLUE_MSG_SELF_FB_VERIFIED: 96,
        BLUE_MSG_SELF_FB_VERIFIED_TO_SELF_PREMISE_UNVERIFIED: 97,
        BLUE_MSG_SELF_PREMISE_TO_BSP_PREMISE: 98,
        BLUE_MSG_SELF_PREMISE_UNVERIFIED: 99,
        BLUE_MSG_SELF_PREMISE_VERIFIED: 100,
        BLUE_MSG_TO_BSP_FB: 101,
        BLUE_MSG_TO_CONSUMER: 102,
        BLUE_MSG_TO_SELF_FB: 103,
        BLUE_MSG_UNVERIFIED_TO_BSP_FB_VERIFIED: 104,
        BLUE_MSG_UNVERIFIED_TO_BSP_PREMISE_VERIFIED: 105,
        BLUE_MSG_UNVERIFIED_TO_SELF_FB_VERIFIED: 106,
        BLUE_MSG_UNVERIFIED_TO_VERIFIED: 107,
        BLUE_MSG_VERIFIED_TO_BSP_FB_UNVERIFIED: 108,
        BLUE_MSG_VERIFIED_TO_BSP_PREMISE_UNVERIFIED: 109,
        BLUE_MSG_VERIFIED_TO_SELF_FB_UNVERIFIED: 110,
        BLUE_MSG_VERIFIED_TO_UNVERIFIED: 111,
        BLUE_MSG_BSP_FB_UNVERIFIED_TO_BSP_PREMISE_VERIFIED: 112,
        BLUE_MSG_BSP_FB_UNVERIFIED_TO_SELF_FB_VERIFIED: 113,
        BLUE_MSG_BSP_FB_VERIFIED_TO_BSP_PREMISE_UNVERIFIED: 114,
        BLUE_MSG_BSP_FB_VERIFIED_TO_SELF_FB_UNVERIFIED: 115,
        BLUE_MSG_SELF_FB_UNVERIFIED_TO_BSP_PREMISE_VERIFIED: 116,
        BLUE_MSG_SELF_FB_VERIFIED_TO_BSP_PREMISE_UNVERIFIED: 117,
        E2E_IDENTITY_UNAVAILABLE: 118,
        GROUP_CREATING: 119,
        GROUP_CREATE_FAILED: 120,
        GROUP_BOUNCED: 121,
        BLOCK_CONTACT: 122,
        EPHEMERAL_SETTING_NOT_APPLIED: 123,
        SYNC_FAILED: 124,
        SYNCING: 125,
        BIZ_PRIVACY_MODE_INIT_FB: 126,
        BIZ_PRIVACY_MODE_INIT_BSP: 127,
        BIZ_PRIVACY_MODE_TO_FB: 128,
        BIZ_PRIVACY_MODE_TO_BSP: 129,
        DISAPPEARING_MODE: 130,
        E2E_DEVICE_FETCH_FAILED: 131,
        ADMIN_REVOKE: 132,
        GROUP_INVITE_LINK_GROWTH_LOCKED: 133,
        COMMUNITY_LINK_PARENT_GROUP: 134,
        COMMUNITY_LINK_SIBLING_GROUP: 135,
        COMMUNITY_LINK_SUB_GROUP: 136,
        COMMUNITY_UNLINK_PARENT_GROUP: 137,
        COMMUNITY_UNLINK_SIBLING_GROUP: 138,
        COMMUNITY_UNLINK_SUB_GROUP: 139,
        GROUP_PARTICIPANT_ACCEPT: 140,
        GROUP_PARTICIPANT_LINKED_GROUP_JOIN: 141,
        COMMUNITY_CREATE: 142,
        EPHEMERAL_KEEP_IN_CHAT: 143,
        GROUP_MEMBERSHIP_JOIN_APPROVAL_REQUEST: 144,
        GROUP_MEMBERSHIP_JOIN_APPROVAL_MODE: 145,
        INTEGRITY_UNLINK_PARENT_GROUP: 146,
        COMMUNITY_PARTICIPANT_PROMOTE: 147,
        COMMUNITY_PARTICIPANT_DEMOTE: 148,
        COMMUNITY_PARENT_GROUP_DELETED: 149,
        COMMUNITY_LINK_PARENT_GROUP_MEMBERSHIP_APPROVAL: 150,
        GROUP_PARTICIPANT_JOINED_GROUP_AND_PARENT_GROUP: 151,
        MASKED_THREAD_CREATED: 152,
        MASKED_THREAD_UNMASKED: 153,
        BIZ_CHAT_ASSIGNMENT: 154,
        CHAT_PSA: 155,
        CHAT_POLL_CREATION_MESSAGE: 156,
        CAG_MASKED_THREAD_CREATED: 157,
        COMMUNITY_PARENT_GROUP_SUBJECT_CHANGED: 158,
        CAG_INVITE_AUTO_ADD: 159,
        BIZ_CHAT_ASSIGNMENT_UNASSIGN: 160,
        CAG_INVITE_AUTO_JOINED: 161,
        SCHEDULED_CALL_START_MESSAGE: 162,
        COMMUNITY_INVITE_RICH: 163,
        COMMUNITY_INVITE_AUTO_ADD_RICH: 164,
        SUB_GROUP_INVITE_RICH: 165,
        SUB_GROUP_PARTICIPANT_ADD_RICH: 166,
        COMMUNITY_LINK_PARENT_GROUP_RICH: 167,
        COMMUNITY_PARTICIPANT_ADD_RICH: 168,
        SILENCED_UNKNOWN_CALLER_AUDIO: 169,
        SILENCED_UNKNOWN_CALLER_VIDEO: 170,
        GROUP_MEMBER_ADD_MODE: 171,
        GROUP_MEMBERSHIP_JOIN_APPROVAL_REQUEST_NON_ADMIN_ADD: 172,
        COMMUNITY_CHANGE_DESCRIPTION: 173,
        SENDER_INVITE: 174,
        RECEIVER_INVITE: 175,
        COMMUNITY_ALLOW_MEMBER_ADDED_GROUPS: 176,
        PINNED_MESSAGE_IN_CHAT: 177,
        PAYMENT_INVITE_SETUP_INVITER: 178,
        PAYMENT_INVITE_SETUP_INVITEE_RECEIVE_ONLY: 179,
        PAYMENT_INVITE_SETUP_INVITEE_SEND_AND_RECEIVE: 180,
        LINKED_GROUP_CALL_START: 181,
        REPORT_TO_ADMIN_ENABLED_STATUS: 182,
        EMPTY_SUBGROUP_CREATE: 183,
        SCHEDULED_CALL_CANCEL: 184,
        SUBGROUP_ADMIN_TRIGGERED_AUTO_ADD_RICH: 185,
        GROUP_CHANGE_RECENT_HISTORY_SHARING: 186,
        PAID_MESSAGE_SERVER_CAMPAIGN_ID: 187,
        GENERAL_CHAT_CREATE: 188,
        GENERAL_CHAT_ADD: 189,
        GENERAL_CHAT_AUTO_ADD_DISABLED: 190,
        SUGGESTED_SUBGROUP_ANNOUNCE: 191,
        BIZ_BOT_1P_MESSAGING_ENABLED: 192,
        CHANGE_USERNAME: 193,
        BIZ_COEX_PRIVACY_INIT_SELF: 194,
        BIZ_COEX_PRIVACY_TRANSITION_SELF: 195,
        SUPPORT_AI_EDUCATION: 196,
        BIZ_BOT_3P_MESSAGING_ENABLED: 197,
        REMINDER_SETUP_MESSAGE: 198,
        REMINDER_SENT_MESSAGE: 199,
        REMINDER_CANCEL_MESSAGE: 200,
        BIZ_COEX_PRIVACY_INIT: 201,
        BIZ_COEX_PRIVACY_TRANSITION: 202,
        GROUP_DEACTIVATED: 203,
        COMMUNITY_DEACTIVATE_SIBLING_GROUP: 204,
        EVENT_UPDATED: 205,
        EVENT_CANCELED: 206,
        COMMUNITY_OWNER_UPDATED: 207,
        COMMUNITY_SUB_GROUP_VISIBILITY_HIDDEN: 208,
        CAPI_GROUP_NE2EE_SYSTEM_MESSAGE: 209,
        STATUS_MENTION: 210,
        USER_CONTROLS_SYSTEM_MESSAGE: 211,
        SUPPORT_SYSTEM_MESSAGE: 212,
        CHANGE_LID: 213,
        BIZ_CUSTOMER_3PD_DATA_SHARING_OPT_IN_MESSAGE: 214,
        BIZ_CUSTOMER_3PD_DATA_SHARING_OPT_OUT_MESSAGE: 215,
        CHANGE_LIMIT_SHARING: 216,
        GROUP_MEMBER_LINK_MODE: 217,
        BIZ_AUTOMATICALLY_LABELED_CHAT_SYSTEM_MESSAGE: 218,
        PHONE_NUMBER_HIDING_CHAT_DEPRECATED_MESSAGE: 219,
        QUARANTINED_MESSAGE: 220,
        GROUP_MEMBER_SHARE_GROUP_HISTORY_MODE: 221,
        GROUP_OPEN_BOT_ADDED: 222,
        GROUP_TEE_BOT_ADDED: 223,
        CONTACT_INFO: 224,
        SCHEDULED_MESSAGE_CREATED: 225,
      }),
      p = c({
        ERROR: 0,
        PENDING: 1,
        SERVER_ACK: 2,
        DELIVERY_ACK: 3,
        READ: 4,
        PLAYED: 5,
      }),
      _ = c({
        UNKNOWN: 0,
        PENDING_SETUP: 1,
        PENDING_RECEIVER_SETUP: 2,
        INIT: 3,
        SUCCESS: 4,
        COMPLETED: 5,
        FAILED: 6,
        FAILED_RISK: 7,
        FAILED_PROCESSING: 8,
        FAILED_RECEIVER_PROCESSING: 9,
        FAILED_DA: 10,
        FAILED_DA_FINAL: 11,
        REFUNDED_TXN: 12,
        REFUND_FAILED: 13,
        REFUND_FAILED_PROCESSING: 14,
        REFUND_FAILED_DA: 15,
        EXPIRED_TXN: 16,
        AUTH_CANCELED: 17,
        AUTH_CANCEL_FAILED_PROCESSING: 18,
        AUTH_CANCEL_FAILED: 19,
        COLLECT_INIT: 20,
        COLLECT_SUCCESS: 21,
        COLLECT_FAILED: 22,
        COLLECT_FAILED_RISK: 23,
        COLLECT_REJECTED: 24,
        COLLECT_EXPIRED: 25,
        COLLECT_CANCELED: 26,
        COLLECT_CANCELLING: 27,
        IN_REVIEW: 28,
        REVERSAL_SUCCESS: 29,
        REVERSAL_PENDING: 30,
        REFUND_PENDING: 31,
      }),
      f = c({
        UNKNOWN_STATUS: 0,
        PROCESSING: 1,
        SENT: 2,
        NEED_TO_ACCEPT: 3,
        COMPLETE: 4,
        COULD_NOT_COMPLETE: 5,
        REFUNDED: 6,
        EXPIRED: 7,
        REJECTED: 8,
        CANCELLED: 9,
        WAITING_FOR_PAYER: 10,
        WAITING: 11,
      }),
      g = c({ UNKNOWN_CURRENCY: 0, INR: 1 }),
      h = c({
        NOT_STARTED: 0,
        FORCE_UPGRADE: 1,
        DEVELOPMENT: 2,
        PRODUCTION: 3,
      }),
      y = c({ UNKNOWN_TYPE: 0, PIN_FOR_ALL: 1, UNPIN_FOR_ALL: 2 }),
      C = c({
        UNDEFINED: 0,
        REACTION: 1,
        EVENT_RESPONSE: 2,
        POLL_UPDATE: 3,
        PIN_IN_CHAT: 4,
      }),
      b = c({
        NOT_INJECTED: 0,
        INJECTED: 1,
        INJECTED_PARTIAL: 2,
        INJECTION_FAILED: 3,
        INJECTION_FAILED_NO_RETRY: 4,
      }),
      v = {},
      S = {},
      R = {},
      L = {},
      E = {},
      k = {},
      I = {},
      T = {},
      D = {},
      x = {},
      $ = {},
      P = {},
      N = {},
      M = {},
      w = {},
      A = {},
      F = {},
      O = {},
      B = {},
      W = {},
      q = {},
      U = {},
      V = {},
      H = {},
      G = {},
      z = {},
      j = {},
      K = {},
      Q = {};
    ((v.internalDefaults = { status: p.PENDING }),
      (v.name = "WebMessageInfo"),
      (v.internalSpec = {
        key: [
          1,
          (e = o("WAProtoConst")).FLAGS.REQUIRED | e.TYPES.MESSAGE,
          (s = o("WAWebProtobufsProtocol.pb")).MessageKeySpec,
        ],
        message: [
          2,
          e.TYPES.MESSAGE,
          (u = o("WAWebProtobufsE2E.pb")).MessageSpec,
        ],
        messageTimestamp: [3, e.TYPES.UINT64],
        status: [4, e.TYPES.ENUM, p],
        participant: [5, e.TYPES.STRING],
        messageC2STimestamp: [6, e.TYPES.UINT64],
        ignore: [16, e.TYPES.BOOL],
        starred: [17, e.TYPES.BOOL],
        broadcast: [18, e.TYPES.BOOL],
        pushName: [19, e.TYPES.STRING],
        mediaCiphertextSha256: [20, e.TYPES.BYTES],
        multicast: [21, e.TYPES.BOOL],
        urlText: [22, e.TYPES.BOOL],
        urlNumber: [23, e.TYPES.BOOL],
        messageStubType: [24, e.TYPES.ENUM, m],
        clearMedia: [25, e.TYPES.BOOL],
        messageStubParameters: [26, e.FLAGS.REPEATED | e.TYPES.STRING],
        duration: [27, e.TYPES.UINT32],
        labels: [28, e.FLAGS.REPEATED | e.TYPES.STRING],
        paymentInfo: [29, e.TYPES.MESSAGE, R],
        finalLiveLocation: [
          30,
          e.TYPES.MESSAGE,
          u.Message$LiveLocationMessageSpec,
        ],
        quotedPaymentInfo: [31, e.TYPES.MESSAGE, R],
        ephemeralStartTimestamp: [32, e.TYPES.UINT64],
        ephemeralDuration: [33, e.TYPES.UINT32],
        ephemeralOffToOn: [34, e.TYPES.BOOL],
        ephemeralOutOfSync: [35, e.TYPES.BOOL],
        bizPrivacyStatus: [36, e.TYPES.ENUM, d],
        verifiedBizName: [37, e.TYPES.STRING],
        mediaData: [38, e.TYPES.MESSAGE, T],
        photoChange: [39, e.TYPES.MESSAGE, D],
        userReceipt: [40, e.FLAGS.REPEATED | e.TYPES.MESSAGE, $],
        reactions: [41, e.FLAGS.REPEATED | e.TYPES.MESSAGE, P],
        quotedStickerData: [42, e.TYPES.MESSAGE, T],
        futureproofData: [43, e.TYPES.BYTES],
        statusPsa: [44, e.TYPES.MESSAGE, x],
        pollUpdates: [45, e.FLAGS.REPEATED | e.TYPES.MESSAGE, N],
        pollAdditionalMetadata: [46, e.TYPES.MESSAGE, M],
        agentId: [47, e.TYPES.STRING],
        statusAlreadyViewed: [48, e.TYPES.BOOL],
        messageSecret: [49, e.TYPES.BYTES],
        keepInChat: [50, e.TYPES.MESSAGE, F],
        originalSelfAuthorUserJidString: [51, e.TYPES.STRING],
        revokeMessageTimestamp: [52, e.TYPES.UINT64],
        pinInChat: [54, e.TYPES.MESSAGE, O],
        premiumMessageInfo: [55, e.TYPES.MESSAGE, W],
        is1PBizBotMessage: [56, e.TYPES.BOOL],
        isGroupHistoryMessage: [57, e.TYPES.BOOL],
        botMessageInvokerJid: [58, e.TYPES.STRING],
        commentMetadata: [59, e.TYPES.MESSAGE, S],
        eventResponses: [61, e.FLAGS.REPEATED | e.TYPES.MESSAGE, q],
        reportingTokenInfo: [62, e.TYPES.MESSAGE, I],
        newsletterServerId: [63, e.TYPES.UINT64],
        eventAdditionalMetadata: [64, e.TYPES.MESSAGE, A],
        isMentionedInStatus: [65, e.TYPES.BOOL],
        statusMentions: [66, e.FLAGS.REPEATED | e.TYPES.STRING],
        targetMessageId: [67, e.TYPES.MESSAGE, s.MessageKeySpec],
        messageAddOns: [68, e.FLAGS.REPEATED | e.TYPES.MESSAGE, V],
        statusMentionMessageInfo: [69, e.TYPES.MESSAGE, H],
        isSupportAiMessage: [70, e.TYPES.BOOL],
        statusMentionSources: [71, e.FLAGS.REPEATED | e.TYPES.STRING],
        supportAiCitations: [72, e.FLAGS.REPEATED | e.TYPES.MESSAGE, G],
        botTargetId: [73, e.TYPES.STRING],
        groupHistoryIndividualMessageInfo: [74, e.TYPES.MESSAGE, z],
        groupHistoryBundleInfo: [75, e.TYPES.MESSAGE, j],
        interactiveMessageAdditionalMetadata: [76, e.TYPES.MESSAGE, w],
        quarantinedMessage: [77, e.TYPES.MESSAGE, K],
        nonJidMentions: [78, e.TYPES.UINT32],
        hsmTag: [79, e.TYPES.STRING],
        ephemeralExpirationTimestamp: [80, e.TYPES.UINT64],
        scheduledMessageMetadata: [81, e.TYPES.MESSAGE, Q],
      }),
      (S.name = "CommentMetadata"),
      (S.internalSpec = {
        commentParentKey: [1, e.TYPES.MESSAGE, s.MessageKeySpec],
        replyCount: [2, e.TYPES.UINT32],
      }),
      (R.name = "PaymentInfo"),
      (R.internalSpec = {
        currencyDeprecated: [1, e.TYPES.ENUM, g],
        amount1000: [2, e.TYPES.UINT64],
        receiverJid: [3, e.TYPES.STRING],
        status: [4, e.TYPES.ENUM, f],
        transactionTimestamp: [5, e.TYPES.UINT64],
        requestMessageKey: [6, e.TYPES.MESSAGE, s.MessageKeySpec],
        expiryTimestamp: [7, e.TYPES.UINT64],
        futureproofed: [8, e.TYPES.BOOL],
        currency: [9, e.TYPES.STRING],
        txnStatus: [10, e.TYPES.ENUM, _],
        useNoviFiatFormat: [11, e.TYPES.BOOL],
        primaryAmount: [12, e.TYPES.MESSAGE, u.MoneySpec],
        exchangeAmount: [13, e.TYPES.MESSAGE, u.MoneySpec],
      }),
      (L.name = "WebNotificationsInfo"),
      (L.internalSpec = {
        timestamp: [2, e.TYPES.UINT64],
        unreadChats: [3, e.TYPES.UINT32],
        notifyMessageCount: [4, e.TYPES.UINT32],
        notifyMessages: [5, e.FLAGS.REPEATED | e.TYPES.MESSAGE, v],
      }),
      (E.name = "NotificationMessageInfo"),
      (E.internalSpec = {
        key: [1, e.TYPES.MESSAGE, s.MessageKeySpec],
        message: [2, e.TYPES.MESSAGE, u.MessageSpec],
        messageTimestamp: [3, e.TYPES.UINT64],
        participant: [4, e.TYPES.STRING],
      }),
      (k.name = "WebFeatures"),
      (k.internalSpec = {
        labelsDisplay: [1, e.TYPES.ENUM, h],
        voipIndividualOutgoing: [2, e.TYPES.ENUM, h],
        groupsV3: [3, e.TYPES.ENUM, h],
        groupsV3Create: [4, e.TYPES.ENUM, h],
        changeNumberV2: [5, e.TYPES.ENUM, h],
        queryStatusV3Thumbnail: [6, e.TYPES.ENUM, h],
        liveLocations: [7, e.TYPES.ENUM, h],
        queryVname: [8, e.TYPES.ENUM, h],
        voipIndividualIncoming: [9, e.TYPES.ENUM, h],
        quickRepliesQuery: [10, e.TYPES.ENUM, h],
        payments: [11, e.TYPES.ENUM, h],
        stickerPackQuery: [12, e.TYPES.ENUM, h],
        liveLocationsFinal: [13, e.TYPES.ENUM, h],
        labelsEdit: [14, e.TYPES.ENUM, h],
        mediaUpload: [15, e.TYPES.ENUM, h],
        mediaUploadRichQuickReplies: [18, e.TYPES.ENUM, h],
        vnameV2: [19, e.TYPES.ENUM, h],
        videoPlaybackUrl: [20, e.TYPES.ENUM, h],
        statusRanking: [21, e.TYPES.ENUM, h],
        voipIndividualVideo: [22, e.TYPES.ENUM, h],
        thirdPartyStickers: [23, e.TYPES.ENUM, h],
        frequentlyForwardedSetting: [24, e.TYPES.ENUM, h],
        groupsV4JoinPermission: [25, e.TYPES.ENUM, h],
        recentStickers: [26, e.TYPES.ENUM, h],
        catalog: [27, e.TYPES.ENUM, h],
        starredStickers: [28, e.TYPES.ENUM, h],
        voipGroupCall: [29, e.TYPES.ENUM, h],
        templateMessage: [30, e.TYPES.ENUM, h],
        templateMessageInteractivity: [31, e.TYPES.ENUM, h],
        ephemeralMessages: [32, e.TYPES.ENUM, h],
        e2ENotificationSync: [33, e.TYPES.ENUM, h],
        recentStickersV2: [34, e.TYPES.ENUM, h],
        recentStickersV3: [36, e.TYPES.ENUM, h],
        userNotice: [37, e.TYPES.ENUM, h],
        support: [39, e.TYPES.ENUM, h],
        groupUiiCleanup: [40, e.TYPES.ENUM, h],
        groupDogfoodingInternalOnly: [41, e.TYPES.ENUM, h],
        settingsSync: [42, e.TYPES.ENUM, h],
        archiveV2: [43, e.TYPES.ENUM, h],
        ephemeralAllowGroupMembers: [44, e.TYPES.ENUM, h],
        ephemeral24HDuration: [45, e.TYPES.ENUM, h],
        mdForceUpgrade: [46, e.TYPES.ENUM, h],
        disappearingMode: [47, e.TYPES.ENUM, h],
        externalMdOptInAvailable: [48, e.TYPES.ENUM, h],
        noDeleteMessageTimeLimit: [49, e.TYPES.ENUM, h],
      }),
      (I.name = "ReportingTokenInfo"),
      (I.internalSpec = { reportingTag: [1, e.TYPES.BYTES] }),
      (T.name = "MediaData"),
      (T.internalSpec = { localPath: [1, e.TYPES.STRING] }),
      (D.name = "PhotoChange"),
      (D.internalSpec = {
        oldPhoto: [1, e.TYPES.BYTES],
        newPhoto: [2, e.TYPES.BYTES],
        newPhotoId: [3, e.TYPES.UINT32],
      }),
      (x.name = "StatusPSA"),
      (x.internalSpec = {
        campaignId: [44, e.FLAGS.REQUIRED | e.TYPES.UINT64],
        campaignExpirationTimestamp: [45, e.TYPES.UINT64],
      }),
      ($.name = "UserReceipt"),
      ($.internalSpec = {
        userJid: [1, e.FLAGS.REQUIRED | e.TYPES.STRING],
        receiptTimestamp: [2, e.TYPES.INT64],
        readTimestamp: [3, e.TYPES.INT64],
        playedTimestamp: [4, e.TYPES.INT64],
        pendingDeviceJid: [5, e.FLAGS.REPEATED | e.TYPES.STRING],
        deliveredDeviceJid: [6, e.FLAGS.REPEATED | e.TYPES.STRING],
      }),
      (P.name = "Reaction"),
      (P.internalSpec = {
        key: [1, e.TYPES.MESSAGE, s.MessageKeySpec],
        text: [2, e.TYPES.STRING],
        groupingKey: [3, e.TYPES.STRING],
        senderTimestampMs: [4, e.TYPES.INT64],
        unread: [5, e.TYPES.BOOL],
      }),
      (N.name = "PollUpdate"),
      (N.internalSpec = {
        pollUpdateMessageKey: [1, e.TYPES.MESSAGE, s.MessageKeySpec],
        vote: [2, e.TYPES.MESSAGE, u.Message$PollVoteMessageSpec],
        senderTimestampMs: [3, e.TYPES.INT64],
        serverTimestampMs: [4, e.TYPES.INT64],
        unread: [5, e.TYPES.BOOL],
      }),
      (M.name = "PollAdditionalMetadata"),
      (M.internalSpec = { pollInvalidated: [1, e.TYPES.BOOL] }),
      (w.name = "InteractiveMessageAdditionalMetadata"),
      (w.internalSpec = { isGalaxyFlowCompleted: [1, e.TYPES.BOOL] }),
      (A.name = "EventAdditionalMetadata"),
      (A.internalSpec = { isStale: [1, e.TYPES.BOOL] }),
      (F.name = "KeepInChat"),
      (F.internalSpec = {
        keepType: [1, e.TYPES.ENUM, u.KeepType],
        serverTimestamp: [2, e.TYPES.INT64],
        key: [3, e.TYPES.MESSAGE, s.MessageKeySpec],
        deviceJid: [4, e.TYPES.STRING],
        clientTimestampMs: [5, e.TYPES.INT64],
        serverTimestampMs: [6, e.TYPES.INT64],
      }),
      (O.name = "PinInChat"),
      (O.internalSpec = {
        type: [1, e.TYPES.ENUM, y],
        key: [2, e.TYPES.MESSAGE, s.MessageKeySpec],
        senderTimestampMs: [3, e.TYPES.INT64],
        serverTimestampMs: [4, e.TYPES.INT64],
        messageAddOnContextInfo: [5, e.TYPES.MESSAGE, B],
      }),
      (B.name = "MessageAddOnContextInfo"),
      (B.internalSpec = {
        messageAddOnDurationInSecs: [1, e.TYPES.UINT32],
        messageAddOnExpiryType: [
          2,
          e.TYPES.ENUM,
          u.MessageContextInfo$MessageAddonExpiryType,
        ],
      }),
      (W.name = "PremiumMessageInfo"),
      (W.internalSpec = { serverCampaignId: [1, e.TYPES.STRING] }),
      (q.name = "EventResponse"),
      (q.internalSpec = {
        eventResponseMessageKey: [1, e.TYPES.MESSAGE, s.MessageKeySpec],
        timestampMs: [2, e.TYPES.INT64],
        eventResponseMessage: [
          3,
          e.TYPES.MESSAGE,
          u.Message$EventResponseMessageSpec,
        ],
        unread: [4, e.TYPES.BOOL],
      }),
      (U.name = "LegacyMessage"),
      (U.internalSpec = {
        eventResponseMessage: [
          1,
          e.TYPES.MESSAGE,
          u.Message$EventResponseMessageSpec,
        ],
        pollVote: [2, e.TYPES.MESSAGE, u.Message$PollVoteMessageSpec],
      }),
      (V.internalDefaults = { status: p.PENDING }),
      (V.name = "MessageAddOn"),
      (V.internalSpec = {
        messageAddOnType: [1, e.TYPES.ENUM, C],
        messageAddOn: [2, e.TYPES.MESSAGE, u.MessageSpec],
        senderTimestampMs: [3, e.TYPES.INT64],
        serverTimestampMs: [4, e.TYPES.INT64],
        status: [5, e.TYPES.ENUM, p],
        addOnContextInfo: [6, e.TYPES.MESSAGE, B],
        messageAddOnKey: [7, e.TYPES.MESSAGE, s.MessageKeySpec],
        legacyMessage: [8, e.TYPES.MESSAGE, U],
      }),
      (H.name = "StatusMentionMessage"),
      (H.internalSpec = { quotedStatus: [1, e.TYPES.MESSAGE, u.MessageSpec] }),
      (G.name = "Citation"),
      (G.internalSpec = {
        title: [1, e.FLAGS.REQUIRED | e.TYPES.STRING],
        subtitle: [2, e.FLAGS.REQUIRED | e.TYPES.STRING],
        cmsId: [3, e.FLAGS.REQUIRED | e.TYPES.STRING],
        imageUrl: [4, e.FLAGS.REQUIRED | e.TYPES.STRING],
      }),
      (z.name = "GroupHistoryIndividualMessageInfo"),
      (z.internalSpec = {
        bundleMessageKey: [1, e.TYPES.MESSAGE, s.MessageKeySpec],
        editedAfterReceivedAsHistory: [2, e.TYPES.BOOL],
      }),
      (j.name = "GroupHistoryBundleInfo"),
      (j.internalSpec = {
        deprecatedMessageHistoryBundle: [
          1,
          e.TYPES.MESSAGE,
          u.Message$MessageHistoryBundleSpec,
        ],
        processState: [2, e.TYPES.ENUM, b],
      }),
      (K.name = "QuarantinedMessage"),
      (K.internalSpec = {
        originalData: [1, e.TYPES.BYTES],
        extractedText: [2, e.TYPES.STRING],
      }),
      (Q.name = "ScheduledMessageMetadata"),
      (Q.internalSpec = {
        revealKeyId: [1, e.TYPES.STRING],
        revealKey: [2, e.TYPES.BYTES],
        scheduledTime: [3, e.TYPES.UINT64],
      }),
      (l.WebMessageInfo$BizPrivacyStatus = d),
      (l.WebMessageInfo$StubType = m),
      (l.WebMessageInfo$Status = p),
      (l.PaymentInfo$TxnStatus = _),
      (l.PaymentInfo$Status = f),
      (l.PaymentInfo$Currency = g),
      (l.WebFeatures$Flag = h),
      (l.PinInChat$Type = y),
      (l.MessageAddOn$MessageAddOnType = C),
      (l.GroupHistoryBundleInfo$ProcessState = b),
      (l.WebMessageInfoSpec = v),
      (l.CommentMetadataSpec = S),
      (l.PaymentInfoSpec = R),
      (l.WebNotificationsInfoSpec = L),
      (l.NotificationMessageInfoSpec = E),
      (l.WebFeaturesSpec = k),
      (l.ReportingTokenInfoSpec = I),
      (l.MediaDataSpec = T),
      (l.PhotoChangeSpec = D),
      (l.StatusPSASpec = x),
      (l.UserReceiptSpec = $),
      (l.ReactionSpec = P),
      (l.PollUpdateSpec = N),
      (l.PollAdditionalMetadataSpec = M),
      (l.InteractiveMessageAdditionalMetadataSpec = w),
      (l.EventAdditionalMetadataSpec = A),
      (l.KeepInChatSpec = F),
      (l.PinInChatSpec = O),
      (l.MessageAddOnContextInfoSpec = B),
      (l.PremiumMessageInfoSpec = W),
      (l.EventResponseSpec = q),
      (l.LegacyMessageSpec = U),
      (l.MessageAddOnSpec = V),
      (l.StatusMentionMessageSpec = H),
      (l.CitationSpec = G),
      (l.GroupHistoryIndividualMessageInfoSpec = z),
      (l.GroupHistoryBundleInfoSpec = j),
      (l.QuarantinedMessageSpec = K),
      (l.ScheduledMessageMetadataSpec = Q));
  },
  98,
);
