__d(
  "WAWebWamEnumPathfinderHealthEventType",
  [],
  function (t, n, r, o, a, i) {
    var e = Object.freeze({
      CHANNEL_SEND_FAILURE: 1,
      EVENT_PROCESSING_EXCEPTION: 2,
      INTERACTION_BUFFER_OVERFLOW: 3,
      PRE_INTERACTION_BUFFER_OVERFLOW: 4,
      DISK_WRITE_FAILURE: 5,
      DISK_READ_FAILURE: 6,
      FILE_ROTATION_FAILURE: 7,
      SERIALIZATION_FAILURE: 8,
      CORRUPT_DATA_SKIPPED: 9,
      DISK_STORE_DEGRADATION: 10,
      LOGGER_EXCEPTION: 11,
      MALFORMED_METADATA: 12,
      TRACE_PROVIDER_FAILURE: 13,
      DIRECTORY_CREATION_FAILURE: 14,
      FILE_DELETE_FAILURE: 15,
      SESSION_ID_UNAVAILABLE: 16,
      RESOURCE_NAME_RESOLUTION_FAILED: 17,
      UNSUPPORTED_USER_ACTION: 18,
      MAIN_THREAD_FILE_IO: 19,
      WEB_SESSION_FOOTPRINT: 20,
    });
    i.PATHFINDER_HEALTH_EVENT_TYPE = e;
  },
  66,
);
