__d(
  "WAWebCommonNewsletterEnums",
  ["$InternalEnum"],
  function (t, n, r, o, a, i) {
    var e,
      l = (e = n("$InternalEnum"))({
        Subscriber: "subscriber",
        Admin: "admin",
        Guest: "guest",
        Owner: "owner",
      }),
      s = e({ Public: "public", Private: "private" }),
      u = e({
        Active: "active",
        Suspended: "suspended",
        GeoSuspended: "geosuspended",
      }),
      c = e({ All: 0, Basic: 1, Blocklist: 2, None: 3 }),
      d = e.Mirrored([
        "GEOSUSPEND",
        "SUSPEND",
        "VIOLATING_MSG",
        "PROFILE_PICTURE_DELETION",
        "SUSPEND_INFORM",
        "GEOSUSPEND_INFORM",
      ]),
      m = e.Mirrored([
        "SUSPENDED_DETAILED_SCREEN",
        "DELETE_NEWSLETTER",
        "VIOLATING_MESSAGES_SCREEN",
        "PROFILE_PICTURE_DELETION_SCREEN",
        "GEOSUSPENDED_COUNTRY_DETAILED_SCREEN",
        "MULTIPLE_ALERTS_LIST_SCREEN",
        "REQUEST_REVIEW_DESCRIPTION_SCREEN",
        "REQUEST_REVIEW_REASON_SCREEN",
        "APPEAL_OUTCOME_SCREEN",
        "REMEDIATION_OPTIONS_SCREEN",
        "DSB_STEP1_SCREEN",
        "DSB_STEP2_SCREEN",
        "DSB_STEP3_SCREEN",
        "CONTACT_IP_REPORTER_STEP1_SCREEN",
        "CONTACT_IP_REPORTER_STEP2_SCREEN",
        "SUSPEND_INFORM_SCREEN",
        "RM_REQUEST_REVIEW_SCREEN_STEP1_SCREEN",
        "RM_REQUEST_REVIEW_SCREEN_STEP2_SCREEN",
        "RM_REQUEST_REVIEW_SCREEN_STEP3_SCREEN",
        "GEOSUSPEND_INFORM_SCREEN",
      ]),
      p = e.Mirrored([
        "IP_SRT_VIOLATION",
        "GENERIC_VIOLATION",
        "RM_COPS",
        "RM_PRODUCT_RESTRICTION",
        "LEGAL_TDR",
        "RESPONSE_VIOLATES_GUIDELINES",
      ]),
      _ = e({
        Insights: 0,
        PhotoPolls: 1,
        QUESTIONS: 2,
        ADMIN_NOTIFICATIONS: 3,
        INVITE_ADMINS_BUTTON: 4,
        INVITE_FOLLOWERS: 5,
        QUIZ: 6,
        ADMIN_CONTEXT_CARD_1: 7,
        ADMIN_CONTEXT_CARD_2: 8,
        ADMIN_CONTEXT_CARD_3: 9,
        SHARE_STICKER_PACKS: 10,
        ADMIN_ONBOARDING: 11,
        ADMIN_ONBOARDING_2: 12,
        MUSIC: 13,
        NEW_MESSAGE_TYPES_TOOLTIP: 14,
        PINNING_NUDGE: 15,
        THREAD_MENU: 16,
        ADMIN_PROFILE: 17,
        CHANNEL_STATUS_PRODUCER: 18,
      }),
      f = e.Mirrored(["ACTIVE", "INACTIVE"]),
      g = e.Mirrored([
        "ENFORCEMENT",
        "REPORT",
        "RESPONSE_REPORT",
        "STATUS_REPORT",
      ]),
      h = e.Mirrored(["MESSAGE", "STATUS"]);
    ((i.NewsletterMembershipType = l),
      (i.NewsletterPrivacy = s),
      (i.NewsletterState = u),
      (i.NewsletterReactionCodesSetting = c),
      (i.EnforcementType = d),
      (i.AlertScreen = m),
      (i.NewsletterDSADecisionModalCategory = p),
      (i.NewsletterCapability = _),
      (i.WamoSubStatus = f),
      (i.ReviewType = g),
      (i.ViolatingContentType = h));
  },
  66,
);
