__d(
  "WAWebWamEnumPttMessageUserJourneyFailureReason",
  [],
  function (t, n, r, o, a, i) {
    var e = Object.freeze({
      FAIL_OTHER: 1,
      FAIL_CREATE_RECORDER: 2,
      FAIL_PREPARE_RECORDER: 3,
      FAIL_START_RECORDER: 4,
      FAIL_RESUME_RECORDER: 5,
      FAIL_MIC_PERMISSION: 6,
      FAIL_STORAGE_READ_WRITE_PERMISSION: 7,
      FAIL_MINIMUM_STORAGE_REQUIREMENT: 8,
      FAIL_PAUSE_RECORDER: 9,
      FAIL_MOVE_PTT_FILE_TO_PERMANENT_STORAGE_ON_SEND: 10,
      FAIL_STORE_PTT_FILE_IN_DRAFT_CACHE: 11,
      FAIL_RECORDER_STOP: 12,
      FAIL_DRAFT_PLAYBACK_START: 13,
      FAIL_DRAFT_PLAYBACK_SEEK: 14,
      FAIL_MIC_AND_STORAGE_READ_WRITE_PERMISSION: 15,
    });
    i.PTT_MESSAGE_USER_JOURNEY_FAILURE_REASON = e;
  },
  66,
);
