__d(
  "WAWebWamEnumStickerSendOriginType",
  [],
  function (t, n, r, o, a, i) {
    var e = Object.freeze({
      STICKER_SEARCH: 1,
      FORWARD: 2,
      STICKER_PICKER_TAB_RECENTS: 3,
      STICKER_PICKER_TAB_FAVORITES: 4,
      STICKER_PICKER_TAB_EMOTION: 5,
      STICKER_PICKER_TAB_PACK: 6,
      STICKER_PICKER_TAB_CONTEXTUAL_SUGGESTIONS: 7,
      STICKER_MAKER: 8,
      STICKER_STORE: 9,
      AI_STICKER_CREATE: 10,
      AI_STICKER_CREATE_TRAY: 11,
      AI_STICKER_CREATE_CHAT: 12,
      STATUS_QUICK_REPLY: 13,
      DISCOVERY_PACK: 14,
      STICKER_FROM_DEVICE_KEYBOARD: 15,
      STICKER_PACK_INFO: 16,
      CONVERSATION_STARTER: 17,
      STICKER_SEARCH_TRENDING: 18,
    });
    i.STICKER_SEND_ORIGIN_TYPE = e;
  },
  66,
);
