__d(
  "WAWebLabyrinthWaWasm.pb",
  ["WAProtoConst"],
  function (t, n, r, o, a, i, l) {
    var e,
      s = {},
      u = {},
      c = {},
      d = {},
      m = {},
      p = {},
      _ = {},
      f = {},
      g = {},
      h = {},
      y = {};
    ((s.name = "CreateBackupInput"),
      (s.internalSpec = {
        recoveryCode: [
          1,
          (e = o("WAProtoConst")).FLAGS.REQUIRED | e.TYPES.STRING,
        ],
        userId: [2, e.FLAGS.REQUIRED | e.TYPES.UINT64],
      }),
      (u.name = "EncryptMessageInput"),
      (u.internalSpec = {
        epochRootKey: [1, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        mailboxRootKey: [2, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        orfClientState: [3, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        epochAnonId: [4, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        epochId: [5, e.FLAGS.REQUIRED | e.TYPES.UINT64],
        threadId: [6, e.FLAGS.REQUIRED | e.TYPES.STRING],
        waCanonicalUserFbid: [7, e.FLAGS.REQUIRED | e.TYPES.UINT64],
        timestampMs: [8, e.FLAGS.REQUIRED | e.TYPES.UINT64],
        backupId: [9, e.FLAGS.REQUIRED | e.TYPES.UINT64],
        plaintextPayload: [10, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        stanzaId: [11, e.FLAGS.REQUIRED | e.TYPES.STRING],
      }),
      (c.name = "DecryptMessageInput"),
      (c.internalSpec = {
        epochRootKey: [1, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        epochAnonId: [2, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        threadId: [3, e.FLAGS.REQUIRED | e.TYPES.STRING],
        encryptionVersion: [4, e.FLAGS.REQUIRED | e.TYPES.INT32],
        ciphertext: [5, e.FLAGS.REQUIRED | e.TYPES.BYTES],
      }),
      (d.name = "DeviceOutput"),
      (d.internalSpec = {
        publicKey: [1, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        epochAuthPublicKey: [2, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        epochAuthPublicKeySig: [3, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        epochStoragePublicKey: [4, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        epochStoragePublicKeySig: [5, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        supportedEncryptionVersions: [6, e.FLAGS.REPEATED | e.TYPES.INT32],
        encryptionVersionSignature: [7, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        clientVersion: [8, e.FLAGS.REQUIRED | e.TYPES.INT32],
        ocmfClientState: [9, e.FLAGS.REQUIRED | e.TYPES.BYTES],
      }),
      (m.name = "EncryptedSecretValuesOutput"),
      (m.internalSpec = {
        encryptedDevicePrivateKey: [1, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        encryptedObliviousValidationTokenBlob: [
          2,
          e.FLAGS.REQUIRED | e.TYPES.BYTES,
        ],
        encryptedEpochStoragePrivateKey: [3, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        encryptedOcmfClientState: [4, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        encryptedOrfClientStateV2: [5, e.TYPES.BYTES],
        encryptedMailboxRootKeyBlob: [6, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        encryptedEpochAnonId: [7, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        encryptedEpochRootKey: [8, e.FLAGS.REQUIRED | e.TYPES.BYTES],
      }),
      (p.name = "VirtualDeviceOutput"),
      (p.internalSpec = {
        vdId: [1, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        vdPublicKey: [2, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        vdEpochStoragePublicKey: [3, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        vdEpochStoragePublicKeySig: [4, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        ocmfRotationToken: [5, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        deviceEpochHmac: [6, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        encryptedSecretValues: [7, e.FLAGS.REQUIRED | e.TYPES.MESSAGE, m],
      }),
      (_.name = "Epoch0Output"),
      (_.internalSpec = {
        epochFbid: [1, e.FLAGS.REQUIRED | e.TYPES.UINT64],
        epochAnonId: [2, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        epochData: [3, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        wrappedRootKeyForSelf: [4, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        epochSignature: [5, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        epochRootKeyFingerprint: [6, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        epochRootKey: [7, e.TYPES.BYTES],
      }),
      (f.name = "CreateBackupOutput"),
      (f.internalSpec = {
        device: [1, e.TYPES.MESSAGE, d],
        virtualDevice: [2, e.TYPES.MESSAGE, p],
        epoch0: [3, e.TYPES.MESSAGE, _],
        mailboxRootKey: [4, e.TYPES.BYTES],
        error: [5, e.TYPES.STRING],
      }),
      (g.name = "EncryptMessageOutput"),
      (g.internalSpec = {
        encryptedProtobuf: [1, e.TYPES.BYTES],
        orfThreadId: [2, e.TYPES.BYTES],
        valueSecretRef: [3, e.TYPES.STRING],
        offlineThreadingId: [4, e.TYPES.UINT64],
        timestampMs: [5, e.TYPES.UINT64],
        messageKey: [6, e.TYPES.BYTES],
        error: [7, e.TYPES.STRING],
      }),
      (h.name = "DecryptMessageOutput"),
      (h.internalSpec = {
        plaintextPayload: [1, e.TYPES.BYTES],
        error: [2, e.TYPES.STRING],
      }),
      (y.name = "LabyrinthWaCommand"),
      (y.internalSpec = {
        createBackupInput: [1, e.TYPES.MESSAGE, s],
        encryptMessageInput: [2, e.TYPES.MESSAGE, u],
        decryptMessageInput: [3, e.TYPES.MESSAGE, c],
        __oneofs__: {
          commandInput: [
            "createBackupInput",
            "encryptMessageInput",
            "decryptMessageInput",
          ],
        },
      }),
      (l.CreateBackupInputSpec = s),
      (l.EncryptMessageInputSpec = u),
      (l.DecryptMessageInputSpec = c),
      (l.DeviceOutputSpec = d),
      (l.EncryptedSecretValuesOutputSpec = m),
      (l.VirtualDeviceOutputSpec = p),
      (l.Epoch0OutputSpec = _),
      (l.CreateBackupOutputSpec = f),
      (l.EncryptMessageOutputSpec = g),
      (l.DecryptMessageOutputSpec = h),
      (l.LabyrinthWaCommandSpec = y));
  },
  98,
);
