__d(
  "WAWebProtobufsServerSync.pb",
  ["$InternalEnum", "WAProtoConst"],
  function (t, n, r, o, a, i, l) {
    var e,
      s = n("$InternalEnum")({ SET: 0, REMOVE: 1 }),
      u = {},
      c = {},
      d = {},
      m = {},
      p = {},
      _ = {},
      f = {},
      g = {},
      h = {},
      y = {},
      C = {};
    ((u.name = "SyncdVersion"),
      (u.internalSpec = { version: [1, (e = o("WAProtoConst")).TYPES.UINT64] }),
      (c.name = "ExitCode"),
      (c.internalSpec = {
        code: [1, e.TYPES.UINT64],
        text: [2, e.TYPES.STRING],
      }),
      (d.name = "SyncdIndex"),
      (d.internalSpec = { blob: [1, e.TYPES.BYTES] }),
      (m.name = "SyncdValue"),
      (m.internalSpec = { blob: [1, e.TYPES.BYTES] }),
      (p.name = "KeyId"),
      (p.internalSpec = { id: [1, e.TYPES.BYTES] }),
      (_.name = "SyncdRecord"),
      (_.internalSpec = {
        index: [1, e.TYPES.MESSAGE, d],
        value: [2, e.TYPES.MESSAGE, m],
        keyId: [3, e.TYPES.MESSAGE, p],
      }),
      (f.name = "ExternalBlobReference"),
      (f.internalSpec = {
        mediaKey: [1, e.TYPES.BYTES],
        directPath: [2, e.TYPES.STRING],
        handle: [3, e.TYPES.STRING],
        fileSizeBytes: [4, e.TYPES.UINT64],
        fileSha256: [5, e.TYPES.BYTES],
        fileEncSha256: [6, e.TYPES.BYTES],
      }),
      (g.name = "SyncdSnapshot"),
      (g.internalSpec = {
        version: [1, e.TYPES.MESSAGE, u],
        records: [2, e.FLAGS.REPEATED | e.TYPES.MESSAGE, _],
        mac: [3, e.TYPES.BYTES],
        keyId: [4, e.TYPES.MESSAGE, p],
      }),
      (h.name = "SyncdMutations"),
      (h.internalSpec = {
        mutations: [1, e.FLAGS.REPEATED | e.TYPES.MESSAGE, y],
      }),
      (y.name = "SyncdMutation"),
      (y.internalSpec = {
        operation: [1, e.TYPES.ENUM, s],
        record: [2, e.TYPES.MESSAGE, _],
      }),
      (C.name = "SyncdPatch"),
      (C.internalSpec = {
        version: [1, e.TYPES.MESSAGE, u],
        mutations: [2, e.FLAGS.REPEATED | e.TYPES.MESSAGE, y],
        externalMutations: [3, e.TYPES.MESSAGE, f],
        snapshotMac: [4, e.TYPES.BYTES],
        patchMac: [5, e.TYPES.BYTES],
        keyId: [6, e.TYPES.MESSAGE, p],
        exitCode: [7, e.TYPES.MESSAGE, c],
        deviceIndex: [8, e.TYPES.UINT32],
        clientDebugData: [9, e.TYPES.BYTES],
      }),
      (l.SyncdMutation$SyncdOperation = s),
      (l.SyncdVersionSpec = u),
      (l.ExitCodeSpec = c),
      (l.SyncdIndexSpec = d),
      (l.SyncdValueSpec = m),
      (l.KeyIdSpec = p),
      (l.SyncdRecordSpec = _),
      (l.ExternalBlobReferenceSpec = f),
      (l.SyncdSnapshotSpec = g),
      (l.SyncdMutationsSpec = h),
      (l.SyncdMutationSpec = y),
      (l.SyncdPatchSpec = C));
  },
  98,
);
