__d(
  "WAWebDBMsgOpaqueDataKeys",
  [],
  function (t, n, r, o, a, i) {
    var e = [
        "body",
        "caption",
        "paymentAmount1000",
        "futureproofBuffer",
        "messageSecret",
        "clientUrl",
        "loc",
        "lng",
        "lat",
        "isLive",
        "matchedText",
        "title",
        "description",
        "pollName",
        "pollSelectableOptionsCount",
        "isSentCagPollCreation",
        "pollEndTime",
        "pollHideVoterNames",
        "pollAllowAddOption",
        "pollUpdateParentKey",
        "encPollVote",
        "senderTimestampMs",
        "targetMessageKey",
        "encIv",
        "encPayload",
        "eventName",
        "isEventCanceled",
        "eventDescription",
        "eventJoinLink",
        "eventStartTime",
        "eventLocation",
        "eventEndTime",
        "eventIsScheduledCall",
        "eventExtraGuestsAllowed",
        "quarantineExtractedText",
      ],
      l = ["targetMessageKey", "pollUpdateParentKey"],
      s = {
        targetMessageKey: "encReactionTargetMessageKey",
        encIv: "encReactionEncIv",
        encPayload: "encReactionEncPayload",
        encReactionTargetMessageKey: "targetMessageKey",
        encReactionEncIv: "encIv",
        encReactionEncPayload: "encPayload",
      };
    function u(e, t) {
      return e === "reaction_enc" ? s[t] : t;
    }
    ((i.MSG_OPAQUE_DATA_KEYS = e),
      (i.MsgKeyFieldsInOpaqueData = l),
      (i.getKey = u));
  },
  66,
);
