__d(
  "WAWebSyncdCryptoConst",
  [],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = "WhatsApp Mutation Keys",
      l = 160,
      s = 32,
      u = 32,
      c = 32,
      d = 32,
      m = 32,
      p = s,
      _ = p + u,
      f = _ + c,
      g = f + d,
      h = g + m,
      y = "0x01",
      C = "0x02",
      b = 0,
      v = 32,
      S = 8,
      R = 16;
    ((i.HKDF_INFO = e),
      (i.DERIVED_KEY_LENGTH = l),
      (i.INDEX_KEY_END = p),
      (i.VALUE_ENCRYPTION_KEY_END = _),
      (i.VALUE_MAC_KEY_END = f),
      (i.SNAPSHOT_MAC_KEY_END = g),
      (i.PATCH_MAC_KEY_END = h),
      (i.OPERATION_SET_HEX = y),
      (i.OPERATION_REMOVE_HEX = C),
      (i.MAX_OF_MIN_DATA_LENGTH = b),
      (i.MAC_LENGTH = v),
      (i.OCTET_LENGTH = S),
      (i.IV_LENGTH = R));
  },
  66,
);
