__d(
  "WAWebMsgType",
  [],
  function (t, n, r, o, a, i) {
    var e = {
        BROADCAST_NOTIFICATION: "broadcast_notification",
        CALL_LOG: "call_log",
        E2E_NOTIFICATION: "e2e_notification",
        GP2: "gp2",
        HISTORY_BUNDLE: "history_bundle",
        NEWSLETTER_NOTIFICATION: "newsletter_notification",
        NOTIFICATION: "notification",
        NOTIFICATION_TEMPLATE: "notification_template",
        PROTOCOL: "protocol",
        ALBUM: "album",
        AUDIO: "audio",
        AUTOMATED_GREETING_MESSAGE: "automated_greeting_message",
        BIZ_CONTENT_PLACEHOLDER: "biz_content_placeholder",
        BIZ_COVER_PHOTO: "biz-cover-photo",
        BUTTONS_RESPONSE: "buttons_response",
        CHAT: "chat",
        CIPHERTEXT: "ciphertext",
        COMMENT: "comment",
        DEBUG: "debug",
        DEBUG_PLACEHOLDER: "debug_placeholder",
        DOCUMENT: "document",
        EVENT_CREATION: "event_creation",
        EVENT_EDIT_ENCRYPTED: "event_edit_encrypted",
        EVENT_RESPONSE: "event_response",
        GROUPS_V4_INVITE: "groups_v4_invite",
        HSM: "hsm",
        IMAGE: "image",
        INTERACTIVE: "interactive",
        INTERACTIVE_RESPONSE: "interactive_response",
        KEEP_IN_CHAT: "keep_in_chat",
        LIST: "list",
        LIST_RESPONSE: "list_response",
        LOADING_MEDIA: "loading_media",
        LOCATION: "location",
        MESSAGE_EDIT_ENCRYPTED: "message_edit_encrypted",
        MESSAGE_HISTORY_BUNDLE: "group-history",
        MESSAGE_HISTORY_NOTICE: "message_history_notice",
        MULTI_VCARD: "multi_vcard",
        NATIVE_FLOW: "native_flow",
        NEWSLETTER_ADMIN_INVITE: "newsletter_admin_invite",
        NEWSLETTER_FOLLOWER_INVITE: "newsletter_follower_invite",
        NEWSLETTER_QUESTION_RESPONSE: "newsletter_question_response",
        ORDER: "order",
        OVERSIZED: "oversized",
        PAYMENT: "payment",
        PIN_MESSAGE: "pin_message",
        PINNED_MESSAGE: "pinned_message",
        POLL_ADD_OPTION_DECRYPTED: "poll_add_option_decrypted",
        POLL_ADD_OPTION_ENCRYPTED: "poll_add_option_encrypted",
        POLL_CREATION: "poll_creation",
        POLL_EDIT_ENCRYPTED: "poll_edit_encrypted",
        POLL_RESULT_SNAPSHOT: "poll_result_snapshot",
        POLL_UPDATE: "poll_update",
        PRODUCT: "product",
        PTT: "ptt",
        PTV: "ptv",
        QUARANTINED: "quarantined",
        REACTION: "reaction",
        REACTION_ENC: "reaction_enc",
        REQUEST_PHONE_NUMBER: "request_phone_number",
        REVOKED: "revoked",
        RICH_RESPONSE: "rich_response",
        STATUS: "status",
        STATUS_NOTIFICATION: "status_notification",
        STICKER: "sticker",
        STICKER_PACK: "sticker-pack",
        GUEST_UPSELL_SYSTEM_MSG: "guest_upsell_system_msg",
        TEMPLATE_BUTTON_REPLY: "template_button_reply",
        UNKNOWN: "unknown",
        VCARD: "vcard",
        VIDEO: "video",
      },
      l = { MEDIA_MSG: 1, DOC_MSG: 2, HAS_LINK: 4 },
      s = new Set(
        Object.keys(e).map(function (t) {
          return e[t];
        }),
      ),
      u = [
        "broadcast_notification",
        "call_log",
        "debug",
        "e2e_notification",
        "gp2",
        "newsletter_notification",
        "notification",
        "notification_template",
        "protocol",
        "pinned_message",
        "poll_add_option_decrypted",
      ],
      c = {
        Album: "album",
        AssociatedImage: "associatedImage",
        AssociatedUnknown: "associatedUnknown",
        AssociatedVideo: "associatedVideo",
        Audio: "audio",
        AutomatedGreetingMessage: "automatedGreetingMessage",
        BizContentPlaceholder: "bizContentPlaceholder",
        BizCoverPhoto: "bizCoverPhoto",
        BroadcastNotification: "broadcastNotification",
        ButtonsResponse: "buttonsResponse",
        CallLog: "callLog",
        Chat: "chat",
        Ciphertext: "ciphertext",
        CommentDecrypted: "commentDecrypted",
        CommentEncrypted: "commentEncrypted",
        Debug: "debug",
        DebugPlaceholder: "debugPlaceholder",
        Document: "document",
        E2eNotification: "e2eNotification",
        EventCreation: "eventCreation",
        EventEditDecrypted: "eventEditDecrypted",
        EventEditEncrypted: "eventEditEncrypted",
        EventResponseDecrypted: "eventResponseDecrypted",
        EventResponseEncrypted: "eventResponseEncrypted",
        Gp2: "gp2",
        GroupsV4Invite: "groupsV4Invite",
        Historybundle: "historyBundle",
        Hsm: "hsm",
        Image: "image",
        Interactive: "interactive",
        InteractiveResponse: "interactiveResponse",
        KeepInChat: "keepInChat",
        List: "list",
        ListResponse: "listResponse",
        LoadingMedia: "loadingMedia",
        Location: "location",
        LocationLive: "locationLive",
        MessageEditEncrypted: "messageEditEncrypted",
        MessageEditDecrypted: "messageEditDecrypted",
        MessageHistoryBundle: "messageHistoryBundle",
        MemberLabel: "memberLabel",
        MessageHistoryNotice: "messageHistoryNotice",
        MultiVcard: "multiVcard",
        NativeFlow: "nativeFlow",
        NewsletterAdminInvite: "newsletterAdminInvite",
        NewsletterFollowerInvite: "newsletterFollowerInvite",
        NewsletterNotification: "newsletterNotification",
        NewsletterQuestionResponse: "newsletterQuestionResponse",
        Notification: "notification",
        NotificationTemplate: "notificationTemplate",
        Order: "order",
        Oversized: "oversized",
        Payment: "payment",
        PeerMessage: "peerMessage",
        PinInChat: "pinInChat",
        PlaceholderMessage: "placeholderMessage",
        PlaceholderAddon: "placeholderAddon",
        PinnedMessage: "pinnedMessage",
        PollAddOptionDecrypted: "pollAddOptionDecrypted",
        PollAddOptionEncrypted: "pollAddOptionEncrypted",
        PollCreation: "pollCreation",
        PollEditDecrypted: "pollEditDecrypted",
        PollEditEncrypted: "pollEditEncrypted",
        PollResultSnapshot: "pollResultSnapshot",
        PollVoteDecrypted: "pollVoteDecrypted",
        PollVoteEncrypted: "pollVoteEncrypted",
        Product: "product",
        Protocol: "protocol",
        ProtocolAddonRevoke: "protocolAddonRevoke",
        ProtocolEventEdit: "protocolEventEdit",
        ProtocolPollEdit: "protocolPollEdit",
        ProtocolRevoke: "protocolRevoke",
        Ptt: "ptt",
        Ptv: "ptv",
        QuarantinedMessage: "quarantinedMessage",
        ReactionDecrypted: "reactionDecrypted",
        ReactionEncrypted: "reactionEncrypted",
        RequestPhoneNumber: "requestPhoneNumber",
        RevokedAddon: "revokedAddon",
        RevokedMessage: "revokedMessage",
        RichResponse: "richResponse",
        Sticker: "sticker",
        StickerPack: "stickerPack",
        Status: "status",
        SystemMsgUpsell: "systemMsgUpsell",
        TemplateButtonReply: "templateButtonReply",
        Unknown: "unknown",
        Vcard: "vcard",
        Video: "video",
      };
    ((i.MSG_TYPE = e),
      (i.MESSAGE_TYPE_FLAGS = l),
      (i.ALL_MSG_TYPES_SET = s),
      (i.SYSTEM_MESSAGE_TYPES = u),
      (i.MsgKind = c));
  },
  66,
);
