__d(
  "WAWebGettersCaches",
  [
    "WAWebABProps",
    "WAWebDummyCacheMap",
    "WAWebEnvironment",
    "WAWebLruCacheMap",
  ],
  function (t, n, r, o, a, i, l) {
    var e = function () {
        var e = o("WAWebABProps").getABPropConfigValue(
          "web_getters_lru_cache_size_limit",
        );
        return e > 0
          ? new (o("WAWebLruCacheMap").LruCacheMap)({ sizeLimit: e })
          : r("WAWebEnvironment").isWindows
            ? new (o("WAWebDummyCacheMap").FakeCacheMap)()
            : new Map();
      },
      s = function () {
        return e();
      },
      u = function () {
        return new (o("WAWebDummyCacheMap").FakeCacheMap)();
      },
      c = function () {
        return new (o("WAWebDummyCacheMap").FakeCacheMap)();
      },
      d = function () {
        return new (o("WAWebDummyCacheMap").FakeCacheMap)();
      },
      m = function () {
        var e = o("WAWebABProps").getABPropConfigValue(
          "web_getters_lru_cache_size_limit",
        );
        return e > 0
          ? new (o("WAWebLruCacheMap").LruCacheMap)({ sizeLimit: e })
          : new Map();
      },
      p = s,
      _ = s,
      f = s,
      g = s,
      h = m,
      y = m,
      C = s,
      b = s,
      v = s,
      S = s,
      R = s,
      L = s,
      E = s,
      k = s,
      I = s,
      T = s,
      D = s,
      x = s,
      $ = s,
      P = s,
      N = d,
      M = s,
      w = s,
      A = s,
      F = s,
      O = s,
      B = s,
      W = s,
      q = s,
      U = s,
      V = s,
      H = s,
      G = s,
      z = s,
      j = s,
      K = s,
      Q = s,
      X = s,
      Y = s,
      J = s,
      Z = s,
      ee = s,
      te = s,
      ne = s,
      re = s,
      oe = s,
      ae = s,
      ie = s,
      le = s,
      se = s,
      ue = s,
      ce = s,
      de = s,
      me = s,
      pe = s,
      _e = s,
      fe = s,
      ge = s,
      he = u,
      ye = u,
      Ce = s,
      be = c,
      ve = s,
      Se = s,
      Re = s,
      Le = s,
      Ee = s,
      ke = s,
      Ie = s;
    ((l.createMessagesCache = p),
      (l.createFrontendMessagesCache = _),
      (l.createChatCache = f),
      (l.createFrontendChatCache = g),
      (l.createContactsCache = h),
      (l.createFrontendContactsCache = y),
      (l.createLabelsCache = C),
      (l.createMuteCache = b),
      (l.createPinInChatsCache = v),
      (l.createFrontendPinInChatsCache = S),
      (l.createMsgInfosCache = R),
      (l.createPollVotesCache = L),
      (l.createFrontendPollVotesCache = E),
      (l.createNewsletterPollVotesCache = k),
      (l.createFrontendNewsletterPollVotesCache = I),
      (l.createSettingsCache = T),
      (l.createStickerModelMdCache = D),
      (l.createStickerCache = x),
      (l.createFrontendStickerCache = $),
      (l.createMediaEditControllerCache = P),
      (l.createMediaDataCache = N),
      (l.createOrderCache = M),
      (l.createOrderItemCache = w),
      (l.createQuickReplyCache = A),
      (l.createFrontendQuickReplyCache = F),
      (l.createStatusCache = O),
      (l.createFrontendStatusCache = B),
      (l.createRecordingSessionCache = W),
      (l.createEventResponseCache = q),
      (l.createFrontendEventResponseCache = U),
      (l.createAiThreadCache = V),
      (l.createCartCache = H),
      (l.createCatalogCache = G),
      (l.createFrontendCatalogCache = z),
      (l.createUnjoinedSubgroupMetadataCache = j),
      (l.createPresenceCache = K),
      (l.createChatstateCache = Q),
      (l.createFrontendPresenceCache = X),
      (l.createReactionsSendersCache = Y),
      (l.createNewsletterMetadataCache = J),
      (l.createFrontendNewsletterMetadataCache = Z),
      (l.createNewsletterLoadingStageManagerCache = ee),
      (l.createBusinessProfileCache = te),
      (l.createFrontendBusinessProfileCache = ne),
      (l.createCommandCache = re),
      (l.createPrimaryFeaturesCache = oe),
      (l.createPttPrefsCache = ae),
      (l.createNoticeCache = ie),
      (l.createBizBroadcastCampaignCache = le),
      (l.createProfilePicThumbCache = se),
      (l.createFrontendProfilePicThumbCache = ue),
      (l.createAttachMediaCache = ce),
      (l.createFrontendAttachMediaCache = de),
      (l.createConnCache = me),
      (l.createStreamCache = pe),
      (l.createNewsletterAdminInsightsCache = _e),
      (l.createCommentCache = fe),
      (l.createChatPreferenceCache = ge),
      (l.createButtonCache = he),
      (l.createFrontendButtonCache = ye),
      (l.createProductImageCache = Ce),
      (l.createProductCache = be),
      (l.createGroupParticipantCache = ve),
      (l.createBroadcastMetadataCache = Se),
      (l.createFrontendCommentCache = Re),
      (l.createGroupMetadataCache = Le),
      (l.createFrontendGroupMetadataCache = Ee),
      (l.createTextStatusCache = ke),
      (l.createFrontendTextStatusCache = Ie));
  },
  98,
);
