__d(
  "WAWebBizAdCreationRootQuery.graphql",
  [
    "WAWebBizAdCreationRootQuery_facebookRelayOperation",
    "LWICometIGUserIdDoubleWriteEnabled.relayprovider",
    "relay-runtime",
  ],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = (function () {
      var e = { defaultValue: null, kind: "LocalArgument", name: "draftID" },
        t = { defaultValue: null, kind: "LocalArgument", name: "input" },
        r = { defaultValue: null, kind: "LocalArgument", name: "isFBAccount" },
        o = { defaultValue: null, kind: "LocalArgument", name: "isWAAccount" },
        a = { defaultValue: null, kind: "LocalArgument", name: "pageID" },
        i = [
          {
            kind: "Literal",
            name: "caller",
            value: "CTWA_SMB_WEB_AD_CREATE_FLOW",
          },
          { kind: "Variable", name: "draft_id", variableName: "draftID" },
          { kind: "Variable", name: "input", variableName: "input" },
        ],
        l = [{ kind: "Variable", name: "id", variableName: "pageID" }],
        s = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "__typename",
          storageKey: null,
        },
        u = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "name",
          storageKey: null,
        },
        c = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "id",
          storageKey: null,
        },
        d = [
          {
            alias: "offsetAmount",
            args: null,
            kind: "ScalarField",
            name: "offset_amount",
            storageKey: null,
          },
        ],
        m = [s, c],
        p = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "type",
          storageKey: null,
        },
        _ = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "image_hash",
          storageKey: null,
        },
        f = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "image_url",
          storageKey: null,
        },
        g = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "instagram_actor_id",
          storageKey: null,
        },
        h = {
          condition:
            "__relay_internal__pv__LWICometIGUserIdDoubleWriteEnabledrelayprovider",
          kind: "Condition",
          passingValue: !0,
          selections: [
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "instagram_user_id",
              storageKey: null,
            },
          ],
        },
        y = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "app_link",
          storageKey: null,
        },
        C = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "event_id",
          storageKey: null,
        },
        b = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "link",
          storageKey: null,
        },
        v = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "whatsapp_number",
          storageKey: null,
        },
        S = {
          alias: null,
          args: null,
          concreteType: "AdCallToActionSpecification",
          kind: "LinkedField",
          name: "call_to_action",
          plural: !1,
          selections: [
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "call_to_action_type",
              storageKey: null,
            },
            {
              alias: null,
              args: null,
              concreteType: "AdCallToActionValueSpecification",
              kind: "LinkedField",
              name: "call_to_action_value",
              plural: !1,
              selections: [
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "app_destination",
                  storageKey: null,
                },
                y,
                C,
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "group_id",
                  storageKey: null,
                },
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "lead_gen_form_id",
                  storageKey: null,
                },
                b,
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "page_id",
                  storageKey: null,
                },
                v,
              ],
              storageKey: null,
            },
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "call_to_action_label",
              storageKey: null,
            },
          ],
          storageKey: null,
        },
        R = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "description",
          storageKey: null,
        },
        L = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "picture",
          storageKey: null,
        },
        E = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "video_id",
          storageKey: null,
        },
        k = [
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "x",
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "y",
            storageKey: null,
          },
        ],
        I = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "message",
          storageKey: null,
        },
        T = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "url",
          storageKey: null,
        },
        D = [
          g,
          h,
          {
            alias: null,
            args: null,
            concreteType: "AdObjectStoryLinkDataSpecification",
            kind: "LinkedField",
            name: "link_data",
            plural: !1,
            selections: [
              S,
              {
                alias: null,
                args: null,
                concreteType: "AdObjectStoryChildLinkDataSpecification",
                kind: "LinkedField",
                name: "child_attachments",
                plural: !0,
                selections: [R, _, b, u, L, E],
                storageKey: null,
              },
              R,
              C,
              {
                alias: null,
                args: null,
                concreteType: "AdImageCropsSpecification",
                kind: "LinkedField",
                name: "image_crops",
                plural: !1,
                selections: [
                  {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "crop_dimension",
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: null,
                    concreteType: "PointPositionSpecification",
                    kind: "LinkedField",
                    name: "lower_right",
                    plural: !1,
                    selections: k,
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: null,
                    concreteType: "PointPositionSpecification",
                    kind: "LinkedField",
                    name: "upper_left",
                    plural: !1,
                    selections: k,
                    storageKey: null,
                  },
                ],
                storageKey: null,
              },
              _,
              b,
              I,
              u,
              L,
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "retailer_item_ids",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "use_flexible_image_aspect_ratio",
                storageKey: null,
              },
            ],
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            concreteType: "NodeWrapper",
            kind: "LinkedField",
            name: "page",
            plural: !1,
            selections: [
              {
                alias: null,
                args: null,
                concreteType: null,
                kind: "LinkedField",
                name: "node",
                plural: !1,
                selections: m,
                storageKey: null,
              },
            ],
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            concreteType: "AdObjectStoryPhotoDataSpecification",
            kind: "LinkedField",
            name: "photo_data",
            plural: !1,
            selections: [
              S,
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "caption",
                storageKey: null,
              },
              _,
              T,
            ],
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            concreteType: "XFBAdObjectStoryProductDataSpecification",
            kind: "LinkedField",
            name: "product_data",
            plural: !0,
            selections: [
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "product_id",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "product_source",
                storageKey: null,
              },
            ],
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            concreteType: "AdObjectStoryVideoDataSpecification",
            kind: "LinkedField",
            name: "video_data",
            plural: !1,
            selections: [
              S,
              _,
              f,
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "link_description",
                storageKey: null,
              },
              I,
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "title",
                storageKey: null,
              },
              E,
            ],
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            concreteType: "AdObjectStoryTemplateDataSpecification",
            kind: "LinkedField",
            name: "template_data",
            plural: !1,
            selections: [
              S,
              b,
              u,
              R,
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "format_option",
                storageKey: null,
              },
              I,
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "multi_share_end_card",
                storageKey: null,
              },
            ],
            storageKey: null,
          },
        ],
        x = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "source",
          storageKey: null,
        };
      return {
        fragment: {
          argumentDefinitions: [e, t, r, o, a],
          kind: "Fragment",
          metadata: null,
          name: "WAWebBizAdCreationRootQuery",
          selections: [
            {
              alias: null,
              args: null,
              concreteType: "LWIAPI",
              kind: "LinkedField",
              name: "lwi",
              plural: !1,
              selections: [
                {
                  alias: "boostedComponent",
                  args: i,
                  concreteType: null,
                  kind: "LinkedField",
                  name: "boosted_component_wrapper",
                  plural: !1,
                  selections: [
                    {
                      args: null,
                      kind: "FragmentSpread",
                      name: "WAWebBizAdCreationSAFRContextProvider_boostedComponentWrapper",
                    },
                    {
                      args: null,
                      kind: "FragmentSpread",
                      name: "WAWebBizAdCreationSpecContextProvider_boostedComponentWrapper",
                    },
                    {
                      args: null,
                      kind: "FragmentSpread",
                      name: "useWAWebBizAdCreationInitialAdgroupsWithPrefill_boostedComponentWrapper",
                    },
                    {
                      args: null,
                      kind: "FragmentSpread",
                      name: "WAWebBizAdCreationPlacementSection_boostedComponentWrapper",
                    },
                    {
                      args: null,
                      kind: "FragmentSpread",
                      name: "WAWebBizAdCreationRoot_adAccount",
                    },
                    {
                      args: null,
                      kind: "FragmentSpread",
                      name: "WAWebBizAdCreationBudgetSectionData",
                    },
                  ],
                  storageKey: null,
                },
              ],
              storageKey: null,
            },
            {
              args: null,
              kind: "FragmentSpread",
              name: "WAWebBizAdCreationPaymentSection_adAccounts",
            },
            {
              alias: null,
              args: l,
              concreteType: "Page",
              kind: "LinkedField",
              name: "page",
              plural: !1,
              selections: [
                {
                  args: null,
                  kind: "FragmentSpread",
                  name: "WAWebBizAdCreationPreviewSection_page",
                },
              ],
              storageKey: null,
            },
            {
              condition: "isFBAccount",
              kind: "Condition",
              passingValue: !0,
              selections: [
                {
                  alias: null,
                  args: null,
                  concreteType: null,
                  kind: "LinkedField",
                  name: "me",
                  plural: !1,
                  selections: [
                    {
                      args: null,
                      kind: "FragmentSpread",
                      name: "WAWebBizAdCreationPaymentSection_facebookProfile",
                    },
                  ],
                  storageKey: null,
                },
              ],
            },
            {
              condition: "isWAAccount",
              kind: "Condition",
              passingValue: !0,
              selections: [
                {
                  fragment: {
                    kind: "InlineFragment",
                    selections: [
                      {
                        args: null,
                        kind: "FragmentSpread",
                        name: "useWAWebBizAdCreationMaybeOpenEmailVerification_query",
                      },
                    ],
                    type: "Query",
                    abstractKey: null,
                  },
                  kind: "AliasedInlineFragmentSpread",
                  name: "waAdAccountOnboardingData",
                },
                {
                  fragment: {
                    kind: "InlineFragment",
                    selections: [
                      {
                        args: null,
                        kind: "FragmentSpread",
                        name: "useWAWebBizAdCreationMaybeOpenEmailOnboarding_query",
                      },
                    ],
                    type: "Query",
                    abstractKey: null,
                  },
                  kind: "AliasedInlineFragmentSpread",
                  name: "emailOnboardingData",
                },
              ],
            },
          ],
          type: "Query",
          abstractKey: null,
        },
        kind: "Request",
        operation: {
          argumentDefinitions: [
            t,
            e,
            r,
            o,
            a,
            {
              defaultValue: null,
              kind: "LocalArgument",
              name: "__relay_internal__pv__LWICometIGUserIdDoubleWriteEnabledrelayprovider",
            },
          ],
          kind: "Operation",
          name: "WAWebBizAdCreationRootQuery",
          selections: [
            {
              alias: null,
              args: null,
              concreteType: "LWIAPI",
              kind: "LinkedField",
              name: "lwi",
              plural: !1,
              selections: [
                {
                  alias: "boostedComponent",
                  args: i,
                  concreteType: null,
                  kind: "LinkedField",
                  name: "boosted_component_wrapper",
                  plural: !1,
                  selections: [
                    s,
                    {
                      kind: "TypeDiscriminator",
                      abstractKey: "__isBoostedComponentCommonWrapper",
                    },
                    {
                      alias: null,
                      args: null,
                      concreteType: "SAFRDynamicUIPolicy",
                      kind: "LinkedField",
                      name: "safr_data",
                      plural: !1,
                      selections: [
                        {
                          alias: null,
                          args: null,
                          concreteType: "SAFRDynamicUIRestrictions",
                          kind: "LinkedField",
                          name: "restrictions",
                          plural: !1,
                          selections: [
                            {
                              alias: null,
                              args: null,
                              concreteType: "SAFRConversionConfig",
                              kind: "LinkedField",
                              name: "conversion",
                              plural: !1,
                              selections: [
                                {
                                  alias: null,
                                  args: null,
                                  kind: "ScalarField",
                                  name: "promoted_object_blacklist",
                                  storageKey: null,
                                },
                              ],
                              storageKey: null,
                            },
                            {
                              alias: null,
                              args: null,
                              concreteType: "SAFRFormatConfig",
                              kind: "LinkedField",
                              name: "format",
                              plural: !1,
                              selections: [
                                {
                                  alias: null,
                                  args: null,
                                  kind: "ScalarField",
                                  name: "format_blacklist",
                                  storageKey: null,
                                },
                              ],
                              storageKey: null,
                            },
                            {
                              alias: null,
                              args: null,
                              concreteType: "SAFRObjectiveConfig",
                              kind: "LinkedField",
                              name: "objective",
                              plural: !1,
                              selections: [
                                {
                                  alias: null,
                                  args: null,
                                  kind: "ScalarField",
                                  name: "objective_blacklist",
                                  storageKey: null,
                                },
                              ],
                              storageKey: null,
                            },
                            {
                              alias: null,
                              args: null,
                              concreteType: "SAFRPlacementsConfig",
                              kind: "LinkedField",
                              name: "placements",
                              plural: !1,
                              selections: [
                                {
                                  alias: null,
                                  args: null,
                                  kind: "ScalarField",
                                  name: "platform_blacklist",
                                  storageKey: null,
                                },
                              ],
                              storageKey: null,
                            },
                            {
                              alias: null,
                              args: null,
                              concreteType: "SAFRAgeConfig",
                              kind: "LinkedField",
                              name: "age",
                              plural: !1,
                              selections: [
                                {
                                  alias: null,
                                  args: null,
                                  kind: "ScalarField",
                                  name: "default_max_age",
                                  storageKey: null,
                                },
                                {
                                  alias: null,
                                  args: null,
                                  kind: "ScalarField",
                                  name: "default_min_age",
                                  storageKey: null,
                                },
                                {
                                  alias: null,
                                  args: null,
                                  kind: "ScalarField",
                                  name: "max_age_range",
                                  storageKey: null,
                                },
                                {
                                  alias: null,
                                  args: null,
                                  kind: "ScalarField",
                                  name: "min_age_range",
                                  storageKey: null,
                                },
                                {
                                  alias: null,
                                  args: null,
                                  kind: "ScalarField",
                                  name: "is_max_age_fixed",
                                  storageKey: null,
                                },
                                {
                                  alias: null,
                                  args: null,
                                  kind: "ScalarField",
                                  name: "is_min_age_fixed",
                                  storageKey: null,
                                },
                              ],
                              storageKey: null,
                            },
                            {
                              alias: null,
                              args: null,
                              concreteType: "SAFRGenderConfig",
                              kind: "LinkedField",
                              name: "gender",
                              plural: !1,
                              selections: [
                                {
                                  alias: null,
                                  args: null,
                                  kind: "ScalarField",
                                  name: "is_enabled",
                                  storageKey: null,
                                },
                              ],
                              storageKey: null,
                            },
                            {
                              alias: null,
                              args: null,
                              concreteType: "SAFRLocationRadiusConfig",
                              kind: "LinkedField",
                              name: "location_radius",
                              plural: !1,
                              selections: [
                                {
                                  alias: null,
                                  args: null,
                                  kind: "ScalarField",
                                  name: "default_radius_unit",
                                  storageKey: null,
                                },
                                {
                                  alias: null,
                                  args: null,
                                  kind: "ScalarField",
                                  name: "default_radius_value",
                                  storageKey: null,
                                },
                                {
                                  alias: null,
                                  args: null,
                                  kind: "ScalarField",
                                  name: "max_radius",
                                  storageKey: null,
                                },
                                {
                                  alias: null,
                                  args: null,
                                  kind: "ScalarField",
                                  name: "min_radius",
                                  storageKey: null,
                                },
                              ],
                              storageKey: null,
                            },
                          ],
                          storageKey: null,
                        },
                      ],
                      storageKey: null,
                    },
                    {
                      alias: null,
                      args: null,
                      concreteType: null,
                      kind: "LinkedField",
                      name: "spec",
                      plural: !1,
                      selections: [
                        s,
                        {
                          alias: null,
                          args: null,
                          kind: "ScalarField",
                          name: "regulated_categories",
                          storageKey: null,
                        },
                        {
                          alias: null,
                          args: null,
                          concreteType: "AdsLWIAudience",
                          kind: "LinkedField",
                          name: "audience",
                          plural: !1,
                          selections: [
                            {
                              alias: null,
                              args: null,
                              kind: "ScalarField",
                              name: "audience_key",
                              storageKey: null,
                            },
                            {
                              alias: null,
                              args: null,
                              kind: "ScalarField",
                              name: "audience_option",
                              storageKey: null,
                            },
                            {
                              alias: null,
                              args: null,
                              kind: "ScalarField",
                              name: "client_editable",
                              storageKey: null,
                            },
                            u,
                            {
                              alias: null,
                              args: null,
                              kind: "ScalarField",
                              name: "subject_to_dsa",
                              storageKey: null,
                            },
                            {
                              alias: null,
                              args: null,
                              kind: "ScalarField",
                              name: "target_spec_string_without_placements",
                              storageKey: null,
                            },
                            c,
                          ],
                          storageKey: null,
                        },
                        {
                          alias: null,
                          args: null,
                          concreteType: "CurrencyQuantity",
                          kind: "LinkedField",
                          name: "budget",
                          plural: !1,
                          selections: d,
                          storageKey: null,
                        },
                        {
                          alias: "durationInDays",
                          args: null,
                          kind: "ScalarField",
                          name: "duration_in_days",
                          storageKey: null,
                        },
                        {
                          alias: null,
                          args: [
                            { kind: "Literal", name: "is_forced", value: !0 },
                          ],
                          concreteType: "AdAccount",
                          kind: "LinkedField",
                          name: "ad_account",
                          plural: !1,
                          selections: [
                            c,
                            u,
                            {
                              alias: "legacyAccountID",
                              args: null,
                              kind: "ScalarField",
                              name: "legacy_account_id",
                              storageKey: null,
                            },
                            {
                              alias: "currencyCodeEnum",
                              args: null,
                              kind: "ScalarField",
                              name: "currency_code_enum",
                              storageKey: null,
                            },
                            {
                              alias: "canSeeSAFRV3",
                              args: [
                                {
                                  kind: "Literal",
                                  name: "capability",
                                  value: "CAN_SEE_SAFR_V3_FLOW",
                                },
                              ],
                              kind: "ScalarField",
                              name: "has_capability",
                              storageKey:
                                'has_capability(capability:"CAN_SEE_SAFR_V3_FLOW")',
                            },
                            {
                              alias: null,
                              args: null,
                              concreteType: null,
                              kind: "LinkedField",
                              name: "payment_account",
                              plural: !1,
                              selections: m,
                              storageKey: null,
                            },
                          ],
                          storageKey: "ad_account(is_forced:true)",
                        },
                        {
                          alias: null,
                          args: null,
                          concreteType: "AdsPlacementSpec",
                          kind: "LinkedField",
                          name: "placement_spec",
                          plural: !1,
                          selections: [
                            {
                              alias: null,
                              args: null,
                              kind: "ScalarField",
                              name: "publisher_platforms",
                              storageKey: null,
                            },
                          ],
                          storageKey: null,
                        },
                        {
                          kind: "TypeDiscriminator",
                          abstractKey: "__isBoostedComponentSpec",
                        },
                        {
                          alias: null,
                          args: null,
                          concreteType: "AdsLWIAdGroupSpec",
                          kind: "LinkedField",
                          name: "adgroup_spec",
                          plural: !0,
                          selections: [
                            {
                              alias: null,
                              args: null,
                              kind: "ScalarField",
                              name: "adgroup_id",
                              storageKey: null,
                            },
                            {
                              alias: null,
                              args: null,
                              kind: "ScalarField",
                              name: "adgroup_status",
                              storageKey: null,
                            },
                            {
                              alias: null,
                              args: null,
                              kind: "ScalarField",
                              name: "conversion_domain",
                              storageKey: null,
                            },
                            {
                              alias: null,
                              args: null,
                              concreteType: "AdsCreativeSpecification",
                              kind: "LinkedField",
                              name: "creative",
                              plural: !1,
                              selections: [
                                {
                                  alias: null,
                                  args: null,
                                  kind: "ScalarField",
                                  name: "asset_feed_spec_string",
                                  storageKey: null,
                                },
                                {
                                  alias: null,
                                  args: null,
                                  kind: "ScalarField",
                                  name: "authorization_category",
                                  storageKey: null,
                                },
                                {
                                  alias: null,
                                  args: null,
                                  kind: "ScalarField",
                                  name: "body",
                                  storageKey: null,
                                },
                                {
                                  alias: null,
                                  args: null,
                                  concreteType: "AdBrandedContentSpecification",
                                  kind: "LinkedField",
                                  name: "branded_content",
                                  plural: !1,
                                  selections: [
                                    {
                                      alias: null,
                                      args: null,
                                      kind: "ScalarField",
                                      name: "ad_format",
                                      storageKey: null,
                                    },
                                    {
                                      alias: null,
                                      args: null,
                                      kind: "ScalarField",
                                      name: "ui_version",
                                      storageKey: null,
                                    },
                                  ],
                                  storageKey: null,
                                },
                                {
                                  alias: null,
                                  args: null,
                                  kind: "ScalarField",
                                  name: "branded_content_boosting_type",
                                  storageKey: null,
                                },
                                {
                                  alias: null,
                                  args: null,
                                  concreteType:
                                    "AdCreativeSourcingSpecification",
                                  kind: "LinkedField",
                                  name: "creative_sourcing_spec",
                                  plural: !1,
                                  selections: [
                                    {
                                      alias: null,
                                      args: null,
                                      kind: "ScalarField",
                                      name: "associated_product_set_id",
                                      storageKey: null,
                                    },
                                  ],
                                  storageKey: null,
                                },
                                {
                                  alias: null,
                                  args: null,
                                  kind: "ScalarField",
                                  name: "degrees_of_freedom_type",
                                  storageKey: null,
                                },
                                {
                                  alias: null,
                                  args: null,
                                  concreteType:
                                    "AdCreativeDegreesOfFreedomSpecification",
                                  kind: "LinkedField",
                                  name: "degrees_of_freedom_spec",
                                  plural: !1,
                                  selections: [
                                    {
                                      alias: null,
                                      args: null,
                                      concreteType:
                                        "AdCreativeFeaturesSpecWrapper",
                                      kind: "LinkedField",
                                      name: "creative_features_spec",
                                      plural: !1,
                                      selections: [
                                        {
                                          alias: null,
                                          args: null,
                                          concreteType:
                                            "AdCreativeFeatureSpecAttachment",
                                          kind: "LinkedField",
                                          name: "product_extensions",
                                          plural: !1,
                                          selections: [
                                            {
                                              alias: null,
                                              args: null,
                                              concreteType:
                                                "XFBAdCreativeFeatureActionMetadataSpec",
                                              kind: "LinkedField",
                                              name: "action_metadata",
                                              plural: !1,
                                              selections: [p],
                                              storageKey: null,
                                            },
                                            {
                                              alias: null,
                                              args: null,
                                              kind: "ScalarField",
                                              name: "enroll_status",
                                              storageKey: null,
                                            },
                                          ],
                                          storageKey: null,
                                        },
                                      ],
                                      storageKey: null,
                                    },
                                  ],
                                  storageKey: null,
                                },
                                {
                                  alias: null,
                                  args: null,
                                  concreteType:
                                    "AdFacebookBrandedContentSpecification",
                                  kind: "LinkedField",
                                  name: "facebook_branded_content",
                                  plural: !1,
                                  selections: [
                                    {
                                      alias: null,
                                      args: null,
                                      kind: "ScalarField",
                                      name: "sponsor_page_id",
                                      storageKey: null,
                                    },
                                  ],
                                  storageKey: null,
                                },
                                _,
                                f,
                                g,
                                h,
                                {
                                  alias: null,
                                  args: null,
                                  concreteType:
                                    "AdInstagramBrandedContentSpecification",
                                  kind: "LinkedField",
                                  name: "instagram_branded_content",
                                  plural: !1,
                                  selections: [
                                    {
                                      alias: null,
                                      args: null,
                                      kind: "ScalarField",
                                      name: "sponsor_id",
                                      storageKey: null,
                                    },
                                  ],
                                  storageKey: null,
                                },
                                {
                                  alias: null,
                                  args: null,
                                  kind: "ScalarField",
                                  name: "instagram_story_id",
                                  storageKey: null,
                                },
                                {
                                  alias: null,
                                  args: null,
                                  kind: "ScalarField",
                                  name: "object_id",
                                  storageKey: null,
                                },
                                {
                                  alias: null,
                                  args: null,
                                  kind: "ScalarField",
                                  name: "object_story_id",
                                  storageKey: null,
                                },
                                {
                                  alias: null,
                                  args: null,
                                  concreteType: "AdObjectStorySpecification",
                                  kind: "LinkedField",
                                  name: "object_story_spec",
                                  plural: !1,
                                  selections: D,
                                  storageKey: null,
                                },
                                {
                                  alias: null,
                                  args: null,
                                  concreteType: "AdObjectStorySpecification",
                                  kind: "LinkedField",
                                  name: "catalog_story_spec",
                                  plural: !1,
                                  selections: D,
                                  storageKey: null,
                                },
                                {
                                  alias: null,
                                  args: null,
                                  kind: "ScalarField",
                                  name: "object_type",
                                  storageKey: null,
                                },
                                {
                                  alias: null,
                                  args: null,
                                  kind: "ScalarField",
                                  name: "product_set_id",
                                  storageKey: null,
                                },
                                {
                                  alias: null,
                                  args: null,
                                  kind: "ScalarField",
                                  name: "use_page_actor_override",
                                  storageKey: null,
                                },
                              ],
                              storageKey: null,
                            },
                            {
                              alias: null,
                              args: null,
                              kind: "ScalarField",
                              name: "creative_spec_json",
                              storageKey: null,
                            },
                            c,
                            {
                              alias: null,
                              args: null,
                              concreteType: "CreativeAssetGroupsSpec",
                              kind: "LinkedField",
                              name: "creative_asset_groups_spec",
                              plural: !1,
                              selections: [
                                {
                                  alias: null,
                                  args: null,
                                  concreteType: "CreativeAssetGroupSpec",
                                  kind: "LinkedField",
                                  name: "groups",
                                  plural: !0,
                                  selections: [
                                    {
                                      alias: null,
                                      args: null,
                                      concreteType:
                                        "CreativeAssetGroupImageSpec",
                                      kind: "LinkedField",
                                      name: "images",
                                      plural: !0,
                                      selections: [
                                        {
                                          alias: null,
                                          args: null,
                                          kind: "ScalarField",
                                          name: "hash",
                                          storageKey: null,
                                        },
                                        T,
                                        x,
                                      ],
                                      storageKey: null,
                                    },
                                    {
                                      alias: null,
                                      args: null,
                                      concreteType:
                                        "CreativeAssetGroupVideoSpec",
                                      kind: "LinkedField",
                                      name: "videos",
                                      plural: !0,
                                      selections: [
                                        _,
                                        f,
                                        x,
                                        {
                                          alias: null,
                                          args: null,
                                          kind: "ScalarField",
                                          name: "thumbnail_id",
                                          storageKey: null,
                                        },
                                        {
                                          alias: null,
                                          args: null,
                                          kind: "ScalarField",
                                          name: "thumbnail_source",
                                          storageKey: null,
                                        },
                                        E,
                                      ],
                                      storageKey: null,
                                    },
                                    {
                                      alias: null,
                                      args: null,
                                      concreteType:
                                        "CreativeAssetGroupTextSpec",
                                      kind: "LinkedField",
                                      name: "texts",
                                      plural: !0,
                                      selections: [
                                        {
                                          alias: null,
                                          args: null,
                                          kind: "ScalarField",
                                          name: "text_type",
                                          storageKey: null,
                                        },
                                        {
                                          alias: null,
                                          args: null,
                                          kind: "ScalarField",
                                          name: "text",
                                          storageKey: null,
                                        },
                                      ],
                                      storageKey: null,
                                    },
                                  ],
                                  storageKey: null,
                                },
                                {
                                  alias: null,
                                  args: null,
                                  kind: "ScalarField",
                                  name: "origins",
                                  storageKey: null,
                                },
                              ],
                              storageKey: null,
                            },
                          ],
                          storageKey: null,
                        },
                        {
                          alias: null,
                          args: null,
                          concreteType: "AdsLWICallToAction",
                          kind: "LinkedField",
                          name: "cta",
                          plural: !1,
                          selections: [y, p, b, v],
                          storageKey: null,
                        },
                      ],
                      storageKey: null,
                    },
                    {
                      alias: "boostedComponentOptions",
                      args: null,
                      concreteType: null,
                      kind: "LinkedField",
                      name: "options",
                      plural: !1,
                      selections: [
                        s,
                        {
                          alias: "budgetOptions",
                          args: [
                            {
                              kind: "Literal",
                              name: "granularity",
                              value: "HIGH",
                            },
                          ],
                          concreteType: "CurrencyQuantity",
                          kind: "LinkedField",
                          name: "budget_options",
                          plural: !0,
                          selections: d,
                          storageKey: 'budget_options(granularity:"HIGH")',
                        },
                      ],
                      storageKey: null,
                    },
                    {
                      alias: null,
                      args: null,
                      concreteType: null,
                      kind: "LinkedField",
                      name: "options",
                      plural: !1,
                      selections: [
                        s,
                        {
                          alias: null,
                          args: null,
                          concreteType: "AdsLWIPublisherPlatform",
                          kind: "LinkedField",
                          name: "eligible_publisher_platforms",
                          plural: !0,
                          selections: [
                            p,
                            {
                              alias: null,
                              args: null,
                              kind: "ScalarField",
                              name: "label",
                              storageKey: null,
                            },
                          ],
                          storageKey: null,
                        },
                      ],
                      storageKey: null,
                    },
                    {
                      alias: "contextSpec",
                      args: null,
                      concreteType: null,
                      kind: "LinkedField",
                      name: "context_spec",
                      plural: !1,
                      selections: [
                        s,
                        {
                          alias: null,
                          args: null,
                          concreteType: "Page",
                          kind: "LinkedField",
                          name: "page",
                          plural: !1,
                          selections: [T, c],
                          storageKey: null,
                        },
                      ],
                      storageKey: null,
                    },
                    {
                      alias: null,
                      args: null,
                      concreteType: "AdsLWIContraints",
                      kind: "LinkedField",
                      name: "constraints",
                      plural: !1,
                      selections: [
                        {
                          alias: "minDailyBudget",
                          args: null,
                          concreteType: "CurrencyQuantity",
                          kind: "LinkedField",
                          name: "min_daily_budget",
                          plural: !1,
                          selections: d,
                          storageKey: null,
                        },
                        {
                          alias: "maxDailyBudget",
                          args: null,
                          concreteType: "CurrencyQuantity",
                          kind: "LinkedField",
                          name: "max_daily_budget",
                          plural: !1,
                          selections: d,
                          storageKey: null,
                        },
                      ],
                      storageKey: null,
                    },
                    c,
                  ],
                  storageKey: null,
                },
              ],
              storageKey: null,
            },
            {
              alias: null,
              args: null,
              concreteType: "WaCtwaAdAccountsConnection",
              kind: "LinkedField",
              name: "wa_ctwa_ad_accounts",
              plural: !1,
              selections: [
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "count",
                  storageKey: null,
                },
              ],
              storageKey: null,
            },
            {
              if: null,
              kind: "Defer",
              label:
                "WAWebBizAdCreationPaymentSection_adAccounts$defer$useWAWebBizAdCreationOpenAdAccountSelectorModal_query",
              selections: [
                {
                  if: null,
                  kind: "Defer",
                  label:
                    "useWAWebBizAdCreationOpenAdAccountSelectorModal_query$defer$WAWebBizAdCreationPaymentAdAccountSelectorModal_query",
                  selections: [
                    {
                      alias: null,
                      args: null,
                      concreteType: "WaCtwaAdAccountsConnection",
                      kind: "LinkedField",
                      name: "wa_ctwa_ad_accounts",
                      plural: !1,
                      selections: [
                        {
                          alias: null,
                          args: null,
                          concreteType: "AdAccount",
                          kind: "LinkedField",
                          name: "nodes",
                          plural: !0,
                          selections: [
                            {
                              alias: null,
                              args: null,
                              kind: "ScalarField",
                              name: "legacy_account_id",
                              storageKey: null,
                            },
                            u,
                            c,
                          ],
                          storageKey: null,
                        },
                      ],
                      storageKey: null,
                    },
                  ],
                },
              ],
            },
            {
              alias: null,
              args: l,
              concreteType: "Page",
              kind: "LinkedField",
              name: "page",
              plural: !1,
              selections: [
                {
                  alias: null,
                  args: null,
                  concreteType: "Image",
                  kind: "LinkedField",
                  name: "profile_picture",
                  plural: !1,
                  selections: [
                    {
                      alias: null,
                      args: null,
                      kind: "ScalarField",
                      name: "uri",
                      storageKey: null,
                    },
                  ],
                  storageKey: null,
                },
                u,
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "is_verified",
                  storageKey: null,
                },
                c,
              ],
              storageKey: null,
            },
            {
              condition: "isFBAccount",
              kind: "Condition",
              passingValue: !0,
              selections: [
                {
                  alias: null,
                  args: null,
                  concreteType: null,
                  kind: "LinkedField",
                  name: "me",
                  plural: !1,
                  selections: [
                    s,
                    { kind: "TypeDiscriminator", abstractKey: "__isActor" },
                    u,
                    {
                      alias: null,
                      args: null,
                      concreteType: "Image",
                      kind: "LinkedField",
                      name: "profile_picture",
                      plural: !1,
                      selections: [
                        {
                          alias: null,
                          args: null,
                          kind: "ScalarField",
                          name: "downloadable_uri",
                          storageKey: null,
                        },
                      ],
                      storageKey: null,
                    },
                    c,
                  ],
                  storageKey: null,
                },
              ],
            },
            {
              condition: "isWAAccount",
              kind: "Condition",
              passingValue: !0,
              selections: [
                {
                  alias: null,
                  args: null,
                  concreteType: "WAAdAccountOnboardingAPI",
                  kind: "LinkedField",
                  name: "wa_ad_account_onboarding_data",
                  plural: !1,
                  selections: [
                    {
                      alias: null,
                      args: null,
                      kind: "ScalarField",
                      name: "email",
                      storageKey: null,
                    },
                  ],
                  storageKey: null,
                },
              ],
            },
          ],
        },
        params: {
          id: n("WAWebBizAdCreationRootQuery_facebookRelayOperation"),
          metadata: {},
          name: "WAWebBizAdCreationRootQuery",
          operationKind: "query",
          text: null,
          providedVariables: {
            __relay_internal__pv__LWICometIGUserIdDoubleWriteEnabledrelayprovider:
              n("LWICometIGUserIdDoubleWriteEnabled.relayprovider"),
          },
        },
      };
    })();
    (n("relay-runtime").PreloadableQueryRegistry.set(e.params.id, e),
      (a.exports = e));
  },
  null,
);
