__d(
  "WAWebE2ETestRobots",
  [],
  function (t, n, r, o, a, i) {
    var e = {
      "compose-box": "ComposeRobot",
      "conversation-panel-body": "ConversationPanelRobot",
      "conversation-header": "ConversationPanelHeaderRobot",
      "conversation-subheader": "ConversationSubheaderBannerRobot",
      "msg-container": "MessageRobot",
      "ui-showroom": "UiShowroomRobot",
      "spam-banner": "SpamBannerRobot",
      "lock-screen-landing-window": "LockScreenRobot",
      "blocked-contacts-drawer": "BlockedContactsSettingsRobot",
      "newsletter-drawer": "ChannelDrawerRobot",
      "chat-butterbar": "ChatButterbarRobot",
      "chat-list": "ChatListRobot",
      "community-deactivation-info-drawer": "CommunityDeactivationRobot",
      "community-settings-drawer": "CommunitySettingsDrawerRobot",
      "create-newsletter-drawer": "CreateChannelDrawerRobot",
      "developer-settings-drawer": "DeveloperSettingsRobot",
      "chatlist-header": "HeaderRobot",
      "drawer-title-help": "HelpRobot",
      "new-chat-drawer": "NewChatRobot",
      "privacy-settings-drawer": "PrivacySettingsRobot",
      "profile-drawer": "ProfileRobot",
      "screen-lock-drawer": "ScreenLockSettingsRobot",
      "security-settings-drawer": "SecuritySettingsRobot",
      "settings-drawer": "SettingsRobot",
      "me-tab-drawer": "SettingsRobot",
      "multi-select-bar": "MultiselectBarRobot",
      "link-device-phone-number-code-view":
        "LoggedOutPhoneNumberCodeScreenRobot",
      "link-device-phone-number-entry-screen":
        "LoggedOutPhoneNumberEntryScreenRobot",
      qrcode: "LoggedOutQrScreenRobot",
      "chat-info-drawer": "ChannelInfoRobot",
      "contact-info-header": "ContactInfoRobot",
      "chat-dm-settings-drawer": "DisappearingMessagesRobot",
      "group-info-header": "GroupInfoRobot",
      "group-settings-drawer": "GroupSettingsRobot",
      "media-gallery-drawer": "MediaDrawerRobot",
      "group-invite-link-drawer": "WAWebGroupInviteLinkDrawerRobot",
      "chat-modal": "ChatModalRobot",
      "block-business-popup": "BlockBusinessModalRobot",
      "confirm-popup": "ConfirmationModalRobot",
      "contacts-modal": "ContactsModalRobot",
      "settings-popup": "GroupSettingsModalRobot",
      "mute-popup": "MuteModalRobot",
      "passcode-removal-modal": "PasscodeRemovalModalRobot",
      "passcode-setup-modal": "PasscodeSetupModalRobot",
      "pin-message-modal": "PinMessageModalRobot",
      "checkmark-large": "ProfilePicEditModalRobot",
      "popup-contents": "ProfilePicSetOrRemoveModalRobot",
      "svg-components-modal": "SVGComponentsModalRobot",
      "status-main-panel": "StatusMainModalRobot",
      "status-player-uie": "StatusPlayerModalRobot",
      "highlight-e2e-message-modal": "UnifyE2EEBottomSheetModalRobot",
      "attach-menu-popup": "AttachMenuPopupRobot",
      "toast-body": "ToastRobot",
    };
    i.E2E_TEST_ROBOTS = e;
  },
  66,
);
