__d(
  "WDSButtonColorCommonConfig.stylex",
  [],
  function (t, n, r, o, a, i, l) {
    var e = {
        pressable: {
          backgroundColor: "xfn3atn",
          color: "x1pse0pq",
          ":hover::after_backgroundColor": "x1yxkqql",
          $$css: !0,
        },
        pressableDisabled: {
          backgroundColor: "x4wrhlh",
          color: "x18cpw0e",
          $$css: !0,
        },
        pressableOverlay: { $$css: !0 },
        pressableHovered: { $$css: !0 },
        pressablePressed: { $$css: !0 },
      },
      s = {
        pressable: {
          backgroundColor: "xk0ssx3",
          color: "x1pse0pq",
          ":hover::after_backgroundColor": "x1yxkqql",
          $$css: !0,
        },
        pressableDisabled: {
          backgroundColor: "x4wrhlh",
          color: "x18cpw0e",
          $$css: !0,
        },
        pressableOverlay: { $$css: !0 },
        pressableHovered: { $$css: !0 },
        pressablePressed: { $$css: !0 },
      },
      u = {
        pressable: {
          backgroundColor: "x1abdmlv",
          color: "xk4n5i7",
          ":hover::after_backgroundColor": "x1wjp2x",
          $$css: !0,
        },
        pressableDisabled: {
          opacity: "x1lxidc1",
          filter: "x4dje6k",
          $$css: !0,
        },
        pressableHovered: { $$css: !0 },
        pressablePressed: { $$css: !0 },
      },
      c = {
        pressable: {
          backgroundColor: "xrkjzwr",
          color: "xqnyt8g",
          ":hover::after_backgroundColor": "x4ju2vy",
          $$css: !0,
        },
        pressableDisabled: {
          opacity: "x1lxidc1",
          filter: "x4dje6k",
          $$css: !0,
        },
        pressableHovered: { $$css: !0 },
        pressablePressed: { $$css: !0 },
      },
      d = {
        pressable: {
          backgroundColor: "xjbqb8w",
          color: "xo1mcw5",
          "::after_transform": "xy0j11r",
          "::after_transition": "xg268so",
          ":hover::after_transform": "x1b4bgnk",
          ":hover::after_backgroundColor": "x1wjp2x",
          $$css: !0,
        },
        pressableDisabled: {
          opacity: "x1lxidc1",
          filter: "x4dje6k",
          $$css: !0,
        },
        pressableOverlay: { $$css: !0 },
        pressableHovered: { $$css: !0 },
        pressablePressed: { $$css: !0 },
      },
      m = {
        pressable: {
          backgroundColor: "xjbqb8w",
          color: "xuwfzo9",
          "::after_transform": "xy0j11r",
          "::after_transition": "xg268so",
          ":hover::after_transform": "x1b4bgnk",
          ":hover::after_backgroundColor": "x1wb366y",
          $$css: !0,
        },
        pressableDisabled: {
          opacity: "x1lxidc1",
          filter: "x4dje6k",
          $$css: !0,
        },
        pressableOverlay: { $$css: !0 },
        pressableHovered: { $$css: !0 },
        pressablePressed: { $$css: !0 },
      },
      p = {
        pressable: {
          backgroundColor: "xjbqb8w",
          color: "xqnyt8g",
          "::after_transform": "xy0j11r",
          "::after_transition": "xg268so",
          ":hover::after_transform": "x1b4bgnk",
          ":hover::after_backgroundColor": "x4ju2vy",
          $$css: !0,
        },
        pressableDisabled: {
          opacity: "x1lxidc1",
          filter: "x4dje6k",
          $$css: !0,
        },
        pressableOverlay: { $$css: !0 },
        pressableHovered: { $$css: !0 },
        pressablePressed: { $$css: !0 },
      },
      _ = {
        pressable: {
          backgroundColor: "xjbqb8w",
          color: "x17t9dm2",
          filter: "x15ri80r",
          "::after_transform": "xy0j11r",
          "::after_transition": "xg268so",
          ":hover::after_transform": "x1b4bgnk",
          ":hover::after_backgroundColor": "xw1yv47",
          $$css: !0,
        },
        pressableDisabled: { opacity: "x1lxidc1", $$css: !0 },
        pressableOverlay: { $$css: !0 },
        pressableHovered: { $$css: !0 },
        pressablePressed: { $$css: !0 },
      };
    ((l.WDSButtonFilledDefaultColorStyles = e),
      (l.WDSButtonFilledDestructiveColorStyles = s),
      (l.WDSButtonTonalDefaultColorStyles = u),
      (l.WDSButtonTonalDestructiveColorStyles = c),
      (l.WDSButtonBorderlessDefaultColorStyles = d),
      (l.WDSButtonBorderlessDefaultIconOnlyColorStyles = m),
      (l.WDSButtonBorderlessDestructiveColorStyles = p),
      (l.WDSButtonBorderlessMediaColorStyles = _));
  },
  98,
);
