__d(
  "WDSFlex.stylex",
  [],
  function (t, n, r, o, a, i, l) {
    "use strict";
    var e = {
      flex: { display: "x78zum5", $$css: !0 },
      flexRow: { display: "x78zum5", flexDirection: "x1q0g3np", $$css: !0 },
      flexColumn: { display: "x78zum5", flexDirection: "xdt5ytf", $$css: !0 },
      flexRowReverse: {
        display: "x78zum5",
        flexDirection: "x15zctf7",
        $$css: !0,
      },
      flexColumnReverse: {
        display: "x78zum5",
        flexDirection: "x3ieub6",
        $$css: !0,
      },
      justifyStart: { justifyContent: "x1nhvcw1", $$css: !0 },
      justifyEnd: { justifyContent: "x13a6bvl", $$css: !0 },
      justifyCenter: { justifyContent: "xl56j7k", $$css: !0 },
      justifyBetween: { justifyContent: "x1qughib", $$css: !0 },
      justifyAround: { justifyContent: "x1l1ennw", $$css: !0 },
      justifyEvenly: { justifyContent: "xaw8158", $$css: !0 },
      alignStart: { alignItems: "x1cy8zhl", $$css: !0 },
      alignEnd: { alignItems: "xuk3077", $$css: !0 },
      alignCenter: { alignItems: "x6s0dn4", $$css: !0 },
      alignStretch: { alignItems: "x1qjc9v5", $$css: !0 },
      alignBaseline: { alignItems: "x1pha0wt", $$css: !0 },
      selfStart: { alignSelf: "xqcrz7y", $$css: !0 },
      selfEnd: { alignSelf: "xpvyfi4", $$css: !0 },
      selfCenter: { alignSelf: "xamitd3", $$css: !0 },
      selfStretch: { alignSelf: "xkh2ocl", $$css: !0 },
      selfBaseline: { alignSelf: "xoi2r2e", $$css: !0 },
      flexWrap: { flexWrap: "x1a02dak", $$css: !0 },
      flexNoWrap: { flexWrap: "xozqiw3", $$css: !0 },
      flexWrapReverse: { flexWrap: "x8hhl5t", $$css: !0 },
      flexGrow0: { flexGrow: "x1c4vz4f", $$css: !0 },
      flexGrow1: { flexGrow: "x1iyjqo2", $$css: !0 },
      flexShrink0: { flexShrink: "x2lah0s", $$css: !0 },
      flexShrink1: { flexShrink: "xs83m0k", $$css: !0 },
      gap: { rowGap: "x1qvou4u", columnGap: "x1s70e7g", $$css: !0 },
      gapQuarter: { rowGap: "x1b73lln", columnGap: "x46w9ns", $$css: !0 },
      gapHalf: { rowGap: "x129bwdz", columnGap: "x1trrmfo", $$css: !0 },
      gapSingle: { rowGap: "x1qvou4u", columnGap: "x1s70e7g", $$css: !0 },
      gapSinglePlus: { rowGap: "x8a3fw1", columnGap: "x1aj3ljl", $$css: !0 },
      gapDouble: { rowGap: "x1f0uite", columnGap: "xs2akgl", $$css: !0 },
      gapDoublePlus: { rowGap: "x121sasi", columnGap: "x1mn2tih", $$css: !0 },
      gapTriple: { rowGap: "x1j3ira4", columnGap: "xrdqr27", $$css: !0 },
      gapTriplePlus: { rowGap: "xka5s13", columnGap: "xeah0mx", $$css: !0 },
      gapQuad: { rowGap: "x1frt3yj", columnGap: "x13a9art", $$css: !0 },
      gapQuint: { rowGap: "xlxy9ep", columnGap: "xf91ah9", $$css: !0 },
      rowGap: { rowGap: "x1qvou4u", $$css: !0 },
      rowGapQuarter: { rowGap: "x1b73lln", $$css: !0 },
      rowGapHalf: { rowGap: "x129bwdz", $$css: !0 },
      rowGapSingle: { rowGap: "x1qvou4u", $$css: !0 },
      rowGapSinglePlus: { rowGap: "x8a3fw1", $$css: !0 },
      rowGapDouble: { rowGap: "x1f0uite", $$css: !0 },
      rowGapDoublePlus: { rowGap: "x121sasi", $$css: !0 },
      rowGapTriple: { rowGap: "x1j3ira4", $$css: !0 },
      rowGapTriplePlus: { rowGap: "xka5s13", $$css: !0 },
      rowGapQuad: { rowGap: "x1frt3yj", $$css: !0 },
      rowGapQuint: { rowGap: "xlxy9ep", $$css: !0 },
      columnGap: { columnGap: "x1s70e7g", $$css: !0 },
      columnGapQuarter: { columnGap: "x46w9ns", $$css: !0 },
      columnGapHalf: { columnGap: "x1trrmfo", $$css: !0 },
      columnGapSingle: { columnGap: "x1s70e7g", $$css: !0 },
      columnGapSinglePlus: { columnGap: "x1aj3ljl", $$css: !0 },
      columnGapDouble: { columnGap: "xs2akgl", $$css: !0 },
      columnGapDoublePlus: { columnGap: "x1mn2tih", $$css: !0 },
      columnGapTriple: { columnGap: "xrdqr27", $$css: !0 },
      columnGapTriplePlus: { columnGap: "xeah0mx", $$css: !0 },
      columnGapQuad: { columnGap: "x13a9art", $$css: !0 },
      columnGapQuint: { columnGap: "xf91ah9", $$css: !0 },
      flexAlignCenter: { display: "x78zum5", alignItems: "x6s0dn4", $$css: !0 },
      flexCenter: {
        display: "x78zum5",
        alignItems: "x6s0dn4",
        justifyContent: "xl56j7k",
        $$css: !0,
      },
      flexBetween: {
        display: "x78zum5",
        justifyContent: "x1qughib",
        $$css: !0,
      },
      flexBetweenCenter: {
        display: "x78zum5",
        justifyContent: "x1qughib",
        alignItems: "x6s0dn4",
        $$css: !0,
      },
      flexColumnCenter: {
        display: "x78zum5",
        flexDirection: "xdt5ytf",
        alignItems: "x6s0dn4",
        $$css: !0,
      },
      flexColumnStart: {
        display: "x78zum5",
        flexDirection: "xdt5ytf",
        alignItems: "x1cy8zhl",
        $$css: !0,
      },
      flexColumnEnd: {
        display: "x78zum5",
        flexDirection: "xdt5ytf",
        alignItems: "xuk3077",
        $$css: !0,
      },
      flexRowCenter: {
        display: "x78zum5",
        flexDirection: "x1q0g3np",
        alignItems: "x6s0dn4",
        $$css: !0,
      },
    };
    l.wdsFlex = e;
  },
  98,
);
