__d(
  "WDSFontTokenStyles",
  [],
  function (t, n, r, o, a, i, l) {
    "use strict";
    var e = {
        Body1: {
          fontSize: "x1jchvi3",
          fontFamily: "xjb2p0i",
          fontWeight: "xo1l8bm",
          lineHeight: "x17mssa0",
          fontOpticalSizing: "x1ic7a3i",
          $$css: !0,
        },
        Body1Emphasized: {
          fontSize: "x1jchvi3",
          fontFamily: "xjb2p0i",
          fontWeight: "xfjzk2p",
          lineHeight: "x17mssa0",
          fontOpticalSizing: "x1ic7a3i",
          $$css: !0,
        },
        Body2: {
          fontSize: "x1f6kntn",
          fontFamily: "xjb2p0i",
          lineHeight: "x8r4c90",
          fontWeight: "xo1l8bm",
          fontOpticalSizing: "x1ic7a3i",
          letterSpacing: "x12xpedu",
          $$css: !0,
        },
        Body2Emphasized: {
          fontSize: "x1f6kntn",
          fontFamily: "xjb2p0i",
          fontWeight: "xfjzk2p",
          lineHeight: "x8r4c90",
          fontOpticalSizing: "x1ic7a3i",
          letterSpacing: "x12xpedu",
          $$css: !0,
        },
        Body3: {
          fontSize: "x1pg5gke",
          fontFamily: "xjb2p0i",
          fontWeight: "xo1l8bm",
          lineHeight: "xl2ypbo",
          fontOpticalSizing: "x1ic7a3i",
          $$css: !0,
        },
        Body3Emphasized: {
          fontSize: "x1pg5gke",
          fontFamily: "xjb2p0i",
          fontWeight: "xfjzk2p",
          lineHeight: "xl2ypbo",
          fontOpticalSizing: "x1ic7a3i",
          $$css: !0,
        },
        Headline1: {
          fontSize: "xngnso2",
          fontFamily: "xjb2p0i",
          fontWeight: "xo1l8bm",
          lineHeight: "xhacrq1",
          fontOpticalSizing: "x1ic7a3i",
          $$css: !0,
        },
        Headline2: {
          fontSize: "x1aueamr",
          fontFamily: "xjb2p0i",
          fontWeight: "xo1l8bm",
          lineHeight: "xladpa3",
          fontOpticalSizing: "x1ic7a3i",
          $$css: !0,
        },
        LargeTitle1: {
          fontSize: "x579bpy",
          fontFamily: "xjb2p0i",
          fontWeight: "xo1l8bm",
          lineHeight: "x1akz92t",
          fontOpticalSizing: "x1ic7a3i",
          $$css: !0,
        },
        LargeTitle2: {
          fontSize: "x1q74xe4",
          fontFamily: "xjb2p0i",
          fontWeight: "xo1l8bm",
          lineHeight: "x16n75kc",
          fontOpticalSizing: "x1ic7a3i",
          $$css: !0,
        },
      },
      s = {
        Body1: {
          fontSize: "x1jchvi3",
          fontFamily: "xjb2p0i",
          fontWeight: "x1iz45ln",
          lineHeight: "x17mssa0",
          fontOpticalSizing: "x1ic7a3i",
          $$css: !0,
        },
        Body1Emphasized: {
          fontSize: "x1jchvi3",
          fontFamily: "xjb2p0i",
          fontWeight: "xmvyi9x",
          lineHeight: "x17mssa0",
          fontOpticalSizing: "x1ic7a3i",
          $$css: !0,
        },
        Body2: {
          fontSize: "x1f6kntn",
          fontFamily: "xjb2p0i",
          lineHeight: "x8r4c90",
          fontWeight: "x1iz45ln",
          fontOpticalSizing: "x1ic7a3i",
          letterSpacing: "x12xpedu",
          $$css: !0,
        },
        Body2Emphasized: {
          fontSize: "x1f6kntn",
          fontFamily: "xjb2p0i",
          fontWeight: "xmvyi9x",
          lineHeight: "x8r4c90",
          fontOpticalSizing: "x1ic7a3i",
          letterSpacing: "x12xpedu",
          $$css: !0,
        },
        Body3: {
          fontSize: "x1pg5gke",
          fontFamily: "xjb2p0i",
          fontWeight: "x1iz45ln",
          lineHeight: "xl2ypbo",
          fontOpticalSizing: "x1ic7a3i",
          $$css: !0,
        },
        Body3Emphasized: {
          fontSize: "x1pg5gke",
          fontFamily: "xjb2p0i",
          fontWeight: "xmvyi9x",
          lineHeight: "xl2ypbo",
          fontOpticalSizing: "x1ic7a3i",
          $$css: !0,
        },
        Headline1: {
          fontSize: "xngnso2",
          fontFamily: "xjb2p0i",
          fontWeight: "x1iz45ln",
          lineHeight: "xhacrq1",
          fontOpticalSizing: "x1ic7a3i",
          $$css: !0,
        },
        Headline2: {
          fontSize: "x1aueamr",
          fontFamily: "xjb2p0i",
          fontWeight: "x1iz45ln",
          lineHeight: "xladpa3",
          fontOpticalSizing: "x1ic7a3i",
          $$css: !0,
        },
        LargeTitle1: {
          fontSize: "x579bpy",
          fontFamily: "xjb2p0i",
          fontWeight: "x1iz45ln",
          lineHeight: "x1akz92t",
          fontOpticalSizing: "x1ic7a3i",
          $$css: !0,
        },
        LargeTitle2: {
          fontSize: "x1q74xe4",
          fontFamily: "xjb2p0i",
          fontWeight: "x1iz45ln",
          lineHeight: "x16n75kc",
          fontOpticalSizing: "x1ic7a3i",
          $$css: !0,
        },
      },
      u = "--wds-native-font-size-scale",
      c = "var(" + u + ", 1)",
      d = {
        LargeTitle1: 34,
        LargeTitle2: 28,
        Headline1: 22,
        Headline2: 20,
        Body1: 17,
        Body2: 15,
        Body3: 13,
      },
      m = {
        LargeTitle1: 60,
        LargeTitle2: 58,
        Headline1: 56,
        Headline2: 55,
        Body1: 53,
        Body2: 49,
        Body3: 44,
      },
      p = {
        LargeTitle1: 31,
        LargeTitle2: 25,
        Headline1: 19,
        Headline2: 17,
        Body1: 14,
        Body2: 12,
        Body3: 12,
      },
      _ = {
        LargeTitle1: -0.62,
        LargeTitle2: -0.5,
        Headline1: -0.25,
        Headline2: -0.15,
        Body1: 0,
        Body2: 0.05,
        Body3: 0.1,
      },
      f = function (t) {
        return "(" + c + " + (" + c + " - 1) * " + _[t] + ")";
      },
      g = function (t) {
        return "calc(" + d[t] + "px * " + f(t) + ")";
      },
      h = function (t) {
        return "min(max(" + g(t) + ", " + p[t] + "px), " + m[t] + "px)";
      },
      y = {
        Body1: {
          fontSize: "x1gzfv8f",
          fontFamily: "xlsuly5",
          fontWeight: "xo1l8bm",
          lineHeight: "x1vnv2wu",
          letterSpacing: "x12oo3zp",
          fontOpticalSizing: "x1ic7a3i",
          $$css: !0,
        },
        Body1Emphasized: {
          fontSize: "x1gzfv8f",
          fontFamily: "xlsuly5",
          fontWeight: "x1s688f",
          lineHeight: "x1vnv2wu",
          letterSpacing: "x12oo3zp",
          fontOpticalSizing: "x1ic7a3i",
          $$css: !0,
        },
        Body2: {
          fontSize: "x69964b",
          fontFamily: "xlsuly5",
          fontWeight: "xo1l8bm",
          lineHeight: "xa1q56p",
          letterSpacing: "x12oo3zp",
          fontOpticalSizing: "x1ic7a3i",
          $$css: !0,
        },
        Body2Emphasized: {
          fontSize: "x69964b",
          fontFamily: "xlsuly5",
          fontWeight: "x1s688f",
          lineHeight: "xa1q56p",
          letterSpacing: "x12oo3zp",
          fontOpticalSizing: "x1ic7a3i",
          $$css: !0,
        },
        Body3: {
          fontSize: "x91x0xt",
          fontFamily: "xlsuly5",
          fontWeight: "xo1l8bm",
          lineHeight: "xce5v9f",
          letterSpacing: "x12oo3zp",
          fontOpticalSizing: "x1ic7a3i",
          $$css: !0,
        },
        Body3Emphasized: {
          fontSize: "x91x0xt",
          fontFamily: "xlsuly5",
          fontWeight: "x1s688f",
          lineHeight: "xce5v9f",
          letterSpacing: "x12oo3zp",
          fontOpticalSizing: "x1ic7a3i",
          $$css: !0,
        },
        Headline1: {
          fontSize: "x19b1dur",
          fontFamily: "xq79xv7",
          fontWeight: "x1s688f",
          lineHeight: "x167hkom",
          letterSpacing: "x12oo3zp",
          fontOpticalSizing: "x1ic7a3i",
          $$css: !0,
        },
        Headline2: {
          fontSize: "x9z20r0",
          fontFamily: "xq79xv7",
          fontWeight: "x1s688f",
          lineHeight: "xrj9dn6",
          letterSpacing: "x12oo3zp",
          fontOpticalSizing: "x1ic7a3i",
          $$css: !0,
        },
        LargeTitle1: {
          fontSize: "x1okcndb",
          fontFamily: "xq79xv7",
          fontWeight: "x1s688f",
          lineHeight: "x1cj699d",
          letterSpacing: "x12oo3zp",
          fontOpticalSizing: "x1ic7a3i",
          $$css: !0,
        },
        LargeTitle2: {
          fontSize: "x1p0w8lr",
          fontFamily: "xq79xv7",
          fontWeight: "x1s688f",
          lineHeight: "x1kie75d",
          letterSpacing: "x12oo3zp",
          fontOpticalSizing: "x1ic7a3i",
          $$css: !0,
        },
      },
      C = {
        Body1: {
          fontSize: "x1jchvi3",
          fontFamily: "xjb2p0i",
          fontWeight: "xo1l8bm",
          lineHeight: "x17mssa0",
          fontOpticalSizing: "x1ic7a3i",
          $$css: !0,
        },
        Body1Emphasized: {
          fontSize: "x1jchvi3",
          fontFamily: "xjb2p0i",
          fontWeight: "xk50ysn",
          lineHeight: "x17mssa0",
          fontOpticalSizing: "x1ic7a3i",
          $$css: !0,
        },
        Body2: {
          fontSize: "x1f6kntn",
          fontFamily: "xjb2p0i",
          lineHeight: "x8r4c90",
          fontWeight: "xo1l8bm",
          fontOpticalSizing: "x1ic7a3i",
          $$css: !0,
        },
        Body2Emphasized: {
          fontSize: "x1f6kntn",
          fontFamily: "xjb2p0i",
          fontWeight: "xk50ysn",
          lineHeight: "x8r4c90",
          fontOpticalSizing: "x1ic7a3i",
          $$css: !0,
        },
        Body3: {
          fontSize: "x1pg5gke",
          fontFamily: "xjb2p0i",
          fontWeight: "xo1l8bm",
          lineHeight: "xl2ypbo",
          fontOpticalSizing: "x1ic7a3i",
          $$css: !0,
        },
        Body3Emphasized: {
          fontSize: "x1pg5gke",
          fontFamily: "xjb2p0i",
          fontWeight: "xk50ysn",
          lineHeight: "xl2ypbo",
          fontOpticalSizing: "x1ic7a3i",
          $$css: !0,
        },
        Headline1: {
          fontSize: "xngnso2",
          fontFamily: "xjb2p0i",
          fontWeight: "xo1l8bm",
          lineHeight: "xhacrq1",
          fontOpticalSizing: "x1ic7a3i",
          $$css: !0,
        },
        Headline2: {
          fontSize: "x1aueamr",
          fontFamily: "xjb2p0i",
          fontWeight: "xo1l8bm",
          lineHeight: "xladpa3",
          fontOpticalSizing: "x1ic7a3i",
          $$css: !0,
        },
        LargeTitle1: {
          fontSize: "x579bpy",
          fontFamily: "xjb2p0i",
          fontWeight: "xo1l8bm",
          lineHeight: "x1akz92t",
          fontOpticalSizing: "x1ic7a3i",
          $$css: !0,
        },
        LargeTitle2: {
          fontSize: "x1q74xe4",
          fontFamily: "xjb2p0i",
          fontWeight: "xo1l8bm",
          lineHeight: "x16n75kc",
          fontOpticalSizing: "x1ic7a3i",
          $$css: !0,
        },
      };
    ((l.WDSFontTokenStyles = e),
      (l.WDSFontTokenStylesMacRoboto = s),
      (l.FONT_SCALE_VAR_NAME_IOS = u),
      (l.WDSFontTokenStylesiOS = y),
      (l.WDSFontTokenStylesAndroid = C));
  },
  98,
);
