__d(
  "WDSHoverStateStyles",
  [],
  function (t, n, r, o, a, i, l) {
    var e = {
        genericHoverPersistent: {
          "::after_content": "x1s928wv",
          "::after_position": "x1j6awrg",
          "::after_top": "x1m1drc7",
          "::after_insetInlineStart": "x1iygr5g",
          "::after_left": null,
          "::after_right": null,
          "::after_pointerEvents": "x2q1x1w",
          "::after_borderStartStartRadius": "xfijbtm",
          "::after_borderStartEndRadius": "xfenqrj",
          "::after_borderEndEndRadius": "xgy0gl7",
          "::after_borderEndStartRadius": "x19igvu",
          "::after_width": "x4eaejv",
          "::after_height": "x1wsn0xg",
          "::after_backgroundColor": "x1qxhgua",
          $$css: !0,
        },
        genericHover: {
          ":hover::after_content": "xapdjt",
          ":hover::after_position": "xr6f91l",
          ":hover::after_borderStartStartRadius": "x5rv0tg",
          ":hover::after_borderStartEndRadius": "x1akc3lz",
          ":hover::after_borderEndEndRadius": "xikp0eg",
          ":hover::after_borderEndStartRadius": "x1xl5mkn",
          ":hover::after_top": "x1mfml39",
          ":hover::after_insetInlineStart": "x1l5mzlr",
          ":hover::after_left": null,
          ":hover::after_right": null,
          ":hover::after_pointerEvents": "xgmdoj8",
          ":hover::after_width": "x1f1wgk5",
          ":hover::after_height": "x1x3ic1u",
          ":hover::after_backgroundColor": "x1wb366y",
          $$css: !0,
        },
      },
      s = {
        WDSSwitchBase: {
          "::after_content": "x1s928wv",
          "::after_position": "x1j6awrg",
          "::after_top": "x1m1drc7",
          "::after_insetInlineStart": "x1iygr5g",
          "::after_left": null,
          "::after_right": null,
          "::after_pointerEvents": "x2q1x1w",
          "::after_width": "x4eaejv",
          "::after_height": "x1wsn0xg",
          $$css: !0,
        },
        WDSSwitchSelected: { "::after_backgroundColor": "xcsgr6n", $$css: !0 },
        WDSSwitchUnselected: {
          "::after_backgroundColor": "x1ozn173",
          $$css: !0,
        },
        WDSCheckboxBase: {
          "::after_content": "x1s928wv",
          "::after_position": "x1j6awrg",
          "::after_width": "x4eaejv",
          "::after_height": "x1wsn0xg",
          "::after_paddingTop": "xwyrele",
          "::after_paddingInlineEnd": "xhbw6x3",
          "::after_paddingBottom": "xrjbgh8",
          "::after_paddingInlineStart": "xlpzgyf",
          "::after_borderStartStartRadius": "x1c5sw9q",
          "::after_borderStartEndRadius": "x16kruab",
          "::after_borderEndEndRadius": "xcpednu",
          "::after_borderEndStartRadius": "x1s9o768",
          "::after_opacity": "xymmlu0",
          "::after_pointerEvents": "x2q1x1w",
          $$css: !0,
        },
        WDSCheckboxCircle: {
          "::after_borderStartStartRadius": "x77mdso",
          "::after_borderStartEndRadius": "x1fidlvn",
          "::after_borderEndEndRadius": "x1nys2zw",
          "::after_borderEndStartRadius": "x14gt54a",
          $$css: !0,
        },
        WDSCheckboxSelected: {
          "::after_backgroundColor": "xqh5yu9",
          $$css: !0,
        },
        WDSCheckboxUnselected: {
          "::after_backgroundColor": "xq7nbw2",
          $$css: !0,
        },
        WDSCheckboxMediaSelected: {
          "::after_backgroundColor": "xsb7zyb",
          $$css: !0,
        },
        WDSCheckboxMediaUnselected: {
          "::after_backgroundColor": "x6kt8ur",
          $$css: !0,
        },
        WDSButton: {
          "::after_content": "x1s928wv",
          "::after_position": "x1j6awrg",
          "::after_width": "x4eaejv",
          "::after_height": "x1wsn0xg",
          "::after_zIndex": "x1r0yslu",
          "::after_pointerEvents": "x2q1x1w",
          ":hover::after_content": "xapdjt",
          ":hover::after_position": "xr6f91l",
          ":hover::after_borderStartStartRadius": "x5rv0tg",
          ":hover::after_borderStartEndRadius": "x1akc3lz",
          ":hover::after_borderEndEndRadius": "xikp0eg",
          ":hover::after_borderEndStartRadius": "x1xl5mkn",
          ":hover::after_top": "x1mfml39",
          ":hover::after_insetInlineStart": "x1l5mzlr",
          ":hover::after_left": null,
          ":hover::after_right": null,
          ":hover::after_pointerEvents": "xgmdoj8",
          ":hover::after_width": "x1f1wgk5",
          ":hover::after_height": "x1x3ic1u",
          $$css: !0,
        },
      };
    ((l.WDSHoverStateStyles = e), (l.WDSComponentHoverStateStyles = s));
  },
  98,
);
