__d(
  "WDSLargeButtonConfig.stylex",
  [],
  function (t, n, r, o, a, i, l) {
    var e = {
        content: {
          height: "xnnlda6",
          paddingInlineStart: "x1phvje8",
          paddingInlineEnd: "xcldk2z",
          $$css: !0,
        },
        item: { paddingInlineEnd: "x1nzty39", $$css: !0 },
        pressed: { $$css: !0 },
        addOnEnd: { paddingInlineEnd: "xde1mab", $$css: !0 },
        addOnStart: { $$css: !0 },
        horizontalContainer: { justifyContent: "xl56j7k", $$css: !0 },
        children: { flexGrow: "x1c4vz4f", $$css: !0 },
      },
      s = e,
      u = e,
      c = {
        content: {
          height: "xnnlda6",
          paddingInlineStart: "xdx6fka",
          paddingInlineEnd: "xde1mab",
          $$css: !0,
        },
        item: { paddingInlineEnd: "x1nzty39", $$css: !0 },
        pressed: { $$css: !0 },
        addOnEnd: { paddingInlineEnd: "x1nzty39", $$css: !0 },
        addOnStart: { $$css: !0 },
        horizontalContainer: { justifyContent: "xl56j7k", $$css: !0 },
        children: { flexGrow: "x1c4vz4f", $$css: !0 },
      },
      d = {
        content: {
          height: "xnnlda6",
          paddingInlineStart: "xdylf7x",
          paddingInlineEnd: "x5s3kwk",
          $$css: !0,
        },
        item: { $$css: !0 },
        pressed: { $$css: !0 },
        addOnEnd: { $$css: !0 },
        addOnStart: { $$css: !0 },
        horizontalContainer: {
          columnGap: "x1s70e7g",
          justifyContent: "xl56j7k",
          $$css: !0,
        },
        children: { flexGrow: "x1c4vz4f", textAlign: "x2b8uid", $$css: !0 },
      },
      m = d,
      p = d,
      _ = {
        content: {
          height: "xnnlda6",
          paddingInlineEnd: "xvtqlqk",
          paddingInlineStart: "xdx6fka",
          $$css: !0,
        },
        item: { $$css: !0 },
        pressed: { $$css: !0 },
        addOnEnd: { $$css: !0 },
        addOnStart: { $$css: !0 },
        horizontalContainer: {
          columnGap: "x1s70e7g",
          justifyContent: "xl56j7k",
          $$css: !0,
        },
        children: { flexGrow: "x1c4vz4f", textAlign: "x2b8uid", $$css: !0 },
      },
      f = {
        content: { height: "xnnlda6", width: "x15yg21f", $$css: !0 },
        item: { $$css: !0 },
        pressed: { $$css: !0 },
        addOnEnd: { $$css: !0 },
        addOnStart: { $$css: !0 },
        horizontalContainer: { justifyContent: "xl56j7k", $$css: !0 },
        children: { flexGrow: "x1c4vz4f", $$css: !0 },
      },
      g = f,
      h = f,
      y = f,
      C = {
        content: {
          height: "xnnlda6",
          paddingInlineStart: "x1iw51ew",
          paddingInlineEnd: "xde1mab",
          paddingLeft: null,
          paddingRight: null,
          $$css: !0,
        },
        item: { $$css: !0 },
        pressed: { $$css: !0 },
        addOnEnd: { $$css: !0 },
        addOnStart: { $$css: !0 },
        horizontalContainer: { justifyContent: "xl56j7k", $$css: !0 },
        children: { flexGrow: "x1c4vz4f", $$css: !0 },
      },
      b = C,
      v = C,
      S = C;
    ((l.WDSButtonLargeIconAndLabelFilledStyles = e),
      (l.WDSButtonLargeIconAndLabelTonalStyles = s),
      (l.WDSButtonLargeIconAndLabelOutlineStyles = u),
      (l.WDSButtonLargeIconAndLabelBorderlessStyles = c),
      (l.WDSButtonLargeLabelOnlyFilledStyles = d),
      (l.WDSButtonLargeLabelOnlyTonalStyles = m),
      (l.WDSButtonLargeLabelOnlyOutlineStyles = p),
      (l.WDSButtonLargeLabelOnlyBorderlessStyles = _),
      (l.WDSButtonLargeIconOnlyFilledStyles = f),
      (l.WDSButtonLargeIconOnlyTonalStyles = g),
      (l.WDSButtonLargeIconOnlyOutlineStyles = h),
      (l.WDSButtonLargeIconOnlyBorderlessStyles = y),
      (l.WDSButtonLargeIconAndDropdownOnlyFilledStyles = C),
      (l.WDSButtonLargeIconAndDropdownOnlyTonalStyles = b),
      (l.WDSButtonLargeIconAndDropdownOnlyOutlineStyles = v),
      (l.WDSButtonLargeIconAndDropdownOnlyBorderlessStyles = S));
  },
  98,
);
