__d(
  "WDSMediumButtonConfig.stylex",
  [],
  function (t, n, r, o, a, i, l) {
    var e = {
        content: {
          height: "x1vqgdyp",
          paddingInlineStart: "xdx6fka",
          paddingInlineEnd: "xvtqlqk",
          $$css: !0,
        },
        item: { paddingInlineEnd: "x1nzty39", $$css: !0 },
        pressed: { $$css: !0 },
        addOnEnd: { paddingInlineEnd: "x1nzty39", $$css: !0 },
        addOnStart: { $$css: !0 },
        horizontalContainer: { justifyContent: "xl56j7k", $$css: !0 },
        children: { flexGrow: "x1c4vz4f", $$css: !0 },
      },
      s = e,
      u = e,
      c = {
        content: {
          height: "x1vqgdyp",
          paddingInlineStart: "x1iw51ew",
          paddingInlineEnd: "x1nzty39",
          $$css: !0,
        },
        item: { paddingInlineEnd: "x1nzty39", $$css: !0 },
        pressed: { $$css: !0 },
        addOnEnd: { paddingInlineEnd: "x1uc92m", $$css: !0 },
        addOnStart: { $$css: !0 },
        horizontalContainer: { justifyContent: "xl56j7k", $$css: !0 },
        children: { flexGrow: "x1c4vz4f", $$css: !0 },
      },
      d = {
        content: {
          height: "x1vqgdyp",
          paddingInlineEnd: "xyo0t3i",
          paddingInlineStart: "xb0esv5",
          $$css: !0,
        },
        item: { $$css: !0 },
        pressed: { $$css: !0 },
        addOnEnd: { $$css: !0 },
        addOnStart: { $$css: !0 },
        horizontalContainer: {
          columnGap: "x1s70e7g",
          justifyContent: "xl56j7k",
          $$css: !0,
        },
        children: { flexGrow: "x1c4vz4f", textAlign: "x2b8uid", $$css: !0 },
      },
      m = d,
      p = d,
      _ = {
        content: {
          height: "x1vqgdyp",
          paddingInlineEnd: "xvtqlqk",
          paddingInlineStart: "xdx6fka",
          $$css: !0,
        },
        item: { $$css: !0 },
        pressed: { $$css: !0 },
        addOnEnd: { $$css: !0 },
        addOnStart: { $$css: !0 },
        horizontalContainer: {
          columnGap: "x1s70e7g",
          justifyContent: "xl56j7k",
          $$css: !0,
        },
        children: { flexGrow: "x1c4vz4f", textAlign: "x2b8uid", $$css: !0 },
      },
      f = {
        content: { height: "x1vqgdyp", width: "x100vrsf", $$css: !0 },
        item: { $$css: !0 },
        pressed: { $$css: !0 },
        addOnEnd: { $$css: !0 },
        addOnStart: { $$css: !0 },
        horizontalContainer: { justifyContent: "xl56j7k", $$css: !0 },
        children: { flexGrow: "x1c4vz4f", $$css: !0 },
      },
      g = f,
      h = f,
      y = f,
      C = {
        content: {
          height: "x1vqgdyp",
          paddingInlineStart: "x1iw51ew",
          paddingInlineEnd: "xde1mab",
          paddingLeft: null,
          paddingRight: null,
          $$css: !0,
        },
        item: { $$css: !0 },
        pressed: { $$css: !0 },
        addOnEnd: { $$css: !0 },
        addOnStart: { $$css: !0 },
        horizontalContainer: { justifyContent: "xl56j7k", $$css: !0 },
        children: { flexGrow: "x1c4vz4f", $$css: !0 },
      },
      b = C,
      v = C,
      S = C;
    ((l.WDSButtonMediumIconAndLabelFilledStyles = e),
      (l.WDSButtonMediumIconAndLabelTonalStyles = s),
      (l.WDSButtonMediumIconAndLabelOutlineStyles = u),
      (l.WDSButtonMediumIconAndLabelBorderlessStyles = c),
      (l.WDSButtonMediumLabelOnlyFilledStyles = d),
      (l.WDSButtonMediumLabelOnlyTonalStyles = m),
      (l.WDSButtonMediumLabelOnlyOutlineStyles = p),
      (l.WDSButtonMediumLabelOnlyBorderlessStyles = _),
      (l.WDSButtonMediumIconOnlyFilledStyles = f),
      (l.WDSButtonMediumIconOnlyTonalStyles = g),
      (l.WDSButtonMediumIconOnlyOutlineStyles = h),
      (l.WDSButtonMediumIconOnlyBorderlessStyles = y),
      (l.WDSButtonMediumIconAndDropdownOnlyFilledStyles = C),
      (l.WDSButtonMediumIconAndDropdownOnlyTonalStyles = b),
      (l.WDSButtonMediumIconAndDropdownOnlyOutlineStyles = v),
      (l.WDSButtonMediumIconAndDropdownOnlyBorderlessStyles = S));
  },
  98,
);
