__d(
  "WDSPaddings.stylex",
  [],
  function (t, n, r, o, a, i, l) {
    "use strict";
    var e = {
      padding0: {
        paddingTop: "xexx8yu",
        paddingInlineEnd: "xyri2b",
        paddingBottom: "x18d9i69",
        paddingInlineStart: "x1c1uobl",
        $$css: !0,
      },
      padding: {
        paddingTop: "x16ovd2e",
        paddingInlineEnd: "x1nzty39",
        paddingBottom: "x12xbjc7",
        paddingInlineStart: "x12w63v0",
        $$css: !0,
      },
      padding2: {
        paddingTop: "x1gxa6cn",
        paddingInlineEnd: "x1j8ymqv",
        paddingBottom: "xa0aww2",
        paddingInlineStart: "x4tra6z",
        $$css: !0,
      },
      padding4: {
        paddingTop: "x1tiyuxx",
        paddingInlineEnd: "x1uc92m",
        paddingBottom: "x1nbhmlj",
        paddingInlineStart: "x181vq82",
        $$css: !0,
      },
      padding8: {
        paddingTop: "x16ovd2e",
        paddingInlineEnd: "x1nzty39",
        paddingBottom: "x12xbjc7",
        paddingInlineStart: "x12w63v0",
        $$css: !0,
      },
      padding12: {
        paddingTop: "x1xrf6ya",
        paddingInlineEnd: "xde1mab",
        paddingBottom: "xscbp6u",
        paddingInlineStart: "x1iw51ew",
        $$css: !0,
      },
      padding16: {
        paddingTop: "x1p57kb1",
        paddingInlineEnd: "xvtqlqk",
        paddingBottom: "xvpt6g3",
        paddingInlineStart: "xdx6fka",
        $$css: !0,
      },
      padding20: {
        paddingTop: "x1h678fw",
        paddingInlineEnd: "xcldk2z",
        paddingBottom: "xv6tirj",
        paddingInlineStart: "x1phvje8",
        $$css: !0,
      },
      padding24: {
        paddingTop: "xl7twdi",
        paddingInlineEnd: "xyo0t3i",
        paddingBottom: "xvg22vi",
        paddingInlineStart: "xb0esv5",
        $$css: !0,
      },
      padding28: {
        paddingTop: "xv8gdss",
        paddingInlineEnd: "x5s3kwk",
        paddingBottom: "xgb8hzy",
        paddingInlineStart: "xdylf7x",
        $$css: !0,
      },
      padding32: {
        paddingTop: "x1sk1jro",
        paddingInlineEnd: "x1evaxtz",
        paddingBottom: "x1ci70gm",
        paddingInlineStart: "x1m4z3lf",
        $$css: !0,
      },
      padding40: {
        paddingTop: "x14a8spa",
        paddingInlineEnd: "x1t7qo4d",
        paddingBottom: "x1c76a8b",
        paddingInlineStart: "xu7uy1i",
        $$css: !0,
      },
      paddingHor0: {
        paddingLeft: "x1uhho1l",
        paddingRight: "x1xpa7k",
        paddingInlineStart: null,
        paddingInlineEnd: null,
        $$css: !0,
      },
      paddingHor2: {
        paddingLeft: "x14gxybt",
        paddingRight: "x1d35fnq",
        paddingInlineStart: null,
        paddingInlineEnd: null,
        $$css: !0,
      },
      paddingHor4: {
        paddingLeft: "x1ihvjk1",
        paddingRight: "x13zs225",
        paddingInlineStart: null,
        paddingInlineEnd: null,
        $$css: !0,
      },
      paddingHor8: {
        paddingLeft: "x1xkzz90",
        paddingRight: "x5u1mw9",
        paddingInlineStart: null,
        paddingInlineEnd: null,
        $$css: !0,
      },
      paddingHor12: {
        paddingLeft: "xd1ia5g",
        paddingRight: "x93zsuu",
        paddingInlineStart: null,
        paddingInlineEnd: null,
        $$css: !0,
      },
      paddingHor16: {
        paddingLeft: "x1tj70yd",
        paddingRight: "x4rnih5",
        paddingInlineStart: null,
        paddingInlineEnd: null,
        $$css: !0,
      },
      paddingHor20: {
        paddingLeft: "xx33nr6",
        paddingRight: "x2piyy4",
        paddingInlineStart: null,
        paddingInlineEnd: null,
        $$css: !0,
      },
      paddingHor24: {
        paddingLeft: "x1tnhpae",
        paddingRight: "x8177ur",
        paddingInlineStart: null,
        paddingInlineEnd: null,
        $$css: !0,
      },
      paddingHor28: {
        paddingLeft: "x1xbv3wn",
        paddingRight: "xi8vop",
        paddingInlineStart: null,
        paddingInlineEnd: null,
        $$css: !0,
      },
      paddingHor32: {
        paddingLeft: "x16ef6iv",
        paddingRight: "x1d3fu6f",
        paddingInlineStart: null,
        paddingInlineEnd: null,
        $$css: !0,
      },
      paddingHor40: {
        paddingLeft: "x1ckndri",
        paddingRight: "xdjcpxt",
        paddingInlineStart: null,
        paddingInlineEnd: null,
        $$css: !0,
      },
      paddingVer0: {
        paddingTop: "xexx8yu",
        paddingBottom: "x18d9i69",
        $$css: !0,
      },
      paddingVer2: {
        paddingTop: "x1gxa6cn",
        paddingBottom: "xa0aww2",
        $$css: !0,
      },
      paddingVer4: {
        paddingTop: "x1tiyuxx",
        paddingBottom: "x1nbhmlj",
        $$css: !0,
      },
      paddingVer8: {
        paddingTop: "x16ovd2e",
        paddingBottom: "x12xbjc7",
        $$css: !0,
      },
      paddingVer12: {
        paddingTop: "x1xrf6ya",
        paddingBottom: "xscbp6u",
        $$css: !0,
      },
      paddingVer16: {
        paddingTop: "x1p57kb1",
        paddingBottom: "xvpt6g3",
        $$css: !0,
      },
      paddingVer20: {
        paddingTop: "x1h678fw",
        paddingBottom: "xv6tirj",
        $$css: !0,
      },
      paddingVer24: {
        paddingTop: "xl7twdi",
        paddingBottom: "xvg22vi",
        $$css: !0,
      },
      paddingVer28: {
        paddingTop: "xv8gdss",
        paddingBottom: "xgb8hzy",
        $$css: !0,
      },
      paddingVer32: {
        paddingTop: "x1sk1jro",
        paddingBottom: "x1ci70gm",
        $$css: !0,
      },
      paddingVer40: {
        paddingTop: "x14a8spa",
        paddingBottom: "x1c76a8b",
        $$css: !0,
      },
      paddingTop0: { paddingTop: "xexx8yu", $$css: !0 },
      paddingTop2: { paddingTop: "x1gxa6cn", $$css: !0 },
      paddingTop4: { paddingTop: "x1tiyuxx", $$css: !0 },
      paddingTop8: { paddingTop: "x16ovd2e", $$css: !0 },
      paddingTop12: { paddingTop: "x1xrf6ya", $$css: !0 },
      paddingTop16: { paddingTop: "x1p57kb1", $$css: !0 },
      paddingTop20: { paddingTop: "x1h678fw", $$css: !0 },
      paddingTop24: { paddingTop: "xl7twdi", $$css: !0 },
      paddingTop28: { paddingTop: "xv8gdss", $$css: !0 },
      paddingTop32: { paddingTop: "x1sk1jro", $$css: !0 },
      paddingTop40: { paddingTop: "x14a8spa", $$css: !0 },
      paddingRight0: {
        paddingRight: "x1xpa7k",
        paddingInlineStart: null,
        paddingInlineEnd: null,
        $$css: !0,
      },
      paddingRight2: {
        paddingRight: "x1d35fnq",
        paddingInlineStart: null,
        paddingInlineEnd: null,
        $$css: !0,
      },
      paddingRight4: {
        paddingRight: "x13zs225",
        paddingInlineStart: null,
        paddingInlineEnd: null,
        $$css: !0,
      },
      paddingRight8: {
        paddingRight: "x5u1mw9",
        paddingInlineStart: null,
        paddingInlineEnd: null,
        $$css: !0,
      },
      paddingRight12: {
        paddingRight: "x93zsuu",
        paddingInlineStart: null,
        paddingInlineEnd: null,
        $$css: !0,
      },
      paddingRight16: {
        paddingRight: "x4rnih5",
        paddingInlineStart: null,
        paddingInlineEnd: null,
        $$css: !0,
      },
      paddingRight20: {
        paddingRight: "x2piyy4",
        paddingInlineStart: null,
        paddingInlineEnd: null,
        $$css: !0,
      },
      paddingRight24: {
        paddingRight: "x8177ur",
        paddingInlineStart: null,
        paddingInlineEnd: null,
        $$css: !0,
      },
      paddingRight28: {
        paddingRight: "xi8vop",
        paddingInlineStart: null,
        paddingInlineEnd: null,
        $$css: !0,
      },
      paddingRight32: {
        paddingRight: "x1d3fu6f",
        paddingInlineStart: null,
        paddingInlineEnd: null,
        $$css: !0,
      },
      paddingRight40: {
        paddingRight: "xdjcpxt",
        paddingInlineStart: null,
        paddingInlineEnd: null,
        $$css: !0,
      },
      paddingBottom0: { paddingBottom: "x18d9i69", $$css: !0 },
      paddingBottom2: { paddingBottom: "xa0aww2", $$css: !0 },
      paddingBottom4: { paddingBottom: "x1nbhmlj", $$css: !0 },
      paddingBottom8: { paddingBottom: "x12xbjc7", $$css: !0 },
      paddingBottom12: { paddingBottom: "xscbp6u", $$css: !0 },
      paddingBottom16: { paddingBottom: "xvpt6g3", $$css: !0 },
      paddingBottom20: { paddingBottom: "xv6tirj", $$css: !0 },
      paddingBottom24: { paddingBottom: "xvg22vi", $$css: !0 },
      paddingBottom28: { paddingBottom: "xgb8hzy", $$css: !0 },
      paddingBottom32: { paddingBottom: "x1ci70gm", $$css: !0 },
      paddingBottom40: { paddingBottom: "x1c76a8b", $$css: !0 },
      paddingLeft0: {
        paddingLeft: "x1uhho1l",
        paddingInlineStart: null,
        paddingInlineEnd: null,
        $$css: !0,
      },
      paddingLeft2: {
        paddingLeft: "x14gxybt",
        paddingInlineStart: null,
        paddingInlineEnd: null,
        $$css: !0,
      },
      paddingLeft4: {
        paddingLeft: "x1ihvjk1",
        paddingInlineStart: null,
        paddingInlineEnd: null,
        $$css: !0,
      },
      paddingLeft8: {
        paddingLeft: "x1xkzz90",
        paddingInlineStart: null,
        paddingInlineEnd: null,
        $$css: !0,
      },
      paddingLeft12: {
        paddingLeft: "xd1ia5g",
        paddingInlineStart: null,
        paddingInlineEnd: null,
        $$css: !0,
      },
      paddingLeft16: {
        paddingLeft: "x1tj70yd",
        paddingInlineStart: null,
        paddingInlineEnd: null,
        $$css: !0,
      },
      paddingLeft20: {
        paddingLeft: "xx33nr6",
        paddingInlineStart: null,
        paddingInlineEnd: null,
        $$css: !0,
      },
      paddingLeft24: {
        paddingLeft: "x1tnhpae",
        paddingInlineStart: null,
        paddingInlineEnd: null,
        $$css: !0,
      },
      paddingLeft28: {
        paddingLeft: "x1xbv3wn",
        paddingInlineStart: null,
        paddingInlineEnd: null,
        $$css: !0,
      },
      paddingLeft32: {
        paddingLeft: "x16ef6iv",
        paddingInlineStart: null,
        paddingInlineEnd: null,
        $$css: !0,
      },
      paddingLeft40: {
        paddingLeft: "x1ckndri",
        paddingInlineStart: null,
        paddingInlineEnd: null,
        $$css: !0,
      },
    };
    l.wdsPaddings = e;
  },
  98,
);
