__d(
  "WDSSmallButtonConfig.stylex",
  [],
  function (t, n, r, o, a, i, l) {
    var e = {
        content: {
          height: "x10w6t97",
          paddingInlineStart: "x1iw51ew",
          paddingInlineEnd: "x1nzty39",
          $$css: !0,
        },
        item: { paddingInlineEnd: "x1nzty39", $$css: !0 },
        pressed: { $$css: !0 },
        addOnEnd: { paddingInlineEnd: "x1icxu4v", $$css: !0 },
        addOnStart: { $$css: !0 },
        horizontalContainer: { justifyContent: "xl56j7k", $$css: !0 },
        children: { flexGrow: "x1c4vz4f", $$css: !0 },
      },
      s = e,
      u = e,
      c = e,
      d = {
        content: {
          height: "x10w6t97",
          paddingInlineStart: "xdx6fka",
          paddingInlineEnd: "xvtqlqk",
          $$css: !0,
        },
        item: { $$css: !0 },
        pressed: { $$css: !0 },
        addOnEnd: { $$css: !0 },
        addOnStart: { $$css: !0 },
        horizontalContainer: {
          justifyContent: "xl56j7k",
          columnGap: "x1s70e7g",
          $$css: !0,
        },
        children: { flexGrow: "x1c4vz4f", textAlign: "x2b8uid", $$css: !0 },
      },
      m = d,
      p = d,
      _ = {
        content: {
          height: "x10w6t97",
          width: "x1td3qas",
          paddingInlineStart: "xdx6fka",
          paddingInlineEnd: "xvtqlqk",
          $$css: !0,
        },
        item: { $$css: !0 },
        pressed: { $$css: !0 },
        addOnEnd: { $$css: !0 },
        addOnStart: { $$css: !0 },
        horizontalContainer: {
          justifyContent: "xl56j7k",
          columnGap: "x1s70e7g",
          $$css: !0,
        },
        children: { flexGrow: "x1c4vz4f", textAlign: "x2b8uid", $$css: !0 },
      },
      f = {
        content: { height: "x10w6t97", width: "x1td3qas", $$css: !0 },
        item: { $$css: !0 },
        pressed: { $$css: !0 },
        addOnEnd: { $$css: !0 },
        addOnStart: { $$css: !0 },
        horizontalContainer: { justifyContent: "xl56j7k", $$css: !0 },
        children: { flexGrow: "x1c4vz4f", $$css: !0 },
      },
      g = f,
      h = f,
      y = f,
      C = {
        content: {
          height: "x1vqgdyp",
          paddingInlineStart: "x1iw51ew",
          paddingInlineEnd: "xde1mab",
          paddingLeft: null,
          paddingRight: null,
          $$css: !0,
        },
        item: { $$css: !0 },
        pressed: { $$css: !0 },
        addOnEnd: { $$css: !0 },
        addOnStart: { $$css: !0 },
        horizontalContainer: { justifyContent: "xl56j7k", $$css: !0 },
        children: { flexGrow: "x1c4vz4f", $$css: !0 },
      },
      b = C,
      v = C,
      S = C;
    ((l.WDSButtonSmallIconAndLabelFilledStyles = e),
      (l.WDSButtonSmallIconAndLabelTonalStyles = s),
      (l.WDSButtonSmallIconAndLabelOutlineStyles = u),
      (l.WDSButtonSmallIconAndLabelBorderlessStyles = c),
      (l.WDSButtonSmallLabelOnlyFilledStyles = d),
      (l.WDSButtonSmallLabelOnlyTonalStyles = m),
      (l.WDSButtonSmallLabelOnlyOutlineStyles = p),
      (l.WDSButtonSmallLabelOnlyBorderlessStyles = _),
      (l.WDSButtonSmallIconOnlyFilledStyles = f),
      (l.WDSButtonSmallIconOnlyTonalStyles = g),
      (l.WDSButtonSmallIconOnlyOutlineStyles = h),
      (l.WDSButtonSmallIconOnlyBorderlessStyles = y),
      (l.WDSButtonSmallIconAndDropdownOnlyFilledStyles = C),
      (l.WDSButtonSmallIconAndDropdownOnlyTonalStyles = b),
      (l.WDSButtonSmallIconAndDropdownOnlyOutlineStyles = v),
      (l.WDSButtonSmallIconAndDropdownOnlyBorderlessStyles = S));
  },
  98,
);
