__d(
  "WebBloksConstants",
  [],
  function (t, n, r, o, a, i) {
    var e = "bk.components.internal.Merge",
      l = "bk.components.internal.MergeWithBind",
      s = "bk.components.internal.Shadow",
      u = "\u3423",
      c = "#",
      d = "&",
      m = "+",
      p = "bk.components.internal.Action",
      _ = "bk.components.Flexbox",
      f = "flex",
      g = "bk.components.Image",
      h = "bk.components.Collection",
      y = "bk.components.Slider",
      C = "bk.components.screen.Wrapper",
      b = "bk.components.screen.ScreenWrapper",
      v = "_style",
      S = "child_templates",
      R = "$DESCENDANT_HAS_BIND",
      L = "on_bind",
      E = "on_reflow",
      k = 13,
      I = 32,
      T = 37,
      D = 39,
      x = "bkContextKeyControllerAssociatedObject",
      $ = "textInputAssociatedObject",
      P = "tooltipVisibilityAssociatedObject",
      N =
        'system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif';
    ((i.BK_INTERNAL_MERGE = e),
      (i.BK_INTERNAL_MERGE_WITH_BIND = l),
      (i.BK_INTERNAL_SHADOW = s),
      (i.BK_INTERNAL_SHADOW_MINIFIED = u),
      (i.BK_INTERNAL_SHADOW_CHILD = c),
      (i.BK_INTERNAL_SHADOW_INIT_STATE = d),
      (i.BK_INTERNAL_SHADOW_REDUCE = m),
      (i.BK_INTERNAL_ACTION = p),
      (i.BK_FLEXBOX = _),
      (i.BK_FLEX = f),
      (i.BK_IMAGE = g),
      (i.BK_COLLECTION = h),
      (i.BK_SLIDER = y),
      (i.BK_SCREEN_WRAPPER_LEGACY = C),
      (i.BK_SCREEN_WRAPPER = b),
      (i.BK_STYLE_ATTR = v),
      (i.CHILD_TEMPLATES = S),
      (i.DESCENDANT_HAS_BIND = R),
      (i.ON_BIND = L),
      (i.ON_REFLOW = E),
      (i.KEY_RETURN = k),
      (i.KEY_SPACE = I),
      (i.KEY_LEFT = T),
      (i.KEY_RIGHT = D),
      (i.CONTROLLER_ASSOCIATED_OBJECT = x),
      (i.TEXT_INPUT_ASSOCIATED_OBJECT = $),
      (i.TOOLTIP_VISIBILITY_ASSOCIATED_OBJECT = P),
      (i.WEBBLOKS_DEFAULT_FONT_FAMILY = N));
  },
  66,
);
