__d(
  "WebBloksConstants",
  ["WebBloksInternalAttributeKeys", "WebBloksModel"],
  function (t, n, r, o, a, i, l) {
    var e,
      s,
      u = (e = o("WebBloksModel")).defineWebBloksGlobalAttributeKey("\x8D"),
      c = e.defineWebBloksGlobalAttributeKey(" "),
      d = e.defineWebBloksGlobalAttributeKey("\x8F"),
      m = e.defineWebBloksGlobalAttributeKey("\x85"),
      p = e.defineWebBloksGlobalAttributeKey("\xA4"),
      _ = e.defineWebBloksGlobalAttributeKey("!"),
      f = e.defineWebBloksGlobalAttributeKey("\x87"),
      g = e.defineWebBloksGlobalAttributeKey("\x86"),
      h = e.defineWebBloksGlobalAttributeKey("\x84"),
      y = e.defineWebBloksGlobalAttributeKey("\x8B"),
      C = "bk.components.internal.Merge",
      b = "bk.components.internal.MergeWithBind",
      v = "bk.components.internal.Shadow",
      S = e.defineWebBloksAttributeKey("#"),
      R = e.defineWebBloksAttributeKey("&"),
      L = e.defineWebBloksAttributeKey("+"),
      E = "bk.components.internal.Action",
      k = "\u341F",
      I = e.defineWebBloksAttributeKey("#"),
      T = "bk.components.Flexbox",
      D = "flex",
      x = "bk.components.Image",
      $ = "bk.components.Collection",
      P = "bk.components.Slider",
      N = "bk.components.screen.Wrapper",
      M = "bk.components.screen.ScreenWrapper",
      w = "_style",
      A = "child_templates",
      F = e.defineWebBloksInternalAttributeKey("$DESCENDANT_HAS_BIND"),
      O = "on_bind",
      B = "on_reflow",
      W = "$YOGA_NORMALIZED_",
      q = 13,
      U = 32,
      V = 37,
      H = 39,
      G = "bkContextKeyControllerAssociatedObject",
      z = "textInputAssociatedObject",
      j = "tooltipVisibilityAssociatedObject",
      K =
        'system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif';
    ((l.MARGIN_ATTRIBUTE_KEY = (s = o(
      "WebBloksInternalAttributeKeys",
    )).MARGIN_ATTRIBUTE_KEY),
      (l.MARGIN_HORIZONTAL_ATTRIBUTE_KEY = s.MARGIN_HORIZONTAL_ATTRIBUTE_KEY),
      (l.MARGIN_VERTICAL_ATTRIBUTE_KEY = s.MARGIN_VERTICAL_ATTRIBUTE_KEY),
      (l.TRANSFORM_ATTRIBUTE_KEY = s.TRANSFORM_ATTRIBUTE_KEY),
      (l.YOGA_JUSTIFY_CONTENT_ATTRIBUTE_KEY =
        s.YOGA_JUSTIFY_CONTENT_ATTRIBUTE_KEY),
      (l.ALPHA_ATTRIBUTE_KEY = u),
      (l.CHILDREN_ATTRIBUTE_KEY = c),
      (l.CHILD_TEMPLATES_ATTRIBUTE_KEY = d),
      (l.EXTENSIONS_ATTRIBUTE_KEY = m),
      (l.HTML_ID_ATTRIBUTE_KEY = p),
      (l.ID_ATTRIBUTE_KEY = _),
      (l.ON_BIND_ATTRIBUTE_KEY = f),
      (l.ON_REFLOW_ATTRIBUTE_KEY = g),
      (l.STYLE_ATTRIBUTE_KEY = h),
      (l.TRANSFORM_3D_ATTRIBUTE_KEY = y),
      (l.BK_INTERNAL_MERGE = C),
      (l.BK_INTERNAL_MERGE_WITH_BIND = b),
      (l.BK_INTERNAL_SHADOW = v),
      (l.BK_INTERNAL_SHADOW_CHILD = S),
      (l.BK_INTERNAL_SHADOW_INIT_STATE = R),
      (l.BK_INTERNAL_SHADOW_REDUCE = L),
      (l.BK_INTERNAL_ACTION = E),
      (l.BK_INTERNAL_ACTION_WIRE_STYLE_ID = k),
      (l.BK_INTERNAL_ACTION_HANDLER = I),
      (l.BK_FLEXBOX = T),
      (l.BK_FLEX = D),
      (l.BK_IMAGE = x),
      (l.BK_COLLECTION = $),
      (l.BK_SLIDER = P),
      (l.BK_SCREEN_WRAPPER_LEGACY = N),
      (l.BK_SCREEN_WRAPPER = M),
      (l.BK_STYLE_ATTR = w),
      (l.CHILD_TEMPLATES = A),
      (l.DESCENDANT_HAS_BIND = F),
      (l.ON_BIND = O),
      (l.ON_REFLOW = B),
      (l.YOGA_NORMALIZED_ATTRIBUTE_PREFIX = W),
      (l.KEY_RETURN = q),
      (l.KEY_SPACE = U),
      (l.KEY_LEFT = V),
      (l.KEY_RIGHT = H),
      (l.CONTROLLER_ASSOCIATED_OBJECT = G),
      (l.TEXT_INPUT_ASSOCIATED_OBJECT = z),
      (l.TOOLTIP_VISIBILITY_ASSOCIATED_OBJECT = j),
      (l.WEBBLOKS_DEFAULT_FONT_FAMILY = K));
  },
  98,
);
