__d(
  "WebBloksExtensionHandlers",
  [
    "WebBloksAccessibilityExtensionHandler",
    "WebBloksAnchorIDExtensionHandler",
    "WebBloksAnchorTagExtensionHandler",
    "WebBloksAutomationTestExtensionHandler",
    "WebBloksBKSTextInputFormatterHandler",
    "WebBloksCssAnimationExtensionHandler",
    "WebBloksDragExtensionHandler",
    "WebBloksGestureExtensionHandler",
    "WebBloksHoverExtensionHandler",
    "WebBloksOnDataChangeExtensionHandler",
    "WebBloksOnMountExtensionHandler",
    "WebBloksRenderLifecycleExtensionHandler",
    "WebBloksTextInputDatePickerExtensionHandler",
    "WebBloksTextInputMaskExtensionHandler",
    "WebBloksTouchExtensionHandler",
    "WebBloksViewTransformExtensionHandler",
    "WebBloksVisibilityExtensionHandler",
    "WebBloksWebDataAttributesExtensionHandler",
    "WebBloksWebFocusBoundaryExtensionHandler",
    "WebBloksWebNativeAccessibilityExtensionHandler",
  ],
  function (t, n, r, o, a, i, l) {
    var e,
      s = "\u3401",
      u = "\u356E",
      c = "\u4244",
      d = "\u34FE",
      m = "\u35C8",
      p = "\u64E4",
      _ = "\u3DD9",
      f = "\u369D",
      g = "\u57F7",
      h = "\u3FB6",
      y = "\u365A",
      C = "\u3558",
      b = "\u3F27",
      v = "\u3419",
      S = "\u3578",
      R = "\u34E2",
      L = "\u639A",
      E = "\u62F0",
      k = "\u4283",
      I = "\u4033",
      T =
        ((e = {}),
        (e[s] = r("WebBloksAccessibilityExtensionHandler")),
        (e[u] = r("WebBloksAnchorIDExtensionHandler")),
        (e[c] = r("WebBloksAnchorTagExtensionHandler")),
        (e[d] = r("WebBloksAutomationTestExtensionHandler")),
        (e[m] = r("WebBloksBKSTextInputFormatterHandler")),
        (e[p] = r("WebBloksDragExtensionHandler")),
        (e[_] = r("WebBloksGestureExtensionHandler")),
        (e[f] = r("WebBloksTouchExtensionHandler")),
        (e[g] = r("WebBloksHoverExtensionHandler")),
        (e[h] = r("WebBloksOnDataChangeExtensionHandler")),
        (e[y] = r("WebBloksOnMountExtensionHandler")),
        (e[C] = r("WebBloksRenderLifecycleExtensionHandler")),
        (e[b] = r("WebBloksTextInputDatePickerExtensionHandler")),
        (e[v] = r("WebBloksTextInputMaskExtensionHandler")),
        (e[S] = r("WebBloksViewTransformExtensionHandler")),
        (e[R] = r("WebBloksVisibilityExtensionHandler")),
        (e[L] = r("WebBloksCssAnimationExtensionHandler")),
        (e[E] = r("WebBloksWebDataAttributesExtensionHandler")),
        (e[k] = r("WebBloksWebFocusBoundaryExtensionHandler")),
        (e[I] = r("WebBloksWebNativeAccessibilityExtensionHandler")),
        e),
      D = babelHelpers.extends({}, T, {
        "bk.components.AnchorIdExtension": r(
          "WebBloksAnchorIDExtensionHandler",
        ),
        "bk.components.AutomationTestExtension": r(
          "WebBloksAutomationTestExtensionHandler",
        ),
        "bk.components.VisibilityExtension": r(
          "WebBloksVisibilityExtensionHandler",
        ),
        "bk.components.AccessibilityExtension": r(
          "WebBloksAccessibilityExtensionHandler",
        ),
        "bk.components.WebDataAttributesExtension": r(
          "WebBloksWebDataAttributesExtensionHandler",
        ),
        "bk.components.WebNativeAccessibilityExtension": r(
          "WebBloksWebNativeAccessibilityExtensionHandler",
        ),
        "bk.components.HoverExtension": r("WebBloksHoverExtensionHandler"),
        "bk.components.OnMount": r("WebBloksOnMountExtensionHandler"),
        "bk.components.RenderLifecycleExtension": r(
          "WebBloksRenderLifecycleExtensionHandler",
        ),
        "bk.components.ViewTransformsExtension": r(
          "WebBloksViewTransformExtensionHandler",
        ),
        "bk.components.WebCssAnimationExtension": r(
          "WebBloksCssAnimationExtensionHandler",
        ),
        "bk.components.FoaTouchExtension": r("WebBloksTouchExtensionHandler"),
        "bk.components.FoaGestureExtension": r(
          "WebBloksGestureExtensionHandler",
        ),
        "bk.components.webbloks.DragExtension": r(
          "WebBloksDragExtensionHandler",
        ),
        "bk.components.TextInputDatePickerExtension": r(
          "WebBloksTextInputDatePickerExtensionHandler",
        ),
        "bk.components.TextInputMaskExtension": r(
          "WebBloksTextInputMaskExtensionHandler",
        ),
        "bk.extensions.OnDataChange": r("WebBloksOnDataChangeExtensionHandler"),
        "bk.components.AnchorTagExtension": r(
          "WebBloksAnchorTagExtensionHandler",
        ),
        "bk.component.WebFocusBoundaryExtension": r(
          "WebBloksWebFocusBoundaryExtensionHandler",
        ),
        "bk.components.BKSTextInputFormatter": r(
          "WebBloksBKSTextInputFormatterHandler",
        ),
      });
    l.EXTENSION_HANDLERS = D;
  },
  98,
);
