__d(
  "WebBloksConstants",
  ["WebBloksInternalAttributeKeys", "WebBloksModel"],
  function (t, n, r, o, a, i, l) {
    var e,
      s,
      u = (e = o("WebBloksModel")).defineWebBloksGlobalAttributeKey("\x8D"),
      c = e.defineWebBloksGlobalAttributeKey(" "),
      d = e.defineWebBloksGlobalAttributeKey("\x8F"),
      m = e.defineWebBloksGlobalAttributeKey("\x85"),
      p = e.defineWebBloksGlobalAttributeKey("\xA4"),
      _ = e.defineWebBloksGlobalAttributeKey("!"),
      f = e.defineWebBloksGlobalAttributeKey("\x87"),
      g = e.defineWebBloksGlobalAttributeKey("\x86"),
      h = e.defineWebBloksGlobalAttributeKey("\x84"),
      y = e.defineWebBloksGlobalAttributeKey("\x8B"),
      C = "bk.components.internal.Merge",
      b = "bk.components.internal.MergeWithBind",
      v = "bk.components.internal.Shadow",
      S = e.defineWebBloksAttributeKey("#"),
      R = e.defineWebBloksAttributeKey("&"),
      L = e.defineWebBloksAttributeKey("+"),
      E = "bk.components.internal.Action",
      k = "bk.components.Flexbox",
      I = "flex",
      T = "bk.components.Image",
      D = "bk.components.Collection",
      x = "bk.components.Slider",
      $ = "bk.components.screen.Wrapper",
      P = "bk.components.screen.ScreenWrapper",
      N = "_style",
      M = "child_templates",
      w = e.defineWebBloksInternalAttributeKey("$DESCENDANT_HAS_BIND"),
      A = "on_bind",
      F = "on_reflow",
      O = "$YOGA_NORMALIZED_",
      B = 13,
      W = 32,
      q = 37,
      U = 39,
      V = "bkContextKeyControllerAssociatedObject",
      H = "textInputAssociatedObject",
      G = "tooltipVisibilityAssociatedObject",
      z =
        'system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif';
    ((l.MARGIN_ATTRIBUTE_KEY = (s = o(
      "WebBloksInternalAttributeKeys",
    )).MARGIN_ATTRIBUTE_KEY),
      (l.MARGIN_HORIZONTAL_ATTRIBUTE_KEY = s.MARGIN_HORIZONTAL_ATTRIBUTE_KEY),
      (l.MARGIN_VERTICAL_ATTRIBUTE_KEY = s.MARGIN_VERTICAL_ATTRIBUTE_KEY),
      (l.TRANSFORM_ATTRIBUTE_KEY = s.TRANSFORM_ATTRIBUTE_KEY),
      (l.YOGA_JUSTIFY_CONTENT_ATTRIBUTE_KEY =
        s.YOGA_JUSTIFY_CONTENT_ATTRIBUTE_KEY),
      (l.ALPHA_ATTRIBUTE_KEY = u),
      (l.CHILDREN_ATTRIBUTE_KEY = c),
      (l.CHILD_TEMPLATES_ATTRIBUTE_KEY = d),
      (l.EXTENSIONS_ATTRIBUTE_KEY = m),
      (l.HTML_ID_ATTRIBUTE_KEY = p),
      (l.ID_ATTRIBUTE_KEY = _),
      (l.ON_BIND_ATTRIBUTE_KEY = f),
      (l.ON_REFLOW_ATTRIBUTE_KEY = g),
      (l.STYLE_ATTRIBUTE_KEY = h),
      (l.TRANSFORM_3D_ATTRIBUTE_KEY = y),
      (l.BK_INTERNAL_MERGE = C),
      (l.BK_INTERNAL_MERGE_WITH_BIND = b),
      (l.BK_INTERNAL_SHADOW = v),
      (l.BK_INTERNAL_SHADOW_CHILD = S),
      (l.BK_INTERNAL_SHADOW_INIT_STATE = R),
      (l.BK_INTERNAL_SHADOW_REDUCE = L),
      (l.BK_INTERNAL_ACTION = E),
      (l.BK_FLEXBOX = k),
      (l.BK_FLEX = I),
      (l.BK_IMAGE = T),
      (l.BK_COLLECTION = D),
      (l.BK_SLIDER = x),
      (l.BK_SCREEN_WRAPPER_LEGACY = $),
      (l.BK_SCREEN_WRAPPER = P),
      (l.BK_STYLE_ATTR = N),
      (l.CHILD_TEMPLATES = M),
      (l.DESCENDANT_HAS_BIND = w),
      (l.ON_BIND = A),
      (l.ON_REFLOW = F),
      (l.YOGA_NORMALIZED_ATTRIBUTE_PREFIX = O),
      (l.KEY_RETURN = B),
      (l.KEY_SPACE = W),
      (l.KEY_LEFT = q),
      (l.KEY_RIGHT = U),
      (l.CONTROLLER_ASSOCIATED_OBJECT = V),
      (l.TEXT_INPUT_ASSOCIATED_OBJECT = H),
      (l.TOOLTIP_VISIBILITY_ASSOCIATED_OBJECT = G),
      (l.WEBBLOKS_DEFAULT_FONT_FAMILY = z));
  },
  98,
);
