__d(
  "WebBloksCollectionMinificationKeys",
  ["WebBloksModel"],
  function (t, n, r, o, a, i, l) {
    var e,
      s = (e = o("WebBloksModel")).defineWebBloksAttributeKey(")"),
      u = e.defineWebBloksAttributeKey(" "),
      c = e.defineWebBloksAttributeKey("*"),
      d = e.defineWebBloksAttributeKey("K"),
      m = e.defineWebBloksAttributeKey("_"),
      p = e.defineWebBloksAttributeKey(","),
      _ = e.defineWebBloksAttributeKey("^"),
      f = e.defineWebBloksAttributeKey("`"),
      g = e.defineWebBloksAttributeKey("c"),
      h = e.defineWebBloksAttributeKey("1"),
      y = e.defineWebBloksAttributeKey("="),
      C = e.defineWebBloksAttributeKey("3"),
      b = e.defineWebBloksAttributeKey("t"),
      v = e.defineWebBloksAttributeKey("C"),
      S = e.defineWebBloksAttributeKey("6"),
      R = e.defineWebBloksAttributeKey("E"),
      L = e.defineWebBloksAttributeKey("7"),
      E = e.defineWebBloksAttributeKey("8"),
      k = e.defineWebBloksAttributeKey("I"),
      I = e.defineWebBloksAttributeKey("B"),
      T = e.defineWebBloksAttributeKey("#"),
      D = e.defineWebBloksAttributeKey("$"),
      x = e.defineWebBloksAttributeKey("&"),
      $ = e.defineWebBloksAttributeKey("("),
      P = e.defineWebBloksAttributeKey(")"),
      N = "collection",
      M = e.defineWebBloksAttributeKey("#"),
      w = e.defineWebBloksAttributeKey("6"),
      A = e.defineWebBloksAttributeKey(")"),
      F = "bk.style.Base",
      O = e.defineWebBloksAttributeKey(">"),
      B = e.defineWebBloksAttributeKey("C"),
      W = e.defineWebBloksAttributeKey("D"),
      q = e.defineWebBloksAttributeKey(")"),
      U = e.defineWebBloksAttributeKey(":"),
      V = "flex",
      H = e.defineWebBloksAttributeKey("*"),
      G = e.defineWebBloksAttributeKey("D"),
      z = "bk.style.GridCollectionStyle",
      j = e.defineWebBloksAttributeKey("$"),
      K = e.defineWebBloksAttributeKey("#"),
      Q = e.defineWebBloksAttributeKey("#"),
      X = e.defineWebBloksAttributeKey("$");
    ((l.COLLECTION_BACKGROUND_THEMED_COLOR = s),
      (l.COLLECTION_CHILDREN = u),
      (l.COLLECTION_DIRECTION = c),
      (l.COLLECTION_FADING_EDGE_LENGTH = d),
      (l.COLLECTION_IS_SCROLL_ENABLED = m),
      (l.COLLECTION_ITEM_SPACING = p),
      (l.COLLECTION_LAYOUT_CONFIG = _),
      (l.COLLECTION_LAYOUT_CONFIG_TYPE = f),
      (l.COLLECTION_MEASUREMENT_VERSION = g),
      (l.COLLECTION_ON_PAGE_SCROLL = h),
      (l.COLLECTION_ON_SCROLL_CALLBACK = y),
      (l.COLLECTION_ON_SCROLL_SNAP = C),
      (l.COLLECTION_PERSIST_SCROLL_POSITION = b),
      (l.COLLECTION_SHOWS_SCROLL_INDICATOR = v),
      (l.COLLECTION_SNAP = S),
      (l.COLLECTION_SNAP_STYLE = R),
      (l.COLLECTION_SPACING_AFTER = L),
      (l.COLLECTION_SPACING_BEFORE = E),
      (l.COLLECTION_STACK_FROM_END = k),
      (l.COLLECTION_STARTING_INDEX = I),
      (l.GRID_CONFIG_CELL_ASPECT_RATIO = T),
      (l.GRID_CONFIG_CROSS_AXIS_SPAN_SPACING = D),
      (l.GRID_CONFIG_MAIN_AXIS_SPAN_SPACING = x),
      (l.GRID_CONFIG_PADDING = $),
      (l.GRID_CONFIG_SPAN_COUNT = P),
      (l.COLLECTION_STYLE = N),
      (l.COLLECTION_STYLE_HEIGHT = M),
      (l.COLLECTION_STYLE_STICKY_ITEM_CONFIG = w),
      (l.COLLECTION_STYLE_WIDTH = A),
      (l.BASE_STYLE = F),
      (l.BASE_STYLE_COLLECTION_STICKY_ITEM_CONFIG = O),
      (l.BASE_STYLE_GRID_IS_FULL_SPAN = B),
      (l.BASE_STYLE_GRID_SPAN_COUNT = W),
      (l.BASE_STYLE_HEIGHT = q),
      (l.BASE_STYLE_WIDTH = U),
      (l.FLEX_STYLE = V),
      (l.FLEX_STYLE_HEIGHT = H),
      (l.FLEX_STYLE_WIDTH = G),
      (l.GRID_COLLECTION_STYLE = z),
      (l.GRID_COLLECTION_STYLE_IS_FULL_SPAN = j),
      (l.GRID_COLLECTION_STYLE_SPAN_COUNT = K),
      (l.STICKY_ITEM_IS_STICKY = Q),
      (l.STICKY_ITEM_POSITION = X));
  },
  98,
);
