__d(
  "XFBAdTargetGeoLocationsAdObjectSpecResolver.graphql",
  [],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = (function () {
      var e = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "key",
          storageKey: null,
        },
        t = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "name",
          storageKey: null,
        },
        n = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "country",
          storageKey: null,
        },
        r = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "region",
          storageKey: null,
        },
        o = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "region_id",
          storageKey: null,
        },
        a = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "radius",
          storageKey: null,
        },
        i = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "distance_unit",
          storageKey: null,
        },
        l = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "latitude",
          storageKey: null,
        },
        s = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "longitude",
          storageKey: null,
        },
        u = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "primary_city_id",
          storageKey: null,
        },
        c = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "primary_city",
          storageKey: null,
        },
        d = [e],
        m = [n, e, t, r, o],
        p = [
          n,
          e,
          t,
          r,
          o,
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "city_id",
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "city",
            storageKey: null,
          },
        ];
      return {
        argumentDefinitions: [],
        kind: "Fragment",
        metadata: { vultureHash: "vSNf3fXOvQikGAKVjnu8NxtoZj4=" },
        name: "XFBAdTargetGeoLocationsAdObjectSpecResolver",
        selections: [
          {
            alias: null,
            args: null,
            concreteType: "XFBAdTargetCity",
            kind: "LinkedField",
            name: "cities",
            plural: !0,
            selections: [e, t, n, r, o, a, i],
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "country_groups",
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            concreteType: "XFBAdTargetCountry",
            kind: "LinkedField",
            name: "countries",
            plural: !0,
            selections: [
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "country_code",
                storageKey: null,
              },
            ],
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            concreteType: "XFBAdTargetCustomLocation",
            kind: "LinkedField",
            name: "custom_locations",
            plural: !0,
            selections: [
              t,
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "address_string",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "custom_type",
                storageKey: null,
              },
              i,
              l,
              s,
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "min_population",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "max_population",
                storageKey: null,
              },
              a,
              u,
              c,
              o,
              n,
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "country_group",
                storageKey: null,
              },
            ],
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "location_types",
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            concreteType: "XFBAdTargetRegion",
            kind: "LinkedField",
            name: "regions",
            plural: !0,
            selections: [e, n, t],
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            concreteType: "XFBAdTargetZipCode",
            kind: "LinkedField",
            name: "zips",
            plural: !0,
            selections: [
              e,
              t,
              u,
              o,
              n,
              c,
              r,
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "country_name",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "supports_city",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "supports_region",
                storageKey: null,
              },
            ],
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            concreteType: "XFBAdTargetElectoralDistrict",
            kind: "LinkedField",
            name: "electoral_districts",
            plural: !0,
            selections: [
              n,
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "deprecation_code",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "electoral_district",
                storageKey: null,
              },
              e,
              t,
            ],
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            concreteType: "XFBAdTargetPoliticalDistrict",
            kind: "LinkedField",
            name: "political_districts",
            plural: !0,
            selections: [n, e, t],
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            concreteType: "XFBAdTargetPlace",
            kind: "LinkedField",
            name: "places",
            plural: !0,
            selections: [n, i, e, l, s, t, u, c, a, o],
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            concreteType: "XFBAdTargetGeoMarket",
            kind: "LinkedField",
            name: "geo_markets",
            plural: !0,
            selections: [
              n,
              e,
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "market_type",
                storageKey: null,
              },
              t,
            ],
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            concreteType: "XFBAdTargetLocationExpansion",
            kind: "LinkedField",
            name: "location_expansion",
            plural: !1,
            selections: [
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "allowed",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "intent",
                storageKey: null,
              },
            ],
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            concreteType: "XFBAdTargetLocationSet",
            kind: "LinkedField",
            name: "location_set_ids",
            plural: !0,
            selections: d,
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            concreteType: "XFBAdTargetLocationCluster",
            kind: "LinkedField",
            name: "location_cluster_ids",
            plural: !0,
            selections: d,
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            concreteType: "XFBAdTargetGeoEntity",
            kind: "LinkedField",
            name: "large_geo_areas",
            plural: !0,
            selections: m,
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            concreteType: "XFBAdTargetGeoEntity",
            kind: "LinkedField",
            name: "medium_geo_areas",
            plural: !0,
            selections: m,
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            concreteType: "XFBAdTargetGeoEntity",
            kind: "LinkedField",
            name: "small_geo_areas",
            plural: !0,
            selections: m,
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            concreteType: "XFBAdTargetGeoEntity",
            kind: "LinkedField",
            name: "metro_areas",
            plural: !0,
            selections: m,
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            concreteType: "XFBAdTargetGeoEntity",
            kind: "LinkedField",
            name: "subcities",
            plural: !0,
            selections: p,
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            concreteType: "XFBAdTargetGeoEntity",
            kind: "LinkedField",
            name: "neighborhoods",
            plural: !0,
            selections: p,
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            concreteType: "XFBAdTargetGeoEntity",
            kind: "LinkedField",
            name: "subneighborhoods",
            plural: !0,
            selections: p,
            storageKey: null,
          },
        ],
        type: "XFBAdTargetGeoLocations",
        abstractKey: null,
      };
    })();
    a.exports = e;
  },
  null,
);
