__d(
  "XMDSButtonBlurSurfaceStyles",
  [],
  function (t, n, r, o, a, i, l) {
    "use strict";
    var e = {
      blurAdaptive: {
        backdropFilter: "x1qb2erx",
        backgroundColor: "x1wwkc0m xq9whpo",
        borderTopColor: "xf14anj",
        borderInlineEndColor: "x1y7n47c",
        borderBottomColor: "x138nd9d",
        borderInlineStartColor: "xxnax9n",
        borderTopStyle: "x13fuv20",
        borderInlineEndStyle: "x18b5jzi",
        borderBottomStyle: "x1q0q8m5",
        borderInlineStartStyle: "x1t7ytsu",
        borderTopWidth: "x1ubrbcp",
        borderInlineEndWidth: "x1rrhv1r",
        borderBottomWidth: "x1rkxrow",
        borderInlineStartWidth: "x1h18uw0",
        $$css: !0,
      },
      blurDark: {
        backdropFilter: "x1qb2erx",
        backgroundColor: "x1oj0ega x7yvwgt",
        borderTopColor: "xf14anj",
        borderInlineEndColor: "x1y7n47c",
        borderBottomColor: "x138nd9d",
        borderInlineStartColor: "xxnax9n",
        borderTopStyle: "x13fuv20",
        borderInlineEndStyle: "x18b5jzi",
        borderBottomStyle: "x1q0q8m5",
        borderInlineStartStyle: "x1t7ytsu",
        borderTopWidth: "x1ubrbcp",
        borderInlineEndWidth: "x1rrhv1r",
        borderBottomWidth: "x1rkxrow",
        borderInlineStartWidth: "x1h18uw0",
        $$css: !0,
      },
      blurLight: {
        backdropFilter: "x1qb2erx",
        backgroundColor: "x1pwquwb",
        borderTopColor: "xf14anj",
        borderInlineEndColor: "x1y7n47c",
        borderBottomColor: "x138nd9d",
        borderInlineStartColor: "xxnax9n",
        borderTopStyle: "x13fuv20",
        borderInlineEndStyle: "x18b5jzi",
        borderBottomStyle: "x1q0q8m5",
        borderInlineStartStyle: "x1t7ytsu",
        borderTopWidth: "x1ubrbcp",
        borderInlineEndWidth: "x1rrhv1r",
        borderBottomWidth: "x1rkxrow",
        borderInlineStartWidth: "x1h18uw0",
        $$css: !0,
      },
    };
    l.blurSurfaceStyles = e;
  },
  98,
);
