__d(
  "ZenonClientPerfQPLConstants",
  [],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = "zenon_popup_opened",
      l = "zenon_call_join_request",
      s = "zenon_sfu_e2ee_negotiation_complete",
      u = "csm_outgoing_start",
      c = "csm_incoming_connection_started",
      d = "csm_invite_sent",
      m = "csm_invite_ack_recv",
      p = "csm_answer_recv",
      _ = "csm_answer_sdp_recv",
      f = "csm_pranswer_sdp_recv",
      g = "csm_offer_sdp_recv",
      h = "csm_answer_sent",
      y = "csm_negotiation_complete",
      C = "csm_network_ready",
      b = "csm_connection_ready",
      v = "csm_dismiss_sent",
      S = "csm_dismiss_recv",
      R = "media_first_audio_packet",
      L = "media_first_audio_packet_sent",
      E = "media_first_video_packet",
      k = "media_first_video_packet_sent",
      I = "media_peer_connection_factory_created",
      T = "signaling_mw_join_req_sent",
      D = "signaling_mw_join_response_recv";
    ((i.POINT_ZENON_POPUP_OPENED = e),
      (i.POINT_ZENON_CALL_JOIN_REQUEST = l),
      (i.POINT_ZENON_SFU_E2EE_NEGOTIATION_COMPLETE = s),
      (i.POINT_CONNECTION_OUTGOING_START = u),
      (i.POINT_CONNECTION_INCOMING_CONNECTION_STARTED = c),
      (i.POINT_CONNECTION_INVITE_SENT = d),
      (i.POINT_CONNECTION_INVITE_ACK_RECV = m),
      (i.POINT_CONNECTION_ANSWER_RECV = p),
      (i.POINT_CONNECTION_ANSWER_SDP_RECV = _),
      (i.POINT_CONNECTION_PRANSWER_SDP_RECV = f),
      (i.POINT_CONNECTION_OFFER_SDP_RECV = g),
      (i.POINT_CONNECTION_ANSWER_SENT = h),
      (i.POINT_CONNECTION_NEGOTIATION_COMPLETE = y),
      (i.POINT_CONNECTION_NETWORK_READY = C),
      (i.POINT_CONNECTION_READY = b),
      (i.POINT_CONNECTION_DISMISS_SENT = v),
      (i.POINT_CONNECTION_DISMISS_RECV = S),
      (i.POINT_MEDIA_FIRST_AUDIO_PACKET = R),
      (i.POINT_MEDIA_FIRST_AUDIO_PACKET_SENT = L),
      (i.POINT_MEDIA_FIRST_VIDEO_PACKET = E),
      (i.POINT_MEDIA_FIRST_VIDEO_PACKET_SENT = k),
      (i.POINT_MEDIA_PEER_CONNECTION_FACTORY_CREATED = I),
      (i.POINT_SIGNALING_MW_JOIN_REQ_SENT = T),
      (i.POINT_SIGNALING_MW_JOIN_RESPONSE_RECV = D));
  },
  66,
);
