__d(
  "ZenonMWMessageTypes",
  [
    "$InternalEnum",
    "fbwebrtc_ClientStack",
    "multiway_ApprovalStatus",
    "multiway_Capability",
    "multiway_ClientEventType",
    "multiway_ConferenceType",
    "multiway_DeviceStatus",
    "multiway_DismissReason",
    "multiway_E2eeMode",
    "multiway_EndpointServiceType",
    "multiway_HangupReason",
    "multiway_JoinMode",
    "multiway_MediaPath",
    "multiway_MediaPauseStatus",
    "multiway_MessageTag",
    "multiway_MessageType",
    "multiway_ParticipantCallState",
    "multiway_RingType",
    "multiway_RtcResponseStatusCode",
    "multiway_RtcResponseSubCode",
    "multiway_SubscriptionType",
    "multiway_VideoQuality",
  ],
  function (t, n, r, o, a, i, l) {
    "use strict";
    var e = n("$InternalEnum")({
      DEFAULT_AUDIO: 0,
      DEFAULT_VIDEO: 1,
      SCREEN_AUDIO: 2,
      SCREEN_VIDEO: 3,
    });
    ((l.ZenonMWClientStack = r("fbwebrtc_ClientStack")),
      (l.ZenonMWApprovalStatus = r("multiway_ApprovalStatus")),
      (l.ZenonMWCapability = r("multiway_Capability")),
      (l.ZenonMWClientEventType = r("multiway_ClientEventType")),
      (l.ZenonMWConferenceType = r("multiway_ConferenceType")),
      (l.ZenonMWDeviceStatus = r("multiway_DeviceStatus")),
      (l.ZenonMWDismissReason = r("multiway_DismissReason")),
      (l.ZenonMWE2eeMode = r("multiway_E2eeMode")),
      (l.ZenonMWEndpointServiceType = r("multiway_EndpointServiceType")),
      (l.ZenonMWHangupReason = r("multiway_HangupReason")),
      (l.ZenonMWMediaPath = r("multiway_MediaPath")),
      (l.ZenonMWJoinMode = r("multiway_JoinMode")),
      (l.ZenonMWMediaPauseStatus = r("multiway_MediaPauseStatus")),
      (l.ZenonMWMessageTag = r("multiway_MessageTag")),
      (l.ZenonMWSignalingPayloadType = r("multiway_MessageType")),
      (l.ZenonMWParticipantCallState = r("multiway_ParticipantCallState")),
      (l.ZenonMWRingType = r("multiway_RingType")),
      (l.ZenonMWResponseStatusCode = r("multiway_RtcResponseStatusCode")),
      (l.ZenonMWResponseSubCode = r("multiway_RtcResponseSubCode")),
      (l.ZenonMWSubscriptionType = r("multiway_SubscriptionType")),
      (l.ZenonMWVideoQuality = r("multiway_VideoQuality")),
      (l.ZenonMWTrackLabel = e));
  },
  98,
);
